### PR TITLE
`Development`: Restructure e2e test fixtures

### PR DESCRIPTION
**Pull request by TheZoker**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

We need more consistency!

### Description

This PR moves the cypress fixtures into a more user friendly and useful structure. 

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

### CODE REVIEW

**Review by JohannesStoehr — DISMISSED** [review]
Restructuring looks good and tests still run successfully

**Review by Strohgelaender — APPROVED** [review]
new structure looks good

**Review by JohannesStoehr — APPROVED** [review]
Re-approve

**Review by mertyldrr — APPROVED** [review]
The new structure looks fine 👍

**Comment by TheZoker** [comment]
For some reason, github shows that the tests failed on bamboo, but they run successful:
image

**Pull request merged**
