### PR TITLE
Hotfix: Add call to set missing totalScore property

### PR DESCRIPTION
**Pull request by nicolasruscher**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Description

Fix https://github.com/ls1intum/Artemis/issues/3243. Now when reviewing a tutor example submission you can see the total points. 

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. .. 
Testing steps as described in the issue #3243

### CODE REVIEW

**Review by rs-maker — APPROVED** [review]
I tested this on TS2 and it works as intended.

Screenshot from 2021-04-19 15-42-22

**Comment by Varnika-Tyagi** [comment]
Tested on TS2. Works as intended for both imported and newly created modeling exercises.  Good job!
Fixing assessment

**Review by Varnika-Tyagi — APPROVED** [review]
Works on TS2

**Review by willergeorg — APPROVED** [review]
Tested on TS2. Works for me as well.

**Review by NicolasUllmann — APPROVED** [review]
Tested on server 3. Worked fine.

**Review by cremertim — APPROVED** [review]
Tested on test Server 2, works fine for me

**Pull request merged**
