### PR TITLE
`Quiz exercises`: Revert broken drag and drop file upload changes

### PR DESCRIPTION
**Pull request by krusche**
PR #6456 unfortunately includes many different bugs, in particular #6825, but also missing preview functionality and issues when editing the newly created quiz with drag and drop questions.

It is not possible to fix all issues on short notice, the whole file upload handing code needs to be refactored, because files are created and/or replaced multiple times, which is simply not necessary.

Therefore, we revert PR #6456 and the related PR #6718. Due to overlapping changes, we also have to revert PR #6445, otherwise there would be too many merge conflicts.

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Testing in courses
Thoroughly test all imaginable uses of drag and drop questions in course quizzes, in particular creating multiple ones, editing them directly after creation or when navigating into them again afterwards. Previewing the whole quiz, participating in the quiz, showing its solution, and re-evaluating drag and drop questions. **Please be creative!**

- [ ] Testing 1
- [ ] Testing 2
- [ ] Testing 3
- [ ] Testing 4

### Testing in exams
Test the same as above for exam quizzes. **Please be creative!**

- [ ] Testing 1
- [ ] Testing 2
- [ ] Testing 3
- [ ] Testing 4

Note, if you find some edge case issues, or usability issues, please report them here. This PR is a **hotfix** for an urgent issue on production systems and should be deployed as quickly as possible. We want to make sure the general functionality is working again.

### CODE REVIEW

**Review by Strohgelaender — DISMISSED** [review]
DND file uplaod works again on the staging server, also other issues seen before (broken preview, delting questions not possible) are resolved.

**Review by laadvo — APPROVED** [review]
Test on ts1, file upload for DnD quiz questions has been fixed

**Comment by krusche** [comment]
The editing and deletion of drag and drop quiz questions might lead to issues. We are unsure if this worked 100% properly before. If anyone can help us investigating those issues, this would be awesome.

**Comment by Santia-go** [comment]
image

The buttons are not perceptive and there is an "alt" 

image

I mapped 3 options out of 4 and when I saved the image was compressed? If you see the size of the slots says 44x23 but they are compressed.

**Review by SolizerCodes — COMMENTED** [review]
File upload for DnD worked but when replacing a png background with a svg background it looks like this:
Screenshot 2023-07-06 224713

I tried deleting and editing DnD questions for a non-started quiz and that worked for me.

**Comment by pal03377** [comment]
https://github.com/ls1intum/Artemis/assets/9006596/72148c1c-dda2-44d3-8bb8-96e71ab358e7

SVG images are supported by the file upload input field, but not by the editor (was probably broken before already)

**Comment by pal03377** [comment]
https://github.com/ls1intum/Artemis/assets/9006596/708dd423-649a-4552-ade6-48aa0b71a12c

When you do a kind of weird replacement and insert the same file twice as `Picture Drag Item`, one of them is broken after saving (probably broken before).

**Review by pal03377 — APPROVED** [review]
Apart from the two issues above, which are most likely unrelated to this PR, everything seems to be working again (especially the drag and drop quiz exercises). Tested on TS4 & artemis-staging.

**Comment by MaximilianAnzinger** [comment]
Probably an issue that existed previously:
When there are 2 identical text-draggables, there is only one correct order to solve the question.
chrome_teDEUqgCYs

**Review by MaximilianAnzinger — APPROVED** [review]

**Comment by Kroko-fant** [comment]
The "Durchsuchen" or however choose file equivalent button does not adapt to Dark Mode. I'm not sure if this is a new issue or if it got introduced with the last changes.

grafik
grafik

**Comment by krusche** [comment]
> The "Durchsuchen" or however choose file equivalent button does not adapt to Dark Mode. I'm not sure if this is a new issue or if it got introduced with the last changes.
> 
> 
> 
> grafik
> 
> grafik
> 
> grafik
> 
> 

Probably also an existing one as we did not change anything here

**Review by Kroko-fant — APPROVED** [review]
Tested it on Artemis-staging with a Test Exam containing one Quiz Exercise and one separate Quiz exercise! Seems to be working again in the expected way 🚀

**Review by Strohgelaender — DISMISSED** [review]

**Comment by FelixTJDietrich** [comment]
Everything worked fine for me so far during testing with a non-exam exercise but I'm getting the following error when finishing a drag:
`Saving answers failed: The quiz is not active` 

Screenshot 2023-07-07 at 10 45 08

I could not see anything in the console but submit still worked fine. 

Another issue was when I refreshed after submitting I was presented with an empty quiz, but when navigating back and pressing view submissions it looked fine.

**Review by Kroko-fant — DISMISSED** [review]

**Comment by pal03377** [comment]
@krusche requested that I add a small bugfix here, which enables the save button when the background image changes.
After changing the background image, you had to trigger some other change so that the save button would be enabled and you could save. Now this is fixed.

Testing steps:
1. Create a drag and drop quiz ("Create Quiz" -> Enter title -> "Add Drag-And-Drop Question" -> Add Short Question Title -> Upload a background -> Add a Drop Area, Add a Text Drag Item, connect them -> `Save`)
2. Upload another background
3. Now the `Save` button is enabled, without you having to change something else


https://github.com/ls1intum/Artemis/assets/9006596/38d2ce1d-2965-4979-9648-52ba0c119d0e

**Review by Strohgelaender — DISMISSED** [review]

**Comment by FelixTJDietrich** [comment]
I could not reproduce the issue I had with the `Saving answers failed: The quiz is not active` error.

Is there a limit how big the file is allowed to be? I had for example some problems with my 2-4MB files. Also with smaller pictures I had sometimes the the `alt` text displayed and a message that it could not load the images. But it worked again after testing it a third and forth time. Are image cached when I upload the same image again? Do I have to try others? I think there are still some occasional issues when creating the exercise but when it displays correctly in the exercise editor it also works fine during participation.

**Review by Strohgelaender — APPROVED** [review]

**Review by pal03377 — APPROVED** [review]
Tested again on TS4 and on artemis-staging in both exams and non-exams after the most recent changes

**Pull request merged**
