### PR TITLE
`Development`: Add endpoints for build agent information in local continuous integration

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).

### Motivation and Context

For admins, it might be interesting to get information on available build agents in local CI, e.g. number of build jobs currently running on an agent, build job capacity.

### Description

This PR adds some REST endpoints to be later used for displaying build agent information on the client. Each hazelcast member adds itself to the list when the LocalCISharedBuildJobQueueService is initialized. The information is updated everytime a member processes a build job. When calling the endpoint, the list is updated to make sure that ex members who left the cluster will not be represented.

### Steps for Testing

Prerequisites:
- 1 Instructor
- Programming exercise
- Postman, logged in as admin user

1. In Postman, GET /api/admin/build-job-queue/build-agents 
    - On TS6, TS11 and locally, you should see one entry, on TS3 three entries (you might have to wait for a moments, until all nodes have registered)
    - `numberOfCurrentBuildJobs` should be 0 for all build agents
2. Create some submissions for the programming exercise
3. Check the endpoint again. Some build agents should have `numberOfCurrentBuildJobs` > 0

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by reschandreas — DISMISSED** [review]
code LGTM

**Review by mateusmm01 — APPROVED** [review]
Tested locally. Work as expected. Code also LGTM

**Review by reschandreas — APPROVED** [review]
demonstrated in testing session, works as expected. code also lgtm!

**Review by RY997 — APPROVED** [review]
Tested in a testing session, worked as expected

**Review by milljoniaer — APPROVED** [review]
Demonstrated in small testing session, works as expected 🚀

**Pull request merged**
