### PR TITLE
`General`: Show registration number in course group table and in the corresponding CSV export

### PR DESCRIPTION
**Pull request by maximiliansoelch**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

In case an instructor exports user groups (tutors, students, etc.) to CSV, the registration number field in the resulting CSV file is currently empty. 
This makes it difficult to import the users into other systems, such as TUMonline, as a registration number is required.

### Description

Through this change the server now includes the registration number in the corresponding response and it is successfully exported in the CSV.
In addition, the registration number is displayed in a new column in the group table.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students **with a registration number**
- 2 Tutors **with a registration number**
- 2 Editors **with a registration number**

_You should be able to set a registration number for different users in the user management section when logged in as an admin_

Assign all of these users to the same course.

1. Log in to Artemis as Instructor
2. Navigate to Course Administration and then to your Test Course
3. For every group (students, tutors, editors, etc.):
4. Confirm that the registration number is shown in the table 
5. Use the Export to CSV button in the top right
6. Confirm that the registration number is also set in the exported CSV

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

Bildschirmfoto 2022-06-07 um 16 03 52
Bildschirmfoto 2022-06-07 um 16 03 07

### CODE REVIEW

**Review by jbllhff — COMMENTED** [review]
Tested on ts2, with Chrome on MacOS. Unfortunately, the registration number are neither displayed in the table nor in the csv file.

**Review by jbllhff — COMMENTED** [review]
Please see my screenshot for that, sorry.
Bildschirmfoto 2022-06-08 um 08 31 01

**Comment by Dominik-Weinzierl** [comment]
@jbllhff Artemis Test User 6 has no registration number ;) therefore no number is shown.
image

**Review by Dominik-Weinzierl — APPROVED** [review]
Works as expected :+1: 
image

**Comment by maximiliansoelch** [comment]
@jbllhff Thanks for testing. A registration number is only shown in case one is assigned to the user as @Dominik-Weinzierl already pointed out. 
You should be able to set a registration number for different users in the user management section when logged in as an admin. After setting the number there it should also be displayed in the course-group table

**Review by manuelmanso — APPROVED** [review]
Tested on ts3. Works as expected and code looks good 👍

**Review by bassner — APPROVED** [review]
Tested on TS5 --> Works. Code looks good to me 👍

**Pull request merged**
