### PR TITLE
[Feature] Show Lecture Unit Release Date and Version to Instructor

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

@krusche requested that instructors can see the release date and attachment version of lecture units.

### Description

Added badges for the release date and attachment version

### Steps for Testing

Open a lecture unit management page and check that the new badges appear (see screenshot)

### Test Coverage

Simple change, no change

### Screenshots

image

### CODE REVIEW

**Review by cremertim — COMMENTED** [review]
seems to be working on Ts1, however the blue rectangle is not displayed on my screen

image

**Comment by stefanwaldhauser** [comment]
> seems to be working on Ts1, however the blue rectangle is not displayed on my screen

Can you please test again I forgot to push a commit

**Review by KiraNickel — DISMISSED** [review]
Tested on TS3 and the badge is now shown. 
Release Date works fine for Video and Text (however for File and Exercise it says "No release date set!" even when they have a release date in the future).
Showing File versions works fine.

**Review by canyelten — CHANGES_REQUESTED** [review]
Tested on ts1 using test_user1 and test_user10. The blue rectangle is not displayed on my screen.
Ekran görüntüsü 2021-04-18 222904

**Comment by stefanwaldhauser** [comment]
image
Should work now pleas test again

**Review by canyelten — COMMENTED** [review]
Tested on ts1. Worked perfectly.

**Review by canyelten — APPROVED** [review]

**Review by KiraNickel — APPROVED** [review]
Tested on ts3, works perfectly now :)

**Review by cremertim — APPROVED** [review]
Tested on test server 1. Everything works fine for me now

**Comment by Strohgelaender** [comment]
This is not directly related to these changes but I think this PR would be the best place to directly fix it:
The tooltip of the not-released badge states "Release Date:" without mentioning the release date afterward.
grafik

**Review by NicolasUllmann — DISMISSED** [review]
Tested on Server 2. Everything worked as expected.

**Review by willergeorg — DISMISSED** [review]
Tested on TS2 as well. Could not find any unexpected behavior.

**Review by maximilianbergmann — DISMISSED** [review]
Tested on TS3. Everything worked as expected.

**Review by ArtemTsurikov — APPROVED** [review]

**Review by canyelten — APPROVED** [review]
Tested on TS2 once more after the changes. Everything works fine.

**Review by krusche — CHANGES_REQUESTED** [review]
The client tests fail. Please fix them

**Review by ivanchimeno — DISMISSED** [review]
Code looks good

**Pull request merged**
