### PR TITLE
`Programming exercises`: Fix an issue with special characters in task names

### PR DESCRIPTION
**Pull request by pzdr7**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

Since #8461, we apply the Markdown syntax to tasks in order to show diffs within tasks. This requires us to escape most of the special markdown characters that may occur in both the test case names and the task name.

This caused #9035, where underscores in the task name and the test cases fused together to italicize the entire task.

### Description

Escaped more characters from the markdown syntax (we use http://demo.showdownjs.com/) that could cause problems with test case names.

Note that due to a limitation in the showdown-katex extension (no escaping possible e.g. with `$$`), we cannot prevent incorrect behavior of formulas within tasks.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming exercise

1. Log in to Artemis
2. Navigate to Course management > Your course > Exercises > Your exercise > Edit
3. Modify the problem statement and check the preview. Check that:
- If an underscore is present in the task name and in the test name, the task name should **not** be *italicized*.
- If an even number of underscores are present in the task name, there should be **no** *italicized* text.
4. Save the exercise and check that the problem statement also looks good from the student's perspective. 
5. Participate in the exercise and check that the problem statement matches the result the student gets.

### Exam mode test

Prerequisites:
- 1 Exam with a programming exercise
- 1 Student
- 1 Instructor (on a different browser/incognito)

Basically - check that #8461 still works.

1. Log in to Artemis as a student in one browser
2. Log in to Artemis as an instructor in the second browser or incognito tab
3. Navigate to the exam as a student and open the programming exercise
4. As the instructor: Modify the problem statement. In particular, make a change to a task name.
6. As the student: Verify that the changes to the task & the problem statement in general are highlighted correctly.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Tests
- [x] Exam Mode Test 1
- [x] Exam Mode Test 2

### Test Coverage

Only trivial changes
 
#### Before

image

image

#### After

image

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved handling of special characters in task or test case names to prevent markdown interpretation issues.

### CODE REVIEW

**Review by JohannesWt — APPROVED** [review]
Tested on TS3 - works as expected / Code also looks good 👍

**Review by coolchock — APPROVED** [review]
tested on ts3, works as expected. Code LGTM

**Review by Jan-Thurner — APPROVED** [review]
Tested on TS2. Code LGTM.

**Review by JohannesStoehr — APPROVED** [review]
Code

**Pull request merged**
