### PR TITLE
`Exam mode`: Enable submission assessment buttons on student exam detail table

### PR DESCRIPTION
**Pull request by canberkanar**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
Fixes assigned task #17 in https://confluence.ase.in.tum.de/display/ArTEMiS/Testing+Session+11.07.2022

### Description
The student's participation ID was not utilized during link generation for assessment. If this object is not undefined, we utilize this property with this PR.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Exam with a text exercise

1. Log in to Artemis
2. Participate in exam as student
3. Log in as instructor
4. Navigate to Student exams -> View. 
5. Make sure that the buttons "Assess Submission" and  "Open latest Assessment" works

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
Not changed

### Screenshots
image
image

### CODE REVIEW

**Review by jschmautzer — APPROVED** [review]
tested on ts1, works as described

**Review by joaquinmurcia — APPROVED** [review]
Tested on TS3. Works as expected.

**Review by akesfeden — APPROVED** [review]
Code changes look good 👍

**Review by stefanwaldhauser — APPROVED** [review]
Lgtm!

**Pull request merged**
