### PR TITLE
`Communication`: Include imageUrl for reactions

### PR DESCRIPTION
**Pull request by FelberMartin**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

The Android app currently expects the reaction authors to also include a imageUrl (basically to have the same format as the author for a post entity). While they are not currently needed for displaying them in the UI, it messes with the database entries.

Additionally, this change is needed for planned future improvements of the reaction overview in Android, which will show the reaction authors profile picture in the BottomSheet.

### Description
Included the imageUrl to be returned for reactions.

### Steps for Testing

Prerequisites:
- 1 User
- 1 Course with communication enabled

1. Log in to Artemis
2. Navigate to the course communication
3. If there are no posts / reactions yet, create some
4. Open Browser dev tools > Network
5. Refresh
6. Click on entry "messages?postSortCriterions=...." > Response
7. Expand the response and see that the reaction user now includes the imageUrl

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
	- Enhanced user information in JSON representation by including the `imageUrl` property alongside `id` and `name` in the Reaction class.

This update improves the data available for users without altering existing functionalities.

### CODE REVIEW

**Review by PaRangger — APPROVED** [review]
Tested on TS1, the response includes the imageUrl now 👍  Code changes LGTM.

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Works as described

image

**Review by krusche — CHANGES_REQUESTED** [review]
I don't think this is a good change. We want to keep the information minimal here. Can you not change the Android way of handling this?

**Comment by FelberMartin** [comment]
> I don't think this is a good change. We want to keep the information minimal here. Can you not change the Android way of handling this?

I actually did this as a workaround in the Android app for now. 

However, I think including the imageUrl here does not expose any private information (can be accessed anyway for a users post).

Additionally this would then also be required in the future to improve the reaction display in the Android app (and maybe also iOS). I assume we want to implement the mobile reaction overview similar to Slack or Whatsapp, both of which show the profile picture in the BottomSheets next to the reactors name.

 Adding this is on the feature collection for Android (see [here](https://confluence.ase.in.tum.de/spaces/ArTEMiS/pages/222037242/Android+Feature+Collection)).

**Review by krusche — CHANGES_REQUESTED** [review]
I don't think this is a good approach, can you try to fix it in the Android app instead?

**Comment by FelberMartin** [comment]
Yes, [this PR](https://github.com/ls1intum/artemis-android/pull/111) already includes a workaround for this on Android.

I am not sure whether I understand correctly, should we then just re-open this PR once we want to start working on the reaction overview improvements?

**Comment by FelberMartin** [comment]
It was decided that including the imageUrl in the reactions is not required, as it is not needed in the webapp and would be too much information the send for every reaction. 
For the mobile apps, if they want to show the ProfilePictures for reactions, they should rather fetch the users separately and get the imageUrl from there.

**Pull request closed without merging**
