### PR TITLE
[Bugfix] Fix wrong translation in programming assessment and issue with complaints

### LINKED ISSUE #3214: You cannot complain anymore for programming exercises
### Describe the bug

Trying to add a complaint does not work anymore. You can click on the `Complain` button but nothing happens and the complaint mask is not rendered. It does work for more feedback requests though.
No error messages are thrown. 
I think this is related to one of the strict template changes, but I am not sure.

Tested on latest develop with @SimonEntholzer 

#### To Reproduce

1. Assess a programming exercise as tutor
2. Try to complain about the assessment as student

#### Expected behavior

After clicking the Complain button the complain mask should be loaded

#### Screenshots

image

It does work for more feedback request:
image

### PR DESCRIPTION
**Pull request by fde312**
### Checklist
- [x] I tested *all* changes and *all* related features locally.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Fixes #3214 and fixes a small translation issue.

### Description

- Fixed translation
- Removed exam check for complaint 

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create an programming exercise, participate and assess 
3.1 After the last assessment, it should say now programming exercise instead of file upload.
4. Complain about assessment, you should be able to fill out the complain mask.

### Test Coverage

Nothing changed

### Screenshots

image
image

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]

**Review by PatZintel — APPROVED** [review]

**Review by cremertim — APPROVED** [review]

**Review by nicolasruscher — APPROVED** [review]
The code looks good. Works as expected

**Review by NicolasUllmann — COMMENTED** [review]
Tested on Server 1. Everything worked as expected and looked good.

**Review by FrankeLukas — APPROVED** [review]
Changes lgtm.

**Review by willergeorg — COMMENTED** [review]
Worked for me, can't see any deviations.

**Pull request merged**
