### PR TITLE
update apollon version

### PR DESCRIPTION
**Pull request by TobiasPr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

New version of apollon brings a bugfix which should increase performance of modeling exercises in Artemis significantly. Also the Apollon dependencies are updated.

### Steps for Testing

1. Create a Modeling Exercise
2. Use modeling functionality / Model diagrams:
 - Hierarchical order elements (put elements in other elements, e.g. classes in packages)
 - Connect elements with each other
 - Reconnect elements
 - Change element types
 - Change element properties in popups (dbl click on element)
 - Resize elements
 - create diagrams with many elements and see if the editor is still usable
 - Copy-Paste elements
 - delete elements
 - create elements
 - change connection types 
3. Assess modeling submission

### Screenshots
image

### CODE REVIEW

**Review by JannisBittlmayer — APPROVED** [review]
Works as intended, even for very large diagrams.
Only encountered one very weird bug, where the properties pop-up was blurry depending on where the class was placed in the diagram (see screenshots). This only occurred when using Chrome, not on Firefox.
image
image

**Review by FlorianStang — APPROVED** [review]
Tested on TS1 (together with @JannisBittlmayer), everything worked as intended. I also found the same issue with the blurry "popup-interface" when using Chrome.

**Review by airelawaleria — COMMENTED** [review]
Noticed a minor bug. If there is an element connected to the package and you resize an inner element of the package so that the package is extended as well, the association to the package  is displayed at the previous position.  However, if after that I resize the package element, the association automatically re-positions.
image

**Review by marvinchimeka — APPROVED** [review]
Tested on ts2. Worked as intended.

**Review by JohannesWeiss — APPROVED** [review]
Basically works as intended. In addition to the aforementioned issues the performance in a larger model degrades (few seconds wait time for changes to apply) when dragging and dropping SGIs into place.

**Review by EneaGore — APPROVED** [review]
Everything appears to work as intended.

**Comment by TobiasPr** [comment]
> Noticed a minor bug. If there is an element connected to the package and you resize an inner element of the package so that the package is extended as well, the association to the package is displayed at the previous position. However, if after that I resize the package element, the association automatically re-positions.

Good find - I created a separate ticket for that: https://github.com/ls1intum/Apollon/issues/140

**Review by airelawaleria — APPROVED** [review]
Apart from that issue, worked fine. Since it is now separated from this pr, approve.

**Review by jpbernius — APPROVED** [review]

**Review by FuchsDominik — APPROVED** [review]
Was able to re-create bugs mentioned in the comments. Apart from that, i noticed that when creating a connection from a class in a package to the package itself, when repositioning the inner class, the whole package starts to move as well. To re-create: Place two classes in a package, connect one class with one side of the package, when moving the class, the class as well as the package moves with it.

**Review by stefanwaldhauser — APPROVED** [review]
Same bugs as mentioned before but seems much better in performance. Nice change @TobiasPr

**Review by nutatuna — APPROVED** [review]
I can approve this :+1:

**Review by krusche — APPROVED** [review]

**Pull request merged**
