### PR TITLE
`General`: Make markdown editor resizable by default

### LINKED ISSUE #7385: `General`: Textareas are not resizable during course creation
### Describe the bug

If you create or edit a course, it is not possible to resize the textareas, even though this is already possible e.g. during editing/creating exercises.

### To Reproduce

1. Create or Edit a course
2. See that the textareas are not resizable

### Expected behavior

The textareas in the course edit view should also be resizable.

### Screenshots

course:
image_720
exercise:
image_720

### Which version of Artemis are you seeing the problem on?

6.6.0

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
This PR closes #7385. Default behavior should be resizable markdown editors (it can still be disabled with `enableResize=false`).
This PR also removes unnecessary on-top built resizing for programming instruction editor.

### Steps for Testing
Look for markdown editors and verify that they are resizable and look/work correctly, especially for:
- Programming instructions editor (edit/create new programming exercise)
- Code of Conduct/Registration Confirmation Message (edit/create course)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
programming exercise instructions:
image
 course code of conduct: 
image

### CODE REVIEW

**Review by aplr — APPROVED** [review]
Code looks good

**Review by valentin-boehm — APPROVED** [review]
lgtm

**Comment by xHadie** [comment]
_Tested on Legacy TS1_
No Markdown editors appear to be resizeable by default for me. I never see the resize icon in the border of the containers.

**Comment by milljoniaer** [comment]
> _Tested on Legacy TS1_ No Markdown editors appear to be resizeable by default for me. I never see the resize icon in the border of the containers.

The markdown editors don't have the resize icon in the bottom right corner like the native textareas have it.
They have it below the editor in the center. You can see it in the screenshot of my PR description.

**Review by max-bergmann — APPROVED** [review]
Tested in testing session - LGTM

**Comment by julian-christl** [comment]
Tested on TS4, works

**Review by julian-christl — APPROVED** [review]

**Pull request merged**
