### PR TITLE
`Development`: Restrict course detail page access

### PR DESCRIPTION
**Pull request by cremertim**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

If the users want to, they can always access any of the subpages in the Course Overview, regardless of the course configuration.  This is possible by inserting the corresponding url e.g /courses/{courseId}/faq

### Description

I implemented an CourseOverviewGuardService to restrict access of the sites

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to **Artemis**.  
2. Navigate to the **Course Overview** page.  
3. Verify the following for the **Exams** tab:  
   - You can access the **Exams** tab if a visible exam exists (create one if necessary).  
   - You cannot access the **Exams** tab if no visible exam exists.  
4. Verify the following for the **Competencies** tab:  
   - You can access the **Competencies** tab if competencies or prerequisites are present (create some if needed).  
   - You cannot access the **Competencies** tab if none competencies and prerequisites are present.  
5. Verify the following for the **Tutorial Groups** tab:  
   - You can access the **Tutorial Groups** tab if at least one tutorial group exists (create one if necessary).  
   - You cannot access the **Tutorial Groups** tab if none exist.  
6. Verify the following for the **FAQs** tab:  
   - You can access the **FAQs** tab if it is enabled  in the course settings.  
   - You cannot access the **FAQs** tab if it is disabled  in the course settings.  
7. Verify the following for the **Learning Paths** tab:  
   - You can access the **Learning Paths** tab if they are enabled in the course settings.  
   - You cannot access the **Learning Paths** tab if they are disabled  in the course settings.  
8. Verify the following:  
   - You are redirected to the **Exercises** tab if you cannot access a specific feature.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| course-overview-guard.ts| 98% | ✅              |

## Summary by CodeRabbit

- **New Features**
	- Introduced `CourseOverviewGuard` to manage access to course overview routes.
	- Added methods to handle route activation and visibility checks for associated exams.

- **Bug Fixes**
	- Removed the outdated `CourseDashboardGuard` for improved access control across various routes.

- **Chores**
	- Updated routing configuration to integrate the new guard, enhancing overall route management and consistency in path definitions.
	- Centralized path definitions using an enum for better organization.

### CODE REVIEW

**Review by SimonKaran13 — APPROVED** [review]
I tested the following on TS6

- I tested the Exams tab is accessible when a visible exam exists and inaccessible otherwise.
-  Similarly, the Competencies tab is accessible only when competencies or prerequisites are present.
- The Tutorial Groups tab requires at least one tutorial group to be visible.
-  For the FAQs tab, access depends on whether it is enabled in the course settings.
-  Learning Paths tab is accessible only when enabled, even if there is not content (expected behavior).
- Finally, I verified that users are redirected to the Exercises tab if none of these features are accessible. 

Sometimes right after activating/deactivating a feature it could still be the case that you are not shown/shown the feature or are wrongly redirected, but this is probably due to caching and after reloading the page a couple of times it works as expected.

**Review by HawKhiem — APPROVED** [review]
Tested on TS3.
Every points mentioned were tested and worked as described!

**Review by sachmii — DISMISSED** [review]
Tested on TS6, every step works as expected.

**Review by SimonEntholzer — DISMISSED** [review]
Code lgtm

**Review by PaRangger — DISMISSED** [review]
Code LGTM. 👍 Small note: Even though the old dashboard-guard service also didn't have tests, i think tests for the guard service would be nice to have.

**Review by asliayk — APPROVED** [review]
tested on ts3, works as expected

**Review by eylulnc — APPROVED** [review]
Tested on TS3 works as expected

**Review by PaRangger — APPROVED** [review]
Reapprove

**Review by SimonEntholzer — APPROVED** [review]
re-approve

**Pull request merged**
