### PR TITLE
`Plagiarism checks`: Improve usability of similarity distribution

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.
### Motivation and Context

The idea of this PR is to increase the usability of plagiarism detection in some details. It is based on the feedback by @dveljacic and @ole-ve for #4669.
### Description

The changes of this PR are rather minor. 
First, it changes the workflow of the plagiarism detection a bit. After running the plagiarism detection, not the first comparison case is shown but the similarity distribution. This allows the instructor to get a first overview about the whole situation. The chart also allows filtering for a specific similarity interval and provides information about how many cases are already processed for one interval.
In addition to that, we disable the confirm/deny button now if the case already has been confirmed/denied. This helps the instructor to keep an overview about already processed cases. 
### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 {Modeling, Text, Programming} Exercise with similar submissions from different users

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to the exercise detail page of the prepared exercise
4. Click 'Check plagiarism'
5. Make sure that the chart is shown after the plagiarism check is finished
6. Select a comparison case and confirm it. Make sure that the confirm button is now disabled
7. Select another comparison case and deny it. Make sure that the deny button is now disabled
8. Return to the chart by clicking "Run details"
9. Hover over the bars of the intervals corresponding to the cases you confirmed and denied. Make sure that the distribution of confirmed/denied/open cases is updated appropriately.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Example workflow:

https://user-images.githubusercontent.com/80622272/157880631-769d87dc-7674-49eb-b116-07f69488c777.mp4

### CODE REVIEW

**Review by ole-ve — APPROVED** [review]
Tested on TS1, works as described.
Code changes also look good to me 👍

**Review by filip-gregurevic — APPROVED** [review]
Changes look good to me, nice job 👍🏼

**Review by dveljacic — APPROVED** [review]
I have tested it on TS2 and everything works as expected. ✅ 
Thank you very much for addressing this issue! 
I also linked the issue I created back in the day regarding this, so I guess you can close it once PR is merged, or however the flow works regarding this.

**Review by canberkanar — APPROVED** [review]
Tested locally according to instructions. Nice job! 👍🏻

**Pull request merged**
