### PR TITLE
Improve performance of tutor leaderboard

### PR DESCRIPTION
**Pull request by krusche**
- Views are too slow, we now use Hibernate queries for tutor leaderboards
- This PR drops all the views in the Artemis database, which also solves a couple of other issues.
- There are still performance improvements possible, so we added time log statements to further analyze which queries are slow on production
- We deactivated the assert statements in the server test for now, but did extensive manual testing.
- We'll improve the test in a follow-up PR (now the tutor leaderboard is also easier to test, because we have no views any more).
- These changes will also make it significantly easier to create an exam tutor leaderboard 

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Steps for Testing
1. Open the course and exercise assessment dashboards in an existing course
2. Make sure the tutor leaderboard is displayed quickly and has the correct data

### CODE REVIEW

**Review by derLalla — CHANGES_REQUESTED** [review]
tested on ts1: Everything worked smooth and fine. In the network tab I found that upon opening the Exercise Assessment Dashboard a 404 error happened. But the page was working correctly: 
image

**Comment by krusche** [comment]
> tested on ts1: Everything worked smooth and fine. In the network tab I found that upon opening the Exercise Assessment Dashboard a 404 error happened. But the page was working correctly:
> image
> This might not be relevant for this PR, though.

The 404 is expected when all submissions have been corrected. We should changes this in the future and instead return an empty response or something like this, because 404 should not be returned if something is expected

**Review by derLalla — APPROVED** [review]
as the 404 error is not relevant for this PR, I am approving 👍

**Review by derLalla — APPROVED** [review]
re-approving changelog change

**Pull request merged**
