### PR TITLE
 `General`: Fix text overlapping buttons in course management view

### LINKED ISSUE #7726: UI: Course management average points statistic overlaps buttons
### Describe the bug

After an exercise has finished the course management overview page has a statistic per exercise on the average achieved points.
In the German translation this bar graph extends behind the buttons.

### To Reproduce

1. Set the Artemis UI language to German.
1. Go to the course management.
2. Compare to screenshot below.

### Expected behavior

Looks like in the English translation with the bar next to the buttons.

### Screenshots

grafik

### Which version of Artemis are you seeing the problem on?

6.7.0

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kaancayli**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Description

After an exercise has finished the course management overview page has a statistic per exercise on the average achieved points.
In the German translation this bar graph extends behind the buttons.

This PR resolves #7726 

### Steps for Testing

Set the Artemis UI language to German.
Go to the course management.
Compare to screenshot below.
287808944-5ebaeced-6c43-4ec3-997d-ec97206231a5

### Screenshots

After seeting the language to German average statistics should not overlap with button container in course overview page.
Screenshot 2024-01-15 at 22 43 35

## Summary by CodeRabbit

- **Style**
	- Adjusted layout dimensions for section and statistics cards.
	- Increased element height for better visual presentation.
	- Improved text wrapping for enhanced readability.

### CODE REVIEW

**Review by konrad2002 — APPROVED** [review]
manually tested on legacy ts1, works as expected

**Review by LenaKahle — APPROVED** [review]
Approve, manually tested on legacy ts11.

**Review by xHadie — APPROVED** [review]
_Manually tested on TS11_Legacy_
Works as expected

**Review by marlon-luca-bu — APPROVED** [review]
LGTM

**Pull request merged**
