### PR TITLE
Remove the legacy popup when deleting a submission

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context

The current delete-logic for submissions used an old method which broke URLs and subsequently the breadcrumbs. (The URL changes to `https://artemistest.ase.in.tum.de/course-management/(306/file-upload-exercises/7087/participations/322478/submissions//popup:participation/322478/submission/437569/delete)` for example.)

### Description

We now re-use the `jhiDeleteButton` like everywhere else in the application.

### Steps for Testing

1. Create or find an exercise with participations and submissions
2. Delete a submission
3. Check that the submission is deleted, the breadcrumbs still work and that the URL is valid

### CODE REVIEW

**Review by sinangunduz — APPROVED** [review]
tested on ts2, works as expected

**Review by willergeorg — APPROVED** [review]
Tested on TS2. Worked for me.

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 2. Everything worked as expected.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Worked for me.

**Review by canyelten — APPROVED** [review]
Tested on TS1. Works as expected.

**Review by katjanakosic — APPROVED** [review]
Worked as expected 👍

**Review by krusche — APPROVED** [review]

**Pull request merged**
