### PR TITLE
`Assessment`: Fix the refresh button on the exercise scores page

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.

### Motivation and Context
The refresh button on the exercise scores page does not work, the showed results stays the same.

### Description
The button only changed the `result` field, not `filteredResults`. I move the code setting this field into a reusable method.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Student
- 1 Exercise of any type (best with programming exercises due to automatic results)

1. Instructor: Open the Scores page of the exercise
2. Student: Submit a new version of the exercise (let the test finish for PE)
3. Instructor: Press the refresh button
4. Instructor: Check that the new test result is now displayed. 

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by bassner — APPROVED** [review]
Tested on TS1; the result showed up after reload. Code looks good to me 👍

**Review by babyygemperor — APPROVED** [review]
Tested on ts1, works as described

**Review by JohannesStoehr — APPROVED** [review]
Code looks good to me

**Review by yuling-sun — APPROVED** [review]
Tested on TS1. Works as described.

**Review by SimonPaul02 — APPROVED** [review]
Tested on TS1, works as expected

**Pull request merged**
