### PR TITLE
`Iris`: Disable Iris toggle for exercises if Iris is disabled on the course level

### LINKED ISSUE #7856: `Iris`: Enabling Iris button is not disabled at Exercise Iris Settings when Iris is disabled in the corresponding course
### Describe the bug

It is possible to turn on/off Iris on the exercise page, even if it is disabled on the "Course Iris Settings" page. 

This Issue is only about the "Exercise Iris Settings" page, Iris is not usable if it is turned off in the course settings but turned on in the exercise settings. 

### To Reproduce

1. Go to "Iris Settings" of a course 
2. Click on "Disable"
3. Go to Iris Settings of an exercise
4. The button can still be turned on and off.

### Expected behavior

The "Enable Iris" button should not be able to get turned on/off in the "Exercise Iris Settings" when Iris is also disabled in the corresponding course.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.7.4

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kaancayli**
> [!WARNING]  
> Only Test on TS9 or other test servers where Iris is available

#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

It is possible to turn on/off Iris on the exercise page, even if it is disabled on the "Course Iris Settings" page.

This Issue is only about the "Exercise Iris Settings" page, Iris is not usable if it is turned off in the course settings but turned on in the exercise settings.

This PR resolves #7856.

### Description

If IRIS is not enabled in parent setting (e.g. Course setting). Disable the enable/disable switch in the settings.

### Steps for Testing

Prerequisites:
- 1 Admin
- 1 Programming Exercise

1. Go to "Iris Settings" of a course
2. Click on "Disable"
3. Go to Iris Settings of an exercise
4. Verify that turning on/off Iris on the exercise page is not possible, i.e. the button is disabled.

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Improved the settings interface with a more streamlined checkbox input.

- **Bug Fixes**
	- Fixed an issue where the checkbox input could be incorrectly enabled.

- **Tests**
	- Added tests to ensure chat settings respect parent settings' enabled state.

### CODE REVIEW

**Review by MichaelOwenDyer — APPROVED** [review]
Tested on TS9, works and looks good!

**Review by konrad2002 — APPROVED** [review]
manually tested on ts9, works as described

anyways I think it would be better to indicate that iris is disabled in the exercise iris settings as well. Because if I disable Iris for the entire course, in the exercise iris settings it still looks like Iris is enabled, since the button is only disabled but not turned off

**Review by LenaKahle — DISMISSED** [review]
Approve, manually tested on ts9 using the demo course.

**Review by Gusti2010 — COMMENTED** [review]
I wasn't able to deploy this pr on ts9

**Comment by kaancayli** [comment]
> manually tested on ts9, works as described
> 
> anyways I think it would be better to indicate that iris is disabled in the exercise iris settings as well. Because if I disable Iris for the entire course, in the exercise iris settings it still looks like Iris is enabled, since the button is only disabled but not turned off

Addressed in the latest commit. Now the users are informed, when IRIS is deactivated in parent settings.

**Review by RY997 — APPROVED** [review]
Tested on TS9, worked as expected and code also looks good

**Review by nata-81 — APPROVED** [review]
Tested on ts9 works as expected.

**Review by AntonGeTUM — COMMENTED** [review]
Tested on ts9, works as described with instructor15 (seems to require admin rights unlike stated in the testing instructions?)

**Comment by kaancayli** [comment]
> Logged in as instructor 11. However I can't click on the enable / disable toggle. Why is that? Screenshot 2024-01-24 at 09 49 22

Thanks for pointing this issue out. Instructors are indeed not allowed to change course level settings, only admins can. I have updated PR description.

**Review by bassner — APPROVED** [review]

**Pull request merged**
