### PR TITLE
`General`: Fix programmatic scrolling to the top of the page

### PR DESCRIPTION
**Pull request by pzdr7**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

During the second testing session for 7.0.0, we noticed that the "Back to overview" button of the student exam summary did not work when no result was available.

It seems that the window is not scrollable because there is an element `page-wrapper` that handles the `overflow-y` of the Artemis page content.

### Description

- Added an id to the page wrapper.
- Instead of the window, queried the page wrapper from the document and scrolled on it to get to the top of the page

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam with at least one submission (but no assessment). Ideally, you have a few exercises so the summary page is long enough to be scrollable.

1. Log in to Artemis
2. Navigate to Course Management > Your course > Exams
3. Open the Student exams of your exam and view one.
4. Open the Summary
5. Scroll to the bottom of the page and click the "Back to overview" button
6. You should now be at the top of the page again.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by undernagruzez — DISMISSED** [review]
lgtm and works as expected

**Review by julian-christl — APPROVED** [review]
code lgtm

**Review by rabeatwork — DISMISSED** [review]
maintainer approve

**Review by coolchock — APPROVED** [review]

**Review by muradium — APPROVED** [review]
Presented in testing session, works as expected

**Review by undernagruzez — APPROVED** [review]
reapprove

**Review by julian-christl — APPROVED** [review]
reapprove code

**Pull request merged**
