### PR TITLE
`General`: Fix sorting in course management exercise list

### LINKED ISSUE #4346: Exercise list sorting not working
### Describe the bug

After opening the exercise list from course management, the exercises cannot be sorted. Changing the table sorting option does not change the order in any way.

### To Reproduce

1. Open course management as editor or instructor.
2. Select exercises
3. Try to change the display order via the arrows next to the table headers.

### Expected behavior

Changing the sorting should affect the order of the exercises.

### Screenshots

Screenshots have been limited to one column. The course I checked was PGDP2122
grafik
grafik

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Fixes #4346 
The exercise lists in the course management exercise page can currently not be sorted.
This is a bug that was introduced with #4205 

### Description

The filtered exercise lists were not updated properly after sorting the unfiltered exercises. This PR fixes this.
It was also not possible to sort by the maximum number of points, which was an issue introduced by #2797 and is also fixed in this PR.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with a couple of exercises

1. Log in to Artemis
2. Navigate to Course Management Exercise Page
3. Try to sort the tables of exercises

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

Unchanged

### Screenshots

No UI change

### CODE REVIEW

**Review by Strohgelaender — DISMISSED** [review]
Tested on TS1, sorting works for almost all values again, but not for the points. Clicking on the table header changes the arrow indicator, but the table remains unsorted. This is the case for all exercise types.

**Comment by Hialus** [comment]
> Tested on TS1, sorting works for almost all values again, but not for the points. Clicking on the table header changes the arrow indicator, but the table remains unsorted. This is the case for all exercise types.

Good catch. Looks like this was a bug that has existed for a few months now and was introduced back in #2797
Should be fixed now.

**Review by ole-ve — APPROVED** [review]
Tested on TS1, works as described. Sorting by points is fixed now, too.
One minor thing, that may be out of scope for this PR but IMO not worth an own issue:

Bildschirmfoto 2021-11-26 um 02 04 34

The column header 'Participation Mode' for programming exercises also has an icon for sorting, while it actually cannot be sorted by.

**Review by MerlinMehmed — CHANGES_REQUESTED** [review]
Tested on TS1, sorting works except sorting by "Start Time" in quiz exercises. Here is a screenshot: 
Screenshot from 2021-11-26 09-16-44

**Comment by Hialus** [comment]
> Tested on TS1, sorting works except sorting by "Start Time" in quiz exercises. Here is a screenshot: Screenshot from 2021-11-26 09-16-44

I investigated this issue and I think what causes it.
The Start Time column is being filled with the following expression: `quizExercise.isPlannedToStart ? (quizExercise.releaseDate | artemisDate: 'long':true) : '-'` and the table column is sorted solely by the release date.
So even if the quiz has a release date it will not show if the isPlannedToStart property is set to false. The underlying issue here is that every quiz exercise has a releaseDate set, even if you do not tick the "Start Time" box in the quiz creation. Also if you ever untick this box the releaseDate will remain unchanged.
This is what you are seeing. The quizzes are sorted correctly by their releaseDate property, but the release dates are simply not all shown.
Due to the way that the table sorting is handled I don't really see a quick way to solve this. And it might even be worth to consider changing the underlying problem that I mentioned in another PR.

**Comment by Hialus** [comment]
> Tested on TS1, works as described. Sorting by points is fixed now, too. One minor thing, that may be out of scope for this PR but IMO not worth an own issue:
> 
> Bildschirmfoto 2021-11-26 um 02 04 34
> 
> The column header 'Participation Mode' for programming exercises also has an icon for sorting, while it actually cannot be sorted by.

I removed the sorting icon from the Participation Mode column, as sorting is not active for this column.

**Review by dveljacic — APPROVED** [review]
Tested on TS2. All problems from the above comments seem to be resolved. Everything works as expected. 👍 ✅

**Review by Olimbia23 — APPROVED** [review]
Nice work @Hialus
Code changes look good.
Approve 👍

**Pull request merged**
