### PR TITLE
`Development`: Add e2e tests for setting exam grading and checking exam result grades

### PR DESCRIPTION
**Pull request by muradium**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Setting an exam grading by instructor and checking an exam grade result by student needs to be tested.

### Description
Adds E2E tests in Playwright for setting exam grading and checking exam result grades

### Steps for Testing
- **Code Review**: Ensure that tests pass for valid reasons, functionality is adequately tested and check the code quality.
- **Run the tests (optional)**: Tests are checked by automatic run in CI environment. You can optionally run them locally and check if they pass.

**Steps for running the tests:**
1. Navigate to **src/tests/playwright**
2. Configure Playwright using playwright.env file based on your local setup. Current configuration should work for default Artemis setup.
3. Run `npm install && npm run playwright:setup && npx playwright test e2e/exam/ExamAssessment.spec.ts`
4. Confirm that **"Set exam gradings"** and **"Check student grade"** tests pass.

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **Tests**
	- Introduced a new end-to-end test scenario for exam grading functionality, covering the process from setting grades by an instructor to the student receiving the grade.
- **New Features**
	- Enhanced the exam grading system with new capabilities, including adding grade steps, entering grade names, selecting passing grades, and saving grading keys.
- **Refactor**
	- Improved the `prepareExam` function for better test setup efficiency.

### CODE REVIEW

**Review by matthiaslehnertum — DISMISSED** [review]
Good looks good!

**Review by basak-akan — DISMISSED** [review]
Code looks good

**Review by rstief — DISMISSED** [review]
Code 👍 Also demonstrated in testing session

**Review by pzdr7 — APPROVED** [review]
LGTM

**Review by undernagruzez — DISMISSED** [review]
lgtm

**Review by coolchock — DISMISSED** [review]
lgtm

**Pull request closed without merging**
