### PR TITLE
`Development`: Refactor documentation buttons

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
This PR fixes some smaller issues I noticed while reviewing PR #7462.

### Description
- Fixed assessment documentation link (pointed to a 404 error)
- Removed any type usage in enum, replaced by ts string literal type.
- added a prefix translation key which now uses "open" / "öffne" instead of "go to" / "gehe zu".
- make button a link to support middle mouse click

### Steps for Testing
Check that the translation buttons (small info symbol next to some headlines) still work.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by tobias-lippert — APPROVED** [review]
Great refactoring.

Thanks for taking care of all these issues you spot in the codebase.

**Review by xHadie — CHANGES_REQUESTED** [review]
_Manually tested on TS3_Legacy_
All your changes work but introduce one minor style regression for the ` jhi-documentation-button `component:
The info icon besides the title has off-positioning after changing `<button>` to `<a>`


image

Before it looked correct:
image

Adjusting the `documentation-button` class to use `display: inline-block; margin-left: 5px;` seems to be an easy fix.

**Review by simon-hng — APPROVED** [review]
Code changes LGTM.

**Review by tobias-lippert — APPROVED** [review]
Reapprove code

**Review by xHadie — APPROVED** [review]

**Review by valentin-boehm — APPROVED** [review]
Manual test

**Pull request merged**
