### PR TITLE
`Programming exercises`: Fix test case type presentation for non Java exercises

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Currently, we only support different test case types ('STRUCTURAL', 'BEHAVIORAL') for JAVA exercises. So for all other programming exercises, the test case type is 'DEFAULT'. Since there was no "DEFAULT" translation string, the UI broke there.

### Description
This PR adds some translation strings and fallbacks to display the test case type for all programming exercises.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 non-JAVA Programming Exercise e.g. Python 

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to Python Exercise > Grading
4. Verify that the test case types display "Default"

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [programming-exercise-grading-tasks-table.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5650/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/grading/tasks/programming-exercise-grading-tasks-table.component.ts.html) | 90.76% | ✅ |
| [programming-exercise-task.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5650/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/grading/tasks/programming-exercise-task.service.ts.html) | 93.65% | ✅ |
| [programming-exercise-task.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5650/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/grading/tasks/programming-exercise-task.ts.html) | 100% | ✅|

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots
Before:
image

After:
image

### CODE REVIEW

**Comment by Strohgelaender** [comment]
Can we keep the 'MIXED' type for taks which have both structural and behavioral test cases?

**Review by LenaKahle — DISMISSED** [review]
Tested on TS2, works as described.

**Comment by nata-81** [comment]
Tested on TS3, works as described.

**Review by sarpsahinalp — COMMENTED** [review]
Tested on ts2 works as expected!
image

**Review by LenaKahle — APPROVED** [review]
Works, tested on TS2.

**Review by dearjasmina — APPROVED** [review]
code lgtm

**Review by Strohgelaender — APPROVED** [review]
code looks good to me.

Default is used for non-Java-exercises:
grafik

The mixed-type is used for tasks with both type of test cases:
grafik

**Review by Gusti2010 — APPROVED** [review]
tested on ts2. works as expected!

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts2 works as expected!
image

**Pull request merged**
