### PR TITLE
`Exam mode`: Import only selected exercises

### PR DESCRIPTION
**Pull request by coolchock**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
(https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
### Description

While importing exercise groups into the exam, a bug caused all exercises of a group to be imported, regardless of whether they were selected or not. This pull requests solves the mentioned issue.
closes https://github.com/ls1intum/Artemis/issues/7541

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam (preferably with more than one exercise group and with more than one exercise in each group)

1. Log in as instructor
2. Navigate to Exams page in the Course Overview
3. Press "Import an Exam" and choose an exam you want to import.
4. Select exercises that you want to import (not all)
5. Press "Import"
6. Go to exercise groups and check if exercises were imported correctly
7. On the Exercise Groups page press "Import Exercise Group"
8. Select exercises that you want to import (not all)
9. Press import and check if exercises were imported correctly
 

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
	- Improved exercise selection validation for exam import functionality.
	- Enhanced exam update process to include exercise group assignments prior to import.

- **Bug Fixes**
	- Fixed a condition where an import button remained enabled even when no exercises were selected.

### CODE REVIEW

**Review by konrad2002 — DISMISSED** [review]
manually tested on legacy ts11, works as expected

**Comment by Strohgelaender** [comment]
Code looks good. Can you add a client test for this functionality?

**Review by georgyia — APPROVED** [review]
manually tested on ts3

**Review by Gusti2010 — APPROVED** [review]
Manually tested on ts11_Legacy. Works as expected

**Review by LenaKahle — APPROVED** [review]
Approve, tested on legacy ts11. Is it intended that one can import exercises from the exam itself?

**Review by nata-81 — DISMISSED** [review]
Tested on ts1 works as expected.

**Review by MaximilianJG — APPROVED** [review]
Manually tested on ts2. works as expected

**Review by konrad2002 — APPROVED** [review]
re-approve

**Review by nata-81 — APPROVED** [review]
re-approved

**Review by georgyia — APPROVED** [review]
reapproved

**Review by Gusti2010 — APPROVED** [review]
reapproved

**Pull request merged**
