### PR TITLE
`Communication`: Add space between filters and create button in group chat modal

### PR DESCRIPTION
**Pull request by egekurt123**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Description

Solves #8869 

### Steps for Testing

Prerequisites:
- 1 Student / Instructor
- 1 Course with Messaging Enabled

1. Log in to Artemis
2. Navigate to Messages
3. Press the Plus Button next to "Group Chats" accordion 
4. Make sure that the spacing looks appropriate

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

OLD
Screenshot 2024-06-28 at 18 31 28

NEW
Screenshot 2024-06-28 at 18 31 11

Screenshot 2024-06-30 at 10 02 18

## Summary by CodeRabbit

- **Style**
  - Adjusted the layout of the group chat creation dialog by adding a top margin to improve spacing and visual alignment.

### CODE REVIEW

**Review by JohannesStoehr — COMMENTED** [review]
Can you also provide a screenshot for the case an error message is shown?

**Review by laadvo — APPROVED** [review]
Tested locally, there is more space between the filters and the button now

**Review by asliayk — APPROVED** [review]
tested locally

**Review by Jan-Thurner — APPROVED** [review]
code

**Review by JohannesStoehr — APPROVED** [review]

**Pull request merged**
