### PR TITLE
Refactoring of the Markdown Editor and Bugfixes

### PR DESCRIPTION
**Pull request by filip-gregurevic**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

- The Markdown editor used the deprecated ngbTabs
- Blockquotes aren't shown properly (closes https://github.com/ls1intum/Artemis/issues/1057)

### Description

- Refactoring of the Markdown editor to use the ngbNav instead of deprecated ngbTabs
- if there is enough space the commands are shown in the same line as the _edit / preview_ buttons
- blockquotes are shown properly (if 'markdown-preview' class is included)

### Steps for Testing

**NOTE: please test the markdown editor everywhere it is used**
(I tested it everywhere and especially for programming exercises, but you never know if you forgot something)

1. Log in to Artemis
2. Navigate to any Markdown Editor
3. Write something with blockquotes and see if it is displayed properly in the preview / when saved
4. Write something with linebreaks and see if it is displayed properly in the preview / when saved

### Screenshots

Commands in one line:
Bildschirmfoto 2020-05-03 um 22 09 08

Blockquote:
Bildschirmfoto 2020-05-03 um 22 10 03
Bildschirmfoto 2020-05-03 um 22 10 08

Linebreak:
Bildschirmfoto 2020-05-03 um 22 12 21
Bildschirmfoto 2020-05-03 um 22 12 25

### CODE REVIEW

**Comment by filip-gregurevic** [comment]
> Could you adapt the question/answer markdown editor to these changes as well? The quote command does not seem to be working properly there (see my screenshot)
> image

This is fixed in https://github.com/ls1intum/Artemis/pull/1348 along with the colours being shown properly

**Comment by krusche** [comment]
Are you sure that this does not break how we show problem statements in programming exercises? I think we intentionally use multiple lines there and do not want it to be displayed in separate lines

**Comment by filip-gregurevic** [comment]
> Are you sure that this does not break how we show problem statements in programming exercises? I think we intentionally use multiple lines there and do not want it to be displayed in separate lines

@krusche  I'll test it specifically and let you know what I find out

**Comment by filip-gregurevic** [comment]
@krusche I marked it as work in progress and moved it to the next milestone, since I need more time to be 100% sure it doesn't affect the special markdown for programming exercises

**Comment by filip-gregurevic** [comment]
I tested the Markdown-editor everywhere I found it and I didn't encounter any unwanted behaviour.

**NOTE: when you test this PR please also test specific usages of the editor such as the grading instructions**

@krusche I tested it specifically for creating and editing programming exercises locally and on the test server where everything worked as expected

**Comment by filip-gregurevic** [comment]
> > Linebreak logic is confusing (only applied if two spaces at the end)
> 
> Sounds like "Working as expected" to me 😉

@jpbernius Well, to me it is as expected, too, but it caused some confusion with other students and sometimes didn't work with the custom commands / markup.

Also the editor commands aren't shown anymore when in preview mode

**Comment by krusche** [comment]
@filip-gregurevic If you look closely to the screenshots of @jpbernius you will notice that the numbers of the tasks are misaligned after your changes.

Can you double check how we can fix this behavior?

**Comment by filip-gregurevic** [comment]
> @filip-gregurevic If you look closely to the screenshots of @jpbernius you will notice that the numbers of the tasks are misaligned after your changes.
> 
> Can you double check how we can fix this behavior?

@krusche Thanks for pointing that out. I'll look into it!

**Comment by filip-gregurevic** [comment]
> **This:**
> image

@krusche I was unable to reproduce the bug locally and on the test server.

@jpbernius Could you please give me some additional information on which test server, course and exercise you used and how you changed the code to preview?

**Comment by jpbernius** [comment]
I cannot reproduce this anymore.

**Comment by krusche** [comment]
Example in the template for Java programming exercises.

Text in the editor:

image


How it should be displayed in production (without unintended line break):

image

How it is displayed with this PR (unintended line break):

image

**Comment by filip-gregurevic** [comment]
> I just tested it and I'm sorry, but I have to reject the change `simpleLineBreaks: true` for all cases.
> 
> This might make sense in the context of questions and answers, but not in the context how we used the markdown editor for problem statements of exercises so far. In many of the existing problem statement, instructors intentionally added line breaks so that the text of the code editor is visible (while editing) without horizontal scrolling.
> 
> This might actually mean we have to prevent horizontal scrolling (it leads to usability problems) and break the text (while editing) automatically to prevent such line breaks (in this Github editor, just when I am typing right now, I also don't need to scroll horizontally).
> 
> I would suggest we let developers (optionally) add this customization option when using the markdown service to convert the text. Then, in the questions and answers component, you can use simple line breaks, and in all other places, we use the old logic for now. (which does not mean that we won't switch at some point in the future)

@krusche I understand the problem now. I'll remove the flag for now and make it optional while looking into https://github.com/ls1intum/Artemis/issues/1446

**Pull request merged**
