### PR TITLE
Remove resolver caching and add documentation for defining routes and breadcrumbs

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist

- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

Caching the resolver data risks breakages when the user edits said data (e.g. a course). Removing it is the simplest solution (and also gets rid of some extra `router-outlet`s.)

### Description

Removes caching and adds a more detailed description to the client guidelines on how I (plan to) handle routes and breadcrumbs.

### Steps for Testing

1. Check that you can still view the details, list overview, edit and create pages for:
    - Courses (Course Management)
    - Users (System Administration)
    - System Notifications (System Administration)
2. Test that data is updated when switching pages after editing (for the same pages as above)
3. Verify that the breadcrumbs still display the same as on develop (for the same pages as above)

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested on ts3. Approve

**Review by JohannesWeiss — APPROVED** [review]
Tested in testing session on ts3, works as intended.

**Review by simonzilker — APPROVED** [review]
tested in testing session. No issues found

**Review by marvinchimeka — APPROVED** [review]
Could not perceive any issues.

**Review by EneaGore — APPROVED** [review]
Could not find any issues on ts3

**Review by LudwigWeide — APPROVED** [review]
Tested on TS3. Approve.

**Review by tiffca — APPROVED** [review]
Tested successfully

**Review by valeriebucher — APPROVED** [review]
Approve. No issues occurred

**Pull request merged**
