### PR TITLE
[Exam] Due date instead of duration for quiz detail and small UI adjustments

### PR DESCRIPTION
**Pull request by filip-gregurevic**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

When creating a quiz for exercises the duration field and visible status is not needed. Instead the due date should be configurable.

### Description

Removed the footer bar fields not necessary for exams.
Added the start and due date to creating an exercise for exams instead of duration.

### Steps for Testing

**Test locally until builds work again**

1. Log in to Artemis
2. Navigate to Exam Management
3. Add a new quiz exercise to an exercise group
4. Check that the new fields are there
5. Check that the new fields work as expected
6. Check that nothing changed when creating / editing regular quizzes

### Screenshots

Bildschirmfoto 2020-06-29 um 23 13 26

### CODE REVIEW

**Comment by Alexanderkrp** [comment]
Same for me, look good 👍

**Comment by filip-gregurevic** [comment]
> 1. Fields are there
> 
> * Especially in regards to #1764 I do expect the release date to be before the due date. Could you add a check there as well?
> * I think a better default for "release Date" would be the release Date" of the exam
> 
> 1. Working as before

Thank you for testing. These are valid points but I think they should be dealt with in a follow-up PR where the checks and the wording is adjusted for all exercise types to keep it consistent

**Comment by Varnika-Tyagi** [comment]
Apart from the points raised by @julian-christl , the PR works as intended within its scope. Well done!
Quizdetail

**Comment by julian-christl** [comment]
>Thank you for testing. These are valid points but I think they should be dealt with in a follow-up PR where the checks and the wording is adjusted for all exercise types to keep it consistent

Just to clarify, you did unterstand this point?
>I think a better default for "release Date" would be the release Date" of the exam
Because you didn't mentioned it in your summary above. It's not about wording but about the default value of the input.
Which is most probably set in
src/main/webapp/app/exercises/quiz/manage/quiz-exercise-detail.component.ts:1042

**Comment by krusche** [comment]
@julian-christl this would be nice, I suggest we work on this in a follow up PR

**Pull request merged**
