### PR TITLE
`General`: Fix position of category select dropdown

### PR DESCRIPTION
**Pull request by milljoniaer**
#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
Category select dropdown was not correctly aligned with the selector, when scrolling after opening the dropdown

### Description
This was caused of some internal behaviour of angular material. For reference: https://stackoverflow.com/questions/60398533/mat-autocomplete-options-dropdown-does-not-stick-when-scrolling

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with already one category

1. Log in to Artemis
2. Create Exercise
3. Click into category selector
4. Scroll and verify that the dropdown is aligned with the input

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
image

### CODE REVIEW

**Review by rstief — APPROVED** [review]
Code

# LGTM 🦅🦅🦅 

(Also demonstrated, works as expected)

**Review by MichaelOwenDyer — APPROVED** [review]
Groundbreaking 💯 💯 💯

**Review by JohannesWt — APPROVED** [review]
Small changes, great effect | Code looks good

**Review by rabeatwork — APPROVED** [review]
maintainer approved

**Review by Strohgelaender — APPROVED** [review]

**Pull request merged**
