### PR TITLE
[Bugfix] Course deletion - The user remains on the course detail page after the course has been deleted

### PR DESCRIPTION
**Pull request by ivohashamov**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context

The delete button in the course detail page didn't redirect the user back to the course management upon deletion. Instead, the user used to remain on the same page and got a 404 Not found error (because the course has been deleted)

### Description

I added a router link to the delete method, so the user gets redirected to the course management page upon successful deletion of the course.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a course
4. Go to the course detail page of the newly created course and delete that course
5. The user should get redirected back to the course management page

### CODE REVIEW

**Review by willergeorg — COMMENTED** [review]
Tested on TS1. Redirect worked without issues.

**Review by argertboja — APPROVED** [review]
Tested on TS1! After deletion of the course redirection to home page worked successfully!

**Review by NicolasUllmann — COMMENTED** [review]
Tested on server 2. Worked as expected.

**Review by cremertim — APPROVED** [review]
Tested on ts 1 - worked as expected

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Rediction worked.

**Review by katjanakosic — APPROVED** [review]
Works as expected :))

**Review by nicolasruscher — APPROVED** [review]
Currently there is a server test failing but it seems to be unrelated, so approving anyways. Code also looks good!

**Pull request merged**
