### PR TITLE
`Lectures`: Fix race condition when re-ordering lecture units

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.

### Motivation and Context

@nairaarnez found an issue that seems to be a race condition when re-ordering lecture units and editing them in quick succession. Then, when two units have the same `order` value, one of them disappears. This can only be reverted in the database itself.
_This issue is again related to Hibernate's `@OrderColumn` annotation._

In the current approach (introduced in #4968 and tested without issues), the order should theoretically be taken from the existing entity and then re-applied to the updated unit. However, this does not work reliably (race condition?).
I could not make out the root cause of the bug. Even flushing the database after re-ordering the items did not solve it.

On a side note, adding a unique index to the tuple `(lecture_id, lecture_unit_order)` could prevent further issues but sadly does not work with the way Hibernate updates the ordering.

### Description

The `order` attribute is now transient, so that from our perspective we never update it manually, but it should be entirely taken care of by Hibernate.
This fixes the race condition in my tests, but nevertheless this PR should be tested extensively.

The proposed solution had re-introduced a known issue with the lecture importing, which from my current understanding can only be fixed with the `@Transactional` annotation on the function (which we tried to avoid back then, see [discussion](https://github.com/ls1intum/Artemis/pull/4931#discussion_r852995125)).

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Lecture with Lecture Units

1. Log in to Artemis
2. Navigate to Course Administration
3. Edit the lecture
4. Re-order lecture units and/or edit the units
5. Perform actions in quick-succession and different sequences
6. Make sure the ordering stays consistent and no lecture unit disappears
7. Ensure that you can also still import a lecture (with associated lecture units) without issues

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by nairaarnez — APPROVED** [review]
Tested on ts1, I performed the edits with multiple units (pdf, video, text) and the behavior is as expected. The units actualize correctly and the units can continue being edited (move, name change).

**Review by nadinesamyy — APPROVED** [review]
tested on ts2, works as described

**Comment by ge65cer** [comment]
I've just found that this PR re-introduces a bug when importing lectures… working on a fix for that.

**Comment by krusche** [comment]
Would be great if you can some server integration tests for the initially broken functionality on develop and the now broken functionality. We should make sure that those issues do not re-appear after future changes are introduced

**Comment by ge65cer** [comment]
@krusche That's part of the reason the server-tests fail in this PR (which was unclear yesterday as we had issues with the build agents). So the tests caught the importing issue as expected. :)
I am not sure if a test to catch race conditions is possible, but maybe an integration test with the steps @nairaarnez performed could help here. I will try that.

**Review by jbllhff — APPROVED** [review]
Tested on ts2, works as described. 
When I import a lecture with exercises with due date in the past, these exercises are not displayed in the imported lecture.

**Comment by ge65cer** [comment]
@jbllhff That is expected, as exercise units are not imported. That's because we have another process for importing exercises into courses.

**Review by willergeorg — APPROVED** [review]
Tested on TS2. Worked as expected.

**Pull request merged**
