### PR TITLE
`Communication`: Increase maximum channel name length to 30

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

With the introduction of automatically generated channels, the maximum channel name length got increased to 30. However, the input field for editing a channel name on the messages tab still had a client-side validation with a maximum length of 20.

### Description

The client-side validation for the input field for the channel name on the messages tab got increased to 30.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 channel

1. Navigate to the messages tab
2. Open the settings for the channel and navigate to the Info tab
3. Edit the channel name
4. Verify, that you can enter a name up to 30 characters

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| channel-form.component.ts | not found (modified) | ❌ |
| conversation-info.component.ts | not found (modified) | ❌ |

### Screenshots

before:
before

after:
after

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]

**Review by tobias-lippert — APPROVED** [review]

**Review by joka2206 — APPROVED** [review]
lgtm

**Review by DominikRemo — APPROVED** [review]
LGTM

**Review by Strohgelaender — APPROVED** [review]

**Review by reschandreas — APPROVED** [review]
LGTM

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM, manually tested on TS3, works like a charm 👍

**Review by basak-akan — APPROVED** [review]
Tested during the testing session on ts3, works as expected.

**Review by dearjasmina — APPROVED** [review]
LGTM

**Pull request merged**
