### PR TITLE
`Quiz exercises`: Fix an issue with the release date when resetting a quiz

### PR DESCRIPTION
**Pull request by rriyaldhi**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Closes: [5158](https://github.com/ls1intum/Artemis/issues/5158)

### Description

Remove plus 1 year of release date when resetting a quiz exercise.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with 1 Quiz Exercise (e.g. **Test 6168** of [6.0 Testing Session Course 1](https://artemis-test1.artemis.in.tum.de/course-management/117/exercises))

1. Log in to Artemis
2. Navigate to Course Administration
3. Select the Course
4. Navigate to Exercises
5. Click Reset of the Quiz Exercise
6. Verify that the Release Date (Visible From) of the Quiz Exercise is set to the current timestamp (instead of 1 year later)

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| QuizExerciseService | 86% | 96% |

### Screenshots

https://user-images.githubusercontent.com/10885503/215498185-a548a760-cb3b-4a99-9231-1c0a5784faaa.mov

### CODE REVIEW

**Review by Vinicius-Agreste — APPROVED** [review]
Tested on ts2. Worked as expected.

**Review by PhilipWerz — APPROVED** [review]
Everything works as expected. Tested on TS1.

**Review by timo07k — APPROVED** [review]
Works as expected. Tested on TS1.

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Pull request merged**
