### PR TITLE
[Bugfix] guided tour improvements

### PR DESCRIPTION
**Pull request by SimonEntholzer**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

This PR fixes two issues the tutor-assessment guided tour had. 

### Description

First of all the example submission assessment are is always highlighted correctly now. (it responds to clicking the textblocks)
<details>
it changes instantly without the need to scroll

</details>

Secondly the guided tour steps are only loaded in when the pages are really completely loaded.

### Steps for Testing

1. Log in to Artemis
2. Go to the course management and start the tutor-assessment guided tour
3. Check if everything works fine / if there aren't any issues even if the page takes long to load

### CODE REVIEW

**Review by ivanchimeno — APPROVED** [review]
Tested and works 👍

**Review by katjanakosic — APPROVED** [review]
Everything worked fine

**Review by willergeorg — COMMENTED** [review]
Tested on TS1. Looks good for me and is a nice graphical improvement that the window expands within the step of submission assessment. Just had the small error that if I select a software pattern at step 14 and close the feedback box it is only possible to re-select the whole line and assess it, not single patterns. The system does not recognize the whole-line-selection as task fulfillment, so it is not possible to go to the next step (see screenshot below if unclear).
But this is obviously an edge case and repairable by going back one step and redoing the steps.

issue4

**Review by NicolasUllmann — COMMENTED** [review]
I ran into the same edge case, but other than that everything worked fine and as expected.

**Review by real-dmy — APPROVED** [review]
Tested on TS2 with @katjanakosic. Everything looks fine.

**Review by ivohashamov — APPROVED** [review]
Looks good, tested on ts1

**Comment by SimonEntholzer** [comment]
> Tested on TS1. Looks good for me and is a nice graphical improvement that the window expands within the step of submission assessment. Just had the small error that if I select a software pattern at step 14 and close the feedback box it is only possible to re-select the whole line and assess it, not single patterns. The system does not recognize the whole-line-selection as task fulfillment, so it is not possible to go to the next step (see screenshot below if unclear).
> But this is obviously an edge case and repairable by going back one step and redoing the steps.
> 
> issue4

Just tried it and it turns out that this is an issue which is not related to the guided tour, but the general behavior of text assessments. (Maybe it's only the case for example submission assessments, I'm not sure)

**Review by maximilianbergmann — APPROVED** [review]
Tested it looks good to me

**Review by FrankeLukas — APPROVED** [review]
Everything seems to work fine.

**Pull request merged**
