### PR TITLE
`Iris`: Fix cooldown message when chat limit is reached

### LINKED ISSUE #7729: IRIS - Cooldown message when chat limit is reached is formatted incorrectly
### Describe the bug

After sending 20 requests to IRIS, the cooldown message looks like it should display a timer, but it does not.

### To Reproduce

1. Go to any exercise with IRIS enabled
2. Send 20 messages
3. See warning message

### Expected behavior

I would expect the message to replay a timer or a time when it can be used again.

### Screenshots

image

### Which version of Artemis are you seeing the problem on?

6.7.0

### What browsers are you seeing the problem on?

Chrome, Safari

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kaancayli**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
After reaching the rate limit on IRIS, the cooldown message should display a timer after string interpolation, but it does not. The string interpolation does not function correctly and the variables are still displayed in curly braces.

This PR resolves #7729

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Programming Exercise with IRIS enabled

Go to any exercise with IRIS enabled
Send messages and reach the rate limit (e.g. 20 messages)
Verify that warning message includes the remaining amount of time for cooldown and the string is interpolated correctly.

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots
Before:
288065078-1a90c09c-c931-4ddf-9358-d570fe129507
After:
Screenshot 2023-12-11 at 14 25 30

### CODE REVIEW

**Review by MichaelOwenDyer — DISMISSED** [review]
Thanks for fixing this :)

**Review by egekurt123 — DISMISSED** [review]
Manually tested on ts9, works as expected

**Review by Hialus — DISMISSED** [review]
Tested on TS9 and it works again. Thanks for the fix :D 

Code also looks good, though @RY997 can you quickly verify that this will not break anything else in the client for Iris?

**Review by rstief — COMMENTED** [review]
Tried testing on ts9, got the following error message when i typed something to IRIS:

```
ERROR TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.fromEntries (<anonymous>)
    at t.getConvertedErrorMap (chatbot-widget.component.ts:882:27)
    at Gr (chatbot-widget.component.html:166:17)
    at UL (core.mjs:11844:5)
    at eA (core.mjs:13017:7)
    at rA (core.mjs:13240:5)
    at nA (core.mjs:13203:3)
    at tA (core.mjs:13161:7)
    at eA (core.mjs:13040:5)
    at rA (core.mjs:13240:5)
    at nA (core.mjs:13203:3)
    at Koe (core.mjs:13192:3)
    at iA (core.mjs:13252:5)
    at eA (core.mjs:13067:7)
    at rA (core.mjs:13240:5)
    at nA (core.mjs:13203:3)
    at tA (core.mjs:13161:7)
    at eA (core.mjs:13040:5)
    at rA (core.mjs:13240:5)
    at nA (core.mjs:13203:3)
    at Koe (core.mjs:13192:3)
    at iA (core.mjs:13252:5)
    at eA (core.mjs:13067:7)
    at qoe (core.mjs:12944:5)
    at $c.detectChanges (core.mjs:13525:5)
    at t.tick (core.mjs:31947:16)
    at core.mjs:32116:33
    at v.invoke (zone.js:344:158)
    at Object.onInvoke (core.mjs:14344:25)
    at v.invoke (zone.js:344:46)
    at h.run (zone.js:127:37)
    at e.run (core.mjs:14198:24)
    at Object.next (core.mjs:32115:21)
    at dv.next (Subscriber.js:87:25)
    at $1._next (Subscriber.js:56:22)
    at $1.next (Subscriber.js:29:12)
    at Subject.js:35:22
    at V3 (errorContext.js:24:5)
    at vC.next (Subject.js:28:7)
    at vC.emit (core.mjs:13928:11)
    at Hb (core.mjs:14265:29)
    at Object.onHasTask (core.mjs:14360:11)
    at v.hasTask (zone.js:389:44)
    at v._updateTaskCount (zone.js:409:14)
    at h._updateTaskCount (zone.js:264:28)
    at h.runTask (zone.js:187:20)
    at m (zone.js:542:23)
(anonym) @ console.js:34
```
I have no Idea if this is caused by this PR or if it is another Issue with IRIS 🙃 
Maybe you have an Idea @Hialus ?

**Comment by kaancayli** [comment]
@rstief Thanks for the review. I'm on it. It's probably caused by the fact that paramsMap is not an iterable object sometimes. I will add an additional check

**Review by LenaKahle — APPROVED** [review]
Approve. 
image

**Review by AntonGeTUM — APPROVED** [review]
Tested on ts9, works as expected

**Comment by yassinsws** [comment]
Code LGTM

**Review by yassinsws — APPROVED** [review]
Code LGTM

**Review by xHadie — CHANGES_REQUESTED** [review]
_Manually tested on TS9_
I am unable to type more than 7 messages.
First I tried with artemis_test_user_3. Once I reach message 7, I start receiving the following error message:
image

I also tried to use my private geXX account and encountered the same issue.

**Comment by kaancayli** [comment]
@xHadie Thanks for the review. The issue seems to be unrelated to this one, since this PR only fixes the wrongly formatted error messages. It can be a temporary problem with the IRIS service. I recommend opening another issue if it still persists

**Review by konrad2002 — APPROVED** [review]
manually tested on ts9 with @Gusti2010

**Review by Gusti2010 — APPROVED** [review]
tested together with @konrad2002 on ts9. Works as expected!

**Review by MaximilianJG — APPROVED** [review]
Looks good to me: 
Screenshot 2023-12-13 at 20 16 56

**Pull request merged**
