### PR TITLE
Programming-Exercise: Don't query test cases for student

### PR DESCRIPTION
**Pull request by thilo-behnke**
### Checklist
- [x] I tested the changes and all related features on the test server https://artemistest.ase.in.tum.de.
- [x] ~I documented my source code using the JavaDoc / JSDoc style.~
- [x] ~I added integration test cases for the server (Spring) related to the features~
- [x] ~I added integration test cases for the client (Jest) related to the features~
- [x] ~I added screenshots/screencast of my UI changes~
- [x] ~I translated all the newly inserted strings~

### Description

The get programming exercise test cases REST endpoint did not have user permissions.
This lead to a lot of access denied errors on Sentry...

The user impact is still very low as the error was caught and it should not have changed anything compared to before (the test case validation only improves the information if available, if not it is treated as before the test cases were integrated).

### Steps for Testing

1. Log in to ArTEMiS
2. Start a programming exercise for which you only have user permissions (enrolled in course)
3. Programming exercise test case get call should not return access denied

### CODE REVIEW

**Comment by krusche** [comment]
I don't really understand why users should have access to this?

**Comment by thilo-behnke** [comment]
> I don't really understand why users should have access to this?

The test cases are used to validate the tasks in the problem statement.

E.g. lets say the instructor enters a test called 'tetsBubbleSort' into the problem statement that is not part of the test repositories test cases.
Normally this test would either be displayed as successful (legacy result) or not successful (non legacy result), as there can be no positive feedback for the test.
I fetch the test cases in this area to make a simple validation on the tests from the problem statement to make sure the student can always solve all tasks, e.g. in this case I would remove the test 'tetsBubbleSort' from the rendered markup of the problem statement.

If we can't fetch any test cases, no validation is done.

The test cases don't contain any sensitive information that would not be visible to the student from a UI point of view anyway (I made sure to json ignore the exercise here):

[{"id":351,"testName":"testConstructors[Policy]","weight":1,"active":true,"exercise":null},{"id":352,"testName":"testMergeSort","weight":1,"active":true,"exercise":null},{"id":353,"testName":"testMethods[SortStrategy]","weight":1,"active":true,"exercise":null},{"id":354,"testName":"testAttributes[Policy]","weight":1,"active":true,"exercise":null},{"id":355,"testName":"testMethods[Policy]","weight":1,"active":true,"exercise":null},{"id":356,"testName":"testUseMergeSortForBigList","weight":1,"active":true,"exercise":null},{"id":357,"testName":"testAttributes[Context]","weight":1,"active":true,"exercise":null},{"id":358,"testName":"testUseBubbleSortForSmallList","weight":1,"active":true,"exercise":null},{"id":359,"testName":"testBubbleSort","weight":1,"active":false,"exercise":null},{"id":360,"testName":"testClass[SortStrategy]","weight":1,"active":true,"exercise":null},{"id":361,"testName":"testClass[MergeSort]","weight":1,"active":true,"exercise":null},{"id":362,"testName":"testMethods[Context]","weight":1,"active":true,"exercise":null},{"id":363,"testName":"testClass[BubbleSort]","weight":1,"active":true,"exercise":null}]

**Comment by krusche** [comment]
This still does not explain why this should be exposed to students. The validation is only necessary when the instructor views the problem statement in the programming exercise details or edits the problem statement (while editing the programming exercise) or while editing everything "in editor". Validation is not necessary when students view the problem statement in the overview exercise details page.

I am also concerned about the long run, when we might have invisible test cases that should not be available to students. In addition I would like to reduce the server load from unnecessary calls. So instead of making this accessible to students, please simply prevent that the REST call happens from a students page!

**Comment by thilo-behnke** [comment]
**I still need to test this on the server**

I think it made more sense to validate the test cases for the students when the instructors did not have  as much indication about missing/faulty test cases in the problem statement.
I agree that now it doesn't really help that much anymore.

I thought about validating the test cases from the problem statement with the latest result's feedbacks, but this can also lead to strange results:
If there is only one test case for one task and this test case is missspelled, we will show `0 of 0 tests passed` and a green checkmark (we could make the logic more complicated here, but I don't see a huge merit from this).

Without further validation we will at the moment show a question mark and a special indication in the feedback detail overlay, which I think is the best compromise:

image

**Comment by thilo-behnke** [comment]
This is done, but the travis builds are not working because of https://github.com/ls1intum/Artemis/pull/655

**Pull request merged**
