### PR TITLE
`Development`: Remove unused participation and repository caching from routing modules

### PR DESCRIPTION
**Pull request by SimonEntholzer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

In several routing module files there is unused code for caching the participation and repository.
```
 flushRepositoryCacheAfter: 900000, // 15 min
            participationCache: {},
            repositoryCache: {},
```

### Description

This PR removes this unused code, as it serves no purpose.

### Steps for Testing

1. Login and check that the routing to repositories with the code button still works

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Streamlined routing configuration for exam management and programming exercises by removing unnecessary cache management properties.
- **Bug Fixes**
	- Improved routing logic by eliminating redundant data properties, potentially enhancing performance and data handling.

### CODE REVIEW

**Review by sachmii — APPROVED** [review]
Tested on TS1, routing works fine.

**Review by HawKhiem — APPROVED** [review]
Tested on TS5. Routing still works as mentioned

**Review by cremertim — APPROVED** [review]
Lgtm

**Review by BBesrour — APPROVED** [review]
code

**Review by coolchock — APPROVED** [review]
code

**Review by krusche — APPROVED** [review]

**Pull request merged**
