### PR TITLE
`Development`: Replace usage of standard streams with logger calls

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
We should not directly use `System.out.println()` and instead use a logger to make sure the messages are correctly saved into the log file.

### Description
Added a new ArchUnit test and replaces all issues found by the test case.

### Steps for Testing
code review

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### CODE REVIEW

**Review by tobias-lippert — APPROVED** [review]
Code

**Comment by tobias-lippert** [comment]
Reapprove

**Review by bensofficial — APPROVED** [review]
All changes look good to me 👍

**Review by tobias-lippert — APPROVED** [review]
Reapprove

**Review by valentin-boehm — APPROVED** [review]
changes look good

**Pull request merged**
