### PR TITLE
`Development`: Remove Apollon UMLDiagramType code duplication

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
The `modeling-exercise.model.ts` duplicated the `UMLDiagrymType` type from `@ls1intum/apollon`. This increases the coupling between Artemis & Apollon since we have to update that type manually, when apollon updates.

Also the type in artemis was not the exact same type as the apollon type, due to differences of enums and types.
This led to linter errors when passing from one to the other.

### Description
This PR removes the artemis type and directly imports the type and options from apollon.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student

1. Log in to Artemis
2. Create a Modeling exercise
3. Submit something
4. Assess it
5. Verify that everything works

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
image

## Summary by CodeRabbit

- **Refactor**
  - Updated the import source of `UMLDiagramType` across various components and tests to enhance consistency and maintainability.

- **Bug Fixes**
  - Removed duplicate declarations and resolved naming conflicts for `UMLDiagramType` to prevent potential issues in UML diagram handling.

- **Tests**
  - Adjusted test imports to align with the new source for `UMLDiagramType`, ensuring test reliability and accuracy.

### CODE REVIEW

**Review by matthiaslehnertum — APPROVED** [review]
Looks good to me! :)

**Review by farisd16 — APPROVED** [review]
tested on ts6, works as expected

**Review by nata-81 — DISMISSED** [review]
Tested on ts1 works as expected.

**Review by konrad2002 — APPROVED** [review]
manually tested on ts1, works as expected

**Review by AntonGeTUM — APPROVED** [review]
Tested on ts11, works as expected

**Review by georgyia — DISMISSED** [review]
tested manually on ts1, works as expected

**Review by matthiaslehnertum — APPROVED** [review]

**Review by georgyia — APPROVED** [review]
reapprove

**Review by nata-81 — APPROVED** [review]
Tested on ts2. Reapprove.

**Review by rstief — APPROVED** [review]
Code looks good 👍 Thanks for looking into this!

**Review by krusche — APPROVED** [review]

**Pull request merged**
