### PR TITLE
update apollon version to 2.3.2

### PR DESCRIPTION
**Pull request by TobiasPr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Description

Update of Apollon Version to 2.3.2
Relase Notes, see https://github.com/ls1intum/Apollon/releases/tag/v.2.3.2

### Steps for Testing

1. Create Modeling Exercise
2. Participate in Modeling Exercise
3. Check if modeling works as expected

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested on ts1. Works fine

**Review by LudwigWeide — APPROVED** [review]
Tested on TS1. with @airelawaleria . Approve.

**Review by EneaGore — APPROVED** [review]
Tested on ts1/3, works fine.

**Review by JohannesWeiss — APPROVED** [review]
Tested int testing session on ts1, works as expected.

**Review by simonzilker — APPROVED** [review]
Approve and what @airelawaleria said

**Review by marvinchimeka — APPROVED** [review]
No issues found. Tested on ts1

**Review by krusche — APPROVED** [review]

**Pull request merged**
