### PR TITLE
`General`: Improve the retrieval of user data when authenticating over external service providers based on SAML2

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] ~~I tested **all** changes and their related features with **all** corresponding user types on a test server.~~
     (Not possible, as SAML2 authentication is not configured on the test servers.)
- [x] This is a small issue that I tested locally and works on our production server ~~and was confirmed by another developer on a test server~~.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Our SAML2 provider changed their configuration in a way such that the registration number now additionally includes some prefix instead of only the actual number. The admin cannot change this on their end. Therefore, the value of interest has to be extracted from the whole attribute value when received from Artemis.

### Description
This PR introduces a new optional configuration parameter `saml2.value-extraction-patterns`. It contains a list of key-value pairs of the format:
- `key`: The name of the SAML2 attribute for which the received value needs some additional extraction.
- `value-pattern`: This is a regular expression that has to match the whole attribute value. It has to contain a named capture group. Only the part of the received value that is matched by this group is stored in Artemis.

If either the key pattern or the value pattern do not match the received attribute, then no transformation is applied to the value. Instead, the value is used as received from the authentication provider.

### Steps for Testing
Only testing with the local installation is possible as the test servers do not have SAML2 logins configured.

1. Artemis should start without the `saml2` profile.

For the following steps, start your local Artemis with the `saml2` profile enabled. You may have to uncomment the example `metadata`, `entity-id`, and `registration-id` in the `identity-providers` list for that to work.
1. Do not enable any of the extraction key/value pairs in `src/main/resources/config/application-saml2.yml`. Artemis should start normally.
2. Enable just one of the two elements of a pair. Artemis should now fail to start.
3. Enable both key and value_pattern. Artemis should now start again.
4. Modify the value of a `value_pattern` such that it no longer contains a named capture group with the name `value`. Artemis should fail to start.
5. Fix the capture group name. Enable an additional key/value_pattern pair with the same key. Artemis should fail to start.

The actual functionality is hard to test without a proper SAML2 provider set up. If you have:
1. Not defining any key/value pairs should not change the behaviour when authenticating via SAML2.
2. Choose a key/value pair where you can extract some part of the value using a regex. Check that only the part of the value that is matched by the capture group is used by Artemis.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class | Branch | Line |
| --- | --- | --- |
| `SAML2Service` | 75% | 93% |

### CODE REVIEW

**Review by dfuchss — CHANGES_REQUESTED** [review]
I'll test it on our test systems before approval :)

I would suggest to adopt https://github.com/ls1intum/Artemis/blob/develop/docs/dev/saml2-shibboleth.rst to keep the documentation up-to-date

**Comment by LDAP** [comment]
Code looks fine, although I would suggest allowing to configure a set of pairs [(key1, pattern1), (key2, pattern2),...] whereas key is a SAML2 attribute and pattern is the extraction pattern (first group extracts the information). This makes this PR apply to more use cases.

**Comment by b-fein** [comment]
> Code looks fine, although I would suggest allowing to configure a set of pairs [(key1, pattern1), (key2, pattern2),...] whereas key is a SAML2 attribute and pattern is the extraction pattern (first group extracts the information). This makes this PR apply to more use cases.

@LDAP Very good suggestion :+1: , I implemented it in the latest commit.

**Review by dfuchss — APPROVED** [review]
Tested on our systems. 
Changes work for instances without partial extraction.
Code looks good!

**Review by LDAP — APPROVED** [review]

**Review by willergeorg — APPROVED** [review]
I followed your testing steps as far as possible without SAML2 setup and Artemis behaved as described.

**Pull request merged**
