### PR TITLE
Refactor more exam exercise group routes

### LINKED ISSUE #2702: Consistent handling of "no submission (to grade) left"
### Is your feature request related to a problem?

When one submitted the assessment for an exercise there is the possibility to "assess (the) next submission". This is not possible when all other submissions have already been assessed or are currently locked by other tutors/instructors (reasonably). 
This case is handled differently for different types of exercises. For instance for text exercises you have the opportunity to go back to the assessment dashboard while for programming exercises only an error gets displayed.

### Describe the solution you'd like

A consistent handling of this case for all types of exercises would be great. Preferably, this would always be handled like e.g. for the text exercises (button to go back to assessment dashboard is displayed).

### Describe alternatives you've considered

/

### Additional context

_described case with text exercises:_
image

_described case with programming exercises:_
image

### LINKED ISSUE #2998: Handling of "no submission left" for file upload exercises
### Is your feature request related to a problem?

When assessing file upload exercise submissions in exams, and there is no submission left but one clicks on "assess next submission", only an empty page is displayed.

### Describe the solution you'd like

Ideally there would be an information "all submissions have been graded" and a button that takes you back to the assessment dashboard of the respective exam.

### Describe alternatives you've considered

Alternatively, an error message like "no submission left" would already be better than the current solution. However, to provide consistency with text exercises, the above descried solution would be better. 

### Additional context

image

### LINKED ISSUE #3004: Exercise Dashboard back button does not work when assessing exams
### Describe the bug
When assessing exam submissions as a tutor, and no further unassessed submissions are found the tutor is redirected to the following page:

image

The _Exercise Dashboard_ button does not work.

#### To Reproduce

1. Create an exam with tasks that are manually assessed, e.g. text exercises
2. Create at least one student submission for this exam
3. Log in as tutor, grade the submission and press the _Assess Next Button_
4. See the page, shown on the screenshot above and click the _Exercise Dashboard_ button

#### Expected behavior
Clicking the _Exercise Dashboard_ button should redirect the tutor/instructor to the corresponding _Exercise Dashboard_ of the Exam the tutor is currently assessing.

#### Screenshots

Artemis-ButtonDoesNotWork

### Environment

<details><pre>
 - Browser: Safari and Firefox
</pre></details>

#### Output in Web Console

<details><pre>
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'course-management/439/exercises/6709/assessment-dashboard'
noMatchError@https://artemistest.ase.in.tum.de/app/main.a2fae626d816ac1b4e59.bundle.js:2:369940
apply/<@https://artemistest.ase.in.tum.de/app/main.a2fae626d816ac1b4e59.bundle.js:2:369658
error@https://artemistest.ase.in.tum.de/app/main.a2fae626d816ac1b4e59.bundle.js:4:1368014
_error@https://artemistest.ase.in.tum.de/app/main.a2fae626d816ac1b4e59.bundle.js:4:989522
error@https://artemistest.ase.in.tum.de/app/main.a2fae626d816ac1b4e59.bundle.js:4:989319
_error@https://artemistest.ase.in.tum.de/app/main.a2fae626d816ac1b4e59.bundle.js:4:989522
error@https://artemistest.ase.in.tum.de/app/main.a2fae626d816ac1b4e59.bundle.js:4:989319
_error@https://artemistest.ase.in.tum.de/app/main.a2fae626d816ac1b4e59.bundle.js:4:989522
error@https://artemistest.ase.in.tum.de/app/main.a2fae626d816ac1b4e59.bundle.js:4:989319
_error@https://artemistest.ase.in.tum.de/app/main.a2fae626…
    Angular 10
        A
        A
        R
        invokeTask
        onInvokeTask
        invokeTask
        runTask
        _
        invokeTask
        _
inboundfilters.js:114:19
</pre></details>

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context

Breadcrumbs didn't work as intended for assessing exam exercises, since the routes were set up to redirect you to the course.
Closes #2998.
Closes #3004.
Closes #2702.

### Description

Now assessment is basically done "in the exam" route, so you can use the breadcrumbs. This also adds buttons to the Exercise Dashboards to make navigation a bit easier during assessment.

### Steps for Testing

(Note: "all exercise types" doesn't include quiz exercises for assessments.)

1. Test the assessment dashboard and exercise dashboards of all exercise types of a course
2. Test the assessment dashboard and exercise dashboards of all exercise types of an exam
3. Test "Scores", "Participations" and "Submissions" of exercises in an exam exercise group
4. Make sure assessing exercises of all types in an exam still works as intended (=> create a test exam with each exercise type, participate and assess)
5. Breadcrumbs should always display the exam title to click on when assessing exam exercises, all following segments do *not* necessarily need to work for now

It is easiest to cover everything by creating an exam, holding a test run (with assessment) and then participate with a few students and assess that.

(Also note that tutors often display IDs instead of titles, that is not a problem with this PR.)

### Screenshots

Example for breadcrumbs when assessing "programming exercise" (name of the exercise) of the "PreviousReturn" exam:
grafik

Buttons during assessment:
grafik
grafik

When there is no submission left to assess the following is displayed (except for programming and file-upload exercises):
grafik

The following exercise-group buttons now leave you with the exam in the breadcrumbs:

### CODE REVIEW

**Review by SimonEntholzer — CHANGES_REQUESTED** [review]
It generally looks good, I just have a few things I noticed while testing:

The "exercise dashboard" button does not work for text, modeling, and fileupload exercises.
image

-----
image
image
I guess it is not part of this PR, but I guess we should remove the /exercise-groups part in the url.

-----

For older exams, when you go to "scores" it just keeps loading. Though, I'm not sure if this is connected to this PR at all.

**Comment by FrankeLukas** [comment]
@SimonEntholzer thanks for the feedback. That scores thing is indeed not related to this PR. I forgot to pass the link to the components you mentioned, which is fixed now.

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS1, all links work as expected now. :D

**Review by FuchsDominik — APPROVED** [review]
We tested, works good now :) I like the new Exercise Dashboard button

**Pull request merged**
