### PR TITLE
`Communication`: Replace discussion labels with communication

### PR DESCRIPTION
**Pull request by canberkanar**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
The communication feature of Artemis was previously named as 'Discussion' within the platform. To respond to the updates of the feature and to make it easier to refer to, we change the label 'Discussion' to 'Communication'.

### Description
Please note that the router link is not updated in this PR and left as 'discussion' like before, since the accessibility of Posts from announcement emails depend on it. The router link is planned to be updated within the semester break.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with postings enabled

1. Log in to Artemis
2. Navigate to a Course Page
3. Make sure that 'Discussion' label is replaced with 'Communication' and that the page is still accessible when clicked.
4. Navigate to an Exercise or Lecture
5. Make sure the 'Discussion' label is replaced with 'Communication' and the tooltips are updated accordinly.
6. Go to course management page.
7. Make sure that 'Discussion' label is replaced with 'Communication' and that the page is still accessible when clicked.
8. Click on a course.
9.  Make sure that 'Discussion' label is replaced with 'Communication' and that the page is still accessible when clicked.

### Documentation
https://artemis-platform--5289.org.readthedocs.build/en/5289/

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
Not changed.

### Screenshots
image
image
image
image
image
image
image
image
about us

### CODE REVIEW

**Comment by Dominik-Weinzierl** [comment]
Can you also replace the documentation?

**Review by TheTrueVester — DISMISSED** [review]
Tested during testing session on ts1. Everything worked as expected.

**Review by babyygemperor — APPROVED** [review]
Tested on ts1 in a testing session, everything worked as described

**Review by minrows — DISMISSED** [review]
Tested on ts1 during testing session. LGTM 👍

**Review by nadinesamyy — DISMISSED** [review]
tested on ts2, works as described

**Review by Santia-go — DISMISSED** [review]
Tested on TS1
Works as expected!

**Review by Strohgelaender — CHANGES_REQUESTED** [review]
1) Discussion is currently mentioned as a possible PR name, maybe we should change that as well:
grafik

2) The readme currently links to the docs with /user/discussion/, but this PR changes the link to /user/communication/. So the readme should be updated as well.

**Review by jbllhff — DISMISSED** [review]
Tested on ts2, looks good!

**Comment by canberkanar** [comment]
> 2\. user/discussion/,

Nice catch 👍🏻

**Comment by canberkanar** [comment]
Readme file and about us page updated. No need for a manual retest.

**Pull request merged**
