### PR TITLE
`Quiz exercises`: Improve user experience when creating modeling drag and drop exercises

### LINKED ISSUE #7019: Drag & Drop: extremly slow scrolling when target field is off-screen
### Describe the bug

When dragging answers to fields off-screen the exercise scrolls painfully slow.

Use arrow keys to see normal/fast scrolling.
Another workaround is placing the answer into a temporary helper field, then scrolling normally, then dragging to actual target 

### To Reproduce

1. Go to a Drag & Drop exercise
2. Try dragging an item into an off-screen field 

### Expected behavior

Normal/ Decently fast scrolling, so off screen fields can be filled.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.3.8

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

### Additional context

See e.g. FPV exam, https://artemis.in.tum.de/courses/271

### Relevant log output

_No response_

### LINKED ISSUE #7020: Drag & Drop: answer menu too small
### Describe the bug

The possible answers list for Drag & Drop exercises does not span the entire height of the screen. Instead there is a scrollbar. The exercise itself is bigger than the screen.

### To Reproduce

1. Go to a Drag & Drop exercise with a big answers list
2. see the answers list

### Expected behavior

The answers field uses the entire height of the screen (or at least most of it) and only if that is not enough uses a scrollbar.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.3.8

### What browsers are you seeing the problem on?

Firefox

### Additional context

See e.g. FPV exam, https://artemis.in.tum.de/courses/271, Exercise 6
encountered while in exam/editable mode

### Relevant log output

_No response_

### LINKED ISSUE #7211: Drag and Drop Model Quiz Exercise "Generate Quiz Exercise" button not working
### Describe the bug

When using the drag-and-drop model quiz, the 'generate quiz exercise' button doesn't appear to function. I expect it to create a quiz exercise and redirect to the course management exercises page. The [documentation](https://ls1intum.github.io/Artemis/user/exercises/quiz/#create-drag-and-drop-model-quiz-exercise) lacks clear instructions on this.

### To Reproduce

1. Go to Course Management of an Artemis course
2. Click on Exercises
3. Scroll down to Quiz Exercises
4. Click on Create Drag and Drop Model Quiz
5. Click on Create a new Apollon Diagram
6. Fill title and select any Diagram Type
7. Drag-drop some modeling
8. Click on Generate a Quiz Exercise
9. No actions happen

### Expected behavior

The expectation would be the generation of an drag and drop model quiz exercise

### Screenshots
Drag_Drop_Quiz_Issue

### Which version of Artemis are you seeing the problem on?

6.5.0

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

```shell
No errors appear on the console
```

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
This PR is a collection of multiple issues regarding the quiz modeling exercise user experience of both instructors and students.
Hence, Closes #7211 closes #7020 

### Description
- it shows a validation error to instructors when there are no interactive elements in an apollonDiagram which is used to generate a quiz exercise (this issue led to the false impression, that the button is not working at all and not only input missing)
- it navigates to the edit page of the generated drag-and-drop quiz exercise
- it increases the auto-scroll speed of draggables when they are moved to the borders of the viewport (the default value is quite slow)
- it increases the height of the draggable items container to 100vh - the footer height

#### First improvement:
Prerequisites:
- 1 Instructor
- 1 course

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to exercises
4. click on "Create Drag and Drop Quiz"
5. click "Generate quiz"
6. See the validation error that there are interactive elements missing
7. Add interactive elements to your model
8. click "Generate quiz"
9. See the success message
10. Verify that you are navigated to the edit page

#### Second and third improvement
Prerequisites:
- 1 Student
- 1 dnd quiz with a lot of draggables and exercises below the dnd exercise

1. Log in to Artemis
2. Start quiz
3. Verify that the container of draggables is as large as the viewport
4. Drag item and move to the bottom/top of page, so that it starts to scroll
5. Verify that the scrolling is faster and feels comfortable

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by dearjasmina — APPROVED** [review]
code lgtm,
side question: "validateError" translation in german here is "Fehler beim Erstellen", german is not my first language but maybe consider using validieren instead?

**Comment by milljoniaer** [comment]
Yes, you are right, it is semantically not totally the same. But I liked this version better in German (I copied the first part from the normal error) and since the second part hints that there are interactive elements missing, I would stick to this version for now.

**Review by MaximilianAnzinger — CHANGES_REQUESTED** [review]
Code looks good. I still think the translation for the error is incorrect, `validation` is not the same as `creation`. This feels inconsistent.

**Comment by milljoniaer** [comment]
Alright, then lets change it, what do you think about "Validierungsfehler: Interaktive Elemente werden zum Generieren benötigt." for the german translation?

**Review by basak-akan — APPROVED** [review]
Thank you for fixing this! Tested on TS4 with provided steps, and worked as expected.

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM 👍

**Review by lennart-keller — CHANGES_REQUESTED** [review]
Tested on TS4. The instructor improvements work fine.
However, the scrolling does not work properly for me using Chrome (version 117) on a Mac. It either scrolls very slowly or just scrolls a tiny bit when reaching the viewport borders and then stops.

**Comment by milljoniaer** [comment]
Thanks for finding this bug. I tested this only on windows. However, I just also could verify, that it is an issue on macs. So I adjusted this PR so it wont close the issue and I will leave a comment in #7019 that there is an issue on macs.

I suggest to merge this PR like it is, since it has other important things and it also improves the scrolling on windows.

**Pull request merged**
