### PR TITLE
Improved exercise scores loading behavior and table display 

### PR DESCRIPTION
**Pull request by madwau**
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] ~~Server: I added multiple integration tests (Spring) related to the features~~
- [x] ~~Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)~~
- [x] ~~Server: I implemented the changes with a good performance and prevented too many database calls~~
- [x] ~~Server: I documented the Java code using JavaDoc style.~~
- [x] ~~Client: I added multiple integration tests (Jest) related to the features~~
- [x] ~~Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)~~
- [x] ~~Client: I documented the TypeScript code using JSDoc style.~~
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] ~~Client: I translated all the newly inserted strings into German and English~~

### Motivation and Context
PR #1011 implemented the functionality to deliver the highly requested feature #999. However, there were still some minor issues found during testing by @krusche. This PR aims at fixing those.

### Description
- The vertically centered loading indicator for the exercise score table had no vertical spacing which looked visually off and didn't communicate to the user that a larger object such as a table is being loaded. This is fixed now by giving the loading container an appropriate height relative to the viewport height.
- When clicking on the "10 results per page" button and selecting a new page size, the dropdown just froze and stayed open, and no loading animation indicated that the table is being rerendered (which can take quite a few seconds when there are a lot of results). With this PR, the dropdown properly closes after clicking and the loading animation is shown while the table is rerendered with the new page size. Since it is not possible to asynchronously render the table within the current setup, this is done by giving the script execution a short time interval of 500ms after requesting to change the page size (in order for the dropdown to properly close and to trigger the loading animation).
- Previously, the width of all columns did not always fill out the whole width of the table, leading to the footer being wider than the table header and body (making it look like the footer is overflowing). This is fixed by transforming the maxWidth attribute of the ngx-datatable columns to a regular width attribute. This allows the remaining width to be equally distributed to the columns.

### Steps for Testing
1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate into a course
4. Click on Scores for a programming exercise (with many scores)
5. Change the page size on the top left

### Screenshots
OnPaste 20191118-194306

OnPaste 20191119-163509

captured

### CODE REVIEW

**Comment by krusche** [comment]
Can you show a screenshot for programming exercises as well?
Also please make sure to tick off all tasks in the PR. In case they don't apply, please strikethrough or remove them

**Comment by madwau** [comment]
> Can you show a screenshot for programming exercises as well?
> Also please make sure to tick off all tasks in the PR. In case they don't apply, please strikethrough or remove them

I used strikethrough for those tasks of the checklist that are not relevant for this PR.

I still have to perform the test steps on the test server and then I will also make a screenshot for programming exercises. I tried to do this locally but as Alex told me, it is not (easily) possible to create programming exercises locally since it requires setting up a local bitbucket instance. I'm not sure if this is something worth doing anyway since the need for it will arise again soon or not. Alex told me it's probably faster to just do it on the test server in this case.

Since many of the developers are executing the test plan on develop on the test server currently, I have to do this later since I don't want to interfere with that by deploying my feature branch (as I understand it there is no parallel multi-branch deployment on the test server).

**Comment by jpbernius** [comment]
> I used strikethrough for those tasks of the checklist that are not relevant for this PR.

Please also check the box, OR convert it to a bullet point.
```diff
+   - [ ] ~Lorem ipsum~
-   - ~Lorem ipsum~
```
That way it will not show open tasks in the overview.

**Comment by madwau** [comment]
@jpbernius Thanks for the feedback. I checked the boxes of the non-applicable checklist steps. Converting them into bullet points makes the checklist lose its list apperance to some degree.

**Comment by madwau** [comment]
@krusche I added a screenshot for programming exercises (see top).

**Comment by madwau** [comment]
As just discussed with @krusche, the issue #1078 (clicking on the arrow icon should also cause a sort) will also be fixed as part of this MR as it is closely related. If possible, also display the correct icon based on the sorting state of the column (none, desc, asc).

**Comment by madwau** [comment]
> As just discussed with @krusche, the issue #1078 (clicking on the arrow icon should also cause a sort) will also be fixed as part of this MR as it is closely related. If possible, also display the correct icon based on the sorting state of the column (none, desc, asc).

@krusche This has now been implemented. The click handler was moved up to the parent element containing both the label and sorting icon, and a helper function was added to determine which icon to show for each column.

OnPaste 20191119-185516

**Pull request merged**
