### PR TITLE
User-statistics-fix

### PR DESCRIPTION
**Pull request by FuchsDominik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

The Month and year displayed in the Month and Year Tab was chosen by the Month/Year of the very right date of the chart. Since this can be confusing, this should be changed.

### Description

- The Year displayed in the year tab is now the year of the 7th bar, which is the right side of the middle of the chart
- The Month displayed in the Month tab is now depending on the length of the month. Its always the right bar next to the middle of the chart:
       If the length of the month is odd, like December, the month of the 17th bar is chosen
       If the length of month is even, like November, the month of the 16th. bar is chosen as the right center of the chart

(for months with odd lengths, choosing the middle bar would lead to never displaying 30 day months like November, August etc., hence the bar right next to the middle is chosen)

### Steps for Testing

1. Log in to Artemis
2. Navigate to Server Administration -> User statistics
3. Make sure that the above mentioned months and years are shown

(edge cases are hard to test, you could check out the branch locally and play around with the time of your pc, like seen in the screenshot)

### Screenshots

November has 30 days:
Screenshot 2021-01-15 at 14 46 24

December has 31 days:
When it's the 14.01.2021:
Screenshot 2021-01-14 at 14 49 45
When it's the 15.01.2021:
Screenshot 2021-01-15 at 14 48 22

Year:
Screenshot 2021-01-14 at 14 50 34

### CODE REVIEW

**Review by JohannesWeiss — APPROVED** [review]
Works as intended now!

**Review by airelawaleria — APPROVED** [review]
Tested on ts1 with @JohannesWeiss. Approve

**Review by marvinchimeka — APPROVED** [review]
Approve

**Review by simonzilker — APPROVED** [review]
Approve

**Review by nicolasruscher — APPROVED** [review]
Code looks good to me 👍

**Review by valeriebucher — APPROVED** [review]
Looks good!

**Review by EneaGore — APPROVED** [review]
All looks fine.

**Pull request merged**
