### PR TITLE
`General`: Display registration number in user settings

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [X] I added multiple screenshots/screencasts of my UI changes.
- [X] I translated all newly inserted strings into English and German.

### Motivation and Context

This PR is inspired of #4647. It makes no sense that users don't see their own registration number if it's available.

### Description

I simply made sure that on `GET /api/account` the registration number gets set and added the registration number, if available to the account information.

### Steps for Testing

Prerequisites:
- TS1
- 1 Account with registration number (TUM linked)
- 1 Account without registration number (test account)

1. Log into Artemis with your TUM-Credentials that have the registration number set
2. Navigate to your account information
3. Make sure that the registration number is shown correctly
4. Log into Artemis with a test account
5. Navigate to the account information
6. Make sure that the registration number is not show

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by ole-ve — DISMISSED** [review]
Tested on TS1, works as described.
Changes also look good to me. 👍
There is one failing server test but I assume this is not related to your PR.

**Comment by julian-christl** [comment]
> Tested on TS1, works as described. Changes also look good to me. 👍 There is one failing server test but I assume this is not related to your PR.

Reran it, just a flaky test. Was running through on Bamboo anyway

**Review by Hialus — APPROVED** [review]
Tested on TS1.
When logging in with my own account the registration number is shown.
When logging in with a test user the registration number box is not shown.
I also could not find a case where the registration number was leaked to other students. 
Code also looks good 👍🏻

**Review by willergeorg — DISMISSED** [review]
Tested on TS1. Worked as expected. I'm a bit unsure about the notation of "Registration Number" as I would intuitively prefer "Registration number", but since it is aligned with "Full Name", I think it is fine.

**Review by Santia-go — DISMISSED** [review]
Tested on TS1
Working as expected. 
My account has no registration number, so the registration number box is not shown.

**Review by valeriebucher — DISMISSED** [review]
Code looks good and worked on ts1 as expected 👍

**Comment by julian-christl** [comment]
Just moved the section down at the request from @krusche. Shouldn't require more testing but feel free to do so if you deem it necessary. Doesn't take much time anyway.

**Review by Hialus — APPROVED** [review]
Reapprove, as only the ordering has changed.

**Review by bassner — APPROVED** [review]

**Review by ole-ve — APPROVED** [review]
Re-approve Code & Testing.

**Review by willergeorg — APPROVED** [review]

**Pull request merged**
