### PR TITLE
Change Instruction Component for File Upload Exercises

### LINKED ISSUE #2141: Inconsistency in instructions side panel
### Describe the bug

I noticed an inconsistency in the assessment view of file upload exercises compared to text and modeling exercises:
for file upload exercises assessors can not see the problem statement in the side panel while this is possible for the other exercise types. As a tutor it is important for me to see the problem statement beside the submission in order to be able to correctly identify requirements and my expectations from the student and assess the submission accordingly

Text Exercise
image

File Upload Exercise
image

#### To Reproduce

1. Go to Submissions
2. Click on assess

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [X] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [X] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Closes #2141

### Description

- Switched to `jhi-resizable-instructions` to `jhi-collapsable-assessment-instructions` for file upload exercises

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Assess a File Upload Exercise and check that the instruction panel works

### Screenshots

image

### CODE REVIEW

**Review by krusche — CHANGES_REQUESTED** [review]
Please fix the lint warnings

**Review by schultek — DISMISSED** [review]
This works fine, however i would remove this extra margin:
Unbenannt

**Review by TobiasPr — CHANGES_REQUESTED** [review]
Same issue that stephan mentioned, other than that testing worked for me and code looks also good

**Comment by stefanwaldhauser** [comment]
> This works fine, however i would remove this extra margin:
> Unbenannt

Done in 52c89a6a535bfbb7a2abf15626928a03a4f7fb42

**Comment by stefanwaldhauser** [comment]
> Please fix the lint warnings

done in 625f530bb1df616398d0e0ba1ec318a3463dddae

**Review by balazs-czopf — COMMENTED** [review]
Code looks good to me and works as expected. Nice work 🚀

**Review by balazs-czopf — APPROVED** [review]

**Comment by HanyaElhashemy** [comment]
Do we need `jhi-resizable-instructions` at all? I think this is duplicate code that we could delete in this PR already.

**Comment by stefanwaldhauser** [comment]
> Do we need `jhi-resizable-instructions` at all? I think this is duplicate code that we could delete in this PR already.

I had some errors switching it out in other places and would like to do it in a follow up pr to keep the scope of this PR small

**Review by sjagla27 — APPROVED** [review]
Code looks good and worked for me.

**Review by filip-gregurevic — APPROVED** [review]

**Review by schultek — APPROVED** [review]
re-approve

**Review by sleiss — APPROVED** [review]

**Comment by fde312** [comment]
Maybe we can also align all exercise types to use the `resizable-container.component.ts`. We are using this currently for the exercise participations (also for exam) and for the assessment of text exercises.

**Review by fde312 — APPROVED** [review]
Works fine and code looks good! :)

**Review by TobiasPr — APPROVED** [review]

**Comment by krusche** [comment]
> Maybe we can also align all exercise types to use the `resizable-container.component.ts`. We are using this currently for the exercise participations (also for exam) and for the assessment of text exercises. What do you think @krusche ?

Yes this would be good. Please change this in a follow-up PR to make this consistent.

**Review by krusche — APPROVED** [review]

**Pull request merged**
