### PR TITLE
`Programming exercises`: Fix buttons changing position on hover in exercise details page

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Stephan approached me with an issue when hovering over the buttons with a tooltip at the top of the programming exercise detail page.

### Description

This seems to be an issue with the browser wanting to render the tooltip div next to the button despite it having `position=absolute`. I am not sure why this happens now, but I fixed it by specifying the body as the container for the tooltip, as it is already used in other places.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise 
- Safari or Chrome base Browser. This does not happen in Firefox

1. Log in to Artemis
2. Navigate to the programming exercise detail page
3. Hover over the gray buttons (e.g. Update Structure Oracle)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Before:
https://user-images.githubusercontent.com/18218285/180463819-2474a30b-8fc2-4e3b-a33e-9bf7ec3dcd88.mov
After:
https://user-images.githubusercontent.com/18218285/180463831-9dd4e60a-e091-4a46-90cf-b6c50bb2c915.mov

### CODE REVIEW

**Review by xlieA — DISMISSED** [review]
Tested on ts2 with Chrome. The hovering works as shown in the video. The buttons don't jump anymore.

**Review by nairaarnez — APPROVED** [review]
Tested in ts1, buttons are working as expected

**Review by mallgaier — DISMISSED** [review]
Tested, works as expected.
Good fix 👍

**Review by yuling-sun — DISMISSED** [review]
Tested on TS1. Works as described.

**Review by SimonPaul02 — DISMISSED** [review]
Tested on TS1 with Chrome, works as expected

**Review by jschmautzer — APPROVED** [review]
tested on ts2 with Chrome, works as described

**Review by babyygemperor — DISMISSED** [review]
Tested on ts2, works as described

**Review by MetinLamby — APPROVED** [review]
Tested on TS2 with Chrome, works as expected

**Review by jbllhff — APPROVED** [review]
Tested on ts2, looks good!

**Review by jschmautzer — APPROVED** [review]
re-approve, tested with Chrome on ts2

**Review by bassner — APPROVED** [review]
LGTM 👍

**Review by alaraozdenler — APPROVED** [review]
Tested on ts1, works as shown

**Review by canberkanar — COMMENTED** [review]
Code changes are good. 👍🏻

**Review by canberkanar — APPROVED** [review]

**Pull request merged**
