### PR TITLE
`Programming exercises`: Allow viewing the repository using the new code editor

### PR DESCRIPTION
**Pull request by pzdr7**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

LocalCI introduced the option to view repositories in the online code editor. Since we want to replace Ace, we have to replace it in this view as well.

### Description

Uses Monaco in the "Open Repository" view. It is read only.

### Steps for Testing

Prerequisites:
- Test Server with LocalCI (e.g. TS1)
- 1 Student
- 1 Programming Exercise (ideally with the online code editor enabled)

1. Log in to Artemis
2. Go to the programming exercise and make a submission.
3. Go back to the programming exercise and click on "Open Repository"
4. Verify that you can see your files and that you cannot modify the code in this view.
5. Review the code of this PR 😉 (+2 -0)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image

## Summary by CodeRabbit

- **New Features**
	- Enhanced the repository viewer with a Monaco Editor for better code visualization and interaction, including a read-only mode for manual feedback.

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]

**Review by b-fein — APPROVED** [review]
Works :+1:

**Review by coolchock — APPROVED** [review]
tested on ts1, works as described 👍

**Review by undernagruzez — APPROVED** [review]
works as described

**Review by BaumiCoder — APPROVED** [review]
Tested in Testing Session :heavy_check_mark:

**Review by kaancayli — APPROVED** [review]
Tested on ts1. Works as expected. LGTM

**Review by egekurt123 — APPROVED** [review]
Tested during testing session, works as expected

**Pull request merged**
