### PR TITLE
`Exam mode`: Improve the appearance of 'Review is Open' in the exam summary

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
#### General

- [X] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guiXelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.

### Motivation and Context
A user in the exam testing session was confused that the "Review is open" text is in a button, that is not clickable.

### Description
- Changed the button to an alert

### Steps for Testing
Nothing really. The before and after screenshots are enough in my opinion

#### Code Review
- [x] Review 1
- [x] Review 2

### Screenshots
Before:
before
After:
after

### CODE REVIEW

**Review by pantageepapa — APPROVED** [review]
tested on ts2 and looks like in the screenshot :)

**Comment by bassner** [comment]
Did you check how it looks in dark mode (since you removed that checkbox for some reason)? :)

**Review by alaraozdenler — APPROVED** [review]
Tested on ts1, works as shown in the screenshots

**Review by luisa-we — APPROVED** [review]
Tested on TS2, looks like shown in the screenshots

**Review by MetinLamby — APPROVED** [review]
tested on ts2, looks like in the second screenshot

**Comment by stefanwaldhauser** [comment]
> Did you check how it looks in dark mode (since you removed that checkbox for some reason)? :)

Sry :D Did not intend to remove it. Also looks good in dark mode

**Comment by Dominik-Weinzierl** [comment]
Just my opinion, but I think it doesn't look good. I think the alert should not be so big.

**Review by bassner — APPROVED** [review]
> Also looks good in dark mode
Great!

> I think the alert should not be so big
Yeah we could have used a large green rounded-pill badge instead, but depends on @krusche being fine with this solution or not :)

Code LGTM in general

**Pull request merged**
