### PR TITLE
[Bugfix] Resolve missing key in translations of alerts

### PR DESCRIPTION
**Pull request by derLalla**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context

The jhiAlert Service uses the translation Service to translate the received `key`. On some occasions, we want to directly use a specified message for which no translation key is available. 

### Description

In case a translation key is not found, the previous output to the alert-component was : 

translation-not-found[translation.key]

The approach now is to remove the `translation-not-found[]` portion and just show the translation key. 
We sent additionally a warning to Sentry to be informed if we are missing such a key.

This is a follow-up of the #2645  PR. It also adapts the separate alert-error.component.ts

### Steps for Testing

1. Log in to Artemis
2. Try to generate a warning message
3. For example create a Programming exercise, with a title and shortname which already exists
4. Verify that the warning message is working as intended and no issue was sent to Sentry. 
(Only issues with a missing translation key shall send a notification to Sentry)

### Test Coverage

No new relevant code or features were added, so the test coverage stays the same.

### Screenshots

Correct alert notification:
image

New Issue in Sentry:
image

### CODE REVIEW

**Review by simonzilker — APPROVED** [review]
Worked as intended on ts1

**Review by airelawaleria — APPROVED** [review]
Approve

**Review by marvinchimeka — APPROVED** [review]

**Review by EneaGore — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]

**Review by philgabr — APPROVED** [review]
Tested on ts3. Approve.

**Comment by kloessst** [comment]
Is there a known instance, where such a sentry error should be issued?

**Review by kloessst — COMMENTED** [review]
Code looks fine, and the described case works as intended. Still I'd like to test that a sentry error is thrown in cases where the key is missing. Do you know such an interaction?

**Comment by derLalla** [comment]
> Is there a known instance, where such a sentry error should be issued?

Not really, because this should actually not happen. Only if you provide a translation key on purpose which is not known. (e.g. locally or you create a commit and deploy it for a test)

**Review by kloessst — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
