### PR TITLE
`Development`: Remove unused tracking of text exercise assessments via Athene

### PR DESCRIPTION
**Pull request by pal03377**
### Checklist

**After merge: The following Nginx Config on the production server can be removed if it exists:**
```
location /athene-tracking {
        proxy_pass https://athene01.ase.in.tum.de/tracking;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```
(introduced after #1719)

I'm not sure if this even still exists, but at least `https://artemis.ase.in.tum.de/athene-tracking` does not return a 404. However, the repository does not include such a configuration.

#### General

- [X] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [X] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
#### Client
- [X] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

A text assessment tracking feature was introduced in #1719. It sends the following events to [the Athena tracking service](https://github.com/ls1intum/Athena/tree/master/tracking):
- `start`: Sent when a tutor starts assessing a text exercise
- `save`: Sent when a tutor saves their assessment
- `submit`: Sent when a tutor submits their assessment

We already have the `text_assessment_event`s, which track these kinds of events in Artemis directly. Also, the existing Athene tracking hasn't been actively used in the last 1-2 years.

Therefore, we remove the Athene tracking functionality in this PR. This also helps bring us closer to a clean integration of Athena-New by reducing coupling between the existing Athene service and Artemis.

### Description

I removed all code that was related to Athene tracking. This includes the three events named above in the client. An authorization header for the Athene tracking service was transmitted directly. This token is now also removed.

### Steps for Testing

Prerequisites:
- Test Server with Athene enabled (only `artemis-staging` to my knowledge)
- A text exercise
- A submission on that text exercise - example exercise with existing submissions: https://artemis-staging.ase.in.tum.de/course-management/3976/text-exercises/6702

1. Log in to Artemis
2. Navigate to the text exercise
3. (If none exists: Create a test submission on the text exercise)
4. Go to the exercise dashboard of the exercise (from the course management exercise view)
5. If you haven't already, click the button to confirm the grading instructions ("Start participating in the exercise" in light blue)
6. Open your DevTools.
7. Start grading a submission or continue grading.
8. Observe that none of the 504 server errors as in the screenshots below appear when you
  - Open the submission
  - Give some feedback
  - Click "Save"
  - Click "Submit"
  - Do anything else with the exercise

This error appears on artemis-staging on the develop branch, because the `/athene-tracking` endpoint is not set up (but still exists):
screenshot-2023-06-24_001463

#### Exam Mode Testing

Prerequisites:
- as before
- an exam with a text exercise

1. Create a submission on the text exercise in the exam.
2. Test assessing the exercise as before.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [X] Test 1
- [X] Test 2

### Test Coverage

I only removed code, so there are no additional assertions to be made.

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [text-submission.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5049-6/artifact/shared/Coverage-Report-Client-Tests/app/entities/text-submission.model.ts.html) | 100% |  |
| [text-assessment.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5049-6/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/assess/text-assessment.service.ts.html) | 91.56% |  |
| [text-submission-assessment.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5049-6/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/assess/text-submission-assessment.component.ts.html) | 89.74% |  |
| [text-submission.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5049-6/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/participate/text-submission.service.ts.html) | 91.66% |  |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [AtheneTrackingTokenProvider.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5049-6/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.security.jwt/AtheneTrackingTokenProvider.html) | deleted |  |
| [TextAssessmentResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5049-6/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/TextAssessmentResource.html) | 91% |  |
| [TextSubmissionResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5049-6/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/TextSubmissionResource.html) | 96% |  |

### Screenshots

There are no changes in the UI. As long as the DevTools are closed, there should be no noticeable changes at all.

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Removal of code looks good to me

**Review by FelixTJDietrich — APPROVED** [review]
Code removal also looks good to me, I couldn't fine any related code remaining 👍

**Review by simon-hng — APPROVED** [review]
Tested on ts4. none of the errors appeared

**Review by TheZoker — APPROVED** [review]
Tested in testing session on TS4. LGTM 👍

**Pull request merged**
