### PR TITLE
`Programming exercises`: Enable static code analysis for Xcode

### PR DESCRIPTION
**Pull request by DanielKainz**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).

### Motivation and Context

This PR introduces Static Code Analysis for iOS programming exercises (Programming Language: Swift, Project Type: Xcode). It is done with swiftlint, like for plain Swift exercises. But in the case of iOS programming exercises fastlane is used to configure the SCA task on the build agents build plan. 
It is necessary to give the instructor the possibility to configure the static code analysis in the exercise creation process. This means that there is a checkbox shown to enable the SCA and if it is ticked a text field is shown to specify the penalty, exactly as it is done for other programming languages and project types. 
The build plan needs to have have a final task called for the SCA. It should contain the creation of the necessary target directory, the configuration necessary for fastlane as well as the fastlane sca command to run the static code analysis (shown in video 1). 
The build plan should also specify an artifact called swiftlint with the result of the SCA (shown in video 2). 
The results displayed on Artemis not only shows the amount of passed test cases but also the amount of static code analysis issues. This is shown on the exercise overview page (screenshot 1 & 2). In the online code editor (for the instructor) the SCA issue is reported in the corresponding line (screenshot 3). 

### Description

I adapted the UI in the exercise creation process to show the checkbox and afterwards the text field. 
I adapted some internal SCA verification for Xcode.
I added a final script task to the build plan for iOS programming exercises to execute the static code analysis. 
I added a new lane for executing swiftlint and saving the result in a predefined file to the existing fastlane configuration. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- TS1 is required!

1. Log in to Artemis as Instructor
2. Navigate to Course Administration
3. Create a new programming exercise
4. Select Swift and Xcode
5. See the SCA checkbox and tick it 
6. See text field and enter value 
7. Finish exercise creation
8. Check build plans (see videos 1 & 2)
9. Check results (screenshots 1-3)
10. Open the online code editor as instructor (click 'edit in editor'-button)
11. Select any .swift file and enter more than one empty line after a { and submit the code. 
12. Wait for the build plan to run 
13. Check that a new issue occurs in the result saying that there are too many empty lines. 

If you want to test the student side regarding the results of the SCS (which will not differ from the instructors side) you need a Mac with a Xcode installation. You need to start the exercise as a student, clone the repository, open it in your local Xcode installation enter one or more SCA issues (see step 11) and push the changes. Afterwards you need to wait for the build plans execution. Last but not least you can see the results as in step 13.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Screenshot 1:
SCA Result_Exercise Overview

Screenshot 2:
SCA_Issue

Screenshot 3:
SCA_Issue_Code Editor

Video 1:
https://user-images.githubusercontent.com/82283581/151281075-4a0f7650-8c34-4e9c-ae1d-5a396d65b421.mov

Video 2:
https://user-images.githubusercontent.com/82283581/151281292-cdc17ae4-6536-4e97-bdde-cd6b887950a1.mov

### CODE REVIEW

**Comment by dveljacic** [comment]
I have tested the instructors' side of this PR manually on TS1 and I believe I found certain issues. 
1. When checking the results on the exercise's page, the template result shows no code issues, even though they exist and are shown when you click on the result (look at the next 2 screenshots).

template_solution

template_issues

2. Template build plan is looking good (compared with provided videos), but there are certain problems with the builds for the solution. As you can see in the next two screenshots, the build for the solution fails after creating the exercise, but also after updating the solution with the `Edit in Editor` button.

no_result

build_failed

I am not the expert, but I noticed that the Solution build plan is missing artifacts shown in the second video (and the Template build plain contains these), so I'm providing the next screenshot in case it helps.

missing_artifacts

What is working as expected is the SCA of the Xcode and these inline warnings when using the Online Code Editor, which can be seen in the following screenshot. ✅ 

file

**Comment by DanielKainz** [comment]
> I have tested the instructors' side of this PR manually on TS1 and I believe I found certain issues.
> 
> 1. When checking the results on the exercise's page, the template result shows no code issues, even though they exist and are shown when you click on the result (look at the next 2 screenshots).
> 
> template_solution
> 
> template_issues
> 
> 2. Template build plan is looking good (compared with provided videos), but there are certain problems with the builds for the solution. As you can see in the next two screenshots, the build for the solution fails after creating the exercise, but also after updating the solution with the `Edit in Editor` button.
> 
> no_result
> 
> build_failed
> 
> I am not the expert, but I noticed that the Solution build plan is missing artifacts shown in the second video (and the Template build plain contains these), so I'm providing the next screenshot in case it helps.
> 
> missing_artifacts
> 
> What is working as expected is the SCA of the Xcode and these inline warnings when using the Online Code Editor, which can be seen in the following screenshot. ✅
> 
> file



Thanks for your review. 🙂

Regarding your first comment:
This should not be related to this PR, since I experienced this issue with other programming languages as well.

Regarding your second comment:
This is also not related to this PR. Since the BuildAgent went offline for some reason, the artifacts could not be there. A rerun should solve the problem.

**Review by akesfeden — COMMENTED** [review]
Code changes look good, I tried following the test steps and I was able to confirm the screenshots, although I am getting an Access Denied error on Bamboo so I couldn't check the build plans. I also don't have a Mac so I couldn't test the with a student. If you know how I can get access to Bamboo I can try to check the build plans too, otherwise I can approve the parts I wrote here.
image

**Review by dveljacic — APPROVED** [review]
Tested on TS1. Everything looks good this time. ✅ 

scac_issues

**Comment by DanielKainz** [comment]
> Code changes look good, I tried following the test steps and I was able to confirm the screenshots, although I am getting an Access Denied error on Bamboo so I couldn't check the build plans. I also don't have a Mac so I couldn't test the with a student. If you know how I can get access to Bamboo I can try to check the build plans too, otherwise I can approve the parts I wrote here.
> 
> image
> 
>  

Thanks for your review. 🙂

Regarding the Build Plans:
You need to make sure to login into Bamboo with the same test user account you used to create the iOS programming exercise on Artemis. Afterwards checking the Build Plan configurations should work. 🙂

Regarding the student side:
No problem. The result does not differ from editing in the online code editor. 🙂

**Review by akesfeden — DISMISSED** [review]
> Regarding the Build Plans:
You need to make sure to login into Bamboo with the same test user account you used to create the iOS programming exercise on Artemis. Afterwards checking the Build Plan configurations should work. 🙂

Thank you for the explanation, I was able to see the build plan script and artifacts with `artemis_test_user_10` on Bamboo. Approved.

**Review by b-fein — APPROVED** [review]
Code changes look good. Nice to see that some special edge-cases could be removed.

A quick grep for xcode over the directory revealed no other places where a special condition for static analysis for this project type is present.

**Review by akesfeden — APPROVED** [review]
Re-approving code after style changes.

**Review by dveljacic — APPROVED** [review]

**Review by dveljacic — APPROVED** [review]
Double-checked on TS1. All good. ✅

**Review by Mtze — APPROVED** [review]
Tested on TS1 - Works as expected

**Pull request merged**
