### PR TITLE
`Communication`: Add icons to conversation options

### PR DESCRIPTION
**Pull request by egekurt123**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Description

This PR adds icons next to the conversation options on the messages page. Icons have been added to the "Settings", "Mute"  and "Hide" options.

The icons have been chosen to visually represent each action, providing users with a clearer and more intuitive interface.

### Steps for Testing

Prerequisites:
- 1 Instructor/Student
- 1 Course with Messaging Enabled

1. Log in to Artemis
2. Navigate to Messages
3. Open the Sidebar
4. Click Conversation-options ("...") of any channel
5. Make sure that the icons appear and everything work as expected

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Screenshots

Screenshot 2024-06-27 at 12 58 09

## Summary by CodeRabbit

- **New Features**
  - Added Font Awesome icons to conversation option buttons for better visual cues (settings, mute, and hide actions).

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code

**Review by asliayk — APPROVED** [review]
code lgtm

**Review by pzdr7 — APPROVED** [review]
Tested on TS1 👍

**Review by laadvo — APPROVED** [review]
Tested on ts1, the icons fit really well!

**Review by Jan-Thurner — APPROVED** [review]
tested on TS3. The new Icons look great. 👍

**Pull request merged**
