### PR TITLE
Feature/update apollon

### LINKED ISSUE #1538: No UML Class Properties shown in Artemis
### Describe the bug
When I open up fullscreen in a modeling exercise, I can't open up the dialog for changing a class's properties.

#### To Reproduce

1. Go to https://artemis.ase.in.tum.de/#/courses/48/modeling-exercises/1250/participate/352939
2. Click on Fullscreen
3. Doubleclick on a class object
4. No properties displayed

#### Expected behavior
Properties displayed (the second screenshot).

#### Screenshots

image
image

### Environment

<details><pre>
Windows 10
image

Chrome
Version 83.0.4103.61 (Offizieller Build) (64-Bit)
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

### PR DESCRIPTION
**Pull request by TobiasPr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

Fixes #1538 
Brings better usability for interfaces in component and deployment diagrams:
- if two required interface are on the opposite sides of the same target, they are not represented as full half circles
- for required interfaces the connection line is not drawn through the marker anymore
- interfaces have different ports to connect to (non overlapping)

Fixes two bugs in element popups (object diagram class, class diagram class and communication link relationship):
- focus is correctly set when moving with the mouse
- when editing e.g. an existing attributes in a class of a class diagram and pressing enter after changing, it happened that the content of the diagram diverged from the popup (diagram displaying the correct value, popup the old one)

#### Popups in fullscreen mode
1. Create a modeling exercise
2. Participate in modeling exercise
3. Activate fullscreen
4. Open popup on element (double click on element)
5. Popup is displayed

#### Usability for interfaces
1. Create 2 modeling exercises, deployment diagram and component diagram (you can also use "Tobis Test Course")
2. Create interfaces, check out the new components for connecting interfaces.
3. think about improvements and let me know :)
4. add two required interfaces on opposite sites to an interface
5. check if interfaces are drawn correctly (not full half circles)

#### Bugs in popup
1. Create 3 modeling exercises, class diagram, object diagram and communication diagram
2. add attributes and methods to the classes, objects and messages to communication link relationships
3. change added objects, click either enter, tab, or escape or use mouse to set focus to other objects
4. elements in diagram and popup are the same (same name)
5. focus behaves as you would espect
6. perform some random flows of actions in the diagram and see if you encounter unexpected behavior (known issue, when deleting communication link messages, popup content diverges from displayed values - see https://github.com/ls1intum/Apollon/issues/106)

### Screenshots

No popups in fullscreen
image

Usability interfaces
usability_interfaces

### CODE REVIEW

**Comment by TobiasPr** [comment]
> I've tested the new Apollon editor on the test server and found some issues:
> 
> **Popups in fullscreen mode**
> This works as described but I found an additional issue: when one drags an element from the element list on the right side to the modeling area the dragged element follows the cursor. In fullscreen mode you can also move elements there but they don't follow the cursor and they will just appear at the place where you dropped them.
> 
> **Usability for interfaces**
> I wasn't able to produce the new interfaces as shown in the screenshots. I tried it by connecting the interface with a component or node and the other way around. I always get full circles:
> 
> image
> 
> There is also some deviation in the behavior between deployment and component diagrams. While the relationship will be attached to the vertical center of the interface in component diagrams the relationship will be attached to the bottom in deployment diagrams:
> 
> image
> 
> **Bugs in popup**
> 
> This works as expected. Really nice to see that the enter button now behaves naturally!

Thank you for the precise testing. Here some comments on the issues you found:

Fullscreen mode: I will update to include that to include the dragging overlay also in the apollon-editor

Usability for Interfaces: 
- You need to dbl click on a relationship and change the type to required interface (then the half circle will appear at the end of that relationship). 
- The other issue, is a current limiation in apollon. Basically the default relationship does not match "Provided Interface" in Deployment Diagrams (which would be required here for proper layouting), because there is one default per diagram and it does not take into account if the components which should be connected supports that relationship type. I agree that this is not very userfriendly, especially because the relationship types look visually the same. I will address this in a separate issue in Apollon.

**Comment by alexmardale** [comment]
Still testing, but came across the following:
In a diagram, if you're at the top of the page and drag an element from the right, everything is ok. But if you scroll down and then drag an element from the right, the element is shifted from your cursor with about the same amount you scrolled. When you release the mouse click the element it is correctly positioned at the location of the cursor.

**Comment by alexmardale** [comment]
The same happens for the popups on elements:

**Comment by TobiasPr** [comment]
thank you for testing, I will fix the issue

**Comment by alexmardale** [comment]
**Popups in fullscreen mode**
Worked as expected

**Usability for interfaces**
Worked as expected

**Bugs in popup**
Just some notes:
Tabbing through attributes/methods doesn't stop on the new field; if you press enter/escape on the new field while it is still empty the focus doesn't go to the next field, but if you press tab the focus does actually go further.
Tabbing through existing elements (attributes/methods/messages) selects the entire field instead of putting the cursor at the end.
But otherwise worked as expected!

**Comment by TobiasPr** [comment]
the scrolling issue is fixed -> popups and ragged elements are at the right positions, independent of window scrolling

**Comment by TobiasPr** [comment]
> **Popups in fullscreen mode**
> Working, issue found by Sascha is fixed.
> 
> **Usability for interfaces**
> Working as intended however since this only applied when having three required interfaces this means that you still have the issue with two required interfaces.
> It's not a big deal but as you can see in the screenshot the required interface intersects the line from the provided interface (right):
> [Screenshot from Gyazo](https://gyazo.com/4e0ae002b082c7bb0940d20cab238a9e)
> 
> **Bugs in popup**
> The issue with the communication diagram still persists:
> [Screenshot from Gyazo](https://gyazo.com/0b7f0521bfcc0e1f1d4339db0912e929)
> 
> **Drag and Drop misbehaves on Scroll**
> Issue found by Alex is fixed

Usability issue: I could change that, but it is not what I discussed with @krusche 
Bugs in popup: Out of scope, that's why I created a separate ticket for that, see https://github.com/ls1intum/Apollon/issues/106

**Comment by Alexanderkrp** [comment]
Everything worked for me as well! 👍  

I have one suggestions: 

image

is it possible for 3 or 4 required interfaces to keep the ones across to each other like they are and add an extra space to the other so that it looks like this? 

image

**Comment by TobiasPr** [comment]
> Everything worked for me as well! 
> 
> I have one suggestions:
> 
> image
> 
> is it possible for 3 or 4 required interfaces to keep the ones across to each other like they are and add an extra space to the other so that it looks like this?
> 
> image

I opened another bug for this in apollon, since it was also requested by @julian-christl

**Comment by TobiasPr** [comment]
> **Popups in fullscreen mode**
> Popups do show up correctly in full screen mode 
> 
> **Usability for interfaces**
> I faced a minor GUI issue on Chrome with the Interface Element.
> interface
> 
> **Bugs in popup**
> Works as expected

Could you change the relationship types from association to provided interface? That should do the trick. Belongs to this issue: https://github.com/ls1intum/Apollon/issues/109

**Pull request merged**
