### PR TITLE
`Lectures`: Fix an issue when saving lecture units in guided mode without linked competency

### PR DESCRIPTION
**Pull request by florian-glombik**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

### Motivation and Context
Found the bug when working on [Lectures: Add status bar to lecture creation and edit mode #9655](https://github.com/ls1intum/Artemis/pull/9655/files). 
If Lecture Units are created within the guided mode and no competency is linked, the server throws an internal server error.

### Description
This PR allows the creation of a lecture unit without linking it to a competency.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Create a lecture unit in guided mode
2. Try to add a lecture unit (e.g. text lecture unit) without defining a linked competency
3. Verify no error is thrown

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Bug
bugLectureUnitWithoutCompetency

#### With the Bugfix
lectureUnitWithoutCompetencyBug-fixed

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]
Code :+1:

**Review by az108 — APPROVED** [review]
Tested on Ts1, no issues were found

image

**Review by sachmii — APPROVED** [review]
Tested on TS1, no error was thrown.

**Review by HawKhiem — APPROVED** [review]
Tested on TS3. No error was thrown when creating a new unit

**Pull request merged**
