### PR TITLE
`Exam mode`: Update cache logic of the exam live statistics

### PR DESCRIPTION
**Pull request by Dominik-Weinzierl**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.

### Motivation and Context

During local extensive testing with more than 10000 actions (per single student) I noticed that some actions are not saved in the cache. The reason is that the write operation for each student was not properly locked. So if a student performs several actions in less than a second, there is a possibility that the actions are not saved.

### Description

To avoid locking the entire exam cache, I added an additional method that locks only the exam activities and not the entire exam. Therefore, we can insert multiple actions from different users without locking.

### Steps for Testing

Prerequisites:
- 1 Instructor
- Multiple Students
- 1 Exam with Exam Live Statistics enabled

1. Log in to Artemis
2. Create an Exam with Exam Live Statistics enabled
3. Register multiple Students
4. Participate with those students
5. View the Exam Live Statistics as instructor during the Exam
6. Reload the page
8. Verify that the provided information are correct and the old actions are also loaded

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Code looks good. The locking should work

**Review by TheTrueVester — APPROVED** [review]
Tested on ts1 during testing session. Everything worked as expected.

**Review by xlieA — APPROVED** [review]
Tested during testing session. Works as described.

**Review by mallgaier — APPROVED** [review]
Tested on TS1, works as expected. Good job 👍

**Review by nairaarnez — APPROVED** [review]
Tested in ts1, works as described!

**Pull request merged**
