### PR TITLE
[Chore] Changing score to the correct noun: points

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

There is a naming problem in our codebase. The **max_score** in an exercise represents the absolute number of points a student can achieve in the exercise and the **score** in result means the relative percentage of all points a student achieved. **This double meaning of score is confusing**

### Description

* Rename exercise.max_score into points (database, server, client)
* Rename quiz_question.score into points (database, server, client)
* Check other places like translation strings that the correct word "points" is used when it concerns points and not score
* Check that in all assessment screens the entry in feedback is changed from score to points **(make it clear to tutors that they are awarding points)** 
IMPORTANT: **To not break anything in the codebase the changes in the code itself are kept to the minimum such that everything still works. I know that there are still a lot of places left in the code where maxScore or score is used but changing all this would break the scope of this PR dramatically**

### Steps for Testing

**There is not really much to check here except that everywhere where the meaning is points it should be written points and not score**

In particular check all the manual assessment views

### Test Coverage

**No changes in test coverage**

### Screenshots

programing assesment
quizPoints
text

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts1, looks good wrt. the new noun.

**Review by EneaGore — APPROVED** [review]

**Review by marvinchimeka — APPROVED** [review]
Tested with @simonzilker. No issues found

**Review by simonzilker — APPROVED** [review]
Looks good :)

**Review by valeriebucher — APPROVED** [review]

**Review by krusche — APPROVED** [review]
code looks good

**Pull request merged**
