### PR TITLE
`Programming exercises`: Fix diff view for renamed files

### PR DESCRIPTION
**Pull request by pzdr7**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

During the review of #8540, I noticed that renaming files wasn't working as expected when viewing commit details. This had two causes:

- Renamed files that had no diff blocks were not mentioned in the generated diff report.
- For renamed and modified files, the wrong "before" content was shown (we used the updated file path)

### Description

- We now explicitly track the renamed files in the server and add corresponding diff entries if needed
- We now use the correct file content when displaying renamed & modified files.
- For renamed and otherwise unchanged files, we now display a placeholder

When processing the diff, we now keep track of entries like this:
```
diff --git a/src/de/tum/cit/ase/Client2.java b/src/de/tum/cit/ase/Client23.java
similarity index 98%
rename from src/de/tum/cit/ase/Client2.java
rename to src/de/tum/cit/ase/Client23.java
```

### Steps for Testing

Prerequisites:
- Test Server with LocalVC enabled
- 1 Student
- 1 Programming exercise (clone the repository; it'll be easier to verify that this feature works correctly)

1. Log in and navigate to the programming exercise
2. Clone the repository
3. Take a file and change 1-2 lines, then rename the file. (**Note**: it's important that you do not change too many lines; otherwise, git will not be able to track the rename. If you're unsure: you should get something like `rename src/de/tum/cit/ase/{WillRename.java => HaveRenamed.java} (82%)` when committing using the command line)
4. Commit your changes.
5. Rename the file again, this time without changing its content.
6. Commit your changes.
7. Make some other changes, e.g. delete / create / modify some files.
8. Commit your changes.
9. Push your changes.
10. On Artemis, click "Open repository," then open the commit history.
11. Verify for each commit that your changes were tracked and are displayed correctly.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [git-diff-file.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6613/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/hestia/git-diff-report/git-diff-file.component.ts.html) | 100% | ✅ |
| [git-diff-report.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6613/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/hestia/git-diff-report/git-diff-report.component.ts.html) | 100% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [GitDiffReportParserService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6613/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/GitDiffReportParserService.html) | 86% | ✅ |

### Screenshots

image
image

### CODE REVIEW

**Review by Jan-Thurner — APPROVED** [review]
Tested on TS1, works great.
Code also looking good

**Review by JohannesWt — APPROVED** [review]
Code LGTM 👍

**Review by coolchock — APPROVED** [review]
tested on ts1, LGTM. Differences are displayed correctly. `DELETED`, `CREATED` and `RENAMED` labels are also displayed for affected files. Files which were only renamed are included in the diff 👍

**Review by florian-glombik — APPROVED** [review]
Followed the testing steps on ts1, worked as described - all commits and respective changes are displayed, the files are labeled properly
<details>
<summary>Second Test logs</summary>

```
florianglombik@MBP-von-Florian ge25bastestcoursevisbilitytest-ge25bas % git add .
florianglombik@MBP-von-Florian ge25bastestcoursevisbilitytest-ge25bas % git commit -m "step 3"
[main 09e74b5] step 3
 1 file changed, 1 insertion(+), 1 deletion(-)
 rename src/in/tum/test/{BubbleSort.java => BubbleSortChangeLineAndFileName.java} (83%)
florianglombik@MBP-von-Florian ge25bastestcoursevisbilitytest-ge25bas % git add .
florianglombik@MBP-von-Florian ge25bastestcoursevisbilitytest-ge25bas % git commit -m "step 5"
[main 9fe3542] step 5
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename src/in/tum/test/{BubbleSortChangeLineAndFileName.java => BubbleSort1234.java} (100%)
florianglombik@MBP-von-Florian ge25bastestcoursevisbilitytest-ge25bas % git add .
florianglombik@MBP-von-Florian ge25bastestcoursevisbilitytest-ge25bas % git commit -m "step 8"
[main 492c396] step 8
 3 files changed, 23 insertions(+), 1 deletion(-)
 create mode 100644 src/in/tum/test/MergeSort1.java
 create mode 100644 src/in/tum/test/NewMergeSort.java
florianglombik@MBP-von-Florian ge25bastestcoursevisbilitytest-ge25bas % git push
Enumerating objects: 28, done.
Counting objects: 100% (28/28), done.
Delta compression using up to 10 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (22/22), 1.79 KiB | 1.79 MiB/s, done.
Total 22 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5)
remote: Updating references: 100% (1/1)
```
</details>


~I might have found another issue in my first testing attempt, it might not be directly related since I had some conflict with the code editor that I've noticed in the last testing step.~

As I didn't review the code I do not know if it is related to the changed: `MergeSort2` and `MergeSort3` are created and not renamed (see logs below)

image


<details>
<summary>Screenshots and further information</summary>


image
Commit that is not displayed properly https://artemis-test1.artemis.cit.tum.de/courses/12/exercises/72/repository/199/commit-history/4f239016dc8e2d181c823787b1a5c1a024f6a164

Repository https://artemis-test1.artemis.cit.tum.de/courses/12/exercises/72/repository/199

</details>

<details>
<summary>First Test logs</summary>

```
florianglombik@MBP-von-Florian ge25bastestcoursecheckoutdirectoriesjava-ge25bas % git add .
florianglombik@MBP-von-Florian ge25bastestcoursecheckoutdirectoriesjava-ge25bas % git commit -m "renamed file"
[main d241c0e] renamed file
 1 file changed, 2 insertions(+), 2 deletions(-)
 rename src/packageName/{BubbleSort.java => AmazingBubbleSort.java} (81%)
florianglombik@MBP-von-Florian ge25bastestcoursecheckoutdirectoriesjava-ge25bas % git add .
florianglombik@MBP-von-Florian ge25bastestcoursecheckoutdirectoriesjava-ge25bas % git commit -m "rename the file a second time"
[main b9b8684] rename the file a second time
 1 file changed, 0 insertions(+), 0 deletions(-)
 rename src/packageName/{AmazingBubbleSort.java => AmazingButNotIncredibleBubbleSort.java} (100%)
florianglombik@MBP-von-Florian ge25bastestcoursecheckoutdirectoriesjava-ge25bas % git add .
florianglombik@MBP-von-Florian ge25bastestcoursecheckoutdirectoriesjava-ge25bas % git add .
florianglombik@MBP-von-Florian ge25bastestcoursecheckoutdirectoriesjava-ge25bas % git commit -m "adding, deleting and modifying files"
[main 4f23901] adding, deleting and modifying files
 4 files changed, 40 insertions(+), 3 deletions(-)
 rename src/packageName/{MergeSort.java => MergeSort1.java} (75%)
 create mode 100644 src/packageName/MergeSort2.java
 create mode 100644 src/packageName/MergeSort3.java
florianglombik@MBP-von-Florian ge25bastestcoursecheckoutdirectoriesjava-ge25bas % git push
Enumerating objects: 21, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 10 threads
Compressing objects: 100% (14/14), done.
Writing objects: 100% (17/17), 1.54 KiB | 1.54 MiB/s, done.
Total 17 (delta 8), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (8/8)
remote: Updating references: 100% (1/1)
To https://artemis-test1.artemis.cit.tum.de/git/GE25BASTESTCOURSECHECKOUTDIRECTORIESJAVA/ge25bastestcoursecheckoutdirectoriesjava-ge25bas.git
   fae4ba0..4f23901  main -> main
```
</details>

**Comment by florian-glombik** [comment]
I investigated how to reproduce it:

1. Copy the MergeSort template file and name the new File and Class `MergeSort1`
2. Copy the MergeSort template file and name the new File and Class `MergeSort2`
3. Copy the MergeSort template file and name the new File and Class `MergeSort3`
4. Delete the the MergeSort template file
5. See that all MergeSorts are displayed as `renamed` even though git labels `MergeSort2` and `MergeSort3` with `created`

**Comment by pzdr7** [comment]
@florian-glombik Good catch! Basically, the copy detection of Git is producing diff entries that the Client interprets as renaming. At the moment, we cannot distinguish between copying and moving.

 @krusche and I have discussed this and decided that we'll handle it in in a separate PR (we may be able to add some transient fields to the diff report or the diff enteries that carry this information)

**Review by rabeatwork — APPROVED** [review]
Maintainer approved

**Pull request merged**
