### PR TITLE
`Development`: Fix a flaky test case in the ExamIntegrationTest

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

Fixes flaky test

### Description

Adds necessary await. Fixes most common bug causing `400` status due to `Max points for the grading scale must be set to a value greater than 0`. Reduces number of minor (less than 1% test runs)  `500` status due to SQL delete error.

### Steps for Testing

1. Compile and run the `de.tum.in.www1.artemis.exam.ExamIntegrationTest.testGetExamScore` test.
2. Verify that it passes.
3. Run the test multiple times and confirm that `400` error from description does not occur.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by danielbode — APPROVED** [review]
Code looks good to me. I also wasn't able to reproduce a failing test on my machine anymore.

**Review by DominikRemo — APPROVED** [review]
Code LGTM. Tested locally 25 times and did not fail once.

**Review by terlan98 — APPROVED** [review]
Tested 10 times locally and got a `500` on one of them. Since this PR focuses on `400` errors, I approve.

**Review by simon-hng — APPROVED** [review]
Run 100 times and got not issues

**Review by rriyaldhi — APPROVED** [review]
tested locally 100 times. runs successfully

**Pull request merged**
