### PR TITLE
`Text exercises`: Allow text assessment when adblocker is running on browser 

### LINKED ISSUE #4989: Adblocker extension blocks text assessment API endpoint
### Describe the Issue

Almost everyone is using an adblocker nowadays.
When assessing a text exercise, the adblocker extension blocks our client request to `/api/analytics`.
However, the error message is rather not descriptive, and you have to look into the console to see that the request was blocked (and the server is actually reachable just fine).

### To Reproduce

1. Login to Artemis as Instructor with Adblocker extension
2. Go to the Assessment of a Text Exercise
3. Try to assess the text exercise
4. See the error

### Expected behavior

The request should not be blocked, we could rename the API endpoint for better user experience.

### Screenshots

Screenshot 2022-04-28 at 21 58 32

### What browsers are you seeing the problem on?

Firefox with uBlock Origin extension

### Additional context

_Originally posted by @ge65cer in https://github.com/ls1intum/Artemis/issues/4987#issuecomment-1112602817_

### PR DESCRIPTION
**Pull request by pellumbbaboci**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Fixes #4989 issue.
### Description

In this PR I changed resource name from ```api/analytics/``` to ```/api/event-insights/``` and therefore adblocker does not block text assessment API endpoint.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Text Exercise

1. Log in to Artemis as student
2. Navigate to text exercise and submit your solution
3. Then log in as instructor with adblocker extension
4. Navigate to assessment of the text exercise
5. Try to asses the exercise, it should asses without error

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Changed files: 
``` src/test/java/de/tum/in/www1/artemis/TextExerciseAnalyticsIntegrationTest.java ```
``` src/test/javascript/spec/service/text-assessment-analytics.service.spec.ts ```
``` src/test/javascript/spec/service/text-assessment.service.spec.ts ```

### CODE REVIEW

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
When I search for the String "/analytics/" in IntelliJ, I find 16 occurrences. Why did you not include the others?

**Comment by pellumbbaboci** [comment]
> When I search for the String "/analytics/" in IntelliJ, I find 16 occurrences. Why did you not include the others?

@JohannesStoehr I changed the api and api calls, but there are "/analytics/" strings across project because there are imports of analytics service and its imported as below: 
```import { TextAssessmentAnalytics } from 'app/exercises/text/assess/analytics/text-assesment-analytics.service';```

And after my changes, I only find 9 occurrences in the project. Can you maybe upload a screenshot of occurrences?

**Review by ge65cer — APPROVED** [review]
Tested on TS1, my ad blocker is okay with the new URL. 🙂

**Comment by JohannesStoehr** [comment]
> And after my changes, I only find 9 occurrences in the project. Can you maybe upload a screenshot of occurrences?

You're right, sorry. Seams that I hallucinated some more...
But maybe we should also rename the import paths in the same way as the rest URLs, what's your opinion on that?

**Comment by pellumbbaboci** [comment]
> > And after my changes, I only find 9 occurrences in the project. Can you maybe upload a screenshot of occurrences?
> 
> You're right, sorry. Seams that I hallucinated some more... But maybe we should also rename the import paths in the same way as the rest URLs, what's your opinion on that?

Okay, I thought about that and at the beginning i started renaming but, this leads to a lot of change like function names and variable names in backend as well as in frontend. There is a possibility that in the future adblocker might block also ```insights``` keyword inside the rest URLs, and therefore this will make maintenance difficult in the future so i renamed only the necessary places.

Changing everything does not make much sense to me because this api still does analytics so in my opinion we shouldn't. @JohannesStoehr  What do you think?

**Review by stefanwaldhauser — APPROVED** [review]
I like the fix. Ublock now seems to accept it! Nice work!

**Review by JohannesStoehr — APPROVED** [review]
Renaming of REST-Calls looks good to me

**Review by simon-hng — APPROVED** [review]
Code looks good

**Review by manuelmanso — APPROVED** [review]

**Pull request merged**
