### PR TITLE
feat(haskell) upgrade dependencies, add more extensive example, test suite, and readme

### PR DESCRIPTION
**Pull request by kappelmann**
### Motivation and Context

Next semester, Artemis will be used for the TUM functional programming course using Haskell.

### Description

This PR upgrades the Haskell templates to use the most up-to-date dependencies, adds a more extensive example test suite, and adds detailed documentation for the build process and test suite structure.

It also adds build files to the exercise template (and solution folder) so that students can test their code more readily on their local machine.

Finally, it adds a script `setup_exercise.sh` which can be used to easily set up the required folder structure on a local machine.
I was not sure if this is the right place for this file nor if you guys even want to have such files in the repository in general, so let me know if I should remove it. 

### Steps for Testing

I created a test exercise using the proposed environment [here](https://bamboo.ase.in.tum.de/browse/FPV2021TESTEXERCISE-SOLUTION-5) and [here](https://bamboo.ase.in.tum.de/browse/FPV2021TESTEXERCISE-BASE/test).

### CODE REVIEW

**Comment by kappelmann** [comment]
@krusche The automated checkout of the solution repository worked fine. The only problem left is that the scripts testing the solution and students' submissions differ slightly, which needs to be manually adjusted as matters stand. See [here](https://github.com/ls1intum/Artemis/pull/2254/files#diff-b1fdfb98c0898ea10b4a6233cfbea6b3484f290a2a3ae168424aa30598b9aa10R34)

Is there any chance one can provided two different scripts for the solution and students' submissions?
A fallback plan would be that both scripts just execute a bash script contained in the test repository and that script then tries to figure out whether the given submission is the sample solution or a student's submission and sets the flags accordingly.

**Comment by sleiss** [comment]
@kappelmann Why exactly is there a need for two separate scripts? If I understood the basic idea of comparing the solution vs. the student's submission correctly, the tester executes both of them and then compares their behavior, bu t I may be missing something.

I believe the issue would be fixed if the solution uses the same files as the template, only containing the code the student would add (so basically, there should be no difference between the sample solution and a correct student solution).
In this template, the files are named differently: `Exercise.hs` vs `Solution.hs`. If the solution repository would also contain the `Exercise.hs` file, there would be no problem as now the tester can run the same script.

When the solution is tested, it gets checked out in both the `assignment` and `solution` folders, but the tester should not need to know this, as the sample solution behaves just like any student submission.

**Comment by kappelmann** [comment]
> @kappelmann Why exactly is there a need for two separate scripts? If I understood the basic idea of comparing the solution vs. the student's submission correctly, the tester executes both of them and then compares their behavior, but I may be missing something.
> 
> I believe the issue would be fixed if the solution uses the same files as the template, only containing the code the student would add (so basically, there should be no difference between the sample solution and a correct student solution).
> In this template, the files are named differently: `Exercise.hs` vs `Solution.hs`. If the solution repository would also contain the `Exercise.hs` file, there would be no problem as now the tester can run the same script.
> 
> When the solution is tested, it gets checked out in both the `assignment` and `solution` folders, but the tester should not need to know this, as the sample solution behaves just like any student submission.

I vaguely remember that it had something to do with clashing module names in the build process. But I was able to fix that now using a [mixin](https://github.com/ls1intum/Artemis/pull/2254/files#diff-eab222ab0063c0946d7ad08809cbe63f9a5c0f67f974edbefc6b81a461d9e7ceR38). The script issue should be gone then. Thanks for questioning the approach!

**Comment by sleiss** [comment]
@kappelmann Great to hear! For me the changes look fine as far as I can tell, maybe @krusche can comment whether we want to include the shell script.

**Comment by krusche** [comment]
@kappelmann thanks for the contribution. I don't mind having such a file in the git repo. I would merge the changes now and you could easily add a follow-up PR in case something should further be improved.
I will also invite you to the Artemis dev team, so that you can work in the main Artemis repository. Then it would be easier for you and us to test the changes on our test servers.

We will soon document the programming exercises in more detail on our documentation platform https://artemis-platform.readthedocs.io/en/latest/?badge=latest

It would be nice if you could add something about the Haskell template then, so that it would be easier for other instructors to use it.

**Comment by kappelmann** [comment]
> @kappelmann thanks for the contribution. I don't mind having such a file in the git repo. I would merge the changes now and you could easily add a follow-up PR in case something should further be improved.
> I will also invite you to the Artemis dev team, so that you can work in the main Artemis repository. Then it would be easier for you and us to test the changes on our test servers.
> 
> We will soon document the programming exercises in more detail on our documentation platform https://artemis-platform.readthedocs.io/en/latest/?badge=latest
> 
> It would be nice if you could add something about the Haskell template then, so that it would be easier for other instructors to use it.

Sure, let me know when and how we should add to the documentation when time has come.

**Pull request merged**
