### PR TITLE
`Development`: Fix flaky test

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
The test `testGetFinishedBuildJobs_returnsJobs` expects the result to be ordered. However, since the order is based on the build finish time which was the same, the test was flaky, especially on postgres.

### Description
The two builds now have two different timing information, leading to the expected order in the finished build jobs view.

### Steps for Testing
code review, maybe run the test.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### CODE REVIEW

**Review by laadvo — APPROVED** [review]
Code LGTM, the test is passing locally

**Review by b-fein — APPROVED** [review]

**Review by sarpsahinalp — APPROVED** [review]
code lgtm, tests are passing

**Review by SimonEntholzer — COMMENTED** [review]
Before the change the jobTimingInfo for the two buildQueueItems were the same. Now they have time periods which do not overlap any more. Doesn't that kinda change the test semantics? I guess it depends on what we actually want to test. What do we test here?

**Comment by Strohgelaender** [comment]
We test that the endpoint for finished build jobs returns both jobs. There we expected an order (which is based on the build completion date). I don't think that the tests really got changed, but I'll double-check.

**Pull request merged**
