### PR TITLE
`Tutorial groups`: Automatically create messages channel for each tutorial group

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
We want to connect the `Tutorial Group` and `Messages` functionality of Artemis to better support communication among students of a tutorial group and with the tutor. There is no such connection, so everything has to be manually set up and maintained. This means, for example, that each channel for a tutorial group has to be created manually and each registered student added to the corresponding channel, and so on.

This PR introduces automatic tutorial group channel creation and maintenance. If enabled, Artemis will create a dedicated channel for each tutorial group in the ‘Messages’ section of the course. The channel can still be managed manually but Artemis automatically performs some common management tasks. Artemis will automatically add and remove students from the channel when they register or unregister for the tutorial group. The assigned tutor of the tutorial group will be made a moderator of the channel. The channel will be deleted when the tutorial group is deleted. It can not be deleted manually. This option can be changed later at any time.

#### Server

Added new configuration properties to `TutorialGroupsConfiguration`, to allow the instructor to configure the automatic channel creation. 

```
    /**
     * If true, tutorial groups channel will be created for each tutorial group. If false, they will not be created.
     */
    @Column(name = "use_tutorial_group_channels")
    @NotNull
    private Boolean useTutorialGroupChannels;

    /**
     * If true, the created tutorial group channels will be public. If false, they will be private.
     */
    @Column(name = "use_public_tutorial_group_channels")
    @NotNull
    private Boolean usePublicTutorialGroupChannels;
```
If `useTutorialGroupChannels` becomes active, all tutorial group channels will be created and from this point on maintained by Artemis. If it is deactivated, all existing channels will be cleaned up (i.e. deleted) again. Instructors can decide whether the channels are either private or public. This can also be changed at any time. All existing channels will be converted to private or public mode respectively.

A `Tutorial Group` is now optionally connected to a `Channel`. We do NOT send the 'raw' channel entity to the client but the corresponding `ChannelDTO`, which is very small. `FetchType.Eager` is selected here to make the server implementation much easier. Note that everything data heavy in `Channel` is lazily loaded, so there is no performance hit expected here by the use of `eager`.

```
    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "tutorial_group_channel_id")
    @JsonIgnore // we send the DTO as a transient field instead
    private Channel tutorialGroupChannel;
```

There is a new service `TutorialGroupChannelManagementService` which acts as a facade and exposes several methods to maintain the channels connected to the tutorial groups.

#### Client

The client changes can best be seen in the screenshots below. They consist mostly of changes to the corresponding forms and links from the tutorial group to the corresponding channel and vice versa.

### Steps for Testing
- You need a course with communication enabled, otherwise the corresponding UI elements do not show up. So make sure to check the checkbox `Enable communication features` in the course edit/creation form.
- Now having such a course, navigate to `Tutorial Groups` in course management. If it is a new course you should be presented with a `Tutorial Group Checklist` that requests you to create a new tutorial group configuration. If it is an existing course with tutorial groups previously configured, you must edit the existing tutorial group configuration by clicking on the `More...` button on the tutorial group management and clicking `Edit Global Configuration`
- You are presented with a form (see 1. Screenshot) where you can activate the automatic channel management and select that either the channels are public or private. Do this now.
- Now for every existing or new tutorial group a channel will be created if it does not exist yet and connected to the tutorial group. The registered students will be automatically added to the channel and removed if they are deregistered from the group. Same for the assigned tutor who will become the channel moderator and be removed from the channel if unassigned from managing the group.
- You can test this by playing around with registering, and deregistering users and checking the channel in the `Message` tab of the course if the changes are reflected there accordingly.
- Note: Manually managing the channel is still possible, meaning channel moderators can remove users, add users, change the title, and so on.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line |
|------------|-----:|
| TutorialGroupResource.java | 90% |
| TutorialGroupChannelManagementService | 83% | 

### Screenshots
_1. Tutorial Groups Configuration Form_
image
_2. Tutorial Group Channel Column_ 
image
_3. Checkbox to Sync Tutorial Group Title Change to Channel Name_
image
_4. Logged in as an assigned tutor. Link to jump directly to the channel._
image
_5. Logged in as a student. Link to jump directly to channel._
image
image
_6. Links from the channel back to the tutorial group page._
_image_
image
image
_7. Channel deletion warning if option is deactivated._
image

### CODE REVIEW

**Review by tobias-lippert — CHANGES_REQUESTED** [review]
Tested on ts1 using the ChannelTestMo21 course. Changing the visibility of the tutorial group channels in the global config doesn't seem to be applied to the channels. I couldn't change the visibility once I had created the tutorial group and it also didn't change for other groups.

**Comment by stefanwaldhauser** [comment]
> Tested on ts1 using the ChannelTestMo21 course. Changing the visibility of the tutorial group channels in the global config doesn't seem to be applied to the channels. I couldn't change the visibility once I had created the tutorial group and it also didn't change for other groups.

I am a little bit confused because it worked perfectly fine for me? 
Here it is a private channel:
image
Now I change the config to public 
image
Now it is public
image

**Review by LiaLism — APPROVED** [review]
Everything works as expected. Tested on ts0.

**Review by tobias-lippert — APPROVED** [review]
Tested again on ts1. Editing the visibility of the channels works as expected.

**Review by luisa1999 — APPROVED** [review]
Looks good to me

**Pull request merged**
