### PR TITLE
`General`: Increase interactivity of student statistics charts

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

This PR increases the interactivity of following charts on the statistics tab:

- The horizontal bar charts grouped by exercise types
- the performance in exercises line chart at the end of the page

### Description

This PR includes the following changes:

- The formatting of the tooltips in the line chart changed minorly: When hovering over a certain point, the size difference between exercise title and displayed score is decreased.
- There was a small bug for the tooltips in the horizontal bar charts. For missing points, they always displayed the value 0 but the correct missing relative part (see screenshot below)
- The performance in exercises line chart is now completely translation sensitive. Currently, if the user changes the language, only parts of the chart were translated directly, the user had to reload the page once in order to get a full translation.
- A new filter allows the user to select the entries in the line chart according to their exercise type
- The horizontal bars are now clickable and delegate the user to the corresponding exercise detail page
- A new filter allows the user to filter the exercises in both the horizontal bar charts and the line chart according to their category.

### Steps for Testing

Prerequisites:
- 1 Student
- For each exercise type:
    - This set once for exercises included in score and optional exercises:
        - 1 exercise with no category
        - 1 exercise with a unique category ( i.e. only 1 exercise included in score and optional has this category) 
        - 1 exercise with an arbitrary category (e.g. 'category 1') (one exercise included in score and one optional exercise can share this category)
        - 1 exercise with another arbitrary category (e.g. 'category 2') (one exercise included in score and one optional exercise can share this category)
        - 1 exercise that has both categories
**Important**: In order to be displayed in the performance in exercises chart, every exercise needs a release date and either a due date or an assessment due date in the past

1. Log in to Artemis
2. Navigate to the statistics tab
3. Check the performance in exercises line chart:
    - The filter contains every exercise type (to be more specific, it contains only every exercise type that would normally be displayed in the chart)
    - The translations are appropriate in English and German
    - Changing the translation changes the language within the chart at every spot (especially x and y-axis labels, the exercise types in the series tooltips and the chart legend)
    - When deselecting an exercise type, all corresponding exercises disappear -> re-selecting -> re-appear
    - The number in the filter button changes according to the number of selected exercise types
    - If no exercise type is selected, the filter button turns from green to grey
    - (If no exercise type is displayed in the chart, the filter button is not visible)
4. Check the horizontal bar charts:
    - In the chart tooltip, the missing absolute points / test cases are displayed now
    - When clicking on a bar, you are delegated to the corresponding exercise detail page
 5. Check the filter at the top of the page next to the refresh button:
    - The first filter option is the "hide optional" option (this was available before, I only moved the checkbox into the dropdown menu)
    - Every category of non-optional course exercises is shown in the filter
    - The translations are appropriate in English and German
    - As per default the optional exercises are hidden, they should not appear in the bar charts and the line chart
    - If deselecting a single category, all exercises that only have this category disappear in the bar charts and the line chart -> re-selecting -> re-appear
    - **Important**: The filter is designed to be non-exclusive, as exercises could have multiple categories. This means an exercise is displayed if at least one of its categories is selected.
    - The number in the filter button changes according to the number of selected filter options
    - If deselecting all categories the exercise(s) with multipe categories has, the exercise(s) disappear in the charts -> re-select one category -> exercise re-appear
    - Deselecting "Exercise with no categories" hides all exercises with no categories in the charts -> re-selecting -> re-appear
    - Deselecting at least one category unticks "Select all options"
    - Deselecting categories has impact on the filter for the performance in exercises line chart:
        - If an exercise type is excluded by the filter setting, it disappears from the filter options for the line chart
    - Deselecting "Select all options" deselects all categories and no exercise is shown in the charts
        - If "Hide optional" is deselected as well, the filter button turns from green to grey
    - Selecting all categories manually ticks "Select all options" as soon as all categories are selected
    - If deselecting "Hide optional", optional exercises appear in the charts and the category filter is updated:
        - categories only assigned to optional exercises are added to the filter list
    - Selecting/ deselecting "Hide optional" resets the category filter and the charts accordingly
    - After deselecting "Hide optional", further category filtering should work accordingly.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

exercise-scores-chart.component.ts: 77.77% | 98.16% 
course-statistics.component.ts: 85.93% | 96.56 %

### Screenshots

The tooltip bug I was referring to above. The relative value is correct, but the absolute value is obviously wrong:
image

The current navigation bar:
image

When changing the language, the line chart was translated only partially:
image

New filter setting for both chart types:
image

New filter setting for line chart (+ chart is now completely translated):
image

When clicking on a horizontal bar, you are delegated to the corresponding exercise detail page:

https://user-images.githubusercontent.com/80622272/149528297-c03791f9-3cb8-4f61-a06c-09621982b988.mp4

### CODE REVIEW

**Review by dveljacic — APPROVED** [review]
First I would like to say Kudos on these detailed steps for testing. This really helped a lot and I believe it increases the testing quality. 
Secondly, Kudos on the implementation, cause I didn't find anything wrong while testing it on the TS1. Everything seems to be exactly like you described. 👍

**Review by b-fein — APPROVED** [review]
The code looks good. :+1: 

I have one question, tough. This is the last frame of your demonstration video:
149528297-c03791f9-3cb8-4f61-a06c-09621982b988

It looks like the scores are >100% and are overlapping the text to the right. At first and when clicking on a bar for the first time and going back they are shown correctly. Only when going back the seconds time the bars get longer.
Does the video represent the current state or has this bug already been fixed?

**Comment by willergeorg** [comment]
> The code looks good. 👍
> 
> I have one question, tough. This is the last frame of your demonstration video: 149528297-c03791f9-3cb8-4f61-a06c-09621982b988
> 
> It looks like the scores are >100 (% ?) and are overlapping the text to the right. At first and when clicking on a bar for the first time and going back they are shown correctly. Only when going back the seconds time the bars get longer. Does the video represent the current state or has this bug already been fixed?

Thanks for pointing that out. This has something to do with the animations of the chart. The framework tries to fit the chart to the parent container dimensions and there is some delay (you should observe comparable overlapping when reducing the screen width). The demonstration suggests that the charts stay in this distorted occurrence, which is not the case in reality, as I have stopped the video before the chart bars align again. We could fix this by disabling the animations of the charts, this would not be a problem at all. I personally prefer keeping the animations and dealing with this little realignments as it makes the chart a lot smother if screen dimensions change in my opinion. And additionally, the user gets visual feedback when applying a filter. But I would like to hear your opinion on this.

**Comment by b-fein** [comment]
> […] The demonstration suggests that the charts stay in this distorted occurrence, which is not the case in reality, as I have stopped the video before the chart bars align again. […]

Okay, in that case it’s not an issue at all and the animations can of course remain as they are.

**Review by VinnavanSembian — APPROVED** [review]
tested on ts1. This works as expected!

**Review by mallgaier — APPROVED** [review]
Tested together with @lBruchmann , @Strohgelaender , @VinnavanSembian and @willergeorg .
The implementation and the filters work as expected.

**Review by Strohgelaender — APPROVED** [review]
Tested on TS1, the new functionality works as described.

**Review by lBruchmann — APPROVED** [review]
Tested together on ts1. Tested during testing session. @VinnavanSembian , @Strohgelaender, and @mallgaier. The interactivity looks good to me.

**Review by filip-gregurevic — APPROVED** [review]
Changes look good to me. Nice work 🚀

**Pull request merged**
