### PR TITLE
Add a missing translation for invalid modeling assessments

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
Fixes the missing translation seen in #2494. #2529 only fixed the issue causing the error with the missing translation to show up.

### Description
The referenced translation simply didn't exist. I fixed the path and added translations.

### Steps for Testing
Actually, since #2529 I don't know how to give a field an invalid amount of credits (it always gets reset to 0), so I changed some things locally to check the translation. Otherwise the testing steps would be the same as in #2494. (If you managed to specify an invalid amount of credits the proper message will show up instead of "translation not found".)

### CODE REVIEW

**Review by tiffca — APPROVED** [review]
I followed the steps in 2494 and the functionality works fine. I can save a sample assessment (with 0 points, tried other points as well) in English/German without errors. Tested on ts3.

**Review by JohannesWeiss — APPROVED** [review]
Tested with @marvinchimeka on ts3, works as intended. Tested different combinations of assessments and none did trigger an error.

**Review by marvinchimeka — APPROVED** [review]
Tested in a testing session on ts3. Worked as intended. The translation not found exception has not been thrown anymore.

**Review by airelawaleria — APPROVED** [review]
Works good

**Review by simonzilker — APPROVED** [review]
Tested with @airelawaleria. Approve :)

**Review by philgabr — APPROVED** [review]
Works as intended.

**Review by valeriebucher — APPROVED** [review]
Works good!

**Review by fde312 — APPROVED** [review]
Code looks good to me. Thanks for adding the translation! 👍

**Review by DenizShabani — APPROVED** [review]
Works as intended!

**Pull request merged**
