### PR TITLE
`Development`: Fix flaky playwright tests and define custom parallelism rules and timeouts

### PR DESCRIPTION
**Pull request by muradium**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Some Playwright tests are flaky and in general, test suites may fail during heavy loads on CI servers because of builds taking longer. We want to make E2E tests more stable.

### Description
This PR fixes the known flaky tests. It also sets custom timeouts and turns off parallel execution of tests in a single file for tests in Exam module and Programming exercises

### Steps for Testing
- **Code Review**: Ensure that tests pass for valid reasons, functionality is adequately tested and check the code quality.
- **Run the tests**: Tests are checked by automatic run in CI environment. You can also run them locally and check if they pass.

**Steps for running the tests locally:**
1. Navigate to **src/tests/playwright**
2. Configure Playwright using playwright.env file based on your local setup. Current configuration should work for default Artemis setup.
3. Run `npm install && npm run playwright:setup && npm run playwright:test` to run all tests

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
  - Introduced new method for changing exam working time to allow exam duration adjustments.

- **Bug Fixes**
  - Corrected exam end time handling and time left calculations to improve exam participation logic.

- **Tests**
  - Configured test timeout settings and mode for various exam and exercise test suites to enhance test reliability and execution consistency.
  - Refined test suite logic, including the usage of `await` for asynchronous operations and visibility checks, improving test accuracy.

- **Refactor**
  - Improved the readability and structure of the `shouldShowExerciseTitle` method in the exercise result page without altering core functionality.

- **Data Adjustments**
  - Updated exam and exercise statistics, including points, grades, and grade distribution data for more accurate performance metrics.

### CODE REVIEW

**Review by krusche — CHANGES_REQUESTED** [review]
Do we really need so long timeouts? This can increase test execution quite significantly, especially if tests with long timeouts are retried several times. 

This is not a good solution in my opinion! Timeouts should be as small as possible!

**Comment by muradium** [comment]
> Do we really need so long timeouts? This can increase test execution quite significantly, especially if tests with long timeouts are retried several times.
> 
> This is not a good solution in my opinion! Timeouts should be as small as possible!

The specified custom timeouts are safe upper bounds for the corresponding test files. For the rest of the tests - the idea is to decrease general timeout on single node configuration from `360 seconds` to `120 seconds` and on multi node to `240 seconds`. Do you think it is still too much?

We can further adjust timeouts of very short tests to amounts like 30 seconds or lower, but it is not a common practice to set individual timeouts for every test case. Also, because of parallel execution, test times may vary based on which tests were executed at the same time and how much the server was loaded. Not saying there are no room for improvements, but I think it'd be good to be on a bit safer side with timeouts. After we see that the whole setup is stable, we can experiment with decreasing timeouts more.

**Comment by krusche** [comment]
The problem with such long timeouts is that they significantly extend the test execution when tests fail. The default timeout should be below 10s and only in case it's justified, the timeout can be increased (e.g. for exercises involving builds), but should not be 3min, because if a test fails due to a stupid mistake, this would lead to 2x3min, which is way too much.

Again, we cannot block our whole build infrastructure by waiting hours for potentially failing tests! Developers want fast feedback if they broke something. The whole idea of testing does not make sense, if you need to wait so long!

The previous Cypress tests never had such long execution times

**Comment by muradium** [comment]
I will set custom timeouts then for each test suite with minimal upper bounds (with only a few seconds extra)

**Comment by muradium** [comment]
@krusche Do you have a chance to check again the latest changes? It solves e2e test instabilities by annotating all tests that are dealing with builds as slow, and the rest as fast. Slow tests run sequentially, so the execution times are consistent. Fast tests run in parallel. Also timeouts are unique to each test.

**Pull request closed without merging**
