### PR TITLE
`Development`: Add exam statistics e2e tests

### PR DESCRIPTION
**Pull request by muradium**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Exam statistics page needs to be tested.

### Description
Adds an E2E test in Playwright for checking exam statistics as an Instructor after students have participated in an exam.

### Steps for Testing
- **Code Review**: Ensure that tests pass for valid reasons, functionality is adequately tested and check the code quality.
- **Run the tests (optional)**: Tests are checked by automatic run in CI environment. You can optionally run them locally and check if they pass.

**Steps for running the tests:**
1. Navigate to **src/tests/playwright**
2. Configure Playwright using playwright.env file based on your local setup. Current configuration should work for default Artemis setup.
3. Run `npm install && npm run playwright:setup && npx playwright test e2e/exam/ExamAssessment.spec.ts`
4. Confirm that **"Check exam statistics"** test passes

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by rstief — APPROVED** [review]
Demonstrated in testing session, code also lgtm 👍

**Review by pzdr7 — APPROVED** [review]
The statistics test works and looks good (-> testing session). You may want to change the base branch of the PR though, as there are a few unrelated changes that might get merged too soon with this PR

**Review by undernagruzez — APPROVED** [review]
statistics test - works and demonstrated in a testing session

**Review by coolchock — APPROVED** [review]
lgtm

**Pull request merged**
