### PR TITLE
Bugfix: _meta undefined in result-details-chart when legend clicked

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [X] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

I investigated the following sentry issue:
 https://sentry.io/organizations/ls1intum/issues/1991312466/?project=1440029&query=assigned%3Ahello%40stefanwaldhauser.me&statsPeriod=14d#request

I could reproduce the issue. The issue happens when clicking on the label of the result-details graph. The reason is the default label click handler for chart.js. https://www.chartjs.org/docs/latest/configuration/legend.html#custom-on-click-actions
image

As you can see it expects that `legendItem.datasetIndex` exists. This was not set. I added it in 95ea2728974e9141c2b4f0e7b11f39ae00cb7870. This now fixes the bug and the default click handler works (hides the element in the gaph)

### Description

Added `legendItem.datasetIndex` in 95ea2728974e9141c2b4f0e7b11f39ae00cb7870

### Steps for Testing

Create a programming exercise, participate in it via the online code editor

image
image

### CODE REVIEW

**Review by kloessst — APPROVED** [review]
Nice fix, I confirmed that no error is thrown when clicking on the label. Well done

**Review by fde312 — APPROVED** [review]
It works for me as well. No error is thrown anymore when clicking on the labels! Good job 👍

**Review by JohannesWeiss — APPROVED** [review]
Works as intended, no errors shown.

**Review by airelawaleria — APPROVED** [review]
Everything works.

**Review by krusche — APPROVED** [review]

**Pull request merged**
