### PR TITLE
Communication: Highlight solution answer in thread

### PR DESCRIPTION
**Pull request by badkeyy**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Implements https://github.com/ls1intum/Artemis/issues/9934

### Description
Add a solution badge to the resolving message of a thread.

### Steps for Testing

Prerequisites:
- 1 Course
- 1 Instructor

1. Log in to Artemis
2. Go to the communication tab of any course
3. Create a conversation (thread) with at least two answers
4. Mark one answer as "Reply resovles the original message"
5. Find that this message is now marked with the "Solution" badge

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

image

## Summary by CodeRabbit

- **New Features**
  - Added a badge to indicate whether a post resolves an issue, enhancing user context.
  - Introduced localization support for the new badge with translations in both German and English.

- **Bug Fixes**
  - Updated tests to ensure accurate verification of the new functionality and existing component behavior.

- **Tests**
  - Added a new test case to check the display of the solution badge based on post resolution status.

### CODE REVIEW

**Review by HawKhiem — COMMENTED** [review]
Hi, could you please check why it's not possible to deploy to the test servers. I tried on TS1 and TS3 but still couldn't deploy. I also did update the brach before deploying. Thank you!

**Comment by badkeyy** [comment]
> Hi, could you please check why it's not possible to deploy to the test servers. I tried on TS1 and TS3 but still couldn't deploy. I also did update the brach before deploying. Thank you!

Hey,
this issue seems to persist across a lot of my PR's an I don't really know why... For me locally everything builds and runs perfectly. Is there any error message I could work with?

**Comment by HawKhiem** [comment]
> > Hi, could you please check why it's not possible to deploy to the test servers. I tried on TS1 and TS3 but still couldn't deploy. I also did update the brach before deploying. Thank you!
> 
> Hey @HawKhiem, this issue seems to persist across a lot of my PR's an I don't really know why... For me locally everything builds and runs perfectly. Is there any error message I could work with?

**Comment by HawKhiem** [comment]
> > Hi, could you please check why it's not possible to deploy to the test servers. I tried on TS1 and TS3 but still couldn't deploy. I also did update the brach before deploying. Thank you!
> 
> Hey @HawKhiem, this issue seems to persist across a lot of my PR's an I don't really know why... For me locally everything builds and runs perfectly. Is there any error message I could work with?

**Comment by badkeyy** [comment]
> > > Hi, could you please check why it's not possible to deploy to the test servers. I tried on TS1 and TS3 but still couldn't deploy. I also did update the brach before deploying. Thank you!
> > 
> > 
> > Hey @HawKhiem, this issue seems to persist across a lot of my PR's an I don't really know why... For me locally everything builds and runs perfectly. Is there any error message I could work with?
> 
> Sorry for pressing the wrong button and acidentally closing this pr a minute ago. I reopen it. Anyway when I tried to deploy to a test server, I got something like this. Starting from the third check onwards somehow didn't run through
> 
> image

@HawKhiem I see, however all this errors seem to be CI related. It also does not make any sense that the server would not build as I didn't change anything in it.

image

**Comment by HawKhiem** [comment]
> > > > Hi, could you please check why it's not possible to deploy to the test servers. I tried on TS1 and TS3 but still couldn't deploy. I also did update the brach before deploying. Thank you!
> > > 
> > > 
> > > Hey @HawKhiem, this issue seems to persist across a lot of my PR's an I don't really know why... For me locally everything builds and runs perfectly. Is there any error message I could work with?
> > 
> > 
> > Sorry for pressing the wrong button and acidentally closing this pr a minute ago. I reopen it. Anyway when I tried to deploy to a test server, I got something like this. Starting from the third check onwards somehow didn't run through
> > image
> 
> @HawKhiem I see, however all the errors seem to be CI related. It also does not make any sense that the server would not build as I didn't change anything in it.
> 
> image

That is indeed quite odd. I reran again and the build still doesnt go through. I will try deploying and test locally later today

image

**Comment by laxerhd** [comment]
I have also encountered this problem. For the majority (maybe even all) of my PRs, the deployment on the test server does not work. For most of them the `Build Expected — Waiting for status to be reported` test did not go through and thus also the tests down below it.

**Comment by HawKhiem** [comment]
> I have also encountered this problem. For the majority (maybe even all) of my PRs, the deployment on the test server does not work. For most of them the `Build Expected — Waiting for status to be reported` test did not go through and thus also the tests down below it. @HawKhiem do you maybe have an option like this shown to you? image I am not sure, but the build did not go through before sb pressed this for me. Or is this related to something else?

Yes I also have that option

**Comment by laxerhd** [comment]
> That is indeed quite odd. I reran again and the build still doesnt go through. I will try deploying and test locally later today

Just a quick update for others who may have the same problem of PRs not being deployed. If you try to create a PR with a branch from a forked Artemis repository, the test server will not deploy it.

**Pull request closed without merging**
