### PR TITLE
`Lecture`: Fix issues with lecture attachments and quiz exercise re-evaluation

### PR DESCRIPTION
**Pull request by krusche**
This PR fixes three issues:
1. When there is a quiz exercise as attachment unit in lecture, you cannot create additional `file` lecture units (e.g. PDFs) any more due to the serialization issue
`Could not write JSON: Cannot invoke \"java.lang.Boolean.booleanValue()\" because \"this.isVisibleBeforeStart\" is null'`
2. When there is a quiz exercise as attachment unit in a lecture, you cannot create additional attachments (directly in the lecture) due to the same serialization issue
3. When a quiz exercise includes categories, you cannot re-evaluate it any more

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
I experienced the issues as instructor in my course

### Description
We remove some unnecessary data (which should also make the REST call faster) and convert categories correctly before re-evaluating quizzes

### Steps for Testing
1 Instructor
1 Student

1. Create a new lecture
2. Create a quiz (with 2-3 questions) with categories, connect it to a lecture (using lecture units) and let the quiz run
3. Re-evaluate the quiz --> should work
4. Add a new `file` lecture unit in the units section of the lecture (e.g. some PDF) --> should work without error
5. Add a new attachment directly to the lecture in the attachment section of the lecture (e.g. some PDF) --> should work without error
6. Display all units and attachments as student
7. Reorder the lecture units as instructor, update the attachments (in the unit and directly) with new file versions
8. Delete the attachments and lecture units as instructor

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by jhainzlschmid — APPROVED** [review]
I followed the testing steps on TS1 and could not find any issues 👍

**Review by mallgaier — APPROVED** [review]
The test steps were executed accordingly on the TS1. After re-evaluating the quiz, all possible attachments could be added

**Review by lschlesinger — APPROVED** [review]
Tested on TS1 according to the described steps. No error occurred.

**Review by lBruchmann — CHANGES_REQUESTED** [review]
error message
Tested on ts1 together with @Strohgelaender . Adding an attachment after adding a quiz exercise does not work as expected and shows the described error message. The reevalution works as expected.

**Review by Strohgelaender — CHANGES_REQUESTED** [review]
Tested together with @lBruchmann on ts1. The reevaluation works as expected, but when adding an attachment the same error message is still shown. When looking at the network traffic I noticed that the client only sends a value for `visibleToStudents` to the server. But instead of using this, the getter `isVisibleToStudents` does not use this value and tries to calculate it instead based on `isVisibleBeforeStart`. This was not sent by the client and therefore throws an exception.

**Comment by krusche** [comment]
> Tested together with @lBruchmann on ts1. The reevaluation works as expected, but when adding an attachment the same error message is still shown. When looking at the network traffic I noticed that the client only sends a value for `visibleToStudents` to the server. But instead of using this, the getter `isVisibleToStudents` does not use this value and tries to calculate it instead based on `isVisibleBeforeStart`. This was not sent by the client and therefore throws an exception.

Are you sure the correct build was deployed while testing? This is exactly the error that I have fixed, so chances are high that you tested the wrong build

**Comment by lschlesinger** [comment]
Agree with @Strohgelaender, adding attachment to lecture shows the error. I will test it again after it's fixed.

**Comment by krusche** [comment]
I think I fixed the other issue as well. We are definitely sending too much unnecessary data in the lecture components.
I added some TODOs in the code for future improvements, but the most important issues should hopefully be fixed now...

**Review by lschlesinger — APPROVED** [review]
For the lecture on TS1 I received the error @Strohgelaender described previously, I can add the attachment without error now. Issue seems to be fixed with the recent changes.

**Comment by krusche** [comment]
Please notice the updated testing steps to make sure everything still works correctly

**Review by Strohgelaender — DISMISSED** [review]
Tested according to the (updated) testing steps, I could not find any issues. The error mentioned above is fixed.

**Review by mallgaier — DISMISSED** [review]
The test steps according to the revised work steps worked as expected without issues.
All Lecture Units (Text - File - Video - Exercise) could be added, modified, moved as well as deleted. Attachments could be added, edited, updated, and removed without an issue.
The viewing of the lecture for instructors and students was as expected.

**Review by VinnavanSembian — DISMISSED** [review]
Followed test steps on ts2. Attaching quiz to lecture and reevaluation works good. Adding file to lecture works as expected. No issues.

**Review by lBruchmann — APPROVED** [review]
Tested on ts2. I followed the test steps. Everything works as expected. Attaching files works for both units and lectures without errors or problems.

**Review by MertAksehirlioglu — DISMISSED** [review]
I followed testing steps and tested on ts2. Everything works as expected, no error occurred.

**Review by baranimo7 — APPROVED** [review]
I have followed the testing steps(in ts2) and everything works as expected.

**Pull request merged**
