### PR TITLE
Show User Management Links only for Admins

### PR DESCRIPTION
**Pull request by Strohgelaender**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) ~~on the test server https://artemistest.ase.in.tum.de~~ locally.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context
The User Management is only accessible for administrators, but links to these pages are displayed at multiple places. Clicking them as non-administrator hast simply no effect at all. This PR removes this links and only displays them if the current user has administrator rights.

### Steps for Testing

Check the following pages once as administrator and once as admin. Make sure that the instructor can only see the value (in most cases the student's name or login) while the administrator sees a clickable link.

- Course Management -> Exams -> Students
- Course Management -> Exams -> Student exams
- Course Management -> Exercises -> Participations
- Course Management -> Exercises -> Scores
- Course Management -> Course (click on title) -> Any user group

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Tested on TS2. Access is restricted for an instructor as described. In the user groups of a course the account names are not clickable for an administrator as well, but the IDs are, so access to the user information is possible. Seems good for me.

**Review by rs-maker — APPROVED** [review]
Tested on Ts3 displays things as links for admin and as plain text for instructor. Seems good.

**Review by NicolasUllmann — APPROVED** [review]
Tested on server 3. Worked as expected.

**Review by KiraNickel — CHANGES_REQUESTED** [review]
Tested on ts3. All Exams->... and Exercise->... views work.

For "Course Management -> Course (click on title) -> Any user group" however while the Instructor does not have a clickable link (as intended), the administrator doesn't have a clickable link either (not intended) in any of the three groups.

**Review by KiraNickel — APPROVED** [review]
Tested on ts3. Works as expected (I previously missed that in the Course->any Group overview the link for the administrator is on the id instead of the user name)

**Review by SimonEntholzer — APPROVED** [review]
The client code looks good, I didn't test it though.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Works.

**Pull request merged**
