### PR TITLE
`Iris`: Upgrade settings system for Pyris V2

### PR DESCRIPTION
**Pull request by Hialus**
> [!WARNING]
> CONTAINS DATABASE MIGRATION INCOMPATIBLE WITH DEVELOP!

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

After the introduction of PyrisV2 the settings system for Iris was outdated. We want to update it to support PyrisV2 fully.
Additionally, we discontinue the Iris Hestia integration.

### Description

- Removed old settings fields
- allowedModels and preferredModels were transformed into allowedVariants and selectedVariant
- All Iris Hestia related stuff was removed
- Updated UI

### Steps for Testing

Prerequisites:
- 1 Admin account
- Local setup with Pyris (unless otherwise announced)
- ls1intum/Pyris#149 merged or deployed on pyris-test

1. **Backup your database**
2. Log in to Artemis
3. In the nav bar in the admin drop down go to Iris settings
4. Play around with the settings
5. After you are done set everything back to original (all enabled)
6. Go to course management page of your test course
7. Open Iris settings
8. Play around
9. Go to the management page of a programming exercise in your course
10. Open Iris settings 
11. Play around
12. Optional: **Restore your database**

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Performance Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| course-detail.component.ts | 91.4% | ✅ |
| iris-settings.model.ts | 81.81% | ✅ |
| iris-sub-settings.model.ts | 100% | ✅ |
| iris-common-sub-settings-update.component.ts | 96.22% | ✅ |
| iris-settings-update.component.ts | 88.6% | ✅ |
| iris-enabled.component.ts | 100% | ✅ |
| iris-settings.service.ts | 90.47% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| IrisSession.java | 100% | ✅ |
| IrisChatSubSettings.java | 100% | ✅ |
| IrisCompetencyGenerationSubSettings.java | 100% | ✅ |
| IrisCourseSettings.java | 100% | ✅ |
| IrisExerciseSettings.java | 91% | ✅ |
| IrisGlobalSettings.java | 100% | ✅ |
| IrisSettings.java | 100% | ✅ |
| IrisSubSettings.java | 100% | ✅ |
| IrisSubSettingsType.java | 100% | ✅ |
| IrisCombinedChatSubSettingsDTO.java | 100% | ✅ |
| IrisCombinedCompetencyGenerationSubSettingsDTO.java | 100% | ✅ |
| IrisCombinedSettingsDTO.java | 100% | ✅ |
| IrisSettingsRepository.java | 100% | ✅ |
| IrisSessionService.java | 76% | ✅ |
| PyrisConnectorService.java | 78% | ✅ |
| IrisExerciseChatSessionService.java | 90% | ✅ |
| IrisSettingsService.java | 86% | ✅ |
| IrisSubSettingsService.java | 89% | ✅ |
| IrisSettingsResource.java | 95% | ✅ |
| CodeHintService.java | 96% | ✅ |
| CodeHintResource.java | 85% | ✅ |

�

### Screenshots

image
image

## Summary by CodeRabbit

- **New Features**
	- Added new methods for assessment management, including the ability to cancel and delete assessments.
	- Introduced a new `BonusResultDTO` record to encapsulate bonus grade results.
	- Updated `BonusSourceResultDTO` to include additional fields for tracking bonus results.
	- Updated method for fetching variants based on specified features in `PyrisConnectorService`.
	- Enhanced role-based access control in `IrisSettingsResource` for various settings operations.
	- Introduced a new REST controller `IrisVariantsResource` for managing variants.

- **Documentation**
	- Enhanced guidelines on database relationships and fetching strategies, including lazy fetching and best practices.

- **Refactor**
	- Improved organization of import statements across several classes for better readability.

- **Style**
	- Reordered import statements to follow a consistent structure across various files.

- **Chores**
	- Removed dependency on Iris functionality from `CodeHintResource`, simplifying the class. 

- **Tests**
	- Streamlined test setups by removing unnecessary components and adjusting expectations in several test suites.

### CODE REVIEW

**Review by MichaelOwenDyer — DISMISSED** [review]
Tested locally, works great. Code looks good too

**Review by MichaelOwenDyer — DISMISSED** [review]
This is a much-needed change and I have tested it continuously for over a month now, imo it is ready to merge.

**Review by kaancayli — DISMISSED** [review]
Changes look good. Tested locally, no issues encountered. LGTM

**Review by yassinsws — APPROVED** [review]
Tested this locally works good !

**Review by MichaelOwenDyer — APPROVED** [review]
Reapprove

**Review by kaancayli — APPROVED** [review]
Reapprove

**Review by yassinsws — APPROVED** [review]
reapprove

**Pull request merged**
