### PR TITLE
`Integrated code lifecycle`: Fix issues in build queue when running on multiple nodes

### PR DESCRIPTION
**Pull request by mateusmm01**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Currently, we can observe the running and queued build jobs, but we can't cancel them deterministically on a multiple node system f.ex. TS3. It would be nice to fix this and be able to cancel these build jobs if they freeze or are irrelevant. For testing purposes, it would also be nice to cancel all. 

### Description

Issues that were causing the build queue to not be updated on ts3 were fixed by changing the EntryListeners from `LocalEntryListeners` to normal `EntryListeners` in `LocalCIQueueWebsocketService`. Also, there was a rounding issue between the Server and Client with the _Long_ `buildJobId`, which was used to update the queue, so it was turned into a _String_ now. For this, the interface `StringBaseEntity` still had to be added in the client and `data-table-component` adjusted.
 As we don't want to save the futures that run the build jobs on every node as an HazelcastInstance we only save them in `runningFutures` in `LocalCIBuildJobManagementService ` on the node that is running this build job. When cancelling a build job we now need to find the right node to cancel the build job. A Broadcast was implemented with Hazelcast ITopic `canceledBuildJobsTopic`, which has a listener that then triggers the cancellation on the correct node. 

### Steps for Testing

**Only deploy on ts3, ts6 and ts11.** 

Prerequisites:
- 1 Instructor
- 1 Admin
- 1 Student/ Tutor

**Build Queue for Instructors/Admin on Course Level:** Course Management > _course xy_ > Build Queue
**Build Queue for Admins only:** Server Administration > Build Queue

Trigger some builds by submitting a few programming exercises. Navigate to the Build Queue and try to cancel some builds differently (individually or canceling all at once). Make sure that Students and Tutors can't access this functionality. Lastly, make sure that you also don't receive any feedback for the canceled build job, suggesting it got processed successfully.  **Make sure that it also works on ts3, which uses multiple nodes.**

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Screenshot 2024-01-16 at 12 52 29

## Summary by CodeRabbit

- **New Features**
	- Introduced new management for tracking and handling cancelled build jobs.
- **Improvements**
	- Enhanced build job management with more efficient data structures.
	- Upgraded event listener configurations for better real-time updates.
- **Bug Fixes**
	- Fixed inconsistencies in build job cancellation logic.
- **Refactor**
	- Standardized build job identifiers to use strings instead of numbers for consistency across the platform.
- **Tests**
	- Updated test suites to reflect changes in build job identifier types.

### CODE REVIEW

**Review by xHadie — CHANGES_REQUESTED** [review]
_Manually tested on TS11_Legacy_

1. Build jobs and queued jobs run correctly and can be cancelled individually or by using the "Cancel all" button. 👍🏼

2. Only instructors and admins can access the build queues view and call the API methods. Access is denied for tutors and students of the course. 👍🏼
image

3. One issues I noticed, is that after cancelling a build, the student view will be stuck on showing that a build is getting processed, leaving the students unaware about the cancellation of their builds.
image

**Comment by mateusmm01** [comment]
> _Manually tested on TS11_Legacy_
> 
> 1. Build jobs and queued jobs run correctly and can be cancelled individually or by using the "Cancel all" button. 👍🏼
> 2. Only instructors and admins can access the build queues view and call the API methods. Access is denied for tutors and students of the course. 👍🏼
>    image
> 3. One issues I noticed, is that after cancelling a build, the student view will be stuck on showing that a build is getting processed, leaving the students unaware about the cancellation of their builds.
> 
> image

That will be tackled in a follow-up 👍 . For this PR it's only important for now that the build queue works as expected.

**Review by laurenzfb — APPROVED** [review]
tested on ts3, cancellation works. Code also LGTM

**Review by konrad2002 — DISMISSED** [review]
manually tested on ts3, works as expected

**Review by milljoniaer — APPROVED** [review]
Demonstrated in testing session, works as expected 👍

**Review by xHadie — APPROVED** [review]

**Review by laurenzfb — APPROVED** [review]
reapprove

**Review by reschandreas — APPROVED** [review]
demonstrated in testing session, lgtm

**Review by milljoniaer — APPROVED** [review]
demonstrated in testing session, works as expected

**Pull request merged**
