### PR TITLE
`Tutorial groups`: Fix an issue when deleting a course with tutorial groups with active messaging

### LINKED ISSUE #8090: Cannot remove courses with tutorial groups
### Describe the bug

We have to delete courses on a regular basis. During the current deletions, I encountered a problem during the deletion of a course with enabled tutorial groups.

```
2024-02-27 17:28:21.872 ERROR 1 --- [io-8080-exec-32] o.h.e.jdbc.batch.internal.BatchingBatch  : HHH000315: Exception executing batch [java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`artemis`.`tutorial_group`, CONSTRAINT `fk_tutorial_group_channel` FOREIGN KEY (`tutorial_group_channel_id`) REFERENCES `conversation` (`id`))], SQL: delete from conversation where id=?
2024-02-27 17:28:21.872  WARN 1 --- [io-8080-exec-32] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1451, SQLState: 23000
2024-02-27 17:28:21.872 ERROR 1 --- [io-8080-exec-32] o.h.engine.jdbc.spi.SqlExceptionHelper   : Cannot delete or update a parent row: a foreign key constraint fails (`artemis`.`tutorial_group`, CONSTRAINT `fk_tutorial_group_channel` FOREIGN KEY (`tutorial_group_channel_id`) REFERENCES `conversation` (`id`))
2024-02-27 17:28:21.898 ERROR 1 --- [io-8080-exec-32] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [delete from conversation where id=?]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276)
	......
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute batch
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:109)
	......
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:562)
	... 137 common frames omitted
Caused by: java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`artemis`.`tutorial_group`, CONSTRAINT `fk_tutorial_group_channel` FOREIGN KEY (`tutorial_group_channel_id`) REFERENCES `conversation` (`id`))
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:223)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:307)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:416)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:802)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:125)
	... 160 common frames omitted
Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`artemis`.`tutorial_group`, CONSTRAINT `fk_tutorial_group_channel` FOREIGN KEY (`tutorial_group_channel_id`) REFERENCES `conversation` (`id`))
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:555)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:339)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1054)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1003)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeBatchSerially(ServerPreparedStatement.java:279)
	... 165 common frames omitted
```

### To Reproduce

Was in production system. Couse has Tutorial groups.

### Expected behavior

Course should be deleted.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.8.2

### What browsers are you seeing the problem on?

Firefox

### Additional context

If I delete all tutorial groups manually, I can delete the course afterwards.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by krusche**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Fixes #8090. It was not possible to delete courses with tutorial groups.

### Description
Fixed the issue by deleting tutorial group channels first before deleting the tutorial groups. 

### Steps for Testing
Prerequisites:
- 1 Admin
- 1 Course with tutorial groups, messaging enabled, and messages in the respective tutorial group channels.

Delete the Course and check that no error occurred.

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage
test added.

## Summary by CodeRabbit

- **New Features**
	- Enhanced course deletion process to include the removal of tutorial group notifications and channels.
- **Tests**
	- Added integration tests for verifying the deletion of courses along with associated tutorial groups and related entities.

### CODE REVIEW

**Review by pzdr7 — APPROVED** [review]
Tested on TS5. The course (w/ tutor group channels that had messages) was deleted successfully -> works as expected!

**Review by egekurt123 — APPROVED** [review]
Manually tested on ts1, works as expected

**Review by Predixx — APPROVED** [review]
Tested manually on ts1. lgtm!

**Review by rstief — APPROVED** [review]
Code looks good (just one optional suggestion)👍

**Review by nata-81 — APPROVED** [review]
Tested on ts1, works as expected.

**Review by farisd16 — APPROVED** [review]
tested on ts2, works as expected

**Pull request merged**
