### PR TITLE
[Feature] Embed Apollon-editor in modelling-exericse-update-component

### PR DESCRIPTION
**Pull request by Olimbia23**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

This change makes it easier for the instructors to create an Example Solution for a modelling exercise as discussed in this PR
https://github.com/ls1intum/Artemis/pull/3540#issuecomment-860722008

### Description

Before, the instructor could only create an Example Solution after creating a modelling exercise.
With the new changes,  we have embedded the Apollon editor inside the modelling-exercise-update-component, thus giving the instructor the possibility to create an Example Solution during the exercise creation/update. 

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Select a course
4. Click exercises
5. Crete a modelling exercise
6. You should be able to create an example solution in the creation view of a modelling exercise.
6. Upon creation you should be redirected to the example submissions dashboard

### Test Coverage

Did not change.

### Screenshots and Gif
Screenshot 2021-06-20 at 7 32 56 PM

DEMO (modeling exercise update)

### CODE REVIEW

**Review by argertboja — DISMISSED** [review]
Tested on TS1 everything works as expected. Code changes look good too 👍🏼

**Review by ga62suz — COMMENTED** [review]
Tested on TS1, on all diagram types.
Everything worked well!

Suggestion: add "Example Solution" header, same as with text exercises:
image
Current:
image

**Comment by Olimbia23** [comment]
> Tested on TS1, on all diagram types.
> Everything worked well!
> 
> Suggestion: add "Example Solution" header, same as with text exercises:

Thank you for noticing this. I added it. @ga62suz 😇

**Review by canyelten — APPROVED** [review]
Tested on TS1, works as expected.

**Review by imstreetspirit — APPROVED** [review]
tested on ts2, everything works as described. I just checked the exercise detail page, and I think that adding "Example Solution Explanation" header would be nice in there like in the edit page. It can be done in context of another PR. I just wanted to share 😊 (Also, space can be added between export button and modeling editor - see image)

**Review by katjanakosic — APPROVED** [review]
Worked as expected on TS1

**Review by cremertim — APPROVED** [review]
works on ts 1 -- really good work.. this is an awesome feature👍

**Review by sinangunduz — APPROVED** [review]
tested on ts1, works as expected

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Works as expected

**Review by real-dmy — APPROVED** [review]
Tested on TS1. Works as described.

**Comment by Olimbia23** [comment]
> tested on ts2, everything works as described. I just checked the exercise detail page, and I think that adding "Example Solution Explanation" header would be nice in there like in the edit page. It can be done in context of another PR. I just wanted to share 😊 (Also, space can be added between export button and modeling editor - see image)

Yeah, it can be a good idea @imstreetspirit , I will discuss it with @krusche  and upon agreement and I can make a PR for it. 👍

**Review by KiraNickel — APPROVED** [review]
Tested on ts3, works as expected 👍🏼

**Review by joschahenningsen — APPROVED** [review]
Works as expected, I especially love net negative diffs, doesn't happen often around here :D

**Pull request merged**
