### PR TITLE
[Bugfix] Resolve missing key in translation in Tutor Assessment

### PR DESCRIPTION
**Pull request by derLalla**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context

The jhiAlert Service uses the translation Service to translate the received `key`. On some occasions, we want to directly use a specified message for which no translation key is available. 

### Description

This fixes a false parameter which was passed into the jhiAlert error function.  
In case a translation key is not found, the previous output to the alert-component was : 

translation-not-found[translation.key]

The approach now is to remove the `translation-not-found[]` portion and just show the translation key. 
We sent additionally a warning to Sentry to be informed if we are missing such a key.

### Steps for Testing

1. Log in to Artemis
2. Try to generate a warning message
3. For example create a Programming exercise, with a title and shortname which already exists
4. Verify that the warning message is working as intended and no issue was sent to Sentry. 
(Only issues with a missing translation key shall send a notification to Sentry)

### Test Coverage

No new relevant code or features were added, so the test coverage stays the same.

### Screenshots

Correct alert notification:
image

New Issue in Sentry:
image

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested with @simonzilker . Could not find any issues

**Review by simonzilker — APPROVED** [review]
tested on ts1 with @airelawaleria . No issues found

**Review by JohannesWeiss — APPROVED** [review]
Tested in testing session, works as intended!

**Review by EneaGore — APPROVED** [review]

**Review by marvinchimeka — APPROVED** [review]
works as stated. tested on ts1

**Review by FlorianStang — APPROVED** [review]
Tested on TS1, everything worked as intended

**Review by krusche — APPROVED** [review]
Great improvement, hopefully, we will never see those ugly translation issues again ;-)

**Pull request merged**
