### PR TITLE
`Development`: Migrate client text module to use inject 

### PR DESCRIPTION
**Pull request by FelixTJDietrich**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

We want to modernize our Angular code, part of this modernization is switching to the `inject` methods which has some minor advantages.

### Description

- Switch to `inject` for the whole text module
- Migrate the common exercise component across modules for completeness
  - file-upload
  - modeling
  - programming
  - quiz

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students

You have to check if all features of text exercises still work as expected.

1. Creating a text exercise
2. Participating in a text exercise
3. Assessing a text exercise
4. Viewing the result / feedback

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

Unchanged.

## Summary by CodeRabbit

- **New Features**
	- Transitioned to Angular's `inject` function for dependency injection across multiple components and services, enhancing code readability and maintainability.
	- Default initialization for several properties, such as `modelingExercises`, `programmingExercises`, and `isSaving`, directly in their declarations.

- **Bug Fixes**
	- No specific bug fixes were mentioned, but the refactoring may improve overall stability by streamlining service management.

- **Refactor**
	- Removed constructors in various components and services, simplifying dependency management.
	- Updated service and component properties to utilize the `inject` function for direct service instantiation.

- **Documentation**
	- Improved clarity in code structure, potentially aiding future development and maintenance efforts.

### CODE REVIEW

**Review by vinceclifford — DISMISSED** [review]
Works as expected, tested on TS6.

**Review by HawKhiem — DISMISSED** [review]
Tested on TS6. All features still work as expected

**Review by sachmii — DISMISSED** [review]
Tested on TS6, everything worked fine, could not notice any errors.

**Review by eceeeren — DISMISSED** [review]
Tested on TS6, everything works as expected

**Review by cremertim — COMMENTED** [review]
Is there a particular reason why you didnt not update the @Input / @Output accordingly / will this be part of a seperate PR.

**Review by cremertim — APPROVED** [review]
Replacements in code lgtm

**Comment by FelixTJDietrich** [comment]
@cremertim I'm migrating step by step to keep it reviewable. First I will start with `inject`.

**Comment by FelixTJDietrich** [comment]
No need to retest, only the test code changed to fix the failing tests.

**Review by eceeeren — APPROVED** [review]
Reapprove.

**Review by sachmii — APPROVED** [review]
re-approve

**Review by cremertim — APPROVED** [review]
Reapprove after latests changes

**Comment by FelixTJDietrich** [comment]
I missed some more TS issues in the tests, should be good to go now, sorry for that

**Review by EneaGore — APPROVED** [review]
code

**Review by cremertim — APPROVED** [review]

**Pull request merged**
