### PR TITLE
`Communication`: Add additional input formatting options

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [X] I documented the TypeScript code using JSDoc style.
- [X] I added multiple screenshots/screencasts of my UI changes.
- [X] I translated all newly inserted strings into English and German.

### Motivation and Context

- In communication module, the input formatting options, such as strike-through, unordered lists, and bullet lists that are available in Slack, are missing.
- Even though the user can add new lines in the editor, when s/he sends the message, the line breaks don’t show up.
- When converting text to emojis automatically, unintended strings like "c:" are also being converted, leading to undesired behavior.

### Description

- Added support for strikethrough, bulleted list, and ordered list options in the communication module.
- New lines can now be used in messages, allowing for line breaks.
- Bulleted and ordered lists were previously available on some other pages containing the editor but did not function correctly. Issues such as Shift+Enter not adding a prefix automatically, Backspace not working properly, and prefix nesting problems when working with nested lists or switching list formats have been resolved in the new action classes.
- Now, only strings that begin with a colon (:) are converted to emojis.

### Steps for Testing

Prerequisites:
- 1 Instructor/Student
- 1 Course with Communication enabled

1. Log in to Artemis
2. Navigate to Communication section of a course
3. Open a conversation and try new options on input area: strikethrough, bulleted list and ordered list
4. Send a message that contains a line break
5. Send a message that contains "c:" and see that it does not converted to an emoji anymore

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| short-answer-question-edit.component.ts | 95.48% | ✅ ❌ |
| markdown-editor-monaco.component.ts | 95.38% | ✅ ❌ |
| posting-content-part.components.ts | 95.65% | ✅ ❌ |
| posting-markdown-editor.component.ts | 100% | ✅ |
| bulleted-list.action.ts | 100% | ✅ |
| list.action.ts | 55.55% | ✅ ❌ |
| ordered-list.action.ts | 100% | ✅ |
| strikethrough.action.ts | 75% | ✅ ❌ |
| monaco-editor.component.ts | 94.66% | ✅ ❌ |

### Screenshots

**new formatting options on editor**
image
**strikethrough example**
image

## Release Notes

- **New Features**
  - Enhanced markdown editor with new formatting options: Bulleted lists and strikethrough text.
  - Improved handling of content rendering with whitespace management in posting content.
  - New processing logic for handling numbered lists in posting content.

- **Bug Fixes**
  - Refined emoji conversion logic to target specific emoticons in text.

- **Documentation**
  - Updated localization files to include new strikethrough formatting options in both English and German.

- **Tests**
  - Added new test cases for validating bulleted and ordered list actions in the markdown editor.

### CODE REVIEW

**Comment by asliayk** [comment]
thank you for your reviews :) I've updated the code with these changes:

- The editor now handles Cmd+Enter for adding new lines, just like it does with Shift+Enter.
- If the cursor is in the middle of a line and a list option is chosen, the prefix is added at the start of the line, similar to how it works in Slack.

**Review by kevinfischer4 — APPROVED** [review]
Tested on TS1, works as expected.
Screenshot 2024-11-03 at 19 15 12

**Review by vinceclifford — APPROVED** [review]
Tested on TS1. Everything works as expected.

**Review by sachmii — APPROVED** [review]
Tested on TS2, worked just fine.

Bildschirmfoto 2024-11-04 um 12 43 27

**Pull request merged**
