### PR TITLE
Athene Scheduling: Exercise hasEnded check

### PR DESCRIPTION
**Pull request by jpbernius**
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [X] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [X] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [X] ~Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)~
- [X] Server: I implemented the changes with a good performance and prevented too many database calls
- [X] Server: I documented the Java code using JavaDoc style.

### Description
- Athene: Resolve TODO for exam exericise due dates
- Extract hasEnded Method for Exercise from ResultResource
  Includes Check for course and exam exercises.

**TODO:**
- Identify more places where this can be used and remove different dueDate after now implementations.

### Steps for Testing

1. Create Text Exercise, add 10 submissions (similar), due date passes, find suggestions during the assessment
2. Create Exam with Text Exercise, add 10 submissions (similar), due date passes, find suggestions during the assessment

### CODE REVIEW

**Comment by tiffca** [comment]
I couldn't get the automatic suggestions to work for me for regular text exercise with automatic suggestions turned on, but it usually doesn't work for me when I test it so it could be something I'm doing wrong. I wonder if we have to grade with 2 different users for automatic suggestions to show up (I graded with only 1 user)

**Review by airelawaleria — COMMENTED** [review]
tested in the testing session. we couldn't see the automatic suggestions

**Review by simonzilker — COMMENTED** [review]
tested in testing session. what @airelawaleria said

**Review by JohannesWeiss — COMMENTED** [review]
Tested in testing session on ts1, there were no suggestions (even with different users).

**Review by LudwigWeide — COMMENTED** [review]
What @airelawaleria said.

**Review by EneaGore — COMMENTED** [review]
Same on ts1

**Review by marvinchimeka — COMMENTED** [review]
Tested in testing session. confirm what @airelawaleria said

**Review by derLalla — APPROVED** [review]
these are nice changes and simplify it a lot!

**Comment by jpbernius** [comment]
Closing this for now until the functionality is tested again and confirmed to work without issues.

**Pull request closed without merging**
