### PR TITLE
[Bugfix] Fix old master buildplans in Jenkins

### PR DESCRIPTION
**Pull request by JohannesStoehr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

The Artemis update 5.0  introduced the option to choose different default branches. This broke the old build plans used in Jenkins that directly refer to the master branch.

### Description

This PR fixes the bug by changing the reference to the master branch whenever a new build plan is created.

### Steps for Testing

1. Log in to Artemis on **ts2**
2. Navigate to an old exercise, that was created before the update to 5.0, for example https://artemistest2.ase.in.tum.de/course-management/615/programming-exercises/4471
3. Check that you can still participate in that exercise as a student
4. Import the old exercise and check that the template and solution build correctly and that you can participate in that exercise as well

### CODE REVIEW

**Review by ndricimrr — APPROVED** [review]
Tested on TS2. I can participate in the old exercise, and in the import of the old exercise 👍

**Review by ArtemTsurikov — APPROVED** [review]
Tested on TS2, everything worked for me as well!

**Review by NicolasUllmann — APPROVED** [review]
Tested on TS2. Everything worked as expected.

**Review by lschlesinger — APPROVED** [review]
Tested on TS2 as described. Did not encounter any problem!

**Pull request merged**
