### PR TITLE
`General`: Increase interactivity of tutor effort distribution chart

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

This PR changes the appearance and interactivity of the tutor effort distribution chart

### Description

- **Positioning**: The chart as well as the explanation text if no information can be displayed are now centered on the page. Furthermore, the recalculation button is moved to the right side.
- **Help icon**: A help icon next to the chart title provides a tooltip that is explaining what data is displayed there
- **Median**: The median of the distribution is now displayed in the table above the chart. If the bar representing the interval the median is contained in is not 0, this bar is highlighted in a darker blue and a corresponding color legend appears next to the table header of the median.
- **Enhanced tooltips**: The tooltips are formulated more clearly and now provide an explanation of what is displayed by the selected bar. Additionally, the tooltip contains the median of assessed submissions from tutors that fell in the corresponding interval.
- **Clickable bars**: By clicking on a chart bar, the user is redirected to the exercise assessment dashboard

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Text exercise with existing tutor efforts

**Important**: There seems to be problems with the computation of the effort statistics. These are not due to my changes, as they also appear on develop (at least for me). If no data is shown to you even though you assessed submissions, you might have to do it again (or do it this way directly):

- After submitting an assessment, do not press "assess next submission". Instead return to the assessment dashboard and start the next assessment from there.

If this does not work for you as well, inspect [this distribution](https://artemistest.ase.in.tum.de/course-management/481/text-exercises/13863/tutor-effort-statistics) on TS1 (e.g. with Test user 12). This is obviously not a long-term solution but might allow you to test this PR. 

1. Log in to Artemis
2. Navigate to Course Administration
3. Click on the exercise name and select "Tutor effort statistics"
4. Inspect the chart:
     - Check that the highlighting of the median works as described above
     - Check that the tooltips are understandable and well structured
     - Check that the explanation of the help icon is understandable
     - Check that you are delegated to the assessment dashboard if you click on a bar chart

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| File name | Branch coverage (%) | Line coverage (%) |
| -- | -- | -- | 
| `tutor-effort-statistics.component.ts` | 76.47 | 95.23 |

### Screenshots

image

### CODE REVIEW

**Review by canberkanar — APPROVED** [review]
Code changes are looking good.

**Comment by willergeorg** [comment]
> I could not test this on TS2. As you can see on the following screenshots there are tutor assessments, but when I click the button "Tutor effort statistics" I always get "No data records...". Just leaving this as a comment here in case more testers are having the same issue. But also, it might be just some kind of my stupid mistake that I'm not seeing at the moment.
> 
> tutor_assessment no_statistic

I observed similar issues while testing locally (and apparently forgot to mention it in the PR text, sorry for that). I'm not very familiar with the underlying logic that is computing the statistics, but I think there is a problem with it. This is not based on my changes, as I had the same problem on develop. The only way I managed to create those statistics was to leave the assessment view after each assessed submission instead of pressing "Assess next submission" and re-entering again for a new submission. Maybe this workaround works for you as well.

**Review by Bofan-Zhu — COMMENTED** [review]
While testing I had the same problem that the statistics were not computed even if assessed submissions existed. I tried your workaround but it did not work for me. I also tried looking into exercises that were some time ago in active course with assessed submissions but I also could not see any statistics.

**Comment by dveljacic** [comment]
Unfortunately, I can confirm that workaround is not working for me as well on TS2. This is the exercise link in case it matters: https://artemistest2.ase.in.tum.de/course-management/2772/assessment-dashboard/10522.

**Comment by willergeorg** [comment]
> Unfortunately, I can confirm that workaround is not working for me as well on TS2. This is the exercise link in case it matters: https://artemistest2.ase.in.tum.de/course-management/2772/assessment-dashboard/10522.

I added a link to a distribution that at least I managed to create on TS1 to the PR description. This might allow you to at least check an example of my changes. Since they are not really breaking and the creation of these distributions seems to be flaky atm, this is the only way for manual testing I currently see.

**Review by cremertim — APPROVED** [review]
tested on ts1 with your test server. Works as expected 👍

**Review by akesfeden — APPROVED** [review]
Tested in testing session, works as expected and code changes look good.

**Pull request merged**
