### PR TITLE
`Plagiarism checks`: Show an alert to the instructor when the plagiarism notification case has been sent

### LINKED ISSUE #5520: `Plagiarism checks`: Show that a short message that the plagiarism notification case has been sent.
### Is your feature request related to a problem?

When I notify a student about a plagiarism case, I don't receive any message if my notification has been sent. 

### Describe the solution you'd like

When I send a notification about a plagiarism case, I should receive a short message like "your notification has been sent" and send me back to the list of plagiarism cases. 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by akesfeden**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Closes #5520. When the instructor notifies a student about a plagiarism case, they don't receive any message if the notification has been sent. 
### Description

Show an alert to the instructor when the plagiarism notification case has been sent to the student.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exercise with Plagiarism Case

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to the Plagiarism Case
4. Notify the student and see that a success alert is shown

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| plagiarism-case-instructor-detail-view.component.ts | 82.35% | 98.03% |

### Screenshots

image

image

### CODE REVIEW

**Comment by akesfeden** [comment]
> @bassner made a similar PR in the other direction: #5514 where he removed some notifications since the success was obvious due to a navigation or UI change. I don't see a reason why we should make this change here

The post becomes visible on the screen but the notification part is an important part of the process to allow students to explain themselves so it may be nice to let the instructors now the student will also receive a notification, also @krusche wanted to have the suggestion mentioned in https://github.com/ls1intum/Artemis/issues/5520 implemented (except for the navigation part).

**Review by rhubinger — DISMISSED** [review]
Tested on TS2, worked as expected.

**Comment by bassner** [comment]
Where do you define the translation for that alert?
If I grep through everything on your branch, I only find the invocation and the test with the used translation key, but no definition of it in a json file anywhere
grafik

**Comment by akesfeden** [comment]
@bassner Thanks for noticing it, it turns out I accidentally committed them to [my other PR](https://github.com/ls1intum/Artemis/pull/5543/files#diff-85681c8518f9c65c763d9ed269fc9ee04e13c758219275242afd9d51cf7aaf1cR87), I committed them here now.

**Review by JohannesStoehr — APPROVED** [review]
Tested on TS1 and checked the code. Looks good to me

**Pull request merged**
