### PR TITLE
`Development`: Remove unnecessary database call

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context

A previous PR introduced a Hibernate check that would add an additional database call to retrieve a submission policy for a programming exercise.

### Description

I adapted two student exam queries to fetch the exercises with the submission policy.

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 1 Exam with 1 Programming Exercise with Submission Lock and 1 Student Exam

1. Try to view the student exam, you should not receive an Internal Server Error message

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
	- Enhanced the exam data export functionality to include exercises submission policies, providing a more comprehensive data set.
- **Bug Fixes**
	- Removed unnecessary checks for Hibernate proxy initialization, streamlining the process of fetching exercises with submission policies.
- **Refactor**
	- Updated method names and functionalities in `StudentExamRepository` and `ExamService` to accurately reflect the inclusion of submission policies in student exams and data exports.
	- Adjusted the `getStudentExam` method to utilize updated repository methods, ensuring the correct retrieval of student exams with submission policies.

### CODE REVIEW

**Review by tobias-lippert — APPROVED** [review]
LGTM

**Review by Strohgelaender — APPROVED** [review]

**Review by milljoniaer — APPROVED** [review]
demonstrated in testing session, still works as expected

**Review by rstief — APPROVED** [review]
Demonstrated in testing session 👍

**Review by mateusmm01 — APPROVED** [review]
Code lgtm. Also works as expected on ts2

**Pull request merged**
