### PR TITLE
`Quiz exercises`: Improve layout for short answer matching options

### PR DESCRIPTION
**Pull request by sunsetcoder**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Issue #5000 

It was "not clear that the two checkboxes and the slider affect the same underlying option about matching the answer text"
Also, it was not clear what the percent slider was used for.

### Description

We visually grouped the two checkboxes and the slider under a border, and placed a header "Answer Matching" to make it more obvious that these options are part of the same setting.
We also added a German translation string for the "Answer Matching" string.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Management
3. Click on Exercises
4. Click on Create Quiz
5. Click on "Add Short-Answer Question"

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

image

image

#### Before

Screenshot 2022-05-09 at 11 20 33

#### After

English UI:
image

German UI:
image

### CODE REVIEW

**Comment by ge65cer** [comment]
Thanks for your contribution! I've added “before” screenshots to your PR.

**Review by mallgaier — DISMISSED** [review]
Code changes look good to me.
Did not perform a test on the test-server, as it is currently blocked

**Review by willergeorg — APPROVED** [review]
Code looks reasonable to me.

**Review by akesfeden — COMMENTED** [review]
Code changes look reasonable but the client-style check fails, running `npm run prettier:write` might fix it.

**Review by Marvin-Vitcu — APPROVED** [review]
Couldn't test it on a testserver yet.
Code looks good.

One suggestion: I would use "case sensitive" instead of "Match Letter Case" as this is the standard phrase for that.

**Comment by sunsetcoder** [comment]
> Couldn't test it on a testserver yet. Code looks good.
> 
> One suggestion: I would use "case sensitive" instead of "Match Letter Case" as this is the standard phrase for that.

Thanks for your suggestion. 👍 I see what you're saying. However, I couldn't find any reference for a consensus or discussions on the web on that being a standard phrase so I checked popular apps such as Google Docs, Microsoft Word and Notepad++ which all use "Match case".

**Comment by sunsetcoder** [comment]
@ls1intum/artemis-maintainers   Requesting review and approval.

**Review by nadinesamyy — COMMENTED** [review]
Couldn't test it on a TS yet either, changes look good

**Comment by krusche** [comment]
The PR is open for longer than 2 months (which is bad practice). We should either merge this soon or close the PR.
@manuelmanso can you please take over?

**Pull request closed without merging**
