### PR TITLE
`Development`: Solve merge conflict breaking the course statistics

### PR DESCRIPTION
**Pull request by MDK5**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation, Context and Description
The combination of #4313 and #4296 left an import that breaks when it is lazily loaded and prevents the statistics page from opening.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 A course the student participates in and has results in exercises

1. Log in to Artemis
2. Enter a course by clicking on the corresponding course card in Course overview
3. Try to enter the statistics tab. This should now be possible again
4. Scroll down and inspect the Performance in Exercises chart. The lines should be visible and interacting with it should also be possible again

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

### CODE REVIEW

**Review by Malyuk-A — APPROVED** [review]
Tested on TS3. The Statistics Page works again and the graphs also work for me. Nice fix.
Code seems reasonable to me.

**Review by filip-gregurevic — APPROVED** [review]
Looks good to me

**Review by JohannesStoehr — APPROVED** [review]
Tested on TS3 and the page works again. Thanks for the fix

**Review by DanielKainz — APPROVED** [review]
I tested it on TS2. Everything works again as expected :-)

**Pull request merged**
