### PR TITLE
`Learning analytics`: Separate chart name and chart in course statistics to fix wrong line breaks

### PR DESCRIPTION
**Pull request by RY997**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

### Motivation and Context

This is a PR to solve issue #6192 
### Description

The issue stems from the fact that on some screen sizes the chart name takes up less space than a word in width. Reducing font size doesn't make much sense(screenshot 2) but separating chart name and chart is a straightforward way(screenshot 3).
### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Statistics
3. Check the chart names and charts are responsive

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

issue:
original
reduce the font size:
splitsmall
separate:
image

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Changes and screenshots look good to me

**Review by basak-akan — APPROVED** [review]
Tested on ts1. Works as expected 👍

**Review by terlan98 — APPROVED** [review]
Tested on TS2. Charts and chart names are responsive.

**Review by SolizerCodes — APPROVED** [review]
Looks good on ts5

**Comment by undernagruzez** [comment]
Looks good on ts5

**Review by DemjenDavid — APPROVED** [review]
Looks good on ts5

**Review by DominikRemo — APPROVED** [review]
Code LGTM

**Pull request merged**
