### PR TITLE
improve test coverage in TextAssessmentResource

### PR DESCRIPTION
**Pull request by PatZintel**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)

### Description

added tests in TextAssessmentIntegrationTest to improve code coverage in TextAssessmentResource,
also refactored TextAssessmentResource to use the new version of auth-checks where applicable

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Asses a Text Exercise submission

### Test Coverage

TestAssessmentResource: 92%

### CODE REVIEW

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 1. Everything worked for me.

**Review by willergeorg — APPROVED** [review]
Tested on TS2 and worked as expected.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Looks good

**Review by sinangunduz — APPROVED** [review]
tested on ts1, looks good.

**Review by canyelten — APPROVED** [review]
Tested on ts2, everything works fine.

**Review by katjanakosic — APPROVED** [review]
Worked fine on TS1!

**Review by krusche — APPROVED** [review]

**Pull request merged**
