### PR TITLE
`Quiz exercises`: Fix LTI Moodle quiz participation results reflection

### PR DESCRIPTION
**Pull request by basak-akan**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Currently, the grade reflection for quiz exercises between Artemis and Moodle via LTI integration is not functioning. As a result, grades are not being transferred or displayed on Moodle. This pull request fixes this issue by ensuring grades are accurately reflected in Moodle.

### Description

- New Results are sent to the external LMS platform with LtiNewService when the quiz is ended.
- Also re-calculated or re-evaluated quiz exercise results are also sent to external platform.
- A new test class is added to make it easier to handle and add new features in the future. It also creates a specific place to look at how quiz scores and LTI work together, without making the current test classes more complicated.

### Steps for Testing
Please test this PR with TS11. I already pre-configured quiz exercises for easy testing for TS11.

Prerequisites:
  - Use "Quiz Exercise" on moodle in LTI Testing Course.
  
- Moodle Login Credentials:
     | Test Server  | Username                   | Password                                                                           |
     | :------------ |    :--------                   |          :------------------------------------------------------ |
     | TS11      | artemis_test_user_1 | same as artemis_test_user_1 from artemis test accounts |
  
Artemis User Testing Steps:
1. Navigate to TS11 and start "Quiz Exercise" in "LTI Testing Course".
2. Navigate to Moodle: https://moodle.ase.in.tum.de/
3. Log in using the test user credentials.
4. Select the "Lti Testing Course".
5. Choose "Quiz Exercise" under Topic 2.
6. Confirm that you can view the Artemis page within the Moodle frame.
7. Through the Moodle frame, log in to Artemis using the same credentials.
8. Ensure you are logged into Artemis.
9. Initiate the quiz exercise participation.
10. Submit your solution.
12. Navigate to the Moodle grades page.
12. Confirm that your submission results are visible.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [course-lti-configuration.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5366/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/manage/course-lti-configuration/course-lti-configuration.component.ts.html) | 100% | ✅ |
| [lti13-exercise-launch.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5366/latest/artifact/shared/Coverage-Report-Client-Tests/app/lti/lti13-exercise-launch.component.ts.html) | 100% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [QuizStatisticService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5366/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/QuizStatisticService.html) | 88% | ✅  |
| [LtiService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5366/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.lti/LtiService.html) | 98% | ✅ |
| [QuizScheduleService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5366/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.scheduled.cache.quiz/QuizScheduleService.html) | 84% | ✅ |
| [PublicProgrammingSubmissionResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5366/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.open/PublicProgrammingSubmissionResource.html) | 96% | ✅  |

### Screenshots

image
image

### CODE REVIEW

**Review by laurenzfb — DISMISSED** [review]
testing session

**Review by milljoniaer — APPROVED** [review]
tested in testing session

**Review by lennart-keller — APPROVED** [review]
Tested in testing session

**Review by Kroko-fant — APPROVED** [review]
tested in a testing session earlier this week

**Review by RY997 — COMMENTED** [review]
Maybe I didn't do it in a right way, but I got this "refuse connect" in model.
I tried login Artemis as test user 1, but no exercise is visible. Then added myself into student group and started the quiz 1, opened moodle and got this.
image

**Comment by basak-akan** [comment]
> Maybe I didn't do it in a right way, but I got this "refuse connect" in model. I tried login Artemis as test user 1, but no exercise is visible. Then added myself into student group and started the quiz 1, opened moodle and got this. image

Thank you for noticing. With new changes, Lti profile needs to be added to servers to enable lti features. Since it is not yet added to TS5 (or other test servers) it refuses to connect. I will mark this PR as work in progress until the lti profile added to the test servers.

**Review by lennart-keller — APPROVED** [review]
Tested in testing session. Works well

**Review by vinceclifford — APPROVED** [review]
Works as expected. Tested during testing session

**Review by florian-glombik — APPROVED** [review]
Participating and practicing in the Quiz via Moodle worked fine!

**Review by laurenzfb — APPROVED** [review]
Code LGTM!

**Review by AntonGeTUM — APPROVED** [review]
Tested as per instructions, LGTM

**Review by RY997 — APPROVED** [review]
Approve!

**Pull request merged**
