### PR TITLE
Improve Code Coverage for Gitlab, Jenkins, Bamboo

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)

### Motivation and Context

Code coverage for Jenkins and Gitlab related files were fairly low and the goal is to get them to >= 80%

### Description

This PR improves the code coverage by:
-  re-writing various existing mocks in order to cover various exception handling code
- creating new mocks to cover new code
- add various new tests  
- minor refactoring of faulty code 

### Test Coverage

Global Jenkins coverage: 87%
Global Gitlab coverage: 82%
Global Bamboo coverage: 88%

BambooService.java 84%
JenkinsBuildPlanService.java 93%
JenkinsService.java 79%
ProgrammingExerciseImportService.java 96%
ProgrammingSubmissionService.java 74%
ProgrammingExerciseResource.java 83%

### CODE REVIEW

**Review by ivohashamov — APPROVED** [review]
Code looks good!

**Review by FrankeLukas — APPROVED** [review]
Code changes lgtm on a cursory glance and the tests pass.

**Review by nicolasruscher — APPROVED** [review]
Approving 👍

**Review by krusche — APPROVED** [review]
Production code changes look good. Thanks for increasing the test coverage 👍

**Pull request merged**
