### PR TITLE
added time details for student review to exam summary

### PR DESCRIPTION
**Pull request by SimonEntholzer**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

resolves https://github.com/ls1intum/Artemis/issues/1923

In the exam summary students could not see the time when they could review and create complaints. The date/times are shown now, also a tag that shows that the review is open.

### Description

image

### Steps for Testing

1. check the exam summary of a student. When the exam is over (and the instructor set review times) you are able to see the review time, and when you are in the review time you can see an "review is open" tag.
2. when the exam is not over yet, you should not be able to see the info about the review in the heading.
--> 
image

### CODE REVIEW

**Review by krusche — CHANGES_REQUESTED** [review]
I don't really like the date format. Why do you have a `-` in it?
Can we use a standardized date format? I think the `artemisDate` pipe also support a format with date + time

**Comment by SimonEntholzer** [comment]
> I don't really like the date format. Why do you have a `-` in it?
> Can we use a standardized date format? I think the `artemisDate` pipe also support a format with date + time

I changed it, now it only uses one pipe. (see the new screenshot)

**Review by airelawaleria — APPROVED** [review]
all worked as described :)

**Review by simonzilker — APPROVED** [review]
Looks good :)

**Review by marvinchimeka — APPROVED** [review]
👍

**Review by JohannesWeiss — APPROVED** [review]
Works as intended.

**Review by krusche — APPROVED** [review]

**Pull request merged**
