### PR TITLE
`Programming exercises`: Don't show participation buttons if repository is not available

### PR DESCRIPTION
**Pull request by reschandreas**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

After our migration from Bitbucket to LocalVC it could happen that some participations have no `repositoryUri`, to counter this and prevent confusion in the UI for students, we don't show buttons related to repositories, if the participation has no repo.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise

1. Log in to Artemis as a student
2. Open a participation of a programming exercise
3. Open your database and find your participation, remove the uri with `update participation set repository_url = NULL where id = <your-participation-id>;`
4. Reload the page, the buttons should be gone, the participation is now also not working anymore, so delete it to have a consistent state of your dev environment.

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

correct_with_buttons
no_buttons

## Summary by CodeRabbit

- **New Features**
	- Improved the display logic for certain buttons in the exercise details, ensuring they are shown only when relevant information is available.

### CODE REVIEW

**Review by milljoniaer — APPROVED** [review]
Code looks good 👍

**Review by laurenzfb — APPROVED** [review]
code lgtm

**Comment by Strohgelaender** [comment]
How likely is this to happen? I'd like to add some information here to explain why nothing is shown. Just an empty field could confuse students trying to access their submissions.

**Comment by reschandreas** [comment]
Hi @Strohgelaender, It is very unlikely; after testing the migration with a production database dump, around 0,2% of the repositories could not be migrated. And I'd wager that those repositories are old and that a student will unlikely revisit their exercise from several years prior.

**Review by Strohgelaender — APPROVED** [review]

**Review by pzdr7 — APPROVED** [review]
Tested locally. The buttons no longer show up when the repository_url is null. -> Works as expected!

**Pull request merged**
