### PR TITLE
`Communication`: Reduce height of channel and chat item card

### PR DESCRIPTION
**Pull request by rabeatwork**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The cards for the channels and chats had a lot of margin. As a result, only a few fit on one page, and there was a lot of scrolling. The height/padding has been reduced.

### Description
The margin for the communication sidebar items has been reduced.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Course with Communication enabled 

1. Log in to Artemis
2. Navigate to Course Communication
3. See Sidebar with Channels / Chats 
4. Verify that the Channel Chats are smaller 
5. Navigate to Exercises / Lectures
6. Verify that everything looks like before

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

Before: 
image

After: 
image

## Summary by CodeRabbit

- **Style**
	- Improved button alignment and spacing in the sidebar components for a more consistent user interface.
	- Adjusted rendering logic for sidebar items based on their type to enhance layout consistency.

- **New Features**
	- Introduced conditional rendering for sidebar items, improving user interaction based on the sidebar type.

### CODE REVIEW

**Review by sachmii — COMMENTED** [review]
I tested on TS2 but could not reproduce the small change. I compared the card margin size on TS2 with my personal account in production but could not notice any difference.

**Comment by sachmii** [comment]
Tested on TS6 and TS2, card margins in the communication tab are smaller as described.

**Review by sachmii — APPROVED** [review]
Tested on TS6 and TS2, card margins in the communication tab are smaller as described.

**Review by az108 — APPROVED** [review]
Code LGTM 👍

**Review by florian-glombik — APPROVED** [review]
The code looks good to me 👍

**Review by cremertim — APPROVED** [review]
tested on ts2, works as expected

**Review by edkaya — APPROVED** [review]
Tested on ts2, works as expected

**Review by HawKhiem — APPROVED** [review]
I tested on test server 1. Bars are indeed smaller as expected.

Screenshot 2024-10-16 161151

**Pull request merged**
