### PR TITLE
`Modeling exercises`: Improve grid appearance for Apollon models

### PR DESCRIPTION
**Pull request by minrows**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context
This PR simply changes the grid color of Apollon in Artemis. 
With the changed color, the bigger grid looks more distinguished than the smaller ones.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a Modeling exercise for any one of the exercises
4. Observe that the bigger grid of the canvas is distinguished from smaller grids (as illustrated in the screenshot section below).

#### Code Review
- [x] Review 1
- [x] Review 2

#### Before
image
#### After
image

### CODE REVIEW

**Comment by Strohgelaender** [comment]
How does it look in the dark mode? We should avoid hardcoded colors in the stylesheet and use variables instead. See https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/

**Comment by minrows** [comment]
> How does it look in the dark mode? We should avoid hardcoded colors in the stylesheet and use variables instead. See https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/

As discussed with @krusche, the change is only for the grid of light mode.
And regarding the hardcoded value, since the default value of `$apollon-background-variant` needed to be changed, I did it that way.

**Comment by minrows** [comment]
> 

Yes. The change is only for light mode.

**Comment by minrows** [comment]
> This only changes the color in the light mode. Is this expected, should the darkmode remain unchanged?
Yes. The change is only for light mode.

**Review by Strohgelaender — APPROVED** [review]

**Review by ge65cer — APPROVED** [review]
Tested locally, looks better. 🙂

**Review by dangcosta — APPROVED** [review]
Also tested locally, it looks fine.

**Review by manuelmanso — APPROVED** [review]
Looks better 👍

**Review by stefanwaldhauser — APPROVED** [review]
Looks good!

**Pull request merged**
