### PR TITLE
[Feature] - Add export button for quizzes in exam exercise row

### PR DESCRIPTION
**Pull request by FuchsDominik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

After creating a good quiz exercise, a instructor would sometimes like to export the quiz exercise. This is not possible yet.

### Description

- Added a button in the exam exercise row where it is possible to download a json, containing the quiz exercise(s) information
### Steps for Testing

1. Log in to Artemis
2. Create new exam with a exercise group containing a quiz exam
3. Make sure it is possible to click "Export" on the right hand side (see screenshot) und that the json file is a correct containing the information of the quiz

### Screenshots

Screenshot 2021-02-14 at 16 46 24

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
worked fine on ts1

**Review by valeriebucher — APPROVED** [review]
Works as expected!

**Review by EneaGore — APPROVED** [review]
Looks good on ts1

**Review by JohannesWeiss — APPROVED** [review]
Works as expected on ts1

**Review by simonzilker — APPROVED** [review]
Works fine :)

**Review by marvinchimeka — APPROVED** [review]
No issues found.

**Review by JannisBittlmayer — APPROVED** [review]
Works as expected

**Review by FlorianStang — APPROVED** [review]
Worked as intended

**Pull request merged**
