### PR TITLE
`Programming exercises`: Speed up build log statistics

### PR DESCRIPTION
**Pull request by krusche**
Mostly reviewing is needed in this PR

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context
There was a slow query which was also incorrect. I fixed it and made it significantly faster.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise

1. Run a couple of template, solution and student builds
2. Open the programming exercise details.
3. Make sure the build logs are calculated and make sense

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
  - Enhanced build log statistics query performance and accuracy for programming exercises.

- **Refactor**
  - Updated `BuildLogStatisticsEntryRepository` with improved query methods.
  - Simplified `BuildLogStatisticsDTO` into a more concise record format.
  - Adjusted test cases to align with the refactored `BuildLogStatisticsDTO` usage and method naming conventions.

- **Documentation**
  - Added comments explaining the use of multiple queries for performance optimization in build log statistics retrieval.

### CODE REVIEW

**Review by bassner — APPROVED** [review]
Tested on TS2, seems to work. Code LGTM 👍

**Review by rstief — APPROVED** [review]
Code looks good 👍

**Review by marlon-luca-bu — APPROVED** [review]
Code LGTM 👍

**Review by RY997 — APPROVED** [review]
Tested on TS2, worked as expected

**Pull request merged**
