### PR TITLE
`Exam mode`: Improve import icons in exercise group overview

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

#6599 changed the icons for the import buttons from a plus to an icon symbolizing the import. This should also apply to the exercise groups in exams.

### Description

Change the faPlus to faFileImport in the exercise groups for all import buttons.

#### Exam Mode Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Create or find an exam
3. Navigate to the exercise groups and create one if none are existent
4. Look at the icons if they are suiting for each button

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Bildschirmfoto 2023-07-16 um 16 07 35

### CODE REVIEW

**Comment by Strohgelaender** [comment]
Looks good, you can now distinguish the add and import buttons even on smaller screens:

grafik

However, as you can see above the "Import File Upload Exercise" button uses the quiz exercise icon in the small mode, can you fix that directly?

**Review by SolizerCodes — APPROVED** [review]
Looks good on ts6

**Review by eceeeren — APPROVED** [review]
Tested on TS1, works well!

**Review by MichaelOwenDyer — APPROVED** [review]
Changes look good to me

**Review by DemjenDavid — APPROVED** [review]
tested on ts3 i think it looks great, the icons make sense

**Review by fschoenberger — APPROVED** [review]
Tested on TS1, looks good!

**Review by laadvo — APPROVED** [review]
code looks good to me :+1:

**Review by Mtze — APPROVED** [review]

**Pull request merged**
