### PR TITLE
`Adaptive learning`: Improve layout of competency relation graph

### PR DESCRIPTION
**Pull request by rstief**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
The relation graph had some shortcomings that were fixed in this PR.

### Description
- Removed the long overdue `BETA` label from the relation graph
- Improved layout of create relation form
- Added zoom function & center button
- Added a minimap
- Added a delete confirmation for relations (before they would just be deleted by clicking on them)

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Management -> Competencies
3. Create competencies if none exist
4. See that the relation graph now supports zooming
5. Create relations if none exist
6. Delete a relation (click on its text)
7. See that a confirmation dialog shows up

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [competency-management.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6455/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/competencies/competency-management/competency-management.component.ts.html) | 92.56% | ✅  |
| [competency-relation-graph.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6455/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/competencies/competency-management/competency-relation-graph.component.ts.html) | 93.39% | ✅  |

### Screenshots
image

## Summary by CodeRabbit

- **New Features**
  - Enhanced the competency management interface with better event handling and a new button to center the competency relation graph view.
  - Added a mini-map feature to the competency relation graph for improved navigation.
- **Enhancements**
  - Updated the layout and interactive elements of the competency relation graph.
- **Internationalization**
  - Introduced new localization keys for deletion confirmation in German and English.
- **Bug Fixes**
  - Improved the removal process of competency relations with added confirmation steps.
- **Tests**
  - Extended test coverage for competency management functionalities, including graph centering and relation removal.

### CODE REVIEW

**Review by mateusmm01 — APPROVED** [review]
Demonstrated in testing session. Worked as expected

**Review by laurenzfb — APPROVED** [review]
demonstrated in testing session, looks good

**Review by florian-glombik — APPROVED** [review]
Tested together on ts1, worked as described 

The code looks good to me aswell

**Review by JohannesWt — APPROVED** [review]
Code looks good

**Pull request merged**
