### PR TITLE
`General`: Make markdown editor buttons more compact

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The height of the buttons above the markdown editor for writing messages/posts are unnecessarily high.

### Description

I removed some margin and padding to reduce the height of the buttons.

### Steps for Testing

Prerequisites:
- None

1. Log in to Artemis as any user
2. Check the markdown editor everywhere where you can write messages/posts

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

Same as develop
### Screenshots

before:
before

after:
after

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
tested in testing session, works. Code looks good.

**Review by JohannesStoehr — APPROVED** [review]
Editor looks good to me in different places and code changes also look good to me

**Review by tobias-lippert — APPROVED** [review]
Tested in testing session, looks good.

**Review by rriyaldhi — APPROVED** [review]
Code changes look good.

**Pull request merged**
