### PR TITLE
`Quiz exercises`: Correct drop location computation

### PR DESCRIPTION
**Pull request by matthiaslehnertum**
This PR corrects the calculation of drop locations for quiz exercises and adds unit tests to ensure correct computation.

#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context
The static offset that was used to calculate the drop location of an answer option for quiz exercises is no longer necessary due to the update SVG export in the Apollon modeling editor. This changes removes the no longer needed offset and adds integration tests to ensure correct calculation.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Create an UML DnD Quiz
2. Participate/preview it
3. In the hole process (creation and participation) the drop locations should be placed exactly where you'd expect them to be on the background.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
	- Enhanced the quiz exercise generator for more external accessibility and utility.

- **Bug Fixes**
	- Minor logic adjustments for improved file handling in quiz exercises.
	- Removed unnecessary console logs for cleaner operation.

- **Tests**
	- Expanded testing for quiz exercise generation, ensuring reliability and performance.

### CODE REVIEW

**Review by julian-christl — APPROVED** [review]
Tested on TS3, works beautifully

**Review by milljoniaer — APPROVED** [review]
Code looks good 👍

**Review by basak-akan — APPROVED** [review]
Tested on TS2, worked as expected 👍

**Review by muradium — APPROVED** [review]
Tested on TS2, works correctly 👍

**Review by Santia-go — APPROVED** [review]
Tested on TS3 

Working as expected. 🙌🏻

A follow up PR would be to add a button to close this notification and comeback to the exercises page or home page. Or the countdown until the Quiz end. 

image

**Pull request merged**
