### PR TITLE
`Learning path`: Introduce loading spinner for navigation between learning objects

### PR DESCRIPTION
**Pull request by JohannesWt**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Although loading times when navigating between adjacent learning objects within the learning path feature are already quite fast, there is still a brief period where the user does not receive any visual feedback indicating that the system is loading or processing.

### Description

This PR adds a small loading spinner next to the navigation buttons to inform the user when the system is loading the next or previous learning object. Additionally, the tests for the learning path navigation have been refactored for improved accuracy.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- at least one competency with at least two learning objects

1. Log in to Artemis
2. Navigate to the learning path student view
3. Navigate between the learning objects
4. verify that you see a small loading spinner within the "Previous" respectively "Next" Button when loading the next learning object 

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| learning-path-student-nav.component.ts | 100% | ✅ |
| learning-path-navigation.service.ts | 100% | ✅ |

### Screenshots

Screen Recording 2024-10-21 at 08 15 51

## Release Notes

- **New Features**
  - Enhanced navigation buttons with loading indicators for improved user feedback.
  - Updated interaction logic for selecting learning objects.

- **Bug Fixes**
  - Resolved issues with button functionality during loading states.

- **Style**
  - Improved visual appearance of dropdown menus and loading icons.

- **Tests**
  - Updated test suite to reflect changes in navigation service and component behavior.

### CODE REVIEW

**Review by SindiBuklaji — APPROVED** [review]
Tested on TS4. Everything works as described & expected. 👍

**Review by pzdr7 — APPROVED** [review]
Code looks good 👍

**Review by raffifasaro — APPROVED** [review]
Code LGTM

**Review by sachmii — APPROVED** [review]
Tested on TS5, works as described, I like the small change :)

**Review by HawKhiem — APPROVED** [review]
Tested on TS3. I can see the loading icon upon clicking on Next and Previous.

**Review by kevinfischer4 — COMMENTED** [review]
Tested on TS5. Works as expected, cool little detail.

**Review by zagemello — COMMENTED** [review]
image


Tested on TS6, spinner worked correctly and was able to switch between parts of the learning path

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS5. Works as expected, nice detail

**Review by MaximilianAnzinger — APPROVED** [review]
Maintainer approved

**Review by bassner — APPROVED** [review]

**Pull request merged**
