### PR TITLE
`Development`: Deprecate external services for Bitbucket, Bamboo and JIRA

### PR DESCRIPTION
**Pull request by krusche**
#### General
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
Starting with the next major release 7.0.0, we will not support Bitbucket, Bamboo and JIRA anymore, therefore the corresponding classes are marked as deprecated.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

## Summary by CodeRabbit

- **Deprecations**
	- Marked various classes and methods related to Bamboo, Bitbucket, and Jira integration as deprecated, indicating their removal in version 7.0.0. This includes classes for authorization, service connectors, DTOs, and exception handling specific to these integrations.

### CODE REVIEW

**Review by laurenzfb — APPROVED** [review]
lgtm

**Review by bensofficial — APPROVED** [review]
Changes look good to me

**Review by rstief — APPROVED** [review]
Changes look good 👍 It also quickly checked and it seems all Atlassian classes are now deprecated

**Review by bassner — APPROVED** [review]

**Review by Hialus — APPROVED** [review]
Looks good, but it may also make sense adding a small note in the Docs and adapting the mentions in the README

**Pull request merged**
