### PR TITLE
[Small Fix] Removing Whitespace on Student Exercise View

### PR DESCRIPTION
**Pull request by niclasschuemann**
### Motivation and Context
When setting bonus points for exercises, the student exercise page view contains an additional whitespace character, that shouldn't be there.

### Description
I removed the whitespace

### Steps for Testing
1. Create an arbitrary exercise with an arbitrary amount of regular points and bonus points 
2. Go to the student exercise view and ensure that the additional whitespace is gone

### Screenshots
**Previously:**
bad

**Now:**
better

### CODE REVIEW

**Review by ivanchimeno — APPROVED** [review]

**Review by FlorianGlombik — APPROVED** [review]
A small change that looks good.

**Review by lschlesinger — APPROVED** [review]
For the sake of completeness: tested on TS1. Worked 😄

**Review by Malyuk-A — APPROVED** [review]
Also works on TS3 😉

**Review by ndricimrr — APPROVED** [review]
a small whitespace for man, a giant leap for Codacy 👍 🚀

**Review by FuchsDominik — APPROVED** [review]

**Review by argertboja — APPROVED** [review]
I can see no space on TS1 😄

**Review by Olimbia23 — APPROVED** [review]

**Review by iozbeyli — APPROVED** [review]
Code looks good

**Review by FrankeLukas — APPROVED** [review]

**Review by ivohashamov — APPROVED** [review]

**Review by ArtemTsurikov — APPROVED** [review]
Nice ;)

**Pull request merged**
