### PR TITLE
[Enhancement] Fixing Documentation Typos/Inaccuracies

### PR DESCRIPTION
**Pull request by niclasschuemann**
### Motivation and Context
While setting up my local Atlassian setup again (after I broke it) I noticed a few typos on the respective documentation page. 

### Description
I fixed the typos on the respective page and used the IntelliJ spell-checker to find and fix additional typos in the documentation.

### Review
Since I have changed nothing besides some words in the documentation, a code review should be sufficient.

### CODE REVIEW

**Review by ndricimrr — DISMISSED** [review]
Documentation changes look good 👍

**Review by Malyuk-A — DISMISSED** [review]
Looks good 👍

**Review by joschahenningsen — APPROVED** [review]
Great addition :+1:

**Review by FuchsDominik — DISMISSED** [review]
All looks good 👍

**Review by argertboja — DISMISSED** [review]
Changes look good 👍🏼

**Review by FlorianGlombik — DISMISSED** [review]
Removed some typos and inconsistencies.

**Review by coolchock — APPROVED** [review]
looks good 👍

**Review by MDK5 — DISMISSED** [review]
Changes look good to me, only found one nitpick

**Review by jhainzlschmid — DISMISSED** [review]
Looks good

**Review by ivanchimeno — APPROVED** [review]

**Review by ivohashamov — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
