### PR TITLE
Improve deletion process of temporary git repositories after plagiarism checks

### PR DESCRIPTION
**Pull request by krusche**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context
Improve deletion process of temporary git repositories after plagiarism checks

### Description
* Artemis keeps the repository references of JGit instead of creating new ones (and pulling again changes) just for the deletion
*  The deletion is triggered async (10s later) so that the user initiating the plagiarism check does not need to wait for the deletion process, which can take a couple of seconds or minutes for exercises with many (>2000) students.

### Steps for Testing
1. Participate in a programming exercises at least with 5 student accounts
2. Make sure to add significant similar code (e.g. the solution to the MergeSort algorithm) for all participants
3. Navigate to the programming exercise view page and click on Check plagiarism, try out both scenarios (with and without `Generate JPlag Report`) multiple times. Wait at least 10s after the last successful check so that the Artemis server can cleanup the git repositories.

Check that no errors occur in the client (console) and check that the zip file includes a proper plagiarism report (`Generate JPlag Report` active) or Artemis shows the plagiarism cases directly in the browser in the inspector

In case you have access to the server: 
* check that there are no errors or warnings
* check that all artifacts are removed in the `repos-download` folder (10s for the git repos, 1min for the zip file when `Generate JPlag Report` is active)

### Test Coverage
no changes

### Screenshots

image

image

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested with @JohannesWeiss, @marvinchimeka @simonzilker on ts1. Have no access to server

**Review by JohannesWeiss — APPROVED** [review]
Tested multiple times in testing session, worked as intended. Only client tested, as @airelawaleria mentioned.

**Review by simonzilker — APPROVED** [review]
Tested in testing session. Approve!

**Review by marvinchimeka — APPROVED** [review]
tested in a testing session on ts1. I do not have access to server so I could not test that part of the pr but everything else works fine.

**Review by EneaGore — APPROVED** [review]
Tested on ts 1, approve. No access to server.

**Review by philippbauch — APPROVED** [review]
Code changes look good to me!

**Comment by krusche** [comment]
Thanks for testing

**Pull request merged**
