### PR TITLE
[Feature] Hide Future Lectures

### PR DESCRIPTION
**Pull request by JohannesStoehr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context

Some lecturers already create the lectures and upload the material at the start of the semester. This leads to the problem that the current week of the lecture is hidden below many unreleased lectures.

### Description

This PR changes the behavior of the lectures overview, so that only the current week is not collapsed when loading the lecture overview.

### Steps for Testing

1. Log in to Artemis
2. Create three lectures. One that is at least one week old, one that is in the current week, one that is in some future week
3. Navigate to the lecture overview from the student's perspective
4. Make sure that only the current week is expanded. All previous and future weeks should be collapsed

### Screenshots

Old standard view:
Bildschirmfoto 2021-05-13 um 17 36 34
New standard view:
Bildschirmfoto 2021-05-13 um 17 36 47

### CODE REVIEW

**Review by FuchsDominik — APPROVED** [review]
Works 👍

**Review by willergeorg — APPROVED** [review]
Tested on TS2. Worked for me.

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 2. Everything worked as expected.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Worked as expected

**Review by cremertim — APPROVED** [review]
tested on ts1. works as expected

**Review by KiraNickel — APPROVED** [review]
Tested on ts1. Works as expected 👍🏼

**Review by canyelten — APPROVED** [review]
Tested on TS1. Works as expected.

**Review by niclasschuemann — APPROVED** [review]

**Review by florian-glombik — DISMISSED** [review]

**Review by florian-glombik — APPROVED** [review]
Tested it on ts1, only the lecture of the current week is uncollapsed 👍

**Pull request merged**
