### PR TITLE
`General`: Show invalid input in forms related to user management

### LINKED ISSUE #4916: Password reset and register not possible for realy long passwords
### Describe the bug

Internal user managment fails with confusing message if password is too long

### To Reproduce

1. Go to register or reset password
2. Try using a super long password e.g.
arfeshbsfghbasdfghsdfgsdfgsfdghsrfghsfdhgbsdfghbsdfghsdfhbfsdfgbasdffhgsdghsrghd
3. Try and fail

### Expected behavior

UI warns you about password being to long, sets a limit

### Screenshots

image

### What browsers are you seeing the problem on?

Chrome

### Additional context

...

### Relevant log output

```shell
artemis          | 2022-04-08 20:47:43.635  WARN 1 --- [-8080-exec-1366] o.z.problem.spring.common.AdviceTraits   : Bad Request: Incorrect password

Network request return:
{
  "type": "https://www.jhipster.tech/problem/invalid-password",
  "title": "Incorrect password",
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by Dominik-Weinzierl**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Closes #4916 (in addition, i also checked if the server validates the length -> looks good)
And as a user/admin, it is sometimes difficult to know the limitations of some inputs. Therefore, this PR shows the requirements of some input fields when adding/creating new users.

### Description

In order to validate the inputs and show the results to the user, we need to use a `formGroup` which contains all inputs (`editForm` in [user-management-update.component.ts](https://github.com/ls1intum/Artemis/pull/5018/files#diff-df49c8bbcd95ce6b0695f83932ab705c08f4adda416eac41fc1868f2c9257366)). In addition, I also extracted some hard coded values in variables (e.g. `EMAIL_MIN_LENGTH`, ...). In order to highlight the required fields, we needed to add `required` to the `<inputs/>`s and use the validators.

### Steps for Testing

Prerequisites:
- 1 Admin

1. Log in to Artemis
2. Navigate to User Management (`admin/user-management`)
3. Create a new User and verify the required fields (e.g. firstName/lastName is required by Bitbucket)
4. Navigate to Password Settings (`/account/password`)
5. Check if the maximum length works as expected 

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test coverage
_not changed_
| Class/File | Branch | Line |
|------------|-------:|-----:|
| user-management-update.component.ts | 68.33% |  91.95% |

### Screenshots

<details>
<summary>Videos</summary>

https://user-images.githubusercontent.com/60005702/166658221-c37953f5-5636-4567-9d61-f7699c357042.mp4

https://user-images.githubusercontent.com/60005702/166658504-75fc370f-c915-4c67-94e5-38a7c8859efb.mp4
</details>

### CODE REVIEW

**Comment by bottbenj** [comment]
Semi-related issue: when using external user management it is possible to have users with passwords that don't fulfill Artemis password requirements and those users cannot login to artemis, but i am not sure if that issue should be fixed by this PR or even in general.

**Comment by Dominik-Weinzierl** [comment]
Good point. I guess it would be better to fix this issue in general and rethink the password policy (or allow custom password policies e.g. as regex in a config file)

**Review by TheTrueVester — DISMISSED** [review]
Tested on ts2. Everything worked as described. The save button is however not grayed out and unclickable when the password entry is empty. Clicking it however just returns "Field translation-not-found[artemisApp.managedUserVM.password] does not meet min/max size requirements!"
Consider changing this if you want

**Comment by Dominik-Weinzierl** [comment]
@TheTrueVester good catch - i wasn't able to reproduce this error message, but this should solve this issue (if the button is not enabled via inspect element)

https://user-images.githubusercontent.com/60005702/166685122-ca77ae09-d8a1-415b-8ce9-cef5b94985a8.mp4

**Review by bassner — CHANGES_REQUESTED** [review]
Could we show warnings for too short passwords and too short logins as well like it's done for the e-mail? I think it could be confusing if the fields are just marked red without an explanation...

image

**Comment by Dominik-Weinzierl** [comment]
@bassner Good idea :+1: Thank you. I reused the existing translations :+1: 
image

**Review by Hialus — CHANGES_REQUESTED** [review]
Tested locally and it works as described. Text fields are highlighted in red when the input is invalid and the reason is given underneath. 
I have one remark however: Why is there a distinction between "This field is required to be at least x characters" + "This field cannot be longer than y characters." and "The password must contain x to y characters"? You should be consistent in the formatting of the messages.

**Comment by Dominik-Weinzierl** [comment]
Mhm, yes - you are right. As I mentioned in another comment, I left the translations as they were before. But for the sake of consistency, let's use the most common translation (less translations -> reusability) :+1: 

image

**Review by Hialus — APPROVED** [review]
Just saw your other comment and I agree that such things should probably be fixed in general.
But thanks for including my suggestion. Retested locally and still works as expected. Code also looks good to me.
Approved 👍🏻

**Review by jbllhff — APPROVED** [review]
Tested on ts2. Maximum length feature works as expected.

**Comment by jbllhff** [comment]
One additional comment though, which is probably not concerning you. When logged in as an admin, I was prompted to the login page again despite being already logged in and being able to access all the pages.

**Review by bottbenj — APPROVED** [review]
Code looks good to me and found no issues other than that the whole code is fundamentally not unicode aware and thus when you start using non-ascii characters the length requirements quickly become rather nonsensical, but that is another can of worms.

**Comment by bottbenj** [comment]
Are you sure you don't have an extra space or something like that in the search field? It does work correctly for me.

**Review by bassner — APPROVED** [review]
LGTM! 👍

**Pull request merged**
