### PR TITLE
Fix submission links from the participations component

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

The link does not work at the moment.

### Description

We had decided to remove the `/submissions` suffix from the exam routes but didn't account for this more hidden case. This is fixed now. Edit: Also includes some consistency improvements from #3058 now. The Submission page wasn't linking to exam routes before.

### Steps for Testing

1. Go to the participations of an exam exercise
2. Open a submission
3. Check that the same still works for non-exam exercises
4. Repeat the same steps with the submissions page of an exercise (exam and non-exam)

### Screenshots

The following links should work for exams now too:
- Participations page:
grafik
- Submissions page:
grafik

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS1, and works as expected now.
The code looks good too, route changes make sense :+1:

**Review by ivohashamov — APPROVED** [review]
Tested on ts1, works as intended

**Review by FuchsDominik — APPROVED** [review]
Tested and participation- and submission-links all worked for all exercises in an exam. Code looks good to me as well

**Review by nicolasruscher — APPROVED** [review]
Code looks good!

**Pull request merged**
