### PR TITLE
[Bugfix] Fix client-side miscalculation of total score during the assessment of modeling submission

### LINKED ISSUE #3633: Client Side Calculation of Points is wrong (using Grading Instructions)
### Describe the bug

When using structured grading criterias, which are limited in the number of times granting points, the client displays the wrong point number.

Example:
You have an grading instruction being limited to use 3 times, however if you drag and drop it 4 times into the assesment, the client will display 4 points instead of 3. 

The number of points of the assesment is correct when submitting it. You can verify this by reloading the page (in the example, the assesment has 3 points after submitting it)

### To Reproduce

1. Go to an assesment of a submission
2. Drag in a grading instruction which is limited in the usage count more often
3. See the displayed points before submitting 
4. Submit the assesment
5. Reload the assesment
6. See the proper points

### Expected behavior

The client should calcutlate the points properly. This avoids wrong assesments

### Screenshots

https://user-images.githubusercontent.com/65229601/123510916-74e01d00-d67e-11eb-8114-a0ffe67c4a89.mp4

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by imstreetspirit**
### Motivation and Context

We introduced `dropInfo` for the assessment object with this [PR](https://github.com/ls1intum/Apollon/pull/165). We only passed grading instruction id for this property. After dropping the grading instruction into UML element feedback, we only know `instructionId` in Artemis side. This cause  a problem to calculate the total score in the client side. Because, grading instructions have `usage count`. since we only passed the `grading instruction id`, the `usage count` returns `undefined` during the calculation (`calculateScoreForGradingInstructions` in `StructuredGradingCriterionService`). In Apollon side, my solution is setting the `dropInfo` with instruction itself.  Artemis can calculate the total score for all feedback elements properly.  

This PR aims to fix #3633. The issue is introduced on modeling assessment. I checked the other feedback elements (unreferenced feedback/text block feedback/inline-editor-feedback) using the grading instruction which has usage count. Total score is computed wrong only in modeling assessment. However, anyone can confirm that this is happening during the modeling submission assessment. 

PR will be updated after Apollon version update. => _**Updated**_

### Steps for Testing

For more details, you can check the screencast in the issue description.

1. Log in to Artemis
2. Navigate to Course Administration
3. Create/Find Modeling Exercise with Structured Grading Instructions
4. Define usage count for grading instruction.
5. Add an submission as a student.
6. As an instructor, go to Assessment Dashboard and Open the assessment.
7. Assess UML elements with grading instruction (you can drag & drop the instruction into the UML element)
8. Do not submit it, because server side calculation works, this is only for client side calculation. 
9. See that total score does not include the instruction credits anymore when it reaches the usage limit.

You can try this for other type of exercises(Text/File Upload/Programming with manual assessment). I did not encounter with this issue, and it needs to be confirmed.

### Test Coverage

nothings changed

### CODE REVIEW

**Review by MDK5 — DISMISSED** [review]
Tested in testing session on ts1, worked correctly

**Review by iozbeyli — APPROVED** [review]
Tested in test session

**Review by ndricimrr — APPROVED** [review]
Tested on TS1. Worked as expected.

**Review by sinangunduz — DISMISSED** [review]
tested on ts1, works as expected

**Review by ndricimrr — APPROVED** [review]
Tested again on TS1. Worked as expected.

**Review by NicolasUllmann — APPROVED** [review]
Tested on TS1. Everything worked as expected.

**Pull request merged**
