### PR TITLE
`Development`: Add support for Apollon 3

### PR DESCRIPTION
**Pull request by matthiaslehnertum**
This PR updates the version of Apollon used in Artemis to 3.0.0. This Apollon update adapts the format how diagrams are stored, adds support BPMN diagrams in a beta version and allows user to zoom in and out on the canvas.

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
This PR is intended to update Artemis with the latest version of Apollon.

### Steps for Testing
When testing this change, the following 4 areas are critical. 

- [x] 1. Modeling by student in course and exam exercises
- [x] 2. Creation of example solution by instructors
- [x] 3. Assessment of a model by tutors
- [x] 4. Creation of a quiz drag and drop exercises by instructors

For all these, it should be ensured if Artemis still behaves as expected in regards to the Apollon integration and if the zoom-in and zoom-out functionalities are available and operating as expected on the Apollon canvas. Additionally, BPMN diagrams should be available for creation but marked as still in beta.

### CODE REVIEW

**Comment by milljoniaer** [comment]
Somehow the deployment through github doesnt work. Maybe you have to update your branch?
There are some Merge conflicts which have to be resolved beforehand.

**Comment by florian-glombik** [comment]
Blocked by another issue found during the testing session, the assessment does not seem to work for modeling exercises

image

**Review by florian-glombik — CHANGES_REQUESTED** [review]
The issue mentioned in https://github.com/ls1intum/Artemis/pull/7419#issuecomment-1790845991 seems to arise from this PR, I could not reproduce it on `develop` but when using this branch.

The exercise stays in a broken state, which is why we thought it would also be broken on develop.

**Comment by loreanvictor** [comment]
> The issue #7484 mentioned in [#7419 (comment)](https://github.com/ls1intum/Artemis/pull/7419#issuecomment-1790845991) seems to arise from this PR, I could not reproduce it on `develop` but when using this branch.
> 
> The exercise stays in a broken state, which is why we thought it would also be broken on develop.

This issue should be fixed now. It was caused by the UML parser not being able to parse diagrams created with Apollon v3, so I restructured the parser into separate parsers based on version, meaning everything should work fine with both V2 models and V3 models.

**Pull request merged**
