### PR TITLE
`Exam mode`: Update exam scores table according to filter configuration

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

The exam scores page provides two filter options that can be selected separately: Include only submitted exams and include only exams with at least one submission. These filter options are currently only applied to the charts on this page, but not on the table right below the filter options. This is changed by this PR.
### Description

I reworked the structure containing the values of the table and added the necessary variants of the statistical values that are shown by the table. Finally, I added methods that update the table state according to the current filter option.
### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam with participation
**Before deploying this PR**: Inspect the table of the exam scores and take a screenshot. This might help you to confirm that the same data is displayed per default.

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to the scores page of the corresponding exam
4. Check the table content. Make sure that still the same data is displayed
5. Play around with the filters. Make sure that the table content changes if appropriate. The easiest cases would be the percentage of passed or submitted exams if you choose a filter.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| File name | Branch coverage (%) | Line coverage (%) |
| -- | -- | -- |
| `exam-scores.component.ts` | 83.72 | 97.62 |

### Screenshots

Default state:
image

Include only submitted exams:
image

Include only non empty submissions:
image

Both filters active:
image

### CODE REVIEW

**Review by canberkanar — APPROVED** [review]
Tested on ts3 in accordance to the instructions. The initial data displayed on the table is the same with previous versions and filtering was added.

**Review by lBruchmann — APPROVED** [review]
Tested on ts3. I followed the testing steps. Everything works as expected.

**Review by dveljacic — APPROVED** [review]
Tested on TS2. Looks good ✅

**Review by filip-gregurevic — APPROVED** [review]
Changes look good to me, great job 🚀

**Pull request merged**
