### PR TITLE
[Chore] Adding role access right overview to the documentation

### PR DESCRIPTION
**Pull request by FlorianGlombik**
### Checklist
- [x] I tested *all* changes locally

### Motivation and Context

The recent introduction of the editor role added complexity to the role system of Artemis.
To keep an overview of the permissions and the purpose of each role a new section is added to the documentation.

### Description

The section `Access Rights` should help understand when to use which role and display which functionality can be accessed by which role.

### Steps for Testing

Once you have installed Sphinx (it does not take long) you can locally create the documentation by executing `make html` in the `docs` folder. 

1. Build the documentation on your machine
2. Check whether all access rights are displayed correctly
3. Check whether access rights are missing
4. Did the documentation help you to understand when to use which role? Are there any questions left open that should be addressed in this section?
5. Check for spelling mistakes

### CODE REVIEW

**Review by rs-maker — APPROVED** [review]
Getting sphinx to work was a bigger pain than expected. Looks good though.

**Review by Malyuk-A — CHANGES_REQUESTED** [review]
The code seems to be fine (but I have not yet written documentation code myself).

As @rs-maker already mentioned the installation of Sphinx took more time than I initially thought.
Here are my tips for the roadblocks I faced, maybe add these to your description to make it easier for others to test your PR.
1. Make sure you have installed:
- Python
- pip (Python package installer)
	(should be included in newer Python versions already)
	 (but was not in mine even though I had a newer version)
		-> fixed it by updating python
2. install Sphinx
	- add necessary system variables if not working already (should be shown in the error message)
	- if you have issues with sphinx_rtd_theme, this command should fix it
		"pip install sphinx_rtd_theme"

I might have found a bug:
When I click on another "chapter" like "User Registration" the "Access Rights" (button) in the left panel disappears. (Once you click on the Artemis home button above it reappears.)
This does not happen with other "chapters". Maybe it's just an issue that I face and will disappear once it is merged to master?
image
image


Question:
What is the purpose of the role ANONYMOUS? You can sign up for courses but not participate in them. Maybe this role is unnecessary?

Remarks:
 Just before "Navigation", the sentence with "... or a subordinated role has all permissions" is not so clear to me. Because Admin is the only role with all permissions and therefore the biggest superset, thus can not be a subordinate role.

Sorry for my change request but I guess these issues are valuable for making the documentation even better.😅

**Comment by FlorianGlombik** [comment]
Answer to https://github.com/ls1intum/Artemis/pull/3426#pullrequestreview-660838444

No worries about the change request, that's why we have reviews :)

Regarding the bug with the overview: 
I faced the same issue, but I was able to resolve it by deleting the `_build` folder and completely rebuilding the documentation with `make html`. It seems like otherwise the dependencies are not updated properly. Could you give it a try and see if that works for you aswell? 
As far as I know adding the page to the `index.rst` should be sufficient.

I have had another look at the role `ANONYMOUS` and changed the documentation accordingly, it was actually not quite correct before.

I don't quite get what confuses you with the Admin - what is the problem with the Admin being the superset?
I have rephrased it a bit: 
> If a subordinated role has all permissions or a role does not have any access rights, it is not explicitly displayed.
I think that this is quite clear, do you have a suggestion how to improve it? Everything that comes to my mind is to include an example, but I wanted to keep it as short and precise as possible.

**Review by Malyuk-A — APPROVED** [review]
Thank you for clarifying the ANONYMOUSE role.
Yes I tried deleting _build and it works as you have told 👍
The last point about the subordinated role could be just me and it is just a minor thing that maybe only I find phrased a little strangely.

**Review by FrankeLukas — APPROVED** [review]
Lgtm.

**Review by ivanchimeno — APPROVED** [review]
looks good

**Review by SimonEntholzer — DISMISSED** [review]
looks good to me. Adding screenshots of the new docs to the PR next time would be great :D

**Review by nicolasruscher — COMMENTED** [review]
The documentation is good. 👍

**Review by coolchock — DISMISSED** [review]
I haven't found any spelling mistakes, looks good

**Review by cremertim — COMMENTED** [review]
Dokumentation changes lgtm.  Within the Navigation table, should there be an Delete Course entry?

**Comment by FlorianGlombik** [comment]
@cremertim https://github.com/ls1intum/Artemis/pull/3426#pullrequestreview-664177172 You're right there, I have added it now  https://github.com/ls1intum/Artemis/pull/3426/commits/518d15b1bf4eb43a09a956bb1d7abf7743511504 👍

**Pull request merged**
