### PR TITLE
`Adaptive learning`: Load legend of learning path graph dynamically

### LINKED ISSUE #7494: `Adaptive learning`: Load legend of learning path graph dynamically
### Is your feature request related to a problem?

The legend shows all possible nodes.

### Describe the solution you'd like

The legend should only contain nodes that are actually contained in the graph view.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaximilianAnzinger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

The legend of the learning path graph should display only descriptions for nodes that are actually displayed.

Resolves #7494 .

### Description

With this PR we check for the presence of node types and display the description in the legend only once the corresponding type is currently displayed.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- Course with Competencies (Linked to lecture units and exercises) and Learning Paths enabled

1. Log in to Artemis
2. View the learning path graph, the legend should contain only the entries for exercises and competency end nodes
3. Navigate to Competency Management and add a matching relation between two competencies
4. View the learning path graph, the legend should now also contain the entries for matching start (branching) and end (dot)

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [learning-path-graph.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5694/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/learning-paths/learning-path-graph/learning-path-graph.component.ts.html) | 87.93% | ✅  |
| [learning-path-legend.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5694/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/learning-paths/learning-path-graph/learning-path-legend.component.ts.html) | 100% | ✅ |

�

### Screenshots

Screenshot 2023-11-07 at 14 23 57

Screenshot 2023-11-07 at 14 24 57

### CODE REVIEW

**Comment by LenaKahle** [comment]
I can't find the "Competencies and Learning Path" setting for courses on artemis or in the documentation. How can I enable it for a course?

**Comment by MaximilianAnzinger** [comment]
> I can't find the "Competencies and Learning Path" setting for courses on artemis or in the documentation. How can I enable it for a course?

You have to enable the Feature Toggle in the Server Administration.

**Review by JohannesStoehr — DISMISSED** [review]
Code looks good to me

**Review by xHadie — CHANGES_REQUESTED** [review]
_Manually tested on TS2_Legacy_

**I noticed the following issues:**
When creating a competency, the first click will not provide feedback.
When you click again an ISE is thrown.
image

After reloading the page it seems like relation is created is displayed accordingly, so I would suggest to improve the user feedback.
image

The testing instructions are a bit unclear for people who don't know the Learning Path/Competencies feature, so I am not really sure where or what the legend is and what you mean by "start (branching) and end (dot)". 

This is what I see if login as a student of the previous course and view the Learning path section:
image
image
In the border I only see Compentency ends:
image


Is this what you expected?
If you could expand your **Steps for Testing** section with images and more clear steps like ("login as admin, enable feature toggle"), I think others would also have an easier time testing this. I'd be glad to have another look then.

**Review by jakubriegel — APPROVED** [review]
Works on ts

**Review by Kroko-fant — APPROVED** [review]
Tested in a testing session on ts2

**Comment by MaximilianAnzinger** [comment]
@xHadie especially the first part is unrelated to this PR. Raphael is from now on Competency Management improvements. Maybe consider opening an GH issue so he can keep this in mind. 👍 

The testing steps are quite short because for recent PRs there were complaints about too long testing instructions ;)

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by lennart-keller — APPROVED** [review]
code lgtm

**Review by xHadie — APPROVED** [review]

**Review by Strohgelaender — APPROVED** [review]
code looks good to me

**Pull request merged**
