### PR TITLE
Consistent entity annotations

### PR DESCRIPTION
**Pull request by krusche**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context
The annotations for some domain / entity objects were inconsistent.
All entities should use ...
```
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@JsonInclude(JsonInclude.Include.NON_EMPTY)
```

.. except there is a good reason to use something else, which should be clearly documented above the entity class in JavaDoc.

### Steps for Testing
1. Log in to Artemis
2. Navigate through the most important parts of the application while having the browser console open and check that there are no exceptions or unwanted behavior

### CODE REVIEW

**Review by FrankeLukas — APPROVED** [review]
Didn't encounter errors locally or on ts1.

**Review by kloessst — APPROVED** [review]
Played around with programming exercises and participated in an exam. Seems to work fine.

**Review by sleiss — APPROVED** [review]
Tested it on TS1 and did not encounter any issues.

**Review by fde312 — APPROVED** [review]
Played around with modeling, file upload and text exercises. Creating, participating and assessing worked. Tried out Questions and Answers and worked also fine. :)

**Pull request merged**
