### PR TITLE
`Development`: Remove unnecessary server API URL constant from client

### PR DESCRIPTION
**Pull request by pal03377**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

#### Client
none of the checks here apply

### Motivation and Context

The `SERVER_API_URL` is a constant used heavily in the client. However, in practice it's always empty (tested on production, ts1, locally, by looking at code).
Also the fact that it is a declared global variable injected by Webpack makes it difficult to switch to a different code bundling process, which is [on the way](https://github.com/ls1intum/Artemis/pull/6538).

Keeping this variable adds unnecessary complexity to the client code. Therefore, it should be removed.

### Description

This PR removes the `SERVER_API_URL` in all places in the client code.

### Steps for Testing

Click around in the application. I've replaced one variable in the whole app, so if it works in one place, it should work in all others.

We should pay a bit more attention in the following places:
- [Group Chat](https://github.com/ls1intum/Artemis/pull/5822)
- [Exam Mode Live Statistics](https://github.com/ls1intum/Artemis/pull/5343)
- [LTI 1.3 Support](https://github.com/ls1intum/Artemis/pull/5693)

The reason being is that code from those features assumed no trailing slash for `SERVER_API_URL`, which differed from all other places. I'm confident that this won't affect anything, but it's better to double-check.

### Code Review Info
List of files where more than literally just removing the variable usage happens:
- `declarations.d.ts`
- `environment.js`
- `webpack.custom.js`
- `interceptor.util.ts`
- `code-editor-domain-dependent-endpoint.service.ts`
- `build-log.service.ts`
- removed slash
  - `lti13-dynamic-registration.ts`
  - `lti13-exercise-launch.component.ts`
  - `exam-monitoring.service.ts`
  - `group-chat.service.ts`

#### Code Review
- [X] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [X] Test 1
- [X] Test 2

### CODE REVIEW

**Review by Hialus — APPROVED** [review]
Tested in testing session on TS1. Did not find any issues.

Though as already mentioned I kinda liked this constant. It allowed devs to test client-side-only changes without running the server locally by setting this value to point to a test server. Having such an option in the future would still be nice if it isn't too much work.

**Review by DominikRemo — APPROVED** [review]
Tested in testing session on ts1. Works fine for me 👍

**Review by JohannesStoehr — APPROVED** [review]
Refactoring looks good to me, worked during the testing session

**Review by pellumbbaboci — APPROVED** [review]
Tested on ts1 during testing session and no bug found, works as expected

**Review by FelixTJDietrich — APPROVED** [review]
All refactorings look good to me.

I also searched the code a bit and found `/api` in the following files:
- `feature-toggle.service.ts`
- `file-uploader.service.ts`

Is this okay? Should it be `api`?

**Pull request merged**
