### PR TITLE
`Exam mode`: Fix sticky navigation bar header

### PR DESCRIPTION
**Pull request by rabeatwork**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).

### Motivation and Context

Since the header is sticky, the offset 0 for navigation bar and validation bar on exercise management pages was not correct anymore. This PR fixes this issue and also prevents the user's dropdown menu from being displayed behind the navigation bar. 

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a long Exercise (e.g. Modeling )

Log in to Artemis
Participate in an Exam 
Verify that the exam header bar is correctly positioned when scrolling 
Click on the user's dropdown 
Verify that the dropdown menu is displayed in front of the exam navigation bar 

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

#### Screenshots
image

### CODE REVIEW

**Review by rstief — APPROVED** [review]
Tested in testing session looks good.

**Review by laurenzfb — APPROVED** [review]
demonstrated in testing session, looks good

**Review by JohannesWt — APPROVED** [review]
Code looks good. Works as intended (tested in test session)

**Review by milljoniaer — APPROVED** [review]
tested in testing session, works as expected 👍

**Review by kaancayli — APPROVED** [review]
Changes work as expected. Approved.

**Pull request merged**
