### PR TITLE
[Bugfix] Fix issue with template and solution participation

### PR DESCRIPTION
**Pull request by fde312**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I implemented the changes with a good performance and prevented too many database calls

### Motivation and Context

There is an issue with the template and solution repository. In case of a new TEST submission the created result gets attached to the wrong submission. This is why the client shows that there is now result and shows a warning with a trigger new build button.

The issue is shown in the following picture: 
image

### Description

When a result is created it gets attached to the first submission which includes the referenced commit hash. This was now changed by using the latest submission (sorted by submission date).

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a programming exercise
4. Verify that both results are shown correctly with no `red trigger again` button. Check in Programming Exercise Details and Online Editor.
5. Now change the Grading of the tests (e.g. set weight from any testcase from 1 to 2) and save. This will trigger the solution and template repository to build. (See other test steps below)
6. Go back to Programming Exercise Details and Online Editor. After the build of solution and template have finished verify that the change was correctly applied and no `red trigger again` button appears.

Further tests, which should be done in step 5):
- Reset the Grading by clicking the `reset` button.
- Apply changes to the SCA Categories (only if SCA is enabled)
- Open the test repository with `Edit in Editor` and push a change by e.g. removing a testcase in `SortingExampleBehaviorTest.java`

**PLEASE ALSO TEST IT LOCALLY ON YOUR MACHINE WITH THE LOCAL SETUP AND CHECK THE DATABASE**

Note: After all steps check the database tables `submission` and `result`.  
Only changes to the test repository will create a new `TEST` submission with a result for the solution and template participation.  
The changes to the grading and SCA categories will not create a new submission! They only trigger a build and therefore create a new result for the latest solution and template submission. See also screenshots below.

### Test Coverage

No changes.

### Triggers solution repo to build:
image
image

### Afterwards the template repo build gets triggered:
image

### Correct result in Programming Details:
image

#### The exercise creation will create two MANUAL submissions and every push into the test repository will create two TEST submissions. In the screenshot below we created the exercise and did one push into the test repository (removed a test):
image

#### For all modifications (changing grading, or SCA) only a new result should be generated which is connected to the lastest submission of the participation:
image

### CODE REVIEW

**Review by airelawaleria — DISMISSED** [review]
worked as expected

**Review by marvinchimeka — APPROVED** [review]
could not see any issues

**Review by simonzilker — APPROVED** [review]
Looks good!

**Review by JohannesWeiss — DISMISSED** [review]
Tested on ts1, works as expected there.

**Review by EneaGore — APPROVED** [review]

**Review by DenizShabani — APPROVED** [review]

**Review by ivanchimeno — APPROVED** [review]
Tested on Jenkins/Gitlab and it works!

**Review by airelawaleria — APPROVED** [review]
Tested with @JohannesWeiss on ts1 and ts2. Red trigger button wasn't shown and the repos were indeed updated.

The only thing we noticed is that when updating the grading page, the update is implicitly triggered, meaning the "Building and Testung" status is not explicitly visible, but in the end it is shown that the repos were updated recently (like few seconds ago)

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts1 and ts2 with @airelawaleria. Works as expected besides the aforementioned issue.

**Review by krusche — APPROVED** [review]
Code looks good

**Pull request merged**
