### PR TITLE
`Adaptive learning`: Limit mastery progress to 100%

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation, Context and Description
It was possible to have a mastery progress of over 100% in case the mastery threshold in a competency was set to something below 100%. This should not be the case, since the progress should stop at 100% for a student.

Also replaces other occurrences of `min(max(value, minValue), maxValue)` with the new `clamp` function in the server.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Competency with a mastery threshold below 100% and at least one lecture unit/exercise linked

1. Log in to Artemis
2. Complete the lecture unit or solve the exercise with 100%
3. Check the mastery progress. E.g. visible in the learning path when viewing the competency graph that you can access when viewing the competencies linked at the top of the learning path UI

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Finding the competency graph:
Bildschirmfoto 2024-07-08 um 22 09 19
Bildschirmfoto 2024-07-08 um 22 09 14

## Summary by CodeRabbit

- **Refactor**
  - Improved consistency and readability by using `Math.clamp` for range enforcement in competency progress, build log statistics, and UML model similarity calculations.
- **Bug Fixes**
  - Ensured critical values such as mastery progress, small integers, and similarity scores stay within the expected range (0 to 1), preventing potential calculation errors.

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
I just learned about a new utility function 🎉 lgtm

**Review by JohannesWt — DISMISSED** [review]
Code 👍

**Review by asliayk — APPROVED** [review]
code

**Review by BBesrour — CHANGES_REQUESTED** [review]
Tested on TS1.
Not sure if I understood the PR, but I still get percentage over 100%

image
image
image

**Review by BBesrour — APPROVED** [review]
Tested on TS1

**Review by egekurt123 — APPROVED** [review]
Code

**Review by JohannesWt — APPROVED** [review]
Code

**Review by Strohgelaender — APPROVED** [review]

**Review by MaximilianAnzinger — APPROVED** [review]
Maintainer approved

**Pull request merged**
