### PR TITLE
`Development`: Refactor the conversation-sidebar-section component

### PR DESCRIPTION
**Pull request by MaximilianJG**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] ~~I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).~~
- [ ] ~~I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).~~
- [ ] ~~I documented the TypeScript code using JSDoc style.~~
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

This PR is connected to issue #7995. 
The change is required to address a code quality issue that was exposed by PR #7535, where the conversation-sidebar-section component was found to be repeating the jhi-conversation-sidebar-entry component multiple times in its template. This repetition lead to code redundancy, which increases code complexity and maintenance costs. 

### Description

To address the issue I refactored the HTML file of the conversation-sidebar-section component. I extracted the common structure and parameters of these instances into a ng-template. I then utilized this template using the ng-container, passing the specific parameters for each instance where necessary.

### Steps for Testing

Prerequisites:
-1 Course
-1 Student / Instructor / Admin

-Navigate to messages tab in the course and make sure everything works as before. 
-Review the Code

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **Refactor**
	- Streamlined the conversation selection sidebar for improved maintainability by introducing a reusable template.

### CODE REVIEW

**Review by nityanandaz — APPROVED** [review]
Code review: Looks good. Thanks for addressing the issue!

**Review by rstief — APPROVED** [review]
Code LGTM 👍

**Review by egekurt123 — APPROVED** [review]
code LGTM and works normally on TS5

**Review by pzdr7 — APPROVED** [review]
Tested on TS5. Looks good to me!

**Pull request merged**
