### PR TITLE
Added exam translation in Course Overview

### PR DESCRIPTION
**Pull request by FuchsDominik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Just discovered the Exam button is hardcoded, added a translation for the german version

### Description

added a translation for the german version

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Management
3. Check that it says Klausuren in german

### Screenshots

Before:

Screenshot 2020-12-19 at 12 02 50

Now:

Screenshot 2020-12-19 at 12 03 04

### CODE REVIEW

**Review by fde312 — APPROVED** [review]
code looks good! 👍

**Review by krusche — APPROVED** [review]

**Review by airelawaleria — APPROVED** [review]
Tested in the testing session. Approve

**Review by simonzilker — APPROVED** [review]
Works as described!

**Review by marvinchimeka — APPROVED** [review]
Works fine.

**Review by JohannesWeiss — APPROVED** [review]
Code looks good.

**Pull request merged**
