### PR TITLE
`Exam mode`: Change label of the example solution repo download button

### PR DESCRIPTION
**Pull request by akesfeden**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

As discussed in the thread starting with https://github.com/ls1intum/Artemis/pull/6087#discussion_r1083893184, using `Download Repo` label for the example solution download button of the exam programming exercises can be understood as downloading the student's own repository, which is misleading.

### Description

Changed label for the example solution download button of the exam programming exercises from `Download Repo` to `Download Example Solution` and updated related text and screenshot in the docs.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam 
- 1 Student who submitted the Exam

1. Log in to Artemis
2. Navigate to Course Administration
3. As an instructor, set the example solution publication date of the Exam to a past date.
4. As a student who submitted the exam, navigate to the exam summary  and check if the button next to the programming exercise says `Download Example Solution` button instead of `Download Repo`.
5. Check that German version of the same page has no missing translations.
6. Check the button still works as before (i.e., downloads the example solution repo).

#### Code Review
- [x] Review 1

#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Not changed.

### Screenshots

image

### CODE REVIEW

**Comment by krusche** [comment]
Can you please simply call it "Download example solution"?
We should stay consistent on the whole system and call it example solution when students get in touch with other the solutions provided.
Please double check that this is the case for all other exercise types as well

**Review by kekskatze — APPROVED** [review]
Tested on ts1. Worked well, but I found a weird translation (Exammodus). I don't think it has anything to do with these changes though so I will create a separate issue

**Review by luisa1999 — APPROVED** [review]

**Review by luisa1999 — APPROVED** [review]
I tested it on ts12. Everything looks fine.

**Review by julian-christl — APPROVED** [review]
Code and documentation look good

**Pull request merged**
