### PR TITLE
`Programming exercises`: Fix Iris settings on detail page

### LINKED ISSUE #7879: `Iris`: Iris components on exercise detail page are broken
### Describe the bug

The Iris components in the exercise details page are currently somewhat broken in two different ways:
1. The Iris button breaks the layout of the other buttons in its row: 
    image
2. The Iris enable/disable buttons are disabled even if I am an Admin: 
    image

I assume that these issues were introduced in #7632.

### To Reproduce

1. Go to an exercise on TS9/Staging as an Instructor/Admin
2. See the broken layout for the buttons
3. Scroll down to the bottom of the page
4. See that the enable/disable buttons are disabled

### Expected behavior

1. The layout should not break if the Iris button is present
2. The enable/disable buttons should be activated for Instructors and Admins

Additionally I think it might make sense to put the Iris enable/disable buttons in a different section, as the do not make much sense under "Grading" imo

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

develop

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context
closes #7879 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 programming exercise
- TS9

1. Log in to Artemis
2. Navigate to Programming Detail Page
3. Verify that the buttons on the top look right 
4. Verify that the iris toggle is not disabled for instructors

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of the programming exercise in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exam_mode/) as reference.
5. ...

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
	- Updated the condition for enabling specific interface elements based on user permissions.

- **Style**
	- Improved the visual layout of buttons by adjusting the margin.

### CODE REVIEW

**Review by Hialus — APPROVED** [review]
Code changes look good.
I also tested it on TS9 and the issues are both resolved:
image
image

Thanks for fixing this so quickly 👍🏻

**Review by konrad2002 — APPROVED** [review]
manually tested on ts9, works as expected

**Review by xHadie — APPROVED** [review]
_Manually tested on TS9_
Works now as described

**Review by reschandreas — APPROVED** [review]
code lgtm

**Comment by yassinsws** [comment]
Code lgtm

**Review by yassinsws — APPROVED** [review]
code lgtm

**Review by rabeatwork — APPROVED** [review]

**Pull request merged**
