### PR TITLE
`Iris`: Add optional client context to message sending

### PR DESCRIPTION
**Pull request by MichaelOwenDyer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
In many Iris features, Iris is designed to be aware of the user's context to provide more personalized and relevant assistance. However, the current system assumes that all necessary contextual information will be available server-side when the user sends a message. Sometimes however, the context on the user's screen has not been persisted to the server (yet) and only resides on the client - for example, unsaved form data. Therefore, it is useful if we have the option to send some extra context from the client when the user sends a message to Iris.

### Description

- We are now accepting a `IrisClientArgumentsDTO context` object in the IrisMessageResource through the Iris services and into the `requestMessageFromIris()` method to be used in the request.
- This DTO type can be subtyped for each Iris feature needing some client context. An example of this can be seen in `IrisCodeEditorClientDTO`, which transports the unsaved problem statement from the Code Editor.
- The Iris button and Iris chatbot widget have been modified with an optional input parameter that allows you to set what context to collect from the UI every time the user sends a message to Iris. The `sendMessage()` and `resendMessage()` methods in the http services now additionally send this context to the server.

### Steps for Testing

Prerequisites:
- 1 Editor
- 1 Programming Exercise with Iris enabled

1. Make sure that sending and receiving messages in the chat window still works

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Enhanced messaging functionality in the Iris service to include context-specific parameters, improving the relevance and accuracy of responses.
	- Introduced new Data Transfer Objects (DTOs) for more structured and efficient data handling in Iris client arguments and messages.
	- Added a dynamic context provision feature in the chatbot interface, allowing for real-time context adjustments based on user interactions.

- **Enhancements**
	- Updated the Iris messaging service to accept additional context parameters, enabling more personalized and context-aware interactions.
	- Improved the code editor's integration with the Iris chatbot, including context-aware problem statement handling.

- **Bug Fixes**
	- Minor formatting and comment adjustments for better code readability and maintenance.

- **Documentation**
	- Detailed documentation for newly introduced DTOs and methods, ensuring clarity on the usage and benefits of the new features.

### CODE REVIEW

**Comment by MichaelOwenDyer** [comment]
Reviewed CodeRabbit suggestions, all were non-issues

**Review by konrad2002 — APPROVED** [review]
manually tested on ts9, works as expected

**Review by LenaKahle — APPROVED** [review]
Approve, manually tested on TS9, Iris is working as usual.

**Review by nata-81 — DISMISSED** [review]
tested on ts9 works as expected.

**Review by Gusti2010 — DISMISSED** [review]
tested manually on ts9. Works as expected!

**Review by egekurt123 — DISMISSED** [review]
Manually tested on ts9, works as expected

**Review by RY997 — DISMISSED** [review]
Code lgtm

**Review by MaximilianJG — DISMISSED** [review]
tested on ts9. working as expected

**Review by AntonGeTUM — APPROVED** [review]
Tested on ts9, works fine

**Review by krusche — CHANGES_REQUESTED** [review]
Without a concrete example, it's a bit difficult to understand what this change is needed. In particular when it comes to the chat window for students, I do not see a reason to send arbitrary form data. While the approach is extensible, it could also lead to security issues if we allow arbitrary data to be sent to the server. I would favor a less generic approach

**Review by georgyia — DISMISSED** [review]
tested manually on ts9, lgtm

**Comment by MichaelOwenDyer** [comment]
Thanks to @krusche for the suggestion to improve security by using a DTO hierarchy instead of JsonNode. I've also introduced an example usage of this feature in the Code Editor, where the unsaved problem statement on the client is sent to the server every time the user sends a message to Iris.

**Review by RY997 — COMMENTED** [review]
Tested on ts9, "Internal server error" always occurs when importing or creating a programming exercise

**Review by yassinsws — APPROVED** [review]
Code lgtm

**Review by kaancayli — DISMISSED** [review]
Looks good to me. LGTM

**Review by Hialus — APPROVED** [review]
Looks okay

**Review by yassinsws — APPROVED** [review]

**Comment by krusche** [comment]
This PR is open too long, therefore we close it. Feel free to reopen it when the actual implementation is finished and needed

**Pull request closed without merging**
