### PR TITLE
Fixed sort programming exercise by programming language

### PR DESCRIPTION
**Pull request by daniels98it**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest2.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

Sorting programming exercises by programming language, in the "import programming exercise" modal, did not work. 

### Description

Added the missing "programming language" in *ExerciseSearchColumn*  Enum.(src/main/java/de/tum/in/www1/artemis/domain/Exercise.java)

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration - <random_course> - Exercises
3. Click on "Import programming exercise"
4. Try to sort the programming exercises by "Programming Language"

### Test Coverage

Exercise.java: 92%

### Screenshots

Before:

new

After:
working

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Everything works

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts1, works as intended.

**Review by krusche — APPROVED** [review]

**Comment by krusche** [comment]
👍

**Review by simonzilker — APPROVED** [review]
Works as intended!

**Review by EneaGore — COMMENTED** [review]
approve

**Pull request merged**
