### PR TITLE
Sync for team-based Text and Modeling Exercises

### PR DESCRIPTION
**Pull request by madwau**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I implemented the changes with a good performance and prevented too many database calls _(will cause quite a lot of database calls when many students are actively working on their submissions at the same time, has to be evaluated if it's too much for the server to handle)_
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
With the introduction of team-based exercises, it is now possible that multiple students will work on the same submission simultaneously. For Programming and File Upload exercises, no obvious changes are required since multiple students can already work on a programming exercise at the same time using version control system `git` and in the case of a file upload exercise, the actual work is performed outside the Artemis platform and only the final resulting document is uploaded by one of the team members.

The two exercise types that require obvious changes to facilitate team work are Text and Modeling exercises. Here it is necessary that the latest state of the submission is synced between the team members in near-realtime (defined as less than 4 seconds), so that everyone is always looking at the most recent version of the team work product.

#### Server-side
1. Add new DTO `SubmissionSyncPayload` that contains a submission and a sender (User)
2. Add two new websocket endpoints for updating modeling and text submissions
  2.1 `/topic/participations/{participationId}/team/modeling-submissions/update`
  2.2 `/topic/participations/{participationId}/team/text-submissions/update`
3. Add new DTO `OnlineTeamStudentDTO` that contains meta information about a team member (`lastTypingDate` used for showing a typing/editing indicator, `lastActionDate` used for showing when the team member last updated the submission)
4. Add new websocket endpoint that a user calls when he starts typing/editing (which will show a typing indicator next to his name in the team info box for the other team members)
  4.1 `/topic/participations/{participationId}/team/typing`

#### Client-side
1. New generic sync component (used for both Text and Modeling): `TeamSubmissionSyncComponent`
  1.1 Receiver: Used to receive the latest submission from other team members
  1.2 Sender: Used to broadcast the latest submission based on own changes to the server (which persists it and forwards it to the other team members)
2. Changes to Modeling Editor
  2.1 Set up a stream of submissions by emitting a new submission whenever the user has made changes (change diff is performed every 2s to determine whether changes have been made)
3. Changes to Text Editor
  3.1 Set up a stream of submissions by emitting a new submission whenever the textarea input has changed (with a debounce time of 2s).
4. Changes to the Team Students Online List (which is the main part of the Team Info Box)
  4.1 The green circle indicating that the user is online now turns into a typing animation whenever one of the other team members is editing the submission (by typing text in the case of a Text Exercise or by modifying the UML model in case of a Modeling Exercise).
  4.2 Behind the name of a student, who is online, a history icon is shown if this student has made changes in the past. Clicking on it shows when he last made changes to the submission.
5. Slightly unrelated to this PR: Improve scrolling behavior of Team Info Box by replacing the package `angular-sticky-things` with css position sticky which is much smoother.

#### Modeling Exercise
1. Log in to Artemis
2. Navigate to Course Management
3. Create a team-based Modeling Exercise ([how?](https://github.com/ls1intum/Artemis/pull/1282#issuecomment-605954482))
4. Create a team for the new exercise with at least two students in it
5. Log in with both of those students (using two separate browser sessions)
6. Start the exercise with one of the students
7. Drag some elements into the model editor
8. Verify that the other student sees the typing/editing animation next to the student's name
9. Verify that the model in the modeling editor is updated and looks equivalent for all team members (of course it won't look identical in terms of positioning on the canvas if the canvas size differs)

#### Text Exercise
1. Log in to Artemis
2. Navigate to Course Management
3. Create a team-based Text Exercise ([how?](https://github.com/ls1intum/Artemis/pull/1282#issuecomment-605954482))
4. Create a team for the new exercise with at least two students in it
5. Log in with both of those students (using two separate browser sessions)
6. Start the exercise with one of the students
7. Type in text into the text editor
8. Verify that the other student sees the typing/editing animation next to the student's name
9. Verify that the text in the text editor is updated shortly after the student stops typing

### Screenshots
`Artemis Test User 1` is working on the model:
OnPaste 20200422-165909

`Martin Wauligmann` is typing something:
OnPaste 20200422-173407

### CODE REVIEW

**Comment by madwau** [comment]
@sleiss Thanks for the feedback!

Did you test this locally or on the test server? I noticed that the online status doesn't appear correctly sometimes when running npm in development mode with hot reload.

> I find the current color of the typing indicator quite hard to see, maybe you can make it a bit darker?

Good point, it is a bit hard to see, I agree. I wasn't really sure how to improve it but you could be right that a darker color might help. Or slighly enlarge the animation as well. I'll experiment.

> The submit state is not synced right now, correct? (One user submits and the others currently won't see it).

Also very helpful suggestion! I didn't really consider this since I was focused on the pure content sync but it definitely makes sense to also sync this. Will add it.

**Comment by sleiss** [comment]
@madwau
> Did you test this locally or on the test server? I noticed that the online status doesn't appear correctly sometimes when running npm in development mode with hot reload.

I tested it only on the test server (1).


> Good point, it is a bit hard to see, I agree. I wasn't really sure how to improve it but you could be right that a darker color might help. Or slighly enlarge the animation as well. I'll experiment.

Great!

> Also very helpful suggestion! I didn't really consider this since I was focused on the pure content sync but it definitely makes sense to also sync this. Will add it.

Also great to hear!

**Comment by madwau** [comment]
> The online status seems to be broken

Luckily this was not websocket related at all but just a simple css bug that caused the circle to not be colored green. It's fixed now.

> I find the current color of the typing indicator quite hard to see, maybe you can make it a bit darker?

I made the typing indicator darker and also larger, so it's easier to notice it:
captured

**Comment by madwau** [comment]
> The submit state is not synced right now, correct? (One user submits and the others currently won't see it).

@sleiss The submission state is synced now.

**Comment by F4lka** [comment]
Great functionality and appealing UI. Also the content appears more or less immediately for the team partner.
 
I found one bug:
Screenshot from 2020-04-26 19-55-37
Steps to reproduce the bug:
1. The above the described setup for a team modeling exercise
2. Two members of the same team open the modeling editor
3. Team member one adds an element 
4. After the appearance of the element, the second team member clicks on the back button of the browser

**Comment by madwau** [comment]
> Great functionality and appealing UI. Also the content appears more or less immediately for the team partner.
> 
> I found one bug:
> Screenshot from 2020-04-26 19-55-37
> Steps to reproduce the bug:
> 
> 1. The above the described setup for a team modeling exercise
> 2. Two members of the same team open the modeling editor
> 3. Team member one adds an element
> 4. After the appearance of the element, the second team member clicks on the back button of the browser

Thanks for testing! I will look into the error tomorrow.

**Pull request merged**
