### PR TITLE
`General:` Improve support for small screens for assessment and code editor

### PR DESCRIPTION
**Pull request by MDK5**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
Currently, both the assessment layout as well as the code editor top bar do not support smaller screens. This causes problems in Orion since Orion's integrated browser is rather small. The buttons get pushed out of the screen and a vertical scollbar appears.

### Description
This PR adds the flex-wrap property to all relevant containers in the assessment layout and code editor headbar. Wherever necessary it also changes the margins, from the current left-only to all four sides. This is required to ensure all buttons align correctly, regardless where they wrap into a new line.

I recommend to review the code with whitespace changes deactivated.

### Steps for Testing

1. View the assessment detail view and the code editor under all circumstances with different browser sizes.
2. The assessment layout circumstances include:
    - Assessment of all exercise types
    - Assessment in Orion (this can also be tested in a regular browser by overriding the userAgent to include "Orion/1.1.1")
    - An additional banner shown when the assessment due date has passed
    - An additional button in second correction rounds in exams
    - An additional button in text and modelling exercises that allow to convert the submission to an example submission
3. The code editor circumstances include:
    - The assessment of programming exercises
    - The participation in programming exercises as a student (both normal an in exams)
    - The creation of programming exercises as an instructor ("Edit in Editor" button)
4. All views should wrap nicely upon reducing the browser size. The code editor only wraps if you collaps the file browser or insstrctions tab
5. I might have missed an occurence or edge case, if you know any other variation of the mentioned components, please let me know

### Review Progress
- Code Review
  - [ ] Review 1
  - [ ] Review 2
- Manual Tests
  - [ ] Test 1
  - [ ] Test 2

### Test Coverage
unchanged

#### Assessment with normal screen size
grafik
#### Assessment with small screen size, old
grafik
#### Assessment with small screen size, new
grafik

### CODE REVIEW

**Review by Malyuk-A — APPROVED** [review]
Tested during testing session on TS2. Works as described 👍

**Review by lschlesinger — CHANGES_REQUESTED** [review]
Tested on TS2, for the assessment detail view I found the layout to be fine.
As we agreed during testing session, in the pictures pasted below one could improve the layout:
Bildschirmfoto 2021-09-27 um 14 58 14
Bildschirmfoto 2021-09-27 um 14 57 22

**Comment by imstreetspirit** [comment]
tested modeling-text assessment and edit-in-editor for programming exercise on ts2. no issues found

**Review by Malyuk-A — CHANGES_REQUESTED** [review]
image
Similar issue to the one Lorena found. But for Instructors when they click the edit in editor button.

**Review by coolchock — DISMISSED** [review]
tested in testing session on ts2, works as expected

**Review by ndricimrr — DISMISSED** [review]
Tested on TS2. A small issue with width, but dissapeared when I closed the two panels on the sides.

**Review by cremertim — DISMISSED** [review]
tested during testing session

**Review by argertboja — DISMISSED** [review]
Works great on TS1 👍🏼

**Comment by imstreetspirit** [comment]
as far as I can see, changes seems reasonable, I'll test when the maintenance is over. I'll confirm PR afterwards.

**Comment by MDK5** [comment]
The issue in the instructor view is resolved now, I added a gap:

grafik

**Pull request merged**
