### PR TITLE
Bugfix/type error short answer question edit component

### PR DESCRIPTION
**Pull request by ivohashamov**
### Checklist
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context

The short answer question component used to throw a TypeError when previewing the exercise text

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to Quiz exercises
4. Create a Short Answer Question
5. Inspect the page -> go to the console tab
6. Click on Visual (below the question editor) and check if a TypeError gets thrown

### CODE REVIEW

**Review by EneaGore — APPROVED** [review]
Issue has been fixed.

**Review by airelawaleria — APPROVED** [review]

**Review by simonzilker — APPROVED** [review]

**Review by marvinchimeka — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]

**Review by sebastiantpeter — COMMENTED** [review]
Deployed a build of commit 6a3037... on test server 2.
Not sure if I did something wrong, but I still get a TypeError in the console:

short_answer_bug

**Comment by EneaGore** [comment]
@sebastiantpeter no matter how much i try i can not reproduce the issue on ts1 or ts2. It does however happen everytime on the live server. Can you maybe share you course with the quiz ?

**Review by DenizShabani — APPROVED** [review]

**Comment by sebastiantpeter** [comment]
> @sebastiantpeter no matter how much i try i can not reproduce the issue on ts1 or ts2. It does however happen everytime on the live server. Can you maybe share you course with the quiz ?

In case you are interested: I do not have the issue anymore in the quiz of yesterday... I guess it was something with caching.

**Pull request merged**
