### PR TITLE
[Bugfix] Course/Exam Archiving should not fail when zipping non-existent files

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

There was a flaky test testing the archival process of courses and exams that kept on failing during the `sever-tests` Github check. 

Furthermore the course archival process was also failing due to an uncaught `java.nio.file.NoSuchFileException` which occurred every time we attempt to zip a non existent file. In this specific case, for some reason the jGit garbage collection kicks in during the zipping. This causes a file `gc.log.lock` to be created and then shortly after deleted.

### Description

This pr fixed the issue by using the `Files.isReadable` check before zipping specific files. We also delete the `gc.log.lock` file before we zip the repo.

Instructor that triggers the archive function will get notified of warnings that occurred during the process via a modal window that opens up after the archival process is finished.

This pr also attempts to improve exception handling and adds missing `throws` statements.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
4. Generate one (or more) exercise of each type
5. Participate in each exercise
6. Generate an exam with exercises of each type
7. Participate in the exam
8. Edit the course and change the end date so that it's in the past
9. Navigate to the course detail page and click on "archive course"
10. Once archiving is complete, you should be able to download the course archive
11. Download the archive. You should be able to see the submissions in the zip file
12. Now go to Bitbucket and/or Gitlab and delete a repository of a programming exercise
13. Archive the course again and you should see the popup once archiving is finished.

### Test Coverage

CourseExamExportService.java 84%
ZipFileService.java 94%
GitService.java 75%
ProgrammingExerciseExportService.java 71%
course-exam-archive-button.component.ts 93.58

### Screenshots

The modal that opens up if the archive process completed with warnings: 

image

### CODE REVIEW

**Comment by FuchsDominik** [comment]
:(

**Review by willergeorg — COMMENTED** [review]
Normal archiving worked as expected , but I did not manage to delete a gitlab repo because artemis admin is as project owner the only account that has the permission to do so. Should be checked by somebody that is more experienced than me.

**Review by NicolasUllmann — COMMENTED** [review]
We students from the practical course aren't able to test the 11. step. We don't have the access right for the GitHub/bitbucket repository or the credentials to log in. Everything else worked as expected up to this point.

**Comment by ivanchimeno** [comment]
> Normal archiving worked as expected , but I did not manage to delete a gitlab repo because artemis admin is as project owner the only account that has the permission to do so. Should be checked by somebody that is more experienced than me.

I think if you use an instructor test account, you can log into Bitbucket with the test account credentials. You can also click on "Template" button in the "Exercises" view which is accessible via the  Course Administration page.

**Review by willergeorg — APPROVED** [review]
Worked with Bitbucket, don't know what went wrong with Gitlab. Archiving finished with errors and they were displayed as described.

**Comment by ivanchimeno** [comment]
> Worked with Bitbucket, don't know what went wrong with Gitlab. Archiving finished with errors and they were displayed as described.

This is expected behavior as long as the warnings are displayed and you can still download the archive

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS1, everything worked as it should. The code looks good as well :D

**Review by DanielKainz — APPROVED** [review]
Code looks good :-)

**Pull request merged**
