### PR TITLE
`Tutorial groups`: Improve checklist consistency

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
When configuring tutorial groups for the first time, a checklist is used to guide the instructor through the configuration. This checklist used disabled checkboxes to indicate the current status, which is confusing and inconsistent with other checklists.

### Description
This PR reuses the exam checklist check component and makes it generally available.

### Steps for Testing
- 1 Instructor
- 1 Course

1. Open the tutorial group configuration checklist. If the course has no tutor groups yet, you can simply open it by pressing the tutorial groups button at the course management card. When groups are already configured you can reach it using the direct URL `course-management/<courseId>/tutorial-groups-checklist`
2. Verify that it works correctly and looks good.

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
before:
grafik

now:
grafik

### CODE REVIEW

**Review by simon-hng — APPROVED** [review]
Code changes look good

**Review by terlan98 — APPROVED** [review]
Tested on TS4. The checklist looks good 👍

**Review by eceeeren — APPROVED** [review]
Tested on TS2, works well!

**Review by dakennguyen — APPROVED** [review]
tested on ts1, works as expected!

**Pull request merged**
