### PR TITLE
`General`: Fix chart series tooltip in performance statistics in exercises for disabled lines 

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

When the user disables a line in Performance in Exercises, the series tooltip shows -1% for the corresponding line. This is fixed in this PR.

### Description

I disabled negative values in the tooltip as I could not imagine a use case where negative relative values in one score type would be needed/meaningful. 

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Course with exercises (the Performance in Exercises Chart is filled)

1. Log in to Artemis
2. Navigate to the student statistic tab of the course
3. Scroll down to the Performance in Exercises chart
4. Disable one line (by clicking on the corresponding legend entry)
5. Hover over an exercise in the chart (not a specific line but anywhere on the vertical line of the corresponding x axis tick)
6. Make sure that the score of the disabled line is changed to 0

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Nothing changed

### Screenshots

Current series tooltip:
image

How it should look:
image

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
Tested on TS2 with @lBruchmann @cremertim @Bofan-Zhu @VinnavanSembian, worked as expected. Code changes look good to me.

**Review by lBruchmann — APPROVED** [review]
Tested on ts2. I followed the testing steps. Everything is correctly displayed.

**Review by cremertim — APPROVED** [review]
everything works as expected 👍  code lgtm

**Review by fh314 — APPROVED** [review]
Tested on ts2 and looks good

**Review by baranimo7 — APPROVED** [review]
Tested on ts1. Everything is shown correctly.

**Pull request merged**
