### PR TITLE
`Development`: Drop feedback_conflict table after removal of related feature

### PR DESCRIPTION
**Pull request by pal03377**
> **Warning**
> **DO NOT DEPLOY to a test server!**

> **Warning**
> **Only merge after #6769 is merged!**

#### General

- [ ] ~I tested **all** changes and their related features with **all** corresponding user types on a test server.~
- [X] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

After the feedback conflict feature is removed in #6769, the corresponding database table can be removed.
To be able to test #6769 on test servers without modifying their database, this change is split into a separate PR.

### Description

Remove the `feedback_conflict` table from the database.

### Steps for Testing

1. Create a backup / dump of your local database
2. Start the server
3. Observe that the `feedback_conflict` table is removed
4. Observe that there are no other changes to the database

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### CODE REVIEW

**Review by TheZoker — DISMISSED** [review]
LGTM 👍

**Review by FelixTJDietrich — DISMISSED** [review]
Migration LGTM 👍

**Review by simon-hng — DISMISSED** [review]
LGTM

**Review by terlan98 — DISMISSED** [review]
Tested locally. Only the `feedback_conflict` table was removed 👍

**Pull request merged**
