### PR TITLE
`Development`: Update Apollon to v2.12.7

### PR DESCRIPTION
**Pull request by minrows**
#### General
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
Update version of Apollon from [v2.12.6](https://github.com/ls1intum/Apollon/releases/tag/v2.12.6) to [v2.12.7](https://github.com/ls1intum/Apollon/releases/tag/v2.12.7)

### Description
This bugfix release of Apollon fixes the alignment of elements to grid issue. 
As Apollon only supports scaling factors with numbers having one decimal place (0.7, 0.8, 1,...) the scaling factor is now changed from 0.75 to 0.8.

**Changes include:**
- Set the default scale factor of Apollon to 0.8 instead of 0.75
- Set the moving/resizing factor of elements to 10 (previous value: 20)
- Fix alignment issue with following elements:
1. Rectangle in syntax tree 
2. Fork nodes
3. Terminal, Process and Function Call in Flow chart

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Create a modeling exercise
2. Observe all the elements (especially the one mentioned above) are aligned perfectly with the grid

#### Before
204931063-27d85340-bc35-4898-b6ab-a7ea03638146

#### After
204930662-d9abd526-aa84-4e44-8ab9-700ccc9bec97

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]

**Review by JohannesStoehr — APPROVED** [review]

**Review by timo07k — DISMISSED** [review]
Tested every single element of all diagrams. Everything works perfect, apart from:

1. Object in an object diagram **and** communication diagram
image

2. Actor in a use case diagram
image

3. Transition in a petri net
image

Tested on TS1.

**Review by tobias-lippert — APPROVED** [review]
Tested on ts1. Didn't encounter any issues other than the ones mentioned by @timo07k above.

**Review by PhilipWerz — DISMISSED** [review]
Tested on TS2. Tested all elements. Most elements work but I encountered a few issues:

1. Flowchart diagram
image

2. Perinet: Transition (same as @timo07k)

**Comment by minrows** [comment]
> Tested on TS2. Tested all elements. Most elements work but I encountered a few issues:
> 
> 1. Flowchart diagram
>    image
> 2. Perinet: Transition (same as @timo07k)

Updated the [Apollon issue](https://github.com/ls1intum/Apollon/issues/279). As mentioned, it will be fixed in a future release of Apollon.

**Review by rriyaldhi — APPROVED** [review]

**Pull request merged**
