### PR TITLE
`Development`: Comment out skipped e2e tests

### PR DESCRIPTION
**Pull request by TheZoker**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

For some reason, cypress sometimes has issues skipping tests. (e.g. https://bamboo.ase.in.tum.de/browse/ARTEMIS-AETG-1026). Since these tests should not be run and cause issues if they are run, we comment them out.

### Description

This PR comments skipped PRs out to avoid running them by accident. 

#### Code Review
- [ ] Review 1
- [ ] Review 2

### CODE REVIEW

**Review by Strohgelaender — COMMENTED** [review]
Should we many add a TODO-comment above the tests? If it's just commented out the code might get overlooked in the future.

**Comment by TheZoker** [comment]
> Should we many add a TODO-comment above the tests? If it's just commented out the code might get overlooked in the future.

Good idea, I added the TODO comment 👍

**Review by rriyaldhi — APPROVED** [review]
Changes look good 👍

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Pull request merged**
