### PR TITLE
`Adaptive learning`: Redesign edit competency relation section

### PR DESCRIPTION
**Pull request by JohannesWt**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Description

This PR introduces a redesigned section for creating/deleting and updating a relation between course competencies. Therefore a new button has been added to the competency management page which opens an own modal to create relations between competencies. The new graph in the modal distinguishes between Prerequisites and Competencies to make to give the Instructor a hint what to connect.

This PR is the first part of a makeover to convert the competency management page to use signals and make all involved components standalone or replace them completely. 

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Competency Management
3. Click the "Edit Relations"-Button
4. Create two or more relations
5. Click on a relation and delete it
6. Click on a relation and update the relation type

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| competency-management.component.ts | 88.76% | ✅ ❌ |
| competency-relation-graph.component.ts | not found (deleted) | ❌ |
| course-competencies-relation-graph.component.ts | 96.42% | ✅ ❌ |
| course-competencies-relation-modal.component.ts | 100% | ✅ |
| course-competency-relation-form.component.ts | 91.54% | ✅ ❌ |
| course-competency-relation-node.component.ts | 100% | ✅ |
| course-competency-api.service.ts | 91.66% | ✅ ❌ |
| competency.model.ts | 88.15% | ✅ ❌ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| UpdateCourseCompetencyRelationDTO.java | 100% | ✅ |
| CompetencyService.java | 90% | ✅ ❌ |
| CourseCompetencyService.java | 90% | ✅ ❌ |
| PrerequisiteService.java | 90% | ✅ ❌ |
| CourseCompetencyResource.java | 97% | ✅ ❌ |

### Screenshots

image

## Summary by CodeRabbit

- **New Features**
	- Introduced a modal for managing course competency relations.
	- Added new components for competency relation management, including a relation graph and relation form.
	- New buttons and labels added for editing relations in multiple languages.
	- Enhanced modularity of the Competency Management Component.

- **Bug Fixes**
	- Removed outdated methods related to competency relations to streamline functionality.

- **Documentation**
	- Updated documentation to reflect changes in competency relation management.

- **Tests**
	- Added new test suites for the newly introduced components and functionalities.

### CODE REVIEW

**Review by pzdr7 — CHANGES_REQUESTED** [review]
A few small comments on the code.

While testing on TS4, I encountered a situation where the cycle detection in the server caught something the client didn't. Can you have a look?

image

**Review by JohannesStoehr — DISMISSED** [review]
Code

**Review by pzdr7 — DISMISSED** [review]
Code

**Review by az108 — DISMISSED** [review]
Tested on TS4, selecting individual relations is possible like described 👍

**Review by sachmii — DISMISSED** [review]
Tetsted on TS4, works as described. I can select and update the relations.

**Review by HawKhiem — DISMISSED** [review]
Tested on TS3. Works as described. 
Screenshot 2024-10-16 202411
Screenshot 2024-10-16 202449
Screenshot 2024-10-16 202459

**Review by SimonEntholzer — APPROVED** [review]
Works on Testserver 2 after merge conflict

**Review by JohannesStoehr — APPROVED** [review]
Reapprove after merge

**Review by pzdr7 — APPROVED** [review]
Reapprove after merge conflicts :+1:

**Review by az108 — APPROVED** [review]
Tested locally, works after merge conflict

**Review by MaximilianAnzinger — APPROVED** [review]
Maintainer approved

**Pull request merged**
