### PR TITLE
[Bugfix] Fix Assessment Information Stats

### PR DESCRIPTION
**Pull request by lschlesinger**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

Solves issue #3890

### Description

The issue: It appears when a course/exam has a programming exercise, which has the assessment mode set to automatic, but has complaints enabled. (click the assessment type button *twice*)
image -> image -> image
When the hibernate query fetches the complaints for the assessment dashboard, it fails because the complaint is for an automatic result. Since the query groups by `result.assessor.id`, but for automatic results this is `null`.

I just investigated and[ found this stack](https://stackoverflow.com/questions/25322583/cant-instantiate-class-using-hibernate-createquery/29879294#29879294) overflow post. I replaced the primitive types used in the constructor (`long`, `double`) by `java.lang.Object` types (`Long`, `Double`). I also did this for the constructors used in the related classes `TutorLeaderboardComplaintResponses`, `TutorLeaderboardAssessments`, …

### Steps for Testing

1. Log in to Artemis as instructor
2. Create an exam at which you can participate as student afterwards, set a review start and end time for that exam. 
**2.1 add a programming exercise -> set assessment type to automatic, but with complaints enabled**
3. Participate as student and submit something
4. Navigate to the Assessment Dashboard of the corresponding exam as instructor
5. Check the stats shown in the information table on the top right side (as shown in the screenshot below)
6. If you, as instructor, retrieve the lock for the assessment by opening it, check that this information is updated in the table
7. If you, as instructor, submitted an assessment, check that this information updated in the table
8. As student, review the automatic assessment (only possible during review phase) and file a complaint
9. As an instructor, check that this information is reflected in the information table as well and that this complaint is linked in the table

### Screenshots

Having assessed the only submission for an exam and receiving a complaint about that assessment should lead to the following stats:
Bildschirmfoto 2021-08-09 um 21 28 05

### CODE REVIEW

**Review by Olimbia23 — APPROVED** [review]
Nice catch @lschlesinger. Changes make sense 👍

**Review by FrankeLukas — DISMISSED** [review]
Seems to work as advertised. One thing I found a bit odd is that the divisor is styled like a link but not clickable for assessment locks:
grafik

No need to adjust that in this PR though.

**Review by julian-christl — APPROVED** [review]
File changes make sense, tested in test session, works as explained. Bug fixed.

**Review by FuchsDominik — APPROVED** [review]
Worked in the testing session

**Review by jpbernius — APPROVED** [review]
:shipit:

**Pull request merged**
