### PR TITLE
`Development`: Increase client test coverage of date time picker

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

This PR increases the test coverage of `date-time-picker.component.ts`
### Description

I introduced a dedicated test suite `date-time-picker.component.spec.ts`

### Steps for Testing

Only code review

#### Code Review
- [x] Review 1
- [x] Review 2

### Test Coverage

`date-time-picker.component.ts`: 100% | 91.3%

### CODE REVIEW

**Review by ole-ve — APPROVED** [review]
Looks good to me, approve 👍

**Review by cremertim — APPROVED** [review]
great job 👍

**Review by coaxial1 — APPROVED** [review]
LGTM!

**Review by Hialus — APPROVED** [review]
Code changes look good to me 👍🏻

**Pull request merged**
