### PR TITLE
`General`: Fix active students charts with limited scope

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.

### Motivation and Context

This PR is concerning Issue #5101: Currently, the scope limitation of the active students charts does not work as intended. If a course has a start date and the difference between the course start date and the current end date of the chart (either the official end date of the course or the current date) was not exactly a multiple of a week, the chart did not show the correct information.
Furthermore, the server test regarding the scope limitation server code is currently flaky.

### Description

I adapted the server code. Now, the difference between start and end dates is computed based on normalized timestamps.
Additionally, I modified the server test so that it passes again.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with student activity

1. Log in to Artemis
2. Edit the course
3. Set a course start date that is  e.g. 20 days ago.
4. Safe the course and check whether the chart on course detail shows the correct information
5. Check that the chart in the course management tile shows correct information as well
6. Edit the course again. Choose the start date so that there is a difference of > 4 weeks between it and the current date. **Still, it should not be the current time exactly X weeks ago**
7. Check the charts again that they still work
8. Edit the course again. Set a course end date that lies in the past. Play around with the start date so that the time difference is not exactly a multiple of a week. Make sure that both charts still work and show correct data.
9. Also try a combination that leads to a course lifetime > 1 year and verify that the charts handle this correctly.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

The scope limitation should work again:
image

### CODE REVIEW

**Review by alaraozdenler — DISMISSED** [review]
Tested on TS2, chart worked as intended

**Review by max-bergmann — DISMISSED** [review]
Tested on TS3. Works as expected

**Review by cremertim — APPROVED** [review]
👍 . tested on ts1. works as expected. Can confirm the mentioned behavior of @Dominik-Weinzierl aswell

**Comment by willergeorg** [comment]
> In step 8 I was able to produce an internal server error since there is no start and end date validation of the course: image Therefore the active student chart wasn't able to handle those invalid dates :D (but this is not in the scope of your PR)
> 
> And there is one codacy issue regarding a println - i guess you can remove it.

I agree that this is not in scope of the PR. Please write an issue for the date validation (and maybe mark it as good first issue). And thanks for the heads-up, obviously I missed removing one of my debug statements. 😅

**Review by jschmautzer — DISMISSED** [review]
tested on ts1, works as expected :)

**Review by jbllhff — APPROVED** [review]
Tested on ts2, works fine. 
One comment: When I try to view the chart on a small window, it is cut off on the left hand side.

**Comment by willergeorg** [comment]
> Tested on ts2, works fine. One comment: When I try to view the chart on a small window, it is cut off on the left hand side.

Thanks for reporting. I'm currently working on enhancing the mobile appearance of various charts, including this one. :)

**Review by nairaarnez — DISMISSED** [review]
I just tested this PR in ts3, it works as described!

**Review by TheTrueVester — APPROVED** [review]
Tested on ts1. Everything works fine until you set the start date to over a year ago. At that point, it doesn't load anymore.

**Review by ge65cer — APPROVED** [review]
Tested on TS2 without issues.

**Review by alaraozdenler — APPROVED** [review]
Tested on TS3, works as described

**Review by nairaarnez — APPROVED** [review]
Tested in ts3, it works very well! The chart shows data from one day before the start of the course until two days after today. I only wanted to comment in case this was not intended. Otherwise, very good!

**Comment by willergeorg** [comment]
> Tested in ts3, it works very well! The chart shows data from one day before the start of the course until two days after today. I only wanted to comment in case this was not intended. Otherwise, very good!

We fetch the data weekly. This means it could be the case that we cover days before the official start date. For example, if the start date is a Wednesday, also data from Monday and Tuesday in this week are included in the weekly presentation. The same holds for the end date: if it is e.g. a Friday, also data from Saturday and Sunday is included. As the scope of the x axis labels is weekly (either calendar weeks in course detail or 'x weeks ago' in course management), this is an acceptable calculation imo. I hope this explanation makes the situation a bit clearer. If there are any further questions, do not hesitate to ask them. :)

**Comment by nairaarnez** [comment]
Perfect, thank you! Then everything else looks good!

**Pull request merged**
