### PR TITLE
Hide "Start new assessment" button in Tutor Exercise Dashboard

### PR DESCRIPTION
**Pull request by madwau**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
This PR addresses [this](https://github.com/ls1intum/Artemis/issues/1597) issue.

### Description
1. Hide row to start a new assessment in the Tutor Exercise Dashboard for Team Exercises
2. If the tutor has no assessments yet for a team exercise, show an info box in the location where assessments are started for individual exercises that informs the tutor that assessments are started elsewhere for team exercises (see screenshot below). This should only be seen in very rare cases though since there is now no longer a way to navigate to the Tutor Exercise Dashboard for team exercises via the UI (since the back button no longer redirects the user there).
3. The back button on assessments should lead back to the team page for team exercises (instead of to the Tutor Exercise Dashboard)
4. Perform server-side check if starting assessment is allowed for team exercise also if no result exists yet
5. The "Start new assessment" button on the team page should not be disabled even when the assessment due date has passed. It must be possible for tutors to assess submissions even when they missed the deadline since the teams need to receive an assessment (this is also allowed server-side). This issue was reported by @julian-christl.

### Steps for Testing
1. Log in to Artemis
2. Navigate to Course Management
3. Click on Tutor Course Dashboard (for a course with team exercises)
4. Click on the button "Exercise Teams" for a team exercise
5. Click on the short name of one of the teams
6. Make sure that team has a submission for that exercise
7. Click on the yellow button "Start Assessment" (or "Continue Assessment")
8. Click on the back arrow at the top left and make sure that it redirects back to the team page (and NOT to the tutor exercise dashboard)

### Screenshots
OnPaste 20200609-182651

### CODE REVIEW

**Comment by TobiasPr** [comment]
> The back button seems to be broken as well as the continue-assessment button.
> 
> teamExercise-backButtonNotWorking

Intresting, for me it's working (I tested modeling exercises)...

**Comment by TobiasPr** [comment]
There is also differnent behavior between modeling exercises and text exercises
Modeling Exercises:
modeling_exercises

Text Exercises
text_exercises

**Comment by madwau** [comment]
Thanks @florian-glombik and @TobiasPr.

I fixed the disabled "Continue assessment" button.

Good finding with the cancel button redirecting to the tutor dashboard for text exercises. Somehow this is slightly different than the modeling assessment component in that it has the route hardcoded for the cancel redirect. Will fix it.

**Comment by florian-glombik** [comment]
_Continue Assessment_ works for me now.

The back button has a very strange behaviour:

tutor: the back button doesn't work

instructor: the back button works

**Comment by TobiasPr** [comment]
Mh weird, still working for me as tutor and as instructor. For file upload, modeling and text exercises.

**Pull request merged**
