### PR TITLE
`General`: Fix wrong display of participation status

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Fix some errors introduced in the latest release.

### Description

Fixes three bugs:
- When starting an exercise the submission status (which would normally show the score), now correctly shows "no submission"
- When resuming an old exercise, the resume button is correctly replaced by the clone button, once the resuming is done
- When participating in a file upload exercise, the participation status always showed "not submitted"

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 normal Programming Exercise
- 1 old Programming Exercise with a participation
- 1 Fileupload exercise

1. Log in to Artemis
2. Participate in the normal exercise with a user that did not participate before
3. Check that "no submission" is correctly displayed

4. Navigate to the old exercise
5. Resume the old exercise
6. Check that the buttons are correctly displayed

7. Navigate to the Fileupload exercise
8. Participate and submit a file
9. Check that Artemis shows that a file was submitted

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by grochlitzzz — APPROVED** [review]
Working fine (tested on ts1)

**Review by simon-hng — APPROVED** [review]
code

**Review by PhilipWerz — DISMISSED** [review]
Works as expected. Tested on ts1.

**Review by TheZoker — DISMISSED** [review]
Code LGTM 👍

**Review by stefanwaldhauser — APPROVED** [review]
Code lgtm

**Review by timo07k — APPROVED** [review]
Everything works as expected. Tested on TS1.

**Review by simon-hng — APPROVED** [review]
reapprove code

**Review by grochlitzzz — COMMENTED** [review]
"No Submission" appears before starting the exercise, but once started, nothing shows up. Resume and File Upload working fine.
image
image
image
image

**Comment by krusche** [comment]
e2e tests currently fail. Please investigate why this is the case

**Review by simon-hng — APPROVED** [review]
reapprove code

**Review by LiaLism — APPROVED** [review]
Participation status is displayed correctly. Tested on ts1.

**Review by tobias-lippert — APPROVED** [review]
Tested on ts2. Works as described.

**Review by stefanwaldhauser — APPROVED** [review]
reapprove

**Pull request merged**
