### PR TITLE
`Development`: Avoid not found errors for missing grading scales

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code lgtm

**Review by laurenzfb — APPROVED** [review]
Code lgtm. Thanks for fixing this!

**Review by lennart-keller — APPROVED** [review]
Code lgtm

**Review by MichaelOwenDyer — APPROVED** [review]
Changes look good to me!

**Review by aplr — APPROVED** [review]
Code looks good, also moving auth checks before doing more db calls

**Pull request merged**
