### PR TITLE
`Development`: Convert constants from camelCase to screaming snake case

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

We have discussed in our weekly dev meeting that we should stick to a defined naming convention for constants, which is the use of "SCREAMING_SNAKE_CASE". This is the case for readonly variables on client-side and for static final variables on server side.

### Description

All constants are converted from camelCase style to SCREAMING_SNAKE_CASE style.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
- [x] Code Review 3
- [x] Code Review 4

### CODE REVIEW

**Review by sarpsahinalp — DISMISSED** [review]
Code lgtm, test are passing

**Review by JohannesStoehr — DISMISSED** [review]
Changes look good to me. Can we also add a rule to our linter and an Architecture test or something like that to verify the naming in the future?

**Review by az108 — DISMISSED** [review]
Code LGTM

**Review by muradium — COMMENTED** [review]
Refactoring LGTM 👍
Can we also make these changes for Playwright tests? There are only a few constants, most of them are the same as in Cypress.

**Review by muradium — COMMENTED** [review]
Thanks for the changes. There are a few more constants on these 2 files. Can you please rename them as well? 🙂 (the one on the first file is actually unused and can be removed)

- src/test/playwright/support/pageobjects/assessment/ProgrammingExerciseAssessmentPage.ts
- src/test/playwright/support/pageobjects/exercises/AbstractExerciseFeedbackPage.ts

**Review by marlon-luca-bu — APPROVED** [review]
Changes look good 👍 thanks for updating!

**Comment by edkaya** [comment]
> Thanks for the changes. There are a few more constants on these 2 files. Can you please rename them as well? 🙂 (the one on the first file is actually unused and can be removed)
> 
>     * src/test/playwright/support/pageobjects/assessment/ProgrammingExerciseAssessmentPage.ts
> 
>     * src/test/playwright/support/pageobjects/exercises/AbstractExerciseFeedbackPage.ts

Thanks for identifying them 🙂 Constants in the second file should already be changed in the previous push and I removed the unused constant in the first file in this push.

**Comment by edkaya** [comment]
> Changes look good to me. Can we also add a rule to our linter and an Architecture test or something like that to verify the naming in the future?

Good point, sure. We can do that in a seperate PR.

**Review by muradium — APPROVED** [review]
Thanks for the changes! LGTM now

**Review by az108 — APPROVED** [review]
reapprove

**Review by JohannesStoehr — APPROVED** [review]

**Review by marlon-luca-bu — APPROVED** [review]
Reapprove

**Review by sarpsahinalp — APPROVED** [review]
Reapproval

**Review by egekurt123 — APPROVED** [review]
Changes LGTM

**Review by pzdr7 — APPROVED** [review]
Code

**Review by krusche — APPROVED** [review]

**Pull request merged**
