### PR TITLE
`Programming exercises`: Fix Jenkins template for C

### LINKED ISSUE #6994: Using C programming exercises with Jenkins is broken
### Describe the bug

Currently when using Jenkins as the main CI and creating a programming exercise using C as the programming language does not work. Jenkins fails to compile it and does not respond with the result back to Artemis. 

### To Reproduce

1. Use for example TS2 (which used Jenkins as the CI)
2. Create a new programming exercise with C as the language
3. Go to the jenkins instance 
4. Inspect the CI run

### Expected behavior

Compile the programming language without issue or at least report the issue back to Artemis.

### Screenshots

No response to Artemis:
image

All builds fail:
image

### Which version of Artemis are you seeing the problem on?

6.3.8

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [X] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [X] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [X] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

Fixes #6994

### Description

I added the checkout path in the Jenkinsfile. I decided to reuse the RepositoryCheckoutPath class here. However, this caused issues if the solution checkout path wasn't defined for the language, hence I added a condition as is done for example for Aeolus.

Additionally, at the request of @JohannesStoehr, I removed the Constants to force developers to use language-dependent functionality in the future.

### Steps for Testing

**Main Test server: Legacy TS2 for Jenkins**, additional LocalCI test server of your choice.

Prerequisites:
- 1 Instructor (Legacy TS2 best accessible with the admin account, see Confluence)

1. Create a C exercise. The build for solution and base should run through as respected with 100% and 0% (retrigger if you get weird numbers on Legacy TS2, the setup there is quite flaky. Same goes for issues on creation. Just recreate the exercise)
2. Create a Java exercise. The build for solution and base should run through as respected with 100% and 0% (retrigger if you get weird numbers on Legacy TS2, the setup there is quite flaky. Same goes for issues on creation. Just recreate the exercise)

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| JenkinsBuildPlanCreator.java | 93% |                            |

## Summary by CodeRabbit

- **New Features**
	- Enhanced Jenkins integration to support multiple programming languages, improving build plan customization based on the project's programming language.
- **Refactor**
	- Modified Jenkins build plan creation logic to include programming language considerations, ensuring more tailored build processes.
- **Style**
	- Updated Jenkinsfile to incorporate directory-specific checkout stages, optimizing test execution paths.

### CODE REVIEW

**Review by coolchock — APPROVED** [review]
tested on legacy TS2 and on LocalVC TS3, template and solution build with 0 and 100% code lgtm

**Review by coolchock — APPROVED** [review]
re-approve

**Review by JohannesStoehr — APPROVED** [review]
Approve code

**Review by pzdr7 — APPROVED** [review]
Tested on legacy TS2 (0% / 100%) and TS1 (0% / 100%) ✅

**Review by krusche — APPROVED** [review]

**Pull request merged**
