### PR TITLE
`Programming exercises`: Only replace existing files when populating build plan repositories

### PR DESCRIPTION
**Pull request by SimonEntholzer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.

#### Client
- [x] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

In https://github.com/ls1intum/Artemis/pull/9521 the build plan population of programming was changed, to provide a consistent insertion of repository content during build plan population.
 
When inserting the contents of an auxiliary repository, at the moment, all content is replaced, even files which do not exist in the auxiliary repository. (First `rm` and then `mv`)

### Description

We want to retain files which are not overwritten.
To do this, this PR changes the `rm` + `mv` to a single `cp -r` operation. This overwrites files with the same name, and retains files not present in the auxiliary repository.

Example with a simple template repository and a simple auxiliary repository with nested directories:
(First screenshot is the directory structure, the second shows the file's content.)

Before copying the auxiliary repository:

After copying the auxiliary repository into the template repository with `cp -r  auxrepo/. assignment/src/`:

Notice, that after this operation, f2 and file2 were overwritten by the operation and have a different content now.

### Steps for Testing

1.  Create a programming exercise (java e.g.) with an auxiliary repository, with a checkout path that will replace data from the template. E.g. if the package name is "package", set the auxiliary repository's checkout directory to assignment/src/package" 
2. Save the exercise. Both the template and solution build plan should succeed. (0% and 100%)
3. Now add the BubbleSort.java file from the solution repository's src/package folder to the root of the auxiliary repository. 
4. The soultion bulid should stay at 100% (the BubbleSort.java file is replaced with an identical copy)
5. The template build should get a build failure, because the SortStrategy is not yet implemented, but needed by the injected BubbleSort.java

Expected build results:  
image

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| BuildJobContainerService.java | 79% | ✅ ❌ |

## Summary by CodeRabbit

- **New Features**
	- Enhanced file handling process for Docker containers, simplifying the management of repository files during build jobs.
	- Updated descriptions in the localization files for auxiliary repositories, clarifying file overwriting behavior.
- **Bug Fixes**
	- Removed outdated methods for directory management, improving overall efficiency and clarity in file operations.

### CODE REVIEW

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Everything works as described

Screenshot 2024-12-08 181726
Screenshot 2024-12-08 181844

**Review by SimonKaran13 — COMMENTED** [review]
I tested on TS1 and it does not work as expect. I followed the instructions and created an aux repo. And I get a build failed in the solution repo. It says that the BubbleSort class is duplicate.

Aux Repo checkout path:
image

Aux repo BubbleSort.java:
image

Solution repo BubbleSort.java
image


Solution Repo build output:
image

**Comment by SimonEntholzer** [comment]
> I tested on TS1 and it does not work as expect. I followed the instructions and created an aux repo. And I get a build failed in the solution repo. It says that the BubbleSort class is duplicate. Additionally, it is not possible to use usual java package names that contain '.' like 'de.tum.cit.xyz' because you are not allowed to set as the check out directory path.
> ...

The problem is that you added the BubbleSort.java in the auxiliary reposiotory, within its own src/testPackage folders. This means the whole folder is injected, and you end up with two identical files, although in different folder places.

This is what you end up with (excluding all other files):
image

By removing the folders from the auxiliary repository, and having the BubbleSort.java at the directory root, it should work as described. 
I adapted the testing instructions to make this more clear.

**Review by SimonKaran13 — APPROVED** [review]
I tested again on TS3 following the updated instructions and it worked as expected. I also tried a nested package name (as usually used in java) and it worked.
image

**Review by BBesrour — APPROVED** [review]
code

**Review by iyannsch — APPROVED** [review]

**Pull request merged**
