### PR TITLE
`Development`: Remove public modifier from server test cases

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
JUnit 4 forced test cases to have public visibility. With JUnit 5 this is no longer the case, in fact it is best practice to not use public as a visibility modifier for test cases. See https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods and https://rules.sonarsource.com/java/RSPEC-5786.

### Description
Search and Replace. Removed public from test cases and test classes.

The additional removed lines are because I removed an empty method [in the FeedbackSelectorTest](https://github.com/ls1intum/Artemis/pull/5324/files#diff-2126dee35cc06b3a4ce6658076badabc8e7c005b3e1c680f4f5b7ac274e2b65f).

### Steps for Testing
code review; check that the tests are still successful.

This PR adds a new PMD-Rule that checks against public test cases. So you can just open the Codacy-Report and check that there are no such style issues present.

#### Code Review
- [x] Review 1
- [x] Review 2

### CODE REVIEW

**Review by Marvin-Vitcu — APPROVED** [review]
Went through the entire code changes.
Code looks fine.
There some methods were "public" was changed to "private", however they all seem to be auxiliary methods therefore this should be fine.

**Review by Marvin-Vitcu — APPROVED** [review]

**Review by Hialus — CHANGES_REQUESTED** [review]
You should also adapt the documentation accordingly. 
Consider adding a note to the Coding & Design Guidelines > Server > General Testing Tips and also adapting any examples like this:
grafik

**Review by ge65cer — DISMISSED** [review]
I'm in favor of these changes. In a perfect world, our static code analysis should complain about public methods in test cases. 😉

**Review by babyygemperor — DISMISSED** [review]
Reapprove, code still good👍🏼

**Review by babyygemperor — DISMISSED** [review]
Reapprove x2, code still looks good to me

**Comment by joaquinmurcia** [comment]
Code looks good to me; no pending method to change from public to protected.

**Review by ge65cer — DISMISSED** [review]
Re-approve

**Review by stefanwaldhauser — DISMISSED** [review]
Looks good!

**Review by yuling-sun — DISMISSED** [review]
LGTM.

**Review by SimonPaul02 — DISMISSED** [review]
LGTM👍

**Comment by krusche** [comment]
@Strohgelaender The PR currently has merge conflicts and cannot be merged. Please resolve them and ping me on Slack, then I can merge it immediately.

**Pull request merged**
