### PR TITLE
`General`: Remove breadcrumbs in student view

### PR DESCRIPTION
**Pull request by rabeatwork**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Instructor
- Navigate through the course

1. Log in to Artemis
2. Navigate to Course Overview
3. Select a Course
4. Verify that Breadcrumbs are gone
5. Navigate to Course Management
6. Verify that Breadcrumbs still available

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

image

### CODE REVIEW

**Review by pzdr7 — APPROVED** [review]
Tested on TS3.

- No breadcrumbs in the student course view ✅ 
- Breadcrumbs in the course management view ✅

**Review by florian-glombik — APPROVED** [review]
The code looks good to me

**Review by marlon-luca-bu — APPROVED** [review]
Code LGTM

**Comment by krusche** [comment]
I would like to wait until 7.2.0 until we merge this PR. We also need to make sure that the navigation really works in all student views without issues

**Pull request closed without merging**
