### PR TITLE
`Communication`: Fix dropdown menu behavior for links to allow default browser options

### LINKED ISSUE #9776: `Communication:` Get standard drop down menu when right clicking a link
### Is your feature request related to a problem?

I want to open a link in a new tab, but I can't because I don't get the normal drop-down menu like I get normally (see reference Confluence screenshot).
Screenshot from 2024-11-13 23-30-12
Screenshot from 2024-11-13 23-30-06

### Describe the solution you'd like

Get the browser's standard drop-down menu. I use, for example, Chrome.

### Describe alternatives you've considered

Or enabled to open the link in a new tab.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] This is a small issue that I tested locally.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

When a user right-clicks on a link within a message, the dropdown menu opens instead of displaying the browser's default context menu (e.g., option to open the link in a new tab). 
(Closes #9776)

### Description

The dropdown menu is now disabled when the user right-clicks on a link, allowing the browser's default options to be displayed.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with Communication enabled

1. Log in to Artemis.
2. Navigate to the Communication section of a course.
3. Post a message in a channel containing a link, such as: "Here is the link [www.google.com](http://www.google.com/)".
4. Right-click on the link and verify that the dropdown menu does not appear, and the browser's default context menu is shown.
5. Right-click on any other part of the text and confirm that the dropdown menu opens as expected.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [X] Code Review 1
- [X] Code Review 2
#### Manual Tests
- [X] Test 1
- [X] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| answer-post.component.ts | 96.22% | ✅ ❌ |
| post.component.ts | 95.28% | ✅ ❌ |

## Summary by CodeRabbit

- **New Features**
	- Enhanced right-click interactions in both the AnswerPost and Post components, ensuring dropdown behavior is contextually appropriate based on cursor style.

- **Bug Fixes**
	- Improved handling of right-click events to prevent default actions when the cursor is not a pointer.

- **Tests**
	- Added new test cases for the `onRightClick` method in both the AnswerPost and Post components to validate behavior under different cursor styles.

### CODE REVIEW

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS6. Works as described.

**Review by HawKhiem — APPROVED** [review]
Tested on TS5. Everything works as expected!

**Review by sachmii — APPROVED** [review]
Tested on TS3, worked fine.

Bildschirmfoto 2024-11-21 um 10 14 01

**Review by sawys777 — APPROVED** [review]
Tested on TS1, everything worked fine.

**Review by PaRangger — DISMISSED** [review]
Tested on TS6, works great, code changes lgtm 👍

**Review by flbrgit — DISMISSED** [review]
Tested on TS1, everything works as expected

**Review by SimonEntholzer — APPROVED** [review]
Works on Ts1

**Review by PaRangger — APPROVED** [review]
Reapprove, Re-tested on TS1 👍

**Review by FelberMartin — APPROVED** [review]
Tested in both Firefox and Chrome, works as described

**Review by cremertim — APPROVED** [review]
Tested on ts1, works as expected

**Review by julian-wls — APPROVED** [review]
Tested on TS1, works as expected.

**Pull request merged**
