### PR TITLE
`Development`: Delete duplicated change set in master.xml

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Description

Delete a duplicated entry in the change set. The change set that is further down is not executed anyway.

### Steps for Testing

Prerequisites:

1. Start Artemis
2. Make sure that there is no exception from liquibase

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by Hialus — APPROVED** [review]
As you only delete a duplicated reference to a changeset, and Liquibase will only execute each changeset once, this will not alter the behavior of Liquibase.

**Review by Strohgelaender — APPROVED** [review]

**Review by TheTrueVester — APPROVED** [review]
Tested on ts1 during testing session. Everything worked as expected.

**Review by Dominik-Weinzierl — APPROVED** [review]
The complex code changes look good to me ;)

**Review by babyygemperor — APPROVED** [review]
Tested on ts1 in a testing session.
Code changes look a bit daunting but look reasonable

**Pull request merged**
