### PR TITLE
`General`: Fix display bug of complaint due date if no submission due date is present

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Fix a bug where a non existent complaint deadline is shown for exercises without deadline.

### Description

A programming exercise without a deadline but with a successful automated result wrongly showed a complaint deadline in the header of the exercise. This wrong information is no longer shown.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1Students
- 1 Programming Exercise without a deadline

1. Log in to Artemis
2. Create the exercise
3. Participate as a student
4. No longer see a wrong complaint deadline in the header.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

No deadline but a complaint deadline:
Bildschirmfoto 2022-07-04 um 17 09 16

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code looks good, thanks for the quick fix.

**Review by ge65cer — APPROVED** [review]
Code approved. Great that you thought about adding a client test for this case! 🙂

**Review by nadinesamyy — APPROVED** [review]
tested on ts2, works as described

**Review by jschmautzer — APPROVED** [review]
tested on ts1, worked as described

**Review by alaraozdenler — APPROVED** [review]
tested on ts1, works as described

**Review by Marvin-Vitcu — APPROVED** [review]
Tested on TS2. Works as intended.

**Pull request merged**
