### PR TITLE
`General`: Improve formatting for long durations

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).

### Motivation and Context
* Generally, long durations were shown as, e.g., `2d 0h 4min 0s`. The updated format removes the unnecessary zero-valued parts to show it as `2d 4min` (unless the duration is zero, then `0s` is still shown).
* On the submissions list pages the durations were always shown in minutes. However, e.g., `11272 minutes` is not intuitive. Those durations are now shown in the format as described above with days/hours/minutes.

### Description
The duration from seconds pipe has been updated, so the change is consistent for all durations across Artemis that use it.

The submissions list views have been updated to now use this pipe as well. There currently is a lot of duplication for those. Fixing this is out-of-scope here, issue #5941 has been created for that. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 non-quiz Exercise that has a few submissions

1. Log in to Artemis
2. Go to the exercise page.
3. Go to ‘Submissions’. A table with the submissions in this exercise is shown. The duration column should be formatted as described in the Motivation section.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| artemis-duration-from-seconds-pipe | 97% | 97% |

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code looks good.

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
The "unnecessary" zeros were added intentionally, since this Pipe is also used for counting timers (e.g. time left during an exam) and it's a bit weird when suddenly the timer gets shorter and in the next second longer again, just because the seconds were equal to zero.

**Comment by b-fein** [comment]
@JohannesStoehr Would it be okay to use the short format for the timers then? That way it has consistently two elements.
If the duration is over one hour, then the additional precision including seconds shouldn’t matter realistically, and if it is less than that, it automatically switches to the minutes+seconds format.

**Review by stefanwaldhauser — APPROVED** [review]
Approve

**Comment by JohannesStoehr** [comment]
> @JohannesStoehr Would it be okay to use the short format for the timers then? That way it has consistently two elements.
> If the duration is over one hour, then the additional precision including seconds shouldn’t matter realistically, and if it is less than that, it automatically switches to the minutes+seconds format.

That should work. Can you take a look at the timers that are visible to students during the conduction of an exam?
If they do not suddenly change lengths every minute, it should be fine

**Comment by b-fein** [comment]
@JohannesStoehr The `exam-timer.component` already uses the short format:
```ts
    updateDisplayTime(timeDiff: plugin.Duration) {
        // […]
        // transform(seconds: number, shortFormat: boolean)
        return this.timePipe.transform(round(timeDiff.asSeconds()), true);
    }
```

So the change here does not affect the exam timer.

**Review by timo07k — COMMENTED** [review]
Everything working, apart from: 

image

Is it supposed to be "0min 0s"?
Tested on TS1.

**Review by JohannesStoehr — APPROVED** [review]
Code changes look good to me

**Review by Strohgelaender — APPROVED** [review]
re-aprove, changes look good.

**Review by LiaLism — APPROVED** [review]
The format is displayed correctly. Tested on ts1.

**Pull request merged**
