### PR TITLE
`Exam mode`: Fix exam test run summary

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Issue #5675 

### Description

When the exam is submitted during a test run, the user is forwarded to the exam summary page.
Furthermore, the "Review is open" alert is hidden for test runs.

### Steps for Testing

Prerequisites:
- 1 Instructor, 1 Student
- 1 Real Exam with multiple exercises of all kind

1. Log in to Artemis
2. Navigate to the Exam
3. Create a Test Run
4. Participate in the Test Run
5. Ensure you are forwarded to `/course-management/x/exams/x/test-runs/x/summary` when the exam is over/you submit the exam
6. Check that the "Review is open" alert no longer appears on the summary page
7. Ensure that normal exam conduction is unaffected
8. Repeat the steps with a _Test Exam_

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

Added a test case for the routing redirect.

### CODE REVIEW

**Review by manuelmanso — CHANGES_REQUESTED** [review]
Tested on ts1, works as described: redirected to the summary page and "Review is open" no longer appears. Code also LGTM.

There's a failing test case though, please fix it.

**Comment by ge65cer** [comment]
@manuelmanso Looks like that was just a flaky test, all green now.

**Review by manuelmanso — APPROVED** [review]
Re-approve!

**Review by JohannesStoehr — APPROVED** [review]
Looks good to me

**Comment by frederik-kt** [comment]
Looks good! Redirection to /course-management/id/exams/id/test-runs/id/summary works and no "Review is open" alert is shown.

**Review by frederik-kt — APPROVED** [review]

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
