### PR TITLE
`Development`: Fix flaky server test

### PR DESCRIPTION
**Pull request by krusche**
One server test fails on Github Actions

`NotificationScheduleServiceTest > shouldCreateNotificationAndEmailAtAssessmentDueDate()`

This PR aims to fix it

### CODE REVIEW

**Review by ge65cer — APPROVED** [review]
Tests ran through, code changes look good.

**Review by manuelmanso — APPROVED** [review]
Changes look good to me 👍

**Review by stefanwaldhauser — APPROVED** [review]
Looks like a good fix!

**Review by JohannesStoehr — APPROVED** [review]
The refactoring and the increase of the timeouts looks good

**Pull request merged**
