### PR TITLE
Speedup the Assessment Dashboard for Large Exams

### LINKED ISSUE #2874: Exam assessment dashboard does not load when manual assessment of programming exericses is enabled
### Describe the bug
When an exam has been conducted, and afterwards the manual assessment of programming exercises is activated, the assessment dashboard does not load.

#### To Reproduce
1. Create exam with some programming exercises.
2. Conduct the exam.
3. Activate "manual assessment" for some programming exercise.
4. The assessment dashboard does not load anymore. Even the exercises the previously showed up (text exercises, for example) don't show up anymore.

#### Expected behavior
All exercises that should be manually reviewed should show up in the assessment dashboard of an exam.

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context
For the EidI exam with about 1800 students, the exam assessment dashboard takes over four minutes each time we load the page. This PR aims to reduce the load times until they match the load times of the assessment dashboards of equally large courses (e.g. PGdP).

This fixes #2874.

### Description
- Replace four levels deep nested sub-queries by (implicit) joins in `countByComplaintResultParticipationExerciseIdAndComplaintComplaintTypeIgnoreTestRuns`. This logic should be closer to the 'magic' `countByComplaint_Result_Participation_Exercise_Id_AndComplaint_ComplaintType_AndSubmittedTimeIsNotNull` now.
  - [ ] TODO: Check that this was the problem / improves the perfomance. -> Will be checked by @krusche when this PR is merged in `develop`.

### Steps for Testing
0. Have an exam with assessments and complaints and at least a few submissions.
1. Check that the complaint statistics and progress bars for the assessment dashboard are the same with this bugfix PR and without it. Only the performance should improve (but you would need a large exam to check that).
2. Check that doing tests runs and assessing them, including answered and unanswered complaints has no effect on the numbers in the dashboard.

### Test Coverage
Same as before. The code that we changed in this PR is covered.
image

### CODE REVIEW

**Review by nicolasruscher — APPROVED** [review]
The new query looks good to me, it should hopefully improve the performance. Tested it locally and the qery itself works well. Couldn't find any deviations from the old query. 👍  But I could not test the performance improvements.

**Review by airelawaleria — APPROVED** [review]
tested in the testing fashion with @simonzilker @JohannesWeiss @marvinchimeka 
Works as expected

**Review by JohannesWeiss — APPROVED** [review]
Tested in testing session on ts1, works as expected.

**Review by marvinchimeka — APPROVED** [review]
No issues found

**Review by simonzilker — APPROVED** [review]
Looks good :)

**Review by SimonEntholzer — APPROVED** [review]
Tested both variants with a (rather dirty) Unit test. Both yield the same values, so the change works correctly, at least as far I tested it. I also tried to test the performance improvement, but I wasn't really successful there. .

**Review by EneaGore — APPROVED** [review]

**Review by ivanchimeno — APPROVED** [review]
Looks good :+1:

**Review by FrankeLukas — APPROVED** [review]
Still works as expected on TS1 and the code changes look reasonable to me.

**Review by krusche — APPROVED** [review]
The new query looks so much better ;-) Thanks

**Pull request merged**
