### PR TITLE
`General`: Animate content sidebar on toggle

### PR DESCRIPTION
**Pull request by PaRangger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context

The sidebar to switch between exercises/lectures/communication is animated when toggling it. The sidebar for the content however simply vanishes. For better consistency and a smoother user interface I animated the content sidebar.

### Description

I added an animation by gradually lowering the width of the sidebar and lowering the opacity of the items inside the sidebar. To make this smooth some minor layout changes were necessary. I removed the gap property that seperated the sidebar and the content, and instead added a margin directly to the sidebar.

### Steps for Testing

Prerequisites:
- 1 Student/Instructor/Tutor
- 1 Course with an exercise/lecture or communication enabled.

1. Log in to Artemis
2. Navigate to the course
3. Locate the sidebar icon and press it
4. The sidebar should smoothly transition in and out
5. Additionally, to verify the layout changes, check if the margin on the right of the sidebar looks proper

### Screenshots
sidebar

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

## Summary by CodeRabbit

- **New Features**
	- Enhanced sidebar behavior with improved transitions and hover effects for a smoother user experience.
	- Introduced new SCSS variables for better styling consistency, including sidebar width and transition durations.
	- Added a new class for improved styling of the collapse button in the exam navigation sidebar.

- **Bug Fixes**
	- Adjusted conditional rendering logic in various components to ensure correct display based on user interactions and application state.

- **Documentation**
	- Updated SCSS variable definitions for improved clarity and organization in styling components.

- **Style**
	- Improved layout, spacing adjustments, and visual feedback in sidebar and course-related components, including refined transition effects.

### CODE REVIEW

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Can you add a screenshot/screencast of the changes in the PR description?

**Review by janthoXO — CHANGES_REQUESTED** [review]
This is a lot of subjective preferences, but for me the sidebar takes too long to collapse. Also I would orientate the animation more on commonly animations like [this react animation](https://codesandbox.io/p/sandbox/animated-sidebar-jvvg2?file=%2Fsrc%2FApp.js)

**Review by janthoXO — CHANGES_REQUESTED** [review]
The animation of the general sidebar and the exercise sidebar are not consistent.
The general sidebar has just an extending and simultaneously fade in of the text. Whereas the exercise sidebar first extends and then lets the text fade in.

**Review by janthoXO — COMMENTED** [review]
The sidebar can be collapsed by pressing crtl+shift+m. 
Is this a feature or a bug? because this is no where documented

**Comment by PaRangger** [comment]
> The animation of the general sidebar and the exercise sidebar are not consistent. The general sidebar has just an extending and simultaneously fade in of the text. Whereas the exercise sidebar first extends and then lets the text fade in.
> 
>  Screen.Recording.2024-10-03.at.22.16.39.mov

I changed the animation to have no delay between fade and slide. Additionally I made the animation faster 👍🏼

**Comment by PaRangger** [comment]
> The sidebar can be collapsed by pressing crtl+shift+m. Is this a feature or a bug? because this is no where documented

It should be possible with ctrl+shift+b. Not with ctrl+shift+m. For me it does not work with ctrl+shift+m though. Could it be a keyboard layout thing? 🤔 I have a german keyboard layout (WERTZ).

**Comment by PaRangger** [comment]
> Can you add a screenshot/screencast of the changes in the PR description?

Added a .gif that shows the animation 👌🏻

**Comment by janthoXO** [comment]
> It should be possible with ctrl+shift+b. Not with ctrl+shift+m. For me it does not work with ctrl+shift+m though. Could it be a keyboard layout thing? 🤔 I have a german keyboard layout (WERTZ).

okay its a weird bug and really an edge case.
But if you click the sidebar button of the exercise sidebar and instantly press ctrl+m, after that the exercise sidebar can be collapsed by pressing crtl+shitt+m
its really a weird edge case, so if you quickly find whats causing it then good, but otherwise just ignore it xD

**Review by janthoXO — DISMISSED** [review]
Tested on TS4

**Review by janthoXO — DISMISSED** [review]
Love that the icon animation is now the same as well 🫶
Tested on TS4 and reapprove

**Review by rabeatwork — APPROVED** [review]

**Review by rabeatwork — APPROVED** [review]
Thanks for addressing my feedback. :)

**Review by SimonEntholzer — DISMISSED** [review]
Looks good on Ts4, I like the animation :+1:

**Review by krusche — DISMISSED** [review]
Great improvement 👍

**Review by krusche — APPROVED** [review]

**Pull request merged**
