### PR TITLE
[Followup] Student-exam-detail rest call checks and logs

### PR DESCRIPTION
**Pull request by SimonEntholzer**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).

### Motivation and Context

The REST calls in the student-exam-detail that change the submitted state of the individual student-exam did not check if the individual working time was already over. I added this, and put the logs at the end, so they are only executed after all checks pass.

### Steps for Testing

Create an exam, for one student increase the individual working time. Now while the exam has already started, and the normal end date of the exam ran out, go to the student-exam-detail again, and try to use the "change student exam to submitted" button. 
There should be an error message:

### CODE REVIEW

**Review by FrankeLukas — APPROVED** [review]
Lgtm and works as advertised. Ideally we wouldn't even show the toggle button for exams where this is not an option yet. Would that be possible?

**Review by tiffca — APPROVED** [review]
Works as described

**Review by airelawaleria — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]
Code lgtm

**Review by nicolasruscher — APPROVED** [review]
looks good!

**Review by philgabr — APPROVED** [review]

**Review by EneaGore — APPROVED** [review]
Lgtm on ts1.

**Review by simonzilker — APPROVED** [review]
works as intended on ts1

**Review by marvinchimeka — APPROVED** [review]
👍

**Review by derLalla — APPROVED** [review]
nice code changes. I couldn't find any issues.

**Review by krusche — APPROVED** [review]

**Pull request merged**
