### PR TITLE
`Assessment`: Update assessor after overriding

### LINKED ISSUE #7757: `Assessment`: Editing another tutor’s assessment shows ‘locked by null (null)’
### Describe the bug

When editing another tutor’s/instructor’s manual assessment, the UI shows which tutor/instructor created the original assessment. After editing/overriding the assessment, this text breaks.

### To Reproduce

1. As an instructor open a manual assessment owned by another tutor/instructor. It shows assessment is locked by the correct owner.
2. Change or add an (inline) feedback.
3. Override the assessment.
4. The name of locked by is now null (null).

### Expected behavior

The assessment locked by text is changed to `me` instead of `null`.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.7.0

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional context

Tested only for programming exercises.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by kaancayli**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

When editing another tutor’s/instructor’s manual assessment, the UI shows which tutor/instructor created the original assessment. After editing/overriding the assessment, this text breaks. This PR fixes #7757 

### Description
After a successful submission/override, update the assessor. After the assessor is updated correctly, right text is shown

### Steps for Testing

Prerequisites:
- 2 Instructors
- 1 Student
- 1 Programming Exercise with manuel assessment enabled.

1. Submit to the programming exercise.
2. After the submission deadline is over, start with the manuel assessment with an instructor.
3. As an instructor open a manual assessment owned by the instructor. It shows assessment is locked by the correct owner.
4. Change or add an (inline) feedback.
5. Override the assessment.
6. Ensure that the lock text is updated correctly, and states that the current instructor (you) ownes the assessment now. (does not contain null (null)).

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

Before overriding (locked by artemis_test_user_11):
Screenshot 2024-01-18 at 23 13 49
After overriding:
Screenshot 2024-01-18 at 23 14 11

## Summary by CodeRabbit

- **New Features**
  - Enhanced assessment submission process with permission checks.

- **Bug Fixes**
  - Improved test cases to reflect updated assessment override behavior.

- **Refactor**
  - Updated imports and variable declarations for consistency and clarity in test specifications.

- **Tests**
  - Refined unit tests to ensure accurate assessor updates and result handling.

### CODE REVIEW

**Review by LenaKahle — APPROVED** [review]
Approve, tested on ts4, works as described.

**Review by konrad2002 — APPROVED** [review]
manually tested on ts4, works as expected

**Review by basak-akan — APPROVED** [review]
code lgtm

**Review by b-fein — APPROVED** [review]
Code change makes sense to me. Thanks!

**Pull request merged**
