### PR TITLE
`Communication`: Fix authorization error in courses without messaging

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Fix a bug when navigating into a course without messaging enabled

### Description

Currently the client always tried to check if there are unread messages, even when they were disabled in a course, which lead to an authorization error on the course page. This is now fixed.

### Steps for Testing

Prerequisites:
- 2 users (instructors, students, ...) that are part in the courses
- 2 courses, one with messages enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. Check that you don't get an authorization error when navigating into the course without messaging
4. Check that you still see a red dot above the messaging tab when navigating into a course with messaging after you received a message there

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by RY997 — APPROVED** [review]
Tested on ts5, worked well!

**Review by Strohgelaender — DISMISSED** [review]

**Review by tunargs — APPROVED** [review]
Code LGTM

**Review by Strohgelaender — APPROVED** [review]

**Review by RY997 — APPROVED** [review]

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM 👍

**Review by tunargs — APPROVED** [review]
reapprove

**Review by MichaelOwenDyer — COMMENTED** [review]
Looks good to me

**Pull request merged**
