### PR TITLE
`Development`: Add e2e tests for exporting quiz exercise questions

### PR DESCRIPTION
**Pull request by muradium**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Exporting quiz exercise questions by user is not tested.

### Description
Adds an E2E test in Playwright for exporting quiz exercise questions from course exercises management page.

### Steps for Testing
- **Code Review**: Ensure that tests pass for valid reasons, functionality is adequately tested, and check the code quality.
- **Run the tests (optional)**: Tests are checked by automatic run in CI environment. You can optionally run them locally and check if they pass.

**Steps for running the tests:**
1. Navigate to **src/tests/playwright**
2. Configure Playwright using playwright.env file based on your local setup. Current configuration should work for default Artemis setup.
3. Run `npm install && npm run playwright:setup && npx playwright test e2e/exercise/quiz-exercise/QuizExerciseManagement.spec.ts`
4. Confirm that **"Export quiz exercise questions"** test passes.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by rstief — DISMISSED** [review]
Demonstrated in testing session, code also looks good 👍

**Review by pzdr7 — DISMISSED** [review]
Demonstrated to work during testing session. Code looks good 👍

**Review by undernagruzez — DISMISSED** [review]
demonstrated in a testing session

**Review by coolchock — DISMISSED** [review]
lgtm

**Review by coolchock — APPROVED** [review]
re-approve

**Review by pzdr7 — APPROVED** [review]

**Review by rstief — APPROVED** [review]

**Review by undernagruzez — APPROVED** [review]

**Pull request merged**
