### PR TITLE
`Quiz exercises`: Do not include ungraded results on scores page

### LINKED ISSUE #7150: `Quiz exercises`: The grade is deleted after practice
### Describe the bug

In production. When a student solves a quiz (during the corresponding time), then this quiz is released for practice and the student resolves it again, the grade is deleted. 

### To Reproduce

1. Create a quiz with a specific time
2. As student, solve the quiz and wait for your grade (screenshot 1)
3. As instructor, verify the student has a grade and then releases the quiz for practice
4. As student, resolves again the quiz
5. As instructor, verify that the grade is deleted (screenshot 2)

### Expected behavior

The grade obtained in the normal quiz resolution should not disappear. 

### Screenshots

Screenshot 1: 

image

Screenshot 2: 

image

### Which version of Artemis are you seeing the problem on?

6.4.2

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

### Motivation and Context
Graded submission of quiz exercises were shadowed by not-graded submissions made during practise period after the end of the exercise period. 
Fixes #7150.

### Description
The reason was that the server was always returning the latest submission. This PR changes database query so that it looks only for graded results.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Quiz Exercise

1. As student, solve the quiz and wait for your grade (screenshot 1)
1. As instructor, verify the student has a grade and then releases the quiz for practice
1. As student, resolves again the quiz
1. As instructor, verify that the original grade is still present.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| ParticipationResource.java | 94% | ✅              |

### CODE REVIEW

**Review by Santia-go — DISMISSED** [review]
Tested on TS1. 

Working as expected. The grade during the first attempt is saved in the instructor's view, even if the student practiced the quiz and got a worse/better result. 

Grade in the first attempt (student 1 = 50 %): 
Screenshot 2023-09-24 at 11 26 55

In the practice, the student gets 0 %
Screenshot 2023-09-24 at 11 32 40

However, the grade in the instructor's view is correct. Showing the one that the student got in the first attempt. 

Screenshot 2023-09-24 at 11 33 28

Approved! Thank you @jakubriegel

**Review by Strohgelaender — CHANGES_REQUESTED** [review]
PE-practice participation are no loger present in the participation list: 

develop:
grafik
 The pratice participation in the bottom is not shown in this PR.

**Review by Strohgelaender — APPROVED** [review]
the issue is now fixed and other exercises still work fine.

**Review by JohannesStoehr — APPROVED** [review]
Approve code changes

**Review by Santia-go — APPROVED** [review]
Tested in TS1 

Working as expected!

**Review by laadvo — APPROVED** [review]
Code LGTM

**Review by dearjasmina — APPROVED** [review]
code lgtm

**Pull request merged**
