### PR TITLE
`Communication`: Fix an issue with list formatting in Markdown

### LINKED ISSUE #9881: `Communication:` Invalid Markdown for Lists in Artemis
**Description**
It seems that Artemis currently adds the bullet point (•) directly as a text character instead of generating valid Markdown syntax for lists. This leads to issues where the following output is produced:
```
• Item 1  
• Item 2 
```
Instead of the proper Markdown format:
```
- Item 1  
- Item 2  
```
https://github.com/ls1intum/Artemis/blob/83ac531853ef2b88367e9d5129b8a6ea94e70711/src/main/webapp/app/shared/monaco-editor/model/actions/bulleted-list.action.ts#L4

image (1)
image

**Expected Behavior**
Lists in Artemis should be generated using valid Markdown syntax to ensure compatibility and proper rendering across all platforms

**Actual Behavior**
Artemis produces lists with the bullet point (•) embedded as plain text. This approach causes:
- Compatibility issues, particularly on iOS and Android.
- General rendering problems in Markdown-compliant tools.

**Steps to Reproduce**
1. Create a list in Artemis.
2. Observe the output format in the preview or exported text.
3. Notice the use of the • character instead of Markdown-compatible list syntax.
4. In the iOS app you can see that it did not got formatted (see screenshot)

**Environment**
Artemis Version: 7.7.2
Platforms: Safari

**Additional Notes**
This issue likely affects all platforms (web, iOS, Android) and could lead to inconsistent behavior. As Markdown is widely used for formatting, generating invalid syntax should be avoided.

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

- Previously, the editor automatically added list prefixes (e.g., -, 1.) after selecting the list option. However, it did not automatically add a prefix when the previous line already contained one unless the user had pressed the list option button once before starting the list, unlike the behavior in Slack.
- The unordered list prefix character is incompatible with the iOS app, it needs to be changed from "• " to "- ". 
(Closes #9881)

### Description

- This change implements auto-prefixing for list creation. If the previous line contains a list prefix (e.g., -, 1.), the editor now automatically adds the same prefix to the next line, without requiring the user to manually select the list option. 
- The unordered list prefix character has been changed from "• " to "- ". 

### Steps for Testing

Prerequisites:
- 1 Instructor/Student
- 1 Course with Communication enabled

1. Log in to Artemis.
2. Navigate to the Communication section of a course.
3. Without selecting any list option, type something that starts with a list prefix, such as "- list item" or "1. list item."
4. Press Shift/Cmd + Enter to move to a new line and notice that the prefix is added automatically.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [X] Code Review 1
- [X] Code Review 2
#### Manual Tests
- [X] Test 1
- [X] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| posting-content-part.components.ts | 94.11% | ✅ ❌ |
| posting-markdown-editor.component.ts | 82.5% | ✅ ❌ |
| bulleted-list.action.ts | 100% | ✅ |
| list.action.ts | 76.92% | ✅ ❌ |
| ordered-list.action.ts | 100% | ✅ |
| monaco-editor.component.ts | 94.8% | ✅ ❌ |

## Release Notes

- **New Features**
  - Enhanced content processing to support unordered lists in the editor.
  - Improved markdown editor functionality for dynamic list formatting based on user input.
  - New methods added to the Monaco editor component for better content management.

- **Bug Fixes**
  - Adjusted list prefix handling to ensure consistent representation in the text editor.

- **Tests**
  - Expanded test coverage for content processing, markdown editing, and Monaco editor interactions to ensure robustness and accuracy.
  - Added tests for handling model content changes and retrieving line content in the Monaco editor.

### CODE REVIEW

**Review by SimonKaran13 — COMMENTED** [review]
Tested on TS3, works as expected. 

I tried adding sub items into the lists.
Like:

1. one
2. two
   1. subitem one
   2. subittem two

But it doesn't work. It seems that having subitems didn't work before though (doesn't render correctly). So I think it's fine :)

**Review by Haoyuli2002 — COMMENTED** [review]
Tested on TS2 as Instructor 16. I checked list options including "-" and "1", "2". Both of them are woking as described. 
Screenshot 2024-12-02 at 11 56 04

**Review by zagemello — APPROVED** [review]
Works as expected, tested on TS2

**Review by SimonEntholzer — APPROVED** [review]
Code

**Pull request merged**
