### PR TITLE
`General`: Fix date time picker issues for modeling, text, and file upload exercises

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context

When creating a modeling, text or file upload exercise, the date time picker for the dates (start date, due date, assessment date) should suggest the value of the previous field as the default like it is the case in programming exercises. E.g. if you select 15:30 h as the release date, the date time picker should suggest 15:30 h for the start date and so on.

### Description

Adapted the update component htmls for the different exercises to provide the described functionality.

### Steps for Testing

**Test for modeling, text and file upload exercise**

Prerequisites:
- 1 Instructor

1. Open create exercise view
2. Select a date in the past or future for the release date
3. Select date for start date: The date time picker should suggest the value from the release date
4. Choose a different time for the start date (e.g. 1 min later)
5. Check the same for due date and then assessment date

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by JohannesWt — APPROVED** [review]
Code looks good

**Review by Jan-Thurner — APPROVED** [review]
Code 👍

**Review by rstief — APPROVED** [review]
tested on ts6 works as expected.

**Review by milljoniaer — APPROVED** [review]
Code LGTM

**Pull request merged**
