### PR TITLE
`Development`: Modernize appearance of plagiarism similarity distribution and tutor effort statistics 

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

This PR changes the implementation of the plagiarism similarity distribution chart and the tutor effort statistics chart from `ng2-charts`/ `chart.js to ngx-charts`.

### Description

The html templates as well as the underlying logic has been refactored in order to fit the requests of `ngx-charts`.
### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Text exercise that already has been assessed by tutors and with at least one plagiarism case.

**Important**: As always, take a look at the old implementation first. Then compare it to the new one.

1. Log in to Artemis
2. Navigate to Course Administration
3. Enter the exercise overview
4. For the text exercise, click on the exercise title
5. Click on "Check plagiarism"
6. If the plagiarism is not detected yet, run the plagiarism detection and confirm the case(s)
7. Click on "Run details" right above the first case
8. Inspect the displayed chart
9. Return to the exercise detail page and click "Tutor Effort Statistics"
10. Inspect the chart

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Old implementation of Similarity Distribution:
image

New implementation of Similarity Distribution:
image

Old implementation of Tutor Effort Statistics:
image

New implementation of Tutor Effort Statistics:
image

### CODE REVIEW

**Review by Malyuk-A — COMMENTED** [review]
Code looks good to me.
However I think there are some issues when I tested the PR on TS1.
image
image

**Review by Malyuk-A — APPROVED** [review]
Thanks for applying my requested changes so quickly. Y-axis looks fine now 👍
image
image

**Review by filip-gregurevic — APPROVED** [review]
Nice work 🚀

**Review by cremertim — APPROVED** [review]
tested locally with the testing steps, nice work 👍

**Review by dveljacic — APPROVED** [review]
Tested on TS3. Charts look as expected. Screenshots attached. ✅ 

run_details
tutor_statistic

**Pull request merged**
