### PR TITLE
`Communication`: Update posts in the sidebar

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Posts are not refreshed upon receiving a WebSocket message on the lecture and exercise details pages within the communication sidebar.

### Description

The criteria for refreshing posts has been extended to include the sidebar as well.

### Steps for Testing

Prerequisites:
- 2 students
- 1 Course with messaging and communication enabled

1. Write messages as student 1 on the messages page, on the communication page, on a lecture details page, and on an exercise details page.
2. Confirm with both student 1 and student 2, that new messages are visible without reloading the page
3. Disable communication and repeat step 1 and 2 (only messaging enabled)
4. Enable communication and disable messaging and repeat step 1 and 2 (only communication enabled)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

No UI changes

### CODE REVIEW

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM
Manually Tested on TS2

Unrelated issue: reactions throw internal server error

**Review by rstief — APPROVED** [review]
Tested in Testing Session on ts2👍

**Review by basak-akan — APPROVED** [review]
Tested in testing session on TS2

**Review by Kroko-fant — APPROVED** [review]
Tested in a testing session worked as expected.

**Comment by sarpsahinalp** [comment]
Tested in ts3. Everything seems to be working fine. 
image

Potential feature: The use of "@" in messages or communication does not currently notify the user. This would be a valuable addition to the platform.

Potential issue: There is a possibility of students spamming an infinite number of messages. Implementing a time limit /message limit could be a beneficial solution.

**Review by sarpsahinalp — APPROVED** [review]
Tested in ts3. Everything seems to be working fine.

Screenshot from 2023-10-17 18-22-20

Potential feature: The use of "@" in messages or communication does not currently notify the user. This would be a valuable addition to the platform.

Potential issue: There is a possibility of students spamming an infinite number of messages. Implementing a time limit /message limit could be a beneficial solution.

**Pull request merged**
