### PR TITLE
`Development`: Fix an issue with gradle in gitignores of programming exercises

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

#6404 refactored the gitignores and missed that gradle needs one .jar to function properly. This .jar was previously excluded in the gigignores, but was left out in the mentioned Pr.

### Description

Readds the exception for the cradle-wrapper.jar, so Gradle programming exercises work again.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise

1. Log in to Artemis
2. Create a programming exercise using Gradle
3. Check that it is correctly building

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by bassner — DISMISSED** [review]

**Comment by Strohgelaender** [comment]
I think we should also include the gradle-wrapper.properties file since it's included in the templates.

**Comment by bassner** [comment]
Can't we just generally include the gradle directory? Everything inside of it is most likely important to check in, regardless of other ignore rules

**Comment by bassner** [comment]
@Strohgelaender I think it's included already as there's no rule that excludes .properties files. Right?

**Review by julian-christl — APPROVED** [review]
Fix works, tested on TS1. Changes look good.

The properties file gets copied.

**Comment by JohannesStoehr** [comment]
> I think we should also include the gradle-wrapper.properties file since it's included in the templates.

This is correct included in the template and solution, when creating an exercise

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Review by laadvo — APPROVED** [review]
Tested on ts1, gradle programming exercises are building as expected.

**Review by Strohgelaender — APPROVED** [review]
@bassner True, I did not look well enough and thought the `gradle` folder was added to the .gitignore file, but it's `.gradle`. Then everything looks good to me.

**Review by DominikRemo — APPROVED** [review]
Tested on ts1. Building Gradle programming exercises works as expected.

**Pull request merged**
