### PR TITLE
Bugfix/deactivate compass

### PR DESCRIPTION
**Pull request by iozbeyli**
### Motivation and Context
Deactivating compass until hazelcast problem is resolved

### Description
Compass is unusable right now since hazelcast is doing too much data transfer which makes Artemis unusable

The PR also adds audit log entries when users with the editor role change an exercise.

### Steps for Testing
1. Log in to Artemis
2. Create a modeling exercise (Class Diagram or Activity Diagram)
3. It shouldn't be possible to activate compass. Following checkbox shouldn't appear
   - image
4. Login as students
5. Submit similar solutions to modeling exercise with different students
6. Assess the submissions 
7. No suggesstions must be made to similar element

### CODE REVIEW

**Review by imstreetspirit — APPROVED** [review]
tested on ts2. checkbox is not displayed during the creation of the modeling exercise. And there is no auto-assessment available for similar submissions. works as expected.

**Review by lschlesinger — APPROVED** [review]
Also tested on ts2. Checkbox was not there during creation and for both student submission assessment there were no suggestions. Alongside, creation and assessment still worked as expected.

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS2, works as expected, compass seems to be disabled.

**Review by nicolasruscher — APPROVED** [review]
I looked at the code, the changes seem necessary and are okay as long as the issue is not solved 👍

**Pull request merged**
