### PR TITLE
`Development`: Remove unnecessary transactional annotations in delete operations

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).

### Description
Reduce the usage of `@Transactional` which can lead to problems. This should also fix flaky tests related to the K6 tests on Bamboo and improve the general performance for the delete operations

### Testing
1. Create a new course with some exercises, submissions, results
2. Delete results, submissions, exercises and the whole course

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by simon-hng — APPROVED** [review]
Code changes look good

**Review by kekskatze — CHANGES_REQUESTED** [review]
Deleting the whole course didn't work. I got the following errors:
image
Tested on ts2 with the course DeleteCourse and the admin account

**Comment by krusche** [comment]
I fixed the issue and the corresponding server tests, now the deletion should work
@kekskatze could you please test again?

**Review by Yunqing-Wang — CHANGES_REQUESTED** [review]
image
I got this message when trying to delete the course. And the "Confirm delete operation" window doesn't disappear and the course is still there

**Comment by krusche** [comment]
> image
> I got this message when trying to delete the course. And the "Confirm delete operation" window doesn't disappear and the course is still there

From the history on Bamboo, it seems that the correct PR was never deployed to TS1. Can you please test it again and deploy the correct PR to the test server?

**Review by kekskatze — APPROVED** [review]
Tested again with fixed issue. This time everything worked well

**Pull request merged**
