### PR TITLE
[Enhancement] Show capped penalty in feedback view

### PR DESCRIPTION
**Pull request by schultek**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I updated integration tests (Spring) related to the features (with a high test coverage)
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I updated integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

For static code analysis issues, the instructor can specify penalty limits for the exercise as well as for each sca category. It is currently not shown to the students when and how those limits are applied to the score. This might lead to confusion for a student, because solving sca issues might not increase the score when above a penalty limit.

### Description

- Added a property in the sca issue object inside the feedback object to contain the original penalty for the category of the issue.
    - (The credits field already contains the reduced penalty with applied limits)
- In the feedback list, the original penalty is shown now (not affected by limits)
- In the score graph, the 'would-be' deductions without any limits are noted in the legend (only if they are actually different to the applied deductions)
- The legend now displays a tooltip to explain the penalty limits to the students (only if there are any applied limits)

### Steps for Testing

1. Log in to Artemis
2. Create a programming exercise or use an existing one
3. Go to the grading page and configure the sca penalties and especially max-penalties for the categories, such that the limits apply when there are multiple issues in one category (e.g. set both to equal values)
4. Participate as a student and make sure to have multiple sca issues in one category (e.g. introduce several magic number issues)
5. View your feedback and score, check the legend to state the deductions with and without limits and check the tooltip.

### Test Coverage

- result-detail.component.ts 94.81%
- scoreChartPreset.ts 92.73%
- StaticCodeAnalysisService 99%

#### 3 Issues in a category:
Bildschirmfoto 2020-11-24 um 11 35 10

#### The category configuration:
Bildschirmfoto 2020-11-24 um 11 35 17

#### The resulting score graph:
Bildschirmfoto 2020-11-24 um 11 35 27

### CODE REVIEW

**Review by airelawaleria — CHANGES_REQUESTED** [review]
Could not change from Feedback to Graded, could not change the penalty and maxPenalty fields at all. 
image

**Review by simonzilker — CHANGES_REQUESTED** [review]
Tested on ts1 with @airelawaleria  . Created a new Porgramming exercise.  "Penalty" and "Max Penalty" could not be changed. Saving and Reseting is also not possible.  I could have only changed the penalty for exercises with penalty stated before this release.

**Review by JohannesWeiss — COMMENTED** [review]
Experienced the same issues as @simonzilker and @airelawaleria with a new course and an existing one on ts1, could not set the properties.

**Comment by kloessst** [comment]
Depends on https://github.com/ls1intum/Artemis/pull/2456 to make this work.

**Review by JohannesWeiss — CHANGES_REQUESTED** [review]
Setting the properties still does not work for a new course. 
Screenshot 2020-11-24 at 17 16 38

**Comment by JohannesWeiss** [comment]
On an existing course I was not able to successfully update the values, always got this error message: 
Screenshot 2020-11-24 at 17 19 22.
Tested on ts1 with Safari 14.0.

**Comment by kloessst** [comment]
@JohannesWeiss Just tested this, and it works now. With the newest release setting of the categories work.

**Review by airelawaleria — APPROVED** [review]
Tested in the testing session. Worked as intended!

**Review by JohannesWeiss — APPROVED** [review]
Works as intended now, great job!

**Review by fde312 — COMMENTED** [review]
Grading settings:
image


My result for capped penalties:
image
image

So therefore max of 1,5 and total of 5,5

**Review by kloessst — APPROVED** [review]
Worked fine. If a cap applies, the tool tip is available and the legend shows the real sum of penalties.

**Review by fde312 — APPROVED** [review]
Code looks also good! Really good job! 🚀

**Pull request merged**
