### PR TITLE
`Development`: Improve angular control flow

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context
There have been some control flow statements which could be simplified due to the migration to angulars new control flow syntax.

### Description
This PR clears some of that up.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Verify that Server Administration > Audits still work

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

## Summary by CodeRabbit

- **New Features**
    - Enhanced the display of table headers, pagination, and various components across the app based on user permissions and loading states.
    - Improved the visibility and arrangement of user management actions based on activation status.
    - Adjusted the display of text and information in assessment headers, metrics, and various dashboards to better reflect current states or modes (e.g., exam mode).
    - Streamlined the display logic for competency management, learning paths, and course discussions, focusing on loading states and user roles.
    - Refined the conditional rendering for exercise hints, scores, and code hints to improve user interaction and feedback based on the current state.

- **Bug Fixes**
    - Corrected inconsistencies in the display logic across several components, ensuring information is presented accurately based on user roles, loading states, and specific conditions (e.g., exam mode, presence of inconsistencies).
    - Fixed the conditional rendering for buttons and information related to student exams and attendance checks, enhancing the user experience for instructors and students alike.

### CODE REVIEW

**Review by matthiaslehnertum — APPROVED** [review]
Looks good to me! Nice clean up of the control flow!

Depending on the outcome of the discussion around our preferred translation approach I guess you might need to adapt the translations but good for now.

**Review by RY997 — APPROVED** [review]
Code LGTM

**Review by Jan-Thurner — APPROVED** [review]
Code LGTM

**Review by rabeatwork — APPROVED** [review]

**Review by rstief — APPROVED** [review]
Code 💯

**Pull request merged**
