### PR TITLE
`Communication`: Correctly align manage button in communications menu

### PR DESCRIPTION
**Pull request by badkeyy**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
There was a alignment issue with the manage button on the course communication page.
See https://github.com/ls1intum/Artemis/issues/9633

### Description
I changed the button class `d-sm-inline` to `d-sm-block` in order to apply the display: block attribute instead of the display: inline attribute for screen sizes > 576px. This fixes the issue.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course

1. Log in to Artemis
2. Navigate to the Course page of your example course
3. Open up the "Communication" tab
4. Find the "Manage" button to be correctly aligned

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots
image

## Summary by CodeRabbit

- **New Features**
	- Enhanced sidebar functionality with conditional rendering based on course state.
	- Improved visibility and styling of course action buttons based on screen size.
	- Simplified layout for LTI users without the sidebar while maintaining core functionality.

- **Bug Fixes**
	- Adjusted rendering logic for course images and navigation items to ensure proper display.

### CODE REVIEW

**Review by JohannesWt — DISMISSED** [review]
Code

**Review by pzdr7 — APPROVED** [review]
Code

**Review by rabeatwork — APPROVED** [review]

**Review by asliayk — APPROVED** [review]
code

**Review by krusche — CHANGES_REQUESTED** [review]
Thanks for this contribution 👍

**Review by krusche — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
