### PR TITLE
`Development`: Use default value if exercise has no plagiarism checks config

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context
Importing programming exercises from files created before merging of the continuous plagiarism control was not possible, because such files didn't contain plagiarism checks config. This caused the client to load the exercise creation form incorrectly. 

Detected during tests of: #7624

Server part fixed in: #7640

### Description
This PR adds a nullability check for exercise's plagiarism detection config before the exercise form is initialised. If exercise does not contain plagiarism detection config, the component inserts a default value into it.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 zip file with Programming Exercise without plagiarism detection config. You can use this one: [Material-cr1-Sorting_Algorithms_Implementation-52-20231125-105137.zip](https://github.com/ls1intum/Artemis/files/13463640/Material-cr1-Sorting_Algorithms_Implementation-52-20231125-105137.zip)

1. Go to course -> exercises.
2. Start programming exercise from the file provided.
3. Verify that the form displays correctly (including default plagiarism detection config).
4. Import the exercise.
5. Verify that the exercise was imported correctly. 

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| exercise-update-plagiarism-component.ts | 63% (testing just the new method)| ✅              |

### CODE REVIEW

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Comment by Strohgelaender** [comment]
Thanks for fixing this, but I already implemented #7657 with the same fix.

**Review by JanaNF — COMMENTED** [review]
I tried to test this PR on TS2, Legcay_TS1, Legacy_TS2 and Legacy_TS11, and I always only saw the loading screen ("We'll be back soon"). I don't know what problems Artemis has right now but I had the same issue with other PRs too. 

I will try to test this PR again tomorrow.

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts2. Worked as expected

**Review by JanaNF — APPROVED** [review]
Manual tested on ts2. Worked as expected.

**Comment by jakubriegel** [comment]
> Thanks for fixing this, but I already implemented #7657 with the same fix.

This is continuation of work started in #7640

**Review by Strohgelaender — APPROVED** [review]
code lgtm, let's merge that quickly.

**Pull request merged**
