### PR TITLE
`Communication`: Fix an issue where the client does not keep track of the posts on screen

### PR DESCRIPTION
**Pull request by PaRangger**
#### General

- [x] I tested all changes and their related features with all corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

Addresses #8985 

The issue was that the _totalNumberOfPosts_ observable in the metis service did not match the posts visible on screen. This led to unintended behaviour in the client in an empty conversation. The icon showing that the conversation was empty did not dissapear when a new message was created, and did not appear when the last remaining message was deleted.

### Description
Instead of listening to the _totalNumberOfPosts_ variable, in the case of the envelope, I changed it to listen to the .length of the _posts_ variable. The _posts_ variable is the cached posts that are actually visible on screen.

Additionally, I checked all occurences of the _totalNumberOfPosts_ observable in the rest of the code for similar issues. The only other occurence is in a thread or while searching, when comparing it for paging, which I did not see any issue with.

Lastly, i fixed a tiny typo in the metis service. I changed the naming of the local variable _cachedTotalNumberOfPots_ -> _cachedTotalNumberOfPosts_.

### Steps for Testing

Prerequisites:
- 1 Course with communication enabled
- 2 Users

With both users:
1. Log in to Artemis
2. Go to a course with communication enabled
3. Go to the "Communication" tab
4. Go to a conversation without any messages
5. Write the first message with one user
6. Check on the current user if the envelope dissapears (same should apply for the other user that had the conversation open)
7. Delete the message
8. Check if the envelope appears

The same flow should also work for the course wide search form.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved accuracy of search results display by updating conditions based on the length of the `posts` array.

- **Refactor**
  - Renamed variable for clarity and consistency within the post handling logic.

These changes enhance the reliability and clarity of search result displays and internal logic.

### CODE REVIEW

**Comment by PaRangger** [comment]
In addition to the changes stated above, I implemented the feedback of coderabbitai in cases where it seemed reasonable.

These cases include:
- A null check when parsing the response header for the _cachedTotalNumberOfPosts_ variable.
- A change of a non-null assertion to a safer optional chaining when calling splice on the answers of a post in the delete method.

**Review by egekurt123 — APPROVED** [review]
Code LGTM, and works as expected on TS3

**Review by asliayk — APPROVED** [review]
tested locally and works as expected

**Review by EneaGore — APPROVED** [review]
Tested on TS2. Works as expected and Code lgtm too.

**Review by JohannesStoehr — APPROVED** [review]
Code

**Pull request merged**
