### PR TITLE
[DOCS] Client Testing Guidelines

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Motivation and Context

We have not yet written down any guidelines for client testing. The goal of this PR is to change this.

### Description

Added a client testing section to the client guidelines

### CODE REVIEW

**Review by FrankeLukas — APPROVED** [review]
Looks like a great starting point for writing tests to me (good job ^^). We could add some more examples later on.

**Review by schultek — COMMENTED** [review]
_An additional section about services and http requests:_

Services, that provide access methods to the servers http api, should not be tested separately, but as part of the component that uses the service. Do not mock the service methods, but do mock the http requests and responses from the api. 

The component test can be extended like this:

  .. code:: ts

    ...
    import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';

    describe('SomeComponent', () => {

      ...

      beforeEach(() => {
          TestBed.configureTestingModule({
              imports: [HttpClientTestingModule],
          });

          ...
          httpMock = injector.get(HttpTestingController);
      });

      afterEach(() => {
          ...
          httpMock.verify();
      });
    
      it('should make get request', async () => {
          const returnedFromApi = {some: 'data'};
        
          component.callServiceMethod()
              .subscribe((data) => expect(data).toMatchObject({body: returnedFromApi}));
        
          const req = httpMock.expectOne({ method: 'GET' });
          req.flush(JSON.stringify(returnedFromApi));
      });

    });

**Review by JohannesWeiss — DISMISSED** [review]
Good documentation as a suitable starting point for testing, clearly written and good to understand.

**Comment by stefanwaldhauser** [comment]
> _An additional section about services and http requests:_
> 
> Services, that provide access methods to the servers http api, should not be tested separately, but as part of the component that uses the service. Do not mock the service methods, but do mock the http requests and responses from the api.
> 
> The component test can be extended like this:
> 
> .. code:: ts
> 
> ```
> ...
> import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
> 
> describe('SomeComponent', () => {
> 
>   ...
> 
>   beforeEach(() => {
>       TestBed.configureTestingModule({
>           imports: [HttpClientTestingModule],
>       });
> 
>       ...
>       httpMock = injector.get(HttpTestingController);
>   });
> 
>   afterEach(() => {
>       ...
>       httpMock.verify();
>   });
> 
>   it('should make get request', async () => {
>       const returnedFromApi = {some: 'data'};
>     
>       component.callServiceMethod()
>           .subscribe((data) => expect(data).toMatchObject({body: returnedFromApi}));
>     
>       const req = httpMock.expectOne({ method: 'GET' });
>       req.flush(JSON.stringify(returnedFromApi));
>   });
> 
> });
> ```

What is the benefit of this approach? Would this not mean that I need the service as a dependency in my component?And if this service than has some dependencies I need those too and so on. I see only one benefit (one less test for the services) and the huge downside that there is a high coupling between the component test and the real service class

**Comment by stefanwaldhauser** [comment]
> });

af86c1f65db59b55462a5e06cb8d0f9f7c67d1ab : I have added a section about this approach as discussed in the meeting. @schultek could you maybe write in the docs some simple test setup for a component with a service and how to mock the http requests here?

**Comment by schultek** [comment]
Whats wrong with the example above?

**Review by krusche — APPROVED** [review]

**Comment by krusche** [comment]
I'll merge this for now. We can still improve it in the future, but this is already a very valuable contribution! Thanks a lot @stefanwaldhauser

**Pull request merged**
