### PR TITLE
`Programming exercises`: Fix an issue with PlantUML diagrams if test names contain parentheses

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
This fixes an issue I encountered while working on #7015. Since moving and changing regular expressions at the same time makes reviewing quite hard. I decided to move this bugfix into its own small PR.

### Description
For Gradle exercises, test case names contain parentheses (e.g. `testBubbleSort()` instead of `testBubbleSort` for Maven exercises).

However, PlantUML diagrams until now did not allow the use of such parenthesis inside the test name. The whole diagram broke when trying to do so. This PR adapts the Regex to allow this and fixes the default gradle template.

### Steps for Testing

1. Create a new gradle programming exercise (to use the updated problem statement)
2. Verify that the UML diagram contains tests with parenthesis. Verify that these are correctly detected and that the correct color is shown.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage
test case added, previously not tested.

### Screenshots
old (default template, wrong names):
grafik

old with parentheses:
grafik

new:

grafik

### CODE REVIEW

**Review by laadvo — APPROVED** [review]
Tested on ts1, test names containing parantheses are now recognized as expected. The corresponding part of the UML diagram is colored correctly
image

**Review by JohannesStoehr — APPROVED** [review]
Approve code changes

**Review by tobias-lippert — APPROVED** [review]
Tested in testing sesison. Issue is fixed.

**Review by DominikRemo — APPROVED** [review]
Tested in testing session on ts1. LGTM

**Review by reschandreas — APPROVED** [review]
Tested locally and LGTM 👍🏻 (approving just because it helped me resolve some issues with my local setup)

**Review by bassner — APPROVED** [review]

**Pull request merged**
