### PR TITLE
`Lectures`: Fix overlay on attachment edit page for Safari

### LINKED ISSUE #6195: `Edit Attachment`: Overlay blocks screen
### Describe the bug

When editing an attachment, the dialog doesn't open and instead the whole screen is blocked by an overlay whichI cannot get rid of.

### To Reproduce

1. Go to attachments
2. Create one
3. Now click edit for that attachment

### Expected behavior

The overlay should not cover the entire screen and the edit form should appear.

### Screenshots

Lectures_Attachments_Edit

### Which version of Artemis are you seeing the problem on?

6.0.2

### What browsers are you seeing the problem on?

Safari

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by DominikRemo**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
fixes #6195
When editing an attachment, the whole screen was blocked by an overlay. This behaviour was encountered on Safari, but not on Chrome and Firefox

### Description
This pull request addresses an issue related to the behavior of the ```position: relative``` CSS property when applied to a table row (```tr```) in HTML5/CSS3 specifications. Currently, Safari ignores the position attribute on table rows, while Chrome and Firefox do not. As the behavior is not specified, this inconsistency is not considered a browser bug, but rather a misuse of the position attribute on a table row to restrict the size of our overlay.

The bug was fixed by removing the reliance on ```position: relative``` for the overlay. As a result, the text can now be horizontally centered, but vertical centering is not supported. Despite this limitation, the overlay is displayed exclusively above the corresponding table row, and the elements within the table row remain disabled.

These changes ensure consistent behavior across different browsers while maintaining the intended functionality of the overlay.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Lecture
- Test at least on Safari, preferably on Safari, Firefox and Chrome

1. Navigate to a Lecture (Course Management)
2. Create an attachment
3. Click edit for that attachment and verify that the overlay is displayed correctly

#### Code Review
- [x] Code Review 1
#### Manual Tests
- [x] Test 1

#### Before
Taken from #6195
Lectures_Attachments_Edit

#### After
Bildschirmfoto 2023-07-05 um 14 21 39

### CODE REVIEW

**Review by SolizerCodes — APPROVED** [review]
Tested on ts5. Could not reproduce the bug on Safari. Chrome and Firefox work as expected

**Review by pellumbbaboci — APPROVED** [review]
Tested on ts1, works as expected in Safari and Chrome

**Review by nityanandaz — APPROVED** [review]
I confirm that Safari only overlays the expected table row now (ts1)

**Review by sleiss — APPROVED** [review]
Works on Firefox and Chromium.

**Review by basak-akan — APPROVED** [review]
Works as expected on Safari, Edge and Opera.

**Review by MaximilianAnzinger — APPROVED** [review]
Firefox, Chrome & Safari 👍 Code LGTM

**Pull request merged**
