### PR TITLE
`Lectures`: Correctly put and get competencies for attachment units

### PR DESCRIPTION
**Pull request by badkeyy**
#### General

- [x] This is a small issue that I tested locally.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Fixes this issue: https://github.com/ls1intum/Artemis/issues/9666 

### Description

- Added the competencyLinks field to `attachment-units` GET-Request
- Added the competencyLinks field to `attachment-units` PUT-Request (Updates the attachment unit)

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Demo Course with at least one lecture and competency

1. Log in to Artemis
2. Navigate to the demo lecture’s units
3. Create a new attachment unit
4. Try to edit the created attachment unit, add the test competency and press "Submit"
5. After pressing edit again find the added competency in the attachment unit

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

video

## Summary by CodeRabbit

- **New Features**
	- Enhanced functionality for updating attachment units, including competency link updates and improved file handling.
	- Retrieval of attachment units now includes associated slides and competencies for better data visibility.

- **Bug Fixes**
	- Improved error handling to ensure attachments are present during updates and to validate file types.

- **Documentation**
	- Updated method signatures to reflect changes in functionality and parameters.

### CODE REVIEW

**Comment by Strohgelaender** [comment]
Welcome to Artemis 👋 
Thanks for the PR, the changes look good. 

Can you also add some server tests to check for this behaviour?

**Comment by JohannesStoehr** [comment]
Thank you for your help with fixing the issue. Since we want to fix the bug quickly, I adapted the tests in a new PR and incorporated your changes in this PR: #9739 Feel free to assign yourself as well in this PR.

As our readme states (https://github.com/ls1intum/Artemis#communication), we also use Slack for communication. If you want to contribute more in the future, feel free to sign up so we can better communicate and easier collaborate on PRs in the future.

**Comment by badkeyy** [comment]
Closed in favor of https://github.com/ls1intum/Artemis/pull/9739

**Comment by badkeyy** [comment]
Closed in favor of https://github.com/ls1intum/Artemis/pull/9739

**Pull request closed without merging**
