### PR TITLE
`Assessment`: Provide a list with all course complaints to tutors

### PR DESCRIPTION
**Pull request by mallgaier**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
A list with all complaints of a course is currently only accessible for instructors. However, some TAs might be responsible for handling complaints and more feedback requests. These TAs currently must check every individual exercise for open complaints and have no overview of all open / closed complaints

### Description
The `list-of-complaints` received a new button, which loads for TAs and Editors all Complaints from the server if necessary. _(Since the complete list can be very long under certain circumstances, lazy loading was chosen here. If the tutor opens the list, only his own Complaints are shown to him.)_
The server-side `ComplaintRessource` and the REST-URL was added with the Boolean-parameter `allComplaintsForTutor`, which loads all complaints from the database if true. Before sending the complaints to the client, the `assessor` is removed from every complaint except for the complaint the requesting tutor received.
A alert-info was added to inform the tutor, that only his complaints / requests are loaded as default and that all complaints can be lazy-loaded into the client.

### Steps for Testing
- 1 Instructor
- 1 Tutor
- 1 Exercise with a submitted complaint/ request, which was assessed by the tutor
- 1 Exercise with a submitted complaint / request, which was assessed by **another** tutor
- 1 Exercise with an addressed complaint / request, which was assessed by either of the two tutors (or a third tutor)

**With the tutor / editor account**
1. Log in to Artemis
2. Navigate to Course Administration -> Select Course -> Total Complaints
3. Click on the Button `Load all Complaints` and check, if complaints from other assessors are loaded and the assessor is not shown. Check if the button is disabled after clicking
4. Check if the alert-info correctly changes after loading the complaints
5. Repeat the same for the More Feedback Requests

**With the instructor account**
1. Log in to Artemis
2. Navigate to Course Administration -> Select Course -> Total Complaints
3. Make sure, that the whole alert-info is not shown. _(For instructors, the whole list of complaints is loaded by default)_
6. Check if the information regarding the assessor is shown for every complaint

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots
https://user-images.githubusercontent.com/94070506/165748859-ddcc8f1b-50c6-44de-ac12-d4635dbb40b1.mp4

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Looked through the code and tested on TS1.
All worked as described.

Two ideas:
- Instead of a button "show addressed complaints" I'd expect a checkbox as in other places where things are filtered
- Why did you choose a button for lazy loading instead of doing it similar to the participation or scores page where a set number of rows are loaded?

**Comment by mallgaier** [comment]
Thanks for the review
> * Instead of a button "show addressed complaints" I'd expect a checkbox as in other places where things are filtered
A button was chosen to align the styling with the new button. But i can also undo this change.
> * Why did you choose a button for lazy loading instead of doing it similar to the participation or scores page where a set number of rows are loaded?
This was originally intended as a small enhancement and not as a complete overhaul of the complaint-list. The average tutor is only interested in his own complaints / requests, so he doesn't necessarily need all complaints (which take quite a time to be loaded into the client, if there are around 800 complaints). But as some tutors might be responsible to answer open complaints, the list of all complaints might be useful. That's why I decided to use lazy-loading here.

**Comment by mallgaier** [comment]
Thanks for the review @JohannesStoehr 

> Instead of a button "show addressed complaints" I'd expect a checkbox as in other places where things are filtered

I have undone the changes and the checkbox is again showed

> Why did you choose a button for lazy loading instead of doing it similar to the participation or scores page where a set number of rows are loaded?

This was originally intended as a small enhancement and not as a complete overhaul of the complaint-list. The average tutor is only interested in his own complaints / requests, so he doesn't necessarily need all complaints (which take quite a time to be loaded into the client, if there are around 800 complaints). But as some tutors might be responsible to answer open complaints, the list of all complaints might be useful. That's why I decided to use lazy-loading here.

**Review by max-bergmann — APPROVED** [review]
Tested on TS3. Works as expected

**Review by max-bergmann — APPROVED** [review]
Re-approve after merge

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Thanks for the change with the checkbox. One more minor thing I noticed, when loading all complaints the state of the checkbox is not considered:
https://user-images.githubusercontent.com/38322605/165933842-555ed3be-e057-4069-832a-31e0c4452223.mov

**Review by JohannesStoehr — APPROVED** [review]
Tested on TS1, all works now. Thanks for the fixes

**Review by max-bergmann — APPROVED** [review]
Tested on TS3 again - for me everything worked as expected

**Pull request merged**
