### PR TITLE
`Development`: Order and optimize imports in client files

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.

### Motivation and Context
Small code quality PR to merge cases where imports from the same module were spread among multiple lines. It also reorders some imports in alphabetical order.

### Description
I just applied the IntelliJ inspection.

### Steps for Testing
Code Review

#### Code Review
- [ ] Review 1
- [ ] Review 2

### CODE REVIEW

**Review by manuelmanso — APPROVED** [review]

**Review by JohannesStoehr — APPROVED** [review]
Refactoring looks good. Is it possible to add this refactoring to e.g. always run when trying to push or something like that?

**Review by simon-hng — APPROVED** [review]
Nice little tweak to improve code quality!

**Review by Santia-go — DISMISSED** [review]
The changes in all these files look good and follow an alphabetic order.

**Review by JohannesStoehr — APPROVED** [review]
Thanks for adding the rule. Looks good to me 👍

**Review by ge65cer — DISMISSED** [review]

**Pull request merged**
