### PR TITLE
`Assessment`: Escape special characters in inline feedback

### LINKED ISSUE #6965: ```Assessment```: < and > incorrectly interpreted in tutor comments
### Describe the bug

When using the `<` and `>` symbols in the tutor feedback comments, they aren't shown properly. Only using < with nothing coming after it, or using <> with nothing in between is displayed correctly. However, when there is text after the opening bracket <, that whole piece of text (including the bracket) is gone, until there is a closing bracket >, which is also not displayed after saving the comment.

Possible explanation:
The brackets might be interpreted as html tags.

### To Reproduce

1. Create a programming exercise with manual feedback enabled.
2. Create an assignment for this exercise and wait till the submission deadline has passed.
3. Create a tutor comment and test out the cases outlined above.
4. After saving, you should be able to see the error (i.e. not see some of the text).

### Expected behavior

Expected behavior would be WYSIWYG, so entering a < or > in any combination should display exactly that after saving.

### Screenshots

Error can be observed in the middle comment.
Bildschirmfoto 2023-07-23 um 17 19 29
Bildschirmfoto 2023-07-23 um 17 19 37

### Which version of Artemis are you seeing the problem on?

6.3.5

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
The inline feedback in the programming exercise assessment renderer sanitized the feedback text from HTML alike tags (e.g. "&lt;something >") because it misinterpreted it as HTML tag. It should be possible to use and display comments including special characters. This resolves #6965 

### Description
This PR uses an already existing escaping function to replace special characters with their unicode representation. (This could lead to weird displaying if the string is inserted in HTML as actual string, but this would already be an issue because of the replacement of line separators with "<br>")

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Programming Exercise with manual assessment enabled

1. Log in to Artemis
2. Navigate to Exercise assessment
3. write inline feedback including some special character combinations (especially also HTML tags, e.g. &lt;div>hello&lt;/div>)
4. verify that they are displayed correctly (just like you wrote it) in the assessment and student view

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
image

image

### CODE REVIEW

**Review by DominikRemo — COMMENTED** [review]
Code LGTM, but maybe you could add some tests (or modify existing ones?) to verify that special characters are correctly escaped

**Review by laadvo — DISMISSED** [review]
Tested on ts1, special characters get escaped and can be seen in the feedback as expected

**Review by MaximilianAnzinger — DISMISSED** [review]
Code LGTM. I have to agree with @DominikRemo. At least one test to ensure this minor change doesn't accidentally get deleted in the future would be useful.

**Review by basak-akan — APPROVED** [review]
Tested on ts3, special characters are escaped and visible in the inline feedback as intended

**Review by laadvo — APPROVED** [review]
reapprove test after client tests added

**Review by Strohgelaender — APPROVED** [review]
lgtm

**Review by DominikRemo — APPROVED** [review]
Thank you for adding a test :)

**Review by basak-akan — APPROVED** [review]
Reapprove

**Review by b-fein — APPROVED** [review]
Thanks! Code looks good.

**Pull request merged**
