### PR TITLE
`Communication`: Remove context duplication while editing answers

### PR DESCRIPTION
**Pull request by canberkanar**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
While editing replies, the context is shown twice; both in the answer's body and the markdown input. This causes information redundancy.

### Description
- We hide the answer body when the markdown is displayed while editing answers.
- A small bugfix is introduced that prevents the posting edit/delete icons found in the header from moving when the posting creation date tooltip is displayed.

### Steps for Testing

Prerequisites:
- 1 Student
-  1 Course with communication enabled

1. Log in to Artemis
2. Navigate to the Course communication page
3. Edit an answer
4. Make sure that the answer body is not displayed while editing the answer
5. Make sure that the answer body is displayed after editing is completed or canceled.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
Not changed

### Old
image

### New
image

### CODE REVIEW

**Review by akesfeden — APPROVED** [review]
Tested on TS5, answer is shown and hidden as described when editing. Code changes also LGTM.

**Review by ge65cer — APPROVED** [review]
Tested on TS2 without issues.

**Review by minrows — APPROVED** [review]
Tested on TS1. Works as described. 👍

**Review by bassner — APPROVED** [review]
Tested on TS5 - works! Code LGTM!

**Pull request merged**
