### PR TITLE
`Development`: Fix inconsistent field name in conversation API

### PR DESCRIPTION
**Pull request by pellumbbaboci**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.

### Motivation and Context

This bug was noticed by @TimOrtel  on production. In `ConversationWebsocketDTO` class `metisCrudAction` field was changed from `crudAction` to `metisCrudAction` in server but not in client side and therefore this caused to not receive the updated conversation through websocket. 

### Description

Renamed the field to `metisCrudAction` on client side.

### Steps for Testing

Prerequisites:
- 2 Users registered at the same course
- 1 Course

1. Log in to Artemis
2. Navigate to messages tab and start chat with 2 users
3. Create new conversation (one-to-one or group chat or channels) and verify that its displayed on the other user (without reloading)
4. Send new message and verify that the unread count badge is displayed on the other user side (in order for badge to be shown the conversation should not be active so do not click the conversation)
5. Navigate to course overview from one of the users and send message from the other user. On **Messages** tab a red circle should be displayed

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code looks good and is now consistant with the server.

**Review by JohannesStoehr — APPROVED** [review]
Renaming looks good to me

**Review by YeetTheFirst21 — APPROVED** [review]
Tested on TS1, works as expected

Screenshot 2023-05-01 011048
Screenshot 2023-05-01 011050

**Review by terlan98 — APPROVED** [review]
Tested on TS1. Works as expected 👍

**Pull request merged**
