### PR TITLE
`General`: Improve email validation when communication with external user management systems

### PR DESCRIPTION
**Pull request by manuelmanso**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Artemis is treating emails as case-sensitive when looking for existing emails in Jira in the context of an LTI launch. Although emails can be case-sensitive, they are pretty much always treated as case-insensitive [(see here)](https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive).

### Description
Use `str.equalsIgnoreCase()` when matching emails in Jira to the launch request email.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 student
- access to https://moodle.ase.in.tum.de/

1. Log in to Artemis as the instructor
2. Create an online course with an exercise
3. Configure an LTI launch for the exercise in moodle
4. Create a user in moodle with the same email as an existing user in Artemis but with a different case
5. Launch the exercise as the user
6. Verify that you were matched with the existing user in Artemis

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage
| Class/File | Branch | Line |
|------------|-------:|-----:|
| JiraAuthenticationProvider.java | 64% | 38% |

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Code changes look good to me

**Review by b-fein — APPROVED** [review]
Code changes look good. :+1: 

This won’t fix the issue we talked about yesterday, though, as we don’t use Jira, but the internal user management.

**Review by b-fein — APPROVED** [review]
The previous comment has been resolved via Slack. Therefore: Code looks good. :+1:

**Review by simon-hng — APPROVED** [review]
code good

**Review by maximiliansoelch — APPROVED** [review]

**Pull request merged**
