### PR TITLE
`Text Exercises`: Link TextBlock to Feedback with feedback_id column

### PR DESCRIPTION
**Pull request by argertboja**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

In order to suggest an automatic feedback from existing text blocks of old assessments, we need to keep a reference of the feedback id to the text block. This id will help us to suggest a feedback for all text blocks which belong to the same cluster as the existing ones.

### Description

Whenever we need to save the text blocks on the database, we need to set the Feedback based on the Feedback which has the reference equal to the corresponding Text Block. There is a foreign key `ON DELETE SET NULL` which prevents keeping a reference to a deleted text block. If the text blocks already exist on the repository, we only update the feedback_id value to the new created Feedback element!

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 or more Text Exercises

1. Log in to Artemis
2. Navigate to Course Administration
3. Create and Import Text and Modeling exercises
4. Participate in the above-created exercises
5. Assess exercises
6. Delete Result
7. Submit a new submission
8. Assess the new submission
9. Check if any errors occur during different scenarios
10. If possible check if `feedback_id` value is set correctly on the database

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by Olimbia23 — COMMENTED** [review]
Nice work @argertboja
Code changes look good.

I left one minor comment, but I am also curious why there are 2k line changes in `package-lock` file, as no new dependencies are introduced, nor existing are changed. Is it an accidental change?

**Comment by argertboja** [comment]
> Nice work @argertboja Code changes look good.
> 
> I left one minor comment, but I am also curious why there are 2k line changes in `package-lock` file, as no new dependencies are introduced, nor existing are changed. Is it an accidental change?

Thank you for your feedback @Olimbia23 😃 I applied your suggestion!

Regarding the package-lock.json I think it was some Windows problem as I didn't introduce any change on this file. I reverted it to the original version though using `git checkout`. Let me know what you think 🙂

**Review by MerlinMehmed — APPROVED** [review]
Followed the testing steps on TS1 and didn't encounter issues. Approve!

**Review by Malyuk-A — APPROVED** [review]
Thank you for fixing the found bug. Code looks good and I tested the PR on TS1. Now I could no longer find any issues. Good job.

**Review by Olimbia23 — APPROVED** [review]
Thank you for incorporating my suggestions.
It looks much better without `package-lock.json`
Approve 👍

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
