### PR TITLE
Bugfix: Fix 'Assessments locked by you' - Views

### PR DESCRIPTION
**Pull request by nicolasruscher**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context

Currently, when going to a Dashboard -> 'Assessments locked by you' you are not able to access the assessments, because the view is not loaded correctly. 

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration -> a Dashboard -> 'Assessments locked by you'
3. Check if you can open your locked assessments

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]
Tested before and after, the bugfix fixes the issue.

**Review by airelawaleria — APPROVED** [review]
Everything works

**Review by marvinchimeka — APPROVED** [review]
Works as intended.

**Review by EneaGore — APPROVED** [review]
Worked on ts1

**Review by simonzilker — APPROVED** [review]
works perfectly on ts1

**Review by JohannesWeiss — APPROVED** [review]
Works on ts1!

**Review by krusche — APPROVED** [review]

**Pull request merged**
