### PR TITLE
`Exam mode`: Improve display of modeling exercises on exam summary pdf

### PR DESCRIPTION
**Pull request by az108**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

This PR solves most of an exam mode issue which was found below.
https://github.com/ls1intum/Artemis/issues/8930
The whitespace issue which exists is still there and known and will be tried to fix in the future as it only affects very extreme modelling diagram cases.

### Description

I have adjusted the height of the modelling sumbission which is the inner box next to the assesement instructions. Additionally I have adjusted the height of the sumbission container which is the outer box so that it has the size of the content inside.
One problem which can occur in extreme large diagrams. If a student expands appolon too far, then an empty whitespace appears as shown in the screenshots below which pushes the content out of the box. The surrounding boxes still have the proper size. This is an issue which will be tried to fix in a follow up PR but I wanted to include the example here as you can see that the heights are proper now.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student

1. Solve an exam with modelling exercises and other kind of exercises 
2. Download the summary 
3. Verify the questions of the modeling exercises are fitting in the corresponding box now.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

General layout now:
image

Extreme case but changes more visible:
1.
image
2.
image
3.
image

## Summary by CodeRabbit

- **New Features**
  - Improved print media styling for the `modeling-assessment` component to fit the print area better.
  - Enhanced print-specific styling for the `modeling-submission` component to ensure proper height adjustment and page break handling during printing.

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Tested on ts4, worked 👍 
Code looks also clean to me

**Review by edkaya — COMMENTED** [review]
When the diagram is vertically too big (which is realistically very an edge case imo), some of the boxes still stay behind of the problem statement / cut off when arriving the border of the page. Is this intended? 

Screenshot 2024-07-12 at 18 42 28
Screenshot 2024-07-12 at 18 42 42

**Review by pzdr7 — APPROVED** [review]
Code

**Review by Jan-Thurner — APPROVED** [review]
code lgtm

**Review by edkaya — APPROVED** [review]
Tested on ts4, works as described. Code also lgtm

**Pull request merged**
