### PR TITLE
`General`: Improve responsive layout

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

There were some issues with the responsive layout. For example, there was a large whitespace left and right present on mobile devices.

### Description

This PR generally enhances the responsive layout in multiple sites and components.
It also fixes the issue that exercise stats (doughnut charts) were not displayed when no release date for the exercise was set.

### Steps for Testing

Prerequisites:
- 1 Instructor or Student

1. Log in to Artemis
2. Enable mobile emulation in your browser's development tools
3. Navigate to changed client components (browse around Artemis for other issues as well if you'd like)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Examples of issues that were reported and fixed.

<details>
  <summary>Screenshot 1</summary>

</details>

<details>
  <summary>Screenshot 2</summary>
  

</details>

<details>
  <summary>Screenshot 3</summary>
  

</details>

### CODE REVIEW

**Review by Hialus — APPROVED** [review]
In that case, I can approve this PR 👍🏻 
Code changes also look reasonable.

Please keep in mind that there are quite a few checks failing. These are most likely flaky tests, but you might consider rerunning them to be sure

**Review by nairaarnez — APPROVED** [review]
Tested in TS3, it looks very good! I also participated with a modeling and text exercise, very nice!

**Review by alaraozdenler — APPROVED** [review]
Tested on TS2, looks good

**Review by max-bergmann — APPROVED** [review]
Tested on TS3. Works as expected

**Review by jschmautzer — APPROVED** [review]
tested on ts3, the 3 cases described in the screenshots worked as expected

**Review by minrows — APPROVED** [review]
Tested on TS3, LGTM! 👍

**Pull request merged**
