### PR TITLE
`General`: Fix responsiveness in user list view

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

There are some responsiveness issues in the header of a course user list view:
grafik

### Description

Fixed those issues by replacing some weird float styles with proper flexboxing

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to a Course Page
3. Scroll down, click the name of the student group (or instructors, tutors ...)
4. In the list view, resize your viewport horizontally like in the video and make sure that everything looks good and is responsive

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

ezgif-3-15bbb95a5b

### CODE REVIEW

**Review by Hialus — DISMISSED** [review]
Code changes look good.
Tested it on TS1 on my iPhone 12 Mini and I think the responsiveness could be improved even further:
IMG_DDD0E5FA948E-1
As you can see in the screenshot (and also at the end of your screencast) the search text field is pretty small on small screens. I have two ideas how you could improve this:
1. Put the search bar in a new line on small screens
2. Reduce the size of the dropdown on small screens, e.g. to "50 u/p" or similar. The content of the dropdown could stay the same.

But this isn't super necessary, as it only really affects very small screens, so consider it an optional suggestion.

**Review by ge65cer — APPROVED** [review]
I agree with @Hialus 🙂 I'd also be okay with simply moving the input field to its own line in smaller screens (Boostrap's `col-sm-x` classes should make this easily possible).

**Review by jschmautzer — COMMENTED** [review]
tested on ts3, works as described

I only noticed one weird thing (look at the yellow markings):
responsive_1
responsive_2
responsive_3
For the width 551 the wrap is again there. (like screenshot 2)

**Comment by bassner** [comment]
@jschmautzer That's not too weird, the reason is that on smaller screen widths the borders around the content vanish to use the space more effectively (looks at the left and right borders of the screen)

**Comment by bassner** [comment]
@ge65cer @Hialus I pushed a suggestion in 71eb849

https://user-images.githubusercontent.com/23171488/182680130-e5a3ee90-1a9a-4681-856f-71a4365b745b.mov

**Review by TheZoker — APPROVED** [review]
Tested on TS3 with the latest commit and works as expected 👍

**Review by ge65cer — APPROVED** [review]
Thanks for the additional fix!

**Pull request merged**
