### PR TITLE
Fix issues with example submissions for exercises with categories

### LINKED ISSUE #3300: Adding an example solution to modelling excercises
### Describe the bug

Adding an example solution to modelling excercises does not work when a category is set.  This also occurs on production

#### To Reproduce

1. Go to 'Course Managment'
2. Click on Excercises
3. Scroll down to Modeling excercises
4. Create a modeling excercise with a category and safe it
5. Try to create an example submission
6. See error
7. Remove the category and save
8. Try to create an example submission
9. Everything should work

#### Expected behavior

You should be able to create example submissions when a category is sett

#### Screenshots

Reproduction of the error on the live server
https://user-images.githubusercontent.com/65229601/116119236-7f058f80-a6be-11eb-8c83-5355cfcdf73f.mp4

### Environment

<details><pre>
 - OS: Windows
 - Browser Chrome
 - Version 90.0.4430.85
</pre></details>

#### Additional context

We had a kind of similar issue when importing of text excercises did not work. https://github.com/ls1intum/Artemis/issues/3261

#### Output in Web Console

<details><pre>
  [Bad request error]
</pre></details>

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context

Closes #3300.

### Description

The modeling submission was sending an exercise alongside itself to the server, but didn't convert that exercise to a format the server expects. (Which is what we do now to fix the "Bad Request" errors.)

### Steps for Testing

1. Create or find a modeling exercise with categories
2. Create, update and delete example submissions
3. Also check if example solutions and example assessments for the example submissions still work

### CODE REVIEW

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 2. Everything worked as expected.

**Review by imstreetspirit — APPROVED** [review]
tested on ts3. created/updated/deleted modeling exercise with categories.
able to add example submission/solution for this exercise. works as expected.

**Review by KiraNickel — APPROVED** [review]
Tested on ts2. Everything works 👍🏼

**Review by DanielKainz — APPROVED** [review]
Tested on TS3 and everything works as intended :-)

**Comment by lschlesinger** [comment]
modelingmov

Is it intended behaviour that after changing and saving, you end up being in the editing mode of the UML model again? I took a screencast to demonstrate. I tested it on TS2.

**Comment by FrankeLukas** [comment]
> Is it intended behaviour that after changing and saving, you end up being in the editing mode of the UML model again? I took a screencast to demonstrate. I tested it on TS2.

No, this was noticed by @imstreetspirit too, but is not related to this PR.

**Review by lschlesinger — APPROVED** [review]
Fixed the described problem!

**Review by canyelten — APPROVED** [review]
Tested on TS2. Works as expected.

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Worked for me.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Works as expected

**Pull request merged**
