### PR TITLE
`General`: Use configured archives path as base of temporary directories in exam export

### PR DESCRIPTION
**Pull request by dfuchss**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).

### Motivation and Context

[This line](https://github.com/ls1intum/Artemis/blob/4f389387c6f71227ed2692325360f446c9b595f4/src/main/java/de/tum/in/www1/artemis/service/CourseExamExportService.java#L85) causes issues if the directory of the Artemis.war is not writable by the artemis user (thats the case for our system).

### Description

 I replaced the path by a unique path within the configured archive path `artemis.course-archives-path`

### Steps for Testing

Prerequisites:
- Admin Access to the Artemis machine

1. Deny the creation of directories in the directory of the Artemis.war
2. Configure the export path to another location (artemis user shall have access to this path)
3. Create an exam
4. Try to archive the course
5. There shall be no error now.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Comment by Strohgelaender** [comment]
I tested this PR locally, the configured path gets used as expected for the temporary folder. But I have two smaller comments:
- The newly created directory `_temp-exports_` never gets deleted. Is this the expected behavior? Before the change, everything related to the ongoing export was removed, including all temporary directories.
- The parameter `outputDir` already contains the archive path, this could be used directly instead of using a new attribute.

**Comment by dfuchss** [comment]
> I tested this PR locally, the configured path gets used as expected for the temporary folder. But I have two smaller comments:

Thanks a lot for the testing :)

> * The newly created directory `_temp-exports_` never gets deleted. Is this the expected behavior? Before the change, everything related to the ongoing export was removed, including all temporary directories.

Yes, that's expected. I think that should be no problem, since the `_temp-exports_` directory should be empty in the end. I know that behavior from other tools as well. In addition, you would have to think about when to delete the directory (imagine two instructors archive their course at the same time)

> * The parameter `outputDir` already contains the archive path, this could be used directly instead of using a new attribute.

I think that the temporary directory shall not rely on the output directory directly. This would introduce an implicit dependency. Furthermore, I think the code for the explicit directory is much easier to understand (compared to String magic or Fíle::getParent() or similar)

**Comment by Strohgelaender** [comment]
> 
> Yes, that's expected. I think that should be no problem, since the `_temp-exports_` directory should be empty in the end. I know that behavior from other tools as well. In addition, you would have to think about when to delete the directory (imagine two instructors archive their course at the same time)
> 

Thank you for the explanation. Yes, the directory itself is empty in the end. 

> I think that the temporary directory shall not rely on the output directory directly. This would introduce an implicit dependency. Furthermore, I think the code for the explicit directory is much easier to understand (compared to String magic or Fíle::getParent() or similar)

If I understood the PR correctly, the idea behind this was just to use any directory with write access, not explicitly the export directory. That's why I thought you could reuse that parameter, since you can expect write rights for the given path. But I'd agree with you, if you want to use the configured export directory explicitly here, using the attribute would be the cleaner solution.

**Comment by dfuchss** [comment]
> If I understood the PR correctly, the idea behind this was just to use any directory with write access, not explicitly the export directory. That's why I thought you could reuse that parameter, since you can expect write rights for the given path. But I'd agree with you, if you want to use the configured export directory explicitly here, using the attribute would be the cleaner solution.

Yes, you are right :) The initial idea was to simply use a directory with right access. Initially, I also thought about simply using `$TEMP`; but then I thought a better way might be to use of a temporary directory in the configured path of the action (here: `archive`) that is currently performed.

Nevertheless, I have no strong opinion on the actual location of the location :)

**Review by Strohgelaender — APPROVED** [review]

**Pull request merged**
