### PR TITLE
`Programming exercises`: Remove duplicate alerts and fix initial dates on page load

### LINKED ISSUE #5248: Alert about invalid example solution publication date is shown repeatedly when accessing the exercise page as instructor
### Describe the bug

When opening a programming exercise the alert ‘The example solution publication date has been set to the due date!’ is repeated multiple times.

### To Reproduce

1. Go to https://artemis-test1.artemis.in.tum.de/course-management/18/programming-exercises/107
2. There are four alerts with the same content.

### Expected behavior

The should only be at maximum one alert.

Additional suggestion: The example solution publication date is *before* the due date, not *at* the due date. The alert message could be improved in that regard.

### Screenshots

To reproduce in case the linked exercise is no longer available:
Screenshot 2022-06-15 at 15-38-31 Programming Exercises

https://user-images.githubusercontent.com/64250573/173842998-d1a4f035-f775-406b-815b-20a6fcc55b24.mp4

### What browsers are you seeing the problem on?

Firefox

### Additional context

Probably introduced by #4983 or related, therefore initially assigning @akesfeden. Feel free to un-assign if not related.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by akesfeden**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Addresses duplicate alert issue mentioned in #5248 and fixes related issues in `ProgrammingExerciseLifecycleComponent` described in the next section.

### Description

Closes #5248. Additionally:
- Prevents auto-modifications to dates in read-only mode for programming exercises.
- Fixes initial dates on page load. Previously, after displaying alerts like `The example solution publication date has been set to the due date`, the dates were not set to correct values, causing saving to fail without manual user intervention.
- Fixes the source of the new date (can be release date or due date) in the alert message when auto-setting the example solution publication date. Tries to minimize number of subsequent alerts for date fixes on edit page load.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise with invalid release date, due date and example solution publication date combinations. (You shouldn't be able to create new invalid ones due to server-side validations so please **do not save the invalid exercises** you find) You can use https://artemis-test1.artemis.in.tum.de/course-management/18/programming-exercises/107/ for testing without saving.

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to details page of the invalid programming exercise and make sure you do not see any browser alerts about invalid dates.
4. Click edit, now you should only see each alert message mentioning invalid date set to a new value at most once before manually changing the dates.
5. Set release date and due date to dates later than example solution publication date, alert message should mention the source of new date correctly.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| programming-exercise-lifecycle.component.ts| 87.5% | 95.65% |

### CODE REVIEW

**Review by jbllhff — APPROVED** [review]
Tested on ts1, looks good!

**Review by xlieA — APPROVED** [review]
Tested on ts1. Everything worked as described.

**Review by JohannesStoehr — APPROVED** [review]
The code changes look good to me

**Review by nadinesamyy — APPROVED** [review]
tested on ts2, works well

**Pull request merged**
