### PR TITLE
`Exam mode`: Fix an issue during the reset of quiz exercises

### PR DESCRIPTION
**Pull request by sleiss**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Resetting an exam does also set the release date of quiz exercises.
This causes issues when importing an exam as exercises that should be imported in an exam must not have any dates set.

### Description
Do not set the release date of quiz exercises in exam.

### Steps for Testing
1. Create an exam with a modelling exercise
2. Reset this exam
3. Import this exam again -> It should work

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### CODE REVIEW

**Review by Dominik-Weinzierl — APPROVED** [review]
Code looks good :+1:

**Review by maximiliansoelch — APPROVED** [review]
Code LGTM

**Review by nairaarnez — APPROVED** [review]
Tested in ts1, the import works as described

**Comment by nairaarnez** [comment]
I have only a question, that since I saw the code does seem to be under the scope of this pr. But just to be sure:  
After reseting the exam this view is displayed:
image
when refreshig the view gets fixed
image

**Review by manuelmanso — APPROVED** [review]
LGTM

**Pull request merged**
