### PR TITLE
`Programming exercises`: Fix check for already existing exercise with same name in GitLab setups

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.
#### Changes affecting Programming Exercises
- [ ] ~~I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).~~ not applicable
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
One instructor tried to create an exercise with short name `ABC`. This did not work since Artemis complained that a project with the same name already exists in GitLab.
This was not the case, only another exercise in the same course with name `ACDEF` already existed.

### Description
The previous solution marked a project as existing if any substring of the project name matched. E.g., a project `COURSE01PROJECTAB` exists. Now the user wants to create a new exercise with short identifier `COURSE01PROJECTA`. This was not possible since the search for this identifier also returned search results matching the different name since they share a common substring in the name.
The new check checks for the _exact_ project key to check if the repositories for this key already exist in GitLab.

As a side-effect this also improves performance of this check:
The previous API call loaded _all_ projects in GitLab that contained the short name _anywhere in their name_. The actual contents of the list was ignored and it was only checked if the list is empty.
The new check limits the search to a single group and also uses a paginated response to limit the number of projects loaded from the GitLab API.

### Steps for Testing

Prerequisites:
- Server with GitLab/Jenkins setup
- 1 Instructor
- 1 Programming Exercise

1. On the details page for the existing exercise: Run the Consistency check (transparent/blue button). This should report no inconsistencies.
2. Note the short name for this exercise (listed under exercise details on the same page).
3. Create a new programming exercise in the same course with a short name that is a substring of the existing one.
4. This should work.

#### Performance Review
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| GitLabService.java | 78% | ✅ (100% line/branch for changed code)  |

### CODE REVIEW

**Review by egekurt123 — APPROVED** [review]
tested manually on ts6, works as expected

**Review by AntonGeTUM — APPROVED** [review]
Manually tested, works as described

**Review by Ceiridge — APPROVED** [review]
Tested on existing t2 deployment. Works as expected.
image

**Review by RY997 — APPROVED** [review]
Code lgtm

**Review by georgyia — APPROVED** [review]
manually tested on ts2, works as expected

**Comment by yassinsws** [comment]
code lgtm

**Pull request merged**
