### PR TITLE
Programming Exercise Template CI

### LINKED ISSUE #1138: [CI] Run Tests for Templates in CI (Github Actions)
### Is your feature request related to a problem?
Part of the Artemis Codebase are [Exercise Templates](https://github.com/ls1intum/Artemis/tree/develop/src/main/resources/templates). With #1133, we received a pull request updating the template. It would be good to run CI against the templates as well. 

### Describe the solution you'd like
We can add a GitHub @actions workflow for this.

### PR DESCRIPTION
**Pull request by jpbernius**
### Motivation and Context
Fixes #1138.

### Description
- [X] Setup GitHub @actions Matrix Environment
- [ ] Run Java Test Template
- [ ] Run Python Test Template
- [ ] Run C Test Template
- [ ] Limit Execution to Template Changes (Revert 51d2751)

@sleiss @ungaralex Can you guys help me with this? I did a basic setup for a matrix build, which will be run whenever we change something on the templates. But I do need help with actually running those tests.

### CODE REVIEW

**Comment by sleiss** [comment]
@jpbernius So we basically want to ensure that the exercise folder does not solve the test and the solution folder does, right? (https://github.com/ls1intum/Artemis/tree/develop/src/main/resources/templates/java)

**Comment by jpbernius** [comment]
@sleiss Yes! And it should probably compile?

**Comment by sleiss** [comment]
@jpbernius I've started working on the java part (some parts can be reused), this sets up the testing structure for the solution:

```
# Copy test template
mkdir github-actions/solution -p
cp -r test/projectTemplate/. github-actions/solution/

# Copy test files
mkdir github-actions/solution/test/githubactionssolution/testutils -p
cp -r test/testutils/. github-actions/solution/test/githubactionssolution/testutils
cp -r test/testFiles/. github-actions/solution/test/githubactionssolution

# Move behaviour & structural tests into one folder
mv github-actions/solution/test/githubactionssolution/structural/* github-actions/solution/test/githubactionssolution/
rm -r github-actions/solution/test/githubactionssolution/structural
mv github-actions/solution/test/githubactionssolution/behavior/* github-actions/solution/test/githubactionssolution/
rm -r github-actions/solution/test/githubactionssolution/behavior

# Copy assignment
mkdir github-actions/solution/assignment -p
cp -r solution/. github-actions/solution/assignment

# Remove everything that is sequential
sed -i '/%sequential-start%/,/%sequential-stop%/d' github-actions/solution/pom.xml

# Remove non-sequential section markers
sed -i '/%non-sequential-start%/d' github-actions/solution/pom.xml
sed -i '/%non-sequential-stop%/d' github-actions/solution/pom.xml

# Replace variables in files
find ./github-actions/solution -type f -exec sed -i 's/${packageName}/githubactionssolution/g' {} \;
find ./github-actions/solution -type f -exec sed -i 's/${packageNameFolder}/githubactionssolution/g' {} \;
find ./github-actions/solution -type f -exec sed -i 's/${exerciseNamePomXml}/githubactionssolution/g' {} \;
find ./github-actions/solution -type f -exec sed -i 's/${exerciseName}/githubactionssolution/g' {} \;

# Replace variables in directory
find ./github-actions/solution -name '${packageNameFolder}' -type d -exec bash -c 'mv "$1" "${1/\$\{packageNameFolder\}/githubactionssolution/}"' -- {} \;
```

This code is working on my ubuntu setup (I can execute `mvn clean test` in the `ArTEMiS/src/main/resources/templates/java/github-actions/solution` directory, but it expects the tools `find` and `sed` to be available. Therefore this will fail on a windows setup, maybe we have to add some Powershell code for this (is this possible?)?

**Comment by ungaralex** [comment]
I am not really familiar with GitHub actions, but from my understanding we are only missing bash scripts running the tests (for Python and C atm)?
I already have a script for the Python tests and will write one for our C template

**Comment by ungaralex** [comment]
I added the C and Python scripts. You can run them using
`./test_{c,python}_template.sh {exercise,solution}` while being in the root directory of Artemis

**Comment by sleiss** [comment]
We are also still missing the script for the template-exercise in Java, but we can simply copy the one from the solution if it is working correctly.

**Comment by krusche** [comment]
There is not much progress here, so I'll close the PR. Feel free to reopen it again

**Pull request closed without merging**
