### PR TITLE
`Development`: Decompose PDF Preview components

### PR DESCRIPTION
**Pull request by eceeeren**
**NOTE: Please test it with both vertical and horizontal PDFs!**

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

The current PDF Preview component enables instructors to individually view uploaded lecture slides and make adjustments, such as deleting or adding pages. However, the component's structure is overly complex, with all functionalities layered within a single component, resulting in lengthy, difficult-to-maintain code. To improve maintainability and flexibility, the component should be modularized into several smaller components, each focused on a specific function. This approach will streamline the codebase, making it easier to manage and adapt over time.

### Description

The PDF Preview has been decomposed into 3 different components:

**1. PDF Preview Component:** Holds the general structure of the view and the buttons, along with their functionalities. This structure consists of 
- Attachment Title
- Delete Pages button
- Append PDF button
- PDF Preview Thumbnail Grid component
- Cancel button (goes back to previous page)
- Save button (saves the edited PDF)

**2. PDF Preview Thumbnail Grid Component:** Holds the grid structure of the slide pages. Consists of
- PDF Container
- Slide pages canvases
- Page checkboxes
- Page number overlay (on hover)
- PDF Preview Enlarged Canvas Component

**3. PDF Preview Enlarged Canvas Component:** Created when the user clicks on one canvas, from the canvas image. Holds the bigger version of the slide page. Consists of

- Close button (to close enlarged view)
- Left & Right arrow buttons (to change slide page)

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to Lectures > Attachments
4. Add an attachment and click 'View' button
5. Observe that 'loading icon' is working during the loading of the PDF
6. Observe that Save/Append PDF/Delete Pages buttons are disabled during loading
7. Observe that PDF is loaded correctly
8. Observe that all of the canvases are populated correctly and shows correct page number during hover
9. Observe that 'Save' button is disabled when no changed have been made
10. Observe that 'Delete Pages' button is disabled when no slides are selected
11. Select one or multiple slides, click 'Delete Pages' and observe that they are disappeared
12. Click 'Append PDF' button, select a suitable PDF file and observe that the pages are added correctly and the thumbnail grid should scroll all the way down
13. Click 'Save' button and observe that it is saved correctly
14. Click 'Cancel' button and observe that you are returned to the previous page
15. Navigate to Lecture Units, add an attachment and repeat the steps from 4 to 14 

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| pdf-preview.component.ts | 100% | ✅              |
| pdf-preview-thumbnail-grid.component.ts | 85% | ✅                           
| pdf-preview-enlarged-canvas.component.ts | 84% | ✅                           |

### Screenshots

**1. Buttons when no slides are selected and no changes are made**

Screenshot 2024-11-04 at 01 27 19

**2. Buttons when slides are selected**

Screenshot 2024-11-04 at 01 27 31

**3. New pages are added**

Screenshot 2024-11-04 at 01 28 10

**4. Horizontal zoom**

Screenshot 2024-11-04 at 01 28 27

**5. Vertical zoom**

Screenshot 2024-11-04 at 01 32 37

## Release Notes

- **New Features**
  - Introduced an enlarged PDF canvas view with navigation controls and loading feedback.
  - Added a thumbnail grid for displaying PDF pages with enhanced user interaction.
  
- **Bug Fixes**
  - Improved error handling for PDF loading and rendering processes.

- **Documentation**
  - Updated component structure and usage guidelines to reflect new features and changes.

- **Tests**
  - Implemented comprehensive test suites for the `PdfPreviewComponent`, `PdfPreviewEnlargedCanvasComponent`, and `PdfPreviewThumbnailGridComponent` to ensure functionality and reliability.

### CODE REVIEW

**Comment by Fallthunderclap** [comment]
Tested following the instructions. I used a pretty large pdf file and still worked good.

**Review by HawKhiem — APPROVED** [review]
I tested on TS3 on Firefox, everything works as described

**Review by kevinfischer4 — APPROVED** [review]
Tested in Safari on TS1. Works as described. One thing I noticed: When deleting pages and reloading the page when it's still loading, the pages don't get deleted. What I did: 
1. Select some pages to delete 
2. Press the remove pages button
3. Confirm delete
4. Instantly refresh the tab

**Comment by eceeeren** [comment]
> Tested in Safari on TS1. Works as described. One thing I noticed: When deleting pages and reloading the page when it's still loading, the pages don't get deleted. What I did:
> 
> 1. Select some pages to delete
> 2. Press the remove pages button
> 3. Confirm delete
> 4. Instantly refresh the tab

I think that's how it should work, as changes won't be saved until Save button is clicked :)

**Review by JerroyTan — COMMENTED** [review]
[Tested on TS4, on Mozilla Firefox]
Functionalities mostly work as expected. Tested both for lecture and lecture units. Tested with both horizontal and vertical pdfs, even together.
There were however two irregularities I encountered:

Issue 1:
Directly after clicking view and right before the page starts loading, it is still possible to click append PDF, and append a PDF (while the PDF is loading). After choosing a new file, the whole loading process starts over and loads the original with appended.
To recreate:
1. Follow steps to upload pdf
2. Click on view (here you can see the button is still not disabled)
image
3. Immediately click on append pdf (Here you see I can choose pdf while the pdf is still loading)
image


Issue 2: Zooming browser with pdfs in Zoom mode (like in the screenshots of the PR description)
When I open up a single page of the pdf and either zoom my browser in or out, the page gets displaced out of view  Only happens with horizontal pdfs.
Before zooming:
image
After zooming in:
image
After zooming out:
image
Note: does not happen when opening a page while browser is already zoomed

**Comment by eceeeren** [comment]
> [Tested on TS4, on Mozilla Firefox] Functionalities mostly work as expected. Tested both for lecture and lecture units. Tested with both horizontal and vertical pdfs, even together. There were however two irregularities I encountered:
> 
> Issue 1: Directly after clicking view and right before the page starts loading, it is still possible to click append PDF, and append a PDF (while the PDF is loading). After choosing a new file, the whole loading process starts over and loads the original with appended. To recreate:
> 
> 1. Follow steps to upload pdf
> 2. Click on view (here you can see the button is still not disabled)
>    image
> 3. Immediately click on append pdf (Here you see I can choose pdf while the pdf is still loading)
>    image
> 
> Issue 2: Zooming browser with pdfs in Zoom mode (like in the screenshots of the PR description) When I open up a single page of the pdf and either zoom my browser in or out, the page gets displaced out of view Only happens with horizontal pdfs. Before zooming: image After zooming in: image After zooming out: image Note: does not happen when opening a page while browser is already zoomed

1. Reloading after a file is appended is expected behaviour, however I can disable the button while the page is loading

2. I could not reproduce this, does not happen with me. I will reach out to you about this

**Review by Haoyuli2002 — COMMENTED** [review]
Tested on TS3 as User 17 (Instructor), I could successfully upload the attachments for the lecture and also observed that the loading icon is working as expected when I clicked "View". 
Also the Buttons are disabled during loading and the "delete" button is only enabled after selecting specific pages. And I also appended another slides after that and it also works. The other features are also working fine.
Screenshot 2024-11-10 at 18 18 43

**Review by HawKhiem — APPROVED** [review]
Tested on TS6. Everything works as described. Reapprove

**Review by SimonEntholzer — APPROVED** [review]
Nice usage of the new signals :+1: code lgtm

**Review by sachmii — APPROVED** [review]
Tested on TS5, every feature works perfectly fine for vertical slides as well as for horizontal ones, in the attachment and attachment unit section.

**Review by asliayk — APPROVED** [review]
tested on ts5 with Firefox, and everything worked correctly

**Review by FelixTJDietrich — APPROVED** [review]
Code looks good to me, good job on using signals etc. :)

I tested on TS1 both on safari and chromium and it works as expected but I think there are a few minor improvements that could be done as a follow-up issue in a separate PR:

 - The select checkbox is tiny and should be a bit larger, I think at least twice as big
 - When pressing "Append PDF" limit the allowed file extensions to just `.pdf`, I could select a PNG and got: "Failed to merge files: Failed to parse PDF document (line:1620 col:357 offset=260789): No PDF header found"
 - Save button
   - There is no immediate user feedback once you press Save and it is processing, I waited 5 seconds before something happened and pressed twice in confusion
   - Prevent users from pressing it multiple times and present a loading spinner
- Cancel button
   - Group with Save button to the right, no need to keep them them apart. I did not immediately see it
   - "View" tooltip on the button is not necessary
   - If there unsaved changes alert the user before leaving the page
- When you open a large pdf initially there is no loading spinner and you see an empty canvas, IMO there needs to be a big one in the middle so you know there is something going on
- Some kind of move or reorder 2D drag and drop functionality is missing. If I delete a slide and append an replacement then I cannot move it to the correct spot

**Pull request merged**
