### PR TITLE
[Exam] Instructor code editor

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Description

- [x] Decouple row buttons displayed in exercise group view from text exercise row buttons of course->exercises
- [x] Enable isAtLeastInstructor and  isAtLeastTutor checks in the exerciseGroup view. Use isAtLeastInstructor for every navigation element there for now
- [x] Enable instructor code editor for exam programming exercises. Disabled assignment repository actions in exam mode for now.

### Steps for Testing

_Check that all course text exercise buttons are still there and work_
1. Navigate to Course Management->Exercises
--> Row buttons for text exercises are displayed correctly and work

_Check that all row buttons in the exercise group view are still there and work_
1. Navigate to Course Management->Exams->Exercise Groups
--> Row buttons for all exercise types are displayed correctly and work

_Check the instructor code editor_
1. Navigate to Course Management->Exams->Exercise Groups. Open the Instructor code editor of a programming exercise by clicking on the button 'Edit in editor'
2. Switch between the different participations and play around here
--> Everything should work as in the course programming exercise instructor code editor

### Screenshots

Capture

### CODE REVIEW

**Comment by kloessst** [comment]
@tiffca I fixed some console errors in the exercise group view but couldn't reproduce not being able to access course management locally and on TS3. Could you please give it another shot?

**Comment by kloessst** [comment]
Thanks for the feedback @tiffca and @pzdr7
I disabled the creation/reset of the assignment repository in exam mode as it is not needed.
I also fixed the saving of solution and template participation files.
Could you please check again?

**Comment by kloessst** [comment]
@tiffca I could reproduce this error. It also occurs with the current release deployed. Some exams created with a previous version of Artemis are faulty and their exercise groups can't be opened anymore. @krusche confirmed this. We probably have to delete them manually from the database. Please ignore this for testing of this PR.

**Comment by schultek** [comment]
I could not save anything in the repositories as an admin, however as a dedicated instructor (test user 11) it worked. Editing the instructions worked with both users.
Bildschirmfoto 2020-07-10 um 23 37 37

The buttons all seem to work, tested both with instructor and tutor users.
Code looks good, no issues found there. Nice work. 👍

**Comment by kloessst** [comment]
@schultek Just checked this with the current release. Code of normal exercises also can't be edited if you aren't instructor in the course. For now, I'd assume this is the wanted behavior.

**Comment by krusche** [comment]
@kloessst I think in this case we should make sure that only instructors see the button "Edit in Editor" and can navigate into the page

**Comment by kloessst** [comment]
@krusche Only instructors and admins should be able to navigate to and safe files in the instructor code editor editor now. There is still a bug related to authorization in websocket channels which leads to the isAdmin() check returning false, even though the user is an admin. https://github.com/ls1intum/Artemis/pull/1864 most likely solves this with the change to REST for saveFiles.

**Pull request merged**
