### PR TITLE
Feature: Lecture Modularisation | Exercise Units and Attachment Units

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Lecture Modularisation
Currently, there is no way for an instructor to "modularize" a lecture. A lecture just has a description, date, and various attachments like lecture notes. In most cases, instructors simply use a lecture as a place in the LMS to attach their lecture slides. Other LMSs follow a more modular approach to lecture design. A lecture can be split up into "self-contained" chunks, called modules. The lecture structure, including the kind of modules (e.g. video, HTML, files) used and how they are sequenced, can be defined by the instructor via the LMS. We want this also in Artemis.

### Notes
**This PR also contains DB changes for another feature called learning goals. You can ignore this part in your testing**

##### How To Create Lecture Units as a Instructor?
- Login as a instructor
- Navigate to "Course Management"
- Navigate to "Lectures"
- Create a Lecture and go back to the list of lectures
- Click on Units to get to the Lecture Unit Management Page 
image
- Activated are the "File" and "Exercise" Lecture Units. Video and Text are not implemented yet and thus greyed out.
image
- Creating a File Unit means basically uploading a file and connecting it to the lecture (think lecture slides). You can optionally give it a description and a release date (students can not see the unit before the release date if it is set)
image
image
- Creating a Exercise Unit means connecting an **already existing** exercise to the lecture. Therefore to test this feature you first have to create an exercise in the course. Then you can select this exercise and connect it to the lecture. **The release date and name of the unit will be taken from the exercise**
image
image
- Using the arrow keys next to the unit you can order the units any way you like and the student will see the units in this order. You can also edit and delete file units und unlink exercise units.
- Clicking on an File units downloads the file and clicking on a exercise unit navigates to the corresponding exercise

##### How to View Lecture Units as a Student?
- Login as a student
- Navigate to "Course Overview"
- Click on a Lecture
- It should be populated with the released lecture units
image
image

##### What is important to test?

- **lecture should still be fully functional in the "old way" without using units. Please that everything works, like setting attachments directly to the lecture. Editing a Lecture. Deleting a Lecture**
- **exercises should NOT be deleted when a exercise unit is removed, please test this. But when a exercise is deleted, the corresponding exercise unit should be removed**
-**Editing, Deleting and creating file units is coding wise the most complicated so these is where I expect to see the most errors**
-**Test the release date functionality so students can not see lecture units before the release date**

### Test Coverage

image
image

### CODE REVIEW

**Review by anditurdiu — CHANGES_REQUESTED** [review]
Really nice feature! It works really well, I just found 1 small issue apart from the one @fde312 mentioned:

The file upload does not validate the filenames on the client which then leads to errors. It would be good if you can add a simple validator which checks the filename against illegal characters. In my case it was: `-`
image

**Review by fde312 — CHANGES_REQUESTED** [review]
When I am in the lecture view, I see that I can start the exercise:
image

When I click into the exercise:
image

When I go back:
image

**Review by schultek — CHANGES_REQUESTED** [review]
The same issue that @fde312 had also exists for the other exercise types. I think the exercise participation of a user does not get loaded, so the exercise row does not show any result and instead the state as if the user is not participating in the exercises.

**Comment by stefanwaldhauser** [comment]
> Really nice feature! It works really well, I just found 1 small issue apart from the one @fde312 mentioned:
> 
> The file upload does not validate the filenames on the client which then leads to errors. It would be good if you can add a simple validator which checks the filename against illegal characters. In my case it was: `-`
> image

This will be fixed in a follow up

**Comment by stefanwaldhauser** [comment]
> The same issue that @fde312 had also exists for the other exercise types. I think the exercise participation of a user does not get loaded, so the exercise row does not show any result and instead the state as if the user is not participating in the exercises.

t

**Comment by stefanwaldhauser** [comment]
> The same issue that @fde312 had also exists for the other exercise types. I think the exercise participation of a user does not get loaded, so the exercise row does not show any result and instead the state as if the user is not participating in the exercises.

will be adressed in follow up

**Review by jpbernius — APPROVED** [review]
I mostly looked through database related changes. Those are fine for me. Please find some more comments below. Those can be addressed in a follow-up.

**Review by krusche — APPROVED** [review]
The general feature looks good. @stefanwaldhauser Please fix all the mentioned issues in a quick follow-up PR.

**Pull request merged**
