### PR TITLE
`Communication`: Enable code of conduct when communication is enabled

### PR DESCRIPTION
**Pull request by sarpsahinalp**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

CoC should be editable if Communication OR Messaging is enabled.

### Description

When Communication enabled CoC is also enabled.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Enable Communication & disable Messaging in a course
2. CoC is shown in the Edit-Page and is editable
3. After edit can bee seen in the management tab

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by JohannesWt — APPROVED** [review]
Small Code change looks good

**Review by pzdr7 — APPROVED** [review]
Tested on TS3.

- Communication xor Messaging enabled -> code of conduct editable ✅

**Review by edkaya — APPROVED** [review]
code lgtm

**Review by marlon-luca-bu — APPROVED** [review]
LGTM 👍

**Review by Strohgelaender — APPROVED** [review]
code

**Review by egekurt123 — APPROVED** [review]
LGTM

**Pull request merged**
