### PR TITLE
`Development`: Make Telemetry service async

### PR DESCRIPTION
**Pull request by SimonEntholzer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

In production, the telemetry service sends telemetry data to https://telemetry.artemis.cit.tum.de/. We want to make sure this sending operation is not blocking any other parts of the Artemis application from starting up.

### Description

We split the TelemetryService into two services, to use the `@Async` annotation. With this the further startup can continue, even if the operation of the TelemetrySendingService would block indefinitely. 

### Steps for Testing

You can only really test this locally, as the feature is disabled for `dev` in the code.
What you could do, is to manually comment out the code disabling it, setting up a local instance of the Telemetry collection service: [Artemis-Telemetry Service](https://github.com/ls1intum/Artemis-Telemetry), and start the server. 
As before it should send the data correctly.
(Functionality should not be changed in any way by this PR) 

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Introduced a new service for asynchronous telemetry data transmission, enhancing system observability.
- **Refactor**
	- Improved the structure of the telemetry functionality by separating concerns between services.
	- Streamlined dependency injection in the telemetry service for better maintainability.
- **Tests**
	- Enhanced test reliability by implementing asynchronous verification methods to accommodate potential delays.

### CODE REVIEW

**Review by az108 — APPROVED** [review]
Code 👍

**Review by az108 — APPROVED** [review]
Reapprove Code after Merge Conflicts 👍

**Review by BBesrour — APPROVED** [review]
Tested in a testing session, works as described

**Review by iyannsch — APPROVED** [review]
Code LGTM - nice changes!

**Review by pzdr7 — APPROVED** [review]
Code LGTM

**Review by krusche — APPROVED** [review]

**Pull request merged**
