### PR TITLE
[Chore] Reduce Metis REST call payloads and refactor Metis Resources

### PR DESCRIPTION
**Pull request by lschlesinger**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Description

To avoid sending `Post` and `AnswerPost` objects with complete nested course, lecture, exercise objects, I reduce the respective fields to their Ids where possible. 
This avoids circular references in serialization and reduces payload sizes.
Also some additional checks were be introduced on Metis related endpoints: 1. no posts for exam exercises, 2. no posts for courses with posts disabled

Furthermore I factored out business logic from the resources `Post`, `AnswerPost`, and `Reaction` by introducing dedicated services for these resources and reduced code duplication by using "validationMethods" that include repetitive checks.

### Steps for Testing

1. Log in to Artemis
2. Navigate to an exercise or lecture of a course with enabled student posts
3. Create, Edit (own), delete (own) posts and answer posts as student
4. Create, Edit (arbitrary), delete (arbitrary), approve posts and answer posts as instructor

### Test Coverage

`PostResource`: 100%
`PostService`: 100%
`AnswerPostResource`: 100%
`AnswerPostService`: 98%
`PostingService`: 100%
`ReactionResource`: 100%
`ReactionService`: 100%

### CODE REVIEW

**Review by rs-maker — APPROVED** [review]
Tested on TS3 everything works.

**Review by katjanakosic — APPROVED** [review]
Worked fine on TS2 👍

**Review by PatZintel — COMMENTED** [review]
Creating, editing, answering and deleting a post works for exercises, but i cant post anything in a lecture... i get a 400 Bad Request for the "creating a post" REST call here
image

I would interpret this error as a problem with the path, maybe its different on server and on client side or its an actual JSON parsing error

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Worked for me. Exercises and also Lectures  worked.

**Pull request merged**
