### PR TITLE
[Feature] Collapsible List Items For Feedback

### PR DESCRIPTION
**Pull request by rs-maker**
TODO:
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
 Feedback items have long text making the feedback view crowded
 #3217

### Description
 Created feedback-collapse.component which takes the feedbacks text and makes it un-/collapsible if it has more than 200 characters.

### Steps for Testing

Easiest way i found is this:
0. Be logged in as instructor
1. Navigate: Course Management -> Some Course -> Exercises -> If there are none generate a basic one for testing -> Edit in Editor 
2. Now you should be able to see the feedback on the top right
3. if none of the feedback messages are over 200 characters go in the test repository and change a message to be longer 
testing_feedback
4. Save and submit
5. look at feedback

### Test Coverage

TODO

### Screenshots

feedback_collapse

### CODE REVIEW

**Comment by dfuchss** [comment]
@rs-maker I've linked the actual Issue and fixed the formatting :) of the text of this PR

**Comment by rs-maker** [comment]
Right now this is how it looks:
Screenshot from 2021-04-20 18-15-20

Screenshot from 2021-04-20 18-15-33

Feedback with text < 200 characters are displayed as usual:
Screenshot from 2021-04-20 18-18-51

I will change the positioning of the arrows slightly and also change the "closed" arrow to be a right facing arrow and open the PR for Review.

**Comment by LDAP** [comment]
Maybe you can use Angular builtin functionality.
https://material.angular.io/components/expansion/overview
The collapse icon does also fit better the look and feel of Artemis.

**Comment by rs-maker** [comment]
> Maybe you can use Angular builtin functionality.
> https://material.angular.io/components/expansion/overview
> The collapse icon does also fit better the look and feel of Artemis.

youre right the icon looks a little out of place even though the fa-icons are being used in artemis a lot. Ill try to use the expansion panel :)

**Comment by rs-maker** [comment]
Closing this PR because it was branched from a fork instead of directly of Artemis. My mistake. Opening a new one asap.

**Pull request closed without merging**
