### PR TITLE
`General`: Enhance styling of announcement notification emails

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).

### Motivation and Context

If a new announcement is created, emails sent by Artemis can look weird at the moment:

grafik

### Description

Changed the styling and formatting of emails sent by Artemis.
For some reason, there was a global CSS rule on the ``*`` selector that removed padding and margin from all elements, causing indentation etc. to be removed.
Additionally changed to font back to default and reworked what the header looks like.

Removed the random border in the email from most notifications and added a better looking box to the announcement notification email template.

Added proper styles for quotes and codeblocks.

Result:
grafik

### Steps for Testing

Prerequisites:
- Be on TS0 or TS1 as these are the only ones with a working email config (thanks to @Mtze for setting this up so quickly!)
- Use your own account with a correct E-Mail

1. Create a new course or use a course where only you participate to avoid spam to everyone
2. Add yourself to the student list of the course
3. Create an annoucement post. Use some markdown formatting
4. Check if you receive the email and it looks as expected

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by ge65cer — APPROVED** [review]
Nicely done, the styling is a lot better now.
I consider this a hotfix, in the long term we should maybe employ a Mailing Framework like [MJML](https://mjml.io/), as there are still some issues on Windows Mail and Outlook (e.g., logo too big and header color not applied). There are just too many issues with Mail Apps trying to parse HTML… 😄

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Email layout looks good to me. 👍

**Review by SimonPaul02 — APPROVED** [review]
Tested on Ts1, worked as described

**Review by yuling-sun — APPROVED** [review]
Tested on TS1 as described. The e-mail works.

**Pull request merged**
