### PR TITLE
Remove outdated modeling conflict code + update dependencies

### PR DESCRIPTION
**Pull request by krusche**
We had some outdated and not used code due to a not finished bachelor thesis.
I removed the code and updated the dependencies in this PR

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context
Cleanup

### Description
Remove everything related to `conflicting_result` and `model_assessment_conflict`

### Steps for Testing
1. Create, participate and assess modeling exercises
2. Everything should work normally

### CODE REVIEW

**Comment by krusche** [comment]
@tiffca not sure what the problem is, but for me this works. Might be an issue with your browser or Internet Connection?!?
Can you try the following. Open the developer tools, right click on the reload icon and choose Empty Cache and hard reload

image

**Comment by tiffca** [comment]
I should have done that before, thanks for the hint! That worked (I couldn't figure out how to hard reload, but I opened incognito browser), however now it seems the assessments are not submitting. 


Steps (test server 3) 
1. create a model exercise, as instructor
2. participate as student
3. assess exercises as instructor 
4. click submit. Expected: override/assess next should show. Actual: submit button still shows, and assessment is not submitted. Student cannot view the grade. 

1996-submiit

**Comment by krusche** [comment]
@tiffca @alexmardale thanks for testing. There was indeed an issue. I accidentally removed the flag `submit=true` when deleting the conflict code. I added it back, so it should work again correctly.

Would be great if you can give it another try (as soon as the yarnpkg build and deployment issues are resolved). Thanks!

**Comment by krusche** [comment]
@stefanwaldhauser @amahmario thanks for testing
Are the UI issues new? (i.e. introduced in this PR?)
Or do you also experience those in the `develop` branch (or on the production server or Artemis)?

**Comment by krusche** [comment]
@alexmardale which browser did you use?
Is this an issue on Chrome? Do you also have it on `develop`

**Comment by krusche** [comment]
@alexmardale which browser did you use?
Is this an issue on Chrome? Do you also have it on `develop`?
Can you check if this happens for other exercise types as well?

**Comment by alexmardale** [comment]
For me it's also on Firefox.
I'll check on `develop` for modeling and other exercise types.

**Comment by FuchsDominik** [comment]
I am using Chrome and dont experience this UI bug.
image

**Comment by alexmardale** [comment]
I'm deploying `develop` on TS3 now if anyone else wants to check

**Comment by alexmardale** [comment]
On `develop` it looks normal (no UI issue) for Firefox:
aaa
bbb

And same for Chrome.

**Comment by alexmardale** [comment]
On `enhancement/cleanup-conflict-update-dependencies` I checked for file upload and text exercises as well and the UI issue is present in Firefox, but in Chrome it looks ok.
Will check on `develop` now for other exercise types.

**Comment by alexmardale** [comment]
On `develop` modeling, file upload and text exercises look ok on both Chrome and Firefox.

**Comment by fde312** [comment]
I am having the same issue for Chrome, Safari and Firefox. Other than that it worked fine for me.
image

**Comment by krusche** [comment]
We will fix the issue in a follow up PR. Help is appreciated here!

**Pull request merged**
