### PR TITLE
[Bugfix] Fix grading related sentry issues

### LINKED ISSUE #2409: NPE in Grading Statistics
```
Nov 11 16:48:47 node1 java[107140]: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "de.tum.in.www1.artemis.domain.Feedback.isPositive()" is null
Nov 11 16:48:47 node1 java[107140]:         at de.tum.in.www1.artemis.service.ProgrammingExerciseGradingService.addFeedbackToStatistics(ProgrammingExerciseGradingService.java:637)
Nov 11 16:48:47 node1 java[107140]:         at de.tum.in.www1.artemis.service.ProgrammingExerciseGradingService.generateGradingStatistics(ProgrammingExerciseGradingService.java:561)
Nov 11 16:48:47 node1 java[107140]:         at de.tum.in.www1.artemis.web.rest.ProgrammingExerciseGradingResource.getGradingStatistics(ProgrammingExerciseGradingResource.java:120)
Nov 11 16:48:47 node1 java[107140]:         at de.tum.in.www1.artemis.web.rest.ProgrammingExerciseGradingResource$$FastClassBySpringCGLIB$$8c8b28fe.invoke(<generated>)
```

### LINKED ISSUE #2410: SQL Exception in processNewProgrammingExerciseResult
We should handle the case and prevent 'NaN' values

```
Nov 11 16:44:13 node1 java[107140]: 2020-11-11 16:44:13.536 ERROR 107140 --- [nio-8080-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : 'NaN' is not a valid numeric or approximate numeric value
Nov 11 16:44:13 node1 java[107140]: 2020-11-11 16:44:13.547 ERROR 107140 --- [nio-8080-exec-3] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
Nov 11 16:44:13 node1 java[107140]: org.springframework.orm.jpa.JpaSystemException: could not insert: [de.tum.in.www1.artemis.domain.Feedback]; nested exception is org.hibernate.exception.GenericJDBCException: could not insert: [de.tum.in.www1.artemis.domain.Feedback]
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:353)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:154)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
Nov 11 16:44:13 node1 java[107140]:         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
Nov 11 16:44:13 node1 java[107140]:         at com.sun.proxy.$Proxy264.save(Unknown Source)
Nov 11 16:44:13 node1 java[107140]:         at de.tum.in.www1.artemis.service.ProgrammingExerciseGradingService.processNewProgrammingExerciseResult(ProgrammingExerciseGradingService.java:105)
```

### PR DESCRIPTION
**Pull request by schultek**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context

This fixes several sentry issues and bugs.

Fixes #2409 
Fixes #2410 

Also fixes [this sentry issue](https://sentry.io/organizations/ls1intum/issues/1741295727/?environment=prod&project=1440029&query=is%3Aunresolved&sort=freq&statsPeriod=7d)

### Description

- Added null / undefined checks
- In the grading page, the input values are not checked for NaN / null values and given a default value.

### Steps for Testing

1. Log in to Artemis
2. Navigate to the Grading Page of a Programming Exercise
3. Try to add NaN values (letters, symbols, etc) -> When navigating out of the input field, the value should be reset to the previous value.
4. Try empty values -> When navigating out of the input field, the value should be reset to the default value for this field.

### Test Coverage

* programming-exercise-configure-grading.component.ts: 82%

### Screenshots

ezgif com-gif-maker (1)

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Works fine (according to the testing steps), tested together with @marvinchimeka 
When updating a field with a valid value, I still first have to click outside of the field so that the "save" button gets enabled. (Hopefully, it is expected)

**Review by marvinchimeka — APPROVED** [review]
Tested in a testing session with @airelawaleria. Everything worked fine.

**Review by JohannesWeiss — APPROVED** [review]
Works like intended.

**Review by EneaGore — APPROVED** [review]
Everything worked as described!

**Review by LudwigWeide — APPROVED** [review]
Tested NaN and empty values on TS1. Works as intended

**Review by krusche — APPROVED** [review]

**Pull request merged**
