### PR TITLE
`Exam mode`: Remove exercise title from solution containers 

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

The title of an exercise is displayed three times during the exam (see screenshot), if the sidebar is not collapsed. Therefore, the exercise title in the solution container becomes unnecessary. 

### Description

Changed the exercise title displayed in the solution container to a static text "Your Solution", which is presented only in text, modeling, and file upload exercises.

#### Exam Mode Testing

Prerequisites:
- 1 Exam with 3 exercises (text, modeling, and file upload)
- 1 Student

**(There is already an exam called 'Exam Title Container' under my course on TS4. Test users 1-5 are registered to the exam.)**

1. Log in to Artemis
2. Participate in the exam
3. Verify that you see 'Your Solution' or 'Deine Lösung' in the solution container header instead of the exercise title

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

Before
Group 155

After
Screenshot 2024-10-08 at 21 32 31

## Summary by CodeRabbit

- **New Features**
	- Updated exercise title display logic to show a translated string for "your solution" based on the exam timeline state.
	- Added new translation keys for "your solution" in both English and German.

- **Bug Fixes**
	- Improved clarity in user submissions by ensuring the correct title is displayed when the exam timeline is not available.

### CODE REVIEW

**Review by anian03 — APPROVED** [review]
Tested, works as expected

**Review by SimonEntholzer — CHANGES_REQUESTED** [review]
Would it be possible here to use the jhiTranslate instead of the artemisTranslate pipe?

**Review by JohannesStoehr — APPROVED** [review]
Code

**Comment by edkaya** [comment]
> Would it be possible here to use the jhiTranslate instead of the artemisTranslate pipe?

I couldn't find a way to use jhiTranslate here. Any suggestions?

**Review by PaRangger — APPROVED** [review]
Code LGTM

**Review by rabeatwork — APPROVED** [review]

**Pull request merged**
