### PR TITLE
`Development`: Update Apollon version

### PR DESCRIPTION
**Pull request by minrows**
#### General

- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
Update version of Apollon from [v2.11.2](https://github.com/ls1intum/Apollon/releases/tag/v2.11.2) to [v2.11.3](https://github.com/ls1intum/Apollon/releases/tag/v2.11.3)

### Description
This bugfix version of Apollon fixes an issue with long text insertion in Apollon, the problem stated by @TheTrueVester at one of the [Testing Session](https://confluence.ase.in.tum.de/display/ArTEMiS/Testing+Session+11.07.2022) [Table: Findings > Assigned Issue > Issue Nr: 24]

### Steps for testing
As stated in "Steps to reproduce" section of Testing session. 

OR
1. Create a modeling exercise
2. Insert any element in canvas and try setting its name (or attributes/methods) with more than 100 characters.
3. Observe that the application stops taking input once 100 characters are inserted.

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]

**Review by SimonPaul02 — APPROVED** [review]
Code change looks good, but I couldn't test it:
image

**Comment by minrows** [comment]
> Code change looks good, but I couldn't test it: image

Ahh, it could be coz of the same branch name I used to update the previous versions of Apollon.
Could you try deploying it with a different release version name?
`general-update-apollon-2.11.3-1` for instance?

**Review by jschmautzer — APPROVED** [review]
tested on ts2, worked as described

**Review by joaquinmurcia — APPROVED** [review]
Tested on TS2. Works as expected.

**Comment by krusche** [comment]
I accidentally updated the version in the last general client updates, thanks for testing that everything works!

**Pull request closed without merging**
