### PR TITLE
Use 0.0 as default value if no credits are present

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Added JUnit test for the bug (that fails when the fix is not present).

### Motivation and Context

Re-evaluate fails for some exercises with manual results because feedback credits are null for some reason.

See Issue: https://sentry.io/organizations/ls1intum/issues/2206895272/

### Description
- Added `Objects.requireNonNullElse` to use `0.0` as default if the feedback credits are null

### Steps for Testing
- Run and check the tests, there is currently no way known to reproduce it on the test server.

### CODE REVIEW

**Review by FrankeLukas — APPROVED** [review]
The code changes look logical to me considering the Sentry error. Since I didn't know a reproduction case I just tested that the score is still calculated correctly after submitting/assessing/updating a result.

**Review by fde312 — DISMISSED** [review]
We were not able to reproduce the error, but the code changes will fix the sentry issue. Good job! 👍

**Review by SimonEntholzer — DISMISSED** [review]
We tried to reproduce the issue but weren't successful unfortunately. Still, the code changes look like they would fix the error.

**Review by derLalla — APPROVED** [review]
re-approve after merge of develop

**Review by FuchsDominik — COMMENTED** [review]
So the PR server tests passes, however locally i get a error message regarding dot and comma notation
Screenshot 2021-02-10 at 16 01 04

**Comment by MaisiKoleni** [comment]
> So the PR server tests passes, however locally i get a error message regarding dot and comma notation

Interesting. That means that our server is locale dependent as well.

**Comment by krusche** [comment]
> > So the PR server tests passes, however locally i get a error message regarding dot and comma notation
> 
> Interesting. That means that our server is locale dependent as well.
> 
> I will fix this, but we should later also fix the locale for the server.

This is one of the reasons why I don't like to have points calculated on the server in a string. This should be decided on client side based on the user locale. I think in the future we should calculate the result string completely on the client side

**Comment by MaisiKoleni** [comment]
I localized the test case for now to avoid that problem and changing more code that is out of scope for this PR.

**Review by FuchsDominik — APPROVED** [review]
Re-ran the test locally and now it passes. 👍

**Review by SimonEntholzer — APPROVED** [review]
Test runs works locally :+1:

**Review by FrankeLukas — APPROVED** [review]
Re-approve (works locally as well).

**Pull request merged**
