### PR TITLE
`Exam mode`: Allow instructors to enable the test download for students

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

#5762 allowed students to download the tests after the due date if the instructor enables it. This should be available for exam exercises as well.

### Description

Instructors can now enable the download of the tests for exam exercises as well after setting a publication date in the exam itself.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student

1. Create an exam without a date for the release of the example solutions and with a programming exercise
2. Participate as student
3. Check that you cannot enable including the tests in the edit screen of the exercise as instructor
4. If the due date of the exam is not over yet, wait until it is
5. Set a publication date for the example solution in the exam in the past
6. Check that the student can now download the example solution
7. Enable the inclusion of the tests in the programming exercise
8. Check that the student can now download the tests as well

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [exam-result-summary.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5777/latest/artifact/shared/Coverage-Report-Client-Tests/app/exam/participate/summary/exam-result-summary.component.ts.html) | 91.35% | ✅ |

### Screenshots

Bildschirmfoto 2023-11-23 um 13 58 29

### CODE REVIEW

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts11. Worked as expected.

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM 👍

**Review by Strohgelaender — APPROVED** [review]
code lgtm

**Review by AntonGeTUM — APPROVED** [review]
Tested on TS11, works as described

**Review by valentin-boehm — APPROVED** [review]
Tested on TS11. Works as expected

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM 👍

**Review by rabeatwork — APPROVED** [review]

**Pull request merged**
