### PR TITLE
Feature/achievements/client

### PR DESCRIPTION
**Pull request by balazs-czopf**
### Checklist
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

No actual server changes included besides the renaming of a url.
The other server changes are for testing purposes only and are to be removed once the client has been tested successfully.

### Description
This PR introduces the client changes for achievements which consist of the checkbox in the course settings to en-/disable the achievements (first screenshot) and the list of achievements in the statistics tab of a course where students can see their earned achievements (second screenshot).

### Steps for Testing

**Current round: second**

First round: ✔

~~1. Log in to Artemis
2. Go to the statistics tab of a course that has at least one exercise
3. Make sure statistics are shown but no achievements.
4. Go to Course Management and edit course by enabling achievements (as seen in first screenshot)
5. Go back to statistics tab and check if now you can see a table of achievements (as seen in second screenshot, but with more achievements)
6. Check if the alignment of the whole table is alright, especially the icons and no displacement or anything strange or unexpected happens.~~

Second round:
After the client was tested succesfully and this PR got enough approvals, the server changes for easier testing are going to be reverted. Only code reviews are required.

### Screenshots
user_interface_management_example
user_interface_full_example

### CODE REVIEW

**Review by JohannesWeiss — APPROVED** [review]
Works as intended. Switching achievements on/ off did function correctly. I tested it with different devices (phone/ tablet/ diff. screen resolutions) and the list of achievements behaved responsively as expected. Good job 👍

**Review by simonzilker — APPROVED** [review]
Works perfectly on ts1! Nice feature!

**Review by marvinchimeka — APPROVED** [review]
Tested on ts1. worked fine !

**Review by airelawaleria — APPROVED** [review]
Works fine

**Review by JannisBittlmayer — COMMENTED** [review]
~~I tried using this build: https://bamboo.ase.in.tum.de/browse/ARTEMIS-WEBAPP1850-8 on TS3 but it got stuck on starting up (tried it twice with another build in between, which worked). I don't know what caused this and if this was a random issue now.~~
Noticed myself this isn't really open for new reviews.

**Review by EneaGore — APPROVED** [review]
Worked exactly as intented on ts1.

**Pull request merged**
