### PR TITLE
`Dark Mode`: Change used emoji-set to avoid hardly noticeable emojis

### PR DESCRIPTION
**Pull request by canberkanar**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
Solves #5118 .

### Description
As reported by @willergeorg, some emojis (from the group 'heavy...') are hardly noticeable within the emoji picker, Posts and Answers when using the darkmode. Since the problem could also be replicated via the used libraries own demo page, we change the used emoji-set to 'facebook', where the emojis are noticeable again.

### Steps for Testing

Prerequisites:
- 1 Students
- 1 Lecture with Discussions enabled

1. Log in to Artemis
2. Navigate to Course Discussions page or an exercise
3. Switch to dark mode
4. Create a Post if none exists.
5. Open the emoji-picker and type 'heavy' to it's searchbar.
6. Make sure that the emojis are more noticeable then they were before.
7. Upvote a post by selecting the 'plus' emoji.
8. Make sure that the upvote is visible.
9. Make sure the same of the steps holds also for AnswerPosts.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

Unchanged

### Screenshots

Old emoji-set
image!
New emoji-set
image!

### CODE REVIEW

**Review by ge65cer — CHANGES_REQUESTED** [review]
I get the intention behind this PR, but the solution is not viable. While it fixes the contrast for some Emojis, others look worse. Take a look at the squares for example.

<details>
<summary>Screenshots</summary>
Left is Facebook (proposed), right is Apple (existing).

Facebook Apple
</details>

Maybe adjusting the picker's background color towards Slack's dark theme could be an idea? There all Emojis seem to have rather good contrast.

<details>
<summary>Screenshot</summary>
Screenshot 2022-05-18 at 15 39 08
</details>

**Review by bassner — DISMISSED** [review]
Tested on TS5; the emoji set was changed to the one of Facebook. The "heavy" icons look good now, even though there are of course still very dark emojis, but they are probably rarely used (e.g. a few ones in the "objects" tab). The heavy ones are way more important! :)
Code looks good to me as well 👍

**Comment by Hialus** [comment]
I am against this change. The default behavior of emojis should be to use the system's native emoji set (e.g. Apples emojis on macOS)
Additionally not using the native emoji set means that the specified emoji set has to be downloaded first. At least for the facebook set, this means a file of about 4 MB just for this one feature.
Lastly, this would also cause inconsistent emojis in Artemis, as Emojis in e.g. the problem statement would still use the native emoji set.

In my opinion, these are too many drawbacks just so a handful of emojis look good when using darkmode. Also, you should consider that even more popular applications like Discord have this problem (see screenshot) so I think we can simply ignore this.
grafik

**Comment by canberkanar** [comment]
> I am against this change. The default behavior of emojis should be to use the system's native emoji set (e.g. Apples emojis on macOS) Additionally not using the native emoji set means that the specified emoji set has to be downloaded first. At least for the facebook set, this means a file of about 4 MB just for this one feature. Lastly, this would also cause inconsistent emojis in Artemis, as Emojis in e.g. the problem statement would still use the native emoji set.
> 
> In my opinion, these are too many drawbacks just so a handful of emojis look good when using darkmode. Also, you should consider that even more popular applications like Discord have this problem (see screenshot) so I think we can simply ignore this. grafik
> 
> Edit: After looking at the emoji-mart package I think the better solution would be to provide custom emoji versions for the problematic emojis, as this seems to be supported by emoji-mart.

Are you really sure about the downloading part? I'm running Artemis over windows but still had the Apple emojis before this change.

**Comment by canberkanar** [comment]
> I get the intention behind this PR, but the solution is not viable. While it fixes the contrast for some Emojis, others look worse. Take a look at the squares for example.
> 
> Screenshots
> Left is Facebook (proposed), right is Apple (existing).
> Facebook Apple
> 

The heavy icons are more important than the ones you have addressed. We need the plus icon for upvoting for instance. Now it's nearly invisible.
image

> Maybe adjusting the colors towards Slack's dark theme could be an idea? There all Emojis seem to have rather good contrast.
Please take a look at the demo page of the tool we are using. I don't think implementing a new theme that just "looks" like Slack is a good idea.
https://ngx-emoji-mart.vercel.app/

> Screenshot
> Screenshot 2022-05-18 at 15 39 08

**Comment by Hialus** [comment]
> Are you really sure about the downloading part? I'm running Artemis over windows but still had the Apple emojis before this change.

I can currently only test this on macOS and it did not need to download anything here before.
It is possible that for Windows emoji-mart never uses the default emoji-set of Windows and instead downloads the apple one by default.

> I don't think simply ignoring the issue is a good idea. Look at the upvote button below, it's nearly invisible.

As I said in my edit it would make a lot more sense to use a custom emoji for this. Or at least we could use another emoji like one of these 3:
grafik

**Review by alaraozdenler — APPROVED** [review]
Tested on TS3, emojis look really good!

**Comment by bassner** [comment]
I've tested this on MacOS with both the ``facebook`` and the ``apple`` set. The picker downloaded the set both times.
This is also currently happening on the production instance, both in Firefox and Safari.
So per-se, downloading emoji sets doesn't seem to be a problem as it always worked up until now.

The real problem is that it's fetched from unpkg. That is a GDPR problem.
We should therefore rather enforce the use of native emojis like @Hialus suggested (can be done by setting ``isNative`` to ``true`` on all emoji related components), or deliver the emoji sheets from our own servers (can be done by passing it manually using ``backgroundImageFn`` to emoji components). The latter would also allow us to pre-fetch it in a service and store it locally for a longer time, maybe weeks, avoiding most performance problems even on slower connections.

**Comment by canberkanar** [comment]
> I've tested this on macOS with both the `facebook` and the `apple` set. The picker downloaded the set both times. This is also currently happening on the production instance, both in Firefox and Safari. So per-se, downloading emoji sets doesn't seem to be a problem as it always worked up until now.
> 
> The real problem is that it's fetched from unpkg. That is a GDPR problem. We should therefore rather enforce the use of native emojis like @Hialus suggested (can be done by setting `isNative` to `true` on all emoji related components), or deliver the emoji sheets from our own servers (can be done by passing it manually using `backgroundImageFn` to emoji components). The latter would also allow us to pre-fetch it in a service and store it locally for a longer time, maybe weeks, avoiding most performance problems even on slower connections.

Can you elaborate on the problem when downloads take place from unpkg? Is it unreliable?

Below I have some screenshots with isNative set to true. This might also work but there are some emojis that can't be loaded. I may remove these but the problem is probably dependent on the device and won't actually work, since on other devices different emojis might break.

image
image

**Comment by bassner** [comment]
> I agree, that sounds like a reasonable idea if it eliminates the need to download the image set entirely.

It still doesn't solve the problem of the important heavy emojis being too dark, though. That's why I added the other alternative.

Changing the theme of the picker is possible, but then we'd need to change backgrounds of all places where ``ngx-emoji`` is used as well, e.g. in reactions, which could be done, but might look weird:
image
image

Therefore, I'd consider using the facebook set as a very reasonable alternative

**Comment by bassner** [comment]
@canberkanar omg, that looks weird, bruh
I'm leaning more and more towards delivering a good set of emojis to windows user :D

The problem with unpkg is not reliability, but privacy. We're fetching the set from the client, thereby transmit the user IP to unpkg

**Comment by canberkanar** [comment]
> > Please take a look at the demo page of the tool we are using. I don't think implementing a new theme that just "looks" like Slack is a good idea.

I think since the set is downloaded anyway and this issue is out of the scope of this PR, we can merge it for the next release so that the user experience is not ruined. You may address your concerns on the weekly.

**Comment by Hialus** [comment]
> Since the scope of this PR is to make sure that users have a pleasant experience at the moment while using dark mode, I think we can merge this little change

I don't think we should just rush this change. It is at most a medium priority issue and only occurs when a user uses a feature that is clearly labeled as being in beta. 
Therefore there is no need for a quick and dirty fix that will get replaced by a better fix later on. Either we ignore the issue or directly fix it properly.

And again I cannot approve of the PR.
This is too big of a change for basically a single emoji. (The plus sign) It would make way more sense to either use a custom emoji for upvoting or use an alternative emoji (like thumbs up, up arrow, up triangle, etc.)
The bare minimum should be that the user can deactivate this change and use the native emoji set instead.

Also regarding the missing emojis in your case: This is a Windows issue. The Windows emoji set is far from complete and that is why there are missing emojis for you. Filtering these out is not feasible for us and would be a feature I expect emoji-mart to have.

This should first be discussed thoroughly with the entire development team before any change is made here.

**Comment by canberkanar** [comment]
> > Since the scope of this PR is to make sure that users have a pleasant experience at the moment while using dark mode, I think we can merge this little change
> 
> I don't think we should just rush this change. It is at most a medium priority issue and only occurs when a user uses a feature that is clearly labeled as being in beta. Therefore there is no need for a quick and dirty fix that will get replaced by a better fix later on. Either we ignore the issue or directly fix it properly.
> 
> And again I cannot approve of the PR. This is too big of a change for basically a single emoji. (The plus sign) It would make way more sense to either use a custom emoji for upvoting or use an alternative emoji (like thumbs up, up arrow, up triangle, etc.) The bare minimum should be that the user can deactivate this change and use the native emoji set instead.
> 

I don't agree with the use of a custom emoji to fix this problem. There are many emojis like this when you take a look at the picker, and handling them one by one would not be efficient in my opinion.

> Also regarding the missing emojis in your case: This is a Windows issue. The Windows emoji set is far from complete and that is why there are missing emojis for you. Filtering these out is not feasible for us and would be a feature I expect emoji-mart to have.

I have raised the missing emoji problem, to let people here know that it is not an applicable solution, since some users with windows will have problems with it. We can't opt out people that don't use MacOS right?

> This should first be discussed thoroughly with the entire development team before any change is made here.

**Comment by Hialus** [comment]
> I don't agree with the use of a custom emoji to fix this problem. There are many emojis like this when you take a look at the picker, and handling them one by one would not be efficient in my opinion.

I never saw any of them being used except the plus one. 

> I have raised the missing emoji problem, to let people here know that it is not an applicable solution, since some users with windows will have problems with it. We can't opt out people that don't use MacOS right?

What is the alternative though? We either have to use the native emoji set or deliver our own, as Patrick mentioned. When we provide our own we can't simply copy one of the existing ones, as that might lead to copyright issues.

You can think of this what you want, but you aren't gonna change my opinion on this PR. Just because it works does not mean it is a good change.

**Comment by canberkanar** [comment]
> > I don't agree with the use of a custom emoji to fix this problem. There are many emojis like this when you take a look at the picker, and handling them one by one would not be efficient in my opinion.
> 
> I never saw any of them being used except the plus one.

If a user decides to react to a post using one, you would see an example.

> 
> > I have raised the missing emoji problem, to let people here know that it is not an applicable solution, since some users with windows will have problems with it. We can't opt out people that don't use MacOS right?
> 
> What is the alternative though? We either have to use the native emoji set or deliver our own, as Patrick mentioned. When we provide our own we can't simply copy one of the existing ones, as that might lead to copyright issues.
> 
> You can think of this what you want, but you aren't gonna change my opinion on this PR. Just because it works does not mean it is a good change.

**Comment by bassner** [comment]
> What is the alternative though? We either have to use the native emoji set or deliver our own, as Patrick mentioned. When we provide our own we can't simply copy one of the existing ones, as that might lead to copyright issues.

If that's a legal issue, we're violating it right now already anyways as all clients are pulling the apple set from unpkg. I'm pretty sure the packages would have been DMCA'ed by Apple or Facebook and taken down from GH and npm if they mustn't be used anywhere else. Given that Artemis is a non-profit open-source project, I'm very sure that we're safe on that point.
If we want an explicit license, the Twitter set for example is licensed under CC-BY 4.0 and is still a good looking one. It doesn't solve the heavy-emoji color problem, but is still a good option for clients running on Windows.

In the end, I personally don't think that letting Windows user hang with that very, very bad, incomplete set of system emojis is a good idea at all. That's really a bad user experience we have to avoid

**Comment by ge65cer** [comment]
Let's discuss this issue in the weekly tomorrow.
There is no rush to merge this PR, as it's rather a small enhancement than a bugfix and dark mode is still in beta anyway.

**Review by nadinesamyy — COMMENTED** [review]
tried to test this with a tutor as well as a student account on ts1 but I could not even find the emoji set when creating a new post in a lecture where the discussion is enabled

**Comment by canberkanar** [comment]
> tried to test this with a tutor as well as a student account on ts1 but I could not even find the emoji set when creating a new post in a lecture where the discussion is enabled

Emojis can only be added after the post is created. For this, you have to use the emoji-picker found at the footer of Posts and AnswerPosts.

**Comment by canberkanar** [comment]
It was decided by the development team not to use the 'Facebook' set. An alternate solution will be implemented.

**Pull request closed without merging**
