### PR TITLE
Setup Sphinx Documentation for Read the Docs

### PR DESCRIPTION
**Pull request by jpbernius**
Convert existing Documentation for Sphinx so we get this:
https://artemis-platform.readthedocs.io/en/chore-setup-read-the-docs/index.html
and this:
https://artemis-platform.readthedocs.io/_/downloads/en/chore-setup-read-the-docs/pdf/

## Please verify
All Information currently present in [`/doc`](https://github.com/ls1intum/Artemis/tree/develop/doc) is present, and all images show up.

## Discussion
Please give feedback on the structure of the documentation. We can outline a basic structure and create issues for additional documentation we want to create here.

So far this is separated into user and developer, but maybe there are better ideas?

### CODE REVIEW

**Comment by tessaRuckstuhl** [comment]
The first link gives me a 

> "This page does not exist yet"

is it supposed to do so?
And do you want us to review only the generated layout or content as well?

**Comment by jpbernius** [comment]
I think they have a caching issue. I updated the link with index.html

**Comment by tessaRuckstuhl** [comment]
Perfect, works now! :) 
Could you please specify what we should review? I'm guessing the generated html and pdf concerning only formatting and layout?

**Comment by jpbernius** [comment]
For now, just that I did not delete anything when converting this.
If the PDF is not satisfying, we can also disable it for now. I just briefly looked at the PDF.

(Also, in one meeting yesterday we talked about adding documentation, so this would be a notification that we have a nicer system for this now.)

**Comment by tessaRuckstuhl** [comment]
Saw your comment just now, so had a look in the pdf, too.

These are the issues I was able to find:

**HTML**
- complete Contributor's Guide, Setup and Guided Tour is missing here

**PDF**
- Fig. 1 is comparatively small in my opinion
- Section "_Using adapters to support multiple VCS_": Figure order is mixed up here e.g. Fig. 3 is shown 2 pages later
- Section on "_Top-Level-Design_": The Fig. 3 (from section mentioned above) is placed in between bullet points, as well as the Fig. 4 referenced in this section
- (found a minor spelling error on page 9: Section Setup for Programming ... "Therefor**(e)**, a check is included with BambooBuildPlanService....")
- Section "_Setup for Programming Exercises with Bamboo, Bitbucket and Jira"_: The screenshots for Bitbucket are not at the correct place (moved down)

**Comment by stefanwaldhauser** [comment]
Website seems fine but formatting of pdf is broken

**Comment by florian-glombik** [comment]
PDF
- Fig. 5: Deployment Overview & Fig. 6: Data Model are not displayed properly
- the last picture on page 13 has no description (the next picture with a description is on page 30) - is that intentional?

**Comment by jpbernius** [comment]
OK, I suggest we disable the PDF for now and stick with the website?

**Comment by tessaRuckstuhl** [comment]
Depends on whether you want to use your time for fixing the pdf, I guess ;). The website seems to be sufficient in my opinion though!

**Comment by tiffca** [comment]
Hi @tessaRuckstuhl , @stefanwaldhauser, if the review is done from interactivelearning20 side, do we need to formally "Add your review"? (I see a green button at the top). I believe this way it marks the pull request as reviewed by our team, and hopefully then it does not show in the filtered pull requests as "awaiting review from you". I recently learned about this so maybe my understanding is incorrect.

**Pull request merged**
