### PR TITLE
`Notifications`: Allow users to hide outdated notifications

### PR DESCRIPTION
**Pull request by Malyuk-A**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
The notification sidebar collects every single notification a user has ever received, the large majority of notifications lose their importance after a couple of days, thus they are no longer of any use to the users. (Besides critical notifications).
E.g.
image

This PR adds a button to this sidebar that lets the user archive/hide the currently displayed notifications.
If no notifications are displayed the user can click on the button to display all saved notifications again (i.e. a toggle)´

See video:

https://user-images.githubusercontent.com/65814168/144606409-9aa2d39f-2b4c-462c-bfdd-abfa68f166c2.mp4

### Description
I added a new property to the jhi_user table where a user can save a specific time. This time will be used to filter the notifications that are displayed in the sidebar. The filter itself is done in a SQL statement (i.e. DB layer) for better performance.
If this value is null then all notifications will be displayed/loaded.

My code changes follow the already established last_notification_read property/column in jhi_user.

### Steps for Testing
Follow the video (I think it is self-explanatory) (Play around with the new buttons (try to also change your notification settings). 

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
- notification-sidebar.component ~ 90%  I also replaced the sinon with a jest implementation (that follows our docs)
- NotificationResource ~ 100% _(97%)_
- notification.service.spec.ts added new tests for new REST call (and old one for lastNotificationRead)
- UserResource -> added adequate tests to UserBambooBitbuckerJiraIntegrationTest & UserJenkinsGitlabIntegrationTest

I do not understand why Codacy claims, that I add ~90+ code duplications. I added completely new things or strictly followed similar very slimm/small implementations that were used for the "last notification read" property.

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Works as expected

**Review by Hialus — APPROVED** [review]
Tested in testing session on TS1.
Works as expected and code changes also look good to me. 👍🏻

**Review by julian-christl — APPROVED** [review]
Tested on TS1, works

**Review by daniels98it — APPROVED** [review]
Tested on TS1 and works good 👍

**Review by filip-gregurevic — APPROVED** [review]
Code changes look good to me 🚀

**Review by argertboja — APPROVED** [review]
Everything works as expected on TS1 👍🏼 

Well done @Malyuk-A 🙂

**Pull request merged**
