### PR TITLE
[Bugfix] Change tooltip placement of jhi-help-icon to auto in team creation/import modal

### PR DESCRIPTION
**Pull request by lschlesinger**
### Checklist
- [x] I tested *all* changes locally
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Solves issue #4029 where the position of the tooltip was fixed to right as `placement` property of the `jhi-help-icon` components. No tooltips were visible in the modals of importing or creating a team for a team exercise. I changed the value of the property to "auto", the tooltips are now shown properly.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Management, find or create a team exercise where there are not teams yet
3. Click on the `teams` button on the detail page of this exercise to be navigated to the teams page of that exercise, you can there choose of importing or creating a team. both option open a modal where the tooltips for the help icons are fixed -> should look like in the screenshot below.

### Review Progress

- Code Review
  - [x] Review 1
  - [x] Review 2
- Manual Tests
  - [x] Test 1
  - [x] Test 2

### Screenshots

it should no look like this:

https://user-images.githubusercontent.com/41366522/134814830-1e47ba09-c829-4540-84f1-9eb33c1e6d00.mov

### CODE REVIEW

**Review by Malyuk-A — APPROVED** [review]
Tested on TS2. Works as described 👍 (code is good as well 😄)

**Review by Olimbia23 — APPROVED** [review]
Nice work @lschlesinger
Code changes look fine. Approve 👍

**Review by ndricimrr — APPROVED** [review]
Tested locally. Worked well 👍

**Review by MerlinMehmed — APPROVED** [review]
Tested on TS1, works as expected

**Pull request merged**
