### PR TITLE
`Assessment`: Make the review of example submission optional for instructors

### PR DESCRIPTION
**Pull request by valeriebucher**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

If an instructor quickly needs to access the exercise dashboard to help a tutor, he shouldn’t need to check the example submissions, but it still should be an option to do it.

### Description

The instructor can already view and access the student’s submissions, complaints or „more feedback requests“ without having to go through example submissions, which sometimes takes some time to get the right assessments.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Tutor
- 1 Text or Modeling Exercise with an example submission to read or to assess

1. Navigate to the exercise dashboard of the text or modeling exercise.
2. Click the button `Start participating in the exercise`
3. a. _For Instructor:_ Check that the example submission is optional and you have access to student's submissions, complaints or „more feedback requests“
b. _For Tutor:_ Check that the example submission needs to be done to start an assessment. 

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

**View for instructors after clicking on `Start participating in the exercise`**
**Old version:** 

Vorher Optional

**New version:**

Nachher Optional

### CODE REVIEW

**Review by ole-ve — APPROVED** [review]
Tested on TS1. Works as described.
Code changes also look reasonable to me 👍

**Review by baranimo7 — APPROVED** [review]
Tested on ts2. Review process of example submission works as described.

**Review by willergeorg — APPROVED** [review]
Tested on TS2. Worked as expected. Code changes are fine for me as well.

**Review by Bofan-Zhu — APPROVED** [review]
Tested on ts2. Changes looked fine to me 👍

**Review by jpbernius — APPROVED** [review]

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on TS2, works as expected.

**Pull request merged**
