### PR TITLE
`Exam mode`: Update student documentation

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Since we made some minor changes in the exam sidebar and added "Exercise save" button, some of the screenshots in the documentation as well as on artemis features page remained outdated.

### Description

I updated exam documentation with the latest screenshots.

### Steps for Testing

Prerequisites:
1 Student

1. Navigate to [exam documentation](https://artemis-platform--9625.org.readthedocs.build/en/9625/user/exams/students_guide.html#participating-in-the-artemis-online-exam) and verify that screenshots look up-to-date.
2. Login Artemis
3. Navigate to the URL: https://artemis-testX.artemis.cit.tum.de/features/students and https://artemis-testX.artemis.cit.tum.de/features/instructors, where X is the current test server number
(e.g. if you deploy on TS3, you need to navigate to https://artemis-test3.artemis.cit.tum.de/features/students)
4. Verify that screenshots look consistent.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Added video links for enhanced guidance on accessing and participating in exams.
	- Expanded instructions on saving changes during exercises, clarifying options for different exercise types.

- **Documentation**
	- Updated the student guide to improve clarity and usability for exam preparation.

### CODE REVIEW

**Review by EneaGore — APPROVED** [review]
Changes lgtm and reflect on TS3. Out of the scope of this PR, but i find the center-aligned text a bit tiresome to read.

**Review by SimonEntholzer — APPROVED** [review]
Nice UI updates, new docs lgtm

**Review by eceeeren — APPROVED** [review]
Changes LGTM

**Comment by Fallthunderclap** [comment]
I tested according to the steps and everything worked as expected.

**Review by magkue — APPROVED** [review]
LGTM

**Review by HawKhiem — APPROVED** [review]
LGTM

**Review by krusche — APPROVED** [review]

**Pull request merged**
