### PR TITLE
[Hotfix] Display View Assessment button also after the assessment due date

### PR DESCRIPTION
**Pull request by fde312**
### Checklist
- [x] I tested *all* changes and *all* related features locally
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

The assessment view button was not displayed anymore after the assessment due date has passed.

### Description

- Removed check for assessment due date, as the button should be displayed disregarding the assessment due date

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a programming exercise with manual assessment and assessment due date and participate and assess or use exercise with participations and manual assessments and add a assessment due date 
4. Check that in the exercise scores view the button is displayed also after the assessment due date

### Test Coverage

Nothing changed

### Screenshots

image

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested on ts3. Everything works

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts3, works flawless.

**Review by valeriebucher — APPROVED** [review]
Looks good! everything worked on ts1

**Review by simonzilker — APPROVED** [review]
Works as intended on ts1!

**Review by marvinchimeka — APPROVED** [review]
tested the functionality on ts1. approve

**Review by FrankeLukas — APPROVED** [review]
Code changes lgtm, although personally I'd remove the `=== true` from `progEx.isAtLeastTutor === true`.

**Review by JannisBittlmayer — APPROVED** [review]
Tested on TS1, works as intended.

**Review by DenizShabani — APPROVED** [review]
Functionality works as intended!

**Review by EneaGore — APPROVED** [review]
Works as intented.

**Review by tiffca — APPROVED** [review]
Confirmed view assessment works after the due date. Nice change!

**Review by FlorianStang — APPROVED** [review]
Tested assessment worked after due date.

**Review by FuchsDominik — APPROVED** [review]
Logical code changes. === true is a matter of taste but since this is how it was before thats fine i guess, up to you :)

**Review by sebastiantpeter — APPROVED** [review]
Worked as expected on ts1.

**Review by krusche — APPROVED** [review]

**Pull request merged**
