### PR TITLE
`Adaptive learning`: Allow instructors to participate in learning paths

### PR DESCRIPTION
**Pull request by MaximilianAnzinger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

When navigating to the learning path participation view as an instructor, the server throws a forbidden access error.

### Description

Allow all users that are at least a student in the course to access the participation view.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with at least one Competency linked at least one lecture (e.g. https://artemis-test1.artemis.cit.tum.de/courses/24/exercises)

1. Log in to Artemis
2. Navigate to Course (e.g. https://artemis-test1.artemis.cit.tum.de/courses/24/exercises)
3. Click on the Learning Path tab
4. You should see no alerts (Access Forbidden)

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [LearningPathResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5752/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/LearningPathResource.html) | 95% | ✅ |

### CODE REVIEW

**Comment by MaximilianJG** [comment]
Worked as expected. I can access the competencies tab without receiving access forbidden alerts.
Screenshot 2023-11-20 at 13 52 34

**Review by AntonGeTUM — APPROVED** [review]
Manually tested, works as described

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts11. Worked as expected

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts11. Works as expected!

**Review by LenaKahle — APPROVED** [review]
Tested on ts11, approve.

**Review by georgyia — APPROVED** [review]
manually tested, works as expected

**Review by lennart-keller — APPROVED** [review]
Code lgtm

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by jakubriegel — APPROVED** [review]
Code LGTM

**Pull request merged**
