### PR TITLE
[Exam] Date validation for create & update

### PR DESCRIPTION
**Pull request by filip-gregurevic**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

The visible, start and due date for an exam are not mandatory and can be set to values that don't make sense.

### Description

The visible, start and due date for an exam are now mandatory and must be in ascending order.

### Steps for Testing

1. Log in to Artemis
2. Navigate to the exam overview
3. Create a new exam
4. Check that the visible, start and due date are mandatory and have to be in ascending order
5. Check the same for updating an exam

### CODE REVIEW

**Comment by Alexanderkrp** [comment]
I wasn't able to create an exam, even tho I did everything in ascending order. Also, I expected the exclamation mark to explain why it is still maked as red. 

image

**Comment by filip-gregurevic** [comment]
> I wasn't able to create an exam, even tho I did everything in ascending order. Also, I expected the exclamation mark to explain why it is still maked as red.

Did you also set the visible date in the future? I cannot be in the past. Maybe that was preventing you from creating exams.

**Comment by filip-gregurevic** [comment]
> Code is okay, everything working as intended, checked every possible permutation (at least I think I did ^^).
> Just one thing:
> [Screenshot from Gyazo](https://gyazo.com/0f6e0b6f5e0d515f4861b066353fe345)
> Even though I know that I have to click on the left to select a date I automatically click on the icon on the right. Firstly it's red, secondly it's on the right side. I think it's too confusing.
> 
> Consider remove the icon there, I think the red border is enough to represent it as an error.
> 
> I request changes for now, if you don't want to change this, I'll approve just let me know.

Thank you for testing. That is the default look of the component when it is in the _invalid_  state. I agree with you that it is not optimal and could also say what is wrong, but I think this is something for a follow-up PR.

**Comment by Varnika-Tyagi** [comment]
Works as intended on test server. Good job!
PR1764

**Comment by julian-christl** [comment]
> > Code is okay, everything working as intended, checked every possible permutation (at least I think I did ^^).
> > Just one thing:
> > [Screenshot from Gyazo](https://gyazo.com/0f6e0b6f5e0d515f4861b066353fe345)
> > Even though I know that I have to click on the left to select a date I automatically click on the icon on the right. Firstly it's red, secondly it's on the right side. I think it's too confusing.
> > Consider remove the icon there, I think the red border is enough to represent it as an error.
> > I request changes for now, if you don't want to change this, I'll approve just let me know.
> 
> Thank you for testing. That is the default look of the component when it is in the _invalid_ state. I agree with you that it is not optimal and could also say what is wrong, but I think this is something for a follow-up PR.

How do you handle "followup PRs"? Should I create a new issue or do you handle such internally?

**Pull request merged**
