### PR TITLE
`Development`: Add git commit short ID to the startup information box

### PR DESCRIPTION
**Pull request by TheZoker**
#### General

- [x] This is a small issue that I tested locally
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.

### Motivation and Context

At the moment (especially for development environments) it is hard to say. which version of Artemis is currently running (or used for CI). 

### Description
As discussed in the deployment working group, we want to add a new information in the startup box, that currently looks like this:
```
----------------------------------------------------------
        'Artemis' is running! Access URLs:
        Local:      http://localhost:8080/
        External:   http://172.19.0.3:8080/
        Profiles:   [dev, bamboo, bitbucket, jira, artemis]
        Version:    5.9.9
        External:   141081
----------------------------------------------------------
```
To uniquely identify the current running version, the best value for that is the current git id, that represents the last commit. 
In order to get this id, we use the `com.gorylenko.gradle-git-properties` as suggested by the spring documentation:
https://docs.spring.io/spring-boot/docs/1.4.1.RELEASE/reference/html/howto-build.html#howto-git-info

### Steps for Testing

1. Build artemis with `./gradlew -Pprod -Pwar clean bootWar`
2. Start artemis and wait for the information box 
3. Compare the displayed git id with the current git id (should be equal)

Alternative you could
1. Look at this log file:
https://bamboo.ase.in.tum.de/download/ARTEMIS-AETG836-DA/build_logs/ARTEMIS-AETG836-DA-2.log
2. Then search for `Git Commit:`.
3. You will see the commit id:
image
4. Which is the same as the commit ID on github:
image

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### CODE REVIEW

**Review by 4ludwig4 — DISMISSED** [review]
Code looks good from my not very Java Expert point of view. Tested it with a different git commit and it works. Also has the same short commit format as Github.

**Review by manuelmanso — DISMISSED** [review]
Code looks good. It's also following the spring docs, even though it's an older version. I tried looking for the same information for more recent spring versions but couldn't find anything.

**Review by Mikael31 — DISMISSED** [review]
Compared the id's. They are the same. Code looks also good.

**Review by bassner — DISMISSED** [review]
Worked on my machine! Code looks good 👍

**Review by sleiss — DISMISSED** [review]
Tested it, worked locally!

**Review by krusche — APPROVED** [review]

**Comment by krusche** [comment]
In a follow-up it would be nice if you could also show the branch

**Pull request merged**
