### PR TITLE
Set default value such that seconds and milliseconds are 0

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

Closes: #1649

As: https://github.com/ls1intum/Artemis/pull/2431 was closed due inactivity I thought i can fix it quickly myself

### Description

Just one line: 58109f12af87a05825f7f16be3927e736568f888

How does it work?
https://daniel-projects.firebaseapp.com/owlng/date-time-picker#starting-view
`The moment that the picker opens to is determined by first checking if any date or time is currently selected, if so it will open to the month or year containing that date and timer is set to that moment. Otherwise it will open to the month or year containing today's date and set to current time. This behavior can be overridden by using the [startAt] property of owl-date-time. In this case the calendar will open to the month or year containing the startAt date and timer is set to startAt time.`
The trick is to just set startAt to the current moment BUT without seconds and milliseconds

### Steps for Testing

Just try the date time picker at any point in Artemis, and select a date and see that seconds are set to 0

### Test Coverage

No changes

### Screenshots

image

### CODE REVIEW

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts3, code looks good. Well done! 👍

**Review by simonzilker — APPROVED** [review]
Works as intended on ts3!

**Review by airelawaleria — APPROVED** [review]
Tested with @JohannesWeiss and @simonzilker. Works fine

**Review by marvinchimeka — APPROVED** [review]
Tested on ts3. Approve

**Review by FrankeLukas — APPROVED** [review]
Confirmed that the seconds are `00`.

**Review by FuchsDominik — APPROVED** [review]
I like the change and works as expected 👍

**Review by DenizShabani — APPROVED** [review]
Works as intended!

**Review by tiffca — APPROVED** [review]
Tested in mode/text/quiz exercises and in system notifications and it all worked as expected. I had to refresh the browser for the change to take effect.

**Review by krusche — APPROVED** [review]

**Pull request merged**
