### PR TITLE
`Iris`: Fix an issue with vertical scroll position reset

### PR DESCRIPTION
**Pull request by yassinsws**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
When opening and using Iris in a long programming exercise, the vertical scroll position is reset multiple time to the start.
This can be very annoying.

To Reproduce
Open a programming exercise, in which you can scroll down far enough
Scroll down
Open Iris and ask some questions
Experience how the scroll position is reset
Expected behavior
The scroll position remains unchanged.
### Description

The bug was produced by "cdk-global-scrollblock" used in the method toggleScrollLock. Specifically by the field overflow-y. So I overrode that field, and changed its value to hidden.

### CODE REVIEW

**Review by RY997 — APPROVED** [review]
Worked as expected

**Review by LenaKahle — APPROVED** [review]
Approve, tested on TS9. Thanks for fixing the bug!

**Review by AntonGeTUM — APPROVED** [review]
Tested on ts9, scroll position doesn't reset anymore

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts9. Worked as expected!

**Review by MaximilianJG — APPROVED** [review]
Tested on Ts9. Worked as expected. Scrolling position does not reset.

**Pull request merged**
