### PR TITLE
`General`: Remove instructor's course and exercise dashboard

### PR DESCRIPTION
**Pull request by Olimbia23**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] *This is a small issue that I tested locally and was confirmed by another developer on a test server
- [ ] *Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
#### Server
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] *I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] *I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] *I implemented the changes with a good performance and prevented too many database calls.
- [ ] *I documented the Java code using JavaDoc style.
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] *I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-testing/).
- [ ] *I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] *I documented the TypeScript code using JSDoc style.
- [ ] *I added multiple screenshots/screencasts of my UI changes.
- [ ] *I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

[ ]* - not needed

### Motivation and Context

Instructor course and exercise dashboards don't add much new information in comparison with course and exercise assessment dashboards. This PR removes instructor course and exercise dashboards as well as all code related to it that is no longer needed.

### Description

Removed the components on the client side, server endpoints that were providing data for the component, tests, adjusted the translation strings as well as file imports that were inside the instructor dashboard folder, but are moved to the dashboard root folder.

### Steps for Testing

1. Log in to Artemis as instructor
2. Navigate to Course Administration
3. Instructor course dashboard button should not be there and Artemis should function as before without any issues.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by imstreetspirit — DISMISSED** [review]
tested on ts2. Instructor Dashboard button removed from course overview and course management. checked Assessment/exercise dashboard could not spot any issue. code changes seems reasonable.

**Review by MerlinMehmed — APPROVED** [review]
Retested on TS1 and didn't find issues. Comments got addressed - the button is removed from course management and the missing translation is added.
Code changes also look reasonable to me

**Review by lschlesinger — APPROVED** [review]
Looks good now 👍

**Review by imstreetspirit — APPROVED** [review]
re-approve, issue got addressed!

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Behavior seems as usual to me.

**Pull request merged**
