### PR TITLE
Fix Feedback Editor Alignment Issue

### LINKED ISSUE #3551: Text Exercise Text Block UI Alignment Broken
#### To Reproduce

1. Open any _TextExercise_ submission : i.e.: [Here](https://artemistest.ase.in.tum.de/course-management/482/text-exercises/7729/submissions/437966/assessment)
2. You should see mis-alignment of the ui elements of the text feedback editor

#### Expected behavior

Elemenets should be properly aligned.

#### Screenshots

b

### Environment

<details><pre>
</pre></details>

#### Additional context

- Should be related to CSS changes 
- Not related to small screen width, expanding the window width will not fix the issue.

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

### PR DESCRIPTION
**Pull request by ndricimrr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Fixes #3551 

### Description

Fixes alignment issues

### Steps for Testing

1. Log in to Artemis
2. Open a Text Submission to grade
2. Check the Feedback editor upon clicking on a block. 

### Screenshots

final

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS2, looks better now :+1:

**Review by coolchock — APPROVED** [review]
tested on ts2, looks good :+1:

**Review by MerlinMehmed — APPROVED** [review]
Tested on TS2. Looks good.

**Review by Malyuk-A — APPROVED** [review]
Works

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
