### PR TITLE
`Development`: Fix duplicated task error in Hestia

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Fixes the imminent issue described in #7736

### Description

A simple `.distinct()` call suffices to fix this issue

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Create a programming exercise with a duplicated task (2 tasks with the same name and test cases)
2. Participate in the exercise
3. Do one submission
4. Wait for the result to come back
5. No error

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
#### Manual Tests
- [x] Test 1

### Test Coverage

Effectively unchanged

### Screenshots

N/A

### CODE REVIEW

**Review by georgyia — CHANGES_REQUESTED** [review]
Tested manually on ts2. I did everything as you provided, however, I have got an internal error. It was shown at Artemis. Nevertheless, that actually worked. 
Снимок экрана 2023-12-06 в 16 15 30

**Comment by Hialus** [comment]
> Tested manually on ts2. I did everything as you provided, however, I have got an internal error. It was shown at Artemis. Nevertheless, that actually worked. Снимок экрана 2023-12-06 в 16 15 30

I am unable to reproduce this on TS2 with this PR deployed. Can you give me the URL of the specific exercise where this happened?

**Review by AntonGeTUM — COMMENTED** [review]
Tested on ts11, works as described

**Review by vinceclifford — APPROVED** [review]
Works as expected, tested on TS11

**Pull request merged**
