### PR TITLE
[Feature] Registration/Login via Shibboleth/SAML

### PR DESCRIPTION
**Pull request by dfuchss**
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
We are currently evaluating Artemis and have determined that for our purposes, integrating Shibboleth for student registration and/or login would be useful. Shibboleth would ensure that only authorized users can log in.  In addition, this would allow us to access student registration numbers directly.

The planned workflow:
* An user clicks on something like "Login via Shibboleth"
* The user will be redirected to the Shibboleth Login Mask and enters his/her credentials
* The user will be redirected to Artemis and is authenticated
* If this account is a newly created account, an E-Mail containing a password-reset link for the current user will be sent. (The body of the email says something like "please click on the link to get your app password for gitlab / artemis").

Therefore, we can use the SAML/Shibboleth information for account creation / login to artemis and use the integrated user management to create passwords for the connected services (in our case: gitlab)

This PR is related to #2377 
If you have any questions, just leave a comment here :)
Currently, @LDAP is working on the implementation of this idea.

### CODE REVIEW

**Comment by LDAP** [comment]
### Description
This feature allows users to Login via SAML2 (Shibboleth) using [Spring Security SAML2 Implementation](https://docs.spring.io/spring-security/site/docs/5.2.8.RELEASE/reference/html/saml2.html). 

- The feature can be completely enabled/disabled via the `saml2` spring profile
- Configuration is dynamic and can be found in `application-saml2.yml`. 
- Multiple IDPs are supported. In this case an auto-generated login page with an IDP selection can be found at /login

To accomplish this a separated security filter chain is added to Artemis. 
Security

- Requests to /saml2/** and /login/** are processed by the new filter chain.
- There is currently an upstream limitation which allows an auto-generated login page only at /login. In the future a custom login page could be used.
- SAML2-authenticated clients can request their JWTToken at `/api/saml2`

Client flow is as follows:
client

### Steps for Testing
- Setup an SAML2 Identity Provider.
  - The configuration for LDAP/docker-compose-artemis would be
```YAML
saml2:
    username-pattern: 'saml2-{first_name}_{last_name}'
    first-name-pattern: '{first_name}'
    last-name-pattern: '{last_name}'
    email-pattern: '{email}'
    registration-number-pattern: '{uid}'
    identity-providers:
        - metadata: http://saml:8080/simplesaml/saml2/idp/metadata.php
          registration-id: testidp
          entity-id: artemis
```
- Enable `saml2` profile
- Configure the IDP and Artemis in application-saml2.yml
- (Reverse proxy: Forward /saml2/** and /login/**)
- Log in with SAML2 (user are created if necessary)

### Test Coverage
- tbd.

### Screenshots
Login

### Limitations:
- GitLab does support SAML2 but when a user logs into GitLab first, Artemis fails to alter the user correctly
Proposed solution: 
  - SAML2 is only enabled at Artemis. 
  - On the first Login the User receives a mail to set the Local Artemis and GitLab password (using the password-reset function).
  - To achieve this, the password-reset API-calls must be enabled not only when registration is enabled but also when SAML2 is enabled. 
  - The timeout of 24 hours is too low, students may set the password later
  - @krusche This would involve changes to the existing codebase. Should I alter the password reset function or implement SAML2 specific routines? Is there something I may have missed?

**Comment by b-fein** [comment]
Thanks for working on that feature! It is one we really want to use as well.
I created #2377 with Artemis and Gitlab both connecting to the same SAML-provider in mind as that would result in a very comfortable login for students and remove exactly this problem of ‘I have not received a email to reset my password’/forgotten passwords/etc.

In what way does Artemis fail to alter a user? Assuming Gitlab is also connected to the same SAML-provider at least the username and email should be the same. I know that Artemis also tries to sync passwords. If users login to both services via SAML, there should be no need for Artmis to change any of that information in Gitlab. Would it be enough to just deny Artemis to change information of existing users in Gitlab when using this feature?

In that scenario there are two options when a user logs into Artemis for the first time:
- The user does not exist in Gitlab: Artemis can create a user with the known email in Gitlab and set a random password. When the user logs into Gitlab the first time via SAML the password from that provider is used and the one Artemis chose is completely ignored. As the email is identical, Gitlab knows it is the same user. I have tested a setup like this recently.
- A user with the same username+email already exists in Gitlab: do not change it and leave as is.

**Comment by LDAP** [comment]
> 
> 
> Thanks for working on that feature! It is one we really want to use as well. I have a few questions about the limitations you mentioned.
> I created #2377 with Artemis and Gitlab both connecting to the same SAML-provider in mind as that would result in a very comfortable login for students and remove exactly this problem of ‘I have not received a email to reset my password’/forgotten passwords/etc.
> 
> In what way does Artemis fail to alter a user? Assuming Gitlab is also connected to the same SAML-provider at least the username and email should be the same. I know that Artemis also tries to sync passwords. If users login to both services via SAML, there should be no need for Artemis to change any of that information in Gitlab. Would it be enough to just disable Artemis changing information of existing users in Gitlab when using this feature?
> 
> In that scenario there are two options when a user logs into Artemis for the first time:
> 
>     - The user does not exist in Gitlab: Artemis can create a user with the known email in Gitlab and set a random password. When the user logs into Gitlab the first time via SAML the password from that provider is used and the one Artemis chose is completely ignored and users are not prompted to change their password. As the email is identical, Gitlab knows it is the same user (when `gitlab_rails['omniauth_auto_link_saml_user'] = true` is set in the configuration). I have tested a setup like this recently.
> 
>     - A user with the same username+email already exists in Gitlab: do not change it and leave as is.

There are some issues to consider:
- GitLab auto links user by email, but Artemis uses usernames. To make this work one must ensure that GitLab uses the same username. If not, a user who does first log into GitLab creates a new user mapped to his mail address, and Artemis creates another user with the same mail address (or fails - I did not test this)
- Artemis creates users with special permissions/restrictions
```java
 new org.gitlab4j.api.models.User().withEmail(user.getEmail()).withUsername(user.getLogin()).withName(user.getName()).withCanCreateGroup(false).withCanCreateProject(false).withSkipConfirmation(true);
```
- Students may want to use Git over https using their GitLab passwords. It may hard to set up SSH Keys for students not familiar with Git.

In any case, I would also implement an option to disable/enable the "set Artemis/GitLab password" mail. This allows adapting the SAML2 feature to your needs.

**Comment by b-fein** [comment]
Thanks for clarifying!

> Gitlab auto links user by email, but Artemis uses usernames. To make this work one must ensure that Gitlab uses the same username.

Gitlab can also retrieve the username via SAML. So this should only be an issue if users are allowed to manually register in Gitlab via a regular login. If this is completely blocked and all users are either created by Artemis or via the same SAML-provider, it should be fine, I assume.

> Artemis creates users with special permissions/restrictions.

I think those can be set as default in the Gitlab-configuration for all new users, so if this ends up being the only remaining issue there is an alternative to it.

> Students may want to use Git over https using their Gitlab passwords.

That is a very good point I missed.
To be able to change their Gitlab password they have to know the old one (or use the ‘forgot my password’ in Gitlab). Receiving an email from Artemis directly after signing up to please set a password like in your proposed solution is then probably easier for students. Then only the ones wanting to set a SSH-key have to actively use Gitlab to set that up, all others can get started without ever touching Gitlab.
For this to work properly for SAML-connected Gitlab, though, Artemis has to still be able to modify some user properties (i.e. password), which is exactly the problem you initially described.

**Comment by dfuchss** [comment]
Moved PR to #3002 . Now testing shall be possible for the future! Closing.

**Pull request closed without merging**
