### PR TITLE
`Exam mode`: Add progress monitoring for exercise start preparation

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

The "preparse exercise start" action that can be applied on all student exams to create participations before the exercise starts can take a long time for large courses. Right now, it's implemented so that the HTTP request doesn't return until it's finished and it's likely that this takes longer than the HTTP timeout. Also, the user does not have any idea how long this will take, and how much is already done.

### Description

This PR adds a progress bar that updates live via the websocket to the student exams view that indicates the progress of the exercise preparation process, including a calculated estimation of the remaining time.

The initial request to run this process will only start it and then return. The status is distributed to everyone who is currently on that student exam page (it has authorization checks in place as well). Additionally, the current status is stored in a cache so if a new user joins the site or the current user reloads, the status can be fetched and displayed immediately without waiting for the next WS update as otherwise the user could think that the process is not running; additionally, the cache allows to show a completed process for a while after it finished as well so the users know there was one in the short past.

### Steps for Testing

Prerequisites:
- 1-2 Instructor(s)
- 1 Exam with a lot of registered students so the preparation takes long enough to observe it

1. Go to the student exams view of the exam
2. If not already done, generate student exams
3. Start the exercise preparation process by clicking the correct button
4. Observe the process in the progress bar. 
5. Verify that it survives reloads, and that it displays for another instructor on the same page as well

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| student-exams.component.ts | 73% | 93% |
| exam-management.service.ts | 73% | 94% |
| ExamService.java | 82% | 96% |
| StudentExamService.java | 76% | 88% |
| StudentExamResource.java | 77% | 92% |
| WebsocketMessagingService.java | 100% | 95% |
| WebsocketConfiguration.TopicSubscriptionInterceptor | 68% | 75% |

### Screenshots

https://user-images.githubusercontent.com/23171488/181344452-33b7fe9f-750b-43b5-997a-bf97f183b91a.mov

### CODE REVIEW

**Review by maximiliansoelch — APPROVED** [review]
Tested during testing session, works as expected.
Code LGTM 👍

**Review by Dominik-Weinzierl — APPROVED** [review]
Works good and looks good :+1:

**Review by Dominik-Weinzierl — APPROVED** [review]
Looks still good after merge :+1:

**Review by sleiss — APPROVED** [review]
Tested it on Staging and checked the server code, looks fine to me!

**Pull request merged**
