### PR TITLE
`Development`: Remove 'tracker' from websocket path

### PR DESCRIPTION
**Pull request by krusche**
We do not really track something, so the path name is misleading (it was part of the generated Jhipster template)

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Steps for Testing
1. Log in to Artemis
2. Check that web socket messages are sent normally (e.g. results for programming exercises)
3. Check in the browser console network tab if the web socket messages are sent normally (see screenshot below)
4. Check that logout disconnects the web socket messages
5. Check that login connects web sockets to the server
6. Check that after a network outage (turn off your Internet, wait up to 20s until the disconnect icon appears and then reconnect and wait until the disconnect icon disappears) the web sockets automatically reconnect

image

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Comment by krusche** [comment]
I tested again after the latest changes and everything is working well 👍

**Review by rriyaldhi — APPROVED** [review]
Tested on TS0 and works as expected.

**Review by simon-hng — APPROVED** [review]
Tested on TS1 and works as described

**Comment by just-max** [comment]
Oh, so this is what broke the elevator music plugin ;)

**Pull request merged**
