### PR TITLE
Plagiarism Checks with Progress Feedback

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

The progress of the "check plagiarism" action may be lengthy. Currently, the user only sees a spinner.

### Description

This PR extends that and adds some progress messages to notify the current state of the plagiarism detection progress so that the user can get more information. It also removes a bit of duplicated code.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create exercises of types programming, modeling, and text
4. Participate in them was different users and try to submit the same things to trigger the plagiarism
5. Navigate to the exercise detail page and click on "check plagiarism"
6. Depending on the amount of participation, you should be able to receive progress messages.

### Test Coverage

ModelingPlagiarismDetectionService.java 94%
PlagiarismWebsocketService.java 85%
ProgrammingPlagiarismDetectionService.java 80%
TextPlagiarismDetectionService.java 92%
ProgrammingExerciseExportService.java 67%
ProgrammingExerciseResource.java 91%
plagiarism-inspector.component.ts 87.93%
### Screenshots

Programming exercises:

Text Exercises:

### CODE REVIEW

**Review by KiraNickel — APPROVED** [review]
Tested on ts3. Works as described 👍🏼 
(The only thing I noticed was that for absolutely identical text submissions, the plagiarism result was 96.46% and I'm not sure why it isn't 100%)

**Comment by ivanchimeno** [comment]
> Tested on ts3. Works as described 👍🏼
> (The only thing I noticed was that for absolutely identical text submissions, the plagiarism result was 96.46% and I'm not sure why it isn't 100%)

Yeah I'm not too familiar with the plagiarism feature myself :D

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Worked as expected.

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 2. Everything worked as expected.

**Review by cremertim — APPROVED** [review]
tested on ts2. Worked as expected

**Review by DanielKainz — APPROVED** [review]
Tested on TS1 and everything works as intended :-)
I submitted the same thing (programming exercise and modelling exercise) for different users and received 100.00%, but for the same answers in a text exercise is received just 86%.

**Pull request merged**
