### PR TITLE
`General`: Improve active students charts view

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
The UI of the active students chart offered hidden changes (e.g. arrows to navigate through periods) which did not work properly.

### Description
This PR streamlines unnecessary UI and adjusts the navigation feature so that it is possible to choose the period size and then use the arrows to navigate.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with Start Date set & Student Participations in the last weeks

1. Log in to Artemis
2. Navigate to Course Detail
3. Verify that the period buttons & navigation arrows work as intended and the data is displayed properly

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [course-management.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5879/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/manage/course-management.service.ts.html) | 87.44% | ✅ |
| [course-detail-line-chart.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5879/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/manage/detail/course-detail-line-chart.component.ts.html) | 94.82% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [CourseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5879/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/CourseResource.html) | 94% | ✅ |

### Screenshots
image

## Summary by CodeRabbit

- **Refactor**
	- Reorganized the HTML structure and adjusted layout classes in the `course-detail-line-chart.component.html`.
	- Removed styles and added a new style for buttons in the `course-detail-line-chart.component.scss`.
	- Changed the `displayedNumberOfWeeks` property and moved enum values to a new enum in the `course-detail-line-chart.component.ts`.
	- Expanded functionality and renamed a method in the `course-detail-line-chart.component.ts`.

- **Tests**
	- Added a new parameter in the `update` method call and a new test case for the `getStatisticsData` method in `course-management.service.spec.ts`.

- **Chores**
	- Modified the `baseUrl` property in the `cypress.config.ts` file.

### CODE REVIEW

**Review by AntonGeTUM — DISMISSED** [review]
Manually tested on TS11, works as expected

**Review by Ceiridge — APPROVED** [review]
Tested on ts3. Works as expected.
image
image

**Review by dearjasmina — APPROVED** [review]
code lgtm

**Review by RY997 — APPROVED** [review]
Code LGTM

**Review by georgyia — COMMENTED** [review]
manually tested on ts2, works as expected

**Review by georgyia — APPROVED** [review]
manually tested on ts2, works as expected

**Review by Ceiridge — APPROVED** [review]

**Review by xHadie — APPROVED** [review]
_Manually tested on TS2_Legacy_
Works as expected!

**Review by MaximilianJG — APPROVED** [review]
Manually tested on Ts2. Works as expected!
Screenshot 2023-12-19 at 18 56 32

**Review by RY997 — APPROVED** [review]

**Review by rabeatwork — APPROVED** [review]

**Review by reschandreas — APPROVED** [review]
overall code lgtm

**Review by laurenzfb — APPROVED** [review]
tested on ts4. works as expected

**Review by rstief — APPROVED** [review]
Tested on ts4 👍

**Review by Ceiridge — APPROVED** [review]

**Review by RY997 — APPROVED** [review]

**Pull request merged**
