### PR TITLE
`Programming exercises`: Do not collapse feedback if there is only one feedback group

### PR DESCRIPTION
**Pull request by simon-hng**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.

### Motivation and Context

When there is only one category available, the Feedback group should not hidden by default. This is a simple usability feature that saves students a single click

### Description

Adds a check for the amount of feedback groups. If there is only one group, set that groups open property to true

### Steps for Testing

Prerequisites:
- a student
- instructor
- an exercise e.g. (modeling, file submission are easy to test) 

1. Create a submission for the exercise 
2. Grade it afterwards as instructor - Only give positive feedback
3. When you check the feedback as student, the group content should be shown (see screenshot below).

### Screenshots

Default before:
image

Default now:
image

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code

**Review by timo07k — APPROVED** [review]
Works as expected. Tested on TS1.

**Review by PhilipWerz — APPROVED** [review]
Works as expected. Tested with mulitple exercises. Tested on TS1.

**Review by luisa1999 — APPROVED** [review]
Code looks fine for me

**Pull request merged**
