### PR TITLE
`Quiz exercises`: Fix multiple choice answer distribution layout in statistics

### LINKED ISSUE #4505: Broken layout for quiz statistics for multiple choice questions
### Describe the bug

One art of questions for Quizzes on Artemis is Multiple Choice questions. When checking the statistics of those questions, the layout on the left side is broken. It renders all possible answers and their markers (a, b, c, d), but not in the same line as it should. The bug is reproducible only on the Firefox browser (see attached screenshots). 

### To Reproduce

1. Go to 'Course Management' 
2. Click on course with the Quiz exercise that contains at least one Multiple Choice question (or create one)
3. Click on 'Exercises'
4. Click on 'Statistic' for the chosen Quiz
5. Switch to the statistic page of the Multiple Choice question
6. See an error

### Expected behavior

Marker and the text of a statement should be in one line in the layout, not broken in two. 

### Screenshots

mc_question_stats_wrong
mc_question_stats2_wrong

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

This PR fixes #4505 

### Description

I declared the list item content as flex container in order to align it with the list prefix

### Steps for Testing

Prerequisites:
- 1 Instructor
- A MC quiz with rather long answer options
- Firefox and another browser of your choice (e.g. Chrome, Edge, Safari, etc.)

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to the exercise overview of the associated course and click on the "Statistics" Button for the quiz
4. Change the view via the drop down menu below to the specific quiz question (below "Point distribution" and "Quiz statistic")
5. Inspect the left side of the view and check whether the list items are aligned with their list prefixes
6. Do the same for the other browser and check that the layout is comparable and not distorted as it was the case for Firefox before.

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Nothing changed
### Screenshots

You can find screenshots about the current situation in the corresponding issue. 
This is how it should look now:
image

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
Tested on TS1, works as expected.

**Review by baranimo7 — APPROVED** [review]
tested on ts2, changes work as expected.

**Review by Malyuk-A — APPROVED** [review]
> Do the same for the other browser and check that the layout is comparable and not distorted as it was the case for Firefox before.

I sadly do not use FireFox but I tested it for Chrome.
I noticed no issues and the code change looks good to me.

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on ts2, it work as expected.

**Review by Bofan-Zhu — APPROVED** [review]
Tested on ts2 with Firefox and Brave. Did not see any issues 👍

**Pull request merged**
