### PR TITLE
migrate programming exercise repo url and build plan id to participations

### PR DESCRIPTION
**Pull request by krusche**
### Checklist
- [x] I run `yarn run webpack:build:main`: the project builds without errors.
- [x] I run `yarn lint`: there project builds without code style warnings.
- [x] I removed unnecessary whitespace changes in all related files.
- [x] I updated the documentation and models.
- [x] ~I tested the changes and all related features on the test server https://artemistest.ase.in.tum.de.~
- [x] ~I added (end-to-end) test cases for the new functionality.~

### Motivation and Context
In the future we want to show the instructor how many test cases failed in the template project and how many passed in the solution project. 

### Description
Migrate baseRepositoryUrl and baseBuildPlanId to templateParticipation and solutionRepositoryUrl and solutionBuildPlanId to solutionParticipation.

**Please note:**
>Testing on the test server should only be done when the changes have been integrated into develop, because after the data migration, the programming exercises won't have certain attributes any more in the database which might lead to errors when version without these changes are deployed.

### Steps for Testing
1. Log in to ArTEMiS
2. Navigate to Course Administration
3. Navigate to Programming Exercises
4. Check if you still can see the repo url and build plan ids

### CODE REVIEW

**Comment by sleiss** [comment]
I've just added 2 commits that should handle most of the server-side part, however the edit-feature of the programming exercise is broke now, I'll look into it.

**Comment by sleiss** [comment]
I just checked it, the edit feature apparently was already broke before. Should we adress this in this PR or in a seperate one? @krusche

**Comment by krusche** [comment]
@sleiss what exactly is broken? edit programming exercises should work, in both cases, manual setup (i.e. link) and automatic setup (i.e. create)

We should definitely fix it in this pull request

**Comment by sleiss** [comment]
@krusche I'm sorry, editing seems to be fine (at least it was before, still have to test after the changes made in this PR).
However, when clicking on "View" first, then the "Edit" button (on the View-page) is broken.

**Comment by krusche** [comment]
Ok, I see. This should be easy to fix :) probably just a routing error

**Pull request merged**
