### PR TITLE
`Development`: Remove lifecycle hooks in learning path related components

### PR DESCRIPTION
**Pull request by JohannesWt**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

When using signals, lifecycle hooks are not needed anymore.

### Description

This PR removes the remaining lifecycle hooks of the learning path feature using signals and effects.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- at least 2 competencies
- at least 1 lecture unit and 1 programming exercise connected to a competency

1. Log in to Artemis
2. Navigate to Student learning path UI
3. Navigate between learning objects
4. navigate between learning objects using the navigation overview
5. basically check if everything still works as expected

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

unchanged

### Scweenshots

unchanged

## Summary by CodeRabbit

- **New Features**
  - Enhanced loading mechanisms for components, improving state management and responsiveness.
  
- **Bug Fixes**
  - Corrected the loading state checks to streamline user experience during data fetching.

- **Refactor**
  - Transitioned from traditional lifecycle hooks to reactive programming paradigms, improving maintainability and readability across components.

- **Tests**
  - Updated unit tests to reflect changes in method and property names, ensuring alignment with the refactored component logic.

### CODE REVIEW

**Review by Jan-Thurner — APPROVED** [review]
Tested on TS1, still works as expected.

**Review by pzdr7 — APPROVED** [review]
Code

**Review by florian-glombik — APPROVED** [review]
Tested on ts1, did not find issues, navigating from student view worked fine

**Review by SimonEntholzer — APPROVED** [review]
Code

**Review by sarpsahinalp — APPROVED** [review]
Code

**Review by rabeatwork — APPROVED** [review]

**Pull request merged**
