### PR TITLE
`Quiz exercises`: Fix short answer spot sequence number

### PR DESCRIPTION
**Pull request by rriyaldhi**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The sequence number of spots in short answer questions of the quiz exercise is not correctly assigned which can potentially create incorrect mappings. Furthermore, the sequence number is never decreased even though some spots are deleted.

https://user-images.githubusercontent.com/10885503/204467333-04536b7a-c00d-4971-adba-f09a02fb8938.mov

### Description

To prevent the issue, the next spot number is set to the highest spot number of current text in the editor.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course

1. Log in to Artemis
2. Navigate to Course Administration
3. Select the Course
4. Click Exercises
5. Create Quiz Exercise
6. Create Short Answer Question
7. Verify that the number sequence is assigned correctly when some spots are deleted.

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| short-answer-question-edit.component.ts | 70.32% | 94.42% |

### Screenshots

https://user-images.githubusercontent.com/10885503/204466456-eec70b4a-5516-49ea-8be7-717393c285b8.mov

### CODE REVIEW

**Review by LiaLism — DISMISSED** [review]
Short Answer Spots work. Tested on ts1.

**Review by minrows — APPROVED** [review]
Tested on ts1 during the testing session. LGTM 👍

**Review by TheZoker — APPROVED** [review]
Tested on TS1 and worked for me 👍

**Review by danielbode — APPROVED** [review]
It works. Tested on ts1.

**Review by sleiss — APPROVED** [review]
LGTM

**Review by akesfeden — APPROVED** [review]
Tested on TS1 during testing session, spot sequence number is always increased (even if previous numbers are deleted but author said this is intended). The fix seems to be working correctly.

**Comment by rriyaldhi** [comment]
> Tested on TS1 during testing session, spot sequence number is always increased (even if previous numbers are deleted but author said this is intended). The fix seems to be working correctly.

Hi, to make it clear. the sequence will be decreased only if the highest spots are deleted. This is the example screencast of such a scenario:

https://user-images.githubusercontent.com/10885503/205069745-ec93f8de-480a-4ed9-a089-e0f8ab42f83f.mov

**Pull request merged**
