### PR TITLE
`Discussion`: Replace answer popup with in-place message

### PR DESCRIPTION
**Pull request by canberkanar**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

While creating or editing answers to posts, users are provided with a pop-up modal where they can enter the answer body. Although the feature is functioning at the moment, users are losing their attention from the post itself when submitting an answer.

### Description

To let the user still see the post they are answering, we replace the post answer pop-up with container rendering. This way, while editing or creating a new answer, users are still able to see and interact with the post itself

Note that we leave post creation and editing as it is since there are multiple columns for posts versus answer posts. Also, each post consists of its own topic, so users do not need to see other posts while altering a post anyway.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Course with postings enabled 

1. Log in to Artemis
2. Navigate to the Discussions page of a course
3. Reply to a post and edit it
4. Make sure that the markdown editor is rendered without the pop-up.
6. Make sure that post creation and editing still works as before via the pop-up.
7. Go to PAGE_SECTION view for Discussions. (Navigate to a specific exercise or lecture)
8. Repeat the steps above on the discussion tab to the right.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| answer-post.component.ts | 100% | 100% |
| posting-create-edit-modal.directive.ts | 80% | 100% |
| answer-post-create-edit-modal.component.ts | 77.41% | 93.54% | 
| post-footer.component.ts | 88% | 100% |
| answer-post-header.component.ts | 81.81% | 100% |

### Screenshots

image
image
image
https://user-images.githubusercontent.com/67344158/170456887-7f5a6874-639a-44e1-940d-c1641e70293d.mp4

### CODE REVIEW

**Review by akesfeden — CHANGES_REQUESTED** [review]
Tested on TS5, functionality works as expected however, in dark mode the text is not readable.

image

**Review by akesfeden — APPROVED** [review]
My comment above seems like a CSS caching issue, the text is visible after a hard refresh on the same browser.

image

**Comment by canberkanar** [comment]
> 
I don't have any issues on ts5 at the moment. Maybe try refreshing the browser cache? 
image

**Review by xlieA — APPROVED** [review]
I tested on ts1. Everything works as described.

**Review by SimonPaul02 — APPROVED** [review]
Tested on TS 1, works as described

**Review by yuling-sun — APPROVED** [review]
Tested on TS1. Works as described.

**Review by TheTrueVester — APPROVED** [review]
Tested on ts1, worked as described

**Pull request merged**
