### PR TITLE
`Communication`: Add FAQ search bar

### PR DESCRIPTION
**Pull request by cremertim**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

I as a student want to be able to search for desired FAQ's based on the text of the FAQ

### Description

Added a search bar to the Course Overview so a student can search via Text for the FAQ

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Course with active FAQ

1. Log in to Artemis
2. Navigate to Course Overview
3. Go to FAQ section
4. See search bar and input a searchText
5. Verifiy it only shows the FAQ's with ALL inputs tokens of the user
6. Filter for category
7. Verify only FAQ with category and search are displayed

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| faq-service.ts | 98.3% | ✅              |
| course-faq.component.ts | 98.14% | ✅              |
| faq.component.ts | 95.83% | ✅              |

### Screenshots

image

Discussion:

Please give me feedback in the comments how you would expect the search functionalities to work:
a) Atleast 1 search token is contained within the FAQ
b) Every search token is contained within the FAQ

a) Search is performed on already filtered FAQ's (based on categories)
b) Search is performed on all FAQ's -> would remove filtering of the FAQ's

## Summary by CodeRabbit

- **New Features**
	- Introduced a new search functionality within the course FAQ component.
	- Added a reusable `SearchFilterComponent` for handling search inputs.
- **Improvements**
	- Enhanced layout using Bootstrap classes for better responsiveness and spacing.
	- Simplified component state management for improved performance.
	- Improved search operations with dynamic input handling.
- **Style**
	- Updated layout for filter dropdowns to ensure consistent alignment with new search components.

### CODE REVIEW

**Review by sarpsahinalp — DISMISSED** [review]
Tested on ts1. Works as expected!

**Review by PaRangger — DISMISSED** [review]
Code LGTM 👍🏼 Tested on TS6, runs very fast on my computer even for many search terms.

One minor remark: Does the `Communication` tag in the title make sense here? I couldn't find a `FAQ` feature tag, but maybe you could use `General` instead.

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by SimonEntholzer — CHANGES_REQUESTED** [review]
Found a minor bug while testing: in the course management view, when the tag filters are de-selected, the searched term from the search bar is not applied any more, and all  FAQs are shown unfiltered again.

**Comment by cremertim** [comment]
> Found a minor bug while testing: in the course management view, when the tag filters are de-selected, the searched term from the search bar is not applied any more, and all FAQs are shown unfiltered again.

Adressed in last commmit 👍

**Comment by cremertim** [comment]
> Code LGTM 👍🏼 Tested on TS6, runs very fast on my computer even for many search terms.
> 
> One minor remark: Does the `Communication` tag in the title make sense here? I couldn't find a `FAQ` feature tag, but maybe you could use `General` instead.

The whole FAQ system is new part of the communication features 👍

**Review by SimonEntholzer — APPROVED** [review]
Issue is resolved on Ts5 :+1:

**Review by PaRangger — DISMISSED** [review]
Re-approve. Tested again on TS5. Works in FAQ tab as well as in the management window.

**Review by JohannesStoehr — DISMISSED** [review]
Code

**Review by ole-ve — APPROVED** [review]
code looks good

**Review by ole-ve — APPROVED** [review]

**Review by JohannesStoehr — APPROVED** [review]
Reapprove after merge

**Review by PaRangger — APPROVED** [review]

**Review by SimonEntholzer — DISMISSED** [review]
Reapprove

**Review by JohannesStoehr — APPROVED** [review]
Reapprove after merge

**Pull request merged**
