### PR TITLE
Improved plagiarism detection for text exercises

### PR DESCRIPTION
**Pull request by philippbauch**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
Currently, the plagiarism split view to inspect similar student submissions is only available for modeling exercises. This PR allows instructors to also compare detected text submissions in the new plagiarism inspection UI.

### Description
This PR contains the following changes:
* Enhancements to the plagiarism inspection UI
    * New page header
    * Updated design of the Sidebar
    * Code improvements
* Display similar **text** submissions in the split view
* Use the new JPlag 3 API to detect plagiarism
* New plagiarism related classes on the client and server

The most notable change will be the updated plagiarism inspection UI and the possibility to compare similar text exercises. Additionally, some server code has been adapted to work with the new JPlag version and to use the added plagiarism types.

### Steps for Testing

To properly test this PR, you need a text exercise with at least two *similar* submissions.

Tip: Use the [Lorem Ipsum Generator](https://loremipsum.io/generator/) and slightly modify the generated text for each submission.

1. Log in to Artemis
2. Navigate to Course Administration
3. Select a course
4. Go to Exercises
5. Navigate to the details page of a text exercise by clicking 'View'
6. Click 'Check Plagiarism'

You should now see the plagiarism page. Make sure the following works:
* The sidebar items correctly display the student logins and similarity
* By selecting a sidebar item, the submissions in the split view update correctly
* You can confirm or deny a detected plagiarism
* You can download the plagiarism results both as JSON and CSV
* The downloaded plagiarism results contain the correct status ('confirmed', 'denied', 'none')
* You can resize the split view panes, both by dragging the gutter and clicking on the shortcut icons in the top right

Lastly, it would be great if you could verify that the plagiarism inspection for **programming** exercises still works. Programming exercises currently don't use the new plagiarism UI, but clicking on 'Check Plagiarism' should correctly download the results as a ZIP file.

**Note**: As mentioned in the reviews below, JPlag sometimes gives identical submissions a similarity slightly below 100%. I double-checked this and found out that this behavior already exists in JPlag 2 (previous version) and since I didn't make any changes to the algorithm itself, fixing this is beyond the scope of this PR.

### Test Coverage
plagiarism-header.component.ts                      100.00 %
plagiarism-inspector.component.ts                    90.91 %
plagiarism-sidebar.component.ts                       87.50 %
plagiarism-details.component.ts                        81.82 %
text-submission-viewer.component.ts              82.35 %
modeling-submission-viewer.component.ts     88.89 %
plagiarism-split-view.component.ts                  84.85 %

### Screenshots
Screenshot 2020-11-30 at 22 10 13
Screenshot 2020-11-30 at 22 10 39

### CODE REVIEW

**Review by airelawaleria — DISMISSED** [review]
Tested on ts3 with @simonzilker . Worked fine, but for completely identical submissions the plagiarism rate is 98.13 :) Don't know if that's okay

**Review by simonzilker — DISMISSED** [review]
Works as intended. Nice feature! What @airelawaleria said :)

**Review by derLalla — DISMISSED** [review]
The GUI looks great and I really like the shortcuts to resize the panels! My text exercises were all correctly displayed. 👍

**Review by JohannesWeiss — DISMISSED** [review]
Great feature and works as intended. 👍 
As mentioned before, 1:1 copied text gets <100% rate, 99.67% in my case.

**Review by marvinchimeka — DISMISSED** [review]
tested on ts1. Worked as intended but for the exact submissions the plag rate was not at 100%. Should it suppose to be or not ?

**Review by tiffca — APPROVED** [review]
Tested the steps, and it works as expected. Nice changes! 
Also confirmed check plagiarism for programming exercises still works.

**Comment by philippbauch** [comment]
> Tested on ts3 with @simonzilker . Worked fine, but for completely identical submissions the plagiarism rate is 98.13 :) Don't know if that's okay

I double-checked this and found out that this behavior already exists in JPlag 2 (previous version). I will get in touch with the JPlag maintainers, but I think fixing this is beyond the scope of this PR 👍

**Comment by philippbauch** [comment]
Added some more client tests to increase the test coverage, functionality should be the same.

**Review by airelawaleria — DISMISSED** [review]
Tested on ts3. Still works! Now the rate for identical submission is up, 98,95% :)

**Review by JohannesWeiss — DISMISSED** [review]
Still works great, percentage didn't change.

**Review by simonzilker — DISMISSED** [review]
Tested on ts3. Still works as described!

**Review by marvinchimeka — DISMISSED** [review]
tested on ts3. Re-approve but the plag rate was still <100%.

**Review by DenizShabani — DISMISSED** [review]
Tested and looks good. However, it would never reach 100% not even for exact same submissions.

**Review by LudwigWeide — DISMISSED** [review]
Tested on TS2. Works as intended.

**Review by krusche — DISMISSED** [review]

**Comment by krusche** [comment]
There are merge conflicts and one server test is failing. Please fix those, then I think we can merge.

**Comment by philgabr** [comment]
I just tested this feature on ts3. In general it works as intended :+1:

One strage thing I noticed is that on "Philipp's Test Course" -> "Text Exercises" -> "Plag Test" it seems to be not working properly:
image

I could not find out why this is the case, for other courses it actually did work fine!

**Review by krusche — APPROVED** [review]

**Pull request merged**
