### PR TITLE
[Bugfix] Fix NPE in getRepository of RepositoryProgrammingExerciseParticipationResource

### PR DESCRIPTION
**Pull request by fde312**
### Checklist
- [x] I tested *all* changes and *all* related features locally
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).

### Motivation and Context

Should fix Sentry issue: https://sentry.io/organizations/ls1intum/issues/1948174164/?environment=prod&project=1440029&query=is%3Aunresolved+assigned%3Ame&statsPeriod=14d

### Description

- Extended the check as it is only relevant for Student Participations

### Steps for Testing

1. Log in to Artemis as Instructor
2. Navigate to Course Administration
3. Go to a Programming Exercise and click on `Edit in editor`
4. Switch between Template Repo and Solution Repo
5. No error should be thrown

NOTE: I was not able to reproduce the issue by doing this test, but if you check the Sentry issue the error is thrown in the GET Call:
image
@krusche checked the participationId and it was a `SolutionParticipation`, so it can be just thrown in the scenario as noted above.

If anyone has an idea how we can reproduce this bug, let me know :)
### Test Coverage

Nothing changed

### Screenshots

image

### CODE REVIEW

**Review by marvinchimeka — APPROVED** [review]
I tested it on ts1. I could not experience any kind of error. The switch between template and solution repository can be done without any error. But i do not know how to reproduce his bug because everything went as expected.

**Review by sjagla27 — APPROVED** [review]
Could not find an error. Test looks good too.

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts1 and worked without an error.

**Review by airelawaleria — APPROVED** [review]
Worked fine. Could not reproduce the error.

**Review by tiffca — APPROVED** [review]
After deploying again in test server 1 I was not able to reproduce the below error and the test steps worked successfully. 

Note, the first time I deployed this on test server 1 I received the below error when clicking on "edit in editor". However, it is no longer reproducible after redeploying. 
main.208fed66ea1c11fa7d58.bundle.js:2 GET https://artemistest.ase.in.tum.de/app/9.208fed66ea1c11fa7d58.chunk.js net::ERR_ABORTED 404
r.e @ main.208fed66ea1c11fa7d58.bundle.js:2
loadChildren @ main.208fed66ea1c11fa7d58.bundle.js:4
loadModuleFactory @ main.208fed66ea1c11fa7d58.bundle.js:2

**Review by DenizShabani — APPROVED** [review]
Tested and the error did not show for me either.

**Review by EneaGore — APPROVED** [review]
Seems to work fine, cannot reproduce error.

**Review by balazs-czopf — APPROVED** [review]
Tested on TS3, worked fine for me, code also looks good 🚀

**Review by krusche — APPROVED** [review]

**Pull request merged**
