### PR TITLE
`Programming exercises`: Update dependencies for Java blackbox exercise template

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
In the last update #7127 we forgot to update the Java version in the `pom.xml` of the tests repository.

### Description
Updates the Java version to 21 to match the template solution and exercise repositories.
Uses this occasion to also update plugins specified in the `pom.xml`.

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Create a new Java programming exercise of type Dejagnu/Blackbox.
2. The solution build passes all tests, the template build none.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by Strohgelaender** [comment]
Do you provide these dependencies within your docker image? If yes, we should probably update the image version as well.

**Comment by b-fein** [comment]
Nö, there ist no caching in the image. No need to update it.

**Review by Strohgelaender — APPROVED** [review]
code

**Review by Hialus — APPROVED** [review]
Changes look good.

**Review by DominikRemo — APPROVED** [review]
Tested on ts2. Works as expected.

_Note: One test fails for the solution build. It's unrelated to this PR but we should at least write an Issue once this PR gets merged._

**Pull request merged**
