### PR TITLE
`Adaptive learning`: Change mastery threshold to input field and validate values

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

An input field is easier to manage and to select a specific value instead of an slider.

### Description

Replace the slide for the mastery threshold with an input field and validate the resulting value on the server and client.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Create/Edit a competency and set a new mastery threshoid value

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Performance Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Bildschirmfoto 2024-10-01 um 15 00 15

## Summary by CodeRabbit

- **New Features**
	- Enhanced validation for competency and prerequisite attributes during creation and updates.
	- Updated input type for mastery threshold to enforce a numeric range (1-100) in the competency form.
	- Default mastery threshold of 42 set for newly created competencies and prerequisites.

- **Bug Fixes**
	- Improved error messaging for invalid competency and prerequisite submissions.

- **Documentation**
	- Clarified validation requirements for competency titles and mastery thresholds in the user interface.

### CODE REVIEW

**Review by raffifasaro — DISMISSED** [review]
code LGTM

**Review by JohannesWt — APPROVED** [review]
Code 👍

**Review by pzdr7 — APPROVED** [review]
Code :+1:

**Review by Jan-Thurner — APPROVED** [review]
Code

**Review by az108 — APPROVED** [review]
Tested on TS4 and works as expected 👍 Just a small question do we intend to keep the mastery treshhold at 100 percent for new competencies? A slighly lower default value might be better as recommendation for new instructors who create competencies.

image

**Review by cremertim — APPROVED** [review]
Code 👍

**Review by MaximilianAnzinger — APPROVED** [review]
Maintainer approved

**Pull request merged**
