### PR TITLE
`Exam mode`: Redesign the user interface of end page

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

The user interface of exam mode is redesigned. However, end page was outdated. Therefore, its user interface should be updated.

### Description

- Added new end page layout, confirmation and continue text
- Changed the button from Continue to Back
- Updated documentation

### Steps for Testing

**(There is already an exam on TS6 under my course ("New End Page"), which you can test. Test users 1-5 are registered for the exam.)**
Prerequisites:
- 1 Student
- 1 Exam

1. Log in to Artemis
2. Participate in the exam
3. Click on Hand in Early
4. Verify that the end page is changed and page layout is responsive in case of window resizements

#### Exam Mode Testing

Prerequisites:
- 1 Student
- 1 Exam

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that remaining submit time is correct (remaining time + grace period (default 3 minutes))
4. Make sure that Back buton works as it is before (it should navigate to the last selected exercise)
5. Make sure that the error messages are correct for wrong input name and unchecked confirmation box
6. Make sure that Finish button is active with correct input
7. Make sure that Finish button works as expected

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| exam-participation.component.ts | 91% | ✅                           |
| exam-participation-cover.component.ts | 97% | ✅ |

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Screenshots

Before
Screenshot 2024-07-24 at 17 32 12

After
Screenshot 2024-07-21 at 19 34 24

## Summary by CodeRabbit

- **New Features**
  - Enhanced exam bar with dynamic timing information based on exam state, improving user interaction.
  - Introduced conditional rendering for exam participation layout, providing clearer status feedback to users.

- **Bug Fixes**
  - Improved visibility conditions for actions based on exam state, preventing premature submissions.

- **Style**
  - Enhanced responsive design for the exam participation interface, ensuring better layout consistency across devices.

- **Refactor**
  - Streamlined component structure in exam participation for improved maintainability and user experience.

### CODE REVIEW

**Review by konrad2002 — DISMISSED** [review]
manually tested on ts4, works as expected
additionally tested endText and confirmationEndText, still working as expected

**Review by magaupp — CHANGES_REQUESTED** [review]
I think `klicke auf den Zurück-Button` or `klicke auf den Button "Zurück"` would be better translations.

The timers on the end page do not update if the exam working times are adjusted by an instructor while the student is looking at the end page. This does work for the exercise pages.

This error gets printed to the console every time I open the end page:
image

**Review by magaupp — DISMISSED** [review]
Tested on TS6. Works as expected. The timer syncs correctly if the working time is adjusted.

**Review by BBesrour — APPROVED** [review]
tested on ts6, works as described

**Review by konrad2002 — DISMISSED** [review]
reapprove

**Review by sarpsahinalp — DISMISSED** [review]
Tested on ts6 works as expected!

**Review by magaupp — APPROVED** [review]
Tested on TS4. Functions as before. The timer is well-behaved. The footer is not shown.

**Review by BBesrour — DISMISSED** [review]

**Comment by edkaya** [comment]
> I added some comments to the code. Please, check the space below exercises within the exam and remove the unnecessary scrolling in the end view
> 
> Screenshot 2024-08-01 at 11 04 28
>  Screen.Recording.2024-08-01.at.10.56.26.mov

I think the version on test servers are outdated. Please deploy the current version again. This should be already fixed 💯

**Review by BBesrour — APPROVED** [review]

**Review by magaupp — COMMENTED** [review]
The scollable overflow cuts off at a strange location:
image

`.scrollable-content-exam-cover` seems to mention a footer which is not there.

**Review by rabeatwork — DISMISSED** [review]
LGTM - thanks for addressing the feedback

**Review by magaupp — DISMISSED** [review]
LGTM - Works well and looks good

**Review by anian03 — APPROVED** [review]
Tested on TS6, everything works as described

**Review by magaupp — APPROVED** [review]
Tested on TS6, works as expected, looks as described.

**Review by BBesrour — APPROVED** [review]
re-approve

**Review by rabeatwork — APPROVED** [review]
maintainer approve

**Review by sarpsahinalp — APPROVED** [review]
Reapprove after conflict

**Pull request merged**
