### PR TITLE
`General`: Apply filters to next relevant exercise

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The filters of the course exercise view are currently not applied to the next relevant exercise shown at the top.
image (1)

### Description

This PR applies the filter to the selection algorithm of the "next relevant exercise" as well by only selecting from those exercises that fulfill the selected filter.

### Steps for Testing

Prerequisites:
- 1 Student
- A few exercises in different, filterable stages: Optional, with full points, ... that are candidates to appear as next relevant exercise

--> Select and deselect filters from the filter dropdown and make sure that only exercises that fulfill the currently selected filters appear as "next relevant exercise".

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| course-exercises.component.ts | 77.98% | 98.81% |

### Screenshots

https://user-images.githubusercontent.com/23171488/161756203-2f6a2b82-d99d-4aab-bbd9-577068ea001c.mov

### CODE REVIEW

**Comment by akesfeden** [comment]
I am not sure if this is introduced by this change here but when I try the testing steps multiple times, the next relevant exercise sometimes behaves weirdly and set to seemingly random values. Sometimes it happens with a few filter toggles and sometimes you need to spam the filter toggles to observe it. I posted a screen record below.

https://user-images.githubusercontent.com/18427209/161854146-dfd6e782-6e2a-4842-951f-c8f4b7e0814d.mp4

**Comment by bassner** [comment]
@akesfeden Interesting catch. It was not introduced by this PR, but I included a fix anyways in ad6094c. :)

**Comment by maximiliansoelch** [comment]
While testing the latest changes on TS3, I noticed another weird behavior when toggling the _hide optional_ filter. It appears the filter is applied correctly, however the optional tag as well as the due date are not refreshed for the current exercise component. Can someone reproduce this?

https://user-images.githubusercontent.com/9954674/161993368-755375ea-73dd-4128-880b-d356cff811cb.mov

**Comment by bassner** [comment]
@maximiliansoelch Seems like this is because a lot of components used in the exercise row initialized their state in ``ngOnInit``, but do not react to changes in their data inputs. I tried to fix that in cf1ba92. Could you please try if you can still observe that behavior?

**Comment by maximiliansoelch** [comment]
Now it works like intended 👍

**Comment by bassner** [comment]
@akesfeden @maximiliansoelch Any chance I could get a green checkmark from you guys? :D

**Review by maximiliansoelch — APPROVED** [review]
Code looks good to me. 
Also tested the changes on TS3 where they worked like intended.

**Review by akesfeden — APPROVED** [review]
Thank you very much for the fix! I cannot produce that bug now and the main functionality is working as expected. Code changes LGTM.

**Review by maximiliansoelch — APPROVED** [review]
Reapproved - also tested again on TS1 and filtering works as intended.

**Review by mallgaier — APPROVED** [review]
Tested on TS1, works as expected.
Good job 👍

**Review by akesfeden — APPROVED** [review]
Tested on TS1, works as expected, re-approved.

**Pull request merged**
