### PR TITLE
`Development`: Migrate client code for conversation detail tabs

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

For the client migration, following files need to be updated:

-- | File Path | Standalone | Signals | Inject | 
-- | -- | -- | -- | -- 
20 | /overview/course-conversations/dialogs/conversation-detail-dialog/tabs/conversation-info/conversation-info.component.html | ✅ | ❌ | ✅ | 
21 | /overview/course-conversations/dialogs/conversation-detail-dialog/tabs/conversation-info/conversation-info.component.ts | ❌ | ❌ | ❌ | 
22 | /overview/course-conversations/dialogs/conversation-detail-dialog/tabs/conversation-members/conversation-member-row/conversation-member-row.component.html | ✅ | ❌ | ✅ |  
23 | /overview/course-conversations/dialogs/conversation-detail-dialog/tabs/conversation-members/conversation-member-row/conversation-member-row.component.ts | ❌ | ❌ | ❌ |
24 | /overview/course-conversations/dialogs/conversation-detail-dialog/tabs/conversation-members/conversation-members.component.html | ✅ | ❌ | ✅ |  
25 | /overview/course-conversations/dialogs/conversation-detail-dialog/tabs/conversation-members/conversation-members.component.ts | ❌ | ❌ | ❌ | 
26 | /overview/course-conversations/dialogs/conversation-detail-dialog/tabs/conversation-settings/conversation-settings.component.html | ✅ | ❌ | ✅ |  
27 | /overview/course-conversations/dialogs/conversation-detail-dialog/tabs/conversation-settings/conversation-settings.component.ts | ❌ | ❌ | ❌

### Description

`ConversationSettingsComponent`, `ConversationMembersComponent`, `ConversationMemberRowComponent`, and `ConversationInfoComponent` have been updated to use inject and signals.

Known Issue: These components have been migrated to use inject and signals, but they haven't been converted to standalone yet, as it would impact other components. This will be addressed in a follow-up PR.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with Communication enabled

1. Log in to Artemis
2. Navigate to Communication section of a course
3. Open the settings of a random channel by clicking the three-dot menu option.
4. Test all functionalities across the three tabs (info, members, settings) and ensure everything works as expected.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| conversation-info.component.ts | 90.09% | ✅ ❌ |
| conversation-member-row.component.ts | 83.91% | ✅ ❌ |
| conversation-members.component.ts | 93.18% | ✅ ❌ |
| conversation-settings.component.ts | 88.37% | ✅ ❌ |

## Summary by CodeRabbit

- **New Features**
	- Enhanced input handling in several components, transitioning to a more reactive programming model.
	- Added new methods for retrieving conversation creator and improved property access in templates.

- **Bug Fixes**
	- Improved handling of optional chaining for safer property access in conversation-related components.

- **Tests**
	- Updated test setups to align with new input/output handling and reactive properties.
	- Adjusted test cases to ensure proper state management using Angular's dependency injection context.

### CODE REVIEW

**Review by iyannsch — APPROVED** [review]
Changes LGTM

**Review by raffifasaro — APPROVED** [review]
Code lgtm

**Review by HawKhiem — APPROVED** [review]
Tested on TS2. I tested the followings: 
✅ Edit the name of a channel
✅ Edit the topic of a channel
✅ Edit the description of a channel (although I'm not really sure how the change is reflected)
✅ Searching for members
✅ Archiving channels

Everything works fine. One thing I noticed was the change for the name of the channel was only updated after I close the edit popup, even after clicking on save, the change is not reflected imediately.

image

After closing the pop up for editing, the change is updated

image

**Review by sachmii — APPROVED** [review]
Tested on TS6, everything works just fine as before.

**Pull request merged**
