### PR TITLE
`Development`: Delete quiz pool when deleting exams

### PR DESCRIPTION
**Pull request by rriyaldhi**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Exams should be able to be deleted regardless of whether the exam has a quiz pool or not.

### Description

Add quiz pool deletion to ExamDeletionService.delete method.

#### Exam Mode Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis as an instructor
2. Create an exam (ensure the **start date is in the future**)
3. Navigate to the Quiz Pool configuration page (atm it is hidden), so you need to manually add **/quiz-pool** at the end of the exam detail URL (e.g. **https://artemis-test1.artemis.in.tum.de/course-management/23/exams/483/quiz-pool**)
4. Add quiz pool group
5. Create at least 1 quiz question
6. Map the quiz question to the group
7. Click save
8. Delete the Exam (Verify that deletion works)
9. Repeat for exam without a quiz pool

#### Performance Review
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| ExerciseDeletionService.java | 100% | ✅                           |

### Screenshots

https://github.com/ls1intum/Artemis/assets/10885503/8a79b01d-55a5-4cff-80c5-e9d8b41c0397

### CODE REVIEW

**Review by matthiaslehnertum — APPROVED** [review]

**Review by sarpsahinalp — APPROVED** [review]
Demonstrated during testing session. Worked as expected

**Review by AlexanderG2207 — APPROVED** [review]
It worked as expected in the testing session.

**Review by mateusmm01 — APPROVED** [review]
Demonstrated on ts5 during testing session. Worked as expected!

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts11. Worked as expected.

**Review by egekurt123 — APPROVED** [review]
Manually tested on ts2, works as expected

**Review by MichaelOwenDyer — APPROVED** [review]
Looks good!

**Review by Santia-go — APPROVED** [review]
Tested on TS6 
working as expected. The deletion process worked perfect! 
image

**Pull request merged**
