### PR TITLE
[Exam] Add working time

### PR DESCRIPTION
**Pull request by sascha11110**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I added multiple integration tests (Spring) related to the features
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
Individual students can receive compensation for disadvantages, i.e. they have X % more time, whereby X can have different values per student (e.g. 25, 40, 50, 100). Simple attribute workingTime (defaults to the exam duration).

### Description
- [x] I've added the attribute `workingTime` to `StudentExam`
- [x] I've ensured that the default working time will be set for all student exams during generation
- [x] The working time will be displayed in the student exam detail view

### Steps for Testing
1. Log in to Artemis
2. Generate student exams
3. Go to the detail view of a student exam and check that the displayed working time equals the duration of the exam

### Screenshots
image

### CODE REVIEW

**Comment by krusche** [comment]
The code looks good to me, so as soon as you have tried this out on the test server, we can merge this!

**Comment by anditurdiu** [comment]
The functionality works well apart from one very unlikely edge case: 
If the duration of the exam is longer than 24h the working time is not displayed correctly. 

Also a thought: Since we are defining a working time, and we force the user to define the start and end time of the exam, do we want to pre-insert the start, and due dates for the exercises in the exercise-update component? The user then still has the option to change them, however by default they would be the same as the start and end date of the exam.

**Comment by sascha11110** [comment]
@krusche I tested it on the test server. Since Andi has more or less also approved, I think we can merge this.

A known limitation / bug that I will fix in a follow-up: The duration is displayed as seconds because our ngx-datatable configuration does not support pipes / function invocation in the template.

@anditurdiu I think we can ignore the case that an exam is longer than 24 hours :-D But I will put it on the list to fix it in a follow-up.

I think we already discussed the sync of the dates of the exam and the exercises. Would be a good solution to implement it that way. But a little bit out of scope of this PR :-)

**Comment by pzdr7** [comment]
I've tested this on the test server and it appears to work as intended. (I'm two minutes late, though 😅)

**Pull request merged**
