### PR TITLE
`General`: Underscore all results correctly

### LINKED ISSUE #7200: `Programming exercises`: Result string is not correctly underlined in the recent results list
### Describe the bug

The result should be underlined to indicate that it is clickable. However, this does not work in the list of results:
grafik

### To Reproduce

1. Participate in a programming exercise as a student
2. View the list of recent results

### Expected behavior

the whole text is underlined.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.5.0

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by simon-hng**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I wrote super performant css
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context
resolves #7200 

### Steps for Testing

Go to any programming exercise with results and look in the results list. (See screenshot below)

Also check that quiz exercises are not underlined (since these results are not clickable)

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Screenshots

image

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
tested on ts5, works! 
grafik

**Review by laurenzfb — APPROVED** [review]
tested in testing session, worked as described

**Review by basak-akan — APPROVED** [review]
tested in testing session worked well

**Review by milljoniaer — APPROVED** [review]
tested in testing session, worked as expected

**Review by lennart-keller — APPROVED** [review]
Tested in testing session, works well.

**Pull request merged**
