### PR TITLE
[Bugfix] Shorten paths in build logs

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

The build logs should not show the absolute file path to the source files causing the issue.

### Description

Use a regex to remove the path up to the assignment directory. The regex should work for both Unix and Windows paths. Note: Bamboo always uses '/' to report paths. Window paths start with '/C:/...'
### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a programming exercise
4. Participate in the exercise
5. Let the build fail
6. Check the build logs
--> Paths to the source file should start with src

### Test Coverage

Coverage is the same. I will deliver a small test targeting the regex in a follow up

### Screenshots

Screenshot 2020-11-19 180839
Before on Windows
image
After on Windows

### CODE REVIEW

**Review by LudwigWeide — APPROVED** [review]
Tested on TS1. Results as intended.

**Review by airelawaleria — APPROVED** [review]
Tested with @marvinchimeka. Works fine!
Screenshot 2020-11-19 183431

**Review by marvinchimeka — APPROVED** [review]
Tested this with @airelawaleria. Everything worked as intended. 
Bildschirmfoto 2020-11-19 um 18 32 29

**Review by FlorianStang — APPROVED** [review]
Tested on TS1, behavior as intended.

**Review by EneaGore — APPROVED** [review]
Build fails succesfully showing src on beginning of path.

**Review by JohannesWeiss — APPROVED** [review]
Worked as intended on ts1

**Review by krusche — APPROVED** [review]

**Pull request merged**
