### PR TITLE
[Bugfix] - Fix Button colors in exercise detail instructor actions

### PR DESCRIPTION
**Pull request by FuchsDominik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

We show edit and re-evaluate buttons in yellow

### Description

Changed edit and re-evaluate button color to yellow (button-warning)

### Steps for Testing

1. Log in to Artemis
2. Navigate into a exercise detail page as an instructor
3. Make sure the edit/re-evaluate button the the top right corner is yellow

### Screenshots

Before:
image

After:
image
image

### CODE REVIEW

**Review by sinangunduz — APPROVED** [review]
tested on ts1, yellow as expected

**Review by willergeorg — APPROVED** [review]
Tested on TS1. New color looks good.

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 1. Everything worked as expected.

**Review by katjanakosic — APPROVED** [review]
Worked as expected :))

**Review by KiraNickel — APPROVED** [review]
Tested on ts1, color looks good 👍🏼

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Looks good.

**Review by canyelten — APPROVED** [review]
Tested on TS1. Color as expected.

**Pull request merged**
