### PR TITLE
`Development`: Remove eager relationship between lecture and attachments

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [X] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context

In #7719, the migration to Hibernate 6 introduced circular references in some produced SQL queries. To mitigate this effect, we replace explicit EAGER references on models with fetch queries wherever necessary.
This PR affects the relation between Lectures and Attachments

### Description

I removed the explicit EAGER, added an attachment fetch to some queries and replaced certain query usages where fetching attachments is required.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Create a lecture
2. Add an attachment to the lecture (not an attachment unit)
3. Make sure you can see and access it in the course overview and the course management section
4. Import this lecture
5. Make sure you can see and access the imported attachment in the course overview and the course management section.

#### Performance Review
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Omitted as there are no changes affecting coverage

## Summary by CodeRabbit

- **Refactor**
  - Improved loading strategy for lecture-related entities to enhance performance.

- **Bug Fixes**
  - Ensured all relevant lecture data, including attachments and lecture units, is fetched consistently across the application.

- **Tests**
  - Updated integration tests to align with the new data fetching methods for lectures.

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code lgtm

**Review by basak-akan — APPROVED** [review]
Tested on TS4 and was able to access attachments from the course overview and the course management sections in the created/imported lecture.

**Review by farisd16 — APPROVED** [review]
tested on ts3, works as expected

**Review by aplr — APPROVED** [review]
Code LGTM

**Review by MaximilianJG — APPROVED** [review]
Tested on ts3. I can access the attachments after creating and after importing. 

Screenshot 2024-01-07 at 21 52 39

**Review by coolchock — APPROVED** [review]
Tested on ts4, works as expected. Code looks good too.

**Pull request merged**
