### PR TITLE
`Programming exercises`: Include mode selection in validation status

### PR DESCRIPTION
**Pull request by milljoniaer**
#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
When both Allow offline IDE and online editor are not checked, the mode section in programming exercises should be invalid.

### Description
This PR includes the specific validation.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Create Programming exercise, Check uncheck these boxes 
3. verify that validation bar shows correct state of mode section

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
image

## Summary by CodeRabbit

- **New Features**
	- Implemented real-time validation checks for modifying difficulty settings in the programming exercise update form.

- **Bug Fixes**
	- Enhanced validation logic in the programming exercise update wizard for accurate step validation based on IDE selections.

- **Tests**
	- Added tests to ensure proper functionality of form status sections and validations in the programming exercise update scenario.

### CODE REVIEW

**Review by rstief — DISMISSED** [review]
Code LGTM!

**Review by MaximilianAnzinger — APPROVED** [review]
Thank you for adding the test 👍 
Code LGTM

**Review by rabeatwork — APPROVED** [review]
maintainer approve

**Review by egekurt123 — APPROVED** [review]
Tested on ts2, works as expected

**Review by JohannesWt — APPROVED** [review]
Tested - works as expected

**Review by Jan-Thurner — APPROVED** [review]
Code LGTM

**Pull request merged**
