### PR TITLE
`Development`: Replace get(0) call with getFirst()

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context

Java 21 instroduced the shorthand `getFirst` for `get(0)` and IntelliJ shows a warning for the usage of `get(0)`, so I want to get rid of the warning.
Reference: https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/List.html#getFirst()

### Description

Replaces the calls of `get(0)` with the equivalent `getFirst()`.
All but two occurrences are in the tests.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### CODE REVIEW

**Review by iyannsch — APPROVED** [review]
Code LGTM

**Review by marlon-luca-bu — APPROVED** [review]
Code

**Review by asliayk — DISMISSED** [review]
code lgtm

**Review by DominikRemo — CHANGES_REQUESTED** [review]
The changes look good to me. However, to prevent future regressions, could you please add an architecture test? This will ensure that the get(0) method is not reintroduced inadvertently.

**Review by coolchock — DISMISSED** [review]
code LGTM

**Review by EneaGore — APPROVED** [review]

**Comment by JohannesStoehr** [comment]
> The changes look good to me. However, to prevent future regressions, could you please add an architecture test? This will ensure that the get(0) method is not reintroduced inadvertently.

IntelliJ already shows warnings if you use get(0). I would expect from our developers to try to write code without warnings and to also inspect them when they write new code without the need for an architecture test

**Review by MaximilianAnzinger — DISMISSED** [review]
Maintainer approved

**Review by egekurt123 — DISMISSED** [review]
Code

**Review by egekurt123 — APPROVED** [review]
Reapprove Code after solving merge conflicts

**Review by iyannsch — APPROVED** [review]
reapprove

**Review by coolchock — APPROVED** [review]
re-approve after merge conflicts were resolved

**Review by az108 — APPROVED** [review]
Code LGTM and changes did not affect artemis

**Pull request merged**
