### PR TITLE
`Programming exercises`: Show exercise dashboard button if complaints for automatic results are enabled

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
For programming exercises with manual corrections, the exercise detail page has a direct link to the corresponding assessment dashboard. In cases of automatically corrected programming exercises with the option to submit a complaint, this button is missing. Since this page also allows correcting the complaints, this PR adds this button.

### Description
Also show the button for exercises with complaints for automatic results.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Programming Exercise with Complaints enabled

1. Open the exercise detail page
2. Check that the button is shown and the link works

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Screenshots
grafik

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Changes look good and display the button correctly

**Review by simon-hng — DISMISSED** [review]
Code changes look good

**Review by tunargs — APPROVED** [review]
Tested on ts1 on exercise with complaints for automatic results. The button is displayed correctly

**Review by Vinicius-Agreste — APPROVED** [review]
Tested on ts2 with user 11 on an exercise with the mentioned specifications. The button is displayed correctly.

**Review by grochlitzzz — APPROVED** [review]
Tested with Instructor 11 on Server 1 and worked as expected

**Review by simon-hng — APPROVED** [review]

**Pull request merged**
