### PR TITLE
`Development`: Improve performance of programming exercise details view

### PR DESCRIPTION
**Pull request by florian-glombik**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
The programming exercise details page sent unnecessary requests to the server, which was caused by poor coordination of subscriptions in `programming-exercise-detail.component.ts,` leading to multiple instantiations and renderings of subcomponents.
Self-contained components (e.g. `programming-exercise-instructions.component.ts` and `programming-exercise-repository-and-build-plan-details.component.ts`), therefore, sent multiple requests to the server to retrieve unchanged information (initialized up to 3 times), in other words, unnecessary requests.

### Description
* Introduced signals and adhered to client guidelines in `detail-overview-list.component.ts`
* Made sure `getExerciseDetails()` is only called once after all subscriptions are finished onInit, preventing unnecessary rendering steps (this is ensured by using `switchMap()`
* Refactored `loadGitDiffReport()` to be able to use `processGitDiffReport()` it in `switchMap()`
* Refactored `loadGitDiffReport()` to reduce code duplication

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Create a programming exercise
2. Open the dev tools and the network tab of your preferred browser _(filter for Fetch/XHR)_
3. Go to the details view of the programming exercise
4. Verify that no requests are sent twice on the initial loading to he page (e.g. `test-cases`, `repository-checkout-directories` - will be send out twice right now and will not be addressed further in this PR (still 2 requests less than before), `details` - exception: it is okay for `time` to be there multiple times)
5. Verify that the details view works as expected (e.g. try out the diff view etc.)

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Duplicated requests before the fix ⚡ 
image

#### With the fix ✅ 
image

## Release Notes

- **New Features**
	- Enhanced detail rendering logic for various detail types in the overview list.
	- Improved handling of Git diff reports for programming exercises, including centralized processing logic.

- **Bug Fixes**
	- Enhanced error handling during data retrieval, ensuring better user feedback.

- **Tests**
	- Updated test cases for `DetailOverviewListComponent` and `ProgrammingExerciseDetailComponent` to align with new input handling and participation changes.

- **Refactor**
	- Streamlined dependency injection and component initialization for better maintainability.

### CODE REVIEW

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. The mentioned requests were indeed sent only once

image

**Review by sachmii — APPROVED** [review]
Tested on TS1, mentioned requests were sent only once.

**Review by cremertim — DISMISSED** [review]
Code refactoring lgtm

**Review by az108 — DISMISSED** [review]
Code Refactoring Looks good to me

**Review by az108 — APPROVED** [review]
Code

**Review by cremertim — APPROVED** [review]
Reapprove latenmst changes

**Review by magaupp — DISMISSED** [review]
Tested on TS3.
If the exercise details view is open while the build changes from building to finished the application gets stuck in a loop of requests:
- `/api/programming-exercises/repository-checkout-directories?programmingLanguage=JAVA&checkoutSolution=false`
- `/api/programming-exercise-participations/5/latest-pending-submission`
- `/api/programming-exercises/3/diff-report`

image

**Comment by florian-glombik** [comment]
@magaupp https://github.com/ls1intum/Artemis/pull/9785#pullrequestreview-2455187269
Good that we caught that in today's testing session, it is now fixed in [this commit](https://github.com/ls1intum/Artemis/pull/9785/commits/f8eaad8e11149d2c2b65da1f1aa1af075390879a)

**Review by cremertim — APPROVED** [review]
Reapprove latent changes

**Review by az108 — APPROVED** [review]
Code 👍

**Review by sachmii — APPROVED** [review]
Re-approve

**Comment by magaupp** [comment]
Tested on Firefox. `repository-checkout-directories` seems to be fetched 2 times, with the first time canceled. What's happening there?

grafik

**Comment by florian-glombik** [comment]
@magaupp https://github.com/ls1intum/Artemis/pull/9785#issuecomment-2495966266 
Thanks for your test, I have now added it to the testing description - I am not sure why this happens but I will not investigate it further as I have already way too much time on this issue and even for the `repository-checkout-directories` it is still an improvement from 4 requests going down to 2 requests, where one is even cancelled.

Do you think we should create an issue for it once the PR is merged?

**Review by magaupp — APPROVED** [review]
The other requests are only sent once, so this is definitely an improvement.
The details view also works as expected without issues.

requests

**Comment by magaupp** [comment]
@florian-glombik 
> Do you think we should create an issue for it once the PR is merged? (Beforehand it might be confusing as there are way more requests send out on the current develop state?)

I don't think it's performance critical. Nothing could wait on it because it's always canceled before it finishes.
Unless this causes any noticeable problems it's purely cosmetic and I wouldn't call it a real issue.

**Review by krusche — APPROVED** [review]
Great improvements, thank you 👍

**Pull request merged**
