### PR TITLE
`Programming exercises`: Improve http header for csrf protection for Bamboo

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [X] Tested on a test server
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).

### Motivation and Context

Currently, Artemis has an issue with the CSFR protection of Bamboo. When the student tries to start the exercise, Bamboo returns an error that a Cookie was not set.

### Description

I implemented this workaround: https://confluence.atlassian.com/bamkb/rest-api-calls-fail-due-to-missing-xsrf-token-899447048.html

After testing the issue was resolved and the programming workflow worked again.

### Steps for Testing

As it's a bit difficult to schedule activating this on the actual instance, please test this locally:
Prerequisites:
- 1 Instructor
- 1 Student

1. Checkout the `develop` branch
2. Go to Bamboo > Settings (Cogwheel) > Overview > Security > Security Settings
3. Click below on edit and check `Enable XSFR protection`. Save.
4. Create a programming exercise (instructor)
5. Try to start the exercise (student). It should fail.
6. Checkout this branch (don't forget to restart the server)
7. Create a new programming exercise (instructor)
8. Try to start the exercise (student). Now it should work.
9. Try to participate in the exercise
10. Go to participations as an instructor and resubmit the submission.
11. The workflow should work without issues. Feel free to try further things that affect Bamboo in some way.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
Tested on my local setup, works as expected. Thanks for adapting the documentation as well.

**Review by Strohgelaender — APPROVED** [review]

**Review by ole-ve — DISMISSED** [review]
Tested on my local setup, works as described. I also verified, that committing and pushing works fine as a student 👍

**Comment by krusche** [comment]
@Mtze how is this handled on our production system?

**Comment by ole-ve** [comment]
Unintentionally pushed to this branch, I reverted the changes to your last commit.

**Comment by Mtze** [comment]
@krusche On our Bamboo instances the CSRF protection is switched off. We tried to enable it some years ago and the Artemis integration broke. Since then I completely forgot about it 😬 It would be great if we could switch that on!

**Comment by krusche** [comment]
We have a similar setting for Jenkins called crumb which can be activated.
The main question is: what would be necessary on Artemis so that admins can activate it?
Jenkins can issue a cookie that is then used in Artemis, however this leads to additional overhead because for each request, the crumb cookie value needs to be queried from Jenkins.

I'm not sure if the additional overhead is justified in terms of security

**Review by ole-ve — DISMISSED** [review]
Re-approve testing since no changes have been made.
Cannot really comment if this workaround is a good one, but its implementation looks good to me. 👍

**Comment by julian-christl** [comment]
> We have a similar setting for Jenkins called crumb which can be activated. The main question is: what would be necessary on Artemis so that admins can activate it? Jenkins can issue a cookie that is then used in Artemis, however this leads to additional overhead because for each request, the crumb cookie value needs to be queried from Jenkins.
> 
> I'm not sure if the additional overhead is justified in terms of security

It looks like we already do this, don't we?
JenkinsJobService:29 we inject our value and for example in JenkinsJobService.createJobInFolder():149 we pass that flag to the `jenkinsServer` that is third-party. If you follow the path along, you can see that the request gets automatically issued if set to true.
I'm not an expert on Jenkins, on the contrary, but I think this should suffice. The flat can be set using the Artemis config files.

**Comment by krusche** [comment]
> > We have a similar setting for Jenkins called crumb which can be activated. The main question is: what would be necessary on Artemis so that admins can activate it? Jenkins can issue a cookie that is then used in Artemis, however this leads to additional overhead because for each request, the crumb cookie value needs to be queried from Jenkins.
> > I'm not sure if the additional overhead is justified in terms of security
> 
> It looks like we already do this, don't we? JenkinsJobService:29 we inject our value and for example in JenkinsJobService.createJobInFolder():149 we pass that flag to the `jenkinsServer` that is third-party. If you follow the path along, you can see that the request gets automatically issued if set to true. I'm not an expert on Jenkins, on the contrary, but I think this should suffice. The flat can be set using the Artemis config files.

This is a misunderstanding. What I meant: It already works for Jenkins, but not yet for Bamboo.

Now the question is: How could we actually enable it for Bamboo? What would be need to issue the token on Bamboo, to retrieve it and to store it?

**Comment by julian-christl** [comment]
> > > We have a similar setting for Jenkins called crumb which can be activated. The main question is: what would be necessary on Artemis so that admins can activate it? Jenkins can issue a cookie that is then used in Artemis, however this leads to additional overhead because for each request, the crumb cookie value needs to be queried from Jenkins.
> > > I'm not sure if the additional overhead is justified in terms of security
> > 
> > 
> > It looks like we already do this, don't we? JenkinsJobService:29 we inject our value and for example in JenkinsJobService.createJobInFolder():149 we pass that flag to the `jenkinsServer` that is third-party. If you follow the path along, you can see that the request gets automatically issued if set to true. I'm not an expert on Jenkins, on the contrary, but I think this should suffice. The flat can be set using the Artemis config files.
> 
> This is a misunderstanding. What I meant: It already works for Jenkins, but not yet for Bamboo.
> 
> Now the question is: How could we actually enable it for Bamboo? What would be need to issue the token on Bamboo, to retrieve it and to store it?

Personally, I am not aware that this would be intended for Bamboo. I can't find any hint on this at all (official or unofficial).
Atlassian only suggests manually logging in or using a PAT.
https://developer.atlassian.com/server/bamboo/using-the-bamboo-rest-apis/
Manually logging in is not really possible for Artemis so PAT is the way to go.

I can check if we still need the basic authentication for the edge cases but that's all then as far as I can see.
Or do you see another approach that I don't?

**Comment by julian-christl** [comment]
Had an idea but didn't work out so I reverted. No changes.

**Comment by julian-christl** [comment]
This PR has already been approved in this version @ole-ve @Strohgelaender if you feel the need, you can reapprove.

And as discussed with @krusche, the commends would be relevant for potential follow-up PRs but not this one.

**Pull request merged**
