### PR TITLE
[Enhancement] Programming Assessment enable SCA and Build logs

### PR DESCRIPTION
**Pull request by fde312**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) locally.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

SCA annotations were not displayed during the manual assessment of programming exercises. In this PR we enable back the build output, which adds the annotations to the code editor. Additionally we enable build logs for manual programming assessments.

### Description

- Add back build output for programming assessment
- Add css to properly display annotations with the inline feedback component
- Remove manual assessment check in when fetching build logs

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create Programming Exercise with SCA, participate and assess it (make also a submission with build failed)
4. Check that SCA annotations are displayed in the gutter of the code editor
5. Add inline feedback and check that the SCA annotations is still displayed
6. When assessing the submission with build failed, the build log should also be displayed in the build output component as well as the error annotation.

See also screenshots below

### Screenshots

Build failed:
image

image

image

SCA:
image

image

image

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
everything worked as described

**Review by EneaGore — APPROVED** [review]
Looks very good on ts1.

**Review by JohannesWeiss — APPROVED** [review]
Works as intended on ts1.

**Review by simonzilker — APPROVED** [review]
Looks good :)

**Review by marvinchimeka — APPROVED** [review]
No issues found

**Review by tiffca — APPROVED** [review]
Tested successfully. sca errors showed up for students when clicking on the issues and in-line, as well as in-line for assessors. build logs/errors displayed for assessors

**Review by DenizShabani — APPROVED** [review]
Looks good!

**Review by krusche — APPROVED** [review]

**Pull request merged**
