### PR TITLE
`Development`: Update Apollon version

### PR DESCRIPTION
**Pull request by minrows**
#### General

- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
Update version of Apollon from [v2.11.1](https://github.com/ls1intum/Apollon/releases/tag/v2.11.1) to [v2.11.2](https://github.com/ls1intum/Apollon/releases/tag/v2.11.2)

### Description
This bugfix version of Apollon fixes an appearance issue with interface connections, the problem stated by @jschmautzer at one of the [Testing Session](https://confluence.ase.in.tum.de/display/ArTEMiS/Testing+Session+11.07.2022) [Table: Findings > Assigned Issue > Issue Nr: 20]

### Steps for testing
As stated in "Steps to reproduce" section of Testing session. 

OR

1. Create a modeling exercise
2. Select Component Diagram as its Diagram type
3. Connect Interface and Component in the canvas
4. Observe that there are no white triangles

### CODE REVIEW

**Review by pantageepapa — APPROVED** [review]
Tested on ts2 and could not reproduce the error

**Review by jschmautzer — APPROVED** [review]
tested on ts2, looks good now :)

**Review by akesfeden — APPROVED** [review]
Tested on TS1, I couldn't reproduce the white triangle error.

**Review by maximiliansoelch — APPROVED** [review]
Tested on TS1, component diagram works as expected 👍

**Pull request merged**
