### PR TITLE
`Exam mode`: Fix rounding of scores in the summary view

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Sentry issues https://sentry.ase.in.tum.de/organizations/artemis/issues/20270 and https://sentry.ase.in.tum.de/organizations/artemis/issues/20271.

### Description
The component that called the rounding did not have a course object to determine the rounding accuracy. This PR updates it to make sure a course is present when rounding.

### Steps for Testing
Prerequisites:
- 1 Finished exam for a student

1. Go to the student exam summary as instructor (Exam Management → Student Exams → View → Summary) or the student the exam belongs to.
2. The table titled ‘Overview’ with the scores of the exercises of the exam should be shown and the scores should be rounded according to the specified course accuracy.

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

### CODE REVIEW

**Review by Bofan-Zhu — APPROVED** [review]
Tested on ts2. Working rounded as expected 👍.

**Review by Strohgelaender — COMMENTED** [review]
Tested on TS1 with @lBruchmann @willergeorg.

The rounding gets applied to the overview as expected, but the score of the exercise is not affected here. Could you use the value here as well?
grafik

**Review by dveljacic — APPROVED** [review]
Tested on TS2. Looks good to me. ✅

**Comment by krusche** [comment]
Thanks for fixing the issue 👍

**Comment by Strohgelaender** [comment]
> Did you change the rounding accuracy of the course before or after the result was created? If before, then there is a separate bug how this string is generated.

No, it was after. I did not know that this is a fixed string, thank you.

**Pull request merged**
