### PR TITLE
`Iris`: Fix duplicated ids in settings UI

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

The settings UI used ids for the input components that were the same between the different Iris sub features. This then caused a click on the label of one e.g. the Hestia feature to instead change the setting in the chat feature.

### Description

This PR fixes this by appending the type of the current sub settings instance as a suffix to the id, which fixes the issue.

@coderabbitai ignore

### Steps for Testing

Prerequisites:
- 1 Instructor/Admin

1. Log in to Artemis
2. Navigate to any Iris settings page (Global, Course, Programming Exercise)
3. Click on the label of any input component in the hestia or code editor settings
4. The correct input component is changed

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

Unchanged

### CODE REVIEW

**Review by rstief — DISMISSED** [review]
Code changes look good. The `sub-settings-update` components also have duplicated ids (inheritTemplate, template-editor...) maybe it would be a good idea to also add a suffix to those?

**Review by kaancayli — DISMISSED** [review]
Changes look good. One potential improvement probably would be extracting  the check`{{ subSettings?.type ?? '' }}` to a getter function.  Rather than using the same expression multiple times, using a function would be less error prone for the future in my opinion. Approved

**Review by RY997 — APPROVED** [review]
Code LGTM

**Review by Gusti2010 — APPROVED** [review]
Manually tested on ts9. Works as expected!

**Review by Strohgelaender — APPROVED** [review]
looks reasonable.

**Review by yassinsws — APPROVED** [review]
Tested, approved

**Pull request merged**
