### PR TITLE
`General`: Hide the keyboard icon from the Monaco editor on Apple devices

### PR DESCRIPTION
**Pull request by pzdr7**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

On Apple devices (e.g. iPad), the Monaco editor displays a keyboard icon as a widget. This looks odd when viewing e.g. the communication page and makes the design less clean, especially when the editor is small:

image

### Description

This PR uses CSS to hide the corresponding element. It also blurs the editor when its widget loses focus, a workaround for an issue that prevents typing in the editor.

### Steps for Testing

Prerequisites:
- 1 User of any role
- 1 Course with communication enabled
- iOS device, e.g. iPad/iPhone. Ideally Safari or Chrome

1. Log in and navigate to the course > communication and open a channel so that the Markdown editor becomes visible.
2. Verify that the icon above is not shown in the editor (see the screenshot above as to what it looks like)

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| monaco-editor.component.ts | 95.58% | ✅ |

### Screenshots

image

## Summary by CodeRabbit

- **New Features**
	- Introduced a new CSS rule to hide the keyboard icon on Apple devices within the Monaco editor.
	- Added a listener to ensure the editor loses focus when clicking outside of it on iOS devices, enhancing focus management.

- **Bug Fixes**
	- Resolved design interference caused by the keyboard icon in the editor.

### CODE REVIEW

**Review by coolchock — APPROVED** [review]
tested both on iPad and iPhone, the keyboard icon is not shown

**Review by sachmii — APPROVED** [review]
Tested on TS3, on iPad and iPhone. Keyboard icon does not show up.

**Review by SimonEntholzer — APPROVED** [review]
Code lgtm :+1:

**Review by edkaya — APPROVED** [review]
code lgtm

**Review by HawKhiem — APPROVED** [review]
Tested on my Ipad on TS3. The keyboard icon doesnt show up

test

**Review by zagemello — COMMENTED** [review]
WhatsApp Image 2024-10-23 at 17 01 05_2c948a13
Found no symbole when trying on IPad on TS4

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS4 with an iPad. Works as expected, mentioned icon is not shown

**Review by krusche — APPROVED** [review]

**Pull request merged**
