### PR TITLE
`Learning analytics`: Allow instructors to import competencies

### LINKED ISSUE #6082: Allow instructors to import learning goals
### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

An improvement could be an import functionality for competencies similar to lectures, exercises or exams.
Instructors could search for existing competencies in other courses, and then import them to their own course.
Ideally, Artemis would then create a _duplicate_ relationship between the two competencies.
This would allow the system to show users their mastery level in a specific competency from their participation in a previous course.
Using this information, users could then even skip certain lecture units or exercises which were meant for repetition.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by terlan98**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Closes #6082 

### Description

The competency management page now shows an import button, enabling instructors (and admin) to import a competency from another course, where the user is at least instructor. Importing an already existing competency or a prerequisite is not allowed.
In addition, some relevant parts of the code containing incorrect variable namings were corrected.

### Steps for Testing

Prerequisites:
- 2 Courses
- 1 Instructor (assigned to both courses)
- 1 Competency (belonging to only one of the courses)

1. Log in to Artemis as an Instructor
2. Go to Course Management
3. Go to the Competencies of a course
4. Click on the '+ Import Competencies' button to open the import modal
5. Competencies already belonging to the course or the prerequisites should be disabled
6. Select a competency to import
7. The selected competency should be added to the course

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Comment |
|------------|-------:|-----:|
| import-component.ts | 95.83% | |
| competency-import.component.ts | 100% | |
| learning-goal-management.component.ts | 82.24% | my changes are covered |
| LearningGoalResource.java | 96% | |
| LearningGoalService.java | 100% | |

### Screenshots

Screenshot 2023-04-04 at 21 11 47
Screenshot 2023-04-17 at 14 23 50

### CODE REVIEW

**Comment by Strohgelaender** [comment]
There is already a lot of duplicated code between the different import components (ExerciseImportComponent, ExamImportComopnent, LectureImportComponent, ExampleSubmissionImportComponen,, etc.). Now the LearningGoalImportComponent introduces another 1:1 copy of these lines.

I wanted to refactor all these different components in the future anyways and remove these large amounts of duplicated code. Therefore I'm fine with keeping this PR like this for now if you want to. However, it would be great if you could have a first look at this already and check if you can re-use at least some already existing parts.

**Comment by terlan98** [comment]
> There is already a lot of duplicated code between the different import components (ExerciseImportComponent, ExamImportComopnent, LectureImportComponent, ExampleSubmissionImportComponent,, etc.). Now the LearningGoalImportComponent introduces another 1:1 copy of these lines.
> 
> I wanted to refactor all these different components in the future anyways and remove these large amounts of duplicated code. Therefore I'm fine with keeping this PR like this for now if you want to. However, it would be great if you could have a first look at this already and check if you can re-use at least some already existing parts.

Thank you for your comment. I created a shared abstract `ImportComponent` to reduce the duplication arising from this PR. Now LearningGoalImportComponent and PrerequisiteImportComponent both extend it. Later, in a separate PR, the component can be adjusted to be used for other components, such as ExerciseImportComponent, ExamImportComponent, etc, reducing the duplication further.

**Review by rriyaldhi — DISMISSED** [review]
Tested on TS 2 and works as expected.

https://user-images.githubusercontent.com/10885503/230837739-f1216acd-514e-4e73-a423-811deba368dd.mov

**Review by frederik-kt — APPROVED** [review]
Tested on TS1. Works as expected.

**Review by tobias-lippert — DISMISSED** [review]
Tested on ts1 Works as expected. Just one small code suggestion.

**Review by tobias-lippert — DISMISSED** [review]
Reapprove

**Review by Strohgelaender — APPROVED** [review]
Thanks for the changes. Let's merge this version and implement an additonal refactoring as follow-up.

**Review by pellumbbaboci — DISMISSED** [review]
Tested on ts1 works as expected 👍

**Review by rriyaldhi — DISMISSED** [review]
Reapprove

**Review by frederik-kt — APPROVED** [review]
Reapprove

**Review by pal03377 — APPROVED** [review]
I reviewed the code. Apart from the things @Strohgelaender mentioned, it looks really good 🎉

**Review by pellumbbaboci — APPROVED** [review]
Tested on ts2, works as expected

**Review by pal03377 — APPROVED** [review]
re-approve code

**Review by tobias-lippert — APPROVED** [review]
Repprove

**Review by Strohgelaender — APPROVED** [review]

**Review by frederik-kt — APPROVED** [review]

**Pull request merged**
