### PR TITLE
`Development`: Minimize messages response payload

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Following #6964 we would like to decrease the payload of the messaging endpoints even further to increase performance. This PR reduces the size of the conversation Object attached to posts.

In a follow-up PR, the conversation object will be set to null completely.

### Description

For GET .../messages, the .hideDetails() method from #6964 is applied to the conversation of the returned posts, including the answers. Also for the endpoints to retrieve the channel for an exercise/lecture this method is invoked.

### Steps for Testing

Prerequisites:
- 1 student
- 1 course with messaging enabled

1. Open the developer tools inspecting the REST calls
2. Visit the messages tab and click on a channel to load messages (write some if necessary)
3. Confirm, that the conversation objects attached to messages in the response contains only minimal information, i.e.  no exercise, no lecture, no exam, no course, no conversation participants
4. The same should apply to the post object attached to answers of a message (write some answers if necessary)
5. Confirm that you can create/edit/delete/react to messages and also create/edit/delete/react to answers
6. Repeat step 5 for the lecture and exercise page for a lecture/exercise with an attached channel and look at the /channel responses as well
7. Repeat step 2-4 for group chats and direct messages

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [BaseExercise.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/BaseExercise.html) | 98% | ✅ |
| [Exercise.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/Exercise.html) | 91% | ✅ |
| [FileUploadExercise.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/FileUploadExercise.html) | 100% | ✅ |
| [FileUploadSubmission.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/FileUploadSubmission.html) | 100% | ✅ |
| [ProgrammingExercise.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/ProgrammingExercise.html) | 92% | ✅ |
| [ProgrammingSubmission.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/ProgrammingSubmission.html) | 100% | ✅ |
| [TextExercise.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/TextExercise.html) | 100% | ✅ |
| [TextSubmission.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/TextSubmission.html) | 98% | ✅ |
| [ModelingExercise.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.modeling/ModelingExercise.html) | 93% | ✅ |
| [ModelingSubmission.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.modeling/ModelingSubmission.html) | 92% | ✅ |
| [DragAndDropQuestion.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/DragAndDropQuestion.html) | 84% | ✅ |
| [DragAndDropQuestionStatistic.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/DragAndDropQuestionStatistic.html) | 98% | ✅ |
| [DragAndDropSubmittedAnswer.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/DragAndDropSubmittedAnswer.html) | 91% | ✅ |
| [MultipleChoiceQuestion.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/MultipleChoiceQuestion.html) | 88% | ✅ |
| [MultipleChoiceQuestionStatistic.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/MultipleChoiceQuestionStatistic.html) | 99% | ✅ |
| [MultipleChoiceSubmittedAnswer.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/MultipleChoiceSubmittedAnswer.html) | 93% | ✅ |
| [QuizExercise.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/QuizExercise.html) | 90% | ✅ |
| [QuizQuestion.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/QuizQuestion.html) | 96% | ✅ |
| [QuizSubmission.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/QuizSubmission.html) | 100% | ✅ |
| [ShortAnswerQuestion.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/ShortAnswerQuestion.html) | 87% | ✅ |
| [ShortAnswerQuestionStatistic.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/ShortAnswerQuestionStatistic.html) | 99% | ✅ |
| [ShortAnswerSubmittedAnswer.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.quiz/ShortAnswerSubmittedAnswer.html) | 87% | ✅ |
| [ConversationMessageResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5239/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.metis/ConversationMessageResource.html) | 97% | ✅ |

### CODE REVIEW

**Review by krusche — APPROVED** [review]

**Review by TimOrtel — APPROVED** [review]
LGTM. Very nice improvement.

**Review by tobias-lippert — APPROVED** [review]
Tested on ts5. Sending messages is still possible and the payload seems to be almost minimal.
I only noticed that the response for /conversations contains the `type` property twice for each conversation and I don't know if this is caused by this PR and can lead to problems.

**Comment by lennart-keller** [comment]
> Tested on ts5. Sending messages is still possible and the payload seems to be almost minimal.
> I only noticed that the response for /conversations contains the `type` property twice for each conversation and I don't know if this is caused by this PR and can lead to problems.

The duplicate `type` property is not introduced by this PR

**Review by Strohgelaender — APPROVED** [review]
code

**Review by krusche — APPROVED** [review]

**Review by tobias-lippert — APPROVED** [review]
Tested on ts5. Still works after removing more content from the response body.

**Review by RY997 — APPROVED** [review]
Tested on ts5, the number of REST calls looks good for me

**Review by laadvo — APPROVED** [review]
tested on ts1, the response payload is now a lot smaller. Writing messages, replies and reacting to them still works

**Pull request merged**
