### PR TITLE
`Quiz exercises`: Improve quiz question points validation

### PR DESCRIPTION
**Pull request by rriyaldhi**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

When an instructor set the question point to 99999999999, the save button was enabled. After clicking the save button, there was Bad Request Error:
image

This error should be prevented by disabling the save button if the points are in invalid range.

### Description

According to the existing implementation in [multiple-choice-question-edit.component.html](https://github.com/ls1intum/Artemis/blob/c5e456e973d3c3145fc52520eb1b15eccaca8dc9/src/main/webapp/app/exercises/quiz/manage/multiple-choice-question/multiple-choice-question-edit.component.html#L23), [drag-and-drop-question-edit.component.html](https://github.com/ls1intum/Artemis/blob/c5e456e973d3c3145fc52520eb1b15eccaca8dc9/src/main/webapp/app/exercises/quiz/manage/drag-and-drop-question/drag-and-drop-question-edit.component.html#L23), and [short-answer-question-edit.component.html](https://github.com/ls1intum/Artemis/blob/c5e456e973d3c3145fc52520eb1b15eccaca8dc9/src/main/webapp/app/exercises/quiz/manage/short-answer-question/short-answer-question-edit.component.html#L23), the max points of each question should be 9999. Therefore, the condition to check if points are greater than 9999 is added to quiz-exercise-validation.directive.ts

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course

1. Log in to Artemis
2. Navigate to Course Administration
3. Select the Course
4. Navigate to Exercises
5. Click **+ Create Quiz** Button
6. Input Quiz Title
7. Add any type of question
8. Input Question Title
9. Verify that the **Save** Button is enabled and no **Invalid Input** sign
10. Modify the Points to 99999999999
11. Verify that the **Save** Button is disabled and there is **Invalid Input** sign

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| quiz-exercise-validation.directive.ts | 91.01% | 97.54% |

### Screenshots

Screenshot 2023-02-10 at 15 55 16

### CODE REVIEW

**Review by PhilipWerz — APPROVED** [review]
Works as expected. Invalid input sign is shown and Save-Button is disabled:

image

Tested on TS1.

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Since we use 9999 in many places, should we make this to one common constant?

**Review by Vinicius-Agreste — APPROVED** [review]
Tested on ts1 and worked as expected. 
image

**Review by danielbode — APPROVED** [review]
Tested on ts1. Works as expected.

**Review by YeetTheFirst21 — APPROVED** [review]
Tested on TS1, looks good.

Screenshot_20230210_050439

**Review by pellumbbaboci — APPROVED** [review]
Tested on ts1 during testing session, works as expected and code looks good.

**Comment by rriyaldhi** [comment]
> Since we use 9999 in many places, should we make this to one common constant?

Constant is created.

**Review by luisa1999 — APPROVED** [review]
Looks fine for me too.

**Review by LiaLism — APPROVED** [review]
Save button is disabled and Invalid input is shown. Tested on ts1.

**Review by JohannesStoehr — APPROVED** [review]
Code looks good to me now

**Pull request merged**
