### PR TITLE
`Development`: Fix gradle run configuration templates

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/)

### Motivation and Context

Since some time, everytime we start IntelliJ, this change comes up. We want to submit this change so it doesn't pop up constantly.
Additionally, during build, a warning logs deprecated usages.

### Description

I started IntelliJ, so the change came up and submitted it. Additionally, I removed the deprecated `--illegal-access` parameter from the templates.

### Steps for Testing

**First test on develop:** 
1. Make sure your git changes are clear and IntelliJ is stopped
2. Start IntelliJ and wait until it's fully started
3. If your git changes are clear, you're group A, if you see the change submitted, you're group B. If you see anything else, let me know.

**Now test on this branch;**

1. Make sure your git changes are clear and IntelliJ is stopped
2. Start IntelliJ and wait until it's fully started
3. Run **new** gradle tasks (e.g. build) and make sure it works and doesn't deviate from any expected behaviour)
4. If no git changes come up, you're test is successful.
5. Group A: If git changes come up, make sure you're IDE version is at least `2022.3.3 Build #IU-223.8836.41`. If you needed to update your IDE, retest, otherwise, let me know.

#### Manual Tests
- [x] Group A 1
- [ ] Group A 2
- [x] Group B 1
- [x] Group B 2

### CODE REVIEW

**Review by jakubriegel — APPROVED** [review]
I'm group A, Version: `Build #IU-231.8770.65`.

Configuration from this branch runs for me and doesn't cause changes

**Review by pal03377 — DISMISSED** [review]
Group B, IntelliJ 2022.3.2, Build `#IU-223.8617.56`. Build works as expected, and now the Git changes are gone. Thanks!

**Review by laadvo — APPROVED** [review]
Group B, Build `#IU-223.8214.52`. Gradle tasks work, no changes get submitted now :+1:

**Review by pal03377 — APPROVED** [review]
Changes look good, I tested Server+Athene and Server+Client and it still works. Also there is still no changed file after starting IntelliJ.

**Review by laadvo — APPROVED** [review]
Reapprove for group B

**Review by jakubriegel — APPROVED** [review]

**Comment by julian-christl** [comment]
I asked multiple times in our dev channel, so if someone had an issue with it, I'd expect them to complain by now.
Therefore, three diverse approvals are enough in my opinion.

**Pull request merged**
