### PR TITLE
`Exam mode`: Fix text exercise feedback view

### LINKED ISSUE #7111: `Text Exercises`: Inline Feedback Items Not Visible to Students During Review
### Describe the bug

When reviewing text exercises, students cannot see which feedback item is associated with which part of their text submission ("block" in the language of the Artemis API).

### To Reproduce

Create a new text exercise, have a student account submit a solution, evaluate the solution using drag and drop feedback items or free-form inline feedback items (i.e. those that are not linked to an assessment instruction; both kinds have the issue).

### Expected behavior

Students should be presented with a view of which part of their submission each feedback item is associated with.

### Screenshots

Nothing to see:

image

### Which version of Artemis are you seeing the problem on?

6.4.1

### What browsers are you seeing the problem on?

Chrome, Firefox

### Relevant log output

The feedback items are properly included in the API response:

<details><summary>API response</summary>

```json
{
  "type": "student",
  "id": 8167815,
  "initializationState": "FINISHED",
  "initializationDate": "2023-08-29T16:05:40.597+02:00",
  "testRun": false,
  "exercise": {
    "type": "text",
    "id": 11180,
    "title": "Test1",
    "maxPoints": 1,
    "bonusPoints": 0,
    "assessmentType": "MANUAL",
    "mode": "INDIVIDUAL",
    "allowComplaintsForAutomaticAssessments": false,
    "allowManualFeedbackRequests": false,
    "includedInOverallScore": "INCLUDED_COMPLETELY",
    "problemStatement": "Please fill out the box",
    "presentationScoreEnabled": false,
    "secondCorrectionEnabled": true,
    "exerciseGroup": {
      "id": 2508,
      "title": "Test",
      "isMandatory": true
    },
    "automaticAssessmentEnabled": false,
    "exerciseType": "TEXT",
    "studentAssignedTeamIdComputed": false,
    "gradingInstructionFeedbackUsed": false,
    "visibleToStudents": true,
    "teamMode": false
  },
  "results": [
    {
      "id": 7082687,
      "completionDate": "2023-08-29T16:13:30.511+02:00",
      "successful": true,
      "score": 100,
      "rated": true,
      "submission": {
        "submissionExerciseType": "text",
        "id": 6686664,
        "submitted": true,
        "type": "MANUAL",
        "submissionDate": "2023-08-29T16:09:12.762+02:00",
        "text": "1.\na) line 1\nline 2\nline 3\n\nb) line 4\nline 5\nline 6\n\nc)\nline 7\nline 8\nline 9\n\n2.\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut viverra velit, non venenatis augue. Integer consequat tortor in justo consectetur tempus. Aliquam in lorem nunc. Etiam tellus neque, ullamcorper laoreet dignissim a, pretium ut elit. Aliquam rhoncus massa id sem auctor facilisis. Mauris quis tortor non ante semper ornare. Nullam consequat, enim ut viverra laoreet, nisl lectus laoreet justo, ac sagittis ex metus id odio. Fusce vitae facilisis eros, sit amet congue orci. Vestibulum consequat, elit ac congue hendrerit, ante nulla molestie urna, quis interdum neque lectus non magna. Nunc tincidunt neque tortor, eget mattis leo venenatis et. Pellentesque lacinia nisl at odio mattis convallis ut a orci. ",
        "blocks": [
          {
            "id": "0a3afb933f6dcb67d7f2992de974bbc892b92dcb",
            "text": "Etiam tellus neque, ullamcorper laoreet dignissim a, pretium ut elit.",
            "startIndex": 260,
            "endIndex": 329,
            "type": "AUTOMATIC"
          },
          {
            "id": "10b7a6c38814a73c2bb0fbdda3ac1892ada468ee",
            "text": "line 9",
            "startIndex": 70,
            "endIndex": 76,
            "type": "AUTOMATIC"
          },
          {
            "id": "115bba2f261b678ddd87adbc53b7122a60924910",
            "text": "b) line 4",
            "startIndex": 28,
            "endIndex": 37,
            "type": "AUTOMATIC"
          },
          {
            "id": "1631f736e0735310c848fcf4b3bbd7ac4a6af2aa",
            "text": "a) line 1",
            "startIndex": 3,
            "endIndex": 12,
            "type": "AUTOMATIC"
          },
          {
            "id": "2028c76f866171a1e0df4e36da56f9820c0360b3",
            "text": "Integer consequat tortor in justo consectetur tempus.",
            "startIndex": 183,
            "endIndex": 236,
            "type": "AUTOMATIC"
          },
          {
            "id": "298c9476dfd9f318d05fa1ed7117d7af47431468",
            "text": "1.",
            "startIndex": 0,
            "endIndex": 2,
            "type": "AUTOMATIC"
          },
          {
            "id": "35bdf3ec93bc508884d34e1a409fb97d63b305e7",
            "text": "line 7",
            "startIndex": 56,
            "endIndex": 62,
            "type": "AUTOMATIC"
          },
          {
            "id": "3b457d9b98e87aa5f582b50ca0cc3ddf41184320",
            "text": "Fusce vitae facilisis eros, sit amet congue orci.",
            "startIndex": 520,
            "endIndex": 569,
            "type": "AUTOMATIC"
          },
          {
            "id": "6447ea0c2742fba6ed066654e96734cc3136e442",
            "text": "Nullam consequat, enim ut viverra laoreet, nisl lectus laoreet justo, ac sagittis ex metus id odio.",
            "startIndex": 420,
            "endIndex": 519,
            "type": "AUTOMATIC"
          },
          {
            "id": "66c5db7ee41d191565b79df0da885ab3421e505c",
            "text": "line 5",
            "startIndex": 38,
            "endIndex": 44,
            "type": "AUTOMATIC"
          },
          {
            "id": "6e4285438c38565311b1198e92bfc5a57854e957",
            "text": "Vestibulum consequat, elit ac congue hendrerit, ante nulla molestie urna, quis interdum neque lectus non magna.",
            "startIndex": 570,
            "endIndex": 681,
            "type": "AUTOMATIC"
          },
          {
            "id": "6ee48a40a71f1559c62c6e295934e36552fa6a6a",
            "text": "line 6",
            "startIndex": 45,
            "endIndex": 51,
            "type": "AUTOMATIC"
          },
          {
            "id": "7fbc2e713dc148dc7b16f3c4c8ea1363e14f3eb6",
            "text": "line 8",
            "startIndex": 63,
            "endIndex": 69,
            "type": "AUTOMATIC"
          },
          {
            "id": "a852fefb8838e479088d6493c619825f2f93386d",
            "text": "line 3",
            "startIndex": 20,
            "endIndex": 26,
            "type": "AUTOMATIC"
          },
          {
            "id": "acc7f0980c3e8d1990fc1e495ea0932dabfa1235",
            "text": "Etiam ut viverra velit, non venenatis augue.",
            "startIndex": 138,
            "endIndex": 182,
            "type": "AUTOMATIC"
          },
          {
            "id": "b6397531552886075206e90dbab6b66b9755ff5e",
            "text": "c)",
            "startIndex": 53,
            "endIndex": 55,
            "type": "AUTOMATIC"
          },
          {
            "id": "bd527a6c265014b9ef0135e3daed458d959e244f",
            "text": "Aliquam in lorem nunc.",
            "startIndex": 237,
            "endIndex": 259,
            "type": "AUTOMATIC"
          },
          {
            "id": "c19a7731124dcda6b85e03df98e046d2e745e943",
            "text": "Mauris quis tortor non ante semper ornare.",
            "startIndex": 377,
            "endIndex": 419,
            "type": "AUTOMATIC"
          },
          {
            "id": "c7447c0da75f8a535a3328f87d1fd3ac357d26cb",
            "text": "line 2",
            "startIndex": 13,
            "endIndex": 19,
            "type": "AUTOMATIC"
          },
          {
            "id": "d46235e9299d30d3f106e4085bc3ef43a3ce8be0",
            "text": "Nunc tincidunt neque tortor, eget mattis leo venenatis et.",
            "startIndex": 682,
            "endIndex": 740,
            "type": "AUTOMATIC"
          },
          {
            "id": "d89a10e59a89df74323b548872bfbb3415ac896f",
            "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "startIndex": 81,
            "endIndex": 137,
            "type": "AUTOMATIC"
          },
          {
            "id": "e2477af39dc0851caba285a136a5f17016d6ea54",
            "text": "Aliquam rhoncus massa id sem auctor facilisis.",
            "startIndex": 330,
            "endIndex": 376,
            "type": "AUTOMATIC"
          },
          {
            "id": "eb59eb6a52253d59da099d0f3ab5821a63d5b1de",
            "text": "Pellentesque lacinia nisl at odio mattis convallis ut a orci.",
            "startIndex": 741,
            "endIndex": 802,
            "type": "AUTOMATIC"
          },
          {
            "id": "f8e1c2303a2163228d5476f9d8f52efee697e659",
            "text": "2.",
            "startIndex": 78,
            "endIndex": 80,
            "type": "AUTOMATIC"
          }
        ],
        "empty": false,
        "durationInMinutes": 3
      },
      "feedbacks": [
        {
          "id": 143563703,
          "detailText": "mhm",
          "hasLongFeedbackText": false,
          "reference": "298c9476dfd9f318d05fa1ed7117d7af47431468",
          "credits": 0.5,
          "positive": true,
          "type": "MANUAL"
        },
        {
          "id": 143563704,
          "hasLongFeedbackText": false,
          "reference": "115bba2f261b678ddd87adbc53b7122a60924910",
          "credits": 1,
          "positive": true,
          "type": "MANUAL",
          "gradingInstruction": {
            "id": 18603,
            "credits": 1,
            "instructionDescription": "very good",
            "feedback": "very very good",
            "usageCount": 1
          }
        },
        {
          "id": 143563705,
          "hasLongFeedbackText": false,
          "reference": "7fbc2e713dc148dc7b16f3c4c8ea1363e14f3eb6",
          "credits": 1,
          "positive": true,
          "type": "MANUAL",
          "gradingInstruction": {
            "id": 18603,
            "credits": 1,
            "instructionDescription": "very good",
            "feedback": "very very good",
            "usageCount": 1
          }
        },
        {
          "id": 143563706,
          "detailText": "yes!!",
          "hasLongFeedbackText": false,
          "reference": "d89a10e59a89df74323b548872bfbb3415ac896f",
          "credits": 1,
          "positive": true,
          "type": "MANUAL"
        },
        {
          "id": 143563707,
          "detailText": "so close :<",
          "hasLongFeedbackText": false,
          "reference": "6e4285438c38565311b1198e92bfc5a57854e957",
          "credits": -0.5,
          "positive": false,
          "type": "MANUAL"
        }
      ],
      "assessmentType": "MANUAL",
      "hasComplaint": false,
      "testCaseCount": 0,
      "passedTestCaseCount": 0,
      "codeIssueCount": 0
    },
    {
      "id": 7082688,
      "completionDate": "2023-08-29T16:14:21.727+02:00",
      "successful": true,
      "score": 100,
      "rated": true,
      "submission": {
        "submissionExerciseType": "text",
        "id": 6686664,
        "submitted": true,
        "type": "MANUAL",
        "submissionDate": "2023-08-29T16:09:12.762+02:00",
        "text": "1.\na) line 1\nline 2\nline 3\n\nb) line 4\nline 5\nline 6\n\nc)\nline 7\nline 8\nline 9\n\n2.\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut viverra velit, non venenatis augue. Integer consequat tortor in justo consectetur tempus. Aliquam in lorem nunc. Etiam tellus neque, ullamcorper laoreet dignissim a, pretium ut elit. Aliquam rhoncus massa id sem auctor facilisis. Mauris quis tortor non ante semper ornare. Nullam consequat, enim ut viverra laoreet, nisl lectus laoreet justo, ac sagittis ex metus id odio. Fusce vitae facilisis eros, sit amet congue orci. Vestibulum consequat, elit ac congue hendrerit, ante nulla molestie urna, quis interdum neque lectus non magna. Nunc tincidunt neque tortor, eget mattis leo venenatis et. Pellentesque lacinia nisl at odio mattis convallis ut a orci. ",
        "blocks": [
          {
            "id": "0a3afb933f6dcb67d7f2992de974bbc892b92dcb",
            "text": "Etiam tellus neque, ullamcorper laoreet dignissim a, pretium ut elit.",
            "startIndex": 260,
            "endIndex": 329,
            "type": "AUTOMATIC"
          },
          {
            "id": "10b7a6c38814a73c2bb0fbdda3ac1892ada468ee",
            "text": "line 9",
            "startIndex": 70,
            "endIndex": 76,
            "type": "AUTOMATIC"
          },
          {
            "id": "115bba2f261b678ddd87adbc53b7122a60924910",
            "text": "b) line 4",
            "startIndex": 28,
            "endIndex": 37,
            "type": "AUTOMATIC"
          },
          {
            "id": "1631f736e0735310c848fcf4b3bbd7ac4a6af2aa",
            "text": "a) line 1",
            "startIndex": 3,
            "endIndex": 12,
            "type": "AUTOMATIC"
          },
          {
            "id": "2028c76f866171a1e0df4e36da56f9820c0360b3",
            "text": "Integer consequat tortor in justo consectetur tempus.",
            "startIndex": 183,
            "endIndex": 236,
            "type": "AUTOMATIC"
          },
          {
            "id": "298c9476dfd9f318d05fa1ed7117d7af47431468",
            "text": "1.",
            "startIndex": 0,
            "endIndex": 2,
            "type": "AUTOMATIC"
          },
          {
            "id": "35bdf3ec93bc508884d34e1a409fb97d63b305e7",
            "text": "line 7",
            "startIndex": 56,
            "endIndex": 62,
            "type": "AUTOMATIC"
          },
          {
            "id": "3b457d9b98e87aa5f582b50ca0cc3ddf41184320",
            "text": "Fusce vitae facilisis eros, sit amet congue orci.",
            "startIndex": 520,
            "endIndex": 569,
            "type": "AUTOMATIC"
          },
          {
            "id": "6447ea0c2742fba6ed066654e96734cc3136e442",
            "text": "Nullam consequat, enim ut viverra laoreet, nisl lectus laoreet justo, ac sagittis ex metus id odio.",
            "startIndex": 420,
            "endIndex": 519,
            "type": "AUTOMATIC"
          },
          {
            "id": "66c5db7ee41d191565b79df0da885ab3421e505c",
            "text": "line 5",
            "startIndex": 38,
            "endIndex": 44,
            "type": "AUTOMATIC"
          },
          {
            "id": "6e4285438c38565311b1198e92bfc5a57854e957",
            "text": "Vestibulum consequat, elit ac congue hendrerit, ante nulla molestie urna, quis interdum neque lectus non magna.",
            "startIndex": 570,
            "endIndex": 681,
            "type": "AUTOMATIC"
          },
          {
            "id": "6ee48a40a71f1559c62c6e295934e36552fa6a6a",
            "text": "line 6",
            "startIndex": 45,
            "endIndex": 51,
            "type": "AUTOMATIC"
          },
          {
            "id": "7fbc2e713dc148dc7b16f3c4c8ea1363e14f3eb6",
            "text": "line 8",
            "startIndex": 63,
            "endIndex": 69,
            "type": "AUTOMATIC"
          },
          {
            "id": "a852fefb8838e479088d6493c619825f2f93386d",
            "text": "line 3",
            "startIndex": 20,
            "endIndex": 26,
            "type": "AUTOMATIC"
          },
          {
            "id": "acc7f0980c3e8d1990fc1e495ea0932dabfa1235",
            "text": "Etiam ut viverra velit, non venenatis augue.",
            "startIndex": 138,
            "endIndex": 182,
            "type": "AUTOMATIC"
          },
          {
            "id": "b6397531552886075206e90dbab6b66b9755ff5e",
            "text": "c)",
            "startIndex": 53,
            "endIndex": 55,
            "type": "AUTOMATIC"
          },
          {
            "id": "bd527a6c265014b9ef0135e3daed458d959e244f",
            "text": "Aliquam in lorem nunc.",
            "startIndex": 237,
            "endIndex": 259,
            "type": "AUTOMATIC"
          },
          {
            "id": "c19a7731124dcda6b85e03df98e046d2e745e943",
            "text": "Mauris quis tortor non ante semper ornare.",
            "startIndex": 377,
            "endIndex": 419,
            "type": "AUTOMATIC"
          },
          {
            "id": "c7447c0da75f8a535a3328f87d1fd3ac357d26cb",
            "text": "line 2",
            "startIndex": 13,
            "endIndex": 19,
            "type": "AUTOMATIC"
          },
          {
            "id": "d46235e9299d30d3f106e4085bc3ef43a3ce8be0",
            "text": "Nunc tincidunt neque tortor, eget mattis leo venenatis et.",
            "startIndex": 682,
            "endIndex": 740,
            "type": "AUTOMATIC"
          },
          {
            "id": "d89a10e59a89df74323b548872bfbb3415ac896f",
            "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
            "startIndex": 81,
            "endIndex": 137,
            "type": "AUTOMATIC"
          },
          {
            "id": "e2477af39dc0851caba285a136a5f17016d6ea54",
            "text": "Aliquam rhoncus massa id sem auctor facilisis.",
            "startIndex": 330,
            "endIndex": 376,
            "type": "AUTOMATIC"
          },
          {
            "id": "eb59eb6a52253d59da099d0f3ab5821a63d5b1de",
            "text": "Pellentesque lacinia nisl at odio mattis convallis ut a orci.",
            "startIndex": 741,
            "endIndex": 802,
            "type": "AUTOMATIC"
          },
          {
            "id": "f8e1c2303a2163228d5476f9d8f52efee697e659",
            "text": "2.",
            "startIndex": 78,
            "endIndex": 80,
            "type": "AUTOMATIC"
          }
        ],
        "empty": false,
        "durationInMinutes": 3
      },
      "feedbacks": [
        {
          "id": 143563708,
          "detailText": "mhm!",
          "hasLongFeedbackText": false,
          "reference": "298c9476dfd9f318d05fa1ed7117d7af47431468",
          "credits": 0.5,
          "positive": true,
          "type": "MANUAL"
        },
        {
          "id": 143563709,
          "hasLongFeedbackText": false,
          "reference": "115bba2f261b678ddd87adbc53b7122a60924910",
          "credits": 1,
          "positive": true,
          "type": "MANUAL",
          "gradingInstruction": {
            "id": 18603,
            "credits": 1,
            "instructionDescription": "very good",
            "feedback": "very very good",
            "usageCount": 1
          }
        },
        {
          "id": 143563710,
          "hasLongFeedbackText": false,
          "reference": "7fbc2e713dc148dc7b16f3c4c8ea1363e14f3eb6",
          "credits": 1,
          "positive": true,
          "type": "MANUAL",
          "gradingInstruction": {
            "id": 18603,
            "credits": 1,
            "instructionDescription": "very good",
            "feedback": "very very good",
            "usageCount": 1
          }
        },
        {
          "id": 143563711,
          "detailText": "yes!!",
          "hasLongFeedbackText": false,
          "reference": "d89a10e59a89df74323b548872bfbb3415ac896f",
          "credits": 1,
          "positive": true,
          "type": "MANUAL"
        },
        {
          "id": 143563712,
          "detailText": "so close :<",
          "hasLongFeedbackText": false,
          "reference": "6e4285438c38565311b1198e92bfc5a57854e957",
          "credits": -0.5,
          "positive": false,
          "type": "MANUAL"
        }
      ],
      "assessmentType": "MANUAL",
      "hasComplaint": false,
      "testCaseCount": 0,
      "passedTestCaseCount": 0,
      "codeIssueCount": 0
    }
  ],
  "submissions": [
    {
      "submissionExerciseType": "text",
      "id": 6686664,
      "submitted": true,
      "type": "MANUAL",
      "submissionDate": "2023-08-29T16:09:12.762+02:00",
      "text": "1.\na) line 1\nline 2\nline 3\n\nb) line 4\nline 5\nline 6\n\nc)\nline 7\nline 8\nline 9\n\n2.\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut viverra velit, non venenatis augue. Integer consequat tortor in justo consectetur tempus. Aliquam in lorem nunc. Etiam tellus neque, ullamcorper laoreet dignissim a, pretium ut elit. Aliquam rhoncus massa id sem auctor facilisis. Mauris quis tortor non ante semper ornare. Nullam consequat, enim ut viverra laoreet, nisl lectus laoreet justo, ac sagittis ex metus id odio. Fusce vitae facilisis eros, sit amet congue orci. Vestibulum consequat, elit ac congue hendrerit, ante nulla molestie urna, quis interdum neque lectus non magna. Nunc tincidunt neque tortor, eget mattis leo venenatis et. Pellentesque lacinia nisl at odio mattis convallis ut a orci. ",
      "blocks": [
        {
          "id": "0a3afb933f6dcb67d7f2992de974bbc892b92dcb",
          "text": "Etiam tellus neque, ullamcorper laoreet dignissim a, pretium ut elit.",
          "startIndex": 260,
          "endIndex": 329,
          "type": "AUTOMATIC"
        },
        {
          "id": "10b7a6c38814a73c2bb0fbdda3ac1892ada468ee",
          "text": "line 9",
          "startIndex": 70,
          "endIndex": 76,
          "type": "AUTOMATIC"
        },
        {
          "id": "115bba2f261b678ddd87adbc53b7122a60924910",
          "text": "b) line 4",
          "startIndex": 28,
          "endIndex": 37,
          "type": "AUTOMATIC"
        },
        {
          "id": "1631f736e0735310c848fcf4b3bbd7ac4a6af2aa",
          "text": "a) line 1",
          "startIndex": 3,
          "endIndex": 12,
          "type": "AUTOMATIC"
        },
        {
          "id": "2028c76f866171a1e0df4e36da56f9820c0360b3",
          "text": "Integer consequat tortor in justo consectetur tempus.",
          "startIndex": 183,
          "endIndex": 236,
          "type": "AUTOMATIC"
        },
        {
          "id": "298c9476dfd9f318d05fa1ed7117d7af47431468",
          "text": "1.",
          "startIndex": 0,
          "endIndex": 2,
          "type": "AUTOMATIC"
        },
        {
          "id": "35bdf3ec93bc508884d34e1a409fb97d63b305e7",
          "text": "line 7",
          "startIndex": 56,
          "endIndex": 62,
          "type": "AUTOMATIC"
        },
        {
          "id": "3b457d9b98e87aa5f582b50ca0cc3ddf41184320",
          "text": "Fusce vitae facilisis eros, sit amet congue orci.",
          "startIndex": 520,
          "endIndex": 569,
          "type": "AUTOMATIC"
        },
        {
          "id": "6447ea0c2742fba6ed066654e96734cc3136e442",
          "text": "Nullam consequat, enim ut viverra laoreet, nisl lectus laoreet justo, ac sagittis ex metus id odio.",
          "startIndex": 420,
          "endIndex": 519,
          "type": "AUTOMATIC"
        },
        {
          "id": "66c5db7ee41d191565b79df0da885ab3421e505c",
          "text": "line 5",
          "startIndex": 38,
          "endIndex": 44,
          "type": "AUTOMATIC"
        },
        {
          "id": "6e4285438c38565311b1198e92bfc5a57854e957",
          "text": "Vestibulum consequat, elit ac congue hendrerit, ante nulla molestie urna, quis interdum neque lectus non magna.",
          "startIndex": 570,
          "endIndex": 681,
          "type": "AUTOMATIC"
        },
        {
          "id": "6ee48a40a71f1559c62c6e295934e36552fa6a6a",
          "text": "line 6",
          "startIndex": 45,
          "endIndex": 51,
          "type": "AUTOMATIC"
        },
        {
          "id": "7fbc2e713dc148dc7b16f3c4c8ea1363e14f3eb6",
          "text": "line 8",
          "startIndex": 63,
          "endIndex": 69,
          "type": "AUTOMATIC"
        },
        {
          "id": "a852fefb8838e479088d6493c619825f2f93386d",
          "text": "line 3",
          "startIndex": 20,
          "endIndex": 26,
          "type": "AUTOMATIC"
        },
        {
          "id": "acc7f0980c3e8d1990fc1e495ea0932dabfa1235",
          "text": "Etiam ut viverra velit, non venenatis augue.",
          "startIndex": 138,
          "endIndex": 182,
          "type": "AUTOMATIC"
        },
        {
          "id": "b6397531552886075206e90dbab6b66b9755ff5e",
          "text": "c)",
          "startIndex": 53,
          "endIndex": 55,
          "type": "AUTOMATIC"
        },
        {
          "id": "bd527a6c265014b9ef0135e3daed458d959e244f",
          "text": "Aliquam in lorem nunc.",
          "startIndex": 237,
          "endIndex": 259,
          "type": "AUTOMATIC"
        },
        {
          "id": "c19a7731124dcda6b85e03df98e046d2e745e943",
          "text": "Mauris quis tortor non ante semper ornare.",
          "startIndex": 377,
          "endIndex": 419,
          "type": "AUTOMATIC"
        },
        {
          "id": "c7447c0da75f8a535a3328f87d1fd3ac357d26cb",
          "text": "line 2",
          "startIndex": 13,
          "endIndex": 19,
          "type": "AUTOMATIC"
        },
        {
          "id": "d46235e9299d30d3f106e4085bc3ef43a3ce8be0",
          "text": "Nunc tincidunt neque tortor, eget mattis leo venenatis et.",
          "startIndex": 682,
          "endIndex": 740,
          "type": "AUTOMATIC"
        },
        {
          "id": "d89a10e59a89df74323b548872bfbb3415ac896f",
          "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          "startIndex": 81,
          "endIndex": 137,
          "type": "AUTOMATIC"
        },
        {
          "id": "e2477af39dc0851caba285a136a5f17016d6ea54",
          "text": "Aliquam rhoncus massa id sem auctor facilisis.",
          "startIndex": 330,
          "endIndex": 376,
          "type": "AUTOMATIC"
        },
        {
          "id": "eb59eb6a52253d59da099d0f3ab5821a63d5b1de",
          "text": "Pellentesque lacinia nisl at odio mattis convallis ut a orci.",
          "startIndex": 741,
          "endIndex": 802,
          "type": "AUTOMATIC"
        },
        {
          "id": "f8e1c2303a2163228d5476f9d8f52efee697e659",
          "text": "2.",
          "startIndex": 78,
          "endIndex": 80,
          "type": "AUTOMATIC"
        }
      ],
      "empty": false,
      "durationInMinutes": 3,
      "results": [
        {
          "id": 7082687,
          "completionDate": "2023-08-29T16:13:30.511+02:00",
          "successful": true,
          "score": 100,
          "rated": true,
          "feedbacks": [
            {
              "id": 143563703,
              "detailText": "mhm",
              "hasLongFeedbackText": false,
              "reference": "298c9476dfd9f318d05fa1ed7117d7af47431468",
              "credits": 0.5,
              "positive": true,
              "type": "MANUAL"
            },
            {
              "id": 143563704,
              "hasLongFeedbackText": false,
              "reference": "115bba2f261b678ddd87adbc53b7122a60924910",
              "credits": 1,
              "positive": true,
              "type": "MANUAL",
              "gradingInstruction": {
                "id": 18603,
                "credits": 1,
                "instructionDescription": "very good",
                "feedback": "very very good",
                "usageCount": 1
              }
            },
            {
              "id": 143563705,
              "hasLongFeedbackText": false,
              "reference": "7fbc2e713dc148dc7b16f3c4c8ea1363e14f3eb6",
              "credits": 1,
              "positive": true,
              "type": "MANUAL",
              "gradingInstruction": {
                "id": 18603,
                "credits": 1,
                "instructionDescription": "very good",
                "feedback": "very very good",
                "usageCount": 1
              }
            },
            {
              "id": 143563706,
              "detailText": "yes!!",
              "hasLongFeedbackText": false,
              "reference": "d89a10e59a89df74323b548872bfbb3415ac896f",
              "credits": 1,
              "positive": true,
              "type": "MANUAL"
            },
            {
              "id": 143563707,
              "detailText": "so close :<",
              "hasLongFeedbackText": false,
              "reference": "6e4285438c38565311b1198e92bfc5a57854e957",
              "credits": -0.5,
              "positive": false,
              "type": "MANUAL"
            }
          ],
          "assessmentType": "MANUAL",
          "hasComplaint": false,
          "testCaseCount": 0,
          "passedTestCaseCount": 0,
          "codeIssueCount": 0
        },
        {
          "id": 7082688,
          "completionDate": "2023-08-29T16:14:21.727+02:00",
          "successful": true,
          "score": 100,
          "rated": true,
          "feedbacks": [
            {
              "id": 143563708,
              "detailText": "mhm!",
              "hasLongFeedbackText": false,
              "reference": "298c9476dfd9f318d05fa1ed7117d7af47431468",
              "credits": 0.5,
              "positive": true,
              "type": "MANUAL"
            },
            {
              "id": 143563709,
              "hasLongFeedbackText": false,
              "reference": "115bba2f261b678ddd87adbc53b7122a60924910",
              "credits": 1,
              "positive": true,
              "type": "MANUAL",
              "gradingInstruction": {
                "id": 18603,
                "credits": 1,
                "instructionDescription": "very good",
                "feedback": "very very good",
                "usageCount": 1
              }
            },
            {
              "id": 143563710,
              "hasLongFeedbackText": false,
              "reference": "7fbc2e713dc148dc7b16f3c4c8ea1363e14f3eb6",
              "credits": 1,
              "positive": true,
              "type": "MANUAL",
              "gradingInstruction": {
                "id": 18603,
                "credits": 1,
                "instructionDescription": "very good",
                "feedback": "very very good",
                "usageCount": 1
              }
            },
            {
              "id": 143563711,
              "detailText": "yes!!",
              "hasLongFeedbackText": false,
              "reference": "d89a10e59a89df74323b548872bfbb3415ac896f",
              "credits": 1,
              "positive": true,
              "type": "MANUAL"
            },
            {
              "id": 143563712,
              "detailText": "so close :<",
              "hasLongFeedbackText": false,
              "reference": "6e4285438c38565311b1198e92bfc5a57854e957",
              "credits": -0.5,
              "positive": false,
              "type": "MANUAL"
            }
          ],
          "assessmentType": "MANUAL",
          "hasComplaint": false,
          "testCaseCount": 0,
          "passedTestCaseCount": 0,
          "codeIssueCount": 0
        }
      ]
    }
  ],
  "student": {
    "id": 99999,
    "createdDate": "2021-02-02T17:33:50Z",
    "login": "XXXXX",
    "firstName": "XXXXX",
    "email": "XXXXX",
    "activated": true,
    "langKey": "en",
    "lastNotificationRead": "2023-06-22T15:34:39.416+02:00",
    "internal": false,
    "name": "XXXXX",
    "participantIdentifier": "XXXXX",
    "deleted": false
  },
  "participantIdentifier": "XXXXX",
  "participantName": "XXXXX"
}
```

</details>

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Fixes #7111

### Description
The client checks the exam publication date to determine if the result should be shown to the student. This information was missing from the server response.

### Steps for Testing
Prerequisites:
- 1 Exam with a corrected text exericse
- 1 Student

1. View the summary and press view result for the text exercise
2. Check that feedback is visible

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by terlan98 — APPROVED** [review]
Tested on TS4. Feedbacks are now visible. Thanks for the fix 👍

**Review by JohannesStoehr — APPROVED** [review]
Approve code changes

**Comment by just-max** [comment]
Thank you for this fix on this issue!

> The client checks the exam publication date to determine if the result should be shown to the student.

Does this mean that the API provides the result to the student before the exam review period has started?

**Comment by Strohgelaender** [comment]
@just-max No, I fixed such cases in a previous PR a few months ago. The client just double-checks the dates as an additional safety measure. We could also remove that client sided check since it's currently redundant, however I'd like to stay save in such cases (maybe a future developer does not filter the results on a different endpoint, then the client should not show everything directly).

**Pull request merged**
