### PR TITLE
`Assessments`: Fix an issue with deactivated complaint button when more feedback requests are disabled

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.(https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [X] I added multiple **unit** tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

1. When more feedback requests were disabled the complaint button was visible for students but disabled
2. The edge case for manually corrected programming exercises with automatic feedback and complaints was not handled. Meaning students could complain on the automatic assessment if the tutors were too slow.

### Description

I added and fixed some conditionals to match the requirements and fix the issues. I also added some unit tests covering these sections.
I also did some syntactical refactoring to make the code easier to understand.

### Steps for Testing

Omitted because already tested.

#### Code Review
- [x] Review 1
- [X] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

complaints-student-view.component.ts: 76.42% | 94.44%

### CODE REVIEW

**Review by JohannesStoehr — DISMISSED** [review]
Tested on TS2 and found no issues.
The code changes look good as well.

Thanks for the quick fix!

**Review by willergeorg — DISMISSED** [review]
Tested on TS2. Works as expected for me.

**Review by MDK5 — APPROVED** [review]
Code looks good to me with the latest changes :+1:

**Review by JohannesStoehr — APPROVED** [review]
Looked through the code again, the changes look goo.
Re-approve

**Review by willergeorg — APPROVED** [review]
Re-approve.

**Pull request merged**
