### PR TITLE
New model type: Flowchart

### PR DESCRIPTION
**Pull request by iozbeyli**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
This is a new diagram type that is used by several courses.
Implementation is based on https://en.wikipedia.org/wiki/Flowchart

### Steps for Testing

!!!IMPORTANT: After testing the pr, delete the flowchart exercises. Otherwise you cannot test anything else because of the object not found error or transalation not found.

1. Login as instructor
2. Create a modeling exercise with flowchart
3. Create an exam with the that modeling exercise
4. Create another modeling exercise with flowchart as team exercise
5. Login as student
6. Solve modeling exercise as student
7. Attend exam and solve the exercise as that
8. Solve team modeling exercise and try collaboration functionality
9. Login as tutor
10. Assess the modeling exercises
11. Login as student look at your result

Additionally, look for modeling related parts of Artemis to check if anything is missing or broken.

### Test Coverage

Flowchart | 100% (1/1) | 100% (9/9) | 96% (26/27)
FlowchartDecision | 100% (1/1) | 66% (4/6) | 88% (15/17)
FlowchartFlowline | 100% (1/1) | 50% (4/8) | 70% (19/27)
FlowchartFunctionCall | 100% (1/1) | 66% (4/6) | 88% (15/17)
FlowchartInputOutput | 100% (1/1) | 66% (4/6) | 88% (15/17)
FlowchartProcess | 100% (1/1) | 66% (4/6) | 88% (15/17)
FlowchartTerminal | 100% (1/1) | 66% (4/6) | 88% (15/17)
UMLModelParser | 100% (2/2) | 100% (51/51) | 97% (480/493)

#### Creating flowchart exercise
out-28

#### Solving flowchart exercise
out-29

#### Assessing flowchart exercise
out-30

#### Viewing assessment result
out-31

### CODE REVIEW

**Review by airelawaleria — DISMISSED** [review]
Tested with @marvinchimeka @simonzilker @JohannesWeiss 
Works as expected

**Review by marvinchimeka — APPROVED** [review]

**Review by simonzilker — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]

**Review by valeriebucher — DISMISSED** [review]
Works as described!

**Review by EneaGore — APPROVED** [review]

**Review by LudwigWeide — APPROVED** [review]

**Review by JannisBittlmayer — CHANGES_REQUESTED** [review]
Tested with @FlorianStang on TS1, works as intended except for one issue:
When a participant does not start the exercise and the due date is over, they can still click on "Start exercise". They cannot submit anything but the status changes to "You have missed the deadline." for the whole team even if the assessment was successful. This is not the true state though, since the points are still registered on the statistics page. This does not seem to be an issue with non-flow-chart modeling exercises (we tested class diagrams on this branch and production))

**Review by FlorianStang — DISMISSED** [review]
Tested with @JannisBittlmayer see above.

**Review by SimonEntholzer — COMMENTED** [review]
I checked the code, it looks pretty good. Since appollon/compass isn't my area though, I didn't understand all parts of the code sadly.

**Comment by iozbeyli** [comment]
> Tested with @FlorianStang on TS1, works as intended except for one issue regarding team exercises:
> When a participant does not start the exercise and the due date is over, they can still click on "Start exercise". They cannot submit anything but the status changes to "You have missed the deadline." for the whole team even if the assessment was successful. This is not the true state though, since the points are still registered on the statistics page. This does not seem to be an issue with non-flow-chart modeling exercises (we tested class diagrams on this branch and production))

@JannisBittlmayer The problem occurs in develop as well and I was able to reproduce it with class diagram. Can you create an issue for this and assign me?

**Comment by JannisBittlmayer** [comment]
> @JannisBittlmayer The problem occurs in develop as well and I was able to reproduce it with class diagram. Can you create an issue for this and assign me?

Created a the issue https://github.com/ls1intum/Artemis/issues/2786

**Review by philgabr — APPROVED** [review]
Everything works as intended. :+1:

Also I didn't encounter the issue mentioned by @JannisBittlmayer:
image

**Review by airelawaleria — APPROVED** [review]

**Review by DenizShabani — APPROVED** [review]
LGTM

**Review by krusche — APPROVED** [review]

**Pull request merged**
