### PR TITLE
`General`: Fix modal background color

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context

Follow-up to #6695: Modal background is incorrect in light theme.
image

### Description

Change background color of modals in light theme to white.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Course with Communication enabled

1. Log in to Artemis
2. Navigate to the courses communication tab
3. Click the "new post" button
4. Make sure that the modal has the correct background color in both themes and that everything is well readable

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by RY997 — APPROVED** [review]
Tested on ts4, worked well

**Review by undernagruzez — APPROVED** [review]
tested on ts6, works as expected

**Review by MichaelOwenDyer — APPROVED** [review]
Fixes the issue 👍🏽

**Review by SolizerCodes — APPROVED** [review]
Works as expected 👍

**Pull request merged**
