### PR TITLE
`Programming exercises`: Fix the position of the save button of the problem statement editor

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

With #6793 the height of the utility buttons from the markdown editor component got reduced. This caused the save button next to the problem statement editor for programming exercises to overlap with the text field.

### Description

I changed the position of the save button by moving it a few pixels upwards. Also, I reduced the height of the domain specific buttons like `Color`, `Formula`, and `Task` to make it consistent with all other places where the markdown editor is used.

The save button can overlap with other buttons, but this is an old issue that will not be fixed in this PR.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course programming exercise
- 1 Exam with a programming exercise

1. Edit the course programming exercise
2. Check that the save button does not overlap with the problem statement input field
3. Edit the exam programming exercise
4. Check that the save button does not overlap with the problem statement input field

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Same as develop

### Screenshots

before: 
before

after:
after

### CODE REVIEW

**Review by DemjenDavid — DISMISSED** [review]
image
image
Tested on ts3, this is an extreme case there is a minor overlap when changing window size but other than that it works well

**Review by SabrinaGlatz — DISMISSED** [review]
tested on ts4, works as expected

**Review by eceeeren — DISMISSED** [review]
Tested on TS1, works well!

**Review by dakennguyen — DISMISSED** [review]
tested on ts1, works as expected, but like David mentioned, maybe we could improve this situation too
image

**Review by fschoenberger — APPROVED** [review]
Tested on TS3, looks good.

**Review by DominikRemo — CHANGES_REQUESTED** [review]
The save button does not overlap with the text field anymore :)

However, the "Insert Test Case" dropdown is now misaligned and the save button can cover the other controls.

Tested on ts1 with chrome and safari
Bildschirmfoto 2023-07-11 um 18 51 31
Bildschirmfoto 2023-07-11 um 18 49 34

**Review by DominikRemo — APPROVED** [review]
Tested on ts1. 
The dropdown is now correctly aligned. The overlap of the save button is not part of this PR

**Review by MaximilianAnzinger — APPROVED** [review]
LGTM
Although the absolute positioning `-16px` seems "interesting" :)

**Review by laadvo — APPROVED** [review]
Tested on ts1, the save button does not overlap the editor anymore

**Review by asliayk — APPROVED** [review]
tested on ts2, works as expected

**Review by Mtze — APPROVED** [review]

**Pull request merged**
