### PR TITLE
`Development`: Fix flaky e2e tests

### PR DESCRIPTION
**Pull request by SimonEntholzer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

A few e2e server tests are still flaky. Here is an overview: https://confluence.ase.in.tum.de/display/ArTEMiS/E2E+Playwright+Tests

### Description

This PR tries to find the core causes of the flakiness, and fix it. For those, where the cause could not yet identified by 100 % I added additional steps, that help finding the issue if the flakiness continues.

### Steps for Testing

Prerequisites:
Start client and server locally, and run all e2e tests with
`npm run playwright:open`

Check the e2e runs on bamboo below.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Enhanced test suite for student exams with the addition of a new student.
	- New methods to facilitate navigation to exercise submissions and verify student submissions.
	- Improved tutor assessment flow by ensuring proper login and submission visibility.
	- Introduced a new exam participation step with the `almostStartExam` method.

- **Bug Fixes**
	- Simplified login process in programming exercise management tests.

- **Tests**
	- Added a new test suite to intentionally fail for testing purposes.

### CODE REVIEW

**Review by sarpsahinalp — APPROVED** [review]
Code lgtm

**Review by cremertim — APPROVED** [review]
Lgtm

**Review by coolchock — APPROVED** [review]
tested locally, tests passed

**Review by JohannesStoehr — APPROVED** [review]
Changes look good to me

**Pull request merged**
