### PR TITLE
`Programming exercises`: Fix updating scores when a manual result exists

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
In ITP we encountered an issue when changing test cases after the due date. When the student complained before the updated test cases were run, the new test run was not correctly reflected in the score. Whilst the feedback showed the new test results, the result itself was still using the old score:
grafik
grafik

### Description
Submitting a complaint or additional feedback request already counts as a manual result.

In these cases, the new programming feedback gets merged with the potential existing manual feedback. This method was not updating the result, only the related feedback objects. This PR changes this behavior.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise with Complaints enabled

1. Student: Submit something to the PE
2. Student: Submit a complaint after the due date
3. Instructor: Change the test cases and trigger all builds (Participations -> Trigger All)
4. Verify that the Student's result got updated (correct score, correct test case count)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by simon-hng — APPROVED** [review]
Code

**Review by danielbode — APPROVED** [review]
The bug is fixed. Tested on ts1.

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Review by Santia-go — APPROVED** [review]
Tested on TS1
Working as expected. The grade changes after a Trigger all when the tests are modified. 

The grade before edit the tests
Screenshot 2023-02-06 at 15 54 18


After a minor change in the tests. 
Screenshot 2023-02-06 at 15 55 12

**Pull request merged**
