### PR TITLE
`Assessment`: Fix an issue where deleting one unsaved inline feedback deletes all unsaved feedbacks

### LINKED ISSUE #7709: `Programming exercises`, `Manual assessment`: Deleting a single unsaved comment deletes all unsaved comments
### Describe the bug

When adding multiple inline comments during manual assessment and then deleting one of them all unsaved comments are deleted.

### To Reproduce

1. As tutor/instructor assess a programming exercise.
2. Add a few inline comments in the code editor.
3. Delete one of those comments.
4. All comments are deleted since they are unsaved. 

### Expected behavior

Only the single comment is removed.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.7.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

### Additional context

relevant code that should be fixed:
https://github.com/ls1intum/Artemis/blob/d3cf5d0d6b8558d2a0f929af9602b9b7432290f9/src/main/webapp/app/exercises/programming/shared/code-editor/ace/code-editor-ace.component.ts#L640

Since all unsaved comments have ID `undefined`, all of them are removed. The deletion filter should also compare other attributes of the feedback (file, line, text) to make sure it is the right one.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by chrisknedl**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Closes #7709 

### Description

To correctly identify the feedback that should be deleted before it has been saved for the first time, the line, file and content of the feedback are now taken into consideration in addition to the id.

### Steps for Testing

Prerequisites:
- 1 Tutor/Instructor
- 1 Programming Exercise with manual assessment

1. As tutor/instructor assess a programming exercise.
2. Add a few inline comments in the code editor.
3. Delete one of those comments.
4. The other comments should still be there.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by bassner** [comment]
Hijacking this PR for a short test, will revert afterwards :D

**Review by LenaKahle — DISMISSED** [review]
Approve, tested on legacy ts11.

**Comment by Ceiridge** [comment]
Tested on ts3, works as expected
image
image

**Review by b-fein — DISMISSED** [review]
Code change look good.

**Review by Gusti2010 — DISMISSED** [review]
tested on ts11_Legacy. Works as expected!

**Comment by MaximilianJG** [comment]
Tested on ts2. LGTM!

**Review by xHadie — APPROVED** [review]
_Manually tested on TS3_
Works as described!

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts5. Worked as expected.

**Review by georgyia — DISMISSED** [review]
tested manually on ts2, works as expected

**Review by vinceclifford — APPROVED** [review]
Tested on TS2, works as expected

**Review by AntonGeTUM — DISMISSED** [review]
Tested on ts11, works as described

**Review by krusche — APPROVED** [review]

**Comment by krusche** [comment]
just waiting for the checks to pass, then I will merge this PR

**Pull request merged**
