### PR TITLE
`Development`: Fix layout of statistics tab

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Currently, the layout of the statistics tab for students is distorted. The old layout is reset with this PR.
### Description

There was an empty `div` that was moving the doughnut chart to the center of the page. I removed it in order to recover the old layout.
### Steps for Testing

Prerequisites:
- 1 Student that is enrolled in a course

1. Log in to Artemis
2. Click on the course card header
3. Navigate to the statistics tab of the course
4. Make sure it has the usual layout

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Nothing changed
### Screenshots

The current distorted layout:
image

The change in this PR:
image

### CODE REVIEW

**Review by baranimo7 — APPROVED** [review]
tested on ts2, works as expected

**Review by Bofan-Zhu — APPROVED** [review]
Tested on ts1 and everything looks fine to me.

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on TS2 and it works as expected

**Review by MerlinMehmed — APPROVED** [review]
Tested on TS1, looks good. Code changes look god as well.

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
