### PR TITLE
`Development`: Increase test coverage

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

### Description

This PR adds some missing tests for new features (auxiliary repositories, endpoints, etc.) and to increase code coverage in general. It also fixes a re-occuring failing local CI postgres test.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

## Summary by CodeRabbit

- **New Features**
  - Modified `ResultRepository` interface to fetch the latest result by participation ID.
  - Enhanced local CI service with listener management and trigger type specification.
  - Expanded local VC service to handle different repository types during push events.

- **Improvements**
  - Set up dedicated result paths for static code analysis tests.

- **Testing**
  - Added new test cases for local CI resource management and handling of auxiliary repositories.
  - Refined existing integration tests with additional setup for instructors and repositories.

- **Bug Fixes**
  - Addressed redundant method calls in integration tests.

- **Refactor**
  - Adjusted access levels and extended functionality in integration test classes.
  - Streamlined import statements in test files.

### CODE REVIEW

**Review by milljoniaer — APPROVED** [review]
demonstrated in testing session, works as expected 👍

**Review by reschandreas — DISMISSED** [review]
code lgtm, thanks for improving the coverage 🚀

**Review by mateusmm01 — DISMISSED** [review]
Code LGTM !

**Review by rstief — DISMISSED** [review]
Code looks good 👍

**Review by rstief — APPROVED** [review]
reapprove

**Review by mateusmm01 — APPROVED** [review]
Reapprove after merge conflict

**Review by milljoniaer — APPROVED** [review]
Reapprove after code changes

**Review by reschandreas — APPROVED** [review]
reapprove after code changes

**Pull request merged**
