### PR TITLE
`Exam mode`: Remove "Online Code Editor" header

### PR DESCRIPTION
**Pull request by pzdr7**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

On the exam, we had a header for the "Online Code Editor" even though we had that nowhere else with the code editor. This was inconsistent. Also, submission policies were causing a bit of whitespace.

### Description

Reworked the formatting of the header in programming exercises, including submission policies.
We now display everything in a single line for exams and regular programming exercises.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Instructor
- 1 Programming exercise with the online code editor enabled and a submission policy.
- 1 Programming exercise with the online code editor enabled and no submission policy.

1. As the student, log in to Artemis
2. Navigate to each exercise, open the online editor, and verify that the header and actions look good
3. As the instructor, log in to Artemis
4. Navigate to course management > your course > exercises > click on the name of one of the programming exercises
5. Click "Edit in Editor"
6. Verify that the header looks okay

#### Exam Mode Testing

Prerequisites:
- 1 Student
- 1 Exam with 6 exercise groups (**Note**: For easier testing on TS3, you can use the exam "[Programming Header Exam](https://artemis-test3.artemis.cit.tum.de/courses/20/exams/48)", e.g. as test user 1.)
  - 1 Programming exercise, offline IDE only, no submission policy
  - 1 Programming exercise, offline IDE only, with a submission policy
  - 1 Programming exercise, online code editor only, no submission policy
  - 1 Programming exercise, online code editor only, with a submission policy
  - 1 Programming exercise, both online/offline, no submission policy
  - 1 Programming exercise, both online/offline, with a submission policy

1. Log in to Artemis
2. Participate in the exam as a student
3. Navigate through the exercises and check that header / UI looks fine for each exercise.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Exam Mode Test
- [x] Test 1
- [ ] Test 2

### Screenshots

Video showing all variants:

https://github.com/user-attachments/assets/d1df1298-9f2f-441a-aab8-5494908ea430

## Summary by CodeRabbit

- **New Features**
  - Enhanced programming exam submission page with improved layout and conditional rendering for online code editor and offline IDE functionality.
  - Updated the code editor's submission policy section with new structural and styling adjustments.

- **Localization**
  - Updated German and English descriptions related to IDE usage, changing button labels from "clone" to "Code".

### CODE REVIEW

**Review by EneaGore — DISMISSED** [review]
Changes lgtm on TS3.

**Review by JohannesStoehr — APPROVED** [review]
Code looks good to me

**Review by edkaya — APPROVED** [review]
Tested on ts3, changes lgtm

**Review by EneaGore — APPROVED** [review]
Retested on TS3. Both Exam mode and normal programming  exercises headers are displayed as expected.

**Review by Jan-Thurner — APPROVED** [review]
Code LGTM

**Review by JohannesStoehr — APPROVED** [review]
Reapprove

**Review by krusche — APPROVED** [review]

**Pull request merged**
