### PR TITLE
`Programming exercises`: Fix Bamboo permissions for Bamboo v8.1.3

### PR DESCRIPTION
**Pull request by mallgaier**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).

### Motivation and Context
After the Atlassian update (#4803 ), in particular the Bamboo 8.1.3 update, the creation of programming tasks was no longer possible because the `CREATEREPOSITORY` permission was missing. 

### Description
This PR adds the `CREATEREPOSITORY` Permission as an Enum to the `CIPermissions`. 
Additionally, the permission is granted within the `ProgrammingExerciseService.java` when creating an exercise. 
The `BambooRequestMockProvider.java` also had to be modified in order for the server tests to work again with the correct parameters.

### Steps for Testing

Prerequisites:
- 1 Instructor (or 1 Editor)
- Update to Bamboo 8.1.3 (see #4803 for your local setup)

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a new programming exercise and make sure that the creation is successful. 

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by Dominik-Weinzierl — COMMENTED** [review]
Works locally with Atlassian Suite as expected :+1:

**Review by Strohgelaender — APPROVED** [review]
Tested locally, creating new exercise works again. 👍

**Review by julian-christl — APPROVED** [review]
Fix works, thanks for the implementation.
Code approved.

**Review by Strohgelaender — DISMISSED** [review]

**Review by ole-ve — APPROVED** [review]
Worked fine for me, good job 👍

**Review by Dominik-Weinzierl — DISMISSED** [review]

**Review by ole-ve — CHANGES_REQUESTED** [review]
I managed to find the source for the failing server tests:
When creating the mock bamboo server, the new permission (`CREATEREPOSITORY`) is missing.

The change is required in `BambooRequestMockProvider::mockGiveProjectPermissions` (line 153-161):
```
final var instructorURI = buildGivePermissionsURIFor(projectKey, exercise.getCourseViaExerciseGroupOrCourseMember().getInstructorGroupName());
mockServer.expect(requestTo(instructorURI)).andExpect(method(HttpMethod.PUT))
        .andExpect(content().json(mapper.writeValueAsString(List.of("CREATE", "READ", "ADMINISTRATION", "CREATEREPOSITORY")))).andRespond(withStatus(HttpStatus.NO_CONTENT));

if (exercise.getCourseViaExerciseGroupOrCourseMember().getEditorGroupName() != null) {
        final var editorURI = buildGivePermissionsURIFor(projectKey, exercise.getCourseViaExerciseGroupOrCourseMember().getEditorGroupName());
        mockServer.expect(requestTo(editorURI)).andExpect(method(HttpMethod.PUT))
            .andExpect(content().json(mapper.writeValueAsString(List.of("CREATE", "READ", "ADMINISTRATION", "CREATEREPOSITORY")))).andRespond(withStatus(HttpStatus.NO_CONTENT));
}
```

**Review by b-fein — CHANGES_REQUESTED** [review]
The failing tests are definitely related: I’d expect that there is a method probably called `mockGiveProjectPermissions` somewhere in the BambooMockProvider where the newly added permission has to be added to the expected requests.

**Review by Strohgelaender — APPROVED** [review]

**Review by ole-ve — APPROVED** [review]

**Review by b-fein — APPROVED** [review]

**Review by julian-christl — APPROVED** [review]

**Pull request merged**
