### PR TITLE
Add Edit, Participations and Configure Grading Buttons

### LINKED ISSUE #611: Allow "Open in new Tab" (CTRL / CMD click or middle mouse button)
### Is your feature request related to a problem?

I sometimes want to compare some submissions/assessments or just quicky open multiple exercise dashboards (for example just before a tutor group session). 

But it's a very tedious task, for each page I'd like, I need to open a new Artemis instance manually in a new tab because right click > "open in new tab" or control-clicking the link doesn't work on any link of Artemis.

### Describe the solution you'd like
When I hold CMD (mac) or CTRL and click on a button or link, I'd like to have it to open in a new tab rather than in the current tab.

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
The instructor actions in the exercise normal course view are very useful, and already offer shortcuts to some pages without loading the complete course management page each time and searching for the correct exercise.

In this PR, we want to add some more buttons that are frequently used and are "missing" in the current version:
- **"Edit"-Button**
  _Use Case: an instructor reads or looks up the exercise in the course view and found mistakes in the problem statement (e.g. spelling errors). The edit button allows to quickly edit the problem statement and make corrections. Exercise release date, due date and so on can also be adjusted quickly._
- **"Participations"-Button** (for programming exercises only)
  _Use Case: allows quickly checking if and how students participated, and investigate problems. An instructor could also trigger a rebuild for a particular student participation if necessary. There are many scenarios related to that based on our (PGdP-ÜL) experience. This would make it just a bit more pleasant._
- **"Configure Grading"-Button** (for programming exercises only)
  _Use case: quick navigation between exercise editing, scores, participations and grading. Instructors can adjust grading based on the scores and automatic feedback that students got, or look up the problem statement again and adjust the test cases (or reverse). This together with the others is estimated to "increase the quality of life" as an instructor of a course with a lot of programming exercises._

In summary, most points just improve navigation centered around issues related to a single exercise at a time. The main reason this is required is that neither #611 is implemented nor does the course management load quickly while restoring the old view (exercise sorting, scroll-position), making it necessary find the exercise for each switch "from scratch".

#### Alternatives
- Restore the course management quickly and the way it has been left when navigating back in the browser.
- Resolve issue #611, although this might still be slower due to full page reload.
- Offer some kind of quick navigation / quick search for exercises, this would fit really well to #2097. But this could also be some sort of extra page just for quick navigation and re-routing related to a single exercise.

### Description
1. Added an edit button for all exercise types and participations and configure
grading only for programming exercises because they are mostly needed
there.
2. Changed all buttons to the design from the course exercise management page.
3. Renamed "Configure Grading" buttons to "Grading" for programming exercises.

### Steps for Testing
_Short version: test that all "Instructor actions" buttons work._

0. You need to be instructor in a course with at least one of each exercise type.
1. Check that edit opens the edit page for each exercise type.
    For quiz exercise that are already over, you should just see that editing is not possible anymore.
2. All exercises should still have a "Scores" button. Check that the "Scores" button leads to the exercise's scores.
3. Check that only for programming exercises the "Participations" and "Configure Grading" are displayed.
    For programming exercises, the "Participations" should redirect to the exercise's participations and "Configure Grading" to the grading configuration page of the exercise.
4. Modelling exercises have "Submissions" and "Statistics" buttons and text exercises have the "Submissions" button as well.
   Check that the "Submissions" button leads to the submissions for both types and that the "Statistics" page can be opened in case of modelling exercises.

### Screenshots

- **Modelling Exercise Example:**
   image
- **Programming Exercise Example:**
   image

### CODE REVIEW

**Review by philippbauch — DISMISSED** [review]
Looks good to me!

**Comment by krusche** [comment]
Great idea 👍 

Can you call it `Grading` instead of `Configure Grading`? (we should change this in the course administration page as well) Then the buttons do not get too large.
How does it look on small devices? Please make sure that it does not overlap.
I guess it would be nice to use the same button colors and font-awesome images as in the course administration page, then we could also just collapse the buttons on smaller screens (similar how it is done in the course administration page)

**Comment by MaisiKoleni** [comment]
> Great idea 👍
> 
> Can you call it `Grading` instead of `Configure Grading`? (we should change this in the course administration page as well) Then the buttons do not get too large.
> How does it look on small devices? Please make sure that it does not overlap.
> I guess it would be nice to use the same button colors and font-awesome images as in the course administration page, then we could also just collapse the buttons on smaller screens (similar how it is done in the course administration page)

Currently, we just seem to hide these option on small displays. I can change the name to "Grading" and will have a look how the buttons look when we use them there.

**Comment by MaisiKoleni** [comment]
@krusche should I also remove the "Instructor Actions" label? I guess when we use the same buttons, it should be clear to instructors what they do (and if space is so much of a concern, this would save some more).

**Comment by MaisiKoleni** [comment]
I now implemented the requested changes. 

On small displays, the elements wrap into new lines, which looks a bit strange. However, if enough space is taken away, the buttons will collapse into the "icons only" mode. Mainly the layout of the parent component is a bit weird here.

**Comment by krusche** [comment]
Thanks. I would leave the Instructor actions label. Otherwise it might be confusing for other instructors which are not that experienced

**Review by stefanwaldhauser — APPROVED** [review]
Looked through the code and tested it for all the exercise types. Only found the `Edit` page for quiz exercises that are past the due date a little bit weird looking but I guess this is not part of this PR. Nice productivity change @MaisiKoleni !
image

**Comment by MaisiKoleni** [comment]
@stefanwaldhauser concerning the quiz exercises, this is intended, see testing point 2. One could consider to put re-evaluate there, but I wanted to focus on actions that are needed frequently which is not the case for re-evaluate as far as I know.
I think it is good to leave the button so that you as instructor see why editing is not allowed anymore, but I guess it could be a bit more prominent than darkening the form and having a little message about that just at the bottom.

**Review by tiffca — APPROVED** [review]
Tested in artemis test server 1 - changes look really good and all functions work smoothly/as expected. I'm able to edit and navigate back and forth through the different options seamlessly for all exercise types. Quiz not editable if completed, as expected. Nice change!

**Review by philippbauch — DISMISSED** [review]
Good job, the buttons also collapse into icon-mode on smaller displays 👍 
Screenshot 2020-10-13 at 00 14 36

**Review by kloessst — CHANGES_REQUESTED** [review]
Works fine. Could you change the Grading button also for exam mode, so that we are consistent everywhere. It's in `exam-exercise-row-buttons.component.html`

**Review by kloessst — DISMISSED** [review]
Good idea and nice execution. Well done!

**Review by FrankeLukas — DISMISSED** [review]
No issues encountered.

**Review by krusche — CHANGES_REQUESTED** [review]
@MaisiKoleni quiz exercises should not have an edit button after they have been finished. Please either add the `re-evaluate` or remove `edit` button in this case.

**Comment by MaisiKoleni** [comment]
> @MaisiKoleni quiz exercises should not have an edit button after they have been finished. Please either add the `re-evaluate` or remove `edit` button in this case.

@krusche I now implemented it that
- Before start, the "Edit" button is usable
- After start, the edit button is disabled
- After the quiz end, "Re-evaluate" is displayed instead.

quiz-button-edit

**Review by krusche — APPROVED** [review]

**Review by fde312 — APPROVED** [review]
The issue with the quiz exercises was solved. Code looks good to me, good job! 👍

**Review by kloessst — APPROVED** [review]
Re-tested the behavior of the quiz edit/re-evaluate button. Works fine. Code looks good.

**Pull request merged**
