### PR TITLE
`Development`: Move feature toggles to resource class level where possible

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Make our code cleaner

### Description

Stacked on #9422

Moved all @FeatureToggle-Annotations to the class level if all endpoints inside the resource were annotated with them. Additionally fixed the issue that @FeatureToggle-Annotations override each other instead of being checked all together when one annotation is over a method and another over the class.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student

1. Log in to Artemis
2. Check that e.g. learning paths, tutorial groups or programming exercises still work.
3. Checking any one rest call for learning paths or tutorial groups is enough, since all endpoints for these features are affected.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Performance Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by pzdr7 — APPROVED** [review]
Code

**Review by iyannsch — APPROVED** [review]
Tested locally, works great!

**Review by az108 — APPROVED** [review]
Tested on TS5, faced a small issue while generating competencies, but i do not think this is related to the changes and is caused by my connection or similar

**Review by MaximilianAnzinger — APPROVED** [review]
Maintainer approved

**Pull request merged**
