### PR TITLE
`Programming exercises`: Always include user in clone URL

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Some students and lecturers have multiple git users on their machine and/or configured in their git client. This can lead to problems when the git user is not specified in the clone url for https.

### Description

This PR always adds the git user name to the clone url before the host of the repository for https urls.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise

1. Log in to Artemis
2. Try to clone the repository as a student (using https and ssh)
3. Try to clone the solution as instructor (using https and ssh)
4. Make sure that the https link always includes the current user and the SSH link still has the `git` user.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| clone-repo-button.component.ts | 80% | 86% |

### Screenshots

HTTPS with user:
Bildschirm­foto 2022-11-22 um 14 11 52
SSH without user:
Bildschirm­foto 2022-11-22 um 14 11 39

### CODE REVIEW

**Review by b-fein — CHANGES_REQUESTED** [review]
The SSH url is now invalid. GitLab requires all users to ssh-login via the `git` user (GitHub as well, no idea about Bamboo). The user it then identified by the SSH key.

**Review by TheZoker — APPROVED** [review]
LGTM 👍

**Comment by dfuchss** [comment]
Has someone tested this PR with enabled gitlab access tokens ? Or does this change nothing for this case ?

**Comment by JohannesStoehr** [comment]
> Has someone tested this PR with enabled gitlab access tokens ? Or does this change nothing for this case ?

In this case it _should_ not be changed

**Review by simon-hng — APPROVED** [review]
Code looks good

**Review by sleiss — APPROVED** [review]
Code looks good :+1:

**Pull request merged**
