### PR TITLE
`Plagiarism detection`: Add possibility for post due date cpc checks

### PR DESCRIPTION
**Pull request by jakubriegel**
### Checklist
⚠️ **This PR targets `cpc` branch instead of `develop`.** The reason is that there is an issue with `@Scheduled` annotations on test servers which prevents cpc related changes to be tested. **All changes in this PR are suitable to be easily tested locally.** Once this PR gets approvals from the team and the maintainer (@MarkusPaulsen) it will be merged into `cpc`. Once issues with test servers are fixed @jakubriegel and @MarkusPaulsen will test everything e2e. @jakubriegel keeps `cpc` up to date with `develop`.

#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types ~~on a test server.~~
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] ~~I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).~~
- [ ] ~~I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).~~

### Motivation and Context
This PR is part of _continuous plagiarism control_ project. It implements CPC-6 milestone from @jakubriegel thesis. More about that can be discovered in the thesis proposal: https://confluence.ase.in.tum.de/display/ArTEMiS/MA+Jakub+Riegel?preview=/157431627/166332701/riegel_proposal.pdf

The cpc runs plagiarism checks automatically each night. So far it was looking for submissions for exercises with cpc enabled and due date after _today_. This means that submissions posted by students on the day of the deadline were not scanned by cpc. This PR fixes this issue.

### Description
This PR introduces optional post due date cpc run. This way instructors can use cpc to scan submissions posted on the due date. Such scans are optional so that instructors are free to run plagiarism checks manually after the due data (for example when they want asses submissions right after the deadline and do not wait for cpc to trigger).

Changes:
- server changes adding new logic to `ContinuousPlagiarismControlService` and `ExerciseRepository`
- client changes adding new checkbox to the exercise create/edit form of text, modeling and programming exercises

### Steps for Testing
Prerequisites:
- ⚠️ **Please test this change locall**y (no ci setup is needed, see the note at the top for more details)
- 1 Instructor
- 2 Students
- 1 modeling or text

1. Change cron so that cpc is triggered every 30s:
    - find the line `@Scheduled(cron = "${artemis.scheduling.continuous-plagiarism-control-trigger-time:0 0 4 * * *}")`
    - replace it with `@Scheduled(initialDelay = 30_000, fixedDelay = 30_000)`
1. Create an exercise with
    - due date in the future
    - selected: _Enable Continuous Plagiarism Control_
    - selected: _Check the submissions for plagiarism in the night after the due date_
1. Create two identical submissions from two different users **and wait 1min**
1. Both submissions should have received results with feedback and 0 score
1. Edit the exercise so that the due date is yesterday **and wait 1min**
1. Both submissions should have received additional results
1. Edit the exercise so that the due date is before yesterday **and wait 1min**
1. No additional results are posted

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual (local) Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| ContinuousPlagiarismControlService.java | 93% | ✅                           |

### Screenshots
New option in exercise create/edit form:
image

The option is checkbox disabled when cpc is not selected:
image

### CODE REVIEW

**Comment by jakubriegel** [comment]
Commit history is a bit mess here due to issues caused by https://ls1tum.slack.com/archives/G6TCVL6HL/p1691858498195679

**Review by HannesLeonhard — APPROVED** [review]
tested locally and worked as described 👍

**Review by reschandreas — COMMENTED** [review]
I tested it locally, and everything worked as expected, but I don't understand what you mean by point 6. Locally I get new results every minute, but the feedback does not change 
Screenshot 2023-08-14 at 14 53 57 Is this intended?

**Comment by jakubriegel** [comment]
> I tested it locally, and everything worked as expected, but I don't understand what you mean by point 6. Locally I get new results every minute, but the feedback does not change
> Screenshot 2023-08-14 at 14 53 57 Is this intended?

Yes, it is. In production cpc is triggered once a day and the code checks if the deadline was on or after yesterday. This means that new feedback will be added only once. In the test set up the check runs multiple times in one day, that' why there are additional results posted

**Review by reschandreas — APPROVED** [review]
Tested locally, works as expected. Thanks!

**Pull request merged**
