### PR TITLE
Add allowList for trusted video providers to video-unit.component.ts

### LINKED ISSUE #4028: Embedding TUM Live Videos as Lecture Unit not working
### Describe the bug

Embedding a video from TUM Live as a lecture unit does not work.
image

### To Reproduce

1. Go to `Lectures`
2. Select your lecture
3. Click on `Add a new Lecture Unit ` -> `Video`
3. Use any TUM Live video URL and append `?video_only=1`.

### Expected behavior

TUM Live videos should render.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

Might be related to: https://github.com/ls1intum/Artemis/blob/c115ad0a53a7217c75c0d0fc191748a3187dc1ea/src/main/webapp/app/lecture/lecture-unit/lecture-unit-management/video-unit-form/video-unit-form.component.ts

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by joschahenningsen**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

The course GBS needs to embed TUM-Live videos into Artemis (ping @COM8). This is not possible due to client side url validation introduced in https://github.com/ls1intum/Artemis/commit/cbe3c93213f0623362b901a69bc96bd03cf414a4. -> fixes #4028 

### Description
I added an allow list with regexes for trusted providers that should not be validated using 'js-video-url-parser'.

### Steps for Testing

Create a video unit with the url `https://live.rbg.tum.de/w/test/26?video_only=1` and make sure it can be viewed

### Review Progress

- Code Review
  - [x] Review 1
  - [x] Review 2
- Manual Tests
  - [x] Test 1
  - [x] Test 2

### CODE REVIEW

**Review by alexanderstephan — APPROVED** [review]
Changes, including the regex look good to me. :+1: Using a list also make sense. Ideally, we should update the plugin itself using their [template](https://github.com/Zod-/jsVideoUrlParser/blob/master/lib/provider/template.js), but its development does not seem very active and TUM websites are not that relevant to the public, so this is really the best solution for now (I think). Nice job! :smile:

**Review by Olimbia23 — APPROVED** [review]
Nice work @joschahenningsen
Code changes make sense. Approve 👍

**Review by lschlesinger — APPROVED** [review]
I tested it with your URL on ts1. Video was successful uploaded and can be viewed afterwards.

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Works good!

**Review by JohannesStoehr — APPROVED** [review]
Tested on TS3, works as expected. Nice video as example in the PR description :)

**Comment by alexanderstephan** [comment]
Tested on TS3, everything works as expected :+1:

**Review by argertboja — APPROVED** [review]
Tested on TS3, works as expected 👍🏼 Nice video btw 😄

**Review by COM8 — APPROVED** [review]

**Pull request merged**
