### PR TITLE
`Development`: Fix flaky PostIntegrationTest

### PR DESCRIPTION
**Pull request by laadvo**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

The test `PostIntegrationTest.testGetPostsForCourse_WithExerciseIdRequestParam()` is flaky and sometimes fails with
```
org.mockito.exceptions.misusing.UnfinishedStubbingException: org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at de.tum.in.www1.artemis.util.AbstractArtemisIntegrationTest.mockMailService(AbstractArtemisIntegrationTest.java:129)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
```

This PR fixes the test `testCreateAnnouncement()` which is executed before `testGetPostsForCourse_WithExerciseIdRequestParam()` and is causing it to be fail.

### Description

In the test `PostIntegrationTest.testCreateAnnouncement()` mails are sent using the `javaMailSender` in async. The mails sometimes get sent after the `javaMailSender` already mock got reset. When the mock is  configured again in the `@BeforeEach` method `mockMailService()` there already exists a recorded call on the mock which causes the cryptic `UnfinishedStubbingException`.  
This happened in the `@BeforeEach` of `testGetPostsForCourse_WithExerciseIdRequestParam()` which is always run directly after `testCreateAnnouncement()`.

The PR adds a `verify` statement at the end of `testCreateAnnouncement()`, making sure that the mails are sent before starting the next test.

### Review Progress

Look at the code changes and feel free to run `PostIntegrationTest` multiple times using the following script (inspired by the script from https://github.com/ls1intum/Artemis/pull/6506).
```
rm postIntegration.log
for i in {1..50}
do
   echo "Starting run: i=$i."
   ./gradlew cleanTest test --tests de.tum.in.www1.artemis.metis.PostIntegrationTest -x webapp | tee -a postIntegration.log
done

echo "Print failed tests:"
cat postIntegration.log | grep "testGetPostsForCourse_WithExerciseIdRequestParam() FAILED" || [[ $? == 1 ]]
```

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### Test Coverage

unchanged

### CODE REVIEW

**Review by DominikRemo — APPROVED** [review]
Changes LGTM. Test succeeds locally

**Review by Strohgelaender — APPROVED** [review]
code lgtm
thanks a lot for figuring this out.

**Review by MaximilianAnzinger — APPROVED** [review]
LGTM

**Review by dearjasmina — APPROVED** [review]
code lgtm

**Pull request merged**
