### PR TITLE
[Bugfix] Category states cannot be changed

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Changing the state of a category in the grading page doesn't work anymore.

### Description

- Fix the bug described above
- Fix reset of test cases. The action should be always available not only if changes have been saved **and** a student participation exists
- Change ordering of elements in programming exercise detail view
- Improve spacing in for the option "Enable static code analysis"

### Steps for Testing

1. Log in to Artemis
2. Create a programming exercise with SCA
3. Go to the categories grading page
4. Play around with the options
--> UI should work and categories should update correctly on save
5. Reset the test cases (**Note: Reset for SCA categories is disabled for now**)

### Test Coverage

Nothing changed

### Screenshots

exercise-creation-sca-unchecked
exercise-detail-view

### CODE REVIEW

**Review by airelawaleria — CHANGES_REQUESTED** [review]
The reset button in the grading page is not working.

**Review by simonzilker — CHANGES_REQUESTED** [review]
Tested with @airelawaleria, reset button does no work. Everything else worked fine.

**Review by FrankeLukas — DISMISSED** [review]

**Review by fde312 — APPROVED** [review]
For me your changes worked fine. The reset button is completely disabled for me, I think this is also the issue for the others. But this is not related to this PR. Maybe you can fix the issue in this PR or in a follow up PR

**Review by marvinchimeka — CHANGES_REQUESTED** [review]
The reset button is not working. 

Bildschirmfoto 2020-11-24 um 12 02 55

**Review by JohannesWeiss — COMMENTED** [review]
Experienced the same behaviour as @fde312 with the disabled reset button, the rest worked.

**Review by fde312 — CHANGES_REQUESTED** [review]
I retested it on ts3 and there it works. Seems to be an issue form here!

**Review by philgabr — CHANGES_REQUESTED** [review]
I just tested again on TS1, and the "Reset" button is not working there.

**Review by airelawaleria — APPROVED** [review]
Tested with @marvinchimeka on ts1. Worked as intended

**Review by marvinchimeka — APPROVED** [review]
Tested with @airelawaleria on ts1. Works as intended. Re-approve.

**Review by JohannesWeiss — APPROVED** [review]
Re-Tested on ts1, now everything worked for me as well.

**Review by simonzilker — APPROVED** [review]
re-approve. Worked as expected

**Review by krusche — APPROVED** [review]

**Review by fde312 — APPROVED** [review]
Looks good now! Good job 👍

**Pull request merged**
