### PR TITLE
`General`: Fix an issue with an unintentional log out during unsaved changes prevented correctly

### LINKED ISSUE #5440: `Exam mode`: Unintentional log out during exam is not prevented correctly
### Describe the bug

When I (unintentional) click on sign out as a student during an exam, I get an alert that all unsaved changes will be lost.
If I then click on cancel, I nevertheless get logged out and receive authentication errors.

### To Reproduce

1. Conduct an exam as a student
2. Click on sign out
3. A warning is shown (see screenshots)
4. If you click cancel, you will be logged out anyways and then get errors that you are not authenticated

### Expected behavior

If I click cancel in the alert box, then I should still remain logged in.

### Screenshots

Bildschirmfoto 2022-07-20 um 12 55 53
Bildschirmfoto 2022-07-20 um 12 56 04
Bildschirmfoto 2022-07-20 um 12 56 16

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by pellumbbaboci**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Fixes #5440 issue.

### Description

Previously, during exam or exercise if user tries to logout, the logout logic is being executed then guard is fired. In this PR i changed it to first navigate to `/` route in order to check if the Pending Changes guard will fire, and only if user confirms to logout then it will execute the logout logic.

### Steps for Testing

Prerequisites:
- 1 Admin
- 1 Students
- 1 Modeling Exercise

1. Log in to Artemis as a admin
2. Navigate to Courses management and create a new course with modeling exercise 
3. Now log in to Artemis as a student
4. Navigate to Courses
5. Select the course and navigate to exercises tab
6. Open modeling editor
7. Make some changes by adding some diagrams
8. Try to logout while there is unsaved changes 
9. A confirmation popup should show up, press OK to logout or cancel to continue

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

E2E Cypress test added in `src/test/cypress/integration/Logout.spec.ts`

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Code changes and cypress tests look good to me

**Review by stefanwaldhauser — APPROVED** [review]
LGTM! Good change

**Review by ge65cer — APPROVED** [review]
Tested locally, bug is fixed! Code changes also approved. 👍

**Review by rriyaldhi — APPROVED** [review]
Code changes look good! 👍

**Comment by krusche** [comment]
@Pellumbengineer sorry, I cannot merge this, because I don't know if all checks succeed.
Can you please create this PR again, however use an internal branch of this repository?
Let me know on Slack if you need access to the repository for this

**Comment by Pellumbengineer** [comment]
> @Pellumbengineer sorry, I cannot merge this, because I don't know if all checks succeed. Can you please create this PR again, however use an internal branch of this repository? Let me know on Slack if you need access to the repository for this

Yes i can create this PR again.

**Pull request closed without merging**
