### PR TITLE
`General`: Add new contributors to about us page

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
Adds new contributors to the about us page.

### How to add yourself
1. Checkout the `chore/about-us` branch locally
2. Add yourself to this file: `src/main/resources/public/content/about-us.json`
 - Use `fullName` for your name
 - Use `sortBy` if the automatic sorting does not detect your last name correctly (if your name consists of mulitple words)
3. Add your image to the `public/images/about` directory and link that image using the `photoDirectory` key. Make sure to use a square, otherwise crop your image before uploading it.

### Steps for Testing
View the about us page and check that the new contributors are visible and sorted.

### CODE REVIEW

**Comment by 4ludwig4** [comment]
@Strohgelaender THX for opening this PR! Maybe recheck and resize your image :wink: Not 100 percent sure so if this impacts the repository or the client.

**Review by TheZoker — DISMISSED** [review]

**Review by Santia-go — CHANGES_REQUESTED** [review]
Tested on TS1

All new members are updated except @rriyaldhi

**Review by terlan98 — CHANGES_REQUESTED** [review]
Tested on TS2 and TS4. The about us page translation labels are not found for some reason. I'm not sure how the changes have lead to this error though 🤔 

Screenshot 2023-05-24 at 14 14 25

**Comment by 4ludwig4** [comment]
> Tested on TS2 and TS4. The about us page translation labels are not found for some reason. I'm not sure how the changes have lead to this error though thinking

Same problem on Docker Compose TS4. @rriyaldhi is displayed so for me.

**Comment by rriyaldhi** [comment]
> Tested on TS2 and TS4. The about us page translation labels are not found for some reason. I'm not sure how the changes have lead to this error though 🤔 
> 
> 
> 
> Screenshot 2023-05-24 at 14 14 25
> 
> 

The error happens on current develop branch as well, so it might not be caused by the changes on this PR.

**Review by terlan98 — DISMISSED** [review]
Approved since the translation issue is unrelated

**Review by pal03377 — CHANGES_REQUESTED** [review]
The changes look good to me in principle, however I think we should try to keep our images smaller. The median image on the about page is ~40kB in size, which is appropriate considering that they are rendered as only 60px square images.

I think we should at least try to keep the size per image below 100kB. @4ludwig4, @pellumbbaboci, @terlan98, @tobias-lippert, @tunargs, @Strohgelaender could you maybe compress your images a bit?

**Review by pal03377 — APPROVED** [review]

**Review by Santia-go — APPROVED** [review]
All good!

**Review by TheZoker — APPROVED** [review]

**Pull request merged**
