### PR TITLE
`Development`: Replace learning goal with competency in client file and class names

### PR DESCRIPTION
**Pull request by terlan98**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

This is a part of follow-up PRs on https://github.com/ls1intum/Artemis/pull/6388 There's currently an inconsistency between the usage of 'learning goal' and 'competency' throughout the system. This PR **only addresses the client file and class names**. 

### Description

Replaced all occurrences of the term 'learning goal' with 'competency' on client file and class names. Also, some fields and functions are renamed to match the new class names. There's only one minor change to a server file that affects the label generation for alerts.

### Steps for Testing

Prerequisites:
- 1 Course with competencies
- 1 Admin

1. Log in to Artemis as Admin
2. Navigate to the Competency Management page of the course
3. Test CRUD operations (+import) for competencies
4. Link this competency to a Lecture Unity or Exercise and see if completing it updates the competency progress for the user

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by SolizerCodes — APPROVED** [review]
CRUD still works on ts1 👍

**Review by RY997 — CHANGES_REQUESTED** [review]
Tested on ts1. Worked well. 
One small issue is that when complete the competency, the firework displays. When it appears at the bottom of the page, a drag bar will appear, and due to its dynamic nature, the bar will appear and disappear, making the page shake which is not good for me.
image

**Review by dakennguyen — COMMENTED** [review]
image
I cannot press save when trying to choose an option from `Linked Competencies`. I need to change something else in order to make the save button enabled. I'm not sure if it's related to your PR.

Otherwise, works well on ts1

**Comment by terlan98** [comment]
> Tested on ts1. Worked well. One small issue is that when complete the competency, the firework displays. When it appears at the bottom of the page, a drag bar will appear, and due to its dynamic nature, the bar will appear and disappear, making the page shake which is not good for me. image

Thank you for the review. It would indeed be better if the confetti animation didn't show a scrollbar. However, this issue is not related to this PR 🙂

**Comment by terlan98** [comment]
> image I cannot press save when trying to choose an option from `Linked Competencies`. I need to change something else in order to make the save button enabled. I'm not sure if it's related to your PR.
> 
> Otherwise, works well on ts1

Thank you for the review. This issue exists in `develop` branch as well. So it's unrelated to this PR 🙂

**Review by dakennguyen — DISMISSED** [review]

**Review by MichaelOwenDyer — APPROVED** [review]

**Review by asliayk — DISMISSED** [review]
tested on ts2, worked well on crud+import operations

**Review by MaximilianAnzinger — DISMISSED** [review]
Renaming looks good

**Review by DominikRemo — DISMISSED** [review]
Code LGTM. I found one comment with _learning goals_ on line 252 in LectureResource.java.
It does not seem to be a part of this PR since it aims to replace occurrences in client files and class names. Therefor, this is an optional change. However, I'd appreciate if you could fix it anyway ^^" 
Bildschirmfoto 2023-06-14 um 17 21 23

**Review by laadvo — DISMISSED** [review]
Looked over the code, the renaming looks good to me

**Review by SolizerCodes — APPROVED** [review]
Reapprove 👍

**Review by DominikRemo — APPROVED** [review]
Reapprove code 👍
Thank you for addressing my comment :)

**Review by laadvo — APPROVED** [review]
Reapprove code

**Review by dakennguyen — APPROVED** [review]
reapprove!

**Review by RY997 — APPROVED** [review]

**Review by bassner — APPROVED** [review]

**Pull request merged**
