### PR TITLE
`Development`: Remove Bonn as university using Artemis

### PR DESCRIPTION
**Pull request by 1-alex98**
No using it anymore

### CODE REVIEW

**Comment by krusche** [comment]
May I ask why? Are you using a different learning platform now?

**Comment by 1-alex98** [comment]
Last semester a new instructor took over the course. I was not really involved but he had some issues with the platform. 

When I as a tutor ran the platform it was fine. I had to invest quite some time in it, even though it was not even my responsibility. Also you might remember there were quite some issues here and there. I am experienced in both Java Spring and Angular. So I always found a way to fix issues. Him being a security researcher this was not really his field of work. Also you have limited time as an instructor. So he dropped it mid course. It was not working and did cost too much time for him. I guess the University would need to have some one responsible for Artemis that offers tech support. 

If I understand correctly you have quite some people working on it. If an instructor has an issues he goes to you guys and asks for help. Our poor guy was just on his own wondering what to do when the system did not work. 

https://net.cs.uni-bonn.de/de/wg/itsec/mitarbeiter/felix-boes/ if you want to ask him about details.

**Comment by 1-alex98** [comment]
I guess the University misses some department to take care of this program. Well I guess there is such a department but they never hosted this program. And then a competent student that is employed there helping hosting, maintaining and offering tech support.

**Comment by krusche** [comment]
Thanks for the feedback

**Pull request merged**
