### PR TITLE
`Communication`: Fix channel creation dialog translation

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] This is a small issue that I tested locally.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I added multiple screenshots/screencasts of my UI changes.
- [X] I translated all newly inserted strings into English and German.

### Motivation and Context

- The ‘Announcement Channel’ header in the create channel dialogue is misleading. It should be changed to  ‘Announcement / Unrestricted Channel’, like ‘Public / Private Channel’, or 'Channel Type'
- The ‘Private Channel / Public Channel’ should be changed to ‘Public / Private Channel’ to avoid the duplication and follow the same order as the buttons below, or it can be changed to 'Visibility'
(The related issue is #6342)

### Description

- 'Announcement Channel' header has been changed to 'Channel Type'.
- ‘Private Channel / Public Channel’ has been changed to ‘Visibility’.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to 'Messages' of a course
3. Click on create new channel button to open the channel creation dialogue

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

image

## Summary by CodeRabbit

- **Improvements**
  - Enhanced clarity of labels related to channel visibility and type:
    - "Private Channel / Public Channel" updated to "Visibility."
    - "Announcement Channel" updated to "Channel Type."
  - Applied to both German and English language settings.

### CODE REVIEW

**Comment by Strohgelaender** [comment]
I think a more fitting header for the selection between public and private would be "Visibility". What do you think? And for the "Announcement / Unrestricted Channel" selection maybe "Channel type" would be fitting?

**Review by marlon-luca-bu — APPROVED** [review]

**Comment by edkaya** [comment]
> I think a more fitting header for the selection between public and private would be "Visibility". What do you think? And for the "Announcement / Unrestricted Channel" selection maybe "Channel type" would be fitting?

I agree with Lucas, I think "Channel Visibility" and "Channel Type" are more suitable.

**Review by edkaya — COMMENTED** [review]
I agree with @Strohgelaender, I think "Channel Visibility" and "Channel Type" are more suitable.

**Review by Strohgelaender — APPROVED** [review]

**Review by pzdr7 — APPROVED** [review]
Tested locally. LGTM

**Pull request merged**
