### PR TITLE
`Adaptive learning`: Make exercise competencies management consistent

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
The competency selector for exercises has been located at a different position in the different exercise type edit views and the current selected competencies have not been shown on the exercise detail page.

### Description
This PR moves the Competency Selector for all exercise types to the end of the problem statement section. Both in the edit view and the detail view.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with competencies

1. Log in to Artemis
2. Navigate to Exercise Overview
3. Check for all exercise types that the competency selector is placed below the problem statement in the edit mode
4. Check for all exercise types that the selected competencies are shown on the detail page of the exercise

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [file-upload-exercise-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6119/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/file-upload/manage/file-upload-exercise-detail.component.ts.html) | 97.91% | ✅  |
| [modeling-exercise-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6119/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/modeling/manage/modeling-exercise-detail.component.ts.html) | 93.05% | ✅  |
| [programming-exercise-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6119/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/programming-exercise-detail.component.ts.html) | 86.47% | ✅  |
| [quiz-exercise-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6119/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/quiz/manage/quiz-exercise-detail.component.ts.html) | 95.65% | ✅ |
| [utils.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6119/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/utils.ts.html) | 86.36% | ✅ |
| [text-exercise-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6119/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/manage/text-exercise/text-exercise-detail.component.ts.html) | 100% | ✅ |

### Screenshots

image
image

## Summary by CodeRabbit

- **New Features**
	- Introduced a competency selection section for exercises across various types (file upload, modeling, programming, quiz, and text) based on exam mode conditions.
	- Enhanced display of exercise details to include competencies when present, improving information accessibility for users.

- **Enhancements**
	- Reorganized HTML structure for file upload and text exercise update components for better usability.
	- Modified exercise detail components to dynamically display competencies, enriching the exercise information provided to users.

### CODE REVIEW

**Review by rstief — DISMISSED** [review]
Code lgtm

**Review by pzdr7 — COMMENTED** [review]
Tested on TS2 - the linked competencies for programming exercises didn't show up for me.

<details>
  <summary>Screenshots</summary>

grafik

grafik

</details>

**Review by rstief — APPROVED** [review]

**Review by pzdr7 — APPROVED** [review]
Tested on TS2 for all exercise types. 
- Competencies are shown (if present) under the problem statement when editing
- Same when viewing

-> Works as expected!

**Review by basak-akan — APPROVED** [review]
Tested on TS5 with all types of exercises, worked as described

**Review by AntonGeTUM — APPROVED** [review]
Manually tested, competencies/linked competencies are shown as described

**Pull request merged**
