### PR TITLE
`Development`: Upgrade to Angular 14 and Jest 28

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation and Context

Upgrade to new major versions of Angular and Jest.

### Description

- Bumped dependencies
- Updated form builder stuff

### Status

We're currently waiting for

- [x] https://github.com/just-jeb/angular-builders/issues/1219
- [x] https://github.com/angular-eslint/angular-eslint/pull/1004
- [x] https://github.com/danielmoncada/date-time-picker/issues/160
- [ ] https://github.com/ng-bootstrap/ng-bootstrap/issues/4340
- [ ] https://github.com/orizens/ngx-infinite-scroll/issues/404

- [x] After we got an update of ``angular-builders``, we probably need to figure out a solution for the ``uuid`` ESM problem

### CODE REVIEW

**Comment by ge65cer** [comment]
We no longer use `ngx-device-detector`. 🙂 
https://github.com/ls1intum/Artemis/commit/c01d5d72b3cbf9823e7fc992a80375f959ab4802

**Comment by krusche** [comment]
I suggest we change from ngx-infinite-scroll to use virtual scrolling with fetching as implemented in angular material, see e.g. https://zoaibkhan.com/blog/create-a-fast-infinite-scrolling-list-in-angular/

The benefit would be that angular material is maintained with angular, so we don't have external dependencies for which we need to wait

**Comment by krusche** [comment]
There seems to be a `13.0.0-beta.1` which `ng-bootstrap` which we can try out and see if it works in our case

**Comment by bassner** [comment]
Seems like the PR upgrading ``ngx-infinite-scroll`` just updates the dependency declarations and does not change anything on the code, so we can just try to override their peer deps for now

**Comment by bassner** [comment]
I've added the beta version of ``ng-bootstrap``. This should work as the only breaking change noted in the change log is the removal of already depreacted button directives which we don't seem to use.

**Review by ge65cer — COMMENTED** [review]
The Bootstrap upgrade seems to have slightly broken the layout of the course cards.
Edit: @mallgaier found the issue to be from changes in https://github.com/ls1intum/Artemis/pull/3764 

<details>
<summary>Screenshot</summary>
Screenshot 2022-07-07 at 14 08 49
</details>

**Review by willergeorg — APPROVED** [review]
Tested during testing session. Lgtm. 👍

**Pull request merged**
