### PR TITLE
`Lectures`: Remove guided mode exercise creation shortcut

### PR DESCRIPTION
**Pull request by florian-glombik**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
It is unlikely that editors / instructors will start creating exercises while they are creating a lecture. This step will usually have been completed before the lecture creation and is not something that will be done within a matter of minutes.

While this feature, of navigating from the lecture creation to the exercise creation and back, is only available in the guided mode and the guided mode will be removed in [Lectures: Add status bar to lecture creation and edit mode #9655](https://github.com/ls1intum/Artemis/pull/9655), this PR already removes the "exercise creation shortcut" to keep #9655 at a manageable size.

### Description
* Removes the "exercise creation shortcut"-feature that is only available in the guided mode of the lecture creation

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Create a lecture in guided mode, make sure to add an exercise within the lecture units
2. Verify there is no "Create new exercise"
3. Go to the exercise overview 
4. Add the following parameters to the URL `?shouldHaveBackButtonToWizard=true&lectureId=83&step=4`
5. Verify there is no `Back to lecture` button displayed
6. Create an exercise, verify that saving worked as expected _(write in your review comment which type you tested, test a type that was not yet tested)_

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Old Version
RemoveGuidedModeExeciseCreationShortcut-10022-old

#### New Version
* `Create new exercise` shortcut removed from guided mode
* `Back to lecture` button removed from exercise overview _(can be tested by adding parameters to URL)_

removGuidedModeExerciseCreationShortcut-10022-new

## Summary by CodeRabbit

- **New Features**
	- Simplified navigation logic across multiple exercise management components.
	- Enhanced clarity in the user interface by removing unnecessary navigation options, including back-to-wizard buttons.

- **Bug Fixes**
	- Corrected comments in subscription handling to improve code clarity.

- **Documentation**
	- Updated localization files to reflect changes in navigation options.

- **Tests**
	- Added new test cases to verify component behavior with query parameters.

### CODE REVIEW

**Review by BBesrour — APPROVED** [review]
code

**Review by az108 — APPROVED** [review]
Code 👍

**Review by sachmii — APPROVED** [review]
Tested on TS3,  the "Create new exercise" button is removed from the guided mode. Also, tested the "back to lecture" with the URL.

**Review by HawKhiem — APPROVED** [review]
Tested on TS3. No "Create new exercise" is displayed in guided mode. No Back to lecture button displayed with the added URL. I created the following exercises:
- A programming exercise
- A quiz in synchronized mode
- A modelling exercise
- A text exercise

The save button works for all the above exercises

Screenshot 2024-12-15 004710
Screenshot 2024-12-15 004931
Screenshot 2024-12-15 004947
Screenshot 2024-12-15 005011
Screenshot 2024-12-15 005051

**Review by alekspetrov9e — COMMENTED** [review]
Tested on TS1. No button "Create new exercise" was shown. Added parameters to url and no back to lecture button was displayed.

**Review by rabeatwork — APPROVED** [review]

**Pull request merged**
