### PR TITLE
`Programming exercises`: Fix an issue with the close button in the result view

### PR DESCRIPTION
**Pull request by egekurt123**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Solves #8135 

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Programming Exercise

1. Log in to Artemis
2. Navigate to a course and open a Programming Exercise
3. Click at the grade (ex. 7.7% (a few seconds ago)) to open the feedback popup
4. Make sure the button [X] is located at right above corner

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
Old
Screenshot 2024-03-07 at 13 23 30

New
Screenshot 2024-03-07 at 13 20 29

### CODE REVIEW

**Review by b-fein — APPROVED** [review]
Looks good. :+1:

**Review by Strohgelaender — APPROVED** [review]
Thanks for looking into this.

**Review by AntonGeTUM — APPROVED** [review]
Tested on ts4, works as expected

**Review by pzdr7 — APPROVED** [review]
Tested on TS2 - looks good to me!

**Pull request merged**
