### PR TITLE
`Programming exercises`: Fix an issue with the access log in exam exercises

### PR DESCRIPTION
**Pull request by SimonEntholzer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The routes for the vcsAccessLog were missing for the exam mode.

### Description

This PR adds the routes for the VcsAccessLog for exam mode exercises.

### Steps for Testing

Prerequisites:

1. Log in to Artemis
2. Create an exam with a programming exercise
3. Add students, generate student exams and prepare exercise start
4. Navigate to Exercise groups -> Exercise -> Participations
5. Use the code button to navigate to the repository of the student participation (exam does not need to have started yet)
6. Check that the `Open access log` button leads to the access log of the repository 
7. In the exercise overview page, access the template and solution repositories, and check that the vcs-access-log is shown for them too 

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual exam mode Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image

### CODE REVIEW

**Review by BBesrour — APPROVED** [review]
code lgtm

**Review by muradium — APPROVED** [review]
Tested on TS3, works as expected

**Review by iyannsch — APPROVED** [review]
Tested and Code LGTM

**Review by janthoXO — APPROVED** [review]
Tested on TS3

**Review by krusche — APPROVED** [review]

**Pull request merged**
