### PR TITLE
Feature/achievements/configuration and client

### PR DESCRIPTION
**Pull request by balazs-czopf**
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into German and English

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### CODE REVIEW

**Comment by krusche** [comment]
I'll close this PR due to inactivity for 10 days

**Comment by balazs-czopf** [comment]
I´ll reopen this PR due to the fact that you´re wrong again and the last commit was 3 days ago (as seen from yesterday).

**Comment by krusche** [comment]
I was just looking at the history here
image


Please keep the PRs small and only open for a few days. We will soon change the rules, that PRs can only be open for at most 7 days. I don't understand why you are constantly breaking these simple rules? :-(

There is no reason to open a PR if you cannot finish it within the next 2-3 days!

**Comment by krusche** [comment]
closing this PR due to inactivity

**Pull request closed without merging**
