### PR TITLE
`Communication`: Add participants to channels lazily

### PR DESCRIPTION
**Pull request by pellumbbaboci**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

With #6513, we create channels for exercises/lectures when exercises/lectures are created/imported. However, users are not added automatically yet.

### Description

This PR adds participants to those channels asynchronously, when a channel is created.
Additionally, it reworks the communication side panel on the exercise/lecture page, where channels can be displayed now instead of posts, if a channel exists. If no channel exists, and communication is enabled, it shows posts like before.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis with Instructor
2. Navigate to Course Administration
3. Select Course
4. Create lecture
5. Check in messages tab, whether a channel was created  AND make sure that all students and tutors are added as **conversation participant** to the channel.
6. Import Lecture
7.  Repeat step 5
8. Repeat 4-7 for each exercise type
9. On lecture/exercise pages: Test if writing, editing, resolving, reacting to, and searching/filtering for messages works
10. Add a user to the course and check if they are added to the lecture/exercise channels

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [exam.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/entities/exam.model.ts.html) | 100% | ✅ |
| [exercise.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/entities/exercise.model.ts.html) | 89.61% | ✅ |
| [lecture.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/entities/lecture.model.ts.html) | 100% | ✅ |
| [channel.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/entities/metis/conversation/channel.model.ts.html) | 90.9% | ✅ |
| [exam-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/exam/manage/exams/exam-update.component.ts.html) | 95.68% | ✅ |
| [file-upload-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/exercises/file-upload/manage/file-upload-exercise-update.component.ts.html) | 84.84% | ✅ |
| [modeling-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/exercises/modeling/manage/modeling-exercise-update.component.ts.html) | 85.71% | ✅ |
| [programming-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/update/programming-exercise-update.component.ts.html) | 80% | ✅ |
| [programming-exercise-information.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/update/update-components/programming-exercise-information.component.ts.html) | 100% | ✅ |
| [quiz-exercise-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/exercises/quiz/manage/quiz-exercise-detail.component.ts.html) | 88.27% | ✅ |
| [text-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/manage/text-exercise/text-exercise-update.component.ts.html) | 86.27% | ✅ |
| [lecture-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/lecture/lecture-update.component.ts.html) | 90.8% | ✅ |
| [course-lecture-details.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-lectures/course-lecture-details.component.ts.html) | 88.52% | ✅ |
| [discussion-section.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/overview/discussion-section/discussion-section.component.ts.html) | 81.51% | ✅ |
| [course-exercise-details.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/overview/exercise-details/course-exercise-details.component.ts.html) | 84.03% | ✅ |
| [title-channel-name.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/shared/form/title-channel-name/title-channel-name.component.ts.html) | 100% | ✅ |
| [channel.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/shared/metis/conversations/channel.service.ts.html) | 93.54% | ✅ |
| [posting-header.directive.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/shared/metis/posting-header/posting-header.directive.ts.html) | 100% | ✅ |
| [posting-thread.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/shared/metis/posting-thread/posting-thread.component.ts.html) | 100% | ✅ |
| [posting.directive.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Client-Tests/app/shared/metis/posting.directive.ts.html) | 100% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [Exercise.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/Exercise.html) | 92% | ✅ |
| [Lecture.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain/Lecture.html) | 100% | ✅ |
| [CourseInformationSharingConfiguration.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.enumeration/CourseInformationSharingConfiguration.html) | 100% | ✅ |
| [Exam.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.exam/Exam.html) | 92% | ✅ |
| [Channel.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.metis.conversation/Channel.html) | 100% | ✅ |
| [LectureRepository.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.repository/LectureRepository.html) | 75% | ✅ |
| [UserRepository.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.repository/UserRepository.html) | 94% | ✅ |
| [ConversationMessageRepository.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.repository.metis/ConversationMessageRepository.html) | 87% | ✅ |
| [ChannelRepository.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.repository.metis.conversation/ChannelRepository.html) | 56% | ✅ |
| [FileUploadExerciseImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/FileUploadExerciseImportService.html) | 100% | ✅ |
| [ModelingExerciseImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/ModelingExerciseImportService.html) | 96% | ✅ |
| [QuizExerciseImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/QuizExerciseImportService.html) | 88% | ✅ |
| [TextExerciseImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/TextExerciseImportService.html) | 100% | ✅ |
| [ExamImportService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.exam/ExamImportService.html) | 98% | ✅ |
| [ExamRegistrationService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.exam/ExamRegistrationService.html) | 89% | ✅ |
| [AnswerMessageService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.metis/AnswerMessageService.html) | 85% | ✅ |
| [ConversationMessagingService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.metis/ConversationMessagingService.html) | 84% | ✅ |
| [ChannelService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.metis.conversation/ChannelService.html) | 94% | ✅ |
| [ConversationService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.metis.conversation/ConversationService.html) | 92% | ✅ |
| [ProgrammingExerciseImportBasicService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseImportBasicService.html) | 97% | ✅ |
| [ProgrammingExerciseService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseService.html) | 93% | ✅ |
| [UserService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.user/UserService.html) | 90% | ✅ |
| [ExamResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/ExamResource.html) | 96% | ✅ |
| [FileUploadExerciseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/FileUploadExerciseResource.html) | 100% | ✅ |
| [LectureResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/LectureResource.html) | 97% | ✅ |
| [ModelingExerciseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/ModelingExerciseResource.html) | 98% | ✅ |
| [ProgrammingExerciseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/ProgrammingExerciseResource.html) | 90% | ✅ |
| [QuizExerciseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/QuizExerciseResource.html) | 93% | ✅ |
| [TextExerciseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/TextExerciseResource.html) | 99% | ✅ |
| [AdminCourseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.admin/AdminCourseResource.html) | 100% | ✅ |
| [ChannelResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4849-59/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.metis.conversation/ChannelResource.html) | 91% | ✅ |

### Screenshots

The communication side panel for the exercise/lecture pages got adapted and looks more like messages instead of posts:
adapted communication panel

### CODE REVIEW

**Review by rriyaldhi — APPROVED** [review]
Except for the minor bugs, everything works well.

**Review by tobias-lippert — APPROVED** [review]
Tested on ts1. Adding participants to channels worked. The communication sidebar and the channel in the messages tab are also in sync.

**Review by rriyaldhi — APPROVED** [review]
Tested File Upload and Text Exercise on TS1 and works as intended.

**Review by MaximilianAnzinger — APPROVED** [review]
Tested on TS1 during testing session. Looks good to me.

**Review by MaximilianAnzinger — APPROVED** [review]
Thank you for addressing my comment. Code now looks fine.

**Pull request merged**
