### PR TITLE
[Enhancement] - Allow score type change in quiz re-evaluation

### PR DESCRIPTION
**Pull request by FuchsDominik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Sometimes instructors may want to change the way the quiz score is calculated into the course / exam score after releasing the exercise. This is not possible at the moment

### Description

Added the option to define the score calculation type in the re-evaluation of a quiz exercises.
Changes the wording from "course / exam" into either "exam" or "course", depending on if the exercises in in a course or exam.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create quiz (While creating, make sure that the score calculation as mentioned in the screenshots says "in the course score calculation")
4. conduct the quiz
5. After the quiz has ended, click on re-evaluate
6. make sure it is possible to change the score calculation type and that is saves correctly after clicking save at the bottom
7. navigate into the creation page of every exercise type and make sure that it says "Should this exercise be included in the course score calculation?"
8. Go into the exercise group page of a exam and go to the creation page of every exercise type
9. Check that it now says "Should this exercise be included in the **exam** score calculation?"

### Screenshots

Re-evaluation view before:
Screenshot 2021-05-22 at 11 54 23

Re-evaluation view after:
Screenshot 2021-05-22 at 11 53 20

Wording before:
Screenshot 2021-05-22 at 12 03 52
Wording after:
Screenshot 2021-05-22 at 11 52 43

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Tested on TS2. Wording changed accordingly and changes in the scoring type of a quiz for re-evaluation are stored as well.

**Review by NicolasUllmann — DISMISSED** [review]
Tested on Server 2. Everything worked as expected.

**Review by KiraNickel — APPROVED** [review]
Tested on ts3, everything works as described 👍🏼

**Review by cremertim — APPROVED** [review]
tested on ts 1, works as expected

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3, works as expected

**Review by canyelten — APPROVED** [review]
Testes on TS1, works as expected.

**Review by katjanakosic — APPROVED** [review]
Worked fine on TS1 :)

**Review by krusche — APPROVED** [review]

**Pull request merged**
