### PR TITLE
`Development`: Add certificates for e2e tests and improve e2e test flakiness detection

### PR DESCRIPTION
**Pull request by 4ludwig4**
#### General

- [x] I tested **all** changes and their related features on a duplicated and modified E2E Bamboo Plan
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
**E2E certificates**
This PR introduces a nginx reverse proxy with pre-configured certificates also configured in cypress, which should make the cypress workaround from the following PR not necessary anymore:

- https://github.com/ls1intum/Artemis/pull/5723

**E2E flake detection:**
The selected build for comparison, the last successful build, could previously end up being one later than the analyzed build.

### Description

**E2E certificates**
We started adopting a docker compose based nginx service based on the Ansible scripts from our current production nginx.
The certificates for this reverse proxy are configured in nginx and cypress and were created with the tool [mkcert](https://github.com/FiloSottile/mkcert).
These certificates are valid until 2025, but we also added a guide and helpers to generate them again.

This PR doesn't yet remove the workaround itself, as it's still needed for some local setups.

**E2E flake detection:**
This is a small change that adds the bamboo scripts into version control and forwards the current build number to the flake checker. This is to make sure the correct reference is used.

### Steps for Testing

... or at least look how we tested the CI pipeline for this branch.

We cloned the E2E test bamboo plans to our [own bamboo E2E test project/plan for testing](https://bamboo.ase.in.tum.de/browse/AMPU-AETM0-56) and disabled the hooks and scripts which interact with GitHub. Respectively, we did the same for [the E2E flake detection bamboo project/plan](https://bamboo.ase.in.tum.de/browse/AMPU-AETFDM0).

Then you can manually select this branch and run the modified CI pipeline (see Migration Path for the modified parts).

### Migration Path

Change the following tasks in the **[Artemis E2E Tests (Cypress in Docker-default)](https://bamboo.ase.in.tum.de/browse/ARTEMIS-AETG)** Bamboo Plan:
- Script `Deploy Artemis and run Cypress tests`: change to `Script location: File` and set it to `.bamboo/E2E-tests/execute.sh`
- Script `Make sure all docker containers are cleaned up`: change to `Script location: File` and set it to `.bamboo/E2E-tests/cleanup.sh`

Change the following tasks in the **[Artemis E2E (Cypress - Docker- Flaky)](https://bamboo.ase.in.tum.de/browse/ARTEMIS-AECF)** Bamboo Plan:
- Script `Deploy Artemis and run Cypress tests`: change to `Script location: File` and set it to `.bamboo/E2E-tests-with-flake-detection/execute.sh`
- Script `Make sure all docker containers are cleaned up`: change to `Script location: File` and set it to `.bamboo/E2E-tests-with-flake-detection/cleanup.sh`

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Comment by 4ludwig4** [comment]
These are the old inline bamboo configs for the reviewers, as you probably can't see them in bamboo:

Script `Deploy Artemis and run Cypress tests`
```
# Create libs folder because the Artemis docker compose file expects the .war file there
mkdir -p build/libs
mv *.war build/libs/

adminUser='${bamboo.artemis_admin_username}'
adminPassword='${bamboo.artemis_admin_password}'
artemisPort=54321

# Start Artemis docker containers with docker-compose
cd src/main/docker/cypress
# Export environmental variables to configure Cypress and Artemis.
export CYPRESS_baseUrl="http://artemis-app:$artemisPort"
export CYPRESS_adminUsername=$adminUser
export CYPRESS_adminPassword=$adminPassword
export CYPRESS_username='${bamboo.cypress_username_template}'
export CYPRESS_password='${bamboo.cypress_password_template}'
export CYPRESS_allowGroupCustomization=true
export CYPRESS_studentGroupName=artemis-e2etest-students
export CYPRESS_tutorGroupName=artemis-e2etest-tutors
export CYPRESS_editorGroupName=artemis-e2etest-editors
export CYPRESS_instructorGroupName=artemis-e2etest-instructors

export DATASOURCE_URL="jdbc:mysql://artemis-mysql:3306/Artemis?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC"
export UM_URL="https://jira-prelive.ase.in.tum.de"
export CI_URL="https://bamboo-prelive.ase.in.tum.de"
export SCM_URL="https://bitbucket-prelive.ase.in.tum.de"
export SCM_USER=$bamboo_jira_prelive_admin_user
export SCM_PASSWORD=$bamboo_jira_prelive_admin_password
export UM_USER=$bamboo_jira_prelive_admin_user
export UM_PASSWORD=$bamboo_jira_prelive_admin_password
export CI_USER=$bamboo_jira_prelive_admin_user
export CI_PASSWORD=$bamboo_jira_prelive_admin_password
export CI_AUTH_TOKEN='${bamboo.ARTEMIS_CONTINUOUS_INTEGRATION_ARTEMIS_AUTHENTICATION_TOKEN_VALUE_SECRET}'
export CI_TOKEN='${bamboo.ARTEMIS_CONTINUOUS_INTEGRATION_TOKEN_SECRET}'
export SERVER_URL="http://$(hostname):$artemisPort"
export SERVER_PORT=$artemisPort
export ADMIN_USERNAME=$adminUser
export ADMIN_PASSWORD=$adminPassword

#TODO: recheck docker compose version and do it in one command
docker-compose pull
docker-compose build --no-cache --pull
docker-compose up --exit-code-from artemis-cypress
exitCode=$?
echo "Cypress container exit code: $exitCode"
if [ $exitCode -eq 0 ]
then
    touch ../../../../.successful
else
    echo "Not creating success file because the tests failed"
fi
```

Script `Make sure all docker containers are cleaned up`
```
export SERVER_PORT=54321
cd src/main/docker/cypress
docker-compose stop
docker-compose rm -f
```

**Comment by 4ludwig4** [comment]
The last two failed tests today seem to be flaky tests, as they also appear in failed develop runs once in a while.
The tests which failed before today were issues which were fixed in this branch.

**Review by JohannesStoehr — COMMENTED** [review]
There are some Codacy comments. Are you aware of them?

**Comment by 4ludwig4** [comment]
> There are some Codacy comments. Are you aware of them?

Ah cool, no I actually wasn't aware of them but will check them out tomorrow! Thanks.

**Comment by 4ludwig4** [comment]
Added the suggested style improvements. I also ran the new E2E pipeline again in my bamboo project. It's working, but still flaky.

**Comment by heddendorp** [comment]
> I would suggest removing the workaround code within Artemis as it should no longer be needed and so we don't forget it.

I am currently still depending on the `cypress` profile locally, either keeping it or providing a good migration would be appreciated. I would assume this also affects other local development.

**Comment by 4ludwig4** [comment]
> I would suggest removing the workaround code within Artemis as it should no longer be needed and so we don't forget it.

@sleiss I guess the workaround should be kept for now as @heddendorp and maybe also @TheZoker might still need it and this PR was for now just meant to fix the Bamboo E2E tests as I don't have insights yet on the local E2E setups.

**Comment by 4ludwig4** [comment]
Tried if I could use certificates also for the server push notifications easily, but as we are using the bamboo agent hostnames, whatever they may be, this might not be trivial, as they might have real not self-signed certificates bound to these hostnames?!

Besides that, I cleaned up the docker compose file already a bit in preparation for:

- #5915

**Review by TheZoker — APPROVED** [review]
Tested on my local setup together with @4ludwig4 and works without any issue 👍 
My setup until now: Artemis running in docker within a LXC container. With this PR I added the NGINX container in front of it, which uses the self generated certs. Also tested with my cypress setup and it still runs without issues

**Comment by 4ludwig4** [comment]
Latest E2E results: https://bamboo.ase.in.tum.de/browse/AMPU-AETM0-56

**Review by heddendorp — DISMISSED** [review]
Will need some changes in the flake check version of the e2e tests but looks good to me in general
I will try to follow up immediately with #6180

**Review by sleiss — DISMISSED** [review]

**Comment by 4ludwig4** [comment]
Okay, guess I shouldn't merge stuff on Friday afternoons (local branches are not always up to date ...).

Reason for this is that @heddendorp and me decided it's the easiest if we combine our PRs around the E2E tests as this way we can test them together and also Stephan or whoever will change the Bamboo plans, will just have to do one bamboo migration!

**Review by heddendorp — APPROVED** [review]
looks good to me

**Review by sleiss — APPROVED** [review]
Reapprove

**Review by TheZoker — APPROVED** [review]
Reapprove LGTM 👍

**Pull request merged**
