### PR TITLE
`Integrated code lifecycle`: Fix issue when pushing to test repository

### PR DESCRIPTION
**Pull request by BBesrour**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

There were a couple of issues when pushing to the test repository using the online editor
- `lscommand()` was not using the correct authentication in Build agent
- test commit hash was not passed to the template build which caused issues when fetching the submissions during the result processing

### Steps for Testing

Prerequisites:
- Don't test on TS1 (config was changed for another PR)
- 1 Programming Exercise
- 1 Instructor

**Student view: Please make sure that these changes don't affect the student's perspective**
1. submit using the online editor 
2. Make sure the build is successful and corresponds to the correct commit.
3. submit using localIDE
4. Make sure the build is successful and corresponds to the correct commit.

Instructor view:
1. Push to the test repository using online editor (Click on `Edit on editor` to access the online editor)
2. Make sure that this triggers a solution and template build
3. Make sure that the builds are successful
4. Push to the test repository using localIDE
2. Make sure that this triggers a solution and template build
3. Make sure that the builds are successful

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
  - Added `TEST` submission type to the system for specific repository operations.
  - Introduced `triggeredByPushTo` parameter in `FinishedBuildJobDTO` for enhanced build job tracking.

- **Improvements**
  - Enhanced build trigger logic in local CI service to include a fallback mechanism for commit hash handling.
  - Updated authentication mechanism in Build Job Git Service to handle SSH and other methods more robustly.

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by pzdr7 — APPROVED** [review]
Tested on TS3. Pushing to the Tests repo correctly triggers a template and a solution build. Same with the code editor.

Student submissions trigger builds as expected as well 👍

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS3, works. When does the bug actually occur? I couldn't reproduce it on another branch on TS3.

**Comment by BBesrour** [comment]
@SimonEntholzer This occurred when pushing to the test repository using the online editor. Both template and solution build would fail and when navigation to either of them you'll get a 403 error.

**Review by EneaGore — APPROVED** [review]
Tested on TS3. Both local and online. All builds are triggered successfully.

**Pull request merged**
