### PR TITLE
`Development`: Remove disabled test

### PR DESCRIPTION
**Pull request by undernagruzez**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
Remove a disabled test as it isn't relevant anymore. The scenario it tests is outdated.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### CODE REVIEW

**Review by egekurt123 — APPROVED** [review]

**Review by pzdr7 — APPROVED** [review]
Code

**Review by edkaya — APPROVED** [review]
code lgtm

**Review by nityanandaz — APPROVED** [review]
Code review

**Review by SimonEntholzer — APPROVED** [review]
Code review

**Review by Jan-Thurner — APPROVED** [review]
lgtm

**Review by maximiliansoelch — APPROVED** [review]

**Review by sarpsahinalp — APPROVED** [review]

**Pull request merged**
