### PR TITLE
[Bugfix] Fix issue when submitting modeling example assessment with feedback credits of 0

### LINKED ISSUE #2494: [Bug] Translation not found exception for the example submission for modeling exercise
### Describe the bug

During assessing the example submission there is an issue if you set one field to 0 Points and add feedback you cannot save your example submission. You get a translation not found exception. 

#### To Reproduce

1. Log in to Artemis.
2. Click on Course Administration 
3. Choose a course
4. Click on Edit on an existing modelling exercise or create one.
5. Click on Create Example Submission 
6. Create an example and save your example
7. Click on show assessment
8. Add 0 Points and a Feedback ( its does not matter in which field e.g attribute:type or method())

#### Expected behavior

You get a translation not found exception.

#### Screenshots

Bildschirmfoto 2020-12-02 um 22 40 01

### Environment

<details><pre>
</pre></details>

-OS: Safari

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

### PR DESCRIPTION
**Pull request by fde312**
### Checklist
- [x] I tested *all* changes and *all* related features locally
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Fixes #2494. Issue was again that `0` evaluates to false

### Description

- Added undefined check 

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a new modeling exercise or use old one and edit it
4. Create example submission
5. Create example assessment with at least one feedback having credits of 0
6. Click on save example assessment and check that everything works as expected
7. Try also different feedback credits  combinations

### Test Coverage

Nothing changed

### Screenshots

image
image

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested in the testing session on ts3. Tried different combinations, everything worked fine

**Review by simonzilker — APPROVED** [review]
Tested with @airelawaleria on ts3. All works fine!

**Review by marvinchimeka — APPROVED** [review]
tested in testing session. Approve

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts3, works as intended.

**Review by sebastiantpeter — APPROVED** [review]
Tested on ts3. There is no different behavior when a feedback with credits 0 is present. However when I review the example submission in the Assessment Dashboard as a tutor, I am wondering, why I do not see the "3/3" points in the top right corner, as I see when creating the example submission as instructor.

example_submission

**Review by JannisBittlmayer — APPROVED** [review]
Tested on TS3, works as intended. I wanted to test the before mentioned note about the points not showing when viewing as a tutor but Artemis didn't save any tutors I added (Unrelated issue, not in the scope of this PR)

**Review by LudwigWeide — APPROVED** [review]
Tested on TS1. Works as intended.

**Review by FlorianStang — APPROVED** [review]
Tested on TS3, everything worked as intended noticed the same behaivor as @sebastiantpeter, that the score is not displayed "correctly".

**Review by EneaGore — APPROVED** [review]
Tested on ts3. Approve.

**Review by krusche — APPROVED** [review]

**Pull request merged**
