### PR TITLE
`Tutorial groups`: Add sidebar to student view

### PR DESCRIPTION
**Pull request by rabeatwork**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Part of the new Design 
Will also fix [this](https://github.com/ls1intum/Artemis/issues/8549 ) issue

### Description
Added the new Sidebar to the Tutorial Groups 

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Tutor
- 1 Tutorial as Tutor 
- 1 Tutorial as registered Student 
- 1 Tutorial not involved

1. Log in to Artemis
2. Navigate to Tutorial Groups of a Course
3. Check that the tutorials are sorted correct (My Tutorial Groups / All Tutorial Groups)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

Screenshot 2024-05-06 at 18 23 39
Screenshot 2024-05-06 at 18 19 11

### CODE REVIEW

**Review by JohannesWt — APPROVED** [review]
Tested in testing session - works as expected 👍

**Review by pzdr7 — COMMENTED** [review]
Tested on TS2.

As a student and as a tutor:

- Own tutorial is visible ✅ 
- Other tutorials are visible ✅ 

Nitpick: When a user without a tutorial group looks at this view, all tutor groups are displayed as "Further tutorial groups". This is more of an edge case, but maybe you could change the label when this happens (as "further" only makes sense imo when there's another category of tutorial groups)

image

**Review by pzdr7 — APPROVED** [review]
Thanks for implementing the change!

----

Tested on TS2.

As tutor and student:

- Can see own tutor groups ✅ 
- Can see further tutor groups ✅ 

As student without tutor groups:

- Can see tutor groups (+ label looks good) ✅

**Review by edkaya — APPROVED** [review]
Tested on ts2, works as expected!

**Review by egekurt123 — APPROVED** [review]
Manually Tested on TS2 with 3 different users, It works as expected

**Review by JohannesWt — APPROVED** [review]
Reapprove

**Pull request merged**
