### PR TITLE
Use Precision class to compare weightSum to 0

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).

### Description

This PR uses the `Precision` class from Apache to compare the weight sum to 0

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to a programming exercise and click on Grading
4. Set the test weight to 0 for all of the tests
5. For the last test, set the visibility to "Never" and set the test weight to something greater than 0
6. Click Trigger All
7. Wait a minute and check that no error has been thrown

### CODE REVIEW

**Review by FuchsDominik — COMMENTED** [review]
So basically we do the same as before but now use a specified function for it? :D

**Comment by dfuchss** [comment]
A provocative question:
Is this really needed (esp. because you use some external library instead of "plain Java" for a simple comparison)
Furthermore, I think you would (maybe) have to introduce this to (possibly all) points in the code where you compare floats, to provide consistency :D

**Comment by ivanchimeno** [comment]
> A provocative question:
> Is this really needed (esp. because you use some external library instead of "plain Java" for a simple comparison)
> Furthermore, I think you would (maybe) have to introduce this to (possibly all) points in the code where you compare floats, to provide consistency :D

It was requested by Stephan ;)

**Comment by dfuchss** [comment]
Ok. Then I would suggest that this PR checks whether floating point ops are performed this way. 
Actually, this helper method for comparison is not used anywhere in Artemis :) -- and as I've mentioned above I think consistency would be very important here.
You could also add the use of this library to the development guidelines.

**Comment by ivanchimeno** [comment]
> Ok. Then I would suggest that this PR checks whether floating point ops are performed this way.
> Actually, this helper method for comparison is not used anywhere in Artemis :) -- and as I've mentioned above, I think consistency would be very important here.
> You could also add the use of this library to the development guidelines.

Puh, do you think there's any easy way to scan all files and replace the checks with that function?

**Comment by krusche** [comment]
In my opinion the code is easier to read and understand using the external library. We took the example from
https://www.baeldung.com/java-comparing-doubles

And yes, we should use it in other places as well. I asked @ivohashamov to use it in https://github.com/ls1intum/Artemis/pull/3437 as well

**Pull request merged**
