### PR TITLE
[Bugfix] Illegal submissions grace period

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

The actual implementation of illegal submission does not take the grace period into account which may lead to false positives when students submit exercises in the exam.

### Description

This pr:
- Now takes the grace period into account and adapts related tests.
- Reverts the filtering of illegal submission in various areas notably the student exam summary, participation, and submission tables.
- Adds database index for submission type
- Fixes a bug in the exam summary view where it crashes when a participation wasn't specified
- Adds a warning to the student's code editor if the submission is illegal

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a new exam and make sure you input a large grace period (e.g 999)
4. Add a programming exercise into the exam, participate as a student, and submit once.
3. Do not hand in early but navigate to the student's repository in Bitbucket
4. Find a code file and edit it. This will trigger a new legal submission since it's within the grace period.
5. Hand in the exam and end it.
6. Now navigate again to Bitbucket and edit a file. This should generate an illegal submission since the exam has ended.
7. Navigate to the submission table of the exam and make sure the submission count and types are correct.

### Test Coverage

ProgrammingExerciseStudentParticipationRepository.java 68%
StudentParticipationRepository.java 90%
ExamSubmissionService.java 98%
ProgrammingSubmissionService.java 76%
RepositoryProgrammingExerciseParticipationResource.java 76%

### Illegal Warning in Exam Summary: 
image

### Participation table shows correct submission count (including illegal)
image

#### Submit code while being in this screen: 
image

image

### Submissions after submitting the exam (hand in early and last page submit) lead to illegal submissions:
image

### CODE REVIEW

**Review by MaisiKoleni — APPROVED** [review]
Works fine, tested on TS1. Code looks good as far as I could see.

**Review by ivohashamov — APPROVED** [review]

**Review by cremertim — APPROVED** [review]
Tested during the testing session. Worked during testing. The Java code looks fine to me

**Review by SimonEntholzer — APPROVED** [review]
Testing worked fine on TS1  :+1: Code is fine too

**Review by nicolasruscher — APPROVED** [review]
tested it in the session, looks good!

**Pull request merged**
