### PR TITLE
update ng-bootstrap and interactjs to latest dependencies

### PR DESCRIPTION
**Pull request by krusche**
### Checklist
- [x] I tested the changes and all related features on the test server https://artemistest.ase.in.tum.de.
- [X] ~I documented my source code using the JavaDoc / JSDoc style.~
- [X] ~I added integration test cases for the server (Spring) related to the features~
- [X] ~I added integration test cases for the client (Jest) related to the features~
- [X] ~I added screenshots/screencast of my UI changes~
- [X] ~I translated all the newly inserted strings~

### Motivation and Context
We want to stay up-to-date with all dependencies

### Description
I updated `interactjs` and `ng-bootstrap`.
- [x] We use `interactjs` to enable collapsable and resizable side menus. The new version included some API changes @thilo-behnke Could you please have a look if everything in the code editor is still working as expected?
- [x] We use `ng-bootstrap` throughout the whole application. One small issue that I noticed is that our notification popup is cut off. @lovaiible could you please have a look why this happens? Update: I was able to fix the problem

image

### Steps for Testing
1. Login
2. Play around in all areas of the app and look for UI problems.

### CODE REVIEW

**Comment by ungaralex** [comment]
> When opening the code editor and submitting a result, I get a server error (500). Additionally, the instructions are partially displayed outside of the box (The bottom of the div).
> artemi_dep_update_error_prog_exc

I'm sorry, the error was caused by the guided tour settings. The build button still hangs, though. And the output also doesn't get updated

**Comment by krusche** [comment]
@ungaralex good finding, thanks.
@thilo-behnke could you have a look why the instructions go over the border? Might be easy to fix!

**Comment by krusche** [comment]
The bamboo build did not really fail, I run it manually by accident and stopped it.

**Comment by krusche** [comment]
@ungaralex which browser do you use? I tried to reproduce the problem in the code editor on Safari and Chrome and for me it does not go beyond the border

image
I noticed another small issue marked in the following screenshot. The white box is not aligned in the upper right and lower right corner, however this also happens on production.
We should definitely fix this small issue, but we could do this in another PR @thilo-behnke 
image

**Comment by ungaralex** [comment]
I used Firefox

**Pull request merged**
