### PR TITLE
Exam Mode User Documentation Improvements

### PR DESCRIPTION
**Pull request by JohannesWeiss**
### Motivation and Context
During reviewing the Exam Mode documentation we found some typos, inconsistencies and smaller errors in the user documentation. In this short PR we want to fix them and improve the documentation before the exam period starts.

### Description
Fixed errors and other issues we found in documentation. 

### Steps for Testing
Only documentation changes. No code changes.

This is our first PR here, so if you have feedback please contact us :)

### CODE REVIEW

**Review by airelawaleria — CHANGES_REQUESTED** [review]
Add documentation for "assess unsubmitted student exams"

**Review by marvinchimeka — COMMENTED** [review]
like @airelawaleria said

**Review by simonzilker — APPROVED** [review]

**Review by EneaGore — APPROVED** [review]

**Comment by JohannesWeiss** [comment]
All smaller mistakes and typos we found are fixed now. Some of the unclarities need to be discussed further and may then be resolved in a follow-up.

**Review by airelawaleria — APPROVED** [review]

**Review by valeriebucher — APPROVED** [review]

**Review by FrankeLukas — APPROVED** [review]

**Review by jpbernius — APPROVED** [review]
👍

**Pull request merged**
