### PR TITLE
[Feature] Learning Goal Instructor View

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

As an instructor it is useful to know how the class is doing on average on a learning goal. This PR implements this feature.

### Description

- New Query to calculate various statistics for exercises (average score etc)
- Used that query to calculate the average course progress for a learning goal 
- Changed client implementation of learning-goal-management to show the average course progress

### Steps for Testing

1. Set up a learning goal with connected exercise units (where results exist)
2. Check that learning goal management calculates the course average

### Test Coverage

Client
learning-goal-course-detail-modal.component.ts 100%

Server
LearningGoalService.java 98%
LearningGoalResource.java 90%
ExerciseService 91%

### Screenshots

image
image

### CODE REVIEW

**Review by airelawaleria — CHANGES_REQUESTED** [review]
Tested with @simonzilker @JohannesWeiss @marvinchimeka . We get a translation-not-found each time we go to the LG management page. And the calculation is not working
image

**Review by marvinchimeka — COMMENTED** [review]
Confirming @airelawaleria's request.

**Review by JohannesWeiss — COMMENTED** [review]
Can confirm the issue stated by @airelawaleria .

**Review by simonzilker — COMMENTED** [review]
What @airelawaleria said

**Comment by stefanwaldhauser** [comment]
> Confirming @airelawaleria's request.



> Can confirm the issue stated by @airelawaleria .



> What @airelawaleria said

I now about this error the necessary view is seemingly not created in the db on the testserver. Will put it into draft until the reason can be found. Help much appreciated @krusche @jpbernius

**Comment by stefanwaldhauser** [comment]
> > Confirming @airelawaleria's request.
> 
> > Can confirm the issue stated by @airelawaleria .
> 
> > What @airelawaleria said
> 
> I now about this error the necessary view is seemingly not created in the db on the testserver. Will put it into draft until the reason can be found. Help much appreciated @krusche @jpbernius

It should be fixed now :)

**Review by airelawaleria — APPROVED** [review]
Tested on ts1 with @EneaGore @simonzilker @JohannesWeiss and @marvinchimeka. Everything worked

**Review by simonzilker — APPROVED** [review]
Approve

**Review by EneaGore — APPROVED** [review]
All works as expected on ts1.

**Review by JohannesWeiss — APPROVED** [review]
Approve!

**Review by marvinchimeka — APPROVED** [review]
tested in testing session. works fine

**Review by valeriebucher — APPROVED** [review]
Works as described. Tested on ts3

**Review by tiffca — APPROVED** [review]
Works as described. No issues encountered from instructor/student view.

**Review by nicolasruscher — APPROVED** [review]
Tested and found no issues. 👍 👍  Didn't test every edge case tho

**Review by krusche — APPROVED** [review]

**Pull request merged**
