### PR TITLE
[Enhancement] Add audit event logs for grading actions

### PR DESCRIPTION
**Pull request by schultek**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

Better logging.

### Description

Added audit logs for 
- Re-Evaluate
- Trigger-All
- Reset Grading

### Steps for Testing

**A:** Test on the test-server, that the three above actions still work.

1. Log in to Artemis
2. Navigate to the grading page of a programming exercise
3. Test the 'Re-Evaluate' button and check the updated results
3. Test the 'Trigger-All' button and check the new results
4. Test the 'Reset' button (works only for test cases)

**B:** Test locally, that for each of the above actions an audit log appears in the database

1. Do the same steps as in **A**
2. Open the _jhi_persistent_audit_event_ table for your local Artemis database
3. Check that for each action an audit event exists (ReEvaluate, TriggerAll, Reset)
4. Open the _jhi_persistent_audit_evt_data_ table for your local Artemis database
5. Check that each audit event has the correct details (exercise, course, etc.)

### Test Coverage

Nothing changed.

### Screenshots

example _jhi_persistent_audit_event_ table
Bildschirmfoto 2020-12-03 um 11 41 24
example _jhi_persistent_audit_evt_data_ table
Bildschirmfoto 2020-12-03 um 11 41 37

### CODE REVIEW

**Review by DenizShabani — COMMENTED** [review]
Tested on TS1 for Part A and everything worked as intended. For Part B i cannot test it locally.

**Review by marvinchimeka — COMMENTED** [review]
Tested on Ts1. I could only test this PR on a test server, so I tested the A part. It worked fine, except for one exercise which I have participated in. I was not able to re-evaluate. Instead of that I got this exception below. But after refreshing the page it worked.
After that I submitted another programming exercise and there it went fine. So I think that this exception happened by chance. But in total I would approve the A part.
Bildschirmfoto 2020-12-03 um 12 04 32

**Review by airelawaleria — COMMENTED** [review]
Part A worked fine, without any errors

**Review by simonzilker — COMMENTED** [review]
Did not had any errors in part 1. Cannot test part 2

**Review by JohannesWeiss — COMMENTED** [review]
Part A worked as intended for me as well.

**Review by krusche — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
