### PR TITLE
`Programming exercises`: Increase the legend's readability of charts in feedback details

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

A student complained that the legend below the chart representing the reached score for a programming exercise is rather hard to read with the new implementation. After looking at the screenshot, I have to agree, the font is not optimal per default with `ngx-charts`.

### Description

I changed the font size to bolder as well as the font color. 

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Programming Exercise with at least one commit of the student. You can use [this submission](https://artemistest.ase.in.tum.de/courses/481/exercises/13320) on TS1 of test user 2 if you want.

1. Log in to Artemis
2. Navigate to the exercise details of the programming exercise
3. Click on the feedback on the right (XY of Z passed...)
4. Inspect the legend. Make sure the Points are now easier to read.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

Nothing changed

### Screenshots

Old legend appearance:
image

**New** legend appearance:
image

### CODE REVIEW

**Review by filip-gregurevic — APPROVED** [review]
Looks good to me 👍🏼

**Review by Malyuk-A — APPROVED** [review]
Code looks good, thanks for applying my suggestions 👍

**Review by dveljacic — APPROVED** [review]
Tested on TS1. Looks good ✅ 

test_4496_bolded

**Review by baranimo7 — APPROVED** [review]
Ekran Resmi 2021-12-14 12 10 11
Tested on ts2. The color changes are as expected.

**Pull request merged**
