### PR TITLE
`Exam mode`: Fix the number of complaints in the exam assessment dashboard 

### PR DESCRIPTION
**Pull request by Santia-go**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
When an exam receives a complaint, the dashboard shows this complaint as solved. 
Screenshot 2022-03-23 at 17 21 45

That is wrong because, without a response, the dashboard should show **0/1 (0%)**. Otherwise, the instructors will think that all complaints were solved. 

According to the presentation of the information, some minor corrections are applied. 

### Description
Now, every time a complaint is submitted, the counting is correct. 

- If there are 2 complaints without an answer, the dashboard will show 0/2 (0%). 
- If one of these is answered, the dashboard will show 1/2 (50%). 
- If all complaints were answered -> 2/2 (100%)   

**Just like the exercises dashboard works.** 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming/Text/Modeling Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration
3. Create an exam
4. Add a couple of exercises with enabled complaints (at least 2)
5. The student submits the exam
6. The instructor makes the assessment 
7. The student submits a complaint to each exercise
8. Verify that the 2 complaints are shown in the dashboard 0/2 (0%)
9. Answer one complaint and verify the dashboard shows Complaints: 1/2 (50%)
10. Answer the second complaint and verify the dashboard shows Complaints: 2/2 (100%)

Reviewers can use the number of exercises and complaints they prefer. They just need to verify that the counting is correct. 

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### CODE REVIEW

**Review by mallgaier — APPROVED** [review]
Tested the basic workflow and the number of complaints is displayed correctly

**Review by Dominik-Weinzierl — APPROVED** [review]
Works as described :+1:

**Comment by Hialus** [comment]
Tested on TS1. Works as expected.
Code changes also look reasonable.
👍🏻

**Review by Hialus — APPROVED** [review]

**Review by canberkanar — APPROVED** [review]
Tested locally. Functionality is as intended.

**Pull request merged**
