### PR TITLE
[Feature] Activate/Deactivate SCA on import

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Instructors often want to reuse programming exercises (import) from previous semesters. This PR allows them to retroactively activate/deactivate SCA for those exercises on import. The SCA option can only change, if the build plans are recreated and template files updated.

### Description

- Update template files deletes the legacy testUtils folder which was moved to AJTS
- Add/Delete all SCA configurations in the test repository for activation/deactivation of SCA on import
- Create default categories if the source exercise for the import has SCA deactivated
- Add validation for the dependency between the change of the SCA option, the recreate build plans and update template files options
- The client automatically activates recreate build plans and update template files if the SCA option changes
- The client automatically reverts the SCA option, if recreate build plans or update template files is deactivated
- Add server tests
- Add client tests

### Steps for Testing

**Import: without SCA -> with SCA**
1. Create a programming exercise without static code analysis (EXwithoutSCA)
2. Add a folder testUtils and some dummy files to the test repository under test/{packageName}/ like in the screenshot below
image
3. Open the import dialog by importing EXwithoutSCAand activate SCA. 
--> If SCA is activated recreation of build plans and update of template files should be automatically selected. 
--> If recreation of build plans or update of template files is deactivated, the SCA option should revert to its original state
4. Create the exercise (importedExWithSCA)
--> In the test repository, the testUtils folder and its content should not exist
--> In the test repository, a staticCodeAnalysisConfig folder should be created with three config files
--> In the test repository pom.xml, check that plugins for Spotbugs, PMD and Checkstyle are created
--> Go to the grading page and check that the categories are created
--> Participate in the exercise, and an unused variable and check that the issue is found

**Import: withSCA -> without SCA**
1. Open the import dialog by importing importedExWithSCA deactivate SCA. 
--> If SCA is deactivated recreation of build plans and update of template files should be automatically selected. 
--> If recreation of build plans or update of template files is deactivated, the SCA option should revert to its original state
2. Create the exercise (importedExWithoutSCA)
--> In the test repository, a staticCodeAnalysisConfig folder should not exist
--> In the test repository pom.xml, check that plugins for Spotbugs, PMD and Checkstyle do not exist
--> Go to the grading page and check that SCA grading options do not exist
--> Participate in the exercise, and check that no SCA is executed by adding an unused variable (no feedback for it should appear).

### Test Coverage

ProgrammingExerciseResource: 82% -> 82%
ProgrammingExerciseImportService: 95% -> 95%
JavaTemplateUpgradeService 4% -> 35% (need to check file level operations without mocking the repositories completely -> follow up)
ProgrammingExerciseUpdateComponent: 67% -> 80%

### CODE REVIEW

**Review by philgabr — CHANGES_REQUESTED** [review]
I just tested on ts1, unfortunately the testUtils folder still existed in the importWithSCA test repository and no staticCodeAnalysisConfig folder was created...

I used build 8 as later ones failed, exercises in Philipp's TestCourse (ts1) -> progex_nosca, progex_import_sca, progex_import

**Comment by kloessst** [comment]
> 
> 
> I just tested on ts1, unfortunately the testUtils folder still existed in the importWithSCA test repository and no staticCodeAnalysisConfig folder was created...
> 
> I used build 8 as later ones failed, exercises in Philipp's TestCourse (ts1) -> progex_nosca, progex_import_sca, progex_import

Thanks for testing. Build 8 is quite old, could u please try again with build 16 or later?

**Review by airelawaleria — APPROVED** [review]
Tested on ts1. Everything worked according to the steps

**Review by JohannesWeiss — APPROVED** [review]
Tested in testing session with @airelawaleria, @simonzilker and @marvinchimeka on ts1, did work as expected.

**Review by simonzilker — DISMISSED** [review]
Tested in testing session. Everything works as described!

**Review by marvinchimeka — APPROVED** [review]
Works fine.

**Review by philgabr — DISMISSED** [review]
Everything works as intended now :+1:

**Review by airelawaleria — APPROVED** [review]
Re-tested with @simonzilker @EneaGore , re-approve

**Review by simonzilker — APPROVED** [review]
Everything works as described!

**Review by EneaGore — APPROVED** [review]
Works as expected.

**Review by JohannesWeiss — APPROVED** [review]
Still works, re-approve!

**Review by marvinchimeka — APPROVED** [review]
Re-approve ! No issues found

**Review by tiffca — APPROVED** [review]
Tested successfully on ts1 !

**Review by JannisBittlmayer — APPROVED** [review]
Tested on TS1, everything works as intended.

**Review by FlorianStang — APPROVED** [review]
Tested on TS1,  everything worked as described.

**Review by derLalla — DISMISSED** [review]
I've tested the functions also with the Swift SCA and everything works fine! 

The code is also looking great, good job 👍

**Pull request merged**
