### PR TITLE
`Assessment`: Add option to hide optional exercises in assessment dashboard

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Artemis offers the option to not include exercises in the score of the course. These exercises might be used for example in tutor groups or for training purposes of students.
Some of these exercises are not graded at all, even though the students can participate and submit in these exercises. For example a modeling exercise that is discussed at the end of the tutor group.
Additionally tutors sometimes want to focus on the exercises that matter for the students' scores first since they might be more important than optional exercises.

### Description

This PR adds a filter to the assessment dashboard to filter all optional exercises.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 3 exercises that need some kind of assessment (One with unfinished assessments, one fully assessed, one which is not included in the score of the course)
- An exam with at least one submission and two correction rounds (may be an old exam)

1. Log in to Artemis
2. Navigate to assessment dashboard
3. Make sure that both filters work
4. Check that you can still enable/disable the second assessment and sort the rows correctly

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

assessment-dashboard.component.ts: 93% -> 94%

### Screenshots
Completely unfiltered:
Bildschirmfoto 2021-12-20 um 14 17 01
Finish exercises filtered out: (standard)
Bildschirmfoto 2021-12-20 um 14 15 29
Finished and optional exercises filtered out:
Bildschirmfoto 2021-12-20 um 14 15 34

### CODE REVIEW

**Review by mallgaier — COMMENTED** [review]
Tested on ts3. 
"HideOptional" works as expected.
However, "HideFinish" hides all tasks for me. Thus, tasks that still have unassessed submissions are also hidden. Regardless of whether they are optional, a DueDate has been set or the DueDate is in the future / past. Is this intended?

**Comment by JohannesStoehr** [comment]
> Tested on ts3.
> "HideOptional" works as expected.
> However, "HideFinish" hides all tasks for me. Thus, tasks that still have unassessed submissions are also hidden. Regardless of whether they are optional, a DueDate has been set or the DueDate is in the future / past. Is this intended?

"Hide finished" replaces the current "Show finished exercises" and should hide all exercises that are finished from a tutors perspective. So you should only see exercises that need some kind of assessment. This is not affected by the deadline at all.
Do you have a better idea for the label that is less confusing?

**Review by mallgaier — CHANGES_REQUESTED** [review]
`Hide finished` hides all tasks, even those that still need to be assessed. And regardless of whether the deadline is in the past/future, a deadline has not been specified or the task is optional.
I have tested this with [Dominik's Test Course](https://vmbruegge60.in.tum.de/course-management/2480/assessment-dashboard) . The underlined tasks should remain visible, as there are still assessments pending. But these are also hidden. Non of these exercises remain visible after selecting `Hide finished`.
 I **personally** find `finished` a bit misleading as finished, in my interpretation, means that the task is closed, hence no action by the tutors/instructors will be necessary. But a finished task becomes unfinished again as soon as there are complaints/feedbackRequests. Therefore, my suggestion is to change this to `Hide fully assessed` / `Hide completely evaluated ` 
image

**Review by mallgaier — APPROVED** [review]
Tested with [Dominik's Test Course (TS3)](https://vmbruegge60.in.tum.de/course-management/2480/assessment-dashboard)
Both options `Hide finished` and `Hide optional` work as expected, the Requested Changes have been incorporated accordingly, and only now finished and/or non-optional tasks are displayed respectively.

**Pull request merged**
