### PR TITLE
[Bugfix] Fix Back Button

### PR DESCRIPTION
**Pull request by MDK5**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context
Resolves part of https://github.com/ls1intum/Orion/issues/50

### Description
The back-button just used location.back, which doesn't work if there is no previous page e.g. because Orion directly loads the correct link without entering the overview.

Artemis does have a helper to solve this issue, however the helper is not working correctly because it uses history.length to check if the page is the first page which does not work reliably since Firefox counts from 1, while Chrome counts from 2 (Chrome also counts the empty page). As discussed in great length [here](https://stackoverflow.com/questions/3588315/how-to-check-if-the-user-can-go-back-in-browser-history-or-not), there is no reliable solution. Thefore I added a new service that tracks the internal navigation, being independent from javascript primitives.

### Steps for Testing
1. Log in to Artemis
2. Create/Locate an exercise as student
3. Click on the back button
grafik
4. You should end up on the previous page
5. Navigate to the exercise from a different source, e.g. by clicking on the diagram points on the statistics page
grafik
6. The back button should correctly lead you back to the different previous page
7. Copy and paste the url of the programming exercise into a new window/tab
8. The back button should now lead to the exercise overview
9. Also check the other buttons by copy/pasting the url and making sure it is still returned correctly. See changes for details.
    1. Save/Cancel after creating/editing a system notification
    2. Save/Cancel after creating/editing a user
    3. Save/Cancel after creating/editing a course
    4. Save/Cancel after creating/editing an exam
    5. Save/Cancel after creating/editing an exercise hint
    6. Save/Cancel after creating/editing a lecture
10. Optional: Try out different browsers

### Test Coverage
navigation.utils.ts 73.8% -> 82.1%

### CODE REVIEW

**Review by JohannesStoehr — DISMISSED** [review]
Tested on ts1 using the latest version of Safari.
Works well! 👍

**Review by PatZintel — APPROVED** [review]
worked as described on ts1 with latest Chrome

**Review by lschlesinger — APPROVED** [review]
I tested on TS1 and used Firefox (85.0). Nice changes, code looks good!!
Some thoughts... 
1. when selecting a lecture, there is no "back arrow", which is not consistent with the exercise use case. We could add the arrow and use the functionality implemented by use here as well.
2. when editing an exercise we should not end up in the page visited before, but we rather see the details page. But for changes in a course/lecture/exam we will be redirected to the previous page after saving the changes... should this be made consistent?

**Review by FrankeLukas — APPROVED** [review]

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3

**Comment by MDK5** [comment]
> 
> 
> I tested on TS1 and used Firefox (85.0). Nice changes, code looks good!!
> Some thoughts...
> 
>     1. when selecting a lecture, there is no "back arrow", which is not consistent with the exercise use case. We could add the arrow and use the functionality implemented by use here as well.
> 
>     2. when editing an exercise we should not end up in the page visited before, but we rather see the details page. But for changes in a course/lecture/exam we will be redirected to the previous page after saving the changes... should this be made consistent?

1. While I agree that the navigation is not consistent there I think this is out of scope for this PR
2. I now also adapted the behavior for exercises although I am surprised you observed buggy behavior, previously the exercises were using the method with window.history.length which should work in Firefox (although not in Chrome)

**Review by rs-maker — APPROVED** [review]
Tested on Ts3 using the most recent version of chrome this seemed to work fine.

**Review by ArtemTsurikov — APPROVED** [review]
Tested on TS1, looks good

**Review by canyelten — APPROVED** [review]
Tested on TS1, the back button works correctly for all test cases.

**Pull request merged**
