### PR TITLE
`Programming exercises`: Improve usability for grading configuration

### PR DESCRIPTION
**Pull request by simon-hng**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Adds the option to collapse and expand all test cases so that grading configuration is possible like it was in the prior interface with only test cases.

### Description

- Adds two buttons to collapse and expand all test cases
- Adds translations for test/task types
- Make weight, bonus points and bonus multiplier columns smaller and replaces their headings with icons
- Adds numeration of tasks and tests
- Fixes an issue where inactive test cases are also included in the task weight

### Steps for Testing

Prerequisites:
- 1 Programming Exercise

1. Go to the grading configuration e.g. `ARTEMISURL/course-management/4/programming-exercises/14/grading/test-cases`
2. Click the buttons and see if tasks collapse/expand correctly
3. Toggle tasks individually by clicking the arrow heads and try out the added buttons.

### Screenshots

image
image

### CODE REVIEW

**Review by terlan98 — COMMENTED** [review]
Tested on TS2. The buttons work as expected. 

There are some translation issues but I'm not sure if all of them should be a part of this PR:
Screenshot 2023-04-09 at 21 34 05

**Review by terlan98 — DISMISSED** [review]
Retested on TS2 and reapproved

**Review by terlan98 — APPROVED** [review]
Reapproved

**Comment by bassner** [comment]
A little thing that seems disturbing is that if some tasks are already expanded it looks like  they are all closed for a very short time and expanded again if you click "Expand all". Is this expected or can we fix this? :)

https://user-images.githubusercontent.com/23171488/232602456-aa9adde4-1129-4961-b591-e604d530c789.mov

**Review by bassner — APPROVED** [review]
Tested on TS1, LGTM!

**Review by terlan98 — APPROVED** [review]
Tested on TS2 and reapproved. The task expansion behavior is now improved 👍

**Review by 1999Markus — APPROVED** [review]
Tested on TS2, LGTM.

**Pull request merged**
