### PR TITLE
`Development`: Remove moved to the Lecture microservice features from the Artemis microservice

### PR DESCRIPTION
**Pull request by MerlinMehmed**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] * This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
- [ ] * not relevant

### Motivation and Context

This PR is the final one for the migration of the Lecture microservice.

### Description

It removes the features related to lectures from Artemis which were moved to the Lecture microservice. Code review should be fast as there are only ~100 lines added and the deleted files already exist in the Lecture microsercvice /lecture.

Since code that was covered by tests is removed from Artemis there is a slight drop in the test coverage which required the change of the coverage rules.

### Steps for Testing

Prerequisites:
- Test server 6: [https://artemistest6.ase.in.tum.de/](https://artemistest6.ase.in.tum.de/) - it is already deployed there
- 1 Instructor (artemis_test_user_12 or you can create another instructor account using the server administration)
- 1 Student (artemis_test_user_1 or you can create another student account using the server administration)

1. Log in to Artemis on [https://artemistest6.ase.in.tum.de/](https://artemistest6.ase.in.tum.de/)
2. Navigate to Course Management
3. Open/Create a course and create a lecture => lecture should be successfully created
5. Edit the lecture => the lecture should be successfully updated
6. Add attachments and lecture units of all types to the lecture => should work fine
7. Navigate to course overview (as a strudent) and the lecture you created => the lecture should be there including the units and the attachments you added
8. Edit the lecture units => should work fine
9. Open the lecture and check that the exercise is removed from the lecture units list
10. Go back to Course Management as an instructor and delete lecture unit(s) => should work fine
11. Delete a lecture => the lecture should be successfully deleted

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### CODE REVIEW

**Review by nairaarnez — CHANGES_REQUESTED** [review]
Tested in ts6 as described, sadly I encountered several issues.
1. It is not posible to create a programming exercise. When this one is created, the following error appears. 
errorWhileCreatingExercise
 When pressing save again, the following message appears
alreadyExists
the programming exercise is not to be seen in the exercises.
(This issue happens only with programming exercises, the other exercises work fine)


2. The student can see the course, but he cannot see the exercises
studentview

**Comment by MerlinMehmed** [comment]
Thanks for testing @nairaarnez. It looks like there is an issue connecting to Bitbucket (due to wrong credentials) which is the reason why programming exercises cannot be created. Will check it and let you know when it's fixed

**Comment by MerlinMehmed** [comment]
@nairaarnez indeed there were server configuration issues. Thanks to @Mtze for fixing them. 
If you can, could you please retest, please?

**Review by Marvin-Vitcu — APPROVED** [review]
Tested on TS1.
Works as intended.
Got no problems with creating programming exercises.

**Review by nairaarnez — CHANGES_REQUESTED** [review]
I just retested your PR, and almost everything is working good! The only issue that remains unresolved is that the existence of Exercises is inconcistent (point 2 of my first review) . 

Course overview from the instructor view:  The exercises exist
image

course management overview from the instructor view: The exercises do not exist
image

Exercises inside of the course, under course Management: The exercises exist
image

From the Student view: The exercises do not exist
image

Other than that, works as expected!

**Comment by nairaarnez** [comment]
@Marvin-Vitcu could you also see the exercises from the Student perspective when you tested this PR?

**Comment by krusche** [comment]
Due to increase maintenance, we do not pursue the split into multiple applications as part of micro services. In fact, @sleiss is trying out a different, less disruptive approach as part of his master thesis.
Therefore, I close this PR.
@MerlinMehmed thanks for your effort, at the moment it's not necessary any more to keep the `develop-microservices` branch up-to-date.

**Pull request closed without merging**
