### PR TITLE
`Communication`: Group consecutive messages

### LINKED ISSUE #9594: Delete message is overlapped by scroll bar
### Describe the bug

I am unable to delete messages as the scrollbar for the messages field is covering the delete option. When I try to hever over the delete icon it reveals the scroll bar and the button is not accessible.

Image 1:
image

Image 2 (cursor is not showing on screenshot but it is right above the delete icon):
image

### To Reproduce

Using Firefox and Artemis web:
1. Open any communication channel with enough messages to make the scroll bar appear
2. scroll to the latest message
3. write a new message if there is none you can delete
4. try to delete the message

### Expected behavior

The delete button should be accessible no matter how large your display is and where your current view is scrolled to.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

7.6.3

### What browsers are you seeing the problem on?

Firefox

### Additional context

-- Current workaround: open message in thread view and delete it from there

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [X] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Most chat applications group messages from the same user within short time intervals for a more intuitive and user-friendly experience. In Artemis, messages have the same spacing regardless of whether they're seconds or days apart, making the interface less engaging. This update aims to adjust message spacing dynamically to enhance the chat experience.

(Also closes #9594 and #9503)

### Description

- Messages from the same user within a 5-minute timeframe are now grouped and appear closer together.
- All message actions (reply, edit, delete, react) are now displayed side by side when hovering over the message, similar to standard chat applications.
- An emoji add button has been added next to existing emoji reactions on messages, providing a familiar experience consistent with modern chat interfaces.
- A right-click dropdown menu has been added for each message, offering options like edit, delete, reply, pin, and add reaction, similar to Slack.
- A yellow background has been applied to pinned messages. (As discussed in the communication subgroup, pinned messages will be accessible in a separate tab in the future.)

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis.
2. Navigate to the Communication section of a course and open a channel.
3. Write 3 consecutive messages to the channel.
4. Verify that the messages are grouped/appear closer together.
5. Hover over each message and test all actions: reply, edit, delete, pin, and react with an emoji.
6. Reply to one of the messages using consecutive messages and verify that they are also grouped correctly.
7. Hover over these consecutive messages and repeat testing all actions: reply, edit, delete, pin, and react with an emoji.
8. Right click on any message to open its related dropdown menu, test all available options on it.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| answer-post.model.ts | 100% | ✅ |
| post.model.ts | 100% | ✅ |
| conversation-messages.component.ts | 96.42% | ✅ ❌ |
| answer-post.component.ts | 92.68% | ✅ ❌ |
| post.component.ts | 95.69% | ✅ ❌ |
| answer-post-create-edit-modal.component.ts | 94.87% | ✅ ❌ |
| answer-post-footer.component.ts | not found (deleted) | ❌ |
| post-footer.component.ts | 98.52% | ✅ ❌ |
| answer-post-header.component.ts | 84.21% | ✅ ❌ |
| post-header.component.ts | 95.45% | ✅ ❌ |
| answer-post-reactions-bar.component.ts | 94.59% | ✅ ❌ |
| post-reactions-bar.component.ts | 93.67% | ✅ ❌ |
| posting-reactions-bar.component.ts | not found (renamed) | ❌ |
| posting-thread.component.ts | 100% | ✅ |
| posting.directive.ts | 100% | ✅ |

### Screenshots

image

image

## Summary by CodeRabbit

- **New Features**
	- Introduced optional `isConsecutive` property for `AnswerPost` and `Post` classes.
	- Enhanced layout of conversation messages by grouping posts.
	- Added a new Angular pipe for date transformation and improved post grouping methods.
	- New classes added for improved styling in message components.
	- Updated components to conditionally render based on the `isConsecutive` property.

- **Bug Fixes**
	- Improved conditional rendering based on the `isConsecutive` property across various components.

- **Style**
	- Updated styles for improved layout and user interface across multiple components, including new classes for better spacing.

- **Tests**
	- Added and updated tests to ensure functionality for new features and changes in components, including role-based visibility and grouping logic.

### CODE REVIEW

**Review by anian03 — CHANGES_REQUESTED** [review]
Tested on TS5, generally it works but I noticed two things:

- In a thread, the button for "message resolves thread" (the tick) is only available for the first of consecutive messages. We probably should have this option available for all messages, like editing and deleting.
- I noticed that the options bar on regular messages often overlaps the message itself. Is this intentional? Considering that there is quite a bit of room in between the messages, we could probably position the menu in a way that doesn't overlap the content 
overlapping content

**Review by edkaya — CHANGES_REQUESTED** [review]
Tested on ts4, consecutive messages are grouped together 👍 However, I found some minor issues regarding the layout. 
- I think elements in post reaction bar are not aligned correctly, reply button seems a little bit off to me. Can you add `align-items-center` in the first line of this component? Besides, when hovering on the message, the white background of the reaction bar disrupts the layout there. I think we can provide some border or something similar (see screenshot). We can also display them in the message bar when we hover on the message instead of letting them pop out at top. 
Screenshot 2024-10-12 at 16 29 22

- Secondy, when I send another message 4-5 min after the consecutive messages, the new message (Test Message 16.40) is still displayed/grouped with older messages. I think it should not be grouped with old messages. 
Screenshot 2024-10-12 at 16 40 53

**Comment by asliayk** [comment]
> Tested on ts4, consecutive messages are grouped together 👍 However, I found some minor issues regarding the layout.
> 
> * I think elements in post reaction bar are not aligned correctly, reply button seems a little bit off to me. Can you add `align-items-center` in the first line of this component? Besides, when hovering on the message, the white background of the reaction bar disrupts the layout there. I think we can provide some border or something similar (see screenshot). We can also display them in the message bar when we hover on the message instead of letting them pop out at top.
> 
> Screenshot 2024-10-12 at 16 29 22
> * Secondy, when I send another message 4-5 min after the consecutive messages, the new message (Test Message 16.40) is still displayed/grouped with older messages. I think it should not be grouped with old messages.
> 
> Screenshot 2024-10-12 at 16 40 53

- I added a border and `align-items-center` for the reaction bar style.
- What do you mean by displaying them on message bar? Since the conversation messages are closer now, I think it is not possible to display the reaction bar without hovering effect. If we display the reactions in the message bar, it may overlap with the content and make it harder to read. 
- I grouped the messages based on a 1-hour window because I thought that's how Slack does it, but I can adjust it to any preferred time interval.

**Comment by anian03** [comment]
> I grouped the messages based on a 1-hour window because I thought that's how Slack does it, but I can adjust it to any preferred time interval.

The iOS app currently has a timeout of 5 minutes. On Slack it’s also something similar (definitely under 10 minutes, so probably also 5), so for consistency I think 5 min makes sense :)

**Review by sachmii — COMMENTED** [review]
Tested on TS3 and TS4, emojis, deleting and updating works as described. Also the messages are grouped together. Yet when I pin the message, it won't appear as pinned:

no pinning

Also, the "Show 1 reply" doesn't appear below the message and I think it would be better if it did appear there so you won't have to hover over each message to know which one is in a thread and which one not.

threads show up only when hovering

**Review by HawKhiem — COMMENTED** [review]
I tested on test server 3. Delete, edit, comments and react worked as expected. The messages are also group as expected. The pin function doens't seem to work. I would also recommend to put the options bar closer or even better, when right click on a message, a pop up would appear and allow users to choose weather to comment, edit or react, similar to that in slack for example. The current options bar are a bit to far and pose to be a nuance when one wants to move the mouse there to choose to comment


Screenshot 2024-10-16 155333

**Review by janthoXO — CHANGES_REQUESTED** [review]
Im not sure if it is related to this PR at all, but why has the add button for an emoji more height than the commented emoji?
image

Otherwise it looks good 👍

**Review by sachmii — DISMISSED** [review]
Tested on TS4, works fine! Nice changes

Bildschirmfoto 2024-10-24 um 23 43 42

**Review by flbrgit — COMMENTED** [review]
Tested on TS2 and if the space between the lines "abc" and "def" is the intended one, all functionality works as described. However, the tooltip after hovering a message and the tooltip after right-clicking on a message is cut of at screen end
Screenshot 2024-10-26 160603

**Review by sachmii — APPROVED** [review]
Tested on TS3, re-approve.

**Review by HawKhiem — DISMISSED** [review]
Tested on TS2. Reapprove

**Review by HawKhiem — APPROVED** [review]
Tested again on TS4. Everything works as described

**Review by sachmii — APPROVED** [review]

**Review by SindiBuklaji — APPROVED** [review]
Tested on TS5 and everything works as described. Nice features 👍

**Review by Cathy0123456789 — DISMISSED** [review]
Tested on TS5. Works as described, looks good!
image

**Review by ahbitaqu — APPROVED** [review]
[Tested on TS2]
Reviewed all features as described in the PR, and even tested some edge cases e.g. with editing messages. Works fine for me :)

**Review by edkaya — DISMISSED** [review]
Tested on ts1, works as expected. Thanks for fixing the issues 👍

**Review by sachmii — APPROVED** [review]
Tested on TS1, reapprove.

Bildschirmfoto 2024-11-04 um 12 00 13

**Review by edkaya — APPROVED** [review]
Reapprove after fixing codacy issues

**Review by ahbitaqu — APPROVED** [review]
[Tested on TS1 | reapprove]
Everything works just fine. Small visual enhancement: center the smiley for the react button vertically
grafik

**Review by vinceclifford — APPROVED** [review]
Tested on TS6, works as expected.

**Review by anian03 — APPROVED** [review]
Tested on TS2, changes work as described.

During testing I had one issue: When I replied to a message that had reactions, those reactions disappeared after sending my reply. After about 15-20 seconds they appeared again. This was not reproducible though, so maybe it was just a connection issue or something and is not related to this PR.

**Review by PaRangger — APPROVED** [review]
Tested on TS2, works great! Code LGTM.

Small remarks for later PRs: I noticed that in the "Lecture" view, the Reply buttons are a bit off now. Also on Mobile the icons seem to be a bit off. On mobile its great that you can tap on a message and show the new toolbar, but when you scroll it also shows the toolbar on tapdown and tapup, which is a bit off-putting.

Bildschirmfoto 2024-11-08 um 14 14 59

**Review by julian-wls — APPROVED** [review]
Just tested on TS2. I didn't encounter any issues. 
Nicely done!

**Pull request merged**
