### PR TITLE
`Development`: Make command execution in local continuous integration compatible with Podman

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Podman (https://podman.io/) is a drop-in replacement for Docker that allows to run containers without having to have `root` permissions (or having a `root`-privileged socket). This would require less privileges to run containers which provides improved security for running untrusted code in a production system. We should therefore aim to support both Docker and Podman if reasonably possible.

### Description
This PR fixes a small API incompatibility: Podman requires that at least one stream is attached to a command, or requires to explicitly set the command to be detached. The Docker API seems to implicitly set the detached flag internally.

Previous error message if both `attachStdout` and `attachStderr` are `false`:
```
[ream-1874955668] c.g.d.api.async.ResultCallbackTemplate   : Error during callback

com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"cause":"invalid argument","message":"must provide at least one stream to attach to: invalid argument","response":500}

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Steps for Testing

Prerequisites:
- Setup with localci
- 1 Programming exercise

Since this is only specific to Podman, but test servers run Docker, you can only check that no functionality is broken:

1. Trigger a build for any submission or the solution/template in the exercise.
2. A build result should be received.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

### CODE REVIEW

**Review by laurenzfb — DISMISSED** [review]
Tested on TS11 and locally, building still works. Code also LGMT! I haven't used Podman before but its sounds interesting. Can you maybe add some documentation on how to use Local CI with Podman in another PR?

**Review by Strohgelaender — APPROVED** [review]
code

**Review by mateusmm01 — APPROVED** [review]
Tested on ts6. Everything still works as expected!

**Review by reschandreas — CHANGES_REQUESTED** [review]
does Artemis work with Podman for you @b-fein? I just tested it locally and line 44 of the class `LocalCIDockerService` throws a `LastErrorException` as it can't find the image to inspect.

**Comment by reschandreas** [comment]
@b-fein ok with that change it works if I create new PE but fails at the same line for a second PE or even a rebuild of an already existing one:
```
java.lang.RuntimeException: org.apache.hc.core5.http.NoHttpResponseException: localhost:2375 failed to respond
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:195)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
	at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:74)
	at com.github.dockerjava.core.exec.InspectImageCmdExec.execute(InspectImageCmdExec.java:28)
	at com.github.dockerjava.core.exec.InspectImageCmdExec.execute(InspectImageCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at com.github.dockerjava.core.command.InspectImageCmdImpl.exec(InspectImageCmdImpl.java:39)
	at de.tum.in.www1.artemis.service.connectors.localci.LocalCIDockerService.pullDockerImage(LocalCIDockerService.java:44)

```

Seeing as this is already merged, can you maybe investigate that or check if you can reproduce that and document what needs to be done for a podman setup?

**Pull request merged**
