### PR TITLE
[Bugfix] Deactivate SCA for Haskell

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

The configuration of programming language features has an error as we do not support static code analysis for Haskell at the moment

### Steps for Testing

1. Log in to Artemis TS1/TS3
2. Navigate to Course Administration
3. Click on create programming exercise
4. Select Haskell as the language
5. Make sure that the option to activate SCA is not shown
6. Click on Generate
7. Make sure that the exercise works by participating and solving a test case

### Test Coverage

No changes

### CODE REVIEW

**Review by derLalla — CHANGES_REQUESTED** [review]
I have tested on ts1 and the SCA option was not shown. But another issue occured.
It seems that I don't have enough rights b/c the build plan of the template and solution repo did not execute any tests. 

image

I guess it is not related to this PR, but still, it needs to be fixed somehow.

**Review by sebastiantpeter — APPROVED** [review]
Tested it on ts3. It is not possible to activate SCA for Haskell anymore. It is possible to participate in the exercise, but the test cases do not work without further configuration. This seems not to be related to this PR however.

**Review by airelawaleria — APPROVED** [review]
SCA was disabled, hence approve :)

**Review by JohannesWeiss — APPROVED** [review]
Works as expected on ts1.

**Review by simonzilker — APPROVED** [review]
Works as described

**Review by marvinchimeka — APPROVED** [review]
No issues found

**Review by EneaGore — APPROVED** [review]
Could not find any issues.

**Review by philgabr — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
