### PR TITLE
`Programming exercises`: Fix an issue when displaying the clone repository button

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
On the live system, the clone button looks distorted:
grafik

grafik

### Description
#5846 set `container=body`  as default for tooltips, but removed it everywhere in the code, which were too many places.

### Steps for Testing
Prerequisites:
- 1 Student
- 1 Programming Exercise

1. Start the PE
2. Show that the clone repository button looks good.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

### Screenshots
grafik

grafik

### CODE REVIEW

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Fix works. But other buttons are broken too.
Can you take a look at #5846 and add the container="body" for other popovers as well? Or you can do some configuration for popovers in core.module.ts as #5846 did for tooltips

**Comment by simon-hng** [comment]
image

**Comment by Strohgelaender** [comment]
@JohannesStoehr I looked through all changes of that PR that were unrelated to tooltips. I fixed the clone and practice button in this PR, another changed button was the connected learning goal button where I did not find any issues: 
grafik

**Review by JohannesStoehr — APPROVED** [review]
Thanks for the quick fix

**Review by tobias-lippert — APPROVED** [review]
Tested on ts1.  Starting the exercise and the practice mode works and the button looks good.

**Review by bensofficial — APPROVED** [review]

**Review by stefanwaldhauser — APPROVED** [review]
Good hotfix!

**Comment by krusche** [comment]
Let's fix the other buttons as well please

**Review by jpbernius — APPROVED** [review]

**Comment by simon-hng** [comment]
Buttons that could be or are related to this issue 
- [ ] `clone-repo-button.component.html:11`
- [ ] `start-practice-mode-button.component.html:10`
- [ ] `theme-switch-component.html:16` (There seems to be no issue)
- [ ] `learning-goals-popover.component.html:17`
- [ ] `open-code-editor-button.component.html:25`
- [ ] `connection-warning.component.html:12`

**Pull request merged**
