### PR TITLE
`Assessment`: Fix the complaint submission for course programming exercises with multiple submissions

### LINKED ISSUE #4250: Complaints get linked to the oldest submission
### Describe the bug

When a student writes a complaint about his submission to a programming exercise, the wrong result is liked to it. Instead of using the newest one, the first one is used.

Note: This bug is time-critical since complaints are possible upon Monday in PGdP and the error occurs when the student submits a complaint.

### To Reproduce

1. You need a course with a programming exercise and a student
2. The student commits and pushes multiple times in order to create multiple submissions
3. (hidden tests are executed) [this might not be necesssary]
4. The student complaints
5. The complaint is linked to its very first submission / result which does not include the hidden tests

### Expected behavior

The result is linked to the newest result / submission.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation and Context

Fixes #4250

### Description

This issue was introduced by me in #3985. During refactoring, I moved one if clause out of another if-condition that limited the execution only to the exam mode.
This was not found in live testing because it was only detectable if there were multiple submissions for one programming exercise, a use case we didn't think of as special.

I moved the conditional to the exam overview so the complaint component can completely rely on the passed result.
I made the result optional, if the result is not defined, the complaint section won't be shown.

I did not add any tests since this situation can't happen anymore since the conditional is removed.

During testing, I also found out that for some reason the order of the submission doesn't work as before. Due to time limitations, I added a sort for this to ensure that always the latest submission gets chosen.
**Known issue:** If the latest submission is invalid it might not get filtered. This is too complex to tackle right now though.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise with Complaints enabled
- 1 Exam with Programming Exercise with Complaints enabled

1. Participate with the student in both, course exercise and exam. Make sure to submit multiple times. You can use the instructor to verify this.
2. After the deadline, complaint as a student for both exercises
3. Accept the complaint as the instructor, add some points
4. Both should work fine

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by JohannesStoehr — DISMISSED** [review]
Tested on TS1 for an automatically graded course exercise and the problem is fixed, but there are two other problems:
The student can fill out more complaints, but gets a bad request when trying to do so:
Bildschirmfoto 2021-11-05 um 10 50 46

And the feedback of the result is not properly displayed in the assessment dashboard, when I click on a result:
Bildschirmfoto 2021-11-05 um 10 51 09

**Review by MerlinMehmed — APPROVED** [review]
Tested on TS1 and didn't find issues. The issue found by Johannes is also fixed - if I have complained 3 times, the Complain button is diasbled

**Review by Hialus — APPROVED** [review]
Tested on TS1 and could not find any issues.
Good job 👍🏻

**Review by MDK5 — APPROVED** [review]
Tested on ts1, was able to complain and respond to it both normally and in exams. Code changes also look reasonable :+1:

**Pull request merged**
