### PR TITLE
`Development`: Add automatic coverage report to pull requests

### PR DESCRIPTION
**Pull request by ge65cer**
### Motivation and Context

During development, I found it exhausting and time-consuming to manually fill the Test Coverage table in our PR template.
Since the coverage reports are automatically generated, I think this process could be automated.
The automatic reports will help developers detect lines and branches that are untested in their pull requests.

### Description

Over the past months, on occasion I experimented with different solutions (e.g., [Dangerfile](https://danger.systems/js/), [GitHub Actions](https://github.com/marketplace/actions/comment-test-coverage)) to automatically add the coverage report to our PRs as a comment.
So far none were able to process both our client and server tests, which run in different CI steps, at the same time.

I recently stumbled upon [Codecov](https://codecov.io), which are able to take in multiple coverage files and generate a single report comment from them. The service is free for open-source projects.
I successfully tested it on my Artemis fork ([here](https://github.com/ge65cer/Artemis/pull/3) and [there](https://github.com/ge65cer/Artemis/pull/2)), so I think it is worth a try.
(If we are unhappy with it later, we'd only have to revert this PR commit to go back to our manual system.)

To setup, one of the Artemis maintainers needs to signup at [Codecov](https://app.codecov.io/login/gh) and add the repository (no tokens are required, as we use GitHub Actions).
Optionally, the following configuration file can be applied as a _Global YAML_ in the settings to get the same result as in my fork:
```
comment:
  after_n_builds: 2
  behavior: new
  layout: header, diff, files, flags, footer
  show_carryforward_flags: true
coverage:
  precision: 2
  range:
  - 70.0
  - 90.0
  round: down
```

#### Code Review
- [x] Review 1
- [x] Review 2

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Nice addition

**Review by simon-hng — DISMISSED** [review]
Love it!

**Review by manuelmanso — APPROVED** [review]
Awesome!

**Review by sleiss — APPROVED** [review]
Nice improvement!

**Pull request merged**
