### PR TITLE
`Development`: Split continuous plagiarism check screencast into shorter videos

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer ~~on a test server~~.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
The original CPC video was too long. Splitting it to smaller one would make it easier to comprehend by watchers.

### Description
I splatted the video into smaller parts:
1. Creating a new exercise with the CPC enabled: https://live.rbg.tum.de/w/artemisintro/42153.
2. Reviewing check's results by an instructor: https://live.rbg.tum.de/w/artemisintro/42154.
3. Reviewing check's results by a student: https://live.rbg.tum.de/w/artemisintro/42155.
4. Fixing submissions marked as a significant similarity: https://live.rbg.tum.de/w/artemisintro/42156.
5. Responding to a significant similarity plagiarism case that persisted after the exercise due date and adding a verdict to it: https://live.rbg.tum.de/w/artemisintro/42157.

### Steps for Testing
Watch the videos and verify they are cut from the original one: https://live.rbg.tum.de/w/artemisintro/42026.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

@coderabbitai ignore

### CODE REVIEW

**Review by konrad2002 — APPROVED** [review]
lgtm

**Review by lennart-keller — APPROVED** [review]
lgtm :)

**Review by tobias-lippert — APPROVED** [review]
LGTM

**Review by basak-akan — APPROVED** [review]
lgtm 👍

**Review by georgyia — APPROVED** [review]
looks great!

**Review by MarkusPaulsen — APPROVED** [review]
Changes look good

**Pull request merged**
