### PR TITLE
`Test`: Add exam management modeling/programming/quiz exercise creation tests

### PR DESCRIPTION
**Pull request by TheZoker**
#### General

- [x] Tested on my local Artemis instance
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

The current exam management test only test the creation of a text exercises. This PR adds modeling, programming and quiz exercises. More will come in the future. 

### Description

This is the first part of my exam management e2e tests, which test creating a modeling, a programming and a quiz exercise within the exam management part.  

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### CODE REVIEW

**Review by bassner — CHANGES_REQUESTED** [review]
Take care how you add ``id`` attributes. For example, in ``exercise-groups.component.html``, almost the entire file is wrapped in a ``*ngFor`` so literally everything on the page will be rendered once per exercise group. However, [IDs need to be unique.](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute)

Please use more specific IDs by integrating e.g. the current exercise IDs, course IDs, group IDs, or whatever fits the current situation to generate dynamic, unique element IDs.
We have a few examples for this in the code already, e.g.:
grafik

**Comment by TheZoker** [comment]
Thanks for pointing that out! 
I think then this original ID was problematic too, right?
https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/exam/manage/exercise-groups/exercise-groups.component.html#L74

I convert this to a draft until I figured out how to solve this in the right way (probably add the id of the group to the id of the button 🤔 )

**Comment by TheZoker** [comment]
I added the index of the current loop to the button. This should make the button id be unique and prevent unwanted sideeffects in future testing.

**Comment by TheZoker** [comment]
Bump (to avoid stale)

**Comment by TheZoker** [comment]
Temp

**Pull request closed without merging**
