### PR TITLE
`Lectures`: Use attachment name for file downloads

### PR DESCRIPTION
**Pull request by SimonEntholzer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Issue: In https://github.com/ls1intum/Artemis/pull/9721 the cryptic attachment text was removed from the filename. Unfortunately, only superficially. When actually saving the file, with Ctrl + S, the cryptic timestamp is still there.
In the URL:
image
But when saving:
image

### Description

Fixes this issue, by simply using the defined attachment name.

### Steps for Testing

1. Instructor: upload files to lecture attachments, and to lecture unit attachments.
2. Download the files (really download it, not just look at the url, but use Ctrl + S / the download button)
image
3. Make sure the file name simply is the name specified when creating the attachment.
4. Please tick the test checkboxes

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
- [x] Test - Firefox
- [x] Test - Chrome
- [ ] Test - Safari

### Screenshots

With the fix:
image
image
image

## Summary by CodeRabbit

- **New Features**
	- Improved file handling with flexible filename options and enhanced caching behavior for file responses.
	- Streamlined response creation process for file handling.

- **Bug Fixes**
	- Adjusted caching settings for specific file response methods to ensure correct behavior.

- **Refactor**
	- Simplified method signatures for better clarity and maintainability in the `FileResource` class.

### CODE REVIEW

**Review by sachmii — APPROVED** [review]
Tested on TS3, worked fine for regular attachments and attachment units. 

Bildschirmfoto 2024-11-13 um 23 45 35

**Review by HawKhiem — APPROVED** [review]
Tested on TS3. The names of attachments and lecture units were displayed correctly

Screenshot 2024-11-13 234655
Screenshot 2024-11-13 234756

**Review by BBesrour — APPROVED** [review]
code lgtm

**Review by ahbitaqu — APPROVED** [review]
[Tested on TS1]
Works as described, couldn't find any issues.
(Might be unrelated but when deploying this PR to TS2, I was unable to login and got an internal server error)

**Review by vinceclifford — APPROVED** [review]
Tested on TS5, works as expected

**Review by HanyangXu0508 — APPROVED** [review]
Tested locally and worked as expected.

**Review by sawys777 — APPROVED** [review]
Tested on TS1, everything works as described

**Review by krusche — APPROVED** [review]

**Pull request merged**
