### PR TITLE
`Development`: Improve filename validation

### PR DESCRIPTION
**Pull request by maximiliansoelch**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).

### Motivation and Context

When downloading a submission file of a file-upload-exercise that has upper case letters in its file extension, it is not downloaded directly, but instead shown in a new browser window.

### Description

In order to download the submission file directly as it is intended, the filename needs to be converted to lowercase before checking the file extension and setting the content type to `attachment`.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 File Upload Exercise with SVG as allowed filetype

1. Log in as instructor
2. Create a new File Upload Exercise with SVG as allowed filetype
3. As a student submit a SVG file with upper case letters in the file extension, e.g. `logo.Svg`
4. After submitting, click on the download submission link
5. The just uploaded file should be downloaded directly and should not be shown in the browser first

Here is an example file that you can use for testing:

logo

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### CODE REVIEW

**Review by jschmautzer — APPROVED** [review]
tested on ts2, works as described

**Review by pantageepapa — APPROVED** [review]
Tested on ts1, works as described!

**Review by alaraozdenler — APPROVED** [review]
tested on ts1, works as described

**Review by Marvin-Vitcu — APPROVED** [review]
Tested on ts1: works as intended.
The changes look fine to me.

**Review by manuelmanso — APPROVED** [review]
Code changes look good and the download works as expected. It also opens a new empty browser window, I'm not sure if that's intended/necessary.

**Review by Hialus — APPROVED** [review]
Code changes look good.

**Pull request merged**
