### PR TITLE
`Development`: Differentiate between buttons and links

### LINKED ISSUE #7564: `General`: Differentiate between buttons and links
### Is your feature request related to a problem?

`<button>` and `<a>` are often mixed when it comes to links and actions within Artemis.
This leads for example to the Problem, that some logical links (button HTML buttons) don't offer the "open in new tab" feature.
E.g. 

- Lecture Attachment Unit Download, Edit, Competencies Links
- Tutorial Groups List -> Link to specific Tutorial group

### Describe the solution you'd like

Logical links (navigate to a different path) should always use `<a>` tags with proper `href` attribute set. (but still using angular routing)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added screenshots of the UI 

### Motivation and Context
closes #7564 

### Description
simplify tutorial groups using relative links and adding some logic to differentiate when lecture units updated within guided mode (we need buttons then) an when in an extra page (-> links).

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Lecture
- 1 Tutorial Group

1. Log in to Artemis as Instructor
2. Navigate to Lecture Management.
3. Verify that it is possible to edit/create lecture units both in guided mode for lecture editing & in lecture-unit page
4. Verify that the buttons for creating/editing on the lecture-unit page are html-a tags (you should see a path preview in your browser when hovering on them -> at least in chrome)
5. Navigate to tutorial Group Management Verify that you can navigate through the tutorial groups and all links on the Detail Page work (Course Link, tutorial Group Link, should also be HTML a tags now)
6. Log in as student
7. Navigate through Tutorial Groups
8. Verify that all links work (Course Link, tutorial group link should be HTML a tags now)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [tutorial-group-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5729/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/tutorial-groups/shared/tutorial-group-detail/tutorial-group-detail.component.ts.html) | 95.65% | ✅  |
| [tutorial-group-row.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5729/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/tutorial-groups/shared/tutorial-groups-table/tutorial-group-row/tutorial-group-row.component.ts.html) | 100% | ✅ |
| [tutorial-groups-table.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5729/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/tutorial-groups/shared/tutorial-groups-table/tutorial-groups-table.component.ts.html) | 90.24% | ✅  |
| [tutorial-group-management-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5729/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/tutorial-groups/tutorial-groups-management/tutorial-groups/detail/tutorial-group-management-detail.component.ts.html) | 96.77% | ✅  |
| [tutorial-groups-management.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5729/latest/artifact/shared/Coverage-Report-Client-Tests/app/course/tutorial-groups/tutorial-groups-management/tutorial-groups/tutorial-groups-management/tutorial-groups-management.component.ts.html) | 91.83% | ✅  |
| [lecture-unit-management.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5729/latest/artifact/shared/Coverage-Report-Client-Tests/app/lecture/lecture-unit/lecture-unit-management/lecture-unit-management.component.ts.html) | 89.24% | ✅  |
| [unit-creation-card.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5729/latest/artifact/shared/Coverage-Report-Client-Tests/app/lecture/lecture-unit/lecture-unit-management/unit-creation-card/unit-creation-card.component.ts.html) | 100% | ✅ |
| [course-tutorial-group-card.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5729/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-tutorial-groups/course-tutorial-group-card/course-tutorial-group-card.component.ts.html) | 100% | ✅ |
| [course-tutorial-groups-overview.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5729/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-tutorial-groups/course-tutorial-groups-overview/course-tutorial-groups-overview.component.ts.html) | 100% | ✅ |
| [course-tutorial-group-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5729/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/tutorial-group-details/course-tutorial-group-detail/course-tutorial-group-detail.component.ts.html) | 95.65% | ✅  |

### Screenshots
image
image

### CODE REVIEW

**Review by reschandreas — APPROVED** [review]
tested locally, works as expected...code also lgtm 👍🏻

**Review by JohannesStoehr — DISMISSED** [review]
Code looks good to me

**Review by AntonGeTUM — DISMISSED** [review]
Manually tested, works as expected

**Review by xHadie — APPROVED** [review]
_Manually tested on TS3_Legacy_
Works as you described, except one thing I was not sure about:
image

The group is not a link in the details page. Should that not be a link?

**Review by Gusti2010 — DISMISSED** [review]
Manually tested on TS11_Legacy, works as expected!

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts2. Worked as expected.

**Review by reschandreas — APPROVED** [review]
reapprove

**Review by JanaNF — APPROVED** [review]
Re-tested on legacy_ts11. Everything still works

**Review by AntonGeTUM — APPROVED** [review]
Reapprove after manual test on TS11

**Review by LenaKahle — APPROVED** [review]
Approve, manually tested on legacy ts2

**Review by georgyia — APPROVED** [review]
manually tested, works as expected!

**Pull request merged**
