### PR TITLE
`General`: Fix LTI 1.3 launch redirect bug

### PR DESCRIPTION
**Pull request by manuelmanso**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context
The LTI1.3 launch has a bug where the user is not redirected to the exercise page because the URL to redirect the user to contains queryParams and therefore no routes are found matching the URL. The user stays stuck in the "Launching..." page. This was broken by https://github.com/ls1intum/Artemis/pull/5948

### Description
NavigateByUrl does not work with absolute URLs including queryParams, window.location.replace has to be used instead.

### Steps for Testing
Prerequisites:
- 1 Instructor in Artemis
- 1 Instructor in an external LMS (https://moodle.ase.in.tum.de/my/courses.php)

1. Setup an online course in Artemis as the instructor
2. Create an exercise for the course
3. Setup an LTI exercise in the external LMS
4. Verify that launching the exercise works, and you get redirected to the exercise page (if a new user, otherwise you get redirected to the login page)

Example:

https://user-images.githubusercontent.com/11006274/215709626-160adae1-dd53-4d56-983f-2500be9832e5.mp4

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Branch | Line |
|------------|-------:|-----:|
| lti13-exercise-launch.component.ts | 85% | 100% |

### Screenshots
Before:
image

### CODE REVIEW

**Review by simon-hng — APPROVED** [review]
code

**Review by simon-hng — APPROVED** [review]
Tested on TS1

**Review by pellumbbaboci — APPROVED** [review]
Tested on ts, works as expected. Code looks good.

**Review by danielbode — APPROVED** [review]
Tested on ts1. Works as expected.

**Review by Vinicius-Agreste — APPROVED** [review]
Tested on ts1.

**Pull request merged**
