### PR TITLE
`Communication`: Add profile picture to sidebar element and conversation header

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [X] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

- In the current sidebar design, group and direct messages share the same icon as channels, causing confusion. Direct messages display the channel icon instead of profile pictures, making it harder for users to distinguish between channels, group chats, and direct messages. 
- The conversation header does not display the profile picture of the person being chatted with, unlike in Slack.

### Description

- Added a group icon for group chats in the sidebar
- Displayed the relevant profile picture for direct chats in the sidebar, differentiating them from channels and group chats
- Updated the conversation header to show the relevant profile picture for direct chats

### Steps for Testing

Prerequisites:
- 1 Instructor/Student
- 1 Course with Communication enabled

1. Log in to Artemis
2. Navigate to Communication section of a course
3. Create a direct chat and a group chat, notice their updated icons on the sidebar
4. Open a direct chat, notice the updated conversation header with a profile picture.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| one-to-one-chat.model.ts | 90.9% | ✅ ❌ |
| conversation-detail-dialog.component.ts | 97.05% | ✅ ❌ |
| conversation-header.component.ts | 95.58% | ✅ ❌ |
| group-chat-icon.component.ts | not found (deleted) | ❌ |
| sidebar-card-item.component.ts | 100% | ✅ |
| sidebar.component.ts | 91.66% | ✅ ❌ |

### Screenshots

**updated conversation header**
image

**updated sidebar elements**
image

## Release Notes

- **New Features**
  - Introduced enhanced handling for one-to-one chat conversations, improving user experience in identifying participants.
  - Updated visual representation of group chats with a new icon.
  - Added profile picture display for one-to-one conversations in the sidebar.

- **Bug Fixes**
  - Removed deprecated group chat icon component, streamlining the conversation interface.

- **Documentation**
  - Updated test suites to reflect the removal of the group chat icon and ensure coverage of new functionalities.

- **Chores**
  - Simplified component dependencies and improved test configurations for better maintainability.

### CODE REVIEW

**Review by FelberMartin — APPROVED** [review]
Tested on TS1 and works as expected. Nice change!

**Review by julian-wls — COMMENTED** [review]
Just tested it on TS1. Works as expected.
Maybe one small remark:

I noticed, that the space between the image and the title is quite small:
Screenshot3

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Works as described

Screenshot 2024-11-09 162343
Screenshot 2024-11-09 162350

**Review by sachmii — APPROVED** [review]
Tested on TS1, works as described.

**Review by PaRangger — APPROVED** [review]
Code LGTM. Tested on TS1, looks great 👍

**Review by ahbitaqu — APPROVED** [review]
[Tested on TS2]
Works as described! Couldn't find any issues
image
image

**Pull request merged**
