### PR TITLE
[Bugfix] Fix the error handling for assessments of prog. ex. before a due date

### PR DESCRIPTION
**Pull request by derLalla**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

An incomprehensible error is thrown when a tutor opens the exercise assessment page of a programming exercise whose 'build after due date' is not reached.

### Description

The server was throwing a forbidden() when `checkIfExerciseDueDateIsReached` returned false. Now a `AccessForbiddenException` is thrown with a more explaining info message.

### Steps for Testing

1. Log in to Artemis
2. Create a programming exercise with a `build after due date`
3. Log in as a student and participate
4. Log in as a tutor and go to the Assessment Dashboard of the course
5. Click on Exercise Dashboard of the programming exercise
6. Verify that the error message on top is displayed correctly

### Test Coverage

Stays the same as no new functionality is added.

### Screenshots

Course Assessment Dashboard:
image

Exercise Assessment Dashboard:
image

### CODE REVIEW

**Review by ivanchimeno — APPROVED** [review]
Nice changes. The code looks good from my point of view (didn't test it yet though)

**Review by FlorianStang — APPROVED** [review]
Tested on TS1 with @JannisBittlmayer, everthing worked as described.

**Review by JannisBittlmayer — APPROVED** [review]
Tested with @FlorianStang on TS1, works as intended.

**Review by airelawaleria — APPROVED** [review]

**Review by marvinchimeka — APPROVED** [review]

**Review by simonzilker — APPROVED** [review]

**Review by LudwigWeide — APPROVED** [review]

**Review by EneaGore — APPROVED** [review]

**Review by DenizShabani — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]
Code looks good to me.

**Pull request merged**
