### PR TITLE
`Messages`: Fix creation and display of direct messages

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [X] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [X] I documented the Java code using JavaDoc style.

### Motivation and Context

In a testing session we found out that currently
- if you already had an open DM, you can't create another one, but receive a 500
- the name of your DM partner does not get displayed, neither in the sidebar nor in the headline after opening

### Description

This issue was introduced because of a misunderstanding of how the JPA queries work. I reverted the changes and documented the queries to prevent future confusion. Additionally, I improved the method names of the query methods.

### Steps for Testing

Prerequisites:
- 1 Instructor
- Multiple Students registered
- Course with Messages enabled

1. Try to create multiple DMs with different students
2. Try to create a DM with a student that already has a DM with another person
3. Make sure the creation works, the student's name gets displayed in the sidebar and when opening the DMs on top.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **Refactor**
	- Enhanced participant data retrieval in one-to-one chat features for improved efficiency in filtering based on user and course IDs.

### CODE REVIEW

**Review by pzdr7 — APPROVED** [review]
Tested on TS2. Looks good to me 👍

**Review by rstief — APPROVED** [review]
Tested on ts2, works as expected. Code also looks good to me 👀

**Review by coolchock — APPROVED** [review]
code lgtm

**Review by milljoniaer — APPROVED** [review]
Code looks good 👍

**Pull request merged**
