### PR TITLE
`Quiz exercises`: Fix an issue where the icons for the questions overlap the page

### LINKED ISSUE #9023: `Preview quiz`: The icons for the questions overlap the page when I scroll down
### Describe the bug

The icons for the questions overlap the page when I scroll down 

### To Reproduce

1. Go to any quiz with several questions 
2. Press preview quiz
3. Verify that the icons for the questions overlap the page when it scroll down 

### Expected behavior

Should not overlap the page 

### Screenshots

https://github.com/ls1intum/Artemis/assets/88991954/1b76a550-0cdc-4f9d-94cb-84d08c179fc0

### Which version of Artemis are you seeing the problem on?

7.4.1

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

It fixes #9023 as well as the unfitted content of quiz footer in live participation mode. (See screenshots)

### Description

I added a custom sticky top css class to be able to modify top property, so we can specify the threshold, where it is treated as fixed positioned after certain point. This will be the case only for preview mode. 

### Steps for Testing

Prerequisites:
- 1 Instructor 
- 1 Student
- 1 Quiz exercise with multiple mc questions (at least 5 questions)

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to Exercises
4. Click on "Preview Quiz" 
5. Scroll down 
6. Verify that the icons for mc questions on the left do not overlap the page header anymore
7. Go back and start the quiz 
8. Log in with a student account
9. Navigate to course 
10. Go to exercises and participate the quiz
11. Verify that the content of footer is not exceeding anymore

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

Before
Screenshot 2024-07-13 at 01 15 09

Screenshot 2024-07-13 at 18 54 18

After 
Screenshot 2024-07-13 at 01 15 27

Screenshot 2024-07-13 at 18 54 30

## Summary by CodeRabbit

- **Style**
  - Updated the CSS class name for quiz navigation to `quiz-navigation stepwizardquiz sticky-top-quiz` for better styling and layout.

- **New Features**
  - Added conditional blocks in the remaining-time section for different modes: 'live', 'practice', and 'preview'. 

- **Bug Fixes**
  - Introduced a new CSS class `.sticky-top-quiz` to ensure sticky behavior for the quiz component, enhancing user experience during quiz navigation.

### CODE REVIEW

**Review by EneaGore — APPROVED** [review]
Tested on TS6. Icons dont overlap with header anymore when scrolling down.

**Review by pzdr7 — DISMISSED** [review]
Tested on TS3. Works as expected 👍

**Review by marlon-luca-bu — DISMISSED** [review]
Tested on TS3, works as described 👍

**Review by PaRangger — DISMISSED** [review]
Hi!

Tested on TS3. Code LGTM. 

Small sidenote: For me it still overlaps with the footer (the timer has z-index: 30). However, I dont think this will become an issue, since no user will have such a tiny window.

Bildschirmfoto 2024-07-13 um 10 30 30

**Review by egekurt123 — DISMISSED** [review]
Tested on TS3, works as expected

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
The icons now stop randomly in the middle of the page in the normal participation view:
Bildschirmfoto 2024-07-13 um 11 01 09

So the preview now longer has the overflow at the top, but we traded it for a weird user interface that all students will see. Can you investigate further why we now have more than 85px between the icons and the top of the page in the participation view?

**Comment by edkaya** [comment]
> Hi!
> 
> Tested on TS3. Code LGTM.
> 
> Small sidenote: For me it still overlaps with the footer (the timer has z-index: 30). However, I dont think this will become an issue, since no user will have such a tiny window.
> 
> Bildschirmfoto 2024-07-13 um 10 30 30

Thanks for detecting, great catch 👍 I can adjust z index according to that

**Review by JohannesStoehr — APPROVED** [review]
Bugfix looks good to me

**Review by marlon-luca-bu — APPROVED** [review]
Adaptions LGTM

**Review by PaRangger — APPROVED** [review]
New Changes LGTM

**Pull request merged**
