### PR TITLE
`Development`: Fix plagiarism update validation

### PR DESCRIPTION
**Pull request by milljoniaer**
#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Validation of Plagiarism update produced a type error and therefore did not work. This PR fixes this issue.

### Steps for Testing

Prerequisites:
- 1 Instructor 

1. Log in to Artemis
2. Edit Programming Exercise
3. Fill out everything
4. Check that all sections are valid and there are no type errors in the console

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image

### CODE REVIEW

**Review by rstief — APPROVED** [review]
Tested in testing session, works as expected.

**Review by laurenzfb — APPROVED** [review]
code good, demonstrated

**Review by JohannesWt — APPROVED** [review]
Tested in testing session on-site -> Works as intended

**Comment by krusche** [comment]
thanks for the quick fix

**Pull request merged**
