### PR TITLE
`Assessment`: Improve tutor training validation logic to not allow negative score without feedback

### PR DESCRIPTION
**Pull request by Olimbia23**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] *This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] *I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] *I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] *I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] *I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

[ ] * - not needed 

### Motivation and Context

We improve our tutor training logic to not allow tutors to create a feedback with a negative score but no content (text).

### Description

Introduced a new `FeedbackCorrectionErrorType`, which is thrown when tutors feedback has negative score but no detail text. As well as added the required translations.

### Steps for Testing

Prerequisites:
- 1 Tutor

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to Exercise Assessment Dashboard of an Exercise that has Example Submissions
4. Assess Text Example Submission
  4.1. Put a Negative Score with Empty Feedback on a Text Block
  4.2. Submit the Assessment
  4.3. You should See the "Feedback is required for negative score" error message (see screenshot below)
5. Assess Modeling Example Submission 
  5.1. Put a Negative Score with Empty Feedback on an UML element
  5.2. Submit the Assessment
  5.3. You should See the "Feedback is required for negative score" error message

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Text
Screen Shot 2021-11-23 at 20 36 15

#### Modeling
Screen Shot 2021-11-23 at 20 37 19

### CODE REVIEW

**Review by filip-gregurevic — APPROVED** [review]
Looks good to me 👍🏼

**Review by lschlesinger — CHANGES_REQUESTED** [review]
I tested on TS2 for text and modeling exercises.
When I start with neg. points and no feedback in a modeling exercise submit and afterwards add feedback and submit, the error message is still shown (see picture) - so it's not updated correctly. For text exercise it is:
Bildschirmfoto 2021-11-23 um 22 34 17

**Comment by Olimbia23** [comment]
> I tested on TS2 for text and modeling exercises. When I start with neg. points and no feedback in a modeling exercise submit and afterwards add feedback and submit, the error message is still shown (see picture) - so it's not updated correctly. For text exercise it is.

Thank you for spotting this bug @lschlesinger. I fixed it 😇

**Review by argertboja — COMMENTED** [review]
Great job @Olimbia23 🙂 

I tested on TS1, however unfortunately I didn't get the error message. I assigned negative points to one block and positive points to another and the assessment was submitted successfully. You can also check the image below:
image
Please let me know once you handle this case as well and I will be happy to test your PR again 🙂

**Comment by Olimbia23** [comment]
Hey @argertboja, you are not testing the example submissions, but real student submissions. Could you please look at it again? 🙈

**Review by filip-gregurevic — APPROVED** [review]

**Comment by argertboja** [comment]
> Hey @argertboja, you are not testing the example submissions, but real student submissions. Could you please look at it again? 🙈

Yep, my bad 😃 Tested again on TS1 and everything is working as expected! Great job @Olimbia23 🙂

**Review by argertboja — APPROVED** [review]

**Review by MerlinMehmed — APPROVED** [review]
Works as described, code changes also look good!

**Review by jhainzlschmid — APPROVED** [review]
Code looks good

**Review by DanielKainz — APPROVED** [review]
I tested it on TS2. Everything worked as expected. Great work :-)

**Pull request merged**
