### PR TITLE
`Development`: Fix usage of SERVER_API_URL

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

While experimenting locally with the `SERVER_API_URL` environment variable I noticed that some endpoints did no longer load. 

### Description

This was due to the fact that the `SERVER_API_URL` is supposed to end with a `/`, but some services expected it not to. To fix this I removed the unnecessary leading `/` in these services and additionally added a comment to the declaration of `SERVER_API_URL`, so this is clear in the future.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate around Artemis and check if everything works as expected
    - Emojis load without issue
    - Submission Policy
    - Build log

If you actually want to test setting the `SERVER_API_URL` you can do the following (locally only):
1. Set `SERVER_API_URL` in `webpack/environment.js` to `https://artemis.ase.in.tum.de`
2. Start the client
3. Open the angular application in your browser
    - Note: You might need to disable CORS in your browser (I did not get this to work in Firefox)
5. You can now navigate around Artemis production with your local client

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Since you're already changing the URLs, I'd also unify their notation to either always use string concatenation or format strings

**Comment by Hialus** [comment]
> Since you're already changing the URLs, I'd also unify their notation to either always use string concatenation or format strings

There are 192 usages of `SERVER_API_URL` in the client code. Going through all of them to unify the notation would be out of scope for this PR, especially since both notations are correct.
And this would only unify the notation for a small part of the Strings used in the client code, so it wouldn't even fix the underlying issue. We would have to adapt the client coding guidelines and create a couple of big PRs that then unify the notations all over the client code (this might even be automated).

**Review by JohannesStoehr — APPROVED** [review]
Code changes look good. We should think about a unified client style for writing urls or strings in general

**Review by Marvin-Vitcu — APPROVED** [review]
Tested with Instructor and student on ts1: submission policy and build log works as intended, emojis load

**Comment by krusche** [comment]
There should be more people testing the changes on a test server

**Review by max-bergmann — APPROVED** [review]
Tested only on TS1. Everything works as expected

**Review by MetinLamby — APPROVED** [review]
Tested on ts2. everything worked as expected

**Review by luisa-we — APPROVED** [review]
Tested on TS1, everything worked as expected

**Pull request merged**
