### PR TITLE
`Development`: Change client and server URLs replacing learning goal with competency

### PR DESCRIPTION
**Pull request by terlan98**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

This PR is a part of follow-up PRs on #6388. There's currently an inconsistency between the usage of 'learning goal' and 'competency' throughout the system. This PR **only addresses the client and server URLs**, replacing all occurrences of the term 'learning-goal' with 'competency'.

### Description

Replaced all occurrences of the term 'learning-goal' with 'competency' on client and server URLs.

#### ℹ️  Please check URLs only. Comments, file names, etc. will be fixed in separate PRs.
Prerequisites:
- 1 Student
- 1 Admin or Instructor
- 1 Course

1. Log in to Artemis **as Admin** (or Instructor)
2. Go to the **Course Management page of the Course**
3. Click **Competencies**
4. **Check** that the client and server URLs are correct (do not contain 'learning goal')
5. Perform **Create, Import, Edit, and Delete** operations, checking the client and server URLs
6. Before moving on, make sure there's at least 1 competency in the Course (for the next steps)
7. Log in to Artemis **as Student**
2. Navigate to **Course Overview** 
3. Click on the Course
4. Navigate to **Competencies**
5. **Check** that the client and server URLs are correct (do not contain 'learning goal')
6. Click on a **specific competency**
5. **Check** that the client and server URLs are correct (do not contain 'learning goal')
 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by terlan98** [comment]
@TimOrtel @sven0311, just wanted to inform you that this PR might break something for you if you have any competency(learning goal)-related functionality in Artemis iOS and Android.

**Review by laadvo — APPROVED** [review]
Tested on ts1, the URLs all now contain competency

**Review by tobias-lippert — APPROVED** [review]
Tested in testing session on ts1. couldn't find any places that were missed and nothing was broken
Code renamings also look good

**Review by maximiliansoelch — APPROVED** [review]
Tested on TS1, competencies still work as expected.
Code changes (i.e. replacements) LGTM 👍

**Pull request merged**
