### PR TITLE
`Development`: Remove cypress

### PR DESCRIPTION
**Pull request by krusche**
#### General
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Cypress E2E testing framework is no longer used in Artemis and was replaced by Playwright

### Description
This PR removes Cypress framework and everything related to it. Following steps were taken:
- Migrate/rename Cypress docker environment files into Playwright
- Move certs from Cypress to Playwright
- Remove Cypress tests
- Remove Cypress setup

### Steps for Testing
- **Code Review**: Ensure that changes either remove everything about Cypress or migrate it to Playwright without breaking other parts of code.

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

## Summary by CodeRabbit

- **New Features**
	- Transitioned end-to-end testing framework from Cypress to Playwright, enhancing testing capabilities.
	- Updated documentation to reflect the new Playwright framework and its usage for generating client certificates.

- **Bug Fixes**
	- Streamlined logic for JWT cookie security, removing unnecessary complexity related to Cypress.

- **Chores**
	- Removed Cypress-related configurations and artifacts from various files to focus on Playwright.
	- Updated Git ignore rules to reflect the removal of Cypress testing artifacts.

### CODE REVIEW

**Review by Hialus — COMMENTED** [review]
The changed files look good to me. Though I searched through the repo locally and Cypress is still part of the docs. This should probably also be removed.

**Comment by krusche** [comment]
> The changed files look good to me. Though I searched through the repo locally and Cypress is still part of the docs. This should probably also be removed.

Let's do this in a follow-up

**Comment by krusche** [comment]
Cypress tests are not executed any more due to issues. The relevant checks pass, so I'd like to move forward and merge this PR. Additional improvements can be made in follow-ups

**Review by Hialus — APPROVED** [review]
Okay. Then the changes in this PR look good to me

**Pull request merged**
