### PR TITLE
[Bugfix] Restore Back button in text-/modelling example submission components

### PR DESCRIPTION
**Pull request by Olimbia23**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test 

### Motivation and Context

The motivation is to restore the Back button in the text-/modelling submission component.

### Description

The back button was removed unintentionally because of the dependencies PR. 
This PR introduces it again.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Pick a course
4. Go to Exercises
5. Click on Example Submissions for a certain text or modelling exercise.
6. Create new Example Submission. 
7. You should be able to see the back button.

### Screenshots
Text Exercise
Before:
Screenshot 2021-07-05 at 3 34 36 PM

After:
after_text

- - - - - - -- - - - 
Modelling Exercise:
Before:
before_modeling

After:
Screenshot 2021-07-05 at 7 20 34 PM

### CODE REVIEW

**Review by PatZintel — DISMISSED** [review]
tested on ts1, back arrow is present, saving text example submissions will be fixed in https://github.com/ls1intum/Artemis/pull/3632#

**Review by MDK5 — CHANGES_REQUESTED** [review]
Tested on ts1 and reviewed code, the buttons are there and working, but I dont understand why the modelling exercise uses a totally different button - I would prefer if all back buttons would look the same.

**Review by joschahenningsen — DISMISSED** [review]
Works :+1: 
Agree that we could use the same approach for all back buttons though.

**Review by ndricimrr — COMMENTED** [review]
Changes look good 👍 .

As in previous comments, maybe it would make sense to keep it similiar. 
I think you can reuse the left arrow from the Statistics page here [(reference)](https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/shared/statistics-graph/statistics-graph.component.html#L5):
image
Seems to fit in well : 
image

**Comment by Olimbia23** [comment]
I made back buttons look the same @MDK5. Now both of them look like in example-text-submission.component

**Review by lschlesinger — COMMENTED** [review]
I think it would be user-friendly to indicate that the arrow is clickable by simply adding the class `clickable` to the `<fa-icon>` tag. With this change, the curser changes when hovering over the arrow, and indicates that the arrow is clickable :) Functionality-wise, I approve.
This is how it would look like with the class added:
Bildschirmfoto 2021-07-05 um 19 55 51

**Review by argertboja — COMMENTED** [review]
No error encountered while testing on TS1. Code changes look good aswell 👍🏼

**Comment by Olimbia23** [comment]
> I think it would be user-friendly to indicate that the arrow is clickable by simply adding the class `clickable` to the `<fa-icon>` tag. With this change, the curser changes when hovering over the arrow, and indicates that the arrow is clickable :) Functionality-wise, I approve.

Thank you for the suggestion @lschlesinger. Done 😄

**Review by ndricimrr — APPROVED** [review]
Tested on TS1 and looks good 👍

**Review by ivanchimeno — APPROVED** [review]
lgtm :+1:

**Review by joschahenningsen — APPROVED** [review]

**Review by lschlesinger — APPROVED** [review]
👍

**Comment by krusche** [comment]
Why do we need back buttons? We have breadcrumbs now and want to get rid of all back buttons. 

The back button is provided by the browser. There is no need to implement it in the Artemis user interface as well!

**Review by ArtemTsurikov — APPROVED** [review]
Tested on TS1, looks good

**Comment by Olimbia23** [comment]
Closing this PR, as a general design decision is to stay away from custom back buttons.

**Pull request closed without merging**
