### PR TITLE
Bugfix: Reference error, ace is not defined

### LINKED ISSUE #2385: Edge case: Students can't participate in exams
### Describe the bug
Students are not able to start exams during working time

#### To Reproduce

1. create an exam, add exercise groups and exercises, register students
2. generate individual exams 
3. change exam "start working time" to present time
4. login as student
5. try to participate in the exam

#### Expected behavior
Student should be able to participate in the exam and complet the exercises during the working time

### Environment

<details><pre>
 - OS: Windows 10
 - Browser Chrome, Firefox, Firefox Nightly
 - Version 86.0.4240.193, 82.0.3, 84.0a1
</pre></details> 

#### Output in Web Console

<details><pre>
  instrument.js:109 ERROR Error: Uncaught (in promise): ReferenceError: ace is not defined
ReferenceError: ace is not defined
    at Object.1028 (language_tools.js:1)
    at r (bootstrap:63)
    at Object.946 (code-editor-ace.component.ts:1)
    at r (bootstrap:63)
    at Object.915 (code-editor-container.component.ts:1)
    at r (bootstrap:63)
    at Object.1253 (programming-exam-submission.component.ts:1)
    at r (bootstrap:63)
    at Object.1248 (exam-participation.component.ts:1)
    at r (bootstrap:63)
    at Module.1703 (8.c6f61002c2a4fe664b33.chunk.js:2)
    at r (bootstrap:63)
    at t.invoke (zone.js:395)
    at Object.onInvoke (core.js:27504)
    at t.invoke (zone.js:394)
    at n.run (zone.js:155)
    at zone.js:1313
    at t.invokeTask (zone.js:429)
    at Object.onInvokeTask (core.js:27492)
    at t.invokeTask (zone.js:428)
    at n.runTask (zone.js:200)
    at _ (zone.js:615)
    at j (zone.js:1250)
    at j (zone.js:1204)
    at zone.js:1316
    at t.invokeTask (zone.js:429)
    at Object.onInvokeTask (core.js:27492)
    at t.invokeTask (zone.js:428)
    at n.runTask (zone.js:200)
    at _ (zone.js:615)
(anonymous) @ instrument.js:109
instrument.js:109 ERROR Error: Uncaught (in promise): ReferenceError: Cannot access 'D' before initialization
ReferenceError: Cannot access 'D' before initialization
    at Module.ArtemisExamParticipationModule (8.c6f61002c2a4fe664b33.chunk.js:2)
    at app-routing.module.ts:58
    at t.invoke (zone.js:395)
    at Object.onInvoke (core.js:27504)
    at t.invoke (zone.js:394)
    at n.run (zone.js:155)
    at zone.js:1313
    at t.invokeTask (zone.js:429)
    at Object.onInvokeTask (core.js:27492)
    at t.invokeTask (zone.js:428)
    at n.runTask (zone.js:200)
    at _ (zone.js:615)
    at n.invokeTask [as invoke] (zone.js:515)
    at _ (zone.js:1651)
    at HTMLDivElement.C (zone.js:1677)
    at j (zone.js:1250)
    at j (zone.js:1204)
    at zone.js:1316
    at t.invokeTask (zone.js:429)
    at Object.onInvokeTask (core.js:27492)
    at t.invokeTask (zone.js:428)
    at n.runTask (zone.js:200)
    at _ (zone.js:615)
    at n.invokeTask [as invoke] (zone.js:515)
    at _ (zone.js:1651)
    at HTMLDivElement.C (zone.js:1677)
</pre></details>

### PR DESCRIPTION
**Pull request by anditurdiu**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context
Fixes #2385

### Description
**Bugfix 1:**
There seemed to be an error when trying to access exam as a student. It is related to the dependencies loaded within the exam mode which includes the code-editor dependencies. These are also loaded if there is no programming exercise in the student exam. @schultek suggested that this is because the `code-editor-ace.component` first loads the `brace dependencies` before loading `ace`. The brace dependencies however try to reference `ace` which leads to: `ReferenceError: ace is not defined`. It is interesting that this behavior is not very consistent. Sometimes this error does not show up. 
However: Exam `examPR2415` in https://vmbruegge60.in.tum.de/#/courses/708/exams throws this error consistently.
**Bugfix 2:** 
We had an unhandled case in the client, when the student tries to access the summary but has not submitted on time. It would briefly show the exam end page which states `you have not submitted on time` and then show a blank page because it threw an unhandled error. 

### Steps for Testing
1. Navigate to https://vmbruegge60.in.tum.de/#/courses/708/exams
2. Try to access exam `examPR2415`.
3. Check the console, you should not see this error: 
    `ReferenceError: ace is not defined
    at Object.946 (code-editor-ace.component.ts:1)`
Note: As you are not registered to the exam you cannot participate in it. It should show: "You are not registered to the exam. Contact your instructor" and throw a 404 error.
-------------------------------------
1. Create an exam and set it in the future. 
2. Register student and generate student exams & prepare exercises
3. Change the start date to now.
4. Wait until time runs out and you can't submit anymore.
5. Navigate away from the exam & navigate back to the exam
6. You should still see the note that your exam will not be graded.
`OR`
1. Log in with test user 4 on https://vmbruegge60.in.tum.de
2. navigate to /#/courses/1939/exams/434
3. You should still see the note that your exam will not be graded because you did not submit on time

### CODE REVIEW

**Review by kloessst — APPROVED** [review]
Tested this with an exam where the error occurred previously. Got an 404 but no error. Seems to work.

**Comment by anditurdiu** [comment]
@tiffca @stefanwaldhauser @philgabr @JannisBittlmayer @FlorianStang Could you please recheck those exams which threw the error for you and check if you can access the exam now? (403 forbidden and 404 errors are expected since the exam is probably over by now/ you are not registered)

**Review by JannisBittlmayer — COMMENTED** [review]
Tested again on TS3 without any reference error but instead got a 403 code, which is unexpected behavior. When trying to access the exam as the student, for a quick moment Artemis shows some kind of "end of exam" screen, then a nearly blank screen (as seen in the attached video)

**Comment by anditurdiu** [comment]
> Tested again on TS3 without any reference error but instead got a 403 code, which is unexpected behavior. When trying to access the exam as the student, for a quick moment Artemis shows some kind of "end of exam" screen, then a nearly blank screen (as seen in the attached video)
> 
> 

I believe this is because in the summary call, we explicitly check for:
```
if (!studentExam.isSubmitted()) {
            return forbidden();
}
```
It will try changing it with : 
```
if (!studentExam.isSubmitted() && studentExam.getIndividualEndDateWithGracePeriod().isBefore(studentExam.getExam().getEndDate())) {
            return forbidden();
        }
```

**Review by kloessst — APPROVED** [review]
Tested the other bug as well and it worked as expected.

image

**Review by krusche — APPROVED** [review]

**Review by FlorianStang — APPROVED** [review]
Tested (TS3) the past exams which created problems for me and newly created exams, after changing the start time. Everything worked as inteneded I had no further issue.

**Pull request merged**
