### PR TITLE
Additional server service refactoring

### PR DESCRIPTION
**Pull request by krusche**
This is a continuation of #2869 

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Description
* I eliminated all circular dependencies and removed most @Autowired annotations which we should not use any.
* I was able to delete many unused or unnecessary lines of code
* I introduced some new services (e.g. UserCreationService)
* I could reduce the lines of code in `ParticipationService` and `UserService`

### Steps for Testing
**Please test all areas of Artemis.** I carefully implemented the refactoring so that it does not break anything The automatic server tests pass, but you never know if something might broke due to the involved changes.

Areas of particular interest: 
* Everything regarding user management (login, create, update, delete user, also with respect to external systems)
* Everything regarding groups (change groups as server admin, register for course, register for exam, etc.)
* Starting and participating in all kinds of exercises

### Test Coverage
no changes

### Screenshots
no changes

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested in the testing session with @simonzilker @marvinchimeka @JohannesWeiss 
Everything worked fine

**Review by marvinchimeka — DISMISSED** [review]
Tested in testing session. Works as intended.

**Review by simonzilker — APPROVED** [review]
Looks good :)

**Review by EneaGore — APPROVED** [review]

**Review by JohannesWeiss — DISMISSED** [review]

**Review by LudwigWeide — DISMISSED** [review]

**Review by tiffca — DISMISSED** [review]
Tested successfully

**Review by valeriebucher — APPROVED** [review]
Didn't find an issue!

**Comment by krusche** [comment]
Thanks for testing. I fixed the merge conflicts after merging some other PRs. Would be awesome if you could quickly check it again and approve it in case everything is working

**Review by philgabr — COMMENTED** [review]
I tested all areas of particular interest, in general everything worked as intended :+1:

I don't know if that's related to this PR or was just a current problem with TS1, but when trying to participate in a programming exercise, I got an internal server error:
image
image

**Review by EneaGore — COMMENTED** [review]
Areas of interest seem to work fine still. I can not reproduce the mentioned issue for programming exercises but i do get "The result for your last submission is not available. Please submit your code again." every time i submit.

**Review by EneaGore — DISMISSED** [review]
I could not find any issues after more carefull testing :)

**Review by philgabr — APPROVED** [review]
As I could not reproduce the error with programming exercises mentioned yesterday, approve 👍🏻 

image

**Comment by krusche** [comment]
I just fixed another small null pointer exception found on production. Would be awesome if you can re-approve. Thanks!

**Review by valeriebucher — APPROVED** [review]
Re-approve!

**Pull request merged**
