### PR TITLE
`General`: Fix small user interface issues

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Users reported a bunch of smaller user interface issues.

### Description

In this PR, I fixed the issues #5536, #5529 and #5496.

### Steps for Testing

Prerequisites:
- 1 Programming Exercise with Manual Assessment
- 1 Instructor
- 1 Student with Submission to the Programming Exercise

1. Log in to Artemis as Instructor
2. Navigate to Course Administration
3. Ensure #5529 is fixed
4. Assess the programming exercise manually
5. Ensure #5536 is fixed
6. Login to Artemis as Student
7. Take a look the inline feedback of the programming exercise assessment
8. Open the Notification Sidebar
9. Ensure #5496 is fixed
10. Make sure all changes also work in dark mode and with smaller screen sizes (responsive)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

_unchanged_

### Screenshots

Screenshot 2022-08-06 at 16 58 13

Screenshot 2022-08-06 at 16 59 38

Screenshot 2022-08-06 at 17 00 22

### CODE REVIEW

**Review by nadinesamyy — APPROVED** [review]
looks good

**Review by Dominik-Weinzierl — APPROVED** [review]
Code looks good! Thanks for fixing those issues

**Review by yuling-sun — APPROVED** [review]
Tested on TS1. Works as described.

**Review by SimonPaul02 — APPROVED** [review]
Tested on TS1, works as expected

**Review by jschmautzer — APPROVED** [review]
tested on ts2, worked as described

**Review by bassner — APPROVED** [review]
Tested on TS5, works good. Code LGTM 👍

**Pull request merged**
