### PR TITLE
`Communication`: Enable reactions if only messaging is enabled

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

### Motivation and Context

Reactions only work if communication is enabled

### Description

Reactions now also work, if only messaging is enabled.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Instructor
- 1 Course with only messaging enabled

1. Check that you can react to messages and replies as both users and they get updated for the other user
2. Enable communication, disable messaging
3. Check that you can react to posts and replies as both users and reactions get updated for the other user

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

No UI changes

### CODE REVIEW

**Review by rstief — DISMISSED** [review]
Tested on ts3, works well.

**Review by MaximilianAnzinger — APPROVED** [review]
Code lgtm

**Review by Kroko-fant — DISMISSED** [review]
tested on ts looks good to me.
Code looks good to me

**Review by Strohgelaender — APPROVED** [review]
code

**Review by Strohgelaender — APPROVED** [review]
code + new tests lgtm

**Comment by lennart-keller** [comment]
Is fixed with #7437

**Pull request closed without merging**
