### PR TITLE
[Bug] SCA categorization when build fails

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

PMD and Checkstyle are in some cases able to deliver feedback even if compilation fails (e.g. on a type error). In such a case the feedback was not properly categorized.

### Description

- Move categorization functionality to `StaticCodeAnalysisService`
- Call categorization functionality even if no test case feedback exists
- Fixed typos in some category mappings
- Move Spotbugs `I18N` ruleset (usage of locale and encodings) to category best practices
- Fix the result String generation for Jenkins. Use the test case feedback to determine the String not all feedback.
- Tests

### Steps for Testing

**Test the Bamboo and Jenkins setup**

1. Log in to Artemis
2. Create a programming exercise with static code analysis enabled
3. Participate in the exercise
4. Submit and check that feedback is properly categorized (in the default configuration, documentation issues should not show up)
5. Let the build fail by submitting the following implementation for a sort algorithm and check that the static code analysis feedback is properly categorized.
```
Collections.sort(input);
int a = "";
```

### Test Coverage

Coverage is at the same level as a method was just moved to another service and called at a slightly different spot. Added two more specialized tests which don't improve coverage.

### CODE REVIEW

**Review by tiffca — CHANGES_REQUESTED** [review]
Build doesn't show as fail when there's the static code analysis code added. 

Reproduce steps: 
1. Create a java programming exercise with static code analysis enabled. 
2. Add the example static code analysis code
3. Add some other code that should pass some test cases
4. Submit 
5. Notice the build is not showing as failed, however the static code analysis warning is showing. Expected: the build should indicate it failed 

image

**Comment by kloessst** [comment]
@tiffca I could not reproduce this behavior on TS1. Did you test on TS2? There might be a slight difference how the initial `Result` is created in the `JenkinsService` which leads to this behavior.

**Comment by kloessst** [comment]
Fixed the build error result String for Jenkins with e9bcd1bb91979ded95a27e7b111789f5a83871f2

**Review by sleiss — APPROVED** [review]
Tested it on both TS1 and TS2, works as expected.

**Review by fde312 — APPROVED** [review]
Tested on ts1 & ts2. Works fine. Good job! 👍

**Pull request merged**
