### PR TITLE
`Exam mode`: Add exam update audit event

### PR DESCRIPTION
**Pull request by coolchock**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Description

This pull request introduces an audit event for tracking updates made to exams.

### Steps for Testing

Prerequisites:
- 1 Admin (ts3)
- 1 Exam

1. Log in to Artemis
2. Navigate to Course Management -> Select a course -> Exams -> Select an Exam 
3. Edit an exam (for example change title or working time)
4. Navigate to Server Administrations -> Audits
5. Verify that `UPDATE_EXAM` audit event appears in the table

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Introduced a new constant for exam operations: `UPDATE_EXAM`.
	- Added audit logging for exam updates to enhance tracking of changes.
	- Improved validation for importing exams and updating exercise groups to prevent conflicts.

- **Bug Fixes**
	- Enhanced validation for suspicious exam sessions to ensure proper parameters are provided.

These updates improve the management and integrity of exam-related functionalities within the application.

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]
code

**Review by BBesrour — APPROVED** [review]
Tested on TS3, editing an exam is shown in the audit view. Would be great to display some additional information in the future like exam ID.
Also code lgtm

**Review by EneaGore — APPROVED** [review]
Tested on TS3. Works as expected.

**Comment by Malekos74** [comment]
Is there a way to access "Server Administrations -> Audits" with a test account?

**Review by raffifasaro — APPROVED** [review]
code

**Pull request merged**
