### PR TITLE
[Bugfix] - Re-evaluate cannot handle more than 9 spots

### PR DESCRIPTION
**Pull request by FuchsDominik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context

For short answer questions which have more than 9 spots, the regex parses the text incorrectly, which results in an NullPointerExeption. 

### Description

Adapted the regex(es) a bit so that numbers with two digits are also recognized (I assume nobody will create a quiz with >= 100 spots, if this is the case, another digit would need to be noticed by the regex)

### Steps for Testing

1. Log in to Artemis
2. Create a short answer quiz with more than 9 spots (also map solutions to them)
3. make sure when editing it after creating the exercise, everything is displayed correctly (+ no errors in the console)
4. run the test, after it click on re-evaluate
5. Every spot should be displayed and functionalities like adding solutions or deleting spots should be possible as well
6. When dragging a solution to a spot to make a mapping (to tell the quiz that this solution is a correct answer for this spot) the spot should get green when hovering over one

### CODE REVIEW

**Review by tiffca — APPROVED** [review]
The view looks a little weird then we click on re-evaluate (all of the boxes), but otherwise the functionality works as expected 

image

**Review by JohannesWeiss — APPROVED** [review]
Works as intended on ts1, no issues were present.

**Review by airelawaleria — APPROVED** [review]

**Review by valeriebucher — APPROVED** [review]

**Review by philgabr — APPROVED** [review]
Looks good :+1:

**Review by simonzilker — APPROVED** [review]
works as described

**Review by FrankeLukas — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
