### PR TITLE
Fix the layout of the video unit creation form

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
Before
grafik
After
grafik

### Description

`form-row` was removed in Bootstrap 5. We can use just `d-flex` as replacement in our specific case. I also increased the bottom-margin of the conversion arrow by one because it looked better to me.

### Steps for Testing

1. Find or create a lecture
2. Create a video unit for it
3. Check if the creation page looks good (~like in the latter screenshot above)

### CODE REVIEW

**Review by lschlesinger — DISMISSED** [review]
Tested on TS1. 
I would assume that the arrow is always vertically aligned with the input fields.
As soon as there is the line break in the description below the transformation input, the arrow is not aligned properly anymore.
My first approach would be to put the input fields and the arrow in one row, all with col-auto, and the description in a row below and edd justify-content-end.
 I think the description should be in a seprate row?
Bildschirmfoto 2021-07-15 um 18 55 49

**Comment by FrankeLukas** [comment]
I'm not sure if we can ever get this aligned for smaller screensizes. As soon as the label above the input has a line break things go awry again:
grafik

**Comment by krusche** [comment]
can you also sanitize the ULR (on the server side) to prevent security issues?

**Review by ArtemTsurikov — DISMISSED** [review]
Looks good on ts3, the button with the arrow has just moved a bit down 
Screenshot 2021-07-16 at 16 39 00

**Review by katjanakosic — APPROVED** [review]
Works as expected on ts2 👍

**Review by argertboja — COMMENTED** [review]
Technically works fine on TS1 however I would suggest that even for smaller screen sizes, the button and the input fields should be vertically aligned! See image below:
image

**Comment by FrankeLukas** [comment]
Updated. The layout should now also work on smaller screen widths.

> can you also sanitize the ULR (on the server side) to prevent security issues?

I didn't find a good way to do this (without duplication an entire js library on the server), so instead the client now validates the URL before displaying anything. If someone posts a malicious URL to the server it will still be fetched but not displayed.

**Review by canyelten — CHANGES_REQUESTED** [review]
Tested on TS1, works as expected. I however encountered a visual problem after adding the videos where the up and down arrows aren't fully visible on smaller screens.
image

**Review by canyelten — APPROVED** [review]
Works fine now:)

**Review by rs-maker — APPROVED** [review]
Looks great on ts3.

**Review by imstreetspirit — APPROVED** [review]
looks good to me on ts2

**Pull request merged**
