### PR TITLE
Athene: REST Templates and Health Indicator

### PR DESCRIPTION
**Pull request by jpbernius**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [X] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [X] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [X] ~Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)~
- [X] Server: I implemented the changes with a good performance and prevented too many database calls
- [X] Server: I documented the Java code using JavaDoc style.
- [X] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [X] ~Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)~
- [X] ~Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)~
- [X] ~Client: I documented the TypeScript code using JSDoc style.~
- [X] Client: I added multiple screenshots/screencasts of my UI changes
- [X] Client: I translated all the newly inserted strings into German and English

### Description
- Use `ClientHttpRequestInterceptor` to authenticate all calls to Athene. Replace custom implementation to set the needed HTTP Authorization header.
- Add `HealthIndicator` to monitor the availability of Athene service.

(Needs config update from Ansible PR `#13`.)

### Steps for Testing

1. 
    1. Log in to Artemis with Admin user
    2. Open the `Health Checks` page (Server Administration -> Health)
    3. Find Athene in the list of services.

2. 
    1. Login into Artemis (Instructor/admin)
    2. Create Text Exercise with Automatic Assessment
    3. (With different student accounts): Create > 10 submissions: for 5 each: identical content in an English sentence. (e.g. copy a sentence from Wikipedia.)
    4. [Exercise due date] + wait a few minutes
    5. Start assessment, find feedback suggestions (as usual).
    6. Add CONFLICTING assessments (different comment + score for identical sentences)
    7. Navigate out of assessment and back into the assessment
    8. Find conflict marked on feedback.
    9. Click the `Conflict` badge and view conflict.

### Test Coverage
`AtheneHealthIndicator`: 100%
`AtheneAuthorizationInterceptor`: 100%

### Screenshots
image

### `application-prod.yml` Update
Configured on:

- [ ] Production
- [ ] Staging
- [X] Test Server 1
- [ ] Test Server 2
- [ ] Test Server 3
- [ ] Test Server 5

### CODE REVIEW

**Review by FuchsDominik — COMMENTED** [review]
Screenshot 2021-03-16 at 18 24 41
Tested, mentioned Testing steps worked as described. When having multiple conflicts its a bit weird to resolve, seems you always have to resolve the first conflicts, otherwise the second conflicts will run into the first conflicts again? And only the left side is overwritable, what if the right side is the false one? Also, only one feedback is overwritable at once, so you have to re-navigate into the view for every feedback

**Review by ivohashamov — COMMENTED** [review]
I second Dominik's comment. Besides that, it works as intended!

**Review by FrankeLukas — APPROVED** [review]
Everything still works as expected aside the things noted above.

**Comment by krusche** [comment]
I guess the mentioned issue is unrelated to this PR

**Review by krusche — APPROVED** [review]
Code changes look good

**Pull request merged**
