### PR TITLE
[Feature] Jenkins user management & access control

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

Access control for build plans in Jenkins is not implemented at the moment. Instructors and teaching assistants do not have access to build plans of programming exercises. In this PR, we implement that.  

This PR enables the following:

1. Creating an Artemis user will automatically create a Jenkins account with the same user login and password. This enables access to Jenkins.
2. Updating an Artemis user will also update the Jenkins account. 
3. Deleting an Artemis user will also delete the Jenkins account and the associated permissions of the build plans.
3. It is possible to assign and remove groups to that user. This will automatically enable/disable access to the appropriate build plans for the user.
4. Editing the groups of a course will also update the permissions to the build plans of that course for all users. 

**Caveats:** 
- It's not possible to update a user because there is no API for it. So we "update" by re-creating the user with the new data.
- In Jenkins, users are created in on-demand basis; for example, when a build is performed, its change log is computed and as a result commits from users who Jenkins has never seen may be discovered and created. This can lead to issues when updating the login of an Artemis user and trying to revert back to its previous login.

### Description

This PR introduces the following classes:
- `JenkinsUserManagementService` class that manages Jenkins users. It implements an abstract `CIUserManagementService` interface that can be used to integrate other CI systems
- `JenkinsJobPermissionsService` class that manages permissions and access control for build plans

This PR also refactors the `JenkinsService` class by extract common functionality into separate classes:
- `JenkinsBuildPlanService` which contains common functionality regarding build plans
- `JenkinsJobService` which contains common functionality regarding jobs 

#### Create, Delete, and Update an Artemis user ####
1. Log in to Artemis
2. Navigate to User Management and create a user
3. You should be able to login into Jenkins with the same login and password
4. Now edit the user in Artemis and change the password, and name 
5. You should be able to re-login with the new password and see the changed name on the top right of the screen.
6. Now delete the user in Artemis. 
7. You should not be able to log into Jenkins anymore.

Note that re-creating the same user can cause issues because Jenkins might create one with the same id (login). This means that if you create a user, delete it, and recreate it, it might raise an error. The same thing goes for updating the user login.

#### Add and Remove groups for a user #### 
1. Create a Course with a Programming Exercise. Make sure to name the instructor and/or teaching assistant groups
2. Create a new Artemis user and add the instructor or teaching assistant group into the groups field
3. Save the user. If you login into Jenkins you should be able to see the build plan of the programming exercise
4. You can edit the Artemis user and remove the group and save it. Go back to Jenkins and the build plan should not be visible anymore.
5. You can also update the login and make sure you can log into Jenkins with the new login

#### Add and Remove a user to a group ####
1. Create a new Artemis user
2. Navigate to Course Management and click on the group of a course (instructor or teaching assistant)
3. In the text input, add the user into the group
4. Log into Jenkins with that user, you should be able to see the build plans of the exercises of that course
5. Remove the user from the group and make should the build plans are not visible anymore.

### Test Coverage

JenkinsJobPermissionsUtils 84%
JenkinsJobService 65%
ProgrammingExerciseService 94%
UserCreationService 93%
JenkinsBuildPlanService.java 71%
JenkinsService.java 61%
JenkinsUserManagementService.java 83%
JenkinsJobPermissionsService.java 97%
CourseResource.java 90%
UserService.java 86%
GitLabService.java 74%
GitLabUserManagementService.java 72%

### Screenshots

After creating a new Artemis user you can log into Jenkins:
image

Teaching assistants can access build plans and trigger them:
image

Instructors can access more actions such as configure the build plans:
image

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
tested in the testing @marvinchimeka @JohannesWeiss 
Works fine

**Review by marvinchimeka — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts2 in testing session, worked as expected for us.

**Review by philgabr — DISMISSED** [review]

**Review by SimonEntholzer — APPROVED** [review]
Testing on TS2 worked perfectly :D The code looks really nice as well.

There is one thing I stumbled upon accidentally: I created a user which had already been created and then deleted. For some reason when I re-create such a user (same login) the groups of the previously deleted user are kept and shown again. (No idea if this is intended and/or wanted or not)

**Review by nicolasruscher — APPROVED** [review]
Tested it in testing session 👍

**Review by iozbeyli — APPROVED** [review]
Coming from test session, works nicely.

**Pull request merged**
