### PR TITLE
`Communication`: Rearrange the plus icon in sort-by menu

### LINKED ISSUE #6198: `Communications`: Sort-By Icons
### Describe the bug

When opening the menu for sort-by in communications, only one of the three entries has an icon and the other two do not, which looks strange.

### To Reproduce

1. Go to communications of a course
2. Click on sort-by

### Expected behavior

Either no option should have an icon or all three of them should have one so it's aligned design-wise.

### Screenshots

inkonsistenz_sort_by_popup

### Which version of Artemis are you seeing the problem on?

6.0.2

### What browsers are you seeing the problem on?

Safari

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by terlan98**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Closes #6198 

### Description
Modified the i18n files for English and German, moving the ➕ emoji to the end of the string.

### Steps for Testing
Prerequisites:
- 1 Course

1. Go to communications of a course
2. Click on sort-by

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots
Screenshot 2023-03-17 at 10 00 05

### CODE REVIEW

**Review by danielbode — APPROVED** [review]
Tested on ts1. Looks like expected. The code also looks fine.

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Review by JohannesStoehr — APPROVED** [review]
Thanks for addressing my comment

**Review by laadvo — APPROVED** [review]
Tested on ts1, the sort-by menu now looks as expected.

**Pull request merged**
