### PR TITLE
[TypoFix] Url typo in Github PR template client documentation

### PR DESCRIPTION
**Pull request by Olimbia23**
### Checklist
- [X] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-testing/).
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all newly inserted strings into English and German.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

There was a typo in the url. It is fixed with this PR. This is why there is no need to check any checkboxes apart from the first one.

### Steps for Testing

Check the changed url and be sure that it redirects to the Artemis client test documentation.

### Review Progress

- Code Review
  - [x] Review 1
  - [x] Review 2
- Manual Tests
  - [x] Test 1
  - [x] Test 2

### Screenshots

Screenshot 2021-09-15 at 12 41 19 AM

### CODE REVIEW

**Review by ndricimrr — APPROVED** [review]
Looks good 👍

**Review by lschlesinger — APPROVED** [review]
Yep, should be changed to the correct link 👍

**Review by MDK5 — APPROVED** [review]
The url works now

**Review by coolchock — APPROVED** [review]
looks good 👍

**Pull request merged**
