### PR TITLE
[Enhancement] Making exam navigation bar buttons consistent 

### PR DESCRIPTION
**Pull request by FlorianGlombik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

The right and left navigation buttons of the exam navigation bar were not always displayed. If the leftmost exercise (or first exercise) is displayed, the navigate to the left button disappears. However, the navigate to the right button does not disappear when the rightmost (or last element) is displayed.
No matter which one is the preferred way, the behavior should be consistent.
NavigationBarButtonsInconsistent

### Description

I think that the UI is more intuitive if the buttons are always displayed. The exercises are enumerated, so it should be clear that going further to the left does not change the displayed exercise if the leftmost exercise is chosen. I am aware that this is a matter of taste, so feel free to criticize this decision!

### Steps for Testing

1. Create an exam exercise with multiple exercises (the exercise type shouldn't matter)
2. Check that the navigation bar and its buttons are displayed properly
3. Check that their functionality is given

### Screenshots

Consistent behavior with always displayed buttons, which are now disabled when leftmost / rightmost element or the overview is selected.
buttonsNowConsistentAndDisabled

### CODE REVIEW

**Review by lschlesinger — CHANGES_REQUESTED** [review]
I agree, that it should be consistent and I think always showing the navigation errors but disabling it when start or end is reached is a good solution.
What I would find better instead of overwriting the click for start and end to "doing nothing", disabling the button. This has the advantage of indicating the user, that the button cannot be clicked in these situations instead of letting the button clickable and do nothing when being clicked. The two respective buttons would then have the `[disabled]` class:
```html
<div class="navigation-item">
    <button class="btn btn-secondary w-100" (click)="changePage(false, exerciseIndex - 1, false)" [disabled]="exerciseIndex===0">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
    </button>
</div>
...
<div class="navigation-item">
    <button class="btn btn-secondary w-100" (click)="changePage(false, overviewPageOpen ? 0 : exerciseIndex + 1, false)" [disabled]="exerciseIndex===exercises.length -1">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
    </button>
</div>
````
In the `click()` function, the corresponding part could be deleted:
```typescript
  // out of index -> do nothing
  if (exerciseIndex > this.exercises.length - 1 || exerciseIndex < 0) {
      return;
  }
````
Result would look like:
First exercise -> button previous disabled, i.e. not clickable
Bildschirmfoto 2021-07-14 um 10 32 03

Last exercise -> button next disabled, i.e. not clickable
Bildschirmfoto 2021-07-14 um 10 32 11

**Comment by FlorianGlombik** [comment]
Thank you for your review @lschlesinger for your review and your suggestions! 
_I actually thought about displaying the buttons in a light grey when they are not supplying any functionality, but since I was not aware of the `disabled` attribute it seemed to introduce more code than needed for this change to me. Thanks for the heads up here, I should have explicitly searched for this attribute._ 

I changed it according to your description https://github.com/ls1intum/Artemis/pull/3758/commits/b1d0237f0b276f65e47315e0e9899361fdff1536, with the small difference of using `<=` and `>=` comparison, I would argue that it makes sense to deactivate bought buttons on the overview.

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Worked for me.

**Review by niclasschuemann — APPROVED** [review]
Tested on TS1, works as expected, code looks good to me 👍

**Review by lschlesinger — APPROVED** [review]
Approve after changes 👍

**Review by ivanchimeno — APPROVED** [review]

**Pull request merged**
