### PR TITLE
Removed Error when value is undefined

### LINKED ISSUE #2318: No participations shown for programming exercise errors in console
### Describe the bug
No participations shown for programming exercise

#### To Reproduce

Open participations 

#### Screenshots
Screenshot from 2020-11-03 10-06-49

### Environment

<details><pre>
 - OS: Linux
 - Browser Chrome und Firefox
 - Version neuste
</pre></details>

#### Additional context
We can grant access to our Artemis if needed.

#### Output in Web Console
[alpro.besec.uni-bonn.de-1604394712135.log](https://github.com/ls1intum/Artemis/files/5480261/alpro.besec.uni-bonn.de-1604394712135.log)

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

Closes #2318 . There was an error when certain dates where undefined in the exercise scores and in the participation table.

### Description

Added a ternary operator to handle the undefined case

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to Exercise Scores / Participations Page of an exercise and see that no error occurs when a date is set to null or undefined

### CODE REVIEW

**Review by MaisiKoleni — APPROVED** [review]
Code looks good to me (if those are the only two components where the date can be undefined)

**Review by kloessst — APPROVED** [review]
Code seems to be fine. Couldn't reproduce the error. At the same time we could not get the participation into an erroneous state. I think this is fine but please fix the Date Pipe in the future or avoid the code duplication by moving the format function to a common service.

**Review by fde312 — APPROVED** [review]
I was not able to test it the issue with `initializationDate = null` like mentioned in #2318. But for me it works and the code looks good as well. NPE should now be catched! Good job! 👍

**Comment by stefanwaldhauser** [comment]
image
Manually set it to null in the db and it works

**Review by krusche — APPROVED** [review]

**Review by axel1200 — APPROVED** [review]

**Pull request merged**
