### PR TITLE
`Adaptive learning`: Improve competency student view

### PR DESCRIPTION
**Pull request by MaximilianAnzinger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

The student view of competencies shows competencies that are not linked to any resources. Furthermore the order of the competencies might be confusing.

### Description

- Adjusted endpoint to support request param to filter out competencies without existing exercise or lecture unit links
- Client: Sort list of competency in student view by due date

### Steps for Testing

Prerequisites:
- 1 Students
- at least one exercise / lecture unit
- at least 4 competencies
1. Competency *without* due date but linked to exercise / lecture unit
2. Competency with due date and linked to exercise / lecture unit
3. Competency with due date and linked to exercise / lecture unit
4. Competency that is not linked to any exercise / lecture unit

1. Log in to Artemis
2. Navigate to Course Competencies
3. You should *not* see the Competency that isn't linked to any exercise / lecture unit
4. You should see all the other competencies ordered by the due date (earliest first, no due date last)

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
	- Introduced a method to filter course competencies based on their linkage to learning objects.
	- Added functionality to retrieve filtered course competencies in the user interface.
	- Implemented sorting of competencies by their due dates.
	- Enhanced the ability to retrieve competencies with additional filtering options.

- **Bug Fixes**
	- Enhanced filtering logic to ensure accurate retrieval of competencies.

- **Tests**
	- Expanded test coverage for filtered competency retrieval scenarios.

### CODE REVIEW

**Review by sachmii — APPROVED** [review]
Tested on TS6, everything works fine.

Bildschirmfoto 2024-11-30 um 12 19 15
Bildschirmfoto 2024-11-30 um 12 19 25

**Review by kevinfischer4 — APPROVED** [review]
Tested on TS4, works as expected.

**Review by JohannesWt — DISMISSED** [review]
Code 👍

**Review by HawKhiem — APPROVED** [review]
Tested on TS4. I created 4 competencies, compe1, compe2, compe3 and compe4. I linked 1 to 3 to an exercise or a lecture unit, 4 is left unlinked. Compe 1 and 2 has a due date, while 3 doesn't. Everything works as described

Screenshot 2024-11-30 205156
Screenshot 2024-11-30 205221

**Review by raffifasaro — DISMISSED** [review]
code

**Review by Haoyuli2002 — COMMENTED** [review]
Tested on TS 2 as Instructor 16. I created four different kinds of competencies and they appeared as described. Everything is working as expected and looks good to me.

**Review by zagemello — APPROVED** [review]
Tested on TS4, all works as expected

**Review by ahbitaqu — DISMISSED** [review]
[Tested on TS4]
Looks good here :)

**Review by krusche — APPROVED** [review]

**Pull request merged**
