### PR TITLE
`Exam mode`: Fix test exam result view after the working period is over

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Fixes student issue 13 from the exam mode testing. 

On test exams, students are no longer able to view their own submissions after the working period is over.

### Description
The endpoint used a method `isAllowedToGetExamResult` which does not consider test exams.

Additionally, I now remove the exam object from the response since it should not be passed to a student.

### Steps for Testing
Prerequisites:
- 1 Student
- 1 Exam, 1 Test exam

1. Participate in the test exam
2. Wait until the test exam working window is closed
3. View your submission and press on `View Result` on the summary page.
4. Verify that everything works as expected
5. Verify that the normal exam mode did not break. No results should be visible to students before the result are published.

#### Performance Review
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [AuthorizationCheckService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5186/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/AuthorizationCheckService.html) | 92% | ✅ |
| [ModelingSubmissionResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5186/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/ModelingSubmissionResource.html) | 96% | ✅ |
| [TextExerciseResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5186/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/TextExerciseResource.html) | 99% | ✅ |

### CODE REVIEW

**Review by laadvo — APPROVED** [review]
Tested on ts1, students are now able to view their results for all types of exercises in both a test and a normal exam after the working period is over

**Review by laadvo — APPROVED** [review]
re-tested on ts1, working as expected

**Review by MaximilianAnzinger — DISMISSED** [review]
Code LGTM 👍

**Review by tobias-lippert — DISMISSED** [review]
Code LGTM

**Review by JohannesStoehr — APPROVED** [review]
New code looks good to me

**Review by bassner — CHANGES_REQUESTED** [review]
Could you document the changes you made to sensitive information filtering in your PR description, please?
Also, please add a coverage table to your PR.
Thanks!

**Review by MaximilianAnzinger — APPROVED** [review]
Recent changes LGTM 👍

**Review by tobias-lippert — APPROVED** [review]
Latest code changes look good to me.

**Review by terlan98 — APPROVED** [review]
Tested on TS5. Works as expected 👍

**Review by rriyaldhi — COMMENTED** [review]
Tested on TS1. As a student participating in a [Test Exam](https://artemis-test1.artemis.in.tum.de/courses/215/exams/437), I could see the answers and the result directly after submitting. Also, I couldn't find the View Result button:
Screenshot 2023-07-22 at 17 52 00

**Comment by Strohgelaender** [comment]
@rriyaldhi Thanks for testing. The view result button is only available for text and modeling exercises, so it's correct that you don't see it for programming exercises and quizzes.

**Pull request merged**
