### PR TITLE
`Text exercises`: Fix a type error for empty text blocks

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation and Context
A student wrote [on Zulip](https://zulip.in.tum.de/#narrow/stream/934-EIST22-Organizational/topic/Artemis.20Error/near/590055) that he was unable to see his feedback. In the console a "cannot read properties from undefined" error was show.

### Description
After looking at the network log, for some reason the text-attribute was undefined:
grafik

In this case, we'll now use an empty string as the content of this block.

### Steps for Testing
Thanks to @bottbenj for the test instructions:

The submission needs to have (multiple?) empty lines at the end and then in assessment you need to select the very last line by clicking it twice with alt pressed. You can then attach a feedback to an empty text block which when sending to the server will still correctly have an empty string as its text property, but when the server sends it back to the student the text will be gone.

After that, go to the student's view and make sure that they can see the result.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by pantageepapa — APPROVED** [review]
Tested on ts1, empty text exercise submission is displayed correctly!

**Comment by Dominik-Weinzierl** [comment]
For those testing this PR, could you please also try creating the empty blocks (e.g. think out of the box and play around :D) - I think it would be good to know if we can reproduce the problem and solve it in a follow up as mentioned by @Strohgelaender  :+1:

**Comment by bottbenj** [comment]
I found how to reproduce it: The submission needs to have (multiple?) empty lines at the end and then in assessment you need to select the very last line by clicking it twice with alt pressed. You can then attach a feedback to an empty text block which when sending to the server will still correctly have an empty string as its text property, but when the server sends it back to the student the text will be gone.

**Comment by Strohgelaender** [comment]
Thank you @bottbenj, with this I also was able to reproduce the bug. Intrestingly enough, the client already sends an empty string to the server, but in the response that value is undefined.

Your method comes with another intresting special case: The index saved with this block is equal to the length of the text. This leads to the corresponding feedback not eeing showed to the student (the loop creating the blocks checks for `currentIndex < length`). I decided not to fix this, since emtpy blocks should not be created usually and the reported case by the student had the blocks in the middle of the submission. I tested this case by manually editing the data, here the feedback was shown.

I tried to fix the double-clicking bug, but could not get much progress here. So I'll move that into a follow-up PR and allow this PR to be merged as quickly as possible.

**Review by nadinesamyy — APPROVED** [review]
Was able to test the PR on ts2, student was able to see feedback. However I noticed that I was always only able to select a very small "space block" not the whole line or several empty lines at once. I am not sure if this is intended thus I approved the PR but wanted to point this out just in case.

**Review by max-bergmann — APPROVED** [review]
Tested on TS2. Feedback was visible for the student

**Review by rhubinger — APPROVED** [review]
Tested on TS2. Worked fine.

**Pull request merged**
