### PR TITLE
[Bugfix] update Gitlab members only if they exist

### LINKED ISSUE #2772: User can not start exercise if participation status is repo_copied
### Describe the bug
Users participation had status repo created without build plan but was unable to start the exercise.

#### To Reproduce

1. Unknown

#### Expected behavior

There is code to handle the case that the user is already member of the repo but the behaviour of gitlab must have changed over time/versions.

```
artemis                    | 2021-01-28 17:52:30.668 ERROR 1 --- [io-8080-exec-30] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
artemis                    | 
artemis                    | java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because the return value of "org.gitlab4j.api.GitLabApiException.getValidationErrors()" is null
artemis                    |    at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.addMemberToRepository(GitLabService.java:129)
artemis                    |    at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.configureRepository(GitLabService.java:113)
artemis                    |    at de.tum.in.www1.artemis.service.ParticipationService.configureRepository(ParticipationService.java:546)
artemis                    |    at de.tum.in.www1.artemis.service.ParticipationService.startProgrammingExercise(ParticipationService.java:255)
artemis                    |    at de.tum.in.www1.artemis.service.ParticipationService.startExercise(ParticipationService.java:219)
artemis                    |    at de.tum.in.www1.artemis.service.ParticipationService$$FastClassBySpringCGLIB$$f26b3f60.invoke(<generated>)
```

### Environment

gitlab

the code (GitLabService.java:129) expects a ValidationError in the Exeption when user already exist but Gitlab instead returns 409

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

This PR should fix #2772.

Gitlab returns an error status code when attempting to add a member to a repository that already exists. Therefore, exceptions occur when calling `addMemberToRepository` in `GitlabService` for existing members. This happens e.g when attempting to lock/unlock repositories for a programming exercise.

### Description

We add a new check in `addMemberToRepository`: We check if the member already exists in the repository. If it does, we simply update its permissions. If it doesn't, we add it to the repository.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration, create a programming exercise, and participate in it by creating a submissions
4. Navigate to Course Administration -> Edit Exercise
5. Press Lock All Repositories button
6. Navigate to the Gitlab repository and click on "Members"
7. Check that the student that submitted the code has "Guest" access level
8. Press Lock All Repositories again and double check that the access level stays as "Guest"
9. Press Unlock All Repositories
10. The member should now have access level "Developer"
11. Press Unlock All Repositories again and double check that the access level stays the same

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
all worked as described

**Review by EneaGore — APPROVED** [review]
Seems to work correctly to me.

**Review by JohannesWeiss — APPROVED** [review]
Works as intended, access was updated correctly in all cases

**Review by tiffca — APPROVED** [review]
Tested successfully on ts2, worked as described

**Review by simonzilker — APPROVED** [review]
Code looks good :)

**Review by LudwigWeide — APPROVED** [review]
Works as described.

**Review by philgabr — COMMENTED** [review]
For me the unlocking did not work as expected, still had guest access only on GitLab. I received this Artemis notification: 
image

**Comment by ivanchimeno** [comment]
> For me the unlocking did not work as expected, still had guest access only on GitLab. I received this Artemis notification:
> image

This error happens when the user doesn't exist in Gitlab and/or the repository doesn't exist. Did you make sure that both exist?

**Review by marvinchimeka — APPROVED** [review]
No issues found

**Review by philgabr — APPROVED** [review]
> This error happens when the user doesn't exist in Gitlab and/or the repository doesn't exist. Did you make sure that both exist?

Both existed, strange...

I just re-tested with the same [exercise](https://artemistest2.ase.in.tum.de/course-management/1787/programming-exercises/3434) and user (test_user_3) & with a new exercise.  Now everything worked as described, hence approve :+1:

**Review by derLalla — APPROVED** [review]
your code changes are easy to understand and straight forward. Approving 👍

**Review by krusche — APPROVED** [review]

**Pull request merged**
