### PR TITLE
`Programming exercises`: Fix repository reset for individual due dates

### LINKED ISSUE #7649: Cannot reset repository during individual deadline extensions
### Describe the bug

When we extend the deadline for an individual participant, they can't reset their repository in the time period between the previous (or general) deadline and the individual extended one. 

### To Reproduce

1. Create programming exercise that is due in 5 minutes
2. Participate in the exercise (`Start exercise` button)
3. Click on the exercise as the participant to view the exercise details (don't click on any of the buttons, click somewhere in the area that surrounds the buttons)
4. The red `Reset Repository` button should still be there.
5. Extend the deadline for this participant by going to `Course Management` -> `Exercises` of the respective course -> `Participations` of the respective exercise -> enter a new individual due date that is some time in the future
6. If the previous due date has passed and the individual due date has not yet passed, repeat step 3.
7. The button is gone even though this participant can otherwise still participate as usual.

### Expected behavior

In the extended timeframe, the participations should also be able to reset their repository.

### Which version of Artemis are you seeing the problem on?

6.7.0

### What browsers are you seeing the problem on?

Chrome, Safari

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Fix #7649

### Description

The reset button was not shown for students after the due date of an exercise, even though their individual due date was still in the future. This is now changed to no longer rely on the ability to start the exercise, which does not take individual due dates into account.

### Steps for Testing

Follow steps from #7649 (The reset button should be *below* the problem statement)
Additionally make sure that resetting actually works after the exercise due date but before the individual due date.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [reset-repo-button.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5776/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/components/reset-repo-button/reset-repo-button.component.ts.html) | 89.28% | ✅ |

### CODE REVIEW

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by MaximilianAnzinger — APPROVED** [review]
Code lgtm 👍

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts11. I saw the button, and I could reset the repository --> worked as expected.

**Comment by MaximilianJG** [comment]
Tested on Artemis test1: Everything working as expected now, I can see the reset Button and can also reset.

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts5. Worked as expected.

**Pull request merged**
