### PR TITLE
`General`: Allow administrators to edit the registration number in user management

### LINKED ISSUE #4647: Make Matriculation Number Editable for Admins
### Is your feature request related to a problem?

We are using SAML2 with the internal user management of Artemis. It would be useful to be able to modify all fields of a user if we only rely on the internal user management.

### Describe the solution you'd like

As admin I would like to be able to modify all fields of a user within the Artemis user edit view 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [X] I translated all newly inserted strings into English and German.

### Motivation and Context

Closes #4647 

### Description

I added the registration number as a column to the overview table and the field to the detail view. Additionally, I added the field to the update form and made sure it gets updated on the server.

I don't like the current implementation with the second parameter but I won't change it here. That change fits well with a fix for #4786 

### Steps for Testing

Prerequisites:
- Access to user management (Admin)

1. Log in to Artemis
2. Navigate to User Management
3. Create a new internal user with a registration number. Make sure that the number is saved and shown correctly.
4. Edit the registration numbers for users, check that they update and are visible throughout the user management.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by julian-christl** [comment]
> I tested on TS2, but it seems that there is an issue. I tried to create users several times. The first time, it was created, but the client didn't show a confirmation message and didn't redirect to another page. I can see the user in the users list. The second time I got an Internal server error, and again I can see the user in the users list :D

Sounds more like an issue of TS2 considering the scope of my changes.

**Review by ole-ve — APPROVED** [review]
Tested on TS3, everything worked as described and expected. I assume the issue encountered by @MerlinMehmed is not related to your changes but TS2.
The code changes also look good to me 👍

**Review by akesfeden — APPROVED** [review]
Tested on TS3, works as described. Code changes look good to me. 

I have a question: Do you think this case should be added to the comment over the field definition of `visibleRegistrationNumberTransient` in `User.java`?

**Review by MerlinMehmed — APPROVED** [review]
Retested on TS3, works fine. Code changes look good as well

**Pull request merged**
