### PR TITLE
[Exam] Add points overview to summary

### PR DESCRIPTION
**Pull request by sascha11110**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
We want to provide an overview of the achieved / achievable points in the exam summary.

### Description
I've implemented an overview table with the achieved / achievable points that is shown in the exam summary for the student and the instructor in the exam management. "-" is shown if no result for that exercise is available.

### Steps for Testing
The following should be checked for the exam summary for students (participation) and the exam summary in the student exams management for instructors.

1. Log in to Artemis
2. Participate in an exam with multiple exercises
3. Check that the table is not shown if the `publishResultsDate` is not set
4. Check that the table is not shown if the `publishResultsDate` is in the future
5. Check that the points in the table are calculated correctly (for each exercise and the sums)

**NOTE:** if you get a null pointer exception in `quiz-exam-summary.component` you could possibly ignore it as that will be fixed here: https://github.com/ls1intum/Artemis/pull/1914

### Screenshots
image

### CODE REVIEW

**Comment by sascha11110** [comment]
@sjagla27 Good catch! Can you re-review?

**Comment by krusche** [comment]
Please round to one digit after the comma if necessary 

1 point should be shown as 1
1,34 points should be shown as 1,3
0 points should be shown as 0
No / empty submission or no / empty result should also be shown as 0

The whole table should only be shown if there is a result publication date set that is in the past.
Otherwise (date is null/undefined or in the future) the table should **not** be shown

**Comment by sascha11110** [comment]
Sorry, I thought I solved the rounding problem. Seems to be more complicated than one would expect. I've now re-used the existing round function from `exam-scores.component`. @sjagla27 @amahmario @pzdr7 Can you test again?

@krusche @pzdr7 If no / empty result / submission is available 0 will be displayed now.

> The whole table should only be shown if there is a result publication date set that is in the past.
Otherwise (date is null/undefined or in the future) the table should not be shown

That is already covered in `exam-points-summary.component:25`:
`return !!(this.exam && this.exam.publishResultsDate && moment(this.exam.publishResultsDate).isBefore(this.serverDateService.now()) && this.hasAtLeastOneResult());`

**Comment by alexmardale** [comment]
> The whole table should only be shown if there is a result publication date set that is in the past.
> Otherwise (date is null/undefined or in the future) the table should **not** be shown

I can confirm this worked as expected.

The individual exercise scores were displayed as expected:
overview_table

But in some situations the sum was not rounded:
overview_not_correct
overview_not_correct_2

**Comment by sascha11110** [comment]
I don't know why rounding is necessary there. Anyway, I've applied the round function also to the sums.

@alexmardale Thanks for testing this thoroughly! Could you test once again? Ideally with the same exercise.

**Pull request merged**
