### PR TITLE
Fix combining template commits in Gitlab

### LINKED ISSUE #2434: Add timeout to jenkins pipline
### Is your feature request related to a problem?
Even tho AJTS offers measures that prevent endless loop it could still happen(maybe somebody forgets the annotations). When a test runs for like 30 minutes it should be killed by Jenkins. Here is how it could be done:
https://stackoverflow.com/questions/38096004/how-to-add-a-timeout-step-to-jenkins-pipeline#38106655

### PR DESCRIPTION
**Pull request by ivanchimeno**
Fixes #2434

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

The "Combine Template Commits" functionality in the programming exercises does not work if Gitlab is used instead of Bitbucket even if the client notifies the user that it succeeded. The reason is that Gitlab protects the master branch by default, leading to an error when force-pushing into that branch.

The solution to this problem is to unprotect the template repository master branch  when creating/importing a programming exercise.

### Description

1. I extended the `VersionControlService` by two methods:
  - `void protectBranch(URL repositoryUrl, String branch)` (not used for added for the sake of completion) 
  - `void unprotectBranch(URL repositoryUrl, String branch)`
2. I implemented these method in the `GitlabService`. The implementation in `BitBucketService` is empty because it's not in use.
3. I unprotected the master branch of the template repository when a programming exercise is created/imported.

### Steps for Testing

Please use test server 2 for testing.

1. Log in to Artemis and create a new programming exercise. Make sure you select the "Online Editor" feature.
2. Open up Gitlab and go to the exercise repository of the programming exercise.
3. Click on Repository -> Branches and make sure the master branch is not protected (only "default" is displayed).
4. Click on Repository -> Commits. There should be a single commit.
5. Go back to the Course Administration -> Course -> programming exercise and open the online editor (as intructor)
6. Make a change in the template repository and submit it.
7. Make another change in the template repository and submit it.
3. Go back to the repository in Gitlab and check that there three commits now.
4. Go back to the Course Administration -> Course -> programming exercise -> View -> Combine Template Commits
5. Go back to the repository in Gitlab and check that there's one commit now.

**Note:** Normally this shouldn't affect the way students modify code.

### Test Coverage
Didn't change

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested on ts2. Everything works

**Review by marvinchimeka — APPROVED** [review]
tested on ts1. worked as intended.

**Review by DenizShabani — DISMISSED** [review]
Everything looks good!

**Review by airelawaleria — COMMENTED** [review]
Re-tested on ts2. The master branch is protected. Combining the templates also didn't work

**Review by marvinchimeka — CHANGES_REQUESTED** [review]
re-Tested the functionality on ts2. It does not work like it supposed.
Bildschirmfoto 2020-12-07 um 18 58 22

**Review by JohannesWeiss — COMMENTED** [review]
Tested on ts2 with @airelawaleria and @marvinchimeka. Combining the commits did not work, there were still 3 commits in GitLab.

**Review by airelawaleria — CHANGES_REQUESTED** [review]
Same issue as @marvinchimeka has

**Review by JohannesWeiss — CHANGES_REQUESTED** [review]
Did not work on ts2, combining had no effects.

**Review by LudwigWeide — CHANGES_REQUESTED** [review]
Tested on TS3. Could not combine. Same problem as previous reviewers.

**Review by tiffca — CHANGES_REQUESTED** [review]
I also noticed the master branch is still protected. Tested on test server 2

**Comment by ivanchimeno** [comment]
Thank you all for finding out that the fix didn't work! I pushed some changes and the bug should really be fixed now :D

**Review by marvinchimeka — APPROVED** [review]
Re-tested it on ts2. Approve. There is one commit after combining the templates.

**Review by airelawaleria — APPROVED** [review]
Tested with @marvinchimeka. Combining the templates was successful

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts2 again and works as intended.

**Review by simonzilker — APPROVED** [review]
Works perfectly on ts2!

**Review by tiffca — APPROVED** [review]
Tested successfully on test server 2. nice changes!

**Review by krusche — APPROVED** [review]
Code looks good. Thanks for investigating and fixing the issues asynchronously.

@axel1200 this PR should also solve the protect issue #2434 when students start the programming exercise in a slightly nicer way than your implementation ;-) Would be great if you can try this out in your Artemis instance and let us know what you find out.

**Pull request merged**
