### PR TITLE
`Development`: Remove LtiUserId association to user

### PR DESCRIPTION
**Pull request by manuelmanso**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
The **ltiUserId** table associated the id of an Artemis user with the id of user in the external LMS (e.g Moodle). This was problematic because we could have users from different LMS's with the same user id in their original LMS, causing them to wrongly be mapped to the same user in Artemis. Additionally, this table wasn't really necessary since it was only used to check if a user was an LTI user on initialization, which we can instead just do by checking if the user belong to the "LTI" group, which is added to all users created during an LTI launch.

### Description
All logic associated to the ltiUserId table is removed. The table itself will be dropped in a follow-up PR. On initialization of a user, to check if a user is an LTI user, instead of using the ltiUserId table, now we check if a user belongs to the "LTI" group.

### Steps for Testing
Prerequisites:
- 1 Instructor in Artemis
- 1 Instructor in an external LMS (https://moodle.ase.in.tum.de/my/courses.php)

1. Setup an online course in Artemis as the instructor
2. Create an exercise for the course
3. Setup an LTI exercise in the external LMS
4. Verify that launching as a new user to Artemis works, you get a generated password, and you can then use that password to login
5. Verify that grading the new user returns a grade to the external LMS
6. Verify that launching as an existing LTI user still works, and that grading also works for these users

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Branch | Line |
|------------|-------:|-----:|
| UserResource.java | 72% | 84% |
| LtiService.java | 100% | 99% |
| Lti10Service.java | 84% | 95% |
| Lti13Service.java | 93% | 95% |

### CODE REVIEW

**Review by JohannesStoehr — DISMISSED** [review]
Removal looks good to me

**Review by danielbode — DISMISSED** [review]
Tested on ts1. Works as expected.

**Review by simon-hng — DISMISSED** [review]
Tested on TS1

**Review by Vinicius-Agreste — DISMISSED** [review]
Tested on ts1. Working as expected.

**Review by Vinicius-Agreste — APPROVED** [review]
Reapproved.

**Review by danielbode — APPROVED** [review]
Reapproved

**Review by JohannesStoehr — APPROVED** [review]
Rechecked latest commit that only reformats JavaDoc. Code looks good to me

**Review by simon-hng — APPROVED** [review]
Reapprove after javadoc issue

**Pull request merged**
