### PR TITLE
Show online status of team members in text and modeling editor

### PR DESCRIPTION
**Pull request by madwau**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
Team-based text and modeling exercises require the students to be aware of what their team members are doing since they are all working on the same artifact. This PR is a first step towards that: On the text editor page and on the modeling editor page, students can now see if they are connected to the server and who else of their team is currently looking at the artifact.

### Description
1. Added `ParticipationTeamWebsocketService.java` (handles subscribe and unsubscribe events for team participations; lets a user know on subscribe who else is currently subscribed to the topic, i.e. watching the same participation)
2. New component: Team Students Online List (vertical chat-like list of users with online indicator dot in front of the names; encapsulated websocket functionality and uses the service above to receive information about who if the team is currently looking at the same page)
3. New component: Team Participate Info Box (combines personal connection status, max score and team students online list into an information box; it is usually placed on the right side of the problem statement; it supports bounded or unbounded sticky positioning when scrolling so that it stays visible when possible)
4. Adapt text editor page and modling editor page to display the `Team Participate Info Box` when the exercise is team-based. If it is a normal, individual-based exercise, the appearance stays the same as it was until now (except for a small column optimization where the right max score only takes as much space as it actually needs).

### Steps for Testing
1. Log in to Artemis
2. Create a team-based text and a modeling exercise ([how?](https://github.com/ls1intum/Artemis/pull/1282#issuecomment-605954482))
3. Create at least one team with at least two students for each exercise
4. Start both exercises as anyone of the students from the teams
5. Log in with two students of the same team at the same time (use incognito mode or a different browser)
6. For both, go to the text or modeling editor page
7. Check that the team list is shown
8. Check that the online status behaves correctly

### Screenshots
**Note:** Updated screenshots in the comments.

1. Team Text Exercise: Right side has connection status and list of team members with their online status (team member list always shows yourself first and the rest alphabetically). A green dot means that the other person has the same page open.
OnPaste 20200406-185351

2. When scrolling, the information is presented in a sticky box with a light box-shadow. For text-exercises, it scrolls along until the very bottom of the page (so it might slightly overlap the textarea field for smaller browser widths).
OnPaste 20200406-185458

3. On mobile, this info is placed between the problem statement and the textarea.
OnPaste 20200406-185547

4. Team Modeling Exercise: Same familiar display as for text exercises.
OnPaste 20200406-185612

5. The sticky box on scrolling is bounded here, meaning it stops at a certain point (when the bounding container, i.e. the problem statement, ends). This is done so that the modeling editor is not overlapped since that could be really annoying for the user. Also since the height of the modeling editor is more or less fixed compared to the flexible textarea for text exercises, the team online info can be kept in the viewport if intended by the user.
OnPaste 20200406-185640

6. Same behavior as for text exercises on mobile.
OnPaste 20200406-185702

### CODE REVIEW

**Comment by madwau** [comment]
> I've checked the code, looks really good 
> 
> When testing it on the test server, I noticed 2 things:
> 
> 1. When I opened the modelling editor in a second browser with a different user, the new user was instantly shown to the old one, but the old one was not shown to the new one, only once I reloaded. However, I was not able to reproduce.
> 2. When scrolling, the Team Participation Info moves around a bit weirdly, I hope you can see it on the screencast (the space between "Some cool modelling exercise" and the Help-button varies):
>    Peek 2020-04-07 09-22
> 
> Edit: Just saw that not the latest version is deployed at the test server, will test again with the latest version

Thanks for reviewing and testing @sleiss!

1. I've experienced this as well. I think it happens when the websocket subscribe response arrives before the client is listening to the topic. I introduced a small timeout and that seemed to have fixed it locally (before it was happening around every 10th time, after the fix it didn't happen for 20 times in a row). On the test server it was still occuring rarely, so I bumped the timeout up some more to 300ms and then it seemed fine but maybe I need to experiment more if it happened to you.

2. This is actually intended. Once the team info starts to leave the viewport, it becomes a floating box that is no longer part of the regular document flow. In your example there is no real benefit since the problem statement is shorter than the team info section but I would assume in most real scenarios the problem statement will be quite a bit longer than the team info section and then the team info would scroll along nicely so that it doesn't disappear from the viewport.

**Comment by madwau** [comment]
> 1. I've experienced this as well. I think it happens when the websocket subscribe response arrives before the client is listening to the topic. I introduced a small timeout and that seemed to have fixed it locally (before it was happening around every 10th time, after the fix it didn't happen for 20 times in a row). On the test server it was still occuring rarely, so I bumped the timeout up some more to 300ms and then it seemed fine but maybe I need to experiment more if it happened to you.

I think I will solve this differently by letting the websocket client explicitly request the list of online members instead of implicitly receiving it on subscribe. That should get rid of this timing issue entirely. Will keep you updated here.

**Comment by madwau** [comment]
> > 1. I've experienced this as well. I think it happens when the websocket subscribe response arrives before the client is listening to the topic. I introduced a small timeout and that seemed to have fixed it locally (before it was happening around every 10th time, after the fix it didn't happen for 20 times in a row). On the test server it was still occuring rarely, so I bumped the timeout up some more to 300ms and then it seemed fine but maybe I need to experiment more if it happened to you.
> 
> I think I will solve this differently by letting the websocket client explicitly request the list of online members instead of implicitly receiving it on subscribe. That should get rid of this timing issue entirely. Will keep you updated here.

The online status should now always appear correctly, in some cases after a short timeout of some hundred milliseconds.

**Comment by krusche** [comment]
I would suggest that we do not add `Max. Score` into the `team-participate-info-box.component.html`. 

This exercise specific info should be in another extracted box with some additional information, e.g. due date, also see #1297. This could be part of a common header for modeling, file-upload and text exercises which should be smaller than the normal version.

Would also be great if you can add some test cases for the new functionality.

**Comment by madwau** [comment]
> I would suggest that we do not add `Max. Score` into the `team-participate-info-box.component.html`.

It does feel quite misplaced there, I agree. For now I just extracted it out again:

OnPaste 20200413-184330
OnPaste 20200413-184358

> This exercise specific info should be in another extracted box with some additional information, e.g. due date, also see #1297. This could be part of a common header for modeling, file-upload and text exercises which should be smaller than the normal version.

A common header for those three probably makes sense.

> Would also be great if you can add some test cases for the new functionality.

I will try to add some tests. I'll have to look into how to test websockets.

**Comment by madwau** [comment]
@krusche As discussed, I added server-side tests for the websocket functionality.

**Comment by madwau** [comment]
I made two changes:
1. Before, the team members were no longer shown once a submission had been made. This is rather impractical since you still want to see the online status of the team members after a first submission has been made but when the exercise is still active.
2. There were no permissions checks in place whether an authorized user is allowed to subscribe to the websocket topic of the team, so by taking the participation id of another team, it would have been possible to spy on the online status of students from other teams. I implemented a `TopicSubscriptionInterceptor` that ignores the user's subscription if he is not allowed to subscribe to that topic.

**Pull request merged**
