### PR TITLE
`Development`: Replace the old translation feature in the client with the new desired approach

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

**Case 1:**

As discussed in this issue (#8561) and this PR (#8132), all the strings with format

`<...>{{ "xxx" | artemisTranslate }}</...>`

should be changed to 

`<... jhiTranslate="xxx"></...>` 

**Case 2:**

As discussed in this PR reviews, translation parameters that use pipe should be updated.

Instead of this `{{ 'artemisApp.textExercise.wordCount' | artemisTranslate: { count: wordCount } }}` for example, this should be used: `jhiTranslate="artemisApp.textExercise.wordCount" [translateValues]="{ count: wordCount }"`

**Case 3:**

As discussed in this PR reviews, translation keys that depend on some variables should be updated.

Instead of this, `<span>{{ 'artemisApp.examManagement.checklist.' + (isTestExam ? 'testExam.' : '') + 'title' | artemisTranslate }}</span>` for example, this should be used:  `<span jhiTranslate="artemisApp.examManagement.checklist.{{ isTestExam ? 'testExam.' : '' }}title"></span>`

**Case 4:**

Translation keys that depend on conditions should be updated.

Instead of this (as an example), 

`<span>
    {{
        this.gradingScale.gradeType === GradeType.GRADE
            ? ('artemisApp.gradingSystem.gradeName' | artemisTranslate)
            : ('artemisApp.gradingSystem.bonusPoints' | artemisTranslate)
    }}
</span>`,

this should be used:  

`<span [jhiTranslate]="this.gradingScale.gradeType === GradeType.GRADE ? 'artemisApp.gradingSystem.gradeName' : 'artemisApp.gradingSystem.bonusPoints'"></span>`

### Description

- Four cases that have been explained above have been updated to their suggested versions.
- It was important to only replace cases where there is ONLY `{{ 'xxx' | artemisTranslate }}` between the tags since `jhiTranslate` removes everything between the tags.
- Here are the regex expressions that I used for replacing:

**Case 1:**
   - For searching: `<(\w+)([^>]*)>\s*(?:<!--.*?-->\s*)*\{\{\s*'([\w\d.-]+)'\s*\|\s*artemisTranslate\s*\}\}\s*(?:<!--.*?-->\s*)*\s*</\1>`
   - For replacing: `<$1$2 jhiTranslate="$3"></$1>`

**Case 2:**
   - For searching: `(<[^>]+)>\s*\{\{\s*'([^']*)'\s*\|\s*artemisTranslate\s*:\s*(\{[^}]*\})\s*\}\}\s*(<\/[^>]+>)`
   - For replacing: `$1 jhiTranslate="$2" [translateValues]="$3">$4`

**Case 3:**
   - For searching: `<(\w+)([^>]*)>\s*\{\{\s*([^?\s]+)\s*\?\s*\(\s*'([^']*)'\s*\|\s*artemisTranslate\s*\)\s*:\s*\(\s*'([^']*)'\s*\|\s*artemisTranslate\s*\)\s*\}\}\s*</\1>` and `<(\w+)([^>]*)>\s*\{\{\s*\(?\s*([^\s?]+(?:\?\.[^\s]+)?)\s*\?\s*'([^']*)'\s*:\s*'([^']*)'\s*\)?\s*\|\s*artemisTranslate\s*\}\}\s*</\1>`
   - For replacing: `<$1$2 jhiTranslate="{{ $3 ? '$4' : '$5' }}"></$1>`

**Case 4:**
   - For searching: `<(\w+)([^>]*)>\s*\{\{\s*([\w\.]+)\s*(===|!==|==|!=|>|<|>=|<=)\s*([\w\.]+)\s*\?\s*\(\s*'([a-zA-Z0-9\._]+)'\s*\|\s*artemisTranslate\s*\)\s*:\s*\(\s*'([a-zA-Z0-9\._]+)'\s*\|\s*artemisTranslate\s*\)\s*\}\}\s*<\/\1>
`
   - For replacing: `<$1$2 [jhiTranslate]="($3 $4 $5 ? '$6' : '$7')"></$1>`
 

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by JohannesStoehr — COMMENTED** [review]
Can we also replace the occurrences with translation parameters? Will this be done in a follow up?

**Comment by asliayk** [comment]
> Can we also replace the occurrences with translation parameters? Will this be done in a follow up?

What do we mean by "translation parameters"? Could you provide a code example please?

**Review by pzdr7 — COMMENTED** [review]
I think @JohannesStoehr means translations where the pipe gets some parameters:

e.g.

```tsx
{{ 'artemisApp.textExercise.wordCount' | artemisTranslate: { count: wordCount } }}
```

In this case, you'd use something like `jhiTranslate="artemisApp.textExercise.wordCount" [translateValues]="{ count: wordCount }"` to get rid of the translate pipe.

----

Something else to consider: sometimes, the translation key depends on some variables.

```html
<span>{{ 'artemisApp.examManagement.checklist.' + (isTestExam ? 'testExam.' : '') + 'title' | artemisTranslate }}</span>
```

These could also be replaced (`<span [jhiTranslate]=".....">`). Will this be done in a follow-up?

**Review by SimonEntholzer — CHANGES_REQUESTED** [review]
Good that someone clears up this mess for once :D.
I checked it out locally and as far as I tested it (which is difficult as this PR affects basically the application in every place) all text I encountered was displayed correctly. Though, there seem to be some files that still make use of the `artemisTranslate` pipe. Like `exam-status.component.html` e.g.
Probably the regexs didn't catch those as they have another pattern like <span> {{"text" | translate }} {{ ... }} ... </span>

**Comment by asliayk** [comment]
> Good that someone clears up this mess for once :D. I checked it out locally and as far as I tested it (which is difficult as this PR affects basically the application in every place) all text I encountered was displayed correctly. Though, there seem to be some files that still make use of the `artemisTranslate` pipe. Like `exam-status.component.html` e.g. Probably the regexs didn't catch those as they have another pattern like {{"text" | translate }} {{ ... }} ...

I think that case should not be updated with `jhiTranslate` because there are at least two items in a tag in that case, and when we use `jhiTranslate` it removes everything between the tags. (as discussed here: https://github.com/ls1intum/Artemis/issues/8561#issuecomment-2107015124)

To check that case I used  `<h2>{{ 'artemisApp.assessmentDashboard.pageHeader' | artemisTranslate }} {{ course?.title }}</h2>` in `assessment-dashboard.component.html`. I converted it to `<h2 jhiTranslate="artemisApp.assessmentDashboard.pageHeader"> {{ course?.title }}</h2>`, and I could not see the course title.

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by pzdr7 — APPROVED** [review]
Code 👍

**Review by SimonEntholzer — APPROVED** [review]
Code

**Review by JohannesStoehr — APPROVED** [review]
Reapprove after merge

**Review by BBesrour — DISMISSED** [review]
Tested on TS1, german and english, looks good.
course details (exercise, lecture, and communication) views. Code editor, course management page, course management details view. Build overview view.

**Review by pzdr7 — APPROVED** [review]
Reapproving code

**Review by edkaya — APPROVED** [review]
Code lgtm, great effort and work, thanks for refactoring!

**Review by egekurt123 — APPROVED** [review]
Code LGTM

**Review by edkaya — DISMISSED** [review]
Reapprove code

**Review by BBesrour — DISMISSED** [review]

**Review by JohannesStoehr — DISMISSED** [review]

**Review by pzdr7 — APPROVED** [review]
Reapprove

**Review by SimonEntholzer — DISMISSED** [review]
re-approve

**Review by coolchock — DISMISSED** [review]

**Review by DominikRemo — APPROVED** [review]
Code LGTM

**Review by sarpsahinalp — COMMENTED** [review]
It looks like there are two server tests that are failing. And you have to solve the merge conflicts

**Review by BBesrour — DISMISSED** [review]
lgtm on ts5, but client tests are failing

**Review by DominikRemo — APPROVED** [review]

**Review by SimonEntholzer — APPROVED** [review]
Code + tested various pages on Ts1, translation seems to work everywhere as expected

**Review by JohannesStoehr — APPROVED** [review]

**Review by pzdr7 — APPROVED** [review]

**Review by bassner — APPROVED** [review]
LGTM

**Pull request merged**
