### PR TITLE
[Bugfix] Fix min-width of plant UML

### PR DESCRIPTION
**Pull request by JohannesStoehr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation and Context

The students should have a clear view of the UML diagram in the problem statement. Especially when using the code editor which only offers a small area for the problem statement

### Steps for Testing

This PR fixes the problem that the UML diagrams in problem statements get squashed, when the vertical area of the problem statement is not big enough. Instead a scrollbar appears.

1. Log in to Artemis
2. Navigate to an exercise with a wide UML diagram (For example the standard Java exercise with the strategy pattern)
3. Check that the UML diagram is not squashed regardless of the window width
4. Check that the diagram is also displayed correctly in the code editor on the right hand side

### Screenshots

An old squashed diagram:
Bildschirmfoto 2021-07-10 um 12 25 41

A new non squashed diagram with a scrollbar at the bottom:
Bildschirmfoto 2021-07-10 um 12 25 54

### CODE REVIEW

**Review by lschlesinger — DISMISSED** [review]
Unfortunately, with this setting, the discussion section is not placed properly next to the UML anymore when it is in the collapsed mode. See picture:
Now:
Bildschirmfoto 2021-07-10 um 13 26 11
Before:
Bildschirmfoto 2021-07-10 um 13 25 23

**Review by willergeorg — DISMISSED** [review]
Tested on TS1. Worked good for me.

**Review by NicolasUllmann — APPROVED** [review]
Tested on TS1. Everything worked as expected.

**Review by lschlesinger — APPROVED** [review]
works on TS1.

**Review by niclasschuemann — APPROVED** [review]
Tested it on TS1 in all views, works as expected :)

**Pull request merged**
