### PR TITLE
`Plagiarism checks`: Fix an issue with plagiarism checks for Java programming exercises when running Artemis within a Docker image

### LINKED ISSUE #5945: `Programming exercises`: Checking plagiarism fails
### Describe the bug

Checking for plagiarism in programming exercises fails. See log below.

### To Reproduce

1. Use a Java programming exercise with multiple submissions.
2. Use the Check Plagiarism > Detect plagiarism functionality.
3. The InternalServerError as below appears.

### Expected behavior

The plagiarism result is created without error.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

5.12.6

### What browsers are you seeing the problem on?

Firefox

### Additional context

cc @dfuchss: You might know if this is specific to how JPlag is used as a dependency in Artemis, or if this happens with standalone JPlag, too.

### Relevant log output

```shell
Caused by: java.lang.NoClassDefFoundError: com/sun/source/tree/TreeVisitor
        at de.jplag.java.Parser.parse(Parser.java:25)
        at de.jplag.java.Language.parse(Language.java:47)
        at de.jplag.Submission.parse(Submission.java:249)
        at de.jplag.SubmissionSet.parseSubmissions(SubmissionSet.java:147)
        at de.jplag.SubmissionSet.parseAllSubmissions(SubmissionSet.java:103)
        at de.jplag.SubmissionSet.<init>(SubmissionSet.java:45)
        at de.jplag.SubmissionSetBuilder.buildSubmissionSet(SubmissionSetBuilder.java:78)
        at de.jplag.JPlag.run(JPlag.java:43)
        at de.tum.in.www1.artemis.service.plagiarism.ProgrammingPlagiarismDetectionService.computeJPlagResult(ProgrammingPlagiarismDetectionService.java:206)
```

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
Closes #5945

### Description
JPlag seems to need JDK-specific classes to compare Java submissions. Those classes are not part of the JRE. Therefore, the comparison fails with the internal server error as described in #5945.

This change increases the size of the Docker image again by 200MB to the same size it was before #5739.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Java Programming exercise with a few submissions

1. Log in to Artemis
2. Go to the exercise instructor view > ‘Check Plagiarism’ and click on Detect Plagiarism.
3. No InternalServerError should appear.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
Probably optional, since the change is so small.
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

### CODE REVIEW

**Comment by b-fein** [comment]
> @4ludwig4 why did you change to jre in the previous PR?

That was because the previous `openjdk` image is deprecated. When we moved to a new base image and since there is a `temurin-JRE` one, we though it was a good opportunity to reduce the image size by not including the full JDK, as that is not necessary to run Artemis.

**Review by timo07k — APPROVED** [review]
No InternalServerError appeared. Tested on TS1.

**Review by LiaLism — APPROVED** [review]
No InternalServerError was displayed. Tested on TS1.

**Review by evgeny1984 — APPROVED** [review]
No internal error occurred, everything worked correctly. Tested on ts1.

**Review by PhilipWerz — APPROVED** [review]
InternalServerError didn't occur/wasn't displayed. Tested on TS1.

**Pull request merged**
