### PR TITLE
Bugfix/quiz/duration selector

### PR DESCRIPTION
**Pull request by fde312**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple integration tests (Jest) related to the features
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

When using the duration selector during the quiz creation a strange behaviour was found. The issue is described in #1391
### Description

The problem is that the input value was not updated correctly even though the model had the right value.
- Added `detectChanges()`before updating duration values
- Bring ngModelChange and ngModel into the right oder (see following issue: https://github.com/angular/angular/issues/11234)
- Removed `(blur)` as `(ngModelChange)` is already getting the changes

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Management
3. Go to exercises of a Course
4. Create a new Quiz
5. Use duration selector
5a. When being at seconds 11:59 and you click up, it should go to 12:00
5b. When being at seconds 12:00 and you click down, it should go to 11:59
5c. When being at 600:00 and you click up nothing changes, when you click down it goes to 599:59
5d. When being at 00:00 and you click down nothing changes, when you click up it goes to 00:01

### Screenshots

Test clicking up to 60 seconds and down to -1 seconds:

video1

Test min and max value:

video2
video3

Delete input values and reenter values:
video4

### CODE REVIEW

**Comment by krusche** [comment]
The behavior is improved. What I do not really like: when changing the values with they keyboard, you cannot delete the leading "0" anymore. Can we allow this while being in the text field?

**Comment by Varnika-Tyagi** [comment]
Works fine for me as well.

**Comment by fde312** [comment]
> The behavior is improved. What I do not really like: when changing the values with they keyboard, you cannot delete the leading "0" anymore. Can we allow this while being in the text field?

Yes, we are checking now if the input fields are empty and do not update their values so that they stay empty and are not overwritten to 0.

**Comment by Varnika-Tyagi** [comment]
Works fine for me.

**Pull request merged**
