### PR TITLE
Fix the link to modeling exercise statistics

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

The instructor actions have a link to the statistics, which doesn't work right now:
grafik

### Description

We correct the link to point to the correct page.

### Steps for Testing

1. Create or find a modeling exercise
2. Go to the student view with an instructor account
3. Click on "statistics"

### Review Progress

- Code Review
  - [x] Review 1
  - [x] Review 2
- Manual Tests
  - [x] Test 1
  - [x] Test 2

### CODE REVIEW

**Review by Olimbia23 — DISMISSED** [review]
Nice catch @FrankeLukas.
Code change seems reasonable. Approve 👍

**Review by MerlinMehmed — DISMISSED** [review]
Tested on TS1 and works as expected. Code changes are also ok.

**Review by FuchsDominik — COMMENTED** [review]
Navigation works, but I am not quite sure about the correctness of the link. I think there is an alternative statistics page for modeling exercises, as I did not add this button and I thought to have seen such a thing. Code-wise, it should be the `modeling-statistics.component.ts`

**Review by FuchsDominik — CHANGES_REQUESTED** [review]
Just looked it up and the route of mentioned component matches the old route you overwrote, so this is probably the component you want to navigate to

**Comment by FrankeLukas** [comment]
I see, the component the old route uses doesn't do anything but throw a 404 at the moment, see https://github.com/ls1intum/Artemis/blob/5af5f40306fa126cca6d761dc8eb42c4ae940300/src/main/java/de/tum/in/www1/artemis/web/rest/ModelingExerciseResource.java#L241-L246 which was done by https://github.com/ls1intum/Artemis/commit/fa90f52fcdfd159faffb42a9abd7b7f82b571561#diff-add7a69d47dc03e894f18150f009b3b1a9290fc48ec484ee21b45c08f7054d24L237

Tbh I don't know what to do here.

**Comment by FrankeLukas** [comment]
> Tbh I don't know what to do here.

@krusche told me to remove all the related code since they are no longer used/required.

**Review by SimonEntholzer — APPROVED** [review]
Code changes look fine, as they mostly are only deletions of now redundant code.

**Comment by FrankeLukas** [comment]
Codacy made a remark about an unused import, so I removed that and the now unused model as well.

**Review by imstreetspirit — APPROVED** [review]
code changes seems fine, lots of unused code removed

**Review by MDK5 — APPROVED** [review]
Tested on ts1, the link works. Code changes look good to me, always great to see some cleanup

**Review by DanielKainz — APPROVED** [review]
Code changes look good. Great cleanup.

**Review by julian-christl — COMMENTED** [review]
Was this already dead code? Because it looks to me like there were quite some specific stats for modelling exercise that you removed and replaced with the generic ones for all exercises.
Or does the specific code already exist somewhere else where I don't find it right now?

**Review by argertboja — APPROVED** [review]
Nice job on making Artemis code more lightweight 😄

**Pull request merged**
