### PR TITLE
`Development`: Throw an exception if an email could not be sent to a user

### PR DESCRIPTION
**Pull request by sleiss**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Currently, there only was a `warn`-log when a mail could not be sent.
This caused issues as a wrong mail-config was not detected (the exception was catched).

### Description
This PR changes the log level to `error` and rethrows the exception as `ArtemisMailException` (a `RuntimeException`).

### Steps for Testing
On TS0/TS1:
1. Enable some email notifications (when an exercise is created in your settings)
2. Trigger that email notification (create a **text** exercise)
3. Make sure that the email is received

On TS3:
Repeat steps 1 & 2 and make sure that the error is logged with the `error`-level.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by max-bergmann — COMMENTED** [review]
Tested on TS3 with @jschmautzer.
Tested with Quiz & Text exercise. 2 valid TUM Accounts with enabled E-Mail notification didn´t recieved an email.

**Review by jschmautzer — COMMENTED** [review]
tested on ts3 with @max-bergmann
created text exercise and quiz exercise, but did not receive emails (beforehand: enabled email notifications in settings)

**Comment by sleiss** [comment]
@max-bergmann @jschmautzer Sorry, I just saw [here](https://confluence.ase.in.tum.de/pages/viewpage.action?pageId=25252245) that TS3 does not support sending emails.
It would be great if you could test it again on TS0 or TS1.

**Review by yuling-sun — COMMENTED** [review]
Tested on TS1. I enabled e-mail notification when exercise is released or quiz is released for practice, but I did not receive an e-mail when triggering any of these. I used my own TUM-account for the test.

**Comment by sleiss** [comment]
> Tested on TS1. I enabled e-mail notification when exercise is released or quiz is released for practice, but I did not receive an e-mail when triggering any of these. I used my own TUM-account for the test.

Thanks for your review. I just tried it on TS1 with my account and received the email. Could you please tell my which course you used?

**Review by jbllhff — COMMENTED** [review]
I tested the mail notification on ts1 with a file upload on georg willers test course. I neither got an error message nor an email notification.

**Review by yuling-sun — CHANGES_REQUESTED** [review]
Tested on TS1 again. The e-mail notification works as described. However, when I disable webapp notification, but enable e-mail notification in file submission, I don't receive an e-mail. When both are enabled, I receive e-mails for some reason.

**Review by jschmautzer — APPROVED** [review]
tested on ts0, worked with text exercises :)

**Comment by ge65cer** [comment]
> Tested on TS1 again. The e-mail notification works as described. However, when I disable webapp notification, but enable e-mail notification in file submission, I don't receive an e-mail. When both are enabled, I receive e-mails for some reason.

I guess that behavior is unrelated to this PR. Would be great if you could open an issue with some more details if you think that's a bug.

**Review by ge65cer — APPROVED** [review]

**Review by yuling-sun — APPROVED** [review]

**Review by ole-ve — APPROVED** [review]
Code looks good 👍

**Review by mallgaier — APPROVED** [review]
Tested on TS3, works as expected.
Code changes look good :)

**Pull request merged**
