### PR TITLE
[Bugfix] Add translated tooltip for not released tag

### PR DESCRIPTION
**Pull request by lschlesinger**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all newly inserted strings into English and German.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

Solves an issue that I found during testing: #4024 

### Steps for Testing

1. Log in to Artemis as tutor/instructor
2. Find or create an exercise with future release date
3. In course overview, search for that exercise and notice that the tag is shown
4. hover over the tag, tooltip should appear
5. changing language to German, tooltip should appear in german language

### Review Progress

- Code Review
  - [x] Review 1
  - [x] Review 2
- Manual Tests
  - [x] Test 1
  - [x] Test 2

### Screenshots

<!-- Create a GIF file from a screen recording in a docker container https://toub.es/2017/09/11/high-quality-gif-with-ffmpeg-and-docker/ --
Bildschirmfoto 2021-09-26 um 17 29 11
Bildschirmfoto 2021-09-26 um 17 29 02
>

### CODE REVIEW

**Review by Malyuk-A — APPROVED** [review]
Tested on TS2. (Code changes are also good) 👍

**Review by Olimbia23 — APPROVED** [review]
Good work @lschlesinger
Code changes look good. Approve 👍

**Review by MerlinMehmed — APPROVED** [review]
Works as expected. Code also looks good.

**Review by ndricimrr — APPROVED** [review]
Tested locally. Worked fine 👍

**Pull request merged**
