### PR TITLE
`Assessment`: Fix link in scores page for multiple assessment rounds

### LINKED ISSUE #6395: Cannot open Assessments from Score Page
### Describe the bug

Since the "Submission" Page has been removed in #6110 , we have to use the new "Score" Page to open certain assessments.

Unfortunately, this is not possible in our case:
image
 We get an error while clicking on open assessment (for exam tasks with two correction rounds enabled) (Error in the additional comments)

In addition, we wonder about these points:

1. If we click on open editor, we get an editor where we can modify the code and click on a submit button (even after the end of the exam)
image

2. How can we create the assessment of the first (or second round manually), before the merge, this was possible in the submission view. This was very useful to do some manual grading for special submissions.

### To Reproduce

See above

### Expected behavior

No error, and opening of assessment

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.1.2

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell
ERROR Error: Uncaught (in promise): Error: NG04002
P@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1307751
noMatchError@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1539989
apply/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1539726
D/</f<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1115041
t/this._error<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1114505
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
_error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103259
error@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1103021
v@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1113284
_trySubscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098710
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098655
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
D/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1115134
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
t/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1117598
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
j@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1118298
U@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1118227
t/this._next<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1114436
next@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1102915
R/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1111824
_trySubscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098710
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098655
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
y@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1118497
f/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1118548
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
g/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1119228
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
Te/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1505143
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
D/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1122455
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
t/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1117598
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
t/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1117598
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
D/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1114992
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
t/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1117598
t/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1129610
subscribe/<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098619
t@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1127705
subscribe@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1098571
D/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1120986
t/this._next<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1114436
next@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1102915
D/</</m<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1121013
t/this._next<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1114436
next@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1102915
A/</<@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1111932
invoke@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:9156
onInvoke@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1412867
invoke@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:9096
run@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:4508
ue/<@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:19366
invokeTask@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:9774
onInvokeTask@https://artemis.praktomat.cs.kit.edu/main.4f1af9765d6042e7.js:1:1412680
invokeTask@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:9695
runTask@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:5131
p@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:11794
invokeTask@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:10858
O@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:23363
I@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:23661
M@https://artemis.praktomat.cs.kit.edu/polyfills.6dd8c378ec2b5726.js:1:23926
```
```

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Fixes #6395

### Description

Some routs were misconfigured.
Additionally the assessment link always needs the submission id, which is now provided. Without the id a random submission would be chosen instead.

### Steps for Testing

Prerequisites:
- 1 Tutor
- 2 Students
- 1 Programming Exercise
- 1 Modeling Exercise
- 1 Text Exercise

1. Log in to Artemis
2. Create or find these exercises with submissions from two students. It doesn't matter if they are assessed.
3. Check that the assessment links in the scores page of each exercise work
4. Check that the assessment links in the assessment of each exercise dashboard work

#### Exam Mode Testing

Prerequisites:
- 1 Tutor
- 2 Students
- 1 Exam with a Programming, Modeling and Text Exercise

1. Log in to Artemis
2. Create or find an exam with submissions from two students. It doesn't matter if they are assessed.
3. Check that the assessment links in the scores page of each exercise work
4. Check that the assessment links in the assessment of each exercise dashboard work

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| ParticipationResource.java | 91% | ✅                           |

### CODE REVIEW

**Review by danielbode — APPROVED** [review]
Code LGTM

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Review by pal03377 — APPROVED** [review]
TS1 (Testing session): The `Assess submission` button is available for rows without any submissions. When clicking it, nothing happens.

screenshot-2023-05-08_001320

(https://artemis-test1.artemis.in.tum.de/course-management/100/text-exercises/1937/scores)


@JohannesStoehr wants to fix this in a follow-up PR to merge this one more quickly, so I still approve as general functionality is not affected and the rest still works as expected.

**Review by tobias-lippert — APPROVED** [review]
Apart from the issue @pal03377 mentioned above, everything worked and since the issue will be addressed in a follow-up, I approve this one.

**Review by DominikRemo — APPROVED** [review]
Tested in testing session on ts1

**Review by pellumbbaboci — APPROVED** [review]
Tested exam mode on ts1 during testing session assessment links work as expected

**Pull request merged**
