### PR TITLE
`Communication`: Fix incorrect display of edit and delete icons when switching between threads

### PR DESCRIPTION
**Pull request by egekurt123**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.

### Description

This PR addresses the issue where the edit and delete icons do not update correctly when switching between threads. The problem was due to the user properties not being set correctly for each thread.

Solves #8981 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Course with Communications enabled

1. Log in to Artemis
2. Navigate to a Course with Communication enabled
3. As User 1 (Instructor), send two messages in a channel.
4. On the first message, reply a few times.
5. As User 2 (Student), on the second message, reply a few times.
6. Switch to the thread of the first message.
7. Make sure that the edit and delete icons are shown correctly (expected behaviour is admin/instructor can edit/delete all messages, while student can only edit/delete their own messages)

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **Refactor**
  - Improved code organization and encapsulation in post header components to better manage user permissions for editing and deleting posts.
  - Consolidated logic for setting user properties and edit/delete permissions into dedicated methods for cleaner and more maintainable code.

### CODE REVIEW

**Review by asliayk — APPROVED** [review]
tested on ts3 and works as expected

**Review by EneaGore — APPROVED** [review]
Tested on TS5 during testing session. Works as expected

**Review by edkaya — APPROVED** [review]
Tested in the testing session, works as expected. Code also good to me

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by krusche — APPROVED** [review]

**Pull request merged**
