### PR TITLE
`Iris`: Embed chat window into exercise creation page instead of floating dialog

### PR DESCRIPTION
**Pull request by RY997**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

### Motivation and Context

Displaying the Iris chat window as a dialog in the "Create Programming Exercise" is not the ideal and expected way. It's better to embed it on the page.

### Description

Rewrite and refactor the chatbot widget component. In "Create Programming Exercise", the chat window will be displayed on the right side and remain visible as the page is scrolled, allowing the user to send new requests while reviewing the problem statement.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with Iris Code Editor feature enabled (you can simply use [Exercise Adaption Test Course](https://artemis-test9.artemis.cit.tum.de/course-management/10/exercises)

1. Log in to Artemis
2. Navigate to the "Create programming exercise" page (Course Management -> Course -> Exercises)
3. See that the Iris logo is there, click it
4. The chat window is on the right side of the page instead of a floating dialog box on the page
5. Resize the page, resize the chat window, and check the responsiveness
6. Scroll the page, the chat window should be visible in the same position

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

Screenshot 2024-02-15 at 16 25 11

Screenshot 2024-02-15 at 16 26 27

Screenshot 2024-02-15 at 16 48 25

### CODE REVIEW

**Review by xHadie — CHANGES_REQUESTED** [review]
_Manually tested on TS9_


I still see the corner floating button in the student view. So that is fine


I can see the button on exercise creation/edit pages


but it overflows the viewport on smaller screens.

**Review by konrad2002 — CHANGES_REQUESTED** [review]
manually tested on TS9.. works as described, however when using the "guided mode" for exercise creation the iris chat box and button are displayed below the creation form.

image

**Review by Gusti2010 — CHANGES_REQUESTED** [review]
Tested manually on ts9. Chat window is where it should be on the exercise creation page. However, on guided mode the window is at the bottom left corner.

**Review by Predixx — COMMENTED** [review]
Not sure if i am doing something wrong but for me it doesnt show IRIS at all. 
grafik
(you can pm me on Slack)

**Pull request closed without merging**
