### PR TITLE
Add documentation for multiple instances.

### PR DESCRIPTION
**Pull request by sleiss**
### Motivation and Context
Added documentation regarding multiple instances.
Most of the configuration is copied from Confluence/Ansible.

### CODE REVIEW

**Comment by jpbernius** [comment]
I activated this branch on RTD: https://artemis-platform.readthedocs.io/en/docu-distributed-setup/dev/setup/distributed/

**Comment by sleiss** [comment]
@jpbernius Thanks!

**Review by MaisiKoleni — APPROVED** [review]
Looks good to me after the suggested spelling and markdown fixes, content seems fine as far as I can tell.

**Review by krusche — APPROVED** [review]
Looks good to me. Additional improvements in the documentation can be done in follow up PRs

**Pull request merged**
