### PR TITLE
Feature/orion/show test output

### PR DESCRIPTION
**Pull request by ungaralex**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple integration tests (Jest) related to the features
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

We wanted to display the test output (and build output in case of compile errors) in the Orion plugin in IntelliJ. This is the PR containing the Angular client changes necessary to forward this information to the IDE.

### Description

There is a new IDE build and test service, which gets called once a user submits code inside the IDE. This service then listens to any build results and forwards them accordingly to IntelliJ.
 
I also filter out any non programming exercises from the overview if the user opens the webpage using IntelliJ. **I do want to change this in a future PR**. I want to move this to a separate component, so that we don't have that many `*ngIf`s and have a dediated programming exercise overview just for IntelliJ (also including minor UI improvements like a smaller header since this takes too much space in the small IDE tool window) 

### Steps for Testing

**Use the current release of Orion: https://github.com/ls1intum/Orion/releases/tag/v0.2.3**

1. Open IntelliJ
2. Navigate to the setting as displayed in the gif and set the URL to the test server
3. Open/import any programming exercise
4. Click on submit
5. The test results should be displayed in a tool window after the build finished

#### Where to find the settings
orion_settings_new

#### How to test
orion_buildoutput

### CODE REVIEW

**Comment by ungaralex** [comment]
If you are not able to login on the first page (login button keeps on loading) please write me the time when you tried to login. This is a known problem which might be connected to Jira

**Comment by ungaralex** [comment]
Thanks a lot for the feedback @lovaiible!
The naming will change in the next minor release of the plugin itself, good suggestion. 
The png missing png was a general bug (also on prod) and has been solved on develop and should not be a problem any more

**Comment by ungaralex** [comment]
> image
> Why does the IntelliJ Button show for Text Exercises?

They shouldn't even be shown. Seems like a recent merge with develop removed the filter I put there.

**Comment by jpbernius** [comment]
image
If I click the "Build & Test on Artemis Server" Button in the IntelliJ Panel (or ⌘ + R), it hangs like so and nothing happens:

image

**Comment by jpbernius** [comment]
Besides the mentioned comments, the feature works very well and is a joy to use!

**Comment by ungaralex** [comment]
@jpbernius thanks a lot for the feedback.
I released a new version of the plugin, which adds support for running builds/tests from within the IDE, just like you tried. However, I could not reproduce the error with the other exercise types showing up in IntelliJ. The screenshots you provided look like a mix from an older build and develop. Could you maybe try this again with the latest changes?

@lovaiible The latest plugin release also contains the change regarding the label of the toolwindow ;)

**Comment by krusche** [comment]
@ungaralex what is the current state of this PR? Can we merge this?

**Comment by jpbernius** [comment]
@ungaralex Can you fix the [TypeScript Formatting](https://bamboobruegge.in.tum.de/browse/ARTEMIS-TESTS77-TSFORMAT-22)?

**Comment by jpbernius** [comment]
@github-actions please lint this

**Pull request merged**
