### PR TITLE
`Development`: Update screenshots with the new Code button

### PR DESCRIPTION
**Pull request by pzdr7**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

#8920 Renamed the Clone Button to "Code". We need to make sure this information is consistent across Artemis. The feature overview still has outdated screenshots.

### Description

Switched out the screenshots and changed the text to refer to the Code button.

### Steps for Testing

Prerequisites:
- Deploy on a test server
- **Important**: Make sure your cache is disabled (Chrome devtools > Network > Check "Disable cache"). Otherwise, you might not see the new screenshots

1. Navigate to the "About" section in the footer.
2. Under "6. Exam mode," open the links for "Students" and "Instructors" in a new tab.
3. Read the text and look at the screenshots. Make sure no reference to the "Clone button" remains.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### Test Coverage

Unchanged

### Screenshots

See the changed files

## Summary by CodeRabbit

- **Style**
  - Updated user instructions to reflect button label change from "Klon-Button" to "Code-Button" in the German interface.
  - Updated user instructions to reflect button label change from "clone" to "Code" in the English interface.

### CODE REVIEW

**Review by Jan-Thurner — APPROVED** [review]

**Review by Jan-Thurner — APPROVED** [review]
LGTM

**Review by JohannesWt — APPROVED** [review]
Tested on TS1 👍

**Review by EneaGore — APPROVED** [review]
Could not find any reference to Clone Button on TS1.

**Review by Strohgelaender — APPROVED** [review]

**Comment by pzdr7** [comment]
More UI changes are on the way. Will probably handle this part in a new PR

**Pull request closed without merging**
