### PR TITLE
`Exam mode`: Fix unhandled exception in exam score view

### PR DESCRIPTION
**Pull request by max-bergmann**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [X] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [X] I documented the Java code using JavaDoc style.
#### Client
- [X] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
This PR should improve the usability of the Exam Scores. An error 500 was triggered if no exercise group was previously created. This fixes the problem and displays an error message to the user.

### Description
fixes https://github.com/ls1intum/Artemis/issues/7417

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to Exam
4. Create a new Exam
5. Open Exam score - Test if there are the 2 new messages shown
6. Create Exam Group - Test if the error message for missing exam groups is solved in the score tab
7. Participate in the Exam - Test if the results are shown correctly. 

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| exam-scores.component.ts | 96% | ✅              |
### Screenshots

image

### CODE REVIEW

**Review by milljoniaer — APPROVED** [review]
tested on ts4 works as expected 👍

**Review by valentin-boehm — APPROVED** [review]
code lgtm

**Comment by xHadie** [comment]
_Tested on TS3_Legacy_
Everything works as expected!

**Review by matthiaslehnertum — APPROVED** [review]

**Review by vinceclifford — APPROVED** [review]
Works as expected. Tested during testing session

**Review by rstief — APPROVED** [review]
Shown in testing session.

**Review by lennart-keller — APPROVED** [review]
Demonstrated in testing session

**Review by florian-glombik — APPROVED** [review]
Demonstrated on ts2

**Review by basak-akan — APPROVED** [review]
Demonstrated in the testing session

**Pull request merged**
