### PR TITLE
Reduce space taken by navbar and notification panels

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

The margins of the notification panels were a bit too large, which was highlighted even more due to the recent breadcrumb changes.
Before:
grafik
grafik
After:
grafik
grafik
grafik

### Steps for Testing

1. Log in to Artemis
2. Create a new System Notification ("Server Management" > "System Notifications")
3. Check if the margins fit in both a student's course overview and the instructors' course management view ("Course Overview" and "Course Management"; in the latter you have breadcrumbs)

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Everything works fine, tested on ts3

**Review by marvinchimeka — APPROVED** [review]
Tested it on Ts3. Everything worked like it is shown in the screenshots.

**Review by tiffca — APPROVED** [review]
Tested successfully on test server 3.

**Review by simonzilker — APPROVED** [review]
Works as intended!

**Review by JohannesWeiss — APPROVED** [review]
Works as intended.

**Review by EneaGore — APPROVED** [review]
Tested on ts3 and works fine.

Unrelated to this PR though: multiple notifcations dont show all at the same time (only shows whchever has the earliest date) and there is no warning if the end date is before the start date.

**Review by philgabr — APPROVED** [review]
Everything works as intended (ts3).
As @EneaGore already mentioned, only one notification message is displayed at the same time.

**Review by LudwigWeide — APPROVED** [review]
Tested on ts1. Works as intended.

**Review by DenizShabani — APPROVED** [review]
Works as intended.

**Review by valeriebucher — APPROVED** [review]
Works as described!

**Review by krusche — APPROVED** [review]

**Pull request merged**
