### PR TITLE
[Client Style] fix the 'assigned but never used' issue

### PR DESCRIPTION
**Pull request by rs-maker**
### Motivation and Context
 It solves this client style issue:
Screenshot from 2021-08-17 20-33-17

### Description
 I removed the variable that was only assigned to but never used.

### Steps for Testing

Mainly code review but you can also run the corresponding test locally.

### Review Progress

- Code Review
  - [x] Review 1
  - [ ] Review 2
- Manual Tests
  - [ ] Test 1
  - [ ] Test 2

### CODE REVIEW

**Review by Olimbia23 — APPROVED** [review]
Thank you for fixing it @rs-maker. 
Code changes are reasonable. Approve 👍

**Review by coolchock — APPROVED** [review]
code changes look good :+1:

**Review by jhainzlschmid — APPROVED** [review]
Nice, thanks for fixing it 👍

**Review by jpbernius — APPROVED** [review]
😍

**Pull request merged**
