### PR TITLE
`General`: Improve exercise rows for small screens

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Improve the experience with users on small screens or mobile.

### Description

The exercises shown in the course overview or the currently active exercise above the courses on the start page did not scale well on small screens. This PR truncates the title and hides the categories when the screen size does not offer enough space.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exercise with a long title and some categories (unreleased, bonus exercise, difficulty and tags)

1. Log in to Artemis
2. Look at the exercise rows with different screen widths

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Wide screen (normal):
Bildschirmfoto 2023-05-30 um 11 36 47
Small screen (title starts to be truncated):
Bildschirmfoto 2023-05-30 um 11 36 59
Smallest screen (title more truncated and categories hidden):
Bildschirmfoto 2023-05-30 um 11 37 12

### CODE REVIEW

**Comment by bassner** [comment]
I'm not sure how happy I am with this view. It looks kinda weird that the icon of the long programming exercise is moved up, looks odd compared to the other rows. Can we instead keep it on the left and just cut of the text like it's done now?
We can set a breakpoint to move the icons up for all rows at once if that helps with small screen layouts.
What do you think? :)
image

**Comment by MaximilianAnzinger** [comment]
The Labels are positioned higher than the button but are a little shorter. This makes the UI look slightly like a staircase to me.
If you set `margin-top` and `margin-bottom` of the labels to `auto`, they should be positioned nicely.

Here is a screenshot before:
chrome_rkCpTZO9rX

Here is a screenshot after:
chrome_APUYmJMgld

Maybe the date should also be vertically centered?

**Review by RY997 — COMMENTED** [review]
Tested on ts5, worked well. Just a small comment: 
The "in 8 minutes" looks a little bit unclear even though it's because of saving space, maybe add "Due". 
In addition, capitalizing 'I' of 'in' is better in my opinion.
image

**Review by DominikRemo — DISMISSED** [review]
Code LGTM

**Review by SabrinaGlatz — DISMISSED** [review]
tested on ts1, works as expected

**Review by dakennguyen — APPROVED** [review]
tested on ts1, works as expected

**Comment by JohannesStoehr** [comment]
> Tested on ts3. Please confirm if this behavior is intended: A very long title was cut off on full screen as well and could only be fully read in the file tree above the title.
> 
> image

The breadcrumbs are not part of this PR. This is mainly about fixing the overview when quickly scrolling through the course on mobile

**Review by greekgeek1 — DISMISSED** [review]
Approve after previous comment was solved.

**Review by DominikRemo — APPROVED** [review]
Reapprove Code

Optional:
Codacy is complaining
_src/main/webapp/app/overview/course-exercises/course-exercise-row.scss#L64
Expected empty line before at-rule (at-rule-empty-line-before)_

**Review by DominikRemo — APPROVED** [review]
Reapproved Code. Thank you for fixing the Codacy issue :D

**Review by greekgeek1 — APPROVED** [review]

**Review by SabrinaGlatz — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
