### PR TITLE
[Refactor] small improvements for grading instruction details component

### PR DESCRIPTION
**Pull request by imstreetspirit**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all newly inserted strings into English and German.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

This PR aims refactoring for grading-instruction-details-component. Currently, reset button for grading criteria title and grading instruction does not work if it is newly added by user. Because, I was comparing the backup exercise and the current exercise, so if the object is not part of backup exercise, reset did not work. To fix, I just initialize with default title and grading instruction if user wants to reset changes for newly added grading criteria or grading instruction. In addition, I added tooltip for reset/delete/plus button in the form.
I also changed some strings to keep consistency.

### Steps for Testing

P.S. _To display the grading instruction in this form, you need to use the grading instruction as a feedback during the assessment at least once, probably we will provide this mode even if the grading instruction is not associated with the feedback. However, its not scope of this PR._ 

1. Log in to Artemis
2. Navigate to Course Administration
3. Create/Find exercise.
4. Go to edit view. Switch Grading Instructions.
5. Hover the buttons for grading instructions, you should see the tooltip. 
6. Add new grading criterion/grading instruction, change something then click the reset button, it should display default text.
7. Change title for newly added grading criteria then click small reset button, it should display only 'Criterion Title' placeholder for input area.

### Test Coverage

nothing changed.

### CODE REVIEW

**Review by KiraNickel — DISMISSED** [review]
Tested on ts3, works as described 👍🏼

**Review by canyelten — DISMISSED** [review]
Tested on TS1, works as expected.

**Review by canyelten — COMMENTED** [review]
Small suggestion: I would remove the word "here". It's unnecessary in my opinion and also isn't a part of the wording in the other buttons. The hover box would also get smaller and the design/wording would be consistent with the other buttons.

**Comment by imstreetspirit** [comment]
> Small suggestion: I would remove the word "here". It's unnecessary in my opinion and also isn't a part of the wording in the other buttons. The hover box would also get smaller and the design/wording would be consistent with the other buttons.
> 

@canyelten ah sure... will do!!

**Pull request merged**
