### PR TITLE
[Exam] Make grace period editable and display additional attributes on participation start cover

### PR DESCRIPTION
**Pull request by sascha11110**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
The grace period should be editable and we want to provide the students with additional information about the exam.

### Description
- [x] I've added the attributes `examiner`, `moduleNumber` and `courseName`
- [x] I've displayed the attributes and more on the participation start cover (see last screenshot)
- [x] I've made the grace period editable

### Steps for Testing
1. Log in to Artemis
2. Create a new exam with all three new attributes and with an individual grace period
3. Check that the attributes are saved
4. Edit the same attributes
5. Check that the attributes were updated
6. Participate in the exam: check that everything is displayed on the participation start cover (compare with the last screenshot)

### Screenshots
image
image
image

### CODE REVIEW

**Comment by krusche** [comment]
@florian-glombik that's really strange behavior. Does this also happen on the newest version of the `develop` branch?

**Comment by florian-glombik** [comment]
I have tested it on release-545 on the develop branch and indeed, there is the same behaviour. 
So this problem might not be related to this PR.

**Comment by krusche** [comment]
> @florian-glombik that's really strange behavior. Does this also happen on the newest version of the `develop` branch?

I ask, because there are no changes in the code to the respective timer.
Can you check the network calls and console logs in your browser and insert them here?

**Comment by krusche** [comment]
> I have tested it on release-545 on the develop branch and indeed, there is the same behaviour.
> So this problem might not be related to this PR.

Thanks, then we should definitely fix it with a high priority.

**Comment by florian-glombik** [comment]
I would like to send you the logs, however right now the problem doesn't occur - I will inform you as soon as I have gathered more information.

**Comment by sascha11110** [comment]
I am still investigating the problem and want to fix it in this branch. There is no uncommon network call but there is an `ExpressionChangedAfterItHasBeenCheckedError`. I think somehow the transition between the components is disturbed.

**Comment by florian-glombik** [comment]
I was not able to reproduce the bug on the develop branch anymore, on the branch of this PR it always occurs for me.

It seems like @sascha11110 and me were only able to reproduce the bug on the development branch after testing the on this PRs branch - maybe some information in the cache was the reason for the bug also occurring on the development branch?

**Comment by sascha11110** [comment]
@florian-glombik @TobiasPr Thanks so far! I've fixed the problem with the counter. Can you test again?

@TobiasPr I couldn't reproduce the problem with the wrong time displayed. Can you check that again?

**Comment by krusche** [comment]
> Everything in this PR works as expected and the attributes are also saved and shown correctly when edited or not edited.
> 
> I found something strange and maybe this is out of scope for this PR but wanted to point that out that it's possible to set the end date of the student review before the start date of the student review
> Bildschirmfoto 2020-07-16 um 17 30 38

That's ok for now. The instructor should add those dates carefully.

**Pull request merged**
