### PR TITLE
`Adaptive learning`: Enable users to view standardized competency details on json import

### PR DESCRIPTION
**Pull request by rstief**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation, Context and Description
Users could not see all details for standardized competencies they imported before. this is now possible.

### Steps for Testing
Prerequisites:
- 1 Admin

1. Log in -> Enable Standardized Competency Feature Toggle
2. Go to Server Administration -> Standardized Competencies
3. Go to import, import the following file: [import_correct.json](https://github.com/ls1intum/Artemis/files/15122048/import_correct.json)
4. Open a knowledge area -> click on a standardized competency
5. See that the competency details now open (and you can close them with x)

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [admin-import-standardized-competencies.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6483/latest/artifact/shared/Coverage-Report-Client-Tests/app/admin/standardized-competencies/import/admin-import-standardized-competencies.component.ts.html) | 97.36% | ✅  |

### Screenshots
image

## Summary by CodeRabbit

- **New Features**
  - Introduced functionality to import standardized competencies into courses.
  - Enhanced user interface for managing and importing standardized competencies, including new components for competency details and filtering.
  - Added new routes and components for competency management in course settings.

- **Enhancements**
  - Renamed components for better clarity and usability in competency management.
  - Improved layout and interaction in competency management components.

- **Bug Fixes**
  - Adjusted button labels in competency management to enhance user understanding.

- **Refactor**
  - Significant refactoring in Angular components related to standardized competencies to improve performance and maintainability.

- **Style**
  - Updated styling for new standardized competency components.

- **Tests**
  - Added and updated test cases for new functionalities and components related to standardized competencies.

### CODE REVIEW

**Review by pzdr7 — DISMISSED** [review]
Code LGTM :+1:

**Comment by BBesrour** [comment]
Code lgtm!

**Review by BBesrour — APPROVED** [review]
Code lgtm!

**Review by JohannesWt — APPROVED** [review]
Also tested in testing session - works as promised 👍

**Review by laurenzfb — DISMISSED** [review]
demonstrated in session

**Review by MaximilianAnzinger — APPROVED** [review]
Maintainer approved

**Comment by florian-glombik** [comment]
Tested in testing session, worked as described.

We noticed that the error message can be improved if the JSON file does not contain a title for a competency. But sine the error handling seems to be part of another component and it is only displayed to admins right now it is out of scope for this PR.

**Review by florian-glombik — DISMISSED** [review]

**Review by BBesrour — APPROVED** [review]

**Review by egekurt123 — APPROVED** [review]
Code LGTM

**Review by pzdr7 — APPROVED** [review]
Reapprove

**Pull request merged**
