### PR TITLE
`Programming exercises`: Improve build triggers by instructors

### LINKED ISSUE #4463: Nullpointer Exception while Trigger All
### Describe the bug

We had to trigger all build plans, since we've updates some test cases.

I've marked it as high, since we need this feature if we have to adapt some test cases due to student responses.

What happened:
* Not all Builds have been triggered 
* Got this exception in the BE

```
2021-12-07 10:07:22.610 ERROR 12 --- [ artemis-task-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.triggerInstructorBuildForExercise(java.lang.Long) throws de.tum.in.www1.artemis.web.rest.errors.EntityNotFoundException

java.lang.NullPointerException: Cannot invoke "org.eclipse.jgit.lib.ObjectId.getName()" because the return value of "de.tum.in.www1.artemis.service.connectors.GitService.getLastCommitHash(de.tum.in.www1.artemis.domain.VcsRepositoryUrl)" is null
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.getLastCommitHashForParticipation(ProgrammingSubmissionService.java:368)
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.getOrCreateSubmissionWithLastCommitHashForParticipation(ProgrammingSubmissionService.java:359)
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.triggerBuildAndNotifyUser(ProgrammingSubmissionService.java:429)
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.triggerBuildForParticipations(ProgrammingSubmissionService.java:316)
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService.triggerInstructorBuildForExercise(ProgrammingSubmissionService.java:291)
        at de.tum.in.www1.artemis.service.programming.ProgrammingSubmissionService$$FastClassBySpringCGLIB$$fadb5611.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at tech.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

### To Reproduce

1. Trigger All for a Programming Task (Unclear what the internal state of all participations must be)

### Expected behavior

Trigger all should not fail. And should trigger all participations.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by krusche**
This PR simplifies the process in two ways:
1. Artemis only triggers builds for participation that already include at least one submission: It does not make sense that instructors can trigger student builds when they have not yet submitted something, in fact this could even confuse the student
2. The code does not try to retrieve the latest submission based on the commit hash any more so no failures in doing so cannot break the process. Instead it simply tries to get the last submission from the participation.

There are further changes needed in the web socket communication from server to client (it should be based on the participation entity, not on the submission entity, because triggering a build should not create submissions any more because a submission supports multiple results now), however this should be done in a follow up PR.

Fixes #4463

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise

1. Login as instructor and create the programming exercise
2. Start the exercise with at least 2 student accounts: at least 1 student should submit changes, at least 1 student should **not** submit anything
3. Login as instructors and open the participation page.
4. Trigger all builds and wait until they finish
5. Only the participations with at least one submission should be triggered and should receive a result

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by coaxial1** [comment]
I have tested this according to the steps above.

It works as described on TS1 (User with submission got a new build, user with started exercise, but no submission, did not build).

**However, on TS2, this triggered a build on both students** (even for the one without submission), and the submission count increased to "1" for that user, and he received a 0% result as well without doing anything himself.
You can check this on TS2 course ID 3816, exercise ID 9799.

The code changes themselves look good to me.

**Review by coaxial1 — APPROVED** [review]
I've tested this on TS1 (Bamboo) and TS2 (Gitlab) according to the steps above with success.

Your code changes look good to me as well.

**Review by dveljacic — APPROVED** [review]
Manually tested on TS1 with 4 different students: one with no submissions, one with exactly one submission, one with multiple submissions, and one with the submissions created in the online editor. After triggering all builds, the behavior is exactly as expected! ✅

**Review by VinnavanSembian — APPROVED** [review]
Tested in testing session with @Bofan-Zhu @lBruchmann @cremertim @Strohgelaender on ts1. Everything looks good to me and works fine!

**Review by lBruchmann — APPROVED** [review]
Tested on ts2. Tested together with @Strohgelaender, @Bofan-Zhu, @cremertim, and @VinnavanSembian. I followed the testing steps. The build triggers have been improved as described.

**Review by Strohgelaender — APPROVED** [review]
Tested in testing session on TS2 with @lBruchmann @VinnavanSembian @Bofan-Zhu @cremertim. Only the student who sumbitted changes got retested after pressing Trigger All, the other students did not produce any errors.

**Review by Bofan-Zhu — APPROVED** [review]
Tested on ts2 with @lBruchmann @Strohgelaender @VinnavanSembian @cremertim. Students with no submissions are not included in the build trigger. 👍

**Review by cremertim — APPROVED** [review]
tested on ts2 👍

**Pull request merged**
