### PR TITLE
`Communication`: Cleanup conversation after a course is deleted

### PR DESCRIPTION
**Pull request by TheZoker**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Currently when we remove a course, that has conversations, we don't remove those from the table. 

### Description

This PR adds logic to remove the conversation of a removed course and also a migration, that will delete conversations of none existing courses. 

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Since this PR introduces migration of deleting conversations of deleted courses, before running this branch or before deploying this PR delete a course with existing conversations and those conversations should include messages, replies and reactions. Then when you refresh the page you should get internal server error.
2. After you run this PR the database should be cleaned up and no internal server error should be displayed.
3. Then, Log in to Artemis
4. Create a course
5. Add conversations to that course
6. Delete the course
7. Look into the database, if the conversations have been removed

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by frederik-kt — APPROVED** [review]
Tested on TS2. Created a course, created a couple of direct messages in there, replied to them, and deleted the course. Reloading the page did not return any errors.

**Review by laadvo — APPROVED** [review]
Tested on ts2 during the testing session, no error appears when deleting a course with conversations. Working as expected

**Review by tobias-lippert — DISMISSED** [review]
Tested in testing session on ts2. No exception occurred after deleting a course with messages

**Review by krusche — APPROVED** [review]
code looks good 👍

**Pull request merged**
