### PR TITLE
Show indents on the text exercise result

### PR DESCRIPTION
**Pull request by MerlinMehmed**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Steps for Testing

1. Log in to Artemis as an instructor
2. Navigate to Course Administration
3. Create a text exercise
4. Log in as a student
5. Participate in the exercise including tabs and space
6. Log in as an instructor
7. Assess the exercise
8. Log in as student
9. See that the tabs and spaces are show in the same way as they were created

### Screenshots

Screenshot before this PR:
before

Screenshot after this PR:
now

### CODE REVIEW

**Review by real-dmy — APPROVED** [review]
Tested on TS1. Works as expected.

**Review by coolchock — APPROVED** [review]
looks good :+1:

**Review by SimonEntholzer — APPROVED** [review]
Works on TS2, code is fine too :+1:

**Review by ndricimrr — APPROVED** [review]
Works for me on TS2 👍

**Review by Malyuk-A — APPROVED** [review]
Looks good (TS2 & local)

**Review by NicolasUllmann — APPROVED** [review]
Tested on TS1. Everything worked as expected.

**Review by katjanakosic — APPROVED** [review]
Worked as expected on TS1 👍

**Review by iozbeyli — APPROVED** [review]
Code looks good

**Review by willergeorg — APPROVED** [review]
Tested on TS2. Worked for me.

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
