### PR TITLE
`Programming exercises`: Fix Jenkins builds by replacing all non-printable characters in JUnit-XMLs

### LINKED ISSUE #6149: Special Characters break Jenkins Notifications to Artemis
### Describe the bug

We encounter the same problem as in https://github.com/ls1intum/Artemis/pull/5780 for Java Tasks.

### To Reproduce

See https://github.com/ls1intum/Artemis/pull/5780

### Expected behavior

See https://github.com/ls1intum/Artemis/pull/5780

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

5.12.9

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Changes affecting Programming Exercises
~~- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).~~
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Closes #6149

### Description
In #5780 the same fix has been applied to only C exercises. This fix is now applied to all exercise types.

### Steps for Testing
Prerequisites:
- TS2 or local setup with Jenkins
- 1 Programming exercise

1. Add a test-case to the Tests-Repository of the exercise so that the failure message contains a non-printable character.
Example for Java:
```java
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class DummyTest {
    @Test
    void nonPrintable() {
        assertEquals("printable", "non-print\u007Fable");
    }
}
```
2. Artemis should receive a test result.
3. The feedback should contain `expected: <printable> but was: <non-print�able>`.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

### CODE REVIEW

**Review by dfuchss — APPROVED** [review]
Tested manually (by modifying Jenkinsfiles directly) Works as expected

**Comment by dfuchss** [comment]
@b-fein do you think it would be possible to escape the non printable character? 
otherwise, you might encounter texts like "expected XY but was XY" instead of "expected XY but was X[specialchar]Y"

**Comment by b-fein** [comment]
> do you think it would be possible to escape the non printable character?

It would be easy to replace all non-printable characters by the explicit fallback-symbol �.
Replacing them so something that still indicates which character was removed would be more tricky.

**Comment by dfuchss** [comment]
Maybe just something like `'s/[^[:print:]]/<NOT_PRINTABLE_CHAR>/g'`

**Review by dfuchss — APPROVED** [review]

**Review by PhilipWerz — DISMISSED** [review]
Everything works as expected. Feedback contains:
image

Tested on TS1.

**Review by dfuchss — APPROVED** [review]

**Review by timo07k — CHANGES_REQUESTED** [review]
Not working as expected: 

image

Tested on TS2.

**Comment by b-fein** [comment]
@timo07k Thanks for testing.
Looks like JUnit is able to replace this symbol by its HTML-entity-representation itself. Then the replacement will no longer be performed, which is okay since the XML can be parsed.

I updated the test case in the PR description to include a different one. For this one it should work now.

**Review by daniels98it — APPROVED** [review]
Tested and works as expected 👍

**Pull request merged**
