### PR TITLE
`Quiz exercises`: Simplify drag-and-drop image upload

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Follow-up of #5733 and #5427 to replace the file upload before entity persistence with a multipart file and entity upload.
Reimplementation after #6456 got reverted. After implementing the file service, the original issue got resolved.

### Description

The changes only affect the drag-and-drop section of the quizzes. But because the quiz editor allows creating all different types of quiz questions, I had to make the component saving the entity to retrieve the files from potential drag-and-drop question children and upload them together with the files.

It affects the Creation, Update, Re-evaluation and Import of quiz exercises. Additionally, it also affects the creation of drag-and-drop mode quizzes. However, those use the same creation endpoint.

### Steps for Testing

We need to fully test the quiz functionalities, including:
- Creation of a normal quiz
- Creation of a Drag and Drop Model Quiz
- Edit
- Import
- Reevaluation
- Adding existing questions (bottom of the editor) to a quiz exercise

During all of these five checks, it makes sense to work
- with and without dnd questions
- with and without background
- with and without picture drag and drop items
- with and without text drag and drop items
- with both drag and drop items
- with adding, removing, and replacing Drag Items and Questions to make sure the files get cleared up and not sent to the server
- try editing steps after a fresh reload as well as continuously editing and saving without a reload

Always check if the quiz gets rendered as expected.

#### Exam Mode Testing

Most of the changes are unrelated to the exam mode. I do not think testing is necessary to test the exam mode as extensively. However, it makes sense to just test the normal quiz exam workflow (creation and conduction) to be sure.

The only change that does require testing here is the import functionality of an existing exercise.

### Review Progress

I squashed all changes from #6456 that already got approved, so technically, it should be enough to review the rest.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| FileService.java | 87.0% |  |
| QuizExerciseImportService.java | 93.7% |  |
| QuizExerciseService.java | 97.7% | ✅ |
| ExamImportService.java | 95.5% |  |
| QuizExerciseResource.java | 93.6% | ✅ |
| quiz-exercise-generator.ts | 89.6% | |
| drag-and-drop-question-edit.component.ts | 91.6% | ✅ |
| quiz-exercise-detail.component.ts | 92.8% | ✅  |
| quiz-question-list-edit.component.ts | 94.8% | ✅  |
| quiz-question-list-edit-existing.component.ts | 98.9% | ✅  |
| re-evaluate-drag-and-drop-question.component.ts | 100% | ✅ |
| quiz-re-evaluate.component.ts | 86.1% |  |
| quiz-exercise.service.ts | 100% | ✅ |
| quiz-re-evaluate.service.ts | 100% | ✅ |
| file.service.ts | 63.0% | ✅ |

### Screenshots

Upload background before (before changes):
1409d1ba0c797661134ab989845ec831
Upload Background before (after changes):
e050fc2202937de46c2976423242c873

Upload background after (before changes):
80251aeeb77554f93832507fce51ee06
Upload background after (after changes):
3557ddaac548194325b3defb284e7f34

Upload picture drag item after (before changes):
593948ae5992864d34e4832ef35d9341
Upload picture drag item after (after changes):
f7deccf1b245d6010fb76aa3a1abbff3

### CODE REVIEW

**Review by pal03377 — DISMISSED** [review]
The DND quiz preview breaks for me with draggable image items. The video shows the current behavior on the left (`develop`, running locally) and the behavior with this PR on the right (on TS4). Note that the image already seems to break while dragging it.

https://github.com/ls1intum/Artemis/assets/9006596/b4e24dac-9d72-4161-b1a9-ed84f9f21b8e

**Review by Kroko-fant — CHANGES_REQUESTED** [review]
I tested uploading files a bit and was able to consistently reproduce a bug that occurs, when I edit a quiz, stay on the page.
1. Upload at least one file
2. Press "Save"
3. Try to delete **any** (could be the one you uploaded could be another file that previously was uploaded)

https://github.com/ls1intum/Artemis/assets/25010075/49656566-4901-4c59-aea5-cdd93f114861

**Comment by julian-christl** [comment]
@pal03377 Fixed the your first issue in d8d3e2283a7af05f1f106fa3003382fa4adc7338, the second in 052d639de5de68330330f0b1a16cf5ce25a1d9e0

@Kroko-fant Fixed in c211afd067288448466464218b934c653230de56

(not yet ready for a retest, need to fix something else first)

**Review by pal03377 — APPROVED** [review]
Tested on TS4. I tried using imports, re-editing and participating in the quiz. I could not find any issues 🎉

**Comment by egekurt123** [comment]
Tested in testing session - Multiple choice / Single choice and  "Fill in the blanks" exercises work as expected. 
Re-evalution works as expected.

**Review by egekurt123 — APPROVED** [review]
Tested in testing session - Multiple choice / Single choice and "Fill in the blanks" exercises work as expected.
Re-evalution works as expected.

**Review by milljoniaer — APPROVED** [review]
Tested in testing session, works as expected

**Review by Strohgelaender — APPROVED** [review]
tested on ts1, all previusly found issues are now resolved. code lgtm.

**Review by laadvo — APPROVED** [review]
Code looks good :+1:

**Review by Santia-go — APPROVED** [review]

**Pull request merged**
