### PR TITLE
[Bugfix] Add missing brace to Scores export button

### PR DESCRIPTION
**Pull request by JohannesStoehr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

Fixes one error from Sentry

### Description

Adds one missing brace

### Steps for Testing

1. Log in to Artemis
2. Go to the scores page of an exercise with participations
3. Export results and check for errors in the console

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Tested on TS1. No error occurred.

**Review by nicolasruscher — APPROVED** [review]

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 1. Everything worked as expected.

**Review by real-dmy — APPROVED** [review]
Tested on TS1. No error is shown.

**Review by FuchsDominik — APPROVED** [review]

**Review by FrankeLukas — APPROVED** [review]
Thanks for the quick fix.

**Review by DanielKainz — APPROVED** [review]
Tested on TS1. No error occurred.

**Review by jhainzlschmid — APPROVED** [review]
Tested on TestServer 1. There was no error in the console

**Review by cremertim — APPROVED** [review]
tested on ts1

**Review by katjanakosic — APPROVED** [review]
Tested on TS1. No errors.

**Review by canyelten — APPROVED** [review]
Tested on TS2. No error occurred.

**Review by ArtemTsurikov — APPROVED** [review]
Tested on TS1, no errors.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. No errors.

**Review by sinangunduz — APPROVED** [review]
tested on ts3

**Review by nicolasruscher — APPROVED** [review]

**Review by SimonEntholzer — APPROVED** [review]

**Review by ivohashamov — APPROVED** [review]

**Pull request merged**
