### PR TITLE
Add websocket broker health indicator

### PR DESCRIPTION
**Pull request by sleiss**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
This PR adds a health indicator for the status of the connection from the server to the broker.
The broker is needed if Artemis is running on multiple instances (see https://artemis-platform.readthedocs.io/en/latest/dev/setup/distributed/#websockets), but is currently not included in the Health status (and thus, not in the monitoring tools).

### Description
This PR adds a health indicator that is based on the [BrokerAvailabilityEvent](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/messaging/simp/broker/BrokerAvailabilityEvent.html).
It is fired if the state of the broker changes, i.e. if the broker gets available or unavailable.
The current status is stored in the WebsocketBrokerHealthIndicator and will be sent to the client, along with the IP address(es) of the broker(s) used.

### Steps for Testing
Please test the PR both on one of TS1/TS2 and one of TS3/TS5.

1. Log in to Artemis with an admin account
2. Navigate to Server Administration > Health
3. Make sure that the new "Websocket Broker" status is added.
4. Click on the "eye" to see the ip-addresses: It should be empty on TS3 and TS5 and should contain one entry on TS1 and TS2.

### Screenshots
Peek 2021-01-03 16-42

### CODE REVIEW

**Review by airelawaleria — COMMENTED** [review]
Tested on ts1 and ts2. Both of them contain exactly ONE entry. 
image

**Review by simonzilker — COMMENTED** [review]
tested with @airelawaleria and @marvinchimeka.
On ts1 there is still one entry!

**Review by marvinchimeka — COMMENTED** [review]
There is still one entry on ts1. Can confirm reviewers statement.

**Review by JohannesWeiss — COMMENTED** [review]
Can confirm the aforementioned issue.

**Comment by sleiss** [comment]
@airelawaleria @JohannesWeiss @simonzilker @marvinchimeka 
Thanks for the fast review!
Actually, I messed something up :sweat_smile: As TS1 is also using a broker, the entry is expected there.
TS3 and TS5 should not have this entry.

I'll update the testing steps. Sorry for the confusion!

**Review by airelawaleria — APPROVED** [review]
Re-approve

**Review by JohannesWeiss — APPROVED** [review]
Since the previous issue isn't one, approve!

**Review by simonzilker — APPROVED** [review]
re-approve

**Review by marvinchimeka — APPROVED** [review]
re-approve

**Review by krusche — APPROVED** [review]

**Pull request merged**
