### PR TITLE
`Development`: Add tests for correct setting of variables in tutor leaderboard

### PR DESCRIPTION
**Pull request by valentin-boehm**
#### General

- [x] This is a small issue that I tested locally.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

This is a follow up on https://github.com/ls1intum/Artemis/pull/7144
I added tests to make sure the bug does not happen again.

### Description

I added two test cases:
- For tutor-leaderboard: A new test case ensures that all variables are set correctly if `exercise` is an exam exercise.
- For account-service: A new test case ensure that the access rights are set correctly for exam exercises and their referenced course.

### CODE REVIEW

**Review by reschandreas — APPROVED** [review]
tests all pass, LGTM

**Review by jakubriegel — APPROVED** [review]
LGTM

**Review by rstief — APPROVED** [review]
Tests pass, code LGTM

**Review by RY997 — APPROVED** [review]
New tests lgtm

**Pull request merged**
