### PR TITLE
`Programming exercises`: Fix display of empty git diffs

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
If the template and solution repositories contain the same contents, the diff-view did not work correctly.

### Description
We now handle the case if the server does not return any diff entries in the client. We show +-0 and 2 squares, opening the diff view will lead to an empty window.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Programming Exercise

1. Setup the exercise in such a way that template and solution repositories contain the same code
2. Navigate to the exercise detail view
3. Check that +-0 is displayed as the diff and the the page still works correctly.
4. Verify that no errors are in the console.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
old:

grafik

now: 
grafik

### CODE REVIEW

**Review by reschandreas — APPROVED** [review]
tested locally, works as expected.
One thought, wouldn't it make sense to not show the 'Show' button if there is no difference?

**Review by milljoniaer — APPROVED** [review]
Code LGTM

**Review by reschandreas — APPROVED** [review]
LGTM

**Review by Hialus — APPROVED** [review]
Changes look good. Thanks for fixing this 🚀

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts2. Worked as expected also show button not displayed when difference 0.

**Pull request merged**
