### PR TITLE
`Development`: Improve and simplify scss imports

### PR DESCRIPTION
**Pull request by krusche**
This fixes user interface issues such as input fields suddenly having a grey background or text getting bold
(both happens after entering the modeling editor)

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation and Context
The SCSS imports are causing issues, in particular when all bootstrap styles are imported again in a component. In the future, we should find a better way and create some guidelines how to use SCSS imports properly.

### Description
This PR tries to restructure some aspects of the SCSS imports and solves two problems, that currently happen when you enter the modeling submission page:
1) suddenly some fonts become bold
2) The input fields (e.g. when creating a course or an exercise) get a grey background

### Steps for Testing
We basically should test all pages for visual differences in styling (font, size, position) and make sure nothing is broken

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
no changes

### Screenshots
no changes

### CODE REVIEW

**Review by Olimbia23 — COMMENTED** [review]
Nice work @krusche!
I tested it on TS1 and noticed one issue with the font in Course Management.
Apart from that everything seems to be working fine.

Before:


After:

**Comment by krusche** [comment]
@Olimbia23 thanks for fixing the font issue

**Review by ole-ve — CHANGES_REQUESTED** [review]
For Students Pages, the font-weight is overridden by a value of 300 by the global.scss file for almost every text field.

Correct would be:
Bildschirmfoto 2021-11-04 um 16 14 55

Actually is:
Bildschirmfoto 2021-11-04 um 16 14 51

**Review by Hialus — CHANGES_REQUESTED** [review]
There seems to be a small style change on the Submissions Page of an Exercise.
This page can be reached by going to the Assessment Dashboard and then pressing the "Submissions" button for any exercise.
In the header of this page the text of the "Show all" and "Show locked" checkboxes is smaller than before.
Before:
grafik
In this PR:
grafik

Obviously this is not a big issue, but I just wanted to mention it.

Edit:
The same goes for some other checkboxes. I could also see the same thing of the notifications settings page.
Before:
grafik
In this PR:
grafik

**Review by MDK5 — DISMISSED** [review]
Tested in testing session on ts1 with focus on exams, could not find any further issues.

**Review by lschlesinger — CHANGES_REQUESTED** [review]
I tested instructor pages, such as assessment dashboard, exercise management, lecture management, statistics, grading, login, and all METIS related functionality.
I found one issue, it's related to the assessment instructions buttons and appears when creating new exercises (text and modeling):
As it is:
image

As it should be:
image

Besides, the interface when adding a file as lecture unit looks a bit off. but this does not seem to be specifically related to the changes in this PR. However, I wonder if the gray input background could be removed here as well:
image

**Review by MDK5 — APPROVED** [review]
Re-Reviewed all noted problems, they are all solved now :+1:

**Review by Hialus — APPROVED** [review]
Retested on TS1.
The mentioned problems are solved now and I also couldn't find another one.
Well done @Olimbia23 👍🏻

**Review by MerlinMehmed — APPROVED** [review]
Checked the pages under the Server Administration and the Course Overview menus. Everything looks fine and I didn't find issues

**Pull request merged**
