### PR TITLE
Bugfixes: re-evaluate mc-quiz 2

### PR DESCRIPTION
**Pull request by filip-gregurevic**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

Follow-up PR to https://github.com/ls1intum/Artemis/pull/1515
After saving changes and changing thing again 'pending changes' isn't shown and therefore the later changes can't be saved.

### Description

Use lodash to clone objects in order to prevent references being assigned.
(And also delete an empty file)

### Steps for Testing

1. Log in to Artemis
2. Create a mc-quiz which is ready to re-evaluate.
3a. Change the text (or an answer option)
3b. 'pending changes' is shown
3c. save your changes
3d. 'pending changes' isn't shwon
4a. Change the text (or an answer option)
4b. 'pending changes' is shown
4c. save your changes
4d. 'pending changes' isn't shwon
(optional: repeat 4a-4d until bored or convinced you can save changes as often as you want)

### CODE REVIEW

**Comment by Varnika-Tyagi** [comment]
_Log in to Artemis
Create a mc-quiz which is ready to re-evaluate.
3a. Change the text (or an answer option)
3b. 'pending changes' is shown
3c. save your changes
3d. 'pending changes' isn't shown_
Works fine upto here.
_4a. Change the text (or an answer option)
4b. 'pending changes' is shown_ --> As of yet, I have to manually refresh the page and change the text again to see 'Unsaved Changes' in the quiz
Need to refresh the page to see further unsaved chages

**Comment by filip-gregurevic** [comment]
> _Log in to Artemis Create a mc-quiz which is ready to re-evaluate. 3a. Change the text (or an answer option) 3b. 'pending changes' is shown 3c. save your changes 3d. 'pending changes' isn't shown_
> Works fine upto here.
> _4a. Change the text (or an answer option) 4b. 'pending changes' is shown_ --> As of yet, I have to manually refresh the page and change the text again to see 'Unsaved Changes' in the quiz
> Need to refresh the page to see further unsaved chages

@Varnika-Tyagi where did you test it? I think the version containing the solution is not yet deployed to a test server

**Comment by Varnika-Tyagi** [comment]
Ah, I'm using the test server 1 ( https://artemistest.ase.in.tum.de) for testing.

**Comment by filip-gregurevic** [comment]
> Ah, I'm using the test server 1 ( https://artemistest.ase.in.tum.de) for testing.

@Varnika-Tyagi it should be deployed there now

**Comment by Varnika-Tyagi** [comment]
Works as expected. Well done!
PR1551works

**Comment by filip-gregurevic** [comment]
> One (probably unrelated) thing I noticed was, that changes which contain Case changes (e.g. changing quiz title from Test to TEST) are not recognized as changes. Do you know whether this is desired?

As it was implemented like that before, I assume that it is desired behaviour. @krusche should I change it to be case-sensitive?

**Comment by filip-gregurevic** [comment]
@tessaRuckstuhl @krusche it is case-sensitive now, since I think it makes more sense

**Comment by filip-gregurevic** [comment]
> Works as described, new changes can always be saved.
> 
> But I ran into a strange issue how changes are detected if you make a small change (e.g. add a letter) and then undo that change again (delete or undo command). One would expect it to show "Saved!", but it depends on some other factors:
> 
> * In the first answer text area of each MC quiz question, it works as expected.
> * In the question text area and other answer text areas, it does not work, it only shows "Unsaved Changes", even after that undo.
> * However, as soon as I save this no-change once, this text area becomes "immune" to the bug from then on, as long as I don't go back or reload the page. The other text areas don't change.
> 
> _Note: It behaves exactly the same and in a reproducible way both in Chrome and Firefox._
> 
> My first guess would be that `backupQuiz` does not get loaded correctly when the re-evaluate is opened and the JSON-Strings differ in some way, but I am not experienced with TS.
> 
> I assume this bug is out of scope here and requires a new PR, since the main goal to allow saving changes works. Is that correct? I would then approve this PR.

@MaisiKoleni Thanks for testing.
Yes I've encountered the issue myself, too, but I will address it in a follow-up PR, since this one's goal is to make changes savable which is quite an important functionality.

**Pull request merged**
