### PR TITLE
`Development`: Refactor course score CSV export

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
The course scores component had huge methods and was not very understandable.

### Description
Splits up the large methods into smaller ones where it makes sense to make the code more readable. Also reduces duplication by extracting some common functionality when putting values into the rows into their own class. 

### Steps for Testing
Prerequisites:
- 1 Instructor
- Some course with a few exercises and some student submissions.

1. Export and download the course scores CSV file (reachable via the Course Management → turquoise ‘Scores’ button) **before** deploying this PR to a test server.
2. After deployment, download the CSV file again for the same course. It should be identical (or no longer be broken as for example for Georg Willer’s test course on TS1). 

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| File | Branch | Statement |
| --- | --- | --- |
| `course-scores.component.ts` | 73.6% | 94.2% | 
| `course-scores-csv-row-builder.ts` | 100% | 100% |

### Screenshots
n/a

### CODE REVIEW

**Comment by coaxial1** [comment]
I've got a line containing "undefined" in my export. Is that somehow expected or normal?
grafik

**Comment by b-fein** [comment]
> I've got a line containing "undefined" in my export. Is that somehow expected or normal? 

Thanks, that was a bug that should now be fixed with 2830744.

**Review by willergeorg — COMMENTED** [review]
Tested on TS1. Thanks for fixing the CSV output of my course, tho. I do have a question since I'm not completely sure about it. The CSV output does not contain the points itemized by exercise types any more as it is the case in the table on Artemis. Is this intended? I had a very brief look over your code and it seems to me that you are trying to include these information in the file.
image
image

**Comment by b-fein** [comment]
@willergeorg @dveljacic Thanks for testing!
The component determined the exercises which should be included before some additional data was fetched from the server. Therefore, depending on how quick the server responded they were indeed missing from the output. This has now been fixed in c0a01c1.

**Review by willergeorg — COMMENTED** [review]
I think now you are including every single exercise as well:
image

**Comment by b-fein** [comment]
> I think now you are including every single exercise as well.

@willergeorg That is the intended behaviour. It works like that on our production system as well. There is a column for each exercise, and then for each exercise type there are two columns (points, score) with some aggregated data.

**Review by willergeorg — APPROVED** [review]
Given that the bar per exercise is intended, functionality approved.

**Review by coaxial1 — DISMISSED** [review]
Works for me and code looks good as well :)

**Review by Strohgelaender — CHANGES_REQUESTED** [review]
Tested on TS1.
When comparing the old csv with the new csv file, we found one exercise where the values changed. The 0. in front is missing and a whole integer was exported instead. 
grafik

This is not excel doing some weird formatting, the issue is present in the files as well:
grafik

**Review by lBruchmann — COMMENTED** [review]
Tested on ts1. Tested together with @Strohgelaender, @VinnavanSembian, and @mallgaier. For some remarks @Strohgelaender.

**Review by mallgaier — COMMENTED** [review]
Tested together with @Strohgelaender, @VinnavanSembian, and @lBruchmann .  @Strohgelaender summarised the issues.

**Comment by b-fein** [comment]
@Strohgelaender @VinnavanSembian @mallgaier @lBruchmann Good catch!

In commit 608c8fb4cd0678453dc3cc82a4e51787ea97acc0 I switched to the correct rounding function and improved the tests to test the changed value.
In commit a09f05a0396315ebafbf57f92196276f89684da2 I then renamed the rounding utility function to a name that actually reflects how it should be used to make it less likely to use the wrong one in the future.

**Review by baranimo7 — DISMISSED** [review]
tested on ts2 and I did not notice a problem

**Review by coaxial1 — DISMISSED** [review]

**Review by mallgaier — APPROVED** [review]

**Review by mallgaier — APPROVED** [review]
Tested again with Georg Willers Test Course on TS1.
The two .csv are identical, the issue described by @Strohgelaender is resolved.

**Review by dveljacic — APPROVED** [review]
Manually tested on TS2. Confirming that all problems from the previous reviews are fixed now. Nice job! ✅

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on TS2 with different scores, everything works as expected

**Pull request merged**
