### PR TITLE
`Development`: Update server dependencies

### PR DESCRIPTION
**Pull request by krusche**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
* Keep server dependencies up to date
* I simplified some server services dependencies

### Steps for Testing
1. Test the most important functionality, including cache synchronization over Hazelcast (e.g. participate in some quizzes)

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by lBruchmann — CHANGES_REQUESTED** [review]
Tested together with @mallgaier, @Strohgelaender, and @cremertim  during testing session. Tested on ts3. Can not open the statistics tab in courses.

Steps for reproduction:
1. Go to the artemis Course Overview.
2. Open a course.
3. Click on the statistics button.

Screenshot from 2021-11-23 17-23-36

We're not sure if this issue is related to this PR, but it does at least occur on a test server with these changes.

**Review by mallgaier — APPROVED** [review]
Successfully tested together with @lBruchmann ,@Strohgelaender and @cremertim :
- Assigning different roles to a user
- Create and delete exercises (text / quizzes, ect)
- Submit exercises as student / review grading of an exercise
- Grade exercises as tutors

**Review by Strohgelaender — CHANGES_REQUESTED** [review]
tested in testing session, can confirm the comments of @lBruchmann and @mallgaier. We noticed that the statistics error is already present in the develop-branch, so the bug is most probably caused by #4313. Nevertheless, it should be addressed before the next version gets released.

**Review by Strohgelaender — APPROVED** [review]
Re-Approve since the found bug will be fixed with #4363. Apart from that, we could not find any issues.

**Pull request merged**
