### PR TITLE
`Iris`: Remove code duplication in Iris session resources

### PR DESCRIPTION
**Pull request by Hialus**
> [!WARNING]
> Only testable on TS9 and Staging

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

After the code editor feature was merged the new `IrisCodeEditorSessionResource` duplicated a lot of code from the `IrisChatSessionResource`. We want to refactor this to be more maintainable.

### Description

I added an abstract super class `IrisExerciseChatBasedSessionResource`, which is implemented by both resources. It bundles the common logic of both resources by providing methods with the parameters to handle the differences of the resources.
@coderabbitai ignore

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Go to a programming exercise with Iris enabled (e.g. Iris Demo Course -> Binary Sort)
3. Send a message to Iris -> Response comes back
4. Go to the instructor view of the exercise
5. Go to the code editor
6. Send a message to Iris and run all the plans -> Also works as before

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [IrisCombinedChatSubSettingsDTO.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5959/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.dto.iris/IrisCombinedChatSubSettingsDTO.html) | 100% | ✅ |
| [IrisCombinedCodeEditorSubSettingsDTO.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5959/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.dto.iris/IrisCombinedCodeEditorSubSettingsDTO.html) | 100% | ✅ |
| [IrisCombinedHestiaSubSettingsDTO.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5959/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.dto.iris/IrisCombinedHestiaSubSettingsDTO.html) | 100% | ✅ |
| [IrisChatSessionResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5959/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.iris/IrisChatSessionResource.html) | 92% | ✅ |
| [IrisCodeEditorSessionResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5959/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.iris/IrisCodeEditorSessionResource.html) | 93% | ✅ |
| [IrisExerciseChatBasedSessionResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5959/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.iris/IrisExerciseChatBasedSessionResource.html) | 96% | ✅ |

### CODE REVIEW

**Review by konrad2002 — APPROVED** [review]
manually tested on TS9, works as expected

**Review by MaximilianAnzinger — APPROVED** [review]
Code

**Review by MaximilianJG — APPROVED** [review]
Manually tested on ts9. Works as expected

**Review by rstief — APPROVED** [review]
Code looks good 👍

**Review by xHadie — DISMISSED** [review]
_Manually tested on TS9_
Works as expected

**Pull request merged**
