### PR TITLE
`Development`: Migrate suspicious behavior module to new client coding guidelines

### PR DESCRIPTION
**Pull request by coolchock**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Description

This pull request migrates suspicious behavior module to signals, inject and standalone.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam with exercise groups and exercises

1. Log in to Artemis
2. Navigate to Course Administration -> Exams -> Selected Exam -> Suspicious Behavior
3. Verify that all data is displayed properly and buttons work

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Release Notes

- **New Features**
  - Enhanced the plagiarism cases overview component with improved data retrieval methods.
  - Updated the suspicious sessions component to streamline data handling through function calls.
  - Declared `SuspiciousSessionsOverviewComponent` as a standalone component, enhancing its modularity.

- **Bug Fixes**
  - Resolved issues related to direct property access in templates, improving data fetching consistency.

- **Refactor**
  - Transitioned to a more functional approach for input properties and dependency injections across components and services, enhancing code readability and maintainability.
  - Simplified component structure by removing unnecessary constructors and utilizing direct property assignments for dependency injection.

- **Chores**
  - Removed several components from the exam management module, streamlining functionality related to suspicious behavior monitoring.

- **Tests**
  - Updated test suites for components to use structured input setting methods, standardizing test initialization processes.

### CODE REVIEW

**Review by BBesrour — APPROVED** [review]
code lgtm

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Data are displayed correctly and all buttons work

Screenshot 2024-11-29 000652

**Review by sawys777 — APPROVED** [review]
Tested on TS1, the buttons and features in suspicious behaviour are correctly displayed.

**Review by kevinfischer4 — APPROVED** [review]
Tested on TS2, all informations are displayed correctly.
image

**Review by SimonEntholzer — APPROVED** [review]
Code

**Review by EneaGore — APPROVED** [review]
code

**Review by Malekos74 — APPROVED** [review]
### Tested on server 2
Works as expected, all buttons are working.

**Review by SimonEntholzer — APPROVED** [review]
Works on Ts2

**Review by BBesrour — APPROVED** [review]
Tested on TS2, lgtm

**Review by muradium — APPROVED** [review]
Tested on TS2, works as expect

**Review by sawys777 — APPROVED** [review]
Tested on TS3, reapprove

**Review by HawKhiem — APPROVED** [review]
Tested on TS3, reapprove

**Review by sachmii — APPROVED** [review]
Tested on TS5, everything works fine.

**Pull request merged**
