### PR TITLE
`Development`: Add documentation for benchmarking tool

### PR DESCRIPTION
**Pull request by valentin-boehm**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

The main documentation of the Benchmarking Tool is available in its README. To make sure that Artemis admins find the tool, I added a short section about it to the Artemis docs. The goal of this section is simply to give a short overview about the tool and then link to its Readme for more information.

### Description
I added a section called "Benchmarking Tool" to the Administration Guide. It gives a short summary about the tool's core functionality and then links to the repo.

### Steps for Testing

 Take a look at the new section in the docs: https://artemis-platform--8047.org.readthedocs.build/en/8047/admin/benchmarking-tool.html

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **Documentation**
    - Updated the documentation with a new entry for the Artemis Benchmarking Tool, a web application for administrators to assess system performance under heavy loads and optimize Artemis for exam scenarios.
    - Added a new entry `admin/benchmarking-tool` to the list of exercises in the documentation.

### CODE REVIEW

**Review by Strohgelaender — DISMISSED** [review]

**Review by georgyia — DISMISSED** [review]
well-written! lgtm

**Review by nata-81 — DISMISSED** [review]
The documentation explains the benchmarking process well. I ran the text through a language tool and checked it with Grammarly, and there were some minor mistakes. You can decide which ones you want to correct.
image
This is the corrected text: 
The Artemis Benchmarking Tool is a web application designed for Artemis administrators to test the performance of Artemis under heavy load. It is available on [GitHub](https://github.com/ls1intum/Artemis-Benchmarking).

The Benchmarking Tool for Artemis is designed to simulate realistic user interactions with the Artemis platform, particularly focusing on exam conduction where the system’s performance and scalability are most critical.

This tool enables system administrators and developers to assess and analyze Artemis’s behavior under simulated load conditions, providing valuable insights into response times, system workload, and overall stability. These insights can be used to identify the limits of the hardware infrastructure as well as the software architecture, thereby allowing for targeted optimizations and improvements. The main goal is to ensure that the respective Artemis setup can handle the expected load during exams without any performance issues.

During an exam simulation, the tool participates in the exam on behalf of a configurable number of students. It performs various actions, such as logging in, starting the exam, submitting answers, and performing git operations. For each action, the tool measures the time it takes to complete the action and records the result. Additionally, the tool can be connected to Prometheus to collect and visualize workload metrics.

For more information on how to set up and use the Benchmarking Tool, please refer to the [README](https://github.com/ls1intum/Artemis-Benchmarking?tab=readme-ov-file#artemis-benchmarking-tool).

**Review by bensofficial — APPROVED** [review]

**Review by Predixx — APPROVED** [review]
Grammar wise it is well written and for me it's understandable. LGTM!

**Review by nata-81 — APPROVED** [review]
Re approve

**Review by AntonGeTUM — APPROVED** [review]
Documentation lgtm

**Pull request merged**
