### PR TITLE
`Development`: Fix server build

### PR DESCRIPTION
**Pull request by DominikRemo**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

The builds on bamboo currently do net succeed.

### Description

Added parameter to constructor call. The build should now succeed.

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2

### CODE REVIEW

**Review by laadvo — APPROVED** [review]
Code looks good, nice quick fix!

**Review by lennart-keller — APPROVED** [review]
Code looks code. Thank you for the quick fix!

**Review by terlan98 — APPROVED** [review]
Code LGTM. Thanks for the fix 👍

**Review by tobias-lippert — APPROVED** [review]
LGTM

**Pull request merged**
