### PR TITLE
`Programming exercises`: Fix inconsistencies between diff viewer and diff line stats

### LINKED ISSUE #9928: `Programming Exercise`: Git diff between template and solution shows incorrect number of changes
### Describe the bug

For some files, the calculated numbers of additions and deletions are incorrect displayed.

### To Reproduce

1. Go to a programming exercise edit page 
2. Click on 'Review Changes' in the Template/Solution Comparison section
3. Look for a file where the calculated number of additions and deletions is incorrect

### Expected behavior

The number of added and deleted lines of code between the template and the solution submission should be correct.

### Screenshots

image

### Which version of Artemis are you seeing the problem on?

7.7.3

### What browsers are you seeing the problem on?

Chrome, Safari

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by magaupp**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

The Monaco Editor ignores leading and trailing whitespace while computing the diff (see [ignoreTrimWhitespace](https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.IStandaloneDiffEditorConstructionOptions.html#ignoreTrimWhitespace)).
The displayed counts of added and removed lines are provided by the server.
The server-side diff does not ignore whitespace like the Monaco Editor.

The git-diff output allows its hunk headers to be annotated with the containing function if the `diff` attribute is set accordingly (see [custom hunk headers](https://git-scm.com/docs/gitattributes#_defining_a_custom_hunk_header)).
Such blocks are not handled correctly by the server parser and are ignored.

### Description

The GitDiffReportParserService is modified to optionally ignore diffs where the lines only differ in leading and trailing whitespace.
This option to ignore whitespace is enabled where the diff is used together with the diff viewer.
Hunk headers are handled correctly.

Closes #9928.

### Steps for Testing

1. Create a Java programming exercise
2. Upload files to the template and solution repositories where the only differences in indentation
3. Upload files with the appropriate file extensions to the template and solution repositories where the only difference is a line 10 lines below the start of its containing function
4. Wait until the builds finish
5. Click on "Review Changes"
6. Verify that the indentation differences are not shown
7. Verify that the shown differences are consistent with the displayed line counts
8. Verify that the change deep within the function is shown

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| CommitHistoryService.java | 85% | ✅ |
| ProgrammingExerciseGitDiffReportService.java | 81% | ✅ |
| GitDiffReportParserService.java | 88% | ✅ |

## Summary by CodeRabbit

- **New Features**
	- Enhanced git diff processing to include whitespace changes.
	- New test method added to validate report handling for whitespace-only differences.

- **Bug Fixes**
	- Improved assertions in integration tests to validate report properties and entries.

- **Refactor**
	- Method signatures updated for clarity and consistency across services.

- **Chores**
	- Organizational change for test class package structure.

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]
Works on Ts1

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Works as described

**Review by sachmii — APPROVED** [review]
Tested on TS1, line stats are consistent.

**Review by eceeeren — APPROVED** [review]
Works in TS6, works as expected!

**Just as a side note:** I would prefer if you could create testing steps a bit more detailed and maybe add screenshots :) I think not everyone knows where every button is placed in the application. For example, for a long time, I searched for the "Review Changes" button. It also could be nice to see the expected output. Just a friendly request :)

**Review by sawys777 — APPROVED** [review]
Tested on TS5, everything works fine.

**Review by alekspetrov9e — APPROVED** [review]
Tested on TS2.  Indentation differences are not shown and the shown differences are consistent with the displayed line counts. Works as expected.

**Review by AjayvirS — APPROVED** [review]
code

**Review by coolchock — APPROVED** [review]
code

**Review by krusche — APPROVED** [review]

**Pull request merged**
