### PR TITLE
`Learning analytics`: Fix a rendering issue when displaying competency relations

### PR DESCRIPTION
**Pull request by danielbode**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

Currently there is a bug when trying to render edges in the ngx-graph component to display competency relations.

### Description

This is a known bug of ngx-graph in combination with angular 15. There are already two GitHub issues in the ngx-graph repository that are not yet resolved (https://github.com/swimlane/ngx-graph/issues/481, https://github.com/swimlane/ngx-graph/issues/487).
To fix this bug for Artemis I applied the workaround to revert the peer dependency of ngx-graph to an old version of d3-transition (d3-transition v.1.1.3) suggested here: https://github.com/swimlane/ngx-graph/issues/481#issuecomment-1431557376
Changing to d3-transition v3.0.0 or an older ngx-graph version did not fix the issue.

### Steps for Testing

Prerequisites:
- 1 Admin (The feature is not yet visible to instructors)

1. Log in to Artemis
2. Navigate to Course Administration
3. Select a course
4. Click on competencies
5. Create at least two competencies and create a relation between them
6. Make sure the edge between the relations gets displayed correctly and there are no errors in the console

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

Screenshot of the bug:
Bildschirm­foto 2023-03-30 um 12 33 33
Screenshot after the bugfix:
Bildschirm­foto 2023-03-30 um 12 37 12

### CODE REVIEW

**Review by TheZoker — APPROVED** [review]
Tested on TS1 and works as expected 👍

**Comment by krusche** [comment]
We cannot merge this, because the old d3 packages contain security issues

**Comment by krusche** [comment]
we need to find another workaround or live with the issue for now

**Comment by danielbode** [comment]
> we need to find another workaround or live with the issue for now

I already tested all the other workarounds I found online or could think of. I guess we have to live with the issue for now and wait for a new version of ngx-graph.

**Pull request closed without merging**
