### PR TITLE
`Communication`: Fix visibility of create channel option for students

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Students currently see the "Create Channel" button despite lacking the permission to create channel, leading to confusion and errors. (Closes [#9969](https://github.com/ls1intum/Artemis/issues/9969))

### Description

The visibility of the "Create Channel" button was fixed using the `canCreateChannel` variable to ensure it only appears for users with the necessary permissions.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Course with Communication enabled

1. Log in to Artemis (as an Instructor)
2. Navigate to Communication section of a course
3. As an Instructor, click on the "+" button in the sidebar and verify that the "Create Channel" option is visible.
4. Log out and log in as a Student.
5. Click on the "+" button in the sidebar and verify that the "Create Channel" option is not visible.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [X] Code Review 1
- [X] Code Review 2
#### Manual Tests
- [X] Test 1
- [X] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| course-conversations.component.ts | 90.76% | ✅ ❌ |
| sidebar.ts | not found (modified) | ❌ |

## Summary by CodeRabbit

- **New Features**
	- Added functionality to determine if users can create a channel, enhancing sidebar data.
	- Conditional rendering for the "Create Channel" button based on user permissions.
  
- **Bug Fixes**
	- Updated tests to verify the visibility of the "Create Channel" button according to permissions.

- **Documentation**
	- Updated the `SidebarData` interface to include a new optional property for channel creation permissions.

### CODE REVIEW

**Review by eylulnc — APPROVED** [review]
Tested in TS5. Works as expected. Created channel not visible yo user.

**Review by anian03 — APPROVED** [review]
Tested on TS5, works as expected. Thanks for the quick fix!

**Review by julian-wls — APPROVED** [review]
Tested on TS5, works as expected!

**Review by FelberMartin — APPROVED** [review]
Tested on TS5, works as described

**Review by HawKhiem — APPROVED** [review]
Tested on TS5. I could indeed create channel as an instructor and/or a tutor and not as a student

image

image

**Pull request merged**
