### PR TITLE
`Development`: Adds playwright e2e quiz exercise tests for different batch modes

### PR DESCRIPTION
**Pull request by muradium**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
We want to test quiz exercise participation in different batch modes and time schedules.

### Description
Adds E2E tests in Playwright for following types of exercises:
- Quiz exercise with specified working time start date
- Batched quiz exercises
- Individual quiz exercises

### Steps for Testing
- **Code Review**: Ensure that tests pass for valid reasons, functionality is adequately tested and check the code quality.
- **Run the tests (optional)**: Tests are checked by automatic run in CI environment. You can optionally run them locally and check if they pass.

**Steps for running the tests:**
1. Navigate to **src/tests/playwright**
2. Configure Playwright using playwright.env file based on your local setup. Current configuration should work for default Artemis setup.
3. Run `npm install && npm run playwright:setup`
4. Run tests with following commands and confirm that they pass:
- `npx playwright test e2e/exercise/quiz-exercise/QuizExerciseParticipation.spec.ts -g "Quiz exercise scheduled participation"`
- `npx playwright test e2e/exercise/quiz-exercise/QuizExerciseParticipation.spec.ts -g "Quiz exercise batched participation"`
- `npx playwright test e2e/exercise/quiz-exercise/QuizExerciseParticipation.spec.ts -g "Quiz exercise individual participation"`

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by rstief — APPROVED** [review]
Demonstrated in testing session, code also LGTM

**Review by BBesrour — APPROVED** [review]
Demonstrated in testing session.

**Review by coolchock — APPROVED** [review]
demonstrated in the testing session, LGTM

**Review by marlon-luca-bu — APPROVED** [review]
Changes look good to me

**Review by sarpsahinalp — APPROVED** [review]
Code lgtm

**Review by az108 — APPROVED** [review]
test cases LGTM👍

**Review by BBesrour — APPROVED** [review]
re-approve

**Review by rstief — APPROVED** [review]
Code changes lgtm

**Pull request merged**
