### PR TITLE
`General`: Always show editor buttons for modeling, text and file upload exercises

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

It is confusing for students when some buttons of exercises are shown in the exercise overview, while others are only shown in the exercise details view. These buttons are the ones showing the submission/result after submissions are done.

### Description

This PR refactors the student actions to always show the submission/result button.
Additionally the modeling, text and file upload buttons are merged, since they share the same behavior.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Tutor
- 2 Text/Modeling/File upload exercises (one with due date, one without)

1. Log in to Artemis
2. Create the exercises and participate as a student
3. You should be able to open the editor as long as you can submit (before due date or no due date and no result yet)
4. You should see "View submission" when you cannot participate any more but did not receive an assessment yet
5. You should see "View result" once you received an assessment

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| exercise-details-student-actions.component.ts | 86% | ✅ |

### CODE REVIEW

**Review by DominikRemo — DISMISSED** [review]
Code LGTM

**Review by julian-christl — DISMISSED** [review]
I like the code changes, especially the refactoring of the actions component simplifying the template.

**Comment by FreshLlamanade** [comment]
Tested on TS3, LGTM

**Review by laadvo — DISMISSED** [review]
Tested on ts1, the buttons are shown in exercise overview, as well as exercise details view and work as expected.
image

**Review by DominikRemo — APPROVED** [review]
Reapprove

**Review by laadvo — APPROVED** [review]
Re-tested on ts1, still working as expected

**Review by julian-christl — APPROVED** [review]
Reapprove code

**Review by greekgeek1 — APPROVED** [review]
Tested on ts3. Worked as expected.

**Review by RY997 — APPROVED** [review]
Tested on ts1. All worked as expected.

**Review by bassner — APPROVED** [review]

**Pull request merged**
