### PR TITLE
`Programming exercises`: Fix continuous rescheduling of timed out build jobs in local continuous integration

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context

Currently, if a build job has timed out it will always get rescheduled. If the system's resources get overloaded this might cause a continuous reinvocation of timed out build jobs and the system might crash. To avoid this, we limit the number of reruns to 1.

### Description

We check whether a job has already been rescheduled once and if yes, cancel.

### Steps for Testing

Hard to test as under normal circumstances, build jobs should not time out.
**Only test on TS3, TS6 or legacy TS11 or locally.**

Prerequisites:
- 1 Instructor

1. Create programming exercise
2. Template and solution builds should still return expected results

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by mateusmm01 — APPROVED** [review]
LGTM. Also tested locally and worked!

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts11. Worked as expected

**Review by xHadie — APPROVED** [review]
_Manually tested on TS6_
Works as expected.

**Review by basak-akan — APPROVED** [review]
Code looks good

**Pull request merged**
