### PR TITLE
`General`: Make spacings consistent

### PR DESCRIPTION
**Pull request by simon-hng**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

- Makes the UI consistent with bootstrap configuration leading to better ease of use.
- Improves accessibility for e.g. better screen reader support.

### Description

- Changes some margins and padding to be consistent with our bootstrap configuration
- Simplifies scss so that future changes are easier
- Improves DOM to use better elements and improve accessibility

### Steps for Testing

Prerequisites:
- Instructor account as some pages are only visible with those permissions

1. See the screenshots below and follow the navigation instructions.
2. Check that the screenshots match and the UI is not broken various screen sizes.

### Screenshots

/course management > Exercises
artemis-test1 artemis in tum de_course-management_66_exercises
localhost_9000_courses_11_exercises (1)

/courses > any course
artemis-test1 artemis in tum de_course-management_66_exercises (1)
localhost_9000_course-management_9

/courses > any course > Exercises
artemis-test1 artemis in tum de_courses
localhost_9000_courses_11_exercises

### CODE REVIEW

**Comment by bassner** [comment]
I think everything looks good, but I'm wondering if we really need the label on the exercise search box. Usually, it should be clear enough by the search button and an appropriate placeholder. What do you think, @simon-hng?

image

**Comment by simon-hng** [comment]
@bassner your're right the label is redundant. 

However it might be better for accessibility reasons and it follows the client [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/?highlight=label#labels).

I propose that we leave it as is since it does not really clutter the UI or does any other harm

**Review by julian-christl — APPROVED** [review]
The changes look good.

Regarding @bassner: While I agree it's technically redundant, I think the current implementation gives a better call to action. The placeholder isn't phrased or coloured adequately to be considered one.

**Comment by bassner** [comment]
@simon-hng @julian-christl 
My opinion stands, though. It's just consuming space for no real reason.

1. Take GitHub for example: The search bar on top does not have an external label. There are several more examples out there, see below.
image
image

2. It's inconsistent with other parts of Artemis. We're not doing that anywhere else, besides maybe the advanced search in the management view, but there we have multiple fields so it makes sense. However, communication and posts have search bars that are not labeled, but use the placeholder and button as call to action and they work and are understood just fine.

image
image

3. To ensure accessibility, you can add an aria label to it. That will work fine. An external, real label is not required

If you want, we can also add an exception to the guidelines for cases like this

**Review by rriyaldhi — APPROVED** [review]
Changes look good!

**Review by danielbode — APPROVED** [review]
Code LGTM

**Comment by simon-hng** [comment]
@bassner sounds like a good solution with the aria label. However I would say it is out of scope here

**Review by mertyldrr — APPROVED** [review]
Spacings look consistent and better 👍

**Review by TimOrtel — APPROVED** [review]
Looks better now! Thank you!

**Review by frederik-kt — APPROVED** [review]
Tested during testing session on TS1. Looked at the screenshot's locations and everything still looks good.

**Pull request merged**
