### PR TITLE
`Integrated code lifecycle`: Fix detection of skipped tests

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Artemis currently does not detect skipped tests correctly and marks them as successful instead.

### Description
Skipped test cases have a `<skipped/>` element inside. I added a check for this to the Parser.

### Steps for Testing
Create a Programming Exercise that uses Assumptions for skipping test cases, for example a test like this:

```java
MergeSort mergeSort = new MergeSort();
mergeSort.performSort(dates);
Assumptions.assumeTrue(datesWithCorrectOrder.equals(dates));
```

Check that the test passes for the solution, but is skipped for the template / student submission:

grafik

#### Performance Review 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage
Test added, changes covered

### CODE REVIEW

**Review by rstief — APPROVED** [review]
Code LGTM

**Review by BBesrour — APPROVED** [review]
code

**Review by pzdr7 — APPROVED** [review]
Tested on TS2. Detection works ✅

**Review by krusche — APPROVED** [review]

**Comment by krusche** [comment]
Thanks for fixing this issue!

**Pull request merged**
