### PR TITLE
`Development`: Fix LTI on multi node systems

### LINKED ISSUE #9017: Error when linking exercises via LTI
### Describe the bug

PR #8998 fixed some issues when setting up a LTI connection e.g. to Moodle. But after selecting exercises to link with moodle, an internal server error occurs and the exercises do not get selected.

### To Reproduce

1. Setup an LTI link following https://docs.artemis.cit.tum.de/user/lti.html
2. Choose exercises to link as an activity.
3. See the error page

### Expected behavior

The exercises are now visible in Moodle.

### Screenshots
grafik
grafik

### Which version of Artemis are you seeing the problem on?

7.4.2 (develop)

### What browsers are you seeing the problem on?

Firefox, Other (specify in "Additional context")

### Additional context

_No response_

### Relevant log output

```shell
Caused by: org.springframework.security.oauth2.core.OAuth2AuthenticationException: [authorization_request_not_found] 
	at uk.ac.ox.ctl.lti13.security.oauth2.client.lti.web.OAuth2LoginAuthenticationFilter.attemptAuthentication(OAuth2LoginAuthenticationFilter.java:131)
	at de.tum.in.www1.artemis.web.filter.Lti13LaunchFilter.finishOidcFlow(Lti13LaunchFilter.java:103)
```

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
LTI does not work on multinode setups.
Fixes #9017.

### Description
I copied the code of the default `StateAuthorizationRequestRepository` (which sadly is a final class) into a new `DistributedStateAuthorizationRequestRepository` that now uses Hazelcast to share the content between nodes.

### Steps for Testing
Use a multinode testserver like TS3 (see https://confluence.ase.in.tum.de/pages/viewpage.action?pageId=25252245).

0. An Admin must connect the testserver with moodle (https://docs.artemis.cit.tum.de/user/lti.html).
1. Activate "Online Course" for your course (Course Management -> Edit -> Checkbox at the bottom).
2. Link exercises to moodle (follow the documentation on https://docs.artemis.cit.tum.de/user/lti.html#linking-artemis-exercises)

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Introduced enhanced security configurations with distributed data management using Hazelcast.
	- Added a new repository for managing OAuth2 authorization requests in a distributed environment.
	- Improved LTI 1.3 security filter configurations and logging capabilities for better traceability.

- **Improvements**
	- Refined error handling in the LTI 1.3 launch filter for better user experience.
	- Clarified naming conventions for JWT lifetime constants to improve code readability.
	- Enhanced the scalability and robustness of state management in security configurations.

- **Bug Fixes**
	- Corrected documentation in the login cookie method for better clarity.

### CODE REVIEW

**Review by krusche — CHANGES_REQUESTED** [review]
Code looks good, but I would appreciate if we can improve the JavaDoc and inline code comments so that it will be easier for future developers to understand the code

**Comment by Strohgelaender** [comment]
@coderabbitai pause

**Review by iyannsch — CHANGES_REQUESTED** [review]
I like the changes, good job! One thing that bothers me a bit, but is done a lot throughout Artemis, is the extensive passing of instances in constructors. In your case, the `hazelcastInstance` passend through multiple objects. 
In Spring Boot, there are `Singleton Beans` which could potentially help to clean up the code a bit more as the global instance would be shared. How do you feel about that as an improvement?

**Review by iyannsch — APPROVED** [review]
Code LGTM

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by MaximilianAnzinger — COMMENTED** [review]
In general I like the logging you did here. However, I'm not sure if all of it should be logged as info?

**Comment by Strohgelaender** [comment]
> In general I like the logging you did here. However, I'm not sure if all of it should be logged as info?

I had it at debug it first, but Stephan requested it to be in info level. LTI is not used often (which makes it a prime candidate for some regressions to sneak in) and in these cases gaining information about the LTI process should be as simple as possible.

**Review by maximiliansoelch — APPROVED** [review]
Didn't look at the code, but tested the PR on the staging server and it now works as expected 👍

**Review by krusche — APPROVED** [review]

**Pull request merged**
