### PR TITLE
Fix Score Calculation for Zero Point Programming Exercises

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context
Calculate the score of zero point programming exercises properly as well (this is common for practice-only exercises that are not graded at all). This worked before we updated the score calculation and is required for PGdP.

**Manual assessment of zero point exercises (programming and in general) are out of scope for this PR. See comment below as well.**

### Description
- Use placeholder point value when calculating the score of a zero point programming exercise. Since it is not used for the students course score (there the exercise score is still 0), the result is only displayed better.
- Adjust some charts in the client to display the values correctly.

### Steps for Testing
0. Review the code.
1. Create a programming exercise with and without SCA but with points.
2. Check that the score calculation still works if you solve test cases (best would be to check weights and bonus points as well)
3. Edit the exercise to give 0 points (and no bonus points as well)
4. Check that the score calculation works just as before (but without you getting any points in the course for that)

### Test Coverage
_Unchanged._

### CODE REVIEW

**Review by kloessst — APPROVED** [review]
Works fine. Code looks good. Grading statistics also work with zero points cause of @schultek  quick fixes.

**Comment by MaisiKoleni** [comment]
Support for manual assessments across all exercise types will be done in a separate PR (also to avoid getting into conflicts with current rework of manual programming assessment).

**Review by schultek — APPROVED** [review]
The server side score calculation now works with zero points exercises. I also added the fixes regarding the score chart for the user and test case chart on the grading page.
The code looks good to me. 👍

**Review by fde312 — APPROVED** [review]
Tested with the others and works fine. Good job! 🚀

**Review by krusche — APPROVED** [review]

**Pull request merged**
