### PR TITLE
`Exam mode`: Fix an issue when using structured grading instructions during the second correction round

### LINKED ISSUE #4754: `Exam Mode`: Structured Grading Feedback does not show up in the second correction round making
### Describe the bug

Feedback from the first correction round that uses the structured grading criteria, only shows up as an empty text box in the second correction round.
This makes the second correction basically impossible since most of the first correction is missing in most cases.
Furthermore because of the empty responses the second correction cannot be submitted unless all feedback have been filled again.

### To Reproduce

1. Create a exam (text) exercise with second correction enabled.
2. Assess it in the first correction round using the structured grading instructions
3. Find that in the second correction round a bunch of feedbacks are empty

### Expected behavior

The feedback items should show up like in the first correction rounds.

### Screenshots

First correction round:
image

Second correction round:
image

Diff View:
image

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

Firefox, Chrome, ...

### Relevant log output

No console errors

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).

### Motivation and Context
Closes #4754

### Description
When preparing the assessment of the second correction round, the existing feedback gets copied. In this process, the `copyFeedback()`-method gets called. Here the gradingIstruction-field is now copied as well so that the connection doesn't get lost.

### Steps for Testing

Prerequisites:
- 1 Exam with different exercises (preferably every type), each exercise with grading instructions.
- Second correction enabled for the exam
- 2 Tutors
- 1 Student

1. Tutor 1: Use Grading instructions during the first correction round
2. Tutor 2: Make sure the grading instructions are visible during the second correction round. Change the assessment.
3. Student: Make sure the grading instructions used in the second correction round are visible in the feedback.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by krusche** [comment]
Good finding, thanks for the fast response 👍 👍 👍 
Would be awesome if some people can test that this actually works correctly now

**Review by cremertim — APPROVED** [review]
tested on ts1, the link is now there as expected.

**Review by willergeorg — APPROVED** [review]
Tested on TS3. Structured grading instructions are visible in second correction round.

**Review by willergeorg — COMMENTED** [review]
Code is good as well. 👍

**Review by akesfeden — APPROVED** [review]
Tested on TS3, the structured grading instructions are visible in both correction rounds, and feedbacks added using the grading instructions in the first correction round is visible and correctly linked at the second correction round, confirmed with the second tutor user.

**Pull request merged**
