### PR TITLE
`Development`: Cleanup legacy and unused client code in the communication feature

### PR DESCRIPTION
**Pull request by egekurt123**
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only 
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

This PR addresses the removal of unused and legacy code within the communications module, including old Sidebar files.

Steps for Testing

- Ensure that no functionality is affected after the deletion of files/code.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

## Summary by CodeRabbit

- **Refactor**
  - Removed unused components from the course conversations module.
  - Simplified `ChannelsOverviewDialogComponent` by removing unnecessary service dependencies.
  - Cleaned up `MetisService` by removing unused methods and reordering existing ones.

- **Tests**
  - Updated `MetisService` test suite to remove references to outdated configurations and simplify tags update logic.

### CODE REVIEW

**Review by SimonEntholzer — DISMISSED** [review]
As far as I checked the code and testing locally nothing seems to have broken

**Review by marlon-luca-bu — DISMISSED** [review]
Code

**Review by JohannesStoehr — APPROVED** [review]
Removal looks good to me

**Review by marlon-luca-bu — APPROVED** [review]
Adaptions look good to me

**Review by SimonEntholzer — APPROVED** [review]

**Review by asliayk — APPROVED** [review]
tested locally, everything looks fine

**Pull request merged**
