### PR TITLE
`Development`: Fix flaky ExerciseGroupIntegrationTest

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] This is a small issue that I tested locally.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
The test `importExerciseGroup_successfulIntoDifferentExam` was flaky on Postgres. 

### Description
This was actually not a wrong test, but a bug in the production code where we relied on the order of the database response.
We expected to get a list of exercise groups in the order of which they are defined in the exam, but no `ORDER BY` section was sepecifed.

We now use the `INDEX()` method to sort the results based on the order defined in the exam. See https://en.wikibooks.org/wiki/Java_Persistence/JPQL#Special_Operators for more details.

I used this opportunity to clean up the `ExerciseGroupRepository`. The method `retrieveCourseOverExerciseGroup` was unused and `findByExamId` has the same issue of not ensuring the order of the list. This method was only used in tests, so I removed it.

### Steps for Testing
You could try to test this PR on a Postgress testserver. Import exercise groups from one exam into the other and check that the order of the groups is correct. However, reviewing the code and verifying that the test is successful now should be enough.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### CODE REVIEW

**Comment by Strohgelaender** [comment]
Thanks for pointing this out, seems like the custom query does not work together with the EntityGraph. I now added the attributes to the custom query.

**Review by DominikRemo — APPROVED** [review]
Tests succeed on bamboo and GitHub Actions. Thank you for the fix 👍

**Review by laadvo — APPROVED** [review]
Ran the test locally 3500 times, it did not fail once. Code also looks good

**Review by JohannesStoehr — APPROVED** [review]
Approve Code changes

**Pull request merged**
