### PR TITLE
`Development`: Set a common locale configuration for server JVM runtime

### PR DESCRIPTION
**Pull request by akesfeden**
#### General

- [x] I tested **all** changes and their related features ~with **all** corresponding user types~ on a test server.
- [x] This is a small issue that I tested locally ~and was confirmed by another developer on a test server~.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Some locales have different rules for comparing strings to lower/uppercase and comparisons. For example in Turkish locale `"I".equalsIgnoreCase("i")` is false. This PR intended to evaluate and discuss whether configuring a common default locale for server JVM in both local development setups and deployed environments would prevent unexpected locale-related errors to happen on deployments or new developers' local setups by standardizing locale configuration and making it independent of the host machine's OS settings. This can increase the chance of other developers getting the same errors and help debugging efforts. 

Note that my intention is not solving a specific error but rather avoiding a potential set of errors by proactively adopting a common standard.

This topic was discussed in [Artemis Developer Meeting - 2022-03-31](https://confluence.ase.in.tum.de/display/ArTEMiS/Artemis+Developer+Meeting+-+2022-03-31#ArtemisDeveloperMeeting20220331-4.Discussion[30min]).

### Description

This PR sets ` -Duser.country=US -Duser.language=en` as VM parameters to JVM related configurations in .idea/runConfigurations folder for IntelliJ and also gradle.properties. The proposed changes are not very robust to enforce the standard since a developer not using IntelliJ or who is running server integration tests with JUnit configuration instead of Gradle configuration can bypass this default locale parameters. Also, existing run/debug configurations apart from the ones explicitly set by the PR are not affected.

The error that leads to this discussion is having `ProgrammingExerciseBitbucketBambooIntegrationTest.importExercise_enablePlanFails` integration test locally fail with the error below. The reason is at the end of `https://version-control.fake.fake/...%C4%B0MPORTED` url. Mock web client was expecting   the url to be `https://version-control.fake.fake/...IMPORTED`. `%C4%B0MPORTED` is the URI encoded version of the string `İMPORTED` (with capital I with a dot), which is the upper case version of the string `imported` in Turkish locale, whereas the uppercase of the same string is `IMPORTED` in English and German locales. The source of the string can be seen [here](https://github.com/ls1intum/Artemis/blob/ec7de46625250bd9e0c9b820fa4a0c46771a4b4e/src/test/java/de/tum/in/www1/artemis/programmingexercise/ProgrammingExerciseTestService.java#L572).

```
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.AssertionError: No further requests expected: HTTP GET https://version-control.fake.fake/rest/api/latest/projects/SHORTB37546010990804E030B79608AD4E6DD8845%C4%B0MPORTED
0 request(s) executed.

	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:517)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:72)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:167)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
	at de.tum.in.www1.artemis.config.ApiVersionFilter.doFilter(ApiVersionFilter.java:51)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
	at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
	at org.springframework.boot.web.servlet.filter.ErrorPageSecurityFilter.doFilter(ErrorPageSecurityFilter.java:80)
	at org.springframework.boot.web.servlet.filter.ErrorPageSecurityFilter.doFilter(ErrorPageSecurityFilter.java:70)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
	at io.sentry.spring.SentryUserFilter.doFilterInternal(SentryUserFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at de.tum.in.www1.artemis.security.jwt.JWTFilter.doFilter(JWTFilter.java:36)
```

### Steps for Testing

Prerequisites:
- Local Artemis Setup
- IntelliJ IDE

1. From IntelliJ, Try debugging the server, putting a breakpoint in the main method and evaluate `Locale.getDefault()`. It should display `en_US`.
2. Try the same for running a server integration test by clicking the green arrow near the test definition in the editor. Note that it should run with Gradle configuration, JUnit configuration didn't apply the locale options I set.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by filip-gregurevic — APPROVED** [review]
Tested it locally and it worked as described. 👍🏼

**Review by ge65cer — APPROVED** [review]
I ran the Java tests with the JVM arguments on my machine without problems.
If this fixes your local development setup, I'll approve this PR.

**Review by Hialus — APPROVED** [review]
Tested it locally in IntelliJ on an M1 Mac and encountered no issues.
Well done 👍🏻

**Review by maximiliansoelch — APPROVED** [review]
Tested locally and it still works as expected.

**Review by canberkanar — APPROVED** [review]
Tested locally according to the instructions. I could not see any issue both with the server and the integration tests. Code is also good! 💪🏻

**Pull request merged**
