### PR TITLE
[Enhancement] - Edit groups in detail page

### PR DESCRIPTION
**Pull request by FuchsDominik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Its more convenient for instructors to be able to add and remove users from usergroups in the detail page

### Description

- Removed the plain user group print and added a link to the user-group editing page
- Also added some more information regarding a course which could be interesting for instructors/TA

- My IDE did some automatic (style-) changes which did not change any behaviour, just ignore that.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Management and click on the course id
3. Make sure you can click on the user-group names (students, tutors and instructors) and get redirected to the page where you can add and remove users from the group
4. Also check that there is no problem at the bottom with displaying complaint and more feedback request information

### Screenshots

Screenshot 2021-02-03 at 19 42 50

### CODE REVIEW

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts2 and works as expected. 
I'm not sure if the "Maximum amount of complaints per team" value should be shown as well on the detail page, since this one is missing. The other values look good.

**Review by airelawaleria — APPROVED** [review]

**Comment by FuchsDominik** [comment]
> Tested on ts2 and works as expected.
> I'm not sure if the "Maximum amount of complaints per team" value should be shown as well on the detail page, since this one is missing. The other values look good.

Sure why not :) Added in [this](https://github.com/ls1intum/Artemis/pull/2817/commits/d3ba5df840b67fd6010986c129568d45398349fc) commit

**Review by marvinchimeka — APPROVED** [review]
Tested on ts2. Works as intended. No issues found

**Review by simonzilker — DISMISSED** [review]
Works fine :)

**Review by airelawaleria — APPROVED** [review]

**Review by EneaGore — DISMISSED** [review]

**Review by JohannesWeiss — APPROVED** [review]

**Pull request merged**
