### PR TITLE
`Programming exercises`: Fix link to build plan editor for exam exercises

### LINKED ISSUE #7125: `Exam`, `Programming exercises`: ‘Edit build plan‘ button not working
### Describe the bug

The ’Edit build plan’ button does nothing for exam exercises.

image

The button currently links to
```
https://ARTEMIS/course-management/4/exams/4/exercise-groups/15/programming-exercises/41/edit-build-plan
```
but should link to
```
https://ARTEMIS/course-management/4/programming-exercises/41/edit-build-plan
```
instead.

### To Reproduce

1. Create an programming exercise in an exam.
2. Go to the details page for the exercise.
3. Click the button.

### Expected behavior

The build plan edit view appears as for regular course exercises.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.4.1

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
#### Changes affecting Programming Exercises
- [ ] ~~I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).~~ not applicable
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Closes #7125

### Description
The URL was wrong for exams since the relative URL for exam exercises is different. Fixes this by adding an additional route.

### Steps for Testing

Prerequisites:
- Gitlab/Jenkins setup
- 1 Instructor
- 1 Exam programming exercise

1. Go to the exam programming exercise details page.
2. Click the ‘Edit build plan’ button (see #7125).
3. You should be redirected to a page with a big text box where you can edit the build plan.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

### CODE REVIEW

**Review by chrisknedl — DISMISSED** [review]
Was able to reproduce the bug, and can confirm that this PR fixes it (tested on my local Jenkins setup). Code also looks good

**Comment by Strohgelaender** [comment]
Should we not allow a second route to the build plan editor which also takes the exam context into account? Currently this gets lost which is important for the breadcrumbs,

**Review by Strohgelaender — APPROVED** [review]
lgtm

**Review by milljoniaer — APPROVED** [review]
Code LGTM

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts2. Worked as expected.

**Pull request merged**
