### PR TITLE
`Integrated code lifecycle`: Return 403 for access attempts to repositories the user doesn't own

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I fixed multiple integration tests (Spring) related to the features (with a high test coverage).

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

Local VC returns 401 / "authentication failed" instead of 403 when trying to clone a repository the student doesn't own, even though the provided username+password are correct.

### Description

Fixed the error message and adapted affected tests. Fixes Issue 8 in https://confluence.ase.in.tum.de/display/ArTEMiS/Issues.

### Steps for Testing

**Test on TS3, TS6 or Local CI Staging**
Prerequisites:
- 1 Student

1. Using local git, try to clone from another users repository
2. Verify the 403 error code

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [RepositoryAccessService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6100/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/RepositoryAccessService.html) | 98% | ✅ |
| [LocalVCServletService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6100/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.localvc/LocalVCServletService.html) | 91% | ✅ |

## Summary by CodeRabbit

- **Refactor**
	- Updated exceptions for unauthorized access to use more specific `AccessForbiddenException` across various services and test cases, enhancing clarity on access restrictions.

### CODE REVIEW

**Review by milljoniaer — APPROVED** [review]
Tested on ts3, works as expected 🚀

**Review by rstief — APPROVED** [review]
Code

**Review by reschandreas — APPROVED** [review]
code lgtm

**Review by MaximilianAnzinger — APPROVED** [review]
Code lgtm

**Review by bassner — APPROVED** [review]
LGTM

**Pull request merged**
