### PR TITLE
Feature/update apollon

### LINKED ISSUE #1345: Lost focus when hitting enter in assessment
### Describe the bug
When I hit enter in a textfield of the assessment (in a diagram) the enter will occurr (the cursor moves one line down) but the input field immeadiatly looses focus. To write the new line of text you have to click in the input field again to reset the focus.

#### To Reproduce
1. Start diagram assessment (possibly on other exercise types as well)
2. Doubleclick an element of the diagram to add some comment
3. Write some text, enter
4. See how the cursur moves and how the focus shifts
5. Try to write something again
6. Get annoyed :P

#### Expected behavior
Simple enter, you're able to continue writing in the next line.

### Environment
<details><pre>
 - OS: Win 10 Pro
 - Browser Chrome 81.0.4044.122
</pre></details>

#### Output in Web Console
Nothing

### LINKED ISSUE #1444: Default Arrow direction in Apollon Communication Diagrams
### Is your feature request related to a problem?
It's frustrating that when using Apollon to draw Communication Diagrams, the message arrows go opposite to the expected direction, and the messages stack opposite to the expected way.

### Describe the solution you'd like
I would like that when connecting A to B, the message arrow goes by default from A to B instead of from B to A.
And that the messages should stack from top to bottom instead of from bottom to top.

### Additional context
Screenshots:
Connect A to B and add these messages:
Take 1
When flipping the arrow direction from 2.1 and 2.2 this happens
Take 2

### LINKED ISSUE #1470: Repeated copypasting in UML editor doesn't work
When trying to copy-paste with Ctrl-C and Ctrl-V, it works as intended. But if you try to paste again without copying before (Ctrl-C, Ctrl-V, Ctrl-V), it moves the previously pasted element to the new location instead of creating a new element.

### PR DESCRIPTION
**Pull request by TobiasPr**
### Bugfixes and Enhancements

Update of Apollon version. It brings some small usability enhancements:
- copy paste is now possible cross browser/tab, multiple pasting will result in creating the same object multiple times
- popup usability improvements: setting autoFocus when opening popups + changed tab / enter key behavior when adding sub elements in popup to element (e.g. adding ClassAttributes to Classes)
- Assessment popup bug: When writing feedback inside the feedback field in the assessment popup dialog for an element, it used to be that by hitting enter, the field lost focus -> fixed. New behavior: newline
- the moving object in the diagram is brought to the front, so that the moving element is always visible
- messages in communication diagram are ordered correctly

#### Copy Paste
1. Copy diagram elements once (Ctrl + C)
2. Paste diagram elements multiple times ( Ctrl + V)
3. Expected outcome: inserted elements are selected, old elements are deselected, new elements are shifted

#### Popup usability improvements
1. Create each diagram element and each kind of relation once 
2. Open the update dialog (Dbl click on diagram element, Apollon Editor has to be in Modelling view) 
3. AutoFocus is set for each popup
4. When elements can be created in the popup (e.g. CommunicationLink between two objects in communication diagram or ClassAtributes in class diagram), clicking tab or enter will create the object and sets focus to the next field to make it possible to directly create another object by starting typing

#### Assessment popup bug:
1. Go to the assessment of a modeling exercise
2. Open assessment popup for element (Dbl. Click)
3. enter textual feedback for that element, pressing enter will result in a newline and textfield will keep the focus

#### Moving object in the diagram is brought to the front
1. Participate in a modeling exercise
2. create multiple UML elements
3. when moving an element, it is always drawn in front (in the top most drawing layer) so that it is always visible to users and not covered by other elements in the diagram
4. Other objects maintain their drawing order

#### Messages in communication diagram are ordered correctly
1. Create a communication diagram with a link in between two objects
2. Create multiple messages on the link in both directions
3. The messages are drawn in correct order (similar to dialog)
4. Move the objects around, so that the arrow direction for the messages changes
5. The messages are still drawn in the correct order

### Screenshots

Copy Paste
copy_paste

Popup
popup_usability

Fixes #1470 
Fixes #1345 
Fixes #1444

### CODE REVIEW

**Comment by TobiasPr** [comment]
@niclasschuemann thank you for reviewing, I will address most of the issues you mentioned i.e.

1. Jumping to next field on first attribute
2. Moving element in front of relationships

I think its legit to press tab twice to get to the methods (not that much of an effort). I fear that tutors will not understand the difference between tab and enter without an explanation

**Comment by Varnika-Tyagi** [comment]
**Copy Paste**
_Copy diagram elements once (Ctrl + C)
Paste diagram elements multiple times ( Ctrl + V)
Expected outcome: inserted elements are selected, old elements are deselected, new elements are shifted_
Works as expected. One nice addition could be: In case of multiple pasting of diagram elements,  the previous 'copy' of the pasted element is automatically selected if current copy is deleted.

Cross-tab pasting works well too.

**Assessment popup bug**
Auto´-focus on text field works as intended.

(!) Moving object in the diagram is brought to the front. As @niclasschuemann mentioned, 
It works perfectly for UML elements, but it does not work well for relations. 
Moving object is brought to the front and other objects maintain their drawing order. But relations always stay at the foreground, even if they're connected to an old object.
Relations are always at front

**Messages in communication diagram are ordered correctly**
Moving around the objects does not change the order of the arrows drawn.

**Comment by alexmardale** [comment]
(From Niclas' comment)
_(!) Moving object in the diagram is brought to the front
It works perfectly for UML elements, but it does not work well for relations_

Didn't catch this one myself, but can confirm it is the same for me.



(From Niclas' comment)
_(!) Popup Usability Improvements
I was able to use enter and tab to "navigate" through the update dialog on every appropriate UML diagram. The AutoFocus was set correctly.
1 small issue:

Pressing enter will not result in a new attribute/method on the first attribute:_

It seems that it doesn't necessarily have to be the first one;
Screenshot from 2020-06-02 15-24-44
Regardless of which of the attributes I go to, pressing enter will not result in a new attribute/method.

It's probably that you need to stay in the flow of "add new attribute"->"press enter"->"add new attribute"->"press enter" etc. in order for this to work. Otherwise if you go/click somewhere else, you have to actually click on the new line to create a new attribute/method.



Otherwise, the rest of the steps worked as expected for me.

**Comment by TobiasPr** [comment]
> @niclasschuemann thank you for reviewing, I will address most of the issues you mentioned i.e.
> 
> 1. Jumping to next field on first attribute
> 2. Moving element in front of relationships
> 
> I think its legit to press tab twice to get to the methods (not that much of an effort). I fear that tutors will not understand the difference between tab and enter without an explanation, thats why I will leave it as it is

okay there is a limitation to overlaying elements over relationships, current SVG browser standard (version 1.2) does not support z-index or anything else to determine drawing order. The drawing order is determined by the order in the html tag (last element is drawen first). Because we are drawing elements and relationships separately it is not possible to let certain elements overlay the relationship and others not. I changed the drawing order, so that elements are drawn in front of relationships by default

**Pull request merged**
