### PR TITLE
`Learning analytics`: Make competency taxonomies more user friendly

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Selecting a taxonomy for a competency was not really user-friendly.

### Description

Artemis now suggests a potential taxonomy based on keywords used in the description.
The select input field makes the hierarchy of the taxonomies more clear.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration, Competencies, Create Competency
3. Select a taxonomy
4. Write a title or description with one or more keywords
5. Leave the input field to see that Artemis suggests a taxonomy

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Added a test case for the single newly introduced client side function.

### Screenshots

Screenshot 2023-03-05 at 12 16 14

### CODE REVIEW

**Review by danielbode — APPROVED** [review]
Tested on ts1 in German and English. Works as expected. Cool idea and feature!

But I have two discussion points.

- Should we consider the taxonomy title itself when suggesting a taxonomy? I think "The students should be able to create an AOM." should suggest the create taxonomy.

- Maybe we can make the detection less sensitive and include e.g. "Implement", "implemeting" and "Implementing" as well as "implement"?

**Comment by ge65cer** [comment]
@danielbode I implemented your suggestions. Checking against the keywords is now case-insensitive and also takes the title into consideration.

**Review by danielbode — APPROVED** [review]
Thanks for implementing my feedback!
Tested again on ts2. Everything works as expected.

**Review by bassner — APPROVED** [review]
LGTM

**Pull request merged**
