### PR TITLE
Make Short Answer Options of Quiz Editor Case-Sensitive

### LINKED ISSUE #3028: Stating lowercased and uppercased option for one short answer question results in error
### Describe the bug

When stating multiple answer options in _short answer questions_ of quiz exercises, a lowercased and an uppercased option for one and the same blank results in the following error:

> Question X: At least one mapping is duplicated.

#### To Reproduce

1. Create quiz exercise
2. Choose short answer question
3. Create a spot with two answer options
4. State one uppercased, the other one lowercased
5. Make sure that both options "Match Letter Case" and "Match Answers Exactly" are active (this is critical for fill-in-the-blank programming exercises)
5. Click "Save"

#### Expected behavior
Saving would occur without yielding an error message.

#### Screenshots
image

#### Additional context
Please fix till March 23 2021 or let us know if this is not possible (ciritcal due to an exam on 26 March).

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
This resolves #3028 by making all options in short answer quiz questions case-sensitive, so that options that only differ in letter case are not regarded as duplicates.

### Description
- Removed `toLowerCase` on both sides.
- Make changes to saved quizzes (also in general) case-sensitive. Current problem:
   quiz-char-case-change

### Steps for Testing
1. Create a quiz with short answer question
2. Add options to the short answer question that only differ in case
3. Make sure you can save the quiz (given that all unrelated problems are resolved)

### Test Coverage
_Unchanged._

### Screenshots
TODO

### CODE REVIEW

**Review by krusche — COMMENTED** [review]
The proposed changes make sense to me

**Review by ivohashamov — CHANGES_REQUESTED** [review]
Screenshot 2021-03-16 212505

Currently, I'm able to save options that differ only in letter case (input and Input), but I'm also able to save two completely identical options (as shown in the screenshot)

**Comment by krusche** [comment]
> Screenshot 2021-03-16 212505
> 
> Currently, I'm able to save options that differ only in letter case (input and Input), but I'm also able to save two completely identical options (as shown in the screenshot)

That's fine, because the two answers `input` and `input` are mapped to 2 different spots.
This should only be invalid, if you map those to the same spot

**Review by ivohashamov — APPROVED** [review]
Works as intended

**Review by krusche — APPROVED** [review]

**Pull request merged**
