### PR TITLE
[WIP] Updated and fixed the C template

### PR DESCRIPTION
**Pull request by COM8**
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

The C template was using a quite outdated version of the tester and had some flaws related to potential vulnerabilities.

### Description

I've updated the C template to fix those vulnerabilities and fixed those tests.

### Steps for Testing

1. Create a new C exercises 
2. The solution should build successfully

### CODE REVIEW

**Comment by sleiss** [comment]
We might have to update the solution used within the K6 tests. I'll have a look at this.

**Comment by krusche** [comment]
@COM8 I invited you to get access to the Artemis Github repository.
Can you please recreate this PR based on a feature branch in the Artemis repo?
Then, you and we can test the changes on our test server.
With external PRs, this is not possible

**Comment by COM8** [comment]
@krusche ACK 👍.

**Comment by COM8** [comment]
Closed in favour of #2150.

**Pull request closed without merging**
