### PR TITLE
`Communication`: Remove announcements from unresolved filter

### PR DESCRIPTION
**Pull request by cremertim**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Description

I removed the announcement channel from the courseWidesearch, if the user looks for unresolved questions

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with Communication enabled

1. Log in to Artemis
2. Navigate to Course Management
3. Create an Announcement 
4. Use the course wide search to search for that announcement
5. verify the announcement is present
6. click on the unresolved filter
7. verify the announcement is not present

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| course-wide-search.component.ts | 97.53% | ✅              |

### Screenshots

image
Unticked unresolved --> you can see the announcement

image
Ticked unresolved --> you cannot see the announcement

## Summary by CodeRabbit

- **New Features**
	- Introduced a new method to identify announcement channels in course conversations.
	- Enhanced filtering logic to exclude announcement channels when viewing unresolved conversations.

- **Bug Fixes**
	- Improved accuracy of channel ID filtering in the course-wide search functionality.

### CODE REVIEW

**Review by PaRangger — APPROVED** [review]
Code LGTM and works just as described 👍🏼

**Review by krusche — APPROVED** [review]
Code looks good to me 👍

**Review by florian-glombik — APPROVED** [review]
I followed the testing steps and it worked as described.

One thing that surprised me, I was first searching for the title of the announcement, but the search does only seem to include the content. Can we extend this in the future?

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS5. Works as described.

**Pull request merged**
