### PR TITLE
`Programming exercises`: Show whitespace changes in diff viewer

### LINKED ISSUE #9928: `Programming Exercise`: Git diff between template and solution shows incorrect number of changes
### Describe the bug

For some files, the calculated numbers of additions and deletions are incorrect displayed.

### To Reproduce

1. Go to a programming exercise edit page 
2. Click on 'Review Changes' in the Template/Solution Comparison section
3. Look for a file where the calculated number of additions and deletions is incorrect

### Expected behavior

The number of added and deleted lines of code between the template and the solution submission should be correct.

### Screenshots

image

### Which version of Artemis are you seeing the problem on?

7.7.3

### What browsers are you seeing the problem on?

Chrome, Safari

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by magaupp**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

Whitespace-only changes are currently hidden in the diff viewer. This, for example, hides tabs vs spaces inconsistencies and causes inconsistencies with the displayed line counts.

### Description

This PR disables the `ignoreTrimWhitespace` option of the monaco DiffEditor.

Closes #9928.

### Steps for Testing

1. Create a programming exercise
2. Replace all space indentation with tabs in the template repo and keep it as spaces in the solution repo
3. Wait until the build finishes
4. Click on "Review Changes"
5. Verify that changes in indentation are shown
6. Verify that the shown number of changed lines matches with the displayed changes with non-empty lines

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review
#### Manual Tests
- [x] Test

#### Before
grafik
#### After
grafik

## Summary by CodeRabbit

- **New Features**
	- Enhanced the diff editor to include an option for ignoring whitespace during text comparisons, improving accuracy in visual diffs.

### CODE REVIEW

**Review by HawKhiem — APPROVED** [review]
Tested on TS2. Everything works as described

image

**Review by ItsaaaMeMario — APPROVED** [review]
Tested on TS3, works as intended. 
Bildschirmfoto 2024-12-08 um 14 53 32

**Review by b-fein — APPROVED** [review]

**Review by krusche — CHANGES_REQUESTED** [review]
I am typically not interested in whitespace changes as an instructor, so the setting in the client was already correct. The numbers should then also take this setting into account, regardless of whether they are calculated on the server or client.

We could offer an option similar to Github "Files changed" tab in the future in case other instructors are interested in whitespace changes.

image

**Comment by magaupp** [comment]
We'll open another PR for a whitespace option in diffs

**Pull request closed without merging**
