### PR TITLE
`Development`: Fix an issue with the usage of mat-chips with Angular 15

### LINKED ISSUE #5960: `Exercises`: Import UI broken
### Describe the bug

See screenshot. The UI to import exercises does not work.

It is probably related to the Category chips.

### To Reproduce

1. As instructor, try to import an exercise (tested with a programming exercise).

### Expected behavior

The import UI works.

### Screenshots

Screenshot 2022-12-13 at 13-07-10 Import Programming Exercise

### Which version of Artemis are you seeing the problem on?

`develop`

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

```shell
ERROR TypeError: this._chipInput is undefined
    Angular 27
        get focused
        MatFormField_HostBindings
        processHostBindingOpCodes
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        detectChangesInternal
        detectChanges
        tick
        next
        invoke
        onInvoke
        invoke
        run
        run
        next
    RxJS 6
    Angular 20
    RxJS 31
    ArtemisVersionInterceptor artemis-version.interceptor.ts:40
    ArtemisVersionInterceptor_Factory main.js:2505
    Angular 22
    RxJS 20
instrument.js:108:32
    instrumentConsole instrument.js:108
    handleError Angular
    handleError sentry.error-handler.ts:73
    Angular 12
    RxJS 6
    Angular 20
    RxJS 31
    ArtemisVersionInterceptor artemis-version.interceptor.ts:40
    ArtemisVersionInterceptor_Factory main.js:2505
    Angular 22
    RxJS 50
    getTranslation ngx-translate-core.mjs:430
    retrieveTranslations ngx-translate-core.mjs:416
    setDefaultLang ngx-translate-core.mjs:363
    ArtemisCoreModule core.module.ts:108
    ArtemisCoreModule_Factory main.js:2345
    Angular 31
    73249 app.main.ts:19
    Webpack 7
```

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.

### Motivation and Context
Closes #5960

- Usage of mat-chips broke on update to angular 15
- Update guide: https://material.angular.io/guide/mdc-migration#chips

### Description
Fixed it by making two changes:              
- mat-chip to mat-chip-row as described in the documentation of mat-chip-grid 
- Change *ngIf to hidden on input
- Fix scss
- Fix duplicated entry and empty entry bug

### Steps for Testing

Prerequisites:
- `mat-chip-grid` is used in three places that should be tested:
- category selection when creating and importing exercise
- post tags when posting in discussion
- group tags in user management

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
- No changes 

### Screenshots

https://user-images.githubusercontent.com/29718932/207657238-3f20f652-016a-44d9-a4ab-7e299d2fe10d.mp4

https://user-images.githubusercontent.com/29718932/207657531-d17f0fab-1774-4ecc-98bf-3fb56406840b.mp4

 

https://user-images.githubusercontent.com/29718932/207658212-bb1a1cde-3a8d-4e60-8ab5-b35d21ddb818.mp4

### CODE REVIEW

**Review by timo07k — DISMISSED** [review]
Everything works as expected. Tested on TS1 and TS2.

**Review by timo07k — COMMENTED** [review]
Small remark: Should it be possible to create a tag which only contains a space?

image

**Review by pellumbbaboci — APPROVED** [review]
Test on ts2, works as expected. Code changes look good.

**Review by danielbode — DISMISSED** [review]
Nice fix! Tested on ts2 and it works as expected. Code changes also look good.

One thing I noticed is, that the chips component is not optimized for the dark mode. The text color is always black, which makes the text unreadable. We should address that in a different PR.

**Comment by stefanwaldhauser** [comment]
> Small remark: Should it be possible to create a tag which only contains a space?
> 
> image

This was an existing bug but I fixed it in: b707bfd7f3bfe58d4772143891742052bc56020b

**Comment by stefanwaldhauser** [comment]
> Nice fix! Tested on ts2 and it works as expected. Code changes also look good.
> 
> One thing I noticed is, that the chips component is not optimized for the dark mode. The text color is always black, which makes the text unreadable. We should address that in a different PR.

Fixed in: bf4f4a0fecdb74aca8e9391e8b85321ac5ecd840

**Review by danielbode — APPROVED** [review]
Thanks for implementing my feedback! Still works well. Tested again on ts2. Code also looks good.

**Comment by frederik-kt** [comment]
Tested on TS1. Works as expected but the x button for the first chip jumps in a weird way when the second chip is deleted.

https://user-images.githubusercontent.com/64478731/207912521-afe1df37-5f37-4c7d-a092-d8d29202590e.mp4

**Review by pellumbbaboci — APPROVED** [review]
Re-approved, tested on ts1. LGTM

**Pull request merged**
