### PR TITLE
`Discussion`: Do not show announcements when unresolved posts are filtered

### PR DESCRIPTION
**Pull request by canberkanar**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Tutors are using the "Unresolved" checkbox found in "Course Discussion" page to quickly reach unresolved posts of students and answer them. However with the current implementation, Announcements are also treated as "Unresolved" which should not be the case. Announcements are unresolvable Posts and should not be provided to users in this context.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with postings enabled

1. Log in to Artemis
2. Navigate to Course Discussion
3. Make sure that when the "Unresolved" checkbox is checked, resolved posts are filtered out as usual. But with this PR, announcements are also filtered out.
4. Make sure that all filtering and sorting of posts are still functioning as expected.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Not changed

### Screenshots

image
image

### CODE REVIEW

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Looked through the code and only found one issue:

**Review by willergeorg — CHANGES_REQUESTED** [review]
Tested on TS3. Announcements are filtered out, just as you stated. However, I might miss something here but somehow, resolved posts were still shown after enabling the "unresolved" filter option:
image
As a user unfamiliar with the underlying logic, this seems to be incorrect. Could you please check this again?

**Comment by canberkanar** [comment]
> Tested on TS3. Announcements are filtered out, just as you stated. However, I might miss something here but somehow, resolved posts were still shown after enabling the "unresolved" filter option: image As a user unfamiliar with the underlying logic, this seems to be incorrect. Could you please check this again?

Thanks for pointing it out. Can you take another look?

**Review by akesfeden — APPROVED** [review]
Tested on TS1 during testing session, announcements are filtered as expected and other (unchanged) features work as before. Code changes also look good.

**Review by ge65cer — APPROVED** [review]
Tested in testing session on TS1, no issues detected.

**Review by JohannesStoehr — APPROVED** [review]
Code looks good

**Review by jschmautzer — APPROVED** [review]
tested on ts1, followed the testing steps, worked as expected :)

**Comment by krusche** [comment]
I merge this now, but I really don't like that we use so many sub queries in the changed code.
@canberkanar for a future refactoring: please change all database queries that include subqueries so that they don't include those in the future! Thanks

**Pull request merged**
