### PR TITLE
`General`: Fix an issue when hovering over tooltips

### PR DESCRIPTION
**Pull request by danielbode**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

When creating a tooltip by hovering over an element, the tooltip is put in the same container as the anchor element. If the tooltip now overflows the previous container size, the container gets resized, which leads to a shifting of other elements on the page when a tooltip appears or vanishes.

### Description

I changed the default value for tooltips, so they get attached to the 'body' element. This way we do not have to change every existing tooltip and it also makes it easier for tooltips created in the future, as the developer does not have to know this possibly unwanted behavior.

NOTE: Even when we attach the tooltips to the 'body' element, overflows can still happen by bad use of the `placement `attribute. For example, if an element is placed on the right side of the screen and we define `placement='right'`. Then we get some overflow to the right, when the popup appears and ugly horizontal scrolling.
We can prevent this by defining fallback options, as bootstrap uses the first value, that doesn't cause overflow. There is also an `auto` option, that tries to put the element to the top, bottom, left, and right. In that order. So `placement='right auto'` will do the same as `placement='right'` in case there is enough space, but otherwise will put the tooltip to the top, bottom or left instead of forcing an overflow.
I already added the fallback option `auto` to every use of `placement`, but we have to keep that in mind for future use.

### Steps for Testing

Prerequisites:
- none

1. Log in to Artemis
2. Hover over an element, that will spawn a tooltip and verify, that other elements on the page do not get shifted

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Before Change:

https://user-images.githubusercontent.com/44734881/201890596-e048a7bc-e46c-4dfb-af87-baa285df362f.mov

After Change:

https://user-images.githubusercontent.com/44734881/201891607-fead39e6-045a-49b2-85f3-576c5cd50446.mov

### CODE REVIEW

**Comment by JohannesStoehr** [comment]
Couldn't we now remove all container="body" occurrences, since they are now handled automatically?

**Comment by danielbode** [comment]
> Couldn't we now remove all container="body" occurrences, since they are now handled automatically?

You are right. I forgot about that and will change it.

**Review by tobias-lippert — DISMISSED** [review]
Tested on ts2. Elements do not get shifted when spawning a tooltip.

**Review by JohannesStoehr — APPROVED** [review]
Thanks for going through all occurrences and fixing all of them.
Codechanges look good and did not find any other occurrences of container="body" or placement="top", which are no longer necessary.

**Review by LiaLism — APPROVED** [review]
Other elements do not get shifted. Tested on ts1

**Review by timo07k — APPROVED** [review]
There is no shifting anymore. Tested on TS1.

**Review by PhilipWerz — APPROVED** [review]
Everything works like it should! Tested on ts1

**Review by laadvo — APPROVED** [review]
Tested on ts2, tooltips do not cause shifting any longer

**Review by Yunqing-Wang — APPROVED** [review]
everything looks great

Yunqing

**Pull request merged**
