### PR TITLE
Feature/Programming Exercise/Allow build for inactivate participations

### PR DESCRIPTION
**Pull request by thilo-behnke**
Fix issue https://github.com/ls1intum/Artemis/issues/1042.
If a participation is inactive, we will restore its build plan during the trigger. This is already implemented, we just need to change the check in the client now.

trigger-inactive

### CODE REVIEW

**Comment by thilo-behnke** [comment]
This works well locally, but not on the test server.
I saw the following when debugging this issue:
- First the build plan is restored
- Then a submission is sent to the client per WS
- Then a result is sent to the client per WS, but the submission of the result is not the previously sent submission, but a new one with type 'OTHER'.

Tested with this exercise: #/exercise/1106/participation

**Comment by thilo-behnke** [comment]
> This works well locally, but not on the test server.
> I saw the following when debugging this issue:
> 
> * First the build plan is restored
> * Then a submission is sent to the client per WS
> * Then a result is sent to the client per WS, but the submission of the result is not the previously sent submission, but a new one with type 'OTHER'.
> 
> Tested with this exercise: #/exercise/1106/participation

I tested this a couple of more times, the issue now only happens rarely and doesn't seem to be connected to the feature. Maybe we have to investigate this issue more deeply in another PR.

**Comment by krusche** [comment]
I think I know why this happens. Due to the empty setup commit, the result does not find the earlier submission with its commit hash. Therefore it creates another one.
I think we need to change the order only in this case: 
1) resume the exercise without empty setup commit if necessary
2) create the submission ok Artemis side
3) trigger the build
4) empty setup commit (if necessary)

**Comment by krusche** [comment]
We changed the empty commit order in `develop`. The code in this PR looks good, but we should test the issue mentioned by @thilo-behnke quickly once on the test server before we merge

**Comment by krusche** [comment]
I think I solved the problem in `develop`, so I will merge this and further test if everything works correctly on `develop`

**Pull request merged**
