### PR TITLE
Change the 'assessment' route to 'submissions'

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context

The route name was inconsistent with what the page actually does (and how the button to it is called): It shows the submissions of an exercise. This also caused the breadcrumbs to not work properly when inspecting an individual submission and trying to go back to "Submissions".

### Description

We change `/assessment` to `/submissions`.

### Steps for Testing

For both course and exam:
1. Check that you can access the "Submissions" page of every exercise type without error
2. Go to an individual submission ("Open Assessment") and navigate back to "Submissions" using the breadcrumbs

grafik

3. Also check that the "Submissions" button in the student's view for a single exercise still works (if you are an instructor viewing an exercise)

### CODE REVIEW

**Review by iozbeyli — DISMISSED** [review]
Code looks good

**Review by sinangunduz — DISMISSED** [review]
tested on ts1, works as expected.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Works as expected

**Review by canyelten — DISMISSED** [review]
Tested on TS1. Works as expected.

**Review by willergeorg — DISMISSED** [review]
Tested on TS1. Worked.

**Comment by FrankeLukas** [comment]
Unfortunately there was one more case I had missed: In the student's view of a single exercise you can also click "Submissions". Changed that link now, too.

**Review by katjanakosic — APPROVED** [review]
Tested on TS1. Looks good to me :)

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 1. Everything worked as expected.

**Review by real-dmy — APPROVED** [review]
Tested on TS2. Works as expected.

**Pull request merged**
