### PR TITLE
[Bugfix] Fix CodeEditor vertical resizing

### PR DESCRIPTION
**Pull request by schultek**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

The code editor could not be resized vertically anymore.

### Description

The resize icon was commented out. It isn't anymore.

### Steps for Testing

1. Log in to Artemis
2. Open the Code Editor
3. Resize vertically.

### Screenshots

Bildschirmfoto 2020-09-25 um 17 40 34

### CODE REVIEW

**Review by anditurdiu — APPROVED** [review]
Works as expected, the code editor can be expanded vertically again without problems

**Review by CanArisan — APPROVED** [review]
Tested on the test server. Resizing works now 👍

**Review by sjagla27 — APPROVED** [review]
Works as expected.

**Review by krusche — APPROVED** [review]

**Review by TobiasPr — APPROVED** [review]
Works as expected

**Review by MaisiKoleni — APPROVED** [review]
Work well for both student view and tutor assessment.

**Review by kloessst — APPROVED** [review]
Works fine for me

**Review by fde312 — APPROVED** [review]
works also for me! 🚀thanks for the fix and sorry again for the inconvenience!

**Pull request merged**
