### PR TITLE
`Development`: Add arm64 docker image

### PR DESCRIPTION
**Pull request by 4ludwig4**
This PR is for now for further testing of the GitHub workflow and will be converted to a real PR as soon as it works.

#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
There is no `arm64` docker image yet and developers have to build it either on their own with emulation on.
On an `amd64` computer, it takes either about 4 hours to just build the _.war_ file in a docker container with Gradle based on an image of Azul Zulu. This probably takes so long because QEMU emulation is used in buildx to build the image for `arm64` on an `amd64` computer. Other docker images as base for the image like temurin take longer than 5h, and I didn't verify that they complete.

### Description
We will now try to follow the approach of using a _.war_ file generated on `amd64` hardware or `arm64` if that is available. Then the following stages like the runtime stage will be built for the targeted architecture. This way our official `arm64` docker images will be "cross compiled" as GitHub just provides `amd64` runners.

:warning: This approach **should not be used for production environments** as the _.war_ file could contain native libraries from third party dependencies! Correct me if I'm wrong! If so, it would crash during runtime?!

Another approach would be to just build the Angular code on `amd64`. I didn't follow this approach further as this would be another build process than how we build Artemis right now for production with Gradle.

### Steps for Testing

Prerequisites:
- arm64 hardware like a M1/M2 from Apple or for instance on an [Oracle Cloud Free Tier Ampere A1 Server ](https://www.oracle.com/de/cloud/free/)

**Build and Run**
1. build docker image
```
cd docker
docker compose build artemis-app --no-cache --progress plain
```
2. run the built artemis docker image and verify it works
```
docker compose -f artemis-dev-mysql.yml up -d
```

**Pull and Run**
1. pull and run the docker image
```
edit docker/artemis.yml to use: image: ghcr.io/ls1intum/artemis:pr-6443
cd docker
docker compose pull artemis-app
docker compose -f artemis-dev-mysql.yml up -d
```

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by jakubriegel — DISMISSED** [review]
The image builds and container starts 👍🏻 

Functionally it is ok. I'd only change that comment to issue.

Tested on MacBook Pro with M1. Commands I used:
```shell
docker compose -f docker/artemis.yml pull
docker compose -f docker/artemis.yml build
docker compose -f docker/artemis.yml up
```

**Review by MaximilianAnzinger — COMMENTED** [review]
Setup: Mac OS X 13.3.1 aarch64
Running: `docker compose -f docker/artemis.yml build`
Issue:
`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':webapp'.`
`Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.`

Shouldn't it use Gradle 8.0.2? (Might be a mistake on my side, correct me if I'm wrong)

**Comment by 4ludwig4** [comment]
> @4ludwig4 Shouldn't it use Gradle 8.0.2? (Might be a mistake on my side, correct me if I'm wrong)

@MaximilianAnzinger first, thanks for testing it! Do you know if you have Rosetta installed, and can you build Artemis natively? I see this warning frequently, and I guess it's just being printed so that you know you have to refactor your Gradle settings before upgrading to version 9. [We should be running version 8.](https://github.com/ls1intum/Artemis/blob/develop/gradle/wrapper/gradle-wrapper.properties)

**Comment by MaximilianAnzinger** [comment]
> Do you know if you have Rosetta installed?

Yes

> Can you build Artemis natively?

Yes

**Comment by 4ludwig4** [comment]
I will tackle this with the feedbag log if there is someone with an Apple Silicon with whom I can debug this.

**Review by Hialus — APPROVED** [review]
Tested on my M1 Pro machine. Works well. :rock:z

Code also 👀z good to me.

**Comment by 4ludwig4** [comment]
@Hialus @MaximilianAnzinger @jakubriegel please reapprove if it works for you. Added documentation about the fact that you need to allocate a lot of memory to docker to get it working!

**Review by Hialus — APPROVED** [review]

**Review by MaximilianAnzinger — DISMISSED** [review]

**Comment by jakubriegel** [comment]
On my side it still doesn't build. I'm on it now

**Comment by 4ludwig4** [comment]
@jakubriegel Thanks for Testing this again! As we just found out for Jakub it just hangs and doesn't even exit with a non zero exit code as it was for @Hialus. Increasing the memory didn't help. Native gradle build works fine without docker. What seems to fail is the npm installation in gradle `Task :npm_install FAILED`. [This might be related to the Gradle node plugin having multiple issues for M1 cpus?](https://github.com/node-gradle/gradle-node-plugin/issues?q=is%3Aissue+m1)

**Review by jakubriegel — APPROVED** [review]
Python-npm problems are gone now. The app builds and starts correctly 👍🏻

Machine: M1 Pro

**Review by Hialus — APPROVED** [review]

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by DominikRemo — APPROVED** [review]
Tested on M1 Max

**Pull request merged**
