### PR TITLE
[Enhancement] Number of SCA issues in result string

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

This PR allows students to directly see, whether static code analysis issues were found.

### Description

- If SCA is enabled, the result string is extended by the following term: ", 1 issue" or ", x issues" if x=0 or x>1. x is the number of visible static code analysis feedback items.

### Steps for Testing

_No hidden tests_
1. Create a programming exercise with SCA
2. Participate in the programming exercise
3. Submit a solution
--> Check if the result string is displayed properly
4. Let the build fail
--> Build failed should be displayed

_Hidden tests_
1. Create a programming exercise with SCA, a release date and activate run after due date
2. Navigate to grading and select `run after due date` for each test case
2. Participate in the programming exercise
3. Submit a solution
--> Check if the result string is displayed properly (0 of 0 passed, x issues found)
4. Let the build fail
--> Build failed should be displayed

### Test Coverage

Adapted old tests to check for the enhanced result string

### Screenshots

image

### CODE REVIEW

**Review by tiffca — APPROVED** [review]
All tests passed successfully/as described, good job! 

Example for non-hidden: 
image

**Review by stefanwaldhauser — APPROVED** [review]
Can confirm result of @tiffca. Works as described!
image

**Review by anditurdiu — APPROVED** [review]
works as expected, nice work :)

**Review by fde312 — APPROVED** [review]
Code looks good and everything works as expected! Good job 🚀

**Review by FuchsDominik — APPROVED** [review]
Can confirm these findings. 
Capture

**Review by schultek — APPROVED** [review]
Works as expected. Nice addition to the result.

**Pull request merged**
