### PR TITLE
Convert build plan buttons to links

### PR DESCRIPTION
**Pull request by julian-christl**
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [ ] Client: I translated all newly inserted strings into English and German.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context
Links to repositories of programming exercises are links and therefore one can open them directly in a new tab. The build plans, however, are still implemented as buttons that have the annoying property of only being left-clickable.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. ...

### CODE REVIEW

**Review by MaisiKoleni — COMMENTED** [review]
*Because you asked for early feedback in the form of a comment:*

First off, good to see that annoying button changed into a link. I am surprised though by the number of changes introduced for that. Some we can simplify, and others maybe as well.
 - You can get rid of the `InfoService` and just inject the value like it is done in the `ExerciseService`:
   https://github.com/ls1intum/Artemis/blob/75a1538b1b2e9844cf9ee6d602ae1bb82976b975/src/main/java/de/tum/in/www1/artemis/service/ExerciseService.java#L45-L49
- If you have added a transient field in the participation, why are you using the DTOs in addition to that? When reading the code, I just expected the field to be set in the correct method and then used in the client.
- I am not happy with the DTOs:
   - The TypeScript DTOs have a type hierarchy, but the Java ones don't.
   - I sort of see why the CI DTO exists, but it is basically a reduced form of a participation, is that correct? Since we already load/loaded the participations where we use the build plan ID, we could use your new transient attribute as well, I assume. This needs fewer major changes and much less code.
   - In general, I would suggest to talk to Stephan or Jan about the DTO changes, as I regard that as a major change. You also need to consider that we now have to mechanisms that are used in parallel, the Exercise DTO for only one thing and the domain objects for almost everything else. I made a bad experience in Artemis with similar problems being solved in multiple ways. But really ask Stephan/Jan about their opinion, as  otherwise, this is an easy way to end up with the work being discarded (so it was a good Idea to ask now).
 - The formatting does not match the one we use in the project, you can run `spotless:apply` (I hope that's correct) and configure you IDE (e.g. max line length of 180, bracket pos., import ordering)
 - I would be careful with DTOs in the service because it might prevent method reuse inside the service (`getAllProgrammingExercisesForCourse` for example).
 - As there are many changes, I probably haven't understood everything properly, but I hope I could help. Another problem might be that there is a lot of testing needed that everything still works.

I would suggest focusing this PR on the change into a link alone, and talk with Stephan and Jan about the refactoring of many parts here and make a future PR out of that if necessary.

**Comment by MaisiKoleni** [comment]
It also seems that the methods are reordered? At least, some classes have many changes they should not have, I think, even if we include your intentions.

**Comment by julian-christl** [comment]
@MaisiKoleni Thanks for the feedback. Yeah, quite possibly I didn't have a second look after using auto reformatting. I reset three files and applied spotless so this should be fine again.

Regarding your other comments:
I can see that this change doesn't make much sense at the moment since it's not part of the scope. I personally like DTOs because they implement the principle of single responsibility => If I introduce some attribute that only a few TS components need, I don't need to share those with all of them because especially when loading tables with a lot of information, this can slow down quite a lot if you don't sit at Uni with a 1 GB/s

I understand that it's not convenient having two things covering a similar area at the same time, however, you can't prevent that if you want to have small PRs

I think for now I will save these changes in a local branch, reset this one and just fix this issue by adding transient attributes as you suggested. Makes the most sense 👍

**Comment by MaisiKoleni** [comment]
@julian-christl Please note that I cannot decide that, I can only give you my estimation on the reaction. In the end, you will need to ask Stephan here. I just want to stress this here because in the past my opinion on things was used as sole decision basis and Stephan was not happy with that.

**Comment by julian-christl** [comment]
@MaisiKoleni No worries. I don't copy opinions from others but change my opinion based on new facts :D
And in this case, I can just see for myself that it makes more sense to do the fix and a potential refactoring separately.

**Comment by julian-christl** [comment]
For the record, I'll leave this PR closed since it contains information not relevant to the final code and will open a new one.

**Pull request closed without merging**
