### PR TITLE
[Bugfix] Fix re-evaluate bug for programming exercises

### LINKED ISSUE #3203: Internal Server Error @ "Re-Evaluate All"
### Describe the bug
We got an Internal Server Error caused by `org.hibernate.LazyInitializationException` while re-evaluating the submissions after changes to the grading schema.

#### To Reproduce
1. Create a Programming Exercise
2. In Grading: Set some test to "After Due Date"
3. Create a Submission (and wait for tests finished)
4. In Grading: Change "After Due Date" to "Never"
5. Click on Re-evaluate all -> Internal Server Error

#### Expected behavior
The Re-evaluation shall start.

### Environment

<details><pre>
 - OS: Windows 10
 - Firefox Stable
 - https://github.com/kit-sdq/Artemis-SAML2-Test-Docker (v. 4.11.3)
</pre></details>

#### Output of the Server

<details><pre>
artemis-be_1  | 2021-04-13 11:21:26.390 DEBUG 10 --- [nio-8080-exec-9] d.t.i.w.artemis.config.ApiVersionFilter  : Adding Version to Request PUT /api/programming-exercise/9/grading/re-evaluate
artemis-be_1  | 2021-04-13 11:21:26.395 DEBUG 10 --- [nio-8080-exec-9] a.w.r.ProgrammingExerciseGradingResource : REST request to reset the weights of exercise 9
artemis-be_1  | 2021-04-13 11:21:26.488 ERROR 10 --- [nio-8080-exec-9] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
artemis-be_1  |
artemis-be_1  | org.hibernate.LazyInitializationException: could not initialize proxy [de.tum.in.www1.artemis.domain.Submission#38] - no Session
artemis-be_1  |         at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:170)
artemis-be_1  |         at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:310)
artemis-be_1  |         at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:45)
artemis-be_1  |         at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:95)
artemis-be_1  |         at de.tum.in.www1.artemis.domain.Submission$HibernateProxy$trUcwifM.getType(Unknown Source)
artemis-be_1  |         at de.tum.in.www1.artemis.domain.participation.Participation.lambda$findLatestResult$0(Participation.java:212)
artemis-be_1  |         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
artemis-be_1  |         at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
artemis-be_1  |         at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
artemis-be_1  |         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
artemis-be_1  |         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
artemis-be_1  |         at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
artemis-be_1  |         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
artemis-be_1  |         at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
artemis-be_1  |         at de.tum.in.www1.artemis.domain.participation.Participation.findLatestResult(Participation.java:213)
artemis-be_1  |         at de.tum.in.www1.artemis.domain.participation.Participation.findLatestResult(Participation.java:189)
artemis-be_1  |         at de.tum.in.www1.artemis.service.programming.ProgrammingExerciseGradingService.lambda$updateAllResults$1(ProgrammingExerciseGradingService.java:261)
artemis-be_1  |         at java.base/java.util.Optional.flatMap(Optional.java:287)
artemis-be_1  |         at de.tum.in.www1.artemis.service.programming.ProgrammingExerciseGradingService.updateAllResults(ProgrammingExerciseGradingService.java:261)
artemis-be_1  |         at de.tum.in.www1.artemis.web.rest.ProgrammingExerciseGradingResource.reEvaluateGradedResults(ProgrammingExerciseGradingResource.java:72)
artemis-be_1  |         at de.tum.in.www1.artemis.web.rest.ProgrammingExerciseGradingResource$$FastClassBySpringCGLIB$$8c8b28fe.invoke(<generated>)
artemis-be_1  |         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
artemis-be_1  |         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
artemis-be_1  |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
artemis-be_1  |         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
artemis-be_1  |         at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61)
artemis-be_1  |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
artemis-be_1  |         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
artemis-be_1  |         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
artemis-be_1  |         at de.tum.in.www1.artemis.web.rest.ProgrammingExerciseGradingResource$$EnhancerBySpringCGLIB$$d48e4f34.reEvaluateGradedResults(<generated>)
artemis-be_1  |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
artemis-be_1  |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
artemis-be_1  |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
artemis-be_1  |         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
artemis-be_1  |         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
artemis-be_1  |         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
artemis-be_1  |         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
artemis-be_1  |         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
artemis-be_1  |         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
artemis-be_1  |         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
artemis-be_1  |         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
artemis-be_1  |         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
artemis-be_1  |         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
artemis-be_1  |         at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920)
artemis-be_1  |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:526)
artemis-be_1  |         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
artemis-be_1  |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
artemis-be_1  |         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
artemis-be_1  |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
artemis-be_1  |         at de.tum.in.www1.artemis.config.ApiVersionFilter.doFilter(ApiVersionFilter.java:46)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
artemis-be_1  |         at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
artemis-be_1  |         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
artemis-be_1  |         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
artemis-be_1  |         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
artemis-be_1  |         at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at de.tum.in.www1.artemis.security.jwt.JWTFilter.doFilter(JWTFilter.java:36)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
artemis-be_1  |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
artemis-be_1  |         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
artemis-be_1  |         at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
artemis-be_1  |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
artemis-be_1  |         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
artemis-be_1  |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
artemis-be_1  |         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
artemis-be_1  |         at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
artemis-be_1  |         at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
artemis-be_1  |         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
artemis-be_1  |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
artemis-be_1  |         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
artemis-be_1  |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
artemis-be_1  |         at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
artemis-be_1  |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
artemis-be_1  |         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
artemis-be_1  |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
artemis-be_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
artemis-be_1  |         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
artemis-be_1  |         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
artemis-be_1  |         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
artemis-be_1  |         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
artemis-be_1  |         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
artemis-be_1  |         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
artemis-be_1  |         at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
artemis-be_1  |         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
artemis-be_1  |         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
artemis-be_1  |         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
artemis-be_1  |         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
artemis-be_1  |         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
artemis-be_1  |         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
artemis-be_1  |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
artemis-be_1  |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
artemis-be_1  |         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
artemis-be_1  |         at java.base/java.lang.Thread.run(Thread.java:832)
</pre></details>

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I implemented the changes with a good performance and prevented too many database calls

### Motivation and Context

Fixes #3203. 

The re-evaluate functionality for programming exercises required that submission are loaded in other to update the results. Submissions weren't loaded eagerly which resulted in a Hibernate exception.

### Description

This pr fixes the issue by loading the submissions. It also adds an extra check in `findLatestResult` to make sure that submissions are loaded before operating on them.

### Steps for Testing

This pr can only be tested on **TS2**

1. Create a Programming Exercise
2. In Grading: Set some test to "After Due Date"
3. Create a Submission (and wait for tests finished)
4. In Grading: Change "After Due Date" to "Never"
5. Click on Re-evaluate all -> Internal Server Error

### Test Coverage

ProgrammingExerciseGradingService 93%

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS2, worked fine without any errors. Code lgtm too.

**Review by katjanakosic — APPROVED** [review]
Tested on ts2. Worked as expected. No errors.

**Review by JohannesStoehr — APPROVED** [review]
Tested on TS2, works well

**Review by willergeorg — COMMENTED** [review]
Works for me as well!

**Review by NicolasUllmann — COMMENTED** [review]
Tested on server 2. Everything worked as expected.

**Review by nicolasruscher — APPROVED** [review]
Checked it and the code looks good too

**Review by FrankeLukas — APPROVED** [review]
Code changes look logical and couldn't reproduce the error any more.

**Pull request merged**
