### PR TITLE
lecture-attachments-tests

### PR DESCRIPTION
**Pull request by FuchsDominik**
### Checklist
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)

### Description

- client tests for test coverage improvements
- removal of unused method

### Test Coverage

lecture-attachments.component: 96%
attachment.service.ts: 100%
lecture.service.ts: 96%

### CODE REVIEW

**Review by balazs-czopf — APPROVED** [review]
Code lgtm :)

**Review by nicolasruscher — APPROVED** [review]
The code looks good to me :)

**Review by schultek — APPROVED** [review]
Code looks good. 👍

**Review by fde312 — APPROVED** [review]
Looks good to me as well. Good job! 👍

**Review by philippbauch — APPROVED** [review]
Tests all work and the code lgtm ✅

**Review by airelawaleria — APPROVED** [review]
Looks fine!

**Review by marvinchimeka — APPROVED** [review]
Looks great.

**Review by JohannesWeiss — APPROVED** [review]
LGTM 👍

**Review by philgabr — APPROVED** [review]
Looks good to me, as well.

**Review by EneaGore — APPROVED** [review]
All looks in order to me as well.

**Review by krusche — APPROVED** [review]

**Pull request merged**
