### PR TITLE
`Integrated code lifecycle`: Use individual due date in exams for afterDueDate check

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

Pushing to LocalVC after the end date of an exam but before the grace period causes an error 500 instead of a 403.

### Description

Modified the `afterDueDate` check to take individual working times of each student into account instead of checking for the exam end date with grace period which did not make sense in this case.

Fixes issue 10 on [LocalVC/CI Issues](https://confluence.ase.in.tum.de/x/XZjLCw).

#### Exam Mode Testing

**Test on TS3, TS6 or Local CI Staging**
Prerequisites:
- 1 Student
- 1 Exam with a Programming Exercise

1. As a student, participate in the exam
2. Try to push to the exercise repository (using local git) during the exam conduction, should work
3. After the exam has ended but still within the grace period, try to push again. You should receive a 403 error.

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [StudentExamRepository.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6106/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.repository/StudentExamRepository.html) | 90% | ✅ |
| [ExerciseDateService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6106/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/ExerciseDateService.html) | 100% | ✅ |
| [ExamDateService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6106/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.exam/ExamDateService.html) | 91% | ✅ |

## Summary by CodeRabbit

- **New Features**
	- Enhanced functionality to check for individual exercise working periods based on student participation and submission status.
	- Introduced a method to retrieve specific test runs by exam ID and user ID.
- **Bug Fixes**
	- Updated due date checks in `ExerciseDateService` to correctly handle student participations and other cases with grace periods.
- **Tests**
	- Enhanced readability and maintainability in several test files by centralizing student names and exam creation logic.
	- Adjusted handling of dates and times in test scenarios to reflect real exam conditions, including grace periods.

### CODE REVIEW

**Review by pzdr7 — APPROVED** [review]
Tested on TS3:

- Push during exam -> The repository accepts my push -> works as expected
- Push during grace period -> The requested URL returned error: 403 -> works as expected

**Review by MaximilianAnzinger — APPROVED** [review]
Code lgtm

**Review by milljoniaer — APPROVED** [review]
tested in testing session, works as expected

**Review by reschandreas — APPROVED** [review]
code lgtm

**Review by krusche — APPROVED** [review]
Looks good 👍

**Pull request merged**
