### PR TITLE
WIP: Kotlin Template

### PR DESCRIPTION
**Pull request by nerdsupremacist**
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I added multiple integration tests (Spring) related to the features
- [ ] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [ ] Server: I implemented the changes with a good performance and prevented too many database calls
- [ ] Server: I documented the Java code using JavaDoc style.
- [ ] Client: I added multiple integration tests (Jest) related to the features
- [ ] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [ ] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
We needed to create multiple Kotlin exercises for the PSE Lecture and encountered a lot of issues when just creating them as Java projects. This creates a template with all the extras that we needed to get it running.

### Description
This PR only adds the extra programming language and the necessary template. This PR has not yet been tested. I'm not quite sure how to run it

### Steps for Testing
1. Log in to Artemis
2. Navigate to Course Administration
3. Create a programming exercise with Kotlin as the template
4. The template should perform just like the java template just with Kotlin files instead of Java files
5. Cloning the repository and importing it as a maven project should work out of the box

### CODE REVIEW

**Comment by nerdsupremacist** [comment]
@krusche @jpbernius can you guys help me testing this

**Comment by nerdsupremacist** [comment]
I will also be pushing a PR for Oracle Generation Support for Kotlin ASAP ;)

**Comment by krusche** [comment]
@nerdsupremacist sorry for not responding, but we don't have enough capacity to fully support you at the moment. However, we would really like to see more progress on this PR and get it merged soon.

I can invite you into our team, then you can work on this PR in a feature branch of this repository. This would allow you to deploy it to our test environment so that you can more easily test if the Kotlin template works as expected. Would that help you?

Some feedback: I would prefer if the test suite stays the same for Java and Kotlin builds, otherwise this will be hard to maintain in the future. I guess in Kotlin exercises we can simply copy the one from the java template to avoid duplicating all the files.

**Comment by krusche** [comment]
There is no progress on this PR. We close it for now. If there is more progress, please reopen it.

**Pull request closed without merging**
