### PR TITLE
`Exam mode`: Fix test runs for test exams

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

The exam test runs were not working, because of an oversight introduced in #5370.
Fixes issue no. 1 and (likely) 15 found during [exam mode testing](https://confluence.ase.in.tum.de/pages/viewpage.action?pageId=138610767).

### Description

Bug fixed by not distinguishing between test exams and real exams in `fetchParticipationsSubmissionsAndResultsForExam()`.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam with different exercises

1. Log in to Artemis
2. Navigate to the Exam, then Test Runs
3. Create and participate in the test run
4. Ensure no errors occur
7. Repeat the steps with a _Test Exam_

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

Added test case for the bug.

### CODE REVIEW

**Comment by dangcosta** [comment]
I tested on ts1 and I'm getting this error when I try the test run (and I change from one exercise to another), including when I click on save and continue:

grafik

But when I handed in early, it actually saved all the results. 

Other than that seemed to be all good

**Comment by ge65cer** [comment]
@dangcosta Did you "continue" an existing test run or "start" a new one?

**Comment by dangcosta** [comment]
> @dangcosta Did you "continue" an existing test run or "start" a new one?

I created a new test run in an existing exam, and I also created a new exam and a new test run for the exam. I got in all these cases. I did not try to continue an existing test run, however.

**Review by dangcosta — APPROVED** [review]
The [499bd82](https://github.com/ls1intum/Artemis/pull/5711/commits/499bd82bab104324324a9427a3cd4108768d2ff0) commit fixed the error that I pointed out. The rest worked as expected, and the code looks good to me.

**Review by JohannesStoehr — APPROVED** [review]
Tested locally and looked through the code. Seams to work now

**Pull request merged**
