### PR TITLE
`General`: Improve the responsiveness of the navigation bar for smaller devices

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The navbar has a fixed breaking point for collapsing everything into a menu. This leads to a lot of unused space on certain screen sizes. In the example below, everything would still easily fit into the navbar itself.

grafik

### Description

This PR adds some more advanced responsive behavior to the navbar. If there's not enough space, the links to Course Overview, Course Management and Server Administration are collapsed into the menu, but the icons for notifications, theme and the user menu stay in the menu bar. Then, if there's not enough space for them, they'll be moved into the collapsed menu in a second step.
The breakpoints are approximately and dynamically calculated, taking the length of the login and the available options into account. For example, the breakpoint for the first wrap step needs to be lower if someone doesn't have access to Server Administration.

### Steps for Testing

Prerequisites:
- A user of each type: Student, Instructor, Admin

Test that the navbar collapses correctly for each user type. You should observe different breakpoints for each as they have different navbar options available. Note that the navbar will always leave space for the maximum occupancy (notification badge, disconnected icon, loading spinner) so it might look like it's wrapping too early but it's actually not - and it's not the intention to be 100% precise. It should just not let 1000 pixels of wasted space, but be a bit more intelligent

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| navbar.component.ts | 76% | 86% |

### Screenshots

https://user-images.githubusercontent.com/23171488/178323269-1be0eeb0-128e-479b-850f-a7a7ae20a6f1.mov

### CODE REVIEW

**Review by MetinLamby — COMMENTED** [review]
i think the responsiveness is well implemented. However, I feel like when the navbar is a minimum width, the notification buttons, dark mode, and user drop-down can also be part of the dropdown list instead of being horizontally aligned. This probably simplifies the problem and makes it more consistent from a UI perspective. What do you think?

**Review by jschmautzer — APPROVED** [review]
tested on ts2, worked as described

however, I think this is not looking very nice / intuitively / user-friendly:
nav_bar

**Comment by bassner** [comment]
@jschmautzer The idea is that if you have to click the hamburger menu, your cursor / finger is on the right side; so we've moved the course link to the right side as well so you don't have to swich to the other side. But yes, we could move it to the middle if the majority thinks that this is better. We could also move the icons to the right side as well instead of spreading them 🤷

**Comment by bassner** [comment]
@jschmautzer After discussing this with @krusche we decided to move the third line to the right as well so it looks more aligned. :)
ezgif-3-82b3aba4f4

**Comment by bassner** [comment]
@S-Eibl Interesting. Could you be more precise on the environment you're using? OS, Browser Version etc? I am not able to reproduce this behavior, see below

grafik

**Comment by bassner** [comment]
Hm, @S-Eibl. Tried it on a fresh windows installation with a fresh chrome installation real quick. Still works good :D
Anyone else who can repro this?

grafik

**Review by S-Eibl — APPROVED** [review]
The "Server-Administration" dropdown is working now after I restarted my computer and using the newest version. Maybe something was misconfigured from my side, sorry for the interruption.
Everything looks good

**Review by ge65cer — COMMENTED** [review]
Are the components re-rendered when changing the screen size? The notification bade re-appears after dismissing it when going from large to small display size.

Screenshot 2022-07-14 at 09 02 00

**Comment by bassner** [comment]
@ge65cer I've had a quick look and that's related to a lot of the logic being reloaded in the notification sidebar component when it gets rerendered. It requires some more refactors of it and the notification service so I'll fix that in a follow up

**Review by luisa-we — APPROVED** [review]
Tested on TS1, the navbar works as expected.

**Review by ge65cer — APPROVED** [review]
Code approved. (Previously reviewed issue will be refactored in another PR.)

**Pull request merged**
