### PR TITLE
[Bugfix] Fix 5 star rating for text and file-upload exercises

### LINKED ISSUE #2857: Feedback rating error
### Describe the bug
Feedback rating (5 stars) is not working i.e. when user rates the feedback of tutor using the 5 stars on text-exercises, the system is not saving the rating and gives an error (in console).

#### To Reproduce 
1. Go to any TEXT exercise in artemis (student account) which has been assessed (graded) by tutor with feedback also provided by the tutor. 
2. Click on 'view results'
3. Scroll down to 'How useful is the feedback for you?'
4. If the user provides the rating using the stars, the system is not saving the ratings and gives error in console

#### Expected behavior
System should save the rating provided
Screen Shot 2021-02-10 at 8 26 08 PM

#### Screenshots
attached screenshot

### Environment 
<details><pre>
 - OS: MacOS
 - Browser: Chrome
 - Version 88.0
</pre></details>

#### Output in Web Console

<details>
Error in file instrument.js:109
<pre>
ERROR TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'submission' -> object with constructor 'Object'
    |     property 'results' -> object with constructor 'Array'
    --- index 0 closes the circle
    at Object.stringify (<anonymous>)
    at O.serializeBody (http.js:688)
    at s._subscribe (http.js:1613)
    at s._trySubscribe (Observable.js:42)
    at subscribe (Observable.js:28)
    at call (tap.js:16)
    at subscribe (Observable.js:23)
    at a.call (finalize.js:11)
    at subscribe (Observable.js:23)
    at call (tap.js:16)
    at subscribe (Observable.js:23)
    at call (tap.js:16)
    at subscribe (Observable.js:23)
    at call (tap.js:16)
    at subscribe (Observable.js:23)
    at s (innerSubscribe.js:67)
    at s._innerSub (mergeMap.js:57)
    at s._tryNext (mergeMap.js:51)
    at s._next (mergeMap.js:34)
    at s.next (Subscriber.js:49)
    at s._subscribe (subscribeToArray.js:3)
    at s._trySubscribe (Observable.js:42)
    at subscribe (Observable.js:28)
    at call (mergeMap.js:19)
    at subscribe (Observable.js:23)
    at i.call (filter.js:13)
    at subscribe (Observable.js:23)
    at i.call (map.js:16)
    at subscribe (Observable.js:23)
    at g.onRate (rating.component.ts:59)
    at rating.component.html:5
    at rg (core.js:15193)
    at r (core.js:15228)
    at d.o [as _next] (core.js:25888)
    at d.__tryOrUnsub (Subscriber.js:183)
    at d.next (Subscriber.js:122)
    at l._next (Subscriber.js:72)
    at l.next (Subscriber.js:49)
    at th.next (Subject.js:39)
    at th.emit (core.js:25857)
    at d.onRate (ng-starrating.js:150)
    at HTMLSpanElement.o (helpers.js:72)
    at t.invokeTask (zone.js:429)
    at Object.onInvokeTask (core.js:28500)
    at t.invokeTask (zone.js:428)
    at e.runTask (zone.js:200)
    at e.invokeTask [as invoke] (zone.js:511)
    at _ (zone.js:1651)
    at HTMLSpanElement.C (zone.js:1688)
(anonymous) @ instrument.js:109
ki @ core.js:6142
handleError @ core.js:6190
handleError @ sentry.error-handler.ts:51
next @ core.js:29120
o @ core.js:25867
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25857
(anonymous) @ core.js:28539
t.invoke @ zone.js:395
e.run @ zone.js:155
runOutsideAngular @ core.js:28442
onHandleError @ core.js:28539
t.handleError @ zone.js:399
e.runTask @ zone.js:203
e.invokeTask @ zone.js:511
i.useG.invoke @ zone.js:500
o @ zone.js:3059
setTimeout (async)
c @ zone.js:3080
t.scheduleTask @ zone.js:416
onScheduleTask @ zone.js:306
t.scheduleTask @ zone.js:409
e.scheduleTask @ zone.js:243
e.scheduleMacroTask @ zone.js:266
u @ zone.js:711
(anonymous) @ zone.js:3095
I.i.<computed> @ zone.js:1010
(anonymous) @ trycatch.js:86
o @ hostReportError.js:2
error @ Subscriber.js:156
_error @ Subscriber.js:75
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
notifyError @ innerSubscribe.js:45
_error @ innerSubscribe.js:13
error @ Subscriber.js:55
_error @ tap.js:56
error @ Subscriber.js:55
_error @ tap.js:56
error @ Subscriber.js:55
_error @ tap.js:56
error @ Subscriber.js:55
_error @ Subscriber.js:75
error @ Subscriber.js:55
_error @ tap.js:56
error @ Subscriber.js:55
_trySubscribe @ Observable.js:50
subscribe @ Observable.js:28
call @ tap.js:16
subscribe @ Observable.js:23
call @ finalize.js:11
subscribe @ Observable.js:23
call @ tap.js:16
subscribe @ Observable.js:23
call @ tap.js:16
subscribe @ Observable.js:23
call @ tap.js:16
subscribe @ Observable.js:23
s @ innerSubscribe.js:67
_innerSub @ mergeMap.js:57
_tryNext @ mergeMap.js:51
_next @ mergeMap.js:34
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:19
subscribe @ Observable.js:23
call @ filter.js:13
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
onRate @ rating.component.ts:59
(anonymous) @ rating.component.html:5
rg @ core.js:15193
r @ core.js:15228
o @ core.js:25888
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25857
onRate @ ng-starrating.js:150
o @ helpers.js:72
t.invokeTask @ zone.js:429
onInvokeTask @ core.js:28500
t.invokeTask @ zone.js:428
e.runTask @ zone.js:200
e.invokeTask @ zone.js:511
_ @ zone.js:1651
C @ zone.js:1688
Show 69 more frames</pre></details>

### PR DESCRIPTION
**Pull request by derLalla**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Feedback rating (5 stars) is not working i.e. when user rates the feedback of tutor using the 5 stars on text-exercises. The system is not saving the rating and gives an error (in console). Also the 5 stars are not shown for file-upload exercises.
Fixes #2857 

### Description

The circular dependency in the result object gets now removed and a participation for the file-upload result gets added, so that the 5 stars can be shown.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to any text or file-upload exercise (student account) which has been assessed (graded) by tutor with feedback also provided by the tutor or create a new text or file-upload exercise, participate, assess it with a tutor and login again as a student
4. Click on 'view results' and scroll down to 'How useful is the feedback for you?'
5. If the user provides the rating using the stars, the system saving the ratings and don't throws an error in the console

### Test Coverage

No changes.

## Showing 5 star rating in File-Upload Exercise Result:
image

## Http Status OK after click on rating:
image

### CODE REVIEW

**Review by sebastiantpeter — APPROVED** [review]
Tested on ts3. Encountered no errors.

**Review by EneaGore — APPROVED** [review]
Seems to be fine on ts3

**Review by airelawaleria — APPROVED** [review]

**Review by simonzilker — APPROVED** [review]

**Review by marvinchimeka — APPROVED** [review]
No issues found

**Review by JohannesWeiss — APPROVED** [review]
Works without issues on ts3

**Review by FuchsDominik — APPROVED** [review]
Code changes also look reasonable :)

**Review by stefanwaldhauser — APPROVED** [review]
Code looks finde and works fine :) Gj

**Review by krusche — APPROVED** [review]

**Pull request merged**
