### PR TITLE
`Text exercises`: Fix breadcrumbs during assessment

### LINKED ISSUE #6778: Broken breadcrumb link in text assessment view
### Describe the bug

A console error appears when clicking on the "Submissions" part in the breadcrumbs on the top in the text assessment view.

### To Reproduce

1. Go to the exercise dashboard of any text exercise with existing submissions (as tutor or higher)
2. Go to the assessment view
3. Click on the "Submissions" link on the top (see screenshot)
4. See error message appear in the DevTools console in Chrome.

### Expected behavior

No error appears.

### Screenshots

screenshot-2023-06-27_001472

### Which version of Artemis are you seeing the problem on?

6.3.2

### What browsers are you seeing the problem on?

Chrome

### Additional context

The error from the logs hints at a missing child route. Probably, the "submissions" part should not be a link at all.

### Relevant log output

```shell
ERROR Error: Uncaught (in promise): Error: NG04002
Error: NG04002
    at ln.noMatchError (router.mjs:3655:16)
    at router.mjs:3670:28
    at catchError.js:10:39
    at t._error (OperatorSubscriber.js:23:21)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at t._error (Subscriber.js:64:30)
    at t.error (Subscriber.js:40:18)
    at T.C [as _subscribe] (throwError.js:5:45)
    at T._trySubscribe (Observable.js:37:25)
    at Observable.js:31:30
    at t (errorContext.js:19:9)
    at T.subscribe (Observable.js:22:9)
    at catchError.js:23:27
    at t.<anonymous> (lift.js:10:28)
    at Observable.js:26:30
    at t (errorContext.js:19:9)
    at T.subscribe (Observable.js:22:9)
    at W (mergeInternals.js:19:44)
    at H (mergeInternals.js:14:57)
    at t._next (OperatorSubscriber.js:13:21)
    at t.next (Subscriber.js:31:18)
    at T._subscribe (innerFrom.js:51:24)
    at T._trySubscribe (Observable.js:37:25)
    at Observable.js:31:30
    at t (errorContext.js:19:9)
    at T.subscribe (Observable.js:22:9)
    at u (mergeInternals.js:50:12)
    at mergeMap.js:13:44
    at t.<anonymous> (lift.js:10:28)
    at Observable.js:26:30
    at t (errorContext.js:19:9)
    at T.subscribe (Observable.js:22:9)
    at scanInternals.js:7:16
    at t.<anonymous> (lift.js:10:28)
    at Observable.js:26:30
    at t (errorContext.js:19:9)
    at T.subscribe (Observable.js:22:9)
    at defaultIfEmpty.js:6:16
    at t.<anonymous> (lift.js:10:28)
    at Observable.js:26:30
    at Q (zone.js:1193:31)
    at Q (zone.js:1147:17)
    at zone.js:1260:17
    at _.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (core.mjs:26236:33)
    at _.invokeTask (zone.js:401:60)
    at j.runTask (zone.js:171:47)
    at p (zone.js:581:35)
    at E.invokeTask [as invoke] (zone.js:487:21)
    at O (zone.js:1631:18)
    at I (zone.js:1674:33)
    at HTMLAnchorElement.M (zone.js:1695:16)
```

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

Fix #6778

### Description

The text exercise was the only one that used the participationId in the browser URL as well. This also affected the breadcrumbs that could not handle that "participations" were followed by "submissions".
This PR unifies the browser URL of text exercises as well as the REST URL of `retrieveParticipationForSubmission` with the other exercise types to not use the participation id.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Text Exercise

1. Log in to Artemis
2. Participate in the text exercise as student
3. Assess the exercise as tutor and check that everything (starting, continuing, submitting the assessment, ...) still works.
4. Check that the breadcrumbs during the assessment work as expected. "submissions" should redirect to the scores page.

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Text Exercise

1. Log in to Artemis
2. Participate in the text exercise as student
3. Assess the exercise as tutor and check that everything (starting, continuing, submitting the assessment, ...) still works.
4. Check that the breadcrumbs during the assessment work as expected. "submissions" should redirect to the scores page.

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
Code looks good, I like that `getLinkToSubmissionAssessment` is singinficantly less complex now 👍

**Review by terlan98 — APPROVED** [review]
Code LGTM 👍 
Please ping me when this PR is merged so that I can adjust the endpoint in Themis 🙂

**Review by SolizerCodes — APPROVED** [review]
Tested non-exam exercise on ts6, looks good 👍

**Review by RY997 — APPROVED** [review]
Code LGTM and worked well on ts2

**Review by MichaelOwenDyer — APPROVED** [review]
Works as described, looks good to me 👍🏽

**Review by SabrinaGlatz — APPROVED** [review]
tested on ts4, works as expected

**Review by dakennguyen — APPROVED** [review]
tested on ts1, works as expected!

**Pull request merged**
