### PR TITLE
`General`: Navigate to the details view after creation or import of text and modeling exercises

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context

#5382 added an automated navigation from a lot of entity update views to the detail views after saving them, for example for some exercise types. However, text and modeling exercises currently navigate to the example submissions page after creating or importing them, which is inconsistent.

### Description

Artemis will now navigate to the detail view of text and modeling exercises after creating or importing them.
This PR also removes the creation success alerts like it did for the other entity types as a forward to the details page of a new exercise makes it obvious that it now exists.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. [Create, import] a [text, modeling] exercise
2. Verify that the app forwards you to the details page of that exercise after it was saved
3. Verify that you did **not** get a green success alert in the top right

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by Strohgelaender — DISMISSED** [review]
Code looks good.

**Review by jschmautzer — COMMENTED** [review]
tested on ts2
- for text and modeling exercises it correctly forwards you to the details page of that exercise after it was saved (tried with creation and import)
- but in case of modeling exercises (tried with creation and import) the green success alert still appears:
alert

**Review by MetinLamby — COMMENTED** [review]
tested on ts3 and created an exercise: I am redirected to the details page but I also still get a green alert message on the top right corner

**Comment by bassner** [comment]
@jschmautzer @MetinLamby Oops, seems like I didn't remove the alerts for modeling exercises. Good catch!
I've removed them in 5fbb3d7. Could you please give it another shot? Thanks!

**Review by maximiliansoelch — DISMISSED** [review]
Tested on TS1, works as described. Code LGTM 👍

**Review by luisa-we — DISMISSED** [review]
Tested on TS1, works as expected!

**Review by pantageepapa — DISMISSED** [review]
Tested on ts2 and works as expected :)

**Review by JohannesStoehr — DISMISSED** [review]
Code looks good

**Review by sleiss — DISMISSED** [review]
Code changes look good

**Comment by bassner** [comment]
Just removed an outdated alert and fixed some Cypress code. Previous tests can be considered valid

**Review by sleiss — APPROVED** [review]
Reapprove

**Review by maximiliansoelch — APPROVED** [review]
Reapprove

**Review by krusche — APPROVED** [review]

**Pull request merged**
