### PR TITLE
Improve processing of multi-line result error messages

### PR DESCRIPTION
**Pull request by b-fein**
### Motivation and Context
#2105 introduced a post-processing step to Java result error messages. The implementation cut all results at the first newline character. This resulted in longer multi-line error messages being no longer shown to users as intended.
This PR applies the intended removal of Junit-Prefixes from the error messages, but implements it in such a way that multi-line messages are no longer cut off.

### Description
If multiple error messages are part of the testcase, the implementation adds an additional newline between them to visually separate different (potentially multi-line by themself) messages.

### Test Coverage
- FeedbackService.java: 93%

### CODE REVIEW

**Review by MaisiKoleni — COMMENTED** [review]
I think this is an excellent change as this has always been hard and ugly to work around 👍 

I just have some a few remarks/questions:
- Artemis never supported multiline error messages (for Java) for the time I know it, this has not changed in #2105.
- How are stack traces handled?
  As far as I know, using only the first line was motivated by the goal to keep the error messages short and not display any stack traces. I haven't tested the PR yet, so I could be wrong, but it seems likely they are not part of the error message. (Maybe one could provide an option here, but I am not sure this is inline with Artemis philosophy)
- How does this look in the client / for the students? Could you provide a screenshot what this will look like?
  This would also directly show what happens with the stack trace of a test failure.

**Comment by b-fein** [comment]
One can add newlines to failure messages. Output of a test case with `fail("BubbleSort does not sort correctly\nAdditional Line");` (modified `SortingExampleBehaviorTest.java`):
Screenshot_20201020_120843

As far as I can tell Artemis looks if a failure `message` attribute is present in the JUnit-XML to decide if a test was successful or not. At which point however the `java.lang.AssertionError` becomes part of the message, I’m not sure.
The raw JUnit-XML still contains the stack trace, but it is not part of the String that is post-processed:
```xml
<failure message="BubbleSort does not sort correctly&#10;Additional Line" type="java.lang.AssertionError">java.lang.AssertionError: 
BubbleSort does not sort correctly
Additional Line
	at pr.SortingExampleBehaviorTest.testBubbleSort(SortingExampleBehaviorTest.java:39)
</failure>
```
This also means that a unit-test that contains `assertTrue(false)`passes according to Artemis, one containing `assertTrue("Failure message!", false)` does not.

At that point I’m not sure if it is even possible to have multiple lines with `java.lang.AssertionError: …`, or if that is possible for the first line of a message only, as the unit-test exits at the first failing assertion.
This would mean I could simplify the code to only replace it once and not consider the possibility of multiple messages present for post-processing.


We definitely need the multi-line functionality, as we use Dejagnu for blackbox-tests and have to use the JUnit-XML to wrap the stdout to get it somehow back to Artemis (if there is a better way we do not know about, feel free to let us know).

**Comment by axel1200** [comment]
@b-fein While I get why multi-line messages are no processed correctly, I don't understand what this has to do with Assertions without a message failing :(

**Comment by axel1200** [comment]
Now I read the code and make sense. Cause `errorList.isEmpty()` defines if test is successful. And errorList is empty if there is no message...

**Comment by krusche** [comment]
Artemis would like to show the feedback messages of tests (based on assertions) to students to help them understand their failures. Depending on the configuration (hidden vs. visible test), the feedback is helpful during or after the working time.

We never intended the use of assertX(...) without error messages, so this is an edge case that you have found here.

I think we should still fix the issue behind this, the question however is what we then show to the student. (Note that some students are in their first semester, so showing too technical error messages such as stack traces might not be helpful)

**Comment by krusche** [comment]
@b-fein thanks for this contribution. If you send me your email address to krusche@in.tum.de I can also invite you into our Slack channel. It might be easier to get some support there.

Would you mind fixing the issue related to empty assert messages in this PR as well?
Would also be great if you could resolve the merge conflict.

**Comment by b-fein** [comment]
@krusche I also implemented a fix for the issue. Now tests are only considered successful if both the error and failure lists are empty regardless of their respective messages.

The ErrorDTO/FailureDTO only contain messages and have no information about the stack-trace. Therefore, the only message I could add to the user feedback is either a static generic one or one based on the type of the error/failure.
I decided to add one based on the type if possible, as this at least gives some hint about the origin of the failure at least for Java, e.g. if it was a NullPointerException or a failed assertion. The message shown to the user is then for example:
`Unsuccessful due to an error of type: java.lang.AssertionError`
If the type is not known, too, then no special message is created.

Of course, if any proper message is present, then that is always used, same as before.

**Review by MaisiKoleni — COMMENTED** [review]
@b-fein I now had another look at the PR and we were both right:
- If you used Bamboo, the post-processing has been there before (for a long time as far as I know).
- If you used Jenkins, there was no such post-processing before the PR.

So the behavior of GitLab + Jenkins now matches the one of Bitbucket + Bamboo a lot better.

The multiline error messages should be supported though (now for both), and if the stack traces are not shown,
we should just use the complete message and replace the first `java.lang.AssertionError` or `org.opentest4j.AssertionFailedError` in a line, if present.

Checking if a test case failed by looking at the errors reported and not the message is definitively an improvement, thanks for that 👍 

I would suggest (maybe you know of a nicer alternative; we could also use a Set of exception names and make a regex out of that)
```java
Pattern.compile("^(?:java\\.lang\\.AssertionError|org\\.opentest4j\\.AssertionFailedError): \n*", Pattern.MULTILINE)
```
and
```
pattern.matcher(message).replaceAll("")
```
to get the simplified message (we could also be more restrictive and remove `MULTILINE`). This would transform
```
java.lang.AssertionErro: expected:
   4
but was:
   5
```
into
```
expected:
   4
but was:
   5
```
and
```
org.opentest4j.AssertionFailedError: 
message is only here on the next line:
  expected: 
    [] 
  to contain:
    ["Java"]
```
into
```
message is only here on the next line:
  expected: 
    [] 
  to contain:
    ["Java"]
```

Concerning the change in the `JenkinsService`, I think this is a good idea, and it would be good to have something like that for Bamboo as well. Maybe this could be moved to the feedback service as well?

(For `NullPointerException`s, this should no longer be a problem because of JEP 358 Helpful NullPointerExceptions: `Cannot invoke "String.concat(String)" because "x" is null` is e.g. what I get when testing on our Jenkins+GitLab setup.)

I also have some improvements and compensation in https://github.com/ls1intum/artemis-java-test-sandbox as JUnit 5 extension because the extension knows the stack trace elements, failures and classes much better at runtime. (When this is merged, I will be able to remove the current multiline processing).

Please let me know what you think, this became a lot longer now than I thought.

**Comment by b-fein** [comment]
@MaisiKoleni  I now implemented the matching and removing of the exceptions via the pattern.
e.g.
```
java.lang.AssertionError: expected:
    4
but was:
    5
org.opentest4j.AssertionFailedError: expected:
   something else
```
will be turned into
```
expected:
    4
but was:
    5
expected:
    something else
```

> Concerning the change in the JenkinsService, I think this is a good idea, and it would be good to have something like that for Bamboo as well. Maybe this could be moved to the feedback service as well?

In the BambooService [1] the underlying data model [2] is different from Jenkins, i.e. the info if success/failed is directly linked to the job already and there is no failure type. The error strings seem to be just part of the response sent to Artemis and as far as I can tell are used as received from the Bamboo plug-in.

[1] https://github.com/ls1intum/Artemis/blob/914effb8556ae7f3287b2710f35fc6f9cd87f0cc/src/main/java/de/tum/in/www1/artemis/service/connectors/bamboo/BambooService.java#L708
[2] https://github.com/ls1intum/Artemis/blob/0949e556fc83e6b4d93d6ad1503bc9cd94a2c285/src/main/java/de/tum/in/www1/artemis/service/connectors/bamboo/dto/BambooBuildResultNotificationDTO.java#L329

**Comment by tiffca** [comment]
if this needs to be tested, I'm not sure how to test this!

**Comment by snowball77** [comment]
I tested it against our setup and it perfectly works. I can confirm that it fixes #2273. If I can be of any help with further testing or code reviewing to get it merged, just let me know. I will continue to run this branch, as #2273 is a blocker for us.

**Comment by MaisiKoleni** [comment]
We now have the following problem for our Bitbucket/Bamboo, we get parts of the stack trace:

image

We will have to find a way to unify that somehow.

**Comment by MaisiKoleni** [comment]
We might need a fix for this in the notification plugin.

Also, Bamboo cannot deal with multiline error messages:

image

and

image

They are displayed twice while they only appear once in the logs.

**Comment by krusche** [comment]
@b-fein if we cannot easily fix the issue with Bamboo, I suggest that we move the code that leads to problems completely into the JenkinsService. This way, we could avoid those issues.

Of course, I am also happy if we find a solution that supports both scenarios.

Do you think we can merge the updated fix (including testing and review) until tomorrow evening, so that it still fits into the next milestone / release?

**Comment by b-fein** [comment]
@krusche I added a commit that reverts `FeedbackService` to the same processing that was done before this PR and moved the (for now) Jenkins-specific processing into `JenkinsService`.

**Review by MaisiKoleni — APPROVED** [review]

**Review by kloessst — APPROVED** [review]

**Pull request merged**
