### PR TITLE
`General`: Fix tooltip in student statistics if exercise is only started

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Given the situation that the user only presses "start exercises", the corresponding bar in the horizontal bar chart of the respective exercise type currently shows an incorrect tooltip indicating that the user participated on the exercise but after the due date.
This is tooltip is fixed in this PR.
### Description

I added an additional check that triggers the correct tooltip if the situation explained above occurs.
### Steps for Testing

Prerequisites:
- 1 Student
- 1 Exercise (the type can be arbitrary)

1. Log in to Artemis
2. Press "Start exercise" of the corresponding exercise
3. Navigate to the statistics tab
4. Hover over the corresponding bar. Make sure that the tooltip displays that you did not participate on the exercise yet.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Nothing changed
### Screenshots

The current tooltip:
image

The correct tooltip:
image

### CODE REVIEW

**Review by ole-ve — APPROVED** [review]
Tested on TS1, works as described 👍
Code changes also look good to me.

**Review by baranimo7 — APPROVED** [review]
Tested on ts2 with an programming exercise. Works correctly.

**Review by b-fein — APPROVED** [review]
Code review: :+1:

**Review by martindevtum — APPROVED** [review]

**Review by Hialus — APPROVED** [review]
Tested locally. Works as expected.
Code changes are also reasonable.

**Pull request merged**
