### PR TITLE
`Development`: Make copying feedback with attached long feedback text more robust

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
For manual assessments the feedbacks of a submission get copied into a new one. This did not always work for long feedback texts attached to feedbacks probably due to some lazy fetching being too lazy.

### Description
During the copy process now explicitly fetches long feedback texts if the lazy fetching did not do so automatically.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Instructor
- 1 Programming Exercise with manual assessment enabled

1. Add a programming exercise test case that produces a long feedback message, e.g. by adding a `fail("abc".repeat(10_000));` inside the test.
2. As the student: Submit to the exercise.
3. As instructor: Start the manual assessment.
4. The long feedback for the previously defined test case should be loaded in the feedback details view when clicking on the result string (_x%, y of z passed_).
   - The long feedback test case should end with `[...] ...` when folded.
   - When unfolding with the `> ` symbol it should show the full long feedback or a download link from which you can download the full text.

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| FeedbackService.java | 100% | ✅                           |

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code lgtm

**Comment by dfuchss** [comment]
I'll have a look at it tomorrow :) Thanks for the fix.

**Review by dfuchss — APPROVED** [review]
Code looks good to me!

**Review by chrisknedl — APPROVED** [review]
Code lgtm, also tested on my local setup, and works as intended.

**Review by valentin-boehm — APPROVED** [review]
Tested locally

**Pull request merged**
