### PR TITLE
`Text exercises`: Hide feedback section when tutor has assessment lock after deadline

### LINKED ISSUE #1575: Students see submission as assessed after assessment due date when tutors holds lock
### Describe the bug

If the assessment due date is over and the student views his submission, the submission is displayed as assessed when a tutor has acquired a lock for the task. 
The student sees the text "Your assessed submission", it is not possible to see the actual assessment before the tutor submits the assessment.
_(in the overview the task is still shown as unassessed)_

#### To Reproduce

0. Create a Text Exercise
0.1 At least 1 students submission is needed
0.2 Set the due date and assessment due date to the current time 
1. Login as a tutor T and acquire a lock for the submission of student S
2. Login as student S and view the submission
3. "Your assessed submission" will be displayed
4.  Login as tutor T and cancel the assessment of student S's submission
5. Login as S, view the submission, see that "Your assessed submission" is no longer displayed

#### Expected behavior

The student should not see the text "Your assessed submission" since this is misleading and may lead to discussions.
_It's an edge case, normally the submissions should be assessed before the assessment due date and the student would have to view his task while a tutor holds a lock for it._

#### Screenshots

showedAsAssessedWhenLockAquired2

### Environment

<details><pre>
 - Windows 10 Pro
 - Chrome (83.0.4103.61)
</pre></details>

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [X] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Fixes #1575 

### Description

I added an explicit check for the case where a result exists, but no feedback (lock). I additionally refactored the section a bit.

### Steps for Testing

Prerequisites:
- 1 Tutor
- 1 Student
- 1 Text exercise with student submission and due date and assessment due date passed

- View the submission as a student: You should be able to submit late
- Acquire a lock for the student submission as tutor
- View the submission as a student: You should not be able to submit late anymore, nothing should indicate that your submission got already assessed
- Remove the lock as tutor
- View the submission as student: You should be able to submit late again

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Before:

Now:

### CODE REVIEW

**Review by Vinicius-Agreste — APPROVED** [review]
Tested on ts1. Seems to be working as expected. Nice bug fix.

**Review by JohannesStoehr — APPROVED** [review]
Additional code looks good.
Do we have a similar structure in a modeling exercise? If so, do we need a similar solution in there as well?

**Comment by julian-christl** [comment]
> Additional code looks good. Do we have a similar structure in a modeling exercise? If so, do we need a similar solution in there as well?

All their own implementations. Seems to be a text-exercise-only problem. Or got already fixed in the meantime (old issue). But as the issue only mentioned text exercises, it's probably been like that since the issue got created.

**Review by PhilipWerz — APPROVED** [review]
Works as expected. "Assement pending" is shown now. Tested on ts1.

**Comment by dfuchss** [comment]
Do you want to show "Assessment Pending" also if no assessment is done but Manual Feedback is enabled.
I'm not sure whether this is currently the case.

**Comment by julian-christl** [comment]
> Do you want to show "Assessment Pending" also if no assessment is done but Manual Feedback is enabled. I'm not sure whether this is currently the case.

@b-fein 
That would be another "issue" tbh. Because right now, it's possible to hand in a ungraded result after the deadline.
The question would be here what our intended workflow is.

For now, I would just like to fix this specific bug.

**Review by Strohgelaender — APPROVED** [review]
code

**Pull request merged**
