### PR TITLE
`Programming exercises`: Improve git-diff view on programming exercise detail page

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

The current displaying of the git-diff on the programming exercise detail page is not very good looking. You have a button at the top and the rough stats at the bottom. It would make sense to combine them.

### Description

This PR moves the button next to the diff stats and modifies it to fit accordingly. While loading the diff, it shows a spinner and opens a modal afterward. 
The modal can now be closed by clicking outside of it.
A small bug that added a 10px margin to all buttons on the detail page instead of only to the button header at the top was fixed as well. This prevented proper centering of buttons next to text.

### Steps for Testing

Prerequisites:
- 1 Instructor/Editor/Tutor
- 1 Programming Exercise

1. Log in to Artemis
2. Navigate to the Programming Exercise Management Detail Page
3. Scroll down
4. See the described git-diff section
5. Hovering on the stats/button works
6. Clicking the button works as described

**Additional request:**
Please let me know if you have any suggestions for better placement of the diff section. I would like to move it further up but am unsure what the best place would be. It is a useful feature when creating and reviewing exercises, so I generally liked the quick access at the top.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Unchanged

### Screenshots
grafik
grafik

### CODE REVIEW

**Comment by joaquinmurcia** [comment]
Tested on TS1. Works as expected:
image
(can't screenshot that the hover works)

**Review by manuelmanso — COMMENTED** [review]
Tested on ts1 and works as expected. Code looks good, and the button/tooltips/modal also look good in my opinion, better than before.

Moving it up would indeed be nice I think, maybe here

**Review by manuelmanso — APPROVED** [review]

**Review by nairaarnez — DISMISSED** [review]
Tested in TS1, the view is as described!

**Review by JohannesStoehr — DISMISSED** [review]
Code changes look good.
Do we actually need tests for getFullGitDiffAsA... for all authorities? I think it should be enough to check the lowest access level if the higher levels don't have any special treatment

**Review by babyygemperor — DISMISSED** [review]
Tested on ts1, works as described

**Review by Hialus — COMMENTED** [review]
.

**Pull request merged**
