### PR TITLE
`Development`: Refactor deprecated Spring HTTP security configuration

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
On Artemis server startup there were a few warnings about using `web.ignoring()` to configure endpoint permissions.

### Description
Refactored them to follow the usual style of `.permitAll()`.

### Steps for Testing
There are no concrete steps for testing, all functions of Artemis should work the same as before. The most likely things to break due to the reorder of the various endpoints in the security config are
- Websocket connections
- receiving global system notifications (can be created using an account with admin permissions), they should then also be visible in a new private tab on the login page
- receiving results from the CI system for new programming exercise results

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

### Screenshots
n/a

### CODE REVIEW

**Review by manuelmanso — APPROVED** [review]
Changes look good, you seem to have followed what is recommended [here](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter)

**Comment by bassner** [comment]
We should have a look at this in testing session

**Review by ge65cer — APPROVED** [review]
Tested different components (programming exercises, websocket notifications, ...) on TS5 and everything still works.

**Review by stefanwaldhauser — APPROVED** [review]
Great refactoring!

**Pull request merged**
