### PR TITLE
[Exam] Bugfix: Do not switch to next exercise if user wants to hand in early

### PR DESCRIPTION
**Pull request by sascha11110**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context
https://github.com/ls1intum/Artemis/issues/1912

### Description
The problem ist that `saveExercise()` is called when the student clicks on *Hand in early*. This method switches to the next exercise and if the user then clicks *Continue* the state of the nav bar is broken. Therefore I've added a flag to `saveExercise()` so that it won't switch to the next exercise.

Additionally, I've ensured that the exercise index will be passed back from the `exam-participation.component` to the `exam-navigation-bar.component` when the students decides to continue.

### Steps for Testing
1. Log in to Artemis
2. Participate in an exam
3. Click on *Hand in early* but to not submit
4. Click on *Continue*
5. Ensure that you are on the same exercise as before

### CODE REVIEW

**Comment by Varnika-Tyagi** [comment]
Works as intended on test server. Unlike @alexmardale , I did not encounter a problem with saving (both my quiz and text answers were saved).

**Comment by sascha11110** [comment]
@alexmardale I wasn't able to reproduce the problem. What exercise type did you use? Could you post the link to the exam on the test server?

**Comment by alexmardale** [comment]
I used all exercise types. (programming might actually be saved for me as well)

It's this exam
TS2
https://artemistest2.ase.in.tum.de/#/course-management/231/exams
Exam: "hand in early"
I think you can still try it with test user 3.

**Comment by alexmardale** [comment]
> I think you can still try it with test user 3.
https://artemistest2.ase.in.tum.de/#/courses/231/exams/72

**Comment by Varnika-Tyagi** [comment]
@alexmardale , I think it's intended behavior, since you do see your answer after coming back from 'Hand in Early' and the nav bar shows 'Exercise not saved'. If you reload at this point, the 'unsaved changes' are lost as intended.
(P.S. Earlier I thought you meant that the answer was lost as soon as you came back from 'Hand in Early', and not on reloading the page)

**Comment by krusche** [comment]
I also think this behavior is ok. Hand in != Save

**Pull request merged**
