### PR TITLE
`Development`: Modernize appearance of quiz statistics

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

This PR is changing the underlying framework for the charts located in quiz statistics from ng2-charts/chart.js to ngx-charts.

### Description

The html templates as well as the underlying logic in the components are refactored in order to fit the requests of ngx-charts.
### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 ( or more) Students
- 1 Quiz containing at least one question of each possible type (MC, DnD, SA)

**Important**: I recommend testing this PR the following way: 
1. Do the steps below one time **before** deploying this PR. 
2. Inspect the old implementation. Maybe take screenshots in order to make the comparison a bit easier.
3. Deploy the PR and re-inspect the charts with the new implementation. 

Alternatively, you can inspect [these statistics](https://artemistest.ase.in.tum.de/course-management/481/quiz-exercises/13559/quiz-point-statistic) on TS1, e.g. with test user 2.

Here are the "original" steps for testing:

1. Log in to Artemis
2. Navigate to Course Administration
3. Set the Quiz visible and start it
4. Participate with the students and submit different answers for each exercise
5. Wait until the working time is finished
6. Switch to the instructor again
7. Navigate to Course Administration
8. In the exercises overview, in the row of the quiz, click on the "Statistics" button
9. Click through the different charts and make sure the displayed information did not change. Also check the behavior when several buttons (e.g. "Show sample solution" or "Show unrated results") are clicked.

Two last comments: 
- I know, the data labels are angled. I know, some of you do not like this. The reason why I decided to leave them angled is the appearance on small screens. Without that angle, the data labels overlap sooner or later. I think it is a more robust solution this way. But feel free to share your opinion on that
- You might notice that the appearance of these bar charts differ a bit from other implementations with `ngx-charts`. The edges of the bars are not rounded here. This is due to an error output I was facing while testing this implementation locally (to be more precise, this error only occurs when the "show (un-)rated results" button is triggered). `d3` seems to have issues when it comes to changing bars representing a non-zero value to zero. It is a bit weird because this error occurred for all charts except the point distribution chart (where the value 0 occurs as well). I did some research and found [this issue thread](https://github.com/swimlane/ngx-charts/issues/498). There, disabling the edge rounding was proposed as workaround, which worked for me. 

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Old design of quiz point distribution:
image

**New** design of quiz point distribution:
image

Old design of Quiz Statistics:
image

**New** design of Quiz Statistics:
image

Old design of MC question statistics:
image

**New** design of MC question statisitcs:
image

Old design of DnD question statistics:
image

**New** design of DnD question statisitcs:
image

Old design of SA question statistics:
image

**New** design of SA question statisitcs:
image

### CODE REVIEW

**Review by Malyuk-A — APPROVED** [review]
Tested on TS1. Thank you for addressing my code feedback.
Code looks good to me now.

**Review by dveljacic — COMMENTED** [review]
Tested on TS1. Found one thing that could be better. As you can see in the attached screenshots, on MC Questions the answers and their markers (A, B, C...) are in different lines for some reason. 
Found it first in the first quiz when I tested the whole PR, then made another quiz just to make sure. Seems to be this odd on both of them. 

Other statistic views are looking good! ✅ 

mc_question_stats
mc_question_stats2

**Review by baranimo7 — APPROVED** [review]
Tested on ts2. Everything works as expected
Ekran Resmi 2021-12-14 13 00 50

**Review by dveljacic — APPROVED** [review]
The bug in my previous comment is not PR-related. It is a common issue on Firefox browsers in all branches. I have created a new issue for that https://github.com/ls1intum/Artemis/issues/4505. 
Tested the changes on TS1 on Chrome, and it looks good. 👍

**Review by DanielKainz — APPROVED** [review]
I tested it on TS1. Everything worked as expected :-).

**Review by MertAksehirlioglu — COMMENTED** [review]
Tested on TS1, works as expected

**Pull request merged**
