### PR TITLE
`Quiz exercises`: Improve layout for short answer matching options

### PR DESCRIPTION
**Pull request by manuelmanso**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Credit to https://github.com/ls1intum/Artemis/pull/5051

Close https://github.com/ls1intum/Artemis/issues/5000

It was "not clear that the two checkboxes and the slider affect the same underlying option about matching the answer text"
Also, it was not clear what the percent slider was used for.

### Description

We visually grouped the two checkboxes and the slider under a border, and placed a header "Answer Matching" to make it more obvious that these options are part of the same setting.
We also added a German translation string for the "Answer Matching" string.

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Management
3. Click on Exercises
4. Click on Create Quiz
5. Click on "Add Short-Answer Question"
6. Check that the Answer Matching div looks as shown in the screenshots and works correctly

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Before

image

#### After

English UI:

image

German UI:

image

### CODE REVIEW

**Review by luisa-we — COMMENTED** [review]
Tested on TS2, the Answer matching div works as expected.
Just a small note:
For some numbers, the % sign is no longer displayed next to the number, but below it. Is there maybe a possibility to adjust this somehow?

Bildschirmfoto 2022-07-16 um 11 56 43

**Comment by manuelmanso** [comment]
> Tested on TS2, the Answer matching div works as expected. Just a small note: For some numbers, the % sign is no longer displayed next to the number, but below it. Is there maybe a possibility to adjust this somehow?
> 
> Bildschirmfoto 2022-07-16 um 11 56 43

Thanks, I improved it!

**Review by luisa-we — DISMISSED** [review]
Tested on TS2, works as expected :)

**Review by alaraozdenler — DISMISSED** [review]
tested on ts1, works as described

**Review by rhubinger — DISMISSED** [review]
Tested on TS2. Works as expected.

**Review by jbllhff — APPROVED** [review]
Tested on ts1, changes work as shown.

**Review by jschmautzer — APPROVED** [review]
tested on ts1, works as described

**Review by babyygemperor — DISMISSED** [review]
Tested on ts1, works as described

**Review by akesfeden — DISMISSED** [review]
Code changes look good to me.

**Review by MetinLamby — APPROVED** [review]
tested on ts2 and works well. Only when in german and the slidebar is at 100%, the outline of the "100%" string is vertically split in two (minor detail)

**Review by nairaarnez — DISMISSED** [review]
Tested in Ts1, It looks as described!

**Review by nadinesamyy — DISMISSED** [review]
tested on ts3, works as described

**Review by bassner — APPROVED** [review]
Just one idea below which I'm not 100% sure about, though. Code looks good 👍

**Review by maximiliansoelch — APPROVED** [review]
Code looks good 👍

**Pull request merged**
