### PR TITLE
`Development`: Increase server test coverage for StatisticsRepository

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
### Motivation and Context

This PR increases the server test coverage of `StatisticsRepository.java`
### Description

I introduced a test suite for the repository and covered some edge cases that are not covered by the current server tests.
### Steps for Testing

Code review and manual test runs

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Prior test coverage:
image

Test coverage of this PR:
image

### CODE REVIEW

**Review by filip-gregurevic — APPROVED** [review]
Good job! 👍🏼

**Review by Malyuk-A — DISMISSED** [review]
Code looks really good. Great job 👍

**Review by Malyuk-A — APPROVED** [review]
Reasonable Change. Re-approve 👍

**Review by filip-gregurevic — DISMISSED** [review]
Re-approve

**Pull request merged**
