### PR TITLE
`Programming exercises`: Fix duplicate build job trigger for local continuous integration

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context

This PR fixes the bug described  #7517. 
### Description
Removed the line where the build gets triggered the second time. Adapted some tests.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student

1. As a student, submit to a new programming exercise and wait for result
2. As instructor, check the submissions for the exercise: Submission for the student should only have one result

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts2. Worked as expected.

**Review by egekurt123 — APPROVED** [review]
Tested on ts3. Submissions had only one corresponding result as expected.

**Review by vinceclifford — APPROVED** [review]
Tested on ts2, works as expected

**Review by milljoniaer — APPROVED** [review]
tested on ts6, works as expected

**Review by reschandreas — APPROVED** [review]
tested locally, works as expected
code also looks good

**Review by Hialus — APPROVED** [review]
Code changes look good 👍🏻

**Pull request merged**
