### PR TITLE
`Development`: Replace learning goal with competency in server file and class names

### PR DESCRIPTION
**Pull request by terlan98**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
This is a part of follow-up PRs on #6388 There's currently an inconsistency between the usage of 'learning goal' and 'competency' throughout the system. This PR only addresses the **server file and class names**.

### Description
Replaced all occurrences of the term 'learning goal' with 'competency' on server file and class names. Also, some fields and functions are renamed to match the new class names. 

**Note**: there can be some fields and annotations left unchanged as they affect the database structure. This is okay since this PR doesn't aim to make any database-related changes.

**Note 2**: I had to rename some fields in client fields as well to match the models sent from the server.

### Steps for Testing
Prerequisites:
- 1 Course with competencies
- 1 Instructor

1. Log in to Artemis as Instructor
2. Navigate to Course Administration
3. Go to the Competency Management page of the course
4. Test CRUD operations (+import) for competencies
5. Link this competency to a Lecture Unity or Exercise and see if completing it updates the competency progress for the user

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by SolizerCodes — CHANGES_REQUESTED** [review]
Tested on ts2 and found two things (not sure if related to this PR)
1. I tried deleting a competency which is in a competency relation and got the following error. Deleting other competencies not in a relation worked fine.
Screenshot 2023-05-17 013106
2. After deleting a competency, the success message looked not right:
Screenshot 2023-05-17 013340
Everything else worked fine.

**Comment by terlan98** [comment]
> Tested on ts2 and found two things (not sure if related to this PR)
> 
> 1. I tried deleting a competency which is in a competency relation and got the following error. Deleting other competencies not in a relation worked fine.
>    Screenshot 2023-05-17 013106
> 2. After deleting a competency, the success message looked not right:
>    Screenshot 2023-05-17 013340
>    Everything else worked fine.

Thanks for testing @SolizerCodes 🙏  I fixed the incorrect success alert message (artemisApp.competency.deleted) in my latest commit. The first point that you mentioned is not related to this PR because the error looks the same on `develop` as well. 🙂

**Review by SolizerCodes — DISMISSED** [review]
Message when deleting competency works now 👍

**Review by laadvo — COMMENTED** [review]
The renamed server files and class names look good, I was unable to find any missed occurences.
However, some tests seem to now have compiler errors because of the changes to the client side, you should consider fixing them.

**Review by laadvo — APPROVED** [review]
the client tests have been fixed, code changes looks good

**Review by greekgeek1 — CHANGES_REQUESTED** [review]
Linking the competency to an exercise resulted in no updates to the competency after the completion of the exercise. It worked when only a text was linked. When both, a text and an exercise were linked, no progress was shown.
image 
image
image

**Review by tunargs — APPROVED** [review]
Code changes look good :+1:

**Comment by FreshLlamanade** [comment]
Found a missing translation: 
image

**Comment by terlan98** [comment]
> Found a missing translation: image Looks like it is the same for German. Other than that tested on ts3 and lgtm

Thanks for the review 🙂 The translation issue is not related to this PR as it exists on the `develop` branch as well.

**Review by SolizerCodes — APPROVED** [review]
Third time's the charm😉 Tested on ts1, looks good

**Review by FreshLlamanade — APPROVED** [review]
Looks good to me!

**Review by bassner — APPROVED** [review]

**Pull request merged**
