### PR TITLE
`Development`: Fix syntax error preventing syntax highlighting in server guidelines

### PR DESCRIPTION
**Pull request by MDK5**
### Motivation, Context and Description
When compiling the documentation, some code blocks get marked as parsing errors. This due to a syntax error in the example code which is fixed now.

Open Question: Looking at the code the call to `request.postWithResponseBodyFile` also requires some export options. This is not relevant for the example, but also makes it outdated. Should I add these options into the documentation as well?

### Steps for Testing
1. Go to the documentation built from this pull-request (readthedocs GitHub action)
2. Navigate to the server code guidelines
3. Check that the last two java code examples (for testing) are highlighted correctly now

#### Code Review
- [x] Review 1
- [x] Review 2

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Code snippets are displayed correctly now.

**Review by coolchock — APPROVED** [review]
looks good 👍

**Review by FlorianGlombik — APPROVED** [review]
The highlighting is now fixed in the documentation 👍
image

**Review by jhainzlschmid — APPROVED** [review]
Makes sense 👍

**Review by DanielKainz — APPROVED** [review]
Code is correctly highlighted :-)

**Pull request merged**
