### PR TITLE
[Chore] Rename Tutor Dashboard to Assessment Dashboard

### PR DESCRIPTION
**Pull request by anditurdiu**
### Motivation
The tutor dashboard name was misleading as it implies that only tutors should access it. Renaming it to assessment dashboard better reflects its function within Artemis. 

### Description
Rename Tutor Course Dashboard & Tutor Exam Dashboard => Assessment Dashboard. 
Tutor Exercise Dashboard => Exercise Assessment Dashboard

### Steps for testing
Click around the Artemis client. You should not see any translation errors, especially in the Assessment Dashboard

### CODE REVIEW

**Review by stefanwaldhauser — CHANGES_REQUESTED** [review]
image
Not correctly translated in german

**Review by FuchsDominik — APPROVED** [review]
As far as I can tell, i did not find any leftover TutorDashboard's in the UI. Also after the german changes those look good. Nice job.

**Review by sjagla27 — APPROVED** [review]
Couldn't find any leftovers. Translation looks good too.

**Review by derLalla — APPROVED** [review]
really good changes

**Review by kokowaahmax — APPROVED** [review]
a good change, nicely done!

**Pull request merged**
