### PR TITLE
`Grading`: Fix client validation for grading keys

### PR DESCRIPTION
**Pull request by yassinsws**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Description
The client validation is implemented in an unusual way for grading keys. Instead of directly preventing the save action and highlighting invalid input, the user can save, receives and error that telĺs to look for the actual error at another place in the user interface.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to assessment 
4. Try to put the value 0 in one of the intervals
5. test if other stuff is broken or does not show any error message

### Screenshots
image

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved handling of null values in grading system to prevent invalid percentage and point entries.
	- Set minimum input values for percentage and points intervals to `0.5` to ensure more accurate grading intervals.

### CODE REVIEW

**Review by Strohgelaender — DISMISSED** [review]
Please do not include generated files (de.json / en.json) into your PR.

**Review by Gusti2010 — DISMISSED** [review]
Tested on TS11_Legacy. Works as expected.

**Review by AntonGeTUM — DISMISSED** [review]
Tested on ts11, works as expected

**Review by Predixx — APPROVED** [review]
tested on ts2. looked just like in the screenshot

**Review by georgyia — DISMISSED** [review]
tested manually on ts3, works as expected

**Review by xHadie — DISMISSED** [review]
_Manually tested on TS11_Legacy_
Works as described!

**Review by Ceiridge — DISMISSED** [review]
Tested on ts11. Change works as expected
image

**Comment by krusche** [comment]
Please fix the merge conflict

**Review by lennart-keller — APPROVED** [review]
Demonstrated in testing session. Works nice

**Review by kaancayli — APPROVED** [review]
Tested in testing session. Works just fine

**Review by nata-81 — APPROVED** [review]
tested in testing session on ts 6. Works as expected.

**Review by MaximilianJG — APPROVED** [review]
Tested manually on TS2. Works as expected. 

Screenshot 2023-12-19 at 21 43 43

**Review by egekurt123 — APPROVED** [review]
Manually tested on ts5, works as expected

**Pull request merged**
