### PR TITLE
[Exam] Show start cover in grace period after browser reload

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context

See https://github.com/ls1intum/Artemis/issues/2795. Exercises for the student exam are only fetched after the student confirmed his participation. When a student reloads the page while in the grace period, the end cover for the final submission of the exam is shown to the student currently. The exam submission will fail.

### Description

- [x] Show start cover if exam is visible, grace period is not over, the student has not submitted or confirmed the exercise start (resets on reload) yet
- [x] Add check to only show the end cover if the student has confirmed the start before. Additionally, we show the end cover page if the grace period is over and the student did not submit to display the message that he failed to submit.
- [x] Reduce code duplication and remove useless flag.

### Steps for Testing

**In depth code review if you are a developer. Double check that the conduction timeline (visible, start, grace period, end, summary) and the displayed components in _exam-participation.component_ are non-overlapping and make sense**

1. Log in to Artemis
2. Navigate to Course Administration
3. Create an exam with multiple users
4. Participate in the exam and test hand-in early, regular hand-in, reloading the page, reloading the page in the grace period and submitting afterwards.
5. Check that the summary page is correctly displayed after submitting the exam early or regularly
6. Also try not to submit the exam in the end. A message that you have failed to submit should be shown.

### CODE REVIEW

**Review by JohannesWeiss — APPROVED** [review]
Tested all hand-in combinations on ts1 and all of them worked as intended.

**Review by airelawaleria — APPROVED** [review]

**Review by tiffca — APPROVED** [review]
Tested successfully

**Review by EneaGore — APPROVED** [review]

**Review by simonzilker — APPROVED** [review]
Looks good. Tested with @marvinchimeka

**Review by marvinchimeka — APPROVED** [review]
Tested in testing Session without any issues.

**Review by FuchsDominik — APPROVED** [review]
Code changes look good :)

**Review by fde312 — APPROVED** [review]
Code looks good to me and the logic as well! Good job! 👍

**Pull request merged**
