### PR TITLE
`Exam mode`: Make browser fingerprints configurable for administrators

### LINKED ISSUE #4913: `Feature`: Toggle Fingerprinting
### Is your feature request related to a problem?

We would like to be able to disable (or enable) the Fingerprinting Feature #1688 via server configuration (similar to sentry)
We are currently investigating whether we can use the feature or not; but until a decision has been made. It has to be disabled for us.

### Describe the solution you'd like

see above

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Fixes #4913 

### Description

Adds a new flag to the ``/info`` endpoint to enable or disable browser fingerprinting; if disabled, the fingerprint service will clear the existing instance key from the local storage and not collect any fingerprints

### Steps for Testing

This is best tested locally as you have full control over your server config.
Run a few requests from the client and make sure that fingerprint headers are only submitted if it's enabled on the server side:

1. Three cases: In ``application.yml``, edit ``browser-fingerprints-enabled`` to ``true`` or ``false``, or remove the configuration option entirely.
2. Restart the server and reload the client
3. Make sure that the headers ``X-Artemis-Client-Instance-ID`` and ``X-Artemis-Client-Fingerprint`` are only submitted in subsequent rest calls if the configuration item is set to ``true`` or has not been defined (to not break current configurations); they should not be submitted if the config is set to ``false``

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by dfuchss — COMMENTED** [review]
Seems to work. I did't find any X-Artemis-Client-Fingerprint or X-Artemis-Client-Instance-ID in the requests now.

**Review by dfuchss — DISMISSED** [review]
Works as expected on our test systems

**Comment by dfuchss** [comment]
I'll add it to the current milestone :) Maybe we get this merged in the current or next milestone :)

**Comment by maximiliansoelch** [comment]
Up for general discussion:
What about the server? Shouldn't it reject a request that still somehow contains the fingerprinting headers when `browser-fingerprints-enabled` is explicitly set to false?

**Comment by dfuchss** [comment]
If server code should be changed I would say that instead of rejecting the request, Artemis should simply ignore the values and should not store it in the DB.

**Comment by bassner** [comment]
Added that real quick in 7eee543 @dfuchss @maximiliansoelch

**Review by maximiliansoelch — APPROVED** [review]
Tested locally, works as expected:

- `browser-fingerprints-enabled: true` or not set -> headers are sent
- `browser-fingerprints-enabled: false` -> headers are not sent, manually injected headers into a request are not persisted by the server

**Review by dfuchss — APPROVED** [review]
Re approve. The one code change after my last test/review looks good.

**Pull request merged**
