### PR TITLE
`General`: Unify translations for due date

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

Currently there were two translations in German and Englisch for due date. This should be unified to reduce confusion among users.

### Description

This pr changes the code and translations to only use "due date" instead of "deadline" in Englisch and "Einreichungsfrist" instead of "Abgabefrist" in German.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- Different Exercises

1. Log in to Artemis
2. Navigate to Course Administration
3. Click around and look for any due dates, e.g on the exercise page, in complaints, in the assessment dashboard, ...

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by MaximilianAnzinger — DISMISSED** [review]
Code LGTM

**Review by undernagruzez — DISMISSED** [review]
tested on ts2, works as expected

**Review by asliayk — DISMISSED** [review]
tested on ts2, works as expected

**Review by eceeeren — COMMENTED** [review]
image

Was it intentional to leave this like that? (Tested on TS2)

**Review by eceeeren — DISMISSED** [review]
Tested on TS2, approved

**Review by MichaelOwenDyer — DISMISSED** [review]
Not sure I see any issue with the terms "Deadline" or "Abgabefrist" but consistency is good

**Review by MaximilianAnzinger — APPROVED** [review]
Code still looks good to me 👍

**Review by undernagruzez — APPROVED** [review]
Reapproved

**Review by Strohgelaender — APPROVED** [review]
code looks good, did not find any left over occurences while searching locally.

**Review by lennart-keller — APPROVED** [review]
lgtm, couldn't find any leftovers locally.

**Pull request merged**
