### PR TITLE
synchronize name, username, and email of a Artemis user with Gitlab user

### LINKED ISSUE #2823: Can not rename user
updateUser Method in UserResource,java has a Problem the way it is written it does not allow for a rename. When users are handled by Artemis internally.

#### Expected behavior
I can rename a user

### Suggested code instead 
```
    @PutMapping("/users")
    @PreAuthorize("hasAnyRole('ADMIN')")
    public ResponseEntity<UserDTO> updateUser(@Valid @RequestBody ManagedUserVM managedUserVM) {
        log.debug("REST request to update User : {}", managedUserVM);
        Optional<User> existingUser = userRepository.findById(managedUserVM.getId());
        existingUser.orElseThrow(() -> new ResponseStatusException(HttpStatus.BAD_REQUEST, "Not a valid id for user."));

        Optional<User> otherUserSameEmail = userRepository.findOneByEmailIgnoreCase(managedUserVM.getEmail());
        if (otherUserSameEmail.isPresent() && (!otherUserSameEmail.get().getId().equals(managedUserVM.getId()))) {
            throw new EmailAlreadyUsedException();
        }
        Optional<User> otherUsersNameName = userRepository.findOneWithGroupsAndAuthoritiesByLogin(managedUserVM.getLogin().toLowerCase());
        if (otherUsersNameName.isPresent() && (!otherUsersNameName.get().getId().equals(managedUserVM.getId()))) {
            throw new LoginAlreadyUsedException();
        }
        if (managedUserVM.getGroups().stream().anyMatch(group -> !artemisAuthenticationProvider.isGroupAvailable(group))) {
            throw new EntityNotFoundException("Not all groups are available: " + managedUserVM.getGroups());
        }

        User updatedUser = userService.updateUser(existingUser.get(), managedUserVM);

        final var responseDTO = Optional.ofNullable(updatedUser != null ? new UserDTO(updatedUser) : null);
        return ResponseUtil.wrapOrNotFound(responseDTO, HeaderUtil.createAlert(applicationName, "userManagement.updated", managedUserVM.getLogin()));
    }

``` 
Screenshot from 2021-02-04 19-18-28

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

Resolves #2823, a bug that prevents the user login to be changed in Artemis when used with Gitlab/Jenkins. 

The reason is that the new updated login is used to check if the user exists in the VCS. Of course the user doesn't exist because it is mapped to the older user login. 

### Description

This PR fixes the bug by introducing the `vcsLogin` parameter in the `updateUser` function of the `VcsUserManagementService` interface. This is the login of the user stored in the VCS and is used for looking up that user in the VCS.

Furthermore, this PR extends `GitLabUserManagementService::updateUser` by synchronizing the user's login, email, and name. This enables changes to the Artemis user to be propagated to Gitlab (if Gitlab is used).

### Steps for Testing

**This PR has no affect on Bitbucket/Bamboo environments. Please use TS2 for testing !**
1. Log in to Artemis
2. Navigate to Server Administration -> User Management
2. Edit a user and change the login, first name, last name, email
3. Log in to Gitlab with an admin account and navigate to the user that you changed: https://artemistest2gitlab.ase.in.tum.de/admin/users
4. Make sure that the user has been changed correctly

### Test Coverage

UserService.java 87%
GitlabUserManagementService.java 28%
UserResource.java 86%

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]
Tested with @airelawaleria . We could not access the admin page via the provided link, but tested by changing a specific user's data, logging in with that user and having a look at the user profile. In this case, the data was updated according to the changes made in Artemis, hence the synchronisation worked for us.

**Review by EneaGore — APPROVED** [review]

**Review by DenizShabani — APPROVED** [review]

**Review by valeriebucher — APPROVED** [review]

**Review by simonzilker — APPROVED** [review]
tested with @marvinchimeka . same as @JohannesWeiss

**Review by marvinchimeka — APPROVED** [review]
tested in testing session.

**Review by philgabr — APPROVED** [review]
Same as @JohannesWeiss

**Review by krusche — APPROVED** [review]

**Pull request merged**
