### PR TITLE
`Development`: Make VCS reachable from host in multi node docker setup

### PR DESCRIPTION
**Pull request by BBesrour**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

In multi node docker setup, we can't clone repositories from host 

### Steps for Testing

1. Start multi node docker. Guide [here](https://docs.artemis.cit.tum.de/admin/setup/distributed.html#running-multiple-instances-locally-with-docker)
2. Create a course with a programming exercise
3. Clone repo from host. In the URL copied from artemis, you have to change `artemis-app-node-2:8080` to `localhost:8080`
4. Clone should be successful

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by anian03 — APPROVED** [review]
Code lgtm

**Review by marlon-luca-bu — APPROVED** [review]
Code

**Comment by magaupp** [comment]
Should the Postgres setup also be supported?

**Comment by magaupp** [comment]
Tested locally. Cloning is successful :+1:

**Review by magaupp — APPROVED** [review]

**Review by bensofficial — CHANGES_REQUESTED** [review]
Why is this change necessary? The docker-compose file you edited also contains nginx, which handles the git-clone requests. This setup is already working, e.g. for TS1.

**Review by Hialus — CHANGES_REQUESTED** [review]
This change is not sensible and should not be implemented.
The file you modified is the docker compose file meant for fully production ready setups on our test-servers. This file should neither contain configs that are only used for local development nor configs that violate the security of the application. This change would fall under both. A production ready setup for Artemis only exposes the secure HTTPs port 443 through a reverse proxy such as Ngnix and never the unencrypted port 80/8080. The setup you modified already works out of the box with Nginx as a reverse proxy with self-signed certificates. You can therefore clone your repo from https://localhost:443. If you are unable to clone due to the self-signed nature, you may have to trust the certificates on an OS level. Feel free to document this process in the docs.

**Comment by BBesrour** [comment]
@bensofficial @Hialus Thanks for the feedback. I didn't about the possiblity to trust the certifcates on OS level. I will add some documentation about it.

**Pull request closed without merging**
