### PR TITLE
Sync feature toggle using Hazelcast map.

### PR DESCRIPTION
**Pull request by sleiss**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest2.ase.in.tum.de.
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context
Artemis has feature toggles that allow administrators to disable certain features of Artemis without having to restart the application server (currently, only programming exercises can be disabled).
The feature toggle state (whether a certain feature is enabled or disabled) was currently only stored in an Enum on the instance where the administrator was connected to when performing the change but was not distributed between all instances.
This leads to inconsistent states where a feature can be enabled on one instance but disabled on another.

This PR synchronizes the feature state between all instances.

### Description
Instead of the Enum that holds the state (which cannot easily be shared), a map is shared between all instances:
- Each feature is either enabled (true) or disabled (false)

### Steps for Testing
This PR can only really be tested if you are running at least two instances of Artemis (thus you should use TS2 for testing).
You can however also test on TS1/3 and just make sure nothing broke.

1. Log in to Artemis
2. Navigate to Server Administration >  Feature Toggles
3. Toggle the state of a feature: The change should immediately be effective to all users, even if they are connected to a different instance.

This can be tested on TS2 with multiple testers connected to different instances, just DM me (or anyone else with access to TS2) on Slack, so that we can verify that the testers are indeed connected to different instances.

### Test Coverage
**Server:**
- FeatureToggleService: 100%

### CODE REVIEW

**Review by MaisiKoleni — COMMENTED** [review]
I would suggest using a `Map<Feature, Boolean>` instead of managing two lists and keeping them consistent. Would that also be an option? 

I think this could simplify the code and remove possible synchronization/concurrency problems or inconsitencies.

**Comment by sleiss** [comment]
> I would suggest using a `Map<Feature, Boolean>` instead of managing two lists and keeping them consistent. Would that also be an option?
> 
> I think this could simplify the code and remove possible synchronization/concurrency problems or inconsitencies.

@MaisiKoleni Good idea, I changed it.

**Review by kloessst — APPROVED** [review]
Worked fine on TS2. Code looks good to me.

**Review by kloessst — APPROVED** [review]
Re-approve

**Review by fde312 — APPROVED** [review]
Works fine! 👍

**Review by MaisiKoleni — APPROVED** [review]
Code looks good to me, and the feature toggle works well (tested on TS2). Good work!

**Review by krusche — APPROVED** [review]

**Pull request merged**
