### PR TITLE
`Assessments`: Display feedback from structured grading criteria more clearly

### PR DESCRIPTION
**Pull request by valeriebucher**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Description

Highlighting feedback generated through structured grading criteria so that it is more visible to tutors when assessing text exercises. 

### Steps for Testing

Prerequisites:
- 1 Tutor
- 1 Text Exercise with structured grading criteria

1. Navigate to the `Exercise Dashboard` of the text exercise.
2. Start an assessment of a submission.
3. Give feedback using structured grading criteria.
4. Check that _`Feedback:`_ ends with a colon, followed by the feedback text displayed as bold.
5. Check that the question mark icon is at the end. 

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Updated version:

Bildschirmfoto 2021-12-23 um 22 46 08

Old version:

Bildschirmfoto 2021-12-23 um 16 33 28

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
Code changes look reasonable and the screenshot looks good -> approve. I did not test the PR though.

**Review by MertAksehirlioglu — APPROVED** [review]
tested on ts1 and feedback works as expected(ends with a colon, followed by the feedback text displayed as bold.)

**Review by Bofan-Zhu — APPROVED** [review]
Tested on ts2. The changes are displayed as expected.

**Review by willergeorg — APPROVED** [review]
Code changes are fine for me.

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
