### PR TITLE
`Lectures`: Validate the date for lecture units

### PR DESCRIPTION
**Pull request by florian-glombik**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
While working on [Lectures: Add status bar to lecture creation and edit mode #9655](https://github.com/ls1intum/Artemis/pull/9655) I noticed that the date is not validated client side, with an invalid date the selection will just be ingored by the server.

### Description
This PR introduces client side validation for the dates, in addition to the already existing visual indicator, the save button is actually disabled now (and the state for the unit set to invalid, which is important for reflecting the correct state in the status bar for #9655)

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 existing lecture

1. Go to the lecture Unit overview
2. Add a lecture unit (text / video / online / file) to a lecture
3. Specify a release date
4. Make the release date invalid (e.g. `Nov 28, 2024, 12:30:00 P`)
5. Verify the date input is marked red
6. Verify the submit button is disabled
7. Modidy the release date to be valid (e.g. `Nov 28, 2024, 12:30:00 PM`)
8. Verify the submit button is enabled again

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
addDatepickerValidation

## Release Notes

- **New Features**
	- Enhanced form validation across multiple components (Attachment, Online, Text, Video) to include checks for the date-time picker component.
	- Integration of a date-time picker in the form management, improving user input for date fields.

These changes ensure that forms are validated not only based on their status but also on the validity of the date picker, leading to a more robust user experience.

### CODE REVIEW

**Review by az108 — APPROVED** [review]
Code LGTM 👍

**Review by cremertim — APPROVED** [review]
Code 👍

**Review by HawKhiem — APPROVED** [review]
Tested on TS4. Invalid date was highlighted red as expected, also the submit button is disabled as described. It also works as described in case of valid date
Screenshot 2024-11-22 203527
Screenshot 2024-11-22 203535

**Review by sawys777 — APPROVED** [review]
Tested on TS1, everything worked as expected.

**Review by flbrgit — COMMENTED** [review]
Tested on TS3, everything works as described. 
Screenshot 2024-11-23 210049
However, when inserting a date that does not exist (in this example the 31st of november), it is not marked as red, and it is automatically changed to the 1st of december:
Screenshot 2024-11-23 210333
Screenshot 2024-11-23 210411

Is this behavior intended?

**Review by krusche — APPROVED** [review]

**Pull request merged**
