### PR TITLE
`Development`: Speedup loading of active courses

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context
While reviewing PR #9727 I spotted a filter call that could be moved into a database query to improve performance.

### Description
We now directly filter out inactive courses at the database level to avoid loading to many objects.

### Steps for Testing
Navigate to Aretmis -> Course management and check that the currently active courses are diplayed correctly.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Introduced a new method to retrieve active courses for users with tutor roles, enhancing course management.
  
- **Improvements**
	- Streamlined the retrieval process for courses, improving efficiency and reducing complexity in the code.

- **Bug Fixes**
	- Updated method naming conventions for clarity and consistency.

### CODE REVIEW

**Review by Longppham — COMMENTED** [review]
I tested this PR on TS4 as a student (Was not specified which to choose?) Following the instructions, I went to artemis and then clicked on course management which lead then to the screenshot I attached here.  When I check the box show only active courses, nothing changes. 
In the current courses, it says 76 but after clicking course management, only 1 Course is shown. 



image

image

image

**Comment by Strohgelaender** [comment]
>  In the current courses, it says 76 but after clicking course management, only 1 Course is shown.

On the front page all courses (where you are at least student) are shown, on the course management page you only see courses where you are at least tutor. So that's a correct behaviour.

**Comment by Longppham** [comment]
> > In the current courses, it says 76 but after clicking course management, only 1 Course is shown.
> 
> On the front page all courses (where you are at least student) are shown, on the course management page you only see courses where you are at least tutor. So that's a correct behaviour.

Perfect! I was not sure how it worked for my account! Should i edit my old comment?

**Review by sachmii — APPROVED** [review]
Tested on TS5, active courses are correctly displayed.

**Review by ahbitaqu — APPROVED** [review]
[Tested on TS1]
Reviewed with instructor, tutor & student. Everything works as it should, all courses get displayed correctly

**Review by Malekos74 — APPROVED** [review]
### Server tested on: Server 01
Works fine

**Review by sawys777 — APPROVED** [review]
Tested on TS1, everything worked as expected.

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS1. Active courses are displayed correctly

**Review by flbrgit — APPROVED** [review]
Tested on TS4. Everything works as expected

**Review by JerroyTan — APPROVED** [review]
[Tested on TS3]
Active courses displayed correctly without problem.

**Pull request closed without merging**
