### PR TITLE
`Development`: Improve documentation for the preset GitLab to Jenkins push notification token

### PR DESCRIPTION
**Pull request by 4ludwig4**
#### General

- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

This is a documentation workaround for issue 5973:

- #5973

### Description

Instead of using the non-working preset tokens for Jenkins, the documentation adds a step to refer to the manual token generation for production systems as long as the Issue persists.

### Steps for Testing

- take a look at the [docs](https://artemis-platform--5982.org.readthedocs.build/en/5982/dev/setup/#automated-jenkins-server-setup) 

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by b-fein — APPROVED** [review]

**Comment by krusche** [comment]
Please choose a proper title for the PR

**Comment by 4ludwig4** [comment]
> Please choose a proper title for the PR

I changed the title. Is the new title better?

**Review by tunargs — APPROVED** [review]
looks good, approved

**Review by sleiss — APPROVED** [review]
LGTM

**Pull request merged**
