### PR TITLE
`General`: Fix internal server error when creating a future course

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

For courses that are starting in the future, an internal server error is thrown if the user enters the course management view or the course detail view. This PR fixes the problem.

### Description

I added a check for the span size of the active student chart to be positive on server side. If not, the server returns an empty list instead of trying to create a List with a negative length.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a course that starts in the future (set start time to any date in future)
4. Save the course
5. Chech that no internal server error is thrown

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| CourseResource.java | 73% | 94% |

### CODE REVIEW

**Review by Dominik-Weinzierl — APPROVED** [review]
The code looks good to me :+1: Thanks for solving this problem, I noticed it today on ts1 ^^

**Review by manuelmanso — APPROVED** [review]
LGTM 👍

**Review by yuling-sun — APPROVED** [review]
Tested on TS1. Works as described.

**Review by SimonPaul02 — APPROVED** [review]
Tested on Ts1. Thank you for the fix, everything works

**Pull request merged**
