### PR TITLE
`Programming exercises`: Fix issues with plagiarism checks

### LINKED ISSUE #4448: Plagiarism checks: Internal server error when parsing empty submission
### Describe the bug

When running JPlag for a given exercise (H06E01) in our course (INHN0002), an Error 500 is returned which seemingly is caused by a submission that is empty (apart from a .gitkeep file)

### To Reproduce

1. Go to Exercise "H06E01" in the "Fundamentals of Programming (INHN0002)" course
2. Click on "Check plagiarism"
3. Open the Network tab of the Chrome Developer tools
4. Start the plagiarism checks
5. See error 
image

### Expected behavior

Plagiarism checks are run and the results are returned. Empty or just template repositories without student submissions could just be excluded (by choice) from the plagiarism checks.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Chrome

### Additional context

For the given submission that is mentioned in the error message, the student didn't commit or push anything. The repository is just the empty template provided by the exercise.
Exercise _H06E01_ (ID: 5663) in the course _Fundamentals of Programming (INHN0002)_ (ID: 161)

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dfuchss**
Fixes #4448

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).

#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

I've updated JPlag to it's current version
* https://github.com/jplag/JPlag/actions/runs/1548612101
* https://github.com/jplag/JPlag/commit/e46aa72cbcc98c4ef70f85e22cf9f619bdab6076

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2..n Students

1. Create some programming submissions (create some similar submissions (they have to be different to the base code / template))
2. As instructor check for plagiarism
3. See whether everything works as expected

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by krusche** [comment]
Thanks for this PR. I would suggest, we wait for the official release and add the dependency to `build.gradle` to avoid the workaround of storing the dependency as jar file in the Github repo

**Comment by dfuchss** [comment]
You are right that in the future this lib should be handled as simple dependency.

I would also see the PR more as a temporary solution that might be needed until JPlag gets officially released in version 3.0, because if you look at the history, some important improvements have been made to JPlag (since the version Artemis is currently using). At the moment we mostly download all repos from Artemis and run JPlag externally, for example because of issues like #4448.

**Comment by krusche** [comment]
Ok, then it's fine from my side. If we can fix a couple of issues with the newer "unofficial" 3.0 version, let's test that the chances work correctly and then merge this PR 👍

**Review by mallgaier — COMMENTED** [review]
Tested together wirh @lBruchmann @Bofan-Zhu @VinnavanSembian @Strohgelaender and @cremertim .
See comment of @Strohgelaender

**Review by Strohgelaender — COMMENTED** [review]
Tested on TS3 in testing session with @mallgaier @lBruchmann @Bofan-Zhu @VinnavanSembian @cremertim . The updated integration worked, but the issue #4448 is still not resolved. Empty submissions lead to an error 500 and no results are shown.

**Review by lBruchmann — COMMENTED** [review]
Tested on ts3. Tested together wirh @lBruchmann, @Bofan-Zhu, @VinnavanSembian, @Strohgelaender, and @cremertim .
General remarks see @Strohgelaender comment.

**Review by VinnavanSembian — COMMENTED** [review]
Tested on ts3 in testing session. The update worked but this does not resolve the issue. Check @Strohgelaender 's remarks

**Comment by dfuchss** [comment]
Thanks for testing! Might be related to the issues in #3603 (not the issue itself, but the list of possible issues that are not handled)

**Comment by Bofan-Zhu** [comment]
Tested on t3 in a testing session with @VinnavanSembian, @mallgaier, @lBruchmann , @Strohgelaender , @cremertim. As @Strohgelaender said the issue [#4448 ](https://github.com/ls1intum/Artemis/issues/4448) is still present.

**Comment by krusche** [comment]
We should probably filter empty submissions on Artemis the Artemis server before sending to Jplag

**Comment by dfuchss** [comment]
Also the BaseCode should not be submitted if no enough tokens are contained

**Comment by dfuchss** [comment]
Also see https://github.com/jplag/JPlag/pull/253
JPlag provides several different exceptions now, they should be handled by artemis later on :)

**Comment by krusche** [comment]
I added filtering for empty submissions before sending them to JPlag, please test again if this works better now.
We can then merge this PR and fix other issues in follow-up PRs.

**Comment by dfuchss** [comment]
I've added a workaround for bad base code submissions.

**Review by fh314 — DISMISSED** [review]
tested on ts2 with @Strohgelaender @Bofan-Zhu @lBruchmann @VinnavanSembian @cremertim  and works fine, also for fully empty and just template submissions

**Review by lBruchmann — APPROVED** [review]
Tested on ts2. tested together with @Strohgelaender, @Bofan-Zhu, @cremertim, @VinnavanSembian, and @fh314. I followed the testing steps. JPlag runs the plagiarism check as expected without errors.

**Review by VinnavanSembian — APPROVED** [review]
Tested on ts2 in testing session. The plagiarism check runs as expected!

**Review by Bofan-Zhu — DISMISSED** [review]
Tested on ts2 with @Strohgelaender @lBruchmann @cremertim @VinnavanSembian and 
@fh314 . Prior error does not appear anymore. Empty submissions are successfully filtered out. 👍

**Review by Strohgelaender — DISMISSED** [review]
Tested on TS2, the check worked correctly with empty submissions. Code changes look good to me.

**Pull request merged**
