### PR TITLE
`Development`: Update Apollon version

### PR DESCRIPTION
**Pull request by minrows**
#### General

- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
Update version of Apollon from [v2.11.3](https://github.com/ls1intum/Apollon/releases/tag/v2.11.3) to [v2.12.1](https://github.com/ls1intum/Apollon/releases/tag/v2.12.1) [(Changelog)](https://github.com/ls1intum/Apollon/compare/v2.11.3...v2.12.1)

### Description
This bugfix release version of Apollon implements the manual layouting feature in Apollon along with minor bugfixes ([changelog](https://github.com/ls1intum/Apollon/releases/tag/v2.12.1)).

### Steps for testing
1. Create a modeling exercise.
2. Insert couple of elements and connect them in a way that the connectors have more than 3 edges. 
3. Observe that the connection can now be layouted manually with the presence of manual layout handle.

### Screenshots
screen-capture (21)

### CODE REVIEW

**Review by ge65cer — APPROVED** [review]

**Review by akesfeden — DISMISSED** [review]
Tested on TS1 during testing session, new features from Apollon are available in Artemis.

**Review by jpbernius — APPROVED** [review]

**Review by jpbernius — CHANGES_REQUESTED** [review]
@minrows Looks like the client tests are failing now. Can you have a look?

**Comment by minrows** [comment]
> @minrows Looks like the client tests are failing now. Can you have a look?

@jpbernius 
I have figured out what an issue is. I will release a new bugfix version of Apollon and create a new PR. 
Till then let's not update Apollon in Artemis.

**Comment by jpbernius** [comment]
Ok, so I will close the PR for now. Feel free to reopen this PR once your Apollon Fix is ready.

**Pull request merged**
