### PR TITLE
`Programming exercises`: Add shortcuts to save problem statement

### PR DESCRIPTION
**Pull request by coolchock**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
(https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Description

This pull requests adds shortcuts for saving problem statement in programming exercises.
closes https://github.com/ls1intum/Artemis/issues/7867

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise

1. Open an existing programming exercies/create a new programming exercises
2. Check if the shortcut cmd + s (mac) and control + s (other systems) saves the problem statement
3. Check if the shortcut control + s (mac) and windows + s (other systems) **does not** save the problem statement

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Introduced keyboard shortcuts "Ctrl + S" and "Cmd + S" for saving instructions within the programming exercise editor.

### CODE REVIEW

**Review by LenaKahle — APPROVED** [review]
Approve, tested on legacy ts11.

**Review by konrad2002 — APPROVED** [review]
manually tested on legacy ts11 with macOS (cmd + s), works as expected

**Review by egekurt123 — APPROVED** [review]
Manually tested on ts6, works as expected

**Review by nata-81 — APPROVED** [review]
Tested on windows on ts2 works as expected.

**Review by Gusti2010 — APPROVED** [review]
Manually tested on ts11_Legacy. Works as expected!

**Review by georgyia — APPROVED** [review]
manually tested on ts3, works as expected

**Pull request merged**
