### PR TITLE
`Assessment`: Display warning when grade scale exceeds max points

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups 
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

#6194

### Description

Added a gentle warning when specified grade scale goes above max points.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to grading scale
4. Warning is not visible.
5. Add new grading step that exceeds max points
6. Warning is visible.

Repeat for internal and detailed scale.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image

### CODE REVIEW

**Review by terlan98 — COMMENTED** [review]
Tried to test on ts2 but it crashed. Not sure about the reason though 🤔

**Comment by jakubriegel** [comment]
@terlan98 I've merged develop and tested this again locally and on ts1. All worked fine - I cannot reproduce your issue. Could try again?

**Review by terlan98 — APPROVED** [review]
Tested on ts2. Works as described 👍 

I would add some bottom padding (between the warning and the save button). Replicating the style of "All grade step fields must be filled in!" warning could also be a good idea. Besides that, it looks fine.

**Review by DominikRemo — CHANGES_REQUESTED** [review]
Tested on ts2 and the warning is shown when expected.

Please have another look at the styling and adapt the style to fit other warnings on this page.

My suggestion, move the warning below the buttons and style it like the "All grade step fields must be filled in!" warning, as terlan98 has suggested. It would look a lot nicer then :)
Bildschirm­foto 2023-03-31 um 08 52 48

**Comment by jakubriegel** [comment]
@DominikRemo @terlan98 thanks for your reviews. The style and location of this warning is different by a purpose. That's because this warning works like a hint and doesn't block the user from saving the grade scale. I think it'd confusing to have blocking and non-blocking warnings presented the same way. WDYT?

**Comment by DominikRemo** [comment]
> 

@jakubriegel I agree with the fact that it should not be displayed exactly the same way, but it should definitely be more similar. Maybe make it an info instead of a warning? We could display it with blue background with the info icon instead of a warning icon.

**Comment by terlan98** [comment]
> @DominikRemo @terlan98 thanks for your reviews. The style and location of this warning is different by a purpose. That's because this warning works like a hint and doesn't block the user from saving the grade scale. I think it'd confusing to have blocking and non-blocking warnings presented the same way. WDYT?

Oh, I see. Yes, it makes sense to make blocking and non-blocking warnings different style-wise. Would it be possible to make the blocking ones red and the non-blocking ones yellow, maybe?

**Comment by jakubriegel** [comment]
New screenshot uploaded to the description

**Review by terlan98 — APPROVED** [review]
Thanks for implementing the suggestion 👍  Tested on TS2. Works as expected

**Review by DominikRemo — APPROVED** [review]
Tested on TS2. Works as expected 👍

**Pull request merged**
