### PR TITLE
`Development`: Update the editor-related screenshots in the documentation

### PR DESCRIPTION
**Pull request by pzdr7**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests)

### Motivation and Context

The documentation contains several screenshots that do not reflect the current state of the code editors in Artemis.

### Description

I updated the screenshots that featured the editor in a meaningful way.

### Steps for Reviewing

1. Deploy on a test server
2. In the footer, click "About", then on 6. Exam mode, go to both the page for "Students" and "Instructors" and check that the screenshots are up to date. (You may have to clear your cache if they are not.)
3. Review the other screenshots that were updated in the documentation: The pages/sections affected are:
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/exercises/programming.html#verify-the-exercise-configuration
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/exercises/programming.html#online-editor
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/exercises/programming.html#manual-assessment
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/exercises/quiz.html#prepare-a-quiz-exercise (each question type)
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/exercises/modeling.html#create-new-modeling-exercise (near example solution / explanation / release date)
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/exercises/textual.html (near example solution)
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/lectures.html#managing-lectures
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/lectures.html#attachment-unit (Attachment unit and below)
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/exams/instructors_guide.html#assess-student-exams (fig. Manually Assessing a Programming Submission)
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/tutorialgroups.html#creating-tutorial-groups
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/plagiarism-check.html#instructors ("5. Notify the student...")
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/adaptive-learning/adaptive-learning-instructor.html#create-edit-competencies
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/adaptive-learning/adaptive-learning-instructor.html#generate-competencies
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/markdown-support.html
  - https://artemis-platform--9552.org.readthedocs.build/en/9552/user/icl/local-version-control.html#access-repositories-as-a-student

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Reviews (steps above)
- [x] Review 1
- [x] Review 2

### Test Coverage

Unchanged

### Screenshots

Please refer to the links above to see the changes in the documentation

## Summary by CodeRabbit

- **Documentation**
	- Enhanced clarity and structure of the adaptive learning instructor guide, particularly on linking competencies.
	- Improved readability and layout of the lecture management document with increased image widths for better visibility.
	- Maintained instructional integrity while refining content for clarity.

### CODE REVIEW

**Review by coolchock — APPROVED** [review]
LGTM

**Review by iyannsch — APPROVED** [review]
Screenshots LGTM

**Review by Jan-Thurner — APPROVED** [review]
Updated screenshots lgtm

**Review by JohannesWt — APPROVED** [review]
👍

**Pull request merged**
