### PR TITLE
`Development`: Add client tests for timeframe view

### PR DESCRIPTION
**Pull request by florian-glombik**
#### General

- [x] I tested the PR on a testserver
- [x] I chose a title conforming to
  the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client

- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following
  the [test guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Description

Follow-up for https://github.com/ls1intum/Artemis/pull/7363 adding tests and improving the coverage for the timeframe
view.

### Steps for Testing

1. Verify that tests are passing and tests make sense _(code review)_
2. Make sure the renaming of files did not break displaying the exercises
3. Test if filters and sorting does still work as expected 
4. Test if exercises are displayed properly in the `weekly view`
5. Verify that upcoming exercises are displayed properly

#### Manual Tests

- [x] Manual Test 1
- [x] Manual Test 2

#### Code Review

- [x] Code Review 1
- [ ] Code Review 2

#### Client

| Class/File | Line Coverage |   Confirmation (assert/expect) |
|------------|--------------:|-------------------------------:|
| [exercise.utils.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5602/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/exercise/exercise.utils.ts.html) | 90.58% |                              ✅ |
| [course-exercises-grouped-by-timeframe.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5602-2/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-exercises/course-exercises-grouped-by-timeframe.component.ts.html) | 98.52%	 |                              ✅ |
| [course-exercises-grouped-by-week.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5602/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-exercises/course-exercises-grouped-by-week.component.ts.html) | 97.77% |                              ✅ |
| [course-exercises.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5602/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-exercises/course-exercises.component.ts.html) | 98.02% |                              ✅ |

### CODE REVIEW

**Comment by simon-hng** [comment]
Found a bug during testing session. Please request reviews after fixing from: 
@simon-hng @vinceclifford @jakubriegel

**Comment by florian-glombik** [comment]
The [mentioned bug](https://github.com/ls1intum/Artemis/pull/7387#issuecomment-1779202876) is the following: 
In the `timeframe view` the exercises are not grouped properly when ordering by `Release Date` (All Exercises displayed with `No Due Date Associated`)

**Comment by florian-glombik** [comment]
I was not able to reproduce the issues, neither locally nor on ts1 - I guess we ran into some caching issue during the testing session

@simon-hng @vinceclifford @jakubriegel

**Comment by florian-glombik** [comment]
The issue with not updating the upcoming exercises properly is actually fixed with this PR, due to the deployment error we have still been looking at an outdated version during the testing session

https://github.com/ls1intum/Artemis/pull/7387#issuecomment-1790789993
image

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy ts2. Worked as expected.

**Review by lennart-keller — APPROVED** [review]
Manually tested on ts1. Works as described.

**Pull request merged**
