### PR TITLE
`General`: Fix several issues in the new dark mode

### LINKED ISSUE #5036: Dark mode on phones has popup window cut off by screenedge
### Describe the bug

When switching between dark and light mode on a phone, the little popup window that shows some more text and an additional option is cut of by the screen edge. I only tried Firefox though.

### To Reproduce

1. Open artemis on a phone.
2. Click the menu button
3. Press the moon or sun icon
4. Dont see the popup

### Expected behavior

The popup should have shifted to the middle or something 

### Screenshots

Screenshot_20220507-104837_Firefox Nightly

### What browsers are you seeing the problem on?

Firefox

### Additional context

Firefox nightly on android

### Relevant log output

```shell
I would need to setup a usb connection to my pc and im nor doing that.
```

### LINKED ISSUE #5037: Dark mode: Exercise feedback is less noticeable in dark mode
### Describe the bug

When opening an exercise with visible feedback: The feedback visuals are less noticeable when using dark mode

image
image

### To Reproduce

1. Go to any exercise with visible feedback
2. See error

### Expected behavior

Make feedback more visible, like in the exercise text
image

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

Firefox version 100
No adblock etc.

### Relevant log output

_No response_

### LINKED ISSUE #5039: Dark Mode: Categories drop-down during exercise creation is not readable
image

## To Reproduce

1. Create or edit an exercise
2. Click the start of the categories field to open the drop down

### LINKED ISSUE #5040: Dark Mode: Associations in UML Diagrams
### Describe the bug

Composition Association is not displayed correctly. It looks similar to aggregation.

### To Reproduce

1. Go to any exercise with UML editor
2. Make a composition association
3. See error

### Expected behavior

"Diamond" in composition should be black.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional context

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #5048: `Dark mode`: Disabled but active checkboxes not noticable
### Describe the bug

You cannot tell if a disbabled checkbox is checked or not when using the darkmode.

### To Reproduce

1. Edit an existing Programming Exercise
2. Check the "SCA enabled" checkbox

### Expected behavior

see that the checkbox is checked.

### Screenshots

white:
grafik

dark:
grafik

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Description

This PR fixes four follow up issues regarding the dark mode

#### 1. Dark Mode settings popover is wrongly positioned if the navbar collapses on smaller screens:
Reported by @jpbernius, @krusche, @JohannesStoehr and @Funky-Punky.
Closes #5036.

#### 2. Lecture attachment details appear black in dark mode
Reported by @ge65cer 

Happens if you select a lecture with at least one attachment as student:
grafik

#### 3. Exercise feedback is less noticeable in dark mode
Reported by @LadnerJonas
Closes #5037.

Before:
grafik

After:
grafik

#### 4. Category dropdown background is white
Reported by @bottbenj
Closes #5039.

Before:
grafik

After:
Screenshot 2022-05-07 at 18 43 07

#### 5. Checked, but disabled checkbox looks like unchecked checkbox in dark mode
Closes #5048.

**Before:**
Light mode
grafik

Dark mode:
grafik

**After:**
grafik

#### 6. Include Apollon release with dark mode issues fixed

Related Apollon Issues: https://github.com/ls1intum/Apollon/issues/225 (resolved by https://github.com/ls1intum/Apollon/pull/226), https://github.com/ls1intum/Apollon/pull/227

Closes #5040.

### Steps for Testing

Please check that each of the described bugs do not appear anymore.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Comment by LadnerJonas** [comment]
3. / #5037 solution is looking great 🚀

**Review by valeriebucher — DISMISSED** [review]
Tested on ts3. Issues 1-4 are solved and look good 👍

**Review by alaraozdenler — APPROVED** [review]
Tested on TS1. Bugs did not appear, everything works as described

**Review by nadinesamyy — DISMISSED** [review]
Tested all four reported fixes on TS3, all work as intended

**Comment by bassner** [comment]
@nadinesamyy @alaraozdenler @valeriebucher 
Hey, I've added 5. and 6. to this PR as well. Could you check them as well? Thank you very much!

**Review by ge65cer — APPROVED** [review]
Thanks for the bugfix, works great!

**Review by joaquinmurcia — COMMENTED** [review]
All fixes tested on TS1. Work as expected. Attach some screenshots about 5:
image
image


I don't understand how #5040 is supposed to look in dark mode, though. Here's a screenshot with the appearance when selecting composition (down) and aggregation (right)
image

**Review by jbllhff — APPROVED** [review]
tested on ts2, works fine. Is there another appollon integration apart from modeling exercises?

**Comment by bassner** [comment]
@joaquinmurcia That looks correct. The difference is whether or not the diamond is filled, and it would be filled with the foreground color. In dark mode, that would be white, so in your case the composition diamond is filled, while the aggregation diamond is not filled (has the background color), which is correct.

**Comment by bassner** [comment]
@jbllhff There is this view which also support all the different diagram types. Reachable if you go to the exercise list of a course in the management area and click "Create Drag and Drop Model Quiz" in the Quiz Exercises section.
grafik

**Review by rhubinger — APPROVED** [review]
Tested on TS2. None of the fixed bugs did reappear.

**Review by nairaarnez — APPROVED** [review]
Tested on ts3. The bugs were solved

**Pull request merged**
