### PR TITLE
`Development`: Improve file input validation

### PR DESCRIPTION
**Pull request by MarkusPaulsen**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x]  I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Improve the methods surrounding input validation and file saves.

### Description
We improved the name of several methods to reflect the functionality better, extracted the functionality of the file save method to improve readability and added appropriate tests for extracted methods.

### Steps for Testing
We just want to make sure that I didn't accidentally break the implementation.

Prerequisites:
- 1 Instructor, 1 Student

Split Lecture PDF (Instructor):
1. Open the lecture tab and click on "Create Lecture"
4. Fill in the title and channel name
5. Check "Automatic unit processing" at the bottom
7. Select a multipage PDF to process and hit "Process units". If you use a PDF that fits the requirements, skip point 5. Otherwise, continue.
8. Add units manually, at least two and set the pages accordingly. Then hit "submit.
9. Open the lecture and download a lecture unit attachment.
11. No issues should occur

Fileupload Exercise (Instructor, Student):
1. Create a file upload exercise with a description. Upload an image to the description
2. Start the exercise, the image should show up properly as well as the rest of the description
3. Participate in the exercise
4. Upload another file
5. View/Download your submission
6. No issues should occur, the correct file should download.

#### Performance Review
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| FileService.java | 85.4% | ✅              |

### CODE REVIEW

**Comment by undernagruzez** [comment]
Tested on ts6, but wasn't able to create a lecture. 
Got 
image
Is this PR related to the problem?

**Review by DemjenDavid — DISMISSED** [review]
Tested on ts3, worked well for me!

**Review by JohannesStoehr — APPROVED** [review]
Tested on TS3 during testing session. Works for me 👍

**Review by tobias-lippert — APPROVED** [review]
Tested the file upload exercise process in the testing session. Everything worked flawlessly.

**Review by MaximilianAnzinger — APPROVED** [review]
Tested on TS3. Works according to testing steps.

**Review by DominikRemo — APPROVED** [review]
Tested in testing session on ts3, works for me

**Review by laadvo — APPROVED** [review]
Tested splitting lecture pdf on ts3, everything is working as expected

**Review by b-fein — APPROVED** [review]
Code changes look good.

**Review by Strohgelaender — APPROVED** [review]
lgtm

**Comment by bassner** [comment]
Hey @julian-christl @MarkusPaulsen, please add a coverage table to your description. Thanks!

**Comment by julian-christl** [comment]
@bassner I added one, but honestly, we don't add trivial changes there. 80% is just renaming the one method anyway and in the FileService that I left we just extracted one method in three (trivial) and added two nullsafe variants to the parsing methods (which is why I added it in the end).

So not sure if that is what you expected, but there is not much else in the PR. It's just very small, very trivial changes. To fix one small and trivial problem.

**Pull request merged**
