### PR TITLE
Chore: increase lecture unit test coverage

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

The lecture unit feature was implemented without sufficient test coverage (especially in the client). This PR addresses this issue by greatly improving the test coverage.

#### Client
| File                                      | TestCoverage |
|-------------------------------------------|--------------|
| video-unit-form.component.ts              | 90%          |
| create-video-unit.component.ts            | 92%          |
| edit-video-unit.componen.ts               | 96%          |
| video-unit.component.ts                   | 100%         |
| videoUnit.service.ts                      | 100%         |
| attachment-unit-form.component.ts         | 90%          |
| attachment-unit.component.ts              | 88%          |
| create-attachment-unit.component.ts       | 92%          |
| edit-attachment-unit.component.ts         | 98%          |
| attachmentUnit.service.ts                 | 100%         |
| exercise-unit.component.ts                | 100%         |
| create-exercise-unit.component.ts         | 88%          |
| exerciseUnit.service.ts                   | 100%         |
| unit-creation-card.component.ts           | 100%         |
| lecture-unit-management.component.spec.ts | 84%          |

#### Server
| File                   | Coverage |
|------------------------|----------|
| TextUnitResource       | 80%      |
| VideoUnitResource      | 82%      |
| ExerciseUnitResource   | 87%      |
| AttachmentUnitResource | 82%      |
| LectureUnitResource    | 80%      |

### Steps for Testing

- No big changes to the functionality in this PR. Just Create, Update, Delete, Reorder the different unit types and also view them as a student :) 

Steps performed by me on the TestServer:

- [x] Created Lecture with all kind of lecture units and check corresponding student view
- [x] Reordering of the lecture units and check corresponding student view
- [x] Updating all kind of lecture units and checking corresponding student view
- [x] Removing all kind of lecture units and checking corresponding student view

### Test Coverage

See Description

### Screenshots

The `view` button were removed
image

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Works as expected. Tested with @simonzilker both from the instructor and student view

**Review by simonzilker — APPROVED** [review]
Tested with @airelawaleria . Everything worked as described.

**Review by EneaGore — APPROVED** [review]
Creating/Deleting/Ordering and Editing worked fine from both views.

**Review by JohannesWeiss — APPROVED** [review]
Worked fine.

**Review by LudwigWeide — DISMISSED** [review]
Tested lecture creation, reordering, updating and revomal without any issues form neither instructor nor student view.

**Review by FlorianStang — APPROVED** [review]
Everything worked fine for from creation to deletion on the Instructor side as well as the "participation" as student.

**Review by krusche — CHANGES_REQUESTED** [review]
Why did you delete this?
image

This should stay available and user should be able to navigate to it by either clicking the ID or the lecture title

**Comment by stefanwaldhauser** [comment]
> Why did you delete this?
> image
> 
> This should stay available and user should be able to navigate to it by either clicking the ID or the lecture title

reverted commit

**Review by krusche — APPROVED** [review]

**Review by simonzilker — APPROVED** [review]
Everything worked as stated

**Review by FlorianStang — COMMENTED** [review]
Everything worked as intended

**Pull request merged**
