### PR TITLE
`Lectures`: Fix display of exercise lecture units

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

When an instructor would add exercises to lectures as units, they would display incorrectly.
PR #4052, which fixed another bug by excluding certain attributes from exercises, introduced this issue where now the client component misses some data to display the exercise row correctly (such as `categories` and `participations`).

### Description

By reverting the change in #4052, the exercise component now again has all data to display correctly.
However, that meant that I had to fix the former bug differently.
I accomplished that by reworking the client-server interface in the lecture unit management page (for ordering the units). 
Now, only the IDs of the units and transmitted, which drastically improves the request size.
Additionally, the lecture units now also parse the exercise categories.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Lecture
- 1 Exercise of each kind

1. Log in to Artemis as instructor
2. Navigate to Course Administration, then to Lectures
3. Add the exercises as units to the lecture
4. Test that you can re-order all lecture units without issues and the order is persisted correctly
5. Test that you can edit lecture units and the lecture itself without any problems (e.g., make sure the bug described in #3958 did not re-appear)
7. Login as student
8. Make sure the exercises in the course overview are displayed equally on the lecture unit page
9. Make sure the exercise lecture units update accordingly when you submit a solution or the due date passes

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Method | Line |
|------------|-------:|-----:|
| LectureUnitResource.java | 66% | 50% |

### Screenshots

New and correct:
Screenshot 2022-05-03 at 14 55 33

Old and incorrect:
Screenshot 2022-05-03 at 14 58 20

### CODE REVIEW

**Review by max-bergmann — APPROVED** [review]
Tested on TS3 with @jschmautzer. Works as expected

**Review by jschmautzer — DISMISSED** [review]
tested on ts3 with @max-bergmann, works as in the screenshots shown

**Review by rhubinger — APPROVED** [review]
Tested on TS2, everything worked as advertised.

**Review by alaraozdenler — APPROVED** [review]
Tested on TS1, works as described

**Review by yuling-sun — APPROVED** [review]
Tested on TS2. The changes work as described.

**Pull request merged**
