### PR TITLE
`Exam mode`: Improve action details in live statistics

### PR DESCRIPTION
**Pull request by Dominik-Weinzierl**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Since the text doesn't look as nice as badges, I replaced the text with badges and icons.

### Description

- Replaced text with badges

### Steps for Testing

Prerequisites:
- 1 Instructor
- One/Multiple Student
- 1 Exam

1. Log in to Artemis
2. Create an Exam with Exam Live Statistics enabled
3. Participate with the student
4. Verify that the exercise section and activity section shows the correct data
5. Verify that the badges work as expected

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

badges
type

### CODE REVIEW

**Review by JohannesStoehr — COMMENTED** [review]
Code and Screenshots look good.
Could you also include translations for the categories (e.g. already done in assessmentType.json for the assessment types)

**Comment by Dominik-Weinzierl** [comment]
>  Could you also include translations for the categories (e.g. already done in assessmentType.json for the assessment types)

At the moment this is not planned, but we can think about adding translations in the future (which imo is not necessary, as the actions are implementation specific data that does not need a German translation). Adding translations needs additional refactoring which is out of scope of this PR.

**Review by ge65cer — APPROVED** [review]
Tested on TS2, works. Code also approved.

**Review by manuelmanso — APPROVED** [review]
Changes look good

**Review by mallgaier — APPROVED** [review]
Tested on TS1, works as expected 👍

**Review by max-bergmann — APPROVED** [review]
Tested on TS1. works as expected

**Review by yuling-sun — APPROVED** [review]
Tested on TS1. Works as described.

**Review by minrows — APPROVED** [review]
Tested on TS1 during testing session, works as expected 👍

**Review by akesfeden — APPROVED** [review]
Tested on TS1 during testing session, live statistics seem correct and new badges look nice.

**Review by babyygemperor — APPROVED** [review]
Tested on ts1, works as described

**Pull request merged**
