### PR TITLE
[Small Fix] Removing Duplicated Warnings for Improper SCA Settings

### PR DESCRIPTION
**Pull request by niclasschuemann**
### Motivation and Context
Putting invalid input in the max static code analysis penalty input field leads to two different warnings, one of them without a translation. This should not be the case.

### Description
I removed the min and max constraints because those were already covered by the pattern that checks if the input is valid. Having min and max set together with a pattern triggers two validity checks. If both validity checks fail, two warnings will be displayed.

### Steps for Testing
1. Open the programming exercise creation view
2. Enable Static Code Analysis
3. Enter a negative number and one above 100
4. Ensure that only one warning is displayed (see screenshots)

### Screenshots
**Previously:**
previously

**After:**
afterfix

### CODE REVIEW

**Review by Malyuk-A — APPROVED** [review]
Tested on TS1 works as described. 👍

(This is most likely not important and not part of your change, but I found a possible issue, where the warning is missing)
image
image

The exercise is actually created but when you look at the details again the field is blank, so no big deal, but a warning would be nice, or simply prohibit the use of + or - (the maximum is 2 signs in front as far as I have tested this).😅

image

**Review by joschahenningsen — COMMENTED** [review]
This works, but is there a reason we use regex to validate that the penalty is in range? If it's because we don't allow decimals I'd prefer using `step="1"` on the input element and adjusting the translations.
Semanically the min and max attributes make sense (for accesibility and code-readability reasons). 
Am I missing something here?

**Review by argertboja — COMMENTED** [review]
Looks good on TS1 👍🏼

**Comment by niclasschuemann** [comment]
@joschahenningsen Thank you for the feedback! I have tried your suggestion, but it does not help with the "integer check", at least my implementation did not provide any warning for decimals. I will check if this check is really relevant.

**Review by Olimbia23 — APPROVED** [review]
Looks good!

**Review by ivanchimeno — APPROVED** [review]

**Review by joschahenningsen — APPROVED** [review]
https://github.com/ls1intum/Artemis/pull/3682#issuecomment-874328534 Was just a nit, your solution works just fine :)

**Review by ivohashamov — APPROVED** [review]

**Review by ArtemTsurikov — APPROVED** [review]
Looks fine on TS1

**Pull request merged**
