### PR TITLE
`Programming exercises`: Fix auxiliary repositories not visible on exercise detail page

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.

### Motivation and Context
I noticed in the live server, that links to auxiliary repositories were no longer shown on the exercise detail page, even if they exist.

### Description
This was caused by overwriting the local `programmingExercise` object after a second server call. The request to `with-template-and-solution-participation` does not contain the auxiliary information anymore:

grafik

With this PR, the second call now also sends the necessary information about auxiliary repositories to the client.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Programming Exercise with auxiliary repositories

1. Open the exercise detail page
2. Check that links to the auxiliary repositories are shown

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
grafik

### CODE REVIEW

**Review by simon-hng — DISMISSED** [review]
Code changes look good

**Review by PhilipWerz — APPROVED** [review]
Link to auxiliary repositories are shown on details page. Tested on TS1.

**Review by tobias-lippert — APPROVED** [review]
Tested on ts1. Auxiliary repository is shown on the exercise details page and link redirects to the repository on bitbucket.

**Review by nikirovast — DISMISSED** [review]
Tested on ts1, seems good to me!

**Review by JohannesStoehr — DISMISSED** [review]
Codechanges and tests look good.
Should we also rename the endpoint or at least its method name, since it now also returns the auxiliary repositories?

**Review by timo07k — DISMISSED** [review]
Works as expected, links to auxiliary repositories are shown. Tested on TS1.

**Comment by Strohgelaender** [comment]
I don't think we should rename the endpoint. While auxiliary repositories are technically a new entity that needs to be loaded, I would consider them a normal part of the exercise details. Since they are also included in the regular endpoint for retrieving a PE, they should also be in this case. Also this would make the endpoint name quite long.

**Review by simon-hng — APPROVED** [review]
Code

**Pull request merged**
