### PR TITLE
Improve user service

### PR DESCRIPTION
**Pull request by krusche**
This PR addresses a couple of issues with the user service, including a bug that is probably related to caching user entities.

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
When users get instructor or tutor rights, they need to logout and login again, most probably because of caching issues.

### Description
I fixed some caching issues and refactored the code so that it is easier to understand and cleaner.
This also fixes some smaller issues when deleting users and adds a TODO to cleanup all user related 

### Steps for Testing
You need 2 users (A, B) and 1 course (C)
C: Course
A: Instructor in C
B: Normal user (who has not any instructor rights yet)

1. Log in to Artemis with both users in two different browsers
2. User A: Navigate to Course Administration and grant B instructor rights in C
3. User B: Refresh the page and check that you can see course administration now (without logout and login)
4. User A: Remove B from the instructors in C
5. User B: Refresh the page and check that you cannot see course administration now (without logout and login)

Please also test other related use cases:
* Course registration for students on TS1 and TS2 should work as before
* Login and logout should work as before
* Registering a new user account (TS2) should work as before

### CODE REVIEW

**Review by LudwigWeide — APPROVED** [review]
Tested on TS2 and TS3. Worked as intended.

**Review by JohannesWeiss — APPROVED** [review]
Tested on TS2 and TS3 and worked as intended.

**Review by FlorianStang — APPROVED** [review]
Tested on TS2 and TS3 and everything worked as intended.

**Review by JannisBittlmayer — APPROVED** [review]
Tested on TS2 and TS3, works as indended.

**Review by marvinchimeka — APPROVED** [review]
Tested on TS2 and TS3 and everything worked as intended.

**Review by stefanwaldhauser — CHANGES_REQUESTED** [review]
I tested the following scenario on TS3: I added artemis_test_user_50 to instructor for my course StefanWTestCourse. I can now see the course-administration page but when I click on it. Even refreshing the page does not solve the problem.
image
It works if i log out and log in again for artemis_test_user_50

**Review by TobiasPr — CHANGES_REQUESTED** [review]
image
Can confirm what @stefanwaldhauser said. If a user who is not a instructor in any course yet, becomes a instructor the course-management site is not accessible after reload.
Tested on TS3

**Review by FuchsDominik — COMMENTED** [review]
Also tested on TS3, same findings. 
image

**Comment by krusche** [comment]
@FuchsDominik @stefanwaldhauser @TobiasPr I just tested it again locally and it works like a charm. I cannot reproduce your error. Can you please double check and help me to reproduce the issue?

**Comment by krusche** [comment]
Ok, I can now reproduce the issue. The problem is the authentication mechanism for roles using 

`@PreAuthorize("hasAnyRole('TA', 'INSTRUCTOR', 'ADMIN')")`

To make this check super fast (and to prevent database access), the authentication seems to be retrieved from the bearer token (I need to double check this), which would basically mean that there is currently no other way than logging out and logging in again to get the new rights.

**Comment by krusche** [comment]
> Ok, I can now reproduce the issue. The problem is the authentication mechanism for roles using
> 
> `@PreAuthorize("hasAnyRole('TA', 'INSTRUCTOR', 'ADMIN')")`
> 
> To make this check super fast (and to prevent database access), the authentication seems to be retrieved from the bearer token (I need to double check this), which would basically mean that there is currently no other way than logging out and logging in again to get the new rights.

Yes, this is the case and there seems to be no easy way to break this :-(
We basically would need to regenerate the token of the user, but the question would be when this regeneration should happen. For performance reasons, we cannot re-generate it all the time.

**Pull request merged**
