### PR TITLE
`General`: Remove next exercise to simplify the user interface

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Quiz that starts in 10min

1. Log in to Artemis
2. Navigate to Course Overview 
3. Verify that next exercise is not displayed
4. Navigate to Course Exercises
5. Verify that Next exercise is not displayed 

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [programming-exercise.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5978/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/services/programming-exercise.service.ts.html) | 90,13% | ✅ |
| [exercise.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5978/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/exercise/exercise.service.ts.html) | 91.97% |✅ |
| [course-exercises-grouped-by-week.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5978/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-exercises/course-exercises-grouped-by-week.component.ts.html) | 100% | ✅|
| [courses.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5978/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/courses.component.ts.html) | 93.87% | ✅ |

## Summary by CodeRabbit

- **New Features**
  - Enhanced test coverage report functionality for programming exercises.
- **Bug Fixes**
  - Fixed an issue where the title of an exercise might not correctly update in certain scenarios.
- **Refactor**
  - Simplified exercise grouping by week in course overview, removing unnecessary dependencies and logic.
  - Streamlined course management features by removing exercise-related functionality.
- **Tests**
  - Expanded test coverage for programming exercises, including various new test cases for exercise management and functionality.
- **Chores**
  - Updated import paths for better consistency and maintenance.

### CODE REVIEW

**Review by pzdr7 — COMMENTED** [review]
Tested on TS2:
- As instructor, created a quiz exercise that starts in 10 minutes, then signed in as student
- **Course overview**: The "Current active exercise in (course)" does not appear.
- **Course exercises**: "Current exercise active until (...)" does not appear.

Is this what "next exercise" in the PR description refers to?

**Review by georgyia — COMMENTED** [review]
It does appear for me, manually tested on ts2, I don't really understand what is expected tbh
Снимок экрана 2024-02-07 в 16 55 53

**Review by pzdr7 — APPROVED** [review]
Worked as intended - thanks for clarifying.

**Review by georgyia — APPROVED** [review]
reapprove

**Review by bassner — APPROVED** [review]

**Pull request merged**
