### PR TITLE
`Exam mode`: Enhance import

### PR DESCRIPTION
**Pull request by mallgaier**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
This Pr fixes some minor issues regarding the intruced Exam Import

### Description
**Enhance appearance of exam management page on mobile devices**
On mobile devices, the buttons for importing / creating an exam are now displayed properly

**Display warning when importing into same course**
When importing programming exercises into the same course, the old title + short name are placed on a blocklist in the client, so the user has to change them before importing.

**Fix translation string**
When opening the exercise import dialoge, the string within the blue box cointained "tasks" instead of "exercises"

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam with one exercise group with one programming exercise

1. Log in to Artemis
2. Navigate to Course Administration -> Exam
3. Resize the Site and make sure, the buttons are displayed properly
4. Try to import the exam with programming exercises into the same course. The title + short name should be displayed as invalid
5. Navigtate into Exam -> Exercise Group
6. Try to import the exercise group with the programming exercise into the same course. The title + short name should be displayed as invalid
7. Verify, that the string within the blue container in the exercise dialoge doesn't cointain "tasks", but "exercises"

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| exam-import.component.ts | 80 % | 96 % |
| exam-exercise-import.component.ts | 100 % | 100 % |
| exam-update.component.ts | 89 % | 96 % |

### Screenshots
Resizing exam management (regarding the two buttons on the top)

Fixed string in the blue box and warning, when importing into the same course
image

### CODE REVIEW

**Review by manuelmanso — APPROVED** [review]
Tested in ts2, works as expected. Code LGTM, comments are also very helpful 👍

**Comment by joaquinmurcia** [comment]
Tested on TS1. Everything works as expected:
1.
image
2,3. 
image

**Review by nairaarnez — APPROVED** [review]
Tested in TS1, works as described!

**Review by pantageepapa — APPROVED** [review]
Tested on ts3 and it works as expected!

**Review by babyygemperor — APPROVED** [review]
Tested on ts1, works as described

**Pull request merged**
