### PR TITLE
`Development`: Update client and server dependencies

### PR DESCRIPTION
**Pull request by krusche**
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] All relevant checks pass.

### Testing steps
- [x]  Try out all PDF features, in particular slide splitting when uploading a PDF (with various configurations as instructor) and merging multiple PDFs from lecture units (download as student)

### CODE REVIEW

**Review by tobias-lippert — APPROVED** [review]
Code LGTM
Tested in testing session. Everything we tested regarding pdf manipulation worked.

**Review by dearjasmina — APPROVED** [review]
tested in the testing session, works as expected

**Review by Strohgelaender — APPROVED** [review]
tested in testing session, merging pds and uploading exam users still works as expected.

code looks good as well.

**Review by laurenzfb — APPROVED** [review]
Tested in testing session. Worked as expected

**Review by aplr — APPROVED** [review]
Tested in testing session, PDF split & merge does not break

**Pull request merged**
