### PR TITLE
`General`: Fix height of course card with no statistics

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Description

A course card with no statistics now has the same hight as one with statistics.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Compare a course with no statistics to a course with statistics on the front page
3. ...

#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Old:
Bildschirmfoto 2022-06-23 um 21 56 25
Fixed:
Bildschirmfoto 2022-06-23 um 21 55 53

### CODE REVIEW

**Review by julian-christl — APPROVED** [review]
Tested on TS2, works.
After an extensive code review, I can also attest to the quality of the code changes.

**Review by willergeorg — APPROVED** [review]
I checked your code. This elegance, this efficiency is mind-blowing. Thanks for giving me the opportunity to see this.

**Review by SimonPaul02 — APPROVED** [review]
Tested on TS1, works as expected

**Review by SimonPaul02 — APPROVED** [review]
Reviewed code. Well done! I'm proud to say that I've seen such excellent work with my own eyes

**Review by babyygemperor — APPROVED** [review]
Tested on ts2, works as described.
It has been an honour to witness such excellent code.

**Review by max-bergmann — APPROVED** [review]
tested on ts1. looks good

**Pull request merged**
