### PR TITLE
`Exam mode`: Speedup unlock operation for programming exercises

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Unlocking many repositories could take some time. This PR aims to speedup the process.

### Description
The performance increments come from:
- Reducing the needed calls to the external system from 2 to 1 (we only configure the branch settings once, that's not needed every time).
- Removing an unnecessary database call that was executed for every participation.

This cuts the time needed for the unlock operation in half!

The other changes in this PR are refactorings:
- Since the unlock operations don't need the programming exercise, we removed the parameter. This should avoid unnecessary database operations in the future.
- There were two duplicated enums containing repository permissions. We now removed one of them.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Exam with many participations

1. Use prepare exercises to create the repositories
2. Verify that branch protection rules are in place. Verify that the students cannot push to the repository.
3. Use the "unlock repositories" button or wait until the planed start of the exercise
4. Verify that all participations got successfully unlocked.

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by terlan98 — APPROVED** [review]
Tested on TS5. The repositories got unlocked 5 minutes before the start time of the exam. As far as I know, that's the intended behavior, but it would be great if you mentioned it in `Steps for Testing` 🙂 

The **lock** and **unlock** buttons also work as intended, switching the repository permissions to **read** and **write** respectively 👍

**Review by terlan98 — COMMENTED** [review]
I noticed that when a student attempts to push to a locked repository via the online editor, Artemis shows 3 errors at once. I think it would be better to just show a single error stating that the repository is locked. **I'm not sure if this is related to this PR, though**:
Screenshot 2023-07-25 at 20 41 59

**Comment by Strohgelaender** [comment]
@terlan98 This issue is already documented in the exam mode issue list and did not get introduced by this PR.

**Review by krusche — APPROVED** [review]
Tested on staging, the changes in this PR allow the unlock operation to be twice as fast 👍 great work

**Pull request merged**
