### PR TITLE
`Communication`: Fix visibility of the edit message option for non-authors

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

As agreed, the "edit message" option should only be enabled for users if they are the author of the post. However, instructors currently have the ability to edit messages posted by other users.

### Description

The "edit message" option is only visible if the logged-in user is the author of the post.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Course with Communication enabled

1. Log in to Artemis as a student.
2. Navigate to the Communication section of a course.
3. Send some messages to a channel and add some replies to those messages.
4. Verify that you can edit your own posts/replies by clicking the "edit message" option, either from the hover bar or the dropdown menu that appears when you right-click.
5. Log in to Artemis as an instructor and navigate to the same channel in the Communication section.
6. Attempt to edit the messages sent by the previous user and verify that the "edit message" option is now disabled if the user is not the author of the post, even if s/he is an instructor.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [X] Code Review 1
- [X] Code Review 2
#### Manual Tests
- [X] Test 1
- [X] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| answer-post.component.ts | 94.23% | ✅ ❌ |
| post.component.ts | 95.23% | ✅ ❌ |
| answer-post-reactions-bar.component.ts | 90.69% | ✅ ❌ |
| post-reactions-bar.component.ts | 93.1% | ✅ ❌ |

## Release Notes

- **New Features**
	- Enhanced user permissions handling for editing and deleting posts with clearer distinctions in the UI.
	- Added confirmation tooltip for delete actions.
  
- **Bug Fixes**
	- Improved conditional rendering for edit and delete buttons based on user permissions.

- **Tests**
	- Refined test cases to accurately reflect user permissions for editing and deleting posts.
	- Added new tests to ensure correct visibility of options based on user roles.

### CODE REVIEW

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS5. Works as described. Instructor can only delete but not edit students' messages anymore, only the authors of the messages can

**Review by HawKhiem — APPROVED** [review]
Tested on TS5. Logged in as test user 20. Editing another user post as instructor is now not possible as described. Editing as owner of post works fine

image

**Review by sawys777 — APPROVED** [review]
Tested on TS1, everything worked accordingly to the instruction.

**Review by sachmii — APPROVED** [review]
Tested on TS3, as described, I cannot edit messages sent by other users even as an instructor.

student view:
student view

instructor view:
instructor view

**Review by ItsaaaMeMario — APPROVED** [review]
Tested on TS3, everything works as described. 

Bildschirmfoto 2024-11-23 um 14 47 47

**Pull request merged**
