### PR TITLE
`Quiz exercises`: Don't open the feedback detail view on results

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Fixes Student-issue 12 from the exam mode testing

Quiz exercises don't use the `Feedback` objects, opening the details shows `No Results available`:
grafik

### Description
No longer open the feedback details for quiz exercises.

### Steps for Testing
Prerequisites:
- 1 Student
- 1 Quiz Exericse

1. Participate in the quiz
2. Check that the result is no longer clickable. Instead, the result is understandable just by the details next to the questions

#### Exam Mode Testing
Same as above with a quiz integrated into an exam.

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

### CODE REVIEW

**Review by PhilipWerz — APPROVED** [review]
Works as expected. Does not open deeback detail anymore. Tested on TS1.

Remark (not that important imo):
Only thing I noticed is that cursor is still the "click mouse" image when hovering over the results although it isn't clickable anymore.

**Review by JohannesStoehr — COMMENTED** [review]
Should we also change the styling (i.e. no line beneath), such that it is clearer that you cannot click on the result?

**Review by timo07k — APPROVED** [review]
Works as expected. Now looks like this, cursor "makes more sense":

Image

Tested on TS1.

**Review by tobias-lippert — APPROVED** [review]
LGTM

**Review by PhilipWerz — APPROVED** [review]
Reapprove: Cursor and style is better now. Works as expected. Tested on TS1.

**Review by JohannesStoehr — APPROVED** [review]
Thanks for adapting the style. Code changes look good to me

**Pull request merged**
