### PR TITLE
`Plagiarism checks`: Hide other plagiarism case submission before exercise due date

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
Continuous plagiarism control (CPC) introduce a possibility that a plagiarism case will be created before the exercise due date. If that happens, Artemis needs to hide the submission of the other student.

### Description
This PR adds a logic for hiding the other submission when plagiarism case is viewed by student before the exercise due date. Change applies to the client and the server. On the client side, Artemis will not load the other submission. On the server side, Artemis will reuse 403 if student tries to retrieve the second submission before the due date.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 2 Students (⚠️ make sure that those student are not instructors not tutors in the course)

1. Create an Exercise with a due date in the future.
2. Create two identical submission by two difference students (add student login at as the first word, so that you can distinguish them). 
3. Log in as instructor and go to the exercise view, then select _Check plagiarism_
4. Start plagiarism checks.
5. When they are done, select the comparison and confirm it.
6. Go to the course page -> _Assesment_ -> _Plagiarism Cases_ and open the case for one of the two students.
7. Notify the student by posting the default post.
8. Log in as that student, navigate to this exercise's participation page and select the _Plagiarism Case_ button.
9. Verify than you can only see you own submission and that the other submission is empty.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| text-submission-viewer-component.ts | 87% | ✅              |
| modeling-submission-viewer-component.ts | 92% | ✅              |

### Screenshots
Student's plagiarism case view before exercise due date:
image

## Summary by CodeRabbit

- **New Features**
  - Enhanced plagiarism detection with due date consideration for submission access.
  - Improved student view for plagiarism case reviews with anonymization based on exercise due dates.

- **Enhancements**
  - Plagiarism review components now have a `forStudent` attribute to tailor the display for student users.
  - Added `hideContent` functionality to submission viewer components to control content visibility.

- **Bug Fixes**
  - Fixed permission checks to prevent unauthorized access to submissions before the due date in various components.

- **Tests**
  - Implemented new integration tests to ensure proper access restrictions for modeling and text submissions.
  - Added front-end test cases to verify the new `hideContent` behavior in submission viewer components.

@coderabbitai ignore

### CODE REVIEW

**Review by LenaKahle — CHANGES_REQUESTED** [review]
Tested on ts2, works generally. I encountered 2 minor issues when testing:
1. When clicking "Notify student" and confirming the default message, it shows an internal server error. When reloading, it shows the message has been sent.
2. For some reason, the last two characters of each submission are not highlighted in the comparison views
image
Are these issues directly related to your pull request or separate issues?

**Comment by Ceiridge** [comment]
This has been tested in a testing with @MaximilianJG on test2 and works exactly as expected.
When the exercise has no due date, the other submission is visible. But when there is a due date in the future, the other submission is empty (see below).

image

**Comment by MaximilianJG** [comment]
Works as expected. Tested together in a testing session with @Ceiridge on testing server 2. When the exercise has a due date in the future the other students (plagiarized) is not visible. However when the exercise does not have a due date the comparison is visible

**Comment by jakubriegel** [comment]
Answers to review notes:

@LenaKahle The server error was caused by not configured email server on a ts - not part of this PR. Highlighting is also not a part if this - it is a known bug and we have an issue for it.

@MaximilianJG plagiarism case before due date can only be created by the CPC and the CPC works only for exercises with a due date, so this is not a problem for us

**Review by LenaKahle — DISMISSED** [review]
Approve. Thanks for the explanation!

**Review by dearjasmina — DISMISSED** [review]
code lgtm

**Review by egekurt123 — DISMISSED** [review]
Tested in testing session, Works as expected and Code LGTM

**Review by JanaNF — DISMISSED** [review]
Manual tested on legacy_ts2. Worked as expected

**Review by MarkusPaulsen — CHANGES_REQUESTED** [review]
Please do not merge without approval of @MarkusPaulsen.

**Review by MarkusPaulsen — COMMENTED** [review]
Code looks good to me.

**Review by JanaNF — CHANGES_REQUESTED** [review]
Re-tested on TS2. Two problems occured:
1. At step 7: As an instructor, I could not notify any of the two students. I always got an internal error.
image

2. At the last step: As a student, I saw the submitted text two times.
image

**Review by laurenzfb — DISMISSED** [review]
Tested in testing session. Worked as expected

**Review by vinceclifford — DISMISSED** [review]
Works as expected, tested during testing session

**Review by basak-akan — DISMISSED** [review]
Demonstrated during the testing session, worked as expected

**Review by sarpsahinalp — APPROVED** [review]
Workes as expected. Tested during testing session.
image

**Comment by jakubriegel** [comment]
> Re-tested on TS2. Two problems occurred:
> 
> 1. At step 7: As an instructor, I could not notify any of the two students. I always got an internal error.
>    image
> 2. At the last step: As a student, I saw the submitted text two times.
>    image

Issues discussed offline. Summary: first error is caused by testing the feature on a ts without email support. The second one is a know issue of plagiarism comparison and is not part of this PR (#6579)

**Review by JanaNF — APPROVED** [review]

**Review by basak-akan — APPROVED** [review]
reapprove after merge conflict resolved

**Review by laurenzfb — APPROVED** [review]
reapprove after resolving conflicts

**Review by LenaKahle — APPROVED** [review]
Reapprove.

**Review by egekurt123 — APPROVED** [review]
Reapprove after solving merge conflicts

**Review by MarkusPaulsen — APPROVED** [review]
Code looks good to me

**Pull request merged**
