### PR TITLE
`Learning path`: Fix scheduling of exercises linked to multiple competencies

### LINKED ISSUE #8623: `Learning path`: Learning objects linked to several competencies are represented multiple times in the learning path

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

If an exercise or lecture unit is linked to multiple competencies they are currently duplicated in the learning path which should not be the case.
Fixes #8623

### Description

We now track the already scheduled learning objects and do not schedule them again for further competencies.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Course with activated learning paths

1. Log in to Artemis
2. Create at least two competencies
3. Create one exercise and one lecture with a lecture unit and link them to both competencies
4. Check the learning path in the path representation (i.e. when participating in the learning path as a student)

#### Performance Review
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
  - Improved scheduling logic to prevent duplicate scheduling of learning objects linked to multiple competencies.

- **Bug Fixes**
  - Enhanced learning path recommendations to ensure learning objects are not duplicated in the suggested order.

### CODE REVIEW

**Review by JohannesWt — APPROVED** [review]
Code looks good - You could just also add the issue link to the description

**Review by az108 — APPROVED** [review]
Code LGTM

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS3, and code looks good :+1:

**Review by pzdr7 — DISMISSED** [review]
Code LGTM 👍

**Review by MaximilianAnzinger — CHANGES_REQUESTED** [review]
Exercises linked to multiple competencies should still be included for both competencies in the dependency graph.

**Review by egekurt123 — APPROVED** [review]
Code LGTM

**Review by pzdr7 — APPROVED** [review]
Code

**Comment by JohannesStoehr** [comment]
Will be fixed in #8733

**Pull request closed without merging**
