### PR TITLE
`Development`: Improve code quality of learning path and competency related server code

### PR DESCRIPTION
**Pull request by MaximilianAnzinger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Description

Improves code quality by extracting business logic into services and optimization of database requests.

### Steps for Testing

In theory, this is only refactoring that shouldn't break anything.
You should still test EVERYTING related to Competencies (creation, import, delete, linking, relations, etc.).

#### Performance Review
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [CompetencyRepository.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.repository/CompetencyRepository.html) | 61% | ✅  |
| [ExerciseService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/ExerciseService.html) | 97% | ✅  |
| [LectureUnitService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/LectureUnitService.html) | 96% | ✅  |
| CompetencyProgressService.java | not found (renamed) | ❌ |
| [CompetencyRelationService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.competency/CompetencyRelationService.html) | 100% | ✅ |
| CompetencyService.java | not found (renamed) | ❌ |
| [LearningPathNgxService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.learningpath/LearningPathNgxService.html) | 97% | ✅  |
| [LearningPathRecommendationService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.learningpath/LearningPathRecommendationService.html) | 98% | ✅  |
| [LearningPathService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.learningpath/LearningPathService.html) | 98% | ✅  |
| [ParticipantScoreScheduleService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.scheduled/ParticipantScoreScheduleService.html) | 91% | ✅  |
| [CompetencyResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/CompetencyResource.html) | 98% | ✅  |
| [LearningPathResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/LearningPathResource.html) | 95% | ✅  |
| [CompetencyRelationDTO.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.dto.competency/CompetencyRelationDTO.html) | 100% | ✅ |
| [LearningPathInformationDTO.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.dto.competency/LearningPathInformationDTO.html) | 100% | ✅ |
| [NgxLearningPathDTO.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.dto.competency/NgxLearningPathDTO.html) | 100% | ✅ |
| [UserNameAndLoginDTO.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.dto.user/UserNameAndLoginDTO.html) | 100% | ✅ |
| [AttachmentUnitResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.lecture/AttachmentUnitResource.html) | 92% | ✅  |
| [LectureUnitResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.lecture/LectureUnitResource.html) | 92% | ✅  |
| [OnlineUnitResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.lecture/OnlineUnitResource.html) | 91% | ✅  |
| [TextUnitResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.lecture/TextUnitResource.html) | 96% | ✅  |
| [VideoUnitResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6048/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest.lecture/VideoUnitResource.html) | 93% | ✅  |

## Summary by CodeRabbit

- **New Features**
    - Replaced learning path imports with competency-related imports for improved functionality.
    - Delegated logic to `competencyService` for creating and updating competencies.
    - Enhanced linking of lecture units to competencies.
    - Introduced `CompetencyProgressService` for competency tracking.

- **Refactor**
    - Restructured package organization for competency services.
    - Updated method signatures to use `long` for `competencyId` and `courseId`.

- **Bug Fixes**
    - Adjusted import statements for `CompetencyProgressService` across various resources.
    - Improved consistency and readability with static factory methods for DTO instances.

- **Tests**
    - Updated `LearningPathServiceTest` to align with refactored codebase changes.

### CODE REVIEW

**Review by Gusti2010 — APPROVED** [review]
manually tested everything related to Competencies (creation, import, delete, linking, relations, etc.) on ts11_Legacy. Works as expected!

**Review by rstief — DISMISSED** [review]
Tested in testing session

**Review by reschandreas — APPROVED** [review]
tested in testing session on ts1, works as expected

**Review by laurenzfb — DISMISSED** [review]
tested on ts1 as a student, works

**Review by basak-akan — DISMISSED** [review]
Tested as an instructor during the testing session, no issues found

**Review by georgyia — DISMISSED** [review]
manually tested creation, import, delete, linking, relations, etc. on ts2, works as expected

**Review by reschandreas — APPROVED** [review]
reapprove

**Review by laurenzfb — APPROVED** [review]
reapprove

**Review by rstief — APPROVED** [review]
Reapprove after merge

**Review by basak-akan — APPROVED** [review]
Re-approve after merge

**Pull request merged**
