### PR TITLE
`Plagiarism checks`: Increase interactivity of similarity distribution chart

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

This PR increase the interactivity of the similarity distribution chart of detected plagiarism cases

### Description

What is changed in this PR:

- **Help icon**: Next to the bar title is now a help icon with a tooltip explaining what is visualized by the chart and emphasizing that those cases have to be confirmed manually in order to punish them.
- **Enhanced bar labels**: The bar labels are now displaying the exact borders of the intervals in order to make it more transparent what is displayed by every chart bar
- **Color coding**: The bars representing cases with similarity >= 80% are now colored red
- **Datalabels**: Above each bar now a datalabel show the numeric value represented by the bar
- **Enhanced tooltips**: The tooltips of the bars are now more comprehensive and contain the relative amount they represent in regards to the number of total detected cases. In addition they itemize the represented cases in number of confirmed, declined and open cases.
- **Filter function**: By clicking on a bar, the cases displayed on the left side get filtered accordingly. Additionally, a disclaimer is shown informing the user that the cases are currently filtered and of course a reset button appears in the header.

Smaller additional improvements:

- The chart is now fitted to consume the whole page width
- The chart title is centered
- I refactored some code on different places. Mostly reoccurring functionality that is now implemented at a central place and reused

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Text/Modeling/Programming exercise with detected plagiarisms

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to the corresponding exercise detail page
4. Click "Check plagiarism"
5. If not done yet, run the plagiarism detection
6. Click "Run details" and inspect the chart. Make sure everything is comprehensive. Check that the tooltips itemize the cases correctly
7. Confirm a case. Check that the tooltip of the corresponding bar updated correctly
8. Do the same after denying a case
9. Select an arbitrary bar. Make sure the cases get filtered correctly and that the numbering is still as it is without filtering. Also make sure that a disclaimer appears after filtering as well as the reset button in the header.
10. Check that the confirming and denying still works when cases are filtered and the chart tooltips get updated accordingly. 

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| File name | Branch coverage (%) | Line coverage (%) |
| -- | -- | -- |
| `plagiarism-inspector.component.ts` | 76.47 | 90.51|
| `plagiarism-inspector.service.ts` | 100 | 100 |
| `plagiarism-run-details.component.ts` | 77.77 | 87.5 |

### Screenshots

Example workflow:

https://user-images.githubusercontent.com/80622272/152644476-ca8c0111-6583-4c93-90d4-2c9195d50dcc.mp4

### CODE REVIEW

**Review by filip-gregurevic — APPROVED** [review]
Code changes look good to me. Nice job 🚀

**Review by Malyuk-A — APPROVED** [review]
Thank you for applying my few nitpicks so quickly. Code looks good to me now.

**Comment by willergeorg** [comment]
> I have tested this on TS2 with 5 different/not so different/same submissions and I can confirm everything is working exactly as expected! ✅
> 
> I do have one suggestion though that you may or may not consider. If you look at the next screenshot you can see that I can scroll down the list of cases on the left and lose out of sight the pair that I'm currently checking for plagiarism. However, the only place where I can see if the case has been confirmed or not is that list (green or red dot). Since the buttons are not changed with confirming/denying, there is a possibility that I will check again this pair without knowing I already checked it.
> 
> confirm_deny
> 
> My idea would be to disable the `Confirm` button for confirmed cases / the `Deny` button for denied cases. Something similar to the next screenshot. Thoughts?
> 
> disabled_confirm

That is indeed a considerable improvement, thanks for suggesting it. But I think it is not in scope of this PR since this problem is not created by my changes. I would like to keep it in mind for a followup. 👍

**Review by mallgaier — APPROVED** [review]
Tested on TS1 together with @lBruchmann , @VinnavanSembian and @Strohgelaender .
Looks good!

**Review by VinnavanSembian — APPROVED** [review]
tested on ts1 with @lBruchmann @Strohgelaender @mallgaier: Everything works well!

**Review by ole-ve — APPROVED** [review]
Tested on TS3, works as described 👍
It would probably be an idea that the 'Run details' page is displayed when opening the Plagiarism Check (instead of the first plagiarism case).

**Review by Strohgelaender — APPROVED** [review]

**Pull request merged**
