### PR TITLE
`Lectures`: Fix lecture unit file attachment names

### PR DESCRIPTION
**Pull request by SimonEntholzer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

The file names in the lecture unit have long cryptic prefixes, which are not relevant for users:
image
 When the user downloads the file, it's named like shown. 
image

### Description

This PR removes the prefix for the displayed name, and for the downloaded file.
image
image

### Steps for Testing

Prerequisites:
1. Create a lecture unit and add a file (with spaces)
2. View the lecture unit, and download the file
3. Make sure there is no 'Attachment_date' prefix 

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| lecture-attachments.component.ts | 96.39% | ✅ ❌ |
| attachment-unit.component.ts | 94.11% | ✅ ❌ |
| course-lecture-details.component.ts | 98.61% | ✅ ❌ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| AttachmentResource.java | 99% | ✅ ❌ |

## Summary by CodeRabbit

- **New Features**
	- Improved file name readability for attachments by removing prefixes and replacing underscores with spaces.
	- Enhanced download functionality to ensure consistent formatting of file names and links.
	- Expanded icon support for various file types, improving visual representation in the interface.

- **Bug Fixes**
	- Updated error handling during file deletions to manage exceptions related to attachment database entries.

These changes aim to provide a better user experience when handling and downloading attachment files.

### CODE REVIEW

**Review by ItsaaaMeMario — CHANGES_REQUESTED** [review]
Tested on TS1, I uploaded a PDF named 'Artemis 1 TEST PDF.pdf' and downloaded it via Artemis.  The 'attachment_date' prefix is still visible.
Bildschirmfoto 2024-11-09 um 18 17 23

**Comment by SimonEntholzer** [comment]
> Tested on TS1, I uploaded a PDF named 'Artemis 1 TEST PDF.pdf' and downloaded it via Artemis. The 'attachment_date' prefix is still visible. Bildschirmfoto 2024-11-09 um 18 17 23

Ok that's weird, for me it works on TS1, also the downloaded name

**Review by HawKhiem — DISMISSED** [review]
Tested on TS3 on Firefox. Works as described

image

**Review by ahbitaqu — COMMENTED** [review]
[Tested on TS2]
Works perfectly fine for me!
image

**Review by ahbitaqu — APPROVED** [review]

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Both the lecture unit and the lecture attachment worked as described

Screenshot 2024-11-09 210735
Screenshot 2024-11-09 210903

**Review by ahbitaqu — APPROVED** [review]
[Tested on TS1]
works on both, lecture and attachment-unit. Re-approve

**Review by BBesrour — APPROVED** [review]
code lgtm

**Pull request merged**
