### PR TITLE
`Exam mode`: Fix an issue where the end page of exam does not scroll when the page is too small

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

In the end page of student view of exam mode, users can not scroll down if the page gets too small. 

### Description

I added a scrollbar if the user is currently in the end page of an exam. 

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Exam

1. Log in to Artemis
2. Participate the exam
3. Click on Hand in Early
4. Verify that you can scroll down if the page gets too small in height

#### Exam Mode Testing

Prerequisites:
- 1 Student
- 1 Exam 
- 
1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of other components in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exams/students_guide.html#participating-in-the-artemis-online-exam) as reference.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Screenshots

Screenshot 2024-06-28 at 19 33 23

## Summary by CodeRabbit

- **New Features**
  - Introduced end view tracking for exams, enhancing the monitoring and display of exam completion status.

- **Style**
  - Added new styles for exam end view and adjusted hover behavior for specific anchor tags, improving UI consistency.

- **Bug Fixes**
  - Ensured proper display of text content in exam cover component based on exam view status.

- **Tests**
  - Updated test mocks to support new end view tracking functionality.

### CODE REVIEW

**Review by pzdr7 — APPROVED** [review]
Tested on TS5. The page is scrollable even with a small window 👍

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS1, and works as expected. Code lgtm too

**Comment by egekurt123** [comment]
I'm not sure if that's a scenario we need to address, but if you narrow the page so much that the footer disappears, scrolling doesn't work. I assume that no student has such a small screen
Screenshot 2024-06-29 at 10 53 32

**Review by egekurt123 — COMMENTED** [review]
I'm not sure if that's a scenario we need to address, but if you narrow the page so much that the attached footer disappears, scrolling doesn't work. I assume that no student has such a small screen

Screenshot 2024-06-29 at 10 53 32

**Comment by edkaya** [comment]
> I'm not sure if that's a scenario we need to address, but if you narrow the page so much that the attached footer disappears, scrolling doesn't work. I assume that no student has such a small screen
> 
> Screenshot 2024-06-29 at 10 53 32

I don't think it is going to be a problem because I am not sure if such a small screen is a realistic use case, but I can discuss this with @rabeatwork on Monday 👍 Since, this PR only fixing the scroll problem in end page and we don't use this footer in end page, it will not be in the scope of this PR.

**Review by sarpsahinalp — APPROVED** [review]
Code lgtm

**Review by egekurt123 — APPROVED** [review]
Code LGTM

**Review by rabeatwork — APPROVED** [review]
maintainer approve

**Review by krusche — APPROVED** [review]

**Pull request merged**
