### PR TITLE
`Programming exercises`: Fix student build plan creation in Jenkins setups

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Build plans for students are not working in Jenkins setups. The build plan contains a link to the base exercise template rather than the student repo.

### Description
The URL for the repository was not correctly changed in the Jenkins build plans. The replacement parameters for the old/new-url were passed into the replacement method the wrong way round.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise
- GitLab/Jenkins setup

1. Start a new participation in the exercise as a student.
2. Commit some code.
3. As instructor, go to the scores page for the exercise.
4. In the submission history, the result should be linked to the latest commit rather than the initial commit that was created when setting up the exercise.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

### CODE REVIEW

**Review by dfuchss — DISMISSED** [review]
Makes sense 😂 (Hopefully, I can test it soonish™️ )

**Review by dfuchss — APPROVED** [review]
Tested using the "Create Assignment Repository" operation as Instructor. It works :)

**Review by MichaelOwenDyer — APPROVED** [review]
Looks like this fixes the issue!

**Review by chrisknedl — APPROVED** [review]
Code looks good 👍

**Review by maximiliansoelch — APPROVED** [review]

**Review by Strohgelaender — APPROVED** [review]
code lgtm, thanks for the new test

**Pull request merged**
