### PR TITLE
`Integrated code lifecycle`: Trigger solution build before template build

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I adapted a test to cover the added functionality
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

A psuh to a test repository triggers the build of the respective solution and template repositories. If the template repository results come in first (which can easily happen if both builds are triggered at the same time) it will display faulty results as it still used the old testcases. Thus, the template repository should only be built after the solution build results are available.

### Description

When a push to a test or auxiliary repository is detected by local VC, it triggers only the solution build. Once the build result has been processed, LocalCI then triggers the template build.

### Steps for Testing

**Only test on TS3 or TS6**
Prerequisites:
- 1 Instructor
- 1 Programming Exercise

1. Edit the test repository and submit
2. The solution build should start right away
3. Once the solution build result is available, the template build is triggered

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [LocalCIResultProcessingService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6098/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.localci/LocalCIResultProcessingService.html) | 71% | ✅ |
| [LocalVCServletService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6098/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.localvc/LocalVCServletService.html) | 91% | ✅ |

## Summary by CodeRabbit

- **New Features**
	- Enhanced build triggering logic to improve the handling of solution and template repositories.
- **Refactor**
	- Refined method for determining if a build is for a solution of test or auxiliary push.
- **Tests**
	- Added integration tests to verify the correct order of build job completions.

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code lgtm.

This should fix #2285 (at least for LocaCI)

**Comment by laurenzfb** [comment]
@Strohgelaender Not sure how easy this is to fix for the other systems as I'm not very familiar with the code.

**Review by rstief — APPROVED** [review]
Code looks good 👍

**Review by Predixx — APPROVED** [review]
tested on ts2. Looks good to me

**Review by milljoniaer — APPROVED** [review]
Tested on ts6 works as expected

**Review by mateusmm01 — APPROVED** [review]
Tested on ts6. Works as expected!

**Pull request merged**
