### PR TITLE
`Discussion`: Add search and filtering to exercise and lecture discussion tabs

### PR DESCRIPTION
**Pull request by canberkanar**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

When users are using the discussion section of exercises or lectures, in particular, long lists of posts make it hard to reach information. Furthermore while creating a new Post in such a context, users have to scroll to the bottom of the long post list, since the "New Post" button is located at the very bottom of the list.

Solves #5050.

### Description

To let the users reach information in a more convenient way, we enable searching and filtering of posts while on the page of a specific exercise or lecture. Furthermore, a second "New Post" is added before the beginning of the list, if there are more than 2 Posts present.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 course with postings enabled

1. Log in to Artemis
2. Navigate to Course discussion page
3. Make sure that all functionality is still present as before. 
4. Go to the page of a specific exercise or lecture.
5. Make sure that searching and filtering work as expected.
6. Make sure that a single "Create Post" button is present if there are less than 3 posts.
7. Make sure that two "Create Post" buttons are present if there are more than 2 posts. 

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
course-discussion.component.ts  | 80.24% | 95.5% |
discussion-section.component.ts | 86% |  90.78% |
course-discussion.directive.ts | 91.66% | 100% |
metis.util.ts | 100% | 100% |
posting-thread.component.ts  | 100% | 100% |

### Screenshots

image
image
image

### CODE REVIEW

**Review by jschmautzer — APPROVED** [review]
tested on ts1, followed the descriped testing steps and everything worked as expected for me :)

**Review by babyygemperor — APPROVED** [review]
Tested on ts2, works as expected. Btw I think you mean "New Post" as opposed to "Create Post" in the last steps

**Review by TheTrueVester — APPROVED** [review]
Tested on ts1. Everything worked as described. 
The new post page (the page that opens when you click the "new post" button) randomly closes when still being edited. Within 6 posts, it occurred 2 times. I'm unsure of the exact causes and just felt that I should mention it.

**Comment by canberkanar** [comment]
> Tested on ts1. Everything worked as described. The new post page (the page that opens when you click the "new post" button) randomly closes when still being edited. Within 6 posts, it occurred 2 times. I'm unsure of the exact causes and just felt that I should mention it.

Nice catch! Thank you for pointing it out. I just committed a fix, can you check it out once again? 😊

**Review by nadinesamyy — APPROVED** [review]
tested on ts2, looks good

**Review by TheTrueVester — APPROVED** [review]
Retested on ts1. Everything worked as expected.

**Review by xlieA — APPROVED** [review]
I tested on ts1 and followed the testing steps. Everything looks good.

**Review by max-bergmann — APPROVED** [review]
tested on ts2. works as expected

**Review by babyygemperor — APPROVED** [review]
Retested on ts2, works as described.

**Review by akesfeden — APPROVED** [review]
Tested on TS1 during testing session. Number of "Create Post" buttons, filtering and search works as expected, looks nice.

**Review by minrows — APPROVED** [review]
Tested on TS1 during the test session. The functionality works as explained. 👍

**Review by pusll-genesis — APPROVED** [review]
Tested during the monday test session and all of the testing steps worked for me on Firefox.

**Review by 4ludwig4 — APPROVED** [review]
Tested all of the steps during the monday testing session with Firefox and everything seemed working.

**Review by jbllhff — APPROVED** [review]
Tested on ts2, works fine. Thanks!

**Pull request merged**
