### PR TITLE
`Quiz exercises`: Fix stuck loading cycle for competency selector in quiz exercise edit view

### PR DESCRIPTION
**Pull request by MaximilianAnzinger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course *WITHOUT* Competencies

1. Log in to Artemis
2. Navigate to Course Administration
For each Exercise type:
3. Create Exercise
4. Check if you see a loading animation for the competency selector. Either the selector disappears after a short time OR it disappeared so quickly you didn't have time to see it. Both cases are fine.
5. Continue with the next Exercise type (step 3.) until all are covered

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [competency-selection.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5747/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/competency-selection/competency-selection.component.ts.html) | 88.63% | ✅ |

### CODE REVIEW

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts2. Worked as expected

**Review by xHadie — APPROVED** [review]
_Manually tested on TS2_Legacy_
LGTM - Works as you described.

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts2. Seems to be working

**Comment by MaximilianJG** [comment]
Everything worked as expected. I cannot see the competency selector and also no competency selector loading animation when creating the different exercises

**Pull request merged**
