### PR TITLE
`Integrated code lifecycle`: Remove /git from local VC repository folder names

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x]  I tested all changes and their related features with all corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

In Local VC, getting the folder name for a repository URI would always include a "/git" at the start. This can cause unwanted issues with other features such as the plagiarism check where a preceding "/git" is not expected.

### Description

This PR removes the preceding "/git" from the repository folder name.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students

Instructor
1. As the instructor, create a programming exercise with online editor enabled.
2. Verify that template and solution build correctly
3. Verify that the repository download still works
4. Verify that you can access the repositories in the editor

Students (do this for both students)
1. Participate in the exercise
2. Open the code editor and verify you can see the files
3. Create a submission and verify the result

Instructor
5. Conduct a plagiarism check for the exercise
6. Verify that you do not receive an error

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved handling of repository paths containing `/git` to avoid issues with specific usernames.
- **Tests**
	- Added tests to ensure repository paths are correctly managed without including `/git`.

### CODE REVIEW

**Review by rstief — APPROVED** [review]
Code LGTM 🦖

**Review by reschandreas — APPROVED** [review]
tested locally, works as expected also code lgtm

**Review by milljoniaer — APPROVED** [review]
code lgtm, and tested on ts6 works as expected

**Review by mateusmm01 — APPROVED** [review]
Code lgtm

**Review by coolchock — APPROVED** [review]
code LGTM

**Pull request merged**
