### PR TITLE
`Exam mode`: Obliterate exam live statistics 💔

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

Exam live statistics were barely used and not implemented in the way that the maintainers actually wished for.

### Description

Obliterated everything related to exam live statistics. Drops the column in the database.

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

### CODE REVIEW

**Review by tobias-lippert — CHANGES_REQUESTED** [review]
The Feature toggle on both the client and the server side still contains the exam monitoring.

Affected files: feature-toggle-service.ts and the Feature enum

It's also listed in the feature-overview.component.ts

The live statistics feature should also be removed from the docs then. Seems all to be documented in live_statistics.rst but could be done in a followup IMO.

**Comment by maximiliansoelch** [comment]
> The Feature toggle on both the client and the server side still contains the exam monitoring.
> 
> Affected files: feature-toggle-service.ts and the Feature enum
> 
> It's also listed in the feature-overview.component.ts
> 
> The live statistics feature should also be removed from the docs then. Seems all to be documented in live_statistics.rst but could be done in a followup IMO.

Thanks for pointing that out! 
It's removed now 👍

**Review by tobias-lippert — APPROVED** [review]
Couldn't find any missed occurrences.

**Review by julian-christl — DISMISSED** [review]
Checked all occurrences of "live" and "monitor" in the system. It looks like you got everything.

**Review by tobias-lippert — APPROVED** [review]
Reapprove after test fix

**Review by Strohgelaender — APPROVED** [review]

**Review by JohannesStoehr — APPROVED** [review]
LGTM

**Review by tobias-lippert — APPROVED** [review]
Reapprove after removing missed related code.

**Review by MaximilianAnzinger — APPROVED** [review]
Couldn't find anything unused either. LGTM

**Pull request merged**
