### PR TITLE
[Bugfix] Fix "exercise-type-icon-tooptip-flickering" and several misalignments and style issue on lecture page

### PR DESCRIPTION
**Pull request by lschlesinger**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all newly inserted strings into English and German.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

I recognized that the discussion section on lecture pages was misaligned and rather below than next to the lecture description/units.
When trying to fix this issue I stumbled upon several other issues which I fixed alongside.

### Description

- Fix sizes and alignment of lecture units
- Fix placement of discussion section
- Fix tooltips, that were flickering due to to the placement="right" attribute on the html tag
- **Note**: this also solves the problem of flickering icon tooltips on every occurence of `course-exercise-row` as shown in the video:

https://user-images.githubusercontent.com/41366522/125634966-f3cf6e2a-2838-4fc0-8bc3-46471ab520db.mov

### Steps for Testing

1. Log in to Artemis
2. Navigate to a Lecture in the course overview -> chose (or create) a lecture that has all different types of lecture units
3. Collapse and uncollapse the lecture units
4. Change the screen size
5. Check the tooltips on the unit/exercise icon and "not released" badges.

### Screenshots

Before:
Bildschirmfoto 2021-07-14 um 14 43 45

After:
Bildschirmfoto 2021-07-14 um 14 44 48

### CODE REVIEW

**Review by katjanakosic — APPROVED** [review]
Works as described on TS1

**Review by NicolasUllmann — APPROVED** [review]
Tested on TS2. Everything worked for me.

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Works.

**Comment by krusche** [comment]
great 👍 thanks

**Pull request merged**
