### PR TITLE
reloading questions when switching the page by notifications

### PR DESCRIPTION
**Pull request by maximilianmeier**
### Description
added on change listener to update the question and answer section

### CODE REVIEW

**Comment by krusche** [comment]
would it not make more sense to properly ask the router to reload the component with the new url parameters instead of handling this case explicitly? other notifications would then need such handling as well. I think using proper routing is more generic for future notifications.

What do you think?

**Comment by maximilianmeier** [comment]
the routing actually works correctly. the main problem is, that the same view is used so no component gets re-rendered and no ngOnInit function is called. thats why i implemented it that way. regardless of the notifications, the StudentQuestionComponent should update the content if the input changes. this should not be depend on a route change. maybe it will be added dynamically as an overview for all exercises at some point just as an example. the reload should work there as well

**Comment by krusche** [comment]
> the routing actually works correctly. the main problem is, that the same view is used so no component gets re-rendered and no ngOnInit function is called. thats why i implemented it that way. regardless of the notifications, the StudentQuestionComponent should update the content if the input changes. this should not be depend on a route change. maybe it will be added dynamically as an overview for all exercises at some point just as an example. the reload should work there as well

I mean that you could ask the router to reload the component. We use this in other places (e.g. Assess next submission) and it works perfectly. Please give it a try. Here is the code:

`this.router.onSameUrlNavigation = 'reload';`
`this.router.navigate(...)`

**Comment by krusche** [comment]
Did you try out my approach?

**Comment by maximilianmeier** [comment]
not yet. i'm stuck on another topic right now. but i'll add it later today

**Pull request merged**
