### PR TITLE
`General`: Fix several small issues in different charts

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

This PR contains several small improvements:

- **Course detail charts**: We faced some overlapping on production for the doughnut charts on course detail page due to large numbers displayed within the doughnut. These are fixed now.
- **Average student score pie chart**: The denominator representing the maximum of reachable points in the course was not correct. This is fixed now.
- **Exercise assessment dashboard pie chart**: If a programming exercise is corrected automatically, the chart currently represents all submissions as unassessed. For this case, the chart is adapted
- **Chart coloring**: Along Artemis, we have several occurrences of the same color, especially in charts, where the color codes are dedicated. I started to centralize the color definition.

### Description

- **Course detail charts**: All charts are now 50px bigger
- **Average student score pie chart**: I removed a occurrence of `.collect(Collectors.toSet())` that filtered all duplicated max points of exercises and therefore returned the wrong reachable points for a course.
- **Exercise assessment dashboard pie chart**: The chart is now representing the ratio of open and resolved complaints in this case as this is the only measurement of interest then.
- **Chart coloring**: I replaced some dedicated color codes with the enum `GraphColors`.
### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with automatic assessment Complaints enabled

1. Log in to Artemis
2. Participate with the students on the Programming exercise
3. Assess the participation as instructor
4. Complain as one student
5. Navigate to the exercise assessment dashboard of the exercise and inspect the pie chart. It should only represent complaints.
6. Also check any other assessment dashboard and the course assessment dashboard. The legend entries should be as usual.
7. Check the course detail page and check the charts there. Make sure no overlapping occurs.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Screenshots

The mentioned overlapping:
Bildschirmfoto 2022-02-07 um 22 58 29

How the Pie charts look now:
image

The old denominator (that is incorrect):
image

The new Pie chart colors (these are open for discussion):
image

How the Pie chart looks in case of automatic assessment programming exercise with complaints enabled:
image

### CODE REVIEW

**Review by filip-gregurevic — APPROVED** [review]
Changes look good to me 👍🏼

**Review by canberkanar — APPROVED** [review]
Did manual testing on my local setup and verified new pie colors. Also couldn't notice any overlapping issue.

**Review by Strohgelaender — APPROVED** [review]
Tested on TS1, works as expected.

**Review by lBruchmann — APPROVED** [review]
Tested on ts1. Tested together with @Strohgelaender. Everything works as expected! Looks good to me.

**Pull request merged**
