### PR TITLE
`Documentation`: Add MySQL 8 root password hint to the setup documentation

### PR DESCRIPTION
**Pull request by TheZoker**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] I implemented the changes with a good performance and prevented too many database calls.
- [ ] I documented the Java code using JavaDoc style.
#### Client
- [ ] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

When I first tried to setup Artemis on my clean ubuntu laptop, I had issues to get the database connection working. 
After researching for quite some time I figured, that the root password for my newly installed MySQL 8 instance was not set, but also not empty. After trying a lot of different solutions on stackoverflow, I finally noticed, that the way to set an empty root password (or any password in general) changed between previous MySQL versions and MySQL 8. And since MySQL 8 is the required version for this project, I figured it would be helpful for future devs who setup this project for the first time, to have a quick solution within the setup docs. 

### Description

I added one small passage right after the MySQL instruction, which describes how to set the root password to an empty password. I also included a disclaimer, that this should only be done for dev setups and not for production setups (for security purpose). I hope the wording is alright, if not please let me know. I also verified this with a second PopOS instance. 

### Steps for Testing

Prerequisites:
- Clean linux installation

1. Follow the setup guide
2. Install MySQL and try to connect. 
3. Connection gets refused. 
4. Use added command to fix the root password
5. Now connections should work

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by Hialus — APPROVED** [review]
Documentation changes look good to me.
I looked at the changes from the documentation GitHub build and the text is properly formatted and in the correct place.
Well done 👍🏻

**Review by Strohgelaender — APPROVED** [review]
looks good, I had the same issues when setting up Artemis first, this should help new developers.

**Review by Santia-go — COMMENTED** [review]
This information is very useful. I had this problem the first time. May I suggest paraphrasing the two statements? 

Something like this: 

If you have problems connecting to the MySQL 8 database using an empty root password, you can try the following command to reset the root password to an empty password:


Note: this should only be used in a development environment. The root password for a production environment should never be empty.

**Comment by TheZoker** [comment]
Sounds good to me! Pushed an update

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
