### PR TITLE
`Plagiarism checks`: Add more plagiarism result stats

### LINKED ISSUE #6143: `Plagiarism checks`: The duration time is correct? make sense to have it?
### Is your feature request related to a problem?

When you run the plagiarism check in any exercise, at the end you can see that took 00:00:00.### that means milliseconds. 
But actually no, It takes several seconds even minutes (when we have a lot of submissions) to show the results. 
So, what exactly is this duration in milliseconds? 
Does it make sense to show this time? 

image

### Describe the solution you'd like

A solution would be to show the real time that takes to show the results of the plagiarism checks. Other wise remove this. 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server..
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Instructors cannot quickly check basic plagiarism checks statictics. They also don't know who (other instructor or cpc) triggered the job.

### Description
This PR introduces several new statistics to be displayed on the plagiarism results page. They are:
- number of detected submissions
- average similarty
- maximal similarity
- duration of the check (in a simplified form, will close #6143)
- start time
- start by (specific user or the cpc)

Because new DTO is created, this PR includes small refactor of moving other plagiarism related DTOs into a separate package.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exercise

1. Create an exercise.
2. Create two similar submissions for that exercise.
3. Go to the exercise as instructor and open _Check plagiarism_
4. Run the check
5. Verify that stats are correct

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| PlagiarismResultResponseBuilder | 86% | ✅                           |

### Screenshots
New statistics (wide screen):
image

New statistics (narrow screen):
image

### CODE REVIEW

**Review by LenaKahle — DISMISSED** [review]
Works as described. Tested on TS2 with students test user 1 and 2, instructor test user 11, exercise "future exercise" (text exercise).

**Review by JanaNF — DISMISSED** [review]
Manual tested on legacy ts2. Worked as expected.

**Review by vinceclifford — DISMISSED** [review]
Tested, works as expected

**Review by LenaKahle — DISMISSED** [review]
Reapprove.

**Review by lennart-keller — APPROVED** [review]
Demonstrated in testing session

**Review by florian-glombik — APPROVED** [review]
Tested during testing session, new statistics are displayed

**Review by JanaNF — DISMISSED** [review]
Reapprove

**Comment by krusche** [comment]
@jakubriegel some server tests are failing, please fix them before setting the PR to `ready to merge`

**Review by florian-glombik — APPROVED** [review]
Re-approve - since last change only non-production code was changed _(did not look into it why changing the paths was needed there)_

Server tests are not failing anymore

**Review by LenaKahle — APPROVED** [review]
Reapprove.

**Review by JanaNF — APPROVED** [review]
Reapprove

**Review by lennart-keller — APPROVED** [review]
Reapprove

**Comment by jakubriegel** [comment]
@krusche tests are fixed

**Pull request merged**
