### PR TITLE
`Assessment`: Increase the maximum configurable length for complaints and complaint responses

### PR DESCRIPTION
**Pull request by Shirkanesi**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I documented the Java code.

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

Closes: https://github.com/ls1intum/Artemis/issues/4664

### Motivation and Context

As discussed in https://github.com/ls1intum/Artemis/issues/4664 the maximum numbers of characters should be increased, as this is required for some instructors.

### Description

I've changed the column for complaints and complaints responses from `VARCHAR(5000)` to `TEXT` as this allows for up to 65535 characters per complaint. This is almost the amount excpected for a bachelors thesis, so this will very likely will be enough for every use-case.

I've also updated the contstants (introduced in https://github.com/ls1intum/Artemis/pull/4810) for the maximum value for those texts in Front- and Backend.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student

1) Log in to Artemis
2) Navigate to Course Administration
3) Increase or decrease complaint text and complaint response text limit (e.g. 10000 and 20000)
4) File a complaint as a student
5) Response to that complaint as a tutor
6) Verify that these new limits work as expected

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

Note: Actions fail due to lack of permissions; actual tests pass.

### CODE REVIEW

**Review by Dominik-Weinzierl — APPROVED** [review]
Code looks good to me :+1: the database change looks also good to me (should be unproblematic).

**Review by akesfeden — DISMISSED** [review]
Code changes look good to me, as @Dominik-Weinzierl mentioned migration shouldn't create incompatibilities since it is only relaxing a constraint.

**Review by dfuchss — DISMISSED** [review]
Code change sounds good. Thx a lot!

**Comment by dfuchss** [comment]
I've added it to the current mile stone since it already have a good amount of reviews

**Review by bassner — DISMISSED** [review]
Changes look good to me 👍

**Comment by dfuchss** [comment]
Marked as ready for merge, due to reviews :)

**Comment by Shirkanesi** [comment]
Nothing realy changed. Just fixed a merge conflict and renamed the liquibase-patch to keep the order somewhat chronological.

Would be nice if someone could test this in order to finally merge the PR :)

**Review by JohannesStoehr — APPROVED** [review]
Changes look good to me

**Review by Dominik-Weinzierl — APPROVED** [review]
re-approve :+1:

**Pull request merged**
