### PR TITLE
`Modeling exercises`: Fix missing references to the grading instructions from feedbacks when importing

### PR DESCRIPTION
**Pull request by akesfeden**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

When importing the modeling exercises, the example submissions are imported, but the feedback from the Grading Instruction (Structured Assessment Instruction) is missing for the assessments meaning that only the points are imported, but the feedback, which should be visible for the students, is not.

### Description

During the modeling exercise import, the new Feedback does not retain a reference to the new Grading Instruction unlike the original Feedback, this reference is established during the copy operation.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Modeling Exercise with Example Submission with Structured Assessment Instruction as Feeedback.

1. Log in to Artemis
2. Navigate to Course Administration
3. Import the prerequisite Modeling Exercise.
4. Ensure the imported exercise displays the feedback message from Structured Assessment Instruction in the assessment view.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| ExampleSubmissionService.java | 75% | 92% |
| ModelingExerciseImportService.java | 66% | 92% |
| ExerciseImportService.java | 91% | 97% |
| Exercise.java | 80% | 93% |

### Screenshots

Original Exercise Before the Fix:
image

Imported Exercise Before the Fix:
image

Feedback of the imported exercise should look the same as the original screenshot above.

### CODE REVIEW

**Review by yuling-sun — APPROVED** [review]
Tested on TS1. The imported example submission had the structured assessment feedback just as described.

**Comment by babyygemperor** [comment]
Tested on TS3. The imports and feedbacks works as described

**Review by rhubinger — APPROVED** [review]
Tested on TS2, imported exercise displayed feedback correctly. LGTM

**Review by bassner — APPROVED** [review]
Tested on TS5. Works as expected.
Code looks good to me, good job 👍

**Pull request merged**
