### PR TITLE
[Enhancement] Programming Assessment refactoring routes to use submissionId

### PR DESCRIPTION
**Pull request by fde312**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I extended and adapted multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I adapted multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

All exercises types except of programming exercises use the submissionId for routing and fetching data. Programming exercises use the participationId as in the past a submission could not have multiple results. This change makes it possible to switch now from the participationId to use the submissionId like for the other exercise types.

### Description

- Change participationId to submissionId in routes and some endpoints
- Refactor CodeEditorTutorContainer
- Remove not needed endpoints and resolvers

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create several programming exercises with manual feedback (exam, team, normal) and also with and without SCA and SGI. Please try different combinations.
4. Participate in the exercise and assess it afterwards, everything should work as always.
4.1 Access the assessment from assessment dashboard, exercise scores and exercise submission view
5. Check that the routes now use submissionId instead of participationId.
6. Check that from the students perspective everything works fine.
7. Complaint as student and evaluate the complaint, everything should work as always

### Test Coverage

Nothing changed

### Screenshots

New URL:
image

After reentering the assessment all feedbacks are correctly loaded:
image

Student View:
image

### CODE REVIEW

**Review by stefanwaldhauser — APPROVED** [review]
Wrong Review See Below :( Found an error after this review

**Review by stefanwaldhauser — CHANGES_REQUESTED** [review]
Everything seems to work but I am unable to accept a complaint: 
https://artemistest.ase.in.tum.de/course-management/456/programming-exercises/6931/submissions/435933/assessment?correction-round=0
image

**Comment by fde312** [comment]
@stefanwaldhauser Thank you for testing. I have solved the issue with the complaint and this should work after PR #3215 is merged :)

**Review by maximilianbergmann — APPROVED** [review]
Tested generating and participating in programming exercices. Seems to work normal. Students perspective is fine.

**Review by katjanakosic — APPROVED** [review]
Tested on TS1 with @airelawaleria. Worked fine :)

**Review by airelawaleria — APPROVED** [review]

**Review by ArtemTsurikov — APPROVED** [review]
Tested on TS1, looks good.

**Review by NicolasUllmann — COMMENTED** [review]
Tested on server 1. Everything worked as expected.

**Review by joschahenningsen — APPROVED** [review]
Could not find any issues.

**Review by willergeorg — COMMENTED** [review]
Tested on TS2. Worked for me without a problem.

**Review by cremertim — DISMISSED** [review]
Everything worked out properly for me

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS1 & TS2 and it works now

**Review by coolchock — APPROVED** [review]
tested on both ts1 and ts2. worked as expected

**Pull request merged**
