### PR TITLE
`Programming exercises`: Improve information for changing auxiliary repositories

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

#5551 mentioned a potential bug that is currently the intended feature. But the warning on Artemis did not 100% reflect the behavior.
The intended behavior is that all changes afterwards need to be carried out manually in the VCS and CIS.

### Description

This PR enhances the information about changing auxiliary repositories after the creation of a programming exercise.
Additionally a warning is now shown after editing a programming exercise if the auxiliary repositories were edited.

### Steps for Testing

Prerequisites:

1. Check the translation keys
2. Create an exercise with an auxiliary repository (no warning should be shown when saving)
3. Edit that exercise and change (add, remove, edit) an auxiliary repository and check that a warning pops up on the top right when saving

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Comment by julian-christl** [comment]
- Tested on TS1
  - Made sure the notification gets displayed when and only when the aux repos get modified & not on creation
  - Made sure the banner was adapted
- Code looks good

**Review by julian-christl — APPROVED** [review]
Tested on TS1
Made sure the notification gets displayed when and only when the aux repos get modified & not on creation
Made sure the banner was adapted
Code looks good

**Review by SimonPaul02 — APPROVED** [review]
Tested on TS1, works as expected

**Review by yuling-sun — APPROVED** [review]
Tested on TS1. Works as described.

**Review by alaraozdenler — APPROVED** [review]
Tested on ts2, works as described

**Review by jschmautzer — APPROVED** [review]
tested on ts2, worked as described

**Pull request merged**
