### PR TITLE
`General`: Improve small screen behavior of exercise action bar

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The UI on small screens looked weired on small screens with only one centered column.

### Description

The exercise actions now always stick to the left of the screen and the result and instructor actions always to the right. Additionally this row tries to stay in one line, but in case there is an overflow, the content wraps around.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- All exercises

1. Log in to Artemis
2. Navigate to each exercise
3. Look at the UI of the action bar with different screen widths
4. Try to clone the repository and start the practice mode using a small screen

#### Exam Mode Testing

Only affects course components.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

https://user-images.githubusercontent.com/38322605/203957593-cef796a2-ad04-4144-afab-574fd06edeb5.mp4

Clone repo button:
Bildschirm­foto 2022-11-26 um 11 50 04

### CODE REVIEW

**Comment by frederik-kt** [comment]
Programming Exercise for instructor: Practice button has no padding to the left.

Screenshot (64)

**Review by akesfeden — COMMENTED** [review]
For screen widths between approximately 769px and 800px there are two rows until the `View submission` button is minimized. Is it possible (or feasible without redundant effort) to have a single row view covering this width range as well?

image

**Comment by evgeny1984** [comment]
I would prefer vertical centering for buttons on the smaller screens. Currently it ist not centered in the left and right columns:
image
It affect all types of exercises.

**Review by kekskatze — APPROVED** [review]
Tested on ts2. No issues found

**Review by MarkusPaulsen — APPROVED** [review]

**Review by danielbode — APPROVED** [review]
Looks good. Nice improvement!

**Review by evgeny1984 — DISMISSED** [review]
Looks good, tested on ts2. 1 small remark regarding the vertical alignment.

**Comment by JohannesStoehr** [comment]
> For screen widths between approximately 769px and 800px there are two rows until the `View submission` button is minimized. Is it possible (or feasible without redundant effort) to have a single row view covering this width range as well?

This really depends on too many cases. There can be a different amount of buttons on the left and right, so if I fix this for one case, another case will suffer something similar

**Comment by JohannesStoehr** [comment]
> I would prefer vertical centering for buttons on the smaller screens. Currently it ist not centered in the left and right columns:
> image
> It affects all types of exercises.

This would lead to more vertical screen space which we specifically want to avoid. Or do you have a suggestion that would not lead to this?

**Review by rriyaldhi — APPROVED** [review]
Looks good! Tested on TS2.

**Comment by evgeny1984** [comment]
> > I would prefer vertical centering for buttons on the smaller screens. Currently it ist not centered in the left and right columns:
> > image
> > It affects all types of exercises.
> 
> This would lead to more vertical screen space which we specifically want to avoid. Or do you have a suggestion that would not lead to this?

I think if you look at the image, you have the disbalance by the button positions, as they are placed differently. But it's only my personal view.

**Review by rriyaldhi — APPROVED** [review]
Reapprove

**Review by tobias-lippert — APPROVED** [review]
Tested on ts1. UI looks good on small screen.

**Review by evgeny1984 — APPROVED** [review]
Tested on ts2. UI changes look good on the different small screens.

**Review by timo07k — CHANGES_REQUESTED** [review]
If I click on "Clone Repository" and then halve my screen, the "Repository window" is cut as you can see in the screenshot:

image

**Review by timo07k — APPROVED** [review]
Everything works as expected. Tested on TS1.

**Review by danielbode — APPROVED** [review]

**Pull request merged**
