### PR TITLE
`Development`: Reduce `for-dashboard` payload significantly when participation results exist

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context
For each participation result, the `for-dashboard` REST call includes the whole data again, because of the chain "result -> participation -> exercise -> course -> exercises -> studentParticipations -> submissions -> results". In the worst case, this could result in a 80x larger payload in case a student participated in 80 course exercises. 

### Description
I created a new DTO because basically just 3 values are needed in the client: score, rated, participationId

### Steps for Testing

1. Open Artemis and navigate into the course statistics
2. Double check there are not Typescript errors in the console related to the changes in this PR
3. Make sure the statistics are still the same as before (when e.g. deploying `develop`) 

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by jakubriegel — APPROVED** [review]
Code LGTM 👍🏻 

Locally it works: no console errors, stats same as on develop

**Review by Strohgelaender — APPROVED** [review]
Payload on TS1 is much smaller now:
grafik

 
grafik

**Review by terlan98 — APPROVED** [review]
Tested on TS5. The course statistics page works as before 👍. There are no Typescript errors related to this PR.

Code also LGTM.

**Review by JohannesStoehr — APPROVED** [review]
Aprove code

**Review by TimOrtel — APPROVED** [review]
Code looks good to me. This will most likely also require changes within our native clients.

**Review by tobias-lippert — APPROVED** [review]
Tested on ts5.
No typescript errors are shown in the console and statistics are correct.

**Comment by maximiliansoelch** [comment]
> Code looks good to me. This will most likely also require changes within our native clients.

@terlan98 Do we need changes directly in Themis or only in the artemis-ios-core-modules?

**Comment by terlan98** [comment]
> > Code looks good to me. This will most likely also require changes within our native clients.
> 
> @terlan98 Do we need changes directly in Themis or only in the artemis-ios-core-modules?

Themis is not affected by the changes on this PR. I'll just apply this change on ArtemisCore.

**Pull request merged**
