### PR TITLE
`Development`: Add e2e tests for student exams page

### PR DESCRIPTION
**Pull request by muradium**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context
Student exams page needs e2e tests.

### Description
Added tests for opening student exams page and checking fields for correctness.
Added tests for searching student exams by student name or username.

### Steps for Testing
Run e2e test **TestExamStudentExams** on cypress and check if it passes.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### CODE REVIEW

**Review by vinceclifford — APPROVED** [review]
Works as expected, demonstrated during testing session

**Review by laurenzfb — APPROVED** [review]
Demonstrated in testing session. LGTM!

**Review by sarpsahinalp — APPROVED** [review]
Works as expected, demonstrated during testing session

**Review by mateusmm01 — APPROVED** [review]
Demonstrated during testing. Looks good!

**Review by florian-glombik — APPROVED** [review]
Testing steps seem reasonable and were demonstrated successfully

**Review by Ceiridge — APPROVED** [review]
The code looks clean and the tests are extensive.

**Pull request merged**
