### PR TITLE
`Communication`: Add loading indicator when adding users to channel

### PR DESCRIPTION
**Pull request by PaRangger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Currently, when adding a lot of users to a channel it may load for a while. The button does not show a loading indicator, leading to users clicking it repeatedly, sending various heavy requests to the server.

### Description

I added a loading indicator when adding users to a channel and disabled the button while loading.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to course
3. Navigate to the communication tab
4. Create a channel (group channel or public channel)
5. On the top right of the channel, click the "Add users" button
6. Go to "Add whole groups" and add all students/tutors/instructors (This should take a while on the testservers)
7. Click "Add Users" and check if a loading indicator is displayed and if the button is disabled

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| conversation-add-users-form.component.ts | 90.9% | ✅ |
| conversation-add-users-dialog.component.ts | 93.47% | ✅ |

### Screenshots

Bildschirmfoto 2024-12-16 um 19 37 01

## Summary by CodeRabbit

- **New Features**
	- Added a loading spinner to the submit button in the user addition form, providing visual feedback during submission.
	- Introduced a loading state management mechanism in the user addition dialog component.

- **Bug Fixes**
	- Ensured form submission is only possible when not in a loading state.

- **Tests**
	- Updated test components to include the new loading state property.

### CODE REVIEW

**Review by HawKhiem — COMMENTED** [review]
Tested on TS2. Upon adding users, the loading indicator is displayed and the "Add users" button is disabled. However other buttons are not disabled. Should they also be disabled to avoid overhead?


https://github.com/user-attachments/assets/bf5c01d9-55a7-4fbb-b08d-b0c1d47704fc

**Review by sachmii — APPROVED** [review]
Tested on TS1, works fine.

image

**Comment by ahbitaqu** [comment]
[Tested on TS2]
Works fine for channels. This loading indicator should also appear when creating group chats to stay consistent, imo

**Review by JerroyTan — APPROVED** [review]
[Tested on TS5]
Functionality works as described. Thought I have some concerns:
1. While users are still being added, the add more users button loads, but user can still exit and go to add users again. I fear that this could in extreme cases lead to synchronize issues.
image

2. In similar fashion, when deleting a course, the user can also exit the loading dialogue while it is still loading. When I tried this and tried to add another channel it did not work. Maybe this would belong to another issue to be opened since it does not only affect user adding functionality.

**Comment by PaRangger** [comment]
> Tested on TS2. Upon adding users, the loading indicator is displayed and the "Add users" button is disabled. However other buttons are not disabled. Should they also be disabled to avoid overhead?
> 
>  test.mp4

Hi! This PR serves as a quick fix to prevent users from spamming the button. So this functionality, while not ideal, is still kind of intended to be there. It only affects the client and does not do any uneccesary calls to the server 😄

**Review by sawys777 — APPROVED** [review]
Tested on TS1, everything works as described

**Pull request merged**
