### PR TITLE
`Plagiarism checks`: Clean up results and cases in case of errors

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
The cpc leaves phantom plagiarism cases when any of its subsequent runs results in an error. Such phantom cases can lead to false positive plagiarism case notification or not removing plagiarism case after cpc detected no plagiarism. An example scenario is when there suddenly is no submissions matching the plagiarism check configuration.

### Description
Now in case an exception Is thrown the cpc will remove all phantom plagiarism comparisons and cases, leaving the system in a correct state.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 2 Students
- 1 Text Exercise
- ⚠️ deployed brand which triggers cpc every 1 minute: `plagiarism-detection-fix-cpc-when-new-short-submission-1min` ⚠️ 

1. Create an exercise (text, modeling or programming) with cpc enabled
    - set a future due date for the exercise
    - check the _Enable Continuos plagiarism control_ checkbox
3. Submit two identical submissions from two students. Each submission needs to be at least 200 words long.
4. Wait 1min until the plagiarism case is created.
5. Verify that plagiarism cases was created for both students.
6. Change one of submissions to a 2-3 words long text.
4. Wait 1min.
5. Verify that both plagiarism case are removed.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| ContinuousPlagiarismControlService | 96% | ✅                           |

### CODE REVIEW

**Review by MarkusPaulsen — COMMENTED** [review]
Code looks good, waiting for testing session.

**Review by vinceclifford — APPROVED** [review]
Tested on ts1

**Review by aplr — APPROVED** [review]
Tested in testing session, LGMT

**Review by lennart-keller — APPROVED** [review]
Demonstrated in testing session.

**Review by florian-glombik — APPROVED** [review]
Worked fine, the plagiarism message was not displayed anymore after submitting something different

**Pull request merged**
