### PR TITLE
`Development`: Remove unnecessary server call to get notification settings

### PR DESCRIPTION
**Pull request by Malyuk-A**
#### General
- [x] This is a small issue that I tested on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- not changed
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

The notification sidebar loads the notification setting at start up to be able to handle group notifications (due to multicast groups, i.e. filters do not work on the server side here). If you open the notification settings one aditional server call is performed to fetch the notification setting. @krusche told me to change this so the notification settings page reuses the already available settings from the sidebar.

### Description
To avoid the direct coupling between components I added a variable to the notification setting service which holds the newest/latest version of the settings with getter and setter methods. I.e. when the sidebar loads the settings its sets them in the service and when the settings page is opened it checks if there are settings in the service. If not it loads them from the server as before. This usecase is still needed in the rare case when someone reloads the settings page itself.

### Steps for Testing
Log into Artemis and open your browser developer debugger tool and select the network panel.
Open the settings and check if they are visible without any loading-lag (instantly).
Check in the network console that no redundant notification-settings are fetched when switching from the homepage to the notification settings page. 

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
The biggest change beside a getter and setter was added to the notification-settings.component -> I added a new test case -> coverage > 85%

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Code changes lgtm. Tested on TS2. Settings are not fetched redundantly.

**Review by cremertim — COMMENTED** [review]
tested on ts2, works as expected. 👍 great work

**Review by cremertim — APPROVED** [review]

**Review by Hialus — APPROVED** [review]
Tested on TS3. 
Works as expected and code also looks good 👍🏻

**Review by ole-ve — APPROVED** [review]
Code changes look reasonable to me 👍

**Review by filip-gregurevic — APPROVED** [review]
Changes look good to me. Nice work 👍🏼

**Pull request merged**
