### PR TITLE
`General`: Fix resizing of markdown editors if multiple are rendered at the same time

### LINKED ISSUE #5397: Problem Statement Cut Off in Exercise Editor (File Upload Exercises, Text Exercises, Quiz Exercises)
### Describe the bug

When editing the problem statement of an exercise, the text editor can be expanded by dragging the handle at the bottom. Normally, this would expand the area that can be used to edit text and leave more space for editing the problem statement.

However, for certain text editors (problem statement in file upload and text exercises, as well as quiz exercises) expanding the size of the editor doesn't actually increase the amount of text visible; instead the extra space just becomes white.

**Note:** while writing this issue, I noticed that this is "fixed" every time it happens by resizing the window.

See screenshots below.

### To Reproduce

Open a file upload/text exercise, paste in a text with more than 15 lines (see below). Then, drag the handle under the editor, and see than no additional text becomes visible.

<details>
<summary>some long text</summary>
<pre>
line 1
line 2
line 3
line 4
line 5
line 6
line 7
line 8
line 9
line 10
line 11
line 12
line 13
line 14
line 15
line 16
line 17
line 18
line 19
line 20
line 21
line 22
line 23
line 24
line 25
line 26
line 27
line 28
line 29
line 30
line 31
line 32
line 33
line 34
line 35
line 36
line 37
line 38
line 39
line 40
line 41
line 42
line 43
line 44
line 45
line 46
line 47
line 48
line 49
line 50
</pre>
</details>

### Expected behavior

More text becomes visible, as still works e.g. when editing the sample solution.

### Screenshots

image
*this text has 50 lines, everything after line 14 was cut off*

---
image
*expected behaviour*

---

### What browsers are you seeing the problem on?

Chrome

### Additional context

Chrome, Firefox. Both on Linux (Mint).

### Relevant log output

```shell
n/a
```

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Markdown editors do currently have an issue where the inner content isn't resized with their container.

Closes #5397. See the issue for an example of the problem.

### Description

After a long debugging process I found that this happens if you have multiple editors rendered at the same time. The InteractJS configuration selects the editor by class name. However, all editors on the page have the same class name, and thus, the wrong one is selected for all InteractJS configurations besides the last one on the page.

To solve this, I've added a UUID as ID to each markdown editor so InteractJS can select the correct one for each editor.
Additionally, I call ``resize`` on the underlying ace editor on each height update as that looks better (otherwise you don't see text appearing while dragging the resize bar) and does not have notable performance impacts.

### Steps for Testing

Prerequisites:
- 1 Instructor

The issue appears on the edit page of an exam or on the edit page of a text exercise, for example, but generally every time multiple markdown editors are used. You can test any of them.

1. Log in to Artemis
2. Navigate to Course Administration
3. Open an exam edit view
4. Add long texts to the different markdown inputs (like exam end text etc)
5. Resize the editors and make sure the inner content is resized appropriately.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

ezgif-3-3bb1011d4f

### CODE REVIEW

**Review by Hialus — APPROVED** [review]
Code changes look good and reasonable.
Well done 👍🏻

**Review by ge65cer — APPROVED** [review]
LGTM

**Review by mallgaier — APPROVED** [review]
Awesome feature 👍

**Review by TheZoker — APPROVED** [review]
LGTM 👍

**Pull request merged**
