### PR TITLE
`Development`: Update client and server dependencies

### PR DESCRIPTION
**Pull request by krusche**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
Update client and server dependencies. There are no major updates for production dependencies, so there should be no breaking changes. However, a couple of third party vulnerabilities were fixed.

### Steps for Testing
Simply browse around some important screens and double check they still work correctly

#### Code Review
- [ ] Code Review
#### Manual Tests
- [ ] Test
#### Exam Mode Test
- [ ] Test

### CODE REVIEW

**Review by julian-christl — DISMISSED** [review]
Code looks good, and I tested some screens on TS3. All looks fine.

**Review by Hialus — CHANGES_REQUESTED** [review]
Tested on TS6 (and also checked it on TS1 to be safe).
I encountered some visual bugs and changes from develop:
In the course management exercises list the tables have different coloring and formatting now:
grafik
Whereas it is like this on TS5 and develop:
grafik
It happens in both dark and light mode and seems to also affect other tables

Also there is an issue with tooltips:
grafik
vs.
grafik
This only happens in dark mode

~The server administration drop down is sometimes scrollable now:
grafik
vs.
grafik
This isn't consistent behavior, but happens sometimes. It seems to happen consistently when you e.g. navigate to the view to create a new exercise hint for a programming exercise.~
EDIT: This also happens on develop interestingly 🤔 

Some text in the notification view is slightly birghter:
grafik
vs. 
grafik

I'll stop testing now, since its pretty clear that there is some underlying issue here. Maybe this is related to the update of Bootstrap?

**Comment by julian-christl** [comment]
@Hialus 

Regarding the tables: The formatting is only because you had presentations enabled for one and not for the other. Therefore the row is missing in one of the tables. True about the colours, though. Completely missed that.

**Comment by Hialus** [comment]
> Regarding the tables: The formatting is only because you had presentations enabled for one and not for the other. Therefore the row is missing in one of the tables.

Whops. Guess I got a bit distracted by the coloring 😅 
Though making this more consistent in the future would still be nice, but no idea if something this minor would be worth the hassle.

**Comment by julian-christl** [comment]
> > Regarding the tables: The formatting is only because you had presentations enabled for one and not for the other. Therefore the row is missing in one of the tables.
> 
> Whops. Guess I got a bit distracted by the coloring 😅 Though making this more consistent in the future would still be nice, but something this minor would probably not be worth the hassle.

Not sure about that. It makes sense not to show the presentation row if presentations are deactivated for the course. Otherwise, it's just wasted space.

**Comment by Hialus** [comment]
> Not sure about that. It makes sense not to show the presentation row if presentations are deactivated for the course. Otherwise, it's just wasted space.

I actually meant how the table headers are inconsistent when the presentation column is shown (1 or 2 lines, sometimes the indicator is on its own line, sometimes not.

**Comment by julian-christl** [comment]
> > Not sure about that. It makes sense not to show the presentation row if presentations are deactivated for the course. Otherwise, it's just wasted space.
> 
> I actually meant how the table headers are inconsistent when the presentation column is shown (1 or 2 lines, sometimes the indicator is on its own line, sometimes not.

I see, but honestly, I did not have this issue on TS3. Maybe a caching issue on your side?

**Comment by pal03377** [comment]
The text color of some tooltips changed.

TS5 with this PR:
screenshot-2023-06-13_001438

TS2 on develop:
screenshot-2023-06-13_001439

**Review by pal03377 — CHANGES_REQUESTED** [review]
Code changes and update changelogs of the updated packages look good to me. I just stumbled over the above error while looking through the Bootstrap changes.

**Review by dakennguyen — DISMISSED** [review]
tested on ts1. I try to play around with course management page and everything work fine

**Comment by bassner** [comment]
The [latest Bootstrap update added a bunch of changes to the underlying color system](https://getbootstrap.com/docs/5.3/migration/#v530), that's why we see some bugs in changed colors.

Fixed the following issues:
- Card backgrounds
- Table backgrounds
- Tooltip text colors
- `text-muted` occurrences have been replaced with `text-body-secondary` (fixes issue reported by @Hialus in the notifications)

Testers should watch out for more weirdly changed colors.

**Review by pal03377 — DISMISSED** [review]
My previous issue is resolved by @bassner's changes (well done! 🎉). When clicking around on TS5, I could not find other issues.

In the linked changelog, I saw the `navbar-dark` is deprecated. We still use that in one place: https://github.com/ls1intum/Artemis/blob/91fdb733a83f64db3ff0addbc8b4a906ebf68d45/src/main/webapp/app/shared/layouts/navbar/navbar.component.html#L74 
Do we want to change this right now?

**Review by terlan98 — DISMISSED** [review]
Tested exam mode on TS4 with an exam containing a programming exercise. Everything looks good from both instructor's and student's perspective.

**Review by tobias-lippert — COMMENTED** [review]
Tested on ts4. Created modeling and text exercise and participated in both. All worked, only encountered one small color issue in light mode.
On develop the text is white
image

**Review by MaximilianAnzinger — COMMENTED** [review]
Tested on TS4. The color of UMLs in the problem statement of programming exercises has changed compared to develop.

This PR:
chrome_ev3dQRcO23

On develop:
chrome_w45o2XJhGJ

**Comment by krusche** [comment]
> Tested on TS4. The color of UMLs in the problem statement of programming exercises has changed compared to develop.
> 
> This PR: chrome_ev3dQRcO23
> 
> On develop: chrome_w45o2XJhGJ

Are you sure you actually compared the same versions? It the exercise is not yet started or there was no submission yet, elements are shown in grey. If you have submitted something and tests fail, those elements are shown in red.

**Comment by bassner** [comment]
@tobias-lippert Please re-check the issue you mentioned

@pal03377 Removed `navbar-dark`. Please test the navbar. It seems to work correctly to me but you never know

**Review by tobias-lippert — APPROVED** [review]
Tested on ts1. Couldn't find any new issues and the issue found yesterday is fixed.

**Pull request merged**
