### PR TITLE
`Communication`: Display hint if no conversation settings are available

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

With the introduction of course-wide channels in #7021, there are channels that do not provide any settings for students (because they cannot be left). Therefore, the settings menu was empty, which looked unintended.

### Description

If the settings menu is empty, i.e. there are no buttons shown, a short hint is displayed, indicating that no settings are possible (see screenshots).

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Course with course-wide channels (if none available, just create a new lecture and use the lecture channel)

1. Login as the student
2. Navigate to the messages tab
3. Click on the settings for the course-wide channel
4. Confirm that a message indicating that no settings are possible is displayed
5. Click on the settings of any other conversation that is not course-wide
6. Confirm that no hint is visible if there are buttons available

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Screenshots

before:
before

after:
after

### CODE REVIEW

**Review by RY997 — APPROVED** [review]
Tested on ts4, checked course-wide and non-course-wide channel, worked as expected

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM 👍

**Review by pal03377 — APPROVED** [review]
Code looks good! Thanks for this follow-up improvement.

**Review by nityanandaz — APPROVED** [review]
Manual test on TS2

Settings are not available as a student

**Review by basak-akan — APPROVED** [review]
Manually tested on TS2, worked as described

**Review by Kroko-fant — APPROVED** [review]
Tested on ts2 workes as expected

**Pull request merged**
