### PR TITLE
`Assessment`: Improve the color of assessment status in tutor training

### PR DESCRIPTION
**Pull request by Olimbia23**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] *This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] *Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [ ] *I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [ ] *I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] *I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] *I implemented the changes with a good performance and prevented too many database calls.
- [ ] *I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [ ] *I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] *I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] *I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

[ ] * - not needed

### Motivation and Context

This PR solved the problem of the wrong color that correction status has in tutor training for text exercises.
As seen in Before screenshots, the color is dependent on what score the tutor gave to the feedback. We want however, the color to always be red if the correction status is indicating a wrong assessment or green if the correction status shows a right assessment.

### Description

In order to achieve that we use `text-success` and `text-danger` css classes. As well as `text-dark` for coloring the exclamation mark.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Tutor

1. Log in to Artemis as Instructor
2. Navigate to Course Administration
3. Navigate to an existing or new Text exercise.
4. Create an example submissions and example assessment and check Used for Tutorial.
-----------------------------------------------------------------------------------------

1. Log in to Artemis as Tutor
2. Navigate to Course Administration
3. Navigate to the exercise dashboard of the exercise created as instructor and assess the example submission.
4. During the tutor training, observe the color that correction status takes. See after screenshots.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Before
Screenshot 2021-11-22 at 12 41 52 AM

#### After
Screen Shot 2021-11-22 at 00 28 58
Screen Shot 2021-11-22 at 00 29 07
Screen Shot 2021-11-22 at 00 29 18

### CODE REVIEW

**Review by lschlesinger — APPROVED** [review]
Tested it on TS1 with different combinations, the coloring is intuitive and makes sense, good changed 👍

**Comment by dveljacic** [comment]
Tested on TS1. Looks good. 👍 ✅

**Review by dveljacic — APPROVED** [review]

**Review by MerlinMehmed — APPROVED** [review]
Tested on TS3, worked as expected. Code changes look good to me as well.

**Review by filip-gregurevic — APPROVED** [review]
Looks good to me 👍🏼

**Review by mallgaier — APPROVED** [review]
PullRequest tested. The colors are displayed according to the correctness of the assessment and no longer depending on the score.

**Review by VinnavanSembian — APPROVED** [review]
Tested in testing session. Colors change according to the correctness of the assessment. Works as it should.

**Review by lBruchmann — APPROVED** [review]
Tested during testing session. Tested on ts3. I followed the testing steps. Everything works as expected. Colors change as expected and intended.

**Pull request merged**
