### PR TITLE
`Bugfix`: Sensitize readers to user roles on plagiarism case posts

### PR DESCRIPTION
**Pull request by canberkanar**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.

### Motivation and Context
Fixes a bug while displaying plagiarism case posts. [Communication: Show author's role as icon in course on post title #5473](https://github.com/ls1intum/Artemis/pull/5473)

### Description
When plagiarism posts are fetched from the database, they do not contain any data about the course they belong to. For sensitizing the author's role, we need the course information to identify the role of the author in that specific course. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Text exercise

1. Log in to Artemis
2. As both students, participate in the same text exercise and trigger a plagiarism case by submitting the same input.
3. As instructor notify the students.
4. Make sure the notification post is created and displayed correctly.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
Not changed

### CODE REVIEW

**Review by ge65cer — COMMENTED** [review]
Good job, this fixed the bug regarding the plagiarism notification posts.
We seem to miss a server test for this endpoint/error, could you maybe add one?

**Comment by canberkanar** [comment]
> Good job, this fixed the bug regarding the plagiarism notification posts. We seem to miss a server test for this endpoint/error, could you maybe add one?

I have covered the edge case in the plagiarism post tests.

**Review by manuelmanso — APPROVED** [review]
LGTM

**Review by ge65cer — APPROVED** [review]

**Review by stefanwaldhauser — APPROVED** [review]

**Review by akesfeden — APPROVED** [review]
Tested on TS1 during testing session, user roles are visible in plagiarism view.

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
