### PR TITLE
`Development`: Update sentry config

### PR DESCRIPTION
**Pull request by magkue**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
As we had a lot of problems fixing the old sentry instances we redeployed it completely. Now we need to set a new Sentry DSN to enable Artemis to send logs to sentry (DSNs are safe to keep public, according to [Sentry Docs](https://docs.sentry.io/concepts/key-terms/dsn-explainer/))

### Description
I updated all occurrences of the old dsn value with the new one.

### Steps for Testing

On Artemis:
1. Log in to Artemis
2. Disable all content filter and ad blocker
3. Open the developer tools of your browser
4. Open the network tap & Reload the site once
5. Search for sentry, check if all request to sentry are successful (status code 200)

On Sentry:
1. Go to https://sentry.ase.in.tum.de/
2. Login with TUM Credentials
3. Check the _artemis_ project

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **Chores**
	- Updated Sentry DSN values in the ProfileService test file for consistency.

### CODE REVIEW

**Comment by magkue** [comment]
@HawKhiem Thanks for already having a look. I also noticed that, I am not sure where the old token is coming from. It is not in the code anymore. But I am on it.

**Review by Mtze — APPROVED** [review]

**Review by iyannsch — APPROVED** [review]

**Review by BBesrour — CHANGES_REQUESTED** [review]
Tested on TS3, not sure if this is related to your PR but I still get these issues in the console
image
image

**Review by HawKhiem — COMMENTED** [review]
Tested on TS3. Had the following

image

**Comment by magkue** [comment]
@HawKhiem Your screenshot looks fine to me, all request are successful. Do I miss something?

**Review by BBesrour — APPROVED** [review]
re-approve code

**Review by HawKhiem — APPROVED** [review]
Tested on TS5. Reapprove

**Review by krusche — APPROVED** [review]

**Pull request merged**
