### PR TITLE
`Exam mode`: Show exercise group title in breadcrumbs

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

### Motivation and Context
For the exam mode we only want to show the exercise group title to students, not the exercise title. However in some cases the exercise title was still shown in the breadcrums.

### Description
I fixed places where the wrong title got saved in the title service by introducing a short method.

### Steps for Testing
Open pages for exam exercises where the title is shown in the breadcrumbs, e.g. the repository view for programming exercises. Verify that the exercise group title is visible here, not the exercise title.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
old:
grafik

new:
grafik

## Summary by CodeRabbit

- **New Features**
	- Introduced a new method for setting exercise titles, enhancing clarity and relevance in the user interface.

- **Improvements**
	- Streamlined the handling of exercise titles across various services, improving code readability and maintainability.
	- Simplified logic for determining exercise titles based on user roles, reducing complexity.
	- Enhanced test coverage for exercise title handling based on user roles and exercise configurations.

### CODE REVIEW

**Review by JohannesStoehr — DISMISSED** [review]
Code

**Review by coolchock — APPROVED** [review]
tested on ts4, LGTM

**Review by Jan-Thurner — DISMISSED** [review]
Code LGTM

**Review by edkaya — DISMISSED** [review]
Tested on ts4, works as expected

**Review by coolchock — APPROVED** [review]
re-approve after merge conflict was resolved

**Review by Jan-Thurner — APPROVED** [review]
Reapprove after merge conflict

**Pull request merged**
