### PR TITLE
 ⚠ Fixed critical exam bug that lead to internal server error at creation time of programming exercises

### PR DESCRIPTION
**Pull request by Malyuk-A**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Currently, it is not possible to create programming exercises for exams (in exam mode/exercise groups). An internal server error is created. By accident, I found out that I am the reason why this is not working for exam programming exercises. The current issue with course programming exercises seems unrelated (because it worked locally and e.g. on TS2 before just fine).

### Description
During my last Exam pop-up PR I changed how notifications for exams are created. I thought I only changed it for the case when an exercise is updated but (out of a reason I do not really understand) currently, tutors get notified when an exam (programming) exercise is created. This "edge-case" of EXERCISE_CREATED falls into my implementation that should only handle EXERCISE_UPDATED. This leads to a database failure. 
I added an if case to catch this "edge-case". 

The problem: Inside an exercise group when a new programming exercise is created a corresponding (I do not know why this design decision was made) EXERCISE_CREATED notification is build. But it falls into the same case as the EXERCISE_UPDATED for exam exercises and receives the entire problem statement as a property. Each notification is saved to the DB. The "target" property has a small size (~ 255 VARCHAR). For UPDATED the target with the huge problem statement is removed before saving. But not for CREATED. So the huge target property is saved and the DB leads to an internal server error. 

image

I am terribly sorry for not catching this prior.

### Steps for Testing
Log in to Artemis (e.g. TS2).
Find an exam and go to its exercise groups.
Add a completely new (not imported) programming exercise.
It should work (and not throw a 500 error code)

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
No changes.

### CODE REVIEW

**Review by lschlesinger — APPROVED** [review]
I tested in on TS2. Adding new and importing existing programming exercises as well as other exercise types worked for me without errors.

**Review by MerlinMehmed — APPROVED** [review]
Tested on TS1 and it looks like the bug has been fixed. Code changes look good :+1:

**Review by jhainzlschmid — APPROVED** [review]
I executed the related Cypress tests (ExamManagement, ExamAssessment and ExamParticipation) locally against ts3 and all passed

**Review by MDK5 — APPROVED** [review]
Code changes look good to me, however I wonder if there is any case where the title is not an update and the exercise in not a programming exercise. In these cases, the target is not set anymore. And even if such cases currently do not exists, it might make sense to still define some meaningful default for potential future implementations.

**Pull request merged**
