### PR TITLE
`Development`: Fix flaky modeling assessment component tests

### PR DESCRIPTION
**Pull request by pal03377**
---

> **Warning**
> **Before merging:**
> - [X] This PR needs to be merged in Apollon: https://github.com/ls1intum/Apollon/pull/296
> - [X] The Apollon package needs to be updated to `@ls1intum/Apollon 2.<newversion>` and *all* references to `@palsch/apollon` need to be removed.

---

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [X] I documented the TypeScript code using JSDoc style.

### Motivation and Context

Some modeling assessment tests are currently flaky:
- Bamboo: https://bamboo.ase.in.tum.de/build/result/viewBuildResults.action?buildKey=ARTEMIS-TESTS5145-TSTEST&buildNumber=4
- Github: Failing more consistently: https://github.com/ls1intum/Artemis/actions/runs/5547057107/job/15030418353?pr=6892

### Description

Used Angular change detection with `whenStable` to wait for the editor to be properly initialized. This still was not enough, as the React render cycle still does not line up with the one from Angular. Therefore, I introduced a new promise to wait for the next React render cycle in Apollon (PR https://github.com/ls1intum/Apollon/pull/296), and I'm waiting for that one now. This also allowed me to remove many test and production code delays.

For testing (locally, on a test server, running the client tests), I changed 

### Steps for Testing

Generally test modeling exercise assessment again and try to be creative:
- Assess a normal modeling exercise or one in an exam
- Make sure that the correct elements are highlighted in the assessment editor at all times
- Make sure that feedbacks on all kinds of elements still work and can be saved, also on Safari if possible (see also https://github.com/ls1intum/Apollon/pull/295)

### Code Review
Ignore all replacements `@ls1intum/apollon` -> `@palsch/apollon`. They are only for testing and will be removed.

#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### Test Coverage

Unchanged.

### CODE REVIEW

**Comment by pal03377** [comment]
I have to work on this some more because the bug fixed in #6893 appeared again :(

**Review by tobias-lippert — APPROVED** [review]
Tested on ts2. Creating, participating, assessing and viewing the result worked flawlessly.
Code also looks good, only the package and the import need to be replaced before merging.

**Review by MaximilianAnzinger — APPROVED** [review]
Code lgtm

**Review by jakubriegel — APPROVED** [review]
Tested on ts5, works fine

**Review by lennart-keller — DISMISSED** [review]
Tested on ts5 during testing session. Works well.

**Comment by pal03377** [comment]
Currently `blocked` only by https://github.com/ls1intum/Apollon/pull/296

**Review by tobias-lippert — APPROVED** [review]
Reapprove after updating the apollon dependency.

**Pull request merged**
