### PR TITLE
`Adaptive learning`: Visualize competencies linked to exercises correctly for exercise lecture units

### LINKED ISSUE #9714: Add linked competencies to exercise units
### Is your feature request related to a problem?

Currently the competencies are missing from exercise units.

### Describe the solution you'd like

When a lecture contains an exercise unit and the exercise is linked to competencies, the lecture unit should display the linked competencies similar to all other lecture unit types.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MaximilianAnzinger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

When a lecture contains an exercise unit it did not show the competencies linked to the exercise even if they existed. This was due to the decision not to allow linking exercise units to competencies, but only exercises themself. This PR resolves this inconsistency in the user interface.

Resolves #9714

### Description

Exercise units now have a transient field that is augmented before returning the lecture unit. Thus, the links will never be persisted in the database, but can be returned to the client for a consistent view.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with a lecture, exercise, and competency

1. Log in to Artemis
2. Navigate to Course Administration > Exercises
3. Edit the exercise and link the competency to the exercise
4. Navigate to Course Administration > Lectures > Units
5. Create a new Exercise unit with the exercise that is linked to the competency
6. Click on the Flag next to the Exercise unit
7. The popup should show the linked competency

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Release Notes

- **New Features**
  - Introduced functionality to link competencies with exercise units in lectures.
  - Added a method to retrieve competency links based on exercise ID.

- **Bug Fixes**
  - Enhanced test coverage to validate competency links associated with exercise units.

- **Documentation**
  - Updated method signatures and constructors to reflect new dependencies and functionality.

### CODE REVIEW

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Works as described

image

image

**Review by sachmii — APPROVED** [review]
Tested on TS1, everything worked as fine. Link sent me to the linked competency.

**Review by zagemello — APPROVED** [review]
Tested on TS1, works as expected!

**Review by JerroyTan — APPROVED** [review]
[Tested on TS1]
Everything worked as described, except I was not shown a popup with the linked competency, instead was brought directly to the page with all the competencies. Not sure if that was intended as it differs from description

**Review by kevinfischer4 — APPROVED** [review]
Tested on TS3, works as described. The linked competencies show up in the pop-up.
Screenshot 2024-11-11 at 13 39 12

**Review by flbrgit — APPROVED** [review]
Tested on TS3. Everything works as expected.
Screenshot 2024-11-11 170626

**Pull request merged**
