### PR TITLE
`Development`: Test VSCode plugin support

### LINKED ISSUE #8777: Adjust Config to support CORS for VSCode plugin
since the VSCode plugin uses CORS, Artemis config needs to be adjusted to allow this

### LINKED ISSUE #8817: Let Authentication support bearer
### Is your feature request related to a problem?

Not every client can use cookies. Therefore an option to authenticate without cookies should be possible

### Describe the solution you'd like

An endpoint similar to the standard authentication endpoint, but that the token is returned in the body.
In addition, rekeying is needed for the plugin use in Theia so that the user does not have to authenticate more than once.

### LINKED ISSUE #8876: Add Authorization header support for problem-statement component
### Is your feature request related to a problem?

VSCode plugins are not able to use cookies. The VSCode plugin is not able to use cookies but needs to fetch the problem statement component. 

### Describe the solution you'd like

The endpoint to fetch the problem statement should be able to receive an authorization header and forward it to get the exercise details.

### PR DESCRIPTION
**Pull request by janthoXO**
# THIS PR IS ONLY FOR TESTING PURPOSES ON TEST SERVERS

### Description
The PR includes the following main points:
1. API support now Bearer as well as cookie
The API looks first if a valid authentication token is provided in the cookie. if not the authorization header is checked.
2. Add CSRF security by custom header [refer to OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#employing-custom-request-headers-for-ajaxapi)
Mainly the custom header `X-ARTEMIS-CSRF` is needed now for every request
3. Adjust cors config
the application.yml defines a "allowed-origin-pattern" which was not checked in the WebConfigurer.java
4. Add endpoints for rekeying and getting exercises by the projectKey

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

## Release Notes

- **New Features**
	- Introduced a custom CSRF filter for enhanced security.
	- Added methods to retrieve build configurations and tokens for programming exercises.
	- Implemented a new HTTP interceptor for CSRF protection in the Angular application.
	- Added a button to start an online IDE based on user profile settings.

- **Bug Fixes**
	- Simplified JWT validation process for improved performance.

- **Documentation**
	- Updated method signatures and added annotations for better clarity.

- **Tests**
	- Enhanced test coverage for the new features and components.

### CODE REVIEW

**Comment by Hialus** [comment]
As this comment was not addressed in #8819 (and this is the PR which contains those changes now), I'll leave it here again so it is not lost/forgotten about:
> From what I get you have a client that for some reason cannot read/set the "Set-Cookie/Cookie" headers, but can read the body or a response and set the "Authorization" Header. Every proper library for executing HTTP requests should be able to handle arbitrary headers nowadays.
Our various iOS/Android apps are also able to use the Cookie headers instead of the Authorization header. Adding a separate way of authentication just for a single client that happens to use a bad requesting library is not a good idea imo.
>
> Edit: I see that Stephan has raised similar concerns in the linked issue, so maybe we can discuss this in the next dev meeting on monday.

**Comment by janthoXO** [comment]
> As this comment was not addressed in #8819 (and this is the PR which contains those changes now), I'll leave it here again so it is not lost/forgotten about:
> 
> > From what I get you have a client that for some reason cannot read/set the "Set-Cookie/Cookie" headers, but can read the body or a response and set the "Authorization" Header. Every proper library for executing HTTP requests should be able to handle arbitrary headers nowadays.
> > Our various iOS/Android apps are also able to use the Cookie headers instead of the Authorization header. Adding a separate way of authentication just for a single client that happens to use a bad requesting library is not a good idea imo.
> > Edit: I see that Stephan has raised similar concerns in the linked issue, so maybe we can discuss this in the next dev meeting on monday.

theres gonna be a discussion on monday concerning this issue

**Comment by janthoXO** [comment]
> > just for a single client that happens to use a bad requesting library is not a good idea imo.
but to answer that its just the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) which is able to handle cookies. the problem is though that [vscode plugins dont support cookie nor local storage](https://github.com/coder/code-server/issues/1148)

**Comment by Hialus** [comment]
> > > just for a single client that happens to use a bad requesting library is not a good idea imo.
> 
> but to answer that its just the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) which is able to handle cookies. the problem is though that [vscode plugins dont support cookie nor local storage](https://github.com/coder/code-server/issues/1148)

I've looked into the fetch docs and it provides the `response.headers.get(String)` method for getting response headers (and various ways to also create headers). Therefore I do not see why it shouldn't be possible to just read and write the proper cookie headers manually. I've done much the same with Pythons `requests` library in the past. Your library does not need to provide first party cookie support for you to use cookies, as cookies are just headers in HTTP.

**Comment by janthoXO** [comment]
> I've looked into the fetch docs and it provides the `response.headers.get(String)` method

It indeed does provide this method. But still if you call the method and in general print all headers the `set cookie` header is still missing

**Comment by janthoXO** [comment]
https://github.com/ls1intum/Artemis/assets/95364200/2ce37ca7-5b8c-4566-86c0-c69d1e9bf2e0

so that you believe me

**Comment by Hialus** [comment]
According to several online sources it seems like you have to set the `credentials` param to `include` or `same-origin` for the fetch api to enable cookies.
So like this:
```
fetch(url, {
  credentials: 'include'
})
```

**Comment by janthoXO** [comment]
> According to several online sources it seems like you have to set the `credentials` param to `include` or `same-origin` for the fetch api to enable cookies. So like this:
> 
> ```
> fetch(url, {
>   credentials: 'include'
> })
> ```

 I'm aware that the fetch API does support cookies. But the vscode extension environment does not. So cookies wont work in a VSCode extension.

**Comment by janthoXO** [comment]
LocalVC clone fails because of missing CSRF Header

**Comment by janthoXO** [comment]
This PR is deprecated

**Pull request closed without merging**
