### PR TITLE
`Exam mode`: Fix collapsible area of problem statement in exercises in student view

### LINKED ISSUE #8883: `Modeling exercises`: Problem statement panel closes if text is clicked
### Describe the bug

Clicking on the text of the problem statement also collapses the panel. This prevents selecting and copying parts of the problem statement.

### To Reproduce

1. Go to a modeling exercise
2. Click on the text of the problem statement (not the button)
3. The problem statement is collapsed

### Expected behavior

The problem statement should not collapse if the text is clicked. The problem statement should only collapse if the arrow button is clicked.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

Branch: feature/exam-mode/new-design Commit Hash: 9e56059

### What browsers are you seeing the problem on?

Chrome, Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Collapsible area of modeling and text exercises in exam mode includes also the text within the problem statement box. Therefore, the collapsible are should be changed to problem statement header and should not collapse by clicking on the text, but should on the header. It fixes #8883 and #8899.

### Description

Click function is moved from the whole problem statement box to the header.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Exam
- 1 Exam with at least one modeling and text exercise

1. Log in to Artemis
2. Participate the exam
3. Verify that you can collapse the problem statement by clicking only the new defined collapsible area (see screenshots) in both modeling and text exercise 

#### Exam Mode Testing

Prerequisites:
- 1 Student
- 1 Exam 

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the UI of other components in the exam mode stays unchanged. You can use the [exam mode documentation](https://docs.artemis.cit.tum.de/user/exams/students_guide.html#participating-in-the-artemis-online-exam) as reference.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Screenshots

Group 26

### CODE REVIEW

**Review by florian-glombik — APPROVED** [review]
Approve code

**Review by pzdr7 — APPROVED** [review]
Tested on TS5 with text, modeling, and file upload exercises. Works as expected 👍

**Review by SimonEntholzer — APPROVED** [review]
Code looks good, and tested successfully on TS1

**Review by egekurt123 — APPROVED** [review]
Works as expected in TS3

**Review by sarpsahinalp — APPROVED** [review]
Code lgtm

**Review by krusche — APPROVED** [review]

**Pull request merged**
