### PR TITLE
`Programming exercises`: Only store build logs of failed builds

### PR DESCRIPTION
**Pull request by sleiss**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Avoid storing too many build logs in the database

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise

1. Create a result with build failed and check  (in the database) that the build logs are available
2. Create a "red" result with test case failures and check (in the database) that the build logs are **not** available
3. Create a "green" result with 100% and check (in the database) that the build logs are **not** available

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by krusche — APPROVED** [review]
Code looks good 👍

**Review by Strohgelaender — APPROVED** [review]
code lgtm

**Review by simon-hng — APPROVED** [review]
Code looks good

**Review by JohannesStoehr — APPROVED** [review]
Looks good to me

**Review by manuelmanso — APPROVED** [review]
Change looks good

**Pull request merged**
