### PR TITLE
`Development`: Fix logging statement for online course client registrations

### PR DESCRIPTION
**Pull request by basak-akan**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [ ] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [ ] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [ ] I documented the Java code using JavaDoc style.

### Motivation and Context

For online courses that aren't linked to an external system or use the older LTI v1.0 standard, some onlineCourseConfiguration fields are left blank. This results in an issue when attempting to construct the ClientRegistration for such courses. Currently, this issue is flagged as an error.

image

### Description

- Adjusted the logging mechanism to categorize these as warnings instead of errors.
- Enhanced the warning message to provide more details.

### Steps for Testing

Please test locally to see the adjusted log message.

Prerequisites:
- 1 Course with Online Course enabled

1. Start Artemis server
2. Verify log warning for newly defined Online Couse 

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

no change

### Screenshots

image

### CODE REVIEW

**Review by terlan98 — APPROVED** [review]
Code LGTM

**Review by Xinyannnnnn — APPROVED** [review]
Code LGTM 👍

**Review by b-fein — APPROVED** [review]

**Review by DominikRemo — APPROVED** [review]

**Review by Strohgelaender — APPROVED** [review]
lgtm

**Comment by Kroko-fant** [comment]
looks good to me

**Review by laurenzfb — APPROVED** [review]
Code lgtm. Demonstrated in testing session, worked as expected

**Review by lennart-keller — APPROVED** [review]
Code lgtm, tested in testing session.

**Pull request merged**
