### PR TITLE
`Assessment`: Fix an issue with the export dropdown in the exercise scores table

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The export options popover in the exercise scores view previously either obstructed the modal that is opened when exporting the repositories or was immediately closed when trying to choose one option of the dropdown for downloading the results.

### Description

Fixes the bug by properly closing the popover whenever needed.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise

1. Log in to Artemis
2. Go to the scores page of the exercise and check that all export options work properly and are not covered or close too quickly

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Popover obstructing the modal:
Bildschirmfoto 2023-04-27 um 20 11 09

### CODE REVIEW

**Review by danielbode — APPROVED** [review]
Code looks good to me

**Review by pal03377 — APPROVED** [review]
Works on TS1, also the code looks good 👍 

Note: Personally, I wasn't able to even reproduce this bug on `develop` with just my mouse. When I clicked the popup, it always properly auto-closed. I was however able to reproduce it by navigating to the "⬇️ Download Repos" button with `Tab` on the keyboard and press `Space` to reproduce it. This PR fixes even that issue for me.

Unrelated issue (also present on develop): I cannot open the sub-menu "Export Results" by clicking with my mouse:
cannot-open-export-results-submenu

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Review by 1999Markus — APPROVED** [review]
Code LGTM!

**Pull request merged**
