### PR TITLE
`Programming exercises`: Add custom build scripts for local continuous integration

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

This PR builds on [#7528](https://github.com/ls1intum/Artemis/pull/7528#pullrequestreview-1726733152) and adds basic support for custom build scripts in Local CI.

### Description

Instructors can define script actions in the client during exercise creation which are then persisted in the database. During the set up of the build job container, these actions are retrieved for the build script.

### Steps for Testing

**Only test on TS3, TS5 or legacy TS11. Or test locally with LocalVC Local CI run configuration**
Prerequisites:
- 1 Admin/Instructor

1. Open "Create Programming Exercise" form, fill all necessary fields and enable custom build plans
2. Click on the displayed action item
3. Add something in the editor that will not interfere with the testing tasks, e.g. `echo "Hello World"`
image
4. Create exercise
5. Wait till template and solution builds complete and verify results. (Template 0 out of 13, Solution 13 out of 13)

_________________________

1. Do the same as above but now remove the action item
2. Add a new action item (don't change the code)
3. Create exercise
4. Verify that both builds fail

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts11. Worked as expected.

**Review by valentin-boehm — APPROVED** [review]
Tested on TS6, works as expected

**Review by reschandreas — APPROVED** [review]
tested locally, works as expected, code also lgtm

**Review by florian-glombik — APPROVED** [review]
Approving code

Quality and changes look good to me.

**Pull request merged**
