### PR TITLE
Chore/test/add gitlab jenkins mocks

### LINKED ISSUE #2077: Improve test coverage for GitlabService and JenkinsService
Currently the test coverage for `GitlabService` and `JenkinsService` are rather low:

image

image

We should reach an instruction coverage of at least 80% for all classes and each method in `GitlabService` and `JenkinsService` should be invoked at least once.

The actual communication to both services should be mocked, by providing exemplary responses for the requests used in the tests.

Examples can be found in the tests and mocks for BambooService and BitbucketService

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).

### Motivation and Context

Fixes #2077 Artemis has low code coverage for both `GitlabService`and `JenkinsService`. This PR aims to improve that coverage.
 
### Description

**Note:** I refactored the HTTP request interceptor for the Jenkins service which injects authorisation headers. Please test on **TS2** im creating, importing, and participating in programming exercises work correctly.

This PR does the following:
- adds mocks or Gitlab and Jenkins services
- implements missing mocking functionality in `AbstractSpringIntegrationJenkinsGitlabTest.java` 
- adds more unit tests to `ProgrammingExerciseGitlabJenkinsIntegrationTest.java`
- adds unit tests for `GitlabService`'s `health()` function
- fixes minor stuff
- refactors `JenkinsAuthorizationInterceptor` so that it uses the `JenkinsHttpClient`

### Testing
The PR affects Jenkins. Therefore it's important to test on TS2 if programming exercises work correctly. This means:
- Create / import / delete programming exercise
- Participate in an exercise and see if everything works correctly
 
### Test Coverage

**Before:**
91813943-b7d68d00-ec33-11ea-82c3-2465f6f856bf

91813980-c15ff500-ec33-11ea-9731-2da03e8b5b5f

**After:**
gitlab
jenkins

### CODE REVIEW

**Review by tiffca — DISMISSED** [review]
I saw an error but no longer reproducible, hence approving. All steps work fine, creating/import/delete/participating/grading manual 

-- previous test --
Importing an exercise produced an ISE. Something restarted the server and I can't reproduce it anymore, so I'm not sure what happened. I deployed twice to make sure I could reproduce the error.

Steps to reproduce: 
1. Import a programming exercise 
2. Click on import 
3. Set a release date
3. Notice you receive an ISE when you submit
4. Click import again and it says the exercise has been imported already (it has)  
5. Expected behavior: we should not see an error message 

/api/programming-exercises/import/2310?recreateBuildPlans=false&updateTemplate=false:1 Failed to load resource: the server responded with a status of 500 ()

zone.js:3363 POST https://artemistest2.ase.in.tum.de/api/programming-exercises/import/2310?recreateBuildPlans=false&updateTemplate=false 400

image

**Comment by philgabr** [comment]
I just tested this PR and for exercise creating/importing/deleting everythink worked as intended.

However I face a simila issue as @tiffca already mentioned, when trying to participate in an exercise:
image

this is the console log:
image

**Comment by ivanchimeno** [comment]
Thanks for the testing. I reverted the changes within the interceptor so these problems should be gone.

**Review by airelawaleria — APPROVED** [review]
Tested with @simonzilker and @marvinchimeka. Worked fine, no ise detected :)

**Review by simonzilker — APPROVED** [review]
Tested in testing session on ts2. Everything works fine,no bugs occured!

**Review by marvinchimeka — APPROVED** [review]
tested in a testing session on ts2. Approve. everything works fine

**Review by JohannesWeiss — APPROVED** [review]
Works as intended on ts2.

**Review by krusche — APPROVED** [review]

**Pull request merged**
