### PR TITLE
`Exam Mode`: Fix a user interface issue during submission updates in programming exercises

### LINKED ISSUE #7560: `Exam mode`: Navbar exercise icons not displaying correct state
### Describe the bug

Navbaricon for working on programming exercises not updated properly

### To Reproduce

DISCLAIMER: If the behaviour from the screencast does not occur for you, force reload the page and clear the cache (`Empty cache and hard reload`) - this seemed to be a reliable way for me to reproduce the issue.

1. Create an exam with a programming exercise, activate the online code editor
2. Join the Exam as student before it begins
3. Already input your username and accept the code of conduct _(so you should see a countdown now)_
4. Edit the code in the code editor and see that the build is triggered
5. See the icon is still the pencil and not a checkmark for having something submitted
6. Reload the page and see that now the navbar displays the correct exercise state

The same issue occurs for cloned exercises

### Expected behavior

The state of the exercise should contain a checkmark if submitted, and turn yellow after changes that were not submitted.

Edit file content (navbar pencil icon turns yellow) -> submit (navbar icon turns blue with save icon)

This should be the case without having to reload the page.

### Screenshots

The state after reloading the page would be the expected state. (Checksmarks for exercises where something was submitted)

https://github.com/ls1intum/Artemis/assets/63976129/e2206277-e576-4346-8f60-5fe143605903

<details>
  <summary>Initial Screencast</summary>

https://github.com/ls1intum/Artemis/assets/63976129/c40a667a-371f-4d6b-b380-0ccb5e439252
</details>

### Which version of Artemis are you seeing the problem on?

6.6.4

### What browsers are you seeing the problem on?

Chrome

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

#7070 changed the websocket submission updates to only send DTOs. The SubmissionDTO contains only a ParticipationDTO, not the entire participation. However, the client currently expects this and overwrites the stored participation in a exam exercise from the received data, causing issues as all the original participation properties are missing.

### Description

Added a hack to only update the stored participation with the new values. In the future, we need to update the data types to reflect the fact that the submission updates sent over WS do not contain the entire entities.

Fixes #7560.

### Exam Mode Testing

Try to reproduce #7560. Verify that if the animation shows "building and testing" while working on an exam:
- the exercise navigation bar shows the current exercise in dark blue
- the exercise status is display correct in the navigation bar (orange if changed but unsubmitted)
- the clone dialog is rendered correctly

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
tested locally, the issue is fixed.
The code looks (considering the time preasure) good to me.

**Review by RY997 — APPROVED** [review]
Tests locally, worked well.

**Review by milljoniaer — APPROVED** [review]
Code looks good!
Tested on ts4, works as expected 👍

**Review by MichaelOwenDyer — APPROVED** [review]
Seems to fix the issue

**Pull request merged**
