### PR TITLE
`Communication`: Improve usability of conversations user interface

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context + Description

Various small UI improvements requested by @krusche :

- Moved the filter icon to the right side of the input. The filter icon blue when active and it shows the number of conversations.
image
**Old:**
image

- Always now show the "plus" icon in the conversation sidebar. Also remove the blue color for active conversations and instead use a darker color to signal something is highlighted or active. Also changed the look of the buttons.
image
image
image
**Old:**
image
image

- Do not show login name any more in the conversation sidebar.
image
**Old:**
image

- Remove the chevron icon in the conversation header.
image
**Old:**
image

- Do not show id any more in info tab of conversation
image
**Old:**
image

- Change button to outline in channel creation form to make it more clear which option is selected.
image
**Old:**
image

- Changing the favorite status or the hidden status of a conversation does not cause a reload any more, meaning the loading indicator does not show up.

- Removed the dividers in the conversation sidebar and instead use margin for separation:
image

**Old:**
image

- Removed the collapse all and expand all buttons as it is rarely used feature and clutters the UI. 
image

- Make the border of the search field flush with the sidebar

image

**Old:**
image

- Decreased size of chevrons:

image

**Old:**
image

- Only keep the top border of the message input to make design cleaner

image

**Old: **

image

- Improved look and usability of search for messages input

https://user-images.githubusercontent.com/29718932/215533529-d1972c7c-9f27-4cc3-89ce-c2be00cd6fa2.mp4

**Old: **

image

- Make text input close to header when few messages are posted:
 
image

**Old: **

image

### Steps for Testing
- Send each other messages in channels, group chats and direct messages and check that everything works
- Please also checks threads are working as I touched the logic here

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage
- No Changes

### CODE REVIEW

**Review by LiaLism — APPROVED** [review]
Everything looks as expected (matches the screenshots). Tested on ts1.

**Review by tobias-lippert — DISMISSED** [review]
Tested on ts2. Works as described. Nice UI improvements.

**Review by Vinicius-Agreste — APPROVED** [review]
Tested on ts2, all changes work. Looks good in both, dark and light mode.

**Review by grochlitzzz — APPROVED** [review]
All changes working (and looking) and looking as expected. Tested on ts2 both in light and dark mode. Only remark is that when someone adds a reply in a Thread, the "New" tag appears normally (as you can see in the screenshot), but nothing appears on the "Conversations" menu, next to the conversation (like a new message does). I don't know if this behaviour is expected
image
image

**Comment by stefanwaldhauser** [comment]
> All changes working (and looking) as expected. Tested on ts2 both in light and dark mode. Only remark is that when someone adds a reply in a Thread, the "New" tag appears normally (as you can see in the screenshot), but nothing appears on the "Conversations" menu, next to the conversation (like a new message does). I don't know if this behaviour is expected image image

This is expected. @krusche any idea if we want to count thread replies also as unread message?

**Review by rriyaldhi — APPROVED** [review]
Code looks good to me.

**Review by bassner — CHANGES_REQUESTED** [review]
Hi!
Code looks fine except for the two very minor things marked below that could be changed.
It works as intended and includes all the fixes you described.

**Review by TheZoker — APPROVED** [review]
Tested on TS1

**Comment by 1999Markus** [comment]
Tested on ts1, works as expected.

**Review by 1999Markus — APPROVED** [review]

**Pull request merged**
