### PR TITLE
`Communication`: Fix announcement emails not rendering correctly

### PR DESCRIPTION
**Pull request by PaRangger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Currently, attachments and references are not properly displayed in announcement e-mails. They are shown as text with their text (e.g. [programming]Test(/link/to/exercise)[/programming]).

### Description

I added a custom parser that matches the tags and replaces them accordingly. Additionally, for images and attachments I added absolute links instead of relative ones to make them display properly. User references should just display their names.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with communication enabled

1. Log in to Artemis
2. Navigate to course
3. Navigate to the communication tab
4. Navigate to the announcement channel
5. Create an announcement
6. Check your e-mails
7. Check if the tags are rendered as links, which should forward you to the according resource. Images should also render as links. User and channel references should be rendered as Text with an @ for users and a # for channels.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Bildschirmfoto 2024-11-22 um 16 20 55

## Release Notes

- **New Features**
  - Enhanced email notifications with efficient markdown rendering and caching.
  - Introduced services for rendering custom markdown links and references.
  - Added functionality for converting relative URLs to absolute URLs during rendering.

- **Bug Fixes**
  - Improved error handling for markdown rendering processes.

- **Tests**
  - Added unit tests for the new markdown rendering services to ensure correct functionality.

### CODE REVIEW

**Review by sawys777 — APPROVED** [review]
Tested on TS1, everything worked perfectly as described.

**Review by zagemello — APPROVED** [review]
image
All works as expected, tested on TS3

**Review by cremertim — APPROVED** [review]
Code changes lgtm

**Review by alekspetrov9e — APPROVED** [review]
Works as expected. Email was received.

**Review by krusche — APPROVED** [review]
Great work 👍

**Pull request merged**
