### PR TITLE
`Programming exercises`: Fix repository link for submissions in practice mode

### PR DESCRIPTION
**Pull request by joka2206**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

For submissions in practice mode, clicking on git URL will lead to a 'page not found' error, because git links in practice mode need the string 'practice-' between exerciseId and userId (see screenshots below)

### Description

In order to fix this issue I added an if condition in ```programming-exercise.utils.ts``` to add the required string if the participation is a practice participation (boolean testRun).

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise where due date has already passed (student is still able to 'practice')

1. Log in to Artemis as student
2. Start the exercise in practice mode
3. Submit anything
4. Log in to Artemis as Instructor
5. Navigate to Course-Management and click the 'Participations' button on your exercise in practice mode
6. Click the participation id of an entry where practice is 'Yes'
7. Click the commit hash link

After the bugfix, this link should lead to the correct gitlab repository. 

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Location of the bug
Screenshot from 2023-08-18 10-02-19

Changes
Screenshot from 2023-08-18 10-23-01

### CODE REVIEW

**Comment by Strohgelaender** [comment]
@JohannesStoehr I think this one got removed for a reason previously, do you remember what exactly was the issue there?

**Review by JohannesStoehr — COMMENTED** [review]
Good catch of that bug. Can you also provide a test in `programming-exercise.utils.spec.ts` for this edge case?

**Review by RY997 — APPROVED** [review]
Tested on ts1, worked well.

**Review by MichaelOwenDyer — APPROVED** [review]
Changes look good to me 👍🏽

**Review by DominikRemo — APPROVED** [review]
LGTM

**Pull request merged**
