### PR TITLE
fix issue with plagiarism state updates on slow connections

### LINKED ISSUE #3321: "Confirm" and "Deny" in plagiarism tool sometimes get applied to the wrong match
### Describe the bug
When clicking on "Deny" while in the plagiarism detection view, it can happen that the wrong submission gets denied.
This happens if the loading times are long and a different submission is selected directly after clicking the "Deny" button.
This happens 100% of the time if a new match is selected while the system is still loading.

#### To Reproduce

1. Run plagiarism check on exercise (tested on Text exercise)
2. Select any match
3. Click "Deny" (or "Confirm")
4. While the system loads, select a different match
5. Once the loading is done, the newly selected match gets denied (or confirmed)

#### Expected behavior

The submission on which the "Deny" button was originally clicked is denied

#### Screenshots

I can try to reproduce it and share a video recording

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 90.0.4430.93
</pre></details>

#### Additional context
This problem seems to only occur if the server is under load, so if there is a noticable loading time after clicking "Deny",
which could make it more difficult to reproduce.

#### Output in Web Console

<details><pre>
  No Error / Warning output
</pre></details>

### PR DESCRIPTION
**Pull request by joschahenningsen**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
fixes #3321

### Description
With slow internet connection after clicking confirm or deny and then selecting another plagiarism comparison, the confirmation/deny get's applied to the now selected results. See:

https://user-images.githubusercontent.com/44805696/121356167-e86cf500-c930-11eb-9357-53c7579d6299.mp4

After my changes: 

https://user-images.githubusercontent.com/44805696/121356111-dc813300-c930-11eb-9dcb-67a993641ec6.mp4

Note: On the right I'm selecting network throttling, this was not picked up when recording :( 
 

### Steps for Testing

1. Navigate to plagiarism detection and select a result
2. Using the dev tools simulate very slow network connection
3. Confirm or deny
4. Select another comparison and turn of throttling
5. Observe, that the update gets applied to the correct comparison.

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Tested on TS2. Works for me.

**Review by NicolasUllmann — APPROVED** [review]
Tested on TS2. Everything worked as expected.

**Review by canyelten — APPROVED** [review]
Everything worked as expected.

**Review by FrankeLukas — APPROVED** [review]
Changes make sense to me.

**Review by krusche — APPROVED** [review]

**Pull request merged**
