### PR TITLE
Bugfix/programming exercise/c docker image as user

### PR DESCRIPTION
**Pull request by COM8**
Reopened #2504

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context

Changes the C docker container in a way, it runs everything as user, not as `root`.
This fixes the issue related to bamboo not being able to delete docker files after usage.

### Description

* Running inside the C docker image not as `root`, but instead as user (`artemis_user`).
* Changed the  C template exercise from rotx to hello world as a more simplistic example for the tester.
* Updated the GBS-Tester from `1.27` to `1.31`.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a new C programming exercise and in case this exercise runs all tests successfully, the job of this PR is done.
4. It should not display any warnings in Bamboo for the jobs like: "Unable to delete working directory" after the job finished so Bamboo is able to cleanup after each run.

### Screenshots

Screenshot from 2021-01-13 09-51-20

### CODE REVIEW

**Comment by tiffca** [comment]
I receive an ISE on ts1 when I try to create a C programming exercise
main.769108fb44e8ba45a6e0.bundle.js:4 POST https://artemistest.ase.in.tum.de/api/programming-exercises/setup 500
k @ main.769108fb44e8ba45a6e0.bundle.js:4
t.scheduleTask @ main.769108fb44e8ba45a6e0.bundle.js:4
main.769108fb44e8ba45a6e0.bundle.js:4 XHR failed loading: POST "https://artemistest.ase.in.tum.de/api/programming-exercises/setup"

**Review by airelawaleria — COMMENTED** [review]
Same ISE as @tiffca on ts1

**Review by simonzilker — COMMENTED** [review]
I get the error, too.

**Comment by COM8** [comment]
ACK. I will have a look at it. Thanks.

**Review by JohannesWeiss — CHANGES_REQUESTED** [review]
Tested with you second build and could not log into Artemis (ts1) at all, with none of the test-users. 

Edit: Does not work on the other test servers as well

**Review by airelawaleria — CHANGES_REQUESTED** [review]
Same issue as @JohannesWeiss. Cannot log in

**Comment by sleiss** [comment]
I've now merged develop into this branch, as this error is probably related to an issue that existed on develop a few days ago.
Could you please re-test it once the build succeded?

**Review by simonzilker — COMMENTED** [review]
Tested with @JohannesWeiss @marvinchimeka @EneaGore @airelawaleria . When accessing the build plans we get this error:
image
Don´t know if this is related to this pr. 
We do not exactly know how to test this pr, could you provide more informations on how to test it?

**Review by airelawaleria — APPROVED** [review]

**Review by EneaGore — COMMENTED** [review]
Tested in testing session, a few things are unclear like @simonzilker has mentioned.

**Review by marvinchimeka — COMMENTED** [review]
confirming what @simonzilker said

**Review by JohannesWeiss — COMMENTED** [review]
Tested in testing session on ts1, can confirm the issue mentioned by @simonzilker.

**Review by airelawaleria — COMMENTED** [review]
accidental approve

**Review by airelawaleria — COMMENTED** [review]
Issue mentioned by @simonzilker

**Review by philgabr — COMMENTED** [review]
For me the build was successful:
image

**Comment by COM8** [comment]
I'm unable to login when I publish this PR to ts1 or ts3 and I do not know how to fix it.
How to test this PR:
* Create a new C programming exercise and in case this exercise runs all tests successfully, the job of this PR is done.
* Also it should not display any warnings in Bamboo for the jobs like: "Unable to delete working directory" after the job finished so Bamboo is able to cleanup after each run.

**Comment by tiffca** [comment]
I receive this warning for the solution build plan, "could not remove working directory"

image

**Comment by COM8** [comment]
> I receive this warning for the solution build plan, "could not remove working directory"
> 
> image

OK. thanks. Could you send me an image of the build plan in bamboo please, so I can see if the new final stage is working like expected.

**Comment by COM8** [comment]
> > I receive this warning for the solution build plan, "could not remove working directory"
> > image
> 
> OK. thanks. Could you send me an image of the build plan in bamboo please, so I can see if the new final stage is working like expected.

Ok. Found the problem. The final task for cleanup is not being added.

**Comment by COM8** [comment]
Ready for review.
I fixed the outstanding issues and updated the initial description of the PR.

**Review by FlorianStang — APPROVED** [review]
Tested on TS1, everything worked as described. @JannisBittlmayer and me also tried to test this on TS3, but bamboo (website) did not seem to load.

**Review by JannisBittlmayer — APPROVED** [review]
Works as intended with what @FlorianStang said

**Review by airelawaleria — APPROVED** [review]
Tested on ts1, works fine

**Review by LudwigWeide — APPROVED** [review]
Works as inteded. Approve.

**Review by simonzilker — APPROVED** [review]
Works as intended

**Review by marvinchimeka — APPROVED** [review]
Tested on ts1. Approve

**Review by JohannesWeiss — APPROVED** [review]

**Review by DenizShabani — APPROVED** [review]
Works as intended

**Review by sleiss — APPROVED** [review]
Code wise it looks fine for me, two minor remarks:
- There was some reformatting of comments in the Java-source-code, was this intended?
- As the K6 tests were modified: Have the tests been successful with regard to the changed template? If the K6 tests are failing, this could be fixed in a follow-up (as probably only minor adjustments would be necessary).

**Comment by COM8** [comment]
> Code wise it looks fine for me, two minor remarks:
> 
> - There was some reformatting of comments in the Java-source-code, was this intended?
> 
> - As the K6 tests were modified: Have the tests been successful with regard to the changed template? If the K6 tests are failing, this could be fixed in a follow-up (as probably only minor adjustments would be necessary).

I just ran `./linting.sh`, which changed the formatting of the comment.

No, not from my side. Any way I can run those K6 test by my self?

**Pull request merged**
