### PR TITLE
`Communication`: Add recents section to sidebar

### LINKED ISSUE #9621: Communication: Add sub-groups to communication channels.
### Is your feature request related to a problem?

In this course the amount of sub-channels will grow and it will be annoying to scroll to the current one after some time: 
image

### Describe the solution you'd like

It would be nice to have a sub-group/folder in which the channels are stored. E.g. for above example: "Past" and "Current", where both can be expanded. 

### Describe alternatives you've considered

keeping the current system works as well, but channels can get very convoluted over time. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [X] I added multiple screenshots/screencasts of my UI changes.
- [X] I translated all newly inserted strings into English and German.

### Motivation and Context

- As decided, conversations marked as favorites should not only appear in the "Favorites" section but also remain at the top of their respective sections.
- To provide easier access to conversations that are more relevant or frequently needed by the user, a new "Currently Important" section should be introduced. This section should include channels linked to recent lectures, exercises, and exams, allowing users to find these conversations faster. (Closes #9621)

### Description

- Favorites now also appear at the top of their respective sections, in addition to the "Favorites" section.
- A new section called "Recents" has been added just below the "Favorites" section. This section includes channels from a time range of 1.5 weeks before to 1.5 weeks after the current date. For lectures and exams, the `startDate` is used as the reference, while for exercises, the `dueDate` and `releaseDate`  are considered. 
- Unused code related to `ChannelAccordionShowAdd` has been removed.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with Communication enabled

1. Log in to Artemis
2. Navigate to a course that has at least one exam/lecture that started no earlier than 1.5 weeks ago or an exercise with a due date no later than 1.5 weeks from now.
3. Navigate to its communication section and notice the new section called "Recents" with its related channels
4. Favorite a random channel and notice that it appears at the top of its related section in addition to being listed under the Favorites section.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| course-conversations.component.ts | 90.76% | ✅ ❌ |
| course-overview.service.ts | 92.77% | ✅ ❌ |
| sidebar.component.ts | 91.66% | ✅ ❌ |
| sidebar.ts | not found (modified) | ❌ |

### Screenshots

image

## Release Notes

- **New Features**
  - Introduced a new "recents" channel type for improved conversation categorization.
  - Added localization support for "recents" in both English and German.

- **Bug Fixes**
  - Enhanced conditional rendering logic for sidebar components, ensuring proper visibility based on user interactions.

- **Documentation**
  - Updated tests to reflect new functionalities and ensure robust coverage for the course conversations component.

- **Chores**
  - Removed unused properties and streamlined event handling in the sidebar component.

### CODE REVIEW

**Review by cremertim — DISMISSED** [review]
code changes lgtm

**Review by HawKhiem — DISMISSED** [review]
Tested on TS2. Everything works as described

image

**Review by julian-wls — APPROVED** [review]
Tested on TS4 during session. Works as expected!
Screenshot 2024-12-17 at 10 08 32


Well done :)

**Review by FelberMartin — DISMISSED** [review]
Tested on TS4, both the recently section and marking channels as favorite work as described 👍

**Review by PaRangger — APPROVED** [review]
Tested on TS4 during testing session. Works great. 👍 I noticed that now you can click the same channel multiple times and it keeps reloading the messages. But I don't think that's a big issue.

reload

**Review by sachmii — DISMISSED** [review]
Tested on TS4, everything works fine.

image

**Review by ahbitaqu — DISMISSED** [review]
[Tested on TS3]
Works exactly as it's supposed to. 

Personally, I'd love to have an indication on how much time there is left for the exercise here as well, but I can see how it might be the wrong place

**Review by JerroyTan — DISMISSED** [review]
[Tested on TS2]
Everything works as expected. I agree with the point mentioned by Anian. I would think that all active exercises would be considered "recent" or be of interest of the students. Perhaps we could fix the active exercises like favourites to the top of the exercise section.
image

**Comment by asliayk** [comment]
thank you for your reviews :) Based on your suggestions, I made the following changes:

- For exercises, not only `dueDate` but also `releaseDate` is considered now.
- "Recently" has been renamed to "Recents".

I appreciate your reviews once again :)

**Review by sachmii — DISMISSED** [review]
Tested on TS1, works fine

**Review by kevinfischer4 — DISMISSED** [review]
Tested on TS1, works as described.
image

**Review by anian03 — APPROVED** [review]
Looks good to me :)

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS1. Works as described, also exercises with postponed due dates then disappear if they do not meet the criteria anymore

**Review by flbrgit — APPROVED** [review]
Tested on TS4, the functionality works as described, and if the due-date of an exercise is changed further into the future than 1.5 weeks, the channels are not affected (what makes sense since there already might have been some communication)

**Review by sawys777 — APPROVED** [review]
Tested on TS4, everything works as described.

**Review by eylulnc — APPROVED** [review]
Tested on TS4, works as described.

**Review by HawKhiem — APPROVED** [review]
Tested again on TS4. Reapprove

**Review by sachmii — APPROVED** [review]
Tested on TS5, reapprove

**Pull request merged**
