### PR TITLE
`Development`: Refactor programming tests

### PR DESCRIPTION
**Pull request by ole-ve**
#### General
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
Autowired components are all-over the place in the test code. Following (for instance) #9415, these changes introduce new abstract test classes for each test setup (LocalCI/Independent/GitlabJenkins/GitlabCI).

### Description
Adds the new abstract test classes and adapt the arch test to accept multiple (abstract) test classes that are allowed to autowire classes.

As a side note, this PR fixes a path in JavaDoc for Atlas.

## Summary by CodeRabbit

- **Refactor**
	- Updated class and method signatures across multiple test files to enhance integration testing structure.
	- Introduced new abstract classes for programming integration tests to streamline testing processes.
	- Removed unnecessary fields from various test classes to improve clarity and maintainability.
	- Added new test cases to cover additional scenarios and edge cases related to learning paths and build job priorities.
	- Restructured test classes to simplify dependencies and enhance readability.

These changes improve the overall efficiency and organization of the testing framework, ensuring better integration and functionality in future updates.

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Refactoring looks good to me

**Review by cremertim — DISMISSED** [review]
refactoring lgtm

**Review by SimonEntholzer — DISMISSED** [review]
Good first step in cleaning up our server tests :+1:

**Review by sarpsahinalp — DISMISSED** [review]
Changes lgtm

**Review by JohannesStoehr — APPROVED** [review]
Reapprove after merge

**Review by cremertim — APPROVED** [review]
Reapprove after merge conflict

**Pull request merged**
