### PR TITLE
`Communication`: Fix reply button message editing issue in exercise view

### LINKED ISSUE #9786: Editing Messages of others in Thread Replys
### Describe the bug

When trying to reply to a message within the exercise-page on the right side, where the chat overview is displayed, you are given the option of editing a message of someone else. Even though the permissions don't allow for editing, the option is still given.

### To Reproduce

1. Go to any exercise that has at least one message in its channel, as well as a reply within the thread of that message
2. Click on "Reply" of the thread reply (within the message-thread)
3. See error: observe that you are given the option of editing the exercise

### Expected behavior

That you only reply to the message within another, newly created thread.

### Screenshots

Screenshot 2024-11-15 101757
Screenshot 2024-11-15 101807

### Which version of Artemis are you seeing the problem on?

7.7.0

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [X] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

There are some minor bugs/issues on the communication overview window of the exercise view:
- **Edit Message Permission:** Users who should not have permission to edit other users' messages can currently do so, because of the misbehavior of reply button. (Closes #9786)
- **Design Compatibility:** The communication overview window's design is not fully consistent with the design of the communication page. A reply button should not appear under a message that has no replies. Instead, users should see the reply option either on the reaction bar or in the dropdown menu (as the "Reply in Thread" option).
- **Replying to Messages:** Users cannot reply to posts that have answers because reply button works incorrectly. It works for editing instead of replying.
- **Reply in Thread Button:** The "Reply in Thread" button in the dropdown menu of messages does not work as expected.

### Description

- Only users with the appropriate permissions can now edit messages from others.
- Users can now reply to posts that already have answers.
- The design has been updated to align better with the communication page.
- The "Reply in Thread" button in the dropdown menu now functions correctly.
- I also removed some unused fields in `post-header` and `answer-post-header`.

### Steps for Testing

Prerequisites:
- 1 Instructor 
- 1 Student
- 1 Course with Communication enabled

1. Log in to Artemis.
2. Navigate to an exercise in a course to view the communication overview window.
3. Observe that the design of the reply buttons now matches the ones on the communication page.
4. Try editing messages from other users:
   - Use an instructor account to verify that you can edit messages.
   - Use a student account to confirm that you cannot edit other users' messages.
5. Right-click on a post, select the "Reply in Thread" option, and verify that it opens the input area (along with any existing replies).
6. For a post that already has replies, click the "Show Replies" button and confirm that you can now add a reply.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| post.component.ts | 95.19% | ✅ ❌ |
| post-footer.component.ts | 97.14% | ✅ ❌ |
| answer-post-header.component.ts | 88.23% | ✅ ❌ |
| post-header.component.ts | 100% | ✅ |
| post-reactions-bar.component.ts | 93.1% | ✅ ❌ |

### Screenshots

**updated reply button on communication window in exercise view**
image

## Release Notes

- **New Features**
	- Enhanced moderation rights handling in the answer and post components.
	- New functionality to close the create answer modal from various components.

- **Bug Fixes**
	- Improved interaction logic for post reactions and answer visibility.

- **Style**
	- Updated styles for reaction buttons to improve layout.

- **Tests**
	- Added new test cases for modal functionality in the Post and PostFooter components.
	- Refactored tests for clarity and improved coverage regarding user permissions in the PostReactionsBar component.

### CODE REVIEW

**Review by sachmii — DISMISSED** [review]
Tested on TS3, worked just fine. Could not edit/delete as a student but as a instructor I could. Yet the user's profile picture would turn grey after deleting the 1st message sent by that user.

Bildschirmfoto 2024-11-18 um 18 03 12

**Review by HawKhiem — DISMISSED** [review]
Tested on TS3. Everything works as described

**Review by cremertim — APPROVED** [review]
Code lgtm. Thanks for fixing the bug

**Review by vinceclifford — APPROVED** [review]
Tested on TS6, works as expected.

**Review by eylulnc — APPROVED** [review]

**Review by PaRangger — APPROVED** [review]
Tested on TS6, code LGTM, great job 👍

**Review by anian03 — APPROVED** [review]
Tested during testing session, works as expected :)

**Review by kevinfischer4 — APPROVED** [review]
Tested on TS1, works as described!

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS1. Works as expected

**Review by zagemello — APPROVED** [review]
Works as expected. Tested on TS5!

**Pull request merged**
