### PR TITLE
Add a "Review Progress" section to PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by FrankeLukas**
As discussed in the last meeting.

### CODE REVIEW

**Review by FuchsDominik — APPROVED** [review]

**Comment by FuchsDominik** [comment]
Any idea why the client tests fail?

**Comment by FrankeLukas** [comment]
> Any idea why the client tests fail?

No, but I'd bet it's at least not related to changes in this PR. 😓 Looks like they fail on develop, too.

**Comment by julian-christl** [comment]
Is it the coverage? Works here https://github.com/ls1intum/Artemis/pull/3888 and I added some client tests in this PR.

**Review by julian-christl — APPROVED** [review]

**Review by MDK5 — APPROVED** [review]
Looks good to me :+1:

**Review by SimonEntholzer — APPROVED** [review]

**Pull request merged**
