### PR TITLE
Small Improvements of the Example Submissions Board

### PR DESCRIPTION
**Pull request by Strohgelaender**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) locally.
- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all newly inserted strings into English and German.

### Motivation and Context
This PR introduces some smaller improvements to the Example Submissions Board. It adds access rights check for the delete / creates buttons to solve problems with tutors that are Editors / Instructors at other courses. Additionally the "Yes / No"-String was not translated until now.

### Description
I use the new checkAndSetCourseRights()-method to set the isAtLeastEditor-attribute and then use it on the buttons. I also moved some checks to the top to make the code a bit more readable.

### Steps for Testing

0. You need a user who is a tutor at your course but is at least editor at another course. 
1. Navigate to the Example Submissions Board as a Tutor
> The easiest way to do this is by navigating to the Assessment Dashboard -> Select an Exercise -> Start reviewing an Example Submission -> Use the breadcrumbs to go to the Example Submission Board
2. Check that the Tutor has no Buttons to create or delete Example Submissions
3. Check that toggling the language translates the Yes / No-String shown in the table ("Tutors need to assess this submission")
4. Check that Editors can still create / delete Example Submissions.

### Screenshots
Old Tutor View (unchanged for Editors)
grafik

New Tutor view (no Buttons)
grafik

German translation:
grafik

### CODE REVIEW

**Review by canyelten — APPROVED** [review]
Tested on TS1, works as expected.

**Review by canyelten — COMMENTED** [review]
A small suggestion; I would remove the point at the end of the sentence in the German version since it causes inconsistency.
image

**Review by Olimbia23 — DISMISSED** [review]
Nice work @Strohgelaender! Code changes look fine.

**Review by katjanakosic — APPROVED** [review]
Works as expected on ts1

**Review by lschlesinger — APPROVED** [review]
Tested on TS1. Works as described, check as tutor and instructor, english and german.

**Review by ArtemTsurikov — APPROVED** [review]
Tested on TS1, looks good

**Review by joschahenningsen — APPROVED** [review]
Looks good :)

**Review by iozbeyli — APPROVED** [review]
Code looks good

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Works.

**Comment by krusche** [comment]
Thanks for the contribution. We should further unify the access right handling in the future to invoke it in the corresponding service / router directly and not on the component level

**Pull request merged**
