### PR TITLE
`Tutorial groups`: Fix the contrast in the tutorial group rows in the dark mode

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

### Motivation and Context

When the tutors attempt to display all the tutorial groups, they face an issue with poor readability of the links in the corresponding rows due to low contrast in dark mode. This problem arises because the rows are highlighted in a cyan/blue color, making the clickable links (the titles of the tutorials) barely visible.

### Description

The same color and contrast used to highlight elements in the left sidebar are also applied to the rows of the tutorial groups for tutors (Discussed with Ramona). By doing this, we maintain consistency in the coloring scheme and avoid hardcoded colors in the client. Additionally, we have removed the hovering effect when users hover over a row, as the row itself is not clickable, which was confusing for users. We keep the hovering effect for the clickable link (title of the tutorial).

### Steps for Testing

Prerequisites:

- 2 Students
- 2 Tutorial Groups 

1. Log in to Artemis
2. Navigate to Course Management
3. Select a Course
4. Navigate to Tutorials 
5. Create a new Tutorial Group 
6. Select the first student (Student X) as a tutor
7. Create another new Tutorial Group 
8. Select the second student (Student Y) as a tutor
9. Log in to Artemis again as Student X 
10. Navigate to Course 
11. Click on Tutorials and show all Tutorial Groups 
12. Verify that the row for the group that you are tutor for has the same contrast as the sidebar
13. Verify that the name of the tutorial is now easy to read in dark and light mode
14. Verify that there is no any hovering effect for the row, but for the name of the tutorial

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Screenshots

- Before the fix: 
68747470733a2f2f6779617a6f2e636f6d2f37363233623235363063343661656139323530373533323438313634373866332f726177
68747470733a2f2f6779617a6f2e636f6d2f34303461353032353234613763373734303161613132633137393339303661322f726177
- After the fix: 
Screenshot 2024-04-28 at 15 12 09
Screenshot 2024-04-28 at 15 11 58

## Summary by CodeRabbit

- **Style**
	- Updated styling for tutor and non-tutor roles in the tutorial groups table.
- **New Features**
	- Enhanced the tutorial groups table by conditionally applying classes based on the user's tutor status.

### CODE REVIEW

**Comment by JohannesStoehr** [comment]
This is also a dark mode issue related to tutorial groups. Do you want to fix this in this PR as well? #6448

**Comment by edkaya** [comment]
> This is also a dark mode issue related to tutorial groups. Do you want to fix this in this PR as well? #6448

Yes, thanks for pointing it out. I can fix that as well.

**Comment by edkaya** [comment]
> > This is also a dark mode issue related to tutorial groups. Do you want to fix this in this PR as well? #6448
> 
> Yes, thanks for pointing it out. I can fix that as well.

After today's dev meeting, I talked to Ramona about this issue and she thought that since it is not super urgent to fix this, I will fix and create another PR for this towards the end of this week. Is it okay for you?

**Review by egekurt123 — APPROVED** [review]
Manually tested on TS4, works as expected

**Review by sarpsahinalp — APPROVED** [review]
code lgtm

**Review by JohannesWt — APPROVED** [review]
Code looks good - good improvement 👍

**Review by rabeatwork — APPROVED** [review]
Maintainer approved

**Pull request merged**
