### PR TITLE
Remove sudo from C Jenkinsfile

### LINKED ISSUE #2778: C jenkins pipline breaks if jenkins user does not have id 1000
### Describe the bug

Run the pipline with a user that has an id other than 1000 and gitlab will execute docker run -u yourid:yourGroupId and the whole pipline starts to break down.
The pipline will fail because the jenkins user is not part of /etct/passwd inside the docker container(happens on calling sudo or whoami).

#### Expected behavior
Jenkins pipline works in all setups :D

#### Example pipeline output
Notice the -u 1004:1004 and how sudo fails
```
$ docker run -t -d -u 1004:1004 -w /home/jenkins/remote_agent/workspace/ALPROCPRIME/ALPROCPRIME-SOLUTION -v /home/jenkins/remote_agent/workspace/ALPROCPRIME/ALPROCPRIME-SOLUTION:/home/jenkins/remote_agent/workspace/ALPROCPRIME/ALPROCPRIME-SOLUTION:rw,z -v /home/jenkins/remote_agent/workspace/ALPROCPRIME/ALPROCPRIME-SOLUTION@tmp:/home/jenkins/remote_agent/workspace/ALPROCPRIME/ALPROCPRIME-SOLUTION@tmp:rw,z -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** ls1tum/artemis-c-docker:latest cat
$ docker top 24c9d5e891530f8fb639c19a3138aa1418e4047d2a20b16d153a470636c5a51a -eo pid,comm
[Pipeline] {
[Pipeline] timeout
Timeout set to expire in 30 min
[...]
 > git rev-parse refs/remotes/assignment/master^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 3a8b38713199d8f4e56da2ccc5e98be7f77b77a8 # timeout=10
2021-01-29T15:27:57+01  + cd /home/jenkins/remote_agent/workspace/ALPROCPRIME/ALPROCPRIME-SOLUTION
2021-01-29T15:27:57+01  + sudo chown artemis_user:artemis_user assignment/ -R
2021-01-29T15:27:57+01  sudo: you do not exist in the passwd database
```
## Possible fixes/workarounds

- use `args '-u 1000:1000' `but that somehow results in no code being executed.
- use `args '-u root' ` and get rid of the sudo calls (not good but only thing that works for me)

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).

### Motivation and Context

Resolves #2778. 

### Description

We remove the use of `sudo` from the Jenkinsfile for C exercises because apparently it's not needed for the pipeline to run correctly (I tested this locally and on TS2 which uses a separate agent for running pipelines). 

### Steps for Testing

Please use TS2 to test this PR:

1. Log in to Artemis
2. Navigate to Course Administration
3. Generate a C programming exercise
4. Click on "Edit in Editor", navigate to solutions and make sure all tests passed
5. Participate in the exercise. Here you should get build errors if you enter gibberish. If you enter the solution code, the tests should pass

### CODE REVIEW

**Review by rs-maker — APPROVED** [review]
Tested on TS3 works perfectly fine.

**Review by jhainzlschmid — APPROVED** [review]
Tested on ts2 and everything worked

**Review by sinangunduz — APPROVED** [review]
tested on ts1, works perfectly fine

**Review by FuchsDominik — APPROVED** [review]
Works 👍

**Pull request merged**
