### PR TITLE
Feature/newdatepicker

### PR DESCRIPTION
**Pull request by Balgorn**
Swapes out the existing datepicker with https://github.com/DanielYKPan/date-time-picker for a fancier look.

Following components were touched:
modeling-exercise-dialog
programming-exercise-dialog
instructor-dashboard-result-dialog

### CODE REVIEW

**Comment by krusche** [comment]
The feature branch leads to a compile error on the build server (see https://bamboobruegge.in.tum.de/browse/ARTEMIS-WEBAPP12-2/log): 

`ERROR in src/main/webapp/app/instructor-dashboard/instructor-dashboard-result-dialog.component.ts(55,50): error TS2339: Property 'releaseDate' does not exist on type 'InstructorDashboardResultDialogComponent'.`

Please run `yarn webpack:prod` locally to make sure that everything compiles

**Comment by Balgorn** [comment]
sorry my local setup didn't catch that. Should be fixed now @krusche

**Comment by krusche** [comment]
Another comment: We already use the dependency 'angular2-moment'. Is there a need to add another moment dependency?

**Comment by Balgorn** [comment]
@krusche thanks for your feedback:

package.json: reduced dependencies needed and fixed indentation to avoid complete change

lines per change: the html changes are necessary to display. Changed the logic of toggling to the html itself. If needed could also remove the safety of temp variables, which prevent side effects and well formed input for server.

**Comment by Balgorn** [comment]
@krusche as discussed in slack i moved the logic for formating to server in the according place that makes the components more clear.

**Pull request merged**
