### PR TITLE
Update apollon to version 2.6.3

### PR DESCRIPTION
**Pull request by iozbeyli**
Update apollon version to 2.6.3

### Steps for Testing
1. Create a modeling exercise
2. Solve the exercsie
3. Assess the submission

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Tested on TS1. No errors occurred.

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 1. Everything worked as expected.

**Review by ArtemTsurikov — APPROVED** [review]
Looks good to me. Tested on TS1

**Review by canyelten — APPROVED** [review]
Tested on TS1. Works as expected.

**Review by FrankeLukas — APPROVED** [review]
Still works.

**Review by katjanakosic — APPROVED** [review]
Works fine :)

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Works.

**Pull request merged**
