### PR TITLE
`Assessment`: Enable save button on all changes in modeling assessments

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [X] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Even with the fix from https://github.com/ls1intum/Apollon/pull/295, the save button is sometimes disabled when it should not be.

### Description

The problem is that the disabled state is not refreshed often enough. A single `return` statement prevented the state to be updated when the Apollon editor somehow was not loaded in the background. Removing this `return` fixes the problem.

### Steps for Testing

Prerequisites:
- 1 exam with >= 1 modeling exercise and a participation (e.g. https://artemis-test5.artemis.cit.tum.de/course-management/9/exams/11)
- 1 tutor to assess the exam

1. Go to the exam assessment dashboard
2. Assess the modeling exercise
3. Add feedback to a part of the submission (referenced feedback). Don't add any text, just the credits.
4. Observe that the save button is enabled. Before, it was still disabled (see https://github.com/ls1intum/Apollon/pull/295#pullrequestreview-1530490008)

#### Exam Mode Testing

see above

#### Performance Review
- [X] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Screenshots

https://github.com/ls1intum/Artemis/assets/9006596/5db08f57-d329-4b62-ba5e-177b19fbf81b

### CODE REVIEW

**Review by terlan98 — APPROVED** [review]
Tested on TS5. Works as expected

**Review by laadvo — APPROVED** [review]
Tested on ts1, the save button is now also enabled on first change.

**Review by RY997 — APPROVED** [review]
Tested on ts2, worked well

**Review by MichaelOwenDyer — APPROVED** [review]
Change fixes the issue 👍🏽

**Review by maximiliansoelch — APPROVED** [review]

**Pull request merged**
