### PR TITLE
`Programming exercises`: Fix initial build on programming exercises imported from files

### PR DESCRIPTION
**Pull request by reschandreas**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Right now, importing a Programming Exercise from a file results in a failing build of the solution plan. (Because the build Is triggered before the exercise is fully imported). This PR fixes that and prevents confusion as the build plan is correctly run the first time and also passes instantly.
### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise exported previously

1. Log in to Artemis
2. Navigate to Course Administration
3. Import a PE from a file, make sure the template plan fails as expected and the solution plan passes
4. Create a new PE normally, make sure the template plan fails as expected and the solution plan passes
5. Import a PE from another PE, make sure the template plan fails as expected and the solution plan passes

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

#### before
Screenshot 2023-10-09 at 14 26 07
#### after
Screenshot 2023-10-09 at 14 26 23

### CODE REVIEW

**Review by laurenzfb — APPROVED** [review]
tested in testing session, worked as expected

**Review by milljoniaer — APPROVED** [review]
tested in testing session, worked as expected

**Review by aplr — APPROVED** [review]
Tested in testing session, LGMT

**Review by Strohgelaender — APPROVED** [review]
code

**Review by terlan98 — COMMENTED** [review]
Tested on TS5. Importing from file works only if the short name of the exercise is not changed. Changing the short name leads to the issue documented in https://github.com/ls1intum/Artemis/issues/7188.

**Review by laadvo — APPROVED** [review]
code lgtm

**Pull request merged**
