### PR TITLE
`Development`: Update documentation on the exam mode

### PR DESCRIPTION
**Pull request by Dominik-Weinzierl**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Description

Updated the documentation of the exam mode (screenshots).

Since the text is already very understandable, it was not necessary to extend it.

If you see outdated screenshots, please mention them and provide an updated one! This will help me a lot.

Information about the Exam Live Statistics and Test Exams will be added once these two features are usable by instructors.

### Steps for Testing

1. Look at the documentation about exams: https://artemis-platform--5352.org.readthedocs.build/en/5352/user/exam_mode/

### Review Progress

- [x] Review 1
- [x] Review 2

### CODE REVIEW

**Review by manuelmanso — DISMISSED** [review]
Good job updating the screenshots.

**Review by TheZoker — APPROVED** [review]
LGTM!

**Review by max-bergmann — APPROVED** [review]
Scrolled through the exam documentation. Looks good to me

**Review by Marvin-Vitcu — APPROVED** [review]
The documentation looks good to me.
I really like the style of the screenshots 👍

**Review by Marvin-Vitcu — COMMENTED** [review]
I thought EIST recommends IntelliJ now and not Eclipse.

image

**Review by luisa-we — DISMISSED** [review]
The documentation is really understandable, looks good to me.

**Review by babyygemperor — APPROVED** [review]
Nice documentation style, very readable, looks great to me 👍🏼

**Review by MetinLamby — APPROVED** [review]
very clear and detailed documentation!

**Comment by Dominik-Weinzierl** [comment]
Added links to the about us page. Re-approving is not required.
https://user-images.githubusercontent.com/60005702/178718002-b2f8dafb-936d-4d81-9316-fcca69f336a1.mp4

**Review by krusche — CHANGES_REQUESTED** [review]
I don't like some of the new screenshots, because they include less details (e.g. exam_assessment_dashboard_second_correction.png) and show unrealistic data such as "Test Text Exercise 1". It would be better to keep the existing realistic data, also e.g. in the assessment dashboard or in the add students view

**Comment by Dominik-Weinzierl** [comment]
I added more realistic screenshots: 
<details>
<summary>Screnshots</summary>

assessment_dashboard
exam_assessment_dashboard_second_correction
exercise_variants
student_exams

</details>

**Review by mallgaier — APPROVED** [review]
Changes look good 👍

**Pull request merged**
