### PR TITLE
`Plagiarism checks`: Include only student submissions

### LINKED ISSUE #6023: `Plagiarism checks`: The submissions of Tutors/Instructors shouldn't be considered in the plagiarism checks
### Describe the bug

Tutors/Instructors sometimes test the code of students to replicate possible issues with the test cases. Their submissions shouldn't be considered in the plagiarism checks. Otherwise, we will have cases with high similarity, which would confuse when instructors deny them. 

### To Reproduce

1. Solve any exercise as a student. 
2. As instructor/tutor, use the submitted code of the student and submit it. 
3. Check that both submissions are presented in the plagiarism checks. 

### Expected behavior

The submissions of Tutors/Instructors shouldn't be considered in the plagiarism checks. 
**_In case this is on purpose should be a way to differentiate the tutor's/instructor's submissions. Maybe a * next to the login (ge##aaa *). In this way, we can deny immediately plagiarism without checking who belongs to that login first._** 
**_Another option would be to mark in another color in the table the case._** 

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

5.12.9

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Fixes #6023.

From the issue:

Tutors/Instructors sometimes test the code of students to replicate possible issues with the test cases. Their submissions shouldn't be considered in the plagiarism checks. Otherwise, we will have cases with high similarity, which would confuse when instructors deny them. 

### Description
This PR introduces a filter which excludes submissions from tutors, editors and instructors from plagiarism checks. The change applies to manual and continuous checks.  

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Tutor
- 2 Students (⚠️ Those students cannot be instructors not tutors in the course!)
- 1 Exercise (text, programming or modeling)

1. Create two identical submissions from two student accounts.
2. Create an identical submission from a tutor account. 
3. Create an identical submission from an instructor account.
4. As instructor run plagiarism checks for the exercise.
5. Verify that only student submissions are visible in checks results.

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Note: _Newly added logic is tested._

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| ProgrammingPlagiarismDetectionService.java | 65% | ✅                           |
| ModelingPlagiarismDetectionService.java | 92% | ✅                           |

### CODE REVIEW

**Review by dearjasmina — APPROVED** [review]
code lgtm, I really like the addition of the authorisation service

**Review by konrad2002 — APPROVED** [review]
tested on TS11L with students 1,2; tutor 6; instructor 11

**Review by marlon-luca-bu — APPROVED** [review]
Tested on TS2, everything worked as expected

**Review by basak-akan — APPROVED** [review]
Code LGTM

**Review by Santia-go — APPROVED** [review]
Tested in TS3

I followed the steps to test. Artemis test account 1 and 2 are students, test account 9 is a tutor and test account 15 is an instructor. 

image

The results after the plagiarism check just show the cases where are involved only students. 
image

**Pull request merged**
