### PR TITLE
`Exam mode`: Prevent content of Exam Checklist from leaving viewport

### LINKED ISSUE #5525: Exercise Groups button out of view
### Describe the bug

When resizing the exam checklist, the exercise group button gets out of the view.

### To Reproduce

1. Go to the Exam Management
2. Click on Exam Checklist
3. Resize the view
4. See the button out of view

### Expected behavior

The button should not get out of the view.

### Screenshots

image

### What browsers are you seeing the problem on?

Firefox

### PR DESCRIPTION
**Pull request by reschandreas**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

It's an old issue that was labeled `good first issue` so I figured I have a go at it. Hope it's alright and if it's not needed anymore, just close the PR unmerged.

closes #5525 

### Description
I added the css class `table-responsive` to a new `div` that wraps the original tables. This prevents the buttons from leaving the view. As a result the table is now more responsive and horizontally scrollable if the content does not fit.
| before | now |
|--------|--------|
| before | after |
### Steps for Testing

Prerequisites:
- 1 Exam

1. Go to the Exam Management
2. Click on Exam Checklist
3. Resize the view
4. Check if the button leaves the view

#### Exam Mode Testing

Prerequisites:
- 1 Exam

1. Go to the Exam Management
2. Click on Exam Checklist
3. Resize the view
4. Check if the button leaves the view

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Exam Mode Test
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by pal03377 — DISMISSED** [review]
Tested on TS5, it works as expected 👍 Reviewing the code was a bit more tricky, but I was confirmed that it is only a new `div` wrapper, which causes a weird Git diff in combination with prettier.

Thanks for the contribution!

**Review by DominikRemo — CHANGES_REQUESTED** [review]
Tested on ts2. Works as expected
However, on small devices, the other tables have the same problem (E.g. Exam correction). Can you wrap them with `<div class="table-responsive"></div>` like you did for the first table, please :)
Bildschirmfoto 2023-08-08 um 17 00 02

**Comment by reschandreas** [comment]
Hi! @DominikRemo, thanks for the idea! I implemented it, looks better now

**Review by DominikRemo — APPROVED** [review]
Tested again on ts2. Works well, thank you for this improvement
Code LGTM

**Review by pal03377 — APPROVED** [review]
Tested again on TS5. Code also looks good 👍

**Review by terlan98 — APPROVED** [review]
Tested on TS5. Works as expected 👍

**Review by julian-christl — APPROVED** [review]
Git is really wonderful. Instead of marking two lines as changed and everything als as whitespace change, this xD

Code lgtm

**Pull request merged**
