### PR TITLE
Add refresh button to code-editor-actions

### PR DESCRIPTION
**Pull request by schultek**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I edited the integration tests (Jest) related to the features
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Students have no way to reload the files in the online editor without reloading the whole page.

### Description

- Added a 'Refresh' Button next to the 'Save' and 'Commit' Buttons
- When there are no unsaved changes, new files are pulled from the server
- When there are unsaved changes, a modal is shown to confirm the action
- Refreshing will delete all unsaved changes
- Refreshing will **keep** saved but uncommitted changes
- Refreshing will update the file-browser and the code-editor

### Steps for Testing

1. Log in to Artemis
2. Navigate to an Programming Exercise Online Editor
3. Test refreshing
      - without changes
      - with unsaved changes
      - with uncommitted changes
      - with changes committed via your local machine
      - any combination of the above :)

### Screenshots

Bildschirmfoto 2020-07-01 um 19 14 15
Bildschirmfoto 2020-07-01 um 19 14 23

### CODE REVIEW

**Comment by Varnika-Tyagi** [comment]
Works as intended for refreshing without changes (No prompt displayed as it isn't needed. The page simply refreshes.)

When refreshing with unsaved changes, the above prompt 'You have unsaved or uncommitted changes...' is displayed. However, if I choose to refresh anyway, make no further changes, press Save and refresh, I still get the prompt 'You have unsaved or uncommitted changes.. again. Is it intended behaviour?

**Comment by anditurdiu** [comment]
The way it is implemented currently, also saved changes will be deleted I believe. I think this makes sense if the student manages to create some sort of conflict, but I think the wording should then be changed from refresh to reset. This is also the function that is being called on the server (resetRepository)

**Comment by krusche** [comment]
@schultek I guess this was a misunderstanding. 

The refresh button should **not** reset the repository immediately. It should just initiate a git pull operation on the server and reload the files list. It should then remove local files so that they are loaded again from the server. (This will make sure that these files have the newest content). In case of unsaved changes, the user should be warned, because unsaved changes (these are the local ones in the browser) will be lost.

Saved, but uncommitted changes should not immediately be lost. Only if pulling leads to a conflict (which might not be the case), the normal warning dialog (already existing) should be shown and an actual reset should be offered to the user.

Can you please adapt the behavior of the refresh button?

**Comment by schultek** [comment]
Thanks for the reviews 👍 I changed the button to be enabled when building.

**Pull request merged**
