### PR TITLE
Avoid too large hibernate entity graphs when preparing the exercise start in exams

### PR DESCRIPTION
**Pull request by krusche**
Exams with 1850 students and 8 exercises can lead to a server crashes (out of memory).
This happens, when additional students are added and prepare exercise start is invoked, when already many exercises and participations exist.

The issue is the use of many-to-many relationships in the entity graph. In this PR, I fixes the issue. There are still potential performance improvements (see TODOs in the code), but the crash should not occur any more.

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the coding and design guidelines

1. Create an exam with 2000 test users (a csv can help). Do not use programming exercises to save time.
2. Generate individual student exams and prepare exercise start
3. Now add one more student, generate the missing individual student exams
4. Click again on prepare exercise start. The server should not crash.

### CODE REVIEW

**Comment by krusche** [comment]
Tested with 1500 students and 12 exercises. Seems to work fine.

**Comment by krusche** [comment]
also works with more users 👍

**Review by kloessst — APPROVED** [review]
Code looks good to me. Haven't tested it yet though.

**Review by airelawaleria — APPROVED** [review]
tested with 2005 students and 10 exercises

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts1 with 2,099 students, did not experience any issues.

**Review by philgabr — APPROVED** [review]
Workes as described, server didn't crash.

(Still the Artemis loading symbol was displayed since I importet the 2000 students)
image

**Review by sebastiantpeter — APPROVED** [review]
Ts1 did not crash.

**Review by EneaGore — APPROVED** [review]
Seems to work fine. Tested on ts1 with 2002 students and 12 exercises

**Pull request merged**
