### PR TITLE
`Plagiarism checks`: Fix formatting of similarity distribution

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

When changing the chart implementation from `chart.js` to `ngx-charts`, I implemented the y-axis formatting in a way, that does not scale for large maximal values.

### Description

Instead of always formatting the y-axis in integer steps, I declared a minimum y-intercept of 5. This means if only values < 5 are displayed by the chart, the highest value on the y-axis is 5. If at least one value is > 5, the y-axis adapts accordingly.
### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming/Text/Modeling Exercise with Plagiarisms

In general there are two possibilities to test these changes:

- Simulate plagiarisms on a test server: This might work, but only in small scale (you would have to do > 20 Submissions with some similarity in order to test these changes for large values)
- Use your local setup: Checkout this branch and use e.g, the following test data:
```
ngxTestData = [
        { name: '0%-10%', value: 0 },
        { name: '10%-20%', value: 0 },
        { name: '20%-30%', value: 0 },
        { name: '30%-40%', value: 0 },
        { name: '40%-50%', value: 13 },
        { name: '50%-60%', value: 24 },
        { name: '60%-70%', value: 36 },
        { name: '70%-80%', value: 41 },
        { name: '80%-90%', value: 57 },
        { name: '90%-100%', value: 0 },
    ];
```
Copy this and paste it as attribute in `plagiarism-run-details.component.ts`. Additionally, you have to change line 19 in the corresponding HTML template to: `[results]="ngxTestData"`

In either case, the testing steps are similar:

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to the exercise details page of your prepared exercise
4. Click the "Check plagiarism" button
5. Run the plagiarism detection once
6. Click on "Run details"
7. Check the chart. The y axis should now be formatted in bigger steps for large values
     - If you work on your local setup: add `ngxTestData` as attribute in `plagiarism-run-details.component.ts` and change the corresponding line in the html template (described above). Feel free to change the test values in order to check how the chart looks if all values are below 10 or even 5 (or even smaller).

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

How it currently looks for large values:
image (5)

How it looks in this PR (different data set):
image

### CODE REVIEW

**Review by coaxial1 — DISMISSED** [review]
I've tested this locally using your provided test data and tried the cases where all values are < 10 and < 5 as well. The chart works as expected.
LGTM!

P.S.: I assume you're going to delete the test data before we merge, tho? :D

**Review by Malyuk-A — COMMENTED** [review]
I tested it locally and it seems to work great. 👍
But I also support the comment above to first remove the test code prior to merging (-> lava anti pattern^^)
image
image

**Review by filip-gregurevic — APPROVED** [review]
Looks good to me. Nice work 🚀

**Review by Malyuk-A — APPROVED** [review]
re-approve 👍

**Review by coaxial1 — APPROVED** [review]
reapprove

**Review by cremertim — APPROVED** [review]
Great work! The prposed test course works on my local setup

**Pull request merged**
