### PR TITLE
Add validation for exam publish and review dates if they are set

### LINKED ISSUE #1907: [Exam] Complaing is possible even though there are no scores shown
### Describe the bug
When the release date of the results is not set but the review period is, the student is allowed to complain, however, no scores are shown, which makes it misleading. We should make setting the release date mandatory and not allow the start student review date to be before the release date.

#### To Reproduce
1. Create an exam, with no result release date. Set the student review period 
2. Participate in the exam, evaluate your submissions. 
3. As a student again, go to the exam summary page.

#### Expected behavior
You should not see the complaint component or the scores should also be shown

### Environment

<details><pre>
 - OS: Windows
 - Browser chromium
</pre></details>

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshotsof my UI changes

### Motivation and Context
Fix #1907. The dates can currently be set incorrectly, e.g. the review end date before the review start date or the review start date before the publish results date. The latter problem can cause the students being able to complain without seeing any results.

### Description
Add checks that the dates have to be in order, meaning
- Exam End before Result Release
- Result Release before Review Start
- Review Start before Review End

Since most of the time those dates are unknown when the exam is created and taken, they can still be left empty and changed later. For one date to be valid, the previous date needs to be set properly.

#### Known issues:
- After setting a date, unsetting/deleting the date is not possible, the input field will retain the value and the following date may remain invalid. This seems to be an issue with the JHipster date time picker. This is also the case for already existing date input fields in Artemis.

#### For consideration:
- Add server-side validation as well. The editing is only available for instructors, however.

### Steps for Testing
1. Open the "Create a new exam"-page and play around with the different dates, especially the lower three.
2. See if the input field get marked red and the "Save" button gets disabled.

### Screenshots
- #### Correct dates
   image
- #### Only release date of the results set
   image
- #### Wrong dates
   image

### CODE REVIEW

**Comment by alexmardale** [comment]
I was able to set the "End of Student Review" before "Release Date of Results" if "Begin of Student Review" was not set:
release_before_review_end
But I imagine this is something that wouldn't make much sense anyway.

So it seems that it is possible to set a date without setting the one before it.
You did mention in the description that the intention is to have it possible to leave the 3 dates at the bottom empty. But just wanted to check if being able to set a date without setting the one before it is alright/intended?

Otherwise, the ordering constraints described worked as expected!

**Comment by MaisiKoleni** [comment]
> I was able to set the "End of Student Review" before "Release Date of Results" if "Begin of Student Review" was not set:
> release_before_review_end
> But I imagine this is something that wouldn't make much sense anyway.
> 
> So it seems that it is possible to set a date without setting the one before it.
> You did mention in the description that the intention is to have it possible to leave the 3 dates at the bottom empty. But just wanted to check if being able to set a date without setting the one before it is alright/intended?
> 
> Otherwise, the ordering constraints described worked as expected!

Interesting, might have something to do with the "known issue" mentioned in the PR description. If I create an exam completely from scratch, I get:
image

The same is the case for another order, and if I enter a date in the middle and delete it again. How did you manage to do that? Maybe knowing the steps you did and browser helps. Is the save-Button at the bottom enabled as well?

What you found would then definitely be a bug.

**Comment by alexmardale** [comment]
> > I was able to set the "End of Student Review" before "Release Date of Results" if "Begin of Student Review" was not set:
> > release_before_review_end
> > But I imagine this is something that wouldn't make much sense anyway.
> > So it seems that it is possible to set a date without setting the one before it.
> > You did mention in the description that the intention is to have it possible to leave the 3 dates at the bottom empty. But just wanted to check if being able to set a date without setting the one before it is alright/intended?
> > Otherwise, the ordering constraints described worked as expected!
> 
> Interesting, might have something to do with the "known issue" mentioned in the PR description. If I create an exam completely from scratch, I get (both with Chromium and Firefox):
> image
> 
> The same is the case for another order, and if I enter a date in the middle and delete it again. How did you manage to do that? Maybe knowing the steps you did and browser helps. Is the save-Button at the bottom enabled as well?
> 
> What you found would then definitely be a bug.

So what I did was put in the first 4 dates correctly and then I put the 6th one, without putting the 5th one.
For the picture you shared, could you try to put the 6th date in the future? It seems that you cannot put a date in the past if the one before it is not set. But you can put it in the past if the one before it is set.

As another example for the future/past thing I just mentioned:
I put the first 3 dates 1 hour in the past.
I put the 5th date in the future and it was ok:


I then put the 5th date in the past and it turned red:



Then I put the 4th date in the past and before the 5th and the 5th was ok again:


(time when the pictures were taken was about 20:15)

**Comment by MaisiKoleni** [comment]
@alexmardale Thank you very much, I was able to reproduce it now. Very strange, that the current date/time makes the difference here. I will look into that. Likely, some similar code snippets in Artemis could be affected as well.

**Comment by MaisiKoleni** [comment]
For those interested, here is the reason: moment just uses now if it is used with undefined.

https://stackoverflow.com/questions/33002861/moment-of-undefined-vs-moment-of-null
and
https://github.com/moment/moment/issues/2697

**Comment by alexmardale** [comment]
I wasn't able to save the exam in an unintended state, so this was ok!

Although I did realise now that the same issue with moment and undefined might be present for the top row of dates.

**Example**
3rd date in the future, the rest of the dates empty:
aaa


3rd date in the past, the rest of the dates empty:
bbb

Would the fix for this simply be adding the same check for the other dates as well (except the first one, since it doesn't depend on another date)?

But the fact that the first 3 dates cannot be empty was, overall, not allowing me to save the exam in an unintended state.

**Comment by MaisiKoleni** [comment]
> But the fact that the first 3 dates cannot be empty was, overall, not allowing me to save the exam in an unintended state.

That was the reason why I didn't bother with it, but you are right, I can also happen for the dates there. We might want to take a closer look in general where such comparisons or validations are done because there are likely more (e.g. exercise creation). I would assume this is out of scope here, but might be worth creating a separate issue.

**Pull request merged**
