### PR TITLE
`General`: Improve header responsiveness for instructors

### PR DESCRIPTION
**Pull request by florian-glombik**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
The Manage Button taking the whole width of the windows when taking half of a 13,3 inch screen - which does not looked intended for me.
Also the separation between the `Show more` and the actual course description could be easier to spot.

### Description
- Always displaying the button to the right of the description and preventing the button to take the full screen width
- Adding arrows as indication of the expand / collapse direction

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Student

1. `instructor`: Edit the parameters of a course _(icon, description, title)_
2. `student` / `instructor`: verify that the header still looks fine, resize the window
3. Click "Show more" and see that the arrow direction changes

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### New Version
https://github.com/ls1intum/Artemis/assets/63976129/ea9cabbd-8c31-410b-8ce3-115369dbf45c

#### Old Version

https://github.com/ls1intum/Artemis/assets/63976129/fb229858-1847-4599-916d-d663619fec86

### CODE REVIEW

**Review by milljoniaer — COMMENTED** [review]
I like these Changes 👍 
Just one thing I recognized: 
The ellipsis is not in the end of each line. As far as i can see, this was also the case before. What do you think about adjusting the shortlength calculation, so that the ellipsis is always at the end of a line? 
But this can also be out of scope for this PR.

**Review by xHadie — CHANGES_REQUESTED** [review]
_Manually tested on TS3_Legacy_
Overall it looks much cleaner this way!

One regression I noticed:
- The title is not wrapping anymore if it is too long. This used to work. So responsiveness is breaking already for some tablet screen-sizes:
image

**Comment by florian-glombik** [comment]
The issue was that the title contained one really long word that was not wrapped. Thanks for investigating it @xHadie 🙏

**Review by xHadie — DISMISSED** [review]
LGTM now :🙂

**Review by milljoniaer — DISMISSED** [review]
LGTM 🥳

**Comment by florian-glombik** [comment]
I found an issue that is now resolved - when not setting the course description the manage button was not aligned to the right, which is now the case.

**Review by laurenzfb — APPROVED** [review]
Tested on Ts6. Header looks good fine when resizing. "Manage" button is on the right

**Review by mallgaier — APPROVED** [review]
Tested on TS1 together with @FiasKr in a testing session.
Working as expected. 
Good job!

**Review by LenaKahle — APPROVED** [review]
Tested on ts2, works as expected.

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy ts2. Worked as expected.

**Review by vinceclifford — APPROVED** [review]
Tested on legacy sever TS3 with Liam Berger. Everything works as intended.

**Review by Predixx — APPROVED** [review]
Tested on legacy ts3 with Vincent Clifford. Looks fine and works for me

**Comment by Ceiridge** [comment]
I and @MaximilianJG have tested it on test3 in a testing session. We have tested it in various display sizes and it works as expected. But at some small display resolution (see screenshots), the text and general UI starts to overflow. Maybe this is something that can be fixed in the future.

image
image
image
image
image

**Comment by MaximilianJG** [comment]
Tested in a testing session with @Ceiridge tested it on test3 in a testing session with an instructor and a student. We tested it with different display sizes and works perfectly. However, with very small displays the text overflows. See @Ceiridges screenshots!

**Pull request merged**
