### PR TITLE
`Lectures`: Fix PDF rendering issue in lecture units

### PR DESCRIPTION
**Pull request by eceeeren**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

1. Current PDF files are not rendering correctly as the Splitter class in PDFBox library does not render them correctly.

**It is:**
image

**Should be:**
image

2. This issue is mentioned on Apache PDFBox Issues page seems to be solved by version 3.0.2.

https://issues.apache.org/jira/browse/PDFBOX-5742

3. However Splitter class breaks down with version 3.0.2 again.

image

4. The fix for the second bug is fixed in version 3.0.3.

https://issues.apache.org/jira/browse/PDFBOX-5833

### Description

Apache PDFBox version made 3.0.3.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
5. Navigate to Course Administration
6. Click on Lectures and Create a Lecture
7. Check Unit Processing
8. Upload a PDF file with an Outline slide **(Important! -So that unit processing doesn't break down, this is fixed in another PR)**
9. Observe if the units are created
10. After saving click View and observe if all of the slides and images inside are rendered correctly

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

**Fixed Version**

image

## Summary by CodeRabbit

- **New Features**
	- Updated the `pdfbox` library to version `3.0.3`, which may include enhancements and bug fixes.

- **Chores**
	- Maintained existing configurations for plugins, repositories, and dependencies to ensure project stability.

### CODE REVIEW

**Review by HawKhiem — COMMENTED** [review]
I tested on server 6. I'm not entirely sure if it is an actual problem but there are some minor issues with the automatic unit processing, which I point out in details on the "artemistest" Slack channel. The pictures and slides are generated correctly!

**Review by HawKhiem — APPROVED** [review]
Tested on server 6. The images and slides are rendered correctly

**Review by sachmii — APPROVED** [review]
Tested on TS6 with PDF document containing outline slides (ITP 2023 first lecture slide). Units were created and all slides and images are rendered correctly.

**Review by az108 — APPROVED** [review]
Code 👍  and tested on TS6, works with the EIST Slides aswell

**Review by magaupp — APPROVED** [review]
Code is good :+1: 
Tested on TS6 with images from the linked issue. Split works without problems.

**Review by Strohgelaender — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
