### PR TITLE
`Quiz exercises`: Change the short answer quiz question editor to Monaco

### PR DESCRIPTION
**Pull request by pzdr7**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

We want to replace all usages of Ace within Artemis with Monaco. The short answer quiz question editor is one instance where the Ace editor is used (directly, in Markdown mode - though without any of the commands).

### Description

- Introduced the markdown editor for short answer quiz questions, including any supported actions.
- Added actions for inserting a spot & option in the short answer quiz question.
- Removed some superfluous newlines at the end of the short answer quiz question template

### Steps for Testing

> [!CAUTION]
> Due to a known issue (#9140), quiz questions containing a short answer quiz question will always be marked as having "Unsaved changes". This is not related to this PR.

Prerequisites:
- 1 Instructor

1. Edit or create a quiz exercise with a short answer question.
2. Try out the spot / option actions. In particular:
- Insert a spot without selecting any text. You should get a spot and an option with the correct spot number & selected default text.
- Select a word and then insert a spot. The spot should replace the text you originally selected and the inserted option should have the same number as the spot.
- Insert an option. You should always get the selected default text (spot number should be a placeholder \#).
3. Make sure the visual editor still works.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| short-answer-question-edit.component.ts | 95.47% | ✅ |
| markdown-editor-monaco.component.ts | 96.55% | ✅ |
| monaco-editor-action.model.ts | 92.72% | ✅ |
| monaco-insert-short-answer-option.action.ts | 100% | ✅ |
| monaco-insert-short-answer-spot.action.ts | 100% | ✅ |
| monaco-editor-option-preset.model.ts | 100% | ✅ |
| monaco-editor-option.helper.ts | 100% | ✅ |
| monaco-editor.component.ts | 95.72% | ✅ |

### Screenshots

image

## Summary by CodeRabbit

- **New Features**
	- Enhanced the Markdown editor with a more user-friendly interface and new editing functionalities.
	- Introduced new actions for inserting short answer options and spots within the editor.
	- Added configurable option presets for the Markdown editor.

- **Bug Fixes**
	- Improved conditional rendering for editor buttons, enhancing dynamic user interface responsiveness.

- **Tests**
	- Expanded test coverage for the new editor functionalities and interactions with short answer questions.

### CODE REVIEW

**Review by BBesrour — APPROVED** [review]
Tested on TS1. works as described. Visual editor also works fine.

**Review by egekurt123 — APPROVED** [review]
Works as expected on TS2.

**Review by JohannesStoehr — DISMISSED** [review]
Code

**Review by SimonEntholzer — APPROVED** [review]
code

**Review by Jan-Thurner — APPROVED** [review]
Tested on TS2. Works as described:

Insert a spot without selecting any text ✅ 
Select a word and then insert a spot ✅ 
Insert an option ✅

**Review by JohannesStoehr — APPROVED** [review]
Reapprove code after merge

**Review by SimonEntholzer — APPROVED** [review]
re-approve code after resolving the merge conflicts

**Pull request merged**
