### PR TITLE
`General`: Disable loading buttons

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.

### Motivation and Context

In some edge cases a button could be pressed multiple times which lead to some bugs in Artemis. E.g. pressing "Start exercise" for a programming exercise could lead to multiple submissions.

### Description

A button with a loading animation is now also automatically disabled.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise

1. Log in to Artemis
2. Try to start the exercise multiple times by spamming "Start exercise" (an auto clicker might help here)
3. Check if the submissions are only registered once. This can be done in two ways:
- Go to the repository and check the settings on the left side. The "Weebhooks" tab should only contain one web hook
- Submit something as a student and check the amount of submissions in the participation overview of the exercise

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by krusche — APPROVED** [review]

**Comment by krusche** [comment]
Change looks good to me 👍

**Review by ge65cer — COMMENTED** [review]
Good solution. 🙂  It only partially fixes the issue though, as clicking on “Start exercise” on the Course tab, then repeatedly clicking “Start exercise” for another exercise still works (even while loading/in disabled state) & shows error messages.

**Review by alaraozdenler — APPROVED** [review]
Tested on ts2, submission is only registered once. One thing to add: Pressing the Start exercise button on the Course overview page and again on the Exercise overview page back to back leads to the following warning: 
image

But it resolves very quickly and lets you start the exercise almost immediately.

**Review by ge65cer — APPROVED** [review]
Can not reproduce my previous report anymore… maybe something with caching. If anything, this PR didn't introduce the issue but rather works towards solving it, so we should merge it. 👍

**Review by Dominik-Weinzierl — APPROVED** [review]
Looks good to me :+1: that should solve the mentioned issue :+1:

**Review by nairaarnez — APPROVED** [review]
I got a similar warning as @alaraozdenler  and an internal server error, but the submission was registered as expected, only once (Just one web hook).
image

**Review by bassner — APPROVED** [review]
I've spammed a "Start exercise" button with an auto clicker app 100 times per second. The repository only contained one webhook afterwards.
Code looks good 👍

**Pull request merged**
