### PR TITLE
`Programming exercises`: Fix client validation when creating exercises for certain languages

### PR DESCRIPTION
**Pull request by ole-ve**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
This PR addresses #4593 and should already been fixed in #4526. Programming exercises with certain languages could not be created as those had no package name set, even if this is irrelevant for creating and cannot be set in the form for these languages.

### Description
The package name is only checked for programming languages that require a package name (Java, Kotlin, Swift).

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Management
3. Click the button to create a new programming exercise
4. Test all programming languages and verify that all exercises can be created. Validation errors for package names for languages Java, Swift and Kotlin should still be displayed.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by b-fein — APPROVED** [review]
Code review: the changes make sense.

Closely related, possibly out-of-scope here: The `getInvalidReasons` method is quite large. I think that refactoring it into a few smaller methods like `validateExerciseTitle(validationErrorReasons: ValidationReason[]): void`, `validateExerciseShortName(…)`, `validateExerciseMaxPoints(…)`, `validateBonusPoints(…)`, `validatePackageName(…)`, … would make sense.

**Review by b-fein — APPROVED** [review]
Code review: thanks for refactoring the large method in this PR, too. Looks good! :+1:

**Review by valeriebucher — APPROVED** [review]
Worked as expected for every programming language. Also for Java, Kotlin and Swift the package name is included.

**Review by Santia-go — APPROVED** [review]
Tested in TS1 
Working as expected. 
All programming exercises in different languages can be created and the validation errors for package names of Java, Swift, and Kotlin exercises are displayed.

**Review by Hialus — DISMISSED** [review]
Code changed look good.
The split up into multiple methods definitely improves the readability.
Approve 👍🏻

**Review by baranimo7 — APPROVED** [review]
tested on ts2. Creating works as expected and Validation errors are shown correctly.

**Pull request merged**
