### PR TITLE
Feature: Provide multiple templates for a programming language

### PR DESCRIPTION
**Pull request by sleiss**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
Currently, there can only be one template per programming exercise. For Java, often two exercise types are used: Eclipse projects and Maven projects. Instructors currently have to manually adjust the exercise if they want to use Maven exercises.
See #2062.

### Description
This PR adds an attribute `projectType` to the Programming Exercises, defaulting to `null`. Each programming language has a base template (consisting of the already present folder `exercise`, `solution`, `tests`, which can be extended by project-specific files (e.g. `pom.xml` or `.project` files). The selection is not shown if there is only one template for this programming language.

The Project Type can not be changed after creating the exercise as the repositories are setup with the selected option during exercise creation.

### Steps for Testing
1. Create a new programming exercise
2. See the new selection for the project type when select Java as programming language.
3. See the difference in the loaded README when selecting Maven instead of Eclipse
4. Create one project using Maven and one using Eclipse.
- The eclipse project should be identical to the previous template.
- The maven project should be identical except that 1) a pom.xml file is generated for student instead of `.classpath` and `.project` file. 2) The `Client` class uses a method from Apache RandomUtils.
5. Import both exercises into eclipse (one as eclipse project and one as maven project), you should be able to run the `main` method in the `Client` class.
6. Create another non-Java Programming exercise: The project type selection should not be present but you should still be able to create the exercise using the default template.

### Test Coverage

* ExerciseService.java: 85%
* programming-exercise.component.ts 95%

### Screenshots
Peek 2020-10-26 18-03

### CODE REVIEW

**Review by tiffca — DISMISSED** [review]
All steps for testing passed successfully (test server 1)! Nice job! 

There is a difference between the main output between eclipse/maven project, but this was mentioned in the steps (the randomutils).

**Review by FrankeLukas — DISMISSED** [review]
Lgtm. One thing I noticed though is that `pom.xml` is showing in the online editor:
grafik
Is there a way to hide it? I don't think students should edit that file. (That can also be done in a follow-up PR if we don't want to block this one, imho.)

**Comment by sleiss** [comment]
> Lgtm. One thing I noticed though is that `pom.xml` is showing in the online editor:
> grafik
> Is there a way to hide it? I don't think students should edit that file. (That can also be done in a follow-up PR if we don't want to block this one, imho.)

@FrankeLukas Thanks for testing! Actually, I believe we had some exercises were students were supposed to edit the `pom.xml`file. Most of the maven exercises, at least in my expectation, won't provide an online-editor so there probably are few cases were that file is shown to the student in the code editor. The students should solve these programming exercises in their IDE (and there we obviously also can't hide these files).

Technically it would be possible to hide all `.xml` files, but I don't know if that breaks other programming languages that might rely on `.xml` files.

So I would propose that we leave this as it is currently.

**Comment by FrankeLukas** [comment]
Ok, that sounds reasonable. :+1:

**Review by krusche — APPROVED** [review]

**Pull request merged**
