### PR TITLE
`Quiz exercises`: Render images immediately upon import

### PR DESCRIPTION
**Pull request by EneaGore**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
~- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).~
~- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).~
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
~- [ ] I translated all newly inserted strings into English and German.~

### Motivation and Context

When importing quiz Exercises at the moment (json,zip or any other import from within the quiz editor). The images (most of the time ) do not show unless the quiz is saved. This PR fixes that by creating Preview paths for the imported images.

### Description

This happened because the import functions make duplicates of the imported image/exercise but did not update the file preview paths and they do not show until they are uploaded in the server and retrieved. This PR creates the file preview Paths directly on import so the user does not have to save them to see them. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Quiz

1. Log in to Artemis
2. Navigate to Course Administration
3. Import any other quiz with Drag and Drop question. 
4. Confirm the images immediatly and correctly displayed.

#### Exam Mode Testing

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Before:
beforeTheFix
After:
afterTheFix

## Summary by CodeRabbit

- **New Features**
	- Enhanced drag-and-drop question editing interface with immediate visual feedback for imported images.
	- Introduced a method for generating previews of uploaded files, improving user interaction.

- **Bug Fixes**
	- Improved variable scoping for question index, ensuring better reliability within the quiz question editing component.

- **Style**
	- Minor formatting adjustments made for improved code readability.

### CODE REVIEW

**Review by edkaya — APPROVED** [review]
code

**Review by N0W0RK — APPROVED** [review]
Code 👍

**Review by SimonEntholzer — APPROVED** [review]
Code looks good, and tested on ts2 :+1: Works now, images show up when imported without, saving the quiz first

**Review by BBesrour — APPROVED** [review]
Tested on TS2, works as described

**Pull request merged**
