### PR TITLE
Feature/lazy loading

### PR DESCRIPTION
**Pull request by krusche**
This PR activates lazy loading for a couple more modules to reduce the initial bundle size from around 2.5 MB to 1.5 MB. This forces improvements in the module structure and reduces the coupling between components.

The PR includes some minor additional changes.

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

**It is important to test whether the navigation to ALL pages works, so I would kindly ask everyone to help**

### Steps for Testing
1. Log in to Artemis
2. Navigate to any Artemis page and check if it works as expected

Fokus on:
- Code Editor and Markdown Editor
- Participation and submission for all exercise types
- Course Management

### CODE REVIEW

**Comment by clemenszuck** [comment]
I tested the following functionalities on Artemis Test Server 1:
- Course Management:
    - Create/edit/delete exercises/lectures/courses
    - general page navigation
- Submission and Participation 
    - File Upload exercises
    - Text exercises
    - Modeling exercises

I found the following issues: 
- When creating exercises (of any type) and clicking the 'Save' button, you are not redirected back to the overview page. The exercise is created and the green notification shows up at the top of the page, but you have to scroll up manually to the top or navigate to the overview again to see it.

- Submitting to a File Upload exercise: 
When trying to upload a file to a File Upload exercise
upload-file

nothing happens and the following exception occurs
file-upload-exception

I tested it locally without the changes to make sure the issues are related to them.

**Comment by alextsakpinis** [comment]
After creating a new course I clicked on Create a new File Upload Exercise. The I wanted to exit this view by pressing the cancel button and got the following error.

image

**Comment by alextsakpinis** [comment]
Saving a modeling exercise does not work. Same error.
image

**Comment by alextsakpinis** [comment]
Clicking on the course link of the lecture view throws the following error

image

**Comment by krusche** [comment]
@alextsakpinis @clemenszuck Thanks for testing. I could only reproduce the issue with save and cancel for file upload and modeling exercises. Text, programming and quiz should be fine. They all now use `window.history.back();` consistently after canceling or when save was successful, except quizzes which have a different logic

**Comment by madwau** [comment]
> @alextsakpinis @clemenszuck Thanks for testing. I could only reproduce the issue with save and cancel for file upload and modeling exercises. Text, programming and quiz should be fine. They all now use `window.history.back();` consistently after canceling or when save was successful, except quizzes which have a different logic

Text exercises were using the same logic and still had the old route. I changed it to match the approach you chose for the other two.

**Comment by madwau** [comment]
> Clicking on the course link of the lecture view throws the following error
> 
> image

Fixed.

**Comment by krusche** [comment]
I fixed the remaining issues (also found two more small other issues)
Thanks also to @madwau for helping out

**Comment by madwau** [comment]
Found another small issue: When clicking on the "Team" button as a student to view their team, rendering the datatable fails since the dependency `SortByPipe` is not injected. I'll fix it.

**Comment by madwau** [comment]
The complaints links on the tutor course dashboard have wrong rputes.

**Pull request merged**
