### PR TITLE
`Exam mode`: Hide unreleased programming exercise results

### PR DESCRIPTION
**Pull request by pzdr7**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Currently, students can see the current result of their programming exercise submissions before the result release date. We do not want to leak this information.

### Description

The repository view, the commit history, and the exam summary no longer receive information about the results of exam programming exercises when the results haven't been published yet. Students can still see the results if:

- The exam is ongoing.
- The results have been published.

Note that this is meant as a quick fix for the bug described above. In the future, we want to show the results that were created during the exam in the repo view / commit history.

#### Exam Mode Testing

Prerequisites:
- 1 Exam with a programming exercise (enable manual assessment). Enable both the online editor and the offline IDE.
- 1 Student
- 1 Instructor
- Two browsers / incognito mode (one for the student, one for the instructor)

1. Participate in the exam as the student. Submit a few solutions to the programming exercise (e.g. some with build errors, some without)
2. Open the repository view via the Code button popup image.
3. Verify that the displayed result is the most recent one.
4. Open the commit history view.
5. Verify that the commit history shows every result.
6. Wait for the exam to end and hand in normally.
7. Check that the summary you see works as expected.
8. Open the repository view via the code button. Check that no result is displayed.
9. Open the commit history view. Check that no results are displayed.

----

10. On the other browser, log in as the instructor.
11. Assess the programming exercise.
12. As the student: Check that you still cannot see the result of the programming exercise on the summary, the repository view, or the commit history.
13. As the instructor: Edit the exam; set the release date of the results to now.
14. As the student: Check that you can see every result again on the summary, repository view, and commit history.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Screenshots

No ui changes

## Summary by CodeRabbit

- **New Features**
	- Introduced logic to determine if students can see their exam results based on specific conditions.
	- Enhanced access control for programming exercise participations in exam contexts.

- **Improvements**
	- Streamlined result visibility checks, improving clarity and maintainability.
	- Improved accuracy of determining working period status for individual exams.

### CODE REVIEW

**Review by JohannesStoehr — DISMISSED** [review]
Code looks good and should fix the leakage. Looking forward to the improved filtering in a follow up pr :+1:

**Review by SimonEntholzer — APPROVED** [review]
Code looks good, and fix works on TS3 :+1:

**Review by florian-glombik — DISMISSED** [review]
Approve code, I will add a manual test soon

**Review by Strohgelaender — COMMENTED** [review]
I found an edge case during testing. In case like this where trigger all gets used to run hidden tests after the deadline:
grafik

I was able to see the 25% result on the repository view page, but it was gone after reloading. I'm not completly shure how I triggerd that, it might be the case that this result was send via websocket enven though it should not.

This is an edge case when you have the page open for a long time (maybe opend it during the exam and then looking at it later agin) and the usual behaviour of just opening the page at some later point does not have this problem, so feel free to fix this at a later point.

**Review by coolchock — APPROVED** [review]
tested on ts3, no issues found

**Review by florian-glombik — APPROVED** [review]
Approve code and tested on ts3

* tested with a user with team extension and one without
* was not released for student without time extension after while the time extension student was still writing the exam
* was not released after the time extension student finished participating
* was released after results release date was passed

**Review by MaximilianAnzinger — APPROVED** [review]
Code

**Review by SimonEntholzer — APPROVED** [review]
Re-approve

**Review by Strohgelaender — APPROVED** [review]
Code lgtm.

I'd love to see some server tests in a followup.

**Review by JohannesStoehr — APPROVED** [review]
Code

**Pull request merged**
