### PR TITLE
`Lectures`: Allow comma-separated keyphrases for automatic slide removal during unit processing

### PR DESCRIPTION
**Pull request by nityanandaz**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server

- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

#### Client

- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Fix issue: #7039 / https://github.com/ls1intum/Artemis/issues/7039#issuecomment-1688489883

### Description

- Merge both input text fields into one.
- Send the comma-separated list with the DTO
- Check the input value in `LectureUnitProcessingService` and remove slides.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Edit or create a new lecture
3. Select _Automatic unit processing_
4. Upload a prepared slide deck
5. Click _Process units_
7. Type in the list of comma-separated key phrases
8. Submit

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance

#### Code Review

- [x] Code Review 1
- [x] Code Review 2

#### Manual Tests

- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [attachment-units.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5302/latest/artifact/shared/Coverage-Report-Client-Tests/app/lecture/lecture-unit/lecture-unit-management/attachment-units/attachment-units.component.ts.html) | 89.13% | ✅  |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [LectureUnitProcessingService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5302/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/LectureUnitProcessingService.html) | 97% | ✅  |

### Screenshots
Screenshot 2023-08-22 at 17 56 46
Screenshot 2023-08-22 at 17 56 55

### CODE REVIEW

**Comment by Strohgelaender** [comment]
The remove solution slides feature is currently seemingly duplicated on purpose. In the future, these slides should not just get removed, but hidden. Instructors should have the ability to re-add them again at a later point. I'd suggest for now to just leave this solution slide functionality like it is and only add the manual keyboard to the slide-removal feature.

**Comment by nityanandaz** [comment]
@Strohgelaender What is duplicated? https://github.com/ls1intum/Artemis/pull/7060 was implemented and merged, but I got feedback to change the input to a comma-separated list.

> only add the manual keyboard to the slide-removal feature

You mean implement just the comma-separated list? That was the intention :)

**Review by terlan98 — COMMENTED** [review]
Tested on TS5. Got the following error when attempting to upload a slide deck for automatic unit processing.
Screenshot 2023-08-31 at 10 40 36
`{"type":"https://www.jhipster.tech/problem/problem-with-message","title":"Internal Server Error","status":500,"detail":"Index 4 out of bounds for length 4","path":"/api/lectures/8/process-units","message":"error.http.500"}`

I used the following pdf:
[Presentation1.pdf](https://github.com/ls1intum/Artemis/files/12483159/Presentation1.pdf)

**Comment by nityanandaz** [comment]
@terlan98 It is throwing here https://github.com/ls1intum/Artemis/blob/feb6b757bddf04269bb84feed763f5a7e04efc69/src/main/java/de/tum/in/www1/artemis/service/LectureUnitProcessingService.java#L191

I does not call my code, but I will see what I can do

**Review by MaximilianAnzinger — APPROVED** [review]
Tested on TS3 during testing session, works as described 👍

**Review by basak-akan — APPROVED** [review]
Tested on ts3, during the testing session works as described.

**Review by lennart-keller — APPROVED** [review]
Tested in testing session, worked well.

**Review by JohannesStoehr — APPROVED** [review]
Thanks for incorporating my suggestion from your last PR.
Approve code changes.

**Review by terlan98 — APPROVED** [review]
Tested on TS5. Works as expected. 

I found one issue but it can be fixed on a separate PR:
- When the keyphrase is a word that is contained in every slide, such as a word from the footer (see below), the generated unit PDFs are corrupted:
Screenshot 2023-08-31 at 17 54 03
Screenshot 2023-08-31 at 17 55 46

**Comment by nityanandaz** [comment]
> * When the keyphrase is a word that is contained in every slide, such as a word from the footer (see below), the generated unit PDFs are corrupted:

My guess is that the result has 0 pages,

**Pull request merged**
