### PR TITLE
`Adaptive learning`: Enable learning paths per default

### PR DESCRIPTION
**Pull request by MaximilianAnzinger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

With #7684 we add the documentation of learning paths in Artemis. Therefore, we can now enable the feature per default on server start-up.

### Description

Enables feature toggle for learning paths per default.

### Steps for Testing

Prerequisites:
- 1 Admin

1. Log in to Artemis
2. Navigate to Server Administration > Feature toggles
3. Make sure the Learning Path feature toggle is enabled

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

unchanged

### CODE REVIEW

**Review by tobias-lippert — DISMISSED** [review]
Code LGTM

**Comment by Strohgelaender** [comment]
Seems like the `FeatureToggleServiceTest` is currently failing, did you miss another part where learning paths need to be enabled?

**Review by LenaKahle — APPROVED** [review]
Approve, tested on ts3.

**Review by valentin-boehm — DISMISSED** [review]
Tested locally, works as expected

**Review by JohannesStoehr — DISMISSED** [review]

**Review by JohannesStoehr — APPROVED** [review]
Approve after test fix

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts2. Worked as expected.

**Comment by MaximilianAnzinger** [comment]
@Strohgelaender thx for pointing this out. In fact, the `LearningPathIntegrationTest` en/disables the feature toggle for testing. That caused the issues. 👍

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts2. Worked as expected!

**Review by AntonGeTUM — APPROVED** [review]
Manually tested, worked as described.

**Review by LenaKahle — APPROVED** [review]
Reapprove, retested on legacy ts2.

**Review by xHadie — APPROVED** [review]
_Tested on TS3_
Works as you described!

**Comment by MaximilianJG** [comment]
Tested on Artemis TS6. LGTM! 

Screenshot 2023-11-29 at 14 48 22

**Review by Strohgelaender — APPROVED** [review]
code

**Review by vinceclifford — APPROVED** [review]
Tested on TS2, works as expected

**Review by Predixx — COMMENTED** [review]
Tested together with Vincent Clifford. Looks good

**Review by Predixx — APPROVED** [review]
Tested together with Vincent Clifford. Looks good

**Pull request merged**
