### PR TITLE
`Development`: Refactor course registration

### PR DESCRIPTION
**Pull request by filip-gregurevic**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

This is a follow-up PR to https://github.com/ls1intum/Artemis/pull/4353, in which the course registration was moved into its own page in order to improve the initial bundle size. Some good suggestions were made on how to improve the code quality of this component and they are addressed here.

### Description

Layout and styling of the courses list is improved. Error and success messages are now displayed using the alert service. The Courses, for which a student can register, are now fetched directly in one API call instead of two.

### Steps for Testing

Prerequisites:
- 1 Students
- At least one course for which the stundet can register

1. Log in to Artemis
2. Navigate to Course Registration
3. Check that the correct registrable courses are displayed
4. Register for the course
5. Check that the registration still works as expected and the student is registered for the course (e.g. it's displayed on the landing page)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

course-registration.component.ts: 52% | 94% (relatively low branch coverage is due to one generic error handling case not being covered)

### Screenshots

Bildschirmfoto 2021-12-20 um 15 23 00

### CODE REVIEW

**Review by Malyuk-A — APPROVED** [review]
Tested on TS3. Works with no issues for me (I could register to courses, I could see the corresponding alerts, and the courses which I was already registered to were filtered out as expected), there were also no console errors. The code changes look reasonable too.

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on ts1 and works as expected

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on ts1 and works as expected

**Review by baranimo7 — APPROVED** [review]
Tested on TS1, works as expected

**Pull request merged**
