### PR TITLE
`Development`: Improve error handling when sending emails fails

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
If one email fails, the remaining ones should still work so that all other users get the important information in an announcement

### Description
Improve error handling in MailService

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students registered in the course

1. Send an announcement and make sure all students in the course receive it

#### Performance Review
good performance
#### Code Review
- [x] Code Review 1
#### Manual Tests
- [x] Test 1

### CODE REVIEW

**Review by Strohgelaender — DISMISSED** [review]
code lgtm

**Review by coolchock — DISMISSED** [review]
tested on ts2, I received an email on my TUM mail. @pzdr7 also confirmed receiving an email. However, there's one test failing.

**Review by pzdr7 — DISMISSED** [review]
Tested on TS3. Received @coolchock's announcement email + created an announcement, which he received 👍

**Review by Strohgelaender — DISMISSED** [review]

**Review by coolchock — DISMISSED** [review]
re-approve

**Review by az108 — COMMENTED** [review]
Tested it on test server 3 and got the email and everything works as expected!

**Comment by marlon-luca-bu** [comment]
ah wow, didnt see that it is already merged and tried to deploy an already deleted branch 🥲 sorry for that.

**Pull request merged**
