### PR TITLE
`Quiz exercises`: Fix visual selection when multiple short answer question exists

### PR DESCRIPTION
**Pull request by rriyaldhi**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Adding spot through visual mode does not work if there are multiple short answer questions in 1 quiz exercise.

https://user-images.githubusercontent.com/10885503/209796414-f905d4d0-8adb-40c8-a406-44957787ae9d.mov

### Description

The id of the short answer questions is the same for all questions. The element that is referenced by the id is used to determine which question is being selected when adding a spot through visual mode. Changing the id to use angular reference solves the issue.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course
- 1 Quiz Exercise with multiple short answer questions

1. Log in to Artemis
2. Navigate to Course Administration
3. Select the Course
4. Navigate to Exercises
5. Select the Exercise
6. Click Visual on the first short answer question
7. Highlight the word and click Add Spot. (Verify that it works)
8. Click Visual on the second short answer question
9. Highlight the word and click Add Spot. (Verify that it still works)

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| short-answer-question-edit.component.ts | 70.32% | 93.81% |

### Screenshots

https://user-images.githubusercontent.com/10885503/209792501-392dee24-41a9-4526-89e4-24dbcdd55429.mov

### CODE REVIEW

**Review by tunargs — APPROVED** [review]
Tested on ts1 with 2 short-answer questions, works as expected

**Review by LiaLism — APPROVED** [review]
Short answer questions work as expected. Tested on ts1.

**Review by laadvo — APPROVED** [review]
Visual selection is now possible with multiple short answer questions, tested on ts1.
This is not related to the PR but I couldn't really figure out how to delete a spot after it has been added. Is there an option to do that in visual mode?

**Comment by rriyaldhi** [comment]
> Visual selection is now possible with multiple short answer questions, tested on ts1.
> This is not related to the PR but I couldn't really figure out how to delete a spot after it has been added. Is there an option to do that in visual mode?

Unfortunately, deleting spots can only be done in text mode when creating/editing a quiz exercise.

**Comment by laadvo** [comment]
> > Visual selection is now possible with multiple short answer questions, tested on ts1.
> > This is not related to the PR but I couldn't really figure out how to delete a spot after it has been added. Is there an option to do that in visual mode?
> 
> Unfortunately, deleting spots can only be done in text mode when creating/editing a quiz exercise.

Ok, thanks for clarifying!

**Review by Santia-go — APPROVED** [review]
Tested on TS1 
Working as expected

**Pull request merged**
