### PR TITLE
Add buttons to Programming Exercises Details Page

### LINKED ISSUE #2468: Show additional instructor buttons on the Programming Exercise Details page
Would be nice if we can show some additional buttons here such as Edit in Editor, Scores, Participations, etc.
Currently, we are limited to Edit and a few custom actions.

I also suggest we move all buttons to the top of the page.
Then, I don't need to navigate back into the overview and have to search again for the correct exercise.

image

We could remove the back button instead.

### PR DESCRIPTION
**Pull request by nutatuna**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
Resolves #2468 

### Description
I keep the existing buttons (except the back button) and add all possible buttons that are related to programming exercise to the page. I moved all the buttons to the top of the page.

### Steps for Testing
1. Go to a Programming Exercise Detail page (For Example: Course management -> Exercises -> Details )
2. Check that all the buttons in the page still working.

### Screenshots

Old:

Capture
Capture

New:

Capture

### CODE REVIEW

**Review by nicolasruscher — APPROVED** [review]
Testet all the buttons, they are shown at the top + work as expected.

**Review by airelawaleria — APPROVED** [review]
Everything works

**Review by JohannesWeiss — APPROVED** [review]
Nice feature! 👍 
Works as expected on ts1.

**Review by DenizShabani — APPROVED** [review]
Tested and works completely fine.

**Review by derLalla — APPROVED** [review]
this looks nice! And everything works as usual. Good work :)

**Review by simonzilker — APPROVED** [review]
All buttons work!

**Review by EneaGore — APPROVED** [review]
All buttons still work

**Review by marvinchimeka — APPROVED** [review]
Tested the functionality of the buttons on the Programming Exercise Detail Page on ts1. Worked fine.

**Review by tiffca — APPROVED** [review]
Buttons all worked fine. 

Noticed the bread crumb navigation does not navigate back to the programming exercise for the following buttons: 
- scores, participations, hints
To reproduce: click on scores, then try to click on the programming exercise number to navigate back to the programming exercise. Expected: should navigate back to the programming exercise. Actual: stays on the same page 
.

**Pull request merged**
