### PR TITLE
`Exam mode`: Fix rendering of the tests status in the exam summary

### PR DESCRIPTION
**Pull request by coolchock**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

In the testing session for 7.0.0 we have noticed that the tests step wizard doesn't display the correct result in the exam summary. This pull requests fixes this problem.

### Description

The problem was that exercise's templateParticipation was used instead of student's individual participation.

#### Exam Mode Testing

Prerequisites:
- 1 Students
- 1 Exam with a Programming Exercise

There's already an exam in 'Test Course Michal Kawka' called 'step-wizard' on TS2. Test users 1-5 are registered. 

1. Log in to Artemis
2. Participate in an exam and make some tests of the programming exercise pass.
3. Submit exam
4. Verify that test results are displayed correctly.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **Bug Fixes**
	- Updated the data binding in the programming exam summary to ensure accurate display of participation details.

### CODE REVIEW

**Review by pzdr7 — APPROVED** [review]
Tested on TS2; works as expected.

**Review by julian-christl — APPROVED** [review]
After extensive consideration and research, I can confirm that water is indeed a fluid.

The change looks good as well!

**Review by egekurt123 — APPROVED** [review]
Tested on ts2 during testing session, works as expected

**Review by BaumiCoder — APPROVED** [review]
Testing in the Exam (Testing session)

**Pull request merged**
