### PR TITLE
Refactor Client Side Service Tests for programming-exercise.service.ts

### PR DESCRIPTION
**Pull request by lschlesinger**
### Motivation and Context
Replaces `async` with `fakeAsync` for `programming-exercise.service.spec.ts`

### CODE REVIEW

**Review by FuchsDominik — COMMENTED** [review]
Could you adapt the `.toMatchObject()` as well, what this method does is check the values of an object, but if this object has nested objects, these are not checked anymore. I think we normally use the sinon.expect().to.deep.equal() which checks the object recursively, but other non-sinon methods might work as well

**Comment by lschlesinger** [comment]
> Could you adapt the `.toMatchObject()` as well, what this method does is check the values of an object, but if this object has nested objects, these are not checked anymore. I think we normally use the sinon.expect().to.deep.equal() which checks the object recursively, but other non-sinon methods might work as well

I changed it in cffcb66 and thereby switched to sinon for the whole file :)

**Review by FuchsDominik — APPROVED** [review]
Looks good I would say :)

**Review by Olimbia23 — APPROVED** [review]
Async problem fixed 👍

**Review by krusche — APPROVED** [review]

**Pull request merged**
