### PR TITLE
Enhance code editor status display

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
Related to https://github.com/ls1intum/Artemis/issues/1854

### Description
Every time files in the code editor change, the status will switch to 'unsaved' and 'unsubmitted'.

### Steps for Testing

**Please test this thoroughly. Code editor state changes can be tricky**
1. Conduct an exam with multiple programming exercises
2. Make sure all actions and state behave as intended

### Screenshots

codeEditor2

### CODE REVIEW

**Comment by schultek** [comment]
After Reloading on an unsubmitted exercise, the navigation bar shows the correct icon, but the wrong tooltip (and color?).
ezgif com-video-to-gif (1)

**Comment by schultek** [comment]
When clicking Submit with unsaved changes, the files seems to get saved and submitted. But after clicking refresh files the commit status is still 'unsubmitted'. (It's back to submitted when reloading, also the build gets triggered so it seems to be just a display bug.)
ezgif com-video-to-gif (2)

**Comment by kloessst** [comment]
Was the nav-bar issue introduced by these changes?
Whats the intended behavior of Refresh Files. Should the state afterwards always be saved and submitted?

**Comment by kloessst** [comment]
I analyzed this. This gets executed on refresh and returns the 'false' state:
```
this.checkIfRepositoryIsClean()
            .pipe(
                tap((commitState) => {
                    this.commitState = commitState;
                }),
```
As I can only reproduce this if I don't wait for the commit to 'settle' I think this is some sort of race condition. Where the code above sets UNCOMITTED_CHANGES after the commit() call updates the state. I don't have a clean solution for this. We should probably just make all buttons unspammable locking them for a few seconds after they have been activated.

**Comment by anditurdiu** [comment]
> After Reloading on an unsubmitted exercise, the navigation bar shows the correct icon, but the wrong tooltip (and color?).
> ezgif com-video-to-gif (1)

To my knowledge, all navigation bar icons are set the wrong status if you reload the page. This is a known issue and there is no easy fix for this as the flags are set to their initial state when the component is reset. When you switch to another exercise and then return it should show up correctly again

**Comment by kloessst** [comment]
EIST test exam was written with the original status behavior. At this point it is too risky to change the status behavior.

**Pull request closed without merging**
