### PR TITLE
[bugfix] unchecked call to code editor

### PR DESCRIPTION
**Pull request by MDK5**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context
Solves Orion's [#49](https://github.com/ls1intum/Orion/issues/49)

### Description
Before leaving the code editor view it is ensured the editor does not have unsaved changes. The Orion variation of that view does not have a code editor, crashing the check and causing the mentioned issue

### Steps for Testing
Either alternative suffices!

#### With a browser:
1. Log in to Artemis as Editor or above
2. Locate or create a programming exercise
3. Click on "Edit in Editor"
4. Adapt the URL ending with /code-editor/_id_ to /code-editor/ide/_id_ to access Orion's view
5. "Course Management", "Course Overview" and the breadcrumbs should work as expected with no errors thrown
6. The selector and the Orion buttons won't work (your browser is no Orion) but should fail with "l().orionVCSConnector is undefined" and not the previous error

#### With Orion
1. Make sure not to use ts3 since ts3's vcs does not work
2. Run Orion
3. Adapt Intellij Settings -> Tools -> Orion -> Artemis URL to point to the test server you're using
4. Log in as instructor
5. Locate or create a programming exercise
6. Click on "Edit with Orion" from the instructor's exercise view (right side of the table, might require scrolling)
7. Load the exercise as Instructor
8. The selector and submit button should work, test locally is currently broken, that's adressed in Orion's [#46](https://github.com/ls1intum/Orion/pull/46)
9. The other buttons should also work, be aware though there is currently no way to navigate back, that will be adressed in Orion's [#45](https://github.com/ls1intum/Orion/pull/45)

### Test Coverage
Unchanged

### Screenshots
Refer to the linked issue

### CODE REVIEW

**Review by FuchsDominik — COMMENTED** [review]
Code looks fine, I am just wondering about all the failed client style checks. Do you know why those error occur?

**Review by FuchsDominik — APPROVED** [review]
Seems unrelated to your PR

**Comment by MDK5** [comment]
> 
> 
> Code looks fine, I am just wondering about all the failed client style checks. Do you know why those error occur?

I cannot tell. The code complained about is years old; Theres a total of 500 errors found so definitely not related to code changes. My best guess is this is due to https://github.com/ls1intum/Artemis/commit/b123a3575f44fae3f924f51af90714316c07e5ce#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R104 where the eslint version was increased

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Breadcrumbs work.

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 1. Everything worked as expected.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS1. Breadcrumbs work.

**Review by canyelten — APPROVED** [review]
Tested on TS1. Works as expected.

**Pull request merged**
