### PR TITLE
`General`: Add event logging for lecture units and exercises

### PR DESCRIPTION
**Pull request by MaximilianAnzinger**
> [!WARNING]
> **This PR is stacked on #7680 ! Do not merge this PR!**
> **Do only test on TS1!**

#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

See #7680 .

### Description

Adds event logging for all types of lecture units and exercises.

### Steps for Testing

Prerequisites:
- 1 User (who didn't opt out of the science feature > see user settings)
- 1 Lecture Unit of each type (excluding Exercise Unit)
- 1 Exercise of each type

1. For each lecture unit type (Video, Text, Online, Attachment/File):
- View the video / view the text / click the link / download the file
- make sure that the database table contains an entry with matching user, time, type (`LECTURE__OPEN_UNIT`= index 1) and resource id (id of the lecture unit)
2. For each exercise type (Programming, Quiz, Text, Model, File):
- View the exercise
- make sure that the database table contains an entry with matching user, time, type (`EXERCISE__OPEN` = index 2) and resource id (id of the exercise)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [attachment-unit.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6032/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-lectures/attachment-unit/attachment-unit.component.ts.html) | 78.26% | ✅ |
| [online-unit.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6032/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-lectures/online-unit/online-unit.component.ts.html) | 96.66% | ✅ |
| [text-unit.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6032/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-lectures/text-unit/text-unit.component.ts.html) | 100% | ✅ |
| [video-unit.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6032/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-lectures/video-unit/video-unit.component.ts.html) | 93.54% | ✅ |
| [course-exercise-details.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6032/latest/artifact/shared/Coverage-Report-Client-Tests/app/overview/exercise-details/course-exercise-details.component.ts.html) | 86.69% | ✅ |
| [science.model.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6032/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/science/science.model.ts.html) | 100% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [ScienceEventType.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6032/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.domain.science/ScienceEventType.html) | 100% | ✅ |

## Summary by CodeRabbit

- **New Features**
	- Expanded event types in the system to include lecture openings and exercise commencements.
	- Enhanced various components (Attachment, Online, Text, and Video Units, along with Course Exercise Details) to integrate with new event logging for improved tracking and analytics.
- **Documentation**
	- Updated inline documentation to reflect the integration of new event types and logging mechanisms.
- **Tests**
	- Introduced new test cases across components to ensure event logging functionality behaves as expected.
	- Added a mock service for simulating science service interactions in tests.

### CODE REVIEW

**Review by Predixx — COMMENTED** [review]
I tested the science feature and all the text is working. I just couldn't check the db (no access)

**Review by rstief — APPROVED** [review]
tested in testing session, works as expected.

**Review by reschandreas — APPROVED** [review]
tested locally, works

**Review by basak-akan — DISMISSED** [review]
Tested during the testing session locally, worked well

**Review by rstief — APPROVED** [review]
Tested locally, worked as expected 👍

**Review by basak-akan — APPROVED** [review]
Re-tested locally still works

**Review by bassner — APPROVED** [review]

**Pull request merged**
