### PR TITLE
`Programming exercises`: Add video setup guide for local version control and continuous integration

### PR DESCRIPTION
**Pull request by frederik-kt**
#### General
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Description
This PR adds the link to a screen recording containing the setup guide for local VC and local CI to the documentation. 

### Steps for Testing
Check that the link is displayed properly in the documentation.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
- [x] Code Review 3
- [x] Code Review 4

### CODE REVIEW

**Review by SolizerCodes — DISMISSED** [review]
Looks good 👍

**Review by pellumbbaboci — DISMISSED** [review]
LGTM 👍

**Review by lennart-keller — DISMISSED** [review]
LGTM :)

**Review by MaximilianAnzinger — DISMISSED** [review]
LGTM 👍

**Review by tobias-lippert — APPROVED** [review]
Link works and procedure is very well explained in the video.

**Review by DominikRemo — APPROVED** [review]
LGTM 🙂

**Review by Mtze — APPROVED** [review]

**Review by dearjasmina — APPROVED** [review]
looks good

**Pull request merged**
