### PR TITLE
`Exam mode`: Removed Redundant Course Name Field in Exam Creation

### LINKED ISSUE #8005: `Exam creation`: Redundant field
### Describe the bug

When you create or import an exam, there is a redundant field 
 
Course name and course title

### To Reproduce

Create or import any exam 

### Expected behavior

Both fields present the same information. Course name should be deleted

### Screenshots

Screenshot 2024-02-05 at 09 12 06

### Which version of Artemis are you seeing the problem on?

6.7.7

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by egekurt123**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Closes #8005 

### Description

Removed Redundant Course Name Field / Removed Duplicate. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course

1. Log in to Artemis
2. Navigate to Course Administration of a Course
3. Navigate to Exams
4. Click to create or import an exam
5. Make sure that duplicate Course Title Field is removed 
6. Ensure that a tooltip is added to the Course Title field (represented by a small "?" button next to the Course Title) and that it is correctly formulated.
7. Confirm that it is possible to modify the course name, and changes to the course name are successfully saved.
8. Course name has the default value of the course it belongs
9. Everything else works as expected.

### Screenshots
OLD
Exam creation old

NEW
Screenshot 2024-02-13 at 19 00 04

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **Style**
	- Adjusted column widths for examiner and module number fields in the exam management form.
- **Bug Fixes**
	- Fixed an issue where the course name was not displaying correctly in the exam update form.

### CODE REVIEW

**Review by Strohgelaender — CHANGES_REQUESTED** [review]
This filed is not complety redundant since it allows to change the course name visible on the exam front page. While it's a good idea to make the course name the default value here, the field should still be editable. You could instead reomove the top field which just displays the Artemis-interal course name and is not editable.

**Review by georgyia — DISMISSED** [review]
manually tested on ts2, duplicate Course Name Field is not there
Снимок экрана 2024-02-09 в 10 32 01

**Review by Gusti2010 — APPROVED** [review]
Manually tested on ts11_Legacy and everything works as expected!

**Review by AntonGeTUM — APPROVED** [review]
Manually tested, works as described

**Review by Predixx — APPROVED** [review]
tested on ts2. Looks good to me

**Review by Strohgelaender — APPROVED** [review]
lgtm

**Review by jakubriegel — APPROVED** [review]
lgtm

**Pull request closed without merging**
