### PR TITLE
[Enhancement] Improve grading page

### LINKED ISSUE #2572: Explain the grading page for programming exercises
The grading page for programming exercise has become more complex recently.
It is not really clear to all instructors how weights, bonus multiplier (relative) and bonus points (absolute) can be used.
We should explain this better with little (?) icons and automatically appearing popups in case the user hovers over those.
We should also have one sentence at the top that introduces the main possibilities at this page, one for the test case grading and one for the static code analysis grading.

There was an interesting discussion in the #artemis Slack space recently that shows some possible misunderstandings.

In addition, it would be good to document the grading page with examples and screenshots in the Github documentation

### PR DESCRIPTION
**Pull request by schultek**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Better explain the options and charts of the grading page.
Resolves #2572 

### Description

- [x] split chart for test-cases
- [x] add better explanations for the charts (+ translations)
- [x] add (?) explanations for weights, bonus multiplier and bonus points
- [x] add (?) explanations for penalty and max penalty
- [x] add explanations to sca category issue chart
- [x] make the tables sortable

### Steps for Testing

1. Log in to Artemis
2. Navigate to the grading page
3. Check that sorting in the test case and category tables works
4. Check the (?) tooltips.
5. Check the chart descriptions.

Please also give Feedback on the hints and descriptions if you have any.

### Test Coverage

Nothing changed.

### Screenshots

Bildschirmfoto 2021-01-03 um 01 36 49
Bildschirmfoto 2021-01-03 um 03 58 52

### CODE REVIEW

**Review by airelawaleria — COMMENTED** [review]
Tested in the testing session with @simonzilker .Everything works fine, but the button in the  "After due date"  (to go to the edit page) is not working.

**Review by simonzilker — COMMENTED** [review]
What @airelawaleria said.

**Review by EneaGore — COMMENTED** [review]
Same issue as @airelawaleria 
editButtonforGradingPage

**Review by JohannesWeiss — COMMENTED** [review]
Can confirm the mentioned issue on ts3.

**Review by marvinchimeka — COMMENTED** [review]
tested on ts3.  I had the same issue which was already stated by reviewers above.

**Review by JohannesWeiss — DISMISSED** [review]
Now everything works as intended.

**Comment by schultek** [comment]
The button in the "After Due Date" popup now works.

**Review by airelawaleria — APPROVED** [review]
Tested with @JohannesWeiss @simonzilker. Works fine

**Review by simonzilker — DISMISSED** [review]
Works perfectly now!

**Review by JohannesWeiss — APPROVED** [review]
Re-Tested on ts1, re-approve!

**Review by airelawaleria — APPROVED** [review]
Re-tested, re-approve

**Review by marvinchimeka — APPROVED** [review]

**Review by simonzilker — APPROVED** [review]
re-approve

**Review by valeriebucher — APPROVED** [review]
works fine. hints and descriptions are also good!

**Review by tiffca — APPROVED** [review]
Tested successfully, no issues encountered!

**Review by philgabr — APPROVED** [review]
Everything works as intended.

**Review by krusche — APPROVED** [review]

**Pull request merged**
