### PR TITLE
[Bugfix][local] Jenkins user management

### PR DESCRIPTION
**Pull request by LDAP**
Local version of #3049 

@ivanchimeno

### CODE REVIEW

**Comment by LDAP** [comment]
Test failure should be not related to changes in this PR

**Review by ivanchimeno — APPROVED** [review]
I'm approving because the code looks got for me and I tested the changes successfully on TS2 (except registering a new user).

**Review by krusche — DISMISSED** [review]

**Comment by krusche** [comment]
It seems that a java server test is still failing. Can you please have a look and fix it?

**Comment by LDAP** [comment]
I found these errors in the logs:

```
2021-03-20T07:36:42.5397684Z     org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.AssertionError: Unexpected request expected:<https://version-control.fake.fake/rest/api/latest/projects/SHORTCCD723A50C259042980890D0792173B87CFETSTEXC/repos/shortccd723a50c259042980890d0792173b87cfetstexc-student1/permissions/users?name=student1&permission=REPO_READ> but was:<https://version-control.fake.fake/rest/api/latest/projects/SHORTCCD723A50C259042980890D0792173B87CFETSTEXC/repos/shortccd723a50c259042980890d0792173b87cfetstexc-student2/permissions/users?name=student2&permission=REPO_READ>
```

```
2021-03-20T07:27:01.7373214Z 
2021-03-20T07:27:01.7378295Z     java.lang.AssertionError: No further requests expected: HTTP POST https://continuous-integration.fake.fake/rest/api/latest/queue/SHORT9E04FBF505D690417108F290EFF49C26D1F5TSTEXC-STUDENT1
2021-03-20T07:27:01.7381473Z     0 request(s) executed.
```

I think they are related to Jenkins but not introduced with this PR. Since I am not familiar with Artemis tests, help is appreciated. @ivanchimeno could you have a look? That may be related to changes in #2959.

**Review by ivanchimeno — APPROVED** [review]
Re-approved

**Review by krusche — APPROVED** [review]

**Pull request merged**
