### PR TITLE
`Programming exercises`: Allow instructors to edit programming exercises in the new code editor

### PR DESCRIPTION
**Pull request by pzdr7**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

The Monaco editor, which was introduced in PR #8130, is currently only available to students in two views. This PR contributes to our gradual removal of Ace from the Artemis client.

### Description

- **Monaco editor for instructors**: Uses Monaco in the "Edit in Editor" view, which allows instructors to edit the template, solution, assignment, and test repositories.
- **Earlier initialization of the monaco editor**: The `MonacoEditorComponent` now initializes its editor in the constructor (rather than `ngOnInit`) by injecting its container into the DOM using Renderer2. This ensures that the `_editor` instance is always available when methods of the component are called and avoids having.

**Known issues**:

- Resizing as mentioned in #8130
- ~~Pasting is broken on non-Firefox browsers because of an issue involving the `process` dependency we use in the client. For these browsers, CTRL+Shift+V works for pasting~~ fixed in #8391 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming exercise

1. Log in to Artemis
2. Navigate to Course management > Your course > Exercises
3. Click "Edit in Editor" for your programming exercise
4. Verify that you can switch between & edit each repository: Template, Solution, Tests, and Assignment (create if necessary).
5. Ensure that your changes are saved.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [code-editor-monaco.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6388/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/shared/code-editor/monaco/code-editor-monaco.component.ts.html) | 92.7% | ✅ |
| [monaco-editor.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6388/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/monaco-editor/monaco-editor.component.ts.html) | 97.4% | ✅ |

### Screenshots

grafik

## Summary by CodeRabbit

- **New Features**
	- Integrated Monaco Editor for enhanced code editing experience in programming exercises.
  
- **Bug Fixes**
	- Improved editor reset functionality to ensure consistent behavior when reverting changes.

- **Refactor**
	- Optimized the initialization and rendering process of the Monaco Editor to improve performance and user interaction.

### CODE REVIEW

**Review by JohannesWt — APPROVED** [review]
Code looks good

**Review by mateusmm01 — APPROVED** [review]
tested on ts5. Works as expected

**Review by Jan-Thurner — APPROVED** [review]
Code lgtm

**Review by coolchock — APPROVED** [review]
tested on ts4, works as expected

**Review by coolchock — APPROVED** [review]
re-tested on ts2, works as expected 👍

**Pull request merged**
