### PR TITLE
Allow instructors to cancel assessments

### PR DESCRIPTION
**Pull request by madwau**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I added multiple integration tests (Spring) related to the features
- [x] ~Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)~
- [x] ~Server: I implemented the changes with a good performance and prevented too many database calls~
- [x] ~Server: I documented the Java code using JavaDoc style.~
- [x] ~Client: I added multiple integration tests (Jest) related to the features~
- [x] ~Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)~
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
This PR solves issue #1150. Right now, instructors are not able to release the lock for assessments if a tutor has it. With this PR, instructors will be able to cancel an assignment (e.g. if a tutor does not complete it or another tutor should do it). This can be done from the submissions and assessments page via the new button "Cancel assessment" or from the assessment detail page via the existing button "Cancel".

### Description
1. Add button "Cancel assessment" to submissions and assessments page (for TextExercise, FileUploadExercise, ModelingExercise) which is only available to instructors and only shown if an assessment exists and it is not completed yet
2. In `/cancel-assessment` endpoints in backend, allow instructor to cancel an assessment (despite not being the assessor themselves)
3. Adapt existing button "Cancel" on assessment detail page to new permission logic (should not be disabled if user is instructor and not completed yet)

### Steps for Testing
1. Log in to Artemis
2. Navigate to Overview
3. Click on a Course for which the user is an instructor and that has a TextExercise, FileUploadExercise, ModelingExercise
4. Click on all those exercises
5. Click on the instructor action button "Submissions"
6. Verify that the button "Cancel assessment" is shown (together with "Open assessment") if there is an assessment
7. Click on "Cancel assessment" and see that the result is removed and the reviewer is unset

### Screenshots
OnPaste 20200107-161811
OnPaste 20200107-161843
OnPaste 20200107-162241

### CODE REVIEW

**Comment by madwau** [comment]
I found an error when trying to cancel a certain [assessment](https://artemistest.ase.in.tum.de/#/text/658/assessment/239847) on the test server. I'm not sure if the issue is related to this PR but I'm looking into it.

OnPaste 20200107-194337

**Comment by HanyaElhashemy** [comment]
@madwau "Steps for testing" describes the submissions page, but what is meant by the assessments page and how can I reach it?

**Comment by madwau** [comment]
> @madwau "Steps for testing" describes the submissions page, but what is meant by the assessments page and how can I reach it?

That refers to the same page. The heading of that page says "Submissions and assessments of..." which is why the issue refered to it as that.

**Comment by madwau** [comment]
> I only think it is important here to add some test cases for permission e.g. test that other tutors cannot unlock assessments in the corresponding exercise type integration test.

Good point. I will add a test case that checks that tutors can only cancel their own assessment and not the one of other tutors.

> Optional: I would rename "cancel assessment" to "unlock assessment" at least in the UI since the button does not cancel a submitted assessment but releases tutors lock to a submission, but that's just my personal opinion :)

I shared your sentiment initially but I think "unlock" actually sounds too harmless in this case. Clicking on the button does not just release the lock but it also discards the current assessment progress (as the user is informed of in the confirmation popup). I think that is what "cancel" refers to and it does make sense semantically since "cancel" implies aborting an ongoing process.

**Comment by madwau** [comment]
I added four permission related test cases for each FileUpload, Text and Modeling assessment:
1. A student should not (!) be able to cancel an assessment
2. A tutor should be able to cancel his own assessment
3. A tutor should not (!) be able to cancel an assessment of another tutor
4. An instructor should be able to cancel an assessment of another tutor

**Comment by madwau** [comment]
> I found an error when trying to cancel a certain [assessment](https://artemistest.ase.in.tum.de/#/text/658/assessment/239847) on the test server. I'm not sure if the issue is related to this PR but I'm looking into it.
> 
> OnPaste 20200107-194337

The issue is unrelated to this PR. When develop is deployed on the test server, the assessor himself also receives a 500 when trying to cancel the assessment.

**Comment by krusche** [comment]
> > I found an error when trying to cancel a certain [assessment](https://artemistest.ase.in.tum.de/#/text/658/assessment/239847) on the test server. I'm not sure if the issue is related to this PR but I'm looking into it.
> > OnPaste 20200107-194337
> 
> The issue is unrelated to this PR. When develop is deployed on the test server, the assessor himself also receives a 500 when trying to cancel the assessment.

Could you still try to fix this here as related functionality is changed.

**Comment by krusche** [comment]
The problem should be easy to fix. The exception is caused by a foreign key constraint.

```
Jan 11 17:45:37 vmbruegge105 java[20811]: Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`ArTEMiS`.`feedback`, CONSTRAINT `feedback_ibfk_1` FOREIGN KEY (`result_id`) REFERENCES `result` (`id`))
```

For some reason the feedback that references the result is not deleted.
The exception happens in `AssessmentService.java:103`
I guess, you need to make sure the feedback of the result is deleted first

**Comment by madwau** [comment]
Thanks for sharing the server log and exeption location. That should be enough info for me to fix that problem as part of this PR.

**Comment by krusche** [comment]
> Thanks for sharing the server log and exeption location. That should be enough info for me to fix that problem as part of this PR.

Would be great if we can update the tests so that they cover this case as well. Means that before executing cancel assessment, we need to add some feedback to the results.

**Comment by krusche** [comment]
What I don't understand: `CascadeType.ALL` in the relationship between result and feedback should make sure that all feedback related to the result entity is also deleted. I don't really understand why this does not work in this particular case...

By the way:
`studentParticipationRepository.save(participation)` should not be necessary in this method. The participation in the database is not really changed, because the reference to the participation is stored in the result.

**Comment by madwau** [comment]
> What I don't understand: `CascadeType.ALL` in the relationship between result and feedback should make sure that all feedback related to the result entity is also deleted. I don't really understand why this does not work in this particular case...

True, that is strange. I just tested it locally and when canceling an assessment with a feedback, the feedback is properly cascade deleted.

**Comment by madwau** [comment]
> Would be great if we can update the tests so that they cover this case as well. Means that before executing cancel assessment, we need to add some feedback to the results.

I'll add that. Looks like there already is a database util service method for that.

**Comment by madwau** [comment]
> The problem should be easy to fix. The exception is caused by a foreign key constraint.
> 
> ```
> Jan 11 17:45:37 vmbruegge105 java[20811]: Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`ArTEMiS`.`feedback`, CONSTRAINT `feedback_ibfk_1` FOREIGN KEY (`result_id`) REFERENCES `result` (`id`))
> ```
> 
> For some reason the feedback that references the result is not deleted.
> The exception happens in `AssessmentService.java:103`
> I guess, you need to make sure the feedback of the result is deleted first

Explicitly deleting the feedback before removing the result solved the issue. I just tested it on the test server.

**Pull request merged**
