### PR TITLE
`General`: Fix course overview control items inconsistencies and persist lecture sorting locally

### LINKED ISSUE #6176: Inconsistent sorting of groups
### Describe the bug

On the exercise overview, exercise groups are sorted by date ascending, with the newest exercises being at the bottom of the page:
grafik

However, Lectures are sorted descending, the newest lectures are at the top:
grafik

This is inconsistent and confusing, I regularly catch me scrolling to the bottom of the lectures tab just to open the slides for L01.

### To Reproduce

see above

### Expected behavior

Consistency

### Screenshots

above

### Which version of Artemis are you seeing the problem on?

6.0.1

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #6288: 'Lectures' tab control buttons are not aligned with the buttons in other tabs
### Describe the bug

In the course overview top bar, the 'refresh' button stays at the same consistent place when navigating through the tabs, except of the 'lectures' tab. At the 'lectures' tab it jumps to the right.

### To Reproduce

1. Go to course overview of the course, containing lectures and exercises.
2. Click on 'exercises'
3. Click on 'lectures'
4. See that the 'refresh' and sorting buttons are jumping in this tab relatively to the other tabs, where 'refresh' button stays consistently on the page.

### Expected behavior

The control buttons of all the tabs in the tab bar stay consistent while navigating across them.

### Screenshots

Screenshot 2023-02-22 at 15 19 32
Screenshot 2023-02-22 at 15 27 21
Screenshot 2023-02-22 at 15 19 45

### Which version of Artemis are you seeing the problem on?

6.0.6

### What browsers are you seeing the problem on?

Chrome, Safari

### Additional context

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #6289: 'Lectures' tab sorting key is not stored in the local storage
### Describe the bug

For all of the tabs in the course overview top bar the sorting keyed filters are stored in the local storage. This goes, for example, for 'Exercises', 'Statistics'. 
That allows users not to input their preferences again after reloading the page. For the 'Lectures' tab this is not yet the case, after the reloading all the settings are gone, e.g. sorting order of the lectures.

### To Reproduce

1. Go to the course overview of the course with multiple lectures
2. Click on 'Lectures'
3. Sort lectures by date, 'oldest'
4. Reload the page
5. See that your sorting key wasn't saved and the lectures are not sorted

### Expected behavior

Lectures sorting key is stored in the local storage as well.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.0.6

### What browsers are you seeing the problem on?

Chrome, Safari

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by FelixTJDietrich**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

There are some inconsistencies/bugs in the course overview page across the different tabs (Exercises, Lectures, ...):
 - Control items alignment (Refresh, filter, sort, etc.)
 - Sorting inconsistency of groups between exercise groups (ascending by date) and lecture groups (descending by date)
 - Sorting of "Lectures" is not persisted in local storage like "Exercises" for example
 - Sort button of "Lectures" inconsistent with sort button of "Exercises"

Fixes #6288
Fixes #6176
Fixes #6289

### Description

In the course overview page the control items are now consistently left-aligned in every tab. The lecture groups are now sorted by default in ascending order like the exercise groups. Additionally, the sorting is locally stored so when the user refreshes the sorting is kept. The drop-down menu for sorting lectures is now a simple button for flipping the sorting with one click. It also uses the same button style and iconography as the exercises' sort button. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course
- 2 Exercises in different weeks
- 2 Lectures in different weeks

1. Go to the course's overview
2. Check sorting of "Exercises". Should be ascending (unchanged).
3. Check sorting of "Lectures" . Should be ascending as well.
4. Compare consistency of the changed sorting button of "Lectures" with the "Exercises" sorting button
5. Press sort button of "Lectures" and refresh. Should now always persist the sorting.
6. Observe the consistent alignment of buttons across tabs (Exercises, Lectures, etc.)

#### Code Review
- [x] Review 1
- [ ] Review 2

#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

unchanged.

### Screenshots

Exercises old:
Exercises_old

Lectures old:
Lectures_old

Exercises new:
Exercises_new

Lectures new:
Lectures_new

Going through tabs and refreshing changed Lectures sorting:
changes

### CODE REVIEW

**Review by Vinicius-Agreste — APPROVED** [review]
Tested on ts1. Working as expected.

**Review by danielbode — APPROVED** [review]
Code LGTM

**Review by pellumbbaboci — APPROVED** [review]
Tested on ts10, works as expected and code changes look good 👍

**Review by JohannesStoehr — APPROVED** [review]
Code changes look good to me

**Pull request merged**
