### PR TITLE
Fix count programming exercises

### PR DESCRIPTION
**Pull request by nicolasruscher**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

There is a problem with counts within the exercise overview dashboard for normal programming exercises (not within exams). 
This PR fixes the problem, now all counts within normal exercises should work correctly. 
We also removed the 'information' Button within the header of the assessment dashboard and made the header itself a bit smaller.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration -> course -> assessment dashboard
3. Check if all progress bars display correct counts 

### Screenshots

Smaller header:
Bildschirmfoto 2021-02-23 um 09 58 19

### CODE REVIEW

**Review by airelawaleria — COMMENTED** [review]
.

**Review by airelawaleria — APPROVED** [review]
tested in the testing session. looks good

**Review by simonzilker — APPROVED** [review]
Looks good to me :)

**Review by marvinchimeka — APPROVED** [review]
No issues found

**Review by EneaGore — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]

**Review by tiffca — APPROVED** [review]
Tested successfully

**Review by SimonEntholzer — APPROVED** [review]
Testing locally worked. The code and tests seem good too. :+1:

**Review by JannisBittlmayer — APPROVED** [review]
Works as intended

**Review by FuchsDominik — APPROVED** [review]
Code itself looks fine :)

**Review by FlorianStang — APPROVED** [review]
Tested on TS1, everything worked as expected

**Review by philgabr — APPROVED** [review]

**Pull request merged**
