### PR TITLE
`Development`: Add PostgreSQL and test container support and cleanup change logs with migration paths

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
* We want to get rid of the many change logs, therefore there is a new initial schema
* We want to support PostgreSQL because it has certain advantages compared to MySQL

- [x] There are still some issues with PostgreSQL in some queries due to the use of native MySQL syntax or datatypes. All occurrences with timestamps / dates might need to be cast and `substring` on dates must be cast explicitly to string
- [x] Check the primary keys of the database: They might have changed between Postgres and Mysql -> Provide SQL script to migrate data

### Steps for Testing
By default, the tests are executed using `H2` with an improved mode (taking liquibase changes into account) and a bit faster than previously.
If you want to use PostgreSQL, you have to set the `postgres` profile, e.g. by running:

`SPRING_PROFILES_INCLUDE=postgres ./gradlew executeTests -x webapp`

If you want to use MySQL, you have to set the `mysql` profile, e.g. by running 

`SPRING_PROFILES_INCLUDE=mysql ./gradlew executeTests -x webapp`

Please navigate through all views of the Artemis app when running PostgreSQL and check if you notice Internal Server Errors  due to SQL syntax.

Example config for testing using Postgres in IntelliJ (which allows to debug)

image

Using MySQL:

image

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by sleiss — DISMISSED** [review]
Tests run (at least for H2) and on TS0 everything seems normal.

**Comment by krusche** [comment]
We will merge this PR soon and will implement further improvements in follow-up PRs.
At the moment, some tests are server disabled, because they currently fail.
Postgres is beta and needs to be thoroughly tested.
Server tests need to be further optimized (in terms of performance) so that they run in less than 30min for Postgres and Mysql Testcontainers

**Review by Strohgelaender — APPROVED** [review]
Tested common functionality on TS0 and did not spot any issues.

**Review by Strohgelaender — DISMISSED** [review]

**Review by sleiss — APPROVED** [review]
Reapprove

**Review by sleiss — APPROVED** [review]
Reapprove²

**Review by Strohgelaender — APPROVED** [review]

**Pull request merged**
