### PR TITLE
[Feature] Reset SCA categories

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Adds missing functionality to restore the default configuration for static code analysis categories.

### Description

- Move REST request handler and service of reset test cases to the test case resource and service
- Add functionality to reset static code analysis categories

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a programming exercise with SCA
4. Navigate to the grading page
5. Alter the test case configuration and save
6. Reset the test case configuration
--> All test cases should now have the weight 1, bonusMultiplier 1 and bonus 0
7. Select the tab for the SCA categories
8. Remember the settings e.g. take a screenshot
9. Alter the category configuration and save
10. Reset the categories
--> The initial category state should be restored

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]

**Review by FrankeLukas — APPROVED** [review]
Code changes lgtm and works as described.

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts1, works as expected.

**Review by marvinchimeka — APPROVED** [review]

**Review by simonzilker — APPROVED** [review]

**Review by valeriebucher — APPROVED** [review]
Works well!

**Review by DenizShabani — APPROVED** [review]

**Review by EneaGore — APPROVED** [review]

**Review by philgabr — APPROVED** [review]
Works as intended :+1:

One side-note (probably not related to this PR):
When changing the weights (and saving) or resetting, the weighting chart doesn't get updated, only when refreshing the page...

**Review by sebastiantpeter — APPROVED** [review]
Tested on ts1. Worked as described.

**Review by krusche — APPROVED** [review]

**Pull request merged**
