### PR TITLE
Add new exercise type icon and tooltip to exam checklist table

### PR DESCRIPTION
**Pull request by nicolasruscher**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [X] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

We display the exercise type and tooltip in the exam checklist exercise table.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Exam -> Checklist -> Check if the exercise type is displayed correctly. 

### Screenshots

grafik

### CODE REVIEW

**Review by argertboja — COMMENTED** [review]
Tested on TS2, icons are displayed correctly! 👍🏼 Code changes also look good!

**Review by lschlesinger — DISMISSED** [review]
Tested on TS3 for all exercise types. I like the changes, tooltips and icons were displayed properly.

I know we are using both terms, but as the buttons shown in the picture use the term "Aufgabe", and also the creation and importing feature in the exam management section use it (Aufgabengruppe, etc.), maybe the tools tips in the exam checklist should also use Aufgabe, e.g. ("Dies ist eine Modellierungsaufgabe").
Bildschirmfoto 2021-07-12 um 16 06 50

**Review by niclasschuemann — APPROVED** [review]
I strongly suggest implementing @lschlesinger's suggestion regarding "Übung" <--> "Aufgabe", since exercises in the exam are theoretically not an "Übung" but rather an "Aufgabe" 😅 
However, everything works as expected, good job 👍

**Review by FrankeLukas — APPROVED** [review]
Works. The placing of the tooltip is a bit odd though:
grafik
(Can we move that above the icon which is hovered over?)

**Review by real-dmy — APPROVED** [review]
Tested on TS1, works as expected

**Review by NicolasUllmann — DISMISSED** [review]
Tested on TS2. Everything worked as expected.

**Comment by FrankeLukas** [comment]
Fixed the translation and tooltip position:
grafik

**Review by katjanakosic — APPROVED** [review]
Everything looks fine on TS2 👍

**Review by canyelten — CHANGES_REQUESTED** [review]
Tested on TS1, the exercise type is displayed correctly however the placement of the message isn't like in the example.

**Comment by FrankeLukas** [comment]
The build on Bamboo hasn't completed, so you can't deploy the latest version yet.

**Review by cremertim — APPROVED** [review]
Tested on ts1 with @PatZintel.. works as expected

**Review by PatZintel — APPROVED** [review]
tested on ts1, changes look good

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3.

**Pull request merged**
