### PR TITLE
`Programming exercises`: Add clone in VSCode button

### PR DESCRIPTION
**Pull request by janthoXO**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
We want to provide students a direct way of cloning their repositories in VSCode instead of manuall copying the links.

### Description
This adds a new "Clone in VSCode" button for programming exercises.
Builds on the code of @Strohgelaender 

### Steps for Testing
Prerequisites:
- 2 Students
- 1 Programming Exercise with Offline IDE enabled

1. Start the exercise (if not already done) by clicking on "Start Exercise"
2. Click on "Clone Repository" and see the new "Clone in VSCode" button
3. Click the Button and see that it clones and opens the repository correctly
Test it with SSH and HTTP. And also test it in Exam mode as that makes a difference apparently.

#### Exam Mode Testing
same but in exam exercises

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Exam Mode Test
- [x] Test 1
- [ ] Test 2

### Screenshots
image

## Summary by CodeRabbit

- **New Features**
  - Introduced buttons for cloning repositories in VSCode and IntelliJ directly from the app with corresponding help icons.

- **Enhancements**
  - Updated existing cloning functionality to include more IDEs (VSCode, IntelliJ) alongside SourceTree.

- **Bug Fixes**
  - Improved the accuracy and reliability of the clone URL generation for different IDEs.

- **Documentation**
  - Added new instructions and help icons for cloning repositories in VSCode and IntelliJ in the UI.

- **Tests**
  - Added unit tests for the new `ExternalCloningService` to ensure proper URL generation for various IDEs.

### CODE REVIEW

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts1 works expected for both exam and normal programming exercise. 

Take a look at the failing server tests I don't think they are related to your PR though.

**Review by Jan-Thurner — APPROVED** [review]
Tested on TS1 for exam-mode and normal exercises. Works as expected.

**Review by EneaGore — APPROVED** [review]
Tested on Ts1. Works as expected for exercises and exam.

**Review by anian03 — APPROVED** [review]
Was only able to test normal mode right now, but that worked perfectly. Code also looks good to me :)

**Review by JohannesStoehr — APPROVED** [review]
Code
For the future please use the other branch as base branch instead of develop if you base your PR on an other PR

**Review by magaupp — APPROVED** [review]
Code LGTM

**Review by Mtze — APPROVED** [review]

**Pull request merged**
