### PR TITLE
Fix an issue related to categories in exercise units

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context

An error similar to #3261 happens when trying to add an exercise unit for an exercise with categories.

### Description

We apply the same fix as in #3262 and stringify the categories before sending them to the server. Also fixes the import of modeling exercises.

### Steps for Testing

1. Find or create an exercise with categories
2. Add that exercise as unit to a lecture
3. Import a modeling exercise with categories

### CODE REVIEW

**Comment by FrankeLukas** [comment]
Modeling exercises not showing categories appears to be a different issue and I'll solve that in another PR.

**Review by willergeorg — APPROVED** [review]
Importing text exercise and modeling exercise with categories as lecture unit worked for me.

**Review by NicolasUllmann — APPROVED** [review]
Worked for me as well

**Review by real-dmy — APPROVED** [review]
Tested on TS1.  Imported text exercise & modelling exercise with categories as lecture units.  Everything worked fine.

**Review by katjanakosic — APPROVED** [review]
Worked as expected for me

**Review by maximilianbergmann — APPROVED** [review]
Tested it.  Worked

**Pull request merged**
