### PR TITLE
`Programming exercises`: Fix test case issue indicator for task descriptions with brackets

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation and Context
When the title of a task cotains brackets (for example because it meantions a method that the student has to implement), these brackets get mistaken as part of the test methods.

### Description
I updated the Regex

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Edit / Create a Programming Exercise
2. Add a new task with brackets inside, e.g. `[task][Implement myMethod()](testMyMethod)`
3. Check that no test case issues are present (if the test acutally exsts) or the test case name gets parsed correctly (if the test does not exist)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
Issue on Production:
grafik

Correctly parsed name if the test actually does not exist:
grafik

### CODE REVIEW

**Review by ole-ve — APPROVED** [review]
Tested with tests for Gradle and Maven and a task name containing `()` and some other possible assignments.
Works as expected 👍

**Review by JohannesStoehr — APPROVED** [review]
Tested on TS1 and looked at the code changes. Both looked good

**Review by max-bergmann — APPROVED** [review]
Tested on TS3. Works for me as expected.

**Review by Hialus — APPROVED** [review]
Tested locally and the issue no longer occurs. Code also looks good.
Well done 👍🏻

**Review by SimonPaul02 — APPROVED** [review]
Tested on ts1, worked as expected

**Pull request merged**
