### PR TITLE
`Lectures`: Fix file names for downloads with chromium browsers

### PR DESCRIPTION
**Pull request by SimonEntholzer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

There are still issues with the attachment downloads for lectures and lecture units:
1. The file name in the URL is still the original file name, and not the attachment name
2. Saving with chromium based browsers does not include the extension : in firefox it does have an extension
Cause: We send the file without extension to the client, firefox manages to automatically deduct the file type + extension from the content, and appends the extension, and chrome simply doesn't. 

### Description

1. Makes sure the user defined attachment name is used as the new file name, which users get when they download the attachment.
2. We explicitly send the file with extension

### Steps for Testing

1. In lecture units and lectures upload attachments, and set names.
2. Download the files again from the instructor view
3. Download the files again from the student view

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| lecture-attachments.component.ts | 96.58% | ✅ ❌ |
| attachment-unit.component.ts | 94.11% | ✅ ❌ |
| course-lecture-details.component.ts | 98.61% | ✅ ❌ |
| file.service.ts | 44.18%  -> 100%| ✅ |

### Screenshots

image
image

## Release Notes

- **New Features**
	- Enhanced file download functionality by allowing downloads using both attachment name and URL.
	- Introduced a new method to download files by attachment name in the file service.

- **Improvements**
	- Updated method signatures across components to include attachment names for improved clarity and functionality.
	- Improved error handling and logging related to file downloads.

- **Bug Fixes**
	- Adjusted parameter handling in download methods to ensure correct attachment retrieval and processing.

### CODE REVIEW

**Review by sachmii — APPROVED** [review]
Tested on TS1, for lecture attachments and lecture units, files are saved and downloaded with attachment name.

**Review by HawKhiem — DISMISSED** [review]
Tested on TS1. The names of downloaded documents work fine

Screenshot 2024-11-29 170050
Screenshot 2024-11-29 170301

**Review by sawys777 — DISMISSED** [review]
Tested on TS3, downloaded files named correctly as expected.

**Review by florian-glombik — DISMISSED** [review]
Tested on ts2, downloading a pdf and a json worked for me

**Review by kaancayli — DISMISSED** [review]
Tested during testing session. File is saved with extensionin Arc Browser (Chromium based). Code is also lgtm.

**Review by coolchock — APPROVED** [review]
tested during testing session, LGTM

**Review by kevinfischer4 — DISMISSED** [review]
Tested on TS2. Filename is correctly adapted.
Screenshot 2024-11-30 at 21 42 57

**Review by coolchock — APPROVED** [review]
re-approve after fixing tests

**Review by kaancayli — APPROVED** [review]
reapprove

**Review by kevinfischer4 — APPROVED** [review]
Reapprove

**Review by florian-glombik — APPROVED** [review]
Re-approve after merge and adding more test cases

**Review by Malekos74 — APPROVED** [review]
### Tested on Server 02:
Works as intended

**Review by sachmii — APPROVED** [review]
re-approve

**Review by sawys777 — APPROVED** [review]
Reapprove

**Review by FelixTJDietrich — APPROVED** [review]
Tested on TS2, works as expected. Thanks for fixing this! Tested with Arc

**Review by krusche — APPROVED** [review]

**Pull request merged**
