### PR TITLE
`Communication`: Fix performance issues in mark all read feature

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
The mark all read was implemented with a poor performance

### Description
This PR improves the performance significantly 

### Steps for Testing

Prerequisites:
- 2 users in a course with communication enabled
- A few existing channels

1. Write a few messages in different channels
2. Use a second account and click on mark all messages as read, see #9994 
3. Make sure the corresponding network call ist fast

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage
no changes

### Screenshots
no changes

## Summary by CodeRabbit

- **New Features**
	- Introduced default boolean values for several properties in `Channel` and `ChannelDTO`, ensuring they default to `false`.
	- Added new properties and methods in `ConversationDTO` for enhanced conversation management.
	- New method to notify users about conversation creation or deletion.

- **Bug Fixes**
	- Improved handling of boolean properties to prevent undefined values during form submissions.

- **Refactor**
	- Streamlined channel creation logic by utilizing `ChannelDTO` directly.
	- Removed unnecessary dependencies and methods, simplifying service and repository classes.

- **Documentation**
	- Enhanced method documentation and added comments for clarity in various classes.

- **Tests**
	- Updated tests to reflect changes in method signatures and property assignments.
	- Improved type safety in test cases by explicitly casting objects to `ChannelDTO`.

### CODE REVIEW

**Review by cremertim — APPROVED** [review]
Tested the feature on ts 1 with ~50 channels. Everything works as expected and is much faster now

**Review by cremertim — CHANGES_REQUESTED** [review]
I realised a weird behaviour when writing new messages. Your own message is marked as a new, not read message


Uploading unknown_2024.12.27-16.38_1_clip_1.mp4…

**Review by cremertim — COMMENTED** [review]
I encountered the same issue at a different, unrelated PR on ts3, So it seems to be unrelated to this PR

**Review by cremertim — APPROVED** [review]
Issue is unrelated to the PR, so everything works as expected

**Review by asliayk — DISMISSED** [review]
tested on ts2 and works as expected.

however, I encountered a UI issue related with this feature:

When I use Artemis in German, the options in the "+" dropdown overlap with other UI elements and become partially invisible. This happens because the string 'Alle Kanäle als gelesen markieren' is long; the issue disappears when replaced with a shorter string. I think this can be solved in a follow-up PR

Alle öffentlichen Nachric

**Review by sawys777 — APPROVED** [review]
Tested on TS4, I've posted messages as User 1 and User 2 in the communication channels of Practical Course: Interactive Learning SS24, everything works as expected except for one time which I have to sign out and then sign in again to notice the intended changes.

**Review by HawKhiem — COMMENTED** [review]
Tested on TS2. Other than the issue mentioned above, everything works

**Pull request merged**
