### PR TITLE
Team complaints logic for programming exercises + indicator icon on team page

### PR DESCRIPTION
**Pull request by madwau**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
This PR addresses issue https://github.com/ls1intum/Artemis/issues/1834.

### Description
- Consider team exercise assessor logic in programming exercise manual result dialog
- Add flag to team participation table to indicate the existence of a complaint or more feedback request

### Steps for Testing
1. Log in to Artemis as a Tutor
2. Assess a team programming exercise
3. Log in as a Student and hand in a complaint or more feedback request
4. With the tutor, go the the team page and check that the complaint/request is indicated with an icon
5. Check that you can respond to the complaint/request as the team tutor

### Screenshots
OnPaste 20200719-164607
OnPaste 20200719-164620
OnPaste 20200719-182713

### CODE REVIEW

**Comment by fde312** [comment]
> I tested it yesterday and i was able to evaluate the complaint of my team as expected, but the flag did not appear. (See background of the screenshot)
> image

@FuchsDominik Does it work for you now? Can you maybe test it?

**Comment by madwau** [comment]
I fixed the two issues (flag icon was missing for programming exercises + complaint was not possible for programming exercises if the user was not at least an instructor).

Would be great if you could test it again.

**Comment by stefanwaldhauser** [comment]
image
Buttons are too small for the german translation.

**Comment by stefanwaldhauser** [comment]
Tooltip for flag is hidden 
image

**Comment by stefanwaldhauser** [comment]
image
Test session with @florian-glombik @fde312 
There are some german translation issues (minutes ago) but I guess they are not releated to this PR.

**Comment by krusche** [comment]
I guess we merge this now and fix the minor visual issues in a follow up

**Pull request merged**
