### PR TITLE
`Exam mode`: Use quiz pool in student exam generation

### PR DESCRIPTION
**Pull request by rriyaldhi**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [ ] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [ ] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [ ] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.

### Motivation and Context

Currently, if an instructor wants every student to have a different set of quiz questions for each student, the instructor must create one quiz exercise for one set of quiz questions. The higher the number of sets of quiz questions, the more quiz exercises must be prepared by the instructor. This is cumbersome if the instructor wants to have a high variance of quiz questions for the students.

To improve the user experience for instructors for such requirements, the quiz pool configuration is created ([#6402](https://github.com/ls1intum/Artemis/pull/6402)). Quiz pool configuration enables the instructor to put quiz questions into a group. The example configuration is shown below:

image

Then, from each group, one question is randomly assigned to each student. Therefore, the student exam creation needs to be modified for an exam that contains configured quiz pool.

### Description

**Data Model**

A new table student_exam_quiz_question is created to map the assigned QuizQuestions to StudentExam. This enables ManyToMany to relationship between StudentExam and QuizQuestion.

This is the data model of quiz questions and student exams:

test

**Server **

- Add ManyToMany quizQuestions property to StudentExam. This property contains the list of QuizQuestions that are assigned to a StudentExam that will be used by the client to display the QuizQuestions during the conduction.

- Add generateQuizQuestionsForExam method to ExamQuizQuestionsGenerator interface. This interface is used to decouple between QuizQuestions generation and QuizPool. In the future, this interface can be reused if there is other way than QuizPool to generate QuizQuestions for an exam.

- Update QuizPoolService to implements the ExamQuizQuestionsGenerator and implement the generateQuizQuestionsForExam to generate QuizQuestions for StudentExam based on QuizPool configuration.

- Add ExamQuizQuestionsGenerator dependency to StudentExamService.

- Add examQuizQuestionsGenerator to the parameter of StudentExamRepository.createRandomStudentExams and call the ExamQuizQuestionsGenerator.generateQuizQuestionsForExam to generate the QuizQuestions for the StudentExam.

- Move generateStudentExams and generateMissingStudentExams from StudentExamRepository to StudentExamService to have access to examQuizQuestionsGenerator and pass it to createRandomStudentExams.

- Update ExamResource to use studentExamService instead of studentExamRepository to call generateStudentExams and generateMissingStudentExams.

#### Exam Mode Testing

**Note: Detailed steps can be seen on the screencast in the screenshot section below**

Prerequisites:
- 1 Instructor (artemis_test_user_[11-15])
- 1 Exam with Quiz Pool:
  - **TS2**: [https://artemis-test2.artemis.cit.tum.de/course-management/22/exams/21](https://artemis-test2.artemis.cit.tum.de/course-management/22/exams/21)
  - **TS3**: [https://artemis-test3.artemis.cit.tum.de/course-management/25/exams/19](https://artemis-test3.artemis.cit.tum.de/course-management/25/exams/19)
  - **TS5**: [https://artemis-test5.artemis.cit.tum.de/course-management/15/exams/18](https://artemis-test5.artemis.cit.tum.de/course-management/15/exams/18)
  - **TS6**: [https://artemis-test6.artemis.cit.tum.de/course-management/24/exams/5](https://artemis-test6.artemis.cit.tum.de/course-management/24/exams/5)
- 1 Exam without Quiz Pool

1. Log in to Artemis as an instructor (artemis_test_user_[11-15]).
2. Go to the exam details page of specified exams above.
3. Generate student exams.
4. Verify that the student exams are generated
5. Repeat the steps 2-4 for another Exam without Quiz Pool

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| StudentExam.java | 98% | ✅                           |
| QuizPool.java | 97% | ✅                           |
| StudentExamRepository.java | 90% | ✅                           |
| QuizPoolService.java | 98% | ✅                           |
| StudentExamService.java | 94% | ✅                           |
| ExamResource.java | 95% | ✅                           |

### Screenshots

https://github.com/ls1intum/Artemis/assets/10885503/ef24f921-7030-4158-9c08-126670827249

## Summary by CodeRabbit

- **New Features**
	- Introduced an interface for generating quiz questions for exams.
	- Added functionality to create random student exams with associated quiz questions.
	- Implemented methods to retrieve student exams with eager loading of quiz questions and exercises.

- **Enhancements**
	- Improved clarity in comments within the `QuizPool` class.
	- Renamed a method for better representation of its functionality in the `QuizPoolService`.

- **Bug Fixes**
	- Modified the `isSubmitted` method to return a `Boolean` to prevent potential null pointer exceptions.

- **Documentation**
	- Updated method comments for better clarity and understanding.

- **Tests**
	- Added integration tests for exam generation with quiz pools.
	- Updated existing tests to reflect changes in student exam generation logic.

### CODE REVIEW

**Review by JanaNF — DISMISSED** [review]
Manual tested on legacy_ts11. Worked as expected

**Review by Gusti2010 — CHANGES_REQUESTED** [review]
Tested manually on TS11_Legacy. I don't know if i understood the steps for manual testing correctly, but from my interpretation there should only be 2 exercises in the exam. One of any type and one quiz exercise. However artemis won't recognize the quiz exericise Group or points that could be attained in this exercise. Is that intended? If i create one more exercise artemis is happy and exams for students can be created.

image
image

**Review by georgyia — DISMISSED** [review]
tested manually on ts2, worked
Снимок экрана 2023-11-22 в 17 55 36

**Review by sarpsahinalp — COMMENTED** [review]
Tested on legacy ts11. While trying to delete the exam with the quiz pool I got the following: 
Screenshot from 2023-11-22 23-26-56
I was able to delete the exam without the quiz pool

**Comment by rriyaldhi** [comment]
> Tested on legacy ts11. While trying to delete the exam with the quiz pool I got the following: Screenshot from 2023-11-22 23-26-56 I was able to delete the exam without the quiz pool

Thanks for noticing this. This will be solved by this PR: [Exam mode: Exam with quiz pool deletion](https://github.com/ls1intum/Artemis/pull/7653)

**Review by matthiaslehnertum — DISMISSED** [review]

**Review by AlexanderG2207 — DISMISSED** [review]
Demonstrated in the testing session and worked as expected.

**Review by sarpsahinalp — DISMISSED** [review]
Demonstrated in the testing session and worked as expected.

**Review by mateusmm01 — DISMISSED** [review]
Demonstrated on ts5 during testing session. Looked good and worked as expected!

**Review by mateusmm01 — DISMISSED** [review]
Reapprove

**Review by Santia-go — APPROVED** [review]
Tested on TS5 
Working as expected and some comments that I discuss with the developer will be implemented in a follow PR

**Comment by Ceiridge** [comment]
Works as expected on ts3
Student exams are generated successfully
image

**Review by vinceclifford — DISMISSED** [review]
Works as expected, tested during testing session

**Review by lennart-keller — APPROVED** [review]
Tested on ts3 in testing session. Works well.

**Review by valentin-boehm — APPROVED** [review]
Tested in testing session, works as expected

**Review by mateusmm01 — APPROVED** [review]
Demonstrated during testing session. Looks good!

**Review by LenaKahle — DISMISSED** [review]
Approve, tested on ts2.

**Review by LenaKahle — DISMISSED** [review]
Reapprove.

**Review by valentin-boehm — DISMISSED** [review]
Reapprove

**Review by lennart-keller — DISMISSED** [review]
Reapprove

**Review by basak-akan — DISMISSED** [review]
Demonstrated during the testing session, worked as described

**Review by sarpsahinalp — DISMISSED** [review]
Demonstrated during the testing session, worked as described

**Review by mateusmm01 — DISMISSED** [review]
Reapprove

**Review by Santia-go — DISMISSED** [review]
Tested on TS2 

image

Working as expected! 

image

**Review by lennart-keller — APPROVED** [review]
Reapprove after merge conflict

**Review by basak-akan — APPROVED** [review]
Reapprove after merge conflict resolved

**Review by Santia-go — APPROVED** [review]
Re-approve after merge conflict resolved. 
Nothing is broken after it

**Review by farisd16 — APPROVED** [review]
Tested on ts2, works as expected

**Review by bassner — APPROVED** [review]
Tested on TS3. LGTM 👍

**Pull request merged**
