### PR TITLE
Update apollon version to version 2.2.5

### LINKED ISSUE #1437: Embedded example solution is cut off for modeling exercises
### Describe the bug

In some cases, not the entire example solution is shown when assessing a modeling exercise. It appears to ignore labels on associations and only show the area delimited by objects and associations. This seems to occur both in the 'Exercises' view (when viewing the details of the exercise) and when assessing submissions.

#### To Reproduce

1. Create a modeling exercise that has a sample solution that fulfills the description above (an example can be found as a screenshot below - in our case, this was a communication diagram)
2. Navigate to 'Course Management'.
3. Go to 'Exercises' of the corresponding course
4. Click the ID of the newly created exercise.
5. Scroll to the embedded sample solution. Its labels should be cut off.

Additionally, you may follow the following steps to find another occurrence of this:

6. Submit a solution to the exercise
7. Navigate to 'Course Management' and go to the Tutor Course Dashboard of the corresponding course.
8. Navigate to the Exercise Dashboard of the exercise in question.
9. If available, start an assessment on any submission (or, alternatively: click on "Instructions" on the right)
10. Scroll to the embedded sample solution. Its labels should be cut off without the ability to scroll.

#### Expected behavior

The entire sample solution should be shown, including the labels on associations (including the ability to scroll if necessary).

#### Screenshots

This is an example solution that has caused this issue. Note that there are messages/labels that are above the topmost association. Note that I have cropped the screenshots in order to prevent revealing too much about the exercise (this task is the L03E03 Model a Communication Diagram exercise from EIST 2020 - if you need the full images, please contact me directly)

image

This is the resulting view of the example solution in the assessment view. The corresponding messages/labels are now gone and there is a label on the left that is cut off by the surrounding container (without the ability to scroll).

image

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Google Chrome v81.0.4044.138
</pre></details>

### PR DESCRIPTION
**Pull request by TobiasPr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

Update Apollon library version to include the newest features and bugfixes. Fixes #1437 

### Description

- layoutable diagram messages for example solutions-> texts of connectiosn are considered when calculating bounding box and text on connections is not cut off anymore, see bug description https://github.com/ls1intum/Artemis/issues/1437
- updated dependencies
- limiting resize function to values of 20 -> connections can always be drawn straight when connecting two elements, see https://github.com/ls1intum/Apollon/issues/104
- elements know which connection types they support and a default is selected accordingly
- tablet support for apollon diagrams
- unsaved changes are not dismissed when closing popover, see https://github.com/ls1intum/Apollon/issues/28

### Steps for Testing

**Please note that I copied the screenshots to the individual test descriptions, because it's several issues which are addressed in this apollon release. I hoped that by copying the screenshots directly to the tests it would be easier to understand what to test**

#### Regression tests for communication diagrams
1. load a communication diagram which was created in a previous Artemis version
2. check if all elements are displayed correctly

#### Layoutable diagram messages

Example of cutoff descriptions when creating an example solution
**before**
pr1
pr2

**after**
screenshot_24

##### Communication diagrams
1. create a modeling exercise with a communication diagram
2. create a sample solution for that exercise (edit exercise - sample solution)
3. create a connection between two diagram elements
4. add messages, so that the text would be out of the diagram bounds
5. check the example solution (tutordashboard when assessing the exercise). Make sure that the messages are still visible and the messages are not cut off in the example solution

##### ClassDiagram, Deployment, Component and Activity Diagram
1. create a modeling exercise with these diagrams
2. participate in the exercise
3. create a connection between two diagram elements
4. add a description/text to the connection, so that the text would be out of the diagram bounds (see screenshot)
5. check that the layout is adapted, so that the whole description/text on the connection is still visible and the message is not cut off

** eg. deployment diagram after **
screenshot_23

#### Tablet support for apollon diagrams
**Note: This is only basic support, so that you should be able to model diagrams on a tablet. No feature is optimized for tablet user experience**
1. Open Artemis on a tablet and navigate to a modeling exercise
2. Model diagrams, including at least:
   - creating 3 elements
   - connecting 3 elements
   - reconnecting 1 element
   - editing an element (dbl click + change properties)
   - delete an element
3. feel free to comment any usability issue, I will put them in a separate ticket

#### Unsaved changes are not dismissed when closing popover

1. create a class diagram
2. create a class
3. open the popover (dbl click on element)
4. add a new attribute, but do not change the focus, so that it is created while the popover is still open
5. click somewhere else in the diagram (outside of the popover)
6. expected behavior: popover is closed, attribute is created

dismiss_popover

### CODE REVIEW

**Review by tiffca — CHANGES_REQUESTED** [review]
Nice work! Most of the testing went smoothly in Chrome! 

Tested in artemis test server 1 (tiff-test course, using test user 1, 2): 
Behavior I noticed:
- I was not able to edit anything (none of the tests passed) in Firefox/Safari. Not sure if others saw this behavior. It could be related to my new course setup, so I'm checking further. 
- I was not able to edit anything on a tablet, using Safari on iPad. 
- Other diagrams worked well, only noticed different behavior for "class" and "use case" details below.

If these are okay I can go ahead and approve instead. 

Details below (tested in Chrome): 

Regression tests for communication diagrams – good.
-Layoutable diagram messages – done, no issues. 
Communication diagrams – done, no issues. 
Other diagrams -
- tested deployment, (firefox doesn’t work) – good.
- component,- n/a
- class - **note**: "role" doesn't fit to window as expected, but assuming this is b/c role is a different type of field than the others, so not considered an error. screenshot accidentally says use case it should say class (it's a class diagram)
image
- Object – n/a
- Activity – works well – good. 
- Use case – resizable instead of fit-to-window  – **assume okay**. 
2168 - use case

Tablet support for apollon diagrams - **error**.
- Safari on iPad. Very buggy, wasn’t able to add any elements or do anything. 
I can create the bug tickets and update. 

Unsaved changes are not dismissed when closing popover – good - works as expected. 


behavior of firefox: 
2168-firefox
maybe it's a user error? I'm testing with test user 1-2 which seems to have admin access, checking further

**Review by MaisiKoleni — CHANGES_REQUESTED** [review]
I have the same problem that @tiffca described with Firefox, I cannot model anything. The web console does not show any errors (noticed that as well when testing #2179).

**Comment by TobiasPr** [comment]
Thank you to the both of you for testing. I also encounter the error on firefox, will investigate what the error is -> converting to draft

**Comment by TobiasPr** [comment]
`if(event instanceof TouchEvent)` made browsers other than chrome crash without a console error... 
I already fixed it but will do some more testing on my own this evening

**Comment by MaisiKoleni** [comment]
What is the status here? I guess it is not ready for review right now. Can I help somehow? I need this for #2179.

**Comment by TobiasPr** [comment]
> What is the status here? I guess it is not ready for review right now. Can I help somehow? (I need this for #2179.)

just updated the version, the issue should be fixed in there (correct bounding box of connection text for class like diagrams + fix for firefox and safari)

**Review by kloessst — CHANGES_REQUESTED** [review]
Testing went fine for Chrome. Unfortunately there is a problem in Firefox. The diagrams jump out of the view after a new element is added.

**Review by kloessst — APPROVED** [review]
Works fine. The bug on Firefox was also fixed! 💯

**Review by tiffca — APPROVED** [review]
Firefox and Safari work well. Previous behavior is the same but assuming it's as designed, for example use case and class diagram. Still having issues on ipad, but discussed that a different issue would be opened.

**Pull request merged**
