### PR TITLE
[Bugfix] Fix Problem Statement in Programming Assessment Instructions

### PR DESCRIPTION
**Pull request by fde312**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) locally.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Previously the problem statement showed that all tests failed even though the test did actually passed (seen in the result details/feedback)

### Description

- Added new input to handover the programming participation during the manual assessment

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Assess a Programming Exercise
4. Check that the passed tests are correctly displayed in the problem statement of the assessment instructions

### Test Coverage

Nothing changed.

### Screenshots

image

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]

**Review by EneaGore — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts1, works as expected.

**Review by FrankeLukas — APPROVED** [review]
Followed the steps, worked as advertised.

**Review by simonzilker — APPROVED** [review]
Tested with @marvinchimeka on ts1. Works as described

**Review by marvinchimeka — APPROVED** [review]
tested in testing session. approve

**Review by krusche — APPROVED** [review]

**Pull request merged**
