### PR TITLE
[Bugfix] GitLab TA Permissions / Readonly Permissions

### PR DESCRIPTION
**Pull request by dfuchss**
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

Only important in GitLab Context:

It is not possible as GUEST to see the code of private repos (See [GitLab Docu](https://docs.gitlab.com/ee/user/permissions.html)).
Therefore, a tutor (TA) cannot access the student's code, as should be supported by the GUI.
In addition, students will not be able to access their "own" repos as GUEST after the deadline has passed.

### Description

I have changed the GUEST visibility to REPORTER, so code access should be possible now.

### Steps for Testing

1. Create a programming-exercise.
2. A student submits a solution
3. A tutor (TA) assesses this solution; during that, the tutor tries to access the repository of the student in gitlab

### Test Coverage
Should be unchanged.

### CODE REVIEW

**Comment by dfuchss** [comment]
I hope the reasons for the proposed changes are apparent. If there are still questions, feel free to ask here, or directly in Slack .

**Review by sleiss — APPROVED** [review]
I've not tested it, but the code changes look reasonable.

**Comment by dfuchss** [comment]
I think the changes only affect new courses and old courses (iff you change group memberships).
At our test system I've encountered no problems so far.
But it may be good that you test it on your test systems as well.

At least that I can check "I tested all changes and all related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de." :)

**Review by krusche — APPROVED** [review]

**Comment by krusche** [comment]
Unfortunately, client and server tests on Github Actions fail and are not executed on our Bamboo CI server.
@dfuchss as discussed, could you add the corresponding branch in our Github repo as well and re-create this PR?

**Comment by dfuchss** [comment]
I'll do that this afternoon.
I'll also link the new PR to that one.

**Comment by dfuchss** [comment]
See #2996

**Pull request closed without merging**
