### PR TITLE
`Development`: Enable standalone problem statement for exam exercises

### PR DESCRIPTION
**Pull request by terlan98**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x]  I added multiple integration tests (Spring) related to the features (with a high test coverage).

### Motivation and Context

The new standalone problem statement introduced in #6427 is limited to non-exam exercises.  However, the Themis app also needs to render the problem statement for exam exercises. This PR **enables access to exam exercises** for users who are **at least teaching assistants** in the course.

### Description

Modified one `if` statement to allow users who are at least teaching assistants for the course to view the problem statement.

### Steps for Testing

Prerequisites:
- Light mode enabled
- 1 Student
- 1 Tutor

###### If you are using TS1
1. Log in as Student (you can use test user 1-5 as they are already registered to the course mentioned below)
2. Navigate to the problem statement of an exercise: (https://artemis-test1.artemis.in.tum.de/courses/78/exercises/1246/problem-statement)
3. Verify that you can see the problem statement
4. Navigate to the problem statement of an exam exercise (https://artemis-test1.artemis.in.tum.de/courses/78/exercises/1952/problem-statement)
5. Verify that you can NOT see the problem statement
6. Log in as Tutor (you can use test user 6-10 as they are already teaching assistants in the aforementioned course)
7. Repeat steps 2 and 4. You should be able to see the problem statement in both cases

###### If you are using TS2
1. Log in as Student (you can use test user 1, 2, or 3 as they are already registered to the course mentioned below)
2. Navigate to the problem statement of an exercise (https://artemis-test2.artemis.in.tum.de/courses/8495/exercises/12271/problem-statement)
3. Verify that you can see the problem statement
4. Navigate to the problem statement of an exam exercise (https://artemis-test2.artemis.in.tum.de/courses/8495/exercises/12283/problem-statement)
5. Verify that you can NOT see the problem statement
6. Log in as Tutor (you can use test user 7 as it is already a teaching assistant in the aforementioned course)
7. Repeat steps 2 and 4. You should be able to see the problem statement in both cases

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| ExerciseResource.java | 95% | ✅ |

### Screenshots
Viewing the standalone problem statement of an exam exercise **as a student**:
error

Viewing the standalone problem statement of an exam exercise **as a teaching assistant**:
success

### CODE REVIEW

**Review by DominikRemo — APPROVED** [review]
Code LGTM

**Review by sven0311 — APPROVED** [review]
Tested on TS1. Works as expected. Code also looks good

**Review by laadvo — APPROVED** [review]
Tested on ts2, the standalone problem statement for exam exercises can be accessed as expected

**Review by SolizerCodes — APPROVED** [review]
Tested on ts1, works as expected 👍

**Review by krusche — APPROVED** [review]

**Pull request merged**
