### PR TITLE
`Exam mode`: Fix a wrong message when deleting a test run

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

It fixes the issues #9187 and #8901.

### Description

Added messages for deleting a test run

### Steps for Testing

**(You can test it with any exams. So you just need to find a course with an exam. I have already one under my course on TS6.)**
Prerequisites:
- 1 Instructor
- 1 Exam

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to the Exam
4. Click Test Run
5. Create a Test Run
6. Delete the Test Run
7. Verify that the correct message is displayed 

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Before 
image
After
Screenshot 2024-08-05 at 18 43 55
Screenshot 2024-08-05 at 18 44 07

## Summary by CodeRabbit

- **New Features**
	- Added user-facing messages for deleted test runs in both English and German localization files.
	- Enhanced user feedback regarding the status of exam submissions.

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by Strohgelaender — APPROVED** [review]
makes sense.

Can you maybe remove the quotes around the of since it's a integer and not a string? Or completely remove it since regular users won't have any use for the id anyways.

**Review by PaRangger — APPROVED** [review]
Code LGTM, Tested on TS6

**Review by anian03 — APPROVED** [review]
Tested on TS6, works as expected

**Review by ole-ve — APPROVED** [review]

**Review by Strohgelaender — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
