### PR TITLE
`Exam mode`: Fix loading of result overview in  the summary of test runs

### PR DESCRIPTION
**Pull request by florian-glombik**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
While working on [Exam mode: Fix loading of modeling exercise results in the summary of test runs #7590](https://github.com/ls1intum/Artemis/pull/7590)
I've noticed that the summary overview is not loaded properly.

This means that instructors have an experience that is further away from the student than needed when executing exam test runs.

### Description
* I have adjusted the database query `StudentExamRepository#findWithExercisesByUserIdAndExamId` to do not by default exclude all test run exams,
which introduced in [Improve performance in assessment dashboard database queries (#3081)](https://github.com/ls1intum/Artemis/pull/3081).
* Fixed the imports for tests according to our policy _(no wildcard imports)_
* Reduced code duplication in client for checking exam release date for results 
* Added client and server tests

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Student
- 1 Ended Exam with a student participation

1. `Instructor`: Create and participate in an exam test run
2. `Instructor`: Assess at least one exercise in the test run
3. `Instructor`: View the summary of the test run 
4. `Instructor`: See that the summary table is loaded _(and no errors regarding the endpoint `/courses/{courseId}/exams/{examId}/student-exams/grade-summary` are displayed in the network tab)_
5. `Instructor`: Verify that you can still view student exams of ended exams
6. `Student`: Verify the exma summary is still displayed properly

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------------:|
| [exam-participation.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5759/latest/artifact/shared/Coverage-Report-Client-Tests/app/exam/participate/exam-participation.service.ts.html) | 77.95% |                           ✅ |
| [exam-result-summary.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5759/latest/artifact/shared/Coverage-Report-Client-Tests/app/exam/participate/summary/exam-result-summary.component.ts.html) | 91.35% |                          ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------------:|
| [StudentExamRepository.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5759/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.repository/StudentExamRepository.html) | 96% |                            ✅ |
| [ExamRegistrationService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5759/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.exam/ExamRegistrationService.html) | 89% |                            ✅ |
| [ExamService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5759/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.exam/ExamService.html) | 93% |                            ✅ |
| [ExamSubmissionService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5759/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.exam/ExamSubmissionService.html) | 100% |                            |
| [StudentExamResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5759/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/StudentExamResource.html) | 86% |                          ✅ |

#### New
The summary table is displayed (and the grade and grading key if the test run was assessed and a reading key is defined)

Picture

#### Old
* Result Summary section is not displayed as it cannot be loaded
* error message in the console

```json
{
    "headers": {
        "normalizedNames": {},
        "lazyUpdate": null
    },
    "status": 404,
    "statusText": "Not Found",
    "url": "http://localhost:9000/api/courses/279/exams/10/student-exams/grade-summary?userId=1",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for http://localhost:9000/api/courses/279/exams/10/student-exams/grade-summary?userId=1: 404 Not Found",
    "error": {
        "type": "https://www.jhipster.tech/problem/problem-with-message",
        "status": 404,
        "path": "/api/courses/279/exams/10/student-exams/grade-summary",
        "message": "Requested resource does not exist."
    }
}
```

Picture

### CODE REVIEW

**Review by georgyia — APPROVED** [review]
tested this manually on the ts2. I could see the summary, test run worked

**Review by sarpsahinalp — COMMENTED** [review]
Demonstrated in testing session. During test run result overview was not visible

**Comment by florian-glombik** [comment]
> Demonstrated in testing session. During test run result overview was not visible

Yes, the issue is resolved with https://github.com/ls1intum/Artemis/pull/7629/commits/656522af885d6c8a846a75ff60c765afb41c5b93 - @georgyia you most likely have tested it with an exam that already had the results release date in the past

**Review by Jan-Thurner — APPROVED** [review]
Got a demo on TS1 during a Testing session. Worked beautifully!

**Review by vinceclifford — APPROVED** [review]
Demonstrated during testing session. Works as expected.

**Review by MichaelOwenDyer — APPROVED** [review]
Tested in testing session and works excellent

**Review by RY997 — APPROVED** [review]
Tested in a testing session, worked as expected

**Review by rstief — APPROVED** [review]
Demo in testing session. Looks good.

**Review by JanaNF — APPROVED** [review]
Demonstrated in testing session on TS1. Worked as expected.

**Pull request merged**
