### PR TITLE
`Development`: Update server dependencies

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Keep server dependencies up to date

### Description
* Mainly update Spring Boot, Spring and Spring Security to the latest minor releases (there should be no breaking changes)
* Due to an issue, I had to change how we enable Problem Support based on Zalando
* I was also able to remove an unused dependency to protobuf and to delete an unused class
* I fixed some deprecation warnings

### Steps for Testing

1. Navigate through Artemis, participate in exercises and make sure nothing breaks

#### Exam Mode Testing

1. Navigate through Artemis, participate in exams and make sure nothing breaks

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by az108 — COMMENTED** [review]
If you hand in early in the exam mode a Internal Server Error arises.

image

**Review by pzdr7 — APPROVED** [review]
Tested on TS2.

Things I've tried:

- Participate & submit multiple times: Programming, modeling, text, file upload
- Participated in a quiz

Exam mode:

- Participated in an exam with all exercise types
- Handed in early; did not get an error (@az108 can you provide more details on how to trigger it?)

**Review by florian-glombik — APPROVED** [review]
The code looks good to me 

Tested the following scenarios on ts3 (3 nodes)
* Programming Exercise (Java, Gradle)
     - template + solution build as expected
     - submission + build result without problems
* Quiz
   - multiple choice question
* Modeling (Class Diagram)
   - submission + grading

Exam Mode
* Programming Exercise (Java, Gradle)
* Modeling Exercise
* Text Exercise
* Quiz Exercise (Multiple Choice Question)
* File Upload Exercise

Submission and participation worked fine, results were displayed properly in summary.

I also submitted an empty exam early and could not reproduce the issue mentioned by @az108

**Review by pzdr7 — APPROVED** [review]
Reapprove after merge conflicts

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS3, seems to work as usual :+1:

**Review by Jan-Thurner — APPROVED** [review]
Tested on TS3. Still works as expected.

**Review by BBesrour — APPROVED** [review]
Tested locally and TS3, works as expected with no errors
- Creating exam with programming exercise
- participating as a student
- Creating normal exercise and participating as a student

**Review by julian-christl — APPROVED** [review]
Tested on TS2
Participated in serveral exercises, moved through several pages, found no issues.

**Review by rstief — APPROVED** [review]
Code Changes LGTM

**Review by laadvo — APPROVED** [review]
Code changes look good

**Pull request merged**
