### PR TITLE
Notification Sidebar

### PR DESCRIPTION
**Pull request by sascha11110**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] ~~Server: I added multiple integration tests (Spring) related to the features~~
- [x] ~~Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)~~
- [x] ~~Server: I implemented the changes with a good performance and prevented too many database calls~~
- [x] ~~Server: I documented the Java code using JavaDoc style.~~
- [x] ~~Client: I added multiple integration tests (Jest) related to the features~~
- [x] ~~Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)~~
- [x] ~~Client: I documented the TypeScript code using JSDoc style.~~
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
Some future functionalities will be added to the notification system and to maintain clarity, the notifications should be displayed in a sidebar. This is a draft of the sidebar:

image

### Description
This PR prepares the future sidebar. Only existing functionality has been incorporated into the new UI.

Further refactoring of the existing code will be part of a future PR.

### Steps for Testing
1. Log in to Artemis
2. Click on the notification icon in the top navigation
3. Open/close the sidebar (cross-browser)
4. Check the pre-existing functionality (notification count, evaluation of *recent* notifications)

### Screenshots
image

### CODE REVIEW

**Comment by krusche** [comment]
@sascha11110 Can you please double check that no guided tutorial is broken due to these changes?

**Comment by sascha11110** [comment]
@krusche The guided tutorial still works as expected on the test server.

--------

This PR should be merged after/simultaneously with https://github.com/ls1intum/Artemis/pull/1323.

**Comment by sascha11110** [comment]
@F4lka and @filip-gregurevic would be nice if you could re-approve :-) Due to a merge conflict I had to add a _not-merge-develop_ commit: https://github.com/ls1intum/Artemis/pull/1304/commits/51a2988842da5fcf1e5ae7b2a6d241ad5a8d158b

**Comment by HanyaElhashemy** [comment]
Also if the notified exercise was deleted  and the user clicks on its notification then you will get a console error and nothing will change in the UI. Maybe consider automatically deleting notifications that are no longer valid or notify the user when they click on the notification that they are not valid anymore
image

**Comment by sascha11110** [comment]
@HanyaElhashemy Thanks for testing! I added the color stripes to make it easier to differentiate the different notifications. Stephan decided that we shouldn't save explicitly which notifications were read by the user at this would introduce another database-intensive many-to-many relation :-)

Your suggestion on deleting notifications if the corresponding entity is deleted is pretty helpful! Way out of scope of this PR but a good feature to add in the future :-) Thanks!

**Pull request merged**
