### PR TITLE
`General`: Fix broken color picker

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
The color picker in the course update view did not open onClick.

### Description
This PR solves this by stopping the eventPropagation within the color picker, so that the functionality doesn't rely on who the parent component opens the picker.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course

1. Log in to Artemis
2. Navigate to Course Administration
3. Click on Edit
4. Click on the Color Picker and Verify that it opens
5. Save Course and verify that the color has been saved.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [category-selector.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5836/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/category-selector/category-selector.component.ts.html) | 97.14% | ✅ |
| [color-selector.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5836/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/color-selector/color-selector.component.ts.html) | 100% | ✅ |

### Screenshots
image

### CODE REVIEW

**Review by reschandreas — APPROVED** [review]
tested locally, works now! thanks! cde also lgtm!

**Review by egekurt123 — APPROVED** [review]
manually tested on ts2, works as expected

**Review by laurenzfb — APPROVED** [review]
Code lgtm!

**Review by LenaKahle — APPROVED** [review]
Approve, tested on legacy ts11.

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts2 worked as expected.

**Pull request merged**
