### PR TITLE
`Lectures`: Add bottom padding in course details

### PR DESCRIPTION
**Pull request by JohannesWt**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context

If a lot of lecture units are displayed in the course-lecture-details page the last lecture unit is aligned with the bottom of the page.

### Description

This PR adds a small padding to the lecture unit list in the course detail page so that the last lecture unit has some space to the bottom of the page.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

unchanged

## Summary by CodeRabbit

- **New Features**
  - Enhanced visual presentation of lecture details with improved spacing and alignment.
  
- **Style**
  - Adjusted padding and margin properties for better readability and layout cohesion within the course lecture details.

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by edkaya — APPROVED** [review]
Code

**Review by pzdr7 — APPROVED** [review]
Tested on TS1.

Before:

image

After:

image

Lgtm 👍

**Review by SimonEntholzer — APPROVED** [review]

**Review by sarpsahinalp — APPROVED** [review]
Code looks good, tested locally!

**Review by rabeatwork — APPROVED** [review]
maintainer approve

**Review by krusche — APPROVED** [review]

**Pull request merged**
