### PR TITLE
`Development`: Move rotate icon css to global style

### PR DESCRIPTION
**Pull request by rstief**
# Ideally test on ts3 so you can check the css still works for standardized competencies

#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
There are a few styles used for rotating arrows (`rotate-icon`, `rotate` and `chevron-position`) that are repeated in many style files.

### Description
This PR moves these styles to the global scss file. It also fixes an UI bug for the communication card (see screenshot below)

image

### Steps for Testing
- 1 Admin
- 1 Course with exam
- Ideally use ts3 and the provided links :)

Verify Exams:
1.Log in to Artemis 
2. [On ts3: View Summary](https://artemis-test3.artemis.cit.tum.de/course-management/19/exams/11/test-runs/32/summary)
3. See that the collapsible arrows in the UI work
(alternatively conduct a test run of an exam yourself and verify the summary afterwards)

Verify Sidebar:
6. Go to Course (Student View) -> Exercises
7. See that the collapsible arrows in the sidebar for exercises still work

Verify Standardized Competencies
8. Go to Server Administration -> Feature Toggles -> Enable StandardizedCompetencies
9. Go to Server Administration -> StandardizedCompetencies
10. See that the collapsible arrows still work (left side)
11. Go to Course Management -> Competencies -> Import -> Import Standardized Competencies
12. See that the collapsible arrows still work (left side)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage
unchanged

### CODE REVIEW

**Review by edkaya — APPROVED** [review]
code lgtm

**Review by florian-glombik — APPROVED** [review]
Thanks for reducing the code duplication 👍 

Approving the code

**Review by marlon-luca-bu — APPROVED** [review]
Code LGTM 👍

**Review by matthiaslehnertum — APPROVED** [review]
Works as intended!

**Review by Jan-Thurner — APPROVED** [review]
Tested on TS3. Works as expected.

**Review by MaximilianAnzinger — APPROVED** [review]
Maintainer approved

**Review by egekurt123 — APPROVED** [review]
Code LGTM

**Pull request merged**
