### PR TITLE
`Assessment`: Fix an issue during the conversion of dates in the submission result component

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

Fix sentry issue: [https://sentry.ase.in.tum.de/organizations/artemis/issues/28726](https://sentry.ase.in.tum.de/organizations/artemis/issues/28726)

### Description

The exercise date were not converted from strings to dayjs objects when the submission/participation was loaded from the server, leading to an error in the console.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Text exercise with a due date

1. Log in to Artemis
2. Participate in the exercise and try to submit a text
3. Check that there is no error in the console

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Comment by undernagruzez** [comment]
Tested on TS2, participated in an exercise, and tried to submit text => there were no errors in the console

**Review by 1999Markus — APPROVED** [review]
Code LGTM!

**Review by TheZoker — APPROVED** [review]
LGTM 👍

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Pull request merged**
