### PR TITLE
`Exam mode`: Show programming exercise submissions in the exam live statistics dashboard

### PR DESCRIPTION
**Pull request by Dominik-Weinzierl**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Exam with Exam Live Statistics enabled
- 1 Programming Exercise

1. Log in to Artemis
2. Create an Exam with Exam Live Statistics enabled
3. Participate with the student
4. Submit a programming exercise via the online editor
5. Verify that the exercise section and activity section shows the correct data

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by mallgaier — APPROVED** [review]
Very sophisticated change 👍

**Review by yuling-sun — APPROVED** [review]
Tested on TS1, Works as described.

**Review by minrows — APPROVED** [review]
Tested on ts1 during testing session. Works as described. 👍

**Review by akesfeden — APPROVED** [review]
Tested on TS1 during testing session, live statistics are updated as expected.

**Comment by Dominik-Weinzierl** [comment]
Wrong button :eyes:

**Review by babyygemperor — APPROVED** [review]
Tested on ts1, works as described

**Pull request closed without merging**
