### PR TITLE
Feature/markdown pdf support

### PR DESCRIPTION
**Pull request by Olimbia23**
### It is reopened from the internal repo in order to check the client tests in Bamboo.
All tests in bamboo are working now. 

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Feature request: #2509

### Description
- added pdf into the accepted file extension.
- link generation for pdf with the corresponding file name.

### Steps for Testing

1. Log in to Artemis
2. Drag & Drop in any markdown editor component

### Screenshots

demo

### Issue
Issue with copy/paste of pdf files. 
The clipboard sees any file copy/pasted as `image.png` (instead of `file.pdf`) as reported [here](https://stackoverflow.com/questions/34508763/why-chrome-convert-the-image-data-to-image-png-mime-type-when-paste) and [here](https://ourcodeworld.com/articles/read/491/how-to-retrieve-images-from-the-clipboard-with-javascript-in-the-browser) and [here](https://stackoverflow.com/questions/58924013/javascript-paste-event-getting-file-name)
After my research I believe there is no way to fix this problem. However, I am very pleased for suggestions.

P.s. this issue occurs in Github Markdown editor as well.

### CODE REVIEW

**Review by imstreetspirit — APPROVED** [review]
I tried to add pdf inside of the markdown editors which I know of being used, it works as described.

**Review by maximilianbergmann — CHANGES_REQUESTED** [review]
Tested on TS3. Works in editors like in problem statements of exercises. In the Registration Confirmation Message it did not work - is a simple textfield and no editor anymore.

**Review by joschahenningsen — APPROVED** [review]
Works as expected

> In the Registration Confirmation Message it did not work - is a simple textfield and no editor anymore.

The branch was out of date

**Review by maximilianbergmann — APPROVED** [review]
https://github.com/ls1intum/Artemis/pull/3303#pullrequestreview-645520201

Then everything works

**Review by cremertim — APPROVED** [review]
Tested on ts3, works as expected

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Worked for me

**Review by NicolasUllmann — APPROVED** [review]
Tested on server 1. Worked as expected.

**Pull request merged**
