### PR TITLE
`Quiz exercises`: Save Apollon diagram when generating drag and drop question

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
When importing an Apollon Diagram into an Quiz Question, the apollon diagram did not save changes if you did any.

### Description
This PR awaits the diagram save before generating the quiz question.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Create or Edit quiz exercise
3. Click Add Apollon diagram drag and drop question
4. create new apollon diagram
5. add elements & make some interactive
6. Click Generate without clicking save
7. Click again on create apollon diagram drag and dop question
8. select your diagram changes are still there

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
image
image
image

## Summary by CodeRabbit

- **New Features**
	- Enhanced the diagram saving process to be asynchronous, improving response handling and feedback.
- **Refactor**
	- Improved the `editDiagram` method to ensure diagrams are saved prior to quiz question generation.
- **Bug Fixes**
	- Concealed internal details for security purposes.

### CODE REVIEW

**Review by pzdr7 — APPROVED** [review]
Tested on TS2

All changes to the diagram are saved when hitting the Generate button -> works as expected

**Review by basak-akan — APPROVED** [review]
Tested on TS5, worked as described

**Review by Gusti2010 — APPROVED** [review]
Manually tested on ts11_Legacy. Works as expected!

**Review by AntonGeTUM — APPROVED** [review]
Manually tested, works as expected

**Review by rabeatwork — APPROVED** [review]

**Pull request merged**
