### PR TITLE
`General`: Fix data table icon color

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context
The icon colours should be consistent.

### Description
Removed the unnecessary variable that overrides the colour just for the right icon.

### Steps for Testing

Prerequisites:
- 1 Artemis user

1. Go to some page that contains a data table that contains >10 data points, e.g., list of users, participants, submissions, …
2. Check the icons in the bottom-right in both dark and light mode. If the icons are not there, reduce the page size in the top-left.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
Before:
Screenshot 2022-11-28 at 16-43-15 Groups
After:
Screenshot 2022-11-28 at 16-42-35 Groups

The background colour is the same in both light and dark mode.

### CODE REVIEW

**Review by timo07k — APPROVED** [review]
Works as expected in light and dark mode. Tested on TS1.

**Review by simon-hng — APPROVED** [review]
code

**Review by nikirovast — APPROVED** [review]
Looks as expected on ts1

**Review by LiaLism — APPROVED** [review]
Works as expected in both light and dark mode. Tested on ts1.

**Review by JohannesStoehr — APPROVED** [review]
Looks good to me

**Pull request merged**
