### PR TITLE
`Lectures`: Make the connection between learning objectives clearer

### PR DESCRIPTION
**Pull request by sebastiannikles**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
In a previous PR I added a wizard mode for editing/creating lectures. There it's become possible to directly create/edit learning goals and connect them to units. However, in several tests it's become obvious that many users cannot see the connecting table at the bottom of the form and were not sure how to connect goals and units.

### Description
In order to fix this, the learning goal step now shows another option for each goal "Connect", which will only open the connecting table so it's clearer and more obvious for the users where to connect goal and unit.

### Steps for Testing
Prerequisites:
- 1 Instructor who can create lectures

1. Log in to Artemis
2. Navigate to Course Management
3. Edit a lecture
4. Go to the learning goals step
5. (If no goal exists, create one)
6. The learning goal in the list should have the new connect option
7. Clicking that opens the table for connecting the units

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots
Bildschirm­foto 2023-01-26 um 02 15 25
Bildschirm­foto 2023-01-26 um 02 15 32

### CODE REVIEW

**Review by Vinicius-Agreste — DISMISSED** [review]
Worked as expected. Tested on ts1. It responds well to units with a long name.

**Review by danielbode — DISMISSED** [review]
Works as expected. Tested on ts1.

**Review by frederik-kt — APPROVED** [review]
Tested on TS2. Button is there and connecting to a lecture unit works.

**Review by ge65cer — COMMENTED** [review]
We have renamed "learning goals" to "competencies" in the client, I'd advise changing it here as well. (Also in the German translation.)
Screenshot

**Comment by krusche** [comment]
@ge65cer good point, I renamed the last occurrences to Competency / Kompetenz now. When all the checks pass, we can merge the PR

**Pull request merged**
