### PR TITLE
Improve the editor role based on first feedback round

### PR DESCRIPTION
**Pull request by JohannesStoehr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Description

Editor can now change the weights of tests. Additionally the grading page button is shown in the overview page of an exercise.

### Steps for Testing

1. Go to the overview of a programming exercise
2. Click on "Grading"
3. Change the grading (weight of tests and penalty for SCA)

### CODE REVIEW

**Review by FuchsDominik — APPROVED** [review]
Only small code changes, look reasonable to me 👍

**Review by niclasschuemann — CHANGES_REQUESTED** [review]
Tested it on TS1, saving the SCA options now works with an editor! Code looks also good to me, but nothing major was changed anyway. I assume the refactoring in the ProgrammingSubmissionIntegrationTest was due to code style issues?

Besides that one small issue occurred while testing: The Reset button on the Code Analysis Categories page does not work for the editor. This behavior can be seen here:
forbidden

**Comment by florian-glombik** [comment]
> I assume the refactoring in the ProgrammingSubmissionIntegrationTest was due to code style issues?
Yes, these are just issues detected by IntelliJ - only the wrong order of imports and the compliance to our 180 character limit for each line.

**Review by katjanakosic — APPROVED** [review]
Works es expected 👍

**Review by canyelten — APPROVED** [review]
Tested on T1, works as expected.

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 1. everything worked as expected.

**Review by niclasschuemann — APPROVED** [review]

**Pull request merged**
