### PR TITLE
`Development`: Add exercise update announcement e2e tests

### PR DESCRIPTION
**Pull request by muradium**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
We want to test the scenario where instructor changes the exercise problem statement during an exam run and students receive information about it.

### Description
Adds E2E tests in Playwright about instructor changing exercise problem statement, all participants receiving pop-up notification about it, and correctly displaying the differences in problem statement.

### Steps for Testing
- **Code Review**: Ensure that tests pass for valid reasons, functionality is adequately tested and check the code quality.
- **Run the tests (optional)**: Tests are executed during automatic run in CI environment. You can optionally run them locally and check if they pass.

**Steps for running the tests:**
1. Navigate to **src/test/playwright**
2. Configure Playwright using playwright.env file based on your local setup. Current configuration should work for default Artemis setup.
3. Run `npm install && npm run playwright:setup`
4. Run the test using one of the methods:
- Run `npx playwright test e2e/exam/ExamParticipation.spec.ts --grep "Instructor changes problem statement and all participants are informed"`
- Run `npm run playwright:open` to open the Playwright UI and search for the "Instructor changes problem statement and all participants are informed" test to run and observe its execution

5. Confirm that the test passes

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Release Notes

- **New Features**
  - Enhanced exercise group management interface with improved accessibility.
  - Instructors can now change problem statements and notify participants of updates.
  - New functionalities for managing exercise groups and modal interactions.
  - Improved methods for interacting with text editors in exercise creation.

- **Bug Fixes**
  - Streamlined button visibility based on user permissions.

- **Tests**
  - Added tests for new functionalities, including dynamic content updates and navigation.
  - Improved testing capabilities for exam participation and editing.

- **Chores**
  - Refactored code for better maintainability and clarity in text exercise creation.

### CODE REVIEW

**Review by iyannsch — APPROVED** [review]
E2E tests work in CI and the code LGTM

**Review by janthoXO — APPROVED** [review]
Code LGTM

**Review by SimonEntholzer — APPROVED** [review]
Ran locally, tests run through as they should

**Review by az108 — APPROVED** [review]
Ran locally and Code 👍

**Pull request merged**
