### PR TITLE
`Programming exercises`: Increase interactivity of programming feedback and grading charts

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

This PR increases the interactivity for the charts on programming feedback detail and programming grading pages

### Description

**Test case tab on programming grading:**
The following changes are made:

- By clicking on an arbitrary test case in the weight and bonus chart, the table next to the chart gets filtered accordingly. Additionally, a reset button appears that allows to reset the filtering
- By clicking on an arbitrary test case on the points chart, the user gets delegated to the corresponding statistics page
- The chart is now instantly translation sensitive

**Static code analysis tab on programming grading:**
The following changes are made:

- By clicking on an arbitrary category within the penalty bar, the table next to the chart gets filtered accordingly. Additionally, a reset button appears that allows to reset the filtering
- By clicking on an arbitrary category within any other bar, the user gets delegated to the corresponding scores page of the exercise
- The chart is now instantly translation sensitive

**Programming feedback details:**
The following changes have been made:

- By clicking on any bar in the chart, the feedback items below it get filtered accordingly. Additionally, a disclaimer is shown remembering the user that the feedback items are currently filtered

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise

1. Log in to Artemis as instructor
2. Navigate to the grading page of the exercise
3. Play around with the configurations. Test whether filtering of test cases and categories works as expected. Also make sure that the modifications persist if you first filter for one test case/ category, modify it and reset the filter again. Last but not least, make sure that your changes are saved appropriately after pressing save if they were done while filtering.
4. Make sure that the routing works as described above
5. Participate with the students on this exercise
6. Check the bar chart in programming feedback details. Make sure that the filtering works as expected and the disclaimer is shown if a filter is applied.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

`sca-category-distribution-chart.component.ts`: 90.32% | 88.4%
`test-case-distribution-chart.component.ts`: 93.33% | 88.6% 
`programming-exercise-configure-grading.component.ts`: 71.42% | 83.02%
`result-detail.component.ts`: 73.01% | 89.44%
### Screenshots

Example how the filtering of the feedback items can look:
image

Example how the filtering of the test cases can look:
image

Example how the filtering of the sca categories can look:
image

### CODE REVIEW

**Review by ole-ve — COMMENTED** [review]
Tested on TS1, nice change 👍
I encountered an issue with the scroll jumping to the top of the page when filtering in the static code analysis tab:

https://user-images.githubusercontent.com/73833780/151967796-e54e208c-63bf-472e-8d80-91128c61e50b.mov

Other than that I have one minor suggestion for the feedback dialog:
When deactivating a category (tests or code style) it may be unclear for the user how to reset that. May could be resolved by adding a border to the button.
Bildschirmfoto 2022-02-01 um 13 22 24

**Comment by willergeorg** [comment]
> Tested on TS1, nice change 👍 I encountered an issue with the scroll jumping to the top of the page when filtering in the static code analysis tab:
> 
>  Bildschirmaufnahme.2022-02-01.um.13.09.21.mov 
> Other than that I have one minor suggestion for the feedback dialog: When deactivating a category (tests or code style) it may be unclear for the user how to reset that. May could be resolved by adding a border to the button. Bildschirmfoto 2022-02-01 um 13 22 24

Thanks for pointing out these two things!
I added a border to the color legend. This should increase the usability a bit.
image

I will further inspect the problem with the auto jump. I understand that this might be annoying. But tbh I'm currently not sure how to tackle that (since this problem never came up before). I might discuss this with team members that are a bit more experienced with angular than me. If I find a solution, I will notify you.

**Review by b-fein — DISMISSED** [review]
Code review: added a few small (mostly formatting-related) comments, looks good otherwise. :+1:

**Comment by willergeorg** [comment]
> Code review: added a few small (mostly formatting-related) comments, looks good otherwise. 👍

Thanks for the code review. I incorporated your feedback in 97987e8.

**Review by b-fein — APPROVED** [review]
Code changes since the previous review make sense. Thanks! :+1:

**Review by Santia-go — APPROVED** [review]
Tested on TS1. 
Working as expected. 
image


image

Looks good!

**Review by dveljacic — APPROVED** [review]
Tested on TS2. Everything looks good. ✅

**Review by Strohgelaender — APPROVED** [review]
Tested on TS1 with @lBruchmann @VinnavanSembian @mallgaier. We did not encounter any issues, the new additions work as expected. Great work 👍

**Review by mallgaier — APPROVED** [review]
Tested together with @lBruchmann , @Strohgelaender and @VinnavanSembian 
Nice implementation!

**Review by VinnavanSembian — APPROVED** [review]
tested on ts1 with @lBruchmann @Strohgelaender @mallgaier. Everything works as expected!

**Review by lBruchmann — APPROVED** [review]
Tested on ts1. Tested together with @Strohgelaender, @VinnavanSembian and @mallgaier. Everything works as expected.

**Review by filip-gregurevic — APPROVED** [review]
Code changes look good to me 👍🏼

**Pull request merged**
