### PR TITLE
`Development`: Use assertions consistently

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.

### Motivation and Context

A discussion sprung up in #5162 regarding the use of assertions. This PR makes the use of assertions consistent in our codebase.

### Description

I've changed `toBe(true)` → `.toBeTrue()`, `toBe(false)` → `.toBeFalse()` and also `.toHaveBeenCalledTimes(1)` → `.toHaveBeenCalledOnce()`.

#### Code Review
- [x] Review 1
- [x] Review 2

### CODE REVIEW

**Review by SimonPaul02 — APPROVED** [review]
Reviewed half of the code. LGTM👍

**Review by yuling-sun — APPROVED** [review]
The changes look fine for me. Looked at around half of the changes.

**Review by Strohgelaender — COMMENTED** [review]
Have you just overlooked those or is there a reason for this?
grafik

**Comment by Dominik-Weinzierl** [comment]
I guess this will cause many merge conflicts - we should wait until the large PRs are merged :+1:

**Review by Strohgelaender — APPROVED** [review]

**Pull request merged**
