### PR TITLE
Remove old REST endpoint to check plagiarism for text exercises

### PR DESCRIPTION
**Pull request by philippbauch**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context
The current system still has a REST endpoint that was used to detect plagiarism for text exercises using different comparison strategies. Since we integrated JPlag to perform the plagiarism detection for text exercises, we don't need the old endpoint and service methods anymore.

### Description
I removed the old REST endpoint `/text-exercises/{exerciseId}/check-plagiarism` and all its related service methods. Additionally, I removed the corresponding method to call this endpoint in the client.

### Steps for Testing
Just make sure that plagiarism detection for text exercises still works. Because only unused methods have been cleaned up, nothing should have changed for the user.

### CODE REVIEW

**Review by stefanwaldhauser — APPROVED** [review]
Looks like good refactoring :)

**Review by airelawaleria — APPROVED** [review]
tested on ts1

**Review by simonzilker — DISMISSED** [review]
Everything works as usual :)

**Review by krusche — APPROVED** [review]

**Review by sebastiantpeter — APPROVED** [review]
Tested on ts1. Plagiarism check still works.

**Review by JohannesWeiss — APPROVED** [review]
Still works as expected.

**Review by marvinchimeka — COMMENTED** [review]
Works as intended.

**Pull request merged**
