### PR TITLE
`Text exercises`: Enforce maximum characters in client

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Issue number 24 found during [exam testing](https://confluence.ase.in.tum.de/display/ArTEMiS/Testing+Session+11.07.2022).
While the server rejects text submissions longer than 30.000 characters, this limit was not enforced in the client.

### Description

Adding a max-length attribute to the text area should fix this problem.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam with a Text Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Try to paste text ([lorem ipsum](https://bavaria-ipsum.de/)) longer than 30.000 characters into the text exercise

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

_unchanged_

### CODE REVIEW

**Review by manuelmanso — DISMISSED** [review]
Code looks good

**Review by bassner — CHANGES_REQUESTED** [review]
Tested this in Firefox, Safari and Chrome - in all browsers you cannot paste more than 30,000 characters, no matter what you do. Works 👍 

However, I suggest to define the limit in ``src/main/webapp/app/shared/constants/input.constants.ts`` and import it from there so it can be reused and changed in a single place instead of hardcoding it twice.

#5501 introduces this constant on the server side, so we should add a hint above the client-side constant where to change it on the server side as well and the other way around, too.

**Comment by ge65cer** [comment]
@bassner Thanks for pointing that out, I will refactor the PR accordingly. 🙂

**Review by pantageepapa — APPROVED** [review]
Tested on ts1 and I cannot paste a text with over 30.000 chars into text exercise of an exam :)

**Review by yuling-sun — APPROVED** [review]
Tested on TS1. Works as described.

**Review by SimonPaul02 — APPROVED** [review]
Tested on TS1, works as expected

**Review by alaraozdenler — APPROVED** [review]
Tested on ts2, works as expected

**Review by bassner — APPROVED** [review]
Thanks for the update, looks good to me now! 👍

**Review by krusche — APPROVED** [review]

**Pull request merged**
