### PR TITLE
`Plagiarism checks`: Fix memory issues with large comparisons and add feature toggle

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

The plagiarism checks can be heavyweight and cause serious issues on the server. Also, loading the plagiarism elements by the native query might cause several issues.

### Description

This PR adds a feature toggle to disable plagiarism checks, e.g. during exams, as they can be quite heavyweight.
It also fixed some warnings in TextExerciseResource and ModelingExerciseResource and modernizes/simplifes their code with respect to authorization checks

### Steps for Testing

Prerequisites:

1 Instructor
2 Students
1 Exercise with two very similar submissions by both students (e.g. text exercise with lorem ipsum)

1a. Login to Artemis as Instructor
1b. Navigate to the exercise detail page
1c. Choose check plagiarism
1d. Detect plagiarism cases
1e. Confirm the plagiarism case

2a. Navigate to Course Detail
2b. Open Plagiarism Cases
2c. Asses the plagiarism case and save instructor statement

2a. Log in to Artemis as Student
2b. Open Notifications
2c. Click on the Plagiarism Notification
2d. Respond to the plagiarism Case

3a. Login in again to Artemis as Instructor
3b. Navigate to Course Detail
3c. Open Plagiarism Cases
3d. Assess the student's response

4a. Log in to Artemis again as Student
4b. Open Notifications
4c. Click on the Plagiarism Notification
4d. Check that the status has been updated by the instructor

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by filip-gregurevic — APPROVED** [review]
Tested it and the new feature toggle works, the plagiarism functionality works the same as before and the code changes look good to me

**Review by Malyuk-A — DISMISSED** [review]
The code changes look good.
I tested this feature again on TS3 and everything worked. (I also discussed some parts with @filip-gregurevic)

**Review by filip-gregurevic — APPROVED** [review]
Code changes since my last approval are minor and look good, especially since all server tests are successful, re-approve

**Review by Malyuk-A — APPROVED** [review]
Based on the same reasoning as @filip-gregurevic I also re-approve the latest changes.

**Pull request merged**
