### PR TITLE
`General`: Add information for manual LTI 1.3 configuration

### PR DESCRIPTION
**Pull request by manuelmanso**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.
### Motivation and Context

It is possible to dynamically register an LTI course as a tool in other Learning Management Systems. However, in Moodle, to use the dynamic registration it is necessary to be an administrator of the system. Therefore, it might be necessary in this and other cases to manually register an Artemis course in a platform. To do this, it is necessary to show the instructor a few more configuration values in the LTI Configuration page.

### Description

Adds/shows the necessary configuration values in the **course-lti-configuration-page** component

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to a course
4. Enable the online course
5. Navigate to the LTI configuration page
6. Go to the LTI 1.3 tab
7. Verify the new "Tool URL", "Initiate Login URL" and "Redirect URI" fields are present, have the correct values, and it is possible to copy them
8. Verify the english/german translations are present and are the same (as it doesn't make sense to translate them)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Branch | Line |
|------------|-------:|-----:|
| course-lti-configuration.component.ts | 75% | 100% |

### Screenshots

New fields in LTI 1.3 tab: 
image

### CODE REVIEW

**Review by rriyaldhi — APPROVED** [review]
Tested on TS2 during testing session and works as expected:
image

**Review by pellumbbaboci — APPROVED** [review]
Works as expected and code looks good. Tested on ts2

**Review by danielbode — APPROVED** [review]
Tested on ts2. I was able to copy the links and they were displayed correctly. The code also looks good!

**Review by frederik-kt — APPROVED** [review]
New values are displayed correctly.

**Review by YeetTheFirst21 — APPROVED** [review]
Tested on TS2 in testing session. Followed the steps specified and looks fine.

**Pull request merged**
