### PR TITLE
`Lectures`: Fix an issue in the automatic lecture unit processing

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
Automatic lecture unit processing does not work.

### Description
The framework PDFBox includes a bug that affects Artemis.
I downgraded the dependency from 3.0.2 to 3.0.1 and added a note that an update is currently not possible

### Steps for Testing

Prerequisites: 1 Instructor with a course

1. Create a new lecture with automatic unit processing
2. Use a lecture from the ASE chair, e.g. [Infun2324 L02 Control Structures.pdf](https://github.com/user-attachments/files/15550829/Infun2324.L02.Control.Structures.pdf) and make sure the splitting works correctly

**Please note**: the feature might not work locally. I tested it with macOS and there are weird awt exceptions. On TS6, it worked for me

#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by florian-glombik — APPROVED** [review]
Tested on ts1 with the example PDF, the lecture Units were generated properly

<details>
<summary>Test Details</summary>

image
image
</details>

**Review by az108 — DISMISSED** [review]
Tested creating lecture units with automatic unit processing and everything worked as expected 👍 . I additionally tested it with another slide deck from the chair and that also worked.

**Review by rstief — APPROVED** [review]
tested on ts1 with the provided slides, worked as expected.

**Review by pzdr7 — DISMISSED** [review]
Tested on TS1. Processing worked as expected ✅

**Pull request merged**
