### PR TITLE
`Exam mode`: Allow editing individual working time during conduction 

### LINKED ISSUE #5962: Exam: Working time extensions during active exam
### Is your feature request related to a problem?

Artemis currently allows instructors to define custom exam working times for individual students. This allows us to adjust for time compensations during exams.
However, those working times need to be defined before the start of the exam.

We want to be able to dynamically react to technical problems (etc.) during an exam and offer time extensions if students e.g. have to move to a different computer during the exam. In this situation, we want to be able to time the interruption (e.g., walking to a different room, logging in to a shared computer, etc.) and extend the working time while the exam is still running.

### Describe the solution you'd like

Within the student exam detail page, I want to be able to adjust the working time for a running exam.
The affected student should be notified within Artemis using a banner-style alert (same as for connection problems) of any extension or deduction in working time. The notification should be sent over WebSockets.

### Describe alternatives you've considered

_No response_

### Additional context

- For students disconnected from Artemis, it is acceptable if they need to reload the page for it to reflect the updated working time.
- It might be necessary to update scheduled tasks which, e.g., lock repositories at the end of the working time.

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Fix #5962

### Description

It is now possible to change the working time of individual student exams during their conduction. The change is also sent via web socket to the student and displayed as an alert at the top right of the screen.
Programming exercises should get locked at the new due date for the student.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with a programming exercise.

1. Log in to Artemis
2. Create the exam
3. Participate as both students (you can do this simultaneously)
4. Go to the student exam overview as instructor
5. Decrease the working time of one student and verify that the student gets a notification (e.g. use two browsers one for the student, one for the instructor)
6. Increase the working time of the other student and verify that the student gets a notification (e.g. use two browsers one for the student, one for the instructor)
7. Make surre that both repositories are locked at their respective due date and the student can no longer push

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| ProgrammingExerciseScheduleService.java | 75% | 87% |
| exam-participation.component.ts | 67% | 78% |

### Screenshots

Instructor view:
Bildschirm­foto 2023-01-28 um 01 08 38
Student view when time was changed:
Bildschirm­foto 2023-01-28 um 01 09 36

### CODE REVIEW

**Review by PhilipWerz — APPROVED** [review]
Everything works as expected. Time deduction/increase both show notifications. Tested on ts1.

**Review by PhilipWerz — CHANGES_REQUESTED** [review]
Links/Videos work for me. But I also have the issue @Strohgelaender pointed out. I haven't participated in the exercise and it shows me the following: 
image

Tested on TS10.

**Review by TheZoker — APPROVED** [review]
Tested on TS1 with two exams and works as expected 👍 

Edit: Sorry wrong PR!

**Review by PhilipWerz — APPROVED** [review]
Everything works as expected (Reapprove).

**Review by danielbode — APPROVED** [review]
Tested on ts1. Increasing and decreasing working time works. Repo is also not accessible.

**Review by simon-hng — COMMENTED** [review]
Code

**Pull request merged**
