### PR TITLE
Disallow the creation of exercises with negative maxPoints / bonusPoints

### PR DESCRIPTION
**Pull request by Strohgelaender**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) ~~on the test server https://artemistest.ase.in.tum.de~~ locally.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context
This PR disallows the creation of text exercises with negative points. The server just checked the maximum points for being equal to 0, not less or equal. 
This now also validates the bonus points.

Same as #3248 but on an internal branch.

### Description
- Validating the exercise against negative points on the server.
- Validate the bonusPoints based on the selected IncludedInOverallScore-value

### Steps for Testing

1. Try creating a text exercise with a negative score / negative bonus points -> not possible.
2. Try submitting the request to the server (by using the developer tools) -> the server rejects the request.

### CODE REVIEW

**Review by krusche — APPROVED** [review]
code looks good 👍

**Review by canyelten — APPROVED** [review]
Tested on TS2. It was not possible to enter negative points.

**Review by lschlesinger — APPROVED** [review]
Tested on TS3. Error message "Must be a number between 1 and 9999." was shown and exercise could not be saved 👍

**Review by joschahenningsen — APPROVED** [review]
Tested locally, looks good!

**Review by imstreetspirit — APPROVED** [review]
tested on ts3. seems to work as expected

**Review by ivohashamov — APPROVED** [review]
Code changes make sense

**Review by NicolasUllmann — APPROVED** [review]
Worked for me

**Review by real-dmy — APPROVED** [review]
Tested on TS1. Works well.

**Pull request merged**
