### PR TITLE
`General`: Make course card clickable again

### LINKED ISSUE #4538: Course cards are currently not clickable
### Describe the bug

Currently, the course card is not a link to the exercise overview any more. This is the case due to some interferences between the link and ngx-charts mouse event handling. 

### To Reproduce

1. Go to Course overview
2. Click on a course card
3. Nothing happens anymore

### Expected behavior

The course card should be clickable again. Ideally, it should be a link that handles right click, left click and middle click events.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

This PR fixes #4538 
### Description

As the missing link decreased the user experience, it is added again. There is some interference between link and the tooltips of the chart, so I increased the z-index of the chart. In order to make this part at least clickable as well, I handle the click via the angular event emitter. 
This solution is not optimal as some parts of the card are now clickable like a normal link (all three mouse buttons work) and the chart container is only reacting to left clicks. But this was the only solution I found so far. If you have an idea, feel free to contact me or leave feedback. 
### Steps for Testing

Prerequisites:
- 1 Student that is enrolled in at least one course

1. Log in to Artemis
2. Click on any part of the course card. Make sure the routing works and you are delegated to the course exercises page

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Only changes in HTML and SCSS files
### Screenshots

<details>
<summary>Current behavior</summary>

https://user-images.githubusercontent.com/80622272/148531795-cf1996a9-4957-41b7-baed-1f5afe68fadb.mp4

</details>
<details>
<summary>Changed behavior in this PR</summary>

https://user-images.githubusercontent.com/80622272/148531810-bb7a121c-0716-4878-b5cb-65e872f41fa3.mp4

</details>

### CODE REVIEW

**Review by baranimo7 — APPROVED** [review]
tested on ts1, works as expected

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on TS1, routing works as expected

**Review by Malyuk-A — APPROVED** [review]
Tested on TS1. Works as described.
I discussed the code changes with @willergeorg (and we tried other implementations with no real success) so I think the current solution is ok.

**Review by filip-gregurevic — APPROVED** [review]
Looks good to me 👍🏼

**Pull request merged**
