### PR TITLE
`Iris`: Hide suggestions during response generation

### PR DESCRIPTION
**Pull request by kaancayli**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context
This PR addresses an inconsistency in the Iris chat interface where suggestions remain visible and clickable while responses are being generated, despite the text input field being disabled during this time. The change implements validation checks to hide suggestions during response generation, ensuring consistent behavior across the interface.

### Description

Added validation logic to control suggestion visibility based on the chat's response generation state. This ensures suggestions are automatically disabled when a response is being generated.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Programming Exercise with Iris enabled

1. Log in to Artemis
2. Navigate to an Exercise with Iris enabled
3. Send a message to Iris
4. Make sure you received a response from the Iris, and suggestions are displayed
5. Select a suggestion or send a custom message to Iris to advance the conversation
6. Make sure the suggestions are disabled while a response is being generated.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

TBD - Coverage script gives an empty result.

### Screenshots

ezgif com-video-to-gif-converter

## Summary by CodeRabbit

- **New Features**
	- Enhanced conditional rendering logic for displaying suggestions in the chatbot interface, ensuring suggestions are shown only under specific criteria.
  
- **Tests**
	- Introduced new test cases to validate the rendering of suggestions based on various conditions, improving test coverage of the chatbot component.

### CODE REVIEW

**Review by Malekos74 — APPROVED** [review]
### Tested on Server: 03
Works as expected. I like this change!

**Review by yassinsws — APPROVED** [review]
code

**Review by alekspetrov9e — APPROVED** [review]
Tested on TS3. Works as described. Nice feature!

**Review by bassner — APPROVED** [review]

**Review by HawKhiem — COMMENTED** [review]
approve after merge

Screenshot 2024-12-02 115703
Screenshot 2024-12-02 115714

**Pull request merged**
