### PR TITLE
Further improvements to the student course overview

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

We didn't display a graph if there were only exercises with bonus points. If there was nothing to display there was just an empty space.

### Description

We now display a text if there is no graph to display, and a graph if there are bonus points (even when there are no "normally" reachable points otherwise). Known limitations: You can't use the canvas like a link now (clicking it directly works however). The animations for the graph are skipped now too, to reduce the amount of visual "noise".

Also updated the course statistics page to have a red instead of grey color for missing points:
grafik

### Steps for Testing

1. Look at the students overview of courses
2. Check that bonus points are included in the statistics
3. Check that a text is displayed if there is no score to be reached and no bonus points

### Screenshots

Without (bonus) points in the course:
grafik

With only bonus points in the course:
grafik

### CODE REVIEW

**Review by NicolasUllmann — DISMISSED** [review]
Tested on server 1. Worked as expected with no exercises in the course and with only bonus points.

**Review by maximilianbergmann — APPROVED** [review]
Tested it. Everything worked :-)

**Review by willergeorg — COMMENTED** [review]
In general seems to work and looks good. Did not test the case of a course that just provides bonus points (bc I didn't manage to create one). Just have the issue that the diagrams are a bit distorted (see screenshot).

issue6PNG

**Comment by FrankeLukas** [comment]
@willergeorg which browser are you using? Is the display always distorted or only after e.g. changing the screen size?

**Comment by willergeorg** [comment]
> @willergeorg which browser are you using? Is the display always distorted or only after e.g. changing the screen size?

I'm using Google Chrome and the diagram is always distorted for me, regardless of using my full screen size or changing it to smaller measurements.

**Review by NicolasUllmann — COMMENTED** [review]
@FrankeLukas for me it was the same, I was also able to scroll up and down endlessly. I am also using google chrome.

**Comment by FrankeLukas** [comment]
@willergeorg , @NicolasUllmann I attempted to fix the issue, can you try again?

**Review by NicolasUllmann — APPROVED** [review]
Tested on server 3. Now the design looks good and I wasn't able to scroll endlessly up and down.

**Review by willergeorg — APPROVED** [review]
Distorted display is fixed for me and can't scroll infinitely.

**Review by cremertim — APPROVED** [review]
tested on test server 2. works pretty good for me

**Review by KiraNickel — APPROVED** [review]
Tested on ts2. Everything works fine now and no distortion

**Pull request merged**
