### PR TITLE
`Development`: Fix flaky playwright e2e tests involving automatic exercise assessments

### PR DESCRIPTION
**Pull request by muradium**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
There are some flaky Playwright e2e tests that are failing due to automatic exercise assessment taking too long

### Description
This PR fixes 3 different test suites as follows:
1. Exam results tests: divided sequential tests into isolated parametrized tests to reduce time and load of each exam assessment
2. Quiz exercise assessment tests: automatic quiz assessments may take long when servers under load, thus, increased time for waiting for results from 20s to 60s
3. Programming exercise team participation - instructor checks the results: this test involves a few programming exercise submissions, which takes long and loads the server. Decreased number of exercise submissions from 3 to 2 (as 2 is enough to check commit history ordering) and now test waits for one build to finish before starting another one to avoid slowing down the server.

### Steps for Testing
- **Code Review**: Ensure that tests pass for valid reasons, functionality is adequately tested and check the code quality.
- **Run the tests**: Tests are checked by automatic run in CI environment. You can also run them locally and check if they pass.

**Steps for running the tests:**
1. Navigate to **src/tests/playwright**
2. Configure Playwright using playwright.env file based on your local setup. Current configuration should work for default Artemis setup.
3. Run `npm install && npm run playwright:setup`
4. Run tests with following commands and confirm that they pass:
- `npx playwright test e2e/exercise/programming/ProgrammingExerciseParticipation.spec.ts -g "Instructor checks the participation"`
- `npx playwright test e2e/exercise/quiz-exercise/QuizExerciseAssessment.spec.ts`
- `npx playwright test e2e/exam/ExamResults.spec.ts`

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Comment by muradium** [comment]
> Some tests seems to be failing on Playwright github action

Do you mean the Multi-Node build? Many tests consistently fail there, probably due to builds running too slowly. But we haven't decided on how to fix them yet.

**Review by BBesrour — COMMENTED** [review]
Code lgtm!
Tests are passing on CI,

However, when I try to run `e2e/exam/ExamResults.spec.ts`, this test fails `e2e\exam\ExamResults.spec.ts:126:21 › Exam Results › Check exam exercise results › Check exam results for programming exercise › Check exam programming exercise results`.
This may be OS dependant or due to my setup. I am using windows

**Review by BBesrour — APPROVED** [review]
The issue previously mentioned is probably due to my setup.
Tests are passing on CI.

**Comment by muradium** [comment]
Current test failures on Bamboo build are solved by [#8764](https://github.com/ls1intum/Artemis/pull/8764)

**Review by coolchock — APPROVED** [review]

**Pull request merged**
