### PR TITLE
[Enhancement] Exercise Assessment Tracking

### PR DESCRIPTION
**Pull request by JonasPetry**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] ~Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)~
- [x] ~Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)~
- [x] ~Server: I implemented the changes with a good performance and prevented too many database calls~
- [x] ~Server: I documented the Java code using JavaDoc style.~
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] ~Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)~
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] ~Client: I added multiple screenshots/screencasts of my UI changes~
- [x] ~Client: I translated all the newly inserted strings into German and English~

### Motivation and Context

We need to label the tracking request in order to calculate the time someone actually assessed the result. We can now omit timeframes between saving for later and starting again.

### Description

- Add method type to tracking body

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Assess an exercise (open, save and submit)
4. See that the tracking requests includes the origin

### CODE REVIEW

**Review by jpbernius — APPROVED** [review]
Did not test, but code looks good. :shipit:

**Review by bigultekin — APPROVED** [review]
I also only checked the code and it looks fine 👍

**Review by anditurdiu — APPROVED** [review]
Looks good

**Review by kloessst — APPROVED** [review]
Looks good to me

**Pull request merged**
