### PR TITLE
`Text exercises`: Add validation bar into update and create view

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
This PR adds a validation Bar to the Text Exercise. The Design is approved.
This gives the user a better feel of navigation through the settings and helps during validation and to get used to the different sections also displayed in the detail page

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to the Edit page of a Text Exercise
3. Verify that the bar is shown, the navigation works and that it reacts to the change of fields to be validated

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [exercise-title-channel-name.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5961/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/exercise-title-channel-name/exercise-title-channel-name.component.ts.html) | 100% | ✅ |
| [exercise.service.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5961/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/exercise/exercise.service.ts.html) | 92.38% | ✅ |
| [exercise-update-plagiarism.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5961/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/plagiarism/exercise-update-plagiarism/exercise-update-plagiarism.component.ts.html) | 100% | ✅ |
| [text-exercise-update.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5961/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/manage/text-exercise/text-exercise-update.component.ts.html) | 94.95% | ✅ |
| [form-status-bar.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5961/latest/artifact/shared/Coverage-Report-Client-Tests/app/forms/form-status-bar/form-status-bar.component.ts.html) | 100% | ✅ |
| [title-channel-name.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5961/latest/artifact/shared/Coverage-Report-Client-Tests/app/shared/form/title-channel-name/title-channel-name.component.ts.html) | 100% | ✅ |

### Screenshots
image

https://github.com/ls1intum/Artemis/assets/78978542/fa656cb0-3598-4ef2-931c-977fade64c44

## Summary by CodeRabbit

- **New Features**
  - Enhanced plagiarism settings with options like `similarityThreshold` and `minimumScore`.

- **Enhancements**
  - Improved form validation and lifecycle hook implementation in various components.
  - Updated section headings and styles in text exercise management.

- **Documentation**
  - Updated template files with new `ngModel` and visibility options.

- **Tests**
  - Added unit tests for the new `FormStatusBarComponent`.
  - Updated existing component tests with new imports and descriptions.

### CODE REVIEW

**Review by farisd16 — APPROVED** [review]
Tested on ts5, works as expected.

**Review by konrad2002 — DISMISSED** [review]
manually tested on legacy ts11, works as expected

**Review by Gusti2010 — DISMISSED** [review]
manually tested on Ts2_Legacy. Works as expected!

**Review by Predixx — DISMISSED** [review]
tested on ts2. LGTM!

**Review by RY997 — APPROVED** [review]
Tested on TS4, worked as expected

**Review by georgyia — DISMISSED** [review]
tested manually, works as expected

**Review by LenaKahle — APPROVED** [review]
Approve, tested on legacy ts11.

**Review by konrad2002 — APPROVED** [review]
reapprove

**Review by georgyia — APPROVED** [review]
reapproved

**Review by LenaKahle — APPROVED** [review]
Reapprove.

**Review by RY997 — APPROVED** [review]

**Review by reschandreas — APPROVED** [review]
code lgtm

**Review by farisd16 — APPROVED** [review]
reapprove

**Pull request merged**
