### PR TITLE
`Communication`: Prevent post submission if already in progress

### LINKED ISSUE #6480: ```Communication```: Hitting Newline Multiple Times Clones The Sent Message
### Describe the bug

When sending a message, spamming the Enter/NewLine can send the same message multiple times.

Happens on TS1,TS2 and also on release at [https://artemis.in.tum.de/](https://artemis.in.tum.de/)

Slow internet connection also helps.

### To Reproduce

1. Go to Any Course with messaging available,
2. Click on any Channel/Group/Direct chat or create a new chat if none exists,
3. Write any message and hit Enter/NewLine at least twice,
4. See that the same message is sent twice or even more.

### Expected behavior

Same message to be only sent once when Enter/NewLine is pressed multiple times.

### Screenshots

enterSpam

Screenshot 2023-04-25 113211

### Which version of Artemis are you seeing the problem on?

6.1.4

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by aplr**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client

- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German. (not applicable)

### Motivation and Context

In communication components, it was possible to repeatedly submit the same message.

* Fixes #6480 

### Description

There are two main changes:

1. The submit button is set to `disabled` while submitting. Changed:
    * `post-create-edit-modal`
    * `anser-post-create-edit-modal`
    * `message-inline-input`
    * `message-reply-inline-input`
2. Before submitting, it is checked if a submission is already in progress
    * This change was made in `PostingCreateEditDirective`, so it affects all components inheriting from this directive.

### Discussion

message-inline-input and message-reply-inline-input are almost identical. From your perspective, would it make sense to make a refactor, which gets rid of the reply input, and the inline input handles both?

### Steps for Testing

1. Log in to Artemis
2. Create a new course or use an existing one
4. Create a new messaging channel or use an existing one
5. Open your browser's dev tools and set network throttling to the slowest connection
6. Type a new message and repeatedly hit either your return key or click the submit button

* The message should be only sent once
* The submit button is in `disabled` state while submitting

#### Exam Mode Testing

1. Log in to Artemis
2. Set up an exam
3. Start the test mode / full exam mode
4. Go to communication / messages
5. Continue w/ steps 5, 6 stated above

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

#### Manual Tests
- [ ] Test 1
- [ ] Test 2

#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Test Coverage

no change in coverage

### Screenshots

Screen Recording 2023-09-01 at 09 41 08

Frame rate is a bit low, but you can see the important points

### CODE REVIEW

**Review by terlan98 — APPROVED** [review]
Tested on TS5. Messages are sent only once when the return key and the submit button are pressed repeatedly 👍 

Regarding the `message-inline-input` and `message-reply-inline-input`:
- They indeed seem very similar. I think it would make sense to get rid of the latter.

**Review by basak-akan — APPROVED** [review]
Tested on TS1, messages are only sent once as expected.

**Comment by aplr** [comment]
> Regarding the `message-inline-input` and `message-reply-inline-input`:
> 
> * They indeed seem very similar. I think it would make sense to get rid of the latter.

Thanks! Yes, I'll do that in a new PR :)

**Review by JohannesStoehr — APPROVED** [review]
Code changes look good to me

**Review by RY997 — APPROVED** [review]
Code LGTM

**Review by dearjasmina — APPROVED** [review]
code looks good to me

**Pull request merged**
