### PR TITLE
`Development`: Update client dependency `export-to-csv`

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context
This PR updates the client dependency `export-to-csv` to the latest version for security and maintainability reasons. 
There have been some breaking changes in the major version update, hence some refactorings had to be made.
See [npmjs](https://www.npmjs.com/package/export-to-csv) for reference.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Verify that the following csv exports work correctly 
2.1. Course Scores (course-management/{courseId}/scores)
2.2. Exam Scores (course-management/{courseId}/exams/{examId}/scores)
2.3. Exercise Scores (course-management/{courseId}/programming-exercises/{exerciseId}/scores)
2.4. Plagiarism Case Export (course-management/{courseId}/programming-exercises/{exerciseId}/plagiarism)
2.5. Base Grading System Export (course-management/{courseId}/grading-system/interval)
2.5. Course Groups (course-management/{courseId}/groups/{groupName e.g. students}

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
  - Implemented custom CSV export functionality across various components.
  - Enhanced CSV export options with additional configuration settings.

- **Improvements**
  - Streamlined CSV generation and download process for better user experience.
  - Updated export modal UI to reflect new CSV export options.

- **Tests**
  - Adjusted unit tests to align with the new CSV export implementation and options.

- **Documentation**
  - Updated in-component documentation to describe the new CSV export process and options.

### CODE REVIEW

**Review by MaximilianJG — DISMISSED** [review]
Tested on Ts6 with Instructor 11 and 14. All exports work as expected. But unfortunately I can't find the groups endpoint. How do I locate this? 

 
Screenshot 2024-01-09 at 21 02 41
Screenshot 2024-01-09 at 21 03 58
Screenshot 2024-01-09 at 21 04 39
Screenshot 2024-01-09 at 21 06 46

**Review by konrad2002 — DISMISSED** [review]
manually tested on legacy TS1, worked as expected... however I assumed that the course groups page means "course-management/{courseId}/tutorial-groups"

**Review by xHadie — DISMISSED** [review]
_Manually tested on TS2_Legacy_
Works as expected - tested together with @Gusti2010

**Review by Gusti2010 — APPROVED** [review]
Tested manually on ts11_Legacy together with @xHadie . Works as expected. We assumed by Course Groups you meant Tutorial Groups?

**Review by laurenzfb — DISMISSED** [review]
code lgtm

**Review by reschandreas — APPROVED** [review]
code lgtm, thanks for fixing the package-lock.json 🚀

**Review by xHadie — APPROVED** [review]

**Review by laurenzfb — APPROVED** [review]

**Review by konrad2002 — APPROVED** [review]

**Review by nata-81 — APPROVED** [review]
tested on ts5 works as expected.

**Pull request merged**
