### PR TITLE
`Integrated code lifecycle`: Show result progress bar in exam overview and exercise details pages

### PR DESCRIPTION
**Pull request by BBesrour**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

We want to show the progress bar in the exercise details view and exam overview page (see screenshots)

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Create programming exercise
2. Make sure that the result component show a progress bar and that it's intuitive.
3. Optional: try pushing to the test repository (using edit in Editor) and check the result component (for template and solution build plans)

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 1 Student

1. Log in to Artemis
2. participate in exam as student
3. push to a programming exercise
4. navigate to the overview page
5. check the result component is correct and intuitive

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2
#### Performance Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image
image

## Summary by CodeRabbit

- **New Features**
	- Added a progress bar to the programming test status and exercise overview pages for enhanced visual feedback during loading states.
  
- **Style**
	- Updated the styling of the progress bar component for improved presentation.

### CODE REVIEW

**Review by florian-glombik — APPROVED** [review]
Code changes look reasonable

**Review by cremertim — APPROVED** [review]
code

**Review by SimonEntholzer — APPROVED** [review]
Works as expected on Ts1, also for exams:
image

Nitpick would be to center the text when the progress bar is displayed

**Review by coolchock — APPROVED** [review]
tested on ts1, works as described 👍

**Review by HawKhiem — APPROVED** [review]
Tested on TS3. Everything works as expected

Screenshot 2024-12-18 210838
Screenshot 2024-12-18 212317

**Review by krusche — APPROVED** [review]

**Pull request merged**
