### PR TITLE
`Development`: Migrate legacy course-wide channels

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

Originally, the course-default, lecture, and exercise channels were created with is_course_wide = false (since the column didn't exist in the database). Now, for corresponding existing database entries, this field can be set to true.

### Description

A migration script handles the update for course-default, lecture and exercise channels. Lecture and exercise channels are recognized by the existence of an id in lecture_id or exercise_id. Course-default channels are recognized by the absence of both a creator and an associated tutorial group.

### Steps for Testing

Prerequisites:
- 1 Instructor
- One course that has tutorial group channels and also legacy default, lecture and exercise channels (you can recognize these legacy channels by the fact that you can add members to them as an instructor)

1. After deploying, the channels have been migrated, if you cannot add members to them anymore (and all course members are a member automatically)
2. Confirm that only default, lecture, and exercise channels have been migrated

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Same as develop

### Screenshots

No UI changes

### CODE REVIEW

**Review by MaximilianAnzinger — APPROVED** [review]
LGTM 👍 
Tested locally, works like a charm.

**Review by Kroko-fant — DISMISSED** [review]
Tested in the testing session looks good 👍

**Review by tobias-lippert — DISMISSED** [review]
Migration works, tested locally. Migration script also looks good.

**Review by basak-akan — APPROVED** [review]
Tested during the testing session, and worked well.

**Review by nityanandaz — DISMISSED** [review]
Code review: looks good

**Review by dearjasmina — DISMISSED** [review]
script looks good

**Review by krusche — APPROVED** [review]

**Pull request merged**
