### PR TITLE
`Exam mode`: Improve performance when loading scores significantly

### PR DESCRIPTION
**Pull request by krusche**
This PR improves the performance when loading exam scores significantly, in particular for exam with many participants and multiple quiz exercises. Local tests improve the performance for exams with ~1500 participants from ~50s to ~5s.

#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Loading exam scores is really slow for exams with many participants

### Description
It turns out that the `OneToMany` relationship (declared as eager loading) from `QuizSubmission` to `SubmittedAnswer` is problematic in terms of performance, because it automatically loads submitted answers in many cases even if those are not needed. Those submitted answers are loaded in multiple database calls (and not a single one) which makes the loading time really long.

This PR changes this relationship from `eager` to `lazy` which is recommended for all  `OneToMany` relationships anyway. The tricky part is that all existing quiz functionality relied on this relationship being eager, so I had to change a couple of places and load the submitted answers subsequently. There are still a couple of performance optimizations possible (e.g. loading those submitted answers in single database calls), but this PR should not make any case worse and only improve the current situation, for exam scores and potentially also for other places like the `for-dashboard` REST call.

Note: I had to add a new database call to calculate if quiz submissions are empty or not.

In addition, this PR converts a couple of DTOs from POJOs to Java `Records`, which will be the way to go forward in the future! Records avoid boilerplate code and are immutable, both having significant advantages in terms of code maintenance, testing and readability.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- Multiple quiz exercises in exams and courses

1. Test everything related to quizzes, in particular participating in course quiz exercises (preview, sample solution, live, batch and practice) and in exam quiz exercises. Also lookup the quiz results subsequently in the different modes and try out reset, re-evaluate and delete
2. Test that the exam scores are still shown correctly 
3. Test that the instructor can lookup statistics, exercise scores and participations 

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
I added a new test for untested server code and removed some unused code by converting POJOs into records, otherwise there are no changes in the test coverage

### Screenshots
no changes

### CODE REVIEW

**Review by akesfeden — CHANGES_REQUESTED** [review]
Tested on TS1, course exercise quizzes behaves the same as develop branch, in preview, sample solution, live, batch and practice modes. I tested resetting the quiz and re-evaluating multiple choice questions which successfully updated the scores.

In exam mode, I had a problem loading the student exam as instructor at url https://artemis-test1.artemis.in.tum.de/course-management/12/exams/159/student-exams/659. The same endpoint works when I deployed develop release-1059 to TS1.
image
The error message in Chrome DevTools console:
```
ERROR TypeError: Cannot read properties of undefined (reading 'exam')
    at nl (student-exam-detail.component.html:3:101)
    at pu (core.mjs:12121:9)
    at C6 (core.mjs:11984:13)
    at x6 (core.mjs:13034:17)
    at C6 (core.mjs:12008:9)
    at B3 (core.mjs:13080:13)
    at s8 (core.mjs:11774:9)
    at C6 (core.mjs:12034:13)
    at x6 (core.mjs:13034:17)
    at C6 (core.mjs:12008:9)
    at B3 (core.mjs:13080:13)
    at s8 (core.mjs:11774:9)
    at C6 (core.mjs:12034:13)
    at a8 (core.mjs:12101:9)
    at b6 (core.mjs:13258:13)
    at A5 (core.mjs:13284:5)
    at k8.detectChanges (core.mjs:13801:9)
    at r.tick (core.mjs:27476:22)
    at core.mjs:27323:26
    at B.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26378:33)
    at B.invoke (zone.js:371:52)
    at T.run (zone.js:134:43)
    at fc.run (core.mjs:26232:28)
    at Object.next (core.mjs:27322:28)
    at F.next (Subscriber.js:91:33)
    at V._next (Subscriber.js:60:26)
    at V.next (Subscriber.js:31:18)
    at Subject.js:34:30
    at e (errorContext.js:19:9)
    at ap.next (Subject.js:27:9)
    at ap.emit (core.mjs:22886:15)
    at S7 (core.mjs:26300:35)
    at M7 (core.mjs:26428:5)
    at Object.onInvokeTask (core.mjs:26372:17)
    at B.invokeTask (zone.js:405:60)
    at T.runTask (zone.js:178:47)
    at invokeTask (zone.js:487:34)
    at invoke (zone.js:476:48)
    at U.z.args.<computed> (zone.js:2385:32)
```

**Review by stefanwaldhauser — CHANGES_REQUESTED** [review]
❌ The student exercise statistics seems broken. The call /charts/exercise-scores returns 0 for every exercise even though I have  achieved for example 2 points in quiz batch2:

image

**Review by minrows — COMMENTED** [review]
- All the quiz exercise-related functionalities are working fine. 
- After participating in test exam though, I am getting following error while trying to access summary of it. (Not sure if its related to this PR) 
- URL: https://artemis-test2.artemis.in.tum.de/course-management/279/exams/258/test-runs/359/summary

image

**Comment by 4ludwig4** [comment]
I was able to reproduce the same problems as @minrows, @stefanwaldhauser, and @akesfeden on a local test instance.
Besides those issues, I wasn't yet able to find other issues by creating multiple quizzes and quizzes inside of exams.

**Comment by stefanwaldhauser** [comment]
> Tested on TS1, course exercise quizzes behaves the same as develop branch in preview, sample solution, live, batch and practice modes. I tested resetting the quiz which worked as expected and re-evaluating multiple choice questions which successfully updated the scores. I was able to lookup statistics and exercise scores with an instructor.
> 
> In exam mode, I had a problem loading the student exam as an instructor at url https://artemis-test1.artemis.in.tum.de/course-management/12/exams/159/student-exams/659 (If you need an instructor login for that course, you can use `artemis_test_user_1`). The same endpoint works when I deployed develop release-1059 to TS1.
> 
> image The error message in Chrome DevTools console:
> 
> ```
> ERROR TypeError: Cannot read properties of undefined (reading 'exam')
>     at nl (student-exam-detail.component.html:3:101)
>     at pu (core.mjs:12121:9)
>     at C6 (core.mjs:11984:13)
>     at x6 (core.mjs:13034:17)
>     at C6 (core.mjs:12008:9)
>     at B3 (core.mjs:13080:13)
>     at s8 (core.mjs:11774:9)
>     at C6 (core.mjs:12034:13)
>     at x6 (core.mjs:13034:17)
>     at C6 (core.mjs:12008:9)
>     at B3 (core.mjs:13080:13)
>     at s8 (core.mjs:11774:9)
>     at C6 (core.mjs:12034:13)
>     at a8 (core.mjs:12101:9)
>     at b6 (core.mjs:13258:13)
>     at A5 (core.mjs:13284:5)
>     at k8.detectChanges (core.mjs:13801:9)
>     at r.tick (core.mjs:27476:22)
>     at core.mjs:27323:26
>     at B.invoke (zone.js:372:26)
>     at Object.onInvoke (core.mjs:26378:33)
>     at B.invoke (zone.js:371:52)
>     at T.run (zone.js:134:43)
>     at fc.run (core.mjs:26232:28)
>     at Object.next (core.mjs:27322:28)
>     at F.next (Subscriber.js:91:33)
>     at V._next (Subscriber.js:60:26)
>     at V.next (Subscriber.js:31:18)
>     at Subject.js:34:30
>     at e (errorContext.js:19:9)
>     at ap.next (Subject.js:27:9)
>     at ap.emit (core.mjs:22886:15)
>     at S7 (core.mjs:26300:35)
>     at M7 (core.mjs:26428:5)
>     at Object.onInvokeTask (core.mjs:26372:17)
>     at B.invokeTask (zone.js:405:60)
>     at T.runTask (zone.js:178:47)
>     at invokeTask (zone.js:487:34)
>     at invoke (zone.js:476:48)
>     at U.z.args.<computed> (zone.js:2385:32)
> ```

Fixed in 7f505cc64116f1bafc10d7d3fd62780f20e57f35

**Comment by stefanwaldhauser** [comment]
> * All the quiz exercise-related functionalities are working fine.
> * After participating in test exam though, I am getting following error while trying to access summary of it. (Not sure if its related to this PR)
> * URL: https://artemis-test2.artemis.in.tum.de/course-management/279/exams/258/test-runs/359/summary
> 
> image

Fixed in 7f505cc64116f1bafc10d7d3fd62780f20e57f35

**Review by stefanwaldhauser — APPROVED** [review]

**Review by manuelmanso — CHANGES_REQUESTED** [review]
Tested locally, found an issue in the course management page: The average score displayed is always 0% after the quiz is finished. Interestingly, if you re-evaluate the quiz and some scores change, the correct average score is then displayed.

image

**Review by ge65cer — APPROVED** [review]
Tested on TS1 with all kinds of quiz modes and actions.
Could not find any issues apart from the one mentioned by @manuelmanso. I re-checked and this bug already exists on `develop`, so likely not introduced here. Will open a separate ticket for it.

**Review by akesfeden — APPROVED** [review]
Re-tested on TS1, I confirm that the problem with student exam result is solved, exam quiz exercises can be displayed, assessed and points are calculated correctly for instructor and student in the student exam view. Course quiz exercises still work as previously.

Since @ge65cer mentioned that the issue first found by @manuelmanso is not created with this PR and since I have not found another issue I approve.

**Review by manuelmanso — APPROVED** [review]
Approving after the comment left by @ge65cer. Could not find other issues, went through the code and it looks good 👍

**Pull request merged**
