### PR TITLE
Wait for fork creation

### LINKED ISSUE #2349: [GitLab]Artemis fails to unprotect branch
### Describe the bug
User can not push because branch is protected.
Log says:
```
Could not unprotectBranch branch (but will try to protect it) due to the following reason: Could not unprotect branch master for repository ALPROSTRINGCON/alprostringcon-xxx
``` 

#### To Reproduce
Unknown. I suspect happens on much Load.

- [x] Fix Exception with real reason is swallowed

### PR DESCRIPTION
**Pull request by axel1200**
Fixes #2349
Discussion PR.
Possible fix. What do you think. Not sure if I like my code. Also have not tested that yet

### CODE REVIEW

**Comment by axel1200** [comment]
How do I convert to a draft?

**Comment by axel1200** [comment]
Without using the taskExecutor I think we would be risking starvation of the Threadpool

**Comment by axel1200** [comment]
Tested it and works. I think I am gonna put that on production because this is pretty bad if it happens to students

**Comment by axel1200** [comment]
Unable to say if it actually fixes it. Only production is gonna show that

**Comment by axel1200** [comment]
Or maybe we just schedule the protection of branches 10 seconds later or so :thinking:

**Comment by krusche** [comment]
What is the status of this PR? Please note that we close unmerged PRs in case they are open longer than 14 days.

**Comment by krusche** [comment]
Closing this PR because there is no progress. Feel free to reopen it in case there is further progress with the implmentation

**Comment by axel1200** [comment]
Yes... I also test a different version in production atm

**Pull request closed without merging**
