### PR TITLE
Use Text Blocks

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] This PR only changes test code
- [x] I checked that all Java tests still work on GitHub, Bamboo and locally.

### Motivation and Context
We switched to Java 15 which offers **text blocks**, see https://openjdk.java.net/jeps/378.

Replace formatted, multiline strings that are hard to read by formatted text blocks.

**Note: this excludes SQL/HQL strings which will be addressed in smaller follow-up PRs.**

### Description

Replaced the strings by text blocks. Currently, only strings that span multiple lines are changed.

Most of the changes affect only test code, with a large proportion of that being mock requests and alike.

This means that
```java
"ABC\n" + "    xyz\n"
"something long\n"
```
is replaced by
```java
"""
ABC
    xyz
something long
"""
```

#### Some things you should know about text blocks

- The position of the first `"""` introducing the text block has no effect, but it must be directly followed by a line break.
- Line breaks in the text block are preserved by default and always of the LF (`\n`) type. The one after the `"""` does not count.
- A line break can be prevented by ending the line with `\`.
- Windows line endings can be archived by ending a line with `\r` (which is then followed by the implicit `\n`).
- Whitespace at the end of the line is removed (unless an escaped space `\s` is added at the very end).
- Single `"` and double `""` do not need to be escaped in a text block.
- A text block ends with `"""`. Examples:
  ```java
  "abc" == """
           abc"""
  
  "abc\n" == """
             abc
             """
  
  "  abc\n" == """
               abc
             """
  ```
- Whitespace at the start of each line is removed as much as it is possible to do consistently. This means that the minimal number of whitespace characters that any line starts with is then removed from all lines. (See e.g. the last example of the point above)

### Steps for Testing
1. Run the server tests on your system
2. Check the code
3. Check that most of the system still works on a test server / locally.

### CODE REVIEW

**Comment by MaisiKoleni** [comment]
I would also recommend using it for the HQL Queries:
```java
    @Query("""
            SELECT c FROM Complaint c
               LEFT JOIN FETCH c.result r
               LEFT JOIN FETCH r.assessor
               LEFT JOIN FETCH r.participation p
               LEFT JOIN FETCH p.exercise e
               LEFT JOIN FETCH r.submission
            WHERE e.id = :#{#exerciseId} AND c.complaintType = :#{#complaintType}
            """)
```
or
```java
    @Query("""
            SELECT count(c) FROM Complaint c
            WHERE c.complaintType = 'COMPLAINT'
              AND c.student.id = :#{#studentId}
              AND c.result.participation.exercise.course.id = :#{#courseId}
              AND (c.accepted = false OR c.accepted is null)""")
```
I started to do that with queries above 200 characters, in my eyes this is much more readable.

But before I continue, we could decide on a format here (how much indentation, where to indent).

More complex example and suggestion:
```java
    @Query("""
            SELECT COUNT (DISTINCT p) FROM StudentParticipation p
            WHERE p.exercise.id = :#{#exerciseId}
              AND EXISTS (Select s FROM p.submissions s
                          where s.result Is not null
                            and exists (select c from Complaint c
                                        where c.result.id = s.result.id
                                          and c.complaintType = :#{#complaintType}))
              AND NOT EXISTS (select prs from p.results prs
                              where prs.assessor.id = p.student.id)
            """)
```
We could e.g. also place from on an extra line, as it is commonly done.

**Comment by MaisiKoleni** [comment]
Maybe we should also finally decide whether we want to use uppercase or lowercase. At the moment we have `SELECT`, `select` and `Select`.

**Comment by krusche** [comment]
Spotless could be a limitation here. I suggest you add an issue in their Github Repo and ask for support.
Please make sure that we do not need to add `enable-preview` here, this was a real pain in the end.

**Comment by krusche** [comment]
I found comments about the missing support of switch expressions e.g. here: https://github.com/google/google-java-format/issues/477 You could add another issue here. 

Another option would be to add it into https://github.com/diffplug/spotless/issues

I just updated spotless and check style to their latest versions on `develop`. You could give it a try. Maybe it works now.

**Comment by MaisiKoleni** [comment]
https://github.com/diffplug/spotless/issues/547 seems to go into the right direction.

**Comment by MaisiKoleni** [comment]
We decided in the developer meeting to split the transformation of the SQL/HQL queries of the `*Repository` classes into smaller PRs. Therefore, such changes are out of scope for this PR and will be addressed in smaller follow-up PRs.

It so happens now that this PR only changes Java test code.

**Review by krusche — COMMENTED** [review]
Would it not make more sense to put the json strings of some of the test cases into actual json files in the folder `src/test/resources/test-data`
I don't think having those strings in Java is beneficial.
We already have a method `loadFileFromResources` in the tests that handles this.
(I refactored this method in another branch into a new Java class `FileUtils`)

**Review by krusche — APPROVED** [review]

**Pull request merged**
