### PR TITLE
`Assessment`:  Fix issues during modeling assessments in tutor training

### PR DESCRIPTION
**Pull request by canberkanar**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).

### Motivation and Context
This is a follow up PR that introduces a client test for the bugfix [#4940](https://github.com/ls1intum/Artemis/pull/4940) and fixes the duplicate request causing `DataIntegrityViolationException` (displayed to the user as `Internal server error`) and the error causing the example submission for modeling exercises to be displayed as empty during tutor assessment training. The relevant Sentry entry for the `DataIntegrityViolationException` is [here](https://sentry.ase.in.tum.de/organizations/artemis/issues/21770/events/1be9ec57e7f244e7b552e5aec266ca29/?project=2).

Another error this PR addresses is that when the UML elements/relations for a modeling exercise example submission is deleted, the referencing feedback is not deleted so there were dangling points that is present in the example submissions list page but no visible feedback is associated with them. This was leading to confusion and make it seem like the model is not loaded properly.

### Description
In order to prevent the same request to create the tutor participation after the tutor reads the instructions, the button is disabled while the response is loading.

Other issue causing the modeling exercises to be displayed as empty during tutor assessment training is due to a race condition. It occurs when the `exercise` is set before the `umlModel` of the example submission in `ExampleModelingSubmissionComponent`. Two independent observables are synchronized to prevent the race condition.

For the dangling points and feedbacks issue, we now delete the reference feedbacks which does not reference an existing UML element/relation.

### Steps for Testing

Prerequisites:
- 1 Tutor
- 1 Instructor
- 1 Modeling Exercise with Example Submission

1. Log in to Artemis with the Tutor account
2. Navigate to Course Administration
3. Go to the course of the prerequisite Modeling Exercise > Assessment Dashboard > Modeling Exercise's Exercise Dashboard
4. Click `Start assessing example submissions` multiple times and check that the button is disabled after the first one and no Internal server error notification is shown (You may need to enable throttling at browser DevTools because it doesn't usually take too long to finish loading).
6. Check that the example solution, assessment instructions and `Submit assessment` button is visible and the model is not empty.
8. Make an assessment and then submit to see the result.

9. Log in to Artemis with the Instructor account
10. Navigate to Course Administration
11. Go to the course of the prerequisite Modeling Exercise > Example Submissions
12. Create new or edit an existing example submission
13. Add some UML elements, Save Example Submission and then click Show Assessments.
14. Add some feedback on the UML elements/associations and then Save Example Assessment
15. Check Modeling Exercise > Example Submissions list page displays total points correctly.
16. Click Show Submissions button and delete a UML element/association with feedback, then Save Example Submission.
17. Check Modeling Exercise > Example Submissions list page displays total points correctly (The point for feedback referencing the deleted UML element/association should be removed).

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| example-text-submission.component.ts  | 78.7% | 95.87% |
| exercise-assessment-dashboard.component.ts  | 78.6% | 95.12% |
| example-modeling-submission.component.ts | 62.69% | 92.2% |

### Screenshots

Before the fix (not always, indeterministic):
image

After the fix:
image

### CODE REVIEW

**Review by willergeorg — COMMENTED** [review]
Tested on TS1. Worked as described. One thing I noticed was a weird alert if the tutor did not grade the submission as intended. I do not know if it is related to your changes, but it should be improved:
image

**Comment by akesfeden** [comment]
Thanks for the review @willergeorg! I set `skipAlert` to true for the `BadRequestAlertException` that is handled in the client. It should only display the readable error now.

**Review by mallgaier — APPROVED** [review]
Tested on TS1, fixes work as expected. 
Excellent and quick fix 👍

**Review by filip-gregurevic — APPROVED** [review]
Tested on TS1 and works as expected, code changes also look good 🚀

**Pull request merged**
