### PR TITLE
Fix: Text JPlag Export has "null" in Zipname

### PR DESCRIPTION
**Pull request by jpbernius**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Description
- Text Exercises do not have a short name.
- Use Exercise Title instead.

### Steps for Testing
1. Download JPlag Report for a Text Exercise
2. Check if Exercise Name is in Filename of the downloaded ZIP file.

### CODE REVIEW

**Comment by jpbernius** [comment]
@philippbauch Is this change ok? Can we merge it?

**Review by philippbauch — APPROVED** [review]
Zip file name contains the correct text exercise title ✅ 
Submissions in JPlag Report contain the correct exercise title ✅ 

Screenshot 2020-10-26 at 13 13 41

**Comment by philippbauch** [comment]
> @philippbauch Is this change ok? Can we merge it?

@jpbernius I think we can merge this change

**Review by tiffca — APPROVED** [review]
Tested successfully in test server 1, confirmed the exercise name is in the .zip file and the .zip unzips without errors.

**Review by stefanwaldhauser — APPROVED** [review]
Nice and easy fix

**Pull request merged**
