### PR TITLE
`Programming exercises`: Add option to ignore elements in the Java test oracle generator

### LINKED ISSUE #4709: Oracle Generator for structural tests: Allow selection of tested members
### Is your feature request related to a problem?

This came up in https://github.com/ls1intum/Artemis/pull/4698#issuecomment-1037238776.

When creating the test oracle, the instructor should have the ability to mark methods / fields / classes as ignored helper structures that are not part of the expected structure and therefore should not be tested against. 

### Describe the solution you'd like

The first idea of the comment was to use an annotation either in Java or in Ares. This might be difficult since Java does not come with a lot of annotations and the solution repository usually has no dependency to Ares.

Another solution would be to add a tree structure view of the sources where the instructor can select which members should be tested against and which not.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
### Motivation and Context
Closes #4709 

### Description
This PR allows users to specify ignored (helper) members which will not be part of the generated test.json file.

You can mark a member as ignored by using the Tag `@oracleIgnore` in the corresponding JavaDoc comment.

The default solution template also gets updated to showcase this.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Programming Exercise

1. Annotate different elements (classes, attributes, methods, etc.) with `@oracleIgnore` in its corresponding JavaDoc comment
2. Presse the "Generate Structural Test Oracle" button
3. Make sure that the annotated elements are not part of the created `test.json` file.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by dveljacic — APPROVED** [review]
Works fine on TS1. ✅

**Review by ole-ve — APPROVED** [review]
Tested on TS1 for classes, interfaces, attributes, constructors, and methods.
Everything works as expected. 👍

**Review by baranimo7 — APPROVED** [review]
tested on ts2. json file is changed correctly.

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on TS2, works as expected

**Review by Bofan-Zhu — APPROVED** [review]
Tested on ts2. Tag works 👍

**Review by willergeorg — APPROVED** [review]
Code. 👍

**Review by Marvin-Vitcu — APPROVED** [review]
Code and comments look good.

**Comment by krusche** [comment]
This PR is very old, but quite useful. I will merge it now.
@Strohgelaender would be great if you could add documentation (e.g. in the best practices) in a follow-up PR

**Pull request merged**
