### PR TITLE
Change exercise management routes to depend on the type

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Motivation and Context

Currently you can't always click on the exercise title (or on "Exercises") and be taken to the respective exercise or list of exercises.
In this example neither `Exercises` nor `test` change the page correctly:
grafik

### Description

Changes the routes to use `type + '-exercises'` consistently, so breadcrumbs always work in courses and exams. Also new is that you can click on the individual exercise titles in exams, and open the plagiarism detection from there.

### Steps for Testing

The following routes changed and need testing (can you still access all of them?):
- Exercise scores
- Exercise participations
- Exercise submissions (note: not accessible via breadcrumbs from the assessment pages)
- Complaints
- More feedback requests
- Exercise hints
- Lti configuration
- Teams

The following links now take you to exam specific routes:
grafik

Breadcrumbs now display for exam exercises like this (check that all links are clickable):
grafik

### CODE REVIEW

**Comment by FrankeLukas** [comment]
Resolved the merge conflicts.

**Review by SimonEntholzer — CHANGES_REQUESTED** [review]
For quiz exercises when you are in the exam -> exercise-groups -> exercise -> participation, you can't click the breadcrum which should lead to the exercise info. (Same for the score page for exam quiz exercises)
image

**Comment by FrankeLukas** [comment]
> For quiz exercises when you are in the exam -> exercise-groups -> exercise -> participation, you can't click the breadcrum which should lead to the exercise info. (Same for the score page for exam quiz exercises)

Fixed an oversight there. Sadly there appears to be some sort of race condition within the quiz exercise detail component (likely because a snapshot of the route is accessed instead of subscribing to the observable), so sometimes it throws an error when loading. I'm also not sure if it makes sense for us to use that component here, since it allows editing too. (Our "details" component for quizzes really is an "edit" component.) I'll have to think about how we continue here. (Maybe we defer this to a follow-up. A better solution might be to create a real, minimal detail component here.)

> I guess that's for a followup/future PR?

Yep

**Comment by FrankeLukas** [comment]
Updated. I'm actually not quite sure how this worked at all to begin with, but it's fixed now.

**Review by katjanakosic — APPROVED** [review]
Tested with @ArtemTsurikov. Looks good to me :)

**Review by ArtemTsurikov — APPROVED** [review]
Tested on ts1, seems fine to me

**Review by willergeorg — CHANGES_REQUESTED** [review]
Tested with @NicolasUllmann on TS2. There seems to be a problem when navigating to submissions in text exercises, opening an assessment
 and then trying to go back to the submissions. Then the "Submissions" subpath does nothing. Same holds for modeling exercises.


Example for text exercise:
Issue1

Example for modeling exercise:
Issue2

**Review by NicolasUllmann — CHANGES_REQUESTED** [review]
Tested on Server 2, together with @willergeorg. We ran into an issue when trying to trace back through the route from "assessments" to "submissions". Clicking on submissions was not possible. Only going back one step further, in this case, clicking the title of the exercise.

**Review by canyelten — CHANGES_REQUESTED** [review]
Tested on ts1. I found a problem:
Ekran görüntüsü 2021-04-18 214456

After clicking o "Participations" I could not navigate one step back to "Bruh", I could only navigate two steps back clicking on "Exercises". I tried a similar process for all exercise types and had the same problem in all of them.

**Comment by FrankeLukas** [comment]
Resolved the merge conflicts.

> After clicking o "Participations" I could not navigate one step back to "Bruh", I could only navigate two steps back clicking on "Exercises". I tried a similar process for all exercise types and had the same problem in all of them.

@canyelten I can't reproduce this, so assume it was fixed by resolving the merge conflicts.

@willergeorg @NicolasUllmann : The "submissions" route is not changed in this PR (it doesn't work on `develop` either). We need to change the route for all types there, so that was planned for another follow-up. I updated the testing steps to clarify that.

**Comment by willergeorg** [comment]
re-checked with @canyelten . The bug he mentioned seems to be solved, I'm not able to reproduce it either. Clicking "Bruh" takes you back to the according exercise now.

**Review by canyelten — COMMENTED** [review]
Rechecked with  @willergeorg on ts2. Worked fine for me.

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 3. Everything worked fine for me as well, with no signs of the bug mentioned above.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Works good :-)

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS2, works fine now

**Review by canyelten — APPROVED** [review]

**Review by FuchsDominik — APPROVED** [review]
Looks good to me :) Check that the mentioned pages are still accessible, every breadcrumb of an exercise in an exam is clickable and the title navigates into the exercise detail page (just noticed, isn't it a bit doppelt gemoppelt that we always provide links for the exerciseId and the title where both navigate into the same page?)

**Review by nicolasruscher — APPROVED** [review]
looks good! tested and looked at the code

**Review by real-dmy — APPROVED** [review]
Tested on TS1. Looks fine to me. Before mentioned issue seems to work as well, breadcrumbs are clickable.

**Review by ArtemTsurikov — APPROVED** [review]
Tested with @katjanakosic on TS1. Looks good!

**Review by katjanakosic — APPROVED** [review]
Tested on TS1 with @ArtemTsurikov. Worked fine :))

**Pull request merged**
