### PR TITLE
Instructor Course Dashboard: Show Submissions Button for Programming Exercises

### PR DESCRIPTION
**Pull request by Strohgelaender**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) ~~on the test server https://artemistest.ase.in.tum.de~~ locally.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context
The Assessment Dashboard shows the Submissions-Button for every exercise type (including programming exercises), the Instructor Course Dashboard did not. This PR makes this consistent and always shows the Submissions-Button.

### Steps for Testing

0. You need a course with exercises of every type and a user with instructor rights
1. Go to the Instructor Course Dashboard
2. Check that for every exercise the Submissions-Button is shown
3. Check that clicking the button opens the correct page

### Screenshots
old:
image

new:
image

### CODE REVIEW

**Review by KiraNickel — APPROVED** [review]
Tested on ts1. Works as described 👍🏼

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Worked for me.

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 3. Everything worked as expected.

**Review by ArtemTsurikov — APPROVED** [review]
Tested on ts1, works perfectly!

**Review by canyelten — APPROVED** [review]
Tested on TS1. Works as expected.

**Review by coolchock — APPROVED** [review]
tested on ts1, works as expected

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Works as expected

**Review by sinangunduz — APPROVED** [review]
tested on ts1, works as expected

**Review by joschahenningsen — APPROVED** [review]

**Pull request merged**
