### PR TITLE
`Programming exercises`: Update Ares to 1.11.3

### PR DESCRIPTION
**Pull request by tobias-lippert**
#### General
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Latest Ares Version that contains a bugfix.
### Description
Update for Ares dependency.
### Steps for Testing

Create a programming exercise, participate and check that the test results are still generated.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]

**Review by nikirovast — APPROVED** [review]
Tested on ts1, works as expected!

**Review by timo07k — APPROVED** [review]
Works as expected. Tested on TS2.

**Review by luisa1999 — APPROVED** [review]
Code looks good to me!

**Review by grochlitzzz — APPROVED** [review]
Everything working fine. Tested on ts2

**Pull request merged**
