### PR TITLE
`Development`: Increase client test coverage for file upload submission and file upload exercise

### PR DESCRIPTION
**Pull request by willergeorg**
#### General
- [x] I ran the tests locally, they all passed.
### Description

I increased the test coverage for two services:
`file-upload-submission.service.ts` was: 78%, is now: 91%
`file-upload-exercise.service.ts` was: 70%, is now: 85%

#### Code Review
- [x] Review 1
- [x] Review 2

### CODE REVIEW

**Review by MDK5 — DISMISSED** [review]
This uses for some reason the old way of writing these tests that should have been replaced a while ago: https://confluence.ase.in.tum.de/display/ArTEMiS/Client+Service+Test+Fix. Apparently this file was missed. Plase try to refactor it as described in the link, otherwise the tests cannot fail since the mocked response never gets sent.

**Review by MDK5 — APPROVED** [review]
Changes look good to me now :+1:

**Review by cremertim — DISMISSED** [review]
changes lgtm

**Comment by krusche** [comment]
The client tests currently fail. Please fix it before setting the PR ready to merge

**Pull request merged**
