### PR TITLE
`Assessment`: Hide complaint component on result subpage for exam exercises

### LINKED ISSUE #4984: Exam: Students Can File Complaints for Text Exercises Before the Review Period
### Describe the bug

In exams, it seems that students can file complaints for text exercises as soon as the results are published, even if the review period has not begun. For programming exercises, it seems to work as expected.

This is not a major problem, it is just strange that it works differently than expected.

### To Reproduce

1. Conduct an exam, grade it.
2. Set the result publication date, and set the review period to only start later
3. Once the results are published, from student view you can file complaints for text exercises (even though the review period has not started)

### Expected behavior

Students can only file complaints for text exercises once the review period started.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Chrome

### Additional context

To see the problem in action, one (w/ admin access to the TUM instance) can currently observe it on the FPV exam (course No. 182) before the start of the review period today at 1:30pm.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by mallgaier**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
**High priority** because students can submit complaints for text- / modelling- and file-upload exercises of an exam up to one week after the assessment due date. This is completely decoupled from the student review window and with that complaints can be filed potentially after the student Review window of an exam.

Closes #4984 

Currently students have two ways to complain about a text-, modelling- or file-upload exercise: 
- The complaint can be filed on the exam summary page. Here, the complaint can only be filed during the specified student review dates. This is the intended way how students should submit their complaints.
- The complaint can also be filed on the results - subpage of the exercise. Here, the complaint can be filed at any time because the complaint-component doesn't receive the exam information and thus cannot determine the student review period. The corresponding text-/modelling-/file-upload component also has no exam information, only a Boolean `examMode` is determined. Thus, the complaint component is displayed, as for normal course exercises, after the assessment due date, which is independent of the exam review period. That's also the reason the wrong hint with the limited number of complaints is shown to the student, because the complaint component identifies the exercises as a course and not as an exam exercise. (see screenshot) 

(Only these three exercise types use result subpages to display the assessment. Programming Exercises and Quiz exercises are displayed only in the summary and for quiz exercises no complaints are possible in general)

### Description
The complaint-component on the results- subpage for text-, modelling- and file-upload exercises only display the component if it is not an exam question. For this, the boolean `examMode` is reused.
In case of an exam question, the students can file their complaints on the exam summary page and the complaint-component on the results - subpage is not needed. 

### Steps for Testing
- 1 Instructor
- 1 Student
- 1 Exam with Text-, Modelling- and File-upload exercise 

1. Create the exam, participate as a student and assess the exercises
2. Open the exam summary page as a student between the `Publish Date of Results` and the `Student Review Start`. Make sure, that the complaint-button isn't shown on both the summary page and the results - subpage
3. Wait until the `Student Review Start`
4. Make sure, that the complaint-button is shown only on the summary page and not on the results - subpage

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots
The first and intended way students can submit complaints - via the exam summary page.
image

This complaint - component is currently displayed on the results - subpage for Text-, Modelling- and File-upload exercises. It should no longer be displayed. 
image

image

### CODE REVIEW

**Review by Dominik-Weinzierl — APPROVED** [review]
Tested with a Text Exercise in an Exam (TS2) - works as described. The Complaint button/textarea is only visible on the summary page, and not visible on the result page anymore :+1:

**Comment by krusche** [comment]
Thanks for the fix, but I think we should also verify on the server side that complaints after the review period are not accepted, if this is really the case.

**Review by Strohgelaender — APPROVED** [review]
I agree with @krusche, but I think as a client-hotfix (with the upcoming release in mind) we can directly integrate this and do more detailed checks in a follow-up PR. I would also find it great if the students could get access to this component on the subpage as well and we integrate / reuse the component on the summary page.

**Comment by mallgaier** [comment]
> I would also find it great if the students could get access to this component on the subpage as well and we integrate / reuse the component on the summary page.

The problem regarding the Compliant component on the subpages is that it reuses functionality from the normal courses. 
The text / modeling / file-upload component infers from the existence of an ExerciseGroup that it is an exam task (`this.examMode = !!this.fileUploadExercise.exerciseGroup;`). 

It would theoretically be possible to use the exerciseGroup to also fetch the exam `this.fileUploadExercise.exerciseGroup.exam` so that it is passed to the Complaint component of the subpage. The Complaint component then decides from the existence of an Exam which endpoint is used (server-side secured in #4990 ). Testing it on my local setup, this would also practically work. But I'm not sure, if this approach would be error prone or work in production

**Pull request merged**
