### PR TITLE
`Programming exercises`: Improve oracle generator for structural tests 

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
This PR resolves a few TODO items in the Oracle Generator.
It also adds support for private and static interface methods which were introduced in Java 9 but were not supported by the generator by this time.
The aim of this PR is to make the generated output directly useable without any additional modifications required when creating the tests.

### Description
- PrettyPrinting the JSON is now done directly via gson to avoid converting the data from gson-objects to jackson-objects.
- The recursive implementation of `walkProjectFileStructure` is removed and replaced by the native Java `walk` method.
- Improved performance of `getClassesFromFiles` due to only creating the `JavaProjectBuilder` once instead of every loop iteration.
- Removed duplicated code in `JavaClassDiff`
- Support for private and static interface methods out of the box.
- Override annotations are not part of the generated file since they cannot be tested against (Source Retention)

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise

1. Create a programming exercise in which the solution contains all types of new methods / attributes that the student should implement:
- Test normal features (new classes / atttributes / methods)
- Add all kind of interface methods (default / static / private)
- Implement these interface methods in another class and include the override annotation.
2. Click the "Update Structure Test Oracle" button
3. Check that the generated tests all pass for the solution, there is no need to further adapt the json file. 

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by ole-ve — APPROVED** [review]
Tested on TS1 with all supported (and unsupported) structural aspects and works as described. Code changes also look good to me.
I really like the feature 👍

However, I experienced the following behavior:
When creating the exercise, 13 Test Cases are generated from which 9 are structural tests generated by the oracle. When I update the oracle without any changes made to the code, suddenly 14 test cases appear. The structural test case `testMethods[MergeSort]` is now present, which was not the case before. 
I confirm that this is not caused by your changes as I experienced the same behavior on other test servers / the live server.
I think it still could be interesting to find the reason for that.
Note: This test case fails without your changes but passes when deploying your PR.

**Review by Hialus — DISMISSED** [review]
Reviewed the code changes.
Looks good to me. 👍🏻 
I left one optional suggestion.

**Review by Hialus — DISMISSED** [review]
Thanks for incorporating my suggestion so fast 😃 
Re-approve (Code) 👍🏻

**Comment by Strohgelaender** [comment]
The additional test is generated because `MergeSort` contains private methods which are not part of the jest.json in the test template (These are meant to be helper methods and not required from the student, that's why they are not tested in the template). The generator does not know that and therefore adds a new entry for these methods. So this is still something the instructor has to change after generating the oracle, but we cannot recognize helper methods as such on the server.

**Comment by Hialus** [comment]
> The additional test is generated because `MergeSort` contains private methods which are not part of the jest.json in the test template (These are meant to be helper methods and not required from the student, that's why they are not tested in the template). The generator does not know that and therefore adds a new entry for these methods. So this is still something the instructor has to change after generating the oracle, but we cannot recognize helper methods as such on the server.

In the future, we could maybe extend Ares to contain special Annotations for the code oracle (like not including a method) as this could reduce the workload on exercise creators.

**Review by ole-ve — APPROVED** [review]
Re-approve because only exception handling changed.

**Review by ole-ve — APPROVED** [review]
Re-tested on TS1, works as described 👍
In addition, code changes since my last approval look good to me.

**Review by Bofan-Zhu — APPROVED** [review]
Tested on ts1 as well. Tests successfully passed with interfaces. 👍

**Review by Hialus — APPROVED** [review]
Re-approve (code)

**Review by dveljacic — APPROVED** [review]
Tested on TS2. Looks good. ✅

**Pull request merged**
