### PR TITLE
`General`: Improve the user interface of course management exercises overview

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
This PR fixes 2 different issues on this page:
- Tutors are able to navigate to the Exercise Management Detail Page through the Student Exercise Detail view, but not through the course management like it is possible for editors & instructions -> makes no sense, only more difficult to navigate for tutors
- the "All Checked" checkbox for exercise was not updated, e.g. if you clicked "All checked" and then removed on specific checkbox of one exercise, the "All Checked" stayed checked, even though not all exercises are checked.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Tutor
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis as instructor
2. Navigate to Course Administration > Exercises
3. Verify that the selection of all exercises interfered with the selection of a specific exercise always gets rendered correctly
4. Log in as tutor
5. Navigate to Course Administration > Exercises
6. Confirm that it is possible to navigate to the Exercise Detail Page from here (by clicking on exercise ID or Exercise title)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [file-upload-exercise.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5680/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/file-upload/manage/file-upload-exercise.component.ts.html) | 91.37% | ✅ |
| [modeling-exercise.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5680/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/modeling/manage/modeling-exercise.component.ts.html) | 92.72% | ✅ |
| [programming-exercise.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5680/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/programming-exercise.component.ts.html) | 88% | ✅ |
| [quiz-exercise.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5680/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/quiz/manage/quiz-exercise.component.ts.html) | 88.49% | ✅ |
| [exercise.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5680/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/exercise/exercise.component.ts.html) | 89.28% | ✅ |
| [text-exercise.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5680/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/manage/text-exercise/text-exercise.component.ts.html) | 90.38% | ✅ |

### Screenshots
image

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Approve code

**Review by vinceclifford — APPROVED** [review]
Manually tested on TS2. Works as expected

**Review by xHadie — APPROVED** [review]
_Manually Tested on TS3_LEGACY_ 
Everything works as you described - no issues found.

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy ts11. Worked as expected.

**Review by AntonGeTUM — APPROVED** [review]
Tested on TS1, working as expected

**Pull request merged**
