### PR TITLE
`Exam mode`: Fix an issue when preparing the exercises shortly before the exam start

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
If an exam participation gets created shortly before the exam starts, the locking of this repository does not get scheduled. 

### Description
This PR reuses the new `sendRescheduleAllStudentExams` message to reschedule all locking tasks at the exam end date.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exam with programming exercises

1. Create an exam with a start date shortly in the future.
2. Edit the individual working time of different students
3. Press `Prepare Exercise start` with less than 5 minutes left until the start date.
4. Ensure that at the end of the exam, all repositories get locked. Ensure that the individual end date gets accounted for here.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by julian-christl — APPROVED** [review]
Code makes sense, looks good

**Review by julian-christl — APPROVED** [review]
Reapprove code

**Review by aplr — APPROVED** [review]
Looks good, thank you!

**Review by Hialus — APPROVED** [review]
Code looks good 👍🏻

**Review by krusche — APPROVED** [review]
code looks good 👍

**Pull request merged**
