### PR TITLE
`Programming exercises`: Change templates for plain Java exercises to contain a build file

### PR DESCRIPTION
**Pull request by ole-ve**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
As discussed with @krusche, the project types PLAIN_MAVEN and PLAIN_GRADLE (for Java exercises) should contain a build configuration file to unify the import process into the local IDE and to make it independent of the used IDE. 

### Description
The changes to the templates are as following:
- PLAIN_MAVEN: Eclipse files have been removed and replaced with a pom.xml
- PLAIN_GRADLE: All required files for importing the exercise as a Gradle project have been added.
- Remove Eclipse-file-related functionality from the creation of new PLAIN_MAVEN exercises. This functionality will not be removed from the ProgrammingExerciseExportService to support exercises that were created with the eclipse project files.
- Client-side: The UI has changed for selecting the project type (see picture below).

**Node**: The project type enum values are not accurate anymore. However, this is not visible to the client and in consideration of including this PR into 5.7.4, this will be adjusted in a follow-up PR.

### Steps for Testing
Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Create new Java Programming Exercises with the project types PLAIN_MAVEN and PLAIN_GRADLE (only one configuration is required, SCA and sequential test runs are not affected by the changes).
4. Clone and import the template/solution repository into your local IDE as Maven/Gradle project and verify that everything works as expected.
5. Older PLAIN_MAVEN exercises that have been created when this PR is not deployed (with Eclipse project files) can be imported when this PR is deployed.
6. Create a programming exercise for every language/project type and verify that the exercise is created for the correct language/project type. The correct project type should be chosen no matter how you wildly click through the UI. This is cumbersome to test. I would suggest to clone locally, change the functionality of the "Generate"-Button to only alert about the chosen project type but not actually creating an exercise. If you need help, contact me.

### Screenshots
Bildschirmfoto 2022-04-23 um 12 58 43

### CODE REVIEW

**Review by Hialus — COMMENTED** [review]
I don't know what you discussed with Stephan, but I currently don't understand why this change would make sense. As far as I see it there is now no difference between `PLAIN_MAVEN` and `MAVEN_MAVEN` projects, as in both cases the template repository is now a maven project. The same goes for the Gradle counterparts.

**Comment by bassner** [comment]
I actually agree with @Hialus.
From my perspective, it would be better to just drop the ``PLAIN_`` project types.
Including an "exemplary dependency" does not justify to have two more separate project types and templates imho.
And, to be honest, is anyone actually using ``PLAIN`` types?

**Comment by ole-ve** [comment]
> I don't know what you discussed with Stephan, but I currently don't understand why this change would make sense. As far as I see it there is now no difference between `PLAIN_MAVEN` and `MAVEN_MAVEN` projects, as in both cases the template repository is now a maven project. The same goes for the Gradle counterparts.

The general idea is to unify the importing process for students so that they don't have to switch between Maven/Eclipse and Gradle/Eclipse. In addition, the projects should be independent of the used IDE. In the future, both types may even be merged into a single one.

The only difference between the project types is that the "non-plain" ones contain an exemplary dependency. The UI has changed accordingly (see above screenshot).

**Review by bassner — APPROVED** [review]
After some discussion, it became more clear that the second project type is intended as an example on how to use dependencies in Artemis exercises (if the exercise needs dependencies) and can therefore be kept for now.
Thanks for adjusting the translations accordingly as suggested in DMs. :)

I've tested this on TS1 according to the testing steps and the last step locally. Everything seems to works as exepcted 👍 
Code looks good to me as well.

**Pull request merged**
