### PR TITLE
`Programming exercises`: Add the option to record the test-wise coverage for Java/Kotlin programming exercises with Maven

### LINKED ISSUE #4963: Add support for Testwise Coverage Analysis for Java/Kotlin Maven exercises on Atlassian-Setup
### Is your feature request related to a problem?

In #4889, support for Testwise Coverage Analyis for Java Gradle programming exercises on the Atlassian-Setup had been added. The [Teamscale JaCoCo agent](https://github.com/cqse/teamscale-jacoco-agent) is used for this analysis but has only been supporting the execution for Gradle projects.
Since support will soonly be added for Maven projects, it would be great to also support Java/Kotlin Maven programming exercises on the GitLab/Jenkins-Setup.

### Describe the solution you'd like

The build plan creation and the template `pom.xml` need to be adjusted accordingly.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ole-ve**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I documented the TypeScript code using JSDoc style.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- ~[ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab)~. _not applicable_

### Motivation and Context
Closes #4963.

These changes are part of the Bachelor Thesis from @Hialus and @ole-ve about the automatic generation of code hints for programming exercises (HESTIA) in Java.

The option to perform a testwise coverage analysis for the solution repository of Java Gradle programming exercises has been implemented in #4889. The resulting report is needed to generate behavioral solution entries for an exercise, from which code hints are generated. These changes extend this functionality to also work for (Java/Kotlin) Maven exercises. While only the generation of hints for Java exercises is in the scope of our thesis, I decided to also add the testwise coverage report option for Kotlin exercises since this can be done easily.

### Description
The utilized Teamscale JaCoCo Agent for generating the coverage report now also supports the execution for Maven projects.
If the option to perform a testwise coverage analysis has been selected on exercise creation, the `pom.xml` (in the test repository) contains a new profile for the test execution including the coverage analysis. This profile will only be executed for solution submissions, and not for template/student submissions. In case the option is not selected, the generated `pom.xml` is not changed in comparison to the current implementation.

### Steps for Testing
Prerequisites:
- 1 Editor on Test-Server with the Atlassian Stack (TS1, TS3)

1. Create a new programming exercise with the following configuration
- Programming Language: Java
- Project Type: Maven (selecting `with exemplary dependency` is not necessary)
- Activate SCA
- Activate the option "Record testwise coverage"
3. Wait for the solution build plan to finish
4. Click the button `Show testwise coverage` from the programming exercise details page.
5. Verify that the coverage report is displayed as in #4889.
6. Repeat step 1, but use Kotlin instead (note that package names in Kotlin cannot contain "in")

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
_no changes_

### Screenshots
For Kotlin exercises:
Bildschirmfoto 2022-06-08 um 22 05 36

### CODE REVIEW

**Review by JohannesStoehr — DISMISSED** [review]
Looked though the code and only found a nitpick about a translation

**Review by canberkanar — APPROVED** [review]
Tested on TS1 in accordance with the given instructions. All functionality is as expected. 👍🏻

**Review by mallgaier — DISMISSED** [review]
Tested on TS1, works as expected.
Code changes look good

**Review by canberkanar — CHANGES_REQUESTED** [review]
Tested on TS1 in the testing session. The coverage report is not generated correctly.

image

**Comment by ole-ve** [comment]
> Tested on TS1 in the testing session. The coverage report is not generated correctly.

I updated the used SNAPSHOT-version to the latest RELEASE-version, now everything should work as expected.

**Review by canberkanar — APPROVED** [review]
Retested on ts5. Coverage for Java and Kotlin exercises is visible after the build has been completed. 

However, I found the notification that suggests push to the repository to generate the report kind of confusing. The report was going to be generated after the build was completed.

**Review by Hialus — APPROVED** [review]
Code looks good. Also briefly tested it locally.
Great job getting the coverage to work for Maven exercises 🎉

**Review by JohannesStoehr — APPROVED** [review]
Code looks good to me

**Review by nairaarnez — APPROVED** [review]
Tested in ts1 with @mallgaier and @ole-ve. It worked as described. We stated that the testwise coverage cannot be changed after creating the exercise, this will be handled in a new PR by Ole. Approved!

**Pull request merged**
