### PR TITLE
`General`: Properly use translations for course enrollment in breadcrumb navigation

### PR DESCRIPTION
**Pull request by bensofficial**
#### General
- [x] This is a small issue that I tested locally.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Currently, `enroll` is shown in the breadcrumb if you want to enroll in a course.

### Description
This PR adds the link to the translation so that the correct English or German word is shown.

### Steps for Testing
Open the course enrollment page and check the breadcrumb.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Screenshots
| Description  | Screenshot |
| ------------- | ------------- |
| Previous breadcrumb text  | Screenshot 2023-10-22 at 12 24 29  |
| New breadcrumb text  | Screenshot 2023-10-22 at 12 28 11  |

Respectively the text was changed for English.

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code + screenshot lgtm

**Comment by egekurt123** [comment]
Deployed Build#2 on ts2 
Kurseinschreibung german
Kurzeinschreibung english

**Comment by bensofficial** [comment]
@egekurt123 I cannot reproduce the problem. Please make sure, that you deploy this branch in the latest version. This branch is currently on version `6.6.3` (and not `6.6.2`).
Thank you!

Screenshot 2023-10-23 at 06 54 08

**Comment by xHadie** [comment]
_Tested on TS3 Legacy_
LGTM 👍Changes are visible as you described and translation looks fine in english and german.

**Review by JohannesStoehr — APPROVED** [review]

**Pull request merged**
