### PR TITLE
`Text exercises`: Replace feedback modal with inline feedback view

### PR DESCRIPTION
**Pull request by EneaGore**
> Deploy only to TS1

Reopened from: https://github.com/ls1intum/Artemis/pull/9310
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

The previous PR in [Athena Feedback for Text Exercises](https://github.com/ls1intum/Artemis/pull/9241) added the option to enable preliminary AI Feedback for students. This PR improves the way the feedback is viewed by adding a new route. Enhanced error handling, integration tests and some minor bug fixes are also included.

### Description

Create new route to view the (preliminary) results inline on the text submission. Add the timeline to that view and make results not show the modal but use that route for text exercises.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Text Exercise

1. Open a text exercise with athena feedback requests avilable
2. Request feedback from inside the editor and from the overview
3. Click on results and check that the correct submission is shown
4. Assessment should continue working as usual

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

✅ ❌

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| header-participation-page.component.ts | 100% | ✅ |
| exercise-scores.component.ts | 95.59% | ✅ ❌ |
| feedback.component.ts | 95% | ✅ ❌ |
| rating.component.ts | 91.66% | ✅ ❌ |
| result.component.ts | 88.81% | ✅ ❌ |
| result.service.ts | 90.75% | ✅ ❌ |
| result.utils.ts | 89.94% | ✅ ❌ |
| text-editor.component.ts | 84.4% | ✅ ❌ |
| text-editor.route.ts | 100% | ✅ |
| course-exercise-details.component.ts | 88.47% | ✅ ❌ |
| exercise-details-student-actions.component.ts | 91.3% | ✅ ❌ |
| request-feedback-button.component.ts | 90.47% | ✅ ❌ |

### Screenshots

newAIButton
view
Flow

https://github.com/user-attachments/assets/8f9a89f4-9844-452a-b1a5-154deefa552a

## Release Notes

- **New Features**
	- Enhanced feedback request handling with new user messages for pending changes.
	- Improved exercise participation management with better error handling and access control.
	- New buttons for "Continue Submission" and "Request Feedback" in the text editor.
	- Added support for localized action labels in both German and English.
	- Dynamic filtering for exercise scores based on user input.
	- New functionality for viewing and hiding the timeline of submissions.
	- Introduction of a new feedback button component to streamline feedback requests.
	- New route configuration for accessing specific submissions in the text editor.

- **Bug Fixes**
	- Refined filtering logic for exercise scores and participation results.
	- Improved navigation handling for text exercises.
	- Adjusted success alert messages based on feedback generation results.

- **Documentation**
	- Updated localization strings for improved clarity and accuracy.

- **Chores**
	- General code refactoring for improved maintainability and readability.

### CODE REVIEW

**Comment by EneaGore** [comment]
@coderabbitai resolve

**Comment by EneaGore** [comment]
@coderabbitai resolve

**Comment by EneaGore** [comment]
@coderabbitai resolve

**Comment by EneaGore** [comment]
@coderabbitai resolve

**Review by eceeeren — APPROVED** [review]
Tested manually on TS1, works as expected

**Review by BBesrour — CHANGES_REQUESTED** [review]
Tested on TS1, automatic and manual assessment works as expected.

But there is an issue when importing exercises, even when the two checkmarks are checked, they are still marked as unchecked after exercise creation. Issue isn't present when creating a new exercise from scratch

image
image

**Review by BBesrour — APPROVED** [review]

**Review by BBesrour — APPROVED** [review]

**Review by FelixTJDietrich — APPROVED** [review]
Tested extensively again on TS1 and everything works as expected, you also no longer can request feedback for an empty submission which previously cased an internal server error alter.

Great work!

**Review by coolchock — DISMISSED** [review]
tested on ts1, works as expected

**Comment by EneaGore** [comment]
@coderabbitai resolve

**Review by HawKhiem — COMMENTED** [review]
Tested on TS1. Currently, AI feedbacks could not be generated.

image

**Comment by maximiliansoelch** [comment]
> Tested on TS1. Currently, AI feedbacks could not be generated.
> 
> image

Hey @HawKhiem 👋
Thanks for testing! The issue arises from the fact that you selected _module_text_coffee_ instead of _module_text_llm_ for your text exercise.

Can you change the assessment module and try again?

In a future PR, we must ensure that only modules that are capable of generating feedback are selectable.

**Review by sachmii — DISMISSED** [review]
Tested on TS1, I really like the new route. worked fine for me

Bildschirmfoto 2024-10-24 um 22 18 44

**Review by HawKhiem — APPROVED** [review]
Retested on TS1. Everything works as expected. One small thing was the rating of the feedback, I presume it hasn't been implemented yet. Should I open an issue for this?

image

https://github.com/user-attachments/assets/d1b267cf-9967-4717-9051-4a983a7ba52d

**Review by kevinfischer4 — COMMENTED** [review]
Tested on TS1. Works as expected. The feature is very cool and the responses are really helpful and give you very useful feedback.
Bildschirmfoto 2024-10-25 um 21 38 30

**Review by flbrgit — COMMENTED** [review]
Tested on TS2 and everything works as exected

**Review by SindiBuklaji — DISMISSED** [review]
Tested on TS1. It can evaluate correctly any different text that I tried. Super neat feature!👍
image

**Comment by ItsaaaMeMario** [comment]
Tested on TS1 with User 1, the feature works as expected.

Bildschirmfoto 2024-10-26 um 21 45 11

**Review by ItsaaaMeMario — APPROVED** [review]
Tested on TS1 with User 1, the feature works as expected.

380449367-9682577c-7f34-4e20-b526-318bf2fc61ce

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Reapprove

image

**Review by sachmii — APPROVED** [review]
Tested on TS1, still works fine. Re-approve

**Review by SindiBuklaji — APPROVED** [review]
Tested on TS1. Re-approved 👍

**Review by FelixTJDietrich — APPROVED** [review]
Tested on TS1 again to verify that everything is still working. Works really well, great job 🎉

**Pull request merged**
