### PR TITLE
Allow to define Manual Text Blocks during Text Assessment

### PR DESCRIPTION
**Pull request by jpbernius**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [ ] Client: I added multiple integration tests (Jest) related to the features
- [X] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [X] Client: I documented the TypeScript code using JSDoc style.
- [ ] Client: I added multiple screenshots/screencasts of my UI changes
- [X] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
#1634

### Description
Allow defining Text Blocks manually during assessment of text exercises.
Press `alt` / `⌥` during the assessment and select text to assess with the cursor. Release `⌥`afterward.

### Testing
Testing this PR should focus on:
1. Assessment for tutors
2. Display of result to students

**Steps:**
1. As a student: Submit Text exercise. (Use some longer text with multiple sentences to test this in a meaningful way.)
2. As a tutor: Assess the submission. Define feedback for both automatic blocks (by hover & click) as well as defining new blocks manually (`⌥` and select).  Edge cases include full text as a manual block, manual block at start/end.
3. View result as student, find all blocks as expected.

**Note:**
For me, displaying the result to students worked without problems so far. No modifications were made. Please test this with edge cases also, as display to students is critical.

### CODE REVIEW

**Comment by jpbernius** [comment]
Thanks for testing this PR @niclasschuemann and @alexmardale!

> 1. When selecting text for assessment, the first occurrence of that particular string is marked for assessment and not the specific part of the text that you have marked:

This, unfortunately, is a limitation of the selection API and cannot be circumvented easily. A possible work is to select a piece of text before (hover & click), select afterward (using `alt`), and then delete initial feedback.

> 2. Even though this will probably not happen that often, lines following a line with " ," at the end cannot be marked properly:

Can you elaborate on this problem? Can the browser not select the line including the `,`?

**Comment by niclasschuemann** [comment]
Regarding the problem with the " ," line:
I can mark the text properly, but Artemis does not create a feedback box for the highlighted text, if it contains a line break with " ," at the end. As @florian-glombik mentioned, this could be a more general problem, but I was only able to reproduce it with " ," line breaks. I am using the latest version of Chrome, but I did not test this with different browsers yet.

**Comment by tiffca** [comment]
The functionality seems to work well. 

The graded feedback results back to the student show up perfectly/as expected. 

I was able to I think re-create what Niclas faced. I think it's when a text group is also a candidate for auto-assessment, and if it's after an automatically graded group. 

There are assessments ready for grading in test server: 1, course: test, exercise: tiff 1705 test, students: test2, test3, test5 (test1 and test 4 already assessed). Browser: Chrome (macos). 

here is a video of the manual text assessment behavior (I was able to re-create it twice). 

re-create 1705 try 2

**Comment by jpbernius** [comment]
Thanks everyone for testing. 

The problems encountered here are unfortunately due to limitations of the text selection API (e.g. not selecting multiple spaces.)

We faced this in the past (e.g. #444) and we resolved this by moving to automatic text blocks. Bringing back these limitations (e.g. not seleceting instances with two spaces, or only selecting the first instance) is unfortunatly part of this change.

For now, we will merge this change as is and hope to eventually replace the text selection API with a more robust solution.

**Pull request merged**
