### PR TITLE
`Programming exercises`: Upgrade static code analysis dependencies

### PR DESCRIPTION
**Pull request by ole-ve**
#### General
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Upgrade multiple versions of SCA dependencies. This will also be covered in a [dependency update](https://github.com/ls1intum/artemis-maven-docker/pull/66) of the Docker image `artemis-maven-template` (same tag will be used for release).

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by bassner — APPROVED** [review]
I've created a new programming exercise on TS1 on this patch with static code analysis enabled and all looks like it's working fine. 👍

**Review by Strohgelaender — CHANGES_REQUESTED** [review]
Please also update the version templates/java/maven_maven/test.projectTemplate/pom.xml to remain consistent.

**Comment by ole-ve** [comment]
> Please also update the version templates/java/maven_maven/test.projectTemplate/pom.xml to remain consistent.

Thanks for heads-up, there also was the old version of Ares used (1.8.0). I updated both in 4c2a779.

**Review by Strohgelaender — APPROVED** [review]
looks good.

**Review by Strohgelaender — APPROVED** [review]

**Pull request merged**
