### PR TITLE
`General`: Fix user interface issues with notifications and assessment dashboard

### LINKED ISSUE #5262: `Notifications` are not wrapped
### Describe the bug

In the current version of Artemis (5.8.5) the notifications with longer texts are not wrapped, but have to be scrolled.
This makes the notifications hard to read (from my point of view)

### To Reproduce

Open Notifications Column

### Expected behavior

The Notification Column should could wrap the texts to make them more easy to read.

### Screenshots

image

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #5263: Horizantal scrollbar visible despite no need to
### Describe the bug

On the assessment dashboard there is a horizontal scrollbar for the Assessment information which is visible even when the full assessment information fits on the page.

### To Reproduce

1. Go to the assessment dashboard of a course
2. Look at the assessment information box in the upper right corner
3. There is a horizontal scrollbar below it although the box is fully visible

### Expected behavior

The scrollbar should only be visible when the box can't be fitted on the page.

### Screenshots

Screenshot (18)

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

There were some small UI issues reported regarding the notification sidebar and the assessment dashboard.

### Description

This PR fixes #5262 and closes #5263.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to the Assessment Dashboard
4. Ensure the table no longer displays a scrollbar (also check responsive design)
5. Trigger some long notifications
6. Open the notification sidebar
7. Ensure the text no longer runs off-screen

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

<details>
<summary>Screenshots</summary>

</details>

### CODE REVIEW

**Review by Hialus — APPROVED** [review]
Tested locally with live data and the notifications have been fixed. The scrollbar also no longer appears.
Code changes also look reasonable to me.
Well done 👍🏻

**Review by Dominik-Weinzierl — APPROVED** [review]
Code changes look good to me :+1:

**Review by Marvin-Vitcu — APPROVED** [review]
Tested on TS1. Workes as intended.

Really likes this fix :)

**Review by yuling-sun — DISMISSED** [review]
Tested on TS1. Works as described.

**Review by SimonPaul02 — APPROVED** [review]
Tested on Ts1, works as expected

**Comment by canberkanar** [comment]
Tested on TS1. Scrollbar on the table is not seen but notifications are not wrapped properly if the user has a very long name.

image

**Review by canberkanar — CHANGES_REQUESTED** [review]
Code looks good. Please look at my comment above.

**Review by nairaarnez — APPROVED** [review]
Tested in TS3, looks good! I also encounter myself with the small issue that [canberkanar](https://github.com/canberkanar) stated, other than that it worked as described

**Comment by ge65cer** [comment]
@canberkanar *sigh* I explicitly left that out since it seemed the browser would fit the whole username in one line when `nowrap` was set. Fixed now.

**Review by mallgaier — APPROVED** [review]
Tested on TS1, works as expected. 
Good job 👍

**Review by rhubinger — APPROVED** [review]
Teseted on TS2. Works as described.

**Review by nairaarnez — APPROVED** [review]
Tested it in ts1. Everything works as described!

**Review by jbllhff — APPROVED** [review]
Tested on ts2, works fine!

**Pull request merged**
