### PR TITLE
Trim solutions and answers when correcting a Short Answer Quiz

### LINKED ISSUE #2082: Short Answer Quiz Answers are not trimmed
### Describe the bug

Short answer quiz answers are not trimmed -> correct words can lead to errors, if they have spaces appended / prepended

#### To Reproduce

1. Create short answer quiz
2. Participate
3. Enter correct solution and append a blank

#### Expected behavior

should be marked as correct / should be trimmed so that the comp evaluates to true

#### Screenshots

**submitted**
image
**solution**
image

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
Closes #2082.

### Description
Strings are now trimmed before being compared for correctness. (Both on the server and client side.)

### Steps for Testing
1. Create a new Quiz using the Course Administration
2. Add a Short Answer Question (you can use the default template)
3. Open/Start the quiz and enter it from the student view
4. Enter a correct answer but put spaces in front and/or behind
5. Submit and view your corrected submission after the timer ran out

### Screenshots
When submitting "is " untrimmed:
grafik
Submitting just "is" without extra spaces:
grafik

### CODE REVIEW

**Comment by MaisiKoleni** [comment]
I guess this just continues #2087 under the same author but a different account, right? _(Just adding this comment to avoid confusion.)_

**Comment by FrankeLukas** [comment]
Yes.

**Comment by FrankeLukas** [comment]
Tested on the testserver, so should be good for review now.

**Review by TobiasPr — APPROVED** [review]
Works for me, good job :+1:

**Review by sjagla27 — APPROVED** [review]
Works as expected.

**Review by filip-gregurevic — APPROVED** [review]

**Review by balazs-czopf — APPROVED** [review]

**Review by fde312 — APPROVED** [review]
Works as expected and code looks good as well! Good job 🚀

**Review by krusche — APPROVED** [review]

**Pull request merged**
