### PR TITLE
[Bugfix] in exercise assessment dashboard show side table in exam mode

### PR DESCRIPTION
**Pull request by Olimbia23**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

For exercise-assessment-dashboard view, show tutor graph and exercise information table in a consistent way.
Before, in exam mode, __tutor graph_ was shown_ while the _side table was hidden_.
This PR places both these ui elements under the same conditions.

### Description

For Exercise Assessment Dashboard view:
1. Set the conditions to show the tutor-graph and the side-table to true in case of a normal exercise and Exam mode. 
2. Set to false in case of Test Run.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to an Exam
4. Navigate to Assessment Dashboard
5. Navigate to Exercise Dashboard.
6. You should be able to see both the **tutor graph** as well as **side-table** on the right.

### Before
Screenshot 2021-07-25 at 1 32 38 AM

### After

Screenshot 2021-07-25 at 1 25 42 AM

### CODE REVIEW

**Review by real-dmy — APPROVED** [review]
Tested on TS1, works as described.

**Review by NicolasUllmann — APPROVED** [review]
Tested on TS2. Everything worked as expected.

**Review by canyelten — APPROVED** [review]
Tested on TS1, works as expected.

**Review by imstreetspirit — APPROVED** [review]
looks good 👍

**Review by katjanakosic — APPROVED** [review]
Looks good on TS1 👍

**Review by lschlesinger — APPROVED** [review]
Tested on TS1, is shown as described.

**Review by SimonEntholzer — APPROVED** [review]

**Review by FuchsDominik — APPROVED** [review]
Looks fine during testing

**Review by sinangunduz — APPROVED** [review]
tested on ts2, works as expected

**Review by ArtemTsurikov — APPROVED** [review]
Tested on ts1, looks fine!

**Review by iozbeyli — APPROVED** [review]
Code changes look good

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Looks good

**Pull request merged**
