### PR TITLE
`Development`: Update documentation to JDK 17

### PR DESCRIPTION
**Pull request by mallgaier**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.(https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
With the recent update to `JDK 17` (see #4853 ), the documentation also needs to be updated

### Description
Updated `JDK 16` to `JDK 17` within the documentation. (Setup-Guide)

#### Code Review
- [x] Review 1
- [x] Review 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]

**Comment by bassner** [comment]
You might want to change the version in ``user/exams/students_guide.rst`` (Line 26) as well

**Comment by mallgaier** [comment]
> You might want to change the version in `user/exams/students_guide.rst` (Line 26) as well

This is only our recommendation to the students to use JDK 16 for programming exercises when participating in the Exam Mode. 
As this is not linked to the the Artemis-used JDK, I decided to not included in this PR.

**Comment by bassner** [comment]
Hmm. As far as I can see all the templates are updated to Java 17 (e.g. look at ``resources/config/application.yml``, line 36). As this is a pure docs update PR, I really think that we can include it.

Additionally, in the same file you edited is another mention of the Java version that needs to be updated (``docs/dev/setup.rst``, line 7).
Another spot that can be updated to a more recent example is in ``dev/docker.rst``, line 34

**Comment by krusche** [comment]
I merge this now to stay consistent at least for the development and will update all other places directly on `develop`

**Pull request merged**
