### PR TITLE
`Lectures`: Add a wizard mode for creating lectures

### PR DESCRIPTION
**Pull request by sebastiannikles**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
When creating a new lecture, not all the sub-menus for adding content to the lecture are visible instantly - this is especially true when trying to create a new exercise unit - and users that are new to Artemis might get stuck when they try to find the right menus and won't be able to add all the content they need.
This became apparent during a user study conducted for my Master's thesis where multiple users were not able to complete certain tasks because they got stuck on the platform during the lecture creation/setup.

### Description
In order to avoid that problem, users now have the option to switch to a guide mode aka a wizard mode when creating new lectures. That wizard mode is a step-by-step dialog where they can enter all information required such as lecture details, attachments, units, and learning goals right from the dialog.

This way, it's easy for new users to complete the entire setup for their lecture without getting lost. Content created during the wizard mode will be sent to the server so in case of accidentally leaving the page or deciding to leave the wizard mode, the changes will not be lost. It's also possible to edit in the wizard mode and switch between the two (as long as the lecture hasn't been created; afterwards leaving the wizard will lead to the lecture's detail page).

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 course where the user can add new lectures

1. Log in to Artemis
2. Navigate to Course Management
3. Navigate to Lectures
4. Click "Create New Lecture"
5. Click the "Switch to guided mode" button in the top right corner
6. Follow the dialog to set up a new lecture with all the content that the user needs

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

A short video of a sample usage of the wizard mode.

https://user-images.githubusercontent.com/16115423/196777146-bdbe3a26-d1ca-4846-b721-0c0216202ccc.mov

### CODE REVIEW

**Comment by sebastiannikles** [comment]
Need to fix the tests

**Comment by bassner** [comment]
I think we should keep the appearance consistent with the wizard interface used for code hint generation. This wizard looks quite different. We could use the same concept, but vertically, to match your solution; e.g. a circle with the checkmark on the left side of the section title with a vertical connection to the next one
image

**Comment by sebastiannikles** [comment]
I like the idea. I'll see whether using a vertical stepper or using the horizontal one works better and will update the PR

**Review by LiaLism — CHANGES_REQUESTED** [review]
I need to add two new lines in order for the text to appear in a new line in the preview mode.

**Comment by sebastiannikles** [comment]
@JonasGeigerTUM That should be fixed, that was/is also a problem with the current lecture creation.

@LiaLism Interesting behaviour. To be honest, I don't know too much about how the editor works and maybe that's - for whatever reason - even intended behaviour? I didn't change any functionality of the editor and just reused the component. I can also see the same behaviour in other usages of the editor, so it's not related to my changes. I would suggest maybe creating a separate issue for it?

**Review by PhilipWerz — DISMISSED** [review]
There are no obvious bugs. Tested on TS1. 

Remark: 

1. If you don't click on save attachment before you leave the page or the wizard mode, the progress will not be saved. 

2. When you create a new Lecture in wizard mode and get to attachments, then switch to normal mode and click on edit, then switch to guided mode again, not only attachments are displayed (as before leaving the wizard mode) but also Units and Learning goals.

**Comment by sebastiannikles** [comment]
With regard to the edit behaviour, that is intentional. When you edit an existing lecture (which it is in that case), I'm just opening all steps because we a) don't know at which step the wizard was left when creating the lecture (or if it was used at all) and b) if you edit a lecture, I think you should be able to see all contents at once so you can quickly edit them without having to step through first again

**Review by stefanwaldhauser — CHANGES_REQUESTED** [review]
I like the PR! Great job! But: I think you should generify the approach here already. We will be using wizards more in the future so you should imo make the wizards components more generic where I can easily transform any form into a wizard. 

- For example the steps all seem to have the `currentStep` property and then use a *ngIf to decide if to show the part of the form. Prime candidate to generify this structure with a generic component and a slot / ng-template

Same with the `wizard` itself. The functions for stepping through the wizard will be the same for all wizards. So it would make sense to put them into a generic component

**Review by manuelmanso — APPROVED** [review]
Great feature!

Some suggestions that you can implement either in this PR or as follow-ups if you agree:
- Create new exercise button takes user to the middle of the page instead of the top, and the "Back to lecture" button isn't very clear
- Make Submit buttons disabled while submitting
- Take user back to "Lectures" page instead of specific lecture page once they click "Finish"

**Review by evgeny1984 — APPROVED** [review]
Tested on ts2: the feature is working great. The code is looking good.
### Small remarks for follow-ups

- Go to the period not neccessary 
- The edit of the learning goal -> taxonomy is not selected

**Review by evgeny1984 — APPROVED** [review]
Looks great, approved.

**Comment by sebastiannikles** [comment]
As discussed during the testing session, I would address the small remarks you had in a follow-up PR where I would also work on making the wizard more generic as suggested by Stefan.

**Review by stefanwaldhauser — APPROVED** [review]
Approve now that I know you plan to make the wizard more generic in a follow up

**Pull request merged**
