### PR TITLE
`Assessment`: Fix missing translation on example submission board

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
PR #4397 introduced a missing translation error on the example submission board. 

### Description
I replaced the old key `importExampleSubmission` with the new key `useAsExampleSubmission`.

### Steps for Testing

1. Go to the example submission board (Course Management -> Exercises -> Select a Modeling or Text Exercise -> Example Submissions)
2. Check that the text is displayed correctly (see Screenshot)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
old:
grafik

new: 
grafik

### CODE REVIEW

**Review by ole-ve — APPROVED** [review]
Tested on TS1, works as described. Code looks also fine. 👍

**Review by baranimo7 — APPROVED** [review]
Tested on TS1, translation is shown correctly

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on TS1, works as expected.

**Review by dveljacic — APPROVED** [review]
Tested on TS3. Looks good ✅ 

fixed_translation

**Comment by krusche** [comment]
Thanks for fixing the issue 👍

**Pull request merged**
