### PR TITLE
Improve exercise scores: performance, paging, searching, filtering

### PR DESCRIPTION
**Pull request by krusche**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] ~Server: I added multiple integration tests (Spring) related to the features~
- [x] ~Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)~
- [x] ~Server: I implemented the changes with a good performance and prevented too many database calls~
- [x] ~Server: I documented the Java code using JavaDoc style.~
- [x] ~Client: I added multiple integration tests (Jest) related to the features~
- [x] ~Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)~
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
Related to #999 

### Description
We use ngx-datatable to improve the performance when many scores are displayed. This enables pagination. All this is done on the client side.

What is missing:
- Pagination should be customizable, e.g. 50, 100, 200, 500, all
- Search functionality is needed so that users can find scores of specific students quickly

### Steps for Testing
1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate into a course
4. Click on Scores for a programming exercise (with many scores)
5. Check that the page is loaded quickly (less than 5s) and is rendered correctly. Sorting, filtering and searching should work

### Screenshots

improved-datatable

### CODE REVIEW

**Comment by krusche** [comment]
@thilo-behnke @ungaralex help is appreciated when you have time

**Comment by thilo-behnke** [comment]
@ungaralex @krusche I'll take care of the rest of the implementation.

**Comment by thilo-behnke** [comment]
@ungaralex @krusche 

I finished the implementation, see screenshot in the description:
- Users can limit the search results by inserting student logins / names into the search field
- The text input can both handle single and multiple values (separated by comma) and has an autocomplete
- Paging can be switched dynamically during runtime (e.g. 10, 20, 50, ..., default is 50)
- Paging is cached in the localStorage

Some notes about the performance:
- When the paging is set to e.g. 100, the paging is a bit sluggish for me, must still be the HTML render. 50 seems to be the best setting.
- The autocomplete is only triggered when more than 2 characters are input (performance reason)
- The search in the input is debounced with 200ms (performance reason)

When we get more complaints about the performance we could try using a virtual list. But from my tests it should be fine with the paging and search. (I tested it shortly and we would probably need to do optimizations to our components because the scrolling in the virtual mode was very slow.)

**Comment by krusche** [comment]
I fixed some styling issues and made the search case insensitive. As this is a highly request feature, we merge and deploy this now. We can still further improve some aspects in the future.
I still found the following minor issues during testing:
- [ ] Resizing the window can sometimes a bit buggy.
- [ ] When changing the results per page limit, there should be a loading animation and the table should be completely redrawn so that issues due to content changes are eliminated
- [ ] After playing around with the column width preferences the table itself behaves quite good. However the footer is not aligned with the table all the time (minor styling issue)

**Comment by madwau** [comment]
I opened PR #1082 to address those open minor issues.

**Pull request merged**
