### PR TITLE
[Feature] [Orion] Assessment in Orion

### PR DESCRIPTION
**Pull request by MDK5**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all newly inserted strings into English and German.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context
This change enables Orion to edit assessment comments locally. Its Artemis' half of https://github.com/ls1intum/Orion/pull/64.

### Description
Adds a new OrionTutorAssessmentComponent which will be displayed to an Orion user instead of the CodeEditorTutorAssessmentContainerComponent. This component does not show the code editor and does send and recieve relevant data from Orion.

### Steps for Testing
These are the testing steps to ensure no regression happened, for the feature testing please go to the Orion PR

1. Log in to Artemis
2. Create/Locate a programming exercise with several submissions
3. Assess the submissions
4. Make sure especially the assessment page with the code editor behaves as expected

### Review Progress
- Code Review
  - [x] Review 1
  - [x] Review 2
- Manual Tests
  - [x] Test 1
  - [x] Test 2

### Test Coverage
Everything in /orion: 100%

### Screenshots
Refer to the Orion PR

### CODE REVIEW

**Comment by julian-christl** [comment]
1. Click on "Assess exercise with Orion"
2. Cancel the pop-up
3. Click on "Assess exercise with Orion" again
4. See that no pop-up comes up and the button also doesn't change its appearance.

**Review by julian-christl — CHANGES_REQUESTED** [review]
Change colors on green and red comments to the Artemis colour => less bright

**Review by julian-christl — CHANGES_REQUESTED** [review]
Bug:
1. Create a comment, save it, save in the internal browser
2. Delete the comment
3. Try to save it in the internal browser, see that the save button is inactive.

**Comment by MDK5** [comment]
> 
> 
> Bug:
> 
>     1. Create a comment, save it, save in the internal browser
> 
>     2. Delete the comment
> 
>     3. Try to save it in the internal browser, see that the save button is inactive.

Upon further investigation I found out this is intended behavior - it is explicitly forbidden to save or submit an assessment with no feedback comment; deleting comments should not block the save button unless it was the only one.

**Comment by julian-christl** [comment]
> > Bug:
> > ```
> > 1. Create a comment, save it, save in the internal browser
> > 
> > 2. Delete the comment
> > 
> > 3. Try to save it in the internal browser, see that the save button is inactive.
> > ```
> 
> Upon further investigation I found out this is intended behavior - it is explicitly forbidden to save or submit an assessment with no feedback comment; deleting comments should not block the save button unless it was the only one.

Then I think this is unintuitive. It makes sense that you can't submit without feedback but you should be able to save without one.
For example, you want to assess something, see that there is an issue and remove the wrong feedback. But you don't want to cancel it (which would remove the feedback) because you need to ask someone about it. Then you would want to save it to actually remove the wrong feedback.
I think as long as it stays internal (which "Save" does), the user should have all freedom.

**Review by julian-christl — APPROVED** [review]
Tested on TS 1, functionality works minus known issues that will be dealt with in other PRs.

**Review by julian-christl — DISMISSED** [review]
Code looks good, functionality works, tested on ts1

**Review by Malyuk-A — APPROVED** [review]
Code looks good 👍

**Review by Malyuk-A — APPROVED** [review]
re-approve of code

**Review by julian-christl — APPROVED** [review]
Reapprove

**Review by rs-maker — APPROVED** [review]
I approve of the code but i urge you to please consider making smaller PRs.

**Review by FlorianGlombik — APPROVED** [review]
Manually tested the related PR https://github.com/ls1intum/Orion/pull/64 and the functionality worked as described, the assessment feedback and related scores were saved properly in the database and displayed in the Application client.

Was deployed on ts5.

**Pull request merged**
