### PR TITLE
`Adaptive learning`: Fix import all competencies with relations

### PR DESCRIPTION
**Pull request by MaximilianAnzinger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context

This resolves a bug related to the bulk import of competencies from another course caused by a wrong endpoint call from the UI. Additionally it improves the propagation of updates to other components, to avoid that users have to refresh the page.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Course Administration of the course without competencies
3. Navigate to Competency Management
4. Scroll to competencies
5. Click 'Import Competencies'
6. Select 'Import all competencies of a course'
7. Select the other course with the competencies
8. Import them with relations
9. They should now appear in the table
10. Click on Edit relations and make sure you see all competencies and relations in the graph

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

unchanged

## Summary by CodeRabbit

- **New Features**
	- Introduced a new input property `allCompetencies` to the Competency Management Table, allowing for better management of competency data.
	- Enhanced the competency management component to utilize the `allCompetencies` property for improved data handling.

- **Improvements**
	- Simplified the URL structure in the import functionality of the Competency Service, streamlining the import process.

### CODE REVIEW

**Review by JohannesStoehr — DISMISSED** [review]
Code

**Review by HawKhiem — APPROVED** [review]
Tested on TS3. Everything works as described. All the imported compentencies and their relations showed up after being imported

Screenshot 2024-11-08 234039
Screenshot 2024-11-08 234118

**Review by sawys777 — DISMISSED** [review]
Tested on TS3, everything worked accordingly to the task description, a cool feature indeed.

**Review by flbrgit — DISMISSED** [review]
Tested on TS3. Everything works as described. Relations and Competencies are successfully imported from another course without problems
Screenshot 2024-11-09 113014

**Review by sachmii — APPROVED** [review]
Tested on TS3, works fine.

**Review by raffifasaro — APPROVED** [review]
Code LGTM

**Review by alekspetrov9e — DISMISSED** [review]
Tested on TS3, works accordingly to description.

**Review by kevinfischer4 — APPROVED** [review]
Tested on TS3, works as described.
Screenshot 2024-11-10 at 12 37 58

**Review by krusche — DISMISSED** [review]

**Comment by krusche** [comment]
I fixed the client test

**Review by krusche — APPROVED** [review]

**Pull request merged**
