### PR TITLE
`Development`: Remove unused endpoint to get single complaint

### PR DESCRIPTION
**Pull request by julian-christl**
#### General

- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

During work on other PRs I found that this endpoint has no usages as the complaintresponses get returned with the results.

### Description

I removed this endpoint and its helper methods as well as the tests.

### Review Progress

Make sure that the endpoint indeed has no usage throughout the system.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| ComplaintResponseResource.java | 100% |                            |

## Summary by CodeRabbit

- **Refactor**
  - Streamlined the complaint resolution process for enhanced user experience.

- **Tests**
  - Adjusted testing to reflect updated complaint handling procedures.

### CODE REVIEW

**Review by Strohgelaender — DISMISSED** [review]
lgtm, can confirm that the endpoint is unused in the webclient.

**Review by coolchock — APPROVED** [review]

**Review by MaximilianAnzinger — DISMISSED** [review]

**Review by Strohgelaender — APPROVED** [review]

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by coolchock — APPROVED** [review]

**Review by MaximilianJG — APPROVED** [review]
Looks good to me.

**Review by rstief — APPROVED** [review]
Code LGTM

**Review by kaancayli — APPROVED** [review]
Code lgtm

**Pull request merged**
