### PR TITLE
Fix some additional Instructor buttons being visible for Tutors

### PR DESCRIPTION
**Pull request by Strohgelaender**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) ~~on the test server https://artemistest.ase.in.tum.de~~ locally.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context
I found some more buttons which are only meant for instructors but they are visible for tutors as well if they have instructor rights in other courses.

### Description
Just checking for `*jhiHasAnyAuthority="['ROLE_ADMIN', 'ROLE_INSTRUCTOR']"` is not enough because this only checks for the global instructor role which is given to users who are instructors at any course. We need to check if the user is an Instructor in this specific course.

### Steps for Testing

Please test that the following buttons are not visible for tutors with instructor rights at other courses:

- Course Management -> Exams -> Create new Exam
- Course Management -> Exercises -> Tests this for modeling and programming exercises -> Scores -> Export Submissions -> Download all repositories

### CODE REVIEW

**Comment by Strohgelaender** [comment]
I added the "Help wanted" Label because I found one additional point where just the roles are used: https://github.com/ls1intum/Artemis/blob/df067ee4e6b6333ca0df332e72052fbd567bb612/src/main/webapp/app/exercises/quiz/manage/apollon-diagrams/apollon-diagram-list.component.html#L42
But here I don't know how to acces the course information, so maybe someone else can have a look at this.

**Review by PatZintel — APPROVED** [review]
Tested on ts1, apart from the fact that for Programming Exercises, the button "export submissions" is called "Download Repos", changes look exactly as described, tested with a tutor and an instructor

**Review by rs-maker — APPROVED** [review]
The code looks good to me. Here is what i did for testing
1. Made Artemis_test_user 8 instructor in another persons course (undid this after testing)
2. Made Artemis_test_user 8 tutor in my course
3. checked in ProgrammingExercise/Scores/DownloadRepos if download all repos was available and it wasnt 
4. checked in ModelingExercise/Scores/ExportSubmissions if export all submissions was available and it wasnt
5. checked in Exams if create new exams was available and it wasnt
6. All these options were available to an instructor in my course

i think these were the changes you intended and they worked as advertised.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Works as expected

**Review by NicolasUllmann — APPROVED** [review]
Tested on Server 3. Everything worked as expected.

**Pull request merged**
