### PR TITLE
`Exam mode`: Fix missing clone repository button for test runs

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
When running an exam test run, no clone repository button was displayed for programming exercises.

### Description
This issue was introduced by #6173 which aimed to hide the practice participation if it's possible to start a normal participation. However, the test run attribute is also used in the exam context. Here, starting the exercise is not possible, and the clone repository button should be shown for the test run.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Exam with Programming Exercises

1. Start a Test Run for the exam
2. Check that the clone repository button is visible
3. Also ensue that the issue described in #6173 is stil fixed.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by tobias-lippert — APPROVED** [review]
Tested in testing session on ts1. LGTM

**Review by danielbode — APPROVED** [review]
Tested on ts1 during the testing session. Works as expected!

**Review by JohannesStoehr — APPROVED** [review]
Code of bugfix and according tests look good to me

**Review by JohannesStoehr — APPROVED** [review]
New Comment and code rearranging looks good as well

**Review by danielbode — APPROVED** [review]
Reapproved

**Review by luisa1999 — APPROVED** [review]

**Review by PhilipWerz — APPROVED** [review]
Works as expected. Button is visible and no other issues. Tested on TS1.

**Pull request merged**
