### PR TITLE
`Development`: Configure dynamic repository checkout for local continuous integration

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

The ContinuousIntegrationService defines the RepositoryCheckoutPath for different programming languages. These checkout paths define where repositories are checked out to in the build job container. Local CI has not been using these predefined paths but this has not caused any issues for Java and Python. Other languages such as C use different paths from Java and Python, thus we should use the predefined paths. 

### Description

This PR refactors the populating of the build job container. The main change is that the predefined paths for the programming language of the exercise are used.

### Steps for Testing

Prerequisites:
- 1 Instructor
- Python exercise
- Java exercise

1. Trigger the template and solution builds of each exercise
2. Build results should be as expected

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by vinceclifford — APPROVED** [review]
Demonstrated during testing session, works as expected

**Review by sarpsahinalp — APPROVED** [review]
Demonstrated during testing session, works as expected

**Review by jakubriegel — APPROVED** [review]
Works fine

**Review by basak-akan — APPROVED** [review]
Demonstrated during testing session, build results worked as expected

**Pull request merged**
