### PR TITLE
Fix the list of complaints router link to the code editor

### LINKED ISSUE #3487: More Feedback Requests cannot be opened
### Describe the bug

I as an instructor cannot open a more feedback request or my teaching assistants. The web console shows a thrown error.

#### To Reproduce

1. Go to the Instructor Dashboard
2. Click on More Feedback Requests
3. Click on "Show the Request" -> Nothing happens
4. See in your web console

#### Expected behavior

The student's More Feedback Request shall be shown
### Environment

<details><pre>
 - OS: Windows 10
 - Browser: FF 88 and Edge (Version from Windows 10 21h1)
 - Artemis: 4.12.2
</pre></details>

#### Output in Web Console

<details><pre>
/api/account:1 Failed to load resource: the server responded with a status of 401 ()
/api/account:1 Failed to load resource: the server responded with a status of 401 ()
core.js:6210 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'course-management/3/programming-exercises/9/code-editor/674/assessment'
Error: Cannot match any routes. URL Segment: 'course-management/3/programming-exercises/9/code-editor/674/assessment'
    at Ie.noMatchError (router.js:2628)
    at a.selector (router.js:2610)
    at a.error (catchError.js:27)
    at a._error (Subscriber.js:75)
    at a.error (Subscriber.js:55)
    at a._error (Subscriber.js:75)
    at a.error (Subscriber.js:55)
    at c._error (Subscriber.js:75)
    at c.error (Subscriber.js:55)
    at s._error (Subscriber.js:75)
    at A (zone.js:1255)
    at A (zone.js:1209)
    at zone.js:1321
    at t.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:28564)
    at t.invokeTask (zone.js:433)
    at e.runTask (zone.js:205)
    at _ (zone.js:620)
Di @ core.js:6210
core.js:6210 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'course-management/3/programming-exercises/9/code-editor/674/assessment'
Error: Cannot match any routes. URL Segment: 'course-management/3/programming-exercises/9/code-editor/674/assessment'
    at Ie.noMatchError (router.js:2628)
    at a.selector (router.js:2610)
    at a.error (catchError.js:27)
    at a._error (Subscriber.js:75)
    at a.error (Subscriber.js:55)
    at a._error (Subscriber.js:75)
    at a.error (Subscriber.js:55)
    at c._error (Subscriber.js:75)
    at c.error (Subscriber.js:55)
    at s._error (Subscriber.js:75)
    at A (zone.js:1255)
    at A (zone.js:1209)
    at zone.js:1321
    at t.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:28564)
    at t.invokeTask (zone.js:433)
    at e.runTask (zone.js:205)
    at _ (zone.js:620)
    at e.invokeTask [as invoke] (zone.js:520)
    at _ (zone.js:1656)
Di @ core.js:6210
handleError @ core.js:6258
handleError @ sentry.error-handler.ts:46
next @ core.js:29184
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25926
(anonymous) @ core.js:28603
t.invoke @ zone.js:400
e.run @ zone.js:160
runOutsideAngular @ core.js:28506
onHandleError @ core.js:28603
t.handleError @ zone.js:404
e.runGuarded @ zone.js:174
t @ zone.js:1113
Zone.__load_patch.n.microtaskDrainDone @ zone.js:1125
_ @ zone.js:627
e.invokeTask @ zone.js:520
_ @ zone.js:1656
C @ zone.js:1682
</pre></details>

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context

#3136 changed the route for programming exercise submissions but forgot to change this link. Closes #3487.

### Description

We adjust the link.

### Steps for Testing

1. Go to the Instructor Dashboard
2. Click on More Feedback Requests
3. Click on "Show the Request" for a request/complaint on a programming exercise
4. There should be no error in the console and the code editor opens

Note: Since a lot of exercises were deleted in the last few days, please make sure the exercise you try to open the request for still exists. A testcase on TS1 is https://artemistest.ase.in.tum.de/course-management/306/more-feedback-requests with test user 1.

### CODE REVIEW

**Review by willergeorg — COMMENTED** [review]
Tested on TS1. When following the testing instructions and trying to open an open request to a programming exercise, I receive the following error in the console:

issue10000

Additionally, the system tells me that "Your Participation could not be found". Not sure if related to this PR or I got something wrong.

**Comment by FrankeLukas** [comment]
A lot of programming exercise were deleted during the last week, does the one the complaint still exist? I'll try to reproduce the error.

**Review by canyelten — CHANGES_REQUESTED** [review]
Tested on TS2. I observed the following problem after clicking on the "Show the request" button:

**Review by ndricimrr — DISMISSED** [review]
Tested on TS2, working well, no error logs 👍

**Comment by FrankeLukas** [comment]
@canyelten @willergeorg the issue you found should be fixed now.

**Review by PatZintel — APPROVED** [review]
tested on ts1, works as expected

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS1 and works

**Review by coolchock — APPROVED** [review]
tested in testing session, works as expected 👍

**Review by MDK5 — APPROVED** [review]
Tested in testing session, worked; changes make sense as well

**Review by ivohashamov — APPROVED** [review]

**Review by tobiasjungmann — APPROVED** [review]
tested in the testing session. Worked as described

**Review by ivanchimeno — APPROVED** [review]

**Review by KiraNickel — APPROVED** [review]
Tested on ts1, works as expected

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
