### PR TITLE
`Development`: Fix e2e playwright tests that navigate to a course page

### PR DESCRIPTION
**Pull request by muradium**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
After changes to course exercises page, directly accessing a course page does not open the first exercise. E2E tests relying on that fail.

### Description
This PR fixes the failing tests by navigating to exercise page instead of the course page.

### Steps for Testing
- **Code Review**: Ensure that tests pass for valid reasons, functionality is adequately tested and check the code quality.
- **Run the tests**: Tests are checked by automatic run in CI environment. You can also run them locally and check if they pass.

**Steps for running the tests:**
1. Navigate to **src/tests/playwright**
2. Configure Playwright using playwright.env file based on your local setup. Current configuration should work for default Artemis setup.
3. Run `npm install && npm run playwright:setup`
4. Run tests with following commands and confirm that they pass:
- `npx playwright test e2e/exercise/modeling/ModelingExerciseParticipation.spec.ts`
- `npx playwright test e2e/exercise/quiz-exercise/QuizExerciseParticipation.spec.ts`
- `npx playwright test e2e/exercise/ExerciseImport.spec.ts`

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **Refactor**
  - Updated login URLs to include exercise IDs for text, quiz, modeling, and programming exercises in the `Import exercises` test suite.
  - Enhanced login process for modeling and quiz exercises to ensure proper navigation and participation by including exercise IDs in the URLs.

### CODE REVIEW

**Review by coolchock — APPROVED** [review]
code changes and explanation make sense, the tests pass

**Review by JohannesStoehr — APPROVED** [review]
Changes look good and the corresponding e2e tests pass

**Review by edkaya — APPROVED** [review]
Corresponding e2e tests pass

**Review by rstief — APPROVED** [review]
shown in testing session lgtm

**Pull request merged**
