### PR TITLE
`Development`: Fix flaky tests in PostIntegrationTest

### PR DESCRIPTION
**Pull request by simon-hng**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

Flaky tests are not good

### Description

Replaces a spy and capture of a method call by a mock.
This allows multiple calls to the `JavaMailSender.send(...)` method to resolve.

This does not strictly resolve the racing conditions leading to multiple calls to the send method but instead just ignores them.

Test specificity is not decreased by this change 

### Steps for Testing

Create a script and run the test 100 times
```bash
# runner.sh
for i in {1..100}
do
   echo "Starting run: i=$i."
   ./gradlew cleanTest test --tests de.tum.in.www1.artemis.metis.PostIntegrationTest -x npmInstall -x webapp > "fixed/log-$i.txt" 2> "fixed/error/log-$i-error.txt"
done
```

Check the logs in `/fixed/error/` and check that there are no errors but only warnings instead.

Most error logs look like this for me
```
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
```

### CODE REVIEW

**Review by tobias-lippert — APPROVED** [review]
Ran the test 100 times locally and it always passed, code also LGTM

**Review by jakubriegel — APPROVED** [review]
Nothing failed after 100 runs

**Review by rriyaldhi — APPROVED** [review]
Executed 100 times successfully.

**Review by julian-christl — APPROVED** [review]
Works as discussed, thanks for the fix.

**Review by julian-christl — APPROVED** [review]
Works as discussed, thanks for the fix.

**Review by jakubriegel — APPROVED** [review]
100 runs no failures

**Pull request merged**
