### PR TITLE
`Exam mode`: Remove duplicated change submission status button

### PR DESCRIPTION
**Pull request by valentin-boehm**
#### General

- [x] This is a small issue that I tested locally.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The button on the student-exam-detail page that Instructors can use to change the sumbission status of a student-exam was displayed twice (see screenshot below). I assume that this was caused by a faulty merge.

### Description

I removed the duplicated button.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 exam after the due date and grace-period with at least one student exma

1. Go to the detail page of the student exam
2. Verify that the button to toggle the subission status is only displayed once

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
### Screenshots

Bildschirmfoto 2023-11-30 um 18 35 10

## Summary by CodeRabbit

- **Bug Fixes**
  - Removed a conditionally rendered button in the student exam details page to ensure consistent submission status visibility.

### CODE REVIEW

**Comment by Ceiridge** [comment]
Also tested on ts3, works as expected:

image
image
image

**Review by AntonGeTUM — DISMISSED** [review]
Tested on ts11, worked as described

**Review by Gusti2010 — DISMISSED** [review]
Tested on Ts11_Legacy. Works as expected!
image

**Review by vinceclifford — DISMISSED** [review]
Tested on T11, works as expected

**Review by xHadie — DISMISSED** [review]
_Manually tested on TS3_
Works as expected, the button is only visible once!

**Review by Strohgelaender — DISMISSED** [review]
lgtm

**Review by Ceiridge — APPROVED** [review]
See my comment above

**Comment by MaximilianJG** [comment]
Manually tested on ts2. Worked as expected!

**Review by b-fein — APPROVED** [review]

**Review by konrad2002 — APPROVED** [review]
manually tested on legacy ts11, works as expected

**Review by yassinsws — APPROVED** [review]
Tested on ts4, works as expected

**Review by georgyia — APPROVED** [review]
tested manually on ts3, works as expected

**Pull request merged**
