### PR TITLE
`Assessment`: Improve user interface for bonus and grading keys

### PR DESCRIPTION
**Pull request by akesfeden**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

The Grading Key and Bonus configuration pages have some usability issues such as non-uniform vertical alignments and unintuitive placement of buttons. These can be confusing to users and lead to a suboptimal user experience.

### Description

Improvements made in this PR are listed below:
- Grading Key
  - Moved common buttons (generate default, import-export) above the Interval/Detailed tabs.
  - Display the title of the exam or course instead of the id.
  - Aligned import-export buttons to the right to make the layout similar to other course/exam management pages.
  - Fixed vertical alignments of elements on the leftmost and rightmost sides.
  - Used fewer font sizes and boldness (Made Interval/Detailed tabs not bold).
  - Set table vertical alignment to middle.

- Bonus
  - Add numbering before each action item.
  - Tried to emphasize help text for inputs are extra information (and user can skip reading if not needed) by adjusting font sizes and moving the help icon to the beginning of the help message on create mode.
  - Convert upper and title cases to lowercase.
  - Fixed vertical alignments of elements on the leftmost side.
  - Improved font sizes and boldness.
  - Replaced some divs and spans with more semantic elements.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exam
- 1 Course (optional)

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to the `Grading Key` page of a course or exam.
4. Observe the UI changes written in the Description section above and make sure functionality is working as before.
5. Go to the `Bonus` page of an exam.
6. Observe the UI changes written in the Description section above and make sure functionality is working as before.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Not changed.

#### Bonus Create - Old
bonus_create_old 

#### Bonus Create - New
bonus_create_new_20220105

#### Bonus Edit - Old
bonus_edit_old

#### Bonus Edit - New
bonus_edit_new_20220105

#### Grading Key - Old
gradingKey_interval_old

#### Grading Key - New
gradingKey_interval_new_20220105

### CODE REVIEW

**Comment by simon-hng** [comment]
Try to use as many bootstrap styles as possible for consistency.
https://ng-bootstrap.github.io/#/home

Also have a look at the following pages, as they use similar components
- Programming exercise Grading page
- Exercise creation page

Otherwise good job!

**Review by frederik-kt — DISMISSED** [review]
Tested on TS1. Changes look good.

**Review by TheZoker — APPROVED** [review]
Tested on TS1, changes look good to me 👍

**Review by pellumbbaboci — APPROVED** [review]
Tested on ts2, works as expected. Code changes look good  :+1:

**Review by simon-hng — APPROVED** [review]
Code and screenshots look good to me

**Pull request merged**
