### PR TITLE
`Development`: Add support for evaluating BPMN diagrams in modeling exercises

### PR DESCRIPTION
**Pull request by matthiaslehnertum**
This PR adds a parser to support BPMN diagrams modelling exercises and bumps the integrated Apollon version to 3.3.4.

#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).(https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

To be able to use the full feature set offered from Artemis including Compass grading suggestions, the newly introduced BPMN diagram type also requires a corresponding parser.

### Description
This change adds a parser for BPMN diagram created with Apollon 3.x.x. No corresponding 2.x.x diagram schema parser has been implemented as no BPMN diagrams created with schema version 2.x.x exist.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Modelling Exercise with a BPMN diagram type

1. Log in to Artemis
2. Navigate to the course "BPMN Test" 
3. Navigate to the exercise "BPMN Modelling" (https://artemis-test6.artemis.cit.tum.de/courses/28/exercises/145)
4. Make a modelling submission
5. Ensure that the submission is accepted properly

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| BPMNTransaction | 89% | ✅              |
| BPMNAnnotation | 89% | ✅                           |
| BPMNSubprocess | 89% | ✅              |
| BPMNDataObject | 89% | ✅              |
| BPMNCallActivity | 89% | ✅              |
| BPMNGroup | 89% | ✅              |
| BPMNSwimlane | 89% | ✅              |
| BPMNTask | 94% | ✅              |
| BPMNEndEvent | 94% | ✅              |
| BPMNGateway | 91% | ✅              |
| BPMNIntermediateEvent | 96% | ✅              |
| BPMNStartEvent | 91% | ✅              |
| BPMNPool | 94% | ✅              |
| BPMNFlow| 66% | ✅                           |
| BPMNDataStore | 94% | ✅              |
| BPMNIntermediateEventType | 97% | ✅              |
| BPMNTaskType | 96% | ✅              |
| BPMNEndEventType | 96% | ✅              |
| BPMNStartEventType | 95% | ✅              |
| BPMNGatewayType | 95% | ✅              |
| BPMNMarker | 94% | ✅              |
| BPMNFlowType | 94% | ✅              |
| BPMNDiagram | 98% | ✅              |
| BPMNDiagramParser | 96% | ✅              |
| **Total** | 92% |               |

### CODE REVIEW

**Review by Predixx — APPROVED** [review]
tested during testing session. worked for me

**Review by egekurt123 — DISMISSED** [review]
Tested in a testing session on ts6, works as expected.

**Comment by coolchock** [comment]
tested during testing session. works as expected

**Review by MaximilianJG — APPROVED** [review]
Tested in a testing session! Works as expected! :)

**Review by coolchock — APPROVED** [review]
tested during testing session, works as expected

**Review by nata-81 — APPROVED** [review]
tested on ts6. works as expected.

**Review by basak-akan — DISMISSED** [review]
Tested in testing session, worked well

**Pull request merged**
