### PR TITLE
`Development`: Improve efficiency for deleting long manual feedback

### PR DESCRIPTION
**Pull request by az108**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

Follow up https://github.com/ls1intum/Artemis/pull/9562
While going through more refactor possibilities, I noticed a slightly more efficient implementation.

### Description

I changed the flag for automatic assesements to true, allowing the updateFeedback method to skip all automatic tests instead of iterating over them aswell.

Note: The saving of manual assesements for programming exercise needs further refactoring but this is not part of this PR!

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise 

1. Log in to Artemis as Instructor
2. Create a Programming Exercise
3. Log in as Student and participate in the Programming Exercise
4. Log in as Instructor and set the Due Date to now and set Manual Assesement 
5. Navigate to the Programming Exercise and press the View button in the TutorActions tab
6. Press the Assesement Dashboard button
7. Assess the Student Sumbission by creating a new Feedback with over 1000 characters
8. Save this and reload the page
9. Verify that the feedback box now displays the whole long feedback and no shortend version
10. Try to edit the long feedback and save again
11. Verify that the long feedback was changed
12. Do this for Modelling and Quiz and Text Exercises aswell

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
#### Manual Tests
- [x] Test 1
#### Performance Tests
- [x] Test 1

### Screenshots

Before:
image
After:
image

## Summary by CodeRabbit

- **New Features**
	- Enhanced feedback management process for improved storage and association with results.
	- Clarified handling of feedback visibility based on assessment types and due dates.
	- Introduced new test cases for assessment and feedback mechanisms, improving coverage and accuracy, including plagiarism checks.

- **Bug Fixes**
	- Resolved potential issues with feedback persistence and Hibernate exceptions.
	- Improved error handling and status code checks in assessment scenarios.

- **Refactor**
	- Updated internal logic for feedback handling methods to ensure correct functionality.

### CODE REVIEW

**Review by JohannesWt — DISMISSED** [review]
Code 👍

**Review by Jan-Thurner — APPROVED** [review]
Code 👍

**Review by HawKhiem — DISMISSED** [review]
Tested on TS1. Works as described 

image

**Review by florian-glombik — DISMISSED** [review]
Approve code, we should not need to execute the automatic tests when changing manual feedback 👍

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by b-fein — CHANGES_REQUESTED** [review]
[Question] I want to make sure I understand the changes before this is merged, therefore marked as request changes:

Why does `deleteLongFeedback` now only update manual results? There can be long feedback from automatic tests. Why does this not break the result score in such cases?

I would consider me quite familiar with how programming exercises and the long feedback work in Artemis. Since the answer is not obvious to me, I would expect it is even less so for someone else in the future. Please add an inline comment in the code why we can ignore automatic results here.

**Comment by az108** [comment]
@b-fein The update is only necessary to reload the feedback from the database when feedback is of type “lazy fetch.” The reason we can ignore automatic results for long feedback is that, based on my analysis, this error only occurred due to incorrectly handled manual submissions. In other words, this fix is required only for manual assessments, not for automatic assessments. The method typically includes a comment stating that it should not be used for fully automatic assessments. Would you like me to add another inline comment?

**Comment by b-fein** [comment]
> The method typically includes a comment stating that it should not be used for fully automatic assessments. Would you like me to add another inline comment?

Ah, I saw that the `Result.updateAllFeedbackItems` mentions this precondition in its Javadoc. Do you ensure, though, that `deleteLongFeedback` is only ever called with non-automatic results? Should there be an `IllegalArgumentException` in case the method is used for an automatic result to ensure this precondition cannot be violated? Since this could affect the scoring (also in exams) this might be important.

**Comment by az108** [comment]
@b-fein I verified that the current method is used exclusively for manual assessments. If anyone wants to use the deleteLongFeedback method in the future, they would naturally review its content and see that the updateFeedback method already includes an inline comment advising against its use for fully automatic results. However, if you still prefer, I can add another comment. I felt it was unnecessary, which is why I initially left it out.

**Comment by b-fein** [comment]
> If anyone wants to use the deleteLongFeedback method in the future, they would naturally review its content and see that the updateFeedback method already includes an inline comment advising against its use for fully automatic results.

To be honest, I don’t think they would. I would expect people to read at best the Javadoc. Since neither the method name nor the Javadoc mention any kind of limitation, that is the point where they will decide ‘Sounds good, I’ll use it’. And even if I’m assuming the worst and people look at the code, I think it’s unlikely that they will check every called method, too.

So, yes, I definitely would prefer a clear description of the precondition right after the first sentence of the Javadoc.

**Pull request merged**
