### PR TITLE
`Development`: Add note about lazy relationships to documentation

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Some time ago I noticed some inconsistencies with Lazy OneToOne relationships. After finding the cause of this Stephan asked me to add my findings to the documentation.

### Description

After some experimentation I found out the following: In order to make Lazy OneToOne relationships work you need to also add the `JoinColumn` annotation to the attribute. In addition this only works in one direction. The parent can lazily load the child, but not the other way around.

I added a small note about this to the database relationships documentation page.

### Steps for Testing

Go to [https://artemis-platform--5290.org.readthedocs.build/en/5290/dev/guidelines/database/](https://artemis-platform--5290.org.readthedocs.build/en/5290/dev/guidelines/database/) and check that the note is there.
Also, check if the note is understandable.

#### Documentation Review
- [x] Review 1
- [x] Review 2

### Screenshots

grafik

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Explanation for the Lazy relationships is clear

**Review by nadinesamyy — APPROVED** [review]
read through it, is understandable to me

**Review by ge65cer — APPROVED** [review]
Thanks for adding this to the documentation.

**Review by jbllhff — APPROVED** [review]
Thank you, the note is clear to me.

**Review by babyygemperor — APPROVED** [review]
The note is there and very understandable.

**Review by mallgaier — APPROVED** [review]
Changes look good 👍

**Pull request merged**
