### PR TITLE
Improvements to BambooService

### PR DESCRIPTION
**Pull request by krusche**
Various improvements in BambooService

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context
We would like to get rid of the used external library and implement the REST requests on our own.
This allows for more flexibility and means less dependencies on other libraries

### Description
* Re-implement a couple of REST calls between Artemis and Bamboo
* Made token authentication in BambooService mandatory
* Change `secret` to `token` for Jenkins
* No client changes

### Steps for Testing on TS1 and TS2

1. Create a programming exercise A
2. Participate in programming exercise A and check that everything works properly
3. Import programming exercise A into programming exercise B
4. Participate in programming exercise B and check that everything works properly
5. Delete the programming exercise A and B

### Test Coverage
I improved the test coverage for BambooService (now > 80%) and for BitbucketService (now 51%)

### CODE REVIEW

**Review by tiffca — CHANGES_REQUESTED** [review]
I deployed this release on test server 1
https://bamboo.ase.in.tum.de/deploy/viewDeploymentResult.action?deploymentResultId=297369866

I was not able to create a programming exercise, it throws the error: "Project already exists on the Version Control Server: tiff tifftest 2199-4. Please choose a different title and short name!"
even when I choose a different title and short name.

reproduce steps: 
1. as an instructor, try to create a new programming exercise 
2. leave the default options and choose a unique title and short name
3. Click generate
4. Error seen at the top. Expected: should be able to create a programming exercise 



I saw these errors in the logs: 
Failed to load resource: the server responded with a status of 401 ()
/api/programming-exercises/setup:1 Failed to load resource: the server responded with a status of 400 ()
instrument.js:109 ERROR TypeError: Cannot read property 'fieldErrors' of null
    at d._next (alert-error.component.ts:56)
    at d.__tryOrUnsub (Subscriber.js:183)
    at d.next (Subscriber.js:122)
...
    at s.invokeTask (zone.js:407)
    at Object.onInvokeTask (core.js:27474)
    at s.invokeTask (zone.js:406)
    at c.runTask (zone.js:179)
    at d.invokeTask [as invoke] (zone.js:488)
    at _ (zone.js:1598)
    at XMLHttpRequest.C (zone.js:1635)
(anonymous) @ instrument.js:109
4/api/programming-exercises/setup:1 Failed to load resource: the server responded with a status of 400 ()


Request URL: https://artemistest.ase.in.tum.de/api/programming-exercises/setup
Request Method: POST
Status Code: 400

**Comment by krusche** [comment]
@tiffca thanks for noticing this issue. Actually, the new token based authentication was using a wrong token in the yml settings. I fixed it, please try again

**Review by tiffca — CHANGES_REQUESTED** [review]
Hi, I noticed when we import an exercise into a new exercise, the old naming/package name is used. Then when I delete the original programming exercise, the student progress on the new programming exercise is affected (the repository enters a conflict state). 

Steps to reproduce (tested on test server 3): 
1. create a new programming exercise, for e.g. exercise A - works ok, participating, push/pull/online work seamlessly  
2. import the programming exercise as a new programming exercise, for e.g. exercise B 
3. start the programming exercise of exercise B. 
4. Notice the naming of the package retains the naming of the original exercise. Expected: it should have the new package name 
5. delete the original exercise 
6. try to participate in exercise B again. Notice the repository has entered a conflict state and the files have been deleted. Expected: the new repository should not be affected. 

Screenshots: 
Created exercise tifftest 2199-2, but the package retains the name of tifftest21991. Expected: package name=tifftest21992
image


the repository in a conflict state after deleting the original programming exercise 
image

**Review by sleiss — APPROVED** [review]
Tested it locally with my Bamboo instance, worked fine.

**Review by schultek — APPROVED** [review]
I tested it on TS3 and could not find any errors. I also could not reproduce the issue found by @tiffca .

**Pull request merged**
