### PR TITLE
`Modeling exercises`: Inline AI feedback view

### PR DESCRIPTION
**Pull request by LeonWehrhahn**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the principle of **data economy** for all database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

When students requested AI feedback for modeling exercises in Artemis, the feedback was previously only displayed as a list in a pop-up window. This made it difficult for students to correlate feedback comments with the corresponding elements in their diagrams.

The goal of this PR is to enhance the feedback experience for modeling exercises by allowing students to view AI-generated feedback directly on the diagram, similar to how tutor feedback is presented. This provides a more intuitive and interactive way for students to receive and understand feedback.

### Description

A new **Feedback View** for modeling exercises has been introduced to enhance the way students receive and interact with AI-generated feedback.

**Accessing the Feedback View:**

- **From the Modeling Editor:** Students can now request AI feedback directly within the modeling editor. After submitting and requesting feedback for their model, they can switch to the Feedback View by clicking on the result tag in the exercise header to see the feedback applied.
- **From the Exercise Overview:** On the exercise overview page, students can select different submissions from a timeline. Clicking on a submission will navigate them to the Feedback View, displaying the selected submission along with its associated feedback.

**Key Features of the Feedback View:**

1. **Feedback Displayed Directly on the Diagram:**

   - **Referenced Feedback:** Feedback linked to specific elements of the UML model is now displayed as annotations directly on those elements within the modeling editor. This visual association allows students to see exactly which parts of their model the feedback refers to.

2. **Unreferenced Feedback Listed Below the Diagram:**

   - **Unreferenced Feedback:** Feedback that is general or not linked to specific diagram elements is displayed below the diagram, similar to how unreferenced tutor feedback is presented.

3. **Submission History and Feedback Navigation:**

   - **Timeline of Submissions:** Students can view a history of their submissions in a timeline format. Selecting a previous submission loads the corresponding UML model and displays the associated feedback in the Feedback View.

4. **Request Feedback Directly in the Editor:**

   - **Feedback Button:** A "Request AI Feedback" button has been added to the modeling editor page. Students can now directly request feedback in the modeling editor.
  
### Steps for Testing

> Only Deploy to TS1

**Prerequisites:**

- 1 Instructor Account
- 1 Student Account
- A Modeling Exercise with the option to request AI feedback enabled

**Testing Steps:**

1. **Instructor Setup:**

   - Log in as an instructor.
   - Create a new modeling exercise with AI feedback enabled.
   - Ensure that the "Allow AI Feedback" option is checked.
   
2. **Student Participation:**
   - Log in as a student.
   - Navigate to the modeling exercise.
   - Create a model using the modeling editor.

   - **Request AI Feedback**:
     - Click on the "Request AI Feedback" button within the modeling editor.
     - Wait for the feedback to be generated.

   - **View Feedback on Diagram**:
     - Switch to the feedback view mode (accessed via a button or link).
     - Confirm that **referenced feedback** annotations are displayed directly on the diagram elements or **unreferenced feedback** is shown below
     
3. **Submission History:**

   - Make several changes to the model and request feedback multiple times.
   - Access the submission history or timeline in the feedback view.
   - Switch between different submissions and confirm that the corresponding feedback is displayed on the diagram and below it.
   - Verify that the model displayed corresponds to the selected submission's state.

4. **Access from Exercise Overview:**

   - Navigate back to the exercise overview page.
   - Access the feedback view mode from the overview.
   - Confirm that the correct model and feedback are displayed.

#### Exam Mode Testing

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

1. **AI Feedback View**: For the selected element class, the corresponding feedback can be seen on the right

image

2. **Submission History**: The submission history can be seen. By selecting a specific submission in the history timeline, the corresponding feedback for that particular submission is displayed

image

3. **Request AI feedback**: AI Feedback can now directly be requested in the modeling exercise header

image

## Release Notes

- **New Features**
  - Introduced a method to retrieve results based on participation ID and assessment type.
  - Added a new endpoint for fetching submissions with results for specific participations.
  - Implemented a new route for accessing submission details based on participation ID.
  - Added a new component for requesting feedback.

- **Improvements**
  - Enhanced feedback representation by simplifying the data model to use a single reference string.
  - Improved user interface responsiveness for feedback and submission processes.
  - Streamlined feedback suggestion processing for better clarity and efficiency.
  - Enhanced the submission view to include detailed result history and improved filtering based on user roles.
  - Improved error handling logic during feedback generation to ensure proper state management.
  - Updated submission component to manage feedback views and submission history more effectively.
  - Enhanced logging and access control for submission retrieval based on user roles.

- **Bug Fixes**
  - Refined error handling and logic for displaying results based on exercise types.
  - Enhanced testing coverage for submission retrieval functionality and component behavior.
  - Improved handling of user permissions and data filtering in the submission view.

### CODE REVIEW

**Review by HawKhiem — DISMISSED** [review]
Tested on TS1. Everything works as described

Screenshot 2024-11-16 202202
Screenshot 2024-11-16 202412
Screenshot 2024-11-16 202508
Screenshot 2024-11-16 202650
Screenshot 2024-11-16 202725
Screenshot 2024-11-16 202730

**Review by alekspetrov9e — APPROVED** [review]
Tested on TS1 by creating a BookLibrary Exercise. Works as expected.
Screenshot from 2024-11-17 18-44-28

**Review by Haoyuli2002 — COMMENTED** [review]
Tested on TS1, I created a modeling exercise as instructor 16 and enabled the AI request function. 
Then I logged in as Student 1 and modeled according to the problem statement. Indeed, the AI will give us a feedback and estimate our preliminary scores based on our model so far. Also if we continue to update our model and request AI feedback consequently, we will also see the sequence of AI feedback along with its scores. 
I would say that this feature is working as expected and looks good to me. However, I would say the AI is not very accurate, meaning that it could possibly provide the students with some wrong feedback.
For example:
The class SUV should extend the class Car and I used the wrong direction of the Inheritance, but AI will tell us that this association is correct. However, AI has nothing to do with this feature and the inline AI feedback view is good enough.
Screenshot 2024-11-18 at 15 56 31

**Review by sachmii — APPROVED** [review]
Tested on TS1, features worked just fine for me.

Bildschirmfoto 2024-11-18 um 18 54 11

**Review by sachmii — DISMISSED** [review]
Tested on TS1, everything works fine. Re-approve

**Review by HawKhiem — DISMISSED** [review]
Tested on TS4. Reapprove

**Review by Haoyuli2002 — COMMENTED** [review]
Tested on TS 2, everything works as expected. Reapprove :D

**Review by Haoyuli2002 — APPROVED** [review]
Reapprove :D

**Review by EneaGore — COMMENTED** [review]
Test on TS1. Works as expected. Code also lgtm, i like the use of reference instead of elementid. In a next PR i would suggest safeguarding from spamming the AI Button.
1 translation is missing.
translation

**Review by EneaGore — APPROVED** [review]
Thanks for the fix

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Reapprove

**Review by sachmii — APPROVED** [review]
Tested on TS1, re-approve.

**Review by maximiliansoelch — APPROVED** [review]
Tested on ts1, and works as expected 👍
Minor improvements, such as preventing spamming the request feedback button and highlighting the currently viewed feedback in the timeline, will be done in a follow-up PR.

**Pull request merged**
