### PR TITLE
`Exam mode`: Fix an issue with formatting the problem statement when switching between exercises

### LINKED ISSUE #7566: `Exam mode`: Switching between exercises breaks formatting of problem statement
### Describe the bug

When switching between exercises via the Exam Navigation Bar the formatting of Programming Exercise Problem Statements breaks.

### To Reproduce

1. Participate in Exam (at least two Programming Exercises)
2. Switch between them via the Exam Navigation Bar (top-center of your screen)
3. View Problem Statement of Programming Exercise

### Expected behavior

The style of Tasks should not be affected.

### Screenshots

chrome_9keYEtF7jb

https://github.com/ls1intum/Artemis/assets/63976129/c40a667a-371f-4d6b-b380-0ccb5e439252

### Which version of Artemis are you seeing the problem on?

6.6.4

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

independent from browser

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by RY997**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [ ] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [ ] I documented the TypeScript code using JSDoc style.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [ ] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Description

Fixed #7566 
#### Exam Mode Testing

Try to reproduce #7566 .

If test on TS4, you can use exam  'Task Injection'
1. Log in to Artemis
2. Participate in the exam as a student
3. Check the problem statement shows correct after switching to another programming exercise
4. Make sure that the UI of the programming exercise in the exam mode stays unchanged. 

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by sarpsahinalp — APPROVED** [review]
I tested it on ts4, and it seems to be working. There where no changes in the problem statement.

**Review by basak-akan — APPROVED** [review]
Tested on TS4, the problem statement of programming exercise is not changing while switching between via exam navigation bar.

**Review by milljoniaer — APPROVED** [review]
Code looks good, tested on ts4, works as expected 👍

**Review by Strohgelaender — APPROVED** [review]
code lgtm
Thanks for looking into this!

**Review by MichaelOwenDyer — APPROVED** [review]
Works perfectly 👍🏽

**Pull request merged**
