### PR TITLE
`Programming exercises`: Fix race condition on exercise detail page for instructors

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

While using Artemis I noticed that the git-diff statistics were not displayed at random times (for the same exercise).
Here it is not displayed:
grafik

And here it is displayed:
grafik

### Description

This was caused by the fact that the programming exercise got overridden by another REST request and the git-diff report was therefore deleted. 
This issue was previously fixed for auxiliary repositories by copying them from the old to the new programming exercise.
I applied this same mechanism to the git-diff report and also the submission policy, as the same problem can happen there as well.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise

1. Log in to Artemis
2. Navigate to the programming exercise detail page (for instructors)
3. The git-diff statistics are always visible even after refreshing the page multiple times

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| programming-exercise-detail.component.ts | 53% | 53% |

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Tested on TS1 and also looked at the code. 👍

**Review by manuelmanso — APPROVED** [review]
Worked on TS1. Code change looks good.

**Review by rhubinger — APPROVED** [review]
Tested PR. Works as described.

**Review by pantageepapa — APPROVED** [review]
Tested on ts2 and the message is visible as described!

**Review by mallgaier — APPROVED** [review]
Tested on TS1, works as expected.
Code changes also look good!

**Pull request merged**
