### PR TITLE
`Communication`: Add shortcut to private messages on usernames

### PR DESCRIPTION
**Pull request by PaRangger**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Currently you the only option for you to directly create a one to one chat with another user is by clicking the create channel icon and searching for the user. This creates a lot of interactions and server calls, which could be avoided by simply providing an option to click usernames to jump to a private channel.

### Description

I added the option to click on usernames in channels to directly jump to a one to one chat with the user. You should not be able to click your own username or the username of deleted users. Additionally, I added a api to create a one to one chat by user id for the native apps.

### Steps for Testing

Prerequisites:
- 2 Students/Tutors/Instructors
- 1 Course with communication enabled

1. Log in to Artemis with user 1
2. Navigate to course
3. Navigate to the communication tab
4. Create a message
5. Log out with user 1 and log in with user 2
6. Go to the same channel
7. Click the username of user 1
8. You should be redirected to a one to one chat with user 1

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| one-to-one-chat.service.ts | 100% | ✅ |
| metis-conversation.service.ts | 85.1% | ✅ |
| metis.service.ts | 86.69% | ✅ |
| post.component.ts | 95.19% | ✅ |
| posting-header.directive.ts | 93.75% | ✅ |
| posting.directive.ts | 93.58% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| OneToOneChatResource.java | 100% | ✅ |

### Screenshots

shortcut

## Release Notes

- **New Features**
  - Added functionality to initiate one-to-one chats using user IDs.
  - Enhanced interactivity in post and answer components with new event bindings for user interactions.

- **Bug Fixes**
  - Improved handling of user reference clicks and username clicks across various components.

- **Documentation**
  - Updated comments and documentation to reflect changes in method parameters and return types.

- **Tests**
  - Added new test cases for one-to-one chat creation and user interaction scenarios.
  - Renamed existing tests for clarity and improved structure. 

- **Chores**
  - Cleaned up imports and updated test setups for better organization and maintainability.

### CODE REVIEW

**Review by sachmii — APPROVED** [review]
Tested on TS1, works just fine.

**Review by ItsaaaMeMario — APPROVED** [review]
Tested on TS1, works as expeced!

https://github.com/user-attachments/assets/4856a654-e915-4658-9485-3ab43a190e38

**Review by HawKhiem — APPROVED** [review]
Tested on TS5. Works as described

**Review by sawys777 — APPROVED** [review]
Tested on TS5, the shortcut works as expected.

**Review by asliayk — APPROVED** [review]
tested on ts2 and works as expected

**Review by krusche — APPROVED** [review]

**Pull request merged**
