### PR TITLE
`Programming exercises`: Fix export of multiple repositories

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
Tutors could not export multiple student repositories since the "Export All Repositories" Flag was enforced during export. but this flag is only allowed for instructors which resulted in a 403 response of the server. 
However, this also led to a misleading UI for instructors, since regardless what they chose for this flag, it was used anyways. So for them it was also not possible to export only the repositories of a subset of students. 

### Description
This PR moves the logic for the allRepositories flag to the init function so that it doesn't destroy the UI for instructors.
Also, this PR adds warnings, if there are no submissions for an exercise or a non-existing student was specified.
Lastly, the disabled Button for invalid export form was fixed, so it is no longer possible to submit without students specified or without allRepositories flag.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Tutor
- 1 Programming Exercise with Submissions

1. Log in to Artemis as instructor
2. Navigate to Course Administration -> Exercise Overview
3. Select Multiple Exercises
4. Click "Download Repositories"
5. Verify that the export works
6. Select single exercise
7. Export once with allStudents flag and once with not-existing student identifier
8. Verify that the first one works and the second one displays a warning
9. Log in as tutor
10. Go to scores view of an exercise
11. specify multiple student names and export the repositories
12. Verify that it works

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
image

### CODE REVIEW

**Review by MichaelOwenDyer — APPROVED** [review]

**Comment by sarpsahinalp** [comment]
I tested the steps on ts3. All the steps are working, and the exports functions properly after pressing the "Download Repos" button. Additionally, when there is no repository for an exercise, it generates an error. Here are some screenshots from my testing:

Screenshot from 2023-10-17 13-14-05
Screenshot from 2023-10-17 13-09-30

**Review by sarpsahinalp — APPROVED** [review]
I tested the steps on ts3. All the steps are working, and the exports functions properly after pressing the "Download Repos" button. Additionally, when there is no repository for an exercise, it generates an error. Here are some screenshots from my testing:

Screenshot from 2023-10-17 13-14-05
Screenshot from 2023-10-17 13-09-30

**Comment by Gusti2010** [comment]
tested on Ts3. Everything works as expected.

**Review by LenaKahle — APPROVED** [review]
Approve, tested on Test Server 3.

**Review by reschandreas — APPROVED** [review]
tested locally, LGTM. Thanks for fixing this!

**Review by Gusti2010 — APPROVED** [review]
tested on Ts3. Everything works as expected.

**Pull request merged**
