### PR TITLE
Prevent creation of empty textblocks

### PR DESCRIPTION
**Pull request by linusmichel**
### Motivation and Context
When assessing text-exercises with multiple sentences with spaces or newlines in between 2 textblocks, an empty textblock with this space/newline in between got created in the database. This PR fixes this problem

### Description
- Introduced a check to prevent the creation of empty (only spaces/newlines) textblocks

### Steps for Testing
1. Create a text-exercise
2. Create a submission with multiple sentences separated by ". " (mind the space after the ".")
3. Assess the submission using the automatic selection of text-blocks
4. Submit the assessment
5. Check the database (Table "text-block") for empty entries

### CODE REVIEW

**Comment by linusmichel** [comment]
Thanks for discovering this! I could reproduce the issue now. This is not related to the change in this PR, since it happens while loading the submission and creating the textblocks initially. Anyway, I will have a look at this bug!

**Comment by linusmichel** [comment]
The issue was the declaration of the `LINE_SEPARATOR` in `TextBlockService.java`. Since there was a double-`\` in the declaration (`\\n` instead of `\n`), the length of it was evaluated to 2, which caused the `splitSubmissionIntoBlocks`-method to set wrong start/end-indices of the TextBlocks. Removing the doubled `\` resolves the issue (on macOS and Linux). Can someone test it on Windows?

@jpbernius Do you know the background of the doubled `\`?

**Comment by JonasPetry** [comment]
Newlines are shown correct now! Good Job! One think I noticed is that multiple SPACE right next to each other are capped to just one. I think this is ok because I don't really see a scenario where this would matter, but I wanted you to know that!

Submission:
image
Assessment:
image

**Comment by madwau** [comment]
> One thing I noticed is that multiple SPACE right next to each other are capped to just one. I think this is ok because I don't really see a scenario where this would matter, but I wanted you to know that!

Was this also the case before? I could see scenarios where this would have unwanted effects, e.g. when someone is trying to align content into a tabular structure (similar to tables in markdown) but I'm not sure if we want to support something like that at all.

**Comment by linusmichel** [comment]
Yes, this was also the case before. So nothing changed here so far.

**Pull request merged**
