### PR TITLE
`Development`: Convert to new control flow syntax in Angular 17

### LINKED ISSUE #7773: `Development`: Add lint rule to enforce Angular 17 control flow syntax
### Is your feature request related to a problem?

#7751 introduces the new [Angular 17 control flow syntax](https://angular.io/guide/control_flow), which is now preferred over the previous html-markup based approach.

### Describe the solution you'd like

A new eslint rule should enforce the use of the new control flow style, by throwing errors if the rule is violated.

* angular-eslint v17.1.1 adds `prefer-control-flow` rule: https://github.com/angular-eslint/angular-eslint/releases

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
The new control flow syntax is easier to understand.
Closes #7773.

### Description
The code is automatically converted using `ng generate @angular/core:control-flow`

### Testing steps

Test the main functionality and check that everything still works correctly.

Especially test places where we use multiple containers on the same page (e.g. the code editor, the assessment view of any exercise type, the exam mode) and check that the projected content is visible.

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

### CODE REVIEW

**Review by MichaelOwenDyer — APPROVED** [review]
did a thorough code review and looks good to me :^)

**Review by rriyaldhi — APPROVED** [review]
Tested Quiz Exercises and Exam mode (All Exercise Type). Couldn't find any noticeable errors.

**Review by valentin-boehm — APPROVED** [review]
Checked all `@switch` statements, there are no overlapping cases left. Also looked at the manual changes, they look good.

**Review by aplr — APPROVED** [review]
lgtm

**Pull request merged**
