### PR TITLE
`General`: Unify header padding

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Improve and unify the appearance of ui elements in Artemis to have a more consistent design.

### Description

The course header was not aligned with the other components around it and had a smaller padding on the left/right side than other ui elements. This is now unified to a common distance.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Text/Modelingexercise

1. Log in to Artemis
2. Check different headers in Artemis that they have a consistent padding. These include:
- The course header in the student and the course management view
- An exercise header
- The participation header when working on/viewing a submission in a text/modeling exercise
- The assessment dashboard
- Lecture detail page
3. Click around and look if there are any other headers that have a too small/large padding

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Before (for example the breadcrumbs and the title in the header are misaligned):
Bildschirmfoto 2023-07-11 um 10 15 01

After (with and without a course icon on the right):
Bildschirmfoto 2023-07-11 um 10 29 39
Bildschirmfoto 2023-07-11 um 10 30 04

### CODE REVIEW

**Review by DemjenDavid — APPROVED** [review]
Looks consistent, tested on ts3

**Review by SabrinaGlatz — APPROVED** [review]
Tested on ts4, looks as expected.

**Review by fschoenberger — APPROVED** [review]
Looks good.

**Review by DominikRemo — APPROVED** [review]
Code LGTM

**Pull request merged**
