### PR TITLE
`General`: Fix display of no submission after due date

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Fix a bug where nothing was displayed after starting an exercise without submitting anything and waiting for the due date to pass.

### Description

This Pr fixes he bug and now shows correctly "No submission" in this case.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 non-Quiz Exercise with a due date

1. Log in to Artemis
2. Navigate to Course Administration
3. Start the exercise but do not submit anything
4. Check that the exercise row correctly displays "No submission"
5. Wait for the due date to pass
6. Check again that the exercise row still correctly displays "No submission"

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image

### CODE REVIEW

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM

**Review by Strohgelaender — APPROVED** [review]
code changes make sense

**Review by SolizerCodes — APPROVED** [review]
Works on ts1 👍

**Review by DominikRemo — APPROVED** [review]
Tested on ts1. Works as expected

**Pull request merged**
