### PR TITLE
`Development`: Add documentation for build agent view

### PR DESCRIPTION
**Pull request by mateusmm01**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

The docs were missing a user guide for the build agent view. This is a stacked PR with https://github.com/ls1intum/Artemis/pull/8413

### Description

https://artemis-platform--8417.org.readthedocs.build/en/8417/user/exercises/programming.html#build-agent-view

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

## Summary by CodeRabbit

- **Documentation**
    - Added a detailed guide on using Git for programming exercises, covering accessing and viewing submissions for students and reviewing submissions for instructors.
    - Enhanced the programming exercise documentation with sections on the integrated code lifecycle system, including Repository View and Build Agent View.

### CODE REVIEW

**Review by laurenzfb — DISMISSED** [review]
lgtm 🚀

**Review by JohannesWt — DISMISSED** [review]
Looks good

**Review by milljoniaer — DISMISSED** [review]

**Review by laurenzfb — APPROVED** [review]

**Review by JohannesWt — APPROVED** [review]
Reapprove

**Review by milljoniaer — APPROVED** [review]

**Review by rstief — APPROVED** [review]
LGTM 👍

**Pull request merged**
