### PR TITLE
`Programming exercises`: Fix display of long feedback details and submission count in exams

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).

### Motivation and Context

The `FeedbackDTO` did not contain the ID of the feedback. This causes that in the feedback detail view a potential long feedback can no longer be fetched, since the ID of the feedback it belongs to is required to construct the URL and know on the server which feedback should be fetched.
Currently it tries to fetch the long feedback from an URL like
https://ARTEMIS/api/results/123456789/feedbacks/undefined/long-feedback
which fails since `undefined` is not a valid id.

### Description
Adds the ID of the feedback to the DTO.
Then the feedback can be fetched from the server again.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming exercise

1. Add a test case in the exercise test repository that contains a long feedback, e.g. by placing a `fail("abc".repeat(10_000))` method call inside.
2. Instructor view of the exercise: ‘Edit in Editor’ to open the online editor, select the solution repository.
3. Submit this solution, the ‘Building and Testing’ spinner is started.
4. When the result from the CI system is returned, open the feedback details and then the ‘See more’ for the test case with the long feedback.
5. The additional text should be loaded without error.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by Strohgelaender — DISMISSED** [review]
lgtm (I included the same fix in #7015 :) )

**Review by chrisknedl — APPROVED** [review]
Code looks good 👍

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Review by Strohgelaender — DISMISSED** [review]

**Review by krusche — APPROVED** [review]
Code looks good 👍

**Comment by krusche** [comment]
Thanks for @Strohgelaender for the new tests

**Pull request merged**
