### PR TITLE
`Programming exercises`: Fix failing build due to missing build script in local continuous integration

### PR DESCRIPTION
**Pull request by laurenzfb**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Sometimes, when creating a programming exercise, the solution build fails due to a missing build script. It uses the same build script file as the template build which sometimes gets deleted before it is used by the solution build.

### Description

The filename of the build script now contains the participation id rather than exercise id. This should avoid concurrency issues.

### Steps for Testing

Prerequisites:
- **Only test this on a Local CI server (new TS3 & TS6, legacy TS11)**
- 1 Instructor

1. Open 2-3 existing programming exercises in different tabs (I recommend Python exercises, they build fast)
2. Rerun template and solution builds in all exercises (in quick succession)
image

3. Verify build results (same results as in screenshot)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code looks reasonable.

**Review by farisd16 — COMMENTED** [review]
Tested on legacy ts11, works as expected

image

**Review by sarpsahinalp — APPROVED** [review]
Tested on ts6. Seems to be working. 
image

**Review by vinceclifford — APPROVED** [review]
Tested on t11. Works as expected

**Review by JanaNF — CHANGES_REQUESTED** [review]
Manual tested on legacy ts11 with instructor user13.
I saw the "Resubmit" button only if I reloaded the whole page. This happened with every newly created exercise (Java and Python), and even when I imported existing exercises, where I always checked the box "Recreate Build Plans".

**Review by basak-akan — APPROVED** [review]
Code LGTM

**Comment by laurenzfb** [comment]
@JanaNF This does not seem to be related to this PR or Local CI in general. I could reproduce this on other test servers. I guess the issue lies on the client size

**Pull request merged**
