### PR TITLE
`Lectures`: Move buttons of lecture units into header

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The buttons of lecture units that allow students to download an attachment or open an URL are currently located in the lecture unit cards that need to be expanded first. Moreover, they still have that "rounded pill" look that doesn't fit out usual styling. Additionally, the checkbox to mark the unit as completed moves in to the next line on smaller viewports which looks weird.

### Description

We decided to move these buttons into the header to make them easily accessible, and convert their design to match all other buttons. Also fixed the responsiveness issue

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with a lecture with one or multiple units of each type

1. Go the lecture page of the course in the student view
2. Open the lecture
3. Verify that all units are visible and that the buttons in the header work correctly
4. Verify that you can still expand the units
5. Verify that the page is responsive enough
6. Go to the course management view
7. Navigate to the page where you can edit the lecture units
8. Verify the same as in steps 3-5
9. Verify that you can still reorder them by dragging and dropping

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

Unchanged

### Screenshots

Before:

https://user-images.githubusercontent.com/23171488/185752990-f4e56f7d-9e94-4094-9039-f3d1bc9eaff8.mov

After:

https://user-images.githubusercontent.com/23171488/185752866-3bfd1e72-b70f-4791-9dfe-355bf505ca62.mov

### CODE REVIEW

**Review by ge65cer — CHANGES_REQUESTED** [review]
Nice work, the layout looks better on mobile devices now. I found two issues:
1. The checkbox is not aligned for video units. 
Screenshot 2022-08-22 at 12 07 15

2. When clicking on the “download” button for attachment units, the collapse is also triggered.

3. Do you have plans to align the exercise cards with the rest of the lecture units? 🙂

**Comment by bassner** [comment]
@ge65cer 1. Fixed in 2fd971eeb8b910bf98c3e3b138d6949c4b5cec6b, 2. fixed in 6b8256289ea467fc53bd15e408ff530735b4ce15
3. No, I don't have plans to change them. These rows are re-used from the normal course overview. I don't think it looks bad at the moment

**Review by ge65cer — APPROVED** [review]
Change requests were addressed. Looks good to me. 🙂

**Review by manuelmanso — APPROVED** [review]
LGTM, styling is standardized and layout is responsive

**Pull request merged**
