### PR TITLE
`General`: Show missing user management fields

### LINKED ISSUE #5076: User Edit view has missing fields
### Describe the bug

In the user Edit View some fields are not filled:
* ID
* Roles
* Language
* Activated

image

### To Reproduce

1. Go to 'User Management'
2. Go to Edit view for an arbitrary user

### Expected behavior

See all fields

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Dominik-Weinzierl**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Closes: #5083 and Closes #5076: Missing values in user edit menu.

### Description

`FormControls` needs to be "registered" in the `FormGroup` ([Link](https://next.angular.io/api/forms/FormControlName#register-formcontrol-within-a-group)).

### Steps for Testing

Prerequisites:
- 1 Admin

1. Log in to Artemis
2. Navigate to User Management
3. Edit a user and verify that all fields are visible
4. Change any values
5. Verify that these changes are also visible

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image

### CODE REVIEW

**Review by ge65cer — APPROVED** [review]
Followed testing steps, reported issues are fixed.

**Review by babyygemperor — APPROVED** [review]
Tested on ts2, wroks as described

**Review by rhubinger — APPROVED** [review]
Tested on TS2. Works as described.

**Review by jbllhff — APPROVED** [review]
Tested on ts2, changes are visible. When I changed the login, the following message was prompted: 
Changing the user's login is not supported for your current setup (Jenkins). You may have to manually update the user's login in Jenkins.
You changed the user test to test123.

**Pull request merged**
