### PR TITLE
`Programming exercises`: Fix missing plagiarism detection config in import

### PR DESCRIPTION
**Pull request by jakubriegel**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context
After introducing continuous plagiarism control (CPC) its config was not added to the exported programming exercise file, which caused issue when trying to import this exercises.

### Description
This PR adds missing `PlagiarismDetectionConfig` to the export json and makes sure the imported config does not override existing one.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Programming Exercise

1. Export programming exercise to file.
2. Import that programming exercise.
3. Verify that new exercise was created correctly.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by reschandreas** [comment]
@jakubriegel, could you also please fix the two server-style issues in ProgrammingPlagiarismDetectionService that [fail on develop](https://github.com/ls1intum/Artemis/actions/runs/6928729608/job/18845065501) since you're already fixing something in that area with this PR?

**Review by valentin-boehm — APPROVED** [review]
Tested locally, works as expected. When I export a programming exercise, the cpc config is included in the Json.

**Comment by jakubriegel** [comment]
> @jakubriegel, could you also please fix the two server-style issues in ProgrammingPlagiarismDetectionService that [fail on develop](https://github.com/ls1intum/Artemis/actions/runs/6928729608/job/18845065501) since you're already fixing something in that area with this PR?

@reschandreas There is a dedicated PR for that #7634 😁

**Review by sarpsahinalp — APPROVED** [review]
Tested manually on ts2. Works as expected

**Review by JanaNF — APPROVED** [review]
Manual tested on legacy_ts11. Worked as expected

**Review by tobias-lippert — APPROVED** [review]
Code LGTM although I would prefer some tests for the change.

**Review by MarkusPaulsen — APPROVED** [review]
Reviewed Code. Tested on TS1.

**Pull request merged**
