### PR TITLE
`Plagiarism`: Create a connection between Plagiarism-Detection and Plagiarism-Cases

### PR DESCRIPTION
**Pull request by dearjasmina**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
This PR solves the issue: https://github.com/ls1intum/Artemis/issues/6596
Snippet from the issue:
image

### Description
Now, next to the Confirm/Deny buttons in the header, we have an additional button "Plagiarism-Cases" that leads directly to the Plagiarism-Cases page for the specific exercise. (_See the short video below_)
(will figure out how to post a video here ;-;)

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Exercise (for example a text exercise)

1. Log in to Artemis as an Instructor and create an text exercise with the deadline soon in the future (not sure if last part is necessary)
2. Log in to Artemis as Student1 and submit one lengthy text
3. Log in to Artemis as Student2 and submit a really similar text
4. Check plagiarism
5. Notice the button "Check Plagiarism" next to the buttons "Confirm" and "Deny"
6. Click on the button
7. Confirm that the button takes you to the Plagiarism-Cases page for the exercise

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [plagiarism-header.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5062-2/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/plagiarism/plagiarism-header/plagiarism-header.component.ts.html) | 100% | :white_check_mark: |

### Screenshots

https://github.com/ls1intum/Artemis/assets/24391701/a83239a1-1dba-4736-9118-2faec4c20c4f

### CODE REVIEW

**Review by SabrinaGlatz — APPROVED** [review]
tested on ts4, works as expected

**Review by jakubriegel — APPROVED** [review]
Code LGTM. Works locally 👍🏻

**Review by DominikRemo — DISMISSED** [review]
Thank you for addressing my feedback :)

**Review by jakubriegel — APPROVED** [review]
Reapprove after code improvements

**Pull request closed without merging**
