### PR TITLE
`Lectures`: Fix inconsistent delete dialog for online unit

### LINKED ISSUE #6014: Inconsistent delete dialog for lecture units
### Describe the bug

While working on #6008,  I recognized that the delete dialog for online units is different from all other lecture unit types. In my opinion, this should be consistent.

See screenshots below.

### To Reproduce

1. Create a lecture with an online unit and e.g. a text unit
2. Try to delete both
3. See the different dialogs.

### Expected behavior

The delete dialog for online units matches the other ones.

### Screenshots

Text unit
image

Online unit
image

### Which version of Artemis are you seeing the problem on?

5.12.8

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tobias-lippert**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Closes #6014 

### Description

Previously, the dialog to delete an online unit was different from all the other ones and didn't require the user to enter the name of the unit again before being able to delete it. This PR fixes this.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to Lectures
4. Create all kinds of lecture units and delete them again. The dialogs should be consistent now.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Before:
image

After:
image

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
tested locally, works as expected. Code looks good as well.

**Review by TheZoker — APPROVED** [review]

**Review by laadvo — APPROVED** [review]
Tested localy with every different kind of lecture unit. The delete dialoge is now consistent for all.

**Review by timo07k — APPROVED** [review]
Delete dialog works as expected. Tested on TS1.

**Review by LiaLism — APPROVED** [review]
The delete dialogue worked as expected. Tested on ts1.

**Pull request merged**
