### PR TITLE
`Communication`: Allow tutors to monitor channels as moderator

### PR DESCRIPTION
**Pull request by cremertim**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

#### Client
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Currently, tutors are not able to monitor chats without the cumbersome work of granting each tutor for each channel moderation rights. This affects teaching, since instructors cannot monitor every channel on their own with potentially over 2000 students asking questions

### Description

I allowed tutors to pin, delete post and answer posts, if they are not an announcement. 

### Steps for Testing

Prerequisites:
- 1 Tutor
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Overview
3. Try to delete an post and an answer to this post from a different user as tutor and instructor (should be possible)
4. Try to delete an announcement as tutor (should not be possible) and as instructor (should be possible)

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image

## Release Notes

- **New Features**
	- Enhanced user role management for moderators in course-wide channels based on channel type (announcement vs. regular).
	- Updated permissions for deleting posts, allowing tutors to delete answers in course-wide channels.

- **Bug Fixes**
	- Corrected visibility of edit and delete options for tutors and instructors based on user roles and post types.

- **Tests**
	- Updated test cases to reflect new logic for user permissions regarding post editing and deletion.
	- Added assertions to ensure correct behavior of UI elements based on user roles.

### CODE REVIEW

**Review by ahbitaqu — CHANGES_REQUESTED** [review]
[Tested on TS4]
Doesn't work for me unfortunately. Even as an Instructor I am unable to edit messages now (see screenshot)
image

**Review by HawKhiem — CHANGES_REQUESTED** [review]
Tested on TS2. I cannot edit messages both as instructor and tutor

Screenshot 2024-12-02 223846
Screenshot 2024-12-02 223932

**Comment by cremertim** [comment]
> Tested on TS2. I cannot edit messages both as instructor and tutor
> 
> Screenshot 2024-12-02 223846 Screenshot 2024-12-02 223932

This is the intended behaviour. As introduced in https://github.com/ls1intum/Artemis/pull/9830, you can now only edit your own messages. Sorry for the missleading description, i updated it. You can only delete them now

**Review by eylulnc — APPROVED** [review]
Tested in TS2

**Review by anian03 — APPROVED** [review]
Tested during Testing session on TS2, works as expected

**Review by PaRangger — APPROVED** [review]
Code LGTM, Tested on TS2.

**Review by HawKhiem — APPROVED** [review]
Tested on TS2. I can indeed delete messages of other users as instuctor but not as tutor

Screenshot 2024-12-02 223846
Screenshot 2024-12-02 223932

**Review by julian-wls — APPROVED** [review]
Tested on TS2, works as expected!

**Review by SimonEntholzer — APPROVED** [review]
Code

**Review by ahbitaqu — APPROVED** [review]
[Tested on TS2]
Behaves exactly as desribed in the new description :)

**Pull request merged**
