### PR TITLE
[Bugfix] fixing the "Server Administration>API" subpage

### PR DESCRIPTION
**Pull request by PatZintel**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Description

Instead of having the OpenAPi embedded, i now open a new Tab with the OpenAPI started

### Steps for Testing

1. Login to Artemis with an admin/Instructor
2. Navigate to Server Administration/API and verify it opens a new Tab with the SwaggerUI loading...
3. The Performance of the OpenAPI still sucks, it is simply due to the massive amount of endpoints we provide; Sometimes it also times out while loading

### CODE REVIEW

**Review by imstreetspirit — APPROVED** [review]
tested on ts2. works as described. i waited so long, but in the end I was able to see the doc 😄

**Review by ndricimrr — APPROVED** [review]
Tested on TS3. Server Administration/API forwards to the new tab as described in the issue. Swagger UI eventually loads after a minute or two.

**Review by willergeorg — APPROVED** [review]
Tested on TS3. Worked for me.

**Review by NicolasUllmann — APPROVED** [review]
Tested on TS3. Everything worked as expected.

**Pull request merged**
