### PR TITLE
Show correct count for complaints/more feedback requests about your assessments

### LINKED ISSUE #1084: Complaints about assessment shows wrong number in link
### Describe the bug
Related to https://github.com/ls1intum/Artemis/issues/1037  and https://github.com/ls1intum/Artemis/pull/1030
When accessing programming exercises in the tutor dashboard, the "complaints about your assessment" section shows 0 complaints even though there is one. 
 
#### To Reproduce
1. Go to Course Administration
2. Click on Tutor Course Dashboard
3. See error

#### Expected behavior

Number in link should match the number of complaints about your assessment 
#### Screenshots
Bildschirmfoto 2019-11-19 um 11 31 36
Bildschirmfoto 2019-11-19 um 11 33 11

### Environment

<details><pre>
 - OS: macOS mojave
 - Browser: Chrome
</pre></details>

### PR DESCRIPTION
**Pull request by maxr96**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] ~Server: I added multiple integration tests (Spring) related to the features~
- [x] ~Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)~
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] ~Client: I added multiple integration tests (Jest) related to the features~
- [x] ~Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)~
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] ~Client: I translated all the newly inserted strings into German and English~

### Motivation and Context

We want to show all complaints/more feedback requests for current tutor (not only accepted).
Fixes #1084 

### Description

Previously number under the complaints about your assessments was showing number of accepted complaints for current tutor. Now it shows all the complaints (accepted/rejected/not resolved) for current tutor.
The same changes are applied to more feedback requests.
I also used primitive types whenever possible for TutorLeaderboard. This also allowed to simplify some if statements.
**UPDATE**: Changes to the database are not destructive anymore. Instead of killing the old views, I only create the new ones. The old ones can be killed later then

**UPDATE 2**: I found a way to test views and bring 100% Test coverage for `TutorLeaderboardService`.
Screenshot_2020-03-16 de tum in www1 artemis service
### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Select Tutor Dashboard
4. Check that number of complaints/feedback requests about your assessments are shown correctly ( it should correspond to the number of complaints/requests shown on list of complaints/requests page when you click on the number)
5. Go to the exercise and check if Tutor Exercise Dashboard also has the correct number of complaints/ more feedback requests about your assessments.

### Screenshots

Correct number on Tutor Course Dashboard
Screenshot_2019-12-14 Tutor Course Dashboard
List of complaints for this tutor
Screenshot_2019-12-14 List of complaints

### CODE REVIEW

**Comment by krusche** [comment]
What is the status here? This PR is open for 1.5 months and still a draft?!? I guess we should close it and reopen it, when the changes are finished and can be reviewed

**Comment by maxr96** [comment]
> @maxr96 please note: due to the recent critical bugs and problems in your changes, we need full test coverage of all changed files in the server and in the client, otherwise we need to decline this PR. Please have a look into the coverage reports and make sure all changed files are fully covered in the tests. If this is not the case, please add new tests to cover everything!
> 
> Please document this by uploading a screenshot of the coverage report to the PR.

I added the screenshot of current Test Coverage for `TutorLeaderboardService`. However, since the views doesn't work in the integration tests I didn't include any additional tests.

**Comment by krusche** [comment]
> > @maxr96 please note: due to the recent critical bugs and problems in your changes, we need full test coverage of all changed files in the server and in the client, otherwise we need to decline this PR. Please have a look into the coverage reports and make sure all changed files are fully covered in the tests. If this is not the case, please add new tests to cover everything!
> > Please document this by uploading a screenshot of the coverage report to the PR.
> 
> I added the screenshot of current Test Coverage for `TutorLeaderboardService`. However, since the views doesn't work in the integration tests I didn't include any additional tests.

The current coverage does not matter. I tell you since several months that you should please write client and server tests for your PRs and you simply ignore this :-( 

If you cannot fulfill this, we cannot merge this PR! This is a hard requirement due to the many problems and bugs that you introduced! 

I don’t see a reason why views should not work in tests.

**Comment by krusche** [comment]
@maxr96 Please resolve the merge conflict and make sure to add the tests as requested.

**Comment by maxr96** [comment]
> @maxr96 Please resolve the merge conflict and make sure to add the tests as requested.

I resolved the conflicts and managed to bring the test coverage for `TutorLeaderboardService` to 100%.

**Comment by krusche** [comment]
@maxr96 I have 3 problems with this PR:

1) It seems that you change the logic how to calculate the points for the leaderboard, e.g. only accepted complaints should count negative for the tutor
2) The views are not really tested, if you insert data manually and then check if the data is correctly retrieved using REST. The main idea is that the view updates automatically after real objects (i.e. results, complaints and feedback requests) are inserted into the database.
3) It is not good if old views still stay around. Please make sure to delete them!

**Comment by maxr96** [comment]
> @maxr96 I have 3 problems with this PR:
> 
>     1. It seems that you change the logic how to calculate the points for the leaderboard, e.g. only accepted complaints should count negative for the tutor
> 
>     2. The views are not really tested, if you insert data manually and then check if the data is correctly retrieved using REST. The main idea is that the view updates automatically after real objects (i.e. results, complaints and feedback requests) are inserted into the database.
> 
>     3. It is not good if old views still stay around. Please make sure to delete them!

@krusche Thank you for reviewing my PR.
1. Thank you for pointing the issues. I adjusted the view so that the max score is now only counted for accepted complaints and not answered more feedback requests instead of all requests and complaints. 
2. Testing the views directly didn't work for me. After several days of investigation, I decided to at least test the logic of the service. However, the issue can be in the Liquibase changelog. I assume that since the tests don't use Liquibase, the views are not created. 
3. Added the `dropView` part to the changelog. I didn't do it before as this change would break other deployments on the Test Server.

**Comment by maxr96** [comment]
Hi @krusche. I just wanted to ask if you received my email and if the document is added to my thesis. Thank you.

**Pull request merged**
