### PR TITLE
`Programming exercises`: Always show result details

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

#5824 made clear that the current feedback for results is not sufficient.
Students should always be able to take a look at the detailed feedback even if all tests pass.

### Description

Students can now always click on their result and the tasks in the problem statement and see their feedback.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise with some tests after the deadline

1. Log in to Artemis
2. Participate in the exercise with all failing/some failing/all passing tests before the deadline
3. Participate in the exercise with all failing/some failing/all passing tests after the deadline
4. Always make sure that all results show their details, and the UI make everything intuitively clear

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by manuelmanso — DISMISSED** [review]
Tested in testing session, works as expected. Code also looks good, nice job!

**Comment by krusche** [comment]
Please try to remove 

`hasFeedback`

in Result.java and result.model.ts

(in a follow-up, we should then remove the column in the database)

**Review by timo07k — APPROVED** [review]
Everything is well displayed. Tested on TS1.

**Review by stefanwaldhauser — APPROVED** [review]
I like that change to always see the feedback! Great job!

**Review by manuelmanso — APPROVED** [review]
Last changes removing `hasFeedback `look good

**Review by evgeny1984 — APPROVED** [review]
Tested on ts2, the changes look good. The presenting of results are far better now as previously.

**Pull request merged**
