### PR TITLE
`Communication`: Prevent senders from getting notifications of their own messages

### PR DESCRIPTION
**Pull request by TimOrtel**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Currently the sender of a message is sent a push notification about their own message.

### Description

With these changes the sender of a message will be filtered out. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Use the Android or iOS application
2. Enable push notifications and conversation notifications
3. Write a message in any conversation
4. Check if you have not received a push notification about your own message.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
code looks good

**Review by sven0311 — APPROVED** [review]
Code looks good

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Review by nityanandaz — APPROVED** [review]
I confirmed manually on the Android emulator that I did not receive a push notification for a reply on my own message

**Pull request merged**
