### PR TITLE
[Bugfix] Correctly unlock programming exercises for exam

### LINKED ISSUE #3663: Offline editor for exam programming exercises does not work
### Describe the bug

When trying to clone a programming exercise, a 403 occurs for students when cloning with sorcetree or directly in intellij.

### To Reproduce

1. Create an exam with an programming exercise
2. participate with a student account
3. Try to clone the repository for example with sourcetree

### Expected behavior

Students should be able to work on programming exercises offline

### Screenshots

image2021-6-30_14-29-31

image2021-6-30_14-29-47

Screenshot 2021-06-30 at 14 29 27

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by JohannesStoehr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).

### Motivation and Context

Closes #3663 

### Description

This PR changes the behaviour of the scheduling to also schedule exercises from exams that are created right before the release.

### Steps for Testing

1. Log in to Artemis
2. Create an exam with a Release date that is 15-20 minutes in the future
2.1. Create a programming exercise in that exam
2.2. Sign up some students for the exam
2.3. Create the student exams and prepare the exercises (This step has to be finished at least 6 minutes before the release date)
2.4. Check that the students have access to their repositories during the exam (see below on how to check that)

3. Create another exam and repeat the steps, but do steps 2.1 to 2.3 during the last 5 minutes before the release of the exam.
3.1 Check that the students have access to their repositories during the exam (see below on how to check that)

How to check the student access:
- Either clone the repository as a student during the exam
- Or take a look at bitbucket. Select the repository of one student and check in the settings under "Repository-Berechtigungen"

### CODE REVIEW

**Comment by dfuchss** [comment]
Related to #3690 ?

**Comment by dfuchss** [comment]
> 
> 
> > Related to #3690 ?
> 
> No, this is only for unlocking the exams correctly before the releasedate. But I'll have a look at your issue after this PR

Thanks a lot, I thought it might be related as the repositories are not unlocked for exam review :)

**Review by MDK5 — APPROVED** [review]
Tested during testing session on ts1, everything worked

**Review by FuchsDominik — APPROVED** [review]
Setting permissions for exam which was created right before the releaseDate works now :) 👍

**Review by imstreetspirit — APPROVED** [review]
tested during the testing session, seems working

**Review by krusche — APPROVED** [review]
Code looks good 👍 
Not sure why you have some unrelated and undescribed changes such as removing the combine template commit notification

**Pull request merged**
