### PR TITLE
Remove deprecated endpoints from modeling submission resource

### PR DESCRIPTION
**Pull request by iozbeyli**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all newly inserted strings into English and German.

### Motivation and Context
Sending optimal submissions and calculating them was a deprecated feature of Compass and this PR removes the endpoints connected to these features.

### Steps for Testing (Course Exercise)
1. Log in to Artemis
2. Navigate to Course Administration
3. Create a modeling exercise
4. Submit with multiple students
5. Assess these submissions with a tutor and instructor

Instructor

https://user-images.githubusercontent.com/16825065/125204750-1bcbd800-e27f-11eb-8ae4-62b10372be39.mp4

Tutor 

https://user-images.githubusercontent.com/16825065/125204754-1ff7f580-e27f-11eb-9bcf-10091b830c34.mp4

### Steps for Testing (Exam)
1. Log in to Artemis
2. Navigate to Course Administration
3. Create an exam
4. Create an exercise group
5. Add a modeling exercise
6. Attend exam with multiple students
7. Assess their submissions with a tutor and instructor

Instructor

https://user-images.githubusercontent.com/16825065/125204794-44ec6880-e27f-11eb-86ea-3732ccf7c3bf.mp4

Tutor

https://user-images.githubusercontent.com/16825065/125204798-4a49b300-e27f-11eb-92a1-91a29a13b4bb.mp4

### CODE REVIEW

**Review by krusche — CHANGES_REQUESTED** [review]
Code changes look good. Two comments:

* Please make sure that the modeling submissions page still works for exams and courses. (provide some screenshots in the PR)
* Fix all the Github warnings in the tests

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Looks good to me.

**Review by NicolasUllmann — APPROVED** [review]
Tested on TS2. Everything worked as expected.

**Review by krusche — APPROVED** [review]
code changes look good 👍

**Pull request merged**
