### PR TITLE
Integration Test for the Java Programming Exercise Template

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] The new test works both on Windows and Linux
- [x] All tests still work on Linux.

### Motivation and Context
Make it possible to test the Java programming exercise template automatically. (And possibly other programming language templates in future)

### Description
Added the test class `ProgrammingExerciseTemplateIntegrationTest` and added two test-scoped dependencies, one for invoking Maven and one for reading maven surefire reports.

### Steps for Testing
1. **Make sure Maven is installed** and on the `PATH`: https://www.baeldung.com/install-maven-on-windows-linux-mac
2. Run the test `gradlew test --tests de.tum.in.www1.artemis.programmingexercise.ProgrammingExerciseTemplateIntegrationTest` (or all tests)

You can also use the [Artemis build docker image](https://hub.docker.com/r/ls1tum/openjdk-node-yarn) to run the tests.

### CODE REVIEW

**Comment by MaisiKoleni** [comment]
It looks like the build on bamboo has no Maven installed. Can I fix that somehow?

**Comment by MaisiKoleni** [comment]
> The code looks fine to me, very good work that will also help us very much! Good work!
> 
> I've rebuilt the build on Bamboo and now only 1 (instead of 2) tests fail, however maven still does not seem to be installed (despite the other PR got merged).
> Maybe you can check again what's wrong here?
> 
> I've executed the tests locally (on Ubuntu 20.04) and after selecting the correct Java version, the test cases passed locally.
> 
> So as soon as the tests on Bamboo are fixed, this can be merged from my point of view.

I am already looking into that together with Stephan. It also works locally for me using:
1. Windows 10
2. Ubuntu 18 in Windows Subsystem for Linux
3. The exact same docker image that Bamboo uses (Ubuntu 19).

This might have to do with the way Bamboo sets the image and tasks up because `mvn` is not in the path anymore. I might try explicitly setting `M2_HOME` like in https://github.com/MaisiKoleni/docker-jdk-node-yarn/tree/patch-2.

**Comment by MaisiKoleni** [comment]
From the 3b69942 experiment I can see in the [build logs](https://bamboo.ase.in.tum.de/download/ARTEMIS-TESTS556-JAVATEST/build_logs/ARTEMIS-TESTS556-JAVATEST-5.log) that `/usr/share/maven` does not exist on Bamboo, using the latest `docker-jdk-node-yarn` image locally prints `MVN-DIR: true` and works, and `M2_HOME` is also set. Because the image on Bamboo does not even have the maven folder, I am very confident that Bamboo does not use the latest version of the docker image (i.e. does not pull the `latest` image or only uses a cached one).

Could someone who has the permission to configure the Artemis Java Test build have a look at that?

**Comment by sleiss** [comment]
> From the [3b69942](https://github.com/ls1intum/Artemis/commit/3b69942aa6fcf338aa597df0dad0d932a9b5eab9) experiment I can see in the [build logs](https://bamboo.ase.in.tum.de/download/ARTEMIS-TESTS556-JAVATEST/build_logs/ARTEMIS-TESTS556-JAVATEST-5.log) that `/usr/share/maven` does not exist on Bamboo, using the latest `docker-jdk-node-yarn` image locally prints `MVN-DIR: true` and works, and `M2_HOME` is also set. Because the image on Bamboo does not even have the maven folder, I am very confident that Bamboo does not use the latest version of the docker image (i.e. does not pull the `latest` image or only uses a cached one).
> 
> Could someone who has the permission to configure the Artemis Java Test build have a look at that?

I believe @krusche or @jpbernius can check that.

**Comment by krusche** [comment]
This is the configuration of the Java Test build job

image

**Comment by krusche** [comment]
I added a Maven Task to test this and it failed with the same error message. So something is wrong with the Docker image

```
simple	01-Jun-2020 09:38:52	Finished task 'Checkout Default Repository' with result: Success
simple	01-Jun-2020 09:38:52	Starting task 'Maven Test' of type 'com.atlassian.bamboo.plugins.maven:task.builder.mvn3'
command	01-Jun-2020 09:38:52	Beginning to execute external process for build 'Artemis - Artemis Tests - enhancement-programming-exercise-template-integration-tests - Java Test #7 (ARTEMIS-TESTS556-JAVATEST-7)'\n ... running command line: \n/tmp/runInDocker6122418298343748659.sh mvn --batch-mode clean test\n ... in: /tmp\n
error	01-Jun-2020 09:38:54	/tmp/runInDocker1546771446242898523.sh: 4: mvn: not found
simple	01-Jun-2020 09:38:54	Failing task since return code of [/tmp/runInDocker6122418298343748659.sh mvn --batch-mode clean test] was 127 while expected 0
simple	01-Jun-2020 09:38:54	Parsing test results under /opt/bambooagent/bamboo-agent-home/xml-data/build-dir/ARTEMIS-TESTS556-JAVATEST...
simple	01-Jun-2020 09:38:54	Finished task 'Maven Test' with result: Failed
```


Maybe the entry point is wrong and Bamboo therefore cannot use Maven correctly?

**Comment by krusche** [comment]
Can you compare the Docker configuration with the one used in `ls1tum/artemis-maven-template:latest`
We know that this one works correctly on Bamboo

**Comment by MaisiKoleni** [comment]
> Can you compare the Docker configuration with the one used in `ls1tum/artemis-maven-template:latest`
> We know that this one works correctly on Bamboo

That one is based on the Java 14 Maven docker image. We could try that approach as well, but that might use a different Ubuntu version (I will check that).

It's just strange that even the maven folder is not present, alongside with the new environment variables, and locally everything is there. But there does not seem to be a good way too get the docker image digest from inside the container to see which version is used.

**Comment by sleiss** [comment]
Could we already verify if Bamboo updates the image? We could try to push an image with a specific tag (not latest) and then define that one in the build plan, then the new image has to be used.

**Comment by MaisiKoleni** [comment]
I think this is the problem to some degree: https://vsupalov.com/docker-latest-tag/ in combination with
> [...] Make sure that your tools handle different images with the same tag well.

Bamboo might not do that automatically. But there seem to be different jobs for managing docker, so one could make that into a pre-build stage: https://confluence.atlassian.com/bamboo/pulling-a-docker-image-from-a-registry-962976993.html

Another option would be to use the digest of the image directly, at least this way one can be certain, which image is used: https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier

I think the latter option is better for our purpose and might be faster.
We could also use new tags for each new image version, e.g. the git commit hash.

**Comment by MaisiKoleni** [comment]
**Some useful diagnosis options I found:**
This job can be added to check the docker images used:
image
*See https://bamboo.ase.in.tum.de/build/admin/edit/editBuildTasks.action?buildKey=ATESTCOURSECHRIS20200505J1-SOLUTION-SD (requires being test user 11 or similar)*

Result:
image
as text:
```log
ls1tum/artemis-maven-template@sha256:87616337dee07817414a441643a6161217d33987092069d66ce6a9d5db9e5a0a
ls1tum/openjdk-node-yarn@sha256:1ca1a84d9e2673c97c97c4a6287583658f46b532bfa9e903ffb152cccb1791c1
```
Both are not the up-to-date versions, at least on this build agent (here `lxcAgent-11`)

**Comment by MaisiKoleni** [comment]
Using the commit hash seems to work fine, in the Bamboo Job I use as image
`ls1tum/artemis-maven-template@sha256:92a374140a5e647bea689e6d74dd5e241827c0b58d211a40505abfb125bc1b45`
and the first execution on an agent looks like this:
image
the second run on the same VM works without pulling the image again, and in the logs you can see 
```log
/usr/bin/docker run [...] ls1tum/artemis-maven-template@sha256:92a374140a5e647bea689e6d74dd5e241827c0b58d211a40505abfb125bc1b45 [...]
```

*See [the two recent builds of VM 184 on Bamboo](https://bamboo.ase.in.tum.de/agent/viewAgent.action?agentId=276758608)*

**Comment by sleiss** [comment]
@MaisiKoleni Great that you figured that out! Although the approach with the digest does work as you explained, I would propose that we tag the images in a semantic way (like `1.0.0` etc). This way, it will be easier to manage the version without having to compare digests.

**Comment by MaisiKoleni** [comment]
> @MaisiKoleni Great that you figured that out! Although the approach with the digest does work as you explained, I would propose that we tag the images in a semantic way (like `1.0.0` etc). This way, it will be easier to manage the version without having to compare digests.

Yes, that would very likely even better, but requires that we build all images with automatic semantic versioning or an automatic build timestamp as tag.

**Comment by sleiss** [comment]
> > @MaisiKoleni Great that you figured that out! Although the approach with the digest does work as you explained, I would propose that we tag the images in a semantic way (like `1.0.0` etc). This way, it will be easier to manage the version without having to compare digests.
> 
> Yes, that would very likely even better, but requires that we build all images with automatic semantic versioning or an automatic build timestamp as tag.

Maybe we can create this based on the automatic versioning of the bamboo-notification-plugin which can be found here: https://github.com/ls1intum/bamboo-server-notification-plugin/blob/master/.travis.yml.

**Pull request merged**
