### PR TITLE
`Plagiarism checks`: Fix files not being shown in plagiarism viewer

### PR DESCRIPTION
**Pull request by magaupp**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

The plagiarism code viewer always displays `No file selected`. #8803 moved the `jhiTranslate` into a tag which sets its content with `innerHTML`. `jhiTranslate` takes precedence over `innerHTML` here.

### Description

The `jhiTranslate` attribute is moved into an inner `<span>` tag.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise supporting plagiarism checks

1. Submit a solution different from the base template as Student 1
2. Submit the same solution as Student 2
3. Run a plagiarism check as the Instructor
4. The file contents should be visible in the plagiarism viewer

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Current:
Screenshot 2024-09-21 at 12-55-41 Plagiarism Detection Java Plag Local Course
Fixed:
Screenshot 2024-09-21 at 12-53-39 Plagiarism Detection Java Plag Test Course Marcel Gaupp

## Summary by CodeRabbit

- **New Features**
	- Improved semantic structure of the text submission viewer by wrapping the translation directive in a span element for better clarity.
  
- **Bug Fixes**
	- Enhanced display handling of text submissions, ensuring proper rendering of content based on conditions.

### CODE REVIEW

**Review by BaumiCoder — APPROVED** [review]
Code

**Review by JohannesWt — APPROVED** [review]
Code

**Review by edkaya — APPROVED** [review]
Tested on TS2, works as expected

**Review by BBesrour — APPROVED** [review]
Tested on TS2, lgtm

**Pull request merged**
