### PR TITLE
`Development`: Refactor atlas tests

### PR DESCRIPTION
**Pull request by MaximilianAnzinger**
#### General

- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a [very good performance](https://docs.artemis.cit.tum.de/dev/guidelines/performance/) and prevented too many (unnecessary) and too complex database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Description

Introduces `AbstractAtlasIntegrationTest` and moves all `@Autowire` into the abstract test class.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### Test Coverage

unchanged

## Summary by CodeRabbit

- **New Features**
	- Introduced a new abstract class for integration tests, providing a shared setup for various test classes.

- **Bug Fixes**
	- Removed unnecessary dependencies from the LearningPathIntegrationTest class, simplifying its setup and execution.

- **Refactor**
	- Refactored LearningPathIntegrationTest to extend the new abstract class, enhancing consistency and reducing complexity.

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Approve refactored code

**Review by cremertim — DISMISSED** [review]
Refactored code lgtm

**Review by JohannesWt — APPROVED** [review]
Code 👍

**Review by cremertim — APPROVED** [review]

**Review by JohannesStoehr — APPROVED** [review]
Approve refactoring

**Pull request merged**
