### PR TITLE
`Adaptive learning`: Enable standardized competencies by default

### PR DESCRIPTION
**Pull request by rstief**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
Standardized Competencies are now ready to be used. We want to enable the feature toggle by default.

### Description
Enables standardized competencies when starting Artemis.

### Steps for Testing
1. Deploy 
2. Go to Course Management -> Competencies
3. See that under Import Competencies ->the Import Standardized Competencies button is visible (I.e. the feature is enabled)

#### Performance Review
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged.

### CODE REVIEW

**Review by Jan-Thurner — APPROVED** [review]
Tested on TS2. Works as described. Code also LGTM.

**Review by muradium — APPROVED** [review]
Code LGTM

**Review by edkaya — APPROVED** [review]
Tested on ts2, works as expected

**Review by Strohgelaender — APPROVED** [review]

**Review by sarpsahinalp — APPROVED** [review]
code lgtm

**Review by MaximilianAnzinger — APPROVED** [review]
Maintainer approved

**Pull request merged**
