### PR TITLE
Improve performance in exam mode with programming exercises

### PR DESCRIPTION
**Pull request by krusche**
When students enter the exam mode, 1 unnecessary REST call to `latest-pending-submisison` was performed for each exercise simultaneously. In case 2.000 students participate in an exam with 2 programming exercises, this means 4.000 requests at the exact same time which are unnecessary.

In addition, when students hand in, 1 unnecessary REST call to `exercise-hints/{exerciseHintId}` was made per exercise, while exercise hints are not even supported. In the scenario above this would lead to 4.000 within ~30s which are unnecessary.

This PR also solve a null pointer exception in LTI Resource (which I do not really understand why it happens) in the context of manual results in team programming exercises. It also includes some minor code improvements.

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Steps for Testing
1. Create an exam with programming exercises (instructor account)
2. Participate in those programming exercises (student account) using the online code editor and git
3. Make sure the build animation is shown properly and the result comes in.

There could be a theoretic edge case now which is quite unlikely to happen and hard to test: If you reload the page between submission and result arrival (you can stop the build on the CI system), you might not see the red button for the failed build. However, I was not able to reproduce this issue. 

In case, someone finds it, we can solve this by passing the submission and its missing result to the right component in the client on exam start, but we should not have so many unnecessary REST calls just for this rare edge case.

### CODE REVIEW

**Comment by krusche** [comment]
I tested everything in an exam on the staging environment and could not find any issues

**Review by MDK5 — APPROVED** [review]
Tested on ts3, results showed correctly.

Code changes also look good to me

**Review by imstreetspirit — APPROVED** [review]
tested on ts3 as well, received the results properly.

**Review by coolchock — APPROVED** [review]
tested on ts1, found no issues

**Comment by jhainzlschmid** [comment]
Also tested on ts3. Build animation is shown and results come in

**Pull request merged**
