### PR TITLE
`Development`: Increase client test coverage for password component

### PR DESCRIPTION
**Pull request by martindevtum**
#### General
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).

### Motivation and Context
We want to increase client test coverage.

### Description
This PR increases client test coverage for app/account/password

### Steps for Testing
Execute the client tests for app/account/password

#### Code Review
- [x] Review 1
- [x] Review 2

### Test Coverage
password-strength-bar.component.ts:  97.77%
password.component.ts:  94.28%

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Code lgtm

**Review by coaxial1 — APPROVED** [review]
Code looks good :)

**Review by Hialus — APPROVED** [review]
Code changes looks good 👍🏻

**Review by MertAksehirlioglu — APPROVED** [review]
Code looks good to me

**Pull request merged**
