### PR TITLE
[Feature] Grading System - Student Exam Detail

### PR DESCRIPTION
**Pull request by ivohashamov**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all newly inserted strings into English and German.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

This PR integrates the grading system on the student exam detail page

### Description

Instructors can now see the student's grade or bonus and whether they have passed in the participant status

### Steps for Testing

1. Log in to Artemis as an instructor and navigate to an exam with existing student submissions.
2. Create a grading key for the exam 
3. Navigate to a student exam detail page for that exam (Student Exams -> View)
4. Check if the grade and whether the student has passed are displayed in the participation status
5. Switch the grading key to 'Bonus' and navigate back to the student exam detail page again
6. Check if the bonus points are displayed
7. Check that the grading information isn't present and that no errors are thrown on the student exam detail page if no grading key exists for the exam

### Test Coverage

student-exam-detail.component.ts: 82.65%

### Screenshots

Screenshot 2021-07-25 133954
Screenshot 2021-07-25 134034

### CODE REVIEW

**Review by FrankeLukas — CHANGES_REQUESTED** [review]
There are a bunch of unused imports in exam-points-summary.component.ts which we need to remove.

**Review by canyelten — APPROVED** [review]
Tested on TS1, grade and student information are displayed as described.

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Looks good.

**Review by Malyuk-A — APPROVED** [review]
Tested on TS3. Code looks reasonable.

**Pull request merged**
