### PR TITLE
[Enhancement] Remove/Update legacy template test files and fix local repo deletion

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

Improves the upgrade template functionality on import and fixes local repository deletions.

### Description

- [x] Overwrite the following test files with the latest version of the template when upgrading the template on import: `AttributeTest.java, ClassTest.java, ConstructorTest.java and MethodTest.java`
- [x] Delete `StructuralTest.java` from the test repository if present when upgrading the template on import.
- [x] Fix deletion of exercise, solution and test repositories on exercise deletion
- [x] Fix deletion of repositories in `repos-downloads` when importing an exercise

### Steps for Testing

**Import: without SCA -> with SCA**
1. Create a programming exercise without static code analysis (EXwithoutSCA)
2. Add a folder testUtils and some dummy files to the test repository under `test/{packageName}/` like in the screenshot below
image
3. Add a dummy file StructuralTest.java under `test/{packageName}/`
4. Delete the contents of the files `AttributeTest.java, ClassTest.java, ConstructorTest.java, MethodTest.java` and submit
5. Open the import dialog by importing EXwithoutSCAand activate static code analysis (SCA). 
6. Create the exercise (importedExWithSCA)
--> In the test repository, the `testUtils` folder and its content should not exist
--> In the test repository, `StructuralTest.java` should not exist
--> In the test repository, check that `AttributeTest.java, ClassTest.java, ConstructorTest.java, MethodTest.java` got overwritten with the latest template files
--> In the test repository, a `staticCodeAnalysisConfig` folder should be created with three config files
--> In the test repository `pom.xml`, check that plugins for Spotbugs, PMD and Checkstyle are created
--> Go to the grading page and check that the categories are created
--> Participate in the exercise, and an unused variable and check that the issue is found

**Import: withSCA -> without SCA**
1. Delete the files AttributeTest.java and ClassTest.java in the test repository of importedExWithSCA
1. Open the import dialog by importing importedExWithSCA and deactivate SCA. 
2. Create the exercise (importedExWithoutSCA)
--> In the test repository, the files `AttributeTest.java and ClassTest.java` should not exist
--> In the test repository, a `staticCodeAnalysisConfig` folder should not exist
--> In the test repository `pom.xml`, check that plugins for Spotbugs, PMD and Checkstyle do not exist
--> Go to the grading page and check that SCA grading options do not exist
--> Participate in the exercise, and check that no SCA is executed by adding an unused variable (no feedback for it should appear).

**Delete the exercises**
1. Delete all three exercises with both deletion options activated 

### Test Coverage

Nothing changed

### CODE REVIEW

**Review by simonzilker — APPROVED** [review]
Works as described on ts1. Tested in testing session with @EneaGore @JohannesWeiss @airelawaleria @marvinchimeka

**Review by marvinchimeka — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]
Tested in testing session, works as expected.

**Review by airelawaleria — APPROVED** [review]

**Review by krusche — APPROVED** [review]
The code changes look good to me. Thanks for fixing and improving the local repo deletion 👍 
(I have not tested it)

**Review by EneaGore — APPROVED** [review]
Tested in testing session, looks fine.

**Pull request merged**
