### PR TITLE
`Communication`: Improve design of hover area on messages

### LINKED ISSUE #9734: `Communication:` Expand clickable space for replying
### Is your feature request related to a problem?

As implemented in #9456, the reply option now appears as a small floating pop-up when you hover over a message. For small messages as e.g. one-liners this makes the area, where the pop-up appears quite small:
image

### Describe the solution you'd like

I'd love if the area can be expanded at least for the first of optinally consecutive messages, so the unused real estate can be minimized and the user doesn't have such a hard time aligning his mouse in the narrow space of a one-liner:
image
(Expand the area to entire message space)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by asliayk**
#### General

- [X] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [X] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [X] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

- The hover area for messages was not completely aligned with Slack's behavior. Instead of covering the entire message container, it only covered the content, reducing the interactive area for users. (Closes #9734)
- When messages were hovered over, the time of the message was not displayed, unlike in Slack.
- For messages sent on days other than the current day, the exact time was not displayed.
- In the `AnswerPost` component, there was an additional spacing issue between consecutive messages compared to the `Post` component. 
- The timeframe for grouping consecutive messages in the `AnswerPost` component was 1 minute, whereas in the `Post` component, it was 5 minutes. 

### Description

- The hover area now covers the entire message container instead of just the content. 
- The sent time of the message is now displayed when hovering over messages, aligning with Slack's functionality.
- For messages sent on days other than the current day, the sent time is now displayed on the message header.
- The additional spacing between consecutive messages in the `AnswerPost` component has been removed.
- The timeframe for grouping consecutive messages in the `AnswerPost` component has been updated from 1 minute to 5 minutes, making it consistent with the `Post` component.

### Steps for Testing

Prerequisites:
- 1 User
- 1 Course with Communication enabled

1. Log in to Artemis.
2. Navigate to the Communication section of a course.
3. Send some consecutive messages to a channel and notice that when the consecutive messages are hovered, the exact time is displayed on the left of the message content.
4. Send some consecutive replies to a message and notice the same hovering behavior.
5. Verify that the spacing between consecutive replies and posts is consistent.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [X] Code Review 1
- [X] Code Review 2
#### Manual Tests
- [X] Test 1
- [X] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| post-footer.component.ts | 98.57% | ✅ ❌ |

### Screenshots

**hovered message with expanded hover area and sent time on header**
image

**hovered consecutive message with sent time**
image

## Release Notes

- **New Features**
  - Enhanced visual feedback for posts with new hover effects and conditional display of posting creation date.
  - Improved grouping logic for consecutive posts, now considering a 5-minute threshold.

- **Bug Fixes**
  - Adjusted rendering logic to ensure accurate display of post timing and saved messages.

- **Style**
  - Updated styles for hover interactions and layout adjustments to improve user experience.

- **Tests**
  - Expanded test coverage for post timing and grouping functionalities, ensuring accurate behavior across components.

### CODE REVIEW

**Review by HawKhiem — APPROVED** [review]
Tested on TS2. Consecutive messages display time when hovered upon. Same goes with the answers on a post. The spacing of messages and answers are consistent.

Screenshot 2024-12-07 113848
Screenshot 2024-12-07 113935

**Comment by Longppham** [comment]
image

Tested on TS1. When i hover over the messages in consecutive messages, It shows the time like shown in the screenshot. Same applies to answers on a post. Format is also uniform

**Review by eylulnc — APPROVED** [review]
Tested in TS3, works as expected the time and texts are aligned, on hoover time is displayed

Screenshot 2024-12-07 at 21 04 58

**Review by ItsaaaMeMario — APPROVED** [review]
Tested on TS3, everything works as expected. When hovering over consecutive messages, their timestamps are displayed. The same applies to answers on a post. Additionally, the spacing between messages and answers remains consistent.

Bildschirmfoto 2024-12-07 um 21 06 46

**Review by ahbitaqu — APPROVED** [review]
[Tested on TS3]

Thanks for working on this, small change but a significant quality of life improvement!
Works amazingly :)

Minor suggestion though:
Is there any way to add a slight bit of padding at the top of the first message
image
Currently, how the box ligns up perfectly with the top of the profile picture feels a little off to me, especially since there is padding in every other direction

**Comment by asliayk** [comment]
> [Tested on TS3]
> 
> Thanks for working on this, small change but a significant quality of life improvement! Works amazingly :)
> 
> Minor suggestion though: Is there any way to add a slight bit of padding at the top of the first message image Currently, how the box ligns up perfectly with the top of the profile picture feels a little off to me, especially since there is padding in every other direction

Adding this padding could be better, I'll include it in a follow-up PR

**Review by krusche — APPROVED** [review]

**Pull request merged**
