### PR TITLE
`Programming exercises`: Execute builds on parallel based on system resources for local continuous integration

### PR DESCRIPTION
**Pull request by laurenzfb**
# Do not deploy on test server, contains config change
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

Currently, the parallel execution of build jobs in Local CI is determined by the config variable `artemis.continuous-integration.thread-pool-size` which is set to 1 at the moment. That means, only one build job will run concurrently on a single machine. We want to facilitate the concurrent execution of build jobs based on the system resources.

### Description

This PR sets the size of allocated thread pool for the thread pool executor that manages the build jobs on a node based on the number of available CPUs. We reserve 2 CPUs for the application itself and assign 2 CPUs for each build job thread. For example, on a system with 8 CPUs, we can run 3 build jobs concurrently. The thread pool size is always at least 1.
Furthermore, this PR limits the resources available to the build job containers based on the default docker flags set in `artemis.continuous-integration.build` which wasn't the case for Local CI until now.

### Steps for Testing

**Do not deploy on a testserver, as it contains a config change. Test locally with LocalVC Local CI run configuration**
Depending on the number of CPUs your machine has, multiple threads will be allocated for running the build jobs. On a machine with 8 CPUs, you should be able to run 3 build jobs concurrently.

1. Open 2-3 existing Java Gradle programming exercises in different tabs
2. Rerun template and solution builds in all exercises (in quick succession)
image
3. Depending on how many build jobs your machine can run concurrently, this number of results should come in approximately at the same time.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by valentin-boehm — APPROVED** [review]
Tested locally. With 12 CPUs I can run 5 build simultanously

**Comment by mateusmm01** [comment]
Tested locally with only 4 CPUs => only 1 Thread. It is running as well. Compared to develop and no performance differences were noticed, as expected.

**Review by pal03377 — APPROVED** [review]
Tested locally on my M1 Mac Pro laptop. When I ran a lot of builds, exactly 3 docker containers spun up and did not consume more than 200% CPU, as expected 👍

**Review by vinceclifford — APPROVED** [review]
Works as expected

**Review by egekurt123 — APPROVED** [review]
demonstrated in testing session, works as expected

**Review by basak-akan — APPROVED** [review]
Demonstrated during the testing session locally, worked as expected.

**Review by reschandreas — APPROVED** [review]
tested locally, works as expected

**Review by florian-glombik — APPROVED** [review]
Demonstrated in testing session on local setup, worked fine

**Pull request merged**
