### PR TITLE
`Development`: Update the documentation engine sphinx to 5.0.2

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

Artemis currently uses Sphinx version 4.2.0. A couple of days ago Sphinx 5.0.2 was released.
While reviewing #5334 I noticed this and decided to update to the newest Sphinx version

### Description

I updated the requirements.txt file to use Sphinx 5.0.2.
Additionally I updated `docutils` from 0.16 to 0.17. It is not possible to update to 0.18 or 0.19, as Sphinx / sphinx-autobuild requires it to be <0.18.
I looked through the documentation locally and could not spot anything that looked wrong.

### Steps for Testing

Goto https://artemis-platform--5353.org.readthedocs.build/en/5353/ and look for any differences from https://docs.artemis.ase.in.tum.de

Optionally try to compile the docs locally (you might have to update your Python version).

#### Documentation Review
- [ ] Review 1
- [ ] Review 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
Did not spot any issues while scrolling through the documentation.

**Review by max-bergmann — APPROVED** [review]
Scrolled through the documentation. I did not notice any issues.

**Review by Marvin-Vitcu — APPROVED** [review]
The documentation looks good to me.

**Review by babyygemperor — APPROVED** [review]
Documentation looks good to me 👍🏼

**Review by manuelmanso — APPROVED** [review]
Docs look good!

**Review by luisa-we — APPROVED** [review]
Looked through the documentation, looks good to me!

**Pull request merged**
