### PR TITLE
`Development`: Improve course client test coverage

### PR DESCRIPTION
**Pull request by pal03377**
#### General

- [X] This is a small issue that I tested locally and was confirmed by another developer on a test server.

#### Client
- [X] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

#6318 decreased the coverage for some files related to courses. We aim for a line coverage of >90% per file, so this should be improved.

### Description

This PR adds tests to improve the coverage on the files from #6318.

### Steps for Testing

Check that the tests pass and make sense.

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2

### Test Coverage

This is the complete table (client only) from #6318 with the updated coverage values. Note that the entries in #6318 apparently were still erroneous in part, so some values here are changed even though this PR does not update the related files.

File | Line % | Confirmation | Improved by this PR
--- | --- | --- | ---
| alert.service.ts | 91.5% | ✅ | ✅ |
| course-overview.component.ts | 90.83% | ✅ | ✅ |
| course-registration.component.ts | 93.33% | ✅ | ✅ |
| | | |
| _course-prerequisites-button.component.ts_ | 100% | ✅ | |
| _course-registration-button.component.ts_ | 96.15% | ✅ | |
| _course-registration-detail.component.ts_ | 96.15% | ✅ | |

### CODE REVIEW

**Review by sven0311 — DISMISSED** [review]
code looks good 👍

**Review by dearjasmina — APPROVED** [review]
code looks good

**Review by lennart-keller — APPROVED** [review]
Code looks really good.

**Review by JohannesStoehr — COMMENTED** [review]
Tests look good to me.
One question, is it possible that the subscriptions never actually return anything/are never called actually? I mean that neither `() => {...}` nor `(error) => {...}` is invoked?

**Pull request merged**
