### PR TITLE
`Development`: Refactor server services

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
There is a cyclic dependency between multiple services on the server side which was hidden by the fact that `instanceMessagingService` was passed as argument into method calls which should not be the case

### Description
This PR splits some larger services into smaller ones, moves methods into more appropriate places and fixes the cyclic dependency. The refactoring was done carefully, but the involved functionality should be tested and the code changes should be reviewed.

### Steps for Testing
* Test the most important functionality for different exercise types
* For programming exercises, test whether typical notifications still work correctly

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
no changes

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Code refactoring looks good to me

**Review by ge65cer — APPROVED** [review]
Tested on TS2 and found no issues. All in all I agree with the refactoring. 👍

**Review by minrows — APPROVED** [review]
Tested on TS1 during the testing session. Found no issues.

**Review by akesfeden — APPROVED** [review]
Tested on TS1 during testing session. Modeling exercise creation/deletion, programming exercise creation, building, consistency checks and text exercise submissions worked as expected and notifications are shown as normal.

**Pull request merged**
