### PR TITLE
Highlight plagiarism matches

### PR DESCRIPTION
**Pull request by philippbauch**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
To make the inspection of similar student submissions even easier, this PR adds the functionality to highlight detected matches between submissions.

**Note**: The highlighting introduced with this PR only works for *text* and *programming* exercises.

### Description
Before we display the student submissions in the split view, we use the information provided by JPlag about the exact matches to insert a token before and right after a detected match.

### Steps for Testing

To properly test this PR, you need both a text and a programming exercise with multiple similar submissions.

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to the Exercises of a course
4. Select a text or programming exercise
5. Click 'Check Plagiarism'

For programming exercises, generate a JPlag report. Then, uncheck 'Generate JPlag Report', click 'Check Plagiarism' again, and inspect the results in the split view. Make sure the Artemis highlighting matches the JPlag highlighting:

Screenshot 2020-12-29 at 16 56 14
Screenshot 2020-12-29 at 17 12 09

For text exercises, we can't compare the highlighting to the JPlag report. Just make sure you can see highlighted matches at all and that they roughly "make sense".

### Test Coverage
text-submission-viewer.component.ts 84.44%
plagiarism-sidebar.component.ts 82.14%

### Screenshots
Screenshot 2020-12-29 at 16 52 15

### CODE REVIEW

**Review by airelawaleria — CHANGES_REQUESTED** [review]
Tested in the testing session. We found some issues. 
1. Programming exercises. The duplicated code is detected correctly and with JPA reports everything works fine. But, if you switch between files (e.g. in this case to Client.java) the solution will be apparently displayed, even though nothing was changed in the Client.java. 
image

2. Text exercise
Some unrelated text (which is present only in one submission is also wrongly detected as plagiarism) 
image

**Review by JohannesWeiss — CHANGES_REQUESTED** [review]
Tested in testing session on ts1, can confirm the issues stated by @airelawaleria.

**Review by LudwigWeide — CHANGES_REQUESTED** [review]
Test in testing session with @airelawaleria . Same issue.

**Review by simonzilker — COMMENTED** [review]
What @airelawaleria said

**Review by marvinchimeka — CHANGES_REQUESTED** [review]
tested in testing session. Confirming @airelawaleria statement about this issue

**Review by EneaGore — COMMENTED** [review]
Same issues, would also add that 100% copy-pasted text is only recognized as 99% plagarism.

**Review by philgabr — COMMENTED** [review]
Same issues as mentioned already.

Also, I wasn't able to scroll down in order to see all plagiarism comparisions sufficiently:
image

**Comment by philippbauch** [comment]
> Same issues, would also add that 100% copy-pasted text is only recognized as 99% plagarism.

The 99% similarity of identical submissions is a known issue and a result of some implementation details in the JPlag code. For now, I think we can ignore this behavior

**Comment by philippbauch** [comment]
> Same issues as mentioned already.
> 
> Also, I wasn't able to scroll down in order to see all plagiarism comparisions sufficiently:
> image

Good finding! I pushed a change to fix the layout in Chrome. Should be more stable now 👍🏻

**Comment by philippbauch** [comment]
> Tested in the testing session. We found some issues.
> 
> 1. Programming exercises. The duplicated code is detected correctly and with JPA reports everything works fine. But, if you switch between files (e.g. in this case to Client.java) the solution will be apparently displayed, even though nothing was changed in the Client.java.
>    image
> 2. Text exercise
>    Some unrelated text (which is present only in one submission) is also wrongly detected as plagiarism
>    image
> 
> P.S. tested on ts1, Valeryia's Course Highlight_plagiarism exercises

The layout issue of the overflowing text should be fixed now. 

Also, I found the reason why some matches were highlighted incorrectly. This should be fixed now as well.

**Note**: The user should still be able to inspect files that don't contain any matches. The highlighting is just an additional layer of information on top of the raw file contents.

**Review by airelawaleria — APPROVED** [review]
Tested in the testing session with @simonzilker @marvinchimeka @JohannesWeiss . 
Everything works fine now. The only thing we noticed, that in the plagiarism check for text exercises, the submitted text is displayed in a single line making it non that user-friedly :D
image

**Review by simonzilker — APPROVED** [review]
Tested in testing session. Approve and what @airelawaleria said.

**Review by JohannesWeiss — APPROVED** [review]
Tested in testing session on ts1, basically works as intended. Can confirm the aforementioned minor issue.

**Review by marvinchimeka — DISMISSED** [review]
Can confirm the mentioned issue but still approve

**Comment by philippbauch** [comment]
> Tested in the testing session with @simonzilker @marvinchimeka @JohannesWeiss .
> Everything works fine now. The only thing we noticed, that in the plagiarism check for text exercises, the submitted text is displayed in a single line making it not that user-friedly :D
> image

I just pushed a fix for this. Text Submissions should now wrap lines, programming exercises keep the horizontal scrolling

**Review by airelawaleria — APPROVED** [review]
Re-tested on ts1. Re-approve

**Review by simonzilker — APPROVED** [review]
Text exercises are now also displayed nicely. Looks good!

**Review by marvinchimeka — APPROVED** [review]
Approve.

**Review by JohannesWeiss — APPROVED** [review]
Re-Approve as well!

**Review by krusche — APPROVED** [review]

**Pull request merged**
