### PR TITLE
Improve the testcoverage of DragAndDropStatisticComponent

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Test Coverage
main/webapp/app/exercises/quiz/manage/statistics/drag-and-drop-question-statistic: `0% -> 88.89%`

### CODE REVIEW

**Review by krusche — CHANGES_REQUESTED** [review]
please fix the issues found by the linter and GitHub

**Comment by tiffca** [comment]
Hi, we don't know what to test for this PR, can someone please add testing steps?

**Comment by FrankeLukas** [comment]
> Hi, we don't know what to test for this PR, can someone please add testing steps?

I fear there is not much to test here. The important part is checking that the test run correctly on the build agents and the coverage report is correct (up to over 80%). One thing that could be done is running the test locally, I can click a run button next to the tests to do that/test them locally:
grafik
grafik

**Review by krusche — CHANGES_REQUESTED** [review]
There are still warnings
image

**Comment by FrankeLukas** [comment]
Resolved the issues.

**Review by krusche — APPROVED** [review]

**Pull request merged**
