### PR TITLE
`General`: Adjust validation bar styles

### PR DESCRIPTION
**Pull request by milljoniaer**
#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
makes circles smaller, fixes client tests

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Edit Programming exercise
3. Circles in validation bar are smaller

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Screenshots

image

### CODE REVIEW

**Review by laurenzfb — APPROVED** [review]
pixel magic approve

**Review by rstief — DISMISSED** [review]
tested in testing session. lgtm

**Review by JohannesWt — DISMISSED** [review]
Code looks good

**Review by kaancayli — DISMISSED** [review]
Changes work as expected. Approved

**Review by JohannesWt — APPROVED** [review]
Code looks good

**Review by laurenzfb — DISMISSED** [review]

**Review by kaancayli — DISMISSED** [review]
Reapprove

**Review by rstief — DISMISSED** [review]

**Review by rabeatwork — DISMISSED** [review]
Maintainer approved

**Review by MichaelOwenDyer — DISMISSED** [review]
bellissimo

**Review by krusche — APPROVED** [review]
Looks good to me 👍 but we need to apply further small improvements in follow-up PRs

**Pull request merged**
