### PR TITLE
`Adaptive learning`: Explain course competency view

### PR DESCRIPTION
**Pull request by JohannesWt**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Currently there is no intuitive explanation for the competencies and adaptive learning feature.

### Description

This PR introduces a modal which explains the competencies and adaptive learning feature.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Log in to Artemis
2. Navigate to Competency management page
3. Open the help window

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image

## Summary by CodeRabbit

- **New Features**
	- Introduced a help button in the competency management interface for enhanced user support.
	- Added a modal for course competency explanations, providing detailed guidance on adaptive learning and competency relationships.
- **Bug Fixes**
	- Improved localization support with new and updated translations for German and English.
- **Documentation**
	- Expanded instructional content within the user interface to clarify functionalities and processes related to competency management.

### CODE REVIEW

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Works as expected! I would like to recommend adding a feature which enables users to close the explaination view simply by clicking outside of the view instead of having to scroll up and press X.

Screenshot 2024-10-18 181716

**Review by pzdr7 — APPROVED** [review]
Code looks good :+1:

**Review by sachmii — APPROVED** [review]
Tested on TS4, works fine.

**Review by krusche — APPROVED** [review]
Great addition for instructors who use the feature for the first time. Thank you 👍

**Pull request merged**
