### PR TITLE
`General`: Further improve responsive layout 

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

There were some more issues with the responsive layout collected in issue #5106.

### Description

Follow-up to #5053, this PR fixes some more issues with the client layout on mobile devices.

### Steps for Testing

Prerequisites:
- 1 Instructor or Student

1. Log in to Artemis
2. Enable mobile emulation in your browser's development tools
3. Navigate to changed client components (Course Management, Discussions, Assessment Dashboard)
4. Test the description's `Show more` and `Show less` on the Course Management page
5. Review the added section in [client documentation](https://artemis-platform--5128.org.readthedocs.build/en/5128/dev/guidelines/client/#responsive-layout)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| [course-overview.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS3394-4/artifact/shared/Coverage-Report-Client-Tests/app/overview/course-overview.component.ts.html) | 80.2% | 92.2% |
| [course-detail.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS3394-4/artifact/shared/Coverage-Report-Client-Tests/app/course/manage/detail/course-detail.component.ts.html) | 83.3% | 96.1% |

### Screenshots

<details>
<summary>Assessment Dashboard</summary>

Before & After

</details>
<details>
<summary>Course Overview</summary>

Before & After

</details>
<details>
<summary>Discussions</summary>

Before & After

</details>

### CODE REVIEW

**Review by joaquinmurcia — COMMENTED** [review]
Tested on TS1. The "Show more / Show less" option does not appear. Except in a very narrow screen, resizing works fine. The rest works as expected. Attached screenshots:
image
image
image
image

**Review by jbllhff — COMMENTED** [review]
Bildschirmfoto 2022-05-25 um 10 51 24
Tested on ts2, the responsive layout works fine, but I detected the following issue on the full screen (see screenshot).

**Comment by joaquinmurcia** [comment]
>

**Comment by joaquinmurcia** [comment]
> Tested on TS1. The "Show more / Show less" works when showing more, but not when showing less (first screenshot, in which I already clicked Showed more, then Show less). Except in a very narrow screen, resizing works fine. The rest works as expected.
> 
> Attached screenshots

"Show more / Show less" bug fixed

**Comment by ge65cer** [comment]
> Tested on ts2, the responsive layout works fine, but I detected the following issue on the full screen (see screenshot).
We can probably ignore this, as #5115 will remove the full-screen button.

**Review by nairaarnez — APPROVED** [review]
The show more/show less bug is fixed! But I just encountered this 
image
It can still be seen and used, but the graph is shown on the left side of the screen. In full screen everything looks good!

**Comment by ge65cer** [comment]
> It can still be seen and used, but the graph is shown on the left side of the screen. In full screen everything looks good!

Out of the scope of this PR, please see https://github.com/ls1intum/Artemis/pull/5115.

**Review by jschmautzer — DISMISSED** [review]
tested on ts1, followed the testing steps and everything in the scope of this PR seems fixed :)

**Review by max-bergmann — APPROVED** [review]
tested on ts2, everything in the scope of this PR seems to work as expected

**Review by babyygemperor — APPROVED** [review]
Tested on ts2, works as described within the scope of this PR

**Comment by Dominik-Weinzierl** [comment]
Seems like the Course-Management page ist now broken after this merge. Thanks to @mallgaier for pointing this out.

@ge65cer could you please check this. Thank you!

**Comment by ge65cer** [comment]
Thanks for pointing that out. The issue is at [this line](https://github.com/ls1intum/Artemis/blob/fbb99675d68b21bd12da99e0334f2ebdf55a5834/src/main/webapp/app/course/manage/overview/course-management-card.scss#L118) and a byproduct from the removal of the CSS hack/workaround for Angular 12.

**Pull request merged**
