### PR TITLE
Add documentation about user management and build access control in Jenkins

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Motivation and Context

The current Jenkins user management functionality has a couple of caveats that the admin needs to know about. Furthermore some minor installation steps are required in order to setup build plan access control.
 
### Description

This PR updates the Jenkins documentation in ReadTheDocs and adds two new section "Jenkins User Management" and "Jenkins Build Plan Access Control Configuration".

### CODE REVIEW

**Review by FrankeLukas — DISMISSED** [review]
Looks good.

**Comment by sleiss** [comment]
Will the jenkins user management be automatically used if the Jenkins+Gitlab setup is used?
If yes, I would propose to add the additional plugin for the matrix authentication to the list of required Jenkins plugins:
https://artemis-platform.readthedocs.io/en/latest/dev/setup/jenkins-gitlab/#required-jenkins-plugins

**Comment by ivanchimeno** [comment]
> @ivanchimeno Will the jenkins user management be automatically used if the Jenkins+Gitlab setup is used?
> If yes, I would propose to add the additional plugin for the matrix authentication to the list of required Jenkins plugins:
> https://artemis-platform.readthedocs.io/en/latest/dev/setup/jenkins-gitlab/#required-jenkins-plugins

Thanks for the heads-up @sleiss!

**Review by sleiss — APPROVED** [review]
Looks good to me.

**Review by FrankeLukas — APPROVED** [review]
Re-approve.

**Pull request merged**
