### PR TITLE
Disallow the creation of text exercises with negative maxPoints

### PR DESCRIPTION
**Pull request by Strohgelaender**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) ~~on the test server https://artemistest.ase.in.tum.de~~ locally.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context
This PR disallows the creation of text exercises with negative points. The save-Button was just never disabled on the client. Also the server just checked the maximum points for being equal to 0, not less or equal. 

### Description
- Disabled the save-Button or form errors for text exercises
- Validating the exercise against negative points on the server.

### Steps for Testing

1. Try creating a text exercise with a negative score -> not possible.
3. Try creating a text exercise with valid settings -> save-Button is active.

### CODE REVIEW

**Comment by Strohgelaender** [comment]
Disabling the save button is done in #3262 so this PR is a one-liner now.

**Review by FrankeLukas — APPROVED** [review]
Confirmed that the server no longer accepts negative max points. I wonder if we want to make a similar change to assure that the bonus points are >= 0?

**Comment by Strohgelaender** [comment]
I added the validation of the bonus points based on the IncludedInOverallScore by using an enum-method. I'm not sure if this is the best way for doing this so I'd like to hear your feedback.

**Review by FrankeLukas — APPROVED** [review]
I have to admit I didn't even know enums could be used like that. 😅 
But it looks like we use similar in other places.

One thing I noticed: Does the following selector even work?
grafik
Regardless of what I set here, it always uses "Yes". (E.g. create an exercise with "No" and then go to edit and it is on "Yes" again?) It doesn't look like this is an issue of this PR, though.

**Comment by FrankeLukas** [comment]
> One thing I noticed: Does the following selector even work?

Looks like a regression from the strict template changes, I filed #3265.

**Review by krusche — APPROVED** [review]

**Comment by Strohgelaender** [comment]
Opend #3279 on an internal branch.

**Pull request closed without merging**
