### PR TITLE
`Development`: Refactor exercise scores CSV export

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
The CSV file was manually assembled before this PR. This is error-prone in case of special characters in the team names and grading criteria. Therefore, using a library to build the CSV that automatically handles required character-escapes is useful.

### Description
This PR refactors the export to no longer manually assemble the CSV but instead uses a library for this task.

### Steps for Testing

Prerequisites:
- 1 Instructor
- Exercises with student submissions: at least some combination of various exercise features should be tested, the exercise can have multiple features at the same time
    - programming exercise: repo link should be part of the CSV
    - grading criteria: the points per grading criterion should be in the CSV
    - team exercise: the team name should be in the CSV instead of the student names, there should be a special column listing all student names in the CSV

1. Go to the ‘Scores’ page of an exercise.
2. Use the ‘Export Results’ button in the top-right-hand corner.
3. The data in the CSV should match the one you can see in the table. The columns as described above should be part of the CSV.

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| File/Class | Branch | Statement |
| --- | --- | --- |
| `exercise-scores-export-button.component.ts` | 84.5% | 94.4% |

### Screenshots
n/a

### CODE REVIEW

**Comment by Garfield96** [comment]
Related to https://github.com/ls1intum/Artemis/issues/4815

**Comment by b-fein** [comment]
> Related to #4815

@Garfield96 Not related, just unfortunate timing on a similar issue. The actual related PR is #4816.

**Comment by b-fein** [comment]
@ole-ve Thanks for testing.
Apparently if I set default values for the score/points on object declaration those attributes are handled differently compared to ones added later on using array key notation. I removed the default values from the `csvRow` object and it now shows the values in the correct order again.

**Review by ole-ve — APPROVED** [review]
Tested on TS1, works as described for me. 👍
Code Review will follow.

**Review by Hialus — APPROVED** [review]
Tested in testing session on TS1.
Works as expected 👍🏻

**Review by valeriebucher — APPROVED** [review]
Tested in testing session, worked as expected 👍

**Review by MerlinMehmed — APPROVED** [review]
Code changes look good to me!

**Pull request merged**
