### PR TITLE
Display plagiarism run details

### PR DESCRIPTION
**Pull request by philippbauch**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context
To make the inspection of plagiarism results more insightful, this PR adds a new tab to the plagiarism sidebar to display additional information (duration of the run, similarity distribution).

### Description
I added a new `PlagiarismRunDetails` component to display the duration and similarity distribution of the plagiarism detection run. It can be viewed by clicking on "Run details" in the sidebar. Details are available for text, programming, and modeling exercises.

### Steps for Testing
**Note**: You need an exercise with multiple, similar submissions to properly test this PR.

1. Log in to Artemis
2. Navigate to Course Administration
3. Go to Exercises of a course
4. Click 'View' on a modeling, text, or programming exercise
5. Click 'Check Plagiarism'
6. On the plagiarism page, click 'Check Plagiarism' again

Make sure that

* In the sidebar, you should see the new "Run details" tab
* Selecting "Run details" should open the run details view
* The duration should be displayed and formatted correctly (HH:mm:ss.SSS)
* The similarity distribution should be rendered as a bar chart
* The bar chart should display the similarities (compare with plagiarism matches in the sidebar)
* Details should be available for text, programming, and modeling exercises

**Note**: If you only have a few submissions for an exercise, the plagiarism detection might be very fast (<1ms). In this case, the duration will be displayed as 00:00:00.000. This is correct behavior; just make sure no errors are thrown in the browser console.

### Test Coverage
plagiarism-sidebar.component.ts **81.25%**
plagiarism-run-details.component.ts **93.75%**

### Screenshots
Screenshot 2021-01-07 at 16 20 29

### CODE REVIEW

**Review by airelawaleria — DISMISSED** [review]
Tested in the testing session. Approve

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts1 in testing session with @airelawaleria, @marvinchimeka  and @simonzilker. 
Works as intended.

**Review by simonzilker — DISMISSED** [review]
Everything wokrs as stated!

**Review by marvinchimeka — APPROVED** [review]
Tested in testing session. Works fine

**Review by LudwigWeide — APPROVED** [review]
Testen in testing session. Approve.

**Review by EneaGore — APPROVED** [review]

**Review by FlorianStang — APPROVED** [review]
Tested on TS1, everything worked as intended.

**Review by philgabr — COMMENTED** [review]
Tested on ts3, works as intended

**Review by krusche — APPROVED** [review]

**Pull request merged**
