### PR TITLE
`Team exercises`: Fix missing character in manual assignment

### LINKED ISSUE #8008: 'Teams': Missing a character in a label
### Describe the bug

Seems like it is missing a ']' in the assessment page of teams exercises. (see the screenshot). 

### To Reproduce

1. Create teams 
2. Create an exercise with a manual assessment
3. Provide the grades (also bonus)
4. Conduct an assessment
5. Verify that the grades is missing the ']' (see the screenshot )

### Expected behavior

I think should be complete that label with a ']'

### Screenshots

image

### Which version of Artemis are you seeing the problem on?

6.7.7

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by egekurt123**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Fixes #8008 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Team Programming Exercise
 with manual assignment
1. Log in to Artemis
2. Create a team programming exercise with manual assessment
3. Provide the grades (also bonus)
4. Conduct an assessment
5. Verify that the title is not missing ']'

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Before
Screenshot 2024-03-03 at 09 41 44

After
Screenshot 2024-03-03 at 09 41 15

## Summary by CodeRabbit

- **Bug Fixes**
	- Corrected a missing visual element in the code editor's tutor assessment interface.

### CODE REVIEW

**Review by b-fein — APPROVED** [review]

**Review by coolchock — APPROVED** [review]

**Review by georgyia — CHANGES_REQUESTED** [review]
tested on ts3, for some reason, its the same 
Снимок экрана 2024-03-04 в 22 57 13

**Review by Predixx — APPROVED** [review]
tested on ts6. lgtm!

**Review by vinceclifford — APPROVED** [review]
Tested on TS6 with Liam. Works as intended. 
image

**Review by georgyia — APPROVED** [review]
reapprove

**Pull request merged**
