### PR TITLE
`Exam mode`: Update collection of switch exercises action in live statistics

### PR DESCRIPTION
**Pull request by Dominik-Weinzierl**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

As noticed in https://github.com/ls1intum/Artemis/pull/5358, the collection of switched exercise actions needs some enhancements.

### Description

- Switching from the handed early page to the exercise is now correctly visible in the dashboard
- Save and continue always puts the save timestamp before continue

### Steps for Testing

Prerequisites:
- 1 Instructor
- One/Multiple Student
- 1 Exam

1. Log in to Artemis
2. Create an Exam with Exam Live Statistics enabled
3. Participate with the student
4. Check that the switches are detected correctly.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

Since the bamboo tests fail:
image

### Screenshots

https://user-images.githubusercontent.com/60005702/178297679-ecfa79eb-2c61-46fa-9c09-bbb3cd4fa598.mp4

### CODE REVIEW

**Comment by joaquinmurcia** [comment]
Tested on TS1. Works as expected.

**Review by jbllhff — APPROVED** [review]
Tested on ts2, works fine!

**Review by manuelmanso — APPROVED** [review]
LGTM, works as expected in TS2

**Review by stefanwaldhauser — APPROVED** [review]
Switching to the exercise is now correctly visible in the dashboard! Good job!

**Review by Hialus — APPROVED** [review]
Code changes looks good 👍🏻

**Pull request merged**
