### PR TITLE
`Quiz exercises`: Fix page not updating after importing questions

### LINKED ISSUE #5157: Quiz exercise - import questions are not displayed immediately
### Describe the bug

When you import questions from other courses, after selecting the questions and after clicking "Add selected questions". You need definitely to click anywhere on the page to load those questions. 
See the short video below

### To Reproduce

1. Go to Course Management
2. Click on any course
3. Go to Exercise
4. Go to quiz exercises
5. Click on create a new quiz exercise
6. Click in Add existing questions
7. Select a course 
8. Select the questions that you want to import 
9. Press "Add selected questions"
10. You will see that nothing is shown until you click anywhere on the page. 
11. See the video below 

### Expected behavior

After pressing "Add selected questions" these should be shown on the page without clicking anywhere else.

### Screenshots

Uploading Screen Recording 2022-05-26 at 12.23.18.mov…

### What browsers are you seeing the problem on?

Chrome, Safari

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by manuelmanso**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Close #5157

### Description

When importing questions, a call to `cacheValidation()` was missing so that the page would update without requiring the user to click somewhere on the page.

### Steps for Testing

As described in #5157:

1. Log in to Artemis
2. Go to Course Management
3. Click on any course
4. Go to Exercises
5. Create a new quiz exercise
6. Click 'Add existing questions'
7. Select a course
8. Select the questions you want to import (select at least 5 or so to make reproducing it more likely)
9. Verify that the questions get imported correctly and no click is required to get the page to update

Maybe reproducing the bug beforehand is better to understand what was fixed. The bug isn't always reproducible so it's better to try a few times with 10+ questions to have a higher chance of seeing the bug.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Branch | Line |
|------------|-------:|-----:|

### CODE REVIEW

**Review by jbllhff — APPROVED** [review]
Tested on ts2, no bug occurred, thanks!

**Review by alaraozdenler — APPROVED** [review]
Tested on ts1, works as expected, no bug has occurred

**Review by Santia-go — APPROVED** [review]
Tested on TS1
Works as expected. Thank you for solved it!

**Review by maximiliansoelch — APPROVED** [review]
Tested on TS1, works as expected 👍

**Pull request merged**
