### PR TITLE
`Communication`: Migrate FAQ feature to new client guidelines

### PR DESCRIPTION
**Pull request by cremertim**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

We want to migrate the communication section to the new client guidelines. In particular, this means that all components should become standalone

### Description

This PR adresses the FAQ feature and updates it to the new client guidelines by removing constructor injection

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Tutor
- 1 Course with FAQ enabled

1. Log in to Artemis
2. Navigate to Course Management
3. Create / Propose an FAQ as Instructor/Tutor
4. Accept the FAQ

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Updated dependency injection method for improved simplicity in the FAQ service and resolver.
  
- **Bug Fixes**
	- No bugs reported or fixed in this release.

- **Documentation**
	- Clarified the changes in dependency injection patterns for developers.

- **Refactor**
	- Simplified the construction of services using Angular's `inject` function.

### CODE REVIEW

**Review by PaRangger — APPROVED** [review]
Code LGTM

**Review by sachmii — APPROVED** [review]
Tested on TS3, created FAQ as instructor and proposed FAQ as tutor. Everything works fine.

**Review by HawKhiem — APPROVED** [review]
Tested on TS3. FAQ proposal and acceptance functionalities work as described

Screenshot 2024-11-29 191106
Screenshot 2024-11-29 191128
Screenshot 2024-11-29 191136

**Review by sawys777 — APPROVED** [review]
Tested on TS3. Everything worked as intended.

**Review by asliayk — APPROVED** [review]
code lgtm

**Comment by Malekos74** [comment]
I can't connect to the artemis test server 3, I will come back again later and try

**Review by FelixTJDietrich — APPROVED** [review]
Worked as expected, code LGTM

**Pull request merged**
