### PR TITLE
`Programming exercises`: Improve form validation bar

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
This PR improves the validation of optional fields (packageName & teamConfig & customBuild Plans). Also the circle within the validation bar is now also clickable to navigate.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Create a Programming Exercise & Programming Exam Exercise
3. Verify that the validation bar reflects the status of the packageName, teamConfig & docker name (when custom build plans enabled)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [programming-exercise-custom-aeolus-build-plan.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6101/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/update/update-components/custom-build-plans/programming-exercise-custom-aeolus-build-plan.component.ts.html) | 91.66% | ✅  |
| [programming-exercise-custom-build-plan.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6101/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/update/update-components/custom-build-plans/programming-exercise-custom-build-plan.component.ts.html) | 94.33% | ✅ |
| [programming-exercise-docker-image.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6101/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/programming/manage/update/update-components/custom-build-plans/programming-exercise-docker-image/programming-exercise-docker-image.component.ts.html) | 100% | ✅ |
| [team-config-form-group.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS6101/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/team-config-form-group/team-config-form-group.component.ts.html) | 100% | ✅ |

### Screenshots
image
image
image
image

## Summary by CodeRabbit

- **New Features**
	- Enhanced programming exercise management with Docker image customization options.
	- Improved form handling and validation for programming exercises and team configurations.
- **Refactor**
	- Streamlined subscription management in team config form group components.
- **Style**
	- Updated form status bar component with clickable functionality.
- **Tests**
	- Updated component tests to accommodate new changes and improve initialization validation.

### CODE REVIEW

**Review by nata-81 — APPROVED** [review]
Tested on ts3 works as expected.

**Review by Gusti2010 — APPROVED** [review]
Manually tested on ts11_Legacy. Everything works as expected!

**Review by georgyia — APPROVED** [review]
manually tested on ts1, works as expected

**Review by reschandreas — APPROVED** [review]
code lgtm, thanks for improving it!

**Review by laurenzfb — APPROVED** [review]
code lgtm

**Pull request merged**
