### PR TITLE
`Programming exercises`: Fix table overflow in rendered markdown

### PR DESCRIPTION
**Pull request by rabeatwork**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

When adding a large table to the problem statement the content of the exercise overflowed. 

### Description

Added logic to check if the rendered Markdown contains `<table>` elements and applied styles dynamically to prevent overflow issues. Ensured tables are responsive by setting max-width: 100% and enabling horizontal scrolling with overflow-x: scroll.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise with a large table in the problem statement 

1. Log in to Artemis
2. Navigate to the programming exercise
3. Verify that the content does not overflow despite the large table 
4. Collapse the Sidebar
5. Verify that the content does not overflow despite the large table 

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

Before: 
Screenshot 2024-12-06 at 12 03 46

After: 
Screenshot 2024-12-06 at 12 03 59

## Release Notes

- **New Features**
	- Enhanced markdown rendering with styled tables for improved readability.
	- Introduced new CSS classes for responsive layout adjustments of exercise content.

- **Bug Fixes**
	- Adjusted layout and class bindings in the course exercises component for better styling and functionality.

- **Style**
	- Added transition effects to new CSS classes for smoother width adjustments.

### CODE REVIEW

**Review by sachmii — APPROVED** [review]
Tested on TS4, everything works fine.

**Review by az108 — APPROVED** [review]
image
Works and Code 👍

**Review by sawys777 — APPROVED** [review]
Tested on TS1, everything works accordingly to the description.

**Review by ahbitaqu — APPROVED** [review]
[Tested on TS3]

Works flawlessly for me, tested it on mobile form-factor, too.

**Review by SimonKaran13 — APPROVED** [review]
Tested on TS1 with a big table. Works as expected
image

**Pull request merged**
