### PR TITLE
`General`: Check missing release date when creating or updating exercise

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Previously only programming exercises warned the instructor that it does not have a release date. This behavior was inconsistent and dangerous. Additionally it was checked for test courses where this check is not necessary.

### Description

It is now checked for programming, modeling, file upload and text exercises and only in non-test courses.
If the exercise does not have a release date and is only updated, there is also no warning.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Try to create an exercise (at least programming and one of the others). If you did not specify a release date, a warning should be shown.
3. Try to update the exercise. You should only get warned when you remove an existing release date
4. Check that the warning is never shown in a test course

#### Exam Mode Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Try to create an exercise, there should be no warning about a release date

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test

### Screenshots

Bildschirm­foto 2022-11-27 um 17 36 02

### CODE REVIEW

**Review by evgeny1984 — CHANGES_REQUESTED** [review]
I got an exception. Steps to reproduce: 

- I created the programming exercise with all set dates and saved
- I removed the Release Date and got the warning as expected as I tried to save
- I set the Release Date again and tried to save and got the exception
image

**Review by timo07k — DISMISSED** [review]
Everything works as expected. Also warnings are never shown in test courses. Tested on TS1.

**Review by TheZoker — APPROVED** [review]
Tested on TS1 and worked 👍

**Comment by simon-hng** [comment]
- Why do we have a list here? 
- IMO the text `You have ...` should not be bold
- Could you add a margin over `Do you want to...`

image

**Review by danielbode — APPROVED** [review]
Looks good! Tested on ts1.

**Review by pellumbbaboci — APPROVED** [review]
Tested on ts1 during testing session works as expected, code looks good.

**Review by rriyaldhi — APPROVED** [review]
Tested on TS1 and code looks good.

**Review by evgeny1984 — APPROVED** [review]
Works as expected, tested on ts1. The code looks good! The issue is fixed.

**Pull request merged**
