### PR TITLE
`Lectures`: Preserve ordering when editing lecture units

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.

### Motivation and Context

There was an issue related to the introduction of the `order` attribute on `LectureUnit` in #4931, which was done to [fix](https://docs.jboss.org/hibernate/stable/annotations/reference/en/html_single/#entity-hibspec-collection-extratype-indexbidir) some Hibernate quirks regarding the `OrderColumn`.
When a lecture unit was updated, the `order` would be set to `0` (which made it disappear as multiple lecture units can not have the same order number).

### Description

This PR fixes the issue by fetching the previous lecture unit from the database and overriding the `order` attribute of the posted object with the previous value in the put requests of all different lecture units.
I also added some tests to make sure this bug does not re-appear.
In the future, we should discuss whether we want to put a unique index on the tuple `(lecture_id, lecture_unit_order)` of the `lecture_unit` table.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a lecture with multiple lecture units
4. Edit the last lecture unit
5. Lecture unit should have updated and the ordering preserved

Please also make sure that importing a lecture with its lecture units and attachments still works.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
Tested locally, the order stays the same when editing units and also gets relayed into other courses when importing a lecture.

**Review by mallgaier — APPROVED** [review]
Tested on TS1, works as expected.
Good job 👍

**Review by maximiliansoelch — APPROVED** [review]
Tested on TS3, works as expected

**Comment by bassner** [comment]
Tested on TS1, works as described. Code looks good to me 👍

**Review by bassner — APPROVED** [review]

**Review by bassner — APPROVED** [review]
Tested on TS1, works as described. Code looks good to me 👍

**Pull request merged**
