### PR TITLE
`General`: Add hover effect for all sidebar items

### LINKED ISSUE #9651: Missing hover effect for `test-sidebar-card-medium` and others in Tab Exercises
### Describe the bug

When hovering over an exercise (`test-sidebar-card-medium`) element, there is no visual indication 
that the element is being interacted with. 
Most other elements on the site have a hover effect that provides feedback to the user.
The lack of this effect on the `test-sidebar-card` makes it inconsistent with the design in general.

### To Reproduce

1. Select any course with an exercise
2. Select "Exercises" on the left
3. Hover over an exercise

### Expected behavior

When you hover over an exercise, there should be a visual indication, like the other hover effects that are already implemented when you move the mouse over a course.

### Screenshots

No hover effect, even though my mouse is on top of it:
Screenshot 2024-11-01 150123
test_course_unhovered
Course with hovereffect:
test_course_hovered

### Which version of Artemis are you seeing the problem on?

7.6.4

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

I don't think it's a browser related bug, but that the hover effect is generally missing.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by laxerhd**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

There were issues regarding consistency. Most elements have a hover effect, this is not the case with the sidecard-card-medium. It did not feel right to hover over these elements. Fixes #9651.

### Description

I added a CSS class for the hover effect of the `sidebar-card-medium` (which is used for exercises) and added it to the classes in the html file.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Programming Exercise

1. Log in to Artemis
2. Navigate to the Course
3. Hover over the Programming Exercise
4. You should see the hover effect (change color)

#### Exam Mode Testing

I'm not sure if the tests are that different than the tests from above. In `sidebar-card-medium.component.html` there is a mention of the Exam Mode. I'm not sure whether this needs to be tested more thoroughly.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2
#### Performance Tests
- [ ] Test 1
- [ ] Test 2

### Screenshots

https://github.com/user-attachments/assets/bbc97764-402f-4a17-a80d-ef2cad84a77b

## Summary by CodeRabbit

- **New Features**
	- Introduced a hover effect for sidebar cards, enhancing visual feedback when users interact with them.
- **Style**
	- Added a new CSS class `.hover-effect` to improve the user experience with a background color change on hover.

### CODE REVIEW

**Comment by laxerhd** [comment]
Could someone please review this PR.
I would be very grateful.

**Review by iyannsch — APPROVED** [review]
Code LGTM

**Review by BBesrour — APPROVED** [review]
code lgtm

**Comment by laxerhd** [comment]
Is there a reason why this was not successfully deployed to the test servers yet?

**Comment by laxerhd** [comment]
Please unstale. Would be great if this could get some more rewies as not many are missing.

**Review by krusche — APPROVED** [review]

**Pull request merged**
