### PR TITLE
`Programming exercise`: Improve anonymize option in export repository dialog

### PR DESCRIPTION
**Pull request by FelixTJDietrich**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] ~~I added multiple integration tests (Spring) related to the features (with a high test coverage).~~
- [x] ~~I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).~~
- [x] I documented the Java code using JavaDoc style.

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] ~~Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.~~
- [x] ~~I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).~~
- [x] ~~I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).~~
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

Currently there is no way to also hide the student's name when exporting the programming exercise repositories, there only is a option for anonymizing student's commits. The anonymization option should include hiding the student's name so it is actually anonymized and can be handed out for example as evaluation data for [Athena](https://github.com/ls1intum/Athena).

### Description

Renamed `Anonymize all of the student's commits` to `Anonymize repository` in the programming exercise's **Export Repository** dialog. This option now also hides the student's names from the directories in the downloaded zip file, in addition to anonymizing the commits.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1-2 Students
- 1 Programming Exercise with submissions

1. Log in to Artemis as instructor
2. Navigate to Course Management
3. Go to the detail view of a Programming Exercise
4. Press **Scores** button to get to the scores page
5. Make sure to have at least 1 participation listed, ideally more
6. Press **Export** -> **Download Repos** button
7. Check `Or download the repositories of all students` and `Anonymize repository` in the **Export Repository** dialog
8. Press **Export** and unzip the downloaded zip
9. Make sure that the student names are now hidden (replaced by **student-submission**), e.g. `themisTest-Sorting-17779-student-submission.git.zip`
10. Repeat export with unchecked `Anonymize repository` and check if student names are there

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Unchanged

### Screenshots

**Renamed `Anonymize all of the student's commits` to `Anonymize repository`:**

| Before | After |
|------------|--------------|
| image | image |

Unzipped repos with `Anonymize repository` set to true (student usernames are now hidden 🎉 )
image

### CODE REVIEW

**Review by SolizerCodes — APPROVED** [review]
Anonymization works, non-anonymized export also works 👍

**Review by asliayk — APPROVED** [review]
tested on ts1 for both anonymization and non-anonymization, works as expected

**Review by pal03377 — APPROVED** [review]
Tested on TS4 with multiple combinations of export options, it works well 👍 

I also looked at the code, which looks good to me. It's pretty elegant how you re-use the existing options, well done! 🎉

**Review by Strohgelaender — APPROVED** [review]
code looks good.

**Pull request merged**
