### PR TITLE
`Learning path`: Fix competency graph overflow and display minimap

### PR DESCRIPTION
**Pull request by JohannesWt**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

When opening the competency graph the graph had a visible overflow at the bottom.

### Description

This PR fixes the bottom overflow of the competency graph and shows the minimap of the graph to give the user better orientation.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- at least 2 connected competencies with each at least one lecture unit (or Exercise)

1. Log in to Artemis
2. Navigate to the student learning path UI
3. Open the Learning path navigation overview
4. Verify that the graph can not be dragged out of the modal window vertically
5. Verify that the minimap of the graph is shown

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Minimap of the competency graph
(difficult to screenshot its better to see it on the test server)
image

## Summary by CodeRabbit

- **New Features**
	- Introduced mini-map functionality within the competency graph component with options for maximum width and height.
  
- **Style**
	- Enhanced styling of the competency graph modal to prevent overflow issues, ensuring a better user experience.

### CODE REVIEW

**Review by Jan-Thurner — APPROVED** [review]
Tested on TS3. The map is quite dark. The navigation works well though. Code also looking good.

**Review by JohannesStoehr — APPROVED** [review]
Tested on TS3. The map is quite dark. The navigation works well though. Code also looks good

**Review by florian-glombik — APPROVED** [review]
Approve code

**Review by egekurt123 — APPROVED** [review]
Code LGTM

**Review by rabeatwork — APPROVED** [review]
Maintainer approved

**Pull request merged**
