### PR TITLE
`Quiz exercises`: Fix drag and drop images not loading

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context
See #6825

### Description
I encountered the same issue as described (images not loading, instead an empty alt text was shown) locally. The error suggested that the image was supposed to get cached in the session storage, but there was not enough space available. This PR fixes this issue, where I assume it's the same one as described in the issue. However, I was not able to reproduce a case where the server returned an empty response.

As an hotfix, we disable caching for DND images. It would be better to change the logic so that a failed attempt to save the image does not result in canceling the whole loading process, but here I aim for a quick fix of the issue.

Also, you currently need to first save the question before using the preview mode. This is because images are only uploaded when saving the exercise, but pressing the preview button tries to load images which are not there yet. Again, this is out of scope for a hotfix.

### Steps for Testing
Do the same steps as in the issue and verify that images (regardless of the size of the image) are always shown. Please notify me if you mange to reproduce the case where an empty server response gets created.

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by dearjasmina — APPROVED** [review]
tested on a testing session as a student and instructor

**Review by jakubriegel — DISMISSED** [review]
Tested on testing session

**Comment by pal03377** [comment]
I could still reproduce the issue on TS4. I'm in contact with @Strohgelaender via Slack about this.

**Comment by Kroko-fant** [comment]
Tested in the testing session and it all worked 👍

**Review by Kroko-fant — APPROVED** [review]

**Pull request closed without merging**
