### PR TITLE
Fix a GitHub Actions warning about using triple-equals

### PR DESCRIPTION
**Pull request by FrankeLukas**
Resolves the following warning:
grafik

### CODE REVIEW

**Review by nicolasruscher — APPROVED** [review]

**Review by kloessst — COMMENTED** [review]
We had a lengthy discussion about this with @krusche. Semantically `== undefined` is not the same as `=== undefined`. The first one also checks for `null` values. If this still works we can keep this change. Otherwise I would suggest `== null` which is the same check as `== undefined` but is accepted in the JS world by convention.

**Comment by FrankeLukas** [comment]
> If this still works we can keep this change.

I just retested this on TS1 and it appears to still work the same as on develop.

**Comment by krusche** [comment]
I would prefer if we do not use null any more
== null and == undefined are the same 

Please use == undefined then

**Comment by krusche** [comment]
I recently changed the lint rules regarding this

**Comment by krusche** [comment]
are you sure there is a warning after the latest version of `develop` was merged?
== undefined should be fine. I close this PR

**Pull request closed without merging**
