### PR TITLE
`General`: Add new contributors to about us page

### PR DESCRIPTION
**Pull request by ge65cer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Description

This pull request adds new contributors to the [“About Us”](https://artemis.ase.in.tum.de/about) page.

### Steps for Adding Yourself

1. Put a photo of yourself in `src/main/resources/public/images/about/`
2. Add your name and image path to `src/main/resources/public/content/about-us.json` (order is not important)
3. Commit your changes to this branch (`chore/about-us-contributors`) 

#### Code Review
- [ ] Review 1
- [ ] Review 2

### CODE REVIEW

**Review by Dominik-Weinzierl — COMMENTED** [review]
deleted

**Review by willergeorg — APPROVED** [review]
Nice 👍

**Review by Dominik-Weinzierl — CHANGES_REQUESTED** [review]
Please use the correct aspect ratio :) @dangcosta 
image

**Review by Dominik-Weinzierl — APPROVED** [review]
Thank you @ge65cer! Look good to me :+1:

**Review by willergeorg — APPROVED** [review]
Reapprove. 👍

**Pull request merged**
