### PR TITLE
[Bugfix] Removing quiz action buttons for editor

### PR DESCRIPTION
**Pull request by FlorianGlombik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Description

Tutors have been able to set quizzes visible - this was fixed server-sided recently - but the UI was forgotten. The buttons don't work for a tutor (403) so they are removed within this PR.

### Steps for Testing

1. Prepare a quiz that is not visible
2. Prepare a quiz that is visible
3. Prepare a quiz that is started
4. Prepare a quiz that is over but not yet ready for practice
5. Check whether tutors do not see the buttons 
6. Check whether editors and tutors can see the buttons to change the state of the quiz

### Screenshots

editor+ view:
image

tutor view:
image

### CODE REVIEW

**Review by canyelten — APPROVED** [review]
Tested on TS1. As a tutor, I could only see the green and blue buttons as described in the screenshot. As an editor, the yellow buttons were also visible as described in the screenshot. Works as expected.

**Review by NicolasUllmann — APPROVED** [review]
Tested no Server 1. Everything worked as expected. The buttons were displayed as described.

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Works.

**Review by KiraNickel — APPROVED** [review]
Tested on ts1, works as described 👍🏼

**Review by ivohashamov — APPROVED** [review]
Tested on TS2, looks good!

**Review by real-dmy — APPROVED** [review]
Tested on TS1. Works as expected.

**Review by jamalxo — COMMENTED** [review]
Tested on TS1, works as expected

**Review by jamalxo — APPROVED** [review]
Tested on TS1, works as expected

**Review by ivanchimeno — APPROVED** [review]

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3, works as expected

**Review by DanielKainz — APPROVED** [review]
Tested on TS1. Buttons are displayed or not visible as expected :-)

**Review by katjanakosic — APPROVED** [review]
Tested on TS2, works as expected

**Pull request merged**
