### PR TITLE
Fix automatic submission service

### PR DESCRIPTION
**Pull request by SiggZ**
### Checklist
- [x] I run `yarn run webpack:build:main`: the project builds without errors.
- [x] I run `yarn lint`: the project builds without code style warnings.
- [x] ~I updated the documentation and models.~
- [x] I tested the changes and all related features on the test server https://artemistest.ase.in.tum.de.
- [x] ~I added (end-to-end) test cases for the new functionality.~

### Motivation and Context

The automatic submission service that was re-enabled in https://github.com/ls1intum/ArTEMiS/pull/393 did not work properly.

### Description

The problem was that the service also loaded example submissions that do not have an associated participation. The missing participation then caused a NullPointerException. I fixed it by excluding submissions that do not have a participation associated when loading the submissions from the database.

### CODE REVIEW

**Comment by SiggZ** [comment]
I still have to check the correct behavior for submissions started after the exercise due date, as these submissions should not get submitted automatically.

**Comment by SiggZ** [comment]
I discussed the desired behavior with @krusche and adjusted the implementation accordingly:

Submissions should be automatically submitted if
 - the corresponding exercise has finished
 - the submission has a `submissionDate`
 - the `submissionDate` is before the exercise `dueDate`

It's not that easy to test it properly, but I think I finally made it to test all different scenarios on the test server. It looks fine to me.

One note: In the text submission component we do not subscribe for automatic submissions, i.e. the UI is not properly updated when the corresponding submission is submitted automatically in the mean time. For modeling exercises it works fine.

**Comment by jpbernius** [comment]
Does this fix #402?

**Comment by SiggZ** [comment]
@jpbernius Yes, modeling and text submissions that are saved before the exercise due date get automatically submitted by the automatic submission service. However, it checks the submissions every night at 01:00 a.m. and not directly at the time of the due date of every exercise.

**Pull request merged**
