### PR TITLE
New User statistics charts

### PR DESCRIPTION
**Pull request by FuchsDominik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

We want to have more charts because charts are life. I am still figuring out if all those charts should be displayed as a bar chart. -> follow-up PR
Also, on Production, longer waiting time for the data seems to create weird looking charts

### Description

Added a couple of new charts:
- Logged-In users
- Exercises due
- Conducted exams
- Exam participations
- Exam registrations
- Active tutors
- Created result
- Created feedbacks

The charts display only zeros until data is loaded

### Steps for Testing

1. Log in to Artemis
2. Navigate to Server Administration -> User statistics
3. Make sure no initial error are thrown
4. Keep in mind the values for the important bars

Test 'Logged-In users' by first logging in with a test-account, checking the number and afterwards logging in with a not-test account. The number should increase by one if you did not already login with this account in the bar period.

Testing Exercise related stats
1. Create a exercise with due date in the future
2. participate in that exercise
3. assess that exercise, keep in mind the amount of feedbacks
4. Look into user statistics - corresponding bars in the charts should rise with the expected amount

Testing Exam related stats
1. Create an exam (its better to manually add the students, is relevant for 'Exam participations', the endDate of the exam is relevant for the 'conducted exam' chart
2. participate in that exam
3. Look into user statistics - corresponding bars in the charts should rise with the expected amount

### Screenshots

The new charts, with different spans:
Screenshot 2020-12-18 at 18 48 27

Screenshot 2020-12-18 at 18 49 07

Screenshot 2020-12-18 at 18 49 32

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested with @simonzilker and @marvinchimeka. Works as expected

**Review by simonzilker — APPROVED** [review]
Tested in testing session. Works perfectly !

**Review by marvinchimeka — APPROVED** [review]
tested in a testing session on ts1. Approve

**Review by JohannesWeiss — APPROVED** [review]
Tested on ts1 and functionally works as intended.

**Comment by JohannesWeiss** [comment]
For some improvement I really would like to see some kind of groups/ categories of the different charts, because the overview is not perfect, especially with the newly added variety of statistics. Therefore ordering them in collapsible groups (e.g. Exam related, Exercise Related, General statistics, …) would help making the statistics more useful.

**Review by krusche — APPROVED** [review]

**Pull request merged**
