### PR TITLE
[Sentry] NaN when calculating score

### PR DESCRIPTION
**Pull request by PatZintel**
apparently sometimes, the score gets set to NaN because the successfulTestPoints are NaN, changed NaN to 0.0 in this case

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
### Motivation and Context

Sentry issue: https://sentry.ase.in.tum.de/organizations/artemis/issues/1706/events/cdbefb9fee564c5196938b653ebd71ca/?project=2#grouping-info

### Steps for Testing

code review, dont know how to replicate the error, bug only happened very seldom

### CODE REVIEW

**Review by GeneralMine — APPROVED** [review]
Even though I wasn't able to reproduce and test the error and the fix, the small code changes seem reasonable and legit

**Review by SimonEntholzer — APPROVED** [review]

**Review by FrankeLukas — APPROVED** [review]
Changes make sense.

**Review by ivohashamov — APPROVED** [review]
Code changes make sense to me

**Review by FuchsDominik — APPROVED** [review]
Should fix the issue

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
