### PR TITLE
`Exam mode`: Remove the footer during an exam

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

To maximize the exam content and reduce the distraction of the page, the footer should be removed.

### Description

Footer is removed, and therefore height of the exam sidebar and exam content is recalculated.

### Steps for Testing

**(You can test it on TS4 under my course with the exam "Hide Footer During Exam". Test users 1-5 are registered for that exam.)**
Prerequisites:
- 1 Exam
- 1 Student

1. Log in to Artemis
2. Participate in the exam as a student
3. Verify that there is no footer displayed during the exam

#### Exam Mode Testing

Prerequisites:
- 1 Exam
-  Student

1. Log in to Artemis
2. Participate in the exam as a student
3. Make sure that the footer is displayed in welcome page as well as after finishing the exam

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| exam-participation.component.ts | 90% | ✅                           |
| exam-participation-cover.component.ts | 99% | ✅ |
| main.component.ts | 68% | ✅ | 

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Screenshots

Before 
Screenshot 2024-07-28 at 16 48 22

After
Screenshot 2024-07-28 at 16 48 49

## Summary by CodeRabbit

- **New Features**
	- Enhanced functionality for continuing exams after early submission, reflecting user intentions more accurately.

- **Bug Fixes**
	- Improved sidebar and exam content heights to ensure a consistent user experience across devices and environments.

- **Style**
	- Simplified height calculations and removed outdated classes for a cleaner and more responsive design in exam-related components.

- **Tests**
	- Introduced unit tests for the main component to ensure proper rendering of the footer based on exam state.

### CODE REVIEW

**Review by BBesrour — DISMISSED** [review]
code

**Review by egekurt123 — DISMISSED** [review]
Works as expected on TS4

**Review by asliayk — APPROVED** [review]
tested locally

**Review by EneaGore — APPROVED** [review]
Tested on TS4. Footer during exam is gone and it shows on welcome page and after the exam.

**Review by sarpsahinalp — APPROVED** [review]
Code lgtm

**Review by sarpsahinalp — APPROVED** [review]
Reapprove after tests

**Review by asliayk — APPROVED** [review]
reapprove

**Review by EneaGore — APPROVED** [review]
re-approve

**Review by BBesrour — APPROVED** [review]

**Review by egekurt123 — APPROVED** [review]
Reapprove

**Review by krusche — APPROVED** [review]

**Pull request merged**
