### PR TITLE
`Development`: Refactor footer styles

### PR DESCRIPTION
**Pull request by simon-hng**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Cleaner code and cleaner UI :)

### Description

Refactors the footer styles into an isolated component. Removes/edits global styles to accommodate that footer.
Fixes some inconsistent spacing

### Steps for Testing
Check that the footer is not broken in different views (We have two footer, one for smaller screens and one for larger ones).

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image

Also fixes a strange margin on the left

image

### CODE REVIEW

**Review by TheZoker — APPROVED** [review]
Visual changes look good to me 👍

**Review by pellumbbaboci — CHANGES_REQUESTED** [review]
As seen in figure below the footer in smaller screens is not in correct position after scroll down. Normally this was not the case, I am not sure what is wrong and where the problem is @simon-hng can you maybe recheck the new changes? 

footerError

**Review by pellumbbaboci — DISMISSED** [review]
LGTM

**Review by LiaLism — APPROVED** [review]
Footers work in different views. Tested on ts1.

**Review by laadvo — COMMENTED** [review]
Footer looks good, works on smaller and bigger screens when testing on ts2. 
The space between the courses and the footer is quite a bit bigger having the browser open on a 4k screen compared to having it open on a normal sized screen. Is this supposed to be like this?
image
https://media.discordapp.net/attachments/803397150238441512/1045366406348292126/image.png

**Comment by simon-hng** [comment]
@laadvo yes this is intended behavior as the spacing you see there is not due to a padding but instead because the footer is always aligned to the bottom of your screen.

If there is space available at the bottom after all your elements in the content are rendered, then the footer will just be at the bottom of your screen. 

If instead a full page height is filled with content, only then a padding is applied/visible.

Thanks for your review!

**Review by laadvo — APPROVED** [review]
Retested on ts1, everything looks as expected

**Pull request merged**
