### PR TITLE
`Exam mode`: Allow import of file upload exercises for exams

### PR DESCRIPTION
**Pull request by tobias-lippert**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
Follow-up of #6048 

### Description
Only client side changes to show the button
### Steps for Testing

Prerequisites:
- 1 Editor or Instructor
- 2 Students
- 1 File Upload Exercise

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to Exams and Exercise Groups
4. See the new button
5. Click on it and import a file upload exercise
6. Check that the import was successful.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test

### Test Coverage

Change is tested
### Screenshots

image

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
Code looks good

**Review by YeetTheFirst21 — APPROVED** [review]
Tested on TS2, seems to be working as expected

**Review by Vinicius-Agreste — APPROVED** [review]
Tested on ts2. Working as expected.

**Review by TheZoker — APPROVED** [review]
Code LGTM 👍

**Pull request merged**
