### PR TITLE
`Quiz exercises`: Fix reset question button of drag and drop questions in re-evaluation page

### PR DESCRIPTION
**Pull request by rriyaldhi**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The question reset button of the DnD question on the quiz reevaluation page does not work. This caused the instructor not to be able to revert the changes made during quiz reevaluation.

https://user-images.githubusercontent.com/10885503/213447528-a1ad1cc3-73a3-491a-b807-c589bcc345d7.mov

### Description

The `questionEditorText` attribute of `DragAndDropQuestionEditComponent` needs to be updated with the new value of the markdown editor, otherwise, `questionEditorText` will always contain the same value (the first value when the component is loaded) which causes the reset functionality to be not working.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Quiz Exercise that is ended ([https://artemis-test1.artemis.in.tum.de/course-management/40/quiz-exercises/1916/re-evaluate](https://artemis-test1.artemis.in.tum.de/course-management/40/quiz-exercises/1916/re-evaluate))

1. Log in to Artemis
2. Navigate to Course Administration
3. Select the Course
4. Navigate to Exercises
5. Create a new Quiz Exercise
6. Set the duration to 1 Second
7. Create 1 Drag n Drop Question in the Quiz Exercise
8. Click Save and then Back
9. Click Start Exercise
10. Wait for 6 seconds, then refresh the page
11. Click the Reevaluation button of the quiz exercise
12. Update the question of DnD question
13. Click the undo button
14. Verify that the undo button works

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| drag-and-drop-question-edit.component.ts | 77.27% | 88.85% |

### Screenshots

https://user-images.githubusercontent.com/10885503/213447553-f75845d8-ce64-4dfd-b270-9ed4d0b80f64.mov

### CODE REVIEW

**Review by grochlitzzz — APPROVED** [review]
Worked fine (tested on ts1)

**Review by laadvo — APPROVED** [review]
The reset button of the dnd question works now, tested on ts1.

**Review by timo07k — APPROVED** [review]
Everything works as expected. Tested on TS1.

**Review by PhilipWerz — APPROVED** [review]
Reset/Undo button works as expected. Tested on TS1.

**Pull request merged**
