### PR TITLE
`Communication`: Reduce FAQ size

### PR DESCRIPTION
**Pull request by cremertim**
#### Client
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Currently, the UI is quite overwhelming

### Description

I reduced the font size of the question and the title

Prerequisites:
- 1 Instructor
- 1 Course with FAQ enabled

1. Log in to Artemis
2. Navigate to Course Overview
3. Click on FAQs
4. See the new UI

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

image
Old UI

image
New UI

### CODE REVIEW

**Review by rabeatwork — APPROVED** [review]
Thank you 🙏🏼

**Review by Malekos74 — APPROVED** [review]
### Server tested on: Server 3
Great change, it's  way better now

**Minor notice:**
On massive screen, the text is too small, maybe increase it's size

image

**Review by sachmii — APPROVED** [review]
Tested on TS4, looks way better with this change. Thank you :)

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS4. Looks a lot better than before, thank you!

Minor notice: It seems like the first FAQ has less space to the top line than others (they look slightly better because they look more centered)
image

**Review by krusche — APPROVED** [review]

**Pull request merged**
