### PR TITLE
`Development`: Fix load rating api spam and fix flaky e2e tests

### PR DESCRIPTION
**Pull request by EneaGore**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

There were some flaky tests. It was because the rating api was being spam called in the on changed hook .

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student

1. Log in to Artemis
2. Participate in the text/modeling/file-upload exercise
3. Assess and view result
4. Make sure rating component still exists in  results and works when clicked

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [ ] Code Review 1
#### Manual Tests
- [ ] Test 1

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved performance by optimizing the rating loading process, ensuring ratings are only fetched when the result changes.

- **Refactor**
	- Enhanced internal logic for tracking previously processed results without altering the public interface.

- **Tests**
	- Expanded test coverage for the `RatingComponent`, ensuring correct behavior when the result changes and preventing unnecessary API calls. Adjusted tests to handle scenarios with missing data.

### CODE REVIEW

**Review by florian-glombik — CHANGES_REQUESTED** [review]
While the fix looks good, would it be possible to add a small client test that ensures (and documents) that this issue does not occur again? 
Not that somebody tries to simplify the condition and the test turns flaky again 😅

**Review by edkaya — APPROVED** [review]
Code lgtm, e2e tests pass

**Review by muradium — APPROVED** [review]
Thanks for the fix. LGTM

**Review by krusche — APPROVED** [review]
Code looks good to me 👍

**Pull request merged**
