### PR TITLE
Redirect specific exercises routes to the shared overview

### PR DESCRIPTION
**Pull request by FrankeLukas**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).

### Motivation and Context

Having views only for specific exercise types doesn't make much sense at the moment (no extra information) and makes navigation harder since you can't go to all exercises from a single exercise using the breadcrumbs.

### Description

Redirects the specific routes to the general route.

### Steps for Testing

1. Open any site belonging to a specific exercise type, e.g. "Create a new Text Exercise" (can also be edit, scores, ...).
2. Click on `text-exercises` (or `modeling-exercises` etc. depending on which type you chose).
3. Check that you were redirected to the overview over all exercise types

Repeat for each of the 5 types.

Example:
Clicking on `text-exercises` here:
grafik
Goes to the `/course-management/209/exercises` URL.

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested in the testing session. Approve

**Review by EneaGore — APPROVED** [review]
Works as described. But i did kinda like that it used to redirect to only that type.

**Review by simonzilker — APPROVED** [review]
Approve!

**Review by marvinchimeka — APPROVED** [review]
Approve. Works as intended

**Review by JohannesWeiss — APPROVED** [review]
Works as expected!

**Review by derLalla — APPROVED** [review]
the code is nice and clean.  I didn't found any issues 👍

**Review by tiffca — APPROVED** [review]
Tested successfully

**Review by LWeide — APPROVED** [review]
Works as intended. Approve.

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
