### PR TITLE
`Development`: Change translations to follow new guidelines

### PR DESCRIPTION
**Pull request by rstief**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context
Changes all tags with jhiTranslate to conform to the new client coding guidelines specified in #8132 
This also reduces the bundle size.

### Description
Replaces all occurrences of text between tags with jhiTranslate using the following regex:
`(<([\w-]+)[^>]* jhiTranslate=".+"[^>]*>)[^{<]*(<\/\2>)`

Replacing occurrences of `artemisTranslate` has been omitted, since it might lead to failing tests and more inconsistencies in the code. Simple occurrences can be replaced by using the following regexes:
`(<.+)>\{\{ '([\w\d.-]*)' \| artemisTranslate \}\}(<\/.+>)` (to find)
`$1 jhiTranslate="$2">$3` (to replace)

### Steps for Testing
Run Artemis and verify no translations break

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### Test Coverage
unchanged

### CODE REVIEW

**Review by farisd16 — APPROVED** [review]
tested on ts2, everything seems fine

**Review by farisd16 — DISMISSED** [review]
tested on ts2, everything seems fine

**Review by laurenzfb — DISMISSED** [review]
looks good. regex makes sense

**Review by milljoniaer — DISMISSED** [review]
Looked through the changes, LGTM 🚀

**Review by RY997 — DISMISSED** [review]
Went through the changes. Looks good.

**Review by MaximilianAnzinger — APPROVED** [review]
Regex & Code

**Pull request merged**
