### PR TITLE
Chore/remove transactional

### PR DESCRIPTION
**Pull request by krusche**
This PR removes the annotation `@Transactional` where possible. The issue with `@Transactional` is that it might lead to unwanted save operations in the database which can lead to very weird bugs that are hard to track.

**Important:** `@Transactional` should only be used for more complex `delete` and `create` operations where it makes sense.

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Steps for Testing
All views and actions in the client should be quickly tested, in particular if they are related to:
1. Functionality related to users (UserService) on both configurations: Jira, Bitbucket, Bamboo on `TS1` and Gitlab, Jenkins on `TS2`
    * registration
    * login
    * logout
    * user administration (create, edit, delete, change groups, change authorities)
    * participate in guided tours (and check if the last step is saved correctly)
    * course registration 
    * course groups changes (add/remove students, tutors, instructors)
    * create courses
2. Complaints

### Test Coverage
no changes

### Screenshots
no UI changes

### CODE REVIEW

**Comment by tiffca** [comment]
Tested on ts1 and I wasn't able to select from the System Administration drop down as an instructor or my own user (admin privileges). Maybe someone else can please test if they can access it. I still need to test on ts2. 
system admin

**Review by tiffca — APPROVED** [review]
Noticed one thing, the "activated" doesn't seem to work properly. When you deactivate a user via user management, the user can still log in. Checked this with admin/non-admin test users such as user 2, 10. It works if I create a new user and deactivate that user, but not on existing users. 

Everything else worked as expected. Tested student registration on ts2 and course registration on ts1. 

I wasn't able to test user admin activities on ts2 yet, but it worked on ts1.

**Review by airelawaleria — COMMENTED** [review]
Tested with @JohannesWeiss @LudwigWeide @simonzilker. Everything worked fine on ts1. On ts2 there was inconsistency between the status in the exercise's dashboard and the status in the assessment dashoard. See vid posted by @JohannesWeiss

**Review by simonzilker — COMMENTED** [review]
experienced same issue as @airelawaleria

**Review by LudwigWeide — COMMENTED** [review]
tested with testing-team. Same issue.

**Review by JohannesWeiss — COMMENTED** [review]
Can confirm the issue mentioned by @airelawaleria, tested in testing session.

output

**Review by marvinchimeka — COMMENTED** [review]
Tested on ts2. The inconsistency was already mentioned. Confirming the issue stated by reviewers above.

**Comment by stefanwaldhauser** [comment]
> Tested on ts1 and I wasn't able to select from the System Administration drop down as an instructor or my own user (admin privileges). Maybe someone else can please test if they can access it. I still need to test on ts2.
> system admin

Can not confirm this error on TS1. Maybe you had an old cache?

**Comment by FrankeLukas** [comment]
> Noticed one thing, the "activated" doesn't seem to work properly. When you deactivate a user via user management, the user can still log in. Checked this with admin/non-admin test users such as user 2, 10. It works if I create a new user and deactivate that user, but not on existing users.

This seems to be intentional behaviour (and is already present like this on develop).

**Comment by stefanwaldhauser** [comment]
> Tested with @JohannesWeiss @LudwigWeide @simonzilker. Everything worked fine on ts1. On ts2 there was inconsistency between the status in the exercise's dashboard and the status in the assessment dashoard. See vid posted by @JohannesWeiss

https://sentry.io/organizations/ls1intum/issues/2118286454/?environment=test&project=1440029&query=is%3Aunresolved

This seems to be related to the view @krusche. I do not think this is related to the PR. Do the views exist on TS2? It fails at line 55 in TutorLeaderBoardService
```
        List<TutorLeaderboardAssessmentView> tutorLeaderboardAssessments = tutorLeaderboardAssessmentViewRepository.findAllByCourseId(course.getId());
```

**Comment by FrankeLukas** [comment]
Confirmed that the issue on TS2 already exists on develop, and thus isn't a regression from this PR.

**Comment by krusche** [comment]
> > Tested with @JohannesWeiss @LudwigWeide @simonzilker. Everything worked fine on ts1. On ts2 there was inconsistency between the status in the exercise's dashboard and the status in the assessment dashoard. See vid posted by @JohannesWeiss
> 
> https://sentry.io/organizations/ls1intum/issues/2118286454/?environment=test&project=1440029&query=is%3Aunresolved
> 
> This seems to be related to the view @krusche. I do not think this is related to the PR. Do the views exist on TS2? It fails at line 55 in TutorLeaderBoardService
> 
> ```
>         List<TutorLeaderboardAssessmentView> tutorLeaderboardAssessments = tutorLeaderboardAssessmentViewRepository.findAllByCourseId(course.getId());
> ```
> 
> ```
> {"type":"https://www.jhipster.tech/problem/problem-with-message","title":"Internal Server Error","status":500,"detail":"could not extract ResultSet; nested exception is org.hibernate.exception.GenericJDBCException: could not extract ResultSet","path":"/api/courses/1915/stats-for-tutor-dashboard","message":"error.http.500"}
> ```

image

Yep, seems to be a database issue with the views. Not sure what happened here, I'll try to re-create them

**Review by stefanwaldhauser — APPROVED** [review]
Tested it with @FrankeLukas and it seems to work fine. Found no other testing the steps given in the test case

**Review by airelawaleria — DISMISSED** [review]
Since the issue is not connected to the pr, re-approve

**Review by FrankeLukas — APPROVED** [review]
Tested functionality on TS1 (and a bit on TS2). User registration (for Artemis and Courses) still works locally.

**Review by simonzilker — DISMISSED** [review]
Re-approve!

**Review by JohannesWeiss — APPROVED** [review]
Re-Approve!

**Pull request merged**
