### PR TITLE
`Development`: Add support for multiple Artemis instances in Athena 

### PR DESCRIPTION
**Pull request by undernagruzez**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).

### Motivation and Context

This PR aims to improve the deployment experience of Athena. Many Artemis deployments will be able to use one Athena deployment now.

### Description

Adds a new header to the Athena-headed HTTP requests.

### Steps for Testing
Make sure the corresponding Athena PR is deployed: https://github.com/ls1intum/Athena/pull/279.
Deploy both PRs and use an arbitrary feature requiring Athena. Make sure everything works.

#### Performance Review
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Review
- [ ] Review 1
- [ ] Review 2

### Test Coverage
It wasn't changed.

### CODE REVIEW

**Review by marlon-luca-bu — COMMENTED** [review]
Code LGTM 👍

**Review by marlon-luca-bu — APPROVED** [review]

**Review by pzdr7 — APPROVED** [review]
Code

**Review by nityanandaz — APPROVED** [review]
Testing session 2024-05-21, manual review: Recent results show Athena's feedback

**Review by rabeatwork — APPROVED** [review]
Tested on test server; works as expected. 
Maintainer approved

**Review by egekurt123 — APPROVED** [review]
LGTM

**Pull request merged**
