### PR TITLE
Fix/lecture units improvements

### PR DESCRIPTION
**Pull request by stefanwaldhauser**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Description

- updated the style of the lecture units to a cleaner and more modern look
- text units should now open in a new tab instead of a popup when the button is clicked
- removed debounce-click directive

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create, Update, Delete Lecture Units of all types as a instructor, view them as a student and see that everything still works

### Test Coverage
No changes in code just fixed and styling changes

### Screenshots

Before:
image
image

After:
image
image

### CODE REVIEW

**Review by nutatuna — DISMISSED** [review]
Built and tested on my local machine. It works. The new UI looks lovely 👍

**Review by airelawaleria — DISMISSED** [review]
Tested on ts1 with @marvinchimeka . Everything worked as expected from both views.

**Review by marvinchimeka — APPROVED** [review]
Tested this on ts1 with @airelawaleria. it worked for both sides.

**Review by JohannesWeiss — DISMISSED** [review]
Tested on ts3 with student and instructor, both worked without issues.

**Review by krusche — CHANGES_REQUESTED** [review]
please fix the issues reported in Github
image

**Review by LudwigWeide — APPROVED** [review]
Tested on ts1 with student and instructor, both worked without issues.

**Comment by stefanwaldhauser** [comment]
> please fix the issues reported in Github
> image

This is not a real issue. Codacy just does not know the selector of components

**Review by DenizShabani — COMMENTED** [review]
Tested with student and instructor and both worked without issues.

**Review by krusche — APPROVED** [review]

**Pull request merged**
