### PR TITLE
[Bugfix] - Only create one result for exam quiz evaluations

### PR DESCRIPTION
**Pull request by FuchsDominik**
Fixes https://github.com/ls1intum/Artemis/issues/2908
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

The evaluate button in the student exams in only supposed to be clicked once. When clicking multiple times, the newly created results have no reference to the participation. As a result, the amount of points the student got is not shown in the view anymore.

### Description

We deactivated the creation and saving of new results after the first evaluation.

### Steps for Testing

1. Log in to Artemis
2. Create a exam with an (short answer) quiz question
3. Participate
4. After the exam is over, click on evaluate once in the student exams page
5. Click on "View" to view the student participations and make sure that every student has the correct result/amount of points in the table
6. Go back to the student exams page and click on evaluate again
7. Check that the results still are correctly displayed
8. Should also work for other quiz exercise types

**Re-evaluate**
1. Also, please check that the re-evaluation of short answer quizzes remains correct
2. Exercise-groups -> Re-evaluate
3. The "Add solution" button for short answer quizzes should now be called "Add Short Answer Solution" (Also check german translation is correct "Short Answer Lösung hinzufügen")
4. add a new solution (Which in the best case, a student typed in somewhere so you can check it gets counted as correct)
5. Make sure to map it to the spot where you want the option to be a correct input
6. save the re-evaluation and check that the student now get credits for this spot

### **Thinking task for Dev's**
Could not creating new results after the first evaluation be a problem somewhere I am not aware of?

### Screenshots

How the student participation view should not look after the second/third/fourth... evaluate
Screenshot 2021-02-22 at 17 30 15

How it should look like:
Screenshot 2021-02-22 at 17 30 47

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
all worked fine on ts1

**Review by JohannesWeiss — APPROVED** [review]
Everything worked as expected on ts1.

**Review by tiffca — APPROVED** [review]
Tested successfully. 

although the re-evaluate quiz page looks weird, likely outside the scope of this PR 
image

**Comment by FuchsDominik** [comment]
@tiffca I am just here for the Bugfix :P If you mean the boxes around the words, these are probably for mapping purposes.

**Comment by krusche** [comment]
We should definitely improve the user experience when adding new solutions, but the origin of the issue seems to be fixed. Thanks

**Review by krusche — APPROVED** [review]

**Pull request merged**
