### PR TITLE
`Development`: Migrate build agents components

### PR DESCRIPTION
**Pull request by BBesrour**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

Migrate build agent components to new Angular standars

### Steps for Testing

Prerequisites:
- Deploy locally or on TS3
- 1 Admin

1. Submit to a programming exercise a few times
2. Navigate to the Build Agents view (Click on Server administration > Build Agents)
3. Make sure that the build agent is displayed and that the processing jobs are displayed correctly
4. Click on build agent
5. Make sure that the build agent details view works correctly

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Release Notes

- **New Features**
	- `BuildAgentSummaryComponent` and `BuildAgentDetailsComponent` are now standalone components, enhancing modularity and reusability.
  
- **Improvements**
	- Streamlined dependency injection for components and services, simplifying code structure.
	- Enhanced test setups by removing unnecessary imports and focusing on core functionality.

- **Bug Fixes**
	- No specific bug fixes were noted, but overall stability and performance improvements are expected from the refactoring.

### CODE REVIEW

**Review by iyannsch — APPROVED** [review]
Changes LGTM, please pull updates from `develop` branch ☺️

**Review by magkue — APPROVED** [review]
Code LGTM

**Review by SimonEntholzer — APPROVED** [review]
code lgtm

**Review by coolchock — APPROVED** [review]
works as expected 👍

**Review by EneaGore — APPROVED** [review]
Tested in testing session. Works as expected.

**Review by FelixTJDietrich — APPROVED** [review]
Tested on TS3 and it worked as expected, everything updated correctly. Code LGTM

**Pull request merged**
