### PR TITLE
`Programming exercises`: Improve test build logs for Haskell exercises

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Changes affecting Programming Exercises
- [ ] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server configured with **Gitlab** and **Jenkins**.

### Motivation and Context

As noted in #9159, the test runner disabled the console output to produce the XML instead. Therefore, the test results no longer show up in the build log which makes it harder to debug what is happening when setting up exercises.

### Description

Updates the test template to produce both the console logs that then show up in the build log, and the XML needed to report the result back to Artemis.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Create a new Haskell programming exercise.
2. The solution should pass all tests.
3. Look at the build logs in Jenkins, or download the build logs for the solution build in the build history tab of the course. The test results should show up in the log as well (example below).

```log
Tests
  Properties
    Checked by SmallCheck
      Testing filtering in A:                  OK
        475 tests completed
      Testing mapping in A:                    OK
        19 tests completed
      Testing filtering in B:                  OK
        475 tests completed
      Testing mapping in B:                    OK
        19 tests completed
      Testing filtering in C:                  OK
        475 tests completed
      Testing mapping in C:                    OK
        19 tests completed
    Checked by QuickCheck
      Testing A against sample solution:       OK
        +++ OK, passed 100 tests.
      Testing B against sample solution:       OK
        +++ OK, passed 100 tests.
      Testing C against sample solution:       OK
        +++ OK, passed 100 tests.
  Unit Tests
    Testing selectAndReflectA (0,0) []:        OK
    Testing selectAndReflectB (0,1) [(0,0)]:   OK
    Testing selectAndReflectC (0,1) [(-1,-1)]: OK

All 12 tests passed (0.01s)
```

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
unchanged

--- 

@coderabbitai ignore

### CODE REVIEW

**Review by HawKhiem — APPROVED** [review]
Tested on TS3. The solution build passed and the mentioned lines were indeed to be found in the build log

Screenshot 2024-11-16 151709
Screenshot 2024-11-16 151821

**Review by chrisknedl — APPROVED** [review]
Works as expected on TS1.

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS3. Works as described 
image

**Review by chrisknedl — APPROVED** [review]
Code also LGTM

**Comment by eneoli** [comment]
@b-fein Regarding your comment in #9159: lgtm!

(Side note: It might be also a good idea to update the default-language to GHC2021. GHC includes certain language extensions, such as `InstanceSigs`, that are enabled by default. However, these extensions are disabled when using Haskell2010, leading to inconsistencies between Artemis and local GHC installations. But this might be a topic for a different PR.)

**Review by sawys777 — APPROVED** [review]
Tested on TS1, everything worked as expected.

**Review by flbrgit — APPROVED** [review]
Tested on TS3, everything works as expected
Screenshot 2024-11-23 223416

**Review by krusche — APPROVED** [review]

**Pull request merged**
