### PR TITLE
`Programming exercises`: Fix code editor read only state after due date

### LINKED ISSUE #6124: 'Programming exercises:' Error when trying to edit the repository in the online IDE after the due date
### Describe the bug

A student that has participated in a programming exercise is able to edit their repository after the submission due date in the online IDE. The changes cannot be saved or refreshed, since the two buttons are disabled, but after changing some lines of code the errors "One file or more could not be updated" and "You are not authorized to acess this page" appear.
When exiting the online IDE the changes are not saved, but the error "You are not authorized to acess this page" appears.

### To Reproduce

1. Paricipate in a programming exercise with the online IDE enabled before the exercise due date
2. After the due date open the IDE and start changing some lines of code
3. The two errors mentioned appear
4. Continue editing the files and the errors should appear again after some time
5. Exit the online IDE with changes that will be disregarded
6. "You are not authorized to acess this page" appears in the exercise page

### Expected behavior

After the due date the students should not be able to edit the repository, or at least the errors should not appear when doing so.
Since it says that the repository is locked it would make sense for the students to only be able to read their code without the ability to edit it.

### Screenshots

Buttons disabled and the repository being locked after the due date:
image

In the online IDE after editing some lines of code:
image

After leaving the online IDE, in the exercise page (the changes were not saved):
image

### Which version of Artemis are you seeing the problem on?

6.0.0

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

Fix #6124

### Description

The text field of the code editor is now also in read only mode (i.e. you cannot write), when the code editor does not allow writing, e.g. after the exercise due date.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 Programming Exercise with a due date

1. Log in to Artemis
2. Participate in the exercise
3. Wait until after the due date
4. Open the code editor of the participation before the due date
5. Try to edit any text in the code editor and hopefully fail

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student
3. Wait until the working time is over
4. Try to edit any text in the code editor and hopefully fail

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test

### CODE REVIEW

**Review by Strohgelaender — APPROVED** [review]
Code

**Review by laadvo — APPROVED** [review]
The online IDE is now in read-only mode after the submission due date so editing then is no longer possible. Tested on ts2.

**Review by LiaLism — APPROVED** [review]
Editing the code after the due date is not possible. Tested on ts1.

**Review by simon-hng — APPROVED** [review]
Code

**Pull request merged**
