### PR TITLE
`Development`: Use self built Bamboo, Bitbucket and Jira Docker images to support x64 and arm64 processors

### PR DESCRIPTION
**Pull request by Hialus**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

The official Atlassian docker images only support the x64 architecture. Their performance will be impaired when running them on a newer Mac with an Apple Silicon processor, as they have to run on Rosetta.
I also encountered some issues while setting these images up.
It is even worse if you want to use the provided MySQL docker-compose file. At least on my machine, Docker would fail to even start the MySQL image.
It is likely that this would also affect other arm64 based computers. And since arm64 is slowly gaining traction in the notebook market, it would be beneficial to provide a docker-compose configuration for these processors.
And since I already created the files for my own use, I wanted to share them, so other developers with Apple Silicon processors can also take advantage of this.

### Description

These changes were discussed with @Mtze.
Instead of using the official images by Atlassian, we have decided to host our own images on ghcr.io.
The Dockerfiles for these images are located in this repository: https://github.com/ls1intum/Artemis-Local-Setup-Docker and are adaptations of the official Dockerfiles that Atlassian provides.
The Dockerfiles are then built (using docker buildx) for x64 and arm64 processors and published to ghcr.io.
When the atlassian.yml is executed Docker will then automatically download the correct image for the local machine. 
If you are using a computer x64 processor nothing will change for you and your old container data will still be valid and usable.
If you are using an arm64 processor (like an M1) you will have to do nothing special but will have the benefit of natively running images.
I also added a small comment in the mysql.yml file for users with arm64 processors to use a different MySQL image that is also providing arm64 version but is 100% compatible with the normal MySQL image.

### Steps for Testing

Prerequisites:
- A Mac with M1, M1-Pro, or M1-Max processor OR a computer with an x64 processor
- Optional: A backup of your container data to be on the safe side

1. You might want to adjust the volume mappings or copy your old Bamboo, BitBucket and Jira save folders if you do not want to go through setting them up again
2. Follow the steps in the setup guide for Bamboo, BitBucket, and Jira (If you are reusing your old container data you can simply execute `docker-compose -f src/main/docker/atlassian.yml up -d` and skip the rest)
3. If you want you can take a look at the used Dockerfiles here: https://github.com/ls1intum/Artemis-Local-Setup-Docker

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

I also tested this setup on my own MacBook with an M1-Pro processor and my Windows 10 computer with an x64 processor.

### CODE REVIEW

**Review by ole-ve — APPROVED** [review]
Tested on MacBook Pro M1, works as described and way faster than emulating via Rosetta. Great work @Hialus ! 👍

**Comment by Hialus** [comment]
After talking with @Mtze I have now made some changes to how the goal of this PR is achieved. Please re-read the Description of this PR.

**Review by krusche — CHANGES_REQUESTED** [review]
I suggest using tags instead of latest

**Comment by Hialus** [comment]
> I suggest using tags instead of latest

Done. The built images are now tagged with latest and their respective version.

**Comment by Mtze** [comment]
I tested it on an x86 Mac - works fine. 

Your docker-compose file is configured to build bamboo on the local machine. I think it would be good to pull bamboo as well. We should add all the bamboo Dockerfiles to the external repository and also build the `c` and `swift` versions in CI. You can add additional flags to the special builds (e.g. `atlassian-bamboo:7.2.5_c`). This would unclutter the docker directory here. 

From my point of view, the Artemis repository should not contain Dockerfiles of external systems. I think we should only reference external systems via docker-compose, but I'm open for discussion. 
Any thoughts on this @krusche @jpbernius @sleiss?

**Comment by Hialus** [comment]
> I tested it on an x86 Mac - works fine.
> 
> Your docker-compose file is configured to build bamboo on the local machine. I think it would be good to pull bamboo as well. We should add all the bamboo Dockerfiles to the external repository and also build the `c` and `swift` versions in CI. You can add additional flags to the special builds (e.g. `atlassian-bamboo:7.2.5_c`). This would unclutter the docker directory here.
> 
> From my point of view, the Artemis repository should not contain Dockerfiles of external systems. I think we should only reference external systems via docker-compose, but I'm open for discussion. Any thoughts on this @krusche @jpbernius @sleiss?

I have just tried to also build these images, however, I am running into a problem.
When trying to build the swift image I get the following error: `ERROR: cannot replace to directory /<some temporary path by docker>/usr/share/doc/perl-base with file` in the command `COPY --from=swift:latest /usr /usr`.
This error also occurs in the original unmodified bamboo/swift/Dockerfile on my local x64 machine. So it looks like this image is currently broken and needs to be fixed first.

**Review by julian-christl — APPROVED** [review]
Tested locally on Windows 10 with AMD Ryzen 2700x CPU
No issues encountered

**Review by ole-ve — APPROVED** [review]
Works fine on my MacBook Pro M1. 👍

**Pull request merged**
