### PR TITLE
`Development`: Skip build triggers for programming exercises during file imports

### PR DESCRIPTION
**Pull request by reschandreas**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

#### Changes affecting Programming Exercises
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

This PR fixes an issue introduced by #7329 that broke two server tests. The assumption in that PR was flawed and is now fixed, we only skip the triggers for the builds if we import an exercise from a file.

### Description

Changed the name of the argument to make it clearer on how to use it and fixed it's usage.
### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with Complaints enabled

1. Run the server tests and check if all pass
2. For functionality, refer to the testing steps from #7329 

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by MaximilianAnzinger — DISMISSED** [review]
In this second I wanted to create a PR with the same fix ^^

LGTM 👍

**Comment by MaximilianAnzinger** [comment]
We still should rename `isImport` to `isFileImport`

**Comment by reschandreas** [comment]
@MaximilianAnzinger haha nice, yeah sorry for breaking it in the first place. The tests on my previous PR all went through without a problem.

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by laurenzfb — APPROVED** [review]
code LGTM

**Review by JohannesStoehr — APPROVED** [review]
Tests run trough and the parameter no longer has a confusing name.
Looks good to me

**Pull request merged**
