### PR TITLE
`General`: Align the top position of both columns in the settings menu

### PR DESCRIPTION
**Pull request by tunargs**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

This PR is related to and closes the issue [6183](https://github.com/ls1intum/Artemis/issues/6183).

### Description

The tops of the left and right columns on the settings page are not aligned in the same position, and there are some unnecessary horizontal lines on the Notifications tab under this page too. This PR aligns them correctly and removes the lines that are not needed.

### Steps for Testing

Prerequisites:
- 1 User (can be any type)

1. Log in to Artemis
2. Navigate to Settings
3. Confirm that the column alignment is correct
4. Open the Notifications tab
5. Confirm that unnecessary horizontal lines are deleted
6. Test the changes on both the dark and light scene

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Before
image

#### After
image

### CODE REVIEW

**Review by terlan98 — APPROVED** [review]
Tested on TS2. Works as expected 👍

**Comment by jakubriegel** [comment]
Tested locally. Works fine 👍🏻

**Review by jakubriegel — APPROVED** [review]
Tested locally. Works fine 👍🏻

**Review by DominikRemo — APPROVED** [review]
Code LGTM

**Review by dearjasmina — APPROVED** [review]
works as expected

**Review by laadvo — APPROVED** [review]
The code changes look good

**Review by terlan98 — APPROVED** [review]

**Pull request merged**
