### PR TITLE
`Programming Exercise`: Add solution and template participations to latest result endpoint

### PR DESCRIPTION
**Pull request by terlan98**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

The `/programming-exercise-participations/{participationId}/latest-result-with-feedbacks` endpoint is used in the Themis app to retrieve student submissions in read-only mode (without performing assessment). The response coming from this endpoint did not contain solution and template participations. This prevented tutors from viewing solution and template repositories in read-only mode in Themis. This PR fixes the problem.

### Description

Added a new `@RequestParam withTemplateAndSolutionParticipations` to `getLatestResultWithFeedbacksForProgrammingExerciseParticipation` to fetch submission and template participations.

### Steps for Testing

Prerequisites:
- 1 Exercise with at least 1 student participation
- 1 Instructor

1. Log in as Instructor
2. Navigate to Course Management 
3. Find the exercise and click on the Scores button

> Screenshot 2023-07-03 at 14 34 22

4. Open one of the results in Online Editor
5. Make sure everything works as before on the Online Editor

#### Performance Review
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [ResultService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5097-5/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service/ResultService.html) | 91% | ✅ |
| [ProgrammingExerciseParticipationResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5097-5/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/ProgrammingExerciseParticipationResource.html) | 86% | ✅ |

### Screencast

https://github.com/ls1intum/Artemis/assets/22798314/be658df4-cd6e-4253-b2f0-000c34d76fe7

Note: You do NOT need to test the Themis app. The video above just shows the effect of this PR on Themis.

### CODE REVIEW

**Review by SolizerCodes — APPROVED** [review]
Online editor still works, also what Sabrina is saying. I could reach the editor for these other repositories over another way, but not sure if that is how it is intended.

**Review by SabrinaGlatz — APPROVED** [review]
I did the testing steps on ts4. The code editor works as before. 
(I can't find a way to access the solution and the template like you showed in the demo. I'm not sure if this is a problem since it is not mentioned in the testing steps)

**Review by Strohgelaender — COMMENTED** [review]
Can you please explain why this is neeed? There already is the endpoint `/with-template-and-solution-participation` which retruns these values, can you not use this one here?

**Comment by terlan98** [comment]
> Can you please explain why this is neeed? There already is the endpoint `/with-template-and-solution-participation` which retruns these values, can you not use this one here?

The specified endpoint returns a `ProgrammingExercise` with those values, but I need a `Result` instead. 

An alternative could be to first use the `/programming-exercise-participations/{participationId}/latest-result-with-feedbacks` endpoint to get the `Result` and then `/with-template-and-solution-participation` to fetch the `ProgrammingExercise` again, but this increases the number of requests by the app (since Result already contains a Participation containing the same ProgrammingExercise)

**Comment by terlan98** [comment]
After a discussion with Lucas, I've decided to handle the problem on the client side instead, by sending 2 separate requests.

**Pull request closed without merging**
