### PR TITLE
[Feature] Fetch latest result from server after submission timed-out

### PR DESCRIPTION
**Pull request by kloessst**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation and Context

Testers noticed recently that the new result for a programming exercise does not arrive sometimes. The reason for this is still unknown. In this PR we will add a fallback mechanism, which requests the latest result from the server if the result does not arrive in time (~2 minutes) over websocket.

### Description

- Add option to request _latest-result-with-feedbacks_ to also return the submission of the result
- Add fallback mechanism, which requests the latest result from the server if the latest submission times out. 
- Check that the fetched result belongs to the latest submission
- Notify all result subscribers with the fetched result if the submissions match

### Steps for Testing

We need to use the developer console to test this feature. I will illustrate the setup using Chrome in the following steps.
Read the instructions carefully before you start testing. Timing is crucial here.

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a programming exercise (activate online code editor)
4. For a later testing step, open the Bamboo project, which contains the build plans for this exercise (e.g. by clicking on the link BASE or SOLUTION for the created exercise)
5. Start a participation for the exercise and open the online code editor
6. In the other tab open the build plan for this participation
7. Switch back to the code editor and open the developer console by pressing F12. Open the network tab
8. Solve one test case and submit. After the result is shown, wait two minutes and make sure that the request _latest-result-with-feedbacks?withSubmission=true_ does not show up in the network tab
9. Open the Network request blocking tool as seen in the screenshot below
image
10. Add the following blocking rule but do not activate the request blocking yet
image
11. Solve another test case and submit. Wait until _Building and testing_ is shown. Then activate the request blocking and refresh the browser page
--> After approximately two minutes the request _latest-result-with-feedbacks?withSubmission=true_ should show up in the network tab and the result with 2 solved test cases should be displayed.
12. Deactivate the request blocking and refresh the browser page
13. Remove the solution for one test case and submit
14. Stop the build plan for the corresponding participation in the other opened tab as seen below (might need to refresh to see the new running build)
image
--> After approximately two minutes check that the request _latest-result-with-feedbacks?withSubmission=true_ was executed. The result with two solved test cases should still be shown and the red re-trigger build button should be shown as seen below
image
15. Test that the normal case, where the result arrives as usual still works and does not trigger the fallback after ~2 minutes
 
### Test Coverage

Add two test cases for the latest-result-with-feedbacks request. Coverage should remain approximately the same.
Added a client test case which tests the submission states after a successful fallback execution. Added assertions for another test case for the case, when the fallback mechanism does not fetch the right result for the pending submission

### CODE REVIEW

**Review by airelawaleria — DISMISSED** [review]
all worked on ts1

**Review by JohannesWeiss — DISMISSED** [review]
Tested on ts1 and the calls/ actions worked as intended.

**Review by ivanchimeno — DISMISSED** [review]
Approving because the code looks correct (didn't test it yet)

**Review by EneaGore — APPROVED** [review]
Works as descibed on ts1.

**Review by LudwigWeide — DISMISSED** [review]
Works as intended on TS1.

**Review by tiffca — DISMISSED** [review]
Worked exactly as described

**Review by DenizShabani — APPROVED** [review]

**Review by krusche — CHANGES_REQUESTED** [review]
can you add client tests for the new behavior? and please remove the TODO, I added previously :)

We should also test this thoroughly to make sure that everything still works in the success case (results is retrieved normally)

**Review by stefanwaldhauser — APPROVED** [review]
Works locally! GJ

**Review by philgabr — DISMISSED** [review]

**Review by SimonEntholzer — APPROVED** [review]
Tested in testing session with @MaisiKoleni and @fde312. It worked as descirbed, and the code looks good aswell.

**Review by fde312 — DISMISSED** [review]
Tested on ts1 and everything worked fine! Code looks also good. Very good job! 🚀

**Review by MaisiKoleni — DISMISSED** [review]
Works and code looks good to me. 👍

**Comment by kloessst** [comment]
> 
> 
> can you add client tests for the new behavior? and please remove the TODO, I added previously :)
> 
> We should also test this thoroughly to make sure that everything still works in the success case (results is retrieved normally)

Which TODO do you mean?
Added client tests and added another testing step.

**Review by ivanchimeno — APPROVED** [review]
The code looks good :+1:

**Review by FrankeLukas — APPROVED** [review]
Works as advertised.

**Review by fde312 — APPROVED** [review]
Everything still works 🚀

**Review by krusche — APPROVED** [review]

**Pull request merged**
