### PR TITLE
Update server and client dependencies

### PR DESCRIPTION
**Pull request by krusche**
This PR updates some server and client dependencies

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Steps for Testing
Click through the most important functionalities and check everything is still working

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]
Tested most important features on TS1. Looks like everything is still working as intended.

**Review by ivohashamov — APPROVED** [review]
Tested on TS1, couldn't find any issues

**Review by FrankeLukas — APPROVED** [review]
Tested a bit on TS1, and works too when locally running.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3. Most important functions like exercise creation and participation work normal. No errors found.

**Review by tobiasjungmann — APPROVED** [review]
Tested on Ts1. All the standard functions I have checked worked as expected.

**Pull request merged**
