### PR TITLE
`General`: Ensure manually created users can log in

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
When manually creating users as admin, the admin can select from a few roles the user can have. By default none of the options is selected. However, to be able to construct a valid token for login the user needs to have at lease one role. This is typically the STUDENT/USER role that has no special permissions.

### Description
Updated the user creation logic to always include at least this role if no other ones have been defined for the user.

### Steps for Testing

Prerequisites:
- 1 Admin

1. As admin, go to the user management page.
2. Create a new user. You can select a set of roles for the new user.
3. Select none of the roles, the newly created user should still be able to log in to Artemis afterwards.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|-----------------------------:|
| UserCreationService.java | 94% | ✅                           |

### CODE REVIEW

**Review by terlan98 — APPROVED** [review]
Tested on TS5. I was able to log in with a new user that did not have any roles specified during creation 👍

**Review by JohannesStoehr — APPROVED** [review]
Code looks good to me

**Review by Strohgelaender — APPROVED** [review]
code lgtm

**Review by chrisknedl — APPROVED** [review]
Tested on my local setup. Everything worked as described above.

**Pull request merged**
