### PR TITLE
`Assessment`: Show number of filtered entries in scores table

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

When instructors take a look at the scores table and especially the filters there, they want to know how many scores are affected by each filter and how many scores there are in total. The scores table should show this information in an clear way to the user.

### Description

Displays next to each filter the number of scores that fit into this filter. Additionally shows how many scores there are in total when some are filtered out

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise with some scores

1. Log in to Artemis
2. Participate with some students or find an exercise with different participations. Some successful, some with errors, some with a build failure or a locked assessment, ...
3. Go to the scores table of that exercise and look at the filter.
4. Make sure that the number displayed next to the filter is correct.

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [exercise-scores.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5061-1/artifact/shared/Coverage-Report-Client-Tests/app/exercises/shared/exercise-scores/exercise-scores.component.ts.html) | 88.23% | ✅ |

### Screenshots

Bildschirmfoto 2023-06-29 um 10 38 33

### CODE REVIEW

**Review by SolizerCodes — APPROVED** [review]
Tested on ts5, works there 👍

**Review by dakennguyen — APPROVED** [review]
tested on ts1, works well with different results!

**Review by MaximilianAnzinger — APPROVED** [review]
Code LGTM

**Review by Hialus — APPROVED** [review]
Code looks good to me.

**Review by Mtze — APPROVED** [review]

**Pull request merged**
