### PR TITLE
`Communication`: Fix an issue when loading more than 50 messages

### PR DESCRIPTION
**Pull request by pellumbbaboci**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

When a conversation contains more the 50 messages (posts) and you try to fetch the messages you get internal server error: 

```
2023-05-15 18:03:40.905 ERROR 85204 --- [nio-8080-exec-7] o.z.problem.spring.common.AdviceTraits   : Internal Server Error

org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.QueryException: query specified join fetching, but the owner of the fetched association was not present in the select list [FromElement{explicit,not a collection join,fetch join,fetch non-lazy properties,classAlias=generatedAlias1,role=de.tum.in.www1.artemis.domain.metis.Post.answers,tableName=answer_post,tableAlias=answers1_,origin=post post0_,columns={post0_.id,className=de.tum.in.www1.artemis.domain.metis.AnswerPost}}] [select distinct count(distinct generatedAlias0) from de.tum.in.www1.artemis.domain.metis.Post as generatedAlias0 left join fetch generatedAlias0.answers as generatedAlias1 left join fetch generatedAlias1.reactions as generatedAlias2 left join fetch generatedAlias0.reactions as generatedAlias3 left join fetch generatedAlias0.tags as generatedAlias4 where generatedAlias0.conversation.id=7L]; nested exception is java.lang.IllegalArgumentException: org.hibernate.QueryException: query specified join fetching, but the owner of the fetched association was not present in the select list [FromElement{explicit,not a collection join,fetch join,fetch non-lazy properties,classAlias=generatedAlias1,role=de.tum.in.www1.artemis.domain.metis.Post.answers,tableName=answer_post,tableAlias=answers1_,origin=post post0_,columns={post0_.id,className=de.tum.in.www1.artemis.domain.metis.AnswerPost}}] [select distinct count(distinct generatedAlias0) from de.tum.in.www1.artemis.domain.metis.Post as generatedAlias0 left join fetch generatedAlias0.answers as generatedAlias1 left join fetch generatedAlias1.reactions as generatedAlias2 left join fetch generatedAlias0.reactions as generatedAlias3 left join fetch generatedAlias0.tags as generatedAlias4 where generatedAlias0.conversation.id=7L]
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:374)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:235)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
	at jdk.proxy3/jdk.proxy3.$Proxy461.findAll(Unknown Source)
	at de.tum.in.www1.artemis.repository.metis.ConversationMessageRepository.findMessages(ConversationMessageRepository.java:39)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:87)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
	at jdk.proxy3/jdk.proxy3.$Proxy461.findMessages(Unknown Source)
	at de.tum.in.www1.artemis.service.metis.ConversationMessagingService.getMessages(ConversationMessagingService.java:134)
	at de.tum.in.www1.artemis.service.metis.ConversationMessagingService$$FastClassBySpringCGLIB$$9e7662c8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at de.tum.in.www1.artemis.aop.logging.LoggingAspect.logAround(LoggingAspect.java:81)
	at jdk.internal.reflect.GeneratedMethodAccessor172.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at de.tum.in.www1.artemis.service.metis.ConversationMessagingService$$EnhancerBySpringCGLIB$$adc9bb1d.getMessages(<generated>)
	at de.tum.in.www1.artemis.web.rest.metis.ConversationMessageResource.getMessages(ConversationMessageResource.java:77)
	at de.tum.in.www1.artemis.web.rest.metis.ConversationMessageResource$$FastClassBySpringCGLIB$$340e2e9d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```
### Description

The issue lies in the count query's utilization of a left join fetch, which is not functioning as intended. Instead, it should employ a regular left join.

In this PR the `count query` is overrode. 

### Steps for Testing

Prerequisites:
- 2 users
- 1 course (Messages feature should be enabled)

1. Log in to Artemis
2. Navigate to messages tab of a course
3. Start messaging with the other user. 
4. Send more then 50 messages (a conversation should have more then 50 messages)
5. There shouldn't be any internal server error

#### Performance Review
- [ ] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by eceeeren — APPROVED** [review]
Tested on ts2, works as expected

**Review by terlan98 — APPROVED** [review]
Tested on TS1 with a group conversation containing 57 messages. Did not encounter any server errors.

**Review by dakennguyen — APPROVED** [review]
tested on ts3, works as expected with 60 messages in total

**Comment by asliayk** [comment]
tested on t5, works for 50+ messages without any server error

**Review by asliayk — APPROVED** [review]
tested on ts5, works for 50+ messages without any server error

**Review by rriyaldhi — APPROVED** [review]
Tested manually on TS4 and test looks good.

**Review by tobias-lippert — APPROVED** [review]
Tested on ts4. Sending over 50 messages in a channel worked without any issues.
Test code looks good.

**Review by frederik-kt — APPROVED** [review]
Tested on TS4. Works fine for 50+ messages.

**Review by RY997 — APPROVED** [review]
Tested on ts1, worked well.

**Comment by pellumbbaboci** [comment]
> Code changes look good to me. Is the problem with the left join vs. left join fetch a bug in jpa or does this come from somewhere else?

Yes, might be a bug in jpa

**Review by krusche — APPROVED** [review]

**Pull request merged**
