### PR TITLE
`Quiz exercises`: Make edit footer sticky

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
As the quiz edit is quite different from the other exercises edit views, it also has another footer. Its footer is still not sticky, this PR fixes this and makes the quiz footer sticky.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Edit, Re-evaluate, export quiz
3. Verify that the footer is sticky not fixed and looks fine

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
image
image

## Summary by CodeRabbit

- **Style**
	- Improved the visual layout and user interaction of the quiz management interface by adjusting the positioning and styling of the quiz editing footer across various components.

- **Refactor**
	- Enhanced the structure and readability of the HTML within the quiz editing sections, leading to a more intuitive user experience.

### CODE REVIEW

**Review by pzdr7 — APPROVED** [review]
Tested on TS2. Looks good to me

**Review by AntonGeTUM — APPROVED** [review]
Manually tested, works as expected

**Review by rstief — APPROVED** [review]
code 👍

**Review by laurenzfb — APPROVED** [review]
tested on ts2, sticky footer is sticky

**Review by mateusmm01 — APPROVED** [review]
Tested on ts2. LGTM

**Review by pzdr7 — APPROVED** [review]
Re-tested on TS2. Looks good to me

**Pull request merged**
