### PR TITLE
`General`: Fix breadcrumb routing from teams page + add teams button to programming exercise details

### LINKED ISSUE #4653: Teams endpoint has wrong link (breadcrumbs not working and teams button missing)
### Describe the bug

In Artemis, all exercises except Quizzes (Programming, Modelling, Text and File Upload exercises) have two solving modes - Individual and **TEAM**. 

When creating any of these in **team mode**, there are 2 kinds of problems. Each of these is, I believe, caused by `/teams` endpoint of the exercise and it makes sense to fix this in one PR. That's why I'm reporting both bugs in one issue.

**1. problem:** Breadcrumb for the exercise page is not working when on `/teams` endpoint. 
**2. problem:** When on the exercise's page in course management, there is no Teams button.

### 1. problem (explanations and screenshots):

As you can see in the first two screenshots (1 and 2), the link of the teams' endpoint is `https://artemis.ase.in.tum.de/course-management/{courseId}/exercises/{exerciseId}/teams`, and the link of the breadcrumb is `https://artemis.ase.in.tum.de/course-management/{courseId}/exercises/{exerciseId}`. 

This causes a problem because the link of the breadcrumb is not a valid link and therefore breadcrumb is not clickable / is not working.

In screenshot 3, you can see how it should be and how it's, e.g. for `/submissions` endpoint. Thus, the teams' endpoint should be changed to `https://artemis.ase.in.tum.de/course-management/{courseId}/{programming/text/file-upload/modeling}-exercises/{exerciseId}/teams` and the links of the breadcrumbs should also contain exercise identifier **(programming/text/file-upload/modeling)** because that is the valid endpoint for the exercise.

Screenshot 1:
teams_breadcrumb_text_exercise

Screenshot 2:
teams_breadcrumb_programming_exercise

Screenshot 3: 
submission_breadcrumb

### 2. problem (explanations and screenshots):

When a user navigates to Course Management and Exercises, every Teams exercise has an appropriate button `Teams` (screenshot 5). But, if the user goes to the exercise page, the `Teams` button does not exist, which can be seen in screenshot 6 (only Programming exercises are having this problem). IMO, it should exist and the Instructor should be able to see the teams page from the exercise page. Both of these buttons for all types of exercises should redirect the user to the `/teams` endpoint that has been fixed in the first part of this issue.

Screenshot 5:
existing_teams_button

Screenshot 6:
exercise_page

### To Reproduce

1. Log in to Artemis as an Instructor
2. Go to 'Course Management'
3. Go to the 'Exercises' of some course
4. Create a new Programming exercise (Text, File Upload, and Modelling exercises are having just the issue with the breadcrumbs, the buttons are being shown there on both pages).
5. Select **Team** mode while creating an exercise.
6. Find the created exercise in the exercise list and see the Teams button.
7. Click right-click on the Teams button and open it in the new tab. The new tab will open the `/teams` endpoint page. 
8. In this tab, click on the exercise name and open the exercise page.
9. Observe that there is no `Teams` button on this page.
10. Now switch to the previously opened tab and try to click on the breadcrumb of the exercise (the one with the exercise name and before '> Teams'.
11. Observe that clicking on the breadcrumb does absolutely nothing.
12. Try opening the same breadcrumb in the new tab.
13. Observe that you will land 'nowhere'.

### Expected behavior

- When on the exercise page in steps 8 and 9 from above, `Teams` button should exist. Clicking on that button should redirect the user to the `/teams` endpoint. On this page, the breadcrumb of the exercise page should be clickable and redirect user back to the exercise page.

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Chrome, Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Fixes #4653.

### Description

- Modified the breadcrumb generation code to fetch the exercise by id and include the type in the breadcrumb URI for backlinks to exercise detail pages
- Added Teams button to the programming exercise buttons on the detail page if the exercise is in team mode

### Steps for Testing

Prerequisites:
- 1 Programming Exercise in Team Mode
- 1 Instructor

1. Navigate to the Details Page of the Exercise. The Teams button should be shown in the second line of buttons.
2. Click the button. You should be redirected to the teams list.
3. Click the breadcrumb link with the name of the exercise. The link should point to .../programming-exercises/... instead of .../exercises/... and forward you to the exercise details page again.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

### Screenshots

grafik

https://user-images.githubusercontent.com/23171488/161262213-6b7ae436-a148-4f0e-8bd0-5f587cdb907e.mov

### CODE REVIEW

**Review by ole-ve — APPROVED** [review]
Tested on TS2, works as described.
Code changes also look good to me

**Review by Dominik-Weinzierl — APPROVED** [review]
Tested on TS1 - works as expected :+1:

**Review by mallgaier — APPROVED** [review]
Works as expected, good job 👍

**Review by willergeorg — APPROVED** [review]
Code lgtm 👍

**Pull request merged**
