### PR TITLE
`Assessment`: Don't allow activating presentations if no presentation scoring is set

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [ ] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
 
### Motivation and Context
A conversation on Slack led me to an issue where an instructor activated presentations for an exercise, but then was unable to grade the presentations since the input was missing. This was caused by them not having setup the presentation mode in Artemis before. 

### Description
You can now only activate presentations for an exercise if the course has a presentation scoring setup.

The issue was caused by the presentation score value being undefined and `undefined !== 0 => true `.

### Steps for Testing
1. Use a course where no presentation scoring is setup (default behaviour and check that)
 - The exercise overview (course -> exercises) has no presentation column.
 - When editing / creating an exercise the presentation checkbox is not visible.
2. Setup presentations via course -> score -> grading key. Now verify that:
- The exercise overview (course -> exercises) shows if an exercise has presentations active.
 - When editing / creating an exercise the presentation checkbox is visible and works.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
	- Enhanced conditional rendering for presentation scores across various exercise components, allowing for broader evaluation of truthy values, improving UI flexibility.
  
- **Bug Fixes**
	- Improved robustness of the presentation score logic, preventing potential runtime errors and ensuring correct display of UI elements based on valid score values. 

- **Refactor**
	- Simplified conditional checks in multiple components for better readability and maintainability.

### CODE REVIEW

**Review by pzdr7 — APPROVED** [review]
The code looks good 👍

**Review by coolchock — APPROVED** [review]
tested on ts4, works as expected

**Review by Jan-Thurner — APPROVED** [review]
Tested on TS4, works as expected. Code LGTM.

**Review by SimonEntholzer — APPROVED** [review]
Also tested on TS4, breadcrums show  up correctly in the repository view :+1:

**Pull request merged**
