### PR TITLE
[Tests] [Orion] Improve Orion Coverage

### PR DESCRIPTION
**Pull request by MDK5**
### Checklist
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.

### Motivation, Context and Descrption
This a follow-up to #3530, providing the missing tests from there as well as adding tests for other Orion functionality.

### Steps for Testing
1. Review code
2. Verify coverage improved

### Test Coverage
exercise-assessment-dashboard.component.ts 78.8% -> 80.4%
programming-submission.service.ts 73.4% -> 78.8%
programming-exercise.component.ts 73.0% -> 77.5%

### CODE REVIEW

**Review by ivanchimeno — APPROVED** [review]
Looks good :+1:

**Review by lschlesinger — APPROVED** [review]
Looks good, coverage improved!

**Review by ivohashamov — APPROVED** [review]
Code looks good

**Review by SimonEntholzer — APPROVED** [review]
code looks good :+1:

**Review by imstreetspirit — APPROVED** [review]
looks good

**Review by ndricimrr — APPROVED** [review]
Code Looks good 👍

**Review by FrankeLukas — APPROVED** [review]

**Pull request merged**
