### PR TITLE
[Bug fix] Fix button layout in example submissions dashboard

### PR DESCRIPTION
**Pull request by Olimbia23**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

This PR fixes the layout of "_Create Example Submission_" button in the example submissions dashboard.

### Description

After updating dependencies in this PR [3470](https://github.com/ls1intum/Artemis/pull/3470), I noticed that "_Create Example Submission_" button's layout had changed. 
I fixed it by placing the button as it was before in this PR [3443](https://github.com/ls1intum/Artemis/pull/3443) 

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Management
3. Pick a course
4. Click on exercises
5. Click on example submissions button for a certain exercise

### Screenshots

Before: 
Screenshot 2021-06-20 at 7 37 56 PM

After: 
Screenshot 2021-06-20 at 7 48 45 PM

### CODE REVIEW

**Review by imstreetspirit — APPROVED** [review]
tested on local. looks good to me

**Review by katjanakosic — APPROVED** [review]
Works as described 👍

**Review by cremertim — APPROVED** [review]
works on ts1

**Review by sinangunduz — APPROVED** [review]
tested on ts1, works as expected

**Review by argertboja — APPROVED** [review]
Looks good on TS1 👍🏼

**Review by ivanchimeno — APPROVED** [review]

**Review by jpbernius — APPROVED** [review]

**Pull request merged**
