### PR TITLE
`Development`: Improve client code quality for learning paths

### PR DESCRIPTION
**Pull request by JohannesWt**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

This PR cleans up the client side code of the learning path feature.

### Description

- Switch to OnPush Change detection
- remove unnecessary imports and import only needed components/modules
- make effects more predictable for the future by using the untracked function

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 student
- at least 1 competency with at least 2 learning objects connected (exercise and/or lecture unit)

1. Log in to Artemis
2. Navigate to the learning path student page
3. verify that the navigation/showing the competencies/opening the competency graph still works as expected
4. verify that all translations are there
5. navigate to the learning path instructor page
6. verify that all the sections (state, learning paths table, analytics) still work as expected
7. verify that the pagination works for the learning paths table
8. verify that all transactions are there

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

unchanged

### Screenshots

unchanged

## Release Notes

- **New Features**
  - Introduced `ChangeDetectionStrategy.OnPush` across multiple components to enhance performance.
  - Added `TranslateDirective` to support translation features in various components.
  - Implemented pagination limit in the `ngb-pagination` component for better user navigation.

- **Bug Fixes**
  - Updated error handling in tests to respond to `HttpErrorResponse` instead of `EntityNotFoundError`.

- **Improvements**
  - Simplified property declarations and imports for better readability and maintainability.
  - Enhanced control flow in components by using `untracked` for effect functions, optimizing reactive behavior.

- **Chores**
  - Removed unused imports and modules to streamline component dependencies.

### CODE REVIEW

**Review by HawKhiem — APPROVED** [review]
Tested on TS1. Everything works as described

**Review by florian-glombik — APPROVED** [review]
Approve code

**Review by kevinfischer4 — APPROVED** [review]
Tested on TS1, everything works as expected.

**Review by raffifasaro — APPROVED** [review]
code LGTM

**Review by sachmii — APPROVED** [review]
Tested on TS5, works as expected.

**Review by JerroyTan — APPROVED** [review]
[Tested on TS3]
Functionalities work as described.

suggestion: maybe add sorting/filtering in the learning paths table where we have the pagination?

**Review by MaximilianAnzinger — APPROVED** [review]
Maintainer approved

**Pull request merged**
