### PR TITLE
`Lectures`: Fix lecture attachment updates with the same name

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
The editing of lecture attachment units was broken. If you uploaded a file and replaced it in the edit mode with a file with the same name, the file was not possible to be downloaded anymore.

### Description
This PR fixes this issue by adjusting an equality check of paths, doing a workaround for buggy FileUtils function and deleting the cache correctly.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Lecture

1. Log in to Artemis
2. Navigate to Lecture Units
3. Create Attachment Unit
4. Edit the Attachment Unit and upload a different file with the same filename as before
5. Save
6. Verify that the attachment ist still downloadable

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by julian-christl — APPROVED** [review]
Code looks good, thanks for the fix

**Review by reschandreas — APPROVED** [review]
tested locally, works as expected. code lgtm 👍🏻

**Review by laurenzfb — APPROVED** [review]
Tested on Ts3. Worked as expected. Code also LGTM!

**Review by vinceclifford — APPROVED** [review]
Tested on ts2, works as expected

**Pull request merged**
