### PR TITLE
`Development`: Use posts for plagiarism cases

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).

### Motivation and Context

#7437 made the client use /messages endpoints instead of /posts endpoints in every case. However, for plagiarism notifications, the /posts endpoints have to be used.

### Description

The client has been adapted and now uses /messages only for messaging/communication related use cases and not plagiarism cases.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 course where all 3 users are a member of

Need to deploy on legacy ts1 or ts0 (for mail support)

1. Generate a plagiarism case:
      1. Create a text exercise with the instructor with a due date in the future.
      2. Participate with **two** students in the exercise and submit the same text of at least 100 characters. You can use [loremipsum.de](https://loremipsum.de).
      3. Wait for the due date or set it to "now" with the instructor
      4. With the instructor, open the exercise under course-management (click the exercise title or id). Then follow the steps Click "Check plagiarism" -> Click "Detect plagiarism" -> Select the result on the left -> Click "Confirm"
2. Assess the plagiarism case:
      1. With the instructor, navigate to "Assessment", and click the "Plagiarism Cases" button. Select one of the students. On the next page click "Notify student" and send the post.
      2. With the student, navigate to the same URL, but replace "course-management" with "courses".
      3. Confirm that you can send a reply as the student
3. Check that the communication/messaging feature still works:
      1. Navigate to the communication tab and check that you can still reply to messages
      2. Navigate to the messages tab and check that you can still send messages and reply to them
      3. Navigate to a lecture and exercise details page and check that you can still send messages and reply to them

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Same as develop

### Screenshots

No UI changes

### CODE REVIEW

**Review by MaximilianAnzinger — DISMISSED** [review]
Code LGTM 👍

**Review by Jan-Thurner — APPROVED** [review]
Tested on test server 1. Works as expected

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by dearjasmina — APPROVED** [review]
reviewed during the testing session

**Review by Kroko-fant — APPROVED** [review]
tested in a testing session on ts 1 worked well!
code also looks good to me

**Pull request merged**
