### PR TITLE
`Assessment`: Fix the loss of submission text due to overlapping manual text blocks

### LINKED ISSUE #6903: `Text Exercises`, `Assessment`: Overlapping manual text blocks lead to the loss of some student text
### Describe the bug

While assessing a text exercise, sometimes an inline feedback assigned to an arbitrary text block leads to the loss of some part of the text. This happens when the user has previously created and deleted another inline feedback assigned to a block overlapping with the block of the new inline feedback. 

### To Reproduce

1. Start assessing a text exercise
2. Select a specific portion of the text, by holding the `alt/option` key. Let's call the selected range r1...r2
3. Add some feedback and save
4. Refresh the page
5. You should see your feedback
6. Delete the feedback
7. Again, hold `alt/option` key to select a different range of text. BUT, make sure that the new range overlaps with r1...r2
8. Add some feedback and save
9. Refresh the page

### Expected behavior

Text content should not be affected

### Screenshots
After adding the first feedback:
Screenshot 2023-07-14 at 18 41 59

After deleting the first feedback and adding another overlapping feedback:
Screenshot 2023-07-14 at 18 44 50
As you can see, the word "Mars" has disappeared

### Which version of Artemis are you seeing the problem on?

6.3.3

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

###### NOTE: the output and the screenshots are captured in different scenarios. Therefore, the content of the blocks and feedbacks are different compared to the screenshots.

```shell
text-assessment-base.component.ts:95 Overlapping MANUAL Text Blocks! 

block: {id: '2eb1a8b013de41e43ff42715b563def05de6bd57', text: 'grace our solar system, Mars, the fourth', startIndex: 32, endIndex: 72, type: 'MANUAL'}
deletable: true
feedback: {id: 333071, detailText: 'goooood :)', hasLongFeedbackText: false, reference: '2eb1a8b013de41e43ff42715b563def05de6bd57', credits: 1, …}
highlighted: false
selectable: true


block: {id: '528c2a895af3a1942df863aa8ba9fa3e54c551b9', text: 'our solar system,', startIndex: 38, endIndex: 55, type: 'MANUAL'}
deletable: true
feedback: undefined
highlighted: false
selectable: true
```

### PR DESCRIPTION
**Pull request by terlan98**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context
Closes #6903 

### Description
Removed the console error for the case when manual text blocks were overlapping. Instead, added some code to handle the case as follows: determine the block that has a feedback assigned to it and add a new text block, if needed, to ensure that the block of the new feedback does not hijack some of the existing text.

### Steps for Testing
Prerequisites:
- 1 Text Exercise with a submission ready for assessment
- 1 Tutor

1. Log in to Artemis as Tutor
2. Go to Course Management -> Assessment Dashboard -> Exercise Dashboard of the text exercise
5. Start an assessment
6. Select a specific portion of the text, by holding the alt/option key. Let's call the selected range [r1, r2]
7. Add some feedback and save
8. Refresh the page
9. Verify that you see your feedback
10. Delete the feedback
11. Again, hold alt/option key to select a different range of text. BUT, make sure that the new range overlaps with [r1, r2]
12. Add some feedback and save
13. Refresh the page
14. Verify that you can see your new feedback

#### Performance Review
- [x] I confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [text-assessment-base.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5187/latest/artifact/shared/Coverage-Report-Client-Tests/app/exercises/text/assess/text-assessment-base.component.ts.html) | 84% | ✅ |

### CODE REVIEW

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Can you also add a test for this bug?

**Review by jakubriegel — APPROVED** [review]
Code with test LGTM 👍🏻 

Works on ts4

**Review by JohannesStoehr — APPROVED** [review]
Thanks for adding the test. Code looks good to me 👍

**Review by tobias-lippert — APPROVED** [review]
tested on ts4. Works as described.

**Review by pal03377 — APPROVED** [review]
Code looks good to me 🎉  I also tested it again on TS4 to get a better feel of what the code is doing.

**Review by maximiliansoelch — APPROVED** [review]

**Pull request merged**
