### PR TITLE
`Quiz exercises`: Disable save quiz button if no changes are present

### LINKED ISSUE #5159: Quiz exercise - The save button is clickable even without changes
### Describe the bug

The save button is clickable even without changes, and when you try to go to another page (e.g. course management) the warning message is displayed. 

### To Reproduce

1. Go to Course Management
2. Click on any course
3. Go to Exercise
4. Go to quiz exercises
5. Click on create a new quiz exercise
6. Import some questions 
7. Click in save
8. Verify that the bottom says unsaved changes and the save button is clickable. But the top part says that the changes were saved (screenshot 1).
9. Try to go to another page e.g. course management or course overview
10. Verify that the warning message is deployed (screenshot 2 and screenshot 3).

### Expected behavior

The changes are already saved, so the save button should not be clickable until a new change and the message on the bottom should not say "unsaved changes". 
Going to other pages should be possible without the warning message. 

### Screenshots

Screenshot 1: 
image

Screenshot 2:
image

Screenshot 3: Also in Safari
image

### What browsers are you seeing the problem on?

Chrome, Safari

### Additional context

_No response_

### Relevant log output

_No response

https://user-images.githubusercontent.com/88991954/172339824-be60d851-1905-46bd-92b7-2b83fa7b112c.mov

_

### PR DESCRIPTION
**Pull request by manuelmanso**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Close #5159. Also a small cleanup of the quiz-exercise-detail-component which had some old and unused code/variables.

### Description

Fixed the issue where the 'saved entity' was not created correctly and therefore the 'Save' button would always be enabled.
Also fixed the issue where even after undoing changes the 'Save' button would still be enabled. Remove the `initCompleted` and the 'entity' variables which aren't used anymore.

There are some cases where making a change and then undoing it will still cause the 'Save' button to be enabled. These are:
- adding/removing categories
- changing the Batch mode type
- changing the content/text of any of the questions

(This can be handled in a future PR if the effort is considered worth it.)

### Steps for Testing

You can just follow the steps in #5159. Additionally, you can test the other fixes:

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to the exercises page for a course
4. Click 'Edit' for quiz exercise (if there's no quiz then create one first)
5. Check that the 'Save' button is disabled at first
6. Check that changing some fields enables the 'Save' button
7. Check that after undoing the changes done in the previous step the 'Save' button is disabled again (There are some exceptions described above)

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Branch | Line |
|------------|-------:|-----:|
| quiz-exercise-detail-component.ts | 80% | 95% |

### CODE REVIEW

**Review by SimonPaul02 — APPROVED** [review]
Tested on TS1, works as described

**Review by yuling-sun — APPROVED** [review]
Tested on TS1. Works as described.

**Review by jbllhff — APPROVED** [review]
tested on ts2, looks good!

**Review by babyygemperor — APPROVED** [review]
Tested on ts2, works as described

**Review by luisa-we — APPROVED** [review]
Tested on TS2, works as described

**Review by MetinLamby — COMMENTED** [review]
tested on ts2, works well. however, when editing and removing the edit of the content of a question (eg. MC question content), the save button remains enabled

**Review by nairaarnez — APPROVED** [review]
Tested in TS1, the save button is disabled as expected

**Review by alaraozdenler — APPROVED** [review]
Tested on ts1, works as described

**Review by bassner — APPROVED** [review]
Code 👍

**Review by Santia-go — APPROVED** [review]
Tested on TS1. It works as expected. 
During the creation of quizzes, the save button is unavailable if there are no changes. However, if I open the quiz to edit, by default (immediately) it shows unsaved changes. 
If you can fix this in this PR would be super. 
I approved anyway because you solved the issue that open this PR.

**Comment by manuelmanso** [comment]
> tested on ts2, works well. however, when editing and removing the edit of the content of a question (eg. MC question content), the save button remains enabled

As described in the 'Description' section, there are still some cases where the 'Save' button will still be enabled after making changes and reverting them, and changing the content of a question is one of them

**Comment by manuelmanso** [comment]
> Tested on TS1. It works as expected. During the creation of quizzes, the save button is unavailable if there are no changes. However, if I open the quiz to edit, by default (immediately) it shows unsaved changes. If you can fix this in this PR would be super. I approved anyway because you solved the issue that open this PR.

I can't reproduce this. When editing an existing quiz, the Save button starts disabled and only becomes enabled after making changes.

**Pull request merged**
