### PR TITLE
`Development`: Use signals in video unit form component

### PR DESCRIPTION
**Pull request by florian-glombik**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
This PR introduces signals, and fixes code smells in components used for editing and updating lectures. This is a preparation for [Lectures: Add status bar to lecture creation and edit mode #9655](https://github.com/ls1intum/Artemis/pull/9655) and aims to keep #9655 at a manageable size of changes.

### Description
- Fixed code smells
- Introduced signals in `video-unit-form.component.ts` (and thereby removed method calls in the template)

### Steps for Testing
Prerequisites:
- 1 Instructor
- Deployed to a testserver with competencies enabled, there is a known bug that lecture units in guided mode can only be added when a competency is selected (will not be fixed as the guided mode is about to be removed with #9655)

1. Navigate to the Instructor lecture view (creating and editing)
2. Click `Units` > `Video` to create a text lecture unit, verify the behavior is the same as on develop
3. Verify Editing the video Unit works as on develop
4. Create a Lecture in the guided mode, where you add a video Unit (make sure to select a competency to prevent known bug!)
5. Verify Adding a video lecture unit works 
6. Verify the cancel button works for the video lecture unit

This is a refactoring PR that does not add functionality, so the behavior should not change in comparison to the develop branch.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
useSignalsInVideoUnitFormComponent-9692

## Release Notes

- **New Features**
  - Enhanced form submission logic to improve validation before submission.
  - Updated cancel button functionality for better user experience.

- **Bug Fixes**
  - Improved handling of form state, ensuring accurate reflection in the UI.

- **Tests**
  - Streamlined input handling in test cases for better alignment with Angular's input binding.

These updates enhance the overall usability and reliability of the video unit form component.

### CODE REVIEW

**Comment by florian-glombik** [comment]
@anditurdiu https://github.com/ls1intum/Artemis/pull/9692#pullrequestreview-2419643747 Which failing client test are you referring to? https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS7337-TSTEST-1

The GitHub Action tasks are flaky, as far as I know that's why they did not replace the Bamboo pipelines yet.

**Review by az108 — APPROVED** [review]
@florian-glombik alright then its fine from my side if its flaky 👍

**Review by JohannesWt — DISMISSED** [review]
Code 👍

**Review by sachmii — DISMISSED** [review]
Tested on TS2, everything works fine.

**Review by kevinfischer4 — DISMISSED** [review]
Tested on TS2, works as described.

**Review by az108 — APPROVED** [review]

**Review by kevinfischer4 — APPROVED** [review]

**Review by sachmii — APPROVED** [review]

**Review by JohannesWt — APPROVED** [review]
Reapprove 🇹🇭

**Pull request merged**
