### PR TITLE
`Development`: Update to Angular 17

### PR DESCRIPTION
**Pull request by krusche**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
#### Changes affecting Programming Exercises
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Description

Updated Artemis Client to Angular 17.

### Steps for Testing

The Angular 17 update introduces a lot of changes. All parts of the Artemis Client need to be tested, especially regarding the UI.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by MaximilianAnzinger — APPROVED** [review]
For Competencies & Learning Paths everything works fine 👍

**Review by Strohgelaender — CHANGES_REQUESTED** [review]
The PE-diff-view is broken and does not show any content.
grafik

**Review by aplr — COMMENTED** [review]
Did a code review, looks good and could not find apparent issues.

One question, why is it not possible to add the `FontAwesomeTestingModule` to the `ArtemisTestingModule` so it does not have to be added everywhere? Guess you already checked that option, just want to understand it.

**Comment by valentin-boehm** [comment]
> One question, why is it not possible to add the `FontAwesomeTestingModule` to the `ArtemisTestingModule` so it does not have to be added everywhere? Guess you already checked that option, just want to understand it.

@aplr You are right, I moved the `FontAwesomeTestingModule` to the `ArtemisTestModule` 👍

**Review by Strohgelaender — APPROVED** [review]
I tested participating in exercises as a student and the general execise managment / assessment functionality, I did not find any UI issues.

**Review by rriyaldhi — APPROVED** [review]
Tested Quiz and Communication.

**Review by vinceclifford — APPROVED** [review]
Tested all typed of exercises (text, models, programming, etc.)as well as participating in exams

**Review by lennart-keller — APPROVED** [review]
Tested messaging and exercise participation. Couldn't see any UI issues.

**Review by mateusmm01 — APPROVED** [review]
Tested basic functionalities, as well as creating and participating in exams, and all types of exercises in testing session. No UI issues seen. Looks good!

**Review by valentin-boehm — APPROVED** [review]
Extensively tested the exam mode, no issues found

**Pull request merged**
