### PR TITLE
Use JDK16 for Java programming exercises

### PR DESCRIPTION
**Pull request by krusche**
Update the Java Programming Exercise Template to JDK16

### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.

### Steps for Testing
1. Create a programming exercise (with and without SCA)
2. Participate in it and check if everything is working correctly

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
The changes should be sufficient to conduct Java 16 exercises on Artemis

**Comment by stefanwaldhauser** [comment]
image
The gradle task :spotlessApply does not seem to work any more with java 16

**Review by stefanwaldhauser — CHANGES_REQUESTED** [review]
See comment above. Have some problems running the gradle scripts with Java 16. Maybe I have a wrong configuration on my machine

**Review by krusche — COMMENTED** [review]
All changes look good. We'll merge it and if something comes up, we'll create a follow up PR

**Pull request merged**
