### PR TITLE
[Bugfix] Displaying columns for small screens in overviews

### PR DESCRIPTION
**Pull request by FlorianGlombik**
### Checklist
- [x] I tested *all* changes and *all* related features (admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Problem
The ID Title disappears when the exam overview/student exam page is displayed on small screens.
IdNotDisplayedProperly

### Description

Always display the ID title by removing the `d-none` class.

I did not understand the reasoning behind adding the `d-none` class, feel free to add a comment in case I might miss why this is valuable.
My knowledge is limited to using the display property [hide for increased accessibility ](https://www.nomensa.com/blog/how-improve-web-accessibility-hiding-elements)- I am not aware of further usages which might apply here? 

### Steps for Testing

1. Create an Exam and participate with one student
2. Navigate to the student exam view (_Student Exams_ | _View_)
3. Shrink the screen and make sure that the ID title is always displayed
4. Repeat step 3 for the _Exam Management_ overview
5. Repeat step 3 for the _Exercise Overview_ (programming exercises and modeling exercises were modified here - you might notice another problem here, an issue for that does already exist https://github.com/ls1intum/Artemis/issues/3993 and respective PR https://github.com/ls1intum/Artemis/pull/3909)
6. Repeat step 3 for the _Exam Exercise Group Overview_

### Screenshots

Fixed version:
IdNotDisplayedProperlyFixed

### Review Progress
- Code Review
  - [x] Review 1
  - [x] Review 2
- Manual Tests
  - [x] Test 1
  - [x] Test 2

### CODE REVIEW

**Review by Malyuk-A — COMMENTED** [review]
Tested on TS3.
It works as described for the student exam view.

What do you mean by Exam Management overview? 
If you mean this part then it does not work sadly. 
bug

**Comment by FlorianGlombik** [comment]
https://github.com/ls1intum/Artemis/pull/3909#pullrequestreview-729421040
Yes that was the view that I meant, and I have missed that not only the title but also the rows above shift

**Comment by FlorianGlombik** [comment]
@Malyuk-A The issue that you have addressed in https://github.com/ls1intum/Artemis/pull/3909#pullrequestreview-729421040 is now fixed with https://github.com/ls1intum/Artemis/pull/3909/commits/ae2f3b2ccf2ff25d0ccee28f8eacf5be4f0551fe

**Review by MaisiKoleni — APPROVED** [review]
Changes improve the table display on mobile devices, e.g. the exam table is usable again. I don't completely understand what we wanted to archive here in the first place, but the broken table is now repaired.

**Review by MerlinMehmed — APPROVED** [review]
Tested on TS1, worked as expected. Code changes also look good.

**Pull request merged**
