### PR TITLE
Modernize Programming Exercise Template JUnit 5 and Ares Tests

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage) - were already present.

### Motivation and Context
The tests for Java and Kotlin - both written in Java - are not using the pest practices and modern ways to write tests with JUnit 5 and Ares. This PR updates and modernizes the test files. See the description for details.

### Description
- Add missing `@Override`
- Remove `public` from the test classes, as JUnit 5 test classes do not need to be public and are not public API.
- Remove `public` from the test methods for the same reasons. We have to keep protected for the structural tests because those override a protected super class method.
- Switch to `target/test-classes` as path for the `@BlacklistPath` so that we are restricting access to the test classes by build directory and not by name (there might be student classes containing "Test").
- Improve Kotlin security by reducing `@AddTrustedPackage` scope
- Increment the version and update the date in each class level Javadoc

### Steps for Testing

1. Review the code changes
2. Check that the template and solution of a Java/Kotlin exercise still work and that all tests are found and work (template 0%, solution 100%) - but we do have automatic tests for that.

### CODE REVIEW

**Comment by JohannesStoehr** [comment]
Since Ares now allows modifiers for classes as well and an optional modifier in the test.json, you might want to update some things there as well.

**Comment by MaisiKoleni** [comment]
@JohannesStoehr I implemented your suggestions. Are there more places you thought of changing?

**Comment by JohannesStoehr** [comment]
> @JohannesStoehr I implemented your suggestions. Are there more places you thought of changing?

Looks good! Should we use an additional annotation that groups all other used annotations into one like in Eist?

**Comment by MaisiKoleni** [comment]
> > @JohannesStoehr I implemented your suggestions. Are there more places you thought of changing?
> 
> Looks good! Should we use an additional annotation that groups all other used annotations into one like in Eist?

I would leave that for the instructor/editor because not everyone might understand what we are doing. It is also common to have a different configuration for the structural tests (and we often use the exercise short name for that which would not be possible).

**Review by FlorianGlombik — APPROVED** [review]
The changes look good to me 👍 

A minor suggestion that could be implemented: `hide circle` could be added to the java exercise template for the PlantUML diagram, however, this might be a very EIST specific convention.
In case this is changed it might make sense to move `hide empty fields` and `hide empty methods` up to the `skinparam`, to keep a better track of the PlantUML settings

**Comment by MaisiKoleni** [comment]
> The changes look good to me 👍 
> 
> A minor suggestion that could be implemented: `hide circle` could be added to the java exercise template for the PlantUML diagram, however, this might be a very EIST specific convention.
> In case this is changed it might make sense to move `hide empty fields` and `hide empty methods` up to the `skinparam`, to keep a better track of the PlantUML settings

@FlorianGlombik you are right, but this PR only focuses on the tests. We could make a new one that focuses on the problem statement and maybe the template.

**Review by krusche — APPROVED** [review]

**Pull request merged**
