### PR TITLE
`Assessment`: Improve warnings for instructors before potentially assessing unfinished submissions

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Follow-up to #4416.

### Description
- Adds a warning on the ‘Submissions’ page if the regular due date is over but not the individual due date for some students.
- Adds a warning to the ‘Team’ page if the regular due date is over but not the individual due date for some students.
- Splits a method in `ProgrammingExerciseScheduleService` into two parts to satisfy Checkstyle (the split makes structural sense, too).
- Adds documentation how the individual due dates work when tests for the programming exercise are marked with visibility ‘After Due Date’.

### Steps for Testing

Prerequisites:
- An Instructor
- A team exercise of any type 

1. Submit something to the exercise as the student/team.
2. As instructor, set an individual due date to some point in the future for the team.
3. Set the regular due date to be in the past.
4. Go to the ‘Submissions‘ page and check that the warning as shown in the screenshot below is shown.
5. Go to the ‘Team’ detail page and check that the warning as shown in the second screenshot below is shown.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Test Coverage

| Component | Branch | Line |
| --- | --- | --- |
| `assessment-warning.component.ts` | 100% | 100% |

### Screenshots
Submissions page:
Screenshot 2021-12-20 at 19-54-28 Assessment Dashboard

Team page:
Screenshot 2021-12-20 at 19-54-08 Team

### CODE REVIEW

**Review by dveljacic — DISMISSED** [review]
Tested on TS1. Looks good. 👍 
submission_warning
team_warning

**Review by Santiastik — DISMISSED** [review]
Tested on ts1. 
Working as expected!
The code looks good also!

**Review by Strohgelaender — CHANGES_REQUESTED** [review]
Tested on TS1 with @cremertim @VinnavanSembian @lBruchmann @willergeorg. The new warning is shown as expected, but we'd like to request two additional changes:

When going to the submissions overview, every team has the enabled "Assess submission" button, even though their individual due date is in the future. This is inconsistent with the team detail view, when navigating to the individual team the "start new Assessment" button is disabled. I think it should be disabled in both places to avoid early assessments. 

When a student navigates to the overview of his own team, the standard due date is still shown in the exercise table. This should be replaced with the individual due date; the student should see that there is more time left.

**Review by cremertim — COMMENTED** [review]
see remarks @Strohgelaender

**Review by lBruchmann — COMMENTED** [review]
Tested on ts1. I followed the testing steps. Everything works as decribed. However, for some remarks see @Strohgelaender.

**Review by VinnavanSembian — COMMENTED** [review]
Tested on ts1 with @Strohgelaender @cremertim @lBruchmann @willergeorg. See our remarks in @Strohgelaender requested changes.

**Comment by b-fein** [comment]
Thanks for testing @Strohgelaender @cremertim @VinnavanSembian @lBruchmann @willergeorg!

> When going to the submissions overview, every team has the enabled "Assess submission" button, even though their individual due date is in the future. This is inconsistent with the team detail view, when navigating to the individual team the "start new Assessment" button is disabled. I think it should be disabled in both places to avoid early assessments.

For me the button on the team page is only disabled if the team has made no submission yet. As soon as they have submitted for the first time, the button is enabled, both before the regular due date and between the regular and the individual due date.
How can I reproduce the behaviour?

I think that the button should always be enabled for instructors to give them full access rights in the rare case it might be needed. The warnings are just there to make sure they know about possible side-effects of their actions. Otherwise, if the buttons are always disabled before the (individual) due date, then the warnings are not needed any more and could be removed entirely.

> When a student navigates to the overview of his own team, the standard due date is still shown in the exercise table. This should be replaced with the individual due date; the student should see that there is more time left.

This has been fixed in commit d9211f8.

**Review by FlorianGlombik — DISMISSED** [review]
As this is a follow-up PR for https://github.com/ls1intum/Artemis/pull/4416 I guess this is the right place to put my _(after merge review)_ directly here. I guess I found a problem with exam exercises, which is probably related to the due date changes.

It seems like I am not able to set individual exam due dates.

https://user-images.githubusercontent.com/63976129/147149291-dc826b12-a759-49d1-a371-bf26dabed2a5.mp4

**Comment by b-fein** [comment]
> As this is a follow-up PR for #4416 I guess this is the right place to put my _(after merge review)_ directly here. I guess I found a problem with exam exercises, which is probably related to the due date changes.
> 
> It seems like I am not able to set individual exam due dates.

@FlorianGlombik When I check the JSON response from the server after reloading the page after an update, the working time is set to the correct amount of minutes. This seems to be only a bug in how this duration is displayed in the UI and is unrelated to the due date changes.

**Comment by Strohgelaender** [comment]
> I think that the button should always be enabled for instructors to give them full access rights in the rare case it might be needed. The warnings are just there to make sure they know about possible side-effects of their actions. Otherwise, if the buttons are always disabled before the (individual) due date, then the warnings are not needed any more and could be removed entirely.

I did not expect instructors to have these rights, but if this is the wanted behavior we should continue it. I checked it and you are right, instructors can assess submissions even before the regular due date is over. 

> For me the button on the team page is only disabled if the team has made no submission yet. As soon as they have submitted for the first time, the button is enabled, both before the regular due date and between the regular and the individual due date.
How can I reproduce the behaviour?

Same here, I think we confused an instructor as a tutor while testing. The instructor can assess the submission before the individual deadline, the tutor cannot. So this works as expected as well. 


I think there is one more issue with categories: I tried to set / change the individual due dates on an exercise with categories and get the following exception on the update-individual-due-date-endpoint: ```JSON parse error: Cannot deserialize value of type `java.util.HashSet<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.HashSet<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`) at [Source: (PushbackInputStream); line: 1, column: 1416] (through reference chain: java.util.ArrayList[0]->de.tum.in.www1.artemis.domain.participation.StudentParticipation["exercise"]->de.tum.in.www1.artemis.domain.TextExercise["categories"]->java.util.HashSet[0])```. Once I remove the categoriese setting the due dates works again.

**Comment by b-fein** [comment]
@Strohgelaender Thanks again for the review, now the categories of the exercise are converted correctly before sending the request to the server.
There are a lot of changes since I refactored a method of the exercise service to now be static and that one was used in a lot of places. It’s the same change everywhere and does not affect the functionality.

**Review by dveljacic — COMMENTED** [review]
Tested on TS2. Followed the steps for testing (as I did the first time I reviewed this PR), but this time, the behavior is not as expected. As you can see in the attached screenshot, the warning is not shown anymore on the submission page. 
On the team page, the warning is shown as expected.

no_warning
team_warning

**Review by Bofan-Zhu — COMMENTED** [review]
Tested on ts2 and the same happened to me. I created a text exercise with a team that only has one student. After submitting a solution, setting an individual due date and changing the normal due date, the warning only appeared on the Team detail page but not Submissions page.

**Comment by dveljacic** [comment]
@b-fein You're welcome. It was a text exercise, a two-students team.

**Comment by b-fein** [comment]
@dveljacic @Bofan-Zhu Thanks for testing. I could reproduce the issue as well. When receiving submissions from the server their dates were not fully converted to the client representation. Therefore, the latest due date could not be determined and the warning was not shown.
It should now work again after the latest commit.

**Review by dveljacic — APPROVED** [review]
Manually tested on TS2, tried to reproduce any of the unexpected behaviors from the previous reviews, but unsuccessfully. This time, everything looks as expected. ✅ 

submission_warning
team_warning

**Pull request merged**
