### PR TITLE
[UI] UI improvements in Exercise create/edit page

### PR DESCRIPTION
**Pull request by Olimbia23**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
improve the create/edit page for each exercise type, by making ui elements consistent and more obvious to the user

### Description

For text/modelling/quiz/programming/ file upload exercise
1. Add space between different form group elements.
2. Increase the font and make it bold for headers of a section
3. Fix alignment for programming exercise.

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to any of exercises.
4. Create/Edit any type of exercise.

### Before
Screenshot 2021-07-13 at 1 27 27 AM

Screenshot 2021-07-13 at 1 27 59 AM

### After
program

text

### CODE REVIEW

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Looks good to me.

**Review by NicolasUllmann — DISMISSED** [review]
Tested on TS2. Everything worked as expected.

**Review by ArtemTsurikov — APPROVED** [review]
Looks good on TS1

**Review by krusche — CHANGES_REQUESTED** [review]
there are many codacy issues reported in the diff on Github. Please try to address them

**Comment by Olimbia23** [comment]
I have addressed the Codacy issues @krusche. The problem is that Codacy doesn't allow us to set styling to custom html-tags, however, the code was still working as expected.

One option as discussed with @MDK5 is to supply the custom config, that will filter out this check, however this seems like an another task on its own, which needs to be discussed and scheduled, therefore I applied another approach of using custom classes for the elements to avoid Codacy complains.

**Review by lschlesinger — CHANGES_REQUESTED** [review]
I found one more thing, that should be changed on the edit/create page:
the tooltip for the title is not completely visible, It should have the placement "right" or maybe "auto".
Bildschirmfoto 2021-07-15 um 09 17 48

Also, but that is a matter of taste, the checkboxes for programming exercises could have less padding in between, this way, it does not look like as list of options you could check or not check. But that is discussable 😄 

Otherwise, I like the changes.
Bildschirmfoto 2021-07-15 um 09 19 09

**Comment by Olimbia23** [comment]
> I found one more thing, that should be changed on the edit/create page:
> the tooltip for the title is not completely visible, It should have the placement "right" or maybe "auto".

> Also, but that is a matter of taste, the checkboxes for programming exercises could have less padding in between, this way, it does not look like as list of options you could check or not check. But that is discussable 😄

Thank you for the suggestions @lschlesinger 
I incorporated both of them 👼

**Review by lschlesinger — APPROVED** [review]
Thanks for incorporating the feedback 👍  -> If you are up for the challenge:
Some of the tooltips in this page are missing the point at the end of the sentence. Those tooltips are composed by view sentences, the last sentence needs a point as well, not just the previous ones in the tooltip:
Bildschirmfoto 2021-07-16 um 15 26 12

Bildschirmfoto 2021-07-16 um 15 26 37
Bildschirmfoto 2021-07-16 um 15 26 32
Bildschirmfoto 2021-07-16 um 15 26 23
Bildschirmfoto 2021-07-16 um 15 26 20
Bildschirmfoto 2021-07-16 um 15 26 16

**Review by ArtemTsurikov — APPROVED** [review]
Tested on TS3, re-approve

**Review by katjanakosic — APPROVED** [review]
Looks as expected on ts2 👍

**Review by canyelten — DISMISSED** [review]
Tested on TS1, works as expected.

**Review by sinangunduz — DISMISSED** [review]
tested on ts2, looks good

**Review by argertboja — DISMISSED** [review]
Works great on TS1!

**Review by real-dmy — DISMISSED** [review]
Tested on TS1, looks good.

**Review by SimonEntholzer — CHANGES_REQUESTED** [review]
Overall the changes look good, but there are still some codacy issues left. I'm not entirely sure if this is your fault or a wrong configuration of the style check. 
https://github.com/kristerkari/stylelint-scss/issues/196

**Review by DanielKainz — DISMISSED** [review]
Tested on TS1. Changes look good to me :-)

**Review by iozbeyli — DISMISSED** [review]
Code looks good. Codacy issues look like they need to be fixed in the codacy configuration since they look fine.

**Review by real-dmy — APPROVED** [review]
Tested on TS1, looks good.

**Review by katjanakosic — APPROVED** [review]
Looks good on ts1 👍

**Review by SimonEntholzer — APPROVED** [review]
code looks good, and it works on ts3.

**Review by DanielKainz — APPROVED** [review]
Tested on TS1. Everything worked as expected.

**Review by maximilianbergmann — APPROVED** [review]
Tested on TS3.

**Pull request merged**
