### PR TITLE
`Integrated code lifecycle`: Open repository for editors and instructors during assessment

### PR DESCRIPTION
**Pull request by SimonEntholzer**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Instructors and editors are not able to open the student's repository when they are assessing submissions.

### Description

Adds the "open repository" link, identically how it is for external repositories for LocalVC repositories.

### Steps for Testing

1. Create a programming exercise, and submit with a student.
2. As the instructor/editor set the submission due date, and change to manual assessment.
3. Navigate to the assessment dashboard -> assess new submission
4. There should be an "Go to repository" link, which leads to the student's repository.
5. Make sure the link is not displayed if you assess a submission as a tutor

#### Exam Mode Testing

1. Create an exam with a programming exercise
2. Participate with a student
3. Assess with an instructor/editor and tutor
4. The "Go to repository" link should be visible for the instructor.

Note: For test-runs, the button we do not show the repository button, as the repository view is not supported for test-run participation repositories yet. This will be added in a follow up.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| code-editor-tutor-assessment-container.component.ts | 89.09% | ✅ ❌ |
| navigation.utils.ts | 88.33% | ✅ ❌ |

### Screenshots

image

## Summary by CodeRabbit

- **New Features**
	- Introduced conditional rendering for repository links based on user permissions.
	- Added functionality to generate links for local repositories based on user roles and local version control status.
	- Enhanced UI with an external link icon for better navigation experience.

- **Bug Fixes**
	- Improved error handling and user feedback mechanisms remain unchanged, ensuring stability.

- **Documentation**
	- Updated navigation utility to include a new function for constructing local repository links.

### CODE REVIEW

**Review by HawKhiem — APPROVED** [review]
Tested on TS3.

The open repository button is indeed only visible for instructor

Screenshot 2024-11-28 232422
Screenshot 2024-11-28 232433
Screenshot 2024-11-28 232720

**Review by florian-glombik — APPROVED** [review]
Tested as editor on ts2 for a course and an exam programming exercise, worked as described

**Review by coolchock — APPROVED** [review]
tested in testing session, works as expected

**Review by kaancayli — APPROVED** [review]
Tested during testing session. Works as expected. Code LGTM

**Review by FelixTJDietrich — APPROVED** [review]
Tested on TS2 with instructor and tutor and it worked as expected, for tutors the button is not visible and for instructors it is.

**Pull request merged**
