### PR TITLE
[Bugfix] Questions & Answers: user check and null error on PUT 

### PR DESCRIPTION
**Pull request by filip-gregurevic**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] ~~Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)~~
- [x] ~~Server: I added `@PreAuthorize` and check the course groups for all new REST Calls (security)~~
- [x] ~~Server: I implemented the changes with a good performance and prevented too many database calls~~
- [x] ~~Server: I documented the Java code using JavaDoc style.~~
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] ~~Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)~~
- [x] ~~Client: I added `authorities` to all new routes and check the course groups for displaying navigation elements (links, buttons)~~
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] ~~Client: I added multiple screenshots/screencasts of my UI changes~~
- [x] ~~Client: I translated all the newly inserted strings into German and English~~

### Motivation and Context

https://github.com/ls1intum/Artemis/issues/2333

### Description

Access the course via the studentQuestion loaded from the db instead of the studentQuestion passed as body to prevent the course from being null.
Perform the check if the user is the author of a question via a method to cover the case that the user is not loaded on initialization of the component.
Only update question text on PUT to preserve references to lectures and exercises.

### Steps for Testing

1. Log in to Artemis as a *student*
2. Navigate to an exercise or lecture with existing questions or answers
3. Buttons to edit and delete should be shown (if it's your question)
4. Edit the question
5. Saving the changes should not throw any errors

### Test Coverage

unchanged

### CODE REVIEW

**Review by tiffca — APPROVED** [review]
Tested successfully in test server 1. Creating, editing, deleting a question works without issues.

**Review by stefanwaldhauser — CHANGES_REQUESTED** [review]
I have a strange bug that my question gets deleted when I edit it? Check out the video: 
https://streamable.com/00d79c

**Review by tiffca — APPROVED** [review]
Works fine again for me, tested in test server 3. Creating/editing/deleting questions/answers works fine.

**Review by stefanwaldhauser — APPROVED** [review]
re-approve

**Review by FuchsDominik — APPROVED** [review]
Tested in on TS2 and everything works very nice. Checked that editing works for the student who created the question/answer, but not for other students. + No errors are thrown.

**Review by sjagla27 — APPROVED** [review]
Worked as expected.

**Review by krusche — APPROVED** [review]

**Pull request merged**
