### PR TITLE
`Quiz exercises`: Fix text overflow in quiz questions

### LINKED ISSUE #4721: Sample solution overflow over card background in student exercise view
### Describe the bug

As soon as the sample solution contains elements that are not resizable with a width greater than the card background (screen width), the elements overflow and are visible outside of the containing card. 

### To Reproduce

1. Open an exercise with a sample solution that contains elements wider than your screen size. (e.g. https://artemis.ase.in.tum.de/courses/147/exercises/6029)
2. Click on "sample solution" to trigger the dropdown.

### Expected behavior

Either the x-overflow should be scrollable within the sample solution container or the background of the card should extend over the viewport's width. 

### Screenshots

Screenshot_20220219_144729

### What browsers are you seeing the problem on?

Chrome, Firefox

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jgrant12345**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

This change is required because in the case of a very long string that cannot be broken up, the string overflows outside the card component. By adding the `overflow: auto` property to the scss file, the card component will become automatically scrollable. The card component however is only scrollable when necessary. If the string can be broken down onto multiple lines, then the text will wrap rather than be scrollable. Overall this fixes an edge case.

This pull request fixes #4721 

### Description
When inputting a very long string that cannot be broken up into a quiz question exercise, such as `"hsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfasdfasdfsahsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfsa"`, this string overflows past the boundaries of the card component.

The text will no longer overflow, instead a scroll bar will appear if and only if the text would overflow otherwise. Currently the text will wrap when possible. However in certain cases when that string cannot be broken up, the text will overflow past the boundaries. In that case, the card will become scrollable.

We made changes to 
the following two files: short-answer-question-component.scss and multiple-choice-question-component.scss

### Steps for Testing

Prerequisites:
-  There shouldn't be any prerequisites but I was logged in as admin to create the quiz

1. Log in to Artemis
2. Navigate to Course Management
3. Click on the "exercises" button
4. Create a quiz exercise and either create a multiple choice question or short answer question.
5. Input the string `"hsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfasdfasdfsahsakjdflahsdfjhasdhadfsahsakjdflahsdfjhasdhadfsa"` on the first line
6. Observe that the string overflows past the card boundaries.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|

Screen Shot 2022-05-08 at 12 45 53 PM

### Screenshots
Before
Screen Shot 2022-05-08 at 12 29 12 PM

After
Screen Shot 2022-05-08 at 12 32 03 PM

### CODE REVIEW

**Comment by jgrant12345** [comment]
Just wanted to mention that we're a group of students who are trying to contribute to an open source project. If you have any feedback, please let us know. We're trying to learn the process of open source contribution. Thank you :)

**Review by Strohgelaender — COMMENTED** [review]
Thank you for your contrubution to Artemis, it is highly appreciated.

I tested the changes locally and it worked as described. But I don't think that adding a scroll bar here would be the best solution. Here the whole content will get scrolled to the side, including the number of points on the top:
grafik

After submitting the quiz there also will be a popup blocking access to the scrollbar:
grafik

Adding a word-wrapp could be a better solution here, but I'm not sure about that either.

**Review by SimonPaul02 — DISMISSED** [review]
Reviewed code, looks good

**Comment by Rocketman112** [comment]
Hello, I just wanted to check on the pull request. Should I look into other solutions or is this pull request in the review phase still?

**Comment by jgrant12345** [comment]
Hello, I just wanted to check on the pull request. Should I look into other solutions or is this pull request in the review phase still?

**Comment by SimonPaul02** [comment]
> Hello, I just wanted to check on the pull request. Should I look into other solutions or is this pull request in the review phase still?

I think you should look into other solutions, as @Strohgelaender said. Thank you for the contribution though, it is highly appreciated!

**Comment by krusche** [comment]
The PR is open for longer than 2 months (which is bad practice). We should either merge this soon or close the PR.
@manuelmanso can you please take over?

**Pull request closed without merging**
