### PR TITLE
`Exam mode`: Fix an issue when canceling assessments

### LINKED ISSUE #7277: Cancelling an exam exercise assessment from the list of assessments does not work (E.participation is undefined)
### Describe the bug

When opening the list of assessments for an individual exam exercise, we find handy buttons to cancel ongoing assessments directly:

image

Yet, clicking the "cancel" button (red button) does nothing. When opening the console, we find an error (`E.participation is undefined`):

image

When instead opening the assessment again (yellow button) and clicking cancel there...

image

... works.

### To Reproduce

1. Open the exam page.
2. Click on "Exercise groups" (Aufgabengruppen)
3. Scroll to one of the exercises.
4. Click on "Assessments" (Bewertungen) for this exercise
5. You need an active assessment, so if none is active, start one by clicking "Assess submission in correction round 2" (Abgabe in Korrekturrunde 2 bewerten)
6. Then, go back to the list and click "Cancel assessment of correction round 2" (Bewertung von Korrekturrunde 2 abbrechen).
7. The assessment will stay locked and active.

### Expected behavior

The assessment should be cancelled.

### Screenshots

_No response_

### Which version of Artemis are you seeing the problem on?

6.5.3

### What browsers are you seeing the problem on?

Firefox

### Additional context

Note that I only tested this in correction round 2, so I'm not sure if this relates to the correction round.

### Relevant log output

```shell
ERROR TypeError: E.participation is undefined
    cancelAssessment exercise-scores.component.ts:412
    t exercise-scores.component.html:351
    Angular 18
    z instrument.js:540
    Angular 6
    $t exercise-scores.component.html:351
    Angular 11
    en exercise-scores.component.html:345
    Angular 89
instrument.js:122:19

XHRPOST
https://sentry.ase.in.tum.de/api/2/envelope/?sentry_key=ceeb3e72ec094684aefbb132f87231f2&sentry_version=7&sentry_client=sentry.javascript.angular-ivy/7.71.0
[HTTP/1.1 403 Forbidden 0ms]
```

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://ls1intum.github.io/Artemis/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://ls1intum.github.io/Artemis/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://ls1intum.github.io/Artemis/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context
Fixes #7277. Canceling text exercise assessments is not possible due to a missing participation value.

### Description
Instead of using `result.participation` (which would be a backreference since the result source is `participation.results[correctionRound]`) we now directly use the participation present in the template.

Note that text exercises are the only exercises that actually need the participation id here. In the future, we should unify these endpoints and also only use the result id here.

### Steps for Testing
Prerequisites:
- 1 Instructor
- 1 Exam with text exercises and second correction enabled.

0. Edit the exam and set the number of correction rounds to 2.
1. Start a text exercise assessment in the second correction round (let one tutor assess the exercise in the first round, active second correction, then let a second tutor start the assessment in the second correction round, but don't submit the assessment yet)
2. Open the scores page (exercise groups -> exercise -> scores) and cancel the assessment
3. Check that no error happens and the assessment got canceled.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by MaximilianAnzinger — APPROVED** [review]
Code lgtm

**Review by jakubriegel — APPROVED** [review]
Code LGTM

**Review by julian-christl — APPROVED** [review]
Code

**Review by aplr — APPROVED** [review]
Code looks good ~, could not find the button to test on TS, so could not test~

Thanks @Strohgelaender for clarifying how to test - works!

However, I found that the assessment page behaves weird for the cancelled correction. You have to force-reload, when clicking cancel, all of the buttons are disabled, and when using breadcrumbs, empty pages with error messages appear. But I guess that's more of a follow-up.

Screenshot 2023-09-30 at 19 11 31

**Review by Kroko-fant — APPROVED** [review]
Code looks good to me tested on ts5

**Review by laurenzfb — APPROVED** [review]
Demonstrated in testing session, worked as expected. Code LGTM as well

**Review by florian-glombik — APPROVED** [review]
Tested on ts5, removing the lock worked - the code looks fine aswell.

**Pull request merged**
