### PR TITLE
Add Kotlin pipeline to Jenkins & Sequential Test Run support

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

It's currently not possible to generate Kotlin programming exercises with the Jenkins/Gitlab setup. Also the "sequential test runs" is not supported.

### Description

This PR does two things:
1. Adds a new Jenkinsfile for Kotlin which configures the pipeline. It allows Kotlin programming exercises to be generated in Artemis
2. Restructures the Jenkins templates directories to add support for sequential test runs
3. Adds sequential test runs support for Java and Kotlin exercises

### Steps for Testing

Since these changes affect Gitlab/Jenkins, you need to use TS2 to test.
1. Log in to Artemis
2. Navigate to Course Administration
3. Click on "Generate a new programming exercise"
4. Check that Kotlin is visible in the drop down list
5. Click on Kotlin and make sure the "sequential test run" option is clickable
5. Select the option and generate the exercise
6. You should be able to participate to the exercise, submit code, and receive feedback
7. You can also check that the feedback received is the same to the feedbacks returned in TS1 (basically reproduce the steps on TS1)
8. Generate a new Java programming exercise and make sure that the sequential test run option is also selectable
9. Click it and participate in the exercise
10. You should be able to receive feedback

### Test Coverage

JenkinsBuildPlanCreator.java 95%
JenkinsBuildPlanService.java 89%
JenkinsProgrammingLanguageFeatureService.java 100%
JenkinsXmlConfigBuilder.java  
### Screenshots

image

image

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS2, I could create & participate in Kotlin exercises, everything worked flawlessly. The code changes are good too, also the docker file additions. :+1:

**Review by SimonEntholzer — APPROVED** [review]
re-approve

**Review by iozbeyli — APPROVED** [review]
I tested it on TS2 and was able to create the exercise and participate. Code looks good as well

**Review by krusche — CHANGES_REQUESTED** [review]
please make sure the new scenario is tested as part of the server integration tests

**Review by willergeorg — COMMENTED** [review]
I was able to select Kotlin as programming language and in the java exercise, the sequential test run seems to work. No bugs occurred.

**Review by NicolasUllmann — COMMENTED** [review]
Tested on server 1. Everything worked as expected.

**Pull request merged**
