### PR TITLE
`General`: Add dark mode ☾ ✨

### LINKED ISSUE #4404: Darkmode
### Is your feature request related to a problem?

Me, everytime I open Artemis:
cat-blind-flashbang-light-mode

### Describe the solution you'd like

Add Darkmode support

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

Dark Modes are commonly available in most software used by programmers today.
Operating Systems, IDEs and browsers all come with some sort UI mode with negative polarity.

As Artemis is mostly used for programming exercises in CS courses and thus is used by a lot of programmers both on the student and the instructor side, we should provide a native dark mode as well.

Closes #4404.

#### Application (TS / HTML)

Added a new theme service that injects a theme override stylesheet to the page ``<head>`` if the dark mode shoud be applied. The theme service has been designed to support more than one additional theme in the future.
The service automatically infers the preferred UI mode from OS / browser settings on first launch, but stores the user preference in local storage from then on.

Added a theme switch component to the navbar to allow for easy and convenient theme switching.
It also contains a popover with a few hints and a big flag that marks this feature as experimental.

#### Styles

The dark mode was implemented by modifying the variables of bootstrap before importing it.
However (or rather, sadly), we have lots and lots of local color definitions in component stylesheets that do not re-use bootstrap colors.

Therefore, a lot of these colors in component stylesheets have been replaced with CSS variables that get different values for both themes. For each theme, there is now a "variables" SCSS file where these colors are defined.
In this first version, there are a lot of variables in there. Future work has to be done to reduce the amount of variables, re-use colors where possible, and reduce the amount of used colors throughout the app in general (we really don't need 38293842 shades of gray everywhere).

The default theme is (like it was before) injected by Angular by default. The dark theme is injected as an overriding stylesheet when requested.

Apollon has been themed as well. A huge thank you to @martindevtum who made easy theming possible in Apollon.

### Steps for Testing

- On first launch of PR: Make sure that the app automatically shows the popover and syncs the theme to your OS setting by default. If you need to test it again, clear local storage for the webapp.
    - Please test this with both themes; at least in Firefox, you can select which preferred theme the browser should report to the page in dev tools:
     grafik
    - If you do it with... (Please test both)
        - ...the light theme, it should automatically show you a popover offering you a "Enable now" button to apply the dark mode, alongside a "No thanks" link that will store the light preference in local storage. 
        - ...the dark theme, it should inform you that it auto-enabled the dark mode based on your preferences and that you can disable it at any time. Please check that the "Got it!" link closes the popover.
- Make sure that you can switch between themes by clicking the icon in the navbar at all times. Verify that this disables the OS-sync feature automatically
- Make sure that your selection survives reload and browser restarts
- Make sure that you can enable and disable the OS-sync feature at any time. If it's enabled, it should sync with the system. In Firefox, you can test this as shown above. If it's disabled, it should keep the currently active theme.
- Probably the biggest thing: In general, this is an experimental feature and we need to make sure that it works everywhere. I expect this to be a longer process where we collect issues over time. Therefore, it's not expected that you test each and every page right now. We should do so in a testing session. However, if there are elements that you know and that are important etc, please go ahead and check if they look okay in both themes.

### Code review

This PR is ultra large. However, a lot of the changes are related to fixing styles and replacing colors with variables.

The most important files to review are the following as they contain the most prominent business logic changes and/or new components:
```
src/main/webapp/app/core/theme/*
src/main/java/de/tum/in/www1/artemis/service/PlantUmlService.java
src/main/java/de/tum/in/www1/artemis/web/rest/PlantUmlResource.java
src/main/resources/config/liquibase/changelog/20220503131200_changelog.xml
```

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| theme-switch.component.ts | 58% |  89% |
| theme.service.ts | 75% | 91% |

### Screenshots

https://user-images.githubusercontent.com/23171488/165316241-244bf6bf-b5e0-46c0-9a12-24c17020196b.mov

### CODE REVIEW

**Comment by ge65cer** [comment]
As soon as I saw this, I had to test it out (even though this is still a draft). 😄 
So far I really love it, good job! ❤️ 

Found no major problems so far, only two small things:
1. I've set my system appearance to auto (light during the day, dark at night). Artemis sticks to the theme it first encountered using local storage (as you described). I'd like it to always follow my system's appearance, but this probably just my preference, so happy to discuss what the others reviewers have to say.
2. Popover is [too fast for me](https://user-images.githubusercontent.com/102237363/165354130-d94bb858-0095-473d-8c99-0a4b8480e8a6.gif) to click on it.

**Comment by bassner** [comment]
@ge65cer Thank you for having a look!

1. Yes, we could do that. I'll add it as discussion points for tomorrow's meeting so we can see how everyone feels about it.

2. The popover you showed in your video should actually be shown right after the page loaded, without any interaction. From there (if you don't touch the icon in the navbar with your mouse), it should be clickable.
However, I just pushed an patch that should optimize the behavior of the popover and the problem you showed should not happen anymore.

**Review by JohannesStoehr — DISMISSED** [review]
The general functionality works as expected. Nice work!

I went through some pages and found these small issues:
Bildschirmfoto 2022-04-27 um 23 41 22
A big whiteish box:
Bildschirmfoto 2022-04-27 um 23 45 45
When checking a text submission: 
Bildschirmfoto 2022-04-27 um 23 46 26
The checkboxes in the settings, while other checkboxes are white:
Bildschirmfoto 2022-04-27 um 23 47 55
Optional: The question marks are a bit dull:
Bildschirmfoto 2022-04-27 um 23 45 19

**Comment by krusche** [comment]
The feature pages, e.g. https://artemis-test1.artemis.in.tum.de/features/students and https://artemis-test1.artemis.in.tum.de/features/instructors are not working yet

**Review by canberkanar — CHANGES_REQUESTED** [review]
Nice feature! Here are some issues I have noticed on ts1;

- The source code editor component does not behave as expected in dark mode;
https://artemis-test1.artemis.in.tum.de/courses/6/discussion (post 35)
- Theming of emojis (count of the same emoji added to post is dark and not clear to read)
image

**Comment by Haspamelodica** [comment]
grafik
Emoji picker always uses system settings

**Review by Dominik-Weinzierl — COMMENTED** [review]
Nice feature :+1: Seems like the footer for Quizes has the wrong background color.
image

**Comment by krusche** [comment]
Small issue, does not really look good

image

**Comment by krusche** [comment]
The right side of the grading page does not look very nice

image

**Review by Dominik-Weinzierl — COMMENTED** [review]
Wrong background color for Spot Quizes (Visual Mode). 
image

**Review by julian-christl — CHANGES_REQUESTED** [review]
Reproduce: Create some custom feedback for a submission and look at it as a student.

**Review by willergeorg — CHANGES_REQUESTED** [review]
What I noticed so far:

- The date picker still appearing in white with the dark mode. 
image

- The charts on programming grading config are not optimal yet
image
image

**Review by Hialus — APPROVED** [review]
The ace editor in the git-diff view is in dark mode when you have Artemis in light mode:
grafik
The ace editor in the test coverage view is in light mode when you have Artemis in dark mode:
grafik
The repo overview is hard to read:
grafik
Text hints have a weird grey background when viewing them from the problem statement:
grafik
Tasks with a question mark have a hard to read test case text:
grafik
Personally I also find the shade of red too dark for this:
grafik
The grading view of a programming exercise has broken charts:
grafik

**Comment by sleiss** [comment]
The log-settings show some kind of table, which now has white borders:
image

Just posting it here so that we don't forget it, but I think it's fine if this is fixed in a follow-up.

**Review by Hialus — CHANGES_REQUESTED** [review]
Misclicked

**Comment by cameronshemilt** [comment]
Little contrast when adding a new lecture unit
Screenshot 2022-04-28 at 10 27 09

**Review by ole-ve — COMMENTED** [review]
Some things I noticed in dev meeting.

Creating/Editing/Display a programming exercise:
Bildschirmfoto 2022-04-28 um 10 14 32

Code Editors for [Testwise Coverage Modal](https://github.com/ls1intum/Artemis/pull/4976):
Bildschirmfoto 2022-04-28 um 10 19 42

Diff-view has some unneat color (not sure how easy to solve):
Bildschirmfoto 2022-04-28 um 10 20 10

Grading charts (background color bites with the labels):
Bildschirmfoto 2022-04-28 um 10 21 43

**Review by mallgaier — COMMENTED** [review]
For Discussion: 
The blue `primary` and turquoise `info` do not differ enough in DarkMode in my opinion.
image

**Comment by ge65cer** [comment]
Button Hover
Screenshot 2022-04-28 at 14 07 48

**Review by ole-ve — CHANGES_REQUESTED** [review]
Some things I noticied during the testing session:

Inconsistent coloring on [creating a new user](https://artemis-test2.artemis.in.tum.de/admin/user-management/new):
Bildschirmfoto 2022-04-28 um 14 04 16

Checkboxes are quite hard to see:
Bildschirmfoto 2022-04-28 um 14 07 27

[Control items](https://artemis-test2.artemis.in.tum.de/courses/157/discussion) are quite hard to see (checkboxes, arrow):
Bildschirmfoto 2022-04-28 um 14 12 36

The [hover color of this button](https://artemis-test2.artemis.in.tum.de/course-management/157/goal-management/6/edit) is the same as the text color making the color not visible:
Bildschirmfoto 2022-04-28 um 14 14 27

**Comment by bassner** [comment]
grafik
Selecting course color has wrong background

**Comment by minrows** [comment]
image

**Review by mallgaier — COMMENTED** [review]
One very, very small thing in the Exam Mode:
image
`create-test-run-model.component` and uses formControl

**Review by willergeorg — DISMISSED** [review]
This is the preview of a modeling exercise submission in an exam:
image
The "frame" should be different imo

**Comment by ge65cer** [comment]
Sidebar & Task Description
Screenshot 2022-04-28 at 14 36 09

Background
Screenshot 2022-04-28 at 14 38 44

Grid Background
Screenshot 2022-04-28 at 14 39 04

Popover too dark
Screenshot 2022-04-28 at 14 36 43

**Comment by minrows** [comment]
Few screenshots of an exam


image
image
image

**Review by akesfeden — APPROVED** [review]
Tested on TS5, the issue with dropdown background color in Windows is fixed. The screens look nice and usable in dark and light modes.

**Review by mallgaier — DISMISSED** [review]
Retested on TS5, found no more issues.
Amazing job 👍

**Review by Dominik-Weinzierl — APPROVED** [review]
Clicked through some pages and saw one inconsistency, but this can be addressed in an additional PR (`/course-management/x/lectures/y/attachments`) - seems to be in multiple cases (Browse-Button):

<details>
<summary>Images</summary>

image
image
</details>

Edit: Well done! I really like the new Dark Mode :tada:

**Comment by Hialus** [comment]
Markdown Code Blocks do not support dark mode:
grafik

**Comment by Hialus** [comment]
A minor issue that could be ignored: PlantUML Diagrams do not automatically change their appearance when changing the theme. They do change their appearance after a page reload, so this isn't anything major.
grafik

**Comment by Hialus** [comment]
The testwise coverage modal still has issues with the ace editor theming when in light mode:
grafik

**Comment by Hialus** [comment]
The "Plagiarism detection can take a long time for large courses." is hard to see in light mode. In dark mode is is easily readable
grafik

**Comment by bassner** [comment]
@Hialus Can you check if the issues are fixed now?

**Review by mallgaier — APPROVED** [review]
Retested, changes work as expected.
Amazing Job 👍

**Review by willergeorg — APPROVED** [review]
Tested again. Works fine, prior problems seem to be resolved.

**Review by Hialus — APPROVED** [review]
All my issues have been addressed. 
Good job 👍🏻

**Review by ole-ve — APPROVED** [review]
Tested on TS1, all my previously found issues were fixed. Good job 👍

**Pull request merged**
