### PR TITLE
`Plagiarism checks`: Do not take practice participations into account

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context

#5882

### Description

Test runs and therefore practice participations are no longer taken into consideration for plagiarism cases.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 2 Students
- 1 Programming Exercise

1. Log in to Artemis
2. Navigate to Course Administration
3. Participate with both students before the deadline and afterwards using the practice mode and submit the same code
4. Check for plagiarism
5. Make sure that only the graded participations are taken into account

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Comment by nikirovast** [comment]
Hey!
Maybe I misunderstood the meaning of "taken into account", but I could still see the results from practice.

Screenshot 2022-11-27 4 00 40 PM

Let me know if I should have checked something else.

**Review by nikirovast — CHANGES_REQUESTED** [review]
Sorry I got confused, I am reviewing it now a second time

**Review by nikirovast — APPROVED** [review]
I've tested it on the test-server 1 and it works as expected.
I am sorry for the confusion!

**Review by tobias-lippert — APPROVED** [review]
Tested on ts1. Works as expected. Practice submissions are filtered out.
Code LGTM as well.

**Review by simon-hng — APPROVED** [review]
Code

**Pull request merged**
