### PR TITLE
`Communication`: Add shortcut to set focus on course-wide search

### PR DESCRIPTION
**Pull request by egekurt123**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Description

This pull request introduces a new keyboard shortcut feature that allows users to set focus on the course-wide search bar.

### Steps for Testing

Prerequisites:
- 1 Instructor / Student / Tutor
- 1 Course with Communication enabled

1. Log in to Artemis
2. Navigate to Communication
3. Navigate to a Channel 
4. Press cmd + k (or ctrl + k) on windows
5. Make sure you get focussed on course-wide search bar

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
  - Enhanced user interaction in the Course Conversations component by adding keyboard shortcuts for quick search actions.
  - Implemented a feature to focus on the search input using a convenient keyboard shortcut.
  - Updated localization to inform users of the new keyboard shortcuts in both German and English.

### CODE REVIEW

**Comment by Strohgelaender** [comment]
Consistency nitpick: In other places we used `@HostListener('document:keydown.control.shift.arrowRight', ['$event'])` for such listeners. Do you know if document vs window makes a relevant difference here? And can you maybe also move the expected keys into the listener definition?

**Review by SimonEntholzer — DISMISSED** [review]
Works on Ts3 :+1:

**Review by pzdr7 — COMMENTED** [review]
Tested on TS3 - works as described. But I wonder: could this work on the "All Messages" screen as well (or when you've already done a course-wide search)?

**Review by pzdr7 — DISMISSED** [review]
Tested again on TS3. Thanks for updating the functionality, works as described 👍

**Review by asliayk — APPROVED** [review]
tested locally, it works as expected

**Review by JohannesStoehr — CHANGES_REQUESTED** [review]
Can you also change the UI, so the users can find this feature?
E.g. adapt the place holder to include `(Ctrl + K)` at the end

**Review by sarpsahinalp — APPROVED** [review]
Code lgtm

**Review by asliayk — APPROVED** [review]
reapproved

**Review by krusche — APPROVED** [review]

**Pull request merged**
