### PR TITLE
`Programming exercises`: Use server time for exercise details dates

### PR DESCRIPTION
**Pull request by rabeatwork**
#### General

- [x] This is a small issue that I tested locally and on a testserverand was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context

If a student manually changes the time on their computer (without changing the time zone), the time until an exercise starts, is due, etc., was displayed incorrectly.

### Description

To avoid this, the server time is fetched and used instead of using dayjs().

### Steps for Testing

Prerequisites:
- 1 Instructor/student
- 1 Programming Exercise with dates (start date, due date, assessment date, complaint date)

1. Log in to Artemis
2. Navigate to Course Exercises
3. See the current dates
4. Change the date/time of your computer (manually and by changing the time zone)
5. Verify that the dates are still displayed correctly

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
	- Introduced server time integration for enhanced date handling in the exercise headers component.
	- Updated date comparison logic to ensure consistency with server time.

- **Bug Fixes**
	- Improved flexibility of date comparison functions to accept user-defined reference times.

- **Refactor**
	- Centralized date logic to reduce redundancy and improve maintainability.
	- Enhanced synchronization checks in the server date service for improved accuracy.

### CODE REVIEW

**Review by sachmii — DISMISSED** [review]
Tested on TS3, works as described

**Review by HawKhiem — DISMISSED** [review]
Tested on TS3. Everything works as described

**Review by iyannsch — DISMISSED** [review]
Good idea, Code LGTM ☺️

**Review by asliayk — DISMISSED** [review]
tested locally, works as described

**Review by vinceclifford — CHANGES_REQUESTED** [review]
Changing the date & time on the computer influences the date of the exercise. Using a 2023 Macbook running MacOS 15.0.

image

**Comment by rabeatwork** [comment]
> Changing the date & time on the computer influences the date of the exercise. Using a 2023 Macbook running MacOS 15.0.
> 
> image image

Thanks. As far as I could reproduce it, the issue occurs only if you don't reload the page after the time change and just switch between exercises. The problem was that with the current `server date service`, the server time was only synchronized if it was more than 60 seconds ahead, but not if it was in the past. Adjusted that. 
TLDR: Fixed.

**Review by sachmii — APPROVED** [review]
re-approve

**Review by HawKhiem — APPROVED** [review]
Reapprove

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by flbrgit — APPROVED** [review]
Tested on TS4, everything works as described when changing time and time zone manually.

**Review by JerroyTan — COMMENTED** [review]
[Tested on TS5]
For me the time only automatically switched according to the changes on my computer system when I changed the time zone. However, when I changed the time manually (moved 5 minutes before, moved 2 hours before) it did not work as expected. The time on the exercise was shown  according to the last time zone I set myself to.
Tested on Windows 11

**Pull request merged**
