### PR TITLE
`General`: Improve chart appearance in course statistics page

### PR DESCRIPTION
**Pull request by willergeorg**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [ ] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

This PR improves the charts on students statistics tab in some details

### Description

- **Chart coloring**: The coloring of the bars is reworked. A bit darker colors are chosen since the current ones are quite loud. For this purpose, standardized colors used in different places are reused. Furthermore, the color of the average score line is changed from red to yellow. Since red is used to indicate missing scores in the bar charts, this leads to a confusing difference in color coding between the two chart types.
- **Performance in exercises positioning**: The positioning of the chart is now changed so that it is centered on the page and consumes 90% of the page width.
- **Readability of legend entries**: The default color of the legend entry test is changed to the Artemis dark color (which is more or less black) as well as its font weight is increased in order to make the legend more readable. If the user now hovers over a chart entry, it is colored in Artemis primary color instead of black as it was previously.
- **Horizontal bar chart height**: We encountered some problems for the horizontal bar charts: As the height of the chart is currently hardcoded, the chart gets hardly readable if many exercises should be displayed. The height is now determined dynamically in order to ensure readability even if many exercises are displayed.

### Steps for Testing

Prerequisites:
- 1 Student
- 1 Course with some contributions

1. Log in to Artemis
2. Navigate to the student statistics tab
3. Inspect the charts there. Feel free to share your opinion about the new colors. These are open for discussion.
4. Also check that the horizontal bar charts are sized conveniently and the dimensions are not reducing your usability.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Mainly UI changes

### Screenshots

An example how a chart with 50 exercises would look with the current implementation. Notice that even some exercise titles are omitted by the framework because there is not enough space:
Old_impl

How it looks with my changes:
image

The new colors:
image

### CODE REVIEW

**Review by Bofan-Zhu — COMMENTED** [review]
So far everything looks quite good to me. However, could the red color be a bit lighter? I don't know if it's only me but the dark color is a bit overwhelming for my eyes, especially if everything is red. 
image

**Comment by willergeorg** [comment]
> So far everything looks quite good to me. However, could the red color be a bit lighter? I don't know if it's only me but the dark color is a bit overwhelming for my eyes, especially if everything is red. image

This is the red we are currently using in other places, mainly for indicating missing parts (points, assessments, etc.). I would like to be consistent in the color domain across the system. However if this red is overwhelming, we might want to switch to a lighter one in general. I append the tint scheme of this color below. let me know which version would be more convenient for you. If no version really works for you, let me know and we try to find another color. 
image

**Review by baranimo7 — APPROVED** [review]
Tested on ts2. Tables with many exercises looked fine and the colour is also fine for me.

**Review by MertAksehirlioglu — COMMENTED** [review]
Colors look good but i have a question about thickness of the bars of each exercise. If we have just one exercise in a type, it's bar is very thin compared to the others. For example "Julis SCA progra.." here:
Screen Shot 2022-02-21 at 10 44 51

Could we have same height for all the bars?

**Comment by willergeorg** [comment]
> Colors look good but i have a question about thickness of the bars of each exercise. If we have just one exercise in a type, it's bar is very thin compared to the others. For example "Julis SCA progra.." here: Screen Shot 2022-02-21 at 10 44 51
> 
> Could we have same height for all the bars?

Well, this definitely has to be changed, thanks for pointing it out. I will have a look into it.

**Comment by Bofan-Zhu** [comment]
> > So far everything looks quite good to me. However, could the red color be a bit lighter? I don't know if it's only me but the dark color is a bit overwhelming for my eyes, especially if everything is red. image
> 
> This is the red we are currently using in other places, mainly for indicating missing parts (points, assessments, etc.). I would like to be consistent in the color domain across the system. However if this red is overwhelming, we might want to switch to a lighter one in general. I append the tint scheme of this color below. let me know which version would be more convenient for you. If no version really works for you, let me know and we try to find another color. image

If no one got the same problem as me, then you can also just leave it as it is. I think color that is just a tad brighter would be fine (20%, 30%)

**Comment by willergeorg** [comment]
@MertAksehirlioglu I changed the chart size calculation a bit. It is now unified for all possible chart sizes (I think this is the easiest and most convenient solution instead of doing random case differentiation). The bar padding is now unified as well. I checked it locally, this should fix the appearance if only one bar is displayed. Feel free to take a look by yourself on a test server again!

**Comment by willergeorg** [comment]
> > > So far everything looks quite good to me. However, could the red color be a bit lighter? I don't know if it's only me but the dark color is a bit overwhelming for my eyes, especially if everything is red. image
> > 
> > 
> > This is the red we are currently using in other places, mainly for indicating missing parts (points, assessments, etc.). I would like to be consistent in the color domain across the system. However if this red is overwhelming, we might want to switch to a lighter one in general. I append the tint scheme of this color below. let me know which version would be more convenient for you. If no version really works for you, let me know and we try to find another color. image
> 
> If no one got the same problem as me, then you can also just leave it as it is. I think a color that is just a tad brighter would be fine (20%, 30%)

I will keep your suggestion in mind. If similar feedback occurs from prod users, it would be an quick fix to change the color in a followup :)

**Review by VinnavanSembian — APPROVED** [review]
tested on ts1 with @lBruchmann and @Strohgelaender. Everything looks good!

**Review by Strohgelaender — APPROVED** [review]

**Review by coaxial1 — APPROVED** [review]
Code looks good to me.
(Except for the usages of ``!important`` maybe, those always have a bad smell... :P)

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on TS1, everything looks good now. The earlier mentioned issue is solved.

**Review by cremertim — APPROVED** [review]
code lgtm

**Pull request merged**
