### PR TITLE
`General`: Fix more button in the course menu

### PR DESCRIPTION
**Pull request by raffifasaro**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data (e.g. using paging).
- [x] I **strictly** followed the principle of **data economy** for all client-server REST calls.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The "more..." feature when compressing the navbar was not working anymore after a PR that changed the syntax of the course-overview-component

### Description

An if else block in the course-overview-component made the definition of "ngbDropdown" inaccessible for some calls, so instead of using an if else block to completely omit the section, we use "d-none" so the ngbDropdown implementation is still accessible.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Exercise

1. Log in to Artemis
2. Navigate to Course 
3. See if "...More" section is displayed again after compressing the page and dropout opens beside it

Before:
image

After:
image

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review

- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance even for very large courses with more than 2000 students.
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance even for very large courses with more than 2000 students.
#### Code Review
- [ ] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

## Summary by CodeRabbit

- **New Features**
	- Improved sidebar rendering logic for better user experience based on the `isLti` condition.
  
- **Bug Fixes**
	- Streamlined conditional checks for sidebar visibility, enhancing clarity and functionality.

- **Style**
	- Minor adjustments to HTML formatting and indentation for improved readability.

### CODE REVIEW

**Comment by rabeatwork** [comment]
The dropdown is now within the sidebar instead of on the right side. Unfortunately, this doesn't work, especially in the collapsed view.

Screenshot 2024-10-24 at 19 09 57
Screenshot 2024-10-24 at 19 09 39

**Review by rabeatwork — APPROVED** [review]

**Review by az108 — APPROVED** [review]
Code 👍

**Review by Cathy0123456789 — APPROVED** [review]
Tested on TS1. Works as expected.
image
image

**Review by JohannesStoehr — APPROVED** [review]
Code

**Review by kevinfischer4 — APPROVED** [review]
Tested on TS5, works as expected.
Bildschirmfoto 2024-10-29 um 12 41 20

**Review by sachmii — APPROVED** [review]
Tested on TS5, works fine.

**Review by SindiBuklaji — APPROVED** [review]
Tested on Ts3 and it works as expected & described 👍

**Review by krusche — APPROVED** [review]

**Pull request merged**
