### PR TITLE
`General`: Use import icon consistently

### PR DESCRIPTION
**Pull request by milljoniaer**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
We used sometimes the "+" icon and only sometimes the "faFileImport" Icon for import actions.
This PR sets the import icon for all the remaining import buttons where "+" was used.

### Steps for Testing

Prerequisites:
- 1 Instructor

1. Log in to Artemis
2. Navigate to Course Administration
3. Check that all Import buttons you can find have only the faFileImport icon.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
image
image

## Summary by CodeRabbit

- **Style Updates**
	- Updated icons across various components from plus (`faPlus`) to import (`faFileImport`) symbols to better represent import actions.
- **New Features**
	- Enhanced the user interface by adding more intuitive import buttons for competencies, tutorial groups, exams, exercise groups, lectures, and user import actions.

### CODE REVIEW

**Review by farisd16 — APPROVED** [review]
tested on ts2, icons look fine

**Review by nata-81 — APPROVED** [review]
Tested on ts1 couldn't find any plus icons.

**Comment by MaximilianAnzinger** [comment]
@rstief keep in mind to follow this convention as well 👍

**Review by konrad2002 — APPROVED** [review]
manually tested on legacy ts1, works as expected

**Review by nityanandaz — APPROVED** [review]
Code review: looks good

**Review by AntonGeTUM — APPROVED** [review]
Tested on ts11, every Import button with an icon had the correct one

**Review by MaximilianAnzinger — APPROVED** [review]

**Pull request merged**
