### PR TITLE
`Development`: Update exam mode working offline student view screenshots

### PR DESCRIPTION
**Pull request by edkaya**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
nted the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Continue Working Offline section does not include a screenshot.

### Description

Added a screenshot for Continue Working Offline section.

### Steps for Testing

Prerequisites:
- 1 Student

1. Log in to Artemis
2. Navigate to URL with respective test server e.g. https://artemis-testX.artemis.cit.tum.de/features/students
3. Verify that Continue Working Offline has a screenshot now

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

workingOffline

## Summary by CodeRabbit

- **New Features**
	- Enhanced the presentation of the "working offline" feature with improved image layout.
	- Clarified user instructions for saving work while offline, including additional triggers for the save mechanism.

- **Bug Fixes**
	- Refined text in the offline functionality descriptions to improve clarity.

### CODE REVIEW

**Review by JohannesWt — APPROVED** [review]
Code/Translations look good 👍

**Review by pzdr7 — APPROVED** [review]
Screenshot is displayed on TS5 and looks good :+1:

**Review by coolchock — APPROVED** [review]
screenshot is displayed on ts5

**Review by egekurt123 — APPROVED** [review]
Looks good on ts5

**Pull request merged**
