### PR TITLE
[BLOCKED] Feature/Programming-Exercise: Add support for Apollon diagrams

### PR DESCRIPTION
**Pull request by thilo-behnke**
### Checklist
- [ ] I tested the changes and all related features on the test server https://artemistest.ase.in.tum.de.
- [ ] I documented my source code using the JavaDoc / JSDoc style.
- [ ] I added integration test cases for the server (Spring) related to the features
- [ ] I added integration test cases for the client (Jest) related to the features
- [ ] I added screenshots/screencast of my UI changes
- [ ] I translated all the newly inserted strings

### Motivation and Context

Atm the programming-exercises instructions only support plantUMLs for rendering Uml diagrams.
However as we have the @ls1intum/apollon library, we should integrate it.

Advantages:
- Much easier to handle through the drag&drop editor
- Reuse of existing diagrams
- Less performance heavy, as we can render the diagram in the client

### Description

Two domain commands will be provided:
- Create/Update apollon diagram
- Insert existing apollon diagram
The apollon diagrams that are inserted into the editor will be saved into our database, but linked to a course (otherwise they could be edited by everyone using artemis).

This PR will not make it possible to replace the plantUML diagrams with apollon diagrams, as we can't atm color specific elements of the uml (this is something we use in the interactive instructions for programming exercises).

- [x] Implement command to insert/edit apollon commands in the markdown editor
- [x] Implement modal for inserting/editing apollon diagrams
- [x] Implement preview in programming exercise instructions (remarkable)
- [x] Implement preview in showdown extension (how to create an extension that generates an async REST call?)
- [ ] Fix issues from Apollon update
- [ ] Add exercise id to apollon diagram model
- [ ] Implement command for inserting existing apollon diagrams of course

### Steps for Testing

1. Log in to ArTEMiS
2. Create/Edit a programming-exercise
3. Insert an apollon diagram by clicking the domain command
4. Check the preview
5. Edit the created apollon diagram by placing the cursor within it and then clicking the domain command 

### Screenshots

**New domain command:**

apollon_2

**Create/Edit diagram in modal:**

apollon_3

**Representation of diagram in markdown:**

apollon_4

**Rendering of the diagram:**

apollon_1

### CODE REVIEW

**Comment by thilo-behnke** [comment]
@krusche What do you think about the implementation as is?
I think from the list of issues only 2 would be relevant for an MVP.

**Comment by krusche** [comment]
I see two use cases here:
1) Insert a static UML diagram. Then we should be able to display it without a canvas and without scroll bars.
2) Insert an interactive UML diagram. Then we should be able to connect test cases to model elements, so that they change the color. This would indeed be a new functionality in Apollon. I think it would be enough to have the ability to change the color of model elements to red and green (and potentially also orange?) which should be rather easy. Can you talk to @jwilland-tum about this?

**If we replace PlantUML (which is the main benefit), the second point is a must.**

Let's also discuss the persistence option. I would be fine storing it inline in the text editor, but I would also be fine storing it separately and referencing it with an identifier. Both options have their advantages and disadvantages so let's go for the easier one

**Comment by thilo-behnke** [comment]
Thanks for your feedback! I'll check with @jwilland-tum :)

**Comment by thilo-behnke** [comment]
blocked by https://github.com/ls1intum/Apollon/issues/50

**Comment by thilo-behnke** [comment]
We'll continue working on this now, as we can at least offer Apollon in the markdown editor, even though we don't have the validation functionality.

**Comment by thilo-behnke** [comment]
The recent update of apollon appearently broke a couple of things in my implementation (mostly the rendering of the apollon diagram in the markdown editor preview).

**Comment by thilo-behnke** [comment]
Blocked by https://github.com/ls1intum/Artemis/pull/672.

**Comment by thilo-behnke** [comment]
This PR will be closed, work is continued in https://github.com/ls1intum/Artemis/pull/713.

**Pull request closed without merging**
