### PR TITLE
`General`: Clean up Spring configurations

### PR DESCRIPTION
**Pull request by 4ludwig4**
#### General
:warning: This is a **config change**! :warning:
- [ ] I tested these configs locally (Artemis) and with multiple docker setups (Artemis, MySQL, Jenkins, GitLab, Atlassian Stack).
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
This cleanup should make it easier to integrate new infrastructure setups and more profiles, like the upcoming ones from the deployment workgroup.
With the introduction of "default" secrets in one versioned file instead of multiple places in the documentation, this should make it easier for newcomers.

### Description
This PR separates configurations depending on the used profiles.
It removes configuration value duplicates by restructuring.
We removed some unnecessary configuration values.

#### application-local.yml
As this file is by it's nature not versioned you have to compare it to ``application-local.yml.sample``.
This is necessary as we extracted all secrets from the other configuration files, so that it's less likely that people use default secrets in production setups.
So make sure to include these secrets in your ``application-local.yml``.

Probably you can exclude some of the other values which aren't mentioned in ``application-local.yml.sample`` as for most values you will probably use the new defaults if you are a developer.

### Steps for Testing

- take a look at the used profiles and especially the order how you load them (this is especially important for production systems)
- try starting your every-day Artemis setup with these new configurations!
- try to follow the instructions for copying the `application-local.yml` then startup a basic Artemis setup

#### Code Review
- [ ] Review 1
- [ ] Review 2
- [ ] KIT review
- [ ] UP review
- [ ] feel free to add other universities using Artemis
#### Manual Tests
- [ ] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test

### CODE REVIEW

**Review by krusche — COMMENTED** [review]
to be honest: I am not a big fan of splitting the config into too many files

**Comment by 4ludwig4** [comment]
> to be honest: I am not a big fan of splitting the config into too many files

There might be the option to just use one [big configuration file](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files.multi-document).
But you would still do the splitting for certain profiles, as some keys, especially in the VCS and CI sections, are competing with each other with their default values.

At least, the introduction of the ``application-local.yml.sample`` with versioned defaults is necessary in my opinion and already advertised as the recommended way in the docs instead of editing the ``application-artemis.yml``.

**Comment by krusche** [comment]
I don't see competing values. What do you mean?

**Comment by 4ludwig4** [comment]
> I don't see competing values. What do you mean?

Depending on if you use the Atlassian Stack, the Jenkins/GitLab Stack or Artemis without any VCS and CI you have different default values for certain keys.

Different default values are for instance needed in ``artemis.version-control.ssh-template-clone-url:``.
There are many keys which are just used either for the Jenkings/Gitlab Stack or the Atlassian Stack.
This leads to confusion for newcomers adapting their setups, but also for administrators who don't know what keys belong to which setup variation.

**Comment by krusche** [comment]
If you want to support multiple configurations locally, you should use multiple **local** yml files and add according profiles to the run config. We can add this to the documentation with examples if this helps newcomers.

I have this setup locally as well and presented it once in the dev meeting to other developers. This should be part of the onboarding process / tutorial...

It's bad practice to change values in the "normal" yml files because developers might accidentally commit and push these changes and leak their passwords. We should emphasis on this in the documentation as well, if this is not yet the case.

So splitting the config into multiple yml files only has disadvantages in my opinion. Please revert this change!

**Comment by 4ludwig4** [comment]
> If you want to support multiple configurations locally, you should use multiple **local** yml files and add according profiles to the run config. We can add this to the documentation with examples if this helps newcomers.
> 
> I have this setup locally as well and presented it once in the dev meeting to other developers. This should be part of the onboarding process / tutorial...
> 
> It's bad practice to change values in the "normal" yml files because developers might accidentally commit and push these changes and leak their passwords. We should emphasis on this in the documentation as well, if this is not yet the case.

One of this PR's goal is exactly what you just mentioned :wink:

- In the docs I added a hint box used in multiple places which recommends the usage of the ``application-local.yml`` file.
- I removed all instances in the docs where ``application-artemis.yml`` was modified!

https://artemis-platform--5944.org.readthedocs.build/en/5944/dev/setup/#server-setup

**Comment by Mtze** [comment]
This was a suggestion from my side. For me the spring configuration files were quite hard to understand when I started working on Artemis. It was not obvious to me which values correspond to which external system. I think it is easier to understand if all the possible config values for e.g. Jenkins  are in the `-jenkins.yml`. In the existing spring properties setup we had a lot of duplication and config mismatches that grew over time and are hard to grasp. 

I suggested this change explicitly because we have to simplify and streamline the configuration for the docker and Kubernetes deployments. In these deployments all the config values come from the environment - so these configuration files will no longer be visible to potential Artemis users/administrators anyway (only developers may interact with these files). However, the (default) environment configuration for docker and Kubernetes has to be kept in sync with these spring configurations. In my opinion it is easier to split all the possible spring profiles explicitly so we can mirror changes in the docker-compose or helm values accordingly if a new spring property value has to be added in the future.

In addition to that this PR introduces a sample configuration for the local setup with instructions how to setup Artemis with the local external systems (See new docker configuration in https://github.com/ls1intum/Artemis/pull/5915) which encapsulates only the important spring values that have to be adjusted by a "normal" developer. This should streamline the onboarding of new developers. 

Maybe we can have a short meeting in the next few days to discuss this change in more detail.

**Comment by krusche** [comment]
@Mtze 

At the moment, we are still far away from a Kubernetes setup. Also, there might still be Artemis administrators who want to use the current setup, so we still have to support it for quite some time

I don't see an advantage to duplicate the values for VCS in a bitbucket and gitlab file and then even out comment them because developers should override them in a local file. 

1. Disadvantage: Common values for VCS need to be maintained in multiple places, this is error prone and could also lead to issues
2. Disadvantage: I need to define all values in my local file, even if I don't want to override a default value

I am perfectly fine when we simplify the configuration, but the current changes do not simplify it. Instead, they make it even more difficult in the future.

From my point of view the following split makes absolute sense and must be kept:
1. `application.yml` --> General Spring Config for Dev and Prod
2. `application-dev.yml` --> Development specific adjustments of the Config
3. `application-prod.yml` --> Production specific adjustments of the Config
4. `application-artemis.yml` --> All Artemis specific values
Which values exactly are in 1, 2 and 3, we can certainly discuss and a cleanup would definitely help (the more values we have in `application.yml`, the better it would be. We can discuss whether 4 is necessary

What we should do in my opinion:
1. `application-gitlab.yml` --> move to `application-artemis.yml` (makes sense from my point of view to reduce the number of config files)
2. `application-jenkins.yml` --> move to `application-artemis.yml` (makes sense from my point of view to reduce the number of config files)
**3. To discuss:** `application-artemis.yml` --> move to `application.yml` 

`gitlab` and `jenkins` whould be own entries below `artemis`, like `athene` and `apollon` are.

**Comment by Mtze** [comment]
@krusche 
> At the moment, we are still far away from a Kubernetes setup. Also, there might still be Artemis administrators who want to use the current setup, so we still have to support it for quite some time

Yes, we're still early on in the process for the transition to a k8s setup. This change is one of many steps we should make at some point to ensure consistency between multiple deployment strategies (for now docker, ansible, and "manual"). Existing setups will still possible the same way they are now.   For production setups all the configuration values are supplied via one `application-prod.yml` which encapsulates all deployment specific values. We don't change that in this PR. Only the location of default values are different. 

I agree with the split: 
- `application.yml`
- `application-dev.yml`
- `application-prod.yml`

you suggest (I believe this PR also fully implements this). 

However, I think the split into spring profiles still makes sense. I agree that in this PR the amount of properties files "looks" complicated, but we only encapsulate the necessary config values for each system (So sort of "information hiding"). 
With the suggested solution a new developer who is concerned with e.g. gitlab/jenkins, can view and access all the interesting configuration values at a glance in the respective files. With the monolithic `artemis.yml` file on the other hand  it is not clear which values are Jenkins related or Bamboo related. Also the creation of custom `-prod.yml` files can be streamlined as all possible options for each external system are mentioned in the respective files. 

Regarding the disadvantages  you mentioned: 
1. Yes, if new common VCS or CI configurations are added, they have to be added to all the respective VCS and/or CI configurations. But I don't think this is a bad thing: New common values are rare and have to be tested very thoroughly  anyway. Explicitly adding the values to the files implies that the developer has thought about the value wrt. the external system. I would also add that most of the (in the end) common values start with an implementation/configuration for only one of the external systems and then are gradually expanded for the other options. 
2. The `local` configuration will not change (correct my if I'm wrong @4ludwig4). Existing setups should still be functional after this PR is integrated. This solution only introduced a new layout of the `local.yml` but the core idea is the same. The local file encapsulates all the config values a developer has to provide for Artemis to work in the IDE. In this file we provide templates for all the external systems which can be un-commented depending on the developers preference/setup. 


Regarding 
> gitlab and jenkins whould be own entries below artemis, like athene and apollon are.

I don't think that this is a good solution on its own, because we are no longe on the same level of abstraction in the config files (`artemis.continuous-integration: {}` -> `artemis.jenkins: {}`. 
We would need the same entries for jira, bitbucket and bamboo then. This would be a large (and breaking) change.  If we want to go that route, I'm up for it but I still belief each system should have its own default config file. 



I'll try to summarize the advantages and disadvantages of this change from my point of view

Advantages: 
- Clear separation of config values for each external system 
- Easy (initial) setup for new developers - They only have to use the sample `-local.yml`
- Dependable config values ("If I load the `jenkins` profile I get the correct default values from `application-jenkins.yml` and have to provide the deployment specific values via `-prod.yml` or  `-local.yml`. I can see all possible option in the `-jenkins.yml` file")
- Future proof: We can use the same config layout for k8s and the docker environment configuration. 


Disadvantages 
- We have more files in the resources folder (I don't think this is a problem - we had already quite a few config files)
- New common values have to be added to multiple locations (See my argument from above)


After all it is a matter of preference I guess. So if you're absolutely against this change we don't have to integrate it. But I hope we can still discuss this once more as I think this is conceptually a valuable addition/simplification in the long term. This PR is still in an early stage after all.

**Comment by 4ludwig4** [comment]
Regarding the split of the configuration files, it was decided in [this developer meeting](https://confluence.ase.in.tum.de/display/ArTEMiS/Artemis+Developer+Meeting+-+2023-01-13) that we will split the spring configuration files and create a configuration file for each profile.

I will now resolve the merge conflicts and retest this PR.

**Pull request closed without merging**
