### PR TITLE
`Development`: Upgrade to Angular 18

### PR DESCRIPTION
**Pull request by JohannesWt**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.

### Motivation and Context

This PR fixes issues preventing the upgrade to Angular 18

Due to the version changes the following things mainly have been changed:
* add a tracking id to @for loops in Angular
* upgrade loadings spinners to new syntax of FontAwesome
* fix tests due to deprecation

### Description

In this PR several issues have been resolved which prevented the upgrade to Angular 18. Using `[styles]` in a component is not supported anymore. Therefore the affected places have been mainly restructured using bootstrap classes and some custom (but simplified) css. Additionally the `[spin]` attribute of fa-icons is not supported anymore which also has been replaced by its new alternative. 
Also quite a lot of tests had to be refactored due to changes/deprecation of Angular or some other npm packages

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Tested in Testing session. Did not find any problems

**Review by az108 — DISMISSED** [review]
Tested in Testing Session, no errors were found

**Review by EneaGore — DISMISSED** [review]
Tested on TS4. Did not encounter any issues.

**Review by BBesrour — DISMISSED** [review]
Demonstrated and tested in a testing session

**Review by coolchock — APPROVED** [review]
tested in testing session, no weird behaviour observed

**Review by krusche — DISMISSED** [review]

**Review by pzdr7 — APPROVED** [review]
Code

**Review by marlon-luca-bu — DISMISSED** [review]
Code

**Review by sarpsahinalp — APPROVED** [review]
Code

**Review by krusche — APPROVED** [review]

**Pull request merged**
