### PR TITLE
[Feature] Always show failed buildlogs in result details

### PR DESCRIPTION
**Pull request by derLalla**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

In case we received any feedback, any build result would be ignored and not shown in the result details modal. 

### Description

In case we have received a failed build log, it is getting displayed together with the feedbacks. 

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Create a programming exercise with the setups described below
4. Now create an SCA issue (e.g. in Java wrap code in redundant curly braces) and let the build fail (e.g. omitting a semicolon)
5. Verify that the result details shows the feedback and also the failed build logs
6. It should be shown in Online Code Editor, Course Exercise Detail, Course Exercise Row and Exams (anywhere where the result is accessible)

The following scenarios need to be tested (in total 8 programming exercise setups):
- Course + exam exercises
- With and without SCA enabled
- With and without online code editor

### Test Coverage

no changes.

#### SCA Feedback + failed build logs:
image

### CODE REVIEW

**Review by SimonEntholzer — APPROVED** [review]
I'm not sure if it already works as intended. E.g. when i have an SCA issue (with not failing build), and submit, it shows the correct SAC errors.
<details>


then, when I let the build fail it does not show the SCA errors anymore.



The issue: When an mistake is detected that breaks the build, the SCA is not run anymore (?, or only partially) 

the orange exclamation marks only show up if the build does not fail.
</details>
---> 
the sca is only tested if the build-failing error comes after the SCA issue.



I guess this issue is not really connected to this PR, so for all the places where I tested it, it worked as inteded: if the SCA error comes before the syntax error.

**Review by EneaGore — DISMISSED** [review]
I experienced the same behaviour as @SimonEntholzer

**Review by airelawaleria — DISMISSED** [review]

**Review by airelawaleria — COMMENTED** [review]
ups, sorry, wrong pr approve

**Review by krusche — CHANGES_REQUESTED** [review]
* Please add a section title "Build error" before the bulldogs
* Show this section and the build logs only when they actually exist (i.e. when the build failed, which should be indicated in the submission)
* Build logs with compile errors are more important than static code analysis issues, so please show them first

**Comment by krusche** [comment]
The testing steps need to be more extensive. We should test all exercise configurations, i.e.
* Course + exam exercises
* With and without SCA enabled
* With and without online code editor

this means at least 8 programming exercises

@derLalla please update the testing steps accordingly

To all the testers: Please clean up those programming exercises after testing)

**Comment by derLalla** [comment]
it really depends on the SCA issue, so if there is a build error, the SCA tools which are used by the build agent are not run or also fail. 
What this PR is trying to fix is that if there are failed build logs AND there is SCA feedback, that both are getting shown instead of just the SCA feedback

**Comment by derLalla** [comment]
> * Please add a section title "Build error" before the bulldogs
> * Show this section and the build logs only when they actually exist (i.e. when the build failed, which should be indicated in the submission)
> * Build logs with compile errors are more important than static code analysis issues, so please show them first

done in 48fd0a59d4d5fcb54be29f9b89aa1215da5ddb70

**Comment by tiffca** [comment]
I couldn't test the no editor for exams b/c I always have an error with cloning the repository in exams. 

Noticed though for code-editor=enabled, SCA=enabled, the build log doesn't show the SCA error for exams. Not sure if this is intended, just noticed the behavior was different 

code-editor=enabled, SCA=enabled, regular exercise (not an exam) 
- the build output shows the SCA error 
image


code-editor=enabled, SCA=enabled, exam mode 
- the SCA error shows in the "Build failed" and the code editor (highlighted with green), but not in the build output (highlighted with red).
image

**Review by FrankeLukas — APPROVED** [review]

**Review by SimonEntholzer — APPROVED** [review]

**Review by tiffca — APPROVED** [review]
Behavior looks mostly the same (some more build logs are showing for me), hence approving

**Comment by derLalla** [comment]
> Behavior looks mostly the same (some more build logs are showing for me), hence approving

which test server did you use? Usually are these more detailed build logs not shown

**Review by airelawaleria — APPROVED** [review]

**Review by ivanchimeno — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
