### PR TITLE
`Programming exercises`: Update template dependencies for java exercises

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
Updates the standard dependency versions in the Java PE templates to their newest versions.

### Description
Also enhances the existing TemplateIntegrationTest to check if the tests can be executed when the testwise coverage analysis is enabled. The maven testwise coverage feature was broken in its current form (the dependency got renamed), this new test can now catch such issues.

Related docker PR: https://github.com/ls1intum/artemis-maven-docker/pull/134

### Steps for Testing
Create a new programming exercise and check that everything still works.

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by aplr — COMMENTED** [review]
Tested in testing session, changes don't seem to break anything

**Review by aplr — APPROVED** [review]

**Review by reschandreas — APPROVED** [review]
Tested in testing session. Looks good, the test still ran through 👍🏻

**Review by nityanandaz — APPROVED** [review]
Code looks neat

**Review by sleiss — APPROVED** [review]
Tested during the testing session, worked as expected.

**Pull request merged**
