### PR TITLE
`Programming exercises`: Update dependencies in Java templates

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context
Update default dependencies and bundled gradle version.

### Steps for Testing
1. Create a new Java programming language (once maven once gradle)
2. Check that executing test cases and SCA still works correctly.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by DominikRemo — APPROVED** [review]
Code LGTM
Tested on ts2 and works as expected 🚀

**Review by JohannesStoehr — APPROVED** [review]
Updated versions look good to me.
Should we also test the changes in the labeler.yml?

**Comment by Strohgelaender** [comment]
> Should we also test the changes in the labeler.yml?

We cannot really test this because GitHub always executes actions from the develop-branch. You can see however that the `template` label was not added automatically to this PR, even though template files got changed. This was due to the fixed typo.

**Review by laadvo — APPROVED** [review]
Tested on ts1, test cases still get executed and SCA works as expected

**Pull request merged**
