### PR TITLE
[Exam] Bugfixes: Exam and Quiz navigation

### PR DESCRIPTION
**Pull request by filip-gregurevic**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Faulty quiz navigation display.
Remaining time _jumping_ when displaying seconds.
Checkmark icon not being shown causes confusion.

### Description

Adjusted the quiz navigation bar
Added min-width to remaining time, so it doesn't _jump_ when displaying seconds.
Checkmark icon is displayed when exercises are synced (so when the students navigates to another exercise)

### Steps for Testing

1. Log in to Artemis
2. Create an exam with multiple quiz questions in one quiz
3. Make sure all are displayed correctly in the view
4. Make sure the _checkmark_ icon is displayed when the exercise is synced
5. Make sure the remaining time doesn't _jump_ when displaying seconds (<10min)

### Screenshots

Bildschirmfoto 2020-06-30 um 15 09 36
Bildschirmfoto 2020-06-30 um 15 09 45
Bildschirmfoto 2020-06-30 um 15 10 26

### CODE REVIEW

**Comment by stefanwaldhauser** [comment]
image
The UI has some scaling problems, where elements overlap.

**Comment by stefanwaldhauser** [comment]
I do not know if this is intended behaviour but once a checkmark has turned blue i never got it to turn yellow again (for example by changing my answer). What is the intended behaviour here?

**Comment by Varnika-Tyagi** [comment]
Works fine for me.
No time skips and the navigation bar looks fine. 
quiz1

**Comment by krusche** [comment]
@filip-gregurevic please have a look into the overlapping issue in another PR, then I'll merge this one as it contains an important visual improvement

**Pull request merged**
