### PR TITLE
Replace Adding Empty Strings by String.valueOf

### PR DESCRIPTION
**Pull request by MaisiKoleni**
### Checklist
- [x] I ran all server tests to check that they still work.

### Motivation and Context
Resolve these issues https://app.codacy.com/gh/ls1intum/Artemis/issues?categoryType=Performance and be more explicit about the string conversion. This mostly affects test code.

### Description
- Replace `"" + ...` and `... + ""` by `String.valueOf(...)`. 
   This yields the same results (`String.valueOf` is null-safe as well).

### Steps for Testing
1. Check the code
2. Run the tests

### CODE REVIEW

**Review by kloessst — APPROVED** [review]
Changes look good to me.

**Review by balazs-czopf — APPROVED** [review]
Not sure whether these changes make that big a difference since it is mostly used in tests and the outcome should be pretty much the same if I´m not mistaken. But it is mostly referred to as best practice so why not do it this way. 😄

**Review by JonasPetry — APPROVED** [review]
Changes look good to me 👍

**Review by sjagla27 — APPROVED** [review]
Looks good.

**Review by filip-gregurevic — APPROVED** [review]

**Review by stefanwaldhauser — APPROVED** [review]
Good job!

**Review by sleiss — APPROVED** [review]

**Review by fde312 — APPROVED** [review]
All tests worked for me locally and changes look good! 👍

**Review by TobiasPr — APPROVED** [review]

**Review by krusche — APPROVED** [review]

**Pull request merged**
