### PR TITLE
`Learning paths`: Fix new student UI for empty competencies

### PR DESCRIPTION
**Pull request by JohannesStoehr**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I **strictly** followed the [server coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).

### Motivation and Context

The navigation in the new UI for learning paths did not properly work in edge cases.

### Description

The server now correctly searches through all competencies to find current and previous/next learning objects for the navigation.
The server no longer throws exceptions if the learning path does not yet/no longer contains any learning objects.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student

1. Log in to Artemis
2. Create multiple competences and link some to learning objects (lecture units are enough)
3. Participate as student in the learning and check that the navigation works no matter how many learning objects you completed
4. Delete all lecture units and check that the student view does not show any errors (doesn't have to be pretty yet)

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by N0W0RK — CHANGES_REQUESTED** [review]

**Review by Jan-Thurner — CHANGES_REQUESTED** [review]
tested on TS2, and when opening the course overview, an internal server error was thrown. 
image

When testing on TS3, Only one Competency can be linked to a lecture. The first two competencies are linked to a lecture unit, two more are not linked to a lecture unit. When navigating through the learning path, I "skipped" the first unit and marked the second one as completed. That led to the order of the units being modified.
Order in the beginning: 
image

Order at the end:
image

The order in the drop_down navigation menu stays the same, but the order when navigating to the previous or next competency changes. 

Is this intended?

**Comment by JohannesStoehr** [comment]
> tested on TS2, and when opening the course overview, an internal server error was thrown.

Ts2 is currently broken. This is not related to this PR.

> When testing on TS3, Only one Competency can be linked to a lecture. 

You can select multiple competencies per lecture unit.

> The first two competencies are linked to a lecture unit, two more are not linked to a lecture unit. When navigating through the learning path, I "skipped" the first unit and marked the second one as completed. That led to the order of the units being modified. 

That is ok, the order of competencies also depends on their mastery as well as the mastery of predeceeding competencies.
After reloading the page, the dropdown should also match the navigation again. In normal circumstances (no empty competencies) this should also not be a problem, but the navigation should at least not throw exceptions in such a case.

**Review by JohannesWt — APPROVED** [review]
Code 👍

**Review by MaximilianAnzinger — APPROVED** [review]

**Review by N0W0RK — COMMENTED** [review]
Code 👍

**Pull request merged**
