### PR TITLE
bugfixes modeling editor + quiz exercises

### LINKED ISSUE #2142: Bugs related to modeling exercises, found in PR #2135
### Describe the bug

This is a ticket which summarizes the errors and bugs related to modeling exercises which were found in PR #2135 

I faced a problem when assessing modeling exercises. 
image

Happened after I assessed a use-case model and clicked on the submit button on the page. Did not look further into the issue and could not reproduce it

Another issue that happened to me, which happens after the due date passed. The size of the container which includes apollon becomes too small, see screenshots, probably unrelated to the PR
image
image

Also had a problem with importing exercises which where created from Apollon:
image
image

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

### PR DESCRIPTION
**Pull request by TobiasPr**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)

### Motivation and Context

Fixes #2142 
Additionally I changed the logic when `pendingChangesCache` is set to fals. This now only happens when the saving was successful and not only when the save function is called

### Description

- Changed the event when pendingChangesCache is set to false (only if saving was successful)
- replaced the way we create deep copies, instead of `JSON.parse(JSON.stringify(object))` we now use lodashs `deepCopy`
- removed the reference from questions to quizexercise (setting undefined) to break circle when serializing

#### Quiz Exercise

1. Test creating quizzes (MultipleChoice, DragAndDrop, ShortAnswer)
2. Test importing quizzes (MultipleChoice, DragAndDrop, Apollon DragAndDrop, ShortAnser)
3. Edit quiz with imported questions - more specifically edit the imported questions.
4. Check if changes are only done to the quiz with imported questions and to the original quiz questions

#### Modeling Exercise

1. create a modeling exercise
2. submit modeling exercise
3. assess modeling exercise and click on submit while participation page of modeling exercise is still open
4. no console error should be thrown
5. you get a notification in Artemis that there is a new assessment for your submission 

### Test Coverage

* quiz-exercise-detail.component.ts 29 -> 58%

### CODE REVIEW

**Comment by krusche** [comment]
Thanks for the fixes. I am a bit confused. Most changes are with respect to quiz exercises.
The error in the screenshot in #2142 which was related to the `modeling-assessment.service.ts` does not seem to be fixed.

Can you please double check?

**Review by schultek — APPROVED** [review]
I did not encounter any errors with creating quiz exercises or importing and editing questions for quiz exercises. Well done. I'm also confused about the title though.

**Comment by TobiasPr** [comment]
> Thanks for the fixes. I am a bit confused. Most changes are with respect to quiz exercises.
> The error in the screenshot in #2142 which was related to the `modeling-assessment.service.ts` does not seem to be fixed.
> 
> Can you please double check?

I did and I was a bit uncreative when I tried to reproduce. In the error we can see that it comes from the websocket, so it occurs when an assessment is submitted, while the student has the participation page open. I will fix that issue in this PR, converted back to draft

**Review by sjagla27 — APPROVED** [review]
Worked as expected.

**Review by krusche — APPROVED** [review]

**Pull request merged**
