### PR TITLE
`Development`: Fix Markdown preview functionality

### LINKED ISSUE #6359: `Programming exercises`: Problem statement preview remains blank
### Describe the bug

When creating a problem statement for a programming exercise in the markdown editor and clicking on Preview, the problem statement does not show up. To actually see the problem statement displayed, the entire exercise needs to be saved since the problem statement cannot be previewed while editing.

### To Reproduce

1. Go to Course Management and select a course
2. Click on Generate a Programming exercise or edit an existing one
3. Scroll down to Problem Statement
4. Edit the problem statement and click on Preview
5. Preview remains blank

### Expected behavior

The edited problem statement should appear when clicking on Preview. The behavior should be the same as in other types of exercises.  

### Screenshots

image

### Which version of Artemis are you seeing the problem on?

6.1.1

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
Closes #6359

### Description
We currently use a `ContentChild` to determine whether a component uses their own or a custom preview. However, during my testing, this value was always undefined. According to the documentation it "does not retrieve elements or directives that are in other components' templates, since a component's template is always a black box to its ancestors".

Instead, we not use a boolean input to determine if a custom preview should be shown.

Also, since the template uses an id-selector (`#preview`), the id must also be set for all the preview childs.

### Steps for Testing

Prerequisites:
- 1 Instructor

Use the markdown editor at the following places and check that the prview works correctly:
- Editing programming exercises
- Editing multiple-choice questions
- Editing a posting

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by TheZoker — APPROVED** [review]
Tested in testing session. Everything works as before 👍 
Just noticed two bugs (probably existed before):
1. When previewing a multiple choice question, always all answers get selected when the user selects one
2. On the programming exercise creation page the preview is cut of by a couple of pixels:
image

**Comment by simon-hng** [comment]
Otherwise preview works as expected from before

Follow up issues not directly related to this PR:
- Preview is clipped at the bottom
image
- Quiz preview click selects all options
image

**Review by danielbode — APPROVED** [review]
Tested on ts1 during a testing session. The preview is now displayed correctly everywhere. Nice bugfix!

**Review by DominikRemo — APPROVED** [review]
Tested on ts1 during a testing session. Preview is displayed, though cut at the bottom for programming exercises (see other comments)

**Comment by Strohgelaender** [comment]
@TheZoker Thanks for testing, both of these issues are already known:
1. It selects all since the selection is done by the answer option id (this has to be the case since they are usually in a random order and we want to allow saving and re-loading e.g in the exam case). However while creating the questions, the id is not yet generated since this will be done on the server side and therefore all of them have "the same" aka no id. I once looked into it but I did not figure out a small solution here, and since it's a rare edge case (selecting an aswer while creating the queastion) I don't think we need to add more compliacted logic for this case.
2. This is also known, but I'm yet to look into this. But it's out of scope for this PR.

**Pull request merged**
