### PR TITLE
`Programming exercises`: Refactor local VC and local CI services

### PR DESCRIPTION
**Pull request by frederik-kt**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I documented the Java code using JavaDoc style.

### Description
This PR improves the the way some of the services connected to local VC and local CI are connected, cleaning up the architecture. No functionality is added or taken away.

## Important: This PR only affects the local VC and local CI system, so you need to deploy it on [Test Server 11](https://artemis-test11.artemis.in.tum.de/) test server for the "localvc" and "localci" profiles to be active.

Prerequisites:
- 1 Instructor
- 1 Student

1. Log in to Artemis as the instructor
2. Navigate to Course Management
3. Create a programming exercise and make sure the template and solution repository are correctly built.
4. Log in as the student, clone the repository for the exercise to your local machine.
5. Push and make sure your changes are built correctly.

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Exam with a Programming Exercise

1. Log in to Artemis
2. Participate in the exam as a student and make sure your submission via the online editor is built correctly.

#### Performance Review
- [x] I confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

### Test Coverage
| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [ArtemisGitServlet.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4937-2/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.config.localvcci/ArtemisGitServlet.html) | 100% | ✅ |
| [JGitServletConfiguration.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4937-2/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.config.localvcci/JGitServletConfiguration.html) | 100% | ✅ |
| [LocalCIBuildJobExecutionService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4937-2/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.localci/LocalCIBuildJobExecutionService.html) | 96% | ✅ |
| [LocalCIConnectorService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4937-2/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.localci/LocalCIConnectorService.html) | 85% | ✅ |
| [LocalCIContainerService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4937-2/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.localci/LocalCIContainerService.html) | 81% | ✅ |
| [LocalVCPostPushHook.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4937-2/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.localvc/LocalVCPostPushHook.html) | 90% | ✅ |
| [LocalVCServletService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4937-2/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.localvc/LocalVCServletService.html) | 94% | ✅ |
| [ProgrammingExerciseParticipationService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS4937-2/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.programming/ProgrammingExerciseParticipationService.html) | 73% | ✅ |

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Refactored code looks good to me

**Review by dakennguyen — COMMENTED** [review]
I tested on ts11. Normally I remember when I submit the code, there will be a loading icon, but now nothing happens. After sometimes I got the result for the build. The same thing when I create a programming exercise: there's also no loading indicator for the templates

### Reply
Thanks for testing! Communication over WebSocket, which is needed for the loading indicator to appear, is a bit unreliable at times unfortunately. This is a general issue and is not connected to this PR. It should however appear in the majority of times.

**Review by rriyaldhi — APPROVED** [review]
Tested the exam mode on TS11 and works as intended.

**Review by laadvo — APPROVED** [review]
Tested on ts11, working as expected :+1:

**Review by dakennguyen — APPROVED** [review]
> Thanks for testing! Communication over WebSocket, which is needed for the loading indicator to appear, is a bit unreliable at times unfortunately. This is a general issue and is not connected to this PR. It should however appear in the majority of times.

thanks for the clarification :)

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Review by Mtze — APPROVED** [review]
The Refactoring is looking good to me. Thank you!

**Review by bassner — APPROVED** [review]

**Pull request merged**
