### PR TITLE
[Enhancement] Remove Jsoup from Jenkins Job Manipulation

### LINKED ISSUE #3499: ESC-Characters are not correctly (re-)encoded when updating config.xml in Jenkins
Context is an Artemis-Installation with Jenkins (and GitLab).
### Describe the bug
The standard jenkins template for C-courses contains an encoded ESC-Character (`&#x1b`) in the snippet below:
```
  post {
            cleanup {
                sh '''
                   sed -i &apos;s/&#x1b;//g&apos; test-reports/tests-results.xml&#xd;
                   sed -i &apos;s/&lt;skipped/&lt;error/g&apos; test-reports/tests-results.xml&#xd;
                   sed -i &apos;s/&lt;\/skipped&gt;/&lt;\/error&gt;/g&apos; test-reports/tests-results.xml&#xd;
                   mv test-reports results
                   '''
                sendTestResults credentialsId: '#jenkinsNotificationToken', notificationUrl: '#notificationsUrl'
                cleanWs()
            }
        }
```
In `JenkinsJobPermissionsService.addInstructorAndEditorAndTAPermissionsToUsersForJob` the config.xml-template is loaded correctly from Jenkins and parsed into a  `org.jsoup.nodes.Document`.

After updateing it with permissions, it is written back to Jenkins as a String. This string however contains the ESC-character as unencoded character:
image

This causes an exeption in Jenkins
```
Caught unhandled exception with ID a57c7285-d280-427c-8234-9454a32c903a
javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 135; columnNumber: 35; An invalid XML character (Unicode: 0x1b) was found in the element content of the document.
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:740)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:343)
	at jenkins.util.xml.XMLUtils._transform(XMLUtils.java:209)
	at jenkins.util.xml.XMLUtils.safeTransform(XMLUtils.java:81)
```

#### To Reproduce

Use an Artemis-Installation with Jenkins (and GitLab).

1. SetUp a new C-Programming Exercise
2. Click on 'Save'
3. See error
   - in User Interface
   - in Jenkins Logfiles

#### Expected behavior
The XML-String is decoded and re-encoded according to the XML-standard.

Our workaround is, to use a different template (without ESC-characters).

If you must work with the built-in template and C-Exercises this is a severe problem.
#### Screenshots
 
See above

### Environment
<details><pre>
 - OS: Artemis Windows, Jenkins Linux
 - Browser: Brave
 - Version: Artemis 4.12.0
</pre></details>

#### Additional context
Not relevant

#### Output in Web Console
Not relevant

### PR DESCRIPTION
**Pull request by ivanchimeno**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Server: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/server.html).
- [x] Server: I added multiple integration tests (Spring) related to the features (with a high test coverage)
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

Artemis uses JSoup to parse and manipulate the configuration files of Jenkins jobs. Since JSoup is not recommended for manipulating XML, errors and bug can occur such as #3499  and #3484. 

### Description

This PR removes JSoup from the classes that manipulate Jenkins jobs and instead uses the native parser from Java. This PR should resolve #3499.

### Steps for Testing

This PR should be tested on TS2.

1. Log in to Artemis
2. Navigate to Course Administration
3. Generate a new C programming exercise -> should work
4. Participate in it -> should work and build results should display

### Test Coverage

JenkinsService.java 88%
JenkinsJobPermissionsService.java 71%
JenkinsJobPermissionsUtils.java 94%
JenkinsJobService.java 63%
XmlFileUtils.java 69%

### CODE REVIEW

**Review by FrankeLukas — APPROVED** [review]

**Review by imstreetspirit — APPROVED** [review]
tested on ts1 during the testing session. works as described

**Review by SimonEntholzer — APPROVED** [review]
Tested on TS2, works fine.

**Review by ndricimrr — APPROVED** [review]
Tested on TS2 with newly created Java and C exercises. Code builds correctly👍

**Review by FlorianGlombik — APPROVED** [review]
Tested it on ts2 and creating and participating in the template exercise worked fine. I participated using the online code editor and the build results were updated!

**Pull request merged**
