### PR TITLE
`Assessment`: Change naming for button when assessing a programming exercise for  the first time

### PR DESCRIPTION
**Pull request by marlon-luca-bu**
#### General

- [X] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [X] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [X] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Client
- [X] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [X] I added multiple screenshots/screencasts of my UI changes.
- [X] I translated all newly inserted strings into English and German.

### Motivation and Context

The Button for starting an assessment, **in case you have not assessed a submission from this exercise before**, was a bit misleading and confusing. Changing the label to a more fitting description would be better. 

### Description

Change "Start participating in the exercise" to "Start manual assessment"

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Students
- 1 Programming Exercise 

1. Log in to Artemis
2. Create a new Programming exercise
3. Log in as a student and submit exercise
4. Go to the Assessment Dashboard of the exercise as an instructor (Important: This instructor should not assessed other submissions in the same exercise before, otherwise the button will not be shown)

#### Performance Review
- [ ] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2
#### Exam Mode Test
- [ ] Test 1
- [ ] Test 2

### Screenshots

image

### CODE REVIEW

**Review by LenaKahle — APPROVED** [review]
Approve, tested on legacy ts11.

**Review by Strohgelaender — APPROVED** [review]

**Review by rstief — APPROVED** [review]
Code LGTM

**Review by egekurt123 — APPROVED** [review]
Manually tested on ts5, works as expected

**Review by xHadie — APPROVED** [review]
_Manually tested on TS11_Legacy_
Works as expected, thanks for handling this!

**Review by Ceiridge — APPROVED** [review]
Works as expected on ts5. There aren't any code changes anyway.
image

**Pull request merged**
