### PR TITLE
`Communication`: Migrate posts to course-wide channels

### PR DESCRIPTION
**Pull request by lennart-keller**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

With #7437 posts are no longer shown in the communication tab. Therefore, they are migrated to the new course-wide channels

### Description

Legacy lecture, exercise, and course-wide-topic posts are migrated to the corresponding course-wide channels.
If channels for lectures, exercises, or course-wide topics do not exist for a course, they are created. Posts are linked with the corresponding channel. Finally, the reference from posts to a lecture/exercise/course-wide-topic is set to null, so that they only have a reference to a conversation.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course with communication and messaging enabled

1. Do not deploy yet! 
2. Delete (some) general course-wide, lecture, and exercise channels from a course
3. Choose long names/names with special characters/... for lectures/exercises where you deleted a channel
4. Deactivate messaging in the course
5. Create course-wide posts on the communication tab
6. Create lecture/exercise posts on the corresponding lecture/exercise details page for lectures/exercises where you deleted channels
7. Deploy the migration
8. Activate messaging in the course
9. Check that all channels have been created and that posts (which are now messages) are shown in the channels. No posts should be shown in the communication tab anymore

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

Same as develop

### Screenshots

No UI changes

### CODE REVIEW

**Review by MaximilianAnzinger — APPROVED** [review]
Migrations look good
Seems to work fine with both Postgres & Mysql 👍

**Review by jakubriegel — DISMISSED** [review]
SQL code looks good

**Review by nityanandaz — APPROVED** [review]
Core review; SQL is well structured

**Review by basak-akan — APPROVED** [review]
Demonstrated in testing session on legacy TS2 and TS4 worked as expected.

**Review by florian-glombik — APPROVED** [review]
Migration worked fine during testion session on ts2

**Review by vinceclifford — APPROVED** [review]
Approved during testing session

**Review by MaximilianAnzinger — APPROVED** [review]

**Pull request merged**
