### PR TITLE
`Programming exercises`: Speed up Gradle builds on Jenkins

### PR DESCRIPTION
**Pull request by b-fein**
#### General

- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Changes affecting Programming Exercises
~~- [ ] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).~~
- [x] I tested **all** changes and their related features with **all** corresponding user types on a local setup (Jenkins and Gitlab).

### Motivation and Context
When only a single Gradle command is executed and then the Docker container is thrown away afterwards, there is no benefit in starting the Gradle daemon. This additional overhead can therefore be saved.

### Description
Gradle has a flag `--no-daemon` that tells it to not start it.
For the static code analysis configuration the daemon is still used, as the tests and the static code analysis are split into two Gradle commands running sequentially.

I don’t know enough about the Bamboo build plans to make the same changes there, but I suppose the same optimisation applies there as well.

### Steps for Testing

Prerequisites:
- TS2 or another Gitlab/Jenkins setup
- 1 Instructor
- 1 Newly Created Programming Exercise

1. Check that you receive a build result for the template/solution repository after creating the exercise and/or after making changes to the repositories.

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage
unchanged

### Screenshots
n/a

### CODE REVIEW

**Review by dfuchss — APPROVED** [review]
Change looks good. I'll test it asap

**Comment by b-fein** [comment]
After some re-testing with and without the options I can no longer see the shorter execution time. It is pretty much exactly the same now. It might have had other causes when testing earlier.

Unless someone else can reproduce a speedup or knows other potential benefits of *not* using the daemon, I think the PR can be closed without merging.

**Review by SimonPaul02 — APPROVED** [review]
Tested on TS2, worked as expected after creating a new exercise. I didn't know how to get access  to make changes, but the built was successful

**Comment by ole-ve** [comment]
> After some re-testing with and without the options I can no longer see the shorter execution time. It is pretty much exactly the same now. It might have had other causes when testing earlier.
> 
> Unless someone else can reproduce a speedup or knows other potential benefits of _not_ using the daemon (e.g., when using an image not based on [the default](https://github.com/ls1intum/artemis-maven-docker)), I think the PR can be closed without merging.

I tested a sample Gradle build with and without the `--no-daemon`-flag on our Bamboo-Prelive system. Both builds took the same amount of time (accuracy < 1s).

**Comment by babyygemperor** [comment]
Tested on TS2, felt considerably fast (about 1.5x by feel), works as expected

**Review by yuling-sun — APPROVED** [review]
Tested on TS2. Tested by repeatedly building and testing a solution repository on this build and comparing to another build. There was a noticeable speed of around 1.5x.

**Comment by dfuchss** [comment]
I guess that there is no real time improvement; therefore, I think the PR can be closed :)

I've executed each command in a new docker container:
```bash
git clone https://github.com/ls1intum/artemis-maven-docker && cd artemis-maven-docker/artemis-java-template && time ./gradlew --no-daemon clean test
real    0m22.901s
user    0m3.203s
sys     0m0.460s


git clone https://github.com/ls1intum/artemis-maven-docker && cd artemis-maven-docker/artemis-java-template && time ./gradlew clean test
real    0m21.314s
user    0m3.491s
sys     0m0.337s
```

**Pull request closed without merging**
