### PR TITLE
`Tutorial Groups`: Ensure consistent button styles in tutorial group creation view

### PR DESCRIPTION
**Pull request by dearjasmina**
#### General
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context
This PR solves a small issue: https://github.com/ls1intum/Artemis/issues/6447
The problem pointed that regarding Mode picker and Language were already solved.

### Description
From the issue:
image
----------
I changed it to match the existing style (for Schedule) on that page regarding so that it is consistent.

**New Style:**
image

**Matches the:** 
image

**on the same page.**

### Steps for Testing
To Reproduce:
1. Go to Tutorial Groups
2. Create a New tutor group.

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by pal03377 — APPROVED** [review]
Tested on TS4, code changes also look good 👍 

When going to the Tutorial Groups Configuration, there still is a grey button:
screenshot-2023-06-23_001451

I suggest we change that one as well, but it doesn't have to be within this PR.

**Review by asliayk — APPROVED** [review]
tested on ts2, works as expected

**Review by simon-hng — APPROVED** [review]
Code changes look good

**Review by SabrinaGlatz — APPROVED** [review]
tested on ts5. Works as expected, but in the light mode, I saw that all other buttons that are in the same blue color have a white text. Maybe it would be more consistent if these buttons were also white when the background is blue, but it's just a suggestion: 
image

**Review by bassner — APPROVED** [review]

**Pull request merged**
