### PR TITLE
`Assessment`: Hide example submissions without assessments in tutor training

### PR DESCRIPTION
**Pull request by Olimbia23**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [ ] *Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [ ] *I added `@PreAuthorize` and checked the course groups for all new REST Calls (security).
- [ ] *I implemented the changes with a good performance and prevented too many database calls.
- [ ] *I documented the Java code using JavaDoc style.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [ ] *I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [ ] *I translated all newly inserted strings into English and German.
#### Changes affecting Programming Exercises
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [ ] *I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

[ ] * - not needed

### Motivation and Context

Currently whenever an instructor creates an example submission, an empty example assessment is automatically created.
This causes issues with assessment (tutor) training, since even example submissions with empty example assessments are shown to the tutors. This PR fixes the issue and hence shows to the tutors only the example submissions that have a corresponding assessment created by instructor.

### Description

Example assessment is now not created automatically with example submission, as well as when clicking on edit example submission button, not only feedback but also the whole example assessment is removed. 

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Tutor

Tutors should not see example submissions without example assessments

1. Log in to Artemis as **Instructor**
2. Navigate to Course Management and pick a course
3. Navigate to a Text or Modeling Exercise
4. Create 2 Example Submissions. One with and the second without example assessment
5. Log in as **tutor**
6. Navigate to Course Management and then Exercise Dashboard of the previously mentioned exercise.
7. You should be able to read/assess only those example submission, that have an assessment (see screenshot)

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### After
Tutors should see only those example submissions that have example assessment created by the instructor.

Screenshot 2021-11-30 at 2 52 00 AM

https://user-images.githubusercontent.com/51077603/144029924-23d27f7a-a714-41a1-911b-539b6b70be49.mov

### CODE REVIEW

**Review by MerlinMehmed — COMMENTED** [review]
Tested on TS1 with modeling exercises, and unfortunately, it doesn't work. As described I created 2 example submissions - one of them is assessed, the other not. When I logged in as a tutor I can read both of the submissions.

**Review by Malyuk-A — COMMENTED** [review]
Code looks reasonable.

I have experiences the same behavior as @MerlinMehmed (at least for modeling exercises).
When I simply create a new submission (regardless if the checkbox [x] "use in tutorial" is checked or not) it is displayed for the tutors.

But it worked for text exercises (for me at least).
image


A couple of general questions:
a) 
image
What is this checkbox used for? I do not really understand it (if you should only display example submissions with (valid) example assessments to the tutors (in their tutorial for this exercise and this should be done automatically via this PR) do we still need this checkbox?

b)
image
I think I mananged to break the tutorial several times by not creating an example assessment (times by accident). So as a tutor I was stuck and could not continue (maybe I am also mistaken and did smth wrong?).

c)
I observed multiple times that (prior to the assesment part) (as instructor and tutor) I had access to the drag and drop assessment parts and could drop them inside of the e.g. text answer and this is most likely a bug and should not be possible 
image

**Comment by Olimbia23** [comment]
> Code looks reasonable.
> 
> I have experiences the same behavior as @MerlinMehmed (at least for modeling exercises). When I simply create a new submission (regardless if the checkbox [x] "use in tutorial" is checked or not) it is displayed for the tutors.
> 
> But it worked for text exercises (for me at least). image
> 
> A couple of general questions: a) image What is this checkbox used for? I do not really understand it (if you should only display example submissions with (valid) example assessments to the tutors (in their tutorial for this exercise and this should be done automatically via this PR) do we still need this checkbox?
> 
> b) image I think I mananged to break the tutorial several times by not creating an example assessment (times by accident). So as a tutor I was stuck and could not continue (maybe I am also mistaken and did smth wrong?).
> 
> c) I observed multiple times that (prior to the assesment part) (as instructor and tutor) I had access to the drag and drop assessment parts and could drop them inside of the e.g. text answer and this is most likely a bug and should not be possible image

Hey Alex, Thank you for testing my PR. 
For me it works on TS1 for both model and text. I uploaded a demo in PR description.
Can you please retest it again?

Regarding your general questions:
a)
_"Tutor needs to assess this submission"_ checkbox is used by the Instructor when creating an example submission.
The meaning behind it: 
**if not checked:** during the training, tutors will be able to see the example assessment. 
**If checked**: during the training, tutors will not be able to see the example assessment but they have to asses the example submission themselves. 

Regarding your other two points. If you want you can create separate Github issues for these cases with the steps to reproduce and somebody can have a look at them. 
I won't fix them here, as they are out of scope for this PR.

**Comment by Olimbia23** [comment]
> Tested on TS1 with modeling exercises, and unfortunately, it doesn't work. As described I created 2 example submissions - one of them is assessed, the other not. When I logged in as a tutor I can read both of the submissions.

Hey @MerlinMehmed 
Thank you for testing my PR. 
For me it works on TS1, could you please retest it again? I added a demo in the PR description.

**Comment by MerlinMehmed** [comment]
@Olimbia23 I retested the PR by creating a new exercise and it worked. I used an already existing exercise when I first tested it, could that be the reason for the issue and is it supposed to work for already existing exercises? Here is the link to the exercise I used for a reference (https://artemistest.ase.in.tum.de/course-management/482/assessment-dashboard/9960)

**Review by willergeorg — APPROVED** [review]
Tested on TS2 with a modeling exercise. It works for me.

**Review by MerlinMehmed — APPROVED** [review]
Thank you for the clarification @imstreetspirit. Approving!

**Comment by imstreetspirit** [comment]
> I observed multiple times that (prior to the assesment part) (as instructor and tutor) I had access to the drag and drop assessment parts and could drop them inside of the e.g. text answer and this is most likely a bug and should not be possible

@Malyuk-A Hi Alex, I changed this recently with this [PR](https://github.com/ls1intum/Artemis/pull/4104). Because, we are using drag and drop instructions in external platforms like Apollon and Orion. The `mimetype` has to be `text/plain` to enable dragging in those platforms(especially Orion), That's why you see the this after dragging and dropping into the text submission editor in Artemis. However this is not the use case of the assessment instructions. To use drag and drop instructions, first you have to select the text block you want to assess, then you need to drag ad drop it into the feedback editor. If someone has better solution to allow dragging in external platforms, it can be applied, and it will require changes in Orion and Apollon side.

**Review by Malyuk-A — APPROVED** [review]
Tested on TS1 again. Thank you for the video and explanation. Works as described 👍

**Review by cremertim — APPROVED** [review]
code changes lgtm

Tested on ts3 with modelling and text exercises. Everytihng worked as expected

**Review by filip-gregurevic — APPROVED** [review]
Code changes look good to me 👍🏼

**Review by argertboja — APPROVED** [review]
Tested on TS1 and it works as expected!

Well done @Olimbia23 🙂

**Pull request merged**
