### PR TITLE
Bugfix/quiz exercises/space at start of lines

### LINKED ISSUE #2569: Show Spaces at Start of Lines in Quiz Exercises
### Describe the bug
When you create a Quiz Exercise of type Short Answer Question with spaces at the start of lines inside of the markdown editor, these spaces are removed in the exercise preview, see [example](https://artemis.ase.in.tum.de/course-management/84/quiz-exercises/2580/preview). This is a problem for fill-in-the-blank coding exercises, as the indentation is removed.

#### To Reproduce

1. Log in as instructor.
2. Click 'Course Management' at the top.
3. Click 'Exercises' of the respective course.
4. Under 'Quiz Exercises' click 'Create Quiz'.
5. Click 'Add Short-Answer Question'.
6. Add a code to the editor, such as the following: 

```
`public class Foo {`
`    public `[-spot 1]`() {}`
`}`
[-option 1] Foo
```
7. Click 'Save'.
8. Go back and click 'Preview Quiz'.

#### Expected behavior
The indentations and the respective spaces at the start of lines are shown in front of `public Foo() {}`.

#### Screenshots
Markdown:
image

Preview:
image

### PR DESCRIPTION
**Pull request by ivohashamov**
### Checklist
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context

Fixes #2569 

### Description

Added line indentation support for the short answer quiz exercises

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Administration
3. Navigate to Exercises
4. Create a quiz exercise with a short answer question
5. Add a code to the editor, such as the following:
```
`public class Foo {`
`    public `[-spot 1]`() {}`
`}`
[-option 1] Foo
```
6. Save
7. Check if the indentation is present in (pre)view mode.

### Screenshots

image

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested on ts3. Works fine

**Review by JohannesWeiss — DISMISSED** [review]
Tested on ts3 and works as intended!

**Review by LudwigWeide — APPROVED** [review]
Tested on Ts1. Approve.

**Review by marvinchimeka — DISMISSED** [review]
Works fine and looks good

**Review by EneaGore — APPROVED** [review]
Approve.

**Review by simonzilker — APPROVED** [review]
Looks good!

**Review by kloessst — COMMENTED** [review]
Worked fine. Could you add some client tests for the new functions?

**Review by tiffca — DISMISSED** [review]
Tested successfully

**Review by valeriebucher — APPROVED** [review]
Tested on ts1, works fine!

**Review by airelawaleria — APPROVED** [review]
Re-approve

**Review by JohannesWeiss — APPROVED** [review]
Re-Approve

**Review by marvinchimeka — APPROVED** [review]
Tested it on ts2. Re-approve

**Review by FlorianStang — APPROVED** [review]
Tested on TS2, everything worked as expected.

**Review by simonzilker — APPROVED** [review]
re-approve. Works perfectly!

**Review by krusche — APPROVED** [review]

**Pull request merged**
