### PR TITLE
`Development`: Add e2e tests for instructors assessing exams in the second round

### PR DESCRIPTION
**Pull request by muradium**
#### General

- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I documented the TypeScript code using JSDoc style.

### Motivation and Context
We want to test the scenario where instructor enables a second round of exam assessment and assesses the exam submission one more time.

### Description
Adds E2E test in Playwright about instructor enabling second round of assessment and making changes to the assessment tutor has done on the first round. To make the test lightweight, it's added as part of the series of text assessment tests, where the first round of assessment is followed by a student complaining, the complaint being rejected and finally, the final assessment done during the second round.

### Steps for Testing
- **Code Review**: Ensure that tests pass for valid reasons, functionality is adequately tested and check the code quality.
- **Run the tests (optional)**: Tests are executed during automatic run in CI environment. You can run them locally and check if they pass.

**Steps for running the tests:**
1. Navigate to **src/test/playwright**
2. Configure Playwright using playwright.env file based on your local setup. Current configuration should work for default Artemis setup.
3. Run `npm install && npm run playwright:setup`
4. Run the test group using one of the methods:
- Run `npx playwright test e2e/exam/ExamAssessment.spec.ts -g "Text exercise assessment"`
- Run `npm run playwright:open` to open the Playwright UI, search for the "Text exercise assessment" and run it
**Warning:** Don't solely run the "Instructor makes a second round of assessment" test as it's part of the serial group of tests and will fail if previous tests are not executed.

5. Confirm that the "Instructor makes a second round of assessment" test passes passes

#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
	- Enhanced conditional rendering on the assessment dashboard based on exam mode and user privileges.
	- Added a toggle for second correction rounds, improving user control during assessments.
- **Bug Fixes**
	- Streamlined complaint handling and feedback processes to prevent errors when data is absent.
- **Documentation**
	- Improved clarity and maintainability of the assessment dashboard templates.
- **Tests**
	- Updated test methods to support new parameters for flexible assessment processes.
- **Chores**
	- Introduced new methods for handling feedback and assessment rounds, enhancing overall functionality.

### CODE REVIEW

**Review by az108 — DISMISSED** [review]
Code 👍

**Review by SimonEntholzer — APPROVED** [review]
Tested locally, thanks for correcting the order of assessments with complaints. 

Assessment round 1 -> Assessment round 2 -> Complaint -> Complaint assessment is the correct assessment order :+1:

**Review by iyannsch — APPROVED** [review]
Code LGTM

**Review by az108 — APPROVED** [review]
reapprove

**Review by krusche — APPROVED** [review]

**Pull request merged**
