### PR TITLE
`Development`: Implement multiple exercise selection in LTI deep linking service

### PR DESCRIPTION
**Pull request by basak-akan**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] **Important**: I implemented the changes with a very good performance and prevented too many (unnecessary) database calls.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I added pre-authorization annotations according to the [guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/#rest-endpoint-best-practices-for-authorization) and checked the course groups for all new REST Calls (security).
- [x] I documented the Java code using JavaDoc style.
#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] Following the [theming guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client-tests/).
- [x] I added `authorities` to all new routes and checked the course groups for displaying navigation elements (links, buttons).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

### Motivation and Context

This update introduces the capability to add multiple exercises in a single LTI deep-linking service response. Previously, instructors had to add exercises individually. By enabling batch addition of exercises, this change enhances usability, and reduces the administrative burden on instructors. Additionally, it includes an improved arrangement of the exercises list view, further optimizing the overall workflow and user interface.

### Description

- Multiple exercises can be selected to Link to external LMS (Moodle).
- If the Artemis exercise is a graded or bonus exercise, it will be added to the grade book of the external LMS.
- If the Artemis exercise is not a graded exercise, it won't appear on the grade book of the external LMS.
- Exercise selection page rearranged:
     - Course title and semester information removed
     - Exercise start date added
     - Exercise graded information added

### Steps for Testing

Prerequisites:
- Test on Test Server 11 where lti profile is enabled.
- 1 Instructor

1. Login to Moodle (https://moodle.ase.in.tum.de/) using instructor credentials (e.g. artemis_test_user_11)
2. Select "LTI Testing Course"
3. Enable edit mode (on top right corner of the page)
5. Select add an activity or resource
6. Select "External Tool"
7. You will be directed to editing external tool page
8. Under preconfigured tools select "Artemis - https://artemis-test11.artemis.in.tum.de/" and click "select content" button.
9. Verify you see login page of artemis and login using same instructor credentials.
10. Verify you see "LTI Single Configuration Test" course and select this course
11. Select multiple exercises where graded column is yes and no and click on "link" button
12. Verify you see selected exercises names and graded information on navigated Moodle page (Please note that if exercise is a graded exercise you will see maximum graded value as 100 - this is the intended behavior to match with current results service)
13. Click on add and verify the selected exercises are added to the Moodle course.

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [x] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [x] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

#### Client

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [lti13-deep-linking.component.ts](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5893/latest/artifact/shared/Coverage-Report-Client-Tests/app/lti/lti13-deep-linking.component.ts.html) | 90.62% | ✅ |

#### Server

| Class/File | Line Coverage | Confirmation (assert/expect) |
|------------|--------------:|---------------------:|
| [LtiDeepLinkingService.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5893/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.service.connectors.lti/LtiDeepLinkingService.html) | 97% | ✅ |
| [LtiResource.java](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS5893/latest/artifact/shared/Coverage-Report-Server-Tests/de.tum.in.www1.artemis.web.rest/LtiResource.html) | 100% | ✅ |
### Screenshots

video

## Summary by CodeRabbit

- **New Features**
	- Enhanced the LTI Deep Linking service to support multiple exercise IDs for deep linking, improving integration flexibility.
	- Updated the LTI deep linking UI to display exercise start dates and inclusion in overall scores, enhancing user information.

- **Refactor**
	- Refactored LTI deep linking components and services for improved handling of multiple exercises.
	- Updated test suites to align with the new multi-exercise deep linking functionality.

- **Style**
	- Adjusted UI elements in the LTI deep linking component for a clearer presentation of exercise details.

### CODE REVIEW

**Review by Predixx — DISMISSED** [review]
tested during testing session. worked for me!

**Review by nata-81 — DISMISSED** [review]
tested on ts11. Works as expected.

**Review by egekurt123 — DISMISSED** [review]
Tested during a testing session, works as expected

**Review by coolchock — APPROVED** [review]
tested during testing session, works as expected

**Review by konrad2002 — DISMISSED** [review]
tested on legacy ts11, lgtm

**Review by MaximilianJG — DISMISSED** [review]
Tested on legacy ts11! Works as expected

**Review by xHadie — APPROVED** [review]
_Manually tested on TS11_Legacy_
Overall, works as expected.

But I was not redirected to the _"editing external tool page"_ after clicking _"Select add an activity or resourse"_
I needed to selecte "External Tool" manually from the listed options.
Was it just missing in the testing description?
image

**Comment by basak-akan** [comment]
> _Manually tested on TS11_Legacy_ Overall, works as expected.
> 
> But I was not redirected to the _"editing external tool page"_ after clicking _"Select add an activity or resourse"_ I needed to selecte "External Tool" manually from the listed options. Was it just missing in the testing description? image

Thanks @xHadie I missed that step on the testing description, it is updated now.

**Review by georgyia — DISMISSED** [review]
manually tested on ts11, works as expected

**Review by egekurt123 — APPROVED** [review]
Reapprove after merge

**Review by rstief — APPROVED** [review]
Demonstrated in testing session, code also lgtm

**Review by MaximilianJG — APPROVED** [review]

**Pull request merged**
