### PR TITLE
[Bugfix] tutor assessment - guided tour

### PR DESCRIPTION
**Pull request by SimonEntholzer**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

Guided tours did not work for the tutor assessment tour. In this PR we fix this problem.

<details>

</details>

### Steps for Testing

1. On test server 2 as a tutor you can test the tutor-assessment guided tour in the tutorial course
2. Go through all steps and check if everything works accordingly

### CODE REVIEW

**Review by willergeorg — COMMENTED** [review]
Tested with test user 1 on TS2. In general seems to look good for me. But I had a difficulty at the step where the user is asked to mark a line in the submission and to asses it. If you mark one of the two the lower lines, the assess box drops out of the tutorial frame and can't be used (see screenshot below). But it works when choosing the first line.

issue3

**Comment by SimonEntholzer** [comment]
> Tested with test user 1 on TS2. In general seems to look good for me. But I had a difficulty at the step where the user is asked to mark a line in the submission and to asses it. If you mark one of the two the lower lines, the assess box drops out of the tutorial frame and can't be used (see screenshot below). But it works when choosing the first line.
> <details>
>
> 
> </details>

I fixed it by increasing the size of the highlighted region. It is not the best possible solution, but for some reason the only possible one. (at least for now)

**Review by ivanchimeno — DISMISSED** [review]
lgtm and success tested

**Review by imstreetspirit — CHANGES_REQUESTED** [review]
tested w/ test user 2 on ts2. the box is not displayed correctly(attached screenshot) apart from that, seems well :)
image

**Review by NicolasUllmann — COMMENTED** [review]
Tested with user 4 on Server 2. I ran into the same problem as mentioned above. Other than that, everything looked good and seemed fine!

**Comment by SimonEntholzer** [comment]
> tested w/ test user 2 on ts2. the box is not displayed correctly(attached screenshot) apart from that, seems well :)
> image

I fixed the issue that you cannot see the whole Guided tour step

**Review by imstreetspirit — APPROVED** [review]
tested on ts2 again, works as expected.

**Pull request merged**
