### PR TITLE
`Development`: Add git branch information to startup log

### PR DESCRIPTION
**Pull request by TheZoker**
#### General

- [x] This is a small issue that I tested locally
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Description

A small PR that adds the branch name next to the git commit id into the startup box:
image

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### CODE REVIEW

**Review by b-fein — APPROVED** [review]

**Review by manuelmanso — APPROVED** [review]
LGTM 👍

**Comment by manuelmanso** [comment]
Also don't forget to add the `ready for review` label (I assumed that it was ready for review since it already had a review)

**Review by Strohgelaender — APPROVED** [review]
code

**Review by ge65cer — COMMENTED** [review]
Is there any way to make this optional? I can no longer start Artemis without a git repository present:

```
Execution failed for task ':generateGitProperties'.
> Error while evaluating property 'generatedProperties' of task ':generateGitProperties'
   > No Git repository found.
```

**Review by Hialus — APPROVED** [review]
Looks good. Nice addition.
Regarding Moritz's comment: I think if you go to the length of removing the git repository from the Artemis folder you could also invest the extra time of removing the plugin from the build.gradle file. Is there any specific usecase where you would need this?

**Review by bassner — APPROVED** [review]
LGTM

**Comment by ge65cer** [comment]
@Hialus Sure, that is possible but would then also require editing the source code. I was just wondering if it'd be possible to make this optional and thereby reduce the dependency between the software and its environment.

**Comment by Hialus** [comment]
> @Hialus Sure, that is possible but would then also require editing the source code. I was just wondering if it'd be possible to make this optional and thereby reduce the dependency between the software and its environment.

Have you tested this? From what I have read removing the plugin should not require any source code changes. The `GitProperties` used for this are provided by Spring Boot and are therefore always accessible. The plugin only creates a file with the properties which Spring then reads. If this file is not present Spring should simply return null or something. So removing this plugin should only lead to `Git Branch: null` being printed in the console

**Comment by ge65cer** [comment]
> Have you tested this? From what I have read about this plugin, removing the plugin should not require any source code changes. The `GitProperties` used for this are provided by Spring Boot and are therefore always accessible. The plugin only creates a file with the properties which Spring then reads. If this file is not present Spring should simply return null or something. So removing this plugin should only lead to `Git Branch: null` being printed in the console

I've only tested removing the git repository (not changing the dependency file), which led to the above error message

**Review by jpbernius — APPROVED** [review]
@ge65cer Your finding here is not specific to this pull request, are they?
The `:generateGitProperties` task is already needed to display the commit hash. So this would also apply to the current state in `develop`. I share @Hialus view that we can require the context of a Git repository to build Artemis.

If we want to support building Artemis outside a Git repository (cc @krusche), we must work around this in a follow-up. So I would merge this if we are on the same page that this PR does not introduce this dependency.

**Comment by jpbernius** [comment]
However, please clean up the PR description before we merge this.

**Review by ge65cer — APPROVED** [review]
Yes, it is not specific to this PR, but I wanted to mention it. Other than that I approve the changes.

**Comment by TheZoker** [comment]
@jpbernius I cleaned up the description

**Pull request merged**
