### PR TITLE
`Programming exercises`: Allow toggling inline feedback in the repository view

### PR DESCRIPTION
**Pull request by pzdr7**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] **Important**: I implemented the changes with a very good performance, prevented too many (unnecessary) REST calls and made sure the UI is responsive, even with large data.
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.
- [x] I translated all newly inserted strings into English and German.

#### Changes affecting Programming Exercises
- [x] **High priority**: I tested **all** changes and their related features with **all** corresponding user types on a test server configured with the **integrated lifecycle setup** (LocalVC and LocalCI).

### Motivation and Context

Discussion in https://github.com/ls1intum/Artemis/issues/7886

### Description

The editor now checks if any feedback could be rendered in the editor (this is the case if any feedback item refers to a specific line, e.g. via GenAI feedback or a manual assessment).

### Steps for Testing

Prerequisites:
- 1 Test server with LocalVC
- 1 Programming exercise with manual assessment enabled. Enable *both* options, local IDE and online editor.
- 1 Student
- 1 Instructor

1. Log in to Artemis as the student
2. Participate in the programming exercise normally.
3. Open the repository in Artemis via the Code button (see [here](https://docs.artemis.cit.tum.de/user/exercises/programming.html#for-students) how to do that).
4. Verify that there is **no** button to toggle the inline feedback.
5. As the instructor, log in and navigate to course management > your course > exercises > your exercise and click on "Edit". 
6. Modify the due date s.t. it is now.
7. Assess the student's submission (either via the assessment dashboard or the "Scores" view of your exercise), adding a few inline comments in different files. Submit the assessment.
8. Go to the "Participations" view of the exercise and open the repository you just assessed via the "Code" button.
9. Verify that you can see a button that toggles the feedback in the editor. Open a file and verify that the feedback is actually toggled.
10. Verify as the student that you can see and toggle the feedback in the repository view as well.

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [ ] Test 1
- [ ] Test 2

### Test Coverage

Only trivial changes in typescript files. Larger changes in HTML files

### Screenshots

https://github.com/user-attachments/assets/b0287c80-7d1e-4ff7-9b69-0565a849348d

## Summary by CodeRabbit

- **New Features**
  - Introduced an option to toggle the display of inline feedback in the code editor.
  - Improved German and English translations for better user experience.

- **User Interface Enhancements**
  - Enhanced layout and interactivity of the repository view with improved toolbar actions and result displays.

- **Bug Fixes**
  - Corrected the visibility of feedbacks in the code editor based on user selections.

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Code

**Comment by Strohgelaender** [comment]
I think having this integrated in the repository view is a bit hidden. Can you maybe add a "View Assessment" Button (similar to how it is done for text exercises) that leads to this page?

**Review by BBesrour — APPROVED** [review]
Tested on TS3, works as expected

**Review by az108 — APPROVED** [review]
Works as expected and tested on TS3 👍 
Before:
image
After assesement:
image

**Review by krusche — APPROVED** [review]
code looks good to me 👍

**Pull request merged**
