### PR TITLE
`Discussion`: Fix post tag selector background color

### LINKED ISSUE #5232: Dark mode: Tags selection white text on white background when creating a new post in the discussion tab
### Describe the bug

When creating a new discussion post in an exercise, the tags selection is white text on a white background
image

### To Reproduce

1. Go to a exercise
2. Navigate to discussion
3. Click new post

### Expected behavior

A dark mode tags selection

### Screenshots

_No response_

### What browsers are you seeing the problem on?

Firefox

### Additional context

Manjaro Linux, Firefox v101.0.1

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by bassner**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] Following the [theming guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-design/), I specified colors only in the theming variable files and checked that the changes look consistent in both the light and the dark theme.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Fixes #5232.

### Description

Replaced the hard-coded colors in this file with themed colors.

### Steps for Testing

Prerequisites:
- 1 Student

1. Log in to Artemis
2. Go to a Discussion page
3. Open the "Create new post" modal
4. Add tags to the post by selecting them from the dropdown and verify that the options are well readable
5. Verify that the background color in the list is slightly lighter in dark mode and slightly darker in light mode when hovering an option

#### Code Review
- [ ] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots

Screenshot 2022-06-13 at 18 00 26

### CODE REVIEW

**Review by jschmautzer — APPROVED** [review]
tested on ts1, followed the testing steps - works as described :)

**Review by TheTrueVester — APPROVED** [review]
Tested on ts2. Everything worked as expected.

**Review by mallgaier — APPROVED** [review]
Tested on TS1, works as expected. Good job 👍

**Review by yuling-sun — APPROVED** [review]
Tested on TS2. Worked as described.

**Pull request merged**
