### PR TITLE
[Enhancement] - Renaming of course statistics

### PR DESCRIPTION
**Pull request by FuchsDominik**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I followed the [coding and design guidelines](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/client.html).
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all the newly inserted strings into German and English

### Motivation and Context

- Integrated some name changes to naming suggestions in the statistics of a course. (in students view) 
- Also, pie chart on the left side of the statistics was refering to maximum scores, where it should actually be reachable score (difference is that max score are all the exercises of the course combined, reachable score are only the maximum exercise points if the participated exercises combined)

### Description

- Integrated some name changes to naming suggestions in the statistics of a course. (in students view) 
- Name changes in the course-card in the course overview for students (see screenshots)
- Pie chart now refers to the reachable scores
- Below the pie chart there is a summary of the points (analogue to the summary next to every exerciseGroup)
- Added a client test which tests if scores and points are calculated correctly

### Steps for Testing

1. Log in to Artemis
2. Navigate to Course Overview
3. Check that it says "Your overall score" in the tile
4. Choose a course
5. Navigate to the Statistics tab
6. Make sure that the the reachable score on the left side is in the chart as well as mentioned below the chart and that it is the sum of the reachable scores of all exerciseGroups
7.  Check that the overall score on the left side is the sum of the overall scores of the right side
8. Make sure that the name changes like shown in the screenshots are correctly displayed and make sure there are translations also in german
9. Check that the tooltips contain the text as mentioned below under the screenshot
10. Check again that your points in the whole course (on the left side) is the same percentage as in the tile in the course overview page (see step 3.)

### Screenshots

Course overview (Your current score -> Your overall score):
Screenshot 2021-01-12 at 17 22 13

1. This score should be the same score as your course points in the following picture

The course statistic changes:
Screenshot 2021-01-13 at 14 51 43

As well as the tooltips (see screenshot):
2. "Reachable points are the sum of the maximum points of all exercises of this type which have already been assessed, independent of your participation"
3. Overall points are the sum of the maximum points of all exercises of this type.
4. "Reachable points are the sum of the maximum points of all exercises which have already been assessed, independent of your participation"
5. "Overall points are the sum of the maximum points of all exercises"

### CODE REVIEW

**Review by airelawaleria — APPROVED** [review]
Tested in the testing session. App

**Review by marvinchimeka — APPROVED** [review]
Works as intended. Approve

**Review by LudwigWeide — APPROVED** [review]
Approve.

**Review by EneaGore — APPROVED** [review]

**Review by JohannesWeiss — APPROVED** [review]

**Review by DenizShabani — APPROVED** [review]
Works as intended!

**Review by sebastiantpeter — APPROVED** [review]
Tested on ts1. Tooltips and namings in the statistics are as described.

**Review by krusche — APPROVED** [review]

**Pull request merged**
