### PR TITLE
`General`: Improve favicon logo for light mode

### PR DESCRIPTION
**Pull request by Malyuk-A**
#### General
- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).

### Motivation and Context
This PR tries to resolve the following Git Hub Issue #3658. 
Original Logo PR : https://github.com/ls1intum/Artemis/pull/3626

The issue was that the logo was not clearly visible in the tab for people with bright/light tabs (light-mode)
image

I discussed this isse with @krusche once more and we decided to do the following:
Based on the original logo PR and the final survey we simply pick the second place for some favicons
image
image

I did not change the main logo.png it should stay the same!

### Description
I additionally moved the icons/logos to a subfolder to not make the main webapp folder less chaotic. 
image

This is how it looks for white-mode users (e.g. Edge)
image

I am aware that this is not a perfect solution. A perfect one would be to differentiate/toggle dynamically between light and dark mode. But we do not have such a feature as of now.
E.g possible issues for dark mode users could appear now:
Incognito mode for Edge
image

I myself use dark mode so yeah:
image
image
(Especially because I have a custom chrome-browser skin that is blue-ish. Such edge-cases can not even be caught by light/dark mode I fear.
image

But I think this is still a good chance because the majority will use white mode.

### Steps for Testing

1. Log in to Artemis and check the main logo and the favicon in the tab
2. Try to use multiple different browsers/devices to check if everything is fine

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Screenshots
Here you can see the design choices/changes I took for the favicon/logo.
I used the following page: https://realfavicongenerator.net/
image
image
image
image
image

No test should be influenced by this PR I only changed a couple of images.
The failing tests are unrelated to this PR (locally the tests work)
image

### CODE REVIEW

**Review by MerlinMehmed — APPROVED** [review]
It looks good on my white theme Chrome. 
Unfortunately, as you have mentioned it does not work on a custom color theme. I have set a purple theme in Mozilla, therefore I don't see the whole logo when the tab is open. 
Screenshot from 2021-11-26 09-26-35

But I think this is still a good improvement even though it doesn't handle all cases!

**Comment by Malyuk-A** [comment]
> It looks good on my white theme Chrome. Unfortunately, as you have mentioned it does not work on a custom color theme. I have set a purple theme in Mozilla, therefore I don't see the whole logo when the tab is open. Screenshot from 2021-11-26 09-26-35
> 
> But I think this is still a good improvement even though it doesn't handle all cases!

This seems to still be the light version of the logo. Strange. 
I looked up what file firefox is using and it seems to be the favicon.ico file and It is the dark version so yeah... can anyone else with firefox test it out please because I do not have it.
image
image

**Review by b-fein — APPROVED** [review]
Firefox caches favicons in a file `favicons.sqlite` in the user profile directory. After removing that file at least for me the correct icon is shown.

**Review by filip-gregurevic — APPROVED** [review]
Looks good to me 👍🏼

**Pull request merged**
