### PR TITLE
Added connectors user update to methods

### PR DESCRIPTION
**Pull request by daniels98it**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest2.ase.in.tum.de.
- [x] ~Server: I added multiple integration tests (Spring) related to the features~
- [x] Server: I implemented the changes with a good performance and prevented too many database calls
- [x] Server: I documented the Java code using JavaDoc style.

### Motivation and Context

This corresponds to my local fix to the [issue nr. 1847](https://github.com/ls1intum/Artemis/issues/1847). It solves the problem of the incorrect synchronization between Artemis and GitLab of the user's groups, if these are added or removed directly from the course's access groups (see screenshots).

### Description

The fix consists in using the already implemented "updateUserInConnectorsAndAuthProvider(User user, Set<String> oldGroups)" method to update the user's groups in both, Artemis and in the GitLab instance. 

### Steps for Testing

1. Go to 'Course management view'
2. Click on an Access Group of a course
3. Add or remove a user to/from the list
4. Check on the GitLab instance if user has been added/removed to/from the members group of the course's exercises

### Screenshots

Screenshot from 2020-07-09 21-43-55
Screenshot from 2020-07-10 19-12-21

### CODE REVIEW

**Review by tiffca — DISMISSED** [review]
I received a 500 error when removing test user 1, using the method mentioned. 

Also can we please know an example GitLab URL to check? I only know the Github and Bamboo URLs.

Steps (test server 1): 
1. (as an instructor) Go to Course-Management 
2. Select an access groups, for example, Test course (id=1), -> Students: "artemis-test-students (37)" 
3. Try to remove a user 
4. Error is thrown. Expected: user should be removed. 
5. I also tested for other courses and users

screenshot: 
Screen Shot 2020-07-13 at 5 06 42 PM

Error: 
Failed to load resource: the server responded with a status of 500 (). 

Request URL: https://artemistest.ase.in.tum.de/api/courses/1/students/artemis_test_user_1
Request Method: DELETE
Status Code: 500 
Remote Address: 131.159.39.4:443
Referrer Policy: same-origin

“translation-not-found[Http failure response for https://artemistest.ase.in.tum.de/api/courses/33/students/artemis_test_user_1: 500 OK]”

**Comment by daniels98it** [comment]
> I received a 500 error when removing test user 1, using the method mentioned.
> 
> Also can we please know an example GitLab URL to check? I only know the Github and Bamboo URLs.
> 
> Steps (test server 1):
> 
> 1. (as an instructor) Go to Course-Management
> 2. Select an access groups, for example, Test course (id=1), -> Students: "artemis-test-students (37)"
> 3. Try to remove a user
> 4. Error is thrown. Expected: user should be removed.
> 5. I also tested for other courses and users
> 
> screenshot:
> Screen Shot 2020-07-13 at 5 06 42 PM
> 
> Error:
> Failed to load resource: the server responded with a status of 500 ().
> 
> Request URL: https://artemistest.ase.in.tum.de/api/courses/1/students/artemis_test_user_1
> Request Method: DELETE
> Status Code: 500
> Remote Address: 131.159.39.4:443
> Referrer Policy: same-origin
> 
> “translation-not-found[Http failure response for https://artemistest.ase.in.tum.de/api/courses/33/students/artemis_test_user_1: 500 OK]”

Thank you for the review.

I now fixed my changes to be used only in case of a VCS use in Artemis (like Gitlab). 

Could you please re-review it? (using Test Server 2 - Gitlab & Jenkins)

Gitlab URL: https://artemistest2gitlab.ase.in.tum.de/

**Review by fde312 — CHANGES_REQUESTED** [review]
We tested it in ts2 and we found an issue that you cannot add a user as instructor and as tutor. When doing so we get a 500 exception, when adding the user to one of the roles while being already in the other role. This is the error which is thrown in sentry:

https://sentry.io/organizations/ls1intum/issues/1870261820/?environment=test&project=1440029&query=is%3Aunresolved
The error is thrown in `GitLabUserManagementService.java` in `updateUser`.
We are not sure, if this behaviour is intended. Removed worked well.

**Comment by daniels98it** [comment]
Thank you @fde312 for testing. I now fixed the issue regarding the impossibility to add a user to both groups (instructors and tutors) and tested it on [artemistest2](https://artemistest2.ase.in.tum.de/).

**Review by anditurdiu — APPROVED** [review]
Works as expected. Nice work 👍

**Review by fde312 — APPROVED** [review]
Works fine now :)

**Review by schultek — DISMISSED** [review]
Adding/Removing users works fine.
As a little note: We noticed that a users password gets resetted when adding/removing the user from a group in Artemis. Not sure if this is wanted or not.

**Comment by krusche** [comment]
> As a little note: We noticed that a users password gets resetted when adding/removing the user from a group in Artemis. Not sure if this is wanted or not.

This is unwanted behavior and should not happen

**Comment by daniels98it** [comment]
> Adding/Removing users works fine.
> As a little note: We noticed that a users password gets resetted when adding/removing the user from a group in Artemis. Not sure if this is wanted or not.

Are you referring to the user's password been resetted in GitLab or in Artemis? I saw this happening in GitLab, but even before my pull-request..

**Comment by fde312** [comment]
The clarify the issue a bit more. When trying to log in to `https://artemistest2gitlab.ase.in.tum.de` then GitLab requires to set a new password. After changing the password you can log into GitLab. 
When the same user is then removed from a group and added back, the new password will be reseted to the password which was there before you tried to log into `https://artemistest2gitlab.ase.in.tum.de`

**Comment by krusche** [comment]
> > Adding/Removing users works fine.
> > As a little note: We noticed that a users password gets resetted when adding/removing the user from a group in Artemis. Not sure if this is wanted or not.
> 
> @schultek Are you referring to the user's password been resetted in GitLab or in Artemis? I saw this happening in GitLab, but even before my pull-request..

Indeed the user password is synchronized between Artemis and Gitlab, which was surprising to me as well. I improved the documentation in the code and added a boolean flag so that developers immediately recognize it and could also use it without synchronizing the password.

@daniels98it It might be unwanted behavior to synchronize (and potentially) reset the password, when adding / removing the user to/from a specific group. From this point of view, I would set the new boolean flag to false.

However, it can be a problematic situation when users change their password in Gitlab and the password in Artemis is still the old one. I don't think password changes can be deactivated in Gitlab. Therefore it might be good, to sync the user password in all situations.

What do you think?

**Comment by schultek** [comment]
It also works for Bamboo/Jira on Test Server 1.

**Comment by daniels98it** [comment]
I already googled the problem and found this [Artemis-GitLab issue](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/36412) which triggered the "reset" within GitLab at line 75
`
userApi.updateUser(gitlabUser, userService.decryptPasswordByLogin(user.getLogin()).get());
`
in 
`src/main/java/de/tum/in/www1/artemis/service/connectors/gitlab/GitLabUserManagementService.java`

To "temporary" solve this problem, I commented out this line to avoid the sychronisation.. But as @krusche already stated, this might have some problems when the password is changed..

**Comment by krusche** [comment]
> To "temporary" solve this problem, I commented out this line to avoid the sychronisation.. But as @krusche already stated, this might have some problems when the password is changed..

With the newest changes, you could simply set the flag to false

**Comment by daniels98it** [comment]
> > To "temporary" solve this problem, I commented out this line to avoid the sychronisation.. But as @krusche already stated, this might have some problems when the password is changed..
> 
> With the newest changes, you could simply set the flag to false

Great! That's clearly a better solution

**Review by fde312 — APPROVED** [review]
Tested it again with the new boolean flag on test server 1&2 and everything works as expected! 🚀

**Review by schultek — APPROVED** [review]
Re-tested and re-approved.

**Comment by daniels98it** [comment]
> However, it can be a problematic situation when users change their password in Gitlab and the password in Artemis is still the old one. I don't think password changes can be deactivated in Gitlab. Therefore it might be good, to sync the user password in all situations.
> 
> What do you think?

I would personally set the flag to false when adding users to groups, as this happens more frequently and the user's password would still remain the same.. The true flag would only be needed when the user's password is actually changed (manually by admin for example).

Or is there something i'm still missing?

**Review by krusche — APPROVED** [review]

**Comment by sleiss** [comment]
> I don't think password changes can be deactivated in Gitlab. 
@krusche 
I believe you are right on this point, it seems that it can only be disabled for LDAP-accounts (as the LRZ Gitlab does: https://gitlab.lrz.de/profile/account).

So, although that's of course a major change, the best option would be to use an LDAP that (or something similar) where the credentials are stored (and not Artemis and Gitlab directly).

**Pull request merged**
