### PR TITLE
`File upload exercises`: Fix an issue with drag and drop feedback duplicates during assessment

### PR DESCRIPTION
**Pull request by sarpsahinalp**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/development-process/development-process.html#naming-conventions-for-github-pull-requests).

#### Client
- [x] I **strictly** followed the [client coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/client/).

### Motivation and Context

Drag and Drop feedback duplicates when applied to additional feedback.

### Description

Added a flag to ensure it is followed when the parent component adds feedback or the child component is updated

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 File Upload Exercise

1. Create a file upload exercise (noticed in an exam assessment)
2. Have at least one participation in that file upload exercise
3. Make sure that there are Drag and Drop grading criteria for the exercise
4. Assess the submissions by adding additional feedback and applying the drag and drop criteria
5. See that the criteria is duplicated

#### Exam Mode Testing

Prerequisites:
- 1 Instructor
- 1 Student
- 1 File Upload Exercise

1. Create a file upload exercise (noticed in an exam assessment)
2. Have at least one participation in that file upload exercise
3. Make sure that there are Drag and Drop grading criteria for the exercise
4. Assess the submissions by adding additional feedback and applying the drag and drop criteria
5. See that the criteria is duplicated

[](https://artemis-test1.artemis.cit.tum.de)
[](https://artemis-test2.artemis.cit.tum.de)
[](https://artemis-test3.artemis.cit.tum.de)
[](https://artemis-test4.artemis.cit.tum.de)
[](https://artemis-test5.artemis.cit.tum.de)
[](https://artemis-test6.artemis.cit.tum.de)
[](https://artemis-test9.artemis.cit.tum.de)

#### Performance Review
- [x] I (as a reviewer) confirm that the client changes (in particular related to REST calls and UI responsiveness) are implemented with a very good performance 
- [ ] I (as a reviewer) confirm that the server changes (in particular related to database calls) are implemented with a very good performance
#### Code Review
- [x] Code Review 1
- [ ] Code Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2
#### Exam Mode Test
- [x] Test 1
- [x] Test 2

## Summary by CodeRabbit

- **New Features**
  - Enhanced feedback management with a new feature to track changes in feedback details, improving the feedback update experience.

### CODE REVIEW

**Review by JohannesWt — COMMENTED** [review]
Code 👍

**Review by edkaya — APPROVED** [review]
Code

**Review by egekurt123 — APPROVED** [review]
Code LGTM

**Review by pzdr7 — APPROVED** [review]
Tested on TS3. Works as described for regular and exam file upload exercises

**Pull request merged**
