### PR TITLE
`Development`: Improve files assertions in server tests 

### PR DESCRIPTION
**Pull request by laadvo**
#### General
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/). 

### Motivation and Context

AssertJ offers different assertions related to files, that not all tests utilize. Some assertions are too long and not as clear as they could be.

### Description

In this PR I replace assertions related to files with better suited AssertJ assertions such as `exists()`, `doesNotExist()`, `hasContent(..)` and others.

### Review Progress

Look through the code and see if the new assertions make sense. Also look if I might have missed some assertions

#### Code Review
- [x] Code Review 1
- [x] Code Review 2

### Test Coverage

unchanged

### CODE REVIEW

**Review by terlan98 — APPROVED** [review]
The changes look good. I also couldn't find any missed assertions.

**Review by RY997 — APPROVED** [review]
More intuitive, LGTM

**Review by SabrinaGlatz — APPROVED** [review]
The assertions look good to me

**Review by maximiliansoelch — APPROVED** [review]
Code changes look good, tests still succeed 👍

**Pull request merged**
