### PR TITLE
`Assessment`: Allow instructors to export exam scores to an Excel file

### PR DESCRIPTION
**Pull request by maximiliansoelch**
#### General

- [x] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I documented the TypeScript code using JSDoc style.
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Currently, exporting to Excel is only supported for course scores, but not for exam scores.

### Description

This change adds the Excel Export functionality (already introduced for course scores in #4941) for exam scores.
In addition, custom CSV export options (already introduced for course scores in #4869) can now be specified when exporting exam scores.
All row builder source files are moved from `course-scores` to the `shared/export folder` and are renamed accordingly, too.

### Steps for Testing

- 1 Course
- min. 1 Student
- 1 Exam, on which the student(s) participated

1. Log in to Artemis
2. Navigate to Course Administration, select the course, Exam, then Scores
3. Click the `Export` 
4. A modal opens, where you can select the file type used for the export (Excel<default> or CSV).
5. Select Excel (which should be selected initially) and click `Export as Excel`
6. Open the downloaded Excel file and make sure the rows and their values are equivalent to the ones displayed in Artemis
7. In addition, also verify that the export to a CSV file still works as expected (the custom CSV export options are incorporated).
8. Please also test the export for course scores as well (according to the test instructions in #4941)

#### Code Review
- [x] Review 1
- [ ] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| exam-scores.component.ts | 83.11% | 96.4% |
| csv-export-row-builder.ts | 100% | 100% |
| excel-export-row-builder.ts | 100% | 100% |
| export-row-builder.ts | 96% | 100% |

### Screenshots

Exam_Excel_Export

### CODE REVIEW

**Review by bassner — APPROVED** [review]
Tested on TS5; the export works fine! The course scores export still works, too.
Code looks good to me 👍

**Review by rhubinger — APPROVED** [review]
Tested on TS2, everything worked. LGTM

**Review by akesfeden — APPROVED** [review]
Tested on TS2, exported Excel and CSV files look correct.

**Review by jbllhff — APPROVED** [review]
tested on ts2, works fine

**Comment by maximiliansoelch** [comment]
@SimonPaul02 Thanks for testing.
Adapting the column width is not that trivial with the library we use to generate Excel files and Excel also provides the [Autofit](https://www.ablebits.com/office-addins-blog/2017/03/16/autofit-excel-columns-rows/) function which automatically adapts the columns to the text width. Therefore I think your proposed improvement currently hasn't the highest priority, but can be for sure picked up in the future.

**Pull request merged**
