### PR TITLE
`Development`: Fix naming of programming exercise endpoints

### PR DESCRIPTION
**Pull request by Olha-D**
Programming Exercises: made endpoint naming consistent 

#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/server/).
- [x] I implemented the changes with a good performance and prevented too many database calls.
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 1 (Atlassian Suite).
- [x] I tested **all** changes and their related features with **all** corresponding user types on Test Server 2 (Jenkins and Gitlab).

### Motivation and Context

This PR fixes issue #5302.

### Description
I have found all end points related to programming exercises and changed URL naming for some of them so that the naming is consistent for all end points and follows the REST paradigm.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Renaming looks good. I also searched the regex "programming-exercise(/|`)" and did not find any other occurrences

**Review by bassner — APPROVED** [review]
Seems like you didn't forget any occurrence. LGTM

**Review by manuelmanso — APPROVED** [review]

**Review by Hialus — DISMISSED** [review]
I also could not spot any missed occurences. 👍🏻

**Review by JohannesStoehr — APPROVED** [review]
Looked through develop and also found 14 occurrences of programming-exercise in REST URLs. (Used this RegEx: `programming-exercise("|/|')`)

**Comment by ge65cer** [comment]
Resolved merged conflict, approvals still stand.

**Comment by ge65cer** [comment]
Taking over ownership from @Olha-D who seems to be inactive here.

**Pull request merged**
