### PR TITLE
`Development`: Add missing legal base path in docker profile configuration

### PR DESCRIPTION
**Pull request by dfuchss**
#### General

- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://docs.artemis.cit.tum.de/dev/guidelines/development-process/#naming-conventions-for-github-pull-requests).

### Motivation and Context

In #6407 the ability to modify the privacy statement in artemis was introduced. In docker setups you have to override the path of the files in order to store it in a suitable volume. This is done in this PR.

### CODE REVIEW

**Review by tobias-lippert — APPROVED** [review]
Code LGTM

**Comment by bassner** [comment]
Will we run into the same problem in #6451 ?

**Comment by dfuchss** [comment]
> Will we run into the same problem in #6451 ?

I guess not, if you reuse the location property (and as far as I can see the configuration files will not change in #6451 )

**Comment by bassner** [comment]
> > Will we run into the same problem in #6451 ?
> 
> I guess not, if you reuse the location property (and as far as I can see the configuration files will not change in #6451 )
> 
> -> https://github.com/ls1intum/Artemis/pull/6451/files#diff-e5c3a5e6fc2efc1541253a24dbff117f259e8721a25275a922b85ff2f400b8faR23-R24

Got it. Thanks for the clarification 👍

**Review by bassner — APPROVED** [review]

**Pull request merged**
