### PR TITLE
`Development:` Add new client tests for metis-related files

### PR DESCRIPTION
**Pull request by lschlesinger**
#### General

- [x] I ran **all** client tests locally, they all passed

### Motivation and Context

We want to increase the client test coverage and get rid of sinon/chai dependency.

### Description

I added two new test files for components that were only implicitly covered by clients tests and had low coverage:
`postings-markdown-editor.component.spec.ts` is now at: 95%
`postings.button.component.spec.ts` is now at: 100%

For `postings-thread.component.spec.ts`, I removed sinon/chai as this was the only metis related test file that still relied on these dependencies.

I ran all client tests locally, the all **passed**

#### Code Review
- [x] Review 1
- [x] Review 2

### CODE REVIEW

**Comment by lschlesinger** [comment]
@b-fein thanks for the suggestion. i applied them and would be happy, if you could reapprove!

**Comment by Malyuk-A** [comment]
Also the build seems to have problems with the fa-icon 
image

**Comment by lschlesinger** [comment]
I fixed the failing test in another PR.  https://github.com/ls1intum/Artemis/pull/4149

**Comment by lschlesinger** [comment]
@Malyuk-A very very good hint!! thanks! It was the identifier name, that was ambiguous. I fixed it, ran the test again (passed), started server and client build successfully.

**Pull request merged**
