### PR TITLE
`Programming exercises`: Fix an issue in the score calculation in case of many SCA issues

### PR DESCRIPTION
**Pull request by Strohgelaender**
#### General
- [ ] I tested **all** changes and their related features with **all** corresponding user types on a test server.
- [ ] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.cit.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Server
- [x] I followed the [coding and design guidelines](https://docs.artemis.cit.tum.de/dev/guidelines/server/).
- [x] I added multiple integration tests (Spring) related to the features (with a high test coverage).
- [x] I implemented the changes with a good performance and prevented too many database calls.
- [x] I documented the Java code using JavaDoc style.

### Motivation and Context
On production, we encountered a student who got a too high point deduction for SCA issues (above the limit specified in the maximum SCA deduction setting)

### Description
On many places in Artemis, it is assumed that you simply can sum up the credits of all feedback elements in order to get the score. To support this, Artemis already adjusts the credits of SCA feedback items in case the maximum value for the category got exceeded.

However, if the sum of all categories exceeded the limit specified by the exercise, the penalty was locally reduced but the feedback items were not changed accordingly.

Now, when a category would exceed the maximum penalty (if overallPenaltyPoints + categoryPenaltyPoints > maxExercisePenaltyPoints), the points for this category get reduced. This change is also reflected in all the related feedback items:

```
┌───────────────────────────────────────────────────────────────┐
│ maxExercisePenaltyPoints                                      │
└───────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────┬────────────────────────────────────────────┐
│ overallPenaltyPoints                 │ categoryPenaltyPoints                      │
└──────────────────────────────────────┴────────────────────────────────────────────┘
                                       ┌────────────────────────┐
 ==>                                   │ categoryPenaltyPoints  │
                                       └────────────────────────┘
```

### Steps for Testing
Prerequisites:
- 1 Tutor
- 1 Student
- 1 Programming Exercise with SCA enabled and a maximum penalty set, also manual correction active

1. Student: Submit a solution that generates many SCA penalties (e.g. a lot of unused imports, unused attributes and methods)
2. Student: View your result and check that the limit got applied.
3. Tutor: After the due date, submit a manual correction.
4. Student: Verify that the manual correction got a correctly calculated score.

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage
changes covered

### CODE REVIEW

**Review by JohannesStoehr — APPROVED** [review]
Code changes and new tests look reasonable

**Review by simon-hng — APPROVED** [review]
Code

**Review by laadvo — APPROVED** [review]
The maximum penalty gets applied as expected even after the manual correction. Tested on ts1

**Review by tobias-lippert — APPROVED** [review]
Tested on ts1. Max penalty is correctly applied.

**Pull request merged**
