### PR TITLE
[Feature] [Orion] Download Auxiliary Repositories

### PR DESCRIPTION
**Pull request by MDK5**
### Motivation, Context and Description
Artemis' half of https://github.com/ls1intum/Orion/pull/63. See there for details.

### CODE REVIEW

**Review by JohannesStoehr — DISMISSED** [review]
The code changes look good in the PR here as well as in the Orion PR

**Review by niclasschuemann — APPROVED** [review]
Tested in the testing session, works fine, tested together with the respective Orion PR

**Review by FlorianGlombik — APPROVED** [review]
Worked as expected, see https://github.com/ls1intum/Orion/pull/63#pullrequestreview-719184672

**Review by coolchock — DISMISSED** [review]
code changes look good 👍

**Review by Olimbia23 — APPROVED** [review]
Great work @MDK5.
Thanks for adding comments. Changes look good 👍

**Review by FuchsDominik — APPROVED** [review]
Would approve code changes 👍

**Review by joschahenningsen — APPROVED** [review]
Changes make sense :+1:

**Pull request merged**
