### PR TITLE
[bugfix] Fix button alignment (linebreak and margin) in student-exam and exam-detail view for instructor

### PR DESCRIPTION
**Pull request by lschlesinger**
### Checklist
- [ ] I tested *all* changes and *all* related features with different users (student, tutor, editor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple screenshots/screencasts of my UI changes
- [x] Client: I translated all newly inserted strings into English and German.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).

### Motivation and Context

There were several style issues with the buttons in `exam-detail.component.html` and `student-exam.component.hmtl`.
See screencasts below.

### Description

I tried to simplify and rearrange the html code to solve the problems.

### Steps for Testing

1. Log in to Artemis as instructor
2. Navigate to Course Administration
3. Navigate to exam pages -> `/course-management/{id}/exams/{id}`
4. Change screen sizes and observe button behavior, judge the general alignment and style of the buttons
5. Click the "Student Exams" button to navigate to the student exam page -> `/course-management/{id}/exams/{id}/student-exams`
6. Change screen sizes and observe button behavior, judge the general alignment and style of the buttons

### Screenshots

**Exam-Detail**
_before: problem with inconsistent margins_

https://user-images.githubusercontent.com/41366522/125640765-db93fa69-b75f-46aa-b80b-0013696e3dfd.mov

_after:_

https://user-images.githubusercontent.com/41366522/125640833-27b9b5ae-69e7-4bc3-b3d8-11ae6251695b.mov

**Student-Exam**
_before: many issues, on 13'' the buttons never fit in one line_

https://user-images.githubusercontent.com/41366522/125641036-d1a4b886-15bd-40ec-9f56-936dcdf0488c.mov

_after:_

https://user-images.githubusercontent.com/41366522/125641069-ac140038-efa6-4537-9992-074f30de29c4.mov

### CODE REVIEW

**Review by katjanakosic — APPROVED** [review]
Looks as describes for both student exam view and exam detail view 👍

**Review by NicolasUllmann — APPROVED** [review]
Tested on 13'', everything was displayed correctly for me.

**Review by willergeorg — APPROVED** [review]
Tested on TS1. Alignment looks good to me.

**Comment by krusche** [comment]
great 👍

**Pull request merged**
