### PR TITLE
`General`: Fix icons on feature overview pages

### PR DESCRIPTION
**Pull request by filip-gregurevic**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

The icons on the feature overview pages were missed during migration to new icon usage and thus not displayed.

### Description

Changed icon usage to current practice.

### Steps for Testing

Prerequisites:
none

1. Navigate to /features/students
2. Make sure all icons are displayed correctly
3. Navigate to /features/instructors
4. Make sure all icons are displayed correctly

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [ ] Test 2

### Screenshots

Before:
Students:
Bildschirmfoto 2022-01-12 um 14 43 04
Instructors:
Bildschirmfoto 2022-01-12 um 14 43 13

After:
Students:
Bildschirmfoto 2022-01-12 um 14 43 21
Instructors:
Bildschirmfoto 2022-01-12 um 14 43 35

### CODE REVIEW

**Review by Malyuk-A — APPROVED** [review]
Tested on TS3. Worked just as described. Code changes LGTM. 👍

**Review by Strohgelaender — APPROVED** [review]
Tested on TS1, all icons are shown 👍

**Review by baranimo7 — APPROVED** [review]
tested on ts2, the icons are shown correctly

**Review by MertAksehirlioglu — APPROVED** [review]
Tested on TS2, works as expected.

**Pull request merged**
