### PR TITLE
[Bugfix] Maintain CommitState Consistency

### PR DESCRIPTION
**Pull request by anditurdiu**
### Checklist
- [x] I tested *all* changes and *all* related features with different users (student, tutor, instructor, admin) on the test server https://artemistest.ase.in.tum.de.
- [x] Client: I added multiple integration tests (Jest) related to the features (with a high test coverage)
- [x] Client: I documented the TypeScript code using JSDoc style.
- [x] Client: I added multiple screenshots/screencasts of my UI changes

### Motivation and Context
See issue #1854 
### Description
This was already started in #1924 but after major code editor refactoring I decided it was best to start fresh.
- When the editor state changes to `EditorState.UNSAVED_CHANGES`, the commit state also changes to `CommitState.UNCOMMITTED_CHANGES`.
- Because the commit state is now dependent on the unsaved changes, we also need to consider the possibility of the user changing a file while a commit is undertaken. In that case we must set the commit state to `CommitState.UNCOMMITTED_CHANGES`. This is done inside `ngOnChanges` because the editor state is updated in another component (`CodeEditorContainerComponent#unsavedFiles`) which maintains the unsaved file status. The alternative to utilizing `ngOnChanges` would be to use busy waiting which would reduce the performance. When we do a commit, if there are unsaved changes we first do a save and then the commit. If we do not wait for the 'save' to settle we run into race conditions which lead to inconsistent results. 

### Steps for Testing
1. Log in to Artemis
2. Start a programming exercise with the code editor enabled
3. Make some changes. 
    The commit state should become `CommitState.UNCOMMITTED_CHANGES`.
4. Press save. 
5. Press commit. 
    The commit state should become `CommitState.CLEAN`
6. Make more changes and press commit immediately. 
    The commit state should become `CommitState.CLEAN`
7. Make more changes and press commit. While it is committing, make more changes and observe the status. 
    It should become: `CommitState.UNCOMMITED_CHANGES`. Unless the auto-save kicked in, the editor state should also be  `EditorState.UNSAVED_CHANGES`.
8. Make more changes. and press commit. As soon as it is possible press refresh files. 
    The editor and commit state should be  `EditorState.CLEAN` and  `CommitState.CLEAN` respectively.

### Test Coverage
CodeEditorContainerComponent => 86%
CodeEditorActions => 78.5%
### Screenshots
image

### CODE REVIEW

**Review by MaisiKoleni — APPROVED** [review]
Looks good to me, and I was unable to break it on TS1.

**Review by sjagla27 — APPROVED** [review]
Looks good and worked as expected.

**Comment by anditurdiu** [comment]
I executed all tests locally with the -detectOpenHandles and all client test run locally. 
image

It is unclear to me why they fail on bamboo and github. I tried rebuilding them often but it does not change the result. This is happening randomly at any given heap size and test: 
image

**Review by kloessst — COMMENTED** [review]
Too late but works fine. Code looks good.

**Pull request merged**
