### PR TITLE
`Quiz exercises`: Fix synchronized mode due date validation

### LINKED ISSUE #5772: `Quiz exercises`: It is not possible to save a quiz exercise when I change the visible date
### Describe the bug

It is not possible to save a quiz exercise when I change the visible date to a date after the actual one. 

### To Reproduce

1. Go to Quiz exercises and create or import a quiz exercise and save it. 
2. Click on edit 
3. Scroll down to change the visible date to a different date than the actual date
4. check if the "save" button is deactivated (see the screen cast)
screencast

### Expected behavior

As long as the visible date is before the start date, the quiz should be able to be saved. 

### Screenshots

https://user-images.githubusercontent.com/88991954/197578028-ca269ce3-d96c-4b10-8df7-f9ca3aa85c6a.mov

### What browsers are you seeing the problem on?

Chrome

### Additional context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by rriyaldhi**
#### General

- [x] This is a small issue that I tested locally and was confirmed by another developer on a test server.
- [x] Language: I followed the [guidelines for inclusive, diversity-sensitive, and appreciative language](https://docs.artemis.ase.in.tum.de/dev/guidelines/language-guidelines/).
- [x] I chose a title conforming to the [naming conventions for pull requests](https://artemis-platform.readthedocs.io/en/latest/dev/guidelines/development-process.html#naming-conventions-for-github-pull-requests).
#### Client
- [x] I followed the [coding and design guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client/) and ensured that the layout is responsive.
- [x] I added multiple integration tests (Jest) related to the features (with a high test coverage), while following the [test guidelines](https://docs.artemis.ase.in.tum.de/dev/guidelines/client-tests/).
- [x] I added multiple screenshots/screencasts of my UI changes.

### Motivation and Context

Closes #5772

### Description

For a quiz whose mode is synchronized, the due date was set to start date + duration + grace period (5 seconds) on the server side as implemented [here](https://github.com/ls1intum/Artemis/blob/b27d53d4d7a543f4849d1e2b628d22430a53c690/src/main/java/de/tum/in/www1/artemis/service/QuizExerciseService.java#L168). When editing the quiz, the due date is never modified even though the start date is changed. Therefore, it is possible that the release date and start date are modified in such a way that: due date < release date < start date. This caused the quiz date to be invalid. To prevent the situation, the due date is set to be undefined (for synchronized mode), so that the quiz date is considered valid.

### Steps for Testing

Prerequisites:
- 1 Instructor
- 1 Course
- 1 Quiz Exercise whose mode is synchronized

1. Log in to Artemis
2. Navigate to Course Administration
3. Select the Course
4. Click Exercises
5. Edit the Quiz Exercise
6. Modify the Release Date to be after the old Start Date
7. Modify the Start Date to be after the old Start Date and before the new Release Date
8. Verify that the Quiz Exercise can be saved

#### Code Review
- [x] Review 1
- [x] Review 2
#### Manual Tests
- [x] Test 1
- [x] Test 2

### Test Coverage

| Class/File | Branch | Line |
|------------|-------:|-----:|
| quiz-exercise-detail.component.ts | 79.71% | 95.08% |

#### Before

https://user-images.githubusercontent.com/10885503/204447348-cba540f7-cefb-4364-9121-1e3a239a08fc.mov

#### After

https://user-images.githubusercontent.com/10885503/204447388-bbe0b4cf-9102-432c-8c5a-a62478cb2828.mov

### CODE REVIEW

**Review by evgeny1984 — CHANGES_REQUESTED** [review]
I got some issues with setting of Start Working Time after the quiz was generated.
Steps to reproduce:

- Create the quiz with the Schedule Quiz Start
- Save the Quiz and wait unitl it starts
- Reset the quiz and edit it
- Try to set the Start Working Time after the Visible From -> Not working and shows the error
image

**Comment by rriyaldhi** [comment]
> I got some issues with setting of Start Working Time after the quiz was generated. Steps to reproduce:
> 
> * Create the quiz with the Schedule Quiz Start
> * Save the Quiz and wait unitl it starts
> * Reset the quiz and edit it
> * Try to set the Start Working Time after the Visible From -> Not working and shows the error
>   image

Hi @evgeny1984, after resetting the quiz, the visible from date was changed to 1 year later as implemented [here](https://github.com/ls1intum/Artemis/blob/b27d53d4d7a543f4849d1e2b628d22430a53c690/src/main/java/de/tum/in/www1/artemis/service/QuizExerciseService.java#L416). In your screenshot, the visible from date is Nov 28 2023. That's why it is considered invalid.

**Review by JohannesStoehr — APPROVED** [review]
Bugfix looks good to me

**Review by simon-hng — APPROVED** [review]
Code changes look good

**Review by TheZoker — APPROVED** [review]
Tested on TS1 and worked for me 👍

**Review by sleiss — APPROVED** [review]
Code changes look fine to me

**Review by akesfeden — APPROVED** [review]
Code changes look good, tested on Ts1 during tested session, I could not find an issue.

**Review by minrows — APPROVED** [review]
Tested on ts1 during the testing session. LGTM 👍

**Pull request merged**
